### ISSUE TITLE
Random answer from list of possible replies for a given command

### ISSUE THREAD

**Issue by Ne0ratek** [alexylem/jarvis#1]
Salut,

D'abord bravo à toi jarvis est vraiment génial. mon idée d'amélioration et de lui faire dire quelque chose ou bien autre chose en alternant parfois exemple :
Question : "Quelle est la couleur du cheval blanc d'henry IV ?"
réponse 1 : "Blanc"
réponse 2 : "c'es blanc évidement"
...

Bonne continuation
Thomas

**Comment by alexylem** [comment]
Bonne idée, mais il faudrait que je revois la manière dont est structuré le fichier de commandes (et ca impacterait tout le monde). Je pensais aussi introduire le concept de modules: tout le monde pourrait contribuer et créer des commandes à partir des modules des autres. Ca serait l'occaz. Je vais y réfléchir.

**Comment by Ne0ratek** [comment]
Très bonne idée ton projet est vraiment intéressant j'avais comme idée de
faire quelque chose de similaire ou tout le monde ajouterais son grain de
sel et puis on ma montré que tu l'avais déjà fait, j'ai lu tes sources (en
bash ça fait vraiment peur tu as du courage) je comptais me faire quand
même ma propre IA en C avec de la reconnaissance faciale et vocal
(reconnaître la voix et le visage de quelqu'un en particulier) avec du
machine learning. Mais si tu as besoin d'un coup de main je serai ravi de
t'aider si j'y arrive.

**Comment by alexylem** [comment]
Salut et bien écoute ca tombe plutôt bien j'ai fini ma détection de visage et reco faciale (+ apprentissage s'il ne le connaissait pas déjà). C'est codé en python (bcp plus agréable que cette horreur de bash) et je compte l'intégrer à jarvis (que je vais réécrire en python).
J'accèpterais ton aide avec grand plaisir, je cherche justement des contributeurs pour le projet! tu connais python? (plus facile que le C car pas de compile et plein de librairies / grosse communauté)

**Comment by Ne0ratek** [comment]
Salut à toi,
Je connais le python, j'hésitais entre c'est 2 langages d'ailleurs. mais
ayant plus programmer en C je me disais que l'optimisation serai plus
facile.

**Comment by JulesMichael** [comment]
Hello ! je suit pas mal le projet et si vous voulez j'ai fait un chatbot en python ^^ ( avec un system d'apprentissage de réponses) car j'ai moi meme codé un agent personnel :D

**Comment by remjou1** [comment]
euh.. salut.. pour en revenir au sujet de l'issue... euh.. il suffirait pas de faire un petit script n bash avec une variable aléatoire et une réponse en fonction de la valeur de la variable ??

**Comment by remjou1** [comment]
ça ressemblerait a ça en gros : 
```
#!/bin/bash

min=1
max=2
number=$[($RANDOM % ($[$max - $min] + 1)) + $min]

if [ $number = 1 ]
then
	./jarvis.sh -s "bonjour"
fi

if [ $number = 2 ]
then
	./jarvis.sh -s "coucou"
fi
```

**Comment by alexylem** [comment]
Je ne m'inquiète pas trop pour la partie random. C'est plus la structure des commandes qui est à revoir. Je pensais à quelque-chose comme:
```
MERCI==say "de rien"
       say "tout le plaisir est pour moi"
       say "avec plaisir"
```
En voyant plusieurs alternatives, Jarvis en prendra une des 3 au hasard.

**Comment by remjou1** [comment]
mouais c'est déja plus compliqué mdr ^^

**Comment by alexylem** [comment]
Je ne sais pas si je l'implémenterai dans Jarvis car il est tout à faire possible de le faire dans un script:
```bash
#!/bin/bash

# Liste de réponses possibles
answers=("De rien" "Avec plaisir" "Tout le plaisir est pour moi" "A ton service")

# Sélection d'une réponse aléatoirement
answer=${answers[$RANDOM % ${#answers[@]} ]}

# Exécution de la réponse
~/jarvis/jarvis.sh -s "$answer"
```

**Comment by remjou1** [comment]
ouais du coup c'est ce que je pensais... mais peu etre mettr des script pardéfaut dans jarvis modfiable par l'utilisateur ensuite on ajoute une commande 
'''
*MERCI*==say "`./de_rien.sh`"
'''
et un autre 
'''
*MERCI*== say "de rien"
'''
et la première phrase serait a décommanter si on veut utiliser le script... Ce serait utilis pour ce qui touche pas trop a la programmation...

**Comment by Ne0ratek** [comment]
Ce que je trouverai plus logique et de modifier le fichier de configuration
et inscrire plusieurs réponse pour la même question

**Comment by alexylem** [comment]
Comme ca?
```
MERCI==say "de rien"
       say "tout le plaisir est pour moi"
       say "avec plaisir"
```
C'était l'idée d'origine mais ca fait bcp de travail/modifs pour quelque-chose qu'on peut déjà aujourd'hui faire facilement avec un script externe...
Si vous le souhaitez vraiment je le ferai, mais je pensais d'abord permettre les discussions imbriquées comme ceci:
```
CA VA==say "et et toi?"
    *OUI*==say "ravi de l'entendre"
    *NON*==say "j'en suis navré"
```
Ce qui peut être drôlement utile pour les demandes complexes
```
AJOUTE A LA LISTE DE COURSE*==say "que dois-je ajouter à la liste de courses?"
    (*)==./add_to_list "(1)" && say "Ok"
```

**Comment by Ne0ratek** [comment]
C'est vraiment une bonne idée comme ça

**Comment by remjou1** [comment]
c'est exactement ce que je pensais faire pour des envoi de mail ou de sms genre : 
ENVOIE UN SMS*==say "que dois--je envoyer ?"
    (*)==./envoie_sms "(1)" && say "Ok"

**Comment by alexylem** [comment]
L'évolution des commandes imbriquées sera implémentée ici: #42 
On garde ce ticket pour les réponses aléatoires.

**Comment by alexylem** [comment]
Qui est toujours intéressé par cette fonctionalité? (depuis l'implémentation de #42 je me demande si c'est toujours utile).
@JulesMichael toujours volontaire pour aider? Si oui tu peux me contacter par email, je cherche toujours des contributeurs avec compétences bash/python/web (pour le store).

**Comment by alexylem** [comment]
Si personne n'y voit un intérêt particulier, je ferme le ticket.
De plus, il est déjà possible de faire des réponses aléatoires, ex:
```shell
*MERCI*==answers=("De rien" "Avec plaisir" "Tout le plaisir est pour moi" "A ton service"); say "${answers[$RANDOM % ${#answers[@]} ]}"
```
