### ISSUE TITLE
durée d'attente

### ISSUE THREAD

**Issue by remjou1** [alexylem/jarvis#10]
j'ai eu une idée quand, avec mon bouton, j'ai lancé une commande : en fait j'ai raté ma commande et j'ai du attendre 10sec avant de la re-éssayé... ne serait-il pas possible d'ajouter un menu ou je ne sais quoi qui nous demande quelle durée d'attente nous voulons ?

**Comment by alexylem** [comment]
SI tu rates ta commande il devrait dire:
```
Je n'ai pas compris: <ce que tu as dit>
```
Si tu as le mode conversation activé (Settings > General), tu peux dire à nouveau une nouvelle commande. Sinon il te faut redire le mot clé `JARVIS`. A aucun moment tu n'es censé attendre 10 secondes...

**Comment by remjou1** [comment]
non en fait je pense qu'il n'avait pas bien entendu ce que j'ai dis et que si j'avais été en "écran" il m'aurait mis un # et donc comme je peu pas le voir et que ensuite je sais pas si c bon ou pas bah je suis obligé d'attendre 10sec

**Comment by alexylem** [comment]
Si jarvis ne "dit" rien c'est qu'il n'a pas entendu la commande ou qu'il n'est pas en mode conversation.
Avant il y avait des "bips" pour indiquer le début d'une écoute, ... mais au final je les ai enlevé car ca a fini par nous casser le tête (bip toutes les 5 à 10 secondes toute la journée...)
Pour répondre à ta première question, tu n'as pas besoin d'attendre 10 secondes. Tu peux le vérifier en lancant jarvis depuis le terminal et voir ce qu'il se passe dans l'affichage.
