### ISSUE TITLE
snowboy initiate

### ISSUE THREAD

**Issue by xsertunc** [alexylem/jarvis#100]
When i started jarvis it gave an error 
jarvis.sh: line 679 snowboy: command not found

i entered jarvis config folder opened triger_stt file
i deleted new line and space after snowboy

and voila, it works now

**Comment by xsertunc** [comment]
also google recognition didnt work 
deleted new line and space after api key config file 
now it works

could you please check and remove empty space and new line after config files,
it causes instability

**Comment by alexylem** [comment]
Thanks for your findings & investigations.
Those file are generated locally with:
```shell
# for each config variable including $trigger_stt and $google_speech_api_key
echo "${!varname}" > config/$varname
```
So there shouldn't be any space or new line within those files.
@xsertunc  could you confirm you haven't opened them in an editor like Atom which could have altered them?

To verify it does normally work, you can simply:

1. Start Jarvis
2. Go in Settings / Voice reco / Reco of magic word
3. Re-select `snowboy` (for example)
4. Go back to main menu (important to get config saved) and quit
5. Check config file content with `cat config/trigger_tts`

Alex.

**Comment by xsertunc** [comment]
i have a problem with my vga to hdmi converter now,
as soon as i fix it, i will test and report to you

for now i can tell, after i set up it didnt work at first but after i deleted the space it worked,
so i think something altered it before i opened them

**Comment by alexylem** [comment]
Ok please keep me informed as you are the only one who reported this, so that I close the ticket.

**Comment by xsertunc** [comment]
after chown pi:pi ~/jarvis
problem solved.
no logic in that but using with sudo may have made this
you can close the ticket, thank you.
also please add a check for sudo jarvis, and don't let it
