### ISSUE TITLE
probleme jarvis compréension vocale

### ISSUE THREAD

**Issue by zulu14** [alexylem/jarvis#102]
### Description

mon probleme et que il ne comprend pas ce que je dis jarvis ne marche que en mode clavier
jai la clef google estok et jai voulut metre poketsphinx a la place de snowboy comme snowboy ne marche pas et pocketsphing se dowload mais il met une éreur au moment de le config.
ps: mon tigger et toujour sur snowboy (jarvis se nome snowboy 

### Résultat
```
je n'ai pas pu vous donné la cosole l'ereur nsri et celle que le message dure plus de 4sec et donc elle est ignoré
```

merci de me répondre :)   question je pourai avoir ton dossier jarvis pour pouvoir voir si sela fonctione 
ou une partie merci si tu veut bien tu me sauve mon jarvis et merci pour ce programe !!!!!

**Comment by alexylem** [comment]
Bienvenue à toi cher utilisateur de Jarvis 😄 
Pour t'aider je vais avoir besoin que tu colles le contenu de la console avec Jarvis lancé en mode troubleshooting. Je te conseille d'utiliser Snowboy (avec jarvis nommé snowboy) pour la reconnaissance du mot magique et bing ou google pour la reconnaissance des commandes.
Colle moi la totalité de la console depuis le lancement jusqu'à l'erreur rencontrée avec snowboy.
Pour la commande qui dure plus de 4 secondes, essaye de réduire les bruits de fond et de baisser la sensibilité de ton micro.
Merci,
Alex.

**Comment by alexylem** [comment]
@zulu14 as-tu toujours le problème?

**Comment by alexylem** [comment]
timeout
