### ISSUE TITLE
voice recognition sound level

### ISSUE THREAD

**Issue by xsertunc** [alexylem/jarvis#104]
i use snowboy for passive recognition, google/wit.ai for active.

snowboy hears me and answers from other room
but for google/wit.ai i have to get very close to the mic.
(i use logitech c270 usb webcam)

do you have any sugestions ?

thanks in advance

**Comment by francoismartin** [comment]
Maybe your microphone is not very good.
Other personn of this community advice to use this [Sound Tech CM-1000USB](https://www.amazon.com/dp/B008BS3CF8/ref=cm_sw_su_dp)

You have the list here (sorry is in french) : [Pré-requis](https://github.com/alexylem/jarvis/wiki/prerequisites)
