### ISSUE TITLE
lecture d'une page web

### ISSUE THREAD

**Issue by remjou1** [alexylem/jarvis#11]
voila : puisque que j'utilise pas jarvis en mode "écran", j'aimerais que jarvis me lise une page internet (pas des truc compliqué genre jarvis n'aura que quelque fonctions comme définition "..." et jarvis fera la recherche et lira la def... ce genre de trucs), moi en mode "écran" (parceque j'ai 2 raspi) je fais cette commende : 
*RECHERCHER(*)==say "ok" && firefox (1)
et ça me fait la recherche de la page... mais ça n'est pas vraiment ça que je veux.... ce serait juste une définitions ou un résumé d'une petite recherche...

est-ce possible ?
merci

**Comment by alexylem** [comment]
Oui je pense qu'on peut déjà le faire, il suffit de faire un script qui prend en paramètre une URL, parse la page et renvoie le contenu à "parler":
```
DEFINITION DE (*)==say "`parse_online_dic http://onlin_dic/(1)`"
```
La création des commandes / scripts n'est pas dans le scope du projet. Elles doivent être faites par l'utilisateur avec l'aide de Google si nécessaire.

**Comment by remjou1** [comment]
ouais j'avais déjà lu un truc du genre sauf que je comprend pas bien le fonctionnement pour parser une page web et je me demandais si il était possible que tu créé une commande pour simplifier le tout... dis... c'est ce système que tu as utilisé pour donner la météo ?

**Comment by alexylem** [comment]
Oui. Mais encore une fois je préfère concentrer mes efforts sur le moteur de Jarvis et pas sur les commandes. Renseigne-toi sur Google tu trouveras plein d'exemples.
