### ISSUE TITLE
Documentation sur jumelage enceintes et micro bluetooth

### ISSUE THREAD

**Issue by NYGHOST** [alexylem/jarvis#110]
Bonjour à tous,
j'avais dans l'idée de jumeler des enceintes et micro en Bluetooth
Probleme, impossible de connecter les enceintes et micro.
j'utilise bluez et pulseaudio-module-bt.
si ca gene tu peux retirer ce post Alexy

**Comment by devauxa** [comment]
Bonjour à toi NYGHOST
Désolé, j'ai complètement oublié d'écrire la procédure...
Mais il est bien possible d'utilisé une enceinte bluetooth (j'ai un micro filaire, donc pas testé de micro en bluetooth)
Dès que j'ai un peu de temps, je retrouverais le tuto et les quelques fix.

**Comment by francoismartin** [comment]
Question, comment tu gère @devauxa pour la mise en veille des enceintes bluetooth quand tu ne l'utilises plus ?

**Comment by devauxa** [comment]
@francoismartin un script qui envoi un son inaudible toute les 5 minutes 😅
Un cron devrait suffire en principe

**Comment by alexylem** [comment]
Petit up sur ce ticket qui je pense pourrait en intéresser plus d'un, il y a un moyen d'avoir un début de tuto?

**Comment by devauxa** [comment]
Je ne retrouve plus le tuto que j'ai suivis... mais dans mes packages installé j'ai : alsa-base alsa-utils gstreamer0.10-alsa libsox-fmt-alsa pavucontrol pulseaudio pulseaudio-module-bluetooth pulseaudio-module-x11 pulseaudio-utils pi-bluetooth bluez blueman bluez-firmware

Tous ce fait à la souris, et c'est ça que j'aime pas... 
> Clic sur le Menu bluetooth
> Active le bluetooth
> Pair avec l’enceinte,
>> Si ça marche pas, Clic sur le Menu Audio
>> Sélectionné l'enceinte bluetooth et c'est bon.

ensuite le script tous bête pour gardé l'enceinte ON : 
`while :
do
    aplay /etc/script/empty.wav;
    sleep 250;
done`
Avec le son :  [http://home.epiteck.eu/empty.wav](url)

Par contre, si je l'ai pas de carte usb audio par défaut, ça fonctionne pas (même si je m'en sert pas pour l'output, mais juste pour l'input)

Désolé si c'est pas très claire où si il manque des bouts, quand je recevrais une autre carte SD, je ferais une installation au propre (full bash, sans cette fichue souris !)

**Comment by francoismartin** [comment]
Des nouvelles sur l'utilisation d'une enceinte en bluetooth pour le stream ? Pensez-vous que c'est possible de le faire nativement en CLI même après un reboot comme la configuration similaire https://github.com/alexylem/jarvis/issues/80#issuecomment-243832815 `hw` du micro et des enceintes dans alsa ?

Merci

**Comment by NYGHOST** [comment]
Jai une astuce au cas ou

Cordialement
PAIN Fabrice

Le 19 oct. 2016 ? 16:50, francoismartin <notifications@github.com<mailto:notifications@github.com>> a ?crit :


Des nouvelles sur l'utilisation d'une enceinte en bluetooth pour le stream ? Pensez-vous que c'est possible de le faire nativement en CLI m?me apr?s un reboot comme la configuration similaire #80 (comment)<https://github.com/alexylem/jarvis/issues/80#issuecomment-243832815> hw du micro et des enceintes dans alsa ?

Merci

-

**Comment by francoismartin** [comment]
@NYGHOST curieux d'avoir ton astuce Fabrice :)

**Comment by NYGHOST** [comment]
Jai eu de gros souci connection bluetoth rasp du coup je passe par une cable usb avec prise jack micro et casque et 2 recepteur bluetooth-jack pulseaudio reconnais le usb-jack comme etant mon casque-micro logitech et hop marche nikel

Cordialement
PAIN Fabrice

Le 19 oct. 2016 ? 19:23, francoismartin <notifications@github.com<mailto:notifications@github.com>> a ?crit :


@NYGHOST<https://github.com/NYGHOST> curieux d'avoir ton astuce Fabrice :)

-

**Comment by NYGHOST** [comment]
Photo [image1.JPG]

Cordialement
PAIN Fabrice

Le 19 oct. 2016 ? 19:23, francoismartin <notifications@github.com<mailto:notifications@github.com>> a ?crit :


@NYGHOST<https://github.com/NYGHOST> curieux d'avoir ton astuce Fabrice :)

-

**Comment by alexylem** [comment]
@NYGHOST La photo n'est pas passée tu peux la rajouter directement sur GitHub?

**Comment by NYGHOST** [comment]
Lien https://www.amazon.com/Logitech-3-5mm-Audio-Adapter-version/dp/B00FH1KTFI

Cordialement
PAIN Fabrice

Le 19 oct. 2016 ? 19:43, Alexandre M?ly <notifications@github.com<mailto:notifications@github.com>> a ?crit :


@NYGHOST<https://github.com/NYGHOST> La photo n'est pas pass?e tu peux la rajouter directement sur GitHub?

-

**Comment by alexylem** [comment]
Ca n'a rien à voir avec le bluetooth... c'est juste USB => Jack :smile:

**Comment by NYGHOST** [comment]
Relis au dessus mon astuce et tu comprendras. Avec un module ?metteur recepteur bluetooth tu peux obtenir un pont. Ce pont est ensuite reli? au jack tu as alors une jontion usb jack emetteur recpteur.
Cet astuce ma permis de relier un micro blietooth et une enceinte jbl clip2

Cordialement
PAIN Fabrice

Le 20 oct. 2016 ? 08:35, Alexandre M?ly <notifications@github.com<mailto:notifications@github.com>> a ?crit :


Ca n'a rien ? voir avec le bluetooth... c'est juste USB => Jack ?

-

**Comment by alexylem** [comment]
Ok je comprends mieux. Tu peux partager ton modèle d'émetteur / récepteur bluetooth?
Une petite photo? (rajoute sur le trhead GitHub directement stp)
Merci!

**Comment by NYGHOST** [comment]
Je joindrais aussi des sites pour ceux qui voudrais utiliser le bluetooth de leur rasp. Bcps utilises bluez en version 4

Cordialement
PAIN Fabrice

Le 20 oct. 2016 ? 08:56, Alexandre M?ly <notifications@github.com<mailto:notifications@github.com>> a ?crit :


Ok je comprends mieux. Tu peux partager ton mod?le d'?metteur / r?cepteur bluetooth?
Une petite photo? (rajoute sur le trhead GitHub directement stp)
Merci!

-

**Comment by francoismartin** [comment]
j'ai réussi a me connecter avec le Rpi3 sans dongle via ces 2 liens :

https://kofler.info/bluetooth-konfiguration-im-terminal-mit-bluetoothctl/ <= écrit en allemand mais les exemples sont assez compréhensible 
http://unix.stackexchange.com/questions/258074/error-when-trying-to-connect-to-bluetooth-speaker-org-bluez-error-failed <= ça a résolut mon problème avec le connect qui me disais une erreur.

Et j'ai ce lien mais ça n'a pas l'air de vraiment fonctionner http://ghostwriter.wikia.com/wiki/Install_Bluetooth_speakers_on_Raspberry_Pi pour la config d'Alsa.

Prochaine étape réussir a streamer le son de jarvis sur mon enceinte bluetooth.

**Comment by alexylem** [comment]
Merci Francois, lorsque tu auras réussi ca serait bien d'écrire un petit tuto je le publierai sur le site, voir l'intégrerai dans le code à l'installation.

**Comment by Thegritche** [comment]
Bonjour à tous
J'ai rédigé un mémo concernant le bluetooth sur raspberry 
ici [http://easydomoticz.com/bluetooth-squeezelite-raspberry-domoticz-2/](url)

Si ça peut aider !

**Comment by alexylem** [comment]
Merci @Thegritche pour ce tuto très clair. Pour Jarvis il faudra juste voir côté `.asoundrc` car il génère le sein, mais en bricolant un peu (merge des 2 contenus dans le même fichier) ca devrait le faire!

**Comment by brakc** [comment]
Bonjour à tous,

Je viens de lire ce post, mais je n'ai pas trouvé de tuto clair pour lancer "pulseaudio --start" et réapairer mon device bluetooth au démarrage de mon Raspberry 3.

J'ai trouvé ce post mais il m'a l'ai un peu compliqué: https://github.com/davidedg/NAS-mod-config/blob/master/bt-sound/bt-sound-Bluez5_PulseAudio5.txt

J'avoue ne pas trop être à l'aise avec le bluetooth et je n'aime pas faire des choses que je ne comprends pas ...

Avez-vous un expérience pour automatiser la configuration au démarrage svp?

**Comment by francoismartin** [comment]
@Thegritche merci pour ton lien.

Mais moi personnelement, je n'ai pas de fichier `sudo nano /etc/bluetooth/audio.conf` j'ai :

```
sudo nano /etc/bluetooth/
input.conf      main.conf       network.conf    proximity.conf
```

**Comment by Thegritche** [comment]
si tu n'as pas de audio.conf tu peux toujours le creer à la main : touch audio.conf

**Comment by francoismartin** [comment]
Bon c'est impossible d'avoir alsa qui fonctionne avec bluez5.

@Thegritche tu es encore sous Wheezie avec Bluez4 ?

@alexylem Impossible de faire fonctionner jarvis avec pulseaudio et non alsa ?

Merci

**Comment by alexylem** [comment]
@francoismartin j'ai développé Jarvis avec Alsa mais ca doit être possible aussi avec pulseaudio il faudra revoir toute la partie audio. Tu peux créer un ticket je regarderai.

**Comment by NYGHOST** [comment]
@alexylem apres test j'aurai un micro BT de la marque NOLAN a ajouté au micro compatible et JBL clip2

**Comment by alexylem** [comment]
@NYGHOST ok tiens moi au courant merci :)

**Comment by francoismartin** [comment]
@NYGHOST Donc ton astuce de pont si j'ai bien compris, tu utilise un récepteur bluetooth, lequel ? Tout modèle confondue fonctionnerait ?

Merci

**Comment by francoismartin** [comment]
Coucou les amis,

On m'a aidé et on m'a indiqué ça : https://github.com/Arkq/bluez-alsa

@Arkq a fait en sorte qu'Alsa fonctionne avec Bluez5 du coup ça résout énormément de problème et j'arrive a streamer le son sur mon enceinte bluetooth en passant par une configuration Alsa.

Youhou ;)

**Comment by NYGHOST** [comment]
Je pense le plus simple reste un raccord usb 2xjack


Le 26 oct. 2016 ? 13:35, francoismartin <notifications@github.com<mailto:notifications@github.com>> a ?crit :


Bon c'est impossible d'avoir alsa qui fonctionne avec bluez5.

@Thegritche<https://github.com/Thegritche> tu es encore sous Wheezie avec Bluez4 ?

@alexylem<https://github.com/alexylem> Impossible de faire fonctionner jarvis avec pulseaudio et non alsa ?

Merci

-

**Comment by NYGHOST** [comment]
Marche nikel et les micro serait du coup tous compatible (jack) je suis avec une jbl 2 et un nolan micro BT.
J'ai testé un émetteur-recepteur BT pas mal qui possède une bonne autonomie (13h) et pour l'instant aucun pb.
Le convertisseur jack usb est un logitech

Cordialement
PAIN Fabrice

Le 28 oct. 2016 à 13:26, francoismartin <notifications@github.com<mailto:notifications@github.com>> a écrit :


Coucou les amis,

On m'a aidé et on m'a indiqué ça : https://github.com/Arkq/bluez-alsa

@Arkq<https://github.com/Arkq> a fait en sorte qu'Alsa fonctionne avec Bluez5 du coup ça résout énormément de problème et j'arrive a streamer le son sur mon enceinte bluetooth en passant par une configuration Alsa.

Youhou ;)

**Comment by NYGHOST** [comment]
La config est basé sur un conv logitech jack usb, et deux emetteur recpteur bluetooth. Pas de de souci de reveil de l'enceinte et le tout tiens 8h sans coupure. J'ai une photo du montage pour ceux qui veulent.

**Comment by NYGHOST** [comment]
émetteur récepteur : 
https://www.amazon.fr/dp/B01FU5QKZS/ref=pe_386181_40444391_TE_item

**Comment by francoismartin** [comment]
@alexylem j'ai réussi a configurer alsa pour que l'enceinte passe, bon j'ai un crop de la première seconde pour applause.wav

Quand je test dans Audio setting, j'entend bien (la fin) des applaudissement et le micro fonctionne (même si c'est écrit `false` pour les deux)

![console jarvis](https://sc-cdn.scaleengine.net/i/897270d20d4d4a9e3071663221ac4381.png)

Voici ma config alsa (mais ça ne passe pas en dmix)

```
# Adapté via http://stackoverflow.com/a/14398926/6268583
#
# Enceinte
pcm.btspeaker {
 type plug
  slave {
    pcm {
      type bluealsa
      interface hci0
      device 00:0C:8A:6B:8E:BD
      profile "a2dp"
    }
  }
#  hint {
#    show on
#    description "BT Headset"
#  }
}
# Micro
pcm.dsnooped {
    type dsnoop
    ipc_key 1025
    # A adapter en fonction de la config de reconnaissance
    # par Pi, il se peut que l'ordre ne soit pas le même
    slave.pcm "hw:1,0"
}

pcm.duplex {
    type asym
    playback.pcm "btspeaker"
    capture.pcm "dsnooped"
}

# Instruct ALSA to use pcm.duplex as the default device
pcm.!default {
    type plug
    slave.pcm "duplex"
}

# tell ALSA to use hw:0 to control the default device (alsamixer and so on)
ctl.!default {
    type hw
    # A adapter en fonction de la config de reconnaissance
    # par Pi, il se peut que l'ordre ne soit pas le même
    card 0
}
```

mais quand je lance jarvis

```
./jarvis/jarvis.sh 
Checking for updates...[Up-to-date]
Jarvis: Bonjour
../../../src/asound/bluealsa-pcm.c:101: Getting transport for 00:0C:8A:6B:8E:BD profile 1
../../../src/asound/bluealsa-pcm.c:502: Setting constraints
../../../src/asound/bluealsa-pcm.c:327: Closing plugin
../../../src/asound/bluealsa-pcm.c:101: Getting transport for 00:0C:8A:6B:8E:BD profile 1
../../../src/asound/bluealsa-pcm.c:502: Setting constraints
../../../src/asound/bluealsa-pcm.c:327: Closing plugin
../../../src/asound/bluealsa-pcm.c:101: Getting transport for 00:0C:8A:6B:8E:BD profile 1
../../../src/asound/bluealsa-pcm.c:502: Setting constraints

[alsa.c:118] error: initialize_device(): cannot set hw params

[audio.c:643] error: failed to open audio device

[mpg123.c:547] error: failed to reset audio device: Success
ANNULE*|TERMINE*	*MERCI*			*AIDE*
*COMMENT*APPELLE*	*BONJOUR*|*SALUT*	*AU REVOIR*|*BYE*
*TEST*			*VERSION*		*REPETE (*) ET (*)
*SENS*VIE*		*METEO*
Jarvis: Waiting to hear 'Jarvis'
Benjamin: ../../../src/asound/bluealsa-pcm.c:101: Getting transport for 00:0C:8A:6B:8E:BD profile 1
../../../src/asound/bluealsa-pcm.c:502: Setting constraints
play FAIL formats: can't open output file `default': snd_pcm_hw_params error: Invalid argument
ERROR: play command failed
HELP: Verify your speaker in Settings > Audio > Speaker
Jarvis
Jarvis: Oui ?
../../../src/asound/bluealsa-pcm.c:101: Getting transport for 00:0C:8A:6B:8E:BD profile 1
../../../src/asound/bluealsa-pcm.c:502: Setting constraints
../../../src/asound/bluealsa-pcm.c:327: Closing plugin
../../../src/asound/bluealsa-pcm.c:101: Getting transport for 00:0C:8A:6B:8E:BD profile 1
../../../src/asound/bluealsa-pcm.c:502: Setting constraints
../../../src/asound/bluealsa-pcm.c:327: Closing plugin
../../../src/asound/bluealsa-pcm.c:101: Getting transport for 00:0C:8A:6B:8E:BD profile 1
../../../src/asound/bluealsa-pcm.c:502: Setting constraints

[alsa.c:118] error: initialize_device(): cannot set hw params

[audio.c:643] error: failed to open audio device

[mpg123.c:547] error: failed to reset audio device: Success
Benjamin: ../../../src/asound/bluealsa-pcm.c:101: Getting transport for 00:0C:8A:6B:8E:BD profile 1
../../../src/asound/bluealsa-pcm.c:502: Setting constraints
play FAIL formats: can't open output file `default': snd_pcm_hw_params error: Invalid argument
ERROR: play command failed
HELP: Verify your speaker in Settings > Audio > Speaker
```

As-tu une idée de comment je peux résoudre le problème ?
Merci

nb : @NYGHOST merci pour tes informations.

**Comment by alexylem** [comment]
@francoismartin je vais avoir du mal à t'aider la... mais je vais quand même essayer. D'après ce que je dois tu as des erreurs avec `PLAY` mais le micro marche.
Dis moi si les commandes suivantes fonctionnent:
```shell
$> cd jarvis/sounds/
$> aplay applause.wav
$> play applause.wav
```

**Comment by Sopalin06** [comment]
Hello, Je relance ce sujet car je suis dans le même soucis. J'utilisais Jarvis avec une enceinte en prise jack, jusque là tout fonctionnait bien. Cependant j'ai voulu configurer une enceinte bluetooth pour stream de la musique via un player en pensant séparer jarvis de la musique mais avec les drivers bluetooth/Also/Pulseaudio j'ai plus rien qui marche. Jarvis a bien la carte son local pourtant aucun son ne sort de l'enceinte

**Comment by Sopalin06** [comment]
Je me répond tout seul, il suffit d'ajouter le paquet pulseaudio-module-jack pour pouvoir utiliser le jack du RPI.

A+

**Comment by wikijm** [comment]
@Sopalin06 Merci pour ton retour et ta solution 👍

**Comment by schnibel** [comment]
Bonjour à tous, 
Je suis sur le point d'acheter une enceinte + micro bluetooth [Jabra 510](https://www.amazon.fr/Jabra-Speak-510-Haut-parleur-Bluetooth/dp/B00ANI7HI2/ref=sr_1_4?ie=UTF8&qid=1490112495&sr=8-4&keywords=jabra+bluetooth). 
J'ai vu que le Jabra 410 avait été testé et qu'il était capable de détection lointaine. Je me suis naïvement dit que le 510 pourrait lui aussi être compatible et de qualité, si on met la problématique Bluetooth de côté.  

Cela offrirait le gros avantage de ne pas avoir de fil, et donc de pouvoir transporter l'enceinte où je veux dès lors que je reste dans le bon périmètre... En plus, elle n'est pas si chère que ça par rapport à des micros sur USB (la qualité est-elle tout de même là ?)

Avant de l'acheter, pourriez-vous me dire si le package Jabra 510 + Raspberry 3 + Jessie pourrait être compatible et de bonne qualité. 

Je me pose des questions d'une part en relisant vos échanges vos échanges d'il y a quelques mois sur le Bluetooth et Jarvis, mais il me semble qu'il n'y a pas de problèmes. 
Par ailleurs, je ne dois pas oublier ma contrainte majeure sur le projet : la WAF... et j'aurais aimé savoir si vous auriez des retours sur la capacité du Jabra à reconnaitre les commandes vocales et bien interpréter ce qui est dit ? savoir aussi si la détection lointaine fonctionne vraiment bien (je ne me vois pas me coller au micro pour commander Jarvis). 

J'ai fait plusieurs tests avec Jarvis et avec des micros de très mauvaises qualité (ex : webcam, ou micro prise jack)... Résultat, le comportement de Jarvis est hyper aléatoire, et il reconnaît très rarement son mot clé... j'ai mis ça sur le dos des micros, là, je suis prêt à casser ma tirelire

Merci d'avance pour vos retours.

**Comment by wikijm** [comment]
@schnibel Tu peux acheter un 510 (ou 410) les yeux fermés, comme plusieurs d'entres nous. 

Pour la connexion Bluetooth, je ne saurais pas te dire je ne l'utilise pas avec Jarvis.

**Comment by Sopalin06** [comment]
Je viens justement de déployer une enceinte bluetooth dans ma salle de bain
pour envoyer de la musique depuis le RPI 3 et un Logitech Media serveur.
Pour t'éviter des nuits à chercher, je t'invite à acheter un dongle
bluetooth, car le BT onboard du RPI crash après une longue utilisation.
Pour l'encinte je suis partis sur une JBL GO à 20€ qui fait très bien le
boulot.

Cependant j'ai pour l'instant mis jarvis en veille à cause d'une
reconnaissance trop faible ce qui rend le système non viable ;( Il faut
investir dans des micros de très bonne qualité pour avoir un système viable
de mon point vue.

**Comment by alexylem** [comment]
>Il faut investir dans des micros de très bonne qualité pour avoir un système viable
de mon point vue.

Je confirme il n'y a pas de secret. JABRA, micro array ou sinon le PS Eye qui est aussi un array pas cher (10 euros) mais qui ne marche pas trop de loin.

**Comment by schnibel** [comment]
Merci à tous pour vos réponses. Commande effectuée :)
et je vais suivre ton conseil @Sopalin06, et commander un dongle bluetooth... 
J'ai hâte de le recevoir maintenant :)

**Comment by schnibel** [comment]
Hello, 
Je viens de recevoir mon Jabra 510... Joli. 
Mais pour le moment ça commence mal, je l'ai branché en USB, j'ai installé les packages conformément au tuto, j'entends bien les applaudissements, mais lors de la phase de test micro, je dis quelque chose et c'est restitué en hyper rapide (comme si j'avais mis un disque vinyl sur 78 tours pour un 33 tours)
Des idées ?

**Comment by wikijm** [comment]
@schnibel Désolé, ça tombe sur toi mais :
**Le sujet a été mainte fois abordé, merci de faire une recherche dans les docs ou les issues en cours/clôturées.**

Une simple recherche donne les résultats suivants :
 - https://github.com/alexylem/jarvis/issues/489
 - https://github.com/alexylem/jarvis/issues/330
 - https://github.com/alexylem/jarvis/issues/319
 - https://github.com/alexylem/jarvis/issues/245

En plus de cela tu parles d'un problème sur un JABRA 510 que tu connecte en USB alors que l'on est sur ue issue parlant du jumelage bluetooth.

**Comment by schnibel** [comment]
Complètement désolé... tu as 200% raison
Merci pour le message, je ferai mieux. 
Encore désolé.

**Comment by wikijm** [comment]
J'avais peur que tu le prennes mal, mais apparemment on arrive à échanger en bonne intelligence :thumbsup:.
Promis, je continuerais d'aider et de répondre en toute circonstance  :wink:.

**Comment by scsifox12** [comment]
Bonjour,
J'ai Jeedom sur un NUC (HYSTOU) dans mon sous-sol. Cela fait longtemps que je rêve d'un JARVIS à la maison. Je pense que n'ai pas le choix : Bluetooth (ou wifi) pour l'avoir dans mon salon. J'ai lu beaucoup de chose et au moment de penser à investir dans un micro et des émetteurs/transmetteurs arrive "GOOGLE HOME" pour guère plus cher que l’équipement cité ci-dessus. Il y a déjà des tutos pour l'utiliser avec Jeedom. Ce qui me gène c'est le cloud de google... Alors je me suis dit, n'y aurait-il pas moyen d'utiliser les micros et enceintes du google home avec jarvis tout en bloquant l'acces au cloud de google, genre bloquer l'ip dans routeur par exemple?
Alors, bonne idée ou pas et surtout, est ce faisable?
Merci
Ps : j’espère que je n'ai pas pollué la discussion...

**Comment by Oliv4945** [comment]
@scsifox12 : Je ne pense pas que ce soit possible, les appels aux serveurs de Google sont chiffrés, enfin j'espère... La meilleure solution est d'attendre que quelqu'un trouve un accès root.
Si tu a déjà tu matériel bluetooth tu peux regarder [ce message](https://github.com/alexylem/jarvis/issues/200#issuecomment-313909560).
Sinon au choix, tout faire sur un rPi ou utiliser un rPi Zero pour micro/hp et déporter le serveur sur ton NUC

**Comment by scsifox12** [comment]
Merci pour la réponse, je sur que les appels aux serveur de Google sont chiffrés, mais je pensais seulement à intégrer le "hardware" sous Jeedom (avec les apis de Google peut être?...) comme l'aspi xiaomi par exemple.

**Comment by Oliv4945** [comment]
@scsifox12 Est-ce qu'il y a une API pour utiliser le hardware ? Si c''est le cas je regarderais avec plaisir.
Mais ça m'étonne de Google du coup les deux solutions que je vois sont
* installer un soft perso dessus, pas encore possible mais ça ne m'étonnerai pas que des gens travaillent déjà dessus
* "hacker" les appels aux serveurs Google mais comme on a évoqué ils doivent être chiffrés

Si tu as de la doc n'hésites pas à la faire passer, je n'ai pas creusé le sujet mais c'est intéressant

**Comment by wikijm** [comment]
Bonsoir @scsifox12,

Je t'invite à créer une nouvelle issue (et supprimer ton message une fois fait) pour ta requête, car cette dernière est hors sujet par rapport à celui actuel.

**Comment by scsifox12** [comment]
Bonjour,
J'ai pris bonne note, et je regarde pour supprimer le msg et créer une nouvelle issue.
Merci

**Comment by Oniric75** [comment]
bonjour à tous,

est ce que quelqu'un a reussi faire marcher le bluetooth de façon stable ou toujours pas ? 

l'idée du pont : "Rpi > usb to bluetooth > bluetooth to usb > jabra" me plait bien comme alternative, mais le device testé par  @NYGHOST ne semble plus exister. et vu l'investissement pour un jabra 410, j'aimerai être sur.
Est ce que Rpi > usb to bluetooth > jabra 510 fonctionnerai sinon ? quelqu'un a testé ? N'ayant que très peu confiance dans le bluetooth des Rpi cette solution me parait pas mal, mais uniquement sur le papier, n'ayant pas investi encore.

merci la communauté :-)

**Comment by JeanBajb** [comment]
Bonjour

Depuis que j'ai installé Jarvis mes enceintes bluetooth fonctionnent parfaitement avec VLC......
Par contre lorsque jarvis parle le son est parfois haché ...voir inaudible. 
Est-ce un problème du bluetooth ?....du micro (je ne pense pas) ?........
Pour info ma config:
Raspbian:Jessie - Micro :Andoer Omni-Directional - Enceinte bluetooth :Créative T12 wireless.

Merci à tous

**Comment by JeanBajb** [comment]
Bonjour 
C'est encore moi......après la mise à jour  de jarvis ....oh! miracle le bluetooth fonctionne relativement bien.
Quelques craquements de temps en temps mais c'est mieux qu'en HDMI.....encore merci et bravo à tous ceux qui contribue à ce projet ....
JeanBa

**Comment by Bobby512** [comment]
Je cherche un micro-cravate Bluetooth pour fonctionner avec Jarvis sur un RPI3 ou une Tinker Board. Que pouvez-vous me conseiller SVP ?
