### ISSUE TITLE
Jarvis continue d'écouter la commande alors que j'ai fini de parler (il affiche des #)

### ISSUE THREAD

**Issue by francoismartin** [alexylem/jarvis#112]
J'ai du mal a comprendre comment configurer Jarvis pour régler la sensibilité

J'ai acheté le micro Array SoundTouch sous plusieurs recommendation, j'ai réglé la sensibilité a 51% pour qu'il m'entend. Mais le problème est que dès que j'ai la fenêtre ouverte ou un léger fond sonore, jarvis n'est pas capable de détecter que j'ai arrêté de parler pour lancer la commande à Bing.

Il entend parfaitement le hotword mais il fait des # car il ne sait pas quand s'arrêtait d'écouter.
Vous savez comment je peux améliorer ça ?

C'est avec les :

```
Min noise duration to start (0.1)
Min noise perc to start (1%)
Min silence duration to stop (0.5)
Min silence level to stop (1%)
Max noise duration to kill (10)
```

?
Merci

**Comment by alexylem** [comment]
**Attention** je te conseille fortement d'ajuster d'abord la sensibilité de ton micro avant de changer ces valeurs. Si ton micro est très sensible, le bruit de fond empêchera l'arrêt automatique de l'enregistrement (ce qui est ton cas). Il faut donc d'abord essayer de baisser la sensibilité dans `Settings > Audio`. 

Si tu veux vraiment exceptionnellement modifier ces valeurs, voici leur signification:
```bash
Min noise duration to start (0.1) # Durée minimale du son pour commencer à enregistrer
Min noise perc to start (1%) # Volume minimum du son pour commencer à enregistrer
Min silence duration to stop (0.5) # Durée minimale du silence pour arrêter d'enregistrer
Min silence level to stop (1%) # Volume minimum du son pour arrêter d'enregistrer
Max noise duration to kill (10) # Durée maximale du son pour arrêter d'enregistrer (timeout quand  trop de bruit, exemple musique, discussions ou télévision)
```
Il te faut donc augmenter
```
Min silence level to stop (1%) # Volume minimum du son pour arrêter d'enregistrer
```
Essaye de le monter progressivement jusqu'à ce que ca marche.

**Comment by francoismartin** [comment]
Oki merci @alexylem pour les explications.
