### ISSUE TITLE
ERROR: snowboy recognition failed sur C.H.I.P

### ISSUE THREAD

**Issue by tuxie1** [alexylem/jarvis#113]
### Description

J'ai réussi à installer jarvis sur mon C.H.I.P.

Cependant, lorsque je l'execute j'obtiens un plantage dès le lancement

### Résultat
```

Checking for updates...[Up-to-date]

------------ Config ------------
system               Linux 4.3.0rd235+ armv7l 
os                   "Debian GNU/Linux 8 (jessie)" 
language             fr_FR 
play_hw              hw:1,0 
rec_hw               hw:1,0 
speaker              Plantronics, Inc.  
microphone           Plantronics, Inc.  
trigger_stt          snowboy 
command_stt          google 
tts_engine           svox_pico 
conversation_mode    true 
--------------------------------

DEBUG: program_startup hook
snowboy: Hello
snowboy: Waiting to hear 'snowboy'
david: (listening...)
DEBUG: models=fouzy-arrosage,germaine-fouzy-l-arrosage,germaine,ouvre-le-portail,que-puis-je-faire,snowboy,snowboy
Traceback (most recent call last):
  File "stt_engines/snowboy/main.py", line 1, in <module>
    import snowboydecoder
  File "/home/vallond/jarvis/stt_engines/snowboy/snowboydecoder.py", line 4, in <module>
    import pyaudio
EOFError: EOF read where object expected
DEBUG: modelid=-10
ERROR: snowboy recognition failed
```

**Comment by alexylem** [comment]
Jarvis utilise des librairies de `snowboy` pré-compilées pour OSX et Raspberry Pi. Je pense que l'erreur vient de ca, C.H.I.P utilise un processeur différent?
Je te conseille de compiler ta propre libraire sur snowboy (voir #79)

**Comment by tuxie1** [comment]
Le C.H.I.P. est un ARMv7 tout comme le rapsberry PI2.
Sur une mauvaise manipulation de recompilation de noyau j'ai dû le réinstaller donc j'ai perdu mon installation.
Je tenterai la compilation de snowboy quand j'aurais plus de temps.

Merci du coup de main, tu peux cloturer.

PS : l'avantage du C.HI.P. de Next Thing est qu'il n'est pas cher (9$) et que la carte son est incorporé :-)
