### ISSUE TITLE
rec FAIL formats: can't open input  `default'

### ISSUE THREAD

**Issue by diyfr** [alexylem/jarvis#115]
### Description
Sur la procédure d'installation, j'ai une erreur à la détection du microphone  
sur  carte audio USB   :
````
Bus 001 Device 005: ID 1b3f:2007 Generalplus Technology Inc.
````
### Résultat
```
ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM false
rec FAIL formats: can't open input  `default': snd_pcm_open error: No such file or directory
``` 
un arecord -l     donnerait :   
```
**** Liste des Périphériques Matériels CAPTURE ****
carte 1: Device [USB Audio Device], périphérique 0: USB Audio [USB Audio]
  Sous-périphériques: 1/1
  Sous-périphérique #0: subdevice #0
```
a priori dans ce cas pas de carte 0 en ce qui me concerne.

**Comment by alexylem** [comment]
Je suis étonné que tu puisses rencontrer une telle erreur à' l'installation.
Pourrais-tu recommencer et me coller le contenu exact de ta console?
Merci!

**Comment by diyfr** [comment]
Avant c'est la validation de la sortie audio.
Il y a juste un truc avant la ligne d'erreur Alsa citée ci avant.
J'essaie demain soir de rejouer l'installation.

**Comment by diyfr** [comment]
Mise à jour réalisée.
A l'étape Haut Parleurs j'ai bien les applaudissements
A l'étape microphone, a priori ça enregistre bien. Mais ça plante à la lecture de l'enregistrement
```
**** Liste des Périphériques Matériels CAPTURE ****
carte 1: Device [USB Audio Device], périphérique 0: USB Audio [USB Audio]
  Sous-périphériques: 1/1
  Sous-périphérique #0: subdevice #0
Indicate the card # to use [0-9]: 1
Indicate the device # to use [0-9]: 0
Updating ~/.asoundrc...
Reloading Alsa...

Input File     : 'default' (alsa)
Channels       : 2
Sample Rate    : 48000
Precision      : 16-bit
Sample Encoding: 16-bit Signed Integer PCM

In:0.00% 00:00:03.07 [00:00:00.00] Out:144k  [      |      ]        Clip:0
Done.
ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM false
play FAIL formats: can't open output file `default': snd_pcm_open error: No such file or directory
false
```
du coup je creuse à la mano et je reviens

**Comment by stonfute** [comment]
J'avais une erreur dans le genre. J'ai installé pulseaudio et passé ma carte en n°0

**Comment by diyfr** [comment]
J'ai supprimé le fichier .asoundrc et relancer l'installation et cela fonctionne. !! par contre le volume micro est très bas.

**Comment by stonfute** [comment]
Un coup de alsamixer avec le mic a fond et capture a fond et c'est réglé.

**Comment by diyfr** [comment]
Bon manuellement ça fonctionne 
Snowboy fonctionne, mais l'enregistrement de la commande il ne se passe rien
````
DEBUG: speech duration was 95 (10 = 1 sec)
DEBUG: too long for a command (max 4 secs), ignoring...
./timeout.sh 10 rec -V1 -q -r 16000 -c 1 -b 16 -e signed-integer --endian little jarvis-record.wav silence 1 0.1 1% 1 0.5 1% trim 0 10
````
une idée @stonfute

**Comment by stonfute** [comment]
Je dirais que tu as trop de bruit. Visiblement d'après le debug, il écoute pendant 9.5sec mais ne capte aucune commande.

**Comment by diyfr** [comment]
Bizarre car snowboy fonctionne sans problèmes. J'essaierai demain manuellement. Il est peut-être possible que Jarvis fasse fi des réglages d'alsamixer ? et pas snowboy ?

**Comment by diyfr** [comment]
Bon je viens de faire de nouveau test, jarvis-record.wav est lisible et je m'entends parler
mais ça ne déclenche pas la reconnaissance via bing.
````
DEBUG: speech duration was 95 (10 = 1 sec)
DEBUG: too long for a command (max 4 secs), ignoring...
./timeout.sh 10 rec -V1 -q -r 16000 -c 1 -b 16 -e signed-integer --endian little jarvis-record.wav silence 1 0.1 1% 1 0.5 1% trim 0 10
````
je vais regarder du côté de jarvis-functions.sh

**Comment by diyfr** [comment]
C'est tout bon pour moi ! Un petit tour dans les paramètres !!!

**Comment by alexylem** [comment]
@diyfr bien joué, chapeau pour l'investigation et l'utilisation des paramètres de sox. Pour les intéressés j'en explique la fonction ici: #112

**Comment by diyfr** [comment]
@alexylem petite précision je suis sur un RPI zero... Je ne veux pas faire de teasing, mais maintenant je recherche activement  un microphone array pas trop cher. j'ai quelques pistes à creuser. 
En tout cas Good Job. Jarvis est simple et efficient.

**Comment by diyfr** [comment]
@alexylem il serait presque possible de faire un étalonnage.
On demande à l'utilisateur de ne pas parler dans son micro
Puis dans une boucle on incrémente le coefficient de silence jusqu’à ce que la longueur de la piste audio générée par sox soit nulle ?

**Comment by alexylem** [comment]
Excellente idée @diyfr, tu peux créer un nouveau ticket en ton nom pour cette évolution?

**Comment by wangxu2016** [comment]
My playback 3.5mm headphone jack, usb device for recording, use the following configuration：
`pcm.!default {
  type asym
   playback.pcm {
     type plug
     slave.pcm "hw:0,0"
   }
   capture.pcm {
     type plug
     slave.pcm "hw:1,0"
   }
}`
