### ISSUE TITLE
probleme avec snowboy avec les fichier python 

### ISSUE THREAD

**Issue by imperloys** [alexylem/jarvis#116]
Bonjour, je ne comprend  pas tous mais aparament un ou deux fichier  python de snowboy ne fonctionne pas 
 ┌─── ─────────────────────────────┤ Jarvis ├────────────────────────────────┐
                                     │ Configuration > Audio                                                    │ 
                                     │                                                                          │ 
                                     │                    Speaker (false)                                       │ 
                                     │                    Mic (false)                                           │ 
                                     │                    Volume                                                │ 
                                     │                    Sensitivity                                           │ 
                                     │                    Min noise duration to start (0.1)                     │ 
                                     │                    Min noise perc to start (1%)                          │ 
                                     │                    Min silence duration to stop (0.5)                    │ 
                                     │                    Min silence level to stop (1%)                        │ 
                                     │                    Max noise duration to kill (10)                       │ 
                                     │                                                                          │ 
                                     │                                                                          │ 
                                     │                                                                          │ 
                                     │                                                                          │ 
                                     │                                                                          │ 
                                     │                   <Ok>                       <Annuler>                   │ 
                                     │                                                                          │ 
                                     └──────────────────────────────────────────────────────────────────────────┘ 
------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------~/jarvis$ ./jarvis.sh
Checking for updates...[Up-to-date]
Checking for updates...[Up-to-date]
Checking dependencies:
alsamixer: [Installed]
aplay: [Installed]
arecord: [Installed]
awk: [Installed]
curl: [Installed]
git: [Installed]
iconv: [Installed]
mpg123: [Installed]
nano: [Installed]
perl: [Installed]
sed: [Installed]
sox: [Installed]
wget: [Installed]
whiptail: [Installed]
Press [Enter] to continue

------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------                                                                                                                  

imperloyce@imperloyce:~/jarvis$ ./jarvis.sh
Checking for updates...[Up-to-date]

------------ Config ------------
system               Linux 4.4.0-31-generic x86_64 
os                   
Ubuntu

"Ubuntu" 
language             fr_FR 
play_hw              false 
rec_hw               false 
speaker              Default 
microphone           Default 
trigger_stt          snowboy 
command_stt          google 
tts_engine           svox_pico 
conversation_mode    true 
--------------------------------

DEBUG: program_startup hook
hey_you: Hello
hey_you: Waiting to hear 'hey_you'
imperloyce: (listening...)
DEBUG: models=hey_you,snowboy
Traceback (most recent call last):
  File "stt_engines/snowboy/main.py", line 1, in <module>
    import snowboydecoder
  File "/home/imperloyce/jarvis/stt_engines/snowboy/snowboydecoder.py", line 5, in <module>
    import snowboydetect
  File "/home/imperloyce/jarvis/stt_engines/snowboy/snowboydetect.py", line 28, in <module>
    _snowboydetect = swig_import_helper()
  File "/home/imperloyce/jarvis/stt_engines/snowboy/snowboydetect.py", line 24, in swig_import_helper
    _mod = imp.load_module('_snowboydetect', fp, pathname, description)
ImportError: /home/imperloyce/jarvis/stt_engines/snowboy/_snowboydetect.so: wrong ELF class: ELFCLASS32
DEBUG: modelid=-10
ERROR: snowboy recognition failed

#

**Comment by alexylem** [comment]
Dupplicate, voir #79
