### ISSUE TITLE
Freeze à l'installation au moment de la configuration du micro avec Jessie Lite

### ISSUE THREAD

**Issue by whoknows** [alexylem/jarvis#117]
### Description

A de l'installation de jarvis, pendant la détection de la voix, l'application crashe et je perd le contrôle de mon terminal. Je dois le quitter, puis relancer une connexion ssh...
Langue fr
J'utilise les moteurs recommandés (snowboy, bing, svox_pico).

Mon micro est une carte son creative (que j'ai testé au préalable sur le pi). J'utilise un rpi 1 B sur lequel tout est à jour. Il est overclocké en mode turbo.

### Résultat
```
./jarvis.sh 
Checking for updates...[Up-to-date]
Checking dependencies:
alsamixer: [Installed]
aplay: [Installed]
arecord: [Installed]
awk: [Installed]
curl: [Installed]
git: [Installed]
iconv: [Installed]
mpg123: [Installed]
nano: [Installed]
perl: [Installed]
sed: [Installed]
sox: [Installed]
wget: [Installed]
whiptail: [Installed]
Press [Enter] to continue
ERROR: Unknown configure bing_speech_api_key1
ERROR: Unknown configure bing_speech_api_key2

sounds/applause.wav:

 File Size: 463k      Bit Rate: 1.41M
  Encoding: Signed PCM    
  Channels: 2 @ 16-bit   
Samplerate: 44100Hz      
Replaygain: off         
  Duration: 00:00:02.62  

In:100%  00:00:02.62 [00:00:00.00] Out:116k  [      |      ] Hd:0.0 Clip:0    
Done.
true

Input File     : 'default' (alsa)
Channels       : 2
Sample Rate    : 48000
Precision      : 16-bit
Sample Encoding: 16-bit Signed Integer PCM

In:0.00% 00:00:03.07 [00:00:00.00] Out:144k  [      |      ]        Clip:0    
Done.

jarvis-record.wav:

 File Size: 576k      Bit Rate: 1.54M
  Encoding: Signed PCM    
  Channels: 2 @ 16-bit   
Samplerate: 48000Hz      
Replaygain: off         
  Duration: 00:00:03.00  

In:34.1% 00:00:01.02 [00:00:01.98] Out:49.2k [      |      ]        Clip:0    
```

**Comment by alexylem** [comment]
Thanks for raising the problem.
I have just committed a fix for it, could you please restart Jarvis to update and relaunch the installation wizard?

**Comment by whoknows** [comment]
I updated Jarvis, created a bing speech api key but the problem is still the same. I'll try on my rpi 2 this weekend, maybe the first one has performance issues ?

```
pi@rp1[~/dev/jarvis](master): ./jarvis.sh 
Checking for updates...[Up-to-date]
Checking dependencies:
alsamixer: [Installed]
aplay: [Installed]
arecord: [Installed]
awk: [Installed]
curl: [Installed]
git: [Installed]
iconv: [Installed]
mpg123: [Installed]
nano: [Installed]
perl: [Installed]
sed: [Installed]
sox: [Installed]
wget: [Installed]
whiptail: [Installed]
Press [Enter] to continue

sounds/applause.wav:

 File Size: 463k      Bit Rate: 1.41M
  Encoding: Signed PCM    
  Channels: 2 @ 16-bit   
Samplerate: 44100Hz      
Replaygain: off         
  Duration: 00:00:02.62  

In:100%  00:00:02.62 [00:00:00.00] Out:116k  [      |      ] Hd:0.0 Clip:0    
Done.
true

Input File     : 'default' (alsa)
Channels       : 2
Sample Rate    : 48000
Precision      : 16-bit
Sample Encoding: 16-bit Signed Integer PCM

In:0.00% 00:00:03.07 [00:00:00.00] Out:144k  [      |      ]        Clip:0    
Done.

jarvis-record.wav:

 File Size: 576k      Bit Rate: 1.54M
  Encoding: Signed PCM    
  Channels: 2 @ 16-bit   
Samplerate: 48000Hz      
Replaygain: off         
  Duration: 00:00:03.00  

In:31.3% 00:00:00.94 [00:00:02.06] Out:45.1k [      |      ]        Clip:0    
```

**Comment by alexylem** [comment]
Mince je sais pas pourquoi je t'ai répondu en anglais :smile: 
Jarvis fonctionne très bien sur Raspberry Pi 1 (il a été conçu pour ce modèle à la base)
Je n'arrive pas trop à comprendre comment ton temrinal "crash".  Ce que je vois sur ton log est simplement l'interface de Sox qui attend que tu parles dans le micro.
Vois-tu la barre de son bouger quand tu parles dans le micro? Ca devrait normalement enregistrer pendant quelques secondes puis t'afficher un menu pour te demander si tu t'es entendu.
Si ca crash vraiment ca devrait retourner dans l'invite de commandes...
Si ce n'est toujours pas clair, il faudrait que tu enregistres une vidéos du terminal en train de suivre les étapes pour que je comprenne mieux ce qu'il se passe...

**Comment by whoknows** [comment]
Pas de soucis ;)
En fait au moment de la détection vocale, mon terminal freeze. Je suis obligé de le quitter et relancer. Je ne peux pas faire ctrl-c ou quoi que ce soit. Pour info je me connecte en ssh.
Je vais essayer de faire une vidéo entre midi et deux.

**Comment by alexylem** [comment]
Avant de faire la vidéo, essaye de lancer cette commande dans le terminal en SSH pour voir si c'est celle la qui fait freezer:
```bash
rec test.wav trim 0 3
```

**Comment by whoknows** [comment]
ça fonctionne bien

```
pi@rp1[~]: rec test.wav trim 0 3

Input File     : 'default' (alsa)
Channels       : 2
Sample Rate    : 48000
Precision      : 16-bit
Sample Encoding: 16-bit Signed Integer PCM

In:0.00% 00:00:03.07 [00:00:00.00] Out:144k  [      |      ]        Clip:0    
Done.
```

**Comment by alexylem** [comment]
Et la 2ème partie? (que j'ai rajouté via un edit du port)
```
play test.wav
```

**Comment by whoknows** [comment]
pareil ça fonctionne bien (après je ne suis pas chez moi donc je fais tourner ça dans le vide, mais je garde le controlle du terminal)
```
pi@rp1[~]: play test.wav

test.wav:

 File Size: 576k      Bit Rate: 1.54M
  Encoding: Signed PCM    
  Channels: 2 @ 16-bit   
Samplerate: 48000Hz      
Replaygain: off         
  Duration: 00:00:03.00  

In:100%  00:00:03.00 [00:00:00.00] Out:144k  [      |      ]        Clip:0    
Done.
```

**Comment by alexylem** [comment]
Pourtant d'après ton log j'ai l'impression que ca plante dans le `play` vu que le compteur ne va pas au bout:
```
In:31.3% 00:00:00.94 [00:00:02.06] Out:45.1k [      |      ]        Clip:0   
```
Tu pourras confirmer que ces chiffrent freezent aussi?
Je pense que la vidéo sera très utile, j'ai hâte de la voir.

**Comment by whoknows** [comment]
Voila la vidéo 
https://drive.google.com/open?id=0ByieTRBKXJbJdzRvdGdYT3U4OTA

**Comment by alexylem** [comment]
Génial merci beaucoup, ca m'a même permis de voir que le STT par défaut était Google alors qu'il devrait être Bing, je vais corriger ca 😄 
Bon alors je vois un truc bizarre, à la lecture des applaudissement tu as bien le VU Meter
![image](https://cloud.githubusercontent.com/assets/11017174/18506576/fd298d40-7a6c-11e6-9fe2-12b92c25d935.png)
Mais pas à l'enregistrement (ni à la lecture) de ta voix:
![image](https://cloud.githubusercontent.com/assets/11017174/18506612/20219acc-7a6d-11e6-8b0c-e329777620b1.png)
Donc effectivement ton micro n'est pas configuré (ce n'est pas une surprise), mais au moins la lecture ne devrait pas planter. C'est d'autant plus bizarre qu'elle ne plante pas si tu le fais manuellement...
Ne t'en fais pas je suis sûr qu'on va trouver très rapidement une solution 😄 
Peux-tu, après avoir relancé le terminal, faire:
```bash
play jarvis-record.wav
```
et voir si ca freeze aussi?

**Comment by whoknows** [comment]
Alors c'est peut être normal qu'à l'enregistrement le VU meter ne bouge pas, je ne suis pas chez moi et donc ne peux pas parler.
J'ai joué la commande, ça a marché :
```
play jarvis-record.wav

jarvis-record.wav:

 File Size: 576k      Bit Rate: 1.54M
  Encoding: Signed PCM    
  Channels: 2 @ 16-bit   
Samplerate: 48000Hz      
Replaygain: off         
  Duration: 00:00:03.00  

In:100%  00:00:03.00 [00:00:00.00] Out:144k  [      |      ]        Clip:0    
Done.
```

**Comment by alexylem** [comment]
C'est carrément bizarre et je n'arrive pas à l'expliquer...
Bon comme vraisemblablement tu es le seul à avoir ce problème, on va tenter une petite solution de contournement.
D'après la vidéo, la lecture tourne pendant 1 seconde avant de planter, il faut que tu essayes de l'interrompre avant que ca freeze. Donc dès que ca commence à lire, fait tout de suite [Ctrl+C]
Et voyons si ca passe à l'étape suivante...

**Comment by whoknows** [comment]
Alors, ça a l'air d'avoir marché !
Petite vidéo avec un top en cadeau
https://drive.google.com/open?id=0ByieTRBKXJbJcFBSZFByN0dqcXc

**Comment by alexylem** [comment]
Did you hear yourself fallait répondre non 😄 
Super, quand tu seras chez toi, si Jarvis ne t'entends pas (ce qui est fort probable avec les settings du Raspberry Pi par défaut), va dans:
Settings > Audio > Mic
Choisis Non quand il te demande si tu t'es entendu, et il va t'aider à configurer ton micro.
On y est presque!

**Comment by jbastian67** [comment]
Bonjour,
j'ai reçu ma raspberry 3 B aujourd'hui et j'ai tenté d'installer Jarvis sur une base de raspbian jessie lite fraichement téléchargée de raspberrypi.org et lors de la config du micro j'ai eu le même problème.
J'ai tenté un apt-get update et upgrade sans effet. Mais j'ai réussi à résoudre ce problème en prenant la version de raspbian jessie complète et non la lite.
Peut être un problème venant d'un module manquant ou non mit a jour?
Cordialement

**Comment by alexylem** [comment]
Merci @jbastian67 pour ton post ca va beaucoup nous aider.
Dans le wiki, je conseille déjà fortement d'utiliser la version full de jessie:
https://github.com/alexylem/jarvis/wiki/prerequisites
![image](https://cloud.githubusercontent.com/assets/11017174/18594474/9398f5b6-7c40-11e6-94c2-5d9f4da38bac.png)

**Comment by whoknows** [comment]
J'ai enfin pu m'occuper de tout ça, j'ai installé la dernière version de Raspbian FULL, et cette fois ci Jarvis marche parfaitement !
