### ISSUE TITLE
Hotword de fin de conversation

### ISSUE THREAD

**Issue by zoic21** [alexylem/jarvis#119]
Bonjour,

Déjà félicitation pour tout le travail accompli qui permet de contrôler ma domotique a la parole (sans un gros windows qui tourne) avec un taux de reconnaissance assez impressionnant.
Après avoir passé pas mal d'heure d'utilisation j'aurais un petit demande ça serait la possibilité d'ajout un mot clef de fin de conversation (idéalement reconnu par snowboy). Car suite à un ordre jarvis reste en écoute or il sera pratique de lui dire par exemple merci et qu'il arrête d'écoute jusqu'au prochain "jarvis".

Merci d'avance

**Comment by alexylem** [comment]
Merci 😄 
C'est déjà possible, et inclu dans les commandes de base:
```bash
ANNULE*|TERMINE*==bypass=false; say "Ok"
```
Il suffit donc de dire "Annuler", "Terminé", ...
C'est la partie `bypass=false` qui permet de sortir du mode conversation.
Tu peux bien entendu la modifier (menu Commands) pour qu'il reconnaisse "Merci"
```bash
MERCI==bypass=false; say "Ok"
```
Tu peux aussi désactiver le mode conversation dans Settings > General.
Alex.

**Comment by zoic21** [comment]
Merci pour ce retour rapide, effectivement j'avais vu cette possibilité mais celle-ci me pose 2 soucis : 
- dans le cadre de mon implémentation je renvoi tous les phrases vers un second logiciel qui traite la demande : (*)==
- La reconnaissance du mot est faite par Google,Bing ou Wit or la l'idée était d'utiliser snowboy qui est local et plus fiable

**Comment by alexylem** [comment]
Ca marche aussi:
```shell
MERCI==bypass=false; say "Ok"
(*)==...
```
Si tu mets `MERCI` avant `(*)` elle ne sera pas envoyée à ton serveur distant.
Puis utilise les commandes rapides de snowboy:
https://github.com/alexylem/jarvis/wiki/snowboy#commandes-rapides
Il te suffit de créer et de trainer `merci.pmdl`
Alex.
