### ISSUE TITLE
Commande météo ne marche plus

### ISSUE THREAD

**Issue by remjou1** [alexylem/jarvis#121]
la commande préconfigurer sur jarvis pour connaitre la météo ne marche plus... voilà la commande : 

```
*METEO*==say "je regarde" && say "`wget -q -O- \"www.accuweather.com/fr/fr/renty/160414/weather-forecast/160414\" | awk -F\\' '/acm_RecentLocationsCarousel\.push/{print \$14\" avec une température de \"\$10\" degrés\" }'| head -1`"
```
Il ne me donne que la température... c'est quoi le problème ?

**Comment by MrJekyll** [comment]
idem pour moi...

**Comment by stonfute** [comment]
Je pense que le plus simple serait de passer par quelque chose de plus évoluer qu'un wget + awk pour scrapper la page. Je pense que html-xml-utils n'est pas trop mal !

Un bon exemple d'utilisation : [http://www.joyofdata.de/blog/using-linux-shell-web-scraping/](http://www.joyofdata.de/blog/using-linux-shell-web-scraping/)

Il faut sélectionner la div.temp pour la température et span.cond pour le temps qu'il fait.

Techniquement ça permet de faire plus que récupérer la météo, ça permet de récupérer n'importe quelle info de n'importe quel site.

**Comment by alexylem** [comment]
Je confirme chez moi aussi ca ne marche plus. J'avoue que je l'avais fait à l'arrache histoire de donner des exemples d'utilisation sans installer de logiciel supplémentaire.
Je vous recommande d'attendre que le store soit en place #52 ainsi vous pourrez publier et bénéficier des plugins de la communauté, et donc de ceux qui sont sans aucun doute plus calé que moi sur le sujet 😄

**Comment by kevincaradant** [comment]
@alexylem, It's resolved since your new plugin,  isn't it ?

**Comment by alexylem** [comment]
Yes it's resolved I re-built it using an API, available in the store :)
