### ISSUE TITLE
Supprimer le son error.wav quand un ordre n'est pas compris

### ISSUE THREAD

**Issue by Thedj95** [alexylem/jarvis#123]
stl mec 
Bien jouée pour ton Project
J'aurais une petit question serais t'il possible que je retire le bong quand il ne comprend pas ( quand il affiche  ? dans la console)

Cordialement

**Comment by alexylem** [comment]
Extrait du code:
```bash
if [ -z "$order" ]; then
  printf '?'
  PLAY sounds/error.wav
```
Tu pourrais supprimer / remplacer le fichier `sounds/error.wav` mais il serait remis à la prochaine mise à jour...
Pourquoi voudrais-tu enlever ce son? C'est le seul moyen, sans écran, de savoir qu'il n'a pas compris...

**Comment by Thedj95** [comment]
Parce que quand il est désactivé il me fait comme le bruit et donc sa m'énerve et en plus j ai un écran constament connecter sur la console

Merci de ta réponse aussi rapide

**Comment by alexylem** [comment]
Tu utilises quoi comme moteur de détection du mot clé? Quand tu ne l'utilises pas il ne devrait pas réagir tant que tu ne dis pas le mot clé...

**Comment by Thedj95** [comment]
J'utilise full Google

**Comment by Thedj95** [comment]
Si tu veut je te prend une vidéo pour te montrer la réaction

**Comment by alexylem** [comment]
C'est le problème... tu devrais utiliser `snowboy` car Google ne t'autorise que 50 reconnaissances par jour... Donc bientôt plus rien ne sera reconnu...
Pas besoin de vidéo, change ton moteur de reconnaissance du mot clé.

**Comment by Thedj95** [comment]
Ok je vais le changer merci pour t'es presieux conseil
Je te dirais si sa marche lieu des que je l'aurais installer

**Comment by alexylem** [comment]
Ok réouvre un autre ticket si tu n'arrives pas à faire fonctionner `snowboy` (regarde d'abord bien entendu le wiki et les autres tickets à ce sujet 😄 )
