### ISSUE TITLE
encore le beug

### ISSUE THREAD

**Issue by Thedj95** [alexylem/jarvis#124]
`Stl` mec je te recontacte parce que j'ait toujours le problème , j ai installer pocketsphinx en recognition of magic word et sa me fait toujours le dong

Je t'ai mis un screen des qu'il y a un point interrogation c est qu'il fait dong
![wp_20160916_21_12_54_pro](https://cloud.githubusercontent.com/assets/22242922/18598569/b95f1f2e-7c53-11e6-9ea6-72bf4f7d532b.jpg)

**Comment by alexylem** [comment]
Le point d'interrogation c'est parce qu'il n'a pas reconnu l'ordre.
Je vois pourtant sur ta capture d'écran que tu as réussi à faire reconnaitre JARVIS une fois (en haut). C'est donc que PocketSphinx est bien configuré.
PocketSphinx est assez difficile à utiliser car il utilise le dictionnaire et modèle de langue ANGLAIS, donc il faut prononcer Jarvis avec un accent anglais pour que ca marche bien.
C'est aussi pour ca que je recommande d'utiliser Snowboy (aussi en local mais bien plus performant) à la place de PocketSphinx désormais.

**Comment by Thedj95** [comment]
le problème c'est q'avec SnowBoy c'est que je peut pas l’appeler Jarvis

**Comment by alexylem** [comment]
Si avec `snowboy` tu peux l'appeler "Jarvis" ou autre en enregistrant un nouveau "Hotword":
https://github.com/alexylem/jarvis/wiki/snowboy
Alex.
