### ISSUE TITLE
Probleme avec snowboy

### ISSUE THREAD

**Issue by Thedj95** [alexylem/jarvis#125]
salut mec j'ai un petit problème avec snowboy
je fait les test enregistrement avec snoboy et lorsque que je clique sur save/download sa fait rien
aurais tu une solution pour mon problèmes .

**Comment by alexylem** [comment]
Si tu n'arrives pas à télécharger le modèle depuis le site de `snowboy`, c'est que tu dois avoir un problème avec ton navigateur (genre popup-blocker). Comme ce n'est pas lié à Jarvis je ne peux pas pas trop t'aider, mais tu pourrais aussi tenter de contacter le support du site de `snowboy`.

**Comment by kevincaradant** [comment]
J'ai perdu beaucoup de temps sur ça .... c'est simplement parceque le mot que tu demandes existe déjà. Il faut le chercher dans la barre de recherche en haut a gauche. Une fois le mot trouver, tu peux cliquer sur "record your voice", un truc du genre et c'est bon :)

**Comment by alexylem** [comment]
Merci @kevincaradant pour cette précision 👍
