### ISSUE TITLE
Kodi plugin: how to create a plugin ?

### ISSUE THREAD

**Issue by kevincaradant** [alexylem/jarvis#127]
Hi

All of this is new for me. But i want control my odroid ( like raspberryPi ) by vocal command  and then, use it with the kodi plugin as we can have with "SARAH" under Windows. So when you said "right" , "left" etc, it moves at left or right in kodi media center. 

Is it possible ? 

Thank you in advance :)

**Comment by Smanar** [comment]
Yes It's possible but never try it.
I think you can use this api http://kodi.wiki/view/JSON-RPC_API/v6 and send request with Jarvis.

**Comment by kevincaradant** [comment]
thank you but Does have I to create my plugin ? On SARAH, you have to download the plugin, and a command is directly asssociated to the good call from the API. here it's the not the case ?

**Comment by Smanar** [comment]
Hu, I have never tried this system, but from the documentation nothing to download, you can simply use this command
>>*DO*THAT*==wget -qO /dev/null "http://you_http_request" & say "Done"

**Comment by kevincaradant** [comment]
Oh ok, thank you. I will check this :)

**Comment by alexylem** [comment]
Just to fix the typo in @Smanar example:
```shell
DOTHAT*==wget -qO /dev/null "http://you_http_request" && say "Done" # double &&
```
It was wrong also [on the FAQ](https://github.com/alexylem/jarvis/wiki/faq), now fixed.
If someone manages to get it work, please share it with other as a plugin via [the Store](https://github.com/alexylem/jarvis/wiki/store).

**Comment by kevincaradant** [comment]
OK, that seems very simple via the http request. Thanks for the example @Smanar  :). just one question. I want a config file to write the IP and port with variables names. I already looked fr_time as example but i didn't see any variables like $my_var defined in a specific file. My aim is to create a little plugin for kodi and I will publish it if you think it's interesting for you and the community ;)

**Comment by kevincaradant** [comment]
I had a problem with this command:
`BAS*==wget -qO /dev/null "http://192.xxx.xxx.xxx::8080/jsonrpc?request={"jsonrpc":"2.0","method":"Input.Left","params":{},"id":1}" && say "Done"`

BAS is interpreted by JARVIS, it says "done" but nothing happened :/. 

In the browser the request `"http://192.xxx.xxx.xxx::8080/jsonrpc?request={"jsonrpc":"2.0","method":"Input.Left","params":{},"id":1}"` is applied on my kodi instantly

 so what's wrong ? Thank you

**Comment by alexylem** [comment]
@kevincaradant,
* Use variable names

>Yes it's possible, my fr_time is too simple and doesn't use them, please follow the tutorial here on [how to publish a plugin on the store](https://github.com/alexylem/jarvis/wiki/store). If it doesn't work for you please report back here I will build a quick plugin with example on how to use variables.

* Problem with your command

> Be careful with the quotes in your json, they are closing the double quote for your wget URL... try to escape them or use single quotes around the URL.

**Comment by kevincaradant** [comment]
@alexylem  ok thank you and as I said in the 'edit' , I fixed my problem using curl. I didn't delete the message that's all ;). 

For the variable it's OK in the store pluggin, I tried on the fr_time. But i don't successful with the jarvis_commands file.
How can i try my plugin ? I deleted all my commands from jarvis-commands to put inside a new folder in the store folder near of the fr_time pluggin but after that ? My commands are not available from jarvis :/. And i can't see it with the pluggin installer from the menu of jarvis. I'm stuck.

**Comment by alexylem** [comment]
I have just pushed a new plugin that gives the weather and uses variables to be configured.
While doing it I realized I had to change the code of jarvis for variables to work, now you should be safe 😄 
Just update your Jarvis and have a look.

How to proceed:

1. To create a plugin, follow the tutorial on [how to publish a plugin on the store](https://github.com/alexylem/jarvis/wiki/store)
2. To test it, install it from the store 😄  (still in the tutorial)
3. To publish it, follow the tutorial on [how to publish a plugin on the store](https://github.com/alexylem/jarvis/wiki/store)

You can have both your commands in the menu commands and your plugins in store/all that are moved to store/installed when installed.

You can be the first one after me to publish a plugin on the store 👍  so don't give up and don't hesitate to ask for help!

**Comment by kevincaradant** [comment]
Oh thank you but it's clear for me on two points.

1- To try my plugin, i have to push it on the store before ? With the variables, I'm not sure that works ... so i want try in local before to push something maybe broken

2-  i can have the same commands in the plugins and in jarvis-Commands at the root of project ? But at the root, in the command file, I didn't see variables used in any example :/ only in the plugins, so maybe it's not possible and it's only reserved for pluggins ?

**Comment by kevincaradant** [comment]
@alexylem , i call your performance in shell :).

I tried something like that: `*VOLUME A (*) POURSAN==curl -X POST -H "Content-Type: application/json" -d '{"jsonrpc":"2.0","method":"Application.SetVolume","params":{"volume":(1)},"id":1}' http://$ip:$port/jsonrpc`

But the answer returned is:` {"error":{"code":-32700,"message":"Parse error."},"id":null,"jsonrpc":"2.0"}`

If i write 10 instead of (1) that works. I also try something like: `$volume=(1)` and use volume like that:
`*VOLUME A (*) POURSAN==volume=(1) && curl -X POST -H "Content-Type: application/json" -d '{"jsonrpc":"2.0","method":"Application.SetVolume","params":{"volume":${volume}},"id":1}' http://$ip:$port/jsonrpc`

Thank you, i search on internet but I'm stuck with this little problem ;)

**Comment by alexylem** [comment]
**Do not modify** `jarvis-config.default.sh` !! It's the config file holding default variable at Jarvis installation (and you will loose your changes on next update).
Again:

* `jarvis-commands` are personal commands not shared with community. You can't use your own variables on this. It has to be hardcoded in the command.
* `store/` are where jarvis plugins can be created. [DTFM](https://github.com/alexylem/jarvis/wiki/store) and set your variables in `config.sh`

As per the procedure, do not name your command `volume`, prefix it with your plugin name to avoid conflicts with jarvis internal variable. Again, please, **read the procedure** 😄 

I don't think `volume=$volume-20`, search google about addition in bash...

Lastly, I don't understand why the (1) replacement did not work for you, I have to test it...

**Comment by kevincaradant** [comment]
Yes I don't understand for the (1),  I can see the value with echo (1). It
works.  but it's like if it's a problem between string and integer... I
tried to use the command expr but without successful :/.

OK for the variables, i use it just for test my command, it's just when I
make a modification, to try again,  it's very slow,  I have to install
again my plug-in,  configure the variable file etc,  so it's very more
quick using the default file of Jarvis because you have to start the script
and that's all, your command is ready unless I miss something to test more
quickly my plug-in after to change something about it?

Also,  do you think it's possible to say use the plug-in kodi and after
that you can say just 'bas' ,  'haut'  etc instead of 'kodiBas',  etc which
can be slow to pronounce.

Thank you!

Le jeu. 22 sept. 2016 07:56, Alexandre Mély <notifications@github.com> a
écrit :

**Comment by kevincaradant** [comment]
Yes I don't understand for the (1),  I can see the value with echo (1). It
works.  but it's like if it's a problem between string and integer... I
tried to use the command expr but without successful :/.

OK for the variables, i use it just to test my command, it's just when I
make a modification, to try again,  it's very slow,  I have to install
again my plug-in,  configure the variable file etc,  so it's very more
quick using the default file of Jarvis because you have to start the script
and that's all, your command is ready unless I miss something to test more
quickly my plug-in after to change something about it?

Also,  do you think it's possible to say use the plug-in kodi and after
that you can say just 'bas' ,  'haut'  etc instead of 'kodiBas',  etc which
can be slow to pronounce. 

Thank you


Edit: OK a begin of the potential solution could be in the wiki,  just write '>'  before the speech regex  and you can say something about kodi but that work only for one command :/ because after I have to write '>>' and '>>>' etc but I can't know what will be the command asked. Any possibilities to avoid this with Jarvis ?

**Comment by kevincaradant** [comment]
Yes I don't understand for the (1),  I can see the value with echo (1). It
works.  but it's like if it's a problem between string and integer... I
tried to use the command expr but without successful :/.

OK for the variables, i use it just to test my command, it's just when I
make a modification, to try again,  it's very slow,  I have to install
again my plug-in,  configure the variable file etc,  so it's very more
quick using the default file of Jarvis because you have to start the script
and that's all, your command is ready unless I miss something to test more
quickly my plug-in after to change something about it?

Also,  do you think it's possible to say use the plug-in kodi and after
that you can say just 'bas' ,  'haut'  etc instead of 'kodiBas',  etc which
can be slow to pronounce. 

Thank you


Edit: OK a begin of the potential solution could be in the wiki,  just write '>'  before the speech regex  and you can say something about kodi but that work only for one command :/ because after I have to write '>>' and '>>>' etc but I can't know what will be the command asked. Any possibilities to avoid this with Jarvis ?

**Comment by alexylem** [comment]
For the (1) replacement, please run in troubleshooting mode and paste here the processed command (will be displayed).

For the plugin development and testing, you are right, it's very annoying to install it again each time. Here is my proposal (will update the wiki):

1. Create the plugin in the `installed/` instead of the `all/` folder
2. Develop & test it directly
3. When done, move it to `all/` to test the installation

Why don't you define "Bas", "Haut", etc directly as commands? It's only your variables you have to prefix, not the commands 😄

**Comment by kevincaradant** [comment]
> "Why don't you define "Bas", "Haut", etc directly as commands? It's only your variables you have to prefix, not the commands "  OK I thought that you said this for commands... otherwise, that I want it's  possible for the moment ? 
```

Example:

Moi: Active Module Kodi
Jarvis: Fait
Moi: Bas
Moi: Valider
etc
Moi: Quitter Module Kodi

Moi: Bas // ici Bas fait autre chose
```

I will try tomorrow the troubleshooting log

**Comment by alexylem** [comment]
Too many questions, i'm getting lost! 😞 
Yes it's technically possible to do so (Activate Kodi). Just use a plugin variable you set to true when this is recognized, and in your simple orders, test this variable before you execute the command....

Are you sure you use Jarvis in French? If you really have a reco issue with you mic because of the mic itself, try using snowboy quick commands instead.

**Comment by kevincaradant** [comment]
- Sorry for this mess with this issue... It's because I find the solution about a problem in the same time I meet a new. I should have to create a new issue for each of them but that made maybe too much :/ .

- I have 15 commands for Kodi, that will be quickly hard to use snowboy quick commands. But i will try if I can't do in an other way. Or I bought again a new micro, or it's a hardware problem on the Odroid... too many possibilities.

- The plugin is almost ready. I just have to fix the **problem with the number with the example on the volume instead of letters** if it's possible :/. Otherwise, I will search an other solution.

- For my question around the "Active Module Kodi", I'm not sure to understand. I have to use the same command for two diff actions ?
 This is my actual command: 

```
ACTIVE*MODULE*KODI== ??
VALIDER==callUrlKodi '{"jsonrpc":"2.0","method":"Input.Select","id":1}'
```
callUrlKodi is a method in config.sh in the am to have a code more easy to read.

And you suggest something like that:
ACTIVE*MODULE*KODI== passMyBoolToTrue dansKodi
VALIDER==callUrlKodi '{"jsonrpc":"2.0","method":"Input.Select","id":1}'
VALIDER==Command in a other plugin which do an other thing ?

How can I manage this possibility ? That can happened now with your new store :)
Maybe that you say is right but in my way, I don't understand like it

**Comment by alexylem** [comment]
* Define a function in `config.sh`
 * I imagined this potential scenario and was thinking to provide a `functions.sh` to make the code clearer. For now just let it in `config.sh` it's fine.
* Plugin "activation"

 * I understand why you don't want to propose such simple commands such as "Haut" "Bas" because this may interfeer with other plugins. Without changing the code of Jarvis you can do this way:

**config.sh**
```shell
kodi_activated=false
kodi_call () { ... }
```
**commands**
```shell
ACTIVER KODI==kodi_activated=true && say "J'écoute"
HAUT=$kodi_activated && kodi_call...
DESACTIVER KODI==kodi_activated=false && say "Ok"
```

You could also automatically disable the module when quitting the command mode (after a timeout) using the Exiting command mode hook:
**Settings / Hooks / Exiting command mode**
```shell
kodi_activated=false
```
You could setup the hook from the plugin install script (to be tested):
`install.sh`
```shell
echo "kodi_activated=false" >> ../../hooks/exiting_cmd
```

**Comment by alexylem** [comment]
I think I will include possibility to set-up hooks directly at plugin level, in addition to functions. Here could be the new module structure:
```shell
my_module/
  commands
  config.sh
  functions.sh # new
  info.md => README.md # to be browsed in Github
  install.sh
  uninstall.sh
  hooks/ # new
    entering_cmd
    exiting_cmd # fill in this file :)
    program_startup
    program_exit
```

**Comment by kevincaradant** [comment]
I like this new structure ! :)
OK I will try that you say, I'm not sure to understand, I have to do some tests before  and I will edit this issue ;)
Thanks

**Comment by alexylem** [comment]
The boolean is only a way to ignore the command `HAUT` is you have not requested to `ACTIVATE KODI` before...
Indeed it will not check for the next one...
In previous versions of Jarvis you have the choice to check for other matching commands, but I removed it 😞 
Still I believe that for this kind of navigation commands to control the tv you need reactivity, and for this the best is to use `snowboy` quick commands, such as `KODI HAUT` `KODI BAS`, but you need to train your `*.pmdl` and this will take some time for you and for every user who will install your plugin (if they choose to use `snowboy` quick commands too).

**Comment by kevincaradant** [comment]
"In previous versions of Jarvis you have the choice to check for other matching commands, but I removed it" Any reason ? Performance ? 

OK I have still 27 commands just for KODI :/. It's too much for Snowboy ?

**Comment by alexylem** [comment]
27 😱  ? Yes indeed it's a bit too many for Snowboy (although I'm sure it can handle them, depends on your machine....).

In this case I think the best approach is to use increments:

**commands**
```
KODI==say "Oui?"
>HAUT==kodi_call...
>BAS==kodi_call...
>GAUCHE==kodi_call...
>DROITE==kodi_call...
```

You will have to say "KODI" before each command, but this way you will have no conflict. Give it a try and see if it's manageable...

**Comment by kevincaradant** [comment]
Yep look at my fork, you will understand why.
https://github.com/kevincaradant/jarvis/blob/master/store/all/kodi/commands

And In this case, I have just write KODI BAS as command no ? Instead of your example. Or I miss something

**Comment by alexylem** [comment]
Stupid me indeed you can directly write `KODI HAUT` in the commands... Sorry if I'm misleading you 😄 
I see in your commands that you mix both languages, I would suggest to have 2 plugins as they are prefixed by the language:
```shell
fr_kodi/
en_kodi/
```
This way you can also translate the `info.md` 👍 
I'm looking forward your pull request...

By the way someone submitted 2 plugins this morning, so you will not be the first one anymore 😉

**Comment by kevincaradant** [comment]
OK for the languages :).

Nooooo, don't accept the others plugin before mine :D.
