### ISSUE TITLE
E: Package 'libttspico-utils' has no installation candidate

### ISSUE THREAD

**Issue by kevincaradant** [alexylem/jarvis#129]
Hi

Do you know what packages or sources are missing in my installation ? 
I'm under lubuntu 14.04 on Odroid C1. 
I get this error during the installation of SVOX Pico:

`E: Package 'libttspico-utils' has no installation candidate`

**Comment by alexylem** [comment]
Jarvis is not compatible with Ubuntu (because of `snowboy` pre-compiled library not available).
If you don't plan to use `snowboy` or wish to compile it yourself...
Here is the automatic installed script for PicoTTS:
```shell
if [[ "$platform" == "linux" ]]; then
            echo -e "Updating..."
            sudo apt-get -qq update || exit 1
            echo -e "Upgrading..."
            sudo apt-get -qq upgrade -y || exit 1
            echo -e "Downloading & Installing..."
            sudo apt-get install -y libttspico-utils >/dev/null || exit 1
            dialog_msg "Installation Completed"
```
However, according to:
https://doc.ubuntu-fr.org/svoxpico
>Pour installer ce logiciel, il suffit d'installer le paquet libttspico-utils.

Maybe a source missing on your apt-get?

**Comment by kevincaradant** [comment]
OK i found this solution:

1- Download  this lib: [libttspico-data](http://ftp.fr.debian.org/debian/pool/non-free/s/svox/libttspico-dat a_1.0+git20130326-3_all.deb)

2- Download this lib: [libttspico0_1.0](http://ftp.fr.debian.org/debian/pool/non-free/s/svox/libttspico0_1. 0+git20130326-3_armhf.deb)

3- Download this lib: [libttspico-utils](http://ftp.fr.debian.org/debian/pool/non-free/s/svox/libttspico-uti ls_1.0+git20130326-3_armhf.deb)

Then Install them with the following commands:

1 - sudo dpkg -i libttspico-data_1.0+git20130326-3_all.deb

2- sudo dpkg -i libttspico0_1.0+git20130326-3_armhf.deb

3- udo dpkg -i libttspico-utils_1.0+git20130326-3_armhf.deb

And voila, that works :)

**Comment by kevincaradant** [comment]
BTW: You said: snowboy is not compatible Ubuntu but it's installed on my odroid without problem ;). The package for Raspbian8.0 seems to be available for Ubuntu also.

**Comment by alexylem** [comment]
I did not say `snowboy` is not compatible with Ubuntu 😉
I said:
>Jarvis is not compatible with Ubuntu (because of snowboy pre-compiled library not available).

As I mentionned, you can still compile the `snowboy` library yourself, see #79

**Comment by kevincaradant** [comment]
Oh ok sorry I read too fast  :) Thanks

**Comment by DMike92** [comment]
Hi
Good work!
Any chance to make this running in2020 (Raspbian)? I'd love it.

**Comment by ebanDev** [comment]
It run in raspbian !

**Comment by DMike92** [comment]
Yes !
https://bugs.launchpad.net/raspbian/+bug/1835974?comments=all
