### ISSUE TITLE
Possibilité de choisir ton propre trigger avec Snowboy

### ISSUE THREAD

**Issue by alexylem** [alexylem/jarvis#13]

**Comment by physicien** [comment]
J'ai commencé à regarder cet aspect. Pour l'entraînement de nouveaux mots, il suffi de d'utiliser l'outil disponible à ceux qui ont un compte sur le site officiel de [snowboy](https://snowboy.kitt.ai/).
Cependant, je trouves les instructions pour utiliser ces nouveaux mots assez peu claires.

Pour ce qui est des mots, je pense qu'il serait intéressant d'avoir un certain nombre de commandes de base dans le cas où la connection à un serveur distant serait coupée.

**Comment by alexylem** [comment]
J'ai aussi regardé, pour les instructions ne t'inquiètes pas trop car je l'intégrerai à Jarvis pour que ca soit ultra-simple pour vous (comme le reste).
L'idée est de, après avoir renseigné le "mot clé" (ex: `JARVIS`) il vous demandera de le prononcer plusieurs fois pour *trainer* le modèle et l'enregistrer.
Je dois d'abord finir de corriger les bugs de la dernière mise à jour 😄

**Comment by physicien** [comment]
Oui, j'ai un peu essayé le générateur de mots. Tu dis trois fois le mot et le réseau neuronal apprend. Et ce qui est intéressant, c'est que tu peux entraîner le mot sur plusieurs personnes (vu que je ne suis pas un ermite).
Quand tu dis « intégrerai à Jarvis pour que ca soit ultra-simple », penses-tu à une option qui ne gère qu'un seul mot ou à une option Add/Remove pour gérer un petit nombre de mots?

J'aimerais expliquer pourquoi plusieurs mots. Pour certaines fonctions de très bas niveau, je ne pense pas qu'il soit nécessaire de passer par un serveur distant. Exemple: si je dis « Bye » dans le but de quitter Jarvis, ou encore si j'ai un thermomètre de branché à ma Pi et que je veux savoir la température qu'il fait dans la pièce.

**Comment by alexylem** [comment]
D'accord je comprends mieux, disons on va le faire par étapes:
1. Entrainement pour un seul mot (le trigger)
2. Evaluer la possibilité d'utiliser `snowboy` comme reco vocale pour les commandes, mais je vois mal comment mixer `snowboy` et google par exemple (de part leur mode de fonctionnement)

**Comment by physicien** [comment]
Je pense qu'on peut y aller simplement. Tu as un hotword pour rediriger vers le STT distant (Google, Wit ou PocketSphinx sur PC) et certaines commandes de base.

**Comment by alexylem** [comment]
Donc si je comprends bien un truc comme ca?

- `JARVIS` => Trigger pour passe en mode écoute commandes avec `google` ou `wit`
- `ALLUME BAR` => Commande rapide (écoute permanente, action directe)
- `TEMPERATURE PIECE` => Commande rapide (écoute permanente, action directe)

Par contre je pense qu'il y a un risque de ralentir la détection des mots clés si on augment le nombre de mots à détecter. A tester..

**Comment by physicien** [comment]
Tu as tout compris. Pour le risque de ralentissement, Snowboy est (selon la documentation) conçu pour comprendre plus d'un mot. La façon dont il fonctionne, c'est qu'il va faire une liste des mots dont il a les modèles et en faire une liste. Pour chaque élément de la liste, une action  associée.
Je crois que tout est dans le dosage: si tu ajoutes 100 commandes rapides, snowboy va être lent, si tu en as 10, je ne pense pas qu'on va réellement voir la différence.
J'ai rapidement regardé le code et je pense que la liste est ordonnée, il suffirait donc que le trigger soit toujours le premier mot à être vérifier pour qu'en moyenne Jarvis soit très rapide.

**Comment by alexylem** [comment]
Okay bonne idée alors, on va faire ca, mais j'aimerais qu'on sépare les 2:

- on garde ce ticket pour enregistrer le mot clé
- et on en créé un autre pour les commandes rapides avec `snowboy` (peux-tu le faire et le référencer ici? merci 👍 )

**Comment by Smanar** [comment]
Pour avoir teste ce n'est pas la performance le probleme, tu peux rajouter gaves d'instruction sans charger le processeur, tu peux aussi reduire son usage en augmentant le temps entre chaques tests.
Le probleme, enfin chez moi, c'est les faux positifs, et la par contre je suis a la recherche de la moindre infos qui ameliorerait ca .......

**Comment by alexylem** [comment]
Merci pour ton retour d'expérience, j'utilise le hotword par défaut "SNOWBOY" et pour n'instant aucun faut positif même avec la télé allumée.

**Comment by alexylem** [comment]
Implémenté. 
Suivre les instructions ici:
https://github.com/alexylem/jarvis/wiki/snowboy
>cette page est aussi référencée à la selection de `snowboy`

Je l'ai testé avec le mot clé `jarvis` et ca marche très bien 😄

**Comment by physicien** [comment]
Je confirme que ça fonctionne très bien de mon côté aussi.
Question: possible d'ajouter un `.title()` pour que le nom de mon interlocuteur électronique commence par une majuscule (voir la capture). Sinon, j'aimerais au moins savoir où c'est dans le code afin de faire cette modification purement esthétique.
![capture d ecran - 2016-07-04 - 18 50 59](https://cloud.githubusercontent.com/assets/19982063/16570672/630bb1a2-4218-11e6-84d8-ec8e21eb5408.png)

**Comment by alexylem** [comment]
Oui j'avais prévu de le faire, voir ici: #30
