### ISSUE TITLE
Micro interne sur GPIO

### ISSUE THREAD

**Issue by rouzinho** [alexylem/jarvis#130]
Bonsoir,

J'aimerai utiliser ce capteur en tant que source au sein du raspberry pi [](https://www.adafruit.com/product/1063). Pour ce qui est de l'utilisation et la programmation de celui ci, je n'ai aucun soucis. Par contre, je n'arrive pas a savoir exactement comment s'interface la prise de son avec le moteur de reconnaissance vocale. Est ce que le son est traite en continu (streaming) ou y a t'il enregistrement en .wav lorsque le mot clef est prononce ?

En tout cas, super projet ;-)

**Comment by alexylem** [comment]
Si j'ai bien compris, tu veux en savoir plus sur le fonctionnement de la prise de son de Jarvis?
Et bien ca dépend des moteurs de reconnaissance vocale que tu as choisis pour le hotword et pour les commandes:

* Hotword
 * Snowboy (conseillé): stream en continu
 * Bing/Google/PocketSphinw: fichier wav temporaire
* Commandes
 * Bing (conseillé)/Google: fichier wav temporaire

Dans le cas du fichier wav temporaire, jarvis utilise `rec` (`sox`) pour l'enregistrement avec la configuration `Default` d'ALSA (fichier `~/.asoundrc` généré lors de la configuration du micro et des enceintes dans `Settings > Audio > Mic/Speakers`)

J'espère que ca répond à ta question.

**Comment by rouzinho** [comment]
Ah super ! j'ai creuse aussi du cote de snowboy, je vais voir si'il y a pas moyen de faire un stream en continu en passant par les GPIO du raspberry. Le but ultime ca serait de coupler le capteur [https://www.adafruit.com/product/1063](url) avec un ESP8266 pour en equiper la maison...

Merci de la reponse ;-)

**Comment by Smanar** [comment]
Ca ne vient pas du type de micro, que tu passes par une interface gpio ou la prise jack c'est pareil, tout vient du code qui est derriere.

Bing et google peuvent fonctionner en stream, c'est meme etudie pour, pour avoir moins de latence, mais les modifs sont a faire dans le coeur de Jarvis pas en touchant au micro.

**Comment by rouzinho** [comment]
En fait je voulais passer par snowboy, donc faire du streaming de son. Le seul truc c'est que snowboy n'accepte que du micro usb, ce qui fait que je ne sais pas encore comment interfacer mon micro a travers les GPIO pour que snowboy le prenne en charge...

**Comment by Smanar** [comment]
Nope Snowboy ne gere pas le son, tu lui donne un buffer avec des donnees (du son) et la library te repond "oui je reconnais un mot", c'est tout. C'est toi qui gere le son.
Apres je pensais avoir vu un projet comme le tien, mais c'etait juste des micro electret (sans ampli contrairement au tiens) cable par dessus des adaptateurs Jack/USB.
Je n'en ai vu aucun avec ton micro et un raspberry, c'est plutot pour arduino.

Apres si c'est juste pr snowboy, si tu le cable sur l'entree analogique, il te suffit de remplir le buffer avec les donnees recues et de passer ton buffer a snowboy, meme pas besoin d'utiliser de librairies son. Mais apres la pratique c'est autre chose ^^. Bon courage pr creer un buffer avec des donnees recues en vrac sur une entree analogique, sachant qu'elle doivent avoir un format precis.

**Comment by dguerizec** [comment]
@rouzinho, 
J'ai l'intention de faire presque la même chose avec un ou plusieurs micros déportés, à l'aide de [ce montage](https://www.hackster.io/middleca/sending-sound-over-the-internet-f097b4).

L'idée étant de streamer l'audio en TCP ou UDP vers le raspberry.

J'imagine qu'il va falloir un démultiplexeur sur le raspberry pour sélectionner la source audio à lire pour recevoir et interpreter les commandes.

Tu as réussi à interfacer ton micro GPIO sur snowboy ou autre ?

**Comment by alexylem** [comment]
@rouzinho as-tu pu avancer sur ton projet de micro GPIO?

**Comment by wikijm** [comment]
Bonjour @rouzinho,

Pas d'évolution de ce ticket depuis le 16 novembre 2016. Est ce que je peux le clôturer ?

**Comment by rouzinho** [comment]
Bien sûr. Et désolé du silence, j'ai essayé de bricoler un truc mais sans succès.

**Comment by wikijm** [comment]
Pas de soucis. Mon but est de faire un peu de ménage dans les tickets, afin de laisser du temps à @alexylem pour continuer à développer Jarvis ;-)
