### ISSUE TITLE
Question: What are the parameters to change if you want increase or decrease the ampli of the mic ?

### ISSUE THREAD

**Issue by kevincaradant** [alexylem/jarvis#132]
Hi :)

I want to know if it's possible to change like in Windows the powerfull of the amplifier in a mic, in the aim to help Jarvis to understand your voice. What are parameters and values which  can be changed ? 

Also Do you have any idea until how much distance (betwwen you and the mic) on a raspberry pi, a mic like this: https://www.amazon.fr/dp/B007RMPV62
can work and to be 100% understood by Jarvis ? 

Thank you :D

**Comment by alexylem** [comment]
To change the mic sensitivity, go to `Settings > Audio > Sensitivity`
For cheap mic and even high end mics without noice/echo reduction, you have to be closed (less than a meter) for good recognition (or speak very loud).
If you need long distance reco, use something like [CM-1000USB](https://amzn.com/B008BS3CF8) or a microphone array (discussed here #103)
Alex.

**Comment by kevincaradant** [comment]
Thank you :)
