### ISSUE TITLE
Question: Is it possible to catch the lyric with number instead of text ? 

### ISSUE THREAD

**Issue by kevincaradant** [alexylem/jarvis#136]
If I say: 

Me when I speak: "Jarvis, mets le Volume A 10 pourcent"
Command applied: *VOLUME A ( * ) pourcent: 

I guess: `(1) = dix`. // I can't try with a mic for the moment

 Is it posssible to have (1) = 10 (integer) ? 

Thank you

**Comment by alexylem** [comment]
I have tested for you with Bing:
```
Alex: jarvis
Jarvis: Oui?
Alex: mets le volume à dit pourcent
Jarvis: Je ne comprends pas: mets le volume a dit pourcent
Alex: mets le volume à trente pourcent
Jarvis: Je ne comprends pas: mets le volume a trente pourcent
```
It's a bit risky to parse the words into digits as it may impact other commands... here "*dix*" is recognized as "*dit*".

I definitely suggest to review the way to handle this, either using `snowboy` or avoiding amounts (ex: Raise / Decrease).

**Comment by kevincaradant** [comment]
Oh my idea for the volume was not stupid, pity :(. OK, I will just say "volumeBas", "volumeNormal", "volumeHaut". I don't want say "decrease", "decrease","decrease" fifty times ^^.
Thanks and if you find a way to help it to understand numbers because the next word is "pourcent" etc. I will happy to know ;)

**Comment by alexylem** [comment]
Well you can always build a simple function to do this...
http://stackoverflow.com/questions/4062022/how-to-convert-words-to-a-number

**Comment by kevincaradant** [comment]
Yes of course Thanks  :) but the problem still the same with 'dix' and 'dis' and 'dit' ect :).
