### ISSUE TITLE
Replace Disqus with Gitter?

### ISSUE THREAD

**Issue by kevincaradant** [alexylem/jarvis#138]
Hi

As you can see @alexylem, I ask a lot questions maybe to make this more easily, you can create a gitter where me and others can ask the questions :) 

It's just a suggestion ;)

Thanks

**Comment by alexylem** [comment]
No worries you are doing it the right way.
For more discussion-oriented topics, you can also use the [Disqus thread] 😄 (http://alexylem.github.io/jarvis/disqus.html)

**Comment by kevincaradant** [comment]
yes I see it but (personnaly)  I prefer gitter with the pretty interface, markdown, and the auto notif /mail in the browser and all is centred ( left bar ) around my hobbies (Webpack, Angular in this case) via some channels.

See this example pictures, If I can make you want to try :)
![image](https://cloud.githubusercontent.com/assets/6093175/18800169/d028dc4e-81db-11e6-8c00-e42a4ff59da2.png)

**Comment by alexylem** [comment]
Mmmmh sounds interesting and looks sexy, will definitely have a look. Current advantage of Disqus is that it is very open to all, not mandatory to login/register.

**Comment by kevincaradant** [comment]
Yes you can see the topics and see the answers but if you want to speak in the tchat, indeed, you have to LogIn with Github but I think many people who try your project have Github. But I let you choose ;)

**Comment by alexylem** [comment]
Disqus is now almost not used anymore, which is not such as bad thing. Much easier to follow-up and leverage on previously answered questions on GitHub 👍
