### ISSUE TITLE
aplay: device_list:268: No sound card found...

### ISSUE THREAD

**Issue by babounx** [alexylem/jarvis#142]
### Description

Bonsoir,

Sur un RPI3, après l'installation de jarvis (git clone...) je lance le .sh qui au moment du son ne trouve aucun périphérique. (j'ai tester le RPI avec une autre distrib max2play et il y a bien un peripherique son fonctionnel)
Le message en mode debug est le suivant.
Une piste ?

Merci
### Résultat

```
Selection of the speaker device
aplay: device_list:268: aucune carte son n'a été trouvée...
Indicate the card # to use [0-9]:
```

**Comment by alexylem** [comment]
Sur quelle distrib es-tu? D'après les minimum requirements, il te faut [Raspbian Jessie (full)](https://downloads.raspberrypi.org/raspbian_latest).

**Comment by babounx** [comment]
Je suis en Jessi Full récupérer depuis le site de raspbian : https://downloads.raspberrypi.org/raspbian_latest (2016-05-27-raspbian-jessie).

pour ce qui est du RPI j'ai celui la : https://www.amazon.fr/gp/product/B01CCOXV34/ref=oh_aui_detailpage_o02_s00?ie=UTF8&psc=1  RPI3 B

**Comment by alexylem** [comment]
Très étonnant, tu as quoi comme enceinte? branché ou?

**Comment by babounx** [comment]
J'ai des enceintes USB. https://www.amazon.fr/gp/product/B00544XKK4/ref=oh_aui_detailpage_o02_s00?ie=UTF8&psc=1
Cela fonctionne parfaitement avec la distrib Max2play. Sur mon RPI2 aussi pas de probleme pour voir ces hp, jarvis marche nikel.

**Comment by alexylem** [comment]
T'es sûr qu'elles sont USB? d'après la fiche amazon:
>Entrée audio 3,5 mm standard pour connecter votre ordinateur portable
Tu les as branchées sur le connecteur Jack?

**Comment by alexylem** [comment]
Je te conseille aussi d'aller faire un petit tour dans:
```shell
$> sudo raspi-config
```
![image](https://cloud.githubusercontent.com/assets/11017174/18814721/21aaad18-831c-11e6-8443-90bedc8187fd.png)

**Comment by alexylem** [comment]
Aussi d'après:
https://www.raspberrypi.org/forums/viewtopic.php?f=28&t=14389

Essaye:
```
sudo aplay -l 
```

Pour voir si ca affiche quelque-chose

**Comment by babounx** [comment]
Pardon oui, alimenté par USB mais connecté sur la prise Jack.
J'ai modifier les parametres via le rpi-config.

root@jarvis:/home/babounx# raspi-config
numid=3,iface=MIXER,name='PCM Playback Route'
  ; type=INTEGER,access=rw------,values=1,min=0,max=2,step=0
  : values=1
root@jarvis:/home/babounx# aplay -l
**** Liste des Périphériques Matériels PLAYBACK ****
carte 0: ALSA [bcm2835 ALSA], périphérique 0: bcm2835 ALSA [bcm2835 ALSA]
  Sous-périphériques: 8/8
  Sous-périphérique #0: subdevice #0
  Sous-périphérique #1: subdevice #1
  Sous-périphérique #2: subdevice #2
  Sous-périphérique #3: subdevice #3
  Sous-périphérique #4: subdevice #4
  Sous-périphérique #5: subdevice #5
  Sous-périphérique #6: subdevice #6
  Sous-périphérique #7: subdevice #7
carte 0: ALSA [bcm2835 ALSA], périphérique 1: bcm2835 ALSA [bcm2835 IEC958/HDMI]
  Sous-périphériques: 1/1
  Sous-périphérique #0: subdevice #0


Je lance Jarvis et ??? bha rien :/

**Comment by babounx** [comment]
Je teste la sortie : sudo /opt/vc/src/hello_pi/hello_audio/hello_audio.bin 
Outputting audio to analogue

Ca marche nikel.
Je test avec l'utilisateur pi et la ça fonctionne... :/
J'imagine qu'il y a des droits à vérifier pour l'utilisateur.

**Comment by alexylem** [comment]
Heu... tu m'expliques pourquoi t'es connecté en root? (vaut mieux utiliser sudo pour éviter les bêtises...)
Bon donc avec root tu arrives à voir les périphériques, tu as donc le même problème de sur ce thread:
https://www.raspberrypi.org/forums/viewtopic.php?f=28&t=14389

La solution proposée est de:
```shell
sudo addgroup pi audio
```

Puis de te relogger.

**Comment by babounx** [comment]
En fait, j'ai un autre utilisateur que PI et je pense après des tests que cela viens de la.
J'ai ajouter mon user au groupe audio. Ca ne change rien.
Je vais faire une comparaison des droits utilisateurs et voir ce qui peut marcher avec l'utilisateur pi et pas avec un autre.

J'ajouterais le résultat de mes recherches dans le ticket ;).
Pour des users lambda je pense qu'il faut utiliser l'utilisateur pi. pour des avancés, un autres utilisateurs doit être paramétrés.

Dès que j'ai trouvé, je te metterais les infos pour éventuellements que ton script de start puisse faire un check des groups nécessaires ;).

**Comment by babounx** [comment]
Je n'ai pas peur des bétises ;) je suis admin linux depuis + de 5 ans responsable de prod :)
Si je peux contribuer au projet, ce sera avec plaisir que je partagerais.

**Comment by alexylem** [comment]
Ah super, ok ca va alors 😄  non je demande parce que Jarvis s'adresse aussi à des novices... c'est d'ailleurs pour ca que j'ai déjà rajouté un check pour éviter de lancer Jarvis en root...
Merci de partager tes découvertes, c'est pas du tout lié à Jarvis mais si ca peut servir à d'autres, tant mieux 👍

**Comment by babounx** [comment]
Tu as un thread spécial ou je pourrais apporter ma pierre ?
Je ne connais que très peu le language que tu utilise (faut que je m'y mette mais je suis plus côté system / automatisation), côté system / script bash je me debrouille :)

J'aime l'idée de ton projet car par rapport a d'autres il est simple. :)

**Comment by alexylem** [comment]
Merci @babounx le langage que j'utilise est le `bash` tout simplement 😄 
Sauf pour `snowboy` ou il y a un tout petit peut de `python`, mais oui la phylosophie du projet est que ca soit simple pour l'utilisateur (avec le moins de dépendances possible).
Lorsque je peux ajouter dans le code des checks pour simplifier encore plus l'installation et la résolution de problème, je le fais avec plaisir. Donc je garde le ticket ouvert pour ca 👍

**Comment by babounx** [comment]
Bon: 
Résolution du problème : aplay: device_list:268: No sound card found
l'utilisateur courant doit faire parti du groupe audio pour lister les devices.

un 'cat /etc/group | grep $USER |grep audio' devrait retourner une valeur (si tu marche avec des 1 ou 0 un |wc-l t'aidera :p)

Cependant, malgré l'ajout a l'audio ça ne marche pas encore. Je peux lister les alsa mais pas jouer avec du son :/
Je continue

**Comment by alexylem** [comment]
Pour jouer le son, il te faut peut-être définir la sortie pas défaut dans `~/.asoundrc`. Ce que Jarvis fait automatiquement à l'installation / configuration.
Essayes peut-être de lancer Jarvis et d'aller dans `Settings > Audio > Speaker` pour sélectionner le device parmi la liste et le tester.

**Comment by alexylem** [comment]
Une fois que tu l'auras complètement résolu, j'ajouterai un check de l'appartenance de l'utilisateur courant au groupe `audio`.

**Comment by babounx** [comment]
Je fais un retour dès que j'ai complètement trouvé.

**Comment by alexylem** [comment]
@babounx as-tu pu avancer sur ce sujet?

**Comment by alexylem** [comment]
J'ai rajouté un check au démarrage que l'utilisateur appartient bien au groupe `audio` et propose de le rajouter automatiquement.

**Comment by babounx** [comment]
Hello Alex, Désolé pour le manque d'info.
Je me suis penché sur un autre projet (multiroom audio) que j'ai terminé chez moi et qui utilise a peu pres les mêmes technos.
Je te confirme qu'il faut bien que l'user fasse parti du groupe audio (j'ai eu le mm probleme avec www-data qui lance mes scripts).

Ayant fini mon projet de multiroom je vais plus me lancer dans jarvis. J'espère pouvoir te faire des remontée utiles.

A bientot.

Bab
