### ISSUE TITLE
ERROR: Access denied due to invalid subscription key. Make sure to provide a valid key for an active subscription.

### ISSUE THREAD

**Issue by MarcProv** [alexylem/jarvis#145]
### Description

Bonjour Alex,

Tout d'abord bravo pour ce beau travail.

Tout fonctionne à l'exception que le service STT ici associé à Bing me répond que la clé est pas bonne ou expiré. Alors que sur le site de les deux clé que j'ai généré sont active et non expirér.

Comment faire pour déverminé ce processu?

voici le résultat de la console après avoir lancé Jarvis en mode troubleshooting
Le  "trigger word" est julie

### Résultat
```
pi@io:~/jarvis $ ./jarvis.sh
Checking for updates...[Up-to-date]

------------ Config ------------
system               Linux 4.1.19-v7+ armv7l 
os                   "Raspbian GNU/Linux 8 (jessie)" 
language             fr_FR 
play_hw              hw:0,0 
rec_hw               hw:1,0 
speaker              ALSA 
microphone           Logitech, Inc. Webcam C270 
trigger_stt          snowboy 
command_stt          bing 
tts_engine           google 
conversation_mode    true 
--------------------------------

DEBUG: program_startup hook
julie: Bonjour
julie: Waiting to hear 'julie'
Marc: (listening...)
DEBUG: models=julie,snowboy
ALSA lib confmisc.c:1286:(snd_func_refer) Unable to find definition 'cards.bcm2835.pcm.front.0:CARD=0'
ALSA lib conf.c:4259:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:4738:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM front
ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.rear
ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.center_lfe
ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.side
ALSA lib confmisc.c:1286:(snd_func_refer) Unable to find definition 'cards.bcm2835.pcm.surround51.0:CARD=0'
ALSA lib conf.c:4259:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:4738:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM surround21
ALSA lib confmisc.c:1286:(snd_func_refer) Unable to find definition 'cards.bcm2835.pcm.surround51.0:CARD=0'
ALSA lib conf.c:4259:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:4738:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM surround21
ALSA lib confmisc.c:1286:(snd_func_refer) Unable to find definition 'cards.bcm2835.pcm.surround40.0:CARD=0'
ALSA lib conf.c:4259:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:4738:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM surround40
ALSA lib confmisc.c:1286:(snd_func_refer) Unable to find definition 'cards.bcm2835.pcm.surround51.0:CARD=0'
ALSA lib conf.c:4259:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:4738:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM surround41
ALSA lib confmisc.c:1286:(snd_func_refer) Unable to find definition 'cards.bcm2835.pcm.surround51.0:CARD=0'
ALSA lib conf.c:4259:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:4738:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM surround50
ALSA lib confmisc.c:1286:(snd_func_refer) Unable to find definition 'cards.bcm2835.pcm.surround51.0:CARD=0'
ALSA lib conf.c:4259:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:4738:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM surround51
ALSA lib confmisc.c:1286:(snd_func_refer) Unable to find definition 'cards.bcm2835.pcm.surround71.0:CARD=0'
ALSA lib conf.c:4259:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:4738:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM surround71
ALSA lib confmisc.c:1286:(snd_func_refer) Unable to find definition 'cards.bcm2835.pcm.iec958.0:CARD=0,AES0=4,AES1=130,AES2=0,AES3=2'
ALSA lib conf.c:4259:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:4738:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM iec958
ALSA lib confmisc.c:1286:(snd_func_refer) Unable to find definition 'cards.bcm2835.pcm.iec958.0:CARD=0,AES0=4,AES1=130,AES2=0,AES3=2'
ALSA lib conf.c:4259:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:4738:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM spdif
ALSA lib confmisc.c:1286:(snd_func_refer) Unable to find definition 'cards.bcm2835.pcm.iec958.0:CARD=0,AES0=4,AES1=130,AES2=0,AES3=2'
ALSA lib conf.c:4259:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:4738:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM spdif
ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.hdmi
ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.hdmi
ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.modem
ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.modem
ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.phoneline
ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.phoneline
ALSA lib pcm_dmix.c:1022:(snd_pcm_dmix_open) unable to open slave
Cannot connect to server socket err = No such file or directory
Cannot connect to server request channel
jack server is not running or cannot be started
INFO:snowboy:Silence
INFO:snowboy:Keyword 1 detected at time: 2016-09-25 09:14:40
DEBUG: modelid=0
julie
DEBUG: entering_cmd hook
julie: OUI?
Marc: (listening...)
./timeout.sh 10 rec -V1 -q -r 16000 -c 1 -b 16 -e signed-integer --endian little jarvis-record.wav silence 1 0.1 1% 1 0.5 1% trim 0 10
DEBUG: speech duration was 03 (10 = 1 sec)
DEBUG: token missing or expired
DEBUG: json={ "statusCode": 401, "message": "Access denied due to invalid subscription key. Make sure to provide a valid key for an active subscription." }
ERROR: Access denied due to invalid subscription key. Make sure to provide a valid key for an active subscription.
?(listening...)
./timeout.sh 10 rec -V1 -q -r 16000 -c 1 -b 16 -e signed-integer --endian little jarvis-record.wav silence 1 0.1 1% 1 0.5 1% trim 0 10
DEBUG: speech duration was  (10 = 1 sec)
DEBUG: timeout, end of conversation
^CDEBUG: program exit handler
DEBUG: program_exit hook
pi@io:~/jarvis $ ^C

```

**Comment by alexylem** [comment]
Juste pour être sûr, ta clé a bien 32 caractères?

**Comment by Smanar** [comment]
Je viens de voir un probleme qui a surement du provoquer ce soucis (j'ai fais la meme erreur de mon cote)
Dans ton wiki https://github.com/alexylem/jarvis/wiki/bing
Sur l'image on voit ecrit "Speaker recognition preview" et c'est "Bing speech preview" qu'on devrait voir.
C'est l'api pour la reconnaissance de la personne qui parle qui est sur tes screenshoot.

**Comment by jbellue** [comment]
J'ai le même problème. On dirait que le la génération du token par oxford-speech.cloudapp.net ne fonctionne pas : quand je lance
`curl -v -X POST "https://oxford-speech.cloudapp.net/token/issueToken" -H "Content-type: application/x-www-form-urlencoded" -d 'grant_type=client_credentials&client_id=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx&client_secret=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx&scope=https://speech.platform.bing.com'`
(en remplaçant les X par une des clefs de Bing Speech - Preview), je reçois
`{ "statusCode": 401, "message": "Access denied due to invalid subscription key. Make sure to provide a valid key for an active subscription." }` comme réponse.

**Comment by MarcProv** [comment]
Oui les 2 clés essayées ont 32 caractères et c'est bien pour API  "Bing Speech Preview".

merci de ces interractions rapides!

**Comment by alexylem** [comment]
Pourtant ca marche très bien pour moi (testé à l'instant)...

**Comment by alexylem** [comment]
Vous pouvez coller une copie d'écran comme celle-ci?
![image](https://cloud.githubusercontent.com/assets/11017174/18817401/91281fd4-835f-11e6-829f-c564d973ad70.png)
Avec un affichage du Quota

**Comment by jbellue** [comment]
J'ai voulu voir si ma clé était quand même atteinte chez Bing, en cliquant sur 'Show quota' et la requête échoue : `Failed to get Quota Info: error:` . J'ai l'impression que leurs serveurs sont dans les choux.
Du coup, j'ai essayé d'annuler ma souscription, et j'ai eu une belle erreur JS: `Failed to cancel the subscription,error:Internal Server Error`.
Leurs serveurs sont bien à la ramasse !
![capture](https://cloud.githubusercontent.com/assets/1430767/18817415/7aaa5414-8357-11e6-8e7b-ece8f98e9d3b.JPG)
Je pense qu'il suffit juste d'attendre un petit peu pour que leurs serveurs se réveillents...

**Comment by alexylem** [comment]
J'avoue j'arrive pas non plus à afficher le quota...

**Comment by alexylem** [comment]
Petite question @jbellue, ca a déjà marché pour toi auparavant? (juste pour confirmer l'histoire du *serveur dans les choux*)

**Comment by jbellue** [comment]
J'ai créé mon compte aujourd'hui, désolé. Mais j'ai eu des tas d'erreurs différentes sur le site (principalement des machins qui timeout), du coup je m'inquiète pas trop !

**Comment by alexylem** [comment]
Ce qui est bizarre c'est que ca fonctionne pour moi (et surement pour d'autres sinon ca râlerait 😄 ).
Peut-être que ta clé fraichement créée n'a pas pu être encore répliquée sur tous leurs serveurs...
Affaire à suivre...

**Comment by MarcProv** [comment]
Bon soir messieur,
J'ai le même résultat que jbellue lors que je demande le "Quota" ce soir ce matin, il m'informais  correctement de 0 requête Voir la capture jointe.

![capture du 2016-09-25 20-13-50](https://cloud.githubusercontent.com/assets/22428903/18819551/9e218a6c-8360-11e6-958d-821ae40a4246.png)

Comme moyen de contournement pour l'instant.

j'ai constaté que le choix de "google speech" pour reconnaissance des commandes a disparu de l'installateur. J'ai une clé google speech. Comment puis-je ré-affecter google speech pour la reconnaissance des commandes?

En attendant de voir si l'hypothèse des serveurs de Bing se corrige.

**Comment by Smanar** [comment]
Le fonctionnement via l'api de "Google speech" va devenir obsolette, remplacée par "Cloud Speech API". Et celle ci te demande systematiquement des informations bancaires pour fonctionner gratuitement et elle devenue tres limitees (240 appels /mois de maxi 15 secondes chacun) du coup elle risque (si c'est pas deja fait justement) de sauter.
Apres si tu as d'autres infos que celles la, ca m'interesse aussi.

**Comment by alexylem** [comment]
Oui les gars je confirme j'ai bien fait sauter `google` pour les raisons citées ci-dessus. Je peux le remettre temporairement sachant toutefois que c'est obsolète.

**Comment by jbellue** [comment]
J'ai tenté de recréer un compte chez bing, et la création du compte s'est faite sans soucis, mais j'ai le même problème ensuite : 
`Access denied due to invalid subscription key. Make sure to provide a valid key for an active subscription.`
Est-ce que quelqu'un peut essayer de se créer un nouveau compte chez MS pour essayer ?

**Comment by jbellue** [comment]
bing speech API a changé le mode de création des tokens :
https://www.microsoft.com/cognitive-services/en-us/speech-api/documentation/API-Reference-REST/BingVoiceRecognition#authenticate-the-api-call
Un coup d'oeil rapide à leur doc ne mentionne rien quant à la durée de validité du token... J'ai une version qui fonctionne plus ou moins, en re-générant le token avant chaque requête... Pas idéal. Des idées ?

**Comment by agustinscaz** [comment]
Same issue here...

**Comment by alexylem** [comment]
My Bing still works...
```
Alex: (listening...)
./timeout.sh 10 rec -V1 -q -r 16000 -c 1 -b 16 -e signed-integer --endian little jarvis-record.wav silence 1 0.1 1% 1 0.5 1% trim 0 10
DEBUG: speech duration was 05 (10 = 1 sec)
DEBUG: curl https://speech.platform.bing.com/recognize/query?version=3.0&requestid=D547AC04-62AA-4768-91E2-034C51BAF694&appid=D4D52672-91D7-4C74-8AD8-42B1D98141A5&format=json&locale=en-GB&device.os=osx&scenarios=ulm&instanceid=E043E4FE-51EF-4B74-8133-B728C4FEA8AA
DEBUG: json={"version":"3.0","header":{"status":"success","scenario":"ulm","name":"bonjour","lexical":"bonjour","properties":{"requestid":"9e8c49dd-eb66-4842-9a73-ef276c474bbc","HIGHCONF":"1"}},"results":[{"scenario":"ulm","name":"bonjour","lexical":"bonjour","confidence":"0.943728","properties":{"HIGHCONF":"1"}}]}
bonjour
$> say "Bonjour $username"
Jarvis: Bonjour Alex
```
Can someone share a key that doesn't work so that I can try the new token creation mechanism and see if it fixes the issue?

**Comment by agustinscaz** [comment]
Hi!
Here you got mine: 9499cdeb1e0c4e499c8e90f1e6e3e0cb

**Comment by alexylem** [comment]
@agustinscaz ok doesn't work with me either. I'm now implementing the new token mechanism provided by @jbellue to see if it helps.
@jbellue currently a validity period is implemented in Jarvis to avoid unnecessary calls. For the new tokens, I can so some kind of loop to see when it stops working... Any piece of code to share with me?

**Comment by alexylem** [comment]
WORKS 😄

**Comment by alexylem** [comment]
Please update your Jarvis the token generation should work now.
No expiration date is sent, so it's always expired. Anyone volunteers to test how long it works before expiration?

**Comment by alexylem** [comment]
it seems that I can reuse the token, so I put the previous expiration duration of 10 mins, please guys update and see if it lasts that long

**Comment by agustinscaz** [comment]
It works!

Thanks Alex!

**Comment by YuukanOO** [comment]
De mon côté, avec Bing, j'ai systématiquement cette erreur:

```
DEBUG: json={"version":"3.0","header":{"status":"error","properties":{"requestid":"80ca150e-0dc7-4b69-961a-9a87ab4d4d3a","NOSPEECH":"1"}}}
```

J'ai sûrement oublié un truc, sachant que ma clé d'API vient d'être régénérée et je que je suis sûr d'être sur le bon service, ça fonctionnait tout à l'heure.

**Comment by alexylem** [comment]
Ok I close the ticket now, please re-open if you face issues with the certification expiration

**Comment by alexylem** [comment]
@YuukanOO c'est lié à ton micro, voir #118

**Comment by MarcProv** [comment]
Bonjour Alexy, Je confirme cela fonctionne aussi pour moi.

Je passe aux étapes suivantes.

J'aurais quelques questions, puis-je me permettre de te les posé?

Encore merci pour cette réactivité/

**Comment by alexylem** [comment]
@MarcProv Si tu rencontres d'autres problèmes, tu peux ouvrir d'autres tickets. Si c'est juste pour discuter, c'est [ici](http://alexylem.github.io/jarvis/disqus.html).

**Comment by D-Kalck** [comment]
J'ai le même problème, j'ai le message d'erreur :
> ERROR: Access denied due to invalid subscription key. Make sure to provide a valid key for an active subscription.
Quand je vais dans ma console Cognitive Services j'ai ça :
> Bing Speech API
> 
> Convert speech to text and back again to understand user intent
> 
> 5,000 transactions, 20 per minute for each feature.
> 
> **State: Expired. Your 30 day trial experience has expired.**
> 
> Please create a free Azure Account to get free access to Cognitive Services or explore purchase options for production use.

J'ai déjà eu le soucis, ça a remarché le lendemain, là, ça fait quelques jours que ça dure. Et pour créer un compte Azure gratuit, il faut insérer les informations de sa carte bancaire.

**Comment by D-Kalck** [comment]
Personne d'autre a le même soucis ?

**Comment by Oliv4945** [comment]
Pas de mon côté, tu peux créer un autre compte avec un email bidon sinon

**Comment by Legend23** [comment]
Même soucis!!  Sur microsoft azure, pour souscrire au service Bing Speech API, il est obligatoire de rentrer les informations d'une carte de crédit! 
Alors que je me rappelle pas l'avoir fait la première fois.

**Comment by alasta** [comment]
Même pb sur MS, passé les 30j d'essai il faut completer des infos comme car de crédit, identité ...

**Comment by D-Kalck** [comment]
J'ai créé un autre compte, et maintenant, pareil ma clé est expirée.

**Comment by Misterlouf97** [comment]
Bonjour, 
j'ai rencontré un problème lors de la reconnaissance vocale sur jarvis. Lorsque que je dis Jarvis il reconnait ma voix parfaitement. Mais lorsque je dit Bonjour un message d'erreur m'affiche : "Access denied due to invalid subscription key. Make sure to provide a valid key for an active subscription".
Pourtant,je me suis bien inscrit sur le site microsoft pour bénéficier du code API.

Merci de votre aide

**Comment by D-Kalck** [comment]
Sur le site de Microsoft, quel est le statut de ta clé ?

**Comment by onechok** [comment]
bonjour même problème
ERROR: Access denied due to invalid subscription key. Make sure to provide a valid key for an active subscription.

**Comment by Intelartifice** [comment]
Bonjour,
Idem même problème:

ERROR: Access denied due to invalid subscription key. Make sure to provide a valid key for an active subscription.
Quelqu'un aurait-il une solution ?

**Comment by coujma** [comment]
j'ai le même problème avec une installation toute propre 
la clef bing ne fonctionne pas 
quelqu'un a t'il trouve la solution

**Comment by ebanDev** [comment]
Quelle est la longeur de ta clé ?

**Comment by coujma** [comment]
Bonjour mes clefs font 32 caracteres 

 

De : Eban <notifications@github.com> 
Envoyé : samedi 25 janvier 2020 20:58
À : alexylem/jarvis <jarvis@noreply.github.com>
Cc : coujma <coujma@free.fr>; Comment <comment@noreply.github.com>
Objet : Re: [alexylem/jarvis] ERROR: Access denied due to invalid subscription key. Make sure to provide a valid key for an active subscription. (#145)

 

Quelle est la longeur de ta clé ?

**Comment by coujma** [comment]
Bonjour 

Je suis passe sur la version beta du coup ma clef Bing marche..

 

Par contre ca fonctionne en mode debug il reconnait mes commandes a 80%

Mais si je passe en mode « normal » il ne reconnait que le mot magique ..

 

Et après tombe en time OUT 

 

Je sais pas trop vers ou chercher 

 

Mon jarvis est installé sur un raspberry 4 sur un carte SD rien d’autre ne tourne dessus 

 

 

 

De : Eban <notifications@github.com> 
Envoyé : samedi 25 janvier 2020 20:58
À : alexylem/jarvis <jarvis@noreply.github.com>
Cc : coujma <coujma@free.fr>; Comment <comment@noreply.github.com>
Objet : Re: [alexylem/jarvis] ERROR: Access denied due to invalid subscription key. Make sure to provide a valid key for an active subscription. (#145)

 

Quelle est la longeur de ta clé ?
