### ISSUE TITLE
WebStore pour les plugins de Jarvis

### ISSUE THREAD

**Issue by alexylem** [alexylem/jarvis#146]
Bon le store est en place et fonctionne. Mais avec la structure actuelle je vois les limitations suivantes:

* 👎  Chaque publication / modification entraine une mise à jour pour toutes les installations de Jarvis
* 👎  Pas possible de connaître le nombre d'installation de chaque plugin
* 👎  Pas possible de noter ni de commenter les plugins
* 👎  Chaque publication nécessite un merge de la part de l'un des contributeurs du repo
* 👎  Les utilisateurs de Jarvis vont logiquement, s'ils rencontrent des problèmes avec un plugin, créer des issues sur le repo de Jarvis. Pas possible pour l'auteur d'un plugin de tracker les issues relatifs a son propre plugin
* 👎  Le fait que le store soit intégré à Jarvis augmente la taille du repo et donc le temps nécessaire à son clonage (installation)
* 👎  Il est nécessaire de forker tout le repo pour soumettre un nouveau plugin, il y a donc un risque de modifier le core de Jarvis lors d'un pull request

Je propose comme nouvelle architecture un **décentralisation complète du store**:

1. **Chaque plugin est en fait un repo à part**, qui appartient à son auteur initial, forké depuis un repo "Modèle de Plugin Jarvis"
2. La publication sur le store est en fait un **enregistrement du plugin** par son auteur via un formulaire web, y indiquant l'URL du repo
3. Le store devient donc un annuaire de plugin que l'on peut noter et commenter. Un bouton sur chaque plugin permettra aux visiteur de logger un ticket directement sur le repo du plugin

Voici les avantages par rapport à la structure d'aujourd'hui:

* 👍  Séparation du core de Jarvis et des plugins, le Core restera ainsi léger et protégé de modifications malencontreuses
* 👍  Chaque publication/modification de plugin n'engendrera de mise à jour pour les utilisateurs
* 👍  Le nb d'installation d'un plugin sera trackée grâce au nombre de clone de son repo
* 👍  Les plugins pourront être notés / commentés via le site web du store
* 👍  Il n'y aura plus de merge nécessaire, seule la soumission sur le store devra être validée (le plugin pourra toujours être testé avant d'être ajouté au store)
* 👍  Les problèmes liés aux plugins pourront être remontés via des issues sur les repos correspondants

Voici cependant les points à noter:

* Hébergement nécessaire (j'ai déjà le domaine domotiquefacile.fr que je pourrais utiliser, les dons serviront à participer au financement) - Jarvis et le store resteront gratuits
* Création du site (dans mes compétences: `bootstrap/php`)
* Il sera nécessaire de développer des web-services pour interroger le store depuis Jarvis et cela ralentira le `browse/search` du Store depuis l'application

Comme Jarvis vous appartient autant qu'à moi, j'ai besoin de votre opinion avant de me lancer.
**Merci d'ajouter votre réaction 👍  ou 👎  sur ce post** et commenter ci-dessous si nécessaire.

**Comment by Michelgard** [comment]
Bonjour, 
De mon coté je suis pour. Dans la version actuelle je vais essayer d'ajouter les commandes que j'ai faite pour ma domotique personnelle.
Merci Alex

**Comment by alexylem** [comment]
N'hésitez pas à continuer de faire des plugins, je vous aiderai à les adapter et je me chargerai de les enregistrer moi même sur le nouveau store en votre nom quand il sera prêt.

**Comment by YuukanOO** [comment]
Et en utilisant des [submodules](https://git-scm.com/docs/git-submodule) pour les plugins ? Comme ça chaque auteur crée son plugin sur son repo personnel (comme tu le précises) avec les tickets associés . Les contributeurs de jarvis ajoutent les submodules au repo jarvis actuel quand ils estiment qu'ils sont suffisamment stables pour apparaître dans le store. Du coup, plus besoin d'interface web.

L'autre avantage c'est que si une personne crée un plugin perso il peut très facilement ajouté un submodule en local au répertoire de jarvis sans interférer avec son développement.

A l'installation, un simple `git submodule init && git submodule update` et tout est récupéré.

**Comment by alexylem** [comment]
@YuukanOO ton idée m'intéresse beaucoup, mais le sub-module a besoin d'être intégré au repo de Jarvis à un moment donné, donc il y a donc un pull request? C'est ce que j'aurais aimé éviter. Par contre on peut combiner les deux:

1. Chaque auteur crée sont plugin sur son repo personnel
2. L'auteur le publie sur le web store via un formulaire (ainsi pas de pull request sur Jarvis)
3. Une fois validé, le plugin est dispo sur le store et depuis Jarvis (APIs)
4. A l'installation, je clone le repo en tant que sous-module, donc je peux gérer les mises à jours automatiquement sans qu'il soit intégré au repo de Jarvis

J'ai déjà commencé à construire le Web Store (9 pour - 0 contre), j'avais presque fini avec Wordpress mais ce n'était pas parfait, donc je bascule sur Drupal. Je tenterai la solution custo en dernier recours.

**Comment by YuukanOO** [comment]
Il y'a bien un PR oui. Après, si tu crées un repo jarvis-store que tu met en ss module dans jarvis, tu sépares proprement les deux et tu gères les PR pour le store (ce qui te sers de validation des plugins). 0 infra à mettre en place.

**Comment by alexylem** [comment]
@YuukanOO oui mais j'aurais qd même un pull request et donc une mise à jour pour tous les utilisateurs de Jarvis à chaque arrivée de nouveau plugin 😞  De plus, pour la recherche intégrée à Jarvis il me faut le détail (description, mots clés...) de tous les plugins, je ne me vois pas chercher en live dans tous les repos 1 à 1, il me faut bien un annuaire centralisé.

**@All**, j'ai bien avancé sur le WebStore, Drupal a bien tenu ses promesses. Je l'ai fait en anglais cette fois. Allez un petit aperçu en attendant l'ouverture des portes:
![image](https://cloud.githubusercontent.com/assets/11017174/19047944/5e9c5fe4-89a4-11e6-80ca-701a139509e1.png)

Il me faut encore finir l'intégration avec Jarvis (pour la recherche, le browse, l'installation...), mais je ne devrais plus en avoir pour très longtemps.

**Comment by alexylem** [comment]
J'avance. Jarvis sait maintenant récupérer les informations du webstore et permet d'y naviguer directement depuis l'application.

**Version sur le store**
![image](https://cloud.githubusercontent.com/assets/11017174/19134361/e07cccbe-8b5d-11e6-8c88-4bc6ad82a96c.png)

**Depuis Jarvis**
![image](https://cloud.githubusercontent.com/assets/11017174/19134377/02cc0154-8b5e-11e6-8c90-ba7cf430a6eb.png)
![image](https://cloud.githubusercontent.com/assets/11017174/19134379/08f01d4a-8b5e-11e6-8adc-fc666ae0b1c8.png)
> Les autres catégories ne sont pas affichées car elles sont vides

![image](https://cloud.githubusercontent.com/assets/11017174/19134382/0ddc9d06-8b5e-11e6-81f8-264d6411b127.png)
![image](https://cloud.githubusercontent.com/assets/11017174/19134387/152a2452-8b5e-11e6-8be2-1b739ab14036.png)

**Comment by alexylem** [comment]
J'ai fini l'intégration côté Jarvis. On peut y chercher et installer des plugins.
J'ai aussi rajouté l'option `-p` pour l'installer directement depuis le terminal:

**Aperçu d'un plugin depuis le WebStore**
![image](https://cloud.githubusercontent.com/assets/11017174/19204135/53e27504-8cdb-11e6-9aec-aac629f4ddec.png)

**Installation depuis le terminal**
```shell
$> ./jarvis.sh -p https://github.com/alexylem/jarvis-time
Cloning into 'jarvis-time'...
remote: Counting objects: 12, done.
remote: Compressing objects: 100% (11/11), done.
remote: Total 12 (delta 0), reused 12 (delta 0), pack-reused 0
Unpacking objects: 100% (12/12), done.
Checking connectivity... done.
$> 
```

**Installation depuis le Store intégré**
![image](https://cloud.githubusercontent.com/assets/11017174/19204234/e6db53e4-8cdb-11e6-9218-ad9a2c75f359.png)
![image](https://cloud.githubusercontent.com/assets/11017174/19204232/e1bb5a26-8cdb-11e6-9ce2-601a81ed40bf.png)

Par contre il faut légèrement revoir vos plugins car j'ai changé la structure pour permettre des plugins multi-langues:
![image](https://cloud.githubusercontent.com/assets/11017174/19204273/32f4cb16-8cdc-11e6-9d85-63fb7084bb1e.png)

Je vais donc cloner vos repos et vous faire des pull-requests avec la nouvelle structure. Il faudra ensuite les publier sur le store (ca je peux aussi le faire pour vous mais tant qu'à faire je préfère que ce soit fait en votre nom). Le store actuel (`jarvis/store/all`) va disparaître. Les plugins sont désormais installés dans `jarvis/plugins/`.

**Comment by alexylem** [comment]
J'ai parlé trop vite. Je ne peux pas vous faire des pull-requests car vos repos sont des forks de `jarvis` et non pas du template de plugin `jarvis-plugin`. En gros les plugins que vous avez déjà soumis sont intégrés à votre fork de `jarvis` et donc ne peuvent pas être publiés sur le store tels quels.
Je vais donc vous contacter un par un pour vous proposer soit de refaire vous même un nouveau repo dédié à votre plugin, ou alors m'autoriser à recréer votre plugin sur mon compte Github et le publier pour vous.
On va y arriver!

**Comment by alexylem** [comment]
Plus que 2 plugins à migrer et je pousserai la mise à jour de Jarvis pour l'intégration avec le nouveau WebStore.
Je viens de publier en prime un plugin pour checker les emails non lus.
http://domotiquefacile.fr/jarvis
![image](https://cloud.githubusercontent.com/assets/11017174/19248698/d19e727e-8f31-11e6-9be6-879b7da55acf.png)

**Comment by alexylem** [comment]
Wiki mis à jour:
https://github.com/alexylem/jarvis/wiki/store
