### ISSUE TITLE
Jarvis n'interprète pas les caractères spéciaux "\*" dans les commandes

### ISSUE THREAD

**Issue by Benfosse** [alexylem/jarvis#147]
Bonjour,
J'ai fini de développé un module de contrôle des **ampoules MI-Light** et avant de le mettre sur le store je souhaite implémenter la gestion de l'IP car celle-ci sera propre à chacun.
J'ai donc mis la variable suivant dans mon fichier **config : adresse_ip="192.168.1.xx"** #Rentrez l'ip de votre ampoule (Pour le moment j'ai rentrée la mienne pour le bon fonctionnement du plugin)
et je l’appelle dans mes ficher avec **$adresse_ip**.
Pourtant lorsque j'execute la commande celle-ci me renvoie une erreur ( qui n'est pas là quand je rentre mon IP directe), j'ai l'impression qu'il ne trouve pas la variable... 
Une idée.. ?

**Comment by alexylem** [comment]
Assures-toi que ta version de Jarvis est à jour, j'ai corrigé ce problème il y a quelques jours.
Ensuite, il est primordial de préfixer ses variables pour éviter les conflits avec Jarvis:

**config.sh**
```
milight_ip_address="XX.XX.XX.XX" # variable names in english please :)
```

Sinon tu peux me filer l'URL de ton plugin que j'y jette un oeil?
Alex.

**Comment by Benfosse** [comment]
J'ai essayé la modification mais pas de changements :/
Je te laisse y jeter un coup d'oeil : 
https://github.com/Benfosse/Jarvis

**Comment by alexylem** [comment]
Ok c'est tout à fait normal car tu exécute un script externe hors contexte...
En plus tu t'es pris la tête un peu pour rien 😄 

**config.sh**
```shell
milight_ip_address="XX.XX.XX.XX"
```

**commands**
```shell
*LUMIERE*BLEU*==sudo echo -n -e "\x42\x30" | nc -u -q 1 $milight_ip_adress 8899 && say "J'ai allumée la lumière bleue"
```

**Comment by Benfosse** [comment]
Du coup il faut que je change quoi exactement ? ^^'
Je dois obligatoirement le mettre dans command ?

**Comment by alexylem** [comment]
Ok, t'es pas obligé de passer par un script externe quand la commande à exécuter est aussi simple. Mets-la directement dans `commands` comme je l'ai fait, car puis là tes variables sont "visibles".
Donc pas besoin de ton fichier `lumiere.sh`. J'espère que c'est assez clair.

**Comment by Benfosse** [comment]
En faite le soucis est que la commande ne fonctionne que dans le cadre d'un bash, en tant que commande sh, celle-ci ne fonctionne pas, d'où mon incapacité à l'intégrer dans le ficher command ...

**Comment by alexylem** [comment]
Ca devrait marcher, car Jarvis exécute les commandes de `commands` comme si elles étaient dans un script `bash`.
Essaye simplement:

**commands**
```shell
ALLUME*LUMIERE BLEU*==<ta commande bash> && say "C'est fait"
```

Ca devrait fonctionner. Sinon colle le résultat de la console Jarvis lancé en mode troubleshooting et je t'aiderai à partir de la.

**Comment by Benfosse** [comment]
Alors sur la double commande, il execute le say et ne met pas d'erreur sur ma commande bash, mais il ne la lance pas....

Voici le code du troobleshooting, j'espère que tu y trouveras quelques choses : 

glados: Waiting to hear 'glados'
Benjamin: (listening...)
DEBUG: models=glados,snowboy
ALSA lib confmisc.c:1286:(snd_func_refer) Unable to find definition 'cards.bcm2835.pcm.front.0:CARD=0'
ALSA lib conf.c:4259:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:4738:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM front
ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.rear
ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.center_lfe
ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.side
ALSA lib confmisc.c:1286:(snd_func_refer) Unable to find definition 'cards.bcm2835.pcm.surround51.0:CARD=0'
ALSA lib conf.c:4259:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:4738:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM surround21
ALSA lib confmisc.c:1286:(snd_func_refer) Unable to find definition 'cards.bcm2835.pcm.surround51.0:CARD=0'
ALSA lib conf.c:4259:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:4738:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM surround21
ALSA lib confmisc.c:1286:(snd_func_refer) Unable to find definition 'cards.bcm2835.pcm.surround40.0:CARD=0'
ALSA lib conf.c:4259:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:4738:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM surround40
ALSA lib confmisc.c:1286:(snd_func_refer) Unable to find definition 'cards.bcm2835.pcm.surround51.0:CARD=0'
ALSA lib conf.c:4259:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:4738:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM surround41
ALSA lib confmisc.c:1286:(snd_func_refer) Unable to find definition 'cards.bcm2835.pcm.surround51.0:CARD=0'
ALSA lib conf.c:4259:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:4738:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM surround50
ALSA lib confmisc.c:1286:(snd_func_refer) Unable to find definition 'cards.bcm2835.pcm.surround51.0:CARD=0'
ALSA lib conf.c:4259:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:4738:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM surround51
ALSA lib confmisc.c:1286:(snd_func_refer) Unable to find definition 'cards.bcm2835.pcm.surround71.0:CARD=0'
ALSA lib conf.c:4259:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:4738:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM surround71
ALSA lib confmisc.c:1286:(snd_func_refer) Unable to find definition 'cards.bcm2835.pcm.iec958.0:CARD=0,AES0=4,AES1=130,AES2=0,AES3=2'
ALSA lib conf.c:4259:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:4738:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM iec958
ALSA lib confmisc.c:1286:(snd_func_refer) Unable to find definition 'cards.bcm2835.pcm.iec958.0:CARD=0,AES0=4,AES1=130,AES2=0,AES3=2'
ALSA lib conf.c:4259:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:4738:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM spdif
ALSA lib confmisc.c:1286:(snd_func_refer) Unable to find definition 'cards.bcm2835.pcm.iec958.0:CARD=0,AES0=4,AES1=130,AES2=0,AES3=2'
ALSA lib conf.c:4259:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:4738:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM spdif
ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.hdmi
ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.hdmi
ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.modem
ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.modem
ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.phoneline
ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.phoneline
ALSA lib pulse.c:243:(pulse_connect) PulseAudio: Unable to connect: Connection refused

ALSA lib pulse.c:243:(pulse_connect) PulseAudio: Unable to connect: Connection refused

Cannot connect to server socket err = No such file or directory
Cannot connect to server request channel
jack server is not running or cannot be started
INFO:snowboy:Silence
INFO:snowboy:Silence
INFO:snowboy:Silence
INFO:snowboy:Silence
INFO:snowboy:Silence
INFO:snowboy:Silence
INFO:snowboy:Silence
^CDEBUG: program exit handler
DEBUG: program_exit hook

**Comment by alexylem** [comment]
Dans ce que tu m'as collé tu ne déclenche même pas le mot clé... tu es sûr que ton Jarvis est configuré et fonctionne bien?

**Comment by Benfosse** [comment]
Il répond à ma voix et déclenche toutes les actions, que ce soit celles de bases ainsi que celles que j'ai ajoutés.
De plus il ressort bien le son de ma voix lorsque qu'il est en mode troobleshooting..

**Comment by alexylem** [comment]
Ok alors ca serait bien que tu me colles la partie ou tu essayes ta commande qui ne fonctionne pas...

**Comment by Benfosse** [comment]
J'ai relancé le mode, voici le nouveau rendu console :

glados: Waiting to hear 'glados'
Benjamin: (listening...)
DEBUG: models=glados,snowboy
^CALSA lib confmisc.c:1286:(snd_func_refer) Unable to find definition 'cards.bcm2835.pcm.front.0:CARD=0'
ALSA lib conf.c:4259:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:4738:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM front
ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.rear
ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.center_lfe
ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.side
ALSA lib confmisc.c:1286:(snd_func_refer) Unable to find definition 'cards.bcm2835.pcm.surround51.0:CARD=0'
ALSA lib conf.c:4259:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:4738:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM surround21
ALSA lib confmisc.c:1286:(snd_func_refer) Unable to find definition 'cards.bcm2835.pcm.surround51.0:CARD=0'
ALSA lib conf.c:4259:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:4738:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM surround21
ALSA lib confmisc.c:1286:(snd_func_refer) Unable to find definition 'cards.bcm2835.pcm.surround40.0:CARD=0'
ALSA lib conf.c:4259:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:4738:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM surround40
ALSA lib confmisc.c:1286:(snd_func_refer) Unable to find definition 'cards.bcm2835.pcm.surround51.0:CARD=0'
ALSA lib conf.c:4259:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:4738:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM surround41
ALSA lib confmisc.c:1286:(snd_func_refer) Unable to find definition 'cards.bcm2835.pcm.surround51.0:CARD=0'
ALSA lib conf.c:4259:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:4738:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM surround50
ALSA lib confmisc.c:1286:(snd_func_refer) Unable to find definition 'cards.bcm2835.pcm.surround51.0:CARD=0'
ALSA lib conf.c:4259:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:4738:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM surround51
ALSA lib confmisc.c:1286:(snd_func_refer) Unable to find definition 'cards.bcm2835.pcm.surround71.0:CARD=0'
ALSA lib conf.c:4259:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:4738:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM surround71
ALSA lib confmisc.c:1286:(snd_func_refer) Unable to find definition 'cards.bcm2835.pcm.iec958.0:CARD=0,AES0=4,AES1=130,AES2=0,AES3=2'
ALSA lib conf.c:4259:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:4738:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM iec958
ALSA lib confmisc.c:1286:(snd_func_refer) Unable to find definition 'cards.bcm2835.pcm.iec958.0:CARD=0,AES0=4,AES1=130,AES2=0,AES3=2'
ALSA lib conf.c:4259:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:4738:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM spdif
ALSA lib confmisc.c:1286:(snd_func_refer) Unable to find definition 'cards.bcm2835.pcm.iec958.0:CARD=0,AES0=4,AES1=130,AES2=0,AES3=2'
ALSA lib conf.c:4259:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:4738:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM spdif
ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.hdmi
ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.hdmi
ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.modem
ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.modem
ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.phoneline
ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.phoneline
ALSA lib pulse.c:243:(pulse_connect) PulseAudio: Unable to connect: Connection refused

ALSA lib pulse.c:243:(pulse_connect) PulseAudio: Unable to connect: Connection refused

Cannot connect to server socket err = No such file or directory
Cannot connect to server request channel
jack server is not running or cannot be started
DEBUG: program exit handler
DEBUG: program_exit hook

**Comment by alexylem** [comment]
@Benfosse Ce que tu me colles est le tout début avant même la reconnaissance du mot clé 'glados'... je vois pas en quoi ca va m'aider...

**Comment by Benfosse** [comment]
Désolé, j'ai édité, le texte était situé au dessus ! :/

**Comment by alexylem** [comment]
Ok 😄  Voici la partie intéressante:
```shell
$> echo -n -e "x40x47" | nc -u -q 1 192.168.1.37 8899 && say "J'ai allumée la lumière bleue"
glados: J'ai allumée la lumière bleue
```
De ce que je vois ca a bien fonctionné... Il a même remplacé la variable correctement...
Si ca n'a pas marché, essaye de copier et coller cette ligne dans le terminal pour voir si ca fonctionne bien:
```shell
echo -n -e "x40x47" | nc -u -q 1 192.168.1.37 8899
```

**Comment by Benfosse** [comment]
Dans le terminal en lui même la commande fonctionne, c'est vraiment quand je l'intègre dans le fichier commande que ça ne marche plus :/

**Comment by alexylem** [comment]
Tu veux dire que si tu copies-colles:
```shell
echo -n -e "x40x47" | nc -u -q 1 192.168.1.37 8899
```
Ca marche, mais tel quel ca ne marche pas si tu le mets dans une commande?

**Comment by Benfosse** [comment]
Alors si j'execute cette commande dans le terminale, elle se lance et la lumière change de couleur. 
En revanche quand elle est intégrée au fichier command de Jarvis, là elle ne s'execute plus, la lumière ne change pas !

**Comment by alexylem** [comment]
Juste pour confirmer ma question j'ai rajouté en éditant mon post, tu n'aurais pas oublié de mettre un `sudo` dans la commande, tu la lances bien telle quelle avec le même utilisateur que Jarvis?

**Comment by Benfosse** [comment]
Alors la commande rentrée dans le terminal fonctionne sans le sudo, pour le test j'ai intégré le sudo dans le fichier command, et rien, pas d'erreur mais la lumière ne change pas !

**Comment by alexylem** [comment]
Franchement je vois pas d'où peut venir le problème, car en mode troubleshooting il affiche exactement la commande qu'il lance:
```shell
$verbose && my_debug "$> $action"
eval "$action" || say "$phrase_failed"
```
Il n'y a aucune raison que ca ne marche pas...
Je vois pas comment t'aider la dessus... peut-être une vidéo?

**Comment by Benfosse** [comment]
Mince... Moi aussi j'ai trouvé ça bizarre et je me suis pas mal pris la tête pour réussir à le faire fonctionner, c'est comme ça que j'en suis venu à la solution d'un fichier script à part ^^"
Voici la vidéo :
https://goo.gl/photos/1mq1jnQxkUbotTCW6
Le moment où je remet la lumière en rouge c'est en faisant appel à mon ficher externe, pour les test je n'ai modifié que la partie de la lumière bleue....

**Comment by Benfosse** [comment]
Et mon fichier de command: http://prntscr.com/cm9qvf

**Comment by alexylem** [comment]
Juste pour être sûr... tu n'aurais pas une vielle commande qui traine dans `jarvis-commands` par hasard... dis moi que ce n'est pas ca...

**Comment by Benfosse** [comment]
Qu'entend tu par vieille commande ? ^^'

**Comment by alexylem** [comment]
Dans `Settings > Commands` tu n'as pas de commande qui pourrait matcher "*LUMIERE*BLEU*"

**Comment by Benfosse** [comment]
Voici mon fichier de commandes de jarvis : http://prntscr.com/cm9uxc

**Comment by Benfosse** [comment]
Ahah non rien de tout ça heureusement ^^

**Comment by alexylem** [comment]
Attends je pense que j'ai une piste...

**Comment by alexylem** [comment]
Ok j'ai trouvé le problème,  ca vient de Jarvis 😄 
L'`eval` interprète mal les caractères spéciaux:
```shell
BIP==echo -e "\a" && say "Bip"
```

```shell
Jarvis: Bonjour Alex
Alex: bip
a # il ne devrait rien afficher mais faire un son "bip"
Jarvis: bip
```
J'essaye de corriger ca.

**Comment by Benfosse** [comment]
Parfait, j'espère que c'est ça !!! :D 👍

**Comment by alexylem** [comment]
bon j'ai trouvé une solution, c'est un peu à l'arrache j'espère que ca va pas casser certaines commandes d'autres utilisateurs de Jarvis.
Mets à jour et dis moi si ca fonctionne.

**Comment by Benfosse** [comment]
Je viens de faire la maj et toujours pas de changement de couleur, mince ... :/

**Comment by Benfosse** [comment]
Fausse alerte, un sudo et c'est bon, merci !! :D

**Comment by Benfosse** [comment]
Euh attend, après plusieurs essaie ça n'a fonctionné qu'une seule fois ...

**Comment by Benfosse** [comment]
Alors petit récapitulatif : 
La commande fonctionne si c'est la première que j'execute après le lancement de Jarvis, si je change la couleur en vert par exemple et que je demande le bleue après rien à faire...

**Comment by alexylem** [comment]
Oui c'est ce que je pensais, ca vient de Jarvis je confirme... faut que je trouve une meilleure solution...

**Comment by alexylem** [comment]
```shell
Jarvis: Bonjour Alex
Alex: bip
# marche la première fois
Alex: bip
a # pas la 2ème
Alex: 
```

**Comment by Benfosse** [comment]
J'espère que tu vas pas trop te prendre la tête dessus ... :/

**Comment by alexylem** [comment]
Met à jour et retente...

**Comment by Benfosse** [comment]
Parfait tout ça, ça fonctionne ;)

**Comment by alexylem** [comment]
Super, j'en suis très heureux pour toi. Merci de m'avoir fait découvert ce bug!
