### ISSUE TITLE
Commandes rapides avec snowboy

### ISSUE THREAD

**Issue by physicien** [alexylem/jarvis#15]
Il serait intéressant d'avoir un certain nombre de commandes de base dans le cas où la connection à un serveur distant serait coupée.
Pour certaines fonctions de très bas niveau, je ne pense pas qu'il soit nécessaire de passer par un serveur distant. Exemple: si je dis « Bye » dans le but de quitter Jarvis, ou encore si j'ai un thermomètre de branché à ma Pi et que je veux savoir la température qu'il fait dans la pièce.
Un hotword pour rediriger vers le STT distant (Google, Wit ou PocketSphinx sur PC) et certaines commandes de base.

- `JARVIS` => Trigger pour passe en mode écoute commandes avec `google` ou `wit`
- `ALLUME BAR` => Commande rapide (écoute permanente, action directe)
- `TEMPERATURE PIECE` => Commande rapide (écoute permanente, action directe)

**Comment by physicien** [comment]
#13

**Comment by physicien** [comment]
J'ai visiblement des difficultés avec la configuration :laughing:

**Comment by physicien** [comment]
Côté documentation, un exemple de `main.py` utilisant plusieurs hotwords est disponible [ici](https://snowboy.kitt.ai/docs) voir Multiple Models and Callbacks.
Pour ce qui est des modèles de hotword (`.pmdl` ou `.umdl`), ils doivent être ajoutés au dossier `~/jarvis/stt_engines/snowboy/resources`.
Finalement, toutes nouvelle commande doit être ajouté dans le `snowboydecoder.py`.

**Comment by NYGHOST** [comment]
bon je me lance dans un full snowboy
petite question, une fois les commandes enregistrées et ajouter a snowboydecoder, comment preciser de ne plus utiliser les autres stt?

**Comment by alexylem** [comment]
Il faudra adapter le core de jarvis puis proposer `snowboy` dans `Settings > Voice recognition > For commands`. Vu que ca fait pas mal de changement à Jarvis et à `snowboydecoder` je pensais le faire moi, mais si tu maitrises le code de jarvis, tu peux le faire toi et proposer un `pull request` pour que je l'intègre à la branche principale du projet. Dis-moi et si oui je t'ajoute en contributeur.

**Comment by NYGHOST** [comment]
je me suis pas mal penché sur le core mais j'ai encore du mal a voir les interactions.
il semble déjà que le main ne gere que le hotword, donc j'ai augmenté les models, la je regarde snowboydecoder et Jarvis.sh je bloque sur la reco des mots apres le trigger. j'ai un echec direct "ERROR reco failed

**Comment by alexylem** [comment]
`ERROR reco failed` est affiché quand main.py ne retourne pas le bon code erreur (c'est fait maison). Honnêtement je préfère t'épargner cette galère si tu peux attendre ce weekend 😄

**Comment by NYGHOST** [comment]
je reviens aux news concernant l'implémentation des commandes via snowboy

**Comment by alexylem** [comment]
Pour l'instant je travaille sur #49 mais je commence aussi à réfléchir sur celui la. Je n'ai pas pu avancer dessus le week-end dernier, mais j'ai pas oublié 😄

**Comment by alexylem** [comment]
Attention, vu sur:
https://snowboy.kitt.ai/docs
>You can give HotwordDetector a mixture of multiple personal and universal models **as long as your CPU is powerful enough** to process them all.

**Comment by Smanar** [comment]
Oui, mais pour l'avoir teste sur un raspberry B+, ca ne consomme que tres peu de cpu, bon je pense que a partir de vingt ca ve se faire sentir ^^, mais pour des hotwords de secours je ne pense pas que ce soit un probleme, pour moi le probleme va etre les faux positifs, avec 5/6 hotwords ca va detecter trop souvent.

**Comment by alexylem** [comment]
D'ou la nécessité de suivre la recommandation de `snowboy` et avec des hotwords d'au moins 3 ou 4 syllables 😄 

👎  Pas conseillé
- Jarvis
- Hé
- Al

👍  Conseillé
- Salut Jarvis
- Hé Jarvis
- Tu es la?
- Tu m'écoutes?

**Comment by alexylem** [comment]
Je commence à regarder pour l'implémentation, c'est possible mais ca ne va pas être facile... allez je me lance!

**Comment by alexylem** [comment]
Voici mon idée de base pour que ce soit le plus facile possible pour l'utilisateur et le mieux intégré possible:

1. Disons que l'utilisateur de Jarvis à cette commande:
```
[...]
ALLUME*LE*BAR=echo pl a1 on | nc localhost 1099 && say "Voilà"
[...]
```
2. Il n'a qu'à entrainer un nouveau hotword `snowboy` et le nommer ainsi:
"Allume le bar" > `allume_le_bar.pmdl`
3. Placer les modèles dans le dossier `resources` de `snowboy`
```
$> ls stt_engines/snowboy/resources/
allume_le_bar.pmdl	jarvis.pmdl	snowboy.umdl
```
4. Au lancement de jarvis, initialiser `snowboydecoder` avec le trigger + tous les `pmdl`
5. A la détection d'un hotword, la commande sera le nom du fichier
```
Alex: allume_le_bar
```
6. Si c'est le trigger, on passe en mode conversation, sinon, on regarde dans les commandes:
```
[[ allume_le_bar == ALLUME*LE*BAR ]]
```
7. La commande correspondante sera donc exécutée

**Comment by physicien** [comment]
Penses-tu rendre la commande accessible par deux chemins? Exemple, si je suis dans le mode conversation, je ne veux pas nécessairement en sortir pour lancer la commande depuis un hotword.

**Comment by alexylem** [comment]
Bonne question, la commande sera bien entendu accessible en mode trigger et en mode conversation. Sauf qu'en mode conversation elle ne sera pas reconnue par `snowboy` mais par le moteur de reconnaissance vocale choisi pour les commandes:
```shell
Jarvis: (waiting to hear "Jarvis")
Alex: allume_le_bar # commande rapide snowboy
Jarvis: Voilà
Jarvis: (waiting to hear "Jarvis")
Alex: jarvis
Jarvis: Oui?
Alex: allume le bar # commande bing / google / wit
Jarvis: Voilà
```

**Comment by alexylem** [comment]
Ca progresse...
```
INFO:snowboy:Silence
"Jarvis"
INFO:snowboy:Keyword 1 detected at time: 2016-07-30 12:02:00
INFO:snowboy:Silence
[...]
"Allume le bar"
INFO:snowboy:Keyword 2 detected at time: 2016-07-30 12:02:03
INFO:snowboy:Silence
```

**Comment by alexylem** [comment]
Terminé et ca fonctionne à merveille, je mets à jour la doc avant de committer

**Comment by alexylem** [comment]
Voici comment créer des commandes rapides:
https://github.com/alexylem/jarvis/wiki/snowboy#commandes-rapides

Tableau des moteurs de reconnaissance vocale mis à jour:
![image](https://cloud.githubusercontent.com/assets/11017174/17270965/5cd28426-566f-11e6-8d9c-3c484135ccf0.png)

**Comment by trarizakaria** [comment]
comment ajouter les commandes a snowboydecoder ou le reinitialiser  ??   j'ai ajouté les .pmdl au dossier /resources  et démarrer jarvis mais ça donne ERROR : snowboy recognition failed. j'ai besoin d'aide et merci d'avance.
je suis déçu avec la mauvaise reconnaissance de bing et je veux mettre mes propres commandes

**Comment by alexylem** [comment]
@trarizakaria 
Merci de coller le résultat complet de la console après avoir lancé Jarvis en mode Troubleshooting, ou partage une session de ton terminal en utilisant [asciinema](http://asciinema.org):
```shell
sudo apt-get install -y asciinema && asciinema rec # start session recording
./jarvish.sh -nv # start jarvis directly in troubleshooting mode
Ctrl+D # stop recording
y # yes to upload and get URL to paste
```

**Comment by trarizakaria** [comment]
merci @alexylem  j'ai essayé de désinstaller et réinstaller snowboy et je me trouve avec une autre erreur dés le démarrage (sans l'ajout des fichiers .pmdl ) 

```
DEBUG: models=alexa,snowboy
Cannot connect to server socket err = No such file or directory
Cannot connect to server request channel
jack server is not running or cannot be started
```
donc je crois que je vais refaire l'installation de jarvis sur un "clean" raspbian sur une autre raspberry  avant d'ouvrir un ticket.

une question stp 
comment désinstaller jarvis proprement ainsi que ses dépendances ? je supprime seulement le dossier jarvis et je recommence le clonage. est ce la procédure correcte ?? 

pour

**Comment by alexylem** [comment]
Ce n'est pas un pb, pour snowboy, voir #364 (ca devrait qd mm marcher)
Pour désinstaller Jarvis, oui simplement supprimer le dossier complet. Si tu veux garder ta config, backup le dossier config.
Pour supprimer toutes les dépendances, tu peux créer un ticket je pourrais mettre en place un script automatique.

**Comment by trarizakaria** [comment]
Merci pour les réponses rapides. J'ai réinstallé jarvis et essayé d'enregistrer les nouveaux hotwords en local avec snowboy  au lieu de les enregistrer et télécharger depuis leur site. Ça  marche bien maintenant. 
Je ne trouve pas la reconnaissance vocale de Google sur jarvis depuis ces derniers MAJ. Je crois qu'elle est mieux que celle de bing en terme de qualité.

**Comment by alexylem** [comment]
Reconnaissance vocale de Google = Bing 😄

**Comment by alexylem** [comment]
>Je ne trouve pas la reconnaissance vocale de Google sur jarvis depuis ces derniers MAJ.

Il a été enlevé, voir #95

**Comment by trarizakaria** [comment]
bonjour tout le monde, salut @alexylem  me voila de retour, je poste toujours la même question d'avant, je part avec une nouvelle installation sur raspbian jessie, je veux passer par des commandes rapides snowboy, j'enregistre "allume la lumiere du sejour" je relance jarvis et puis rien !! il connais juste le hotword snowboy , en mode verbose je contate que DEBUG models=snowboy donc il n'y a pas les autre models que j'ai enregistré, que faire donc ?? ou dois je ajouter ces models et comment ? 
voila ma config
`pi@raspberrypi:~/jarvis $ ./jarvis.sh
Notice: you can use 'jarvis' instead of './jarvis.sh'

------------ Config ------------
jv_branch            master
jv_version
jv_arch              armv7l
jv_os_name           raspbian
jv_os_version        8
language             fr_FR
play_hw              hw:0,0
rec_hw               hw:1,0
speaker              ALSA
microphone           Asahi Kasei Microsystems Co., Ltd
recorder             snowboy
trigger_stt          snowboy
command_stt          wit
tts_engine           svox_pico
--------------------------------

DEBUG: program_startup hook
DEBUG: start_speaking hook
snowboy: Hello
DEBUG: models=snowboy
INFO:snowboy:Ticks: [2, 20, 5, -1]
INFO:snowboy:Keyword 1 detected at time: 2017-12-20 16:55:46
INFO:snowboy:No match - no voice before hotword
INFO:snowboy:Keyword 1 detected at time: 2017-12-20 16:55:53
INFO:snowboy:Keyword 1 detected at time: 2017-12-20 16:56:03`

**Comment by trarizakaria** [comment]
j'ai essayé de chercher quoi modifier sur main.py et snowboydecoder.py mais j'ai rien compris. voila une capture
[https://asciinema.org/a/QIKi68RjWYdwsexQ5ghdHw1Ot](url)

**Comment by ghost** [comment]
Quick orders are not working, even though I did exactly what you (@alexylem)  explained in [https://www.openjarvis.com/content/snowboy#commandes-rapides](url)
Things I did : 

1. recorded my new hotword in snowboy website.
2. tested it.
3. downloaded the file which is in .pmdl format with file name all in lower_case .
4. placed it in stt_engines/snowboy/resources/
5. restarted openjarvis as well as rpi too.

jarvis didn't recongnize the second trigger word or quick word
Did I miss something in the above step?
Is there any changes to be made in snowboydecoder as you mentioned earlier?

> initialize snowboydecoderwith trigger + allpmdl

Btw awesome project @alexylem  , appreciate you're work. Thanks for making it open-source.

**Comment by Oliv4945** [comment]
@arjun312 : Please avoid double posting here and in #802 
Est-ce qu'une personne ayant réussi à les faire fonctionner pourrait poster le résultat de `jarvis -nv`, en particulier la ligne `DEBUG: models= ` ?
