### ISSUE TITLE
Voice Recognition & Speech Synthesis in Spanish

### ISSUE THREAD

**Issue by agustinscaz** [alexylem/jarvis#155]
### Description

What can I do to add Spanish language to jarvis, also I want to add Italian.
Thanks

**Comment by alexylem** [comment]
Please update ticket #55

**Comment by alexylem** [comment]
Today Jarvis can only be configured to understand & speak English & French.
Request is to add Spanish (which should already be supported by Bing / Google / eSpeak / PicoTTS).

**Comment by alexylem** [comment]
@agustinscaz please update your Jarvis and go to Settings > General to change your language to es_ES. I have tested with Bing & OSX it works, should also work with PicoTTS & Google Speech. Please give it a try and let me know.

**Comment by agustinscaz** [comment]
Works perfect! thanks :+1:
