### ISSUE TITLE
Conversation with Jarvis

### ISSUE THREAD

**Issue by agustinscaz** [alexylem/jarvis#156]
### Description

I want to create a real conversation between me and jarvis, to get the temperature from different places like this

Me: Temperature
Jarvis: Where do you want to know the temperature?
Me: France
Jarvis: The temperature for France is 15ºC
Me: Thanks

How can i do this?

Thanks :)

**Comment by alexylem** [comment]
Already possible with [indented commands](https://github.com/alexylem/jarvis/wiki/commands#commandes-imbriqu%C3%A9es)
