### ISSUE TITLE
pip : unknown command lors de l'installation de Snowboy

### ISSUE THREAD

**Issue by patrick95470** [alexylem/jarvis#16]
Hi Alex,

Just to notice that the last update does not fully work on jessie lite
PIP doesn't seem to be installed by default

![image](https://cloud.githubusercontent.com/assets/11017174/16362940/a82385c0-3bbb-11e6-99fe-76688e4d641f.png)

Patrick

**Comment by alexylem** [comment]
> pip is installed by default in Raspbian Jessie (but not Raspbian Wheezy or Jessie Lite).

**Comment by alexylem** [comment]
Ajouté au script d'installation de `snowboy`
```
wget https://bootstrap.pypa.io/get-pip.py
python get-pip.py
```
@patrick95470 peux-tu vérifier que l'exécution de ces 2 commandes débloquent l'installation de `snowboy` ?
