### ISSUE TITLE
Message d'erreur lors de fail d'une commande

### ISSUE THREAD

**Issue by controlom** [alexylem/jarvis#161]
Bonjour,

Lorsque qu'un script envoi une erreur lors d'exécution, la sortie du message est le fichier jarvis-commands.

Ex:
Ici une erreur avec mon fichier météo:
```
jarviss: je regarde
/var/lib/gems/2.1.0/gems/weather-api-1.3.0/lib/weather-api.rb:56:in `get_response': undefined method `[]' for nil:NilClass (NoMethodError)
        from /var/lib/gems/2.1.0/gems/weather-api-1.3.0/lib/weather-api.rb:44:in `lookup'
        from ./store/all/fr_weather/weather.rb:6:in `<main>'
jarviss: *ANNULER* TERMINE*==bypass=false; say "Ok"
*MERCI*==say " De rien je vous en prie "
*AIDE*==cat jarvis-commands
*COMMENT*APPELLE*==say "Je m'appelle $trigger"
*TU*APPELLE*COMMENT*==say "Je m'appelle $trigger"
*BONJOUR* *SALUT* *COUCOU*==say " Bonjour $username Salut, Heureux de vous voir "
*AU REVOIR* *BYE*==say "Au revoir $username"; exit
*TEST*==say " Ca fonctionne! Test OK "
*VERSION*==say "Je suis en version 0.1"
```

Comment faire  pour qu'il affiche un message d'erreur ?

merci

**Comment by alexylem** [comment]
Tu peux coller ton fichier météo que tu utilises? C'est un plugin perso non publié sur le store?

**Comment by controlom** [comment]
Oui c'est un plugin perso qui va chercher des infos sur Yahoo.
J'ai corrigé mon script pour éviter d'avoir l'erreur mais je voulais savoir si c'est possible de gérer aussi coté jarvis.

**Comment by alexylem** [comment]
Jarvis gère déjà les erreurs, il check le code de retour de la commande, et si c'est différent de 0, il dit la phrase "Cette commande a retourné une erreur" (que l'on peut changer dans les Settings).
Il doit surement y avoir un problème dans ton plugin perso qui génère tout cet affichage étrange...

**Comment by controlom** [comment]
Ok merci pour l'info.

**Comment by alexylem** [comment]
Je ferme le ticket réouvre si tu ne trouve pas l'origine de ton problème et que tu penses que ça vient de jarvis.
