### ISSUE TITLE
lancer des requetes http sur une box Fibaro hcl

### ISSUE THREAD

**Issue by davidobrasil** [alexylem/jarvis#163]
bonjour, 
j aimerais créer une ligne de commande pour agir sur ma box domotique fibaro hcl.
je connais la requêtes a envoyer  (http://<LOGIN>:<PASS>@<IP>/api/callAction?deviceID=<16>&name=turnOn) bien sur le login,pass,et ip sont renseigner cette requête fonction avec l ipad.
donc j ai créer ceci dans la liste de commande

*ALLUME LE COULOIR*==get "http://<LOGIN>:<PASS>@<IP>/api/callAction?deviceID=<16>&name=turnOn && say "la lumiere est fut"

j ai fais une erreur car bien sur ça marche pas peu tu me donner la ligne de commande a executer
merci par avance.
très beau projet c est  vraiment ce que je recherche pour pouvoir piloter mon hcl par la voix merci je vais suivre de prêt.
y a plein d autre question qui  me viennent mais pour l instant je vais commencer avec ça pour faire simple .
si je peux être utile pour essayer des trucs sur fibaro demande mes compétence sont limite mais y a google.
a bientôt
PS: j ai suivi le tuto vidéo pour l installation et c plus du-tout pareil j ai galéré  mais j y suis arriver ouf!!!!

### Résultat
```
coller ici contenu de la console après avoir lancé Jarvis en mode troubleshooting
ou supprimer ce paragraphe si non-applicable.
```

**Comment by Michelgard** [comment]
Bonjour, moi je fais cela : 
*ALLUME*LAMPE*SALON*==wget -qO /dev/null "http://mon-ip:85/?LED2=ON" & say "La lampe du salon est allumée"
Donc tu dois pouvoir faire : ALLUME LE COULOIR==wget -qO /dev/null "http://:@/api/callAction?deviceID=<16>&name=turnOn" & say "la lumiere fut"

J'ai trouvé cela dans un autre post d'Alex et ça marche.

**Comment by alexylem** [comment]
Il faut mieux utiliser deux `&&` si vous voulez attendre que la commande soit exécutée avant de dire "*C'est fait*" 😄 
```shell
ALLUME LE COULOIR==wget -qO /dev/null "http://..." && say "la lumiere fut"
```
