### ISSUE TITLE
Dictionary of correspondance for specific words usually not recognized

### ISSUE THREAD

**Issue by kevincaradant** [alexylem/jarvis#168]
Hi
Just a question, is there any way to say at Jarvis. Write this word with this syntax ? 
Example: "Lancer kodi" is understood by "Lancer cody" 
Thanks :)

**Comment by alexylem** [comment]
Why don't you simply write you command the way it understand you?
Ex:
```bash
LANCER CODY==<run kodi>
```
Instead of:
```bash
LANCER KODI==<run kodi>
```

**Comment by kevincaradant** [comment]
Yes I did that, but I ask just in case something was already ready for this transformation or not.
I will republish it with the new system soon. I hope have the time today otherwise I will do tomorrow ( the evening). Thanks

**Comment by alexylem** [comment]
That could be an improvement idea, like a word translation dictionary:
```
CODY=KODI
[...]
```
Plugins should be able to augment that dictionary for their own specific terms.
If more than 1 person needs this, I will implement it.

**Comment by wikijm** [comment]
Une tâche a été crée dans la fonctionnalité 'Projects' pour cela (https://github.com/alexylem/jarvis/projects/1), avec le statut 'To be discussed'.

Si avancée sur le sujet, la tâche sera déplacée dans la fonctionnalité 'Projects' et le ticket pourra être ré-ouvert.
