### ISSUE TITLE
JARVIS too slow at the begin ?

### ISSUE THREAD

**Issue by kevincaradant** [alexylem/jarvis#171]
Hi @alexylem

I create here a little issue here to avoid a topic off on the other issue.
Can you tell me if it's normal or not but 8 times on 10 when I say "KODI", JARVIS heards "AUDI" and I understood because in the troubleshooting, he records "ODI", why the first letter is not heards by JARVIS ?  Is it too slow or maybe settings to change ?  

Thanks :)

**Comment by alexylem** [comment]
Can you show me with the troubleshooting more what is looks like in the logs?
Thanks!

**Comment by kevincaradant** [comment]
I totally forgot to answer you.  I have to repair my odroid.  So,  I will answer and edit this issue you,  as soon as possible :).  I hope before the last week

**Comment by alexylem** [comment]
@kevincaradant can you still reproduce this issue?

**Comment by kevincaradant** [comment]
I try to install again Jarvis,  tomorrow.  The odroid I using in the moment  for Jarvis,  is used for many things and I worked on others projects.  And the last month,  I had a lot of things to do,  since the crash of the odroid,  I didn't take the time to install again Jarvis,  so sorry to be slow to answer about this bug.  I will edit soon.

**Comment by alexylem** [comment]
No problem, just doing my weekly clean-up of old tickets. If you don't need my help at this stage, you can close the ticket and create a new one later if needed 😄

**Comment by kevincaradant** [comment]
Hi @alexylem 

I don't have time in the moment, I close it and when I will work on it again, I will opened it :)
