### ISSUE TITLE
Question: What microphone to use?

### ISSUE THREAD

**Issue by agustinscaz** [alexylem/jarvis#173]
### Description

Can anyone answer me what is the best microphone to use in my problem? 

I want to speak Jarvis from about 5 meters of distance.

Thanks!

**Comment by alexylem** [comment]
Jabra brand seems to be a very good choice, although it suffers from issues on the playback side (see #65 ). See also CM-1000USB from the [list of recommended Microphones](https://github.com/alexylem/jarvis/wiki/prerequisites). I personally use the PsEye for its price & noise reduction, but doesn't work well from far. See also discussion on using Mic Array #103.

**Comment by kevincaradant** [comment]
Je suis en cours de migration mais j'essaie de comprendre ce que je dois modifier dans mon code avec la nouvelle architecture :/. Je vois function.sh et je pense que dans mon cas c'est la méthode callKodiUrl() mais je ne sais pas trop ;)

**Comment by wikijm** [comment]
I confirm that JABRA brand is a good one. 
I'm actually use a JABRA 410 (with 3m USB cable)  and it works like a charm at 5m.

**Comment by Melmann** [comment]
Hello,

I try to use a Jabra 410 but Jarvis don't understand me above 1 or 2 meters.

I read that it's ok for you at 5 meters.

What kind of settings you have ?

Thank you.

**Comment by wikijm** [comment]
Nothing more than default settings.
Same case for Jabra 510.
