### ISSUE TITLE
Utilisation du TTS Voxygen

### ISSUE THREAD

**Issue by argonlefou** [alexylem/jarvis#176]
Bonjour,

Voici le ticket pour présenter le petit script en bash permettant d'automatiser l'utilisation de la démo en ligne du TTS voxygen (https://www.voxygen.fr/) pour JARVIS
Il y à des voix masculines, féminines et des voix fun assez bien fichues.
[SayVoxygen.sh.zip](https://github.com/alexylem/jarvis/files/524108/SayVoxygen.sh.zip)

L'utilisation est du type : ./SayVoxygen.sh Electra "Bonjour"

Les voix disponibles (toutes langues confondues) sont :  
{ 'Adel', 'Matthias', 'Sylvia', 'Bronwen', 'Elizabeth', 'Judith', 'Paul', 'Witch', 'Amanda', 'Martha', 'Agnes', 'Becool', 'Electra', 'Emma', 'Fabienne', 'Helene', 'Loic', 'Matteo', 'Melodine', 'Mendoo', 'Michel', 'Moussa', 'Philippe', 'Sorciere', 'Sonia', 'Jenny', 'Bruce', 'Marion' }

Sur ma machine sous debian (en internet Fibre) j'ai une latence mesurée entre 100ms et 150ms entre l'éxécution du script et la réception du fichier son.
Mon seul raspberry est un raspberry 1 model B+,  et là ça tourne plus aux alentours de 1s à 2s

**Comment by davidobrasil** [comment]
bonjour,
je suis intéressé par l utilisation de voxygen peut tu faire un petit tuto pour l installation ou un plugins.
Sachant que ma connexion internet n est pas la fibre (c la campagne) d ou est ce que ça vas fonctionner.
Et puis dans les voies propose y aurais t il pas la vraie voie de jarvis de iron man , ça serait vraiment cool??

**Comment by alexylem** [comment]
Tous ceux qui sont intéressés veuillez upvoter le premier post de @argonlefou.
+1 pour les voix fun!!

**Comment by Gilles76** [comment]
Bonjour,
Ca paraît bien , mais cela m'étonnerai que cela soit gratuit !

**Comment by LengZai** [comment]
Yes, 

I use it for my answering machine :-P.. But yes indeed, it's not free if we want to use it with Jarvis.

**Comment by alexylem** [comment]
Quelqu'un a une idée du prix? Any idea on the cost?
Si ce n'est pas gratuit je doute que ca intéresse la communauté Jarvis... (c'est aussi pour ca qu'on a viré Google...)

**Comment by argonlefou** [comment]
Le script que j'ai mis en exemple fonctionne de manière gratuite, il ne fait qu'utiliser la démo qui est sur la page principale de Voxygen.

Pour avoir accès au moteur TTS en local il faut en effet payer, mais celà n'est pas le but de ce que j'avais posté.
Sur Windows c'est dans les 40 euros (et la licence à l'air limité à 1 installation sur 1 machine d'après pas mal de messages dans des forums)
Sur Android, c'est de l'ordre de 1 à 2 euros par voix. Et pour avoir testé avec une, je l'ai installé sur 4 téléphones différents sans soucis (du moment que j'ai mon compte android dessus)
Sur Linux, il n'en parlent pas (pour les particuliers)

**Comment by alexylem** [comment]
Merged, il ne reste qu'à rajouter la sélection de la langue

**Comment by alexylem** [comment]
J'ai rajouté Voxygen aussi à [Jarvis-UI](http://domotiquefacile.fr/jarvis/plugins/jarvis-ui)
![image](https://cloud.githubusercontent.com/assets/11017174/20682296/b7ff120a-b5a7-11e6-8b38-4ba01c66df99.png)

**Comment by alexylem** [comment]
@JZacharie je n'arrive pas à faire marcher les autres voix, ca me sort toujours la voix Loic...

**Comment by alexylem** [comment]
@JZacharie / @argonlefou  j'arrive à le faire marcher en 2 lignes...
```shell
wget -O test.mp3 "http://www.voxygen.fr/sites/all/modules/voxygen_voices/assets/proxy/index.php?method=redirect&text=$1&voice=$voxygen_voice&ts=1480362849466"
mpg123 test.mp3
```
Ca m'a l'air tellement simple que j'ai du passer à côté d'un truc... votre code fait 50 lignes...

**Comment by alexylem** [comment]
Je me pisse de rire avec la voix Electra 😋  je pousse bientôt la mise à jour

**Comment by JZacharie** [comment]
Le code récupère le la phrase et fait un MD5 de la phrase pour créer un fichier mp3 unique.
Si le fichier mp3 existe il ne fait que le jouer (rapide), sinon il le récupère avant (un peu plus long).

Je n'ai fait qu'intégrer le code de argonlefou
.
Après c'est qu'une utilisation de curl au lieu de wget. Je pense que si on reste sur wget c'est plus simple.

**Comment by alexylem** [comment]
Le `md5` était inspiré de ma version de google TTS. Je l'ai remplacé par un `jv_sanitize` qui permet de savoir le contenu des `mp3`. Le `curl` allait plus loin car il récupérait manuellement la redirection du serveur en parsant chaque ligne pour trouver `Location` puis faisait un second appel...
Vous pouvez mettre à jour et jouer avec, les voix sont super avec avec le cache c'est bien réactif!
Je mets à jour le plugin jarvis-ui pour rajouter la sélection de la voix.

**Comment by alexylem** [comment]
![image](https://cloud.githubusercontent.com/assets/11017174/20685550/1ca11a52-b5b5-11e6-8a96-6f9007d310c0.png)
Dites-moi si vous voulez que je rajoute des voix et lesquelles.

**Comment by JZacharie** [comment]
pour information voxygen support le SSLM.
https://msdn.microsoft.com/en-us/library/jj127898.aspx

Example : 
--------------

<?xml version="1.0" encoding="ISO-8859-1"?>
<speak version="1.0"
 xmlns="http://www.w3.org/2001/10/synthesis"
 xml:lang="fr-FR">quatre, cinq, six
  <s xml:lang="en-US">one, two, three</s>
</speak>

**Comment by JZacharie** [comment]
<?xml version="1.0" encoding="ISO-8859-1"?>
<speak version="1.0"
 xmlns="http://www.w3.org/2001/10/synthesis"
 xml:lang="fr-FR">quatre, cinq, six
  <s xml:lang="en-US">one, two, three</s>
</speak>

**Comment by JZacharie** [comment]
"<?xml version="1.0" encoding="ISO-8859-1"?>
<speak version="1.0"
 xmlns="http://www.w3.org/2001/10/synthesis"
 xml:lang="fr-FR">quatre, cinq, six
  <s xml:lang="en-US">one, two, three</s>
</speak>"

**Comment by JZacharie** [comment]
pour les voix disponible il faut utiliser ce json : https://voxygen.fr/voices.json
Agnes et Loic sont mes préférés.

**Comment by JZacharie** [comment]
J'ai aussi Alain sur mon Phone mais il n'est plus disponible sur le web service.

**Comment by argonlefou** [comment]
+1 aussi pour Loïc, je trouve la voix vraiment passe partout et adaptée au sujet

**Comment by alexylem** [comment]
@argonlefou Loïc est déjà dans Jarvis. @JZacharie merci pour le JSON, en fonction des retours j'en rajouterai d'autres.  J'avais mis Marion plutôt que Agnès par peur de l'accent de Agn**è**s 😄

**Comment by themask38** [comment]
bonjour, je voudrai utiliser voxygen mais sa ne dit rien et voici le message d'erreur 
utils/utils.sh: line 101: voxygen_TTS: command not found

PS : swox_pico fonctionne très bien mais sa voix est juste horrible, merci de m'aider .

**Comment by alexylem** [comment]
@themask38 pas normal.
Tu peux:
1) vérifier que Jarvis est à jour:
```shell
$> ./jarvis.sh -u
```
2) vérifie que tu as bien le dossier voxygen
```shell
$> ls tts_engines/voxygen
```
3) lance jarvis en mode troubleshooting et partage le résultat
```shell
$> ./jarvis.sh -nv
```

**Comment by themask38** [comment]
jarvis est a jour, le dossier voxygen existe, et il comprend le fichier main.sh.
j'ai lancée jarvis en mode troubleshooting et voici le résultat 

------------ Config ------------
jv_version           17.02.16 
jv_arch              x86_64 
jv_os_name           ubuntu 
jv_os_version        12.04 
language             fr_FR 
play_hw              hw:1,9 
rec_hw               hw:2,0 
speaker              NVidia 
microphone           Logitech, Inc.  
trigger_stt          pocketsphinx 
command_stt          bing 
tts_engine           voxygen 
--------------------------------
jarvis: bonjour
DEBUG: start_speaking hook
utils/utils.sh: line 101: voxygen_TTS: command not found
DEBUG: stop_speaking hook
jarvis: Waiting to hear 'jarvis'
nicolas: (listening...)
 rec -V1 -q -r 16000 -c 1 -b 16 -e signed-integer --endian little jarvis-record.wav silence 1 0.1 1% 1 0.5 1% trim 0 10

**Comment by alexylem** [comment]
La dernière version de Jarvis est la 17.02.20
Peux-tu s'il te plait:
```
$> ./jarvis.sh -u
```
Merci

**Comment by themask38** [comment]
HA en fait il faut que je lance plusieurs fois  $> ./jarvis.sh -u

**Comment by themask38** [comment]
ha non c'est juste que j'ai modifier jarvis.sh et que la mise a joue ne se fait pas

**Comment by alexylem** [comment]
C'est sûr que si tu modifies le code après c'est sûr que ca va moins bien marcher 😄 
Pour toute demande de modification / évolution, merci de créer un ticket, je suis très réactif sur les bonnes idées.
Du coup je te conseille de remettre le code d'origine:
```
$> git reset --hard
$> ./jarvis.sh -u
```

**Comment by themask38** [comment]
ok

**Comment by alexylem** [comment]
Pour info, tu peux changer la fréquence de vérification de la mise à jour automatique dans les préférences / general.

**Comment by themask38** [comment]
nicolas@nicolas-ubuntu-12:~$ git reset --hard
fatal: Not a git repository (or any of the parent directories): .git
nicolas@nicolas-ubuntu-12:~$ cd jarvis
nicolas@nicolas-ubuntu-12:~/jarvis$ git reset --hard
HEAD is now at ba96324 Merge pull request #435 from wikijm/master
nicolas@nicolas-ubuntu-12:~/jarvis$ ^C
nicolas@nicolas-ubuntu-12:~/jarvis$ 

ca a marché la ou pas ?

**Comment by alexylem** [comment]
oui, maintenant mets à jour

**Comment by themask38** [comment]
c'est bon je retest voxygen et je te dit

**Comment by themask38** [comment]
c'est fonctione c'était un probleme de version

**Comment by themask38** [comment]
merci

**Comment by themask38** [comment]
heu... j'ai un nouveau probleme avec voxygen.
j'ai l'impresion que les phrases longues 

nicolas: .jarvis: Waiting to hear 'jarvis'
nicolas: jarvis
jarvis: oui ? /c'est dit par voxygen
nicolas: ?ça va
jarvis: Très bien et vous? /c'est dit par voxygen
*OUI*		*NON*
nicolas: oui
jarvis: tant mieux /c'est dit par voxygen
nicolas: quelle heure est-il
jarvis: il est  2 heures 59 /ce n'est pas dit
nicolas: quel jour sommes-nous
jarvis: nous sommes le mercredi 22 février 2017 /idem

et sa ma fait ca plusieurs fois je ne comprend pas pour quoi

**Comment by alexylem** [comment]
Tu peux stp créer un nouveau ticket?
Merci de coller le résultat complet de la console après avoir lancé Jarvis en mode Troubleshooting, ou partage une session de ton terminal en utilisant http://asciinema.org.

**Comment by themask38** [comment]
a OK merci

**Comment by lecopsportif** [comment]
Nouveau site pour Voxygen, donc lien mort. Plus de démonstration.
