### ISSUE TITLE
DAC USB low cost compatible raspberry & Jarvis ;-)

### ISSUE THREAD

**Issue by pascalouRASP** [alexylem/jarvis#177]
Bonjour à tous.

Je ne sais pas trop si c'est le bon endroit pour ce genre d'info, je ne connais pas GITUB, n'hésitez pas à déplacer mon post ;-)
Je viens de tester Jarvis avec mon petit DAC USB à moins de 10€ et que ça fonctionne très bien je fais donc circuler l'info.
Ca évitera à certains de se caser la tête sur des histoires de compatibilité de micros/webcam usb...

C'est un petit DAC USB générique acheté chez Electrodepot.
http://www.electrodepot.fr/carte-son-connectland-usb-pour-preecoute.html
Il est équipé de deux prises femelle jack 3.5mm ce qui permet de facilement le relier à un ampli et d'y mettre à peu près n'importe quel micro en entrée.

Il faut jouer un peu avec ALSAMIXER pour ne pas saturer l'entrée mais une fois les bons réglages trouvés ça marche vraiment très bien.
En plus, cerise sur le gateau, il est reconnu d'office par le rasp: 
Bus 001 Device 006: ID 0d8c:000c C-Media Electronics, Inc. Audio Adapter

Chez moi, il est branché sur le raspberry avec en plus une clé wifi et ça fonctionne parfaitement sans HUB auto-alimenté supplémentaire. On obtient donc une installation très compacte qui peut se planquer  très facilement.

Autre chose:
Je suis en train de développer des modules de mesure de temperature et des RELAIS ON/OFF sur base de ESP8266. (puce programmable avec wifi intégré)
C'est très facile à piloter sous Jarvis. (chaque module est connecté en wifi à la box du domicile et possède donc sa propre adresse IP. Il reçoit les ordres allumage/extinction via http par un ordre que Jarvis traduit en une simple requête HTTP)
J'ai déjà réalisé des capteurs temperature/humidité qui fonctionnent bien, je vais tenter de les faire causer avec Jarvis.
Je vous tiens au courant dès que j'ai reçu les pièces et que ça fonctionne sans accroc.

Ah oui j'allais oublier: Bravo pour le travail réalisé !
La reconnaissance vocale sous raspberry j'en ai rêvé et quelqu'un l'a fait ;-)

**Comment by alexylem** [comment]
1. Page [matériel supporté](https://github.com/alexylem/jarvis/wiki/prerequisites) mise à jour 👍 
2. Tu comptes nous faire [un petit plugin](http://domotiquefacile.fr/jarvis/content/publish-your-plugin)? 😄 
3. Merci! Et je ne suis plus seul la communauté s'agrandit de jour en jour!

**Comment by pascalouRASP** [comment]
Dès que tout ça est au point j’essaye de publier un plugin mais je ne suis pas un crack en programmation et je dois d’abord comprendre comment ça s’organise.

Si besoin je demanderai un petit coup de main.
