### ISSUE TITLE
SAY () avec des valeurs dans le résultat d'une requête http

### ISSUE THREAD

**Issue by pascalouRASP** [alexylem/jarvis#178]
Bonjour à tous,

Je travaille sur la réalisation de capteurs connectés (mini serveurs web avec ip) sur base de ESP8266.
Ces capteurs reviennent à quelques euros et on peut donc en fabriquer un grand nombre sans se ruiner. Comme c'est basé sur un microcontrôleur,  les capteurs sont très polyvalents et peuvent retourner des informations de tout type mais aussi en recevoir (température, humidité, mesure de PH, pression , distance, commande de relais etc...) y compris à partir d'une application sur un smartphone ou une tablette connectée sur le réseau wifi puisque le capteur embarque un mini serveur web.

J'essaye désespérément de faire dire à Jarvis la température et le taux d'humidité d'un capteur qui tourne actuellement chez moi.

On interroge le capteur comme un simple serveur web à l'aide de son url:
192.168.0.65/Jarvis

Et il répond:

```Bash
<html><head><title>Capteur</title></head><body><div id="temp"><TEMP>21.20</TEMP></div><BR><div id="hum"><HUM>54.90</HUM></div></body></html>
```

J'ai placé les balises TEMP et HUM pour faciliter le travail de découpe et la récupération des deux valeurs. J'ai essayé des tonnes de trucs dont **html-xml-utils** que j'ai installé sur mon raspberry mais rien à faire. Comme je ne maitrise pas bien les échappements (et d'une manière générale linux) je n'arrive à rien depuis 2 jours...

Je continue à creuser l'instruction SED que je découvre grâce à Alex mais je tourne en rond...

Toute aide est bienvenue, j'espère à terme pouvoir publier un plugin et quelques capteurs faciles à utiliser ;-)

EDIT: [https://www.w3.org/Tools/HTML-XML-utils/man1/hxextract.html](url) paraît être LA solution mais je n'arrive pas à inclure la syntaxe dans le SAY...

EDIT N°2: J'ai rajouté des balises DIV (temp & hum)pour pouvoir utiliser la commande **HXSELECT**  qui travaille directement sur les sélecteurs mais toujours sans succès.

**Comment by devauxa** [comment]
Peut tu nous donner ton résultat dans des balises 
\`\`\`Bash
Ton texte
\`\`\`
Si ton curl ressemble à  
```Bash
Capteur
21.20
54.90
```

Sinon pour faire simple tu peux faire (pas très joliment) :
`curl 192.168.0.65/Jarvis 2>/dev/null | awk -F '*' '$1 ~ /^[0-9.]+$/ {print $1}' |sed ':a;N;$!ba;s/\n/ et temperature de /g'|sed -e 's/^/Humidité de /g'`
qui te retournera 
Humidité de 21.20 et temperature de 54.90

**Comment by pascalouRASP** [comment]
****

**Comment by devauxa** [comment]
Merci pour ton édition,
Etant un fan de python, tu peux le faire avec bs4
`apt-get install python-bs4`
```Bash
echo -e "import bs4\nfrom urllib2 import urlopen\nsoup = bs4.BeautifulSoup(urlopen('http://192.168.0.65/Jarvis').read(), 'lxml')\nfor div in soup.find_all('div'):\n print(str(div['id']) + ' ' + div.text)" | python
```
Qui te retourne
```Bash
temp 21.20
hum 54.90
```

**Comment by pascalouRASP** [comment]
Me voici de retour.
J'ai tenté ça directement dans un terminal via ssh et je n'obtiens rien du tout en sortie:
curl 192.168.0.65/Jarvis 2>/dev/null | awk -F '*' '$1 ~ /^[0-9.]+$/ {print $1}' |sed ':a;N;$!ba;s/\n/ et temperature de /g'|sed -e 's/^/Humidité de /g'

Mon capteur est bien actif, il me retourne bien une page web:
```Bash
<html><head><title>Capteur</title></head><body><div id="temp"><TEMP>21.30</TEMP></div><BR><div id="hum"><HUM>55.70</HUM></div></body></html>
```

**Comment by pascalouRASP** [comment]
Je viens de tester avec Python et j'ai une erreur.
(J'ai fait un reboot du raspberry au cas où ce serait nécessaire après l'installation de python-bs4)
J'execute la ligne de commande : 
```Bash
echo -e "import bs4\nfrom urllib2 import urlopen\nsoup = bs4.BeautifulSoup(urlopen('http://192.168.0.65/Jarvis').read(), 'lxml')\nprint('Temperature de {0} degrés avec une humidité de {1} pourcents'.format(soup.find('div', {'id':'temp'}), soup.find('div', {'id': 'hum'})))" | python
```
Et j'obtiens l'erreur: 
```Bash
SyntaxError: Non-ASCII character '\xc3' in file <stdin> on line 4, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details
pi@raspberrypi:~/jarvis $ 
```
J'ai vu que c'était un problème d'encodage des caractères mais je ne sais pas comment corriger cette erreur.
Je pense que le plus simple serait d'appeler un script dans lequel je placerai toutes ces instructions mais je ne sais pas comment m'y prendre pour appeler un script à partir des commandes reconnues par jarvis.
Il me semble qu'il faut créer un fichier .py et lui donner les droits pour qu'il s'exécute mais côté Jarvis je ne sais pas comment l'appeler. (Le script doit être placé dans le dossier de jarvis ?)

**Comment by devauxa** [comment]
Enleve les "é" dans les strings, remplace les par "er"

**Comment by pascalouRASP** [comment]
Voilà ce que j'ai envoyé: (j'ai viré les caractères accentués)

```Bash
echo -e "import bs4\nfrom urllib2 import urlopen\nsoup = bs4.BeautifulSoup(urlopen('http://192.168.0.65/Jarvis').read(), 'lxml')\nprint('Temperature de {0} degrers avec une humiditer de {1} pourcents'.format(soup.find('div', {'id':'temp'}), soup.find('div', {'id': 'hum'})))" | python
```

Et l'erreur obtenue:
```Bash
Traceback (most recent call last):
  File "<stdin>", line 3, in <module>
  File "/usr/lib/python2.7/dist-packages/bs4/__init__.py", line 152, in __init__
    % ",".join(features))
bs4.FeatureNotFound: Couldn't find a tree builder with the features you requested: lxml. Do you need to install a parser library?
```

**Comment by devauxa** [comment]
Il semblerait qu'il faut lxml, tu peux tenter :
```
sudo apt-get install python-lxml
```

**Comment by pascalouRASP** [comment]
On y est presque !
```Bash
pi@raspberrypi:~/jarvis $ echo -e "import bs4\nfrom urllib2 import urlopen\nsoup = bs4.BeautifulSoup(urlopen('http://192.168.0.65/Jarvis').read(), 'lxml')\nprint('Temperature de {0} degres avec une humidite de {1} pourcents'.format(soup.find('div', {'id':'temp'}), soup.find('div', {'id': 'hum'})))" | python
Temperature de <div id="temp"><temp>21.30</temp></div> degres avec une humidite de <div id="hum"><hum>55.30</hum></div> pourcents
pi@raspberrypi:~/jarvis $
```

**Comment by devauxa** [comment]
Ah oui, j'ai oublié le .text au niveau des deux soup.find().text

**Comment by pascalouRASP** [comment]
Merci.
J'ai dû me planter dans la syntaxe ?

pi@raspberrypi:~/jarvis $ echo -e "import bs4\nfrom urllib2 import urlopen\nsoup = bs4.BeautifulSoup(urlopen('http://192.168.0.65/Jarvis').read(), 'lxml')\nprint('Temperature de {0} degres avec une humidite de {1} pourcents'.format(soup.find('div', {'id':'temp'}).txt, soup.find('div', {'id': 'hum'}).txt))" | python
Temperature de None degres avec une humidite de None pourcents

**Comment by devauxa** [comment]
J'aurais un jarvis sous la main ce soir si tu as un souci. J'ai mis un example pour la commande

**Comment by pascalouRASP** [comment]
Je te remercie pour ton aide.
Je vais continuer à chercher de mon côté comment intégrer cette commande sans avoir d'erreur.
Je suis un peu perdu avec tous ces caractères d'échappement mais je commence à saisir pas mal de trucs.

**Comment by pascalouRASP** [comment]
Je confirme que l'erreur provenait bien des ' que j'avais mis à la place des ``` ` ```
J'ai remplacé mes '  et tout fonctionne à présent.
Je ne sais absolument pas comment obtenir le caractère ` sur mon macbook.
Je l'ai copié collé à partir des exemples mais franchement c'était pas simple pour repérer l'erreur !

**Comment by alexylem** [comment]
Sur mon macbook le caractère d'échappement ` est juste à Gauche de la touche entrée sous le $ (il faut appuyer 2 fois pour l'avoir).
D'ailleurs il est devenu obsolète et je te conseille plutôt d'utiliser cette syntaxe pour exécuter des commandes:
```bash
say "`echo hello`" # works
say "$(echo hello)" # better way
```
