### ISSUE TITLE
Snowboy tourne en boucle infinie

### ISSUE THREAD

**Issue by alexylem** [alexylem/jarvis#18]
![image](https://cloud.githubusercontent.com/assets/11017174/16363229/7d80c5b8-3bc4-11e6-8359-cbd73022415e.png)

**Comment by alexylem** [comment]
Si vous rencontrez cette erreur, suivre les étapes suivantes:
```
cd stt_engines/snowboy/
python main.py resources/snowboy.umdl
```
Voici l'erreur que vous pourriez avoir:
```
ImportError: **libf77blas.so.3**: cannot open shared object file: No such file or directory
```

**Comment by Lezeper** [comment]
@alexylem Thanks!
