### ISSUE TITLE
envoyer une commande SAY à Jarvis depuis un autre ordinateur via http. Possible ?

### ISSUE THREAD

**Issue by pascalouRASP** [alexylem/jarvis#180]
Bonjour,

Je travaille toujours sur mes modules wifi et Jarvis.

Grâce à l'aide efficace du forum, je peut à présent interroger par exemple un capteur de température depuis Jarvis et obtenir en retour une réponse vocale.
Je cherche maintenant un moyen qui permettrait à l'inverse qu'un capteur puisse demander à Jarvis d'exécuter une commande SAY via une requête http.

Un exemple concret: A la maison j'ai un module qui surveille la température et la filtration d'un aquarium et qui gère l'éclairage et la nourriture des poissons.
Ce serait formidable de pouvoir avoir une alerte vocale automatique via Jarvis en cas de soucis. 
Il faudrait pour cela que le module puisse envoyer un ordre SAY à Jarvis via HTTP.
J'ignore si c'est possible.

Quelqu'un à une piste à me suggérer ?

**Comment by alexylem** [comment]
Tout à fait possible, tu as 2 possibilités:

- Soit c'est Jarvis qui monitor ton aquarium et te préviens si quelque-chose ne va pas (recommandé)

**Jarvis > Events**
```bash
0 * * * * ~/check_aquarium_is_ok.sh || ~/jarvis/jarvis.sh -s "Il y a un problème" # toutes les heures
```
Bien sûr c'est à toi de faire `check_aquarium_is_ok` et faire en forte qu'il renvoit un code erreur si les valeurs sont hors côte.

- Soit depuis ton monitoring existant tu demandes juste à Jarvis de parler à voix haute:

```bash
~/jarvis/jarvis.sh -s "Il y a un problème"
```

Si c'est depuis une machine distante tu peux exécuter avec cette commande avec SSH (recommandé si tu es sur le même réseau), car c'est dommage de devoir installer un serveur PHP juste pour ca...
