### ISSUE TITLE
wrong link on the "http://domotiquefacile.fr/jarvis/content/faq" website

### ISSUE THREAD

**Issue by Sispheor** [alexylem/jarvis#183]
The link "Quel micro ou enceintes dois-je utilise?" seems to be invalid. We are redirected to the [empty wiki on Github](https://github.com/alexylem/jarvis/wiki).

I think about that because I remember you had a page about tested microphone. I was thinking about buying the CM-1000 USB. Did you test it?

**Comment by alexylem** [comment]
http://domotiquefacile.fr/jarvis/content/prerequisites
Where is the broken link?

**Comment by Sispheor** [comment]
Here : http://domotiquefacile.fr/jarvis/content/faq

If you click on "Voir ici". (Quel micro ou enceintes dois-je utilise?)

Thx for the page I was looking for.

**Comment by alexylem** [comment]
Link fixed. Merci
