### ISSUE TITLE
column: command not found

### ISSUE THREAD

**Issue by taostaos** [alexylem/jarvis#186]
When I updated jarvis, I got this error

`./jarvis.sh: line 507: column: command not found`

Need to check if the package is installed =)

**Comment by alexylem** [comment]
Ooops, what distrib are you using?
```bash
head -n1 /etc/*release | cut -f2 -d=
```

**Comment by alexylem** [comment]
```
sudo apt-get install bsdmainutils
```
But now that I see it's not a standard command, I'm thinking if I should not remove this dependency...

**Comment by alexylem** [comment]
I found a way to do it manually, removing that dependency...

**Comment by taostaos** [comment]
"Debian GNU/Linux 8 (jessie)"

But I'm running inside the official [docker container](https://hub.docker.com/_/debian/) , I suppose they install the minimum. 

`apt-get install bsdmainutils`
That was my fix yesterday.

**Comment by alexylem** [comment]
I have removed the dependency so you can uninstall it if you don't need this package.

**Comment by Gilles76** [comment]
@taostaos ,

tu utilises docker ?

Je débute avec docker. pour ajouter la carte son, il semblerai qu'il faille ajouter "/dev/snd"

Tu utilises quoi pour lancer tes containers? ligne de commande, UI?

en ligne de commande cela ressemble à cela, mais le container ne se lance pas :+1: 
docker run -d --device=/dev/snd --name jarvis3 jarvis:dev2

il semblerai que ma syntaxe ne soit pas bonne à moins que cela soit un pb de droit sur /dev/snd".

Si tu as des infos, je suis preneur.

Le but si @alexylem est ok est de fournir un tuto pour utiliser un container jarvis.
