### ISSUE TITLE
Faux positif magic word avec SnowBoy

### ISSUE THREAD

**Issue by controlom** [alexylem/jarvis#187]
Bonjour,

Je ne sais pas si je suis seul dans ce cas mais j'ai jarvis qui se déclenche souvent sans meme prononcer le magic word.

Par ex: 
 Lorsque mon files de 2ans pleur ou crie :), ou encore avec la TV.

Le réglage : Snowboy sensitivity (0.5)
Je garde le micro desactivé pour éviter cela mais je trouve une solution pour éviter.

merci

**Comment by alexylem** [comment]
Beaucoup d'utilisateurs de Jarvis ont changé la sensibilité de Snowboy à 0.4.
Sinon tu peux mieux entrainer en hotword ou en choisir un plus compliqué / plus long.
Snowboy recommande des hotwords d'au moins 3 ou 4 syllabes.
