### ISSUE TITLE
Low pitch at the end of long spoken sentences

### ISSUE THREAD

**Issue by taostaos** [alexylem/jarvis#188]
tested : 
`./jarvis.sh -s "test test  test test test test test test test test test test test test test test test test test test test test test test test test test test test test test"`
The last five "test" are low pitched.

[audio sample](https://fromsmash.com/91baa69e-955f-11e6-ad20-068b54a51e61)

**Comment by alexylem** [comment]
Well spotted. Thanks for the sample.
What TTS are you using?

**Comment by taostaos** [comment]
Yeah sorry, didn't gave all the infos, I'm using bing

**Comment by alexylem** [comment]
`bing` is not (yet) available in the TTS engines 😄  did you mean `google` ?
Check in Settings > Speech Synthesis > Speech Engine

**Comment by taostaos** [comment]
Oh yeah no, sorry, I'm a bit tired, I'm using svox...

**Comment by alexylem** [comment]
Ok I tested the same:
```shell
./jarvis.sh -s "test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test"
```
on my raspberry pi 3 (I also have `svox_pico`) and it is fine. Of course a lower pitch at the end like finishing the sentence, but nothing like what you have.

Please directly try this:
```shell
/usr/bin/pico2wave -l fr-FR -w /tmp/test.wav "test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test" && aplay /tmp/test.wav
```

**Comment by taostaos** [comment]
Well, Jarvis code is fine. I only got the low pitch because I'm not using a temp file to convert the tts.wav to 44100 rate (jabra user). If you do something like `sox tts.wav -r 44100 tts.wav` , the conversion is going bad because you write on the file you read... 

Thx for the attention.

**Comment by alexylem** [comment]
Guys if I can help with Jabra please let me know (ex: integrate conversion in Jarvis to use two different file names...)

**Comment by taostaos** [comment]
As soon as I have a really stable solution I'll give you the changes I did.  The worst part is that maybe it's just an alsa config to do, but didn't found it ^^'
