### ISSUE TITLE
pkilling jarvis (in background) doesn't stop python used by snowboy

### ISSUE THREAD

**Issue by alexylem** [alexylem/jarvis#19]
```
$> ./jarvis.sh -b
$> pgrep -af jarvis.sh
6193 /bin/bash ./jarvis.sh -n
$> top
PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND    
 6263 pi        20   0   31328  12280   8524 S   5.6  1.4   0:04.51 python     
$> pkill -f jarvis
$> pgrep -af jarvis.sh
(no process)
$> top
PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND    
 6263 pi        20   0   31328  12280   8524 S   6.0  1.4   0:08.05 python     
```

**Problème**: relancer Jarvis va accumuler des process `python` (pour `snowboy`), solliciter de plus en plus le CPU et mettre en échec le micro.

**Comment by alexylem** [comment]
Je me retrouve régulièrement avec le CPU à 100% à cause d'un processus python `snowboy` qui traine.
Vérifier avec:
```
htop
pgrep -f python
pkill -f python
```

**Comment by alexylem** [comment]
En envoyant `SIGINT` (Ctrl+C) à Jarvis en mode rnomal, cela arrête bien le processus `snowboy`sigint

**Comment by alexylem** [comment]
J'arriver à stopper jarvis et ses sous process en tuant le groupe directement
```bash
$> ./jarvis.sh -b # jarvis lancé en tâche de fond
$> pgrep -fa jarvis.sh
14891 /bin/bash ./jarvis.sh -n # process id de jarvis.sh
$> pgrep -fa python
14965 python stt_engines/snowboy/main.py stt_engines/snowboy/resources/snowboy.umdl # process id de snowboy
$> ps -p 14891 -o pgid=
14882 # group id de jarvis.sh
$> kill -TERM -14882 # le (-) devant 14882 indique de tuer le groupe complet
$> pgrep -fa jarvis.sh
# aucun
$> pgrep -f python
# aucun
```
Voici la script pour tuer Jarvis proprement lorsqu'il est lancé en tâche de fond:
```bash
pid=pgrep -f jarvis.sh # process id de jarvis
gid=ps -p $pid -o pgid= # group id de jarvis
kill -TERM -$gid # tuer le group complet
```

**Comment by alexylem** [comment]
A été implémenté dans la mise à jour qui détecte si Jarvis tourne déjà en tâche de fond et propose de l'arrêter.

**Comment by trarizakaria** [comment]
re Alex j'espère que tu vas bien ! j'ai encore ce soucis. jarvis plante en mode service et puis j'arrive plus à l'arrêter 
./jarvis.sh -q me renvoie qu'il est fermé. mais il reste toujours en backround, seule solution c'est redémarrer le raspberry.
j'ai essayé de suivre ce qui est dit sur ce Issue mais j'arrive pas à comprendre
salutations
