### ISSUE TITLE
pulseaudio & bluetooth au démarrage

### ISSUE THREAD

**Issue by brakc** [alexylem/jarvis#191]
Bonjour,

J'ai une petite install très sympa de Jarvis sur sur RPI3. mais je me pause une petite question?

Y a til un tuto clair pour pour apairer le périphérique bluetooth et lancer "pulseaudio --start" apres un reboot? et pourquoi pas lancer Jarvis aussi d'ailleurs ...

J'ai trouvé ce lien, mais cela me semble un peu compliqué: https://github.com/davidedg/NAS-mod-config/blob/master/bt-sound/bt-sound-Bluez5_PulseAudio5.txt

Y a t il une façon plus simple de lancer le service pulseaudio et d'apairer de device bluetooth?

Merci de votre aide.

Fabrice.

**Comment by alexylem** [comment]
Discuté ici: #110 
Il y a un tuto proposé dans l'un des derniers posts.

**Comment by brakc** [comment]
OK merci!
