### ISSUE TITLE
Jarvis reste dans la discussion imbriquée malgré un timeout ou 3 mauvaises réponses

### ISSUE THREAD

**Issue by NikoS34** [alexylem/jarvis#192]
### Description
J'ai ajouté une commande imbriquée au fichier jarvis-commands:

```shell
MONTE*SON*BUREAU*==jv_curl "http://192.168.xxx.xxx:nnnnn/bureau/volume/+2"; say "ça te va maintenant ?"
>*OUI*==say "a ton service"
>*NON*==jv_curl "http://192.168.xxx.xxx:nnnn/bureau/volume/+3"
```

### Result
dans le cas où je ne réponds pas ou si ma réponse n'est pas bien comprise (sur les 3 essais...), jarvis repasse "normalement" en mode écoute, détecte bien mon mot clé (config snowboy) mais ne comprend plus une seule commande (comme version par exemple).

**Comment by alexylem** [comment]
>si ma réponse n'est pas bien comprise (sur les 3 essais...)

Soit tu testes Jarvis aux limites, soit ta reco n'est pas très efficace 😄 
Je regarde...

**Comment by NikoS34** [comment]
Merci.
La reco est bonne, je vois bien le retour du texte dans la console:
jarvis: Je ne comprends pas: version

**Comment by NikoS34** [comment]
j'avais pas capté le smiley... effectivement la reco ratée sur 3 essais c'est du testing !
Par contre le fait de ne pas être obligé de continuer la conversation dans une commande imbriquée c'est vraiment de l'usage !

**Comment by alexylem** [comment]
J'ai testé en fait Jarvis reste dans la commande imbriquée et attends toujours sa réponse...
```shell
Alexa: Waiting to hear 'Alexa'
Alex: Alexa
Alexa: Oui?
Alex: ça va
Alexa: Très bien et toi ça va?
Alex: ??? # 3 essais ratés
Alexa: Waiting to hear 'Alexa'
Alex: Alexa
Alexa: Oui?
Alex: oui # réponse à la question précédente, n'est pas une commande valide sinon
Alexa: ravi de l'entendre
```
On peut appeler ca de la persévérance ou de l'entêtement...
En effet logiquement on devrait sortir de la commande imbriquée au timeout ou après 3 essais râtés.

**Comment by alexylem** [comment]
Corrigé:
```yml
Alex: Jarvis
Jarvis: Oui?
Alex: ça va
Jarvis: Très bien et toi ça va?
Alex: ???
Jarvis: Waiting to hear 'Jarvis'
Alex: Jarvis
Jarvis: Oui?
Alex: au revoir
Jarvis: Au revoir Alex
```
