### ISSUE TITLE
Not possible to train hotword at installation before Mic not yet set up

### ISSUE THREAD

**Issue by NYGHOST** [alexylem/jarvis#193]
je remarque qu'en réinstallant Jarvis, et que l'on souhiate utiliser notre propre hotword ex "paul", il est impossible de trainer le model et donc de pouvoir continuer l'install, en faute, les micros/enceintes n'étant pas initialiser "rec FAIL formats: cant open input 'defaut: snd_pcm_open" typique il me semble de l'absnce de réglage des micro/enceinte. il faut obligatoirement conserver snowboy pour pouvoir par la suite modifier le hotword.

**Comment by alexylem** [comment]
Wow... effectivement c'est gênant... je règle ca ce soir

**Comment by NYGHOST** [comment]
je remarque aussi que svox est tres long a s'installer maintenant (javais pas fait de mis a jour de Jarvis depuis juillet...) pas mal de grosse modif bravo

**Comment by alexylem** [comment]
Je vais re-tester l'installation complète.
Je t'encourage à activer la mise à jour automatique au démarrage :smile:
