### ISSUE TITLE
erreur avec plugin Freebox

### ISSUE THREAD

**Issue by Chris54220** [alexylem/jarvis#194]
Bonjour j'ai un petit soucis avec le plugin de la Freebox

alors j'ai 2 lecteur  donc j'ai changer le fichier commande pour que les commande fonctionne sur hd2 au lieu de hd1

mais sa me renvois cela 

Forbidden
 You don't have permission to access this file on this server.
Cheyenne/2.2.8 Server at localhost Port 80

**Comment by alexylem** [comment]
Il te faut logger le pb sur le github du plugin:
Jarvis > Store > Installed > Freebox > Report an Issue

**Comment by wikijm** [comment]
Pour information, l'issue crée par @Chris54220 est [ici](https://github.com/wikijm/jarvis-freeboxplayer/issues)
