### ISSUE TITLE
Say énonce toutes les commandes lorsque la chaine à dire est vide

### ISSUE THREAD

**Issue by Thib0o** [alexylem/jarvis#195]
Bonjour,

Tout d'abord je tiens à vous remercier pour l'ensemble du travail effectué sur la reconnaissance vocale.

Depuis quelques temps, (depuis la création du store et des nouveaux plugins) la version proposée rentre en conflit avec les commandes simples que j'ai pu développer. 
Ces commandes étaient exécuter suite à l'appel de script bash en utilisant la fonction "say". Ainsi, je pouvais développer un script plus ou moins long sans l'intégrer directement dans le fichier "jarvis-commands". Cependant, votre travail sur la mise en place du store qui est un travail fort utile et appréciable a dû (je pense) nécessité une modification de la fonction "say" en introduisant cette ligne de commande : 
"   set -- "${1:-$(</dev/stdin)}" "${@:2} "   ". Or cette ligne de commande indispensable pour les plugins du store, énonce l'ensemble des commandes inscrites dans le fichier "jarvis-commands" lorsque je fais appel à l'un de mes scripts bash. Commenter cette dernière me permet de réutiliser mes scripts correctement mais ne me permet pas d'utiliser le store. 

Voici un petit exemple : 

"jarvis-commands" : 
*ANNULE* |*TERMINE* ==bypass=false; say "Ok"
*TOTO* == say `/home/pi/jarvis/modules/toto.sh`
*TEST* == say "Ca fonctionne!"

- Execution de jarvis.sh

- Moi : ANNULE ; Jarvis : Ok ; en attente d'autres commandes

==> fonctionnement OK
- Moi : TOTO ; Jarvis : (réalisation du script puis ennonce) *ANNULE* |*TERMINE* ==bypass=false; say "Ok" *TOTO* == say `/home/pi/jarvis/modules/toto.sh` *TEST* == say "Ca fonctionne!" ; en attente d'autres commandes

==> fonctionnement NOK

J'espère avoir été assez clair et je répondrai à vos interrogations avec plaisir. En attendant vos retours, je continue mes recherches pour pouvoir faire cohabiter l'utilisation du store et de simples scripts ^^.

Thib0o

**Comment by alexylem** [comment]
Je ne pense pas qu'il y ait un lien avec le store, essaye simplement:
```shell
TOTO==say $(/home/pi/jarvis/modules/toto.sh)
```

**Comment by Thib0o** [comment]
Cette commande rencontre le même résultat que 
TOTO == say `/home/pi/jarvis/modules/toto.sh`

Je ne suis pas assez calé en langage LINUX pour comprendre complétement ce que fait la première ligne de commande de la fonction "SAY" ( " set -- "${1:-$(</dev/stdin)}" "${@:2} " )mais l'origine vient de là. Une fois cette dernière commenté je peux exécuter mes scripts sans soucis.

**Comment by alexylem** [comment]
Cette première ligne permet d'utiliser `say` ainsi:
```shell
$> say "hello world"
Jarvis: hello world
$> echo "hello world" | say
Jarvis: hello world
```
Essaye avec les guillemets...
```
TOTO==say "$(/home/pi/jarvis/modules/toto.sh)"
```
Sinon une petite copie de ton terminal et du contenu du script seraient utiles...

**Comment by Thib0o** [comment]
Je te remercie pour ton aide. Après un essai, j'obtiens toujours la même chose.
Voici un screenshot d'un exemple de script et du terminal.

![capture_bug_script](https://cloud.githubusercontent.com/assets/18536689/19742426/5189203e-9bc5-11e6-9a9d-e10b9788d56b.PNG)
![capture_bug_terminal](https://cloud.githubusercontent.com/assets/18536689/19742427/5190d9dc-9bc5-11e6-8853-e7e4220878b4.PNG)

**Comment by alexylem** [comment]
Bon déjà ton script il ne sort pas de texte, donc il n'a rien à dire.
Dans ce cas tu peux remplacer ta commande par:
```shell
*RADIO*VIRGIN*==say "Ok" && /home/pi/jarvis/modules/radio_virgin.sh
```
Aussi par curiosité, que se passe-t-il si tu lances ton script en dehors de Jarvis?
```shell
$> /home/pi/jarvis/modules/radio_virgin.sh
```
Merci

**Comment by Thib0o** [comment]
*RADIO*VIRGIN*==say "Ok" && /home/pi/jarvis/modules/radio_virgin.sh
Cette commande m'as engendré le même problème. 

Une autre solution simple et efficace et de mettre directement le script appelé :
*RADIO*VIRGIN*== /home/pi/jarvis/modules/radio_virgin.sh

Le scrip utilisé par lui même réalise ses fonctions. Dans ce cas précis, il tue les programmes VLC, joue un fichier son (Jarvis qui dit OK), lance un url sur VLC en ouvrant une autre fenêtre de terminal (ne pas occuper le terminal où s’exécute Jarvis)

**Comment by alexylem** [comment]
Attends tu es en train de me dire que le moindre `say` te fait ce problème?
Essayes:
```shell
$> ./jarvis.sh -x "merci"
```

**Comment by devauxa** [comment]
Si je comprends bien il faut que tu rediriges ta sortie d'erreur (2) et t'a sortie standard vers /dev/null, comme cela par exemple : 

``
vlc http://vr-live-mp3-128.scdn.arkena.com/virginradio.mp3 2>/dev/null 1>&2 &
``


Ici, je redirige stderr vers /dev/null (un vide sans fond d'unix) et stdout vers stderr

Par contre, je ne comprends pas l'utilité de la fin de ton script (sleep 2 puis exit 0 et ton && exit 0)

**Comment by Thib0o** [comment]
Autant pour moi, le test effectué était le suivant :  
\*RADIO\*VIRGIN\*==say " " && /home/pi/jarvis/modules/radio_virgin.sh

J'en conclue donc que lorsque je mettais cette ligne de commande : 
\*RADIO\*VIRGIN\*==say \`/home/pi/jarvis/modules/radio_virgin.sh\ `
Il exécutait le script puis considéré la fonction "SAY" vide ce qui réalise une énonciation des lignes de commandes du fichier "jarvis-commands". (La raison de cela pour moi reste flou)

**Comment by alexylem** [comment]
AAAAh ben voila où est le problème, je confirme je reproduis chez moi, je vais corriger ca...

**Comment by Thib0o** [comment]
@devauxa 
euh effectivement je ne sais plus pourquoi j'ai l'instruction " && exit 0" (sans cela fonctionne je viens de tester)
Par contre, mon " sleep 2 " permet d'effectuer une temporisation (utile lorsque il veut enchainer certaines actions qui lui prenne du temps à mettre en place) avant de sortir du script proprement avec le dernier " exit 0 "

@alexylem 
Content d'avoir pu aider un minimum. En tout cas, je tiens à te remercier pour ce travail, c'est VRAIMENT GENIAL !!!

**Comment by alexylem** [comment]
Corrigé, mettez à jour.
Tu avais raison j'ai du virer la ligne:
```shell
set -- "${1:-$(</dev/stdin)}" "${@:2}"
```
Car lorsque `$1` est vide il lisait depuis `stdin` (voulu) mais si `stdin` n'était pas fourni alors il lisait dans les commandes car c'est ainsi que le code est construit dans la boucle.
On ne peut donc plus utiliser `say` de cette façon:
```shell
$> echo "hello world" | say
Jarvis: # maintenant c'est vide
```
