### ISSUE TITLE
update flag for jarvis.sh

### ISSUE THREAD

**Issue by Damien60** [alexylem/jarvis#197]
Is it possible to add a flag to force the update (maybe -u) without interaction?
I would like to automatically update jarvis with cron like I do with "sudo apt-get update -y; sudo apt-get upgrade -y". Please, keep the changelog output.
Label enhancement, Priority minor.

By the way, great job for your job Alexandre.
Damien, a french user :-)

**Comment by alexylem** [comment]
Ok. It will update without interaction (without "are you sure?" question). I will also include the update of all installed plugins.

**Comment by alexylem** [comment]
![image](https://cloud.githubusercontent.com/assets/11017174/19721290/e7f91e56-9b71-11e6-9f69-beda90fa66b9.png)
