### ISSUE TITLE
Problème de reconnaissance vocale avec BING

### ISSUE THREAD

**Issue by teubize** [alexylem/jarvis#199]
Bonjour,

je suis sur un raspberry 1, et la reconnaissance vocal avec BING ne fonctionne pas correctement.
j'ai bien la Key API, j'ai configuré avec BING pour les commandes et SNOWBOY pour les Keywords.
Snowboy fonctionne.
mais pour les commandes ça fait des # à la suite.
il n'y que le soir du 25/10/2016 suite à une mise à jour que ça à fonctionné correctement. mais le lendemain j'ai fait la mise à jour qu'il demandé et c'est revenu avec les #.

si quelqu'un a eu le même problème.

**Comment by alexylem** [comment]
`#` veut dire que le son enregistré est trop long. Tu peux le vérifier en lançant Jarvis en mode troubleshooting.
Ceci est généralement lié à la sensibilité de ton micro, qui fait que le silence attendu pour arrêter d'écouter la commande n'est pas détecté, voir #135 et #33 
Les pistes pour le résoudre sont:
- Couper les bruits en arrière plan (télé, fenêtres, ...)
- Baisser sensibilité du micro (dans les settings)
- Si ca marche toujours pas (rare), changer les niveaux de détections de sox (dans les settings)

**Comment by teubize** [comment]
merci, pour les info sa fonctionne nickel.

**Comment by alibari** [comment]
Bonjour, 
j'ai le meme probleme avec Bing, j'ai tout tester et je sais plus quoi faire, Je dois presenter mon projet ce vendredi 23juin, j'ai besoin d'aide c URGENT !!! plz 
Et merci d'avance

**Comment by wikijm** [comment]
Merci de créer une nouvelle issue en fournissant les résultat du mode debugging.

**Comment by satana888** [comment]
Bonjour,

 

Par Hazard ? tu l’a pas mal utilisé, testé en vocal ? car je me demande quand même si on aurai pas épuisé le quota admis par mois ? je sais pas suis pas sûr, mais je recherche des solutions qui auraient pu nous faire ça soudainement… car c’est un super projet mais après 5 jours de non fonctionnement… ça commence à ne plus ressemblé a rien L et de jour en jour je suis déçu…..

J’ai investi pas mal de temps a tout configurer et j’étais plein de projet encore…. 

Le pire c’est de ne même pas avoir une autre solution… valable pour la reconnaissance de voix… car tous les autres il n’y a rien qui fonctionne correctement ou très mal expliqué.

Que faire, que faire…. 

 

C’est quelques choses qui peut tomber en panne 1 jour maximum… mais autant de temps…….

 

 

De : alibari [mailto:notifications@github.com] 
Envoyé : mercredi 21 juin 2017 02:28
À : alexylem/jarvis
Cc : Subscribed
Objet : Re: [alexylem/jarvis] Pourquoi des # s'affiche lors de la reconnaissance vocale avec Bing (#199)

 

Bonjour,
j'ai le meme probleme avec Bing, j'ai tout tester et je sais plus quoi faire, Je dois presenter mon projet ce vendredi 23juin, j'ai besoin d'aide c URGENT !!! plz
Et merci d'avance

**Comment by wikijm** [comment]
Cette issue est close car @alibari l'a déclarée comme résolu ici : https://github.com/alexylem/jarvis/issues/199#issuecomment-256586917
Merci de créer une nouvelle issue en fournissant les résultat du mode debugging.
