### ISSUE TITLE
PocketSphinx doesn't seem to be installed

### ISSUE THREAD

**Issue by dlsagayaraj** [alexylem/jarvis#2]
Failed ininstallation with the folowintn error 
The program is looking for "Translation-en" but in the repo we only have Translation-en.gz and Translation-en.xz in 
http://ports.ubuntu.com/dists/xenial-backports/restricted/i18n/

E: Failed to fetch http://ports.ubuntu.com/dists/xenial-backports/restricted/source/Sources  Empty files can't be valid archives
E: Failed to fetch http://ports.ubuntu.com/dists/xenial-backports/universe/source/Sources  Empty files can't be valid archives
E: Failed to fetch http://ports.ubuntu.com/dists/xenial-backports/multiverse/source/Sources  Empty files can't be valid archives
E: Failed to fetch http://ports.ubuntu.com/dists/xenial-backports/restricted/binary-armhf/Packages  Empty files can't be valid archives
E: Failed to fetch http://ports.ubuntu.com/dists/xenial-backports/restricted/i18n/Translation-en  Empty files can't be valid archives
E: Failed to fetch http://ports.ubuntu.com/dists/xenial-backports/universe/binary-armhf/Packages  Empty files can't be valid archives
E: Failed to fetch http://ports.ubuntu.com/dists/xenial-backports/universe/i18n/Translation-en  Empty files can't be valid archives
E: Failed to fetch http://ports.ubuntu.com/dists/xenial-backports/multiverse/binary-armhf/Packages  Empty files can't be valid archives
E: Failed to fetch http://ports.ubuntu.com/dists/xenial-backports/multiverse/i18n/Translation-en  Empty files can't be valid archives
E: Some index files failed to download. They have been ignored, or old ones used instead.
E: Encountered a section with no Package: header
E: Problem with MergeList /var/lib/apt/lists/ports.ubuntu.com_dists_xenial-backports_main_binary-armhf_Packages
E: The package lists or status file could not be parsed or opened.

**Comment by alexylem** [comment]
Looks like this error occurs within the install script of PocketSphinx.
Would you please provide which step you were at? Make sure the update/upgrade steps went fine.

**Comment by alexylem** [comment]
@dlsagayaraj 
Please provide details or I'll close the issue
Merci de fournir plus d'information ou je fermerai ce ticket

**Comment by physicien** [comment]
Vu qu'il n'y a pas eu d'activité de @dlsagayaraj sur le post depuis 18 jours je prends la liberté de fermer ce ticket.
