### ISSUE TITLE
Pas de reconnaissance mic interne

### ISSUE THREAD

**Issue by dud29** [alexylem/jarvis#201]
Bonjour,
je suis sur orange pi. L 'installation se passe correctement, le micro est reconnu et le test fonctionne bien. Par contre lors de l'utilisation, ça ne fonctionne pas. J'ai remarqué que la ligne microphone est vide (voir si dessous). Je pense (je n'ai pas de compétence en programmation) que le fait que ce soit un micro intégré pose problème. Si ça peut aider lorsque j'essaye de créer un trigger snowboy il m'affiche l'erreur suivante :  {"microphone":["This field may not be blank."]}.
Merci pour l'aide que vous pourrez m'apporter.
------------ Config ------------
jv_version           16.10.26
system               Linux 3.4.112-sun8i armv7l os

"Debian GNU/Linux 8 (jessie)"
language             fr_FR
play_hw              hw:0,0
rec_hw               hw:0,0
speaker              audiocodec
microphone
trigger_stt          pocketsphinx
command_stt          pocketsphinx
tts_engine           svox_pico
conversation_mode    true

**Comment by alexylem** [comment]
Le fait que le micro soit vide n'est pas en soit un problème, du moment qu'il marche dans le set-up.
Je vois dans ton setup que tu utilises pocketsphinx. Je te conseille plutôt d'utiliser snowboy pour la reco du hotword et bing pour la reco de la commande.
Tu peux changer et faire un test en lancant Jarvis en mode troubleshooting et coller ici le résultat de la console?
Merci!

**Comment by dud29** [comment]
j'ai déjà ait des tests avec snowboy, il affiche silence à l'infini, même si je crie dans le micro. Avec pocketsphinx j'ai joué le fichier jarvis-record.wav à priori ça donne rien alors que si je fais un rec t.wav l'enregistrement fonctionne. Je refais un test avec snowboy.

**Comment by alexylem** [comment]
jarvis-record.wav n'est pas utilisé pour snowboy, uniquement pour pocketsphinx et bing.
Si tu vas dans Settings > Audio > Mic le test du micro fonctionne?
Si oui tu peux quand même coller le résultat de la console en mode troubleshooting que je vérifie quels models sont actifs?
Merci

**Comment by dud29** [comment]
J'ai réinstalle snowboy, maintenant ça fonctionne. Désolé pour le ticket inutile.

**Comment by alexylem** [comment]
Ok, je ferme, pas de soucy c'est un plaisir d'aider
