### ISSUE TITLE
erreur a l'install 

### ISSUE THREAD

**Issue by Chris54220** [alexylem/jarvis#202]
bonjour j'ai une erreur que je veux install Jarvis au niveau de mic voila mon erreur

rec FAIL formats: can't open input  `default': snd_pcm_open error: No such file or directory
Selection of the microphone device
***\* Liste des Périphériques Matériels CAPTURE ****
carte 1: Device [USB PnP Sound Device], périphérique 0: USB Audio [USB Audio]
  Sous-périphériques: 1/1
  Sous-périphérique #0: subdevice #0
Indicate the card # to use [0-9]:

**Comment by alexylem** [comment]
Justement la il te demande d'indiquer la carte à utiliser, tu n'as qu'à choix:
Card: 1
Périphérique: 0
Donc écris 1 et Enter; puis 0 et Enter :smile:

**Comment by alexylem** [comment]
@Chris54220 Tu as pu résoudre ton problème?

**Comment by Chris54220** [comment]
Oui oui merci faut juste que je trouve un autre micro car celui que j'ai
pas assez puissant

Christopher JOLLY

**Comment by alexylem** [comment]
http://domotiquefacile.fr/jarvis/content/prerequisites
