### ISSUE TITLE
Jarvis ne semble pas m'entendre alors que je me suis entendu lors de l'installation

### ISSUE THREAD

**Issue by Darkjeje** [alexylem/jarvis#203]
### Description

Bonjour à tous,
C'est avec grand plaisir que j'ai installer Jarvis sur mon rasp, mais que je bloque avec Snowboy.
Lorsque je laisse snowboy comme mot clef, je n'arrive pas à le faire sortir de l'écoute, il ne me reconnait pas et je ne sais pas pourquoi.

Quand je change le mot clef en mettant Jarvis, il me demande de prononcer 3 fois Jarvis ce que je fais.
Mais lors du mixage il me sors une erreur : 
Le code : 
Input File     : 'default' (alsa)
Channels       : 1
Sample Rate    : 16000
Precision      : 16-bit
Sample Encoding: 16-bit Signed Integer PCM

In:0.00% 00:00:04.61 [00:00:00.00] Out:65.5k [      |      ] Hd:1.2 Clip:0    ^C
Aborted.

Input File     : 'default' (alsa)
Channels       : 1
Sample Rate    : 16000
Precision      : 16-bit
Sample Encoding: 16-bit Signed Integer PCM

In:0.00% 00:00:04.10 [00:00:00.00] Out:57.3k [      |      ] Hd:0.0 Clip:0    ^C
Aborted.

Input File     : 'default' (alsa)
Channels       : 1
Sample Rate    : 16000
Precision      : 16-bit
Sample Encoding: 16-bit Signed Integer PCM

In:0.00% 00:00:03.07 [00:00:00.00] Out:41.0k [      |      ] Hd:0.1 Clip:0    ^C
Aborted.
Training model...
######################################################################## 100.0%
{"detail":"Authentication credentials were not provided."}
ERROR: error occured while training the model
pi@raspberrypi:~/jarvis $

Lorsque je lance le mode troubleshooting, j'obtiens ceci.

pi@raspberrypi:~/jarvis $ ./jarvis.sh
Checking for updates...[Up-to-date]

------------ Config ------------
jv_version           16.10.26
system               Linux 4.4.21+ armv6l
os                   "Raspbian GNU/Linux 8 (jessie)"
language             fr_FR
play_hw              false
rec_hw               hw:1,0
speaker              Default
microphone           Nam Tai E&E Products Ltd. or OmniVision Technologies, Inc. Sony Playstation Eye
trigger_stt          snowboy
command_stt          bing
tts_engine           svox_pico
conversation_mode    true
--------------------------------

DEBUG: program_startup hook
snowboy: Bonjour
ANNULE*|TERMINE*        *AIDE*                  *COMMENT*APPELLE*
"Bonjour $username" *AU *TEST*                  *REPETE (*) ET (*)
*EST CE QUE MARIE-CAMIL *ALLUME*                *ETEIN*
snowboy: Waiting to hear 'snowboy'
Monsieur: (listening...)
DEBUG: models=snowboy
ALSA lib confmisc.c:1286:(snd_func_refer) Unable to find definition 'cards.bcm2835.pcm.front.0:CARD=0'
ALSA lib conf.c:4259:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:4738:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM front
ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.rear
ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.center_lfe
ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.side
ALSA lib confmisc.c:1286:(snd_func_refer) Unable to find definition 'cards.bcm2835.pcm.surround51.0:CARD=0'
ALSA lib conf.c:4259:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:4738:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM surround21
ALSA lib confmisc.c:1286:(snd_func_refer) Unable to find definition 'cards.bcm2835.pcm.surround51.0:CARD=0'
ALSA lib conf.c:4259:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:4738:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM surround21
ALSA lib confmisc.c:1286:(snd_func_refer) Unable to find definition 'cards.bcm2835.pcm.surround40.0:CARD=0'
ALSA lib conf.c:4259:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:4738:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM surround40
ALSA lib confmisc.c:1286:(snd_func_refer) Unable to find definition 'cards.bcm2835.pcm.surround51.0:CARD=0'
ALSA lib conf.c:4259:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:4738:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM surround41
ALSA lib confmisc.c:1286:(snd_func_refer) Unable to find definition 'cards.bcm2835.pcm.surround51.0:CARD=0'
ALSA lib conf.c:4259:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:4738:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM surround50
ALSA lib confmisc.c:1286:(snd_func_refer) Unable to find definition 'cards.bcm2835.pcm.surround51.0:CARD=0'
ALSA lib conf.c:4259:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:4738:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM surround51
ALSA lib confmisc.c:1286:(snd_func_refer) Unable to find definition 'cards.bcm2835.pcm.surround71.0:CARD=0'
ALSA lib conf.c:4259:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:4738:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM surround71
ALSA lib confmisc.c:1286:(snd_func_refer) Unable to find definition 'cards.bcm2835.pcm.iec958.0:CARD=0,AES0=4,AES1=130,AES2=0,AES3=2'
ALSA lib conf.c:4259:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:4738:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM iec958
ALSA lib confmisc.c:1286:(snd_func_refer) Unable to find definition 'cards.bcm2835.pcm.iec958.0:CARD=0,AES0=4,AES1=130,AES2=0,AES3=2'
ALSA lib conf.c:4259:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:4738:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM spdif
ALSA lib confmisc.c:1286:(snd_func_refer) Unable to find definition 'cards.bcm2835.pcm.iec958.0:CARD=0,AES0=4,AES1=130,AES2=0,AES3=2'
ALSA lib conf.c:4259:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:4738:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM spdif
ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.hdmi
ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.hdmi
ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.modem
ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.modem
ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.phoneline
ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.phoneline
ALSA lib pulse.c:243:(pulse_connect) PulseAudio: Unable to connect: Connection refused

ALSA lib pulse.c:243:(pulse_connect) PulseAudio: Unable to connect: Connection refused

Cannot connect to server socket err = No such file or directory
Cannot connect to server request channel
jack server is not running or cannot be started
INFO:snowboy:Silence
INFO:snowboy:Silence
INFO:snowboy:Silence
INFO:snowboy:Silence
INFO:snowboy:Silence
INFO:snowboy:Silence
INFO:snowboy:Silence
INFO:snowboy:Silence
INFO:snowboy:Silence
INFO:snowboy:Silence
INFO:snowboy:Silence

Auriez-vous une idée ?

**Comment by Darkjeje** [comment]
Bon finalement j'ai créé ma voix Jarvis avec l'ancienne méthode sur le site web et j'ai copié le son sur le rasp et cela fonctionne ;)

**Comment by taostaos** [comment]
"Authentication credentials were not provided" -> tu n'as pas créé le token snowboy sur le site.

@alexylem , je n'ai pas encore pris le temps de réinstaller snowboy, tu as bien demandé à un endroit le token ?  si oui, il faut catch l'erreur ci dessus, et ne pas proposer a la personne de changer son hotword a mon avis, ca évitera ce genre de pb...

**Comment by Darkjeje** [comment]
Bonjour taostaos,

Oui je vois bien l'erreur mais je ne l'a comprends pas, dans le sens où j'ai créé mon token snowboy et que je l'ai copié dans Jarvis.sh.
Bon j'ai finalement contourné la chose en téléchargeant directement mon fichier son Jarvis dans mon rasp. J'espère que cela ne va pas me bloquer ultérieurement. Car si j'ai bien compris snowboy me permettra de créer des phrases rapides qui permettront de déclencher une action via Jarvis et cela pourra m'être utile.

J'ai testé le plugin my home et cela fonctionne plutôt bien avec ma domotique legrand/bticino pour ce qui est des lumière.
J'ai dupliqué le plugin pour faire de même avec les volets, ça fonctionne mais dans ce cas le plugin pour les lumières ne fonctionnent plus.
Je vais me pencher sur le code car je n'y connais rien, donc comme à l'époque pour le php, va falloir que j'apprenne ;)
J'espère créer un plugin concurrent/complémentaire pour gérer la domotique legrand/bticino (Lumière/volet/obtenir la température) et aussi pouvoir avoir la vrai voix de Jarvis dans le film en utilisant des fichiers sons. Bref j'ai hâte de me pencher dans cette super appli et d'y apporter ce que je pourrai !!!
Bonne journée à tous

**Comment by alexylem** [comment]
@taostaos normalement il devrait demander le token avant de trainer le hotword. Il faut que je reteste une installation complète pour voir.
Par contre voir #198 il semblerait que snowboy n'accèpte par certain token même valides. Je serais tenté de créer une issue chez eux...
https://github.com/kitt-ai/snowboy/issues/new
@Darkjeje oui tu peux aussi créer des quick commands manuellement en attendant de trouver un token valide:
domotiquefacile.fr/jarvis/content/snowboy
Aussi j'aimerai améliorer le plugin home-control avec tes retours, tu souhaiterais ajouter des commandes de type "Monte/Descend" "Ouvre/Ferme" et "Obtient température" c'est ca? Si oui est-ce que tu peux créer un ticket sur le repo du plugin je le ferai (rapidement):
https://github.com/alexylem/jarvis-home-control/issues/new

**Comment by Darkjeje** [comment]
@alexylem merci pour ton retour.
J'ouvre un ticket pour expliquer ce que j'ai, ce que j'ai déjà fait et ce que j'aimerai faire, avec Jarvis ;)

**Comment by alexylem** [comment]
Ok du coup je ferme le ticket. N'hésites pas à contacter les créateurs de snowboy pour le problem de token, tu n'es pas le premier à avoir ce soucis.
