### ISSUE TITLE
Bonjour... je suis équipé d'un Raspberry PI3 avec Domoticz.... Pas de reconnaissance Voval pour les commandess

### ISSUE THREAD

**Issue by Jean-Bernard-Hallez** [alexylem/jarvis#204]
J'ai trouvé enfin ce que je recherche !!!
J'ai installé Jarvis... il reconais bien ma voix (avec snowboy) mais pour déclencher la commande là... il y a plus rien que des #.... là j'ai tout essayé Bing, wit, Pocketsphinx et il reste sans voix ! lol
Je ne sais pas quoi faire... j'ai suivi le tutos pour les clef API.
Meci de votre aide.

**Comment by alexylem** [comment]
`#` veut dire que le son enregistré est trop long. Tu peux le vérifier en lançant Jarvis en mode troubleshooting.
Ceci est généralement lié à la sensibilité de ton micro, qui fait que le silence attendu pour arrêter d'écouter la commande n'est pas détecté, voir #135 et #33 
Les pistes pour le résoudre sont:
- Couper les bruits en arrière plan (télé, fenêtres, ...)
- Baisser sensibilité du micro (dans les settings)
- Si ca marche toujours pas (rare), changer les niveaux de détections de sox (dans les settings)
