### ISSUE TITLE
probleme jarvis

### ISSUE THREAD

**Issue by PAPOU59** [alexylem/jarvis#205]
Bonjour

Merci, réponse super rapide 
un deuxième petit soucis, là le son ne marche plus, j'ai essayé de refaire l'installation du son, mais ça arrive directement à la détection du micro sans passer par la détection de la sortie son. j'avais mis 0-0 pour le son et 1-0 pour le micro lors de l'installation et ça fonctionner.
bref je t'envoie se qui s'affiche en mode troubleshooting 

```shell
pi@raspberrypi:~ $ cd jarvis
pi@raspberrypi:~/jarvis $ ./jarvis.sh
Checking updates for jarvis...Up-to-date

------------ Config ------------
jv_version           16.11.01 
system               Linux 4.4.26-v7+ armv7l 
os                   "Raspbian GNU/Linux 8 (jessie)" 
language             en_GB 
play_hw              hw:0,0 
rec_hw               hw:1,0 
speaker              ALSA 
microphone           Midiman  
trigger_stt          snowboy 
command_stt          bing 
tts_engine           svox_pico 
conversation_mode    false 
--------------------------------

DEBUG: program_startup hook
snowboy: Hello
play FAIL formats: can't open output file `default': snd_pcm_open error: No such file or directory
ERROR: play command failed
HELP: Verify your speaker in Settings > Audio > Speaker
DEBUG: program exit handler
DEBUG: program_exit hook
pi@raspberrypi:~/jarvis $ 
```

Cdt

**Comment by alexylem** [comment]
@PAPOU59 donc tu as eu le problème en faisant quoi exactement? Tu parles d'une réinstallation, mais tu as fait quoi exactement? (Wizard via le menu? Audio Settings? ./jarvis.sh -i?)
Si je comprends bien c'est passé au test du micro directement mais c'est normal si tu as choisi Settings > Audio > Mic..

**Comment by alexylem** [comment]
timeout
