### ISSUE TITLE
jarvis n'entend pas les commandes

### ISSUE THREAD

**Issue by manattom** [alexylem/jarvis#207]
Bonjour,
Nouveau utilisateur de Jarvis, j ai un micro trixe, Jarvis comprend les commandes rapides avec snowboy, mais pas les autres commandes. 
Quand Jarvis répond "oui" et que je demande une commande, j'ai en réponse "." ou "?"
si je dois changer de micro lequelle conseillez vous
en vous remerciant

**Comment by manattom** [comment]
petite précision, j'ai fait le test de bing(./test.sh) ça fonctionne

**Comment by Gilles76** [comment]
Quand vous lancer jarvis en debug ou keyboard, avez-vous une liste de commande avec des asterisk affiché.

**Comment by manattom** [comment]
oui
quand je lance jarvis en mode clavier, ça fonctionne.

**Comment by manattom** [comment]
ça fonctionne c'est un problème de réglage micro. c'est un fonctionnement un peu hazardeux donc
si quelqu'un à un réglage optimun pour un micro TRIXES (celui qui est proposé dans les pré-requis du site) merci pour votre aide

**Comment by alexylem** [comment]
Bonjour @manattom 
Oui je confirme c'est bien un problème de micro.
En mode troubleshooting, tu devrais t'entendre avant que l'enregistrement de ta voix parte sur Bing. Vérifie que le son est propre et clair.
Essaye de parler plus près de micro, plus distinctement.
Tu peux aussi tester avec d'autres réglages de sensibilité du micro dans Settings > Audio > Sensitivity.
Si le micro est dans la liste c'est qu'un utilisateur a confirmé qu'il fonctionne bien. Fais une recherche dans les Tickets voir qui c'est et s'il a partagé ses réglages.

**Comment by alexylem** [comment]
Pour la signification de `.`, `?` et `#` c'est dans la FAQ, c'est aussi affiché dans la console en mode troubleshooting.

**Comment by manattom** [comment]
Merci pour les renseignements
et Bravo pour ce super projet
