### ISSUE TITLE
ajouter un argument de silence temporaire

### ISSUE THREAD

**Issue by Gilles76** [alexylem/jarvis#210]
Vu que l'on peut accéder à distance à Jarvis de différente façon, serait-il possible ajouter un argument qui le rend silencieux uniquement pour cette requête.

Exemple. 

Je demande à travers mon smartphone à Jarvis la météo. J'obtiens la réponse sur mon smartphone mais il n'est pas utile qu'on l'entende localement sur l'enceinte.

La commande pourrait-être: ./Jarvis -X "météo"
-X signifiant pas de son TTS local pour cette demande.

**Comment by Gilles76** [comment]
C'est parfait, merci

**Comment by Gilles76** [comment]
C'est parfait, merci.

**Comment by alexylem** [comment]
`-x` est déjà le flag pour passer un ordre.
Je vais créer un nouveau flag `-m` pour le lancer en mode muet:
```shell
$> ./jarvis.sh -m -x "meteo"
```
Ca t'irait?
