### ISSUE TITLE
Voix masculine

### ISSUE THREAD

**Issue by jbouziat** [alexylem/jarvis#211]
Bonjour,
Je suis très satisfait de l'utilisation de Jarvis. Le seul problème c'est qu'il n'y a pas de voix masculine.
Comme j’utilise Jarvis pour piloter mon robot humanoïde (inmoov) cela me pose problème.
Comment peux-t-on remédier à ce problème.
Merci

```

**Comment by physicien** [comment]
Aux dernières nouvelles, je ne pense pas qu'on ait de solution encore (j'ai le même problème et toi et la même utilisation de Jarvis, soit comme module principal d'un robot)

**Comment by alexylem** [comment]
Ca sera couvert par #176 merci d'upvoter la bas.

**Comment by jbouziat** [comment]
Merci pour votre réponse.

**Comment by jbouziat** [comment]
Bonsoir,
Excusez moi mais je ne comprends pas le terme upvoter. 
Quand pensez-vous intégrer les modifs dans jarvis.
En vous remerciant

**Comment by alexylem** [comment]
Upvoter = voter
1) Clique ici pour ouvrir l'autre Ticket qui répond déjà à ton besoin:
https://github.com/alexylem/jarvis/issues/176
2) Sur le premier Post, rajoute une réaction +1 (pouce en l'air)
![image](https://cloud.githubusercontent.com/assets/11017174/20078225/fcb75240-a53f-11e6-9123-691958d35b55.png)
3) Pour la date, assez difficile à dire, il y a déjà 9 personnes qui sont intéressées, donc je ne vais pas trop trainer 😄
