### ISSUE TITLE
?./jarvis.sh:line 574:_STT:command not found 

### ISSUE THREAD

**Issue by NYGHOST** [alexylem/jarvis#212]
bonjour a tous je rencontre cette erreur a chaque fois
tout fonctionne bien mais j'ai constament cette erreur.

**Comment by alexylem** [comment]
Lance Jarvis puis va dans Settings > Voice Reco > For Commands
Choisis un STT engine (ex: Bing)
Quitte les Settings puis démarre Jarvis

**Comment by NYGHOST** [comment]
Le probleme c'est que bing me met une erreur du coup je l'ai decoch?

Cordialement
PAIN Fabrice

Le 7 nov. 2016 ? 16:35, Alexandre M?ly <notifications@github.com<mailto:notifications@github.com>> a ?crit :


Lance Jarvis puis va dans Settings > Voice Reco > For Commands
Choisis un STT engine (ex: Bing)
Quitte les Settings puis d?marre Jarvis

-

**Comment by alexylem** [comment]
Tu peux nous dire quelle erreur tu as avec Bing?
Tu es obligé de sélectionner un moteur de reconnaissance vocal pour les commandes...

**Comment by NYGHOST** [comment]
Je suis en hors ligne avec snowboy

Cordialement
PAIN Fabrice

Le 7 nov. 2016 ? 18:50, Alexandre M?ly <notifications@github.com<mailto:notifications@github.com>> a ?crit :


Tu peux nous dire quelle erreur tu as avec Bing?
Tu es oblig? de s?lectionner un moteur de reconnaissance vocal pour les commandes...

-

**Comment by alexylem** [comment]
Dans ce cas il te reste les quick commands snowboy:
http://domotiquefacile.fr/jarvis/content/snowboy#commandes-rapides

**Comment by NYGHOST** [comment]
je pense que tu as lu trop vite, j'utilise uniquement snowboy, tout fonctionne , mes commandes sont reconnues mais j'ai constamment l'erreur et ce en triple qui s'affiche après ma commande et donc trois fois le bip. c'est toujours un bug

**Comment by alexylem** [comment]
Ah ok j'ai compris!

**Comment by NYGHOST** [comment]
Aaaah merci lol ;) j'avais pas cette erreur dans la version de juillet je vais voir si je peux bidouiller ca.

**Comment by alexylem** [comment]
J'ai compris pourquoi tu as une erreur en mettant Bing, c'est parce que les quick commands de `snowboy` te font entrer en mode conversation:
http://domotiquefacile.fr/jarvis/content/snowboy
![image](https://cloud.githubusercontent.com/assets/11017174/20096677/5109c93e-a5ab-11e6-9cff-5a99b495a5ec.png)
Du coup il passe sur la reconnaissance des commandes avec Bing.
Tu confirmes bien que tu as des erreurs uniquement à la seconde commande (après avoir déclenché une quick command)?
Je ne sais pas si ca fait vraiment sens d'ailleurs, je pense que je vais le désactiver...

**Comment by NYGHOST** [comment]
Tu penses qu'en enlevant le mode conversation ca irait? Je test ca dans 1h

**Comment by alexylem** [comment]
Non je ne pense pas que ca marchera... Le code est ainsi fait, il faut que je le change... mais tu pourrais me faire un test avec Bing (hors ligne) et me coller ce que ca donne dans la console depuis le début? (pour confirmer mon sentiment)
Merci!

**Comment by NYGHOST** [comment]
Ba apres le mode conversation peut tjr m'int�resser et surement d'autre personne mais seulement sur le triggername.

**Comment by NYGHOST** [comment]
Ca roule je te fait ca

**Comment by alexylem** [comment]
Oui bien sûr je garde le mode conversation pour le trigger. J'enlèverai juste le mode conversation automatique depuis une quick command. J'attends ton test merci!

**Comment by NYGHOST** [comment]
combien

$> ./con.sh && say " $(cat num.txt)"
_eva:_  56
**moi**: (listening...)
utils/timeout.sh 10 rec -V1 -q -r 16000 -c 1 -b 16 -e signed-integer --endian little jarvis-record.wav silence 1 0.1 1% 1 0.5 1% trim 0 10

**DEBUG:** speech duration was 15 (10 = 1 sec)
**DEBUG:** token missing or expired
**DEBUG**: json=
**DEBUG:** token will expire in 590 seconds
**DEBUG:** curl https://speech.platform.bing.com/recognize/query?version=3.0&requestid=9057efa9-d1d3-409a-9eba-2dce3825257b&appid=D4D52672-91D7-4C74-8AD8-42B1D98141A5&format=json&locale=fr-FR&device.os=linux&scenarios=ulm&instanceid=E043E4FE-51EF-4B74-8133-B728C4FEA8AA&result.profanitymarkup=0

**ERROR:** bing recognition curl failed
?(listening...)

**Comment by alexylem** [comment]
Il me manque le début, tu peux lancer Jarvis en mode troubleshooting et me coller toute la console depuis le début jusqu'à ce que le problème arrive?
Merci!

**Comment by NYGHOST** [comment]
Up-to-date

------------ Config ------------
jv_version           16.11.06
system               Linux 4.4.26-v7+ armv7l
os                   "Raspbian GNU/Linux 8 (jessie)"
language             fr_FR
play_hw              hw:1,0
rec_hw               hw:1,0
speaker              Logitech, Inc. USB Headset
microphone           Logitech, Inc. USB Headset
trigger_stt          snowboy
command_stt          bing
tts_engine           svox_pico
conversation_mode    true
--------------------------------

DEBUG: program_startup hook
ANNULE*|TERMINE*        *RARE*                  *AU REVOIR*|*BYE*
*TEST*                  *QUELLE HEURE*          *METEO*
eva:  ordre?
op: play FAIL formats: can't open output file `default': snd_pcm_hw_params error                                                                                   : Input/output error

**Comment by alexylem** [comment]
Voila tu peux choisir `snowboy` comme STT pour les commandes, tu ne devrais plus avoir le problème.
![image](https://cloud.githubusercontent.com/assets/11017174/20117074/49e2b234-a5ff-11e6-965f-6eb455c478fe.png)
