### ISSUE TITLE
aide snowboy

### ISSUE THREAD

**Issue by NYGHOST** [alexylem/jarvis#213]
j'ai mis cela dans une issue mais il s'agit plus d'une aide.
après plusieurs mois d'essais je remarque que snowboy est plus efficace sur des mots "court" que des phrases longues.
j'obtient ainsi 100% de réussite pour un mot contre 50% pour une phrase a 3mots

**Comment by alexylem** [comment]
C'est normal, par contre Snowboy recommande d'utiliser des hotwords d'au moins 3 syllabes pour éviter les faux positifs.
Tu peux aussi baisser la Sensibilité de Snowboy dans les Settings de Jarvis (Settings > Voice Reco)
