### ISSUE TITLE
Ou intégrer des fonctions sans plugins

### ISSUE THREAD

**Issue by Gilles76** [alexylem/jarvis#215]
Question du jour !

J'ai besoin de créer des fonctions pour réduire mes commandes par défaut dans Jarvis.

Tu proposerai quoi ?

EDIT: Je me lance! Pour des raisons de simplification, il serait bien q'un répertoire dédié puisse être mis en place au niveau du répertoire de Jarvis. Comme ça plus facile pour les sauvegardes, déplacements, etc ...

EDIT2:

Humm va me falloir des fonctions de Jarvis !

**Comment by alexylem** [comment]
Tu peux créer des fichiers / dossiers dans le répertoire de Jarvis, ils ne seront pas écrasés par les mises à jour (sauf bien sûr si c'est le même nom...)

Plusieurs possibilités:

* Utiliser des scripts  

**commands**  
```shell
  *ACTION ONE*==action1.sh
  *ACTION TWO*==action2.sh
```

* Utiliser des fonctions

Créer un fichier de fonctions
```shell
$> cat my_functions.sh
action1 () {...}
action2 () {...}
```
Inclure de fichier à Jarvis avec un hook (Settings > Hooks)
```shell
$> cat hooks/program_startup
source my_functions.sh
```
Utiliser les fonctions dans commands
**commands**  
```shell
  *ACTION ONE*==action1
  *ACTION TWO*==action2
```

Pour les fonctions de Jarvis, tu peux checker ceci:
http://domotiquefacile.fr/jarvis/content/public-api-reference
Sinon directement:
```shell
$> ls docs/
api-reference-internal.md
api-reference-public.md
```

**Comment by Gilles76** [comment]
J'ai créer un fichier de fonction functions_OH.sh déposé dans un répertoire my_config.

Le mieux, si j'ai bien compris c'est d'utiliser le système de Hook.
Par contre si je veux utiliser une fonction de jarvis dans mes fonctions, il faut que je source mon fichier de fonctions ?

**Comment by alexylem** [comment]
Oui il te faudra utiliser un `hook` pour sourcer ton fichier de fonctions.
Si tu mets tout dans un dossier tu peux aussi:
```shell
$>cat hook/program_startup
source my_config/*.sh
```
Les fonctions de Jarvis (globales) seront automatiquement disponibles dans tes scripts.

**Comment by Gilles76** [comment]
Ok j'y suis presque, merci pour tes indications.

J'appelle une fonction Scenario_VR $order

Sachant que fonction Scenario_VR attends un argument, il semblerai que $order ne soit pas pris en compte.
comment puis-je avoir un meilleur debug ?

**Comment by Gilles76** [comment]
Merci pour tout j'arrête de t'embêter.

J'avais oublié les && après le say .

Rahaaaa... merci, c'est super nickel.

J'arrive à lancer un scenario complexe avec choix multiple avec une seule commande.

**Comment by alexylem** [comment]
Cool, je te conseille aussi de mettre `$order` entre guillements pour éviter les problèmes avec les espaces:
```shell
*FAIT CECI*==Scenario_VR "$order"
```

**Comment by Gilles76** [comment]
Pour $order, c'était déjà fait, encore merci pour ton aide.
