### ISSUE TITLE
permettre un ou des caractères "jocker" au niveau des commandes

### ISSUE THREAD

**Issue by Gilles76** [alexylem/jarvis#216]
Comme j'étend les commandes à certains dispositifs de ma maison, de nouvelles problématiques surviennent.

Afin de ne pas avoir différentes déclinaisons de commandes est-ce que l'on pourrait prévoir des caractères génériques.

exemple:
*OUVRE*TOUT*VOLETS* j'ai parfois VOLET au singulier ou au pluriel.

Du coup est-ce que cela pourrai-être:
*OUVRE*TOUT*VOLET?

Le point d'interrogation étant vu comme un caractère non obligatoire. Ou si tu as une idée.

**Comment by alexylem** [comment]
Ca me parait tellement évident que j'ai peur d'avoir mal compris la question...
Tu as lu la doc? 😄 
http://domotiquefacile.fr/jarvis/content/commands
![image](https://cloud.githubusercontent.com/assets/11017174/20110452/b447a92e-a5e4-11e6-99a7-3d1499f1daba.png)
```shell
*OUVR* VOLET*==...
```
Matchera les ordres suivants:
* Ouvre le volet s'il te plait
* Peux-tu ouvrir les volets?

**Comment by Gilles76** [comment]
Effectivement, ça m'a echappé, j'étais trop dessus.

Excuse moi.

**Comment by alexylem** [comment]
Pas de soucy t'inquiètes 👍
