### ISSUE TITLE
Hook program_startup not called with -x flag

### ISSUE THREAD

**Issue by Gilles76** [alexylem/jarvis#217]
Quand je passe par le micro c'est ok. Quand je passe par le clavier c'est ok. Quand je passe par ma fonction en direct ok aussi....

```
sudo -u pi /home/pi/jarvis/jarvis.sh -m -x "ouvre volet jardin"| grep jarvis | sed "s,\x1B\[[0-9;]*[a-zA-Z],,g"
/home/pi/jarvis/jarvis.sh: ligne 467: Scenario_VR : commande introuvable
jarvis: Ouverture des volets coté jardin en cours
jarvis: cette commande retourne une erreur

```
Il semblerai qu'il ne trouve pas la fonction que j'ai sourcé dans program_startup.

**Comment by alexylem** [comment]
En effet il semblerait que le hook ne soit pas appelé avec le flag `-x`
Je corrige ca rapidement...
Pour info j'ai bien avancé sur #206 donc tu n'auras pas besoin de faire tout ce parsing...
Voila ou j'en suis la tout de suite:
```shell
$> curl -d '{"order":"bonjour"}' http://192.168.1.20:8080
{"response":[{"Jarvis":"Bonjour Alex"}]}
```
Le RestAPI utilise un nouveau flag `-j` de Jarvis pour crasher du JSON:
```shell
$> ./jarvis.sh -j -m -x "bonjour"
{"Jarvis":"Bonjour Alex"}
```
Il suffit donc d'extraire la réponse du JSON, par ex avec `jq`:
```
$> ./jarvis.sh -j -m -x "bonjour" | jq -r '.Jarvis'
Bonjour Alex
```

**Comment by alexylem** [comment]
Ca devrait marcher maintenant, j'ai aussi commité le flag `-j` même si je te conseille d'attendre que je publie (d'ici à demain) le plugin Jarvis API.

**Comment by alexylem** [comment]
Plus d'info ici: #206

**Comment by Gilles76** [comment]
Ok, merci. Super pour le correctif et j'attendrai demain pour jouer avec le flag j.
