### ISSUE TITLE
High Pitch with Namtai camera eye toy for playstation2

### ISSUE THREAD

**Issue by Mahieut** [alexylem/jarvis#218]
Bonjour,
Je viens d'installer Jarvis, tout va bien jusqu'à la configuration du micro,
En effet, l'enregistrement se passe bien, mais à la lecture de celui-ci,le son enregistré est deux foix plus rapide.
Je ne comprends pas pourquoi.
Est-ce réglable?
Merci de me venir en aide.

**Comment by alexylem** [comment]
Salut @Mahieut c'est quoi comme micro/enceintes?
D'autres utilisateurs ont déjà remonté des problèmes de pitch avec la marque JABRA: #65 
Ta solution se trouve peut-être de ce côté la, sinon je te conseille de tester avec d'autres micro/enceinte (je pars du principe que ton install est "clean" et que tu n'as pas de settings bizarre dans alsa).

**Comment by CaptainStouf** [comment]
Salut,
Pour ma part, j'avais ce genre de problème qui m'empêchait de configurer Jarvis.
J'ai résolu le souci avec ces 2 commandes, à lancer juste avant d'effectuer la configuration de Jarvis :
`export AUDIODEV=hw:0,0`
`export AUDIODRIVER=alsa`
La première commande se réfère au périphérique de lecture, donc à adapter dans ton cas. Tu peux utiliser `aplay -l` pour trouver ton périphérique.
Ca ne résoudra peut-être pas ton problème, mais c'est une piste à essayer. Ces variables sont remises à zero après un redémarrage, mais elles ne sont apparemment utiles que lors de la configuration.

**Comment by Mahieut** [comment]
J'utilise un camera eye toy playstation2 de Namtai

**Comment by Mahieut** [comment]
Les 2 commandes n'y ont rien fait je vais chercher vers le post #65

**Comment by Mahieut** [comment]
A priori le post #65 mentionne un problème à la lecture des sons,
Dans mon cas, il s'agit d'un problème d'enregistrement car lors du test des hauts parleurs, le son "applause" est à la bonne vitesse

**Comment by alexylem** [comment]
Ce problème va surement être résolu par le fix en cours sur #103
