### ISSUE TITLE
Discrimination des commandes

### ISSUE THREAD

**Issue by Gilles76** [alexylem/jarvis#219]
Alexy,

J'ai un doute sur la logique de discrimination des commandes.

De ce que j'en comprends, si nous avons:

expression A: ` *VOLET*FERME*NUIT*` et
expression B: ` *VOLET*FERME*`

Si je prononce "ferme les volets nuit" il devrait prendre en compte l'expression A.

Hé ben non, il prend l'expression B.

Normal ?

**Comment by alexylem** [comment]
Ca dépend l'ordre de tes commandes.
Il faut toujours mettre la plus discriminante en premier (dans l'ordre que tu as donné).
Il existe un problème si ces commandes sont dans différent plugins, car aujourd'hui ils sont traités dans l'ordre alphabétique, voir #209

**Comment by Gilles76** [comment]
J'ai parcouru la discussion sur les plugins et il semblerait que cela ne soit pas mon cas car j'ai des plugins qui n'ont pas de commandes de plus haut niveau.

Je pencherai plus pour un problème de regex. Jusqu'à deux mot clefs c'est bon, au delà ça pose problème.

Une autre solution serait que je fasse une discrimination dans ma fonction pour ne me retrouver qu'avec *OUVRE*VOLET* et *FERME*VOLET*
Tu en penses quoi pour le regex ?

**Comment by alexylem** [comment]
Dans ton premier post tu dis:

> expression A: *VOLET*FERME*NUIT* et
> expression B: *VOLET*FERME*
> Si je prononce "ferme les volets nuit" il devrait prendre en compte l'expression A.
> Hé ben non, il prend l'expression B.

Tes mots ne sont pas dans le même ordre "ferme les volets" vs `*VOLET*FERME*`. Je te confirme que l'ordre des mots sont important.

Par contre si c'est dans le bon ordre, il n'y a aucune raison que ca ne marche pas.

Je viens de tester tes commandes chez moi, mon fichier de commandes:
```
*VOLET*FERME*NUIT*==say "Je ferme les volets la nuit"
*VOLET*FERME*==say "Je ferme les volets"
```
Le test:
```shell
./jarvis.sh -x "volets ferme nuit"
Jarvis: Je ferme les volets la nuit
```

**Comment by Gilles76** [comment]
Merci pour tes précisions.
Je n'avais pas intégré que l'ordre des mots dans la commande ont une importance.
Du coup on perd le côté naturel du langage car deux personnes risquent d'employer les même mots mais pas dans le même ordre.
C'est un choix technique ? Ou est-ce modifiable ?
Ok y gagnerai un peu plus si la règle était: contient tout les mots dans n'importe quel ordre.

**Comment by alexylem** [comment]
C'est techniquement possible, mais dangereux, car on pourrait déclencher la mauvaise command si les mots ne sont pas bien choisis... la j'ai pas d'exemple en tête mais je suis convaincu que ca augmente ce genre de risque.
Dans ton cas précis, je ne pense pas qu'il y ait de formulation naturelle du style "Les volets ferme s'il te plait", à moins que tu sois Yoda...

**Comment by Gilles76** [comment]
Moi non plus j'ai pas vraiment d'exemple en tête ! ;0)
Bon ok compris, j'admet que cela puisse être génant. J'ai modifié mes commandes et tout va bien.

J'ai bien mis mes commandes les moins discriminantes à la fin et ça fonctionne.
Peut-être devrais-tu mieux mieux le mentionner dans ton site ? Car ce n'est pas facile à comprendre si la commande s'execute bien pour un utilisateur lambda. Il faut avoir l'idée de faire un test avec "say"

Au pire comme solution de repli, j'avais envisagé une fonction discrimante en fonction de la variable "$order". Ce que je fais déjà à l'image des plugins pour aller chercher une liste d'items en json corespondant à certains objet de la maison.

D'ailleurs encore merci pour le tuyau du dossier personnel "sourcé" car ça m'a permis d'intégrer assez rapidement les actions les plus courantes.

**Comment by alexylem** [comment]
Tu peux m'en dire un peu plus sur ta fonction discriminante en fonction de la variable `$order`?
Juste par curiosité 😄

**Comment by alexylem** [comment]
Suite à ta reco, j'ai rajouté quelque conseils sur la [page Commandes](http://domotiquefacile.fr/jarvis/content/commands) du site:
![image](https://cloud.githubusercontent.com/assets/11017174/20215784/fca821ce-a816-11e6-9ccf-631dc7f440d4.png)

**Comment by Gilles76** [comment]
Houlà ma fonction n'est pas complexe, elle recherche en fonction d'une liste json. Je m'en sers pour ouvrir mes volets en fonction d'une piece. Comme je suis tordu, je donne une ordre en fonction de trois types d'ouvertures. Soit indulgent, je ne suis pas une dev !

Ainsi je n'ai qu'à faire:
*OUVRE*VOLET*== VR_select "$order"

```
VR_select()
{
#declaration des variables
local local_order=$(jv_sanitize "$1")
#local local_order="$1"

if [[ $local_order =~ "ouvre" ]]
then
search_device "$local_order" 100
fi

if [[ $local_order =~ "ferme" ]]
then
search_device "$local_order" 0
fi

if [[ $local_order =~ "pointille" ]] || [[ $local_order =~ "guillemet" ]]
then
search_device "$local_order" 14
fi
}



search_device()
{
local VR_STATE=$2
local local_device=$(jv_sanitize "$1")  #est attendu pour $1 $order de jarvis
#local local_device=$1
while read device; do
        if [[ "$local_device" =~ .*$device.* ]]; then
            #echo "trouvé $device"
            local local_link="$(jq -r ".items[] | select(.name==\"$device\") | .link" "$JARVIS_PERSO_DIR"VR.json)"
            #echo "$local_link"
            curl --header "Content-Type: text/plain" --request POST --data "$VR_STATE" "$local_link" 
        fi
    done <<< "$(jq -r '.items[].name' "$JARVIS_PERSO_DIR"VR.json)"
}
```

extrait du json:

```
{
"items": [
{"name":"baie","link":"http://10.10.1.71:8080/rest/items/VR_Baie_Select"},
{"name":"cuisine","link":"http://10.10.1.71:8080/rest/items/VR_Cuisine_Select"},
....
```

Pour le moment c'est fonctionnel, il faut que je factorise un peu le code et que je commente.

**Comment by alexylem** [comment]
J'ai modifié ton post pour masquer ton IP... 😇 

Nickel merci pour le partage.
En fait tu as refait exactement ce que propose [le plugin home control](http://domotiquefacile.fr/jarvis/plugins/home-control)... Je te conseille de le tester, et si tu as besoin que je l'améliore tu n'as qu'à demander 😉

**Comment by Gilles76** [comment]
Merci pour l'adresse IP mais c'est pas bien grave c'est mon lan et de rien pour le partage, c'est un minimum au vu  de ce que tu fais.

Je n'ai pas essayé le plugin home-control j'aurai dû ! Je vais y jetter un oeil.
