### ISSUE TITLE
E: Impossible de trouver le paquet python3-pyaudio

### ISSUE THREAD

**Issue by alexylem** [alexylem/jarvis#22]
Erreur rencontrée durant l'installation automatique de `snowboy`:
```
E: Impossible de trouver le paquet python3-pyaudio
```
OS utilisé: `wheezy` (OK sur `Jessie`)
@remjou1

**Comment by alexylem** [comment]
@remjou1

**Comment by alexylem** [comment]
Essaye:
```
pip install pyaudio
```

**Comment by remjou1** [comment]
pi@raspberrypi ~ $ pip install pyaudio
Requirement already satisfied (use --upgrade to upgrade): pyaudio in /usr/lib/pymodules/python2.7
Cleaning up...
Vous avez du nouveau courrier dans /var/mail/pi

**Comment by alexylem** [comment]
J'aimerais que tu essayes voir si snowboy peut fonctionner sans `python3-pyaudio`, peux-tu:
```
nano +7 stt_engines/snowboy/main.sh
```
Enlève `python3-pyaudio`
```
sudo apt-get install -y python-pyaudio libatlas-base-dev
```
Puis relance l'installation de `snowboy`
Merci

**Comment by remjou1** [comment]
mdr ^^j'avais vu le fichier et l'install mais je voulais pas y toucher au cas où... je lance l'install...

**Comment by remjou1** [comment]
fail ^^

pi@raspberrypi ~/jarvis $ ./jarvis.sh
Checking for updates...[Up-to-date]
SNOWBOY: Bonjour rèmjou
SNOWBOY: Waiting to hear 'SNOWBOY'
rèmjou: ERROR: snowboy recognition failed

**Comment by alexylem** [comment]
Ok au moins tu es allé jusqu'au bout de l'installation. Peux-tu faire:
```bash
python stt_engines/snowboy/main.py stt_engines/snowboy/resources/snowboy.umdl
```
(je te préviens ca risque de sortir bcp de chose)

**Comment by remjou1** [comment]
c'est a dire ?

**Comment by alexylem** [comment]
Tu peux faire la commande s'il te plait et me coller le résultat? merci

**Comment by remjou1** [comment]
lol pas grand chose finalement ^^ : 

python stt_engines/snowboy/main.py stt_engines/snowboy/resources/snowboy.umdl
Traceback (most recent call last):
  File "stt_engines/snowboy/main.py", line 1, in <module>
    import snowboydecoder
  File "/home/pi/jarvis/stt_engines/snowboy/snowboydecoder.py", line 5, in <module>
    import snowboydetect
  File "/home/pi/jarvis/stt_engines/snowboy/snowboydetect.py", line 28, in <module>
    _snowboydetect = swig_import_helper()
  File "/home/pi/jarvis/stt_engines/snowboy/snowboydetect.py", line 24, in swig_import_helper
    _mod = imp.load_module('_snowboydetect', fp, pathname, description)
ImportError: /usr/lib/arm-linux-gnueabihf/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by /home/pi/jarvis/stt_engines/snowboy/_snowboydetect.so)


problème de module ?

**Comment by remjou1** [comment]
prob de copier coller... : 

pi@raspberrypi ~/jarvis $ python stt_engines/snowboy/main.py stt_engines/snowboy/resources/snowboy.umdl
Traceback (most recent call last):
  File "stt_engines/snowboy/main.py", line 1, in <module>
    import snowboydecoder
  File "/home/pi/jarvis/stt_engines/snowboy/snowboydecoder.py", line 5, in <module>
    import snowboydetect
  File "/home/pi/jarvis/stt_engines/snowboy/snowboydetect.py", line 28, in <module>
    _snowboydetect = swig_import_helper()
  File "/home/pi/jarvis/stt_engines/snowboy/snowboydetect.py", line 24, in swig_import_helper
    _mod = imp.load_module('_snowboydetect', fp, pathname, description)
ImportError: /usr/lib/arm-linux-gnueabihf/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by /home/pi/jarvis/stt_engines/snowboy/_snowboydetect.so)

**Comment by alexylem** [comment]
N'hésites pas à utiliser le bouton `edit` sur Github au lieu de multiplier les posts, je fais pas mal de ménage derrière toi 😄  (pour enlever les "lol" et compagnie, on n'est pas sur un chat mais un bug tracker)

**Comment by remjou1** [comment]
scuse...

**Comment by alexylem** [comment]
```
sudo apt-get install libstdc++6
```

**Comment by remjou1** [comment]
pi@raspberrypi ~ $ sudo apt-get install libstdc++6
Lecture des listes de paquets... Fait
Construction de l'arbre des dépendances       
Lecture des informations d'état... Fait
libstdc++6 est déjà la plus récente version disponible.
0 mis à jour, 0 nouvellement installés, 0 à enlever et 4 non mis à jour.

**Comment by alexylem** [comment]
Ok j'ai trouvé, d'après:
https://snowboy.kitt.ai/docspartials/docs/index.html

> If you see the following error:
```
mportError: /usr/lib/arm-linux-gnueabihf/libstdc++.so.6:
version `GLIBCXX_3.4.20' not found (required by rpi-arm-raspbian-8.0-1.0.1/_snowboy.so)
```
> It means that your g++ library is not up-to-date. You are probably still using Debian Wheezy 7.5 (check with lsb_release -a). However we compiled the snowboy library under Raspbian based on Debian Jessie 8.0 that comes with g++-4.9. You can either upgrade your Raspbian version to Jessie, or follow [this post](https://solarianprogrammer.com/2015/01/13/raspberry-pi-raspbian-install-gcc-compile-cpp-14-programs/) to install g++-4.9 on your Wheezy, or compile a version youself from [GitHub](https://github.com/kitt-ai/snowboy).

En gros **il faut être sur Jessie** (car j'utilise les versions précompilées de `snowboy`), ou suivre les instructions proposées pour mettre à jour g++ vers la 4.9.

**Comment by remjou1** [comment]
donc impossible pour la wheezy...

sauf si maj...
