### ISSUE TITLE
Problème avec bing depuis aujourd'hui

### ISSUE THREAD

**Issue by azertigrou** [alexylem/jarvis#221]
### Description

Bonjour,

Jarvis ne fonctionne plus depuis cette après midi sans raison apparente. 
Apparement c'est plutot Bing car j'ai essayé Snowboy et ca a l'air de marcher (bon, sauf que Snowboy, je l'aime pas trop).
Ma clé est bonne. Le site montre que ma clé n'est pas expirée et que je n'ai pas atteint le quota.

La commande `~/jarvis/stt_engines/bing $ ./test.sh`
me renvoie
```
pi@jarvis:~/jarvis/stt_engines/bing $ ./test.sh
cat: version.txt: Aucun fichier ou dossier de ce type
{"debug":"DEBUG: token missing or expired"},{"debug":"DEBUG: json=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzY29wZSI6Imh0dHBzOi8vc3BlZWNoLnBsYXRmb3JtLmJpbmcuY29tIiwic3Vic2NyaXB0aW9uLWlkIjoiNDNhYjA2Yzg3MDBiNGM2NTg4ODU5M2UxZDBhZGE4YjUiLCJwcm9kdWN0LWlkIjoiQmluZy5TcGVlY2guUHJldmlldyIsImNvZ25pdGl2ZS1zZXJ2aWNlcy1lbmRwb2ludCI6Imh0dHBzOi8vYXBpLmNvZ25pdGl2ZS5taWNyb3NvZnQuY29tL2ludGVybmFsL3YxLjAvIiwiYXp1cmUtcmVzb3VyY2UtaWQiOiIiLCJpc3MiOiJ1cm46bXMuY29nbml0aXZlc2VydmljZXMiLCJhdWQiOiJ1cm46bXMuc3BlZWNoIiwiZXhwIjoxNDc4ODA0OTU4fQ.uDCZds9fHis1i0cw4AxHzJpiRr9ZR1muZBPOVoIx9Dw"},{"debug":"DEBUG: token will expire in 590 seconds"},{"debug":"DEBUG: curl https://speech.platform.bing.com/recognize/query?version=3.0&requestid=e89a6700-9dbd-43d7-ae56-c51cf446d9d1&appid=D4D52672-91D7-4C74-8AD8-42B1D98141A5&format=json&locale=fr-FR&device.os=osx&scenarios=ulm&instanceid=E043E4FE-51EF-4B74-8133-B728C4FEA8AA&result.profanitymarkup=0"},{"debug":"DEBUG: json={\"version\":\"3.0\",\"header\":{\"status\":\"success\",\"scenario\":\"ulm\",\"name\":\"hello\",\"lexical\":\"hello\",\"properties\":{\"requestid\":\"9722fe40-158c-407f-b9ee-6e0125cdd4c2\",\"HIGHCONF\":\"1\"}},\"results\":[{\"scenario\":\"ulm\",\"name\":\"hello\",\"lexical\":\"hello\",\"confidence\":\"0.8591111\",\"properties\":{\"HIGHCONF\":\"1\"}}]}"}hello
```

En relancant la meme commande juste à la suite:
```
pi@jarvis:~/jarvis/stt_engines/bing $ ./test.sh
cat: version.txt: Aucun fichier ou dossier de ce type
{"debug":"DEBUG: curl https://speech.platform.bing.com/recognize/query?version=3.0&requestid=43ea9aeb-467d-4fa0-bffa-885517efc6b2&appid=D4D52672-91D7-4C74-8AD8-42B1D98141A5&format=json&locale=fr-FR&device.os=osx&scenarios=ulm&instanceid=E043E4FE-51EF-4B74-8133-B728C4FEA8AA&result.profanitymarkup=0"},{"debug":"DEBUG: json={\"version\":\"3.0\",\"header\":{\"status\":\"success\",\"scenario\":\"ulm\",\"name\":\"hello\",\"lexical\":\"hello\",\"properties\":{\"requestid\":\"8ffe9bf8-4186-4905-9920-59d7fe5eac26\",\"HIGHCONF\":\"1\"}},\"results\":[{\"scenario\":\"ulm\",\"name\":\"hello\",\"lexical\":\"hello\",\"confidence\":\"0.8591111\",\"properties\":{\"HIGHCONF\":\"1\"}}]}"}hello
```

et le fichier test.wav est bien généré.
J'ai essayé de reinstaller jarvis mais rien y fait.

En mode debug j'obtiens le log ci-dessous.

### Result
```shell
LSA lib pulse.c:243:(pulse_connect) PulseAudio: Unable to connect: Connection refused

Cannot connect to server socket err = No such file or directory
Cannot connect to server request channel
jack server is not running or cannot be started
INFO:snowboy:Silence
INFO:snowboy:Silence
INFO:snowboy:Silence
INFO:snowboy:Silence
INFO:snowboy:Silence
INFO:snowboy:Silence
INFO:snowboy:Silence
INFO:snowboy:Silence
INFO:snowboy:Silence
INFO:snowboy:Silence
INFO:snowboy:Silence
INFO:snowboy:Keyword 1 detected at time: 2016-11-10 18:57:24
DEBUG: modelid=0
Jarvis
DEBUG: entering_cmd hook
Jarvis: Oui?
Thierry: (listening...)
utils/timeout.sh
DEBUG: speech duration was 85 (10 = 1 sec)
DEBUG: too long for a command (max 4 secs), ignoring...
utils/timeout.sh
DEBUG: speech duration was 95 (10 = 1 sec)
DEBUG: too long for a command (max 4 secs), ignoring...
utils/timeout.sh
```

**Comment by alexylem** [comment]
Je regarde tout de suite...

**Comment by alexylem** [comment]
Je confirme le problème, j'investigue

**Comment by alexylem** [comment]
Non en fait ca marche...
```
DEBUG: curl https://speech.platform.bing.com/recognize/query?version=3.0&requestid=D99B2427-AE9B-4A74-82CE-F42C6877B3FE&appid=D4D52672-91D7-4C74-8AD8-42B1D98141A5&format=json&locale=fr-FR&device.os=osx&scenarios=ulm&instanceid=E043E4FE-51EF-4B74-8133-B728C4FEA8AA&result.profanitymarkup=0
DEBUG: json={"version":"3.0","header":{"status":"success","scenario":"ulm","name":"bonjour","lexical":"bonjour","properties":{"requestid":"f4c8f09e-10bb-4e96-a8e6-1c325bb49e38","HIGHCONF":"1"}},"results":[{"scenario":"ulm","name":"bonjour","lexical":"bonjour","confidence":"0.9513558","properties":{"HIGHCONF":"1"}}]}
bonjour
$> say "Bonjour $username"
Jarvis: Bonjour Alex
```

**Comment by alexylem** [comment]
Ton `test.sh` fonctionne, il envoie un enregistrement de ma voix (`test.wav`) qui dit *hello* qu'il envoie à Bing, le retour que tu as partagé est bien le texte `hello`.

Pour la suite de ton teste, il t'affiche la raison du problème en mode troubleshooting:
```
DEBUG: too long for a command (max 4 secs), ignoring...
```
Bruit de fond, sensibilité, ... 
Continue d'essayer à mon avis le problème est ailleurs...

**Comment by alexylem** [comment]
J'ai vraiment aucun problème...
![image](https://cloud.githubusercontent.com/assets/11017174/20190668/adcf12e0-a782-11e6-856d-84453185c337.png)

**Comment by azertigrou** [comment]
Bon, je reinstalle mon OS et je recommence l'install de jarvis.

**Comment by alexylem** [comment]
Carrément...
Tu veux pas avant réessayer de faire plusieurs tentatives en mode normal, en parlant bien distinctement (et pas trop longtemps la durée des commandes est limitée, la tu as dépassé les 4 secondes)
Je vois pas pourquoi ca ne marcherait pas...

**Comment by azertigrou** [comment]
Bon, la reinstall n'a rien donné. J'ai essayé pendant plus d'heure de lui parler distinctement, rien y fait.
Pourtant il comprend le mot jarvis au départ, c'est bien qu'il reconnait quelque chose. 
Le micro fonctionne bien puisque le wizard passe bien, je m'entends bien.

**Comment by azertigrou** [comment]
Par contre, le site de microsoft est carrément dans les choux: https://www.microsoft.com/cognitive-services/en-US/subscriptions ne fonctionne plus chez moi; je pense que c'est peut-être lié.

**Comment by alexylem** [comment]
S'il te plait peux-tu essayer:
```shell
$> cd stt_engines/bing/
$> ./test.sh
```
Si tu as:
```shell
{"debug":"DEBUG: curl https://speech.platform.bing.com/recognize/query?version=3.0&requestid=A33FC554-B249-4697-826D-9A63BB3D6F5A&appid=D4D52672-91D7-4C74-8AD8-42B1D98141A5&format=json&locale=en-US&device.os=osx&scenarios=ulm&instanceid=E043E4FE-51EF-4B74-8133-B728C4FEA8AA&result.profanitymarkup=0"},{"debug":"DEBUG: json={\"version\":\"3.0\",\"header\":{\"status\":\"success\",\"scenario\":\"ulm\",\"name\":\"hello\",\"lexical\":\"hello\",\"properties\":{\"requestid\":\"e5fcb7e5-78c4-4407-ab76-c31973499ef0\",\"HIGHCONF\":\"1\"}},\"results\":[{\"scenario\":\"ulm\",\"name\":\"hello\",\"lexical\":\"hello\",\"confidence\":\"0.9443262\",\"properties\":{\"HIGHCONF\":\"1\"}}]}"}
hello # le dernier mot est le plus important, tout à la fin
```
C'est que tout va bien côté Bing.

Ensuite essaye de lancer Jarvis en mode normal (`-n` pour passer le menu):
```shell
$> ./jarvis.sh -n
```
Déclenche le hotword, puis tente quelques commandes
```yml
Jarvis: Waiting to hear 'Jarvis'
Azertigrou: Jarvis
Jarvis: Oui?
Azertigrou: # que s'affiche-t-il ici?
```
Que s'affiche-t-il? Rien? des catactères comme `#`, `?`, `-` ou `.` ?

Si tu n'as rien du tout, il y a un bug,
Si tu as les des caractères, alors il faut lancer en mode troubleshooting pour en savoir plus:

```shell
$> ./jarvis.sh
# Puis choisis Start > Troubleshooting mode
Jarvis: Waiting to hear 'Jarvis'
Azertigrou: Jarvis
Jarvis: Oui?
Azertigrou:
# Regarde bien ce qu'il s'affiche ici, notamment qqchose comme
DEBUG: speech duration was 95 (10 = 1 sec)
DEBUG: too long for a command (max 4 secs), ignoring...
# Ca t'aidera à adapter ton temps de parole...
```

Allez on va y arriver! Je suis la pour t'aider 👍

**Comment by azertigrou** [comment]
Merci beaucoup pour ton aide:
Le test test.sh me répond deux messages différents :
1ere fois:
pi@raspberrypi:~/jarvis/stt_engines/bing $ ./test.sh
{"debug":"DEBUG: token missing or expired"},{"debug":"DEBUG: json=eyJ0eXAiOiJKV1
...

puis 

pi@raspberrypi:~/jarvis/stt_engines/bing $ ./test.sh
{"debug":"DEBUG: curl https://speech.platform.bing.com/recognize/query?version=3.0&requestid=db809524-b27b-42da-b1ba-424c2020f0e1&appid=D4D52672-91D7-4C74-8AD8-42B1D98141A5&format=json&locale=en-US&device.os=osx&scenarios=ulm&instanceid=E043E4FE-51EF-4B74-8133-B728C4FEA8AA&result.profanitymarkup=0"},{"debug":"DEBUG: json={\"version\":\"3.0\",\"header\":{\"status\":\"success\",\"scenario\":\"ulm\",\"name\":\"hello\",\"lexical\":\"hello\",\"properties\":{\"requestid\":\"55193cbd-8127-49d0-905a-c6474a0268ef\",\"HIGHCONF\":\"1\"}},\"results\":[{\"scenario\":\"ulm\",\"name\":\"hello\",\"lexical\":\"hello\",\"confidence\":\"0.9443262\",\"properties\":{\"HIGHCONF\":\"1\"}}]}"}hello


En mode normal, j'ai des # . J'ai beau dire des mots qu'il est censé comprendre, rien y fait.

En mode debug, que je dise rien ou quelque chose, il m'affiche toujours le meme message:
snowboy: Oui?
Thierry: (listening...)
utils/timeout.sh
DEBUG: speech duration was 95 (10 = 1 sec)
DEBUG: too long for a command (max 4 secs), ignoring...
utils/timeout.sh
DEBUG: speech duration was 95 (10 = 1 sec)
DEBUG: too long for a command (max 4 secs), ignoring...
utils/timeout.sh
DEBUG: speech duration was 95 (10 = 1 sec)
DEBUG: too long for a command (max 4 secs), ignoring...
utils/timeout.sh
DEBUG: speech duration was 95 (10 = 1 sec)
DEBUG: too long for a command (max 4 secs), ignoring...
utils/timeout.sh

Tu es sur que le fait que je n'arrive pas à me logguer sur le site de Bing n'a rien à voir?

**Comment by alexylem** [comment]
Rien à voir, Bing fonctionne pour toi, tu as le hello.
A mon avis tu as un problème de sensibilité de micro.

1. En mode troubleshooting tu t'entends bien dire les commandes clairement?
2. Vu que tout est à duration 95, le seuil de silence n'est pas atteint quand tu fini de parler, du coup il timeout...

C'est un problème assez classique je dois dire, il a été discuté ici: #199 
![image](https://cloud.githubusercontent.com/assets/11017174/20194936/b55033e8-a794-11e6-8fa0-686b4a767fc6.png)

**Comment by azertigrou** [comment]
C'était ca ! Le volume du micro était trop haut. Ca marche nikel merci.
Un grand merci pour ta patience et pour ton aide!
Bon, je vais pouvoir tester le plugin jeedom maintenant ;)

**Comment by alexylem** [comment]
Super! 😄

**Comment by azertigrou** [comment]
Bon, par contre je suis obligé de parler à 10 cm du micro. J'ai commandé un CM1000-USB, j'espère que je pourrai parler à 2-3m

**Comment by alexylem** [comment]
Tu utilises quoi comme micro?
Pour parler à distance il n'y a pas de secret, il faut un micro spécial. Celui que tu as commandé devrait donner de bons résultats.

**Comment by azertigrou** [comment]
Actuellement ca: 
http://www.cdiscount.com/informatique/clavier-souris-webcam/trixes-microphone-easy-mic-usb-de-bureau-pour-p/f-1070219-tri5060281003058.html?gclid=CjwKEAiA0pDBBRCFtoPyguTh8AUSJADNWeuxRoDgJfrjQ29dZFsgOYKWNmXxxKTyvqBmkz_v505v9RoCFNnw_wcB&idOffre=35258527&s_kwcid=AL!639!3!87239645482!!!g!!&cid=search&cm_mmc=SE_mckv!_Shopping_ShoppingMKP&ef_id=VjdZiwAABCfyZ0XQ:20161110214233:s

Un truc à 10€

**Comment by satana888** [comment]
bonjour,

J'ai plus rien depuis hier soir non plus.....
Voici le message qu'ils ont laissé sur leur site speech.platform.bing.com : 

Our services aren't available right now

We're working to restore all services as soon as possible. Please check back soon.
Ref A: 1AB84F0B40E84800A60B9CEDF31E33E0 Ref B: BRU30EDGE0113 Ref C: Sun Jun 18 01:54:36 2017 PST


Je pense qu'il va falloir être patient...

**Comment by satana888** [comment]
oupssss

j'avais pas vu la date...
 mais a ce jour j'espere qu'ils vont faire vite, j'ai encore plein de trucs a essayer...
mais si quelqu'un pouvait me confirmer que c'est bien ça?
j'appel jarvis le hotword fonctionne nikel et quand je demande mes commandes habituelles il veux plus rien savoir et m'affiche cette erreur : ERROR: bing recognition curl failed

**Comment by wikijm** [comment]
Ton analyse semble juste, je rencontre les mêmes difficultés.

**Comment by alexylem** [comment]
dupe #646
