### ISSUE TITLE
Re executer une commande

### ISSUE THREAD

**Issue by etopit** [alexylem/jarvis#222]
Bonjour,

petit compliment pour le projet ca fonctionne super bien avec ma box domotique jeedom.

j'aurai voulu savoir si il y a un moyen simple de refaire exécuter la dernière commande à jarvis ? Afin de lui faire répéter une action que j'aurais mal entendu ou par exemple d’augmenté ou diminué graduellement la lumière de mon variateur. ou le volume de la tv  ... enfin de répéter la dernière commande :)

je pensais a un truc du genre :
REPETE|ENCORE== script-repete.sh

et dans le script-repete.sh un truc du genre je récupère la dernière ligne que j'ai prononcé dans le fichier jarvis.log que je re-execute via la commande jarvis -x  "$ligne" ?

Ca vous semble jouable cette méthode ?

**Comment by alexylem** [comment]
Bonjour à toi @etopit 
Intéressant comme idée, ca me semble tout à faire jouable, il faut simplement que je stocke la dernière commande exécutée dans une nouvelle variable Jarvis publique (ex: `jv_last_command`) et que je propose ta commande par défaut qui exécute cette variable.
```shell
REPETE*|ENCORE*==$(jv_last_command)
```
J'ai mis des étoiles pour capter "Répéter..." / "Encore une fois".
Si t'es d'accord je te fais ca.

**Comment by etopit** [comment]
Nickel :-D

**Comment by alexylem** [comment]
Voila met à jour.
La commande a utiliser:
```
ENCORE*==jv_repeat_last_command
```

**Comment by etopit** [comment]
Super merci pour la nouvelle fonction, cependant ca eu marché :).

j'ai un problème ca répète dans mon cas que les commandes qui sont dans le jarvis-command ou qui sont listé lors du démarage de jarvis. (quelle heure , cody gauche etc ...)

Mais les commandes qui match vers le wildcard * pour être rediriger vers ma box domotique (jeedom) ne match pas via la commande "encore" jarvis me répond "Je ne comprends pas". 

il me semble cependant que ça eu marché entre la mise à jour d'ajout de la fonctionnalité et la mise à jour suivante qui re-organise l'affichage des mots clefs ?

**Comment by alexylem** [comment]
Ca m'étonnerait je n'ai pas changé ce mecanisme entre les 2 version. Je vais tester et trouver une solution pour cas du wildcard.

**Comment by alexylem** [comment]
Je reproduis:
![image](https://cloud.githubusercontent.com/assets/11017174/20279791/422bd08e-aaaa-11e6-86da-4aa445b02655.png)

**Comment by alexylem** [comment]
Pas évident...
J'ai trouvé un moyen pour le faire fonctionner avec les wilcards qui se basent sur `$order` (ce qui est le cas du plugin Jeedom):
```
*==say "commande whildcard: $order"
```
![image](https://cloud.githubusercontent.com/assets/11017174/20280467/e1cb0eb4-aaac-11e6-8553-1f848fa6c69f.png)

Mais pas sur les commandes avec des captures:
```
(*)==say "commande whildcard: (1)"
```
![image](https://cloud.githubusercontent.com/assets/11017174/20280517/0f1dc41a-aaad-11e6-9085-656c05e49cbd.png)

**Comment by etopit** [comment]
*==say "commande whildcard: $order"

effectivement ça fonctionne comme tu le mentionne

**Comment by alexylem** [comment]
Je ferme le ticket vu que ca adresse ton besoin avec Jeedom. Si d'autres personnes ont besoin de le faire marcher sur des commandes avec des (captures) on ré-ouvrira.
