### ISSUE TITLE
jeedom-plugin répond 404 Not Found

### ISSUE THREAD

**Issue by nicoxygen** [alexylem/jarvis#224]
Quand jeedom est installé et paramétré, jarvis me répond:
snowboy: <html> <head><title>404 Not Found</title></head> <body bgcolor="white"> <center><h1>404 Not Found</h1></center> <hr><center>nginx/1.2.1</center> </body> </html>

au lieu de l'habituel: je n'ai pas compris la question, une fois le plugin désinstallé tout est à nouveau ok.

**Comment by alexylem** [comment]
Le plugin Jeedom forward toutes les commandes à Jeedom. Il se peut que tu aies mal paramétré l'IP, le port, et le path de Jeedom...
Peux-tu coller ta config (en anonymisant l'IP si elle est publique) ?

**Comment by nicoxygen** [comment]
excuse moi j'ai trouvé, j'ai mis le dossier dans les mauvais "" sur la config, je l'ai mis après le # c'est ok maintenant, je m'excuse
