### ISSUE TITLE
Interface Utilisateur (Web) pour Jarvis

### ISSUE THREAD

**Issue by nicoxygen** [alexylem/jarvis#225]
Bonjour alex, as-tu prévu une interface web type gladys pour gérer le projet jarvis à l'avenir ?

**Comment by alexylem** [comment]
Salut @nicoxygen oui en effet j'avais pensé faire ca.
L'idée serait de pouvoir gérer ses commandes et event depuis une interface web (car aujourd'hui via le terminal c'est un peu limité). Et aussi de pouvoir interagir avec Jarvis depuis le browser avec le reconnaissance vocale intégrée à Chrome.
Tu voyais d'autres utilités?

**Comment by nicoxygen** [comment]
Le soucis du terminal ce n'est pas accessibles au plus grand nombre.
Pour les utilités tu peux rajouter un envoi de fichier pour snowboy si on veut faire un import.
L'interface de gladys est assez waf je trouve ça pas mal, je pense que c'est une priorité si tu veux imposer ton projet rapidement, c'est vrais que l'avenir est au stt, le fait de rendre compatible jarvis avec des home automation via des plugins est un grand plus.

**Comment by nicoxygen** [comment]
actuellement node.js est incontournable pour ce type de projet mais le coupler avec le framework sailsjs le rend encore plus waf, jeedom tourne aussi en partie sur node.js

**Comment by Gilles76** [comment]
Ok avec "node.js",  je ne l'utilise pas mais c'est assez puissant. il est aussi possible d'utiliser nginx (léger, rapide, automatisable en terme d'installation). J'aime bien php, même si je ne suis pas développeur, on s'en sort toujours. 

Après en terme de fonctionnalité, il faut forcément intégrer tout le paramétrage de jarvis, la reconnaissance vocale (qui imposerai chrome pour plus de facilité). d'autre idées viendront au fur et à mesure.

La bonne question est quelle technologie à employer pour que cela soit maintenable facilement.

Au vue de ton, projet Alex, je dirai interaction bash, python, serveur web (node.js, nginx). Prévoir un design sympa "auto-adaptable" au smartphone et autre. Limite sans adaptation prévoir un framework qui rende cette interface web une webapp.

**Comment by alexylem** [comment]
Sachez que je reprends aussi le plugin Jarvis de Jeedom qui possède déjà une interface. Je vais donc réfléchir à créer une interface commune utilisant l'API JSON de Jarvis (qu'il faudra faire évoluer). Pour éviter l'installation d'un web-serveur, j'essayerai d'utiliser le server web intégré de Python qu'on lancera au démarrage de Jarvis (comme pour l'API). Ca sera bien entendu ultra léger, pour continuer dans la philosophie de Jarvis.

**Comment by nicoxygen** [comment]
J'avais aussi pensé à l'interface Jeedom encore faut-il que les utilisateurs utilisent Jeedom, perso toute ma domotique tourne dessus. En attendant le module Jarvis de Jeedom n'est pas fonctionnel à l'installation

**Comment by alexylem** [comment]
Je sais j'ai justement échangé avec le fondateur de Jeedom (qui a développé ce plugin) pour que je reprenne le développement de ce plugin. En attendant, il faut utiliser le plugin Jeedom de Jarvis qui lui est 100% fonctionnel.

**Comment by alexylem** [comment]
Je commence à développer une interface web sous la forme de plugin à installer: `jarvis-ui`
Ce plugin a besoin du plugin `jarvis-api` pour fonctionner, j'introduirai donc le concept de dependance pour les plugins.
Voila un premier aperçu de l'interface (coquille vide)
![image](https://cloud.githubusercontent.com/assets/11017174/20497204/966e1444-b028-11e6-8f2e-ef5da2e8973d.png)

**Comment by alexylem** [comment]
Ca y est ca répond depuis l'API de Jarvis 😄  (ca se voit que c'est brut de coffrage)
![image](https://cloud.githubusercontent.com/assets/11017174/20501110/b1dc0834-b038-11e6-9337-c83d804b7cb8.png)

**Comment by Gilles76** [comment]
Hummm, bien! Bientôt les utilisateurs allergiques à l'éditeur de texte pourront utiliser Jarvis.
Beau travail.

**Comment by nicoxygen** [comment]
C'est ce qu'il faut, le WAF c'est la clé pour faire connaître son projet au maximum d'utilisateurs possible.

**Comment by alexylem** [comment]
Ca progresse...
![image](https://cloud.githubusercontent.com/assets/11017174/20538543/022de1cc-b0f2-11e6-864a-fce2637649d2.png)
![image](https://cloud.githubusercontent.com/assets/11017174/20538554/0937a732-b0f2-11e6-8642-68315123d7a7.png)

**Comment by wikijm** [comment]
Je suis en train de réfléchir à utiliser un écran tactile pour utiliser de la domotique et/ou piloter Jarvis. Actuellement j'expérimente sur un écran Spotpear 2.4"

**Comment by alexylem** [comment]
Aller un dernier pour la route:
![image](https://cloud.githubusercontent.com/assets/11017174/20544113/be8eee2c-b108-11e6-8c20-b90e2ee6bc0e.png)
![image](https://cloud.githubusercontent.com/assets/11017174/20544125/d34d2270-b108-11e6-8ac7-5a7ad06a5b18.png)
J'ai loin d'avoir fini en ce qui concerne la partie reconnaissance vocale par le browser et configuration de Jarvis. Mais pour la partie dialogue textuel, le plugin est fonctionnel (pas encore publié).

**Comment by Gilles76** [comment]
À toi de voir mais tu peux livrer le plugin des qu'il sera prêt pour l'édition des commandes, etc ....
Et tu gardes la partie reconnaissance vocale pour après. Comme ça les allergiques à la ligne de commande pourront l'utiliser.

**Comment by alexylem** [comment]
Ok bonne idée je ferai les settings après ! Par contre le risque de déployer une early version c'est qu'il y ait des gros changements nécessitant des réinstallation/reconfig de plugin mais si ça vous va je vous partage ça dès que c'est prêt.

**Comment by alexylem** [comment]
En attendant vous pouvez toujours modifier le fichier de commandes en FTP / SCP 😉

**Comment by Gilles76** [comment]
A voir avec d'autres, mais ce n'est pas très grave car pas beaucoup de config à faire.

**Comment by alexylem** [comment]
Ca avance, maintenant ca récupère les commandes depuis l'API et les affiche dans un éditeur. Il y a même la coloration syntaxique 😄 
![image](https://cloud.githubusercontent.com/assets/11017174/20580163/18337c54-b1d1-11e6-9827-d9a2f92139d5.png)
![image](https://cloud.githubusercontent.com/assets/11017174/20580175/22bcb74e-b1d1-11e6-9bbd-bbb84343dd95.png)

**Comment by alexylem** [comment]
Et comme c'est un plugin, il y a juste à l'installer, voici ce qui s'affiche au démarrage:
![image](https://cloud.githubusercontent.com/assets/11017174/20580329/0205e9ca-b1d2-11e6-956f-1c5387b57894.png)
Il suffit donc de copier-coller l'URL de l'interface dans un navigateur (l'IP locale est détectée automatiquement, le port vient de la configuration du plugin)

**Comment by alexylem** [comment]
![image](https://cloud.githubusercontent.com/assets/11017174/20636186/b327c646-b368-11e6-8089-e0a9292ff6e3.png)

Allez pour les plus impatients d'entre vous je vous mets à disposition une version alpha.
Elle n'est pas encore sur le store mais vous pouvez l'installer manuellement:
```shell
$> ./jarvis.sh -p https://github.com/alexylem/jarvis-ui
```
⚠️  Il faut avoir le plugin `jarvis-api` installé.

Ce que vous pouvez faire:
- Lancer l'interface graphique depuis n'importe quel browser
- Ecrire des commandes à exécuter
- Gérer les commandes utilisateurs
- Mettre en mode Muet / Verbose
- Thème Light / Dark
- L'utiliser sur un smartphone (responsive)

Ce que vous ne pouvez pas encore faire:
- Faire dire quelque chose à Jarvis
- Configurer Jarvis
- Dicter des commandes à exécuter
- Gérer les Events
- Gérer les plugins

J'attends vos premier retours.

**Comment by alexylem** [comment]
![image](https://cloud.githubusercontent.com/assets/11017174/20639505/ae673f6c-b3c5-11e6-9022-df14d62bb909.png)

Ce que vous pouvez faire:
- Lancer l'interface graphique depuis n'importe quel browser
- Ecrire des commandes à exécuter
- Gérer les commandes utilisateurs
- Mettre en mode Muet / Verbose
- Thème Light / Dark
- L'utiliser sur un smartphone (responsive)
- Faire dire quelque chose à Jarvis

Ce que vous ne pouvez pas encore faire:
- Configurer Jarvis
- Dicter des commandes à exécuter
- Gérer les Events
- Gérer les plugins

**Comment by alexylem** [comment]
Personne l'a testé?
De mon côté j'avance bien dans la config, même si je pense pouvoir faire beaucoup mieux à l'avenir côté usability. Petit aperçu avec le thème Light:

![image](https://cloud.githubusercontent.com/assets/11017174/20642986/86d5d65e-b41d-11e6-83da-65e8e0ba21d4.png)

![image](https://cloud.githubusercontent.com/assets/11017174/20642975/5656c3ee-b41d-11e6-98d3-c13b83e3c5c7.png)

**Comment by Gilles76** [comment]
Désolé,
j'ai eu pas mal à faire ces temps-ci !

J'ai installé l'ui. C'est super bien. J'aime bien le thème dark, tout est fluide est bien représenté. J'ai essayé d'envoyer des ordres par clavier ça marche nickel.

Par contre, même si j'en connais certaine cause, l'api de jarvis est très fragile. il n'est pas rare que je doive "killer" et redémarrer jarvis à cause de certaines actions.

Je t'ouvre un ticket ?

Encore bon boulot, c'est le genre d'ui que j'aime.

**Comment by alexylem** [comment]
Oui je veux bien pour la stabilité de l'API, avec des exemples concrets si possible:
https://github.com/alexylem/jarvis-api/issues/new

**Comment by alexylem** [comment]
Ca y est on peut gérer la config Jarvis depuis l'interface.

![image](https://cloud.githubusercontent.com/assets/11017174/20649162/b9ef199c-b4b8-11e6-8534-584de684c51b.png)

Ce que vous pouvez faire:
- Lancer l'interface graphique depuis n'importe quel browser
- Ecrire des commandes à exécuter
- Gérer les commandes utilisateurs
- Mettre en mode Muet / Verbose
- Thème Light / Dark
- L'utiliser sur un smartphone (responsive)
- Faire dire quelque chose à Jarvis
- 🆕  Configurer Jarvis

Ce que vous ne pouvez pas encore faire:
- Dicter des commandes à exécuter
- Gérer les Events
- Gérer les plugins

Pour rappel vous pouvez installer et tester la version beta avant que je ne la publie sur le store:
```shell
$> ./jarvis.sh -p https://github.com/alexylem/jarvis-ui
```
⚠️  Il faut avoir le plugin `jarvis-api` installé et à jour.

**Comment by alexylem** [comment]
Publié sur le store:
http://domotiquefacile.fr/jarvis/plugins/jarvis-ui

Il me reste toutefois à implémenter la gestion des dépendances (c'est écrit dans le README.md du plugin pas mais encore automatique...).

**Comment by Gilles76** [comment]
Bien cool, encore une fois bon boulot, c'est super fluide et agréable à utiliser.

**Comment by LengZai** [comment]
Je viens de tester..
C'est sobre et efficace

Petite note pour ameliorer les choses... je peux faire un autre ticket si besoin:
Pouvoir "désactiver" un plugin sans forcement le deinstaller
Pour quitter Jarvis, je suis obligé de redemarrer le Pi car une commande kill ne marche pas et je reste bloqué sur Stopping HTTP server

**Comment by alexylem** [comment]
Pour les 3 points remontés @LengZai tu peux créer des Tickets séparés (sur le repo Jarvis)? ca sera plus facile pour suivre, merci d'y joindre un max d'info. Merci :+1:

**Comment by LengZai** [comment]
Pas de souci.. yes je me dis que ca serait plus simple également.
Je te fais cela ce soir en rentrant du taff lol..

J'ai trouvé d'autres petit comportement bizarre mais tu les verras dans les tickets :-P

**Comment by alexylem** [comment]
![image](https://cloud.githubusercontent.com/assets/11017174/20898574/21f224b6-bb27-11e6-8c12-049d9ee74a4e.png)
![image](https://cloud.githubusercontent.com/assets/11017174/20898581/2e81c2cc-bb27-11e6-9897-8e7e0643ef40.png)

Ce que vous pouvez faire:
- Lancer l'interface graphique depuis n'importe quel browser
- Ecrire des commandes à exécuter
- Gérer les commandes utilisateurs
- Mettre en mode Muet / Verbose
- Thème Light / Dark
- L'utiliser sur un smartphone (responsive)
- Faire dire quelque chose à Jarvis
- Configurer Jarvis
- 🆕  Gérer les Events

Ce que vous ne pouvez pas encore faire:
- Dicter des commandes à exécuter
- Gérer les plugins
- Installer Jarvis 😄 

Mettez à jour:
```shell
$> ./jarvis.sh -u
```

**Comment by Dadiss** [comment]
Bonjour, merci pour votre disponibilité et votre travaille. 
je viens aux nouvelle de l'intégration du plugin jarvis-ui à Jeedom? merci pour votre réponse.

**Comment by wikijm** [comment]
Bonjour @Dadiss

Pour ta demande, je t'invite à créer un nouveau ticket dans le repository du plugin [jarvis-ui](https://github.com/alexylem/jarvis-ui/issues).

**Comment by wikijm** [comment]
N'ayant pour le moment plus de questions/requêtes en suspens, et le plugin ayant son propre repository, je clôture le ticket.
