### ISSUE TITLE
Plugin - passage parametre a une fonction

### ISSUE THREAD

**Issue by NikoS34** [alexylem/jarvis#227]
### Description

Bonjour,

dans le cadre d'un plugin j’essaie de passer une capture (voir fichier de commande) en paramètre à ma fonction dicus() définie dans le fichier functions.sh du plugin.

fichier de commande du plugin =
`*LE MOT (*)==say "je vérifie..." && say "$(dicus((1)))"; bypass=false`

### Result
```
rebecca: Waiting to hear 'rebecca'
niko: rebecca
rebecca: Oui?
niko: le mot table
rebecca: je vérifie...
./jarvis.sh: command substitution: line 524: syntax error near unexpected token `${BASH_REMATCH[1]}'
./jarvis.sh: command substitution: line 524: `dicus(${BASH_REMATCH[1]}))"'
rebecca: This command has returned an error

```

**Comment by devauxa** [comment]
Tu veux juste passé en argument ce qui est dit dans (*) à ta fonction discus ?

Si c'est ça ```*LE MOT (*)==say "je vérifie..." && say "$(dicus (1))"```
Pour donner un argument à une fonction bash, il ne faut pas mettre de parenthèse encadrant les args.
N’hésite pas à regardé les autres plugins pour voir comment ils sont réalisés.

**Comment by NikoS34** [comment]
Merci devauxa, c'est OK !
J'avais bien essayé sans les parenthèses mais j'avais zappé le caractère "espace" avant (1), car sans lui le nom de la fonction et l'argument sont en effet concaténés...

**Comment by alexylem** [comment]
Je dirais même plus:
```shell
*LE MOT (*)==say "je vérifie..." && say "$(dicus "(1)")"
```
Que tu récupères avec `$1` dans `dicus` dans le cas ou il y aurait plusieurs mots
