### ISSUE TITLE
Probléme de micro et conf alsa

### ISSUE THREAD

**Issue by etopit** [alexylem/jarvis#228]
Bonjour,

j'ai un problème au niveau de la captation de ma voix par jarvis. j'ai voulu toucher un peu à la conf alsa (asound.conf) afin d'augmenter le volume (pourtant au max) de la sorti audio (relativement faible). Et depuis et ce malgrès la remise en place des fichier de conf d'origine j'ai de gros problème. ( mise à part mes déboire avec pulseaudio que j'ai fini par supprimer)

Le mot clef "jarvis" très bien est capté et de loin, ensuite j'ai l'impression qu'il ne capte plus grand chose.
En mode débug le mot clef est capturé facile ensuite c'est vraiment compliqué j'ai même pas le temps de dire "quelle heure" qu'il me coupe et ca même le bouche sur le micro le retour de l'enregistrement me fais vraiment penser a un problème de réglage du micro mais je ne sais pas trop sur quel fichier travailler. Si je m'éloigne de plus d'un mettre on entend vraiment plus rien dans le retour du mode debug.

ce qui est étrange c'est que je n'arrive même plus a lui dire quelques chose il me coupe tout le temps parce qu'il ne comprends pas ma demande.

j'ai l'impression que la qualité du teste effectué dans jarvis est de bonne qualité : 
équivalent a un arecord avec un rate 48000 en S16_LE

mais j'ai pas cette impression en captation classic de jarvis

**Comment by etopit** [comment]
Une simple re-installation de jarvis dans un répertoire vierge à résolu le problème de compréhension de jarvis, coupure d'enregistrement en plein milieu de le phrase. Ce qui régle grandement mon problème de communication avec jarvis. Cependant je suis toujours obligé de parler terriblement près du micro pour avoir un bon résultat correcte mais celà est un autre problème en attendant d'avoir le combo jarvis (linux) micro parfait .... ;-)

**Comment by alexylem** [comment]
Oui c'est malheureusement un fait, pour la reco de loin, il faut un micro adapté.
Voir:
http://domotiquefacile.fr/jarvis/content/prerequisites
![image](https://cloud.githubusercontent.com/assets/11017174/20272256/ac8f2b5a-aa8d-11e6-9ad6-b790fbc95f98.png)
