### ISSUE TITLE
Horodatage log jarvis.log

### ISSUE THREAD

**Issue by etopit** [alexylem/jarvis#229]
Bonjour,

j'ai quelques faux positifs avec le mots clef snowboy que j'utilise pour activer le mode conversation. Afin de savoir combien de fois il se déclenche, y a t'il un moyen d'ajouter une option d'horodatage dans les log de jarvis ?

**Comment by alexylem** [comment]
Bonne idée,
Ca s'appliquera lorsque Jarvis sera lancé en background (Menu "Start as a Service" or flag `-b`) et visible dans le fichier `jarvis/jarvis.log`
Je pense même que j'horodaterai le fichier de log lui même dans un répertoire `log/` car aujourd'hui il s'écrase lui même, donc en fait ca sera dans le fichier `jarvis/log/jarvis-YY-MM-DD.log`. Ca te permettra de faire des plus grosses stats.
J'attends ton GO.

**Comment by etopit** [comment]
Super,
L'horodatage des logs dans le fichier jarvis.log est déjà nickel . Un répertoire log encore mieux, car ca peut être aussi utile à d'autre plugins, je pense au plugins API qui pourra générer des logs dans ce répertoire ou tout autre plugins future ...

Pour le typage du fichier en fonction de la date, de mon point de vu ce n'est pas forcement utile logrotage fait ca déjà très bien ;-) à toi de voir...

heuu ... GO :D

**Comment by alexylem** [comment]
Ah je parlais d'un fichier nommé avec la date pour éviter qu'il s'écrase, après c'est vrai que je peux toujours rajouter à la fin du fichier de log surtout s'il est horodaté... je vais plutôt faire ca dans un premier temps, c'est plus simple 😄 
Allez s'partiiii!

**Comment by alexylem** [comment]
Fini, mettez à jour
