### ISSUE TITLE
pb avec mon plugin wikipedia

### ISSUE THREAD

**Issue by Gilles76** [alexylem/jarvis#231]
Je suis en train de créer un plugin qui permet une interation avec wikipedia

en langage naturel:

`Donne moi la définition de XXXXXXXXX`

la commande est:

`*DONNE*DEFINITION*DE (*)`

la fonction:

```
WIKI_SEARCH=$(jv_sanitize $1)
LIMITED_WIKI_QUERY="https://fr.wikipedia.org/w/api.php?action=opensearch&search="$WIKI_SEARCH"&prop=revisions&rvprop=content&format=json"
full_wiki_query="https://fr.wikipedia.org/w/api.php?action=opensearch&search="$WIKI_SEARCH"&prop=revisions&rvprop=content&format=json"

curl -s "$LIMITED_WIKI_QUERY" | jq -r '.[2][0]'



```La réponse:

```
gilles: donne moi la definition de superman
jarvis: Je me renseigne
jarvis: [
  "Superman est un super-héros de bande dessinée américaine appartenant au monde imaginaire de l’Univers DC."
]

```

Je n'arrive pas à me débarasser des crochets ! grrrr....

Si je le fais en bash, il n'y a pas de souci. Quelqu'un aurai un avis ?

**Comment by Gilles76** [comment]
Autoréponse ;0)

mettre echo et ça fait l'affaire.....

**Comment by alexylem** [comment]
Tu peux activer les issues sur ton repo, j'aimerais te logger une proposition d'amélioration sur ton plugin :smile:

**Comment by Gilles76** [comment]
Désolé, je ne sais pas encore bien utiliser github, mais ça vient.

C'est bon, les issues sont accessibles.
