### ISSUE TITLE
Jarvis pose une question

### ISSUE THREAD

**Issue by Le42Vaincra** [alexylem/jarvis#233]
### Description

Bonjour, 
J'aimerai savoir comment faire en sorte que JARVIS me pose une question, à laquelle je dois répondre oui/non.
Le but est que JARVIS attende ma réponse et agisse en fonction de la question posée avant.

### Exemple

JARVIS -Dois-je fermer la porte ?
Moi -Oui !
(_JARVIS ferme la porte_)

**Comment by alexylem** [comment]
Commandes imbriquées?
http://domotiquefacile.fr/jarvis/content/commands

Mais que sera le déclencheur de cette question? une commande? un évènement?

**Comment by Le42Vaincra** [comment]
Oulalah c'est la fatigue j'aurai du mieux chercher avant de demander. 
Le déclencheur sera une commande, je fais parti d'un groupe dans une école d'ingénieur et pour un workshop on va tenter d'ajouter une IA sur JARVIS qui analyse le comportement d'un habitant et peut prendre des initiative et proposer des actions. Si cette IA est assez bien on pourra éventuellement proposer un plugin pour JARVIS ! Merci pour la réponse rapide et surtout pour le travail sur JARVIS c'est vraiment génial !

**Comment by alexylem** [comment]
@Le42Vaincra avec plaisir, content que ca vous plaise et vous aide dans votre projet.
Si vous voulez contribuer, sachez qu'une petite publication sur vos travaux avec Jarvis apporterait beaucoup à la communauté et m'aiderait à faire connaitre Jarvis!
Alex.

**Comment by jessux** [comment]
Bonjour,

Je me permet de répondre à cette conversation.
Moi ce que j'aimerais faire c'est pouvoir envoyer une commande à JARVIS par le biais d'un JSON qui fait appel à une commande (ex: musique) mais qui n'est autre qu'une question avec plusieurs commande imbriquées.

>*MUSIQUE* ==say "Voulez-vous un peux de musique ?"
> (>)*OUI*==(lance la musique)
> (>)*NON*==say "Ok va pour le silence"

*sans les parenthèses*

malheureusement, pour le moment quand j’envoie mon JSON {"order":"musique"} jarvis me pose la question mais impossible de lui répondre...

Une idée?

ps: Vraiment super ce petit jarvis sinon :)

**Comment by alexylem** [comment]
Ca devrait fonctionner, tu peux coller l'ensemble des commandes imbriquées dans une section code qu'on y voit plus clair (selection tout ton texte puis bouton insert code) ? La je vois aussi un espace entre `MUSIQUE` et `==`. Je te conseille aussi d'utiliser des wildcards (`*`)
```
*MUSIQUE*==say "Voulez-vous un peux de musique ?"
>*OUI*==say "Ok" && ./musique.sh
>*NON*==say "Ok va pour le silence"
```
Si ca marche toujours pas, peux-tu créer coller le résultat de la console en mode troubleshooting?

**Comment by jessux** [comment]
Le code de la commande est exactement celui que tu as repris.
```
*MUSIQUE*==say "Voulez-vous un peux de musique ?"
>*OUI*==say "Ok" && ./actions/musique.sh
>*NON*==say "Ok va pour le silence"
```
le resultat est que jarvis me dit _Voulez-vous un peux de musique ?_

avec la requête  
```
curl -d '{"order":"joue de la musique"}' http://127.0.0.1:8080
```
resultat : 

```
{"hestia":"Voulez-vous un peux de musique ?"}
```

```
INFO:snowboy:Silence
127.0.0.1 - - [16/Nov/2016 19:12:35] "POST / HTTP/1.1" 200 -
INFO:snowboy:Silence
INFO:snowboy:Silence

```
resultat de la reconnaissance vocale juste après la requete 

`
?(listening...)
`
et par une autre requete json

```
curl -d '{"order":"oui"}' http://127.0.0.1:8080 
{"hestia":"Je n'ai pas compris: oui"}]`
```

**Comment by alexylem** [comment]
AAAAAAhhhh je comprends, tu utilises le plugin Jarvis API et effectivement il ne support pas (encore) les commandes imbriquées.
SI tu utilises Jarvis directement, ca devrait fonctionner, ex en mode clavier/muet:
```
$> ./jarvis.sh -nkm
Jessux: Jouer de la musique
Hestia: Voulez-vous un peu de musique ?
Jessux: Oui
Hestia: Ok
```
Pour le support des commandes imbriquées dans Jarvis API (via JSON), merci de créer un ticket sur le repo du plugin:
https://github.com/alexylem/jarvis-api/issues/new

**Comment by jessux** [comment]
Oui exactement
En mode calvier/muet ça fonctionne comme il faut.

Je vais alors créer un ticket alors. 

Merci.
