### ISSUE TITLE
Comment utiliser le plugin Jeedom de Jarvis?

### ISSUE THREAD

**Issue by parrain27** [alexylem/jarvis#234]
bonjour et surtout un énorme merci a toi pour ton travail cela fait 1 ans que j'essai de créé mon jarvis (gros fan de tony stark mdr)
en vein étant pas très doué 

mon petit souci étant que étant noob je galère a paramétré jarvis avec jeedom

**Comment by wikijm** [comment]
Bonjour @parrain27

As-tu installé le plugin Jeedom ? http://domotiquefacile.fr/jarvis/plugins/jeedom

**Comment by parrain27** [comment]
oui pas noob a ce point :p 
bien config ma cle api mon ip

mais zero reaction a par bonjour et oui

**Comment by dud29** [comment]
Bonjour,  @parrain27 as tu vérifie si la partie interaction de Jeedom reçoit les ordres que tu envoies. ça permettra de vérifier si c'est un problème du à Jarvis ou si c'est du à Jeedom.
Dud29

**Comment by alexylem** [comment]
J'allais le dire, une copie de ta console avec Jarvis lancé en mode troubleshooting nous aidera...
Ou au moins un petit:
```shell
$> ./jarvis.sh -vx "allume la lumière"
```
(j'en profite pour vous montrer le nouveau flag `-v` que j'ai implémenté pour forcer le mode verbose/troubleshooting)

**Comment by parrain27** [comment]
bon aujourd'hui elle fait la tronche elle veut plus me répondre mdr voila le résultat de la commande alex

Debian GNU/Linux comes with ABSOLUTELY NO WARRANTY, to the extent
permitted by applicable law.
Last login: Wed Nov 16 10:23:55 2016 from 192.168.1.31
pi@raspberrypi:~ $ ./jarvis.sh -vx "allume la lumière"
-bash: ./jarvis.sh: No such file or directory
pi@raspberrypi:~ $ cd jarvis
pi@raspberrypi:~/jarvis $ ./jarvis.sh -vx "allume la lumière"
DEBUG: program_startup hook
plugins/jarvis-wikipedia/config.sh: line 2: $'\r': command not found
$> pg_jc_turn on "$order" && say "Voilà"
ERROR: no device maching allume la lumière
katy: commande introuvable maitre
DEBUG: program exit handler
DEBUG: program_exit hook
pi@raspberrypi:~/jarvis $

**Comment by parrain27** [comment]
et le mode trouble 

DEBUG: program_startup hook
plugins/jarvis-wikipedia/config.sh: line 2: $'\r': command not found
Starting RestAPI server on http://192.168.1.5:8080
katy: bonjour maitre
User defined commands:
cat: jarvis-commands: No such file or directory

Commands from plugin jarvis-api:

Commands from plugin jarvis-domogeek:
*JP* *MAINTENANT*       *JP* *DEMAIN*
*TARIF* *MAINTENANT*    *TARIF* *DEMAIN*
                        *SAINT*
*LEVER*|*LEVE* *SOLEIL* *COUCHER*|*COUCHE* *SOL
Commands from plugin jarvis-gmail:
*MAIL*
Commands from plugin jarvis-home-control:
*ALLUME*                *ETEIN*
Commands from plugin jarvis-jeedom:
*
Commands from plugin jarvis-kodi:
CODY VALIDE             CODY GAUCHE             CODY DROITE
CODY HAUT               CODY BAS                CODY PAUSE|CODY JOUER
CODY ARRET              CODY MUET               CODY NON MUET
CODY RETOUR             CODY AFFICHE *INFORMATI CODY ACTIVE *SOUS-TITRE
CODY DESACTIVE *SOUS-TI CODY SOUS-TITRE SUIVANT CODY PLEIN ECRAN
CODY MENU PRINCIPAL     QUITTER CODY            RELANCER CODY
LANCER CODY             CODY *LISTE*FILMS       CODY *LISTE*MUSIQUES
CODY *LISTE*PHOTOS      CODY VOLUME BAS         CODY VOLUME NORMAL
CODY VOLUME HAUT
Commands from plugin jarvis-math:
*CALCUL* (*)
Commands from plugin jarvis-weather-wunderground-fr:
*METEO*DEMAIN*          *METEO*
Commands from plugin jarvis-wikipedia:
*DONNE*DEFINITION*DE (*
katy: Waiting to hear 'katy'
maitre: (listening...)
rec
DEBUG: speech duration was 100 (10 = 1 sec)
DEBUG: too long for a trigger (min 0.5 max 1.5 sec), ignoring...
rec

**Comment by parrain27** [comment]
bon vais essaye a partir du plugin sur jeedom

**Comment by alexylem** [comment]
Bon alors déjà:
```
plugins/jarvis-wikipedia/config.sh: line 2: $'\r': command not found
```
Je pense que tu as un problème dans ta config du plugin Wikipedia. Corrige le ou désinstalle le plugin.
```
ERROR: no device maching allume la lumière
```
Tu utilises le plugin Home Control? Il vient d'ou ce code?
```
$> pg_jc_turn on "$order" && say "Voilà"
```
A priori rien à voir avec Jarvis, mais plutôt avec tes plugins / config de tes plugins...

Si tu veux utiliser Jeedom, commence déjà par n'installer que ce plugin pour éviter de te faire polluer par les autres plugins...

**Comment by parrain27** [comment]
voila juste avec jeedom

------------ Config ------------
jv_version           16.11.20
system               Linux 4.4.32+ armv6l
os                   "Raspbian GNU/Linux 8 (jessie)"
language             fr_FR
play_hw              hw:0,1
rec_hw               hw:1,0
speaker              ALSA
microphone           Hewlett-Packard
trigger_stt          snowboy
command_stt          bing
tts_engine           svox_pico
conversation_mode    true
--------------------------------

DEBUG: program_startup hook
katy: bonjour maitre
User defined commands:
*AIDE*                  *BONJOUR*|*SALUT*       *COMMENT*APPELLE*
*MERCI*                 *AU REVOIR*|*BYE*       ANNULE*|TERMINE*
ENCORE*                 *TEST*                  *VERSION*
*REPETE (*) ET (*)      *CA VA*                 >*OUI*
>*NON*
Commands from plugin jarvis-jeedom:
*
katy: Waiting to hear 'katy'
maitre: (listening...)
DEBUG: models=jarvice,jarvis,katy,snowboy
ALSA lib confmisc.c:1286:(snd_func_refer) Unable to find definition 'cards.bcm2835.pcm.front.0:CARD=0'
ALSA lib conf.c:4259:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:4738:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM front
ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.rear
ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.center_lfe
ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.side
ALSA lib confmisc.c:1286:(snd_func_refer) Unable to find definition 'cards.bcm2835.pcm.surround51.0:CARD=0'
ALSA lib conf.c:4259:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:4738:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM surround21
ALSA lib confmisc.c:1286:(snd_func_refer) Unable to find definition 'cards.bcm2835.pcm.surround51.0:CARD=0'
ALSA lib conf.c:4259:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:4738:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM surround21
ALSA lib confmisc.c:1286:(snd_func_refer) Unable to find definition 'cards.bcm2835.pcm.surround40.0:CARD=0'
ALSA lib conf.c:4259:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:4738:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM surround40
ALSA lib confmisc.c:1286:(snd_func_refer) Unable to find definition 'cards.bcm2835.pcm.surround51.0:CARD=0'
ALSA lib conf.c:4259:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:4738:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM surround41
ALSA lib confmisc.c:1286:(snd_func_refer) Unable to find definition 'cards.bcm2835.pcm.surround51.0:CARD=0'
ALSA lib conf.c:4259:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:4738:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM surround50
ALSA lib confmisc.c:1286:(snd_func_refer) Unable to find definition 'cards.bcm2835.pcm.surround51.0:CARD=0'
ALSA lib conf.c:4259:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:4738:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM surround51
ALSA lib confmisc.c:1286:(snd_func_refer) Unable to find definition 'cards.bcm2835.pcm.surround71.0:CARD=0'
ALSA lib conf.c:4259:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:4738:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM surround71
ALSA lib confmisc.c:1286:(snd_func_refer) Unable to find definition 'cards.bcm2835.pcm.iec958.0:CARD=0,AES0=4,AES1=130,AES2=0,AES3=2'
ALSA lib conf.c:4259:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:4738:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM iec958
ALSA lib confmisc.c:1286:(snd_func_refer) Unable to find definition 'cards.bcm2835.pcm.iec958.0:CARD=0,AES0=4,AES1=130,AES2=0,AES3=2'
ALSA lib conf.c:4259:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:4738:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM spdif
ALSA lib confmisc.c:1286:(snd_func_refer) Unable to find definition 'cards.bcm2835.pcm.iec958.0:CARD=0,AES0=4,AES1=130,AES2=0,AES3=2'
ALSA lib conf.c:4259:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:4738:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM spdif
ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.hdmi
ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.hdmi
ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.modem
ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.modem
ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.phoneline
ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.phoneline
Cannot connect to server socket err = No such file or directory
Cannot connect to server request channel
jack server is not running or cannot be started
INFO:snowboy:Silence
INFO:snowboy:Silence
INFO:snowboy:Silence
INFO:snowboy:Silence
INFO:snowboy:Silence
INFO:snowboy:Silence
INFO:snowboy:Silence
INFO:snowboy:Silence
INFO:snowboy:Silence
INFO:snowboy:Silence
INFO:snowboy:Silence
INFO:snowboy:Silence
INFO:snowboy:Silence
INFO:snowboy:Silence
INFO:snowboy:Silence
INFO:snowboy:Silence
INFO:snowboy:Silence
INFO:snowboy:Silence
INFO:snowboy:Silence
INFO:snowboy:Silence
INFO:snowboy:Silence
INFO:snowboy:Silence
INFO:snowboy:Silence
INFO:snowboy:Silence
INFO:snowboy:Silence
INFO:snowboy:Silence
INFO:snowboy:Silence
INFO:snowboy:Silence
INFO:snowboy:Silence
INFO:snowboy:Silence
INFO:snowboy:Silence
INFO:snowboy:Silence
INFO:snowboy:Silence
INFO:snowboy:Silence
INFO:snowboy:Silence
INFO:snowboy:Silence
INFO:snowboy:Silence
INFO:snowboy:Silence
INFO:snowboy:Silence
INFO:snowboy:Silence
INFO:snowboy:Silence
INFO:snowboy:Silence
INFO:snowboy:Silence
INFO:snowboy:Keyword 2 detected at time: 2016-11-22 13:28:40
sys.excepthook is missing
lost sys.stderr
DEBUG: modelid=1
jarvis
$> say "$(curl "http://$jv_pg_jd_ip:$jv_pg_jd_port/${jv_pg_jd_path}core/api/jeeApi.php?apikey=$jv_pg_jd_apikey&type=interact" --data-urlencode "query=$order")"
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (6) Could not resolve host: http
katy:
maitre: (listening...)
utils/timeout.sh
DEBUG: speech duration was 90 (10 = 1 sec)
DEBUG: too long for a command (max 4 secs), ignoring...
utils/timeout.sh

**Comment by parrain27** [comment]
bon après une journée c'est bon je parle elle me répond mon problème reste avec jeedom je doit mal le configurer

**Comment by parrain27** [comment]
![jeedom](https://cloud.githubusercontent.com/assets/13090519/20530405/85a9cc60-b0d3-11e6-9fc3-1337fac75af0.png)

**Comment by alexylem** [comment]
![image](https://cloud.githubusercontent.com/assets/11017174/20533063/847654fe-b0dc-11e6-9163-8b4571feda80.png)
Enlève les `<` et `>`
Tu dois mettre l'`ip` et l'`apikey` tels quels.

**Comment by parrain27** [comment]
donc comme ceci mais pareil
![jeedom](https://cloud.githubusercontent.com/assets/13090519/20533473/ece88290-b0dd-11e6-835b-26c265119d85.png)

**Comment by alexylem** [comment]
```
DEBUG: speech duration was 90 (10 = 1 sec)
DEBUG: too long for a command (max 4 secs), ignoring...
```
Si c'est ca ton problème, rien à voir avec Jeedom, regarde plutôt du côté de:
#33 et #135 

Tu peux tester tes interactions Jeedom sans micro en mode clavier:
```shell
$> ./jarvis.sh -nkm
```
Ou en passant directement ton interaction Jeedom au démarrage:
```shell
$> ./jarvis.sh -x "Fais ceci"
```

**Comment by parrain27** [comment]
c'est bon sa marche va savoir pourquoi j'ai rien changer merci de ton aide alex :)
