### ISSUE TITLE
Utiliser la fonctionnalité Projets / Use Projects GitHub functionnality

### ISSUE THREAD

**Issue by wikijm** [alexylem/jarvis#235]
### Description

Utiliser la fonctionnalité Projects de GitHub pour définir par exemple une to do list, ou les évolutions prévues.

**Comment by alexylem** [comment]
Ok très bonne idée, je bien de voir la vidéo pour comprendre à quoi ca pouvait bien servir...
https://youtu.be/C6MGKHkNtxU

Des idées de projet? On top of my head:
- Jarvis Core
- TTS Engines
- STT Engines
- User Interface
- Plugins (pour faciliter la discussion initiée sur #230)
En poussant un peu plus loin:
- Experimentations
- Marketing
- Documentation (questions, answers, faq...)
Quoi que on peut déjà utiliser les Labels pour la plupart... d'autres idées d'utilisation?

Pour les colonnes, on restera basique dans le genre:
- To be discussed
- Confirmed
- On-going
- Blocked
- Done
(Aujourd'hui vous avez du remarqué que j'utilise les milestones pour ca...)

**Comment by wikijm** [comment]
Ça me semble parfait :simple_smile:

**Comment by Jean-Bernard-Hallez** [comment]
a la façon K2000... et 007...

Votre mission si vous l'accepté est de réussir à intégrer la reconnaissance vocal au travers d'une montre connecté !!! Plus besoin d'être à coté du micro pour lancer les commandes...  ca serait que du bonheur !!!!
Qui va y arriver... Hélas pas moi... je ne suis qu'un petit amateur de bricolage... mais ça serait sincèrement le top du top... Au plaisir de voir une application en ce sens... JB.

**Comment by alexylem** [comment]
Ca a déjà été discuté ici: #206
C'est tout à fait possible avec android auto-wear et tasker (avec le plugin jarvis-api). Il me semble que certains utilisateurs de jarvis l'ont déjà fait.

**Comment by wikijm** [comment]
Mis en place hier.
