### ISSUE TITLE
Plugin Jouer de la musique local ou distante (flux possible)

### ISSUE THREAD

**Issue by ghost** [alexylem/jarvis#238]
### Description

Pouvoir faire jouer Jarvis des musique (mp3 ,etc ...) à partir de différentes sources comme upnp/dlna, (NFS, samba optionnel car il est mieux de centraliser avec un serveur upnp). De plus il sera possible de manipuler le seveur de musique en direct à partir d'un client android (mac et windows probablement).

En premier lieu, je commencerai doucement par le lancement de play-lists. Puis des instructions plus précises. De base les commandes comme monter/descendre le son seront là.

Si Alex confirme ma solution, je propose mpd en tant que serveur de musique local si besoin (sinon mpd peut-être déporté sur le même réseau), mpc en tant que client qui recevra les commande et djmount en tant que client upnp.

Tout ces programmes ont des dépendances minimes, une faible empreinte, et sont disponible dans la majorité des distributions.

Ca vous tente, votez pour moi ! ;0)

**Comment by fatoldsun00** [comment]
Salut,

Je decouvre le soft mais je comptai m'y mettre apres un plugin que je debute pour les hue. Par contre j'etais parti sur squeezebox mais suis ouvert. Bref : a voté !

**Comment by kiki51** [comment]
+1 aussi
Pourquoi ne pas proposer un mode streaming aussi, je pense aux utilisateurs de spotify ou deezer qui seraient ravis ;-p

Eric

**Comment by slobberbone** [comment]
SAlut,
A voir mais je pense que tout ça pourrait être fait avec PulseAudio (cf : https://github.com/alexylem/jarvis/issues/200 )
Pareil, il y aura la possibilité d'avoir un serveur UPNP afin de balancer le son sur une sortie PulseAudio de Jarvis depuis un appareil Android ou tout autre device UPNP ...
Centraliser nos efforts autour de PulseAudio me semble être une bonne voie !

Au passage, voici une démo que j'ai fait pour Jeedom : https://www.youtube.com/watch?v=dOVXAlCRe1c

**Comment by wikijm** [comment]
@ghost As-tu commencé le développement de ton plugin ?

**Comment by alexylem** [comment]
Ghost veut dire que l'utilisateur n'existe plus :)
Je crois que c'est @Sellig28

**Comment by wikijm** [comment]
Ah ... bien bien bien  :sweat_smile:

**Comment by Sellig28** [comment]
@alexylem et @wikijm ,

Oui, j'ai repris l'activité de ghost.

Par contre je crois que l'on peut cloturer car je vais pas réinventer la roue vu qu'il existe un polugin de musique.
