### ISSUE TITLE
mot entre les (*) des commandes "repeat"

### ISSUE THREAD

**Issue by remjou1** [alexylem/jarvis#24]
voila en fait j'ai une api qui me permet de m'envoyer des notifications pas sms... je l'utilise en events mais je voudrais éventuellement envoyer un sms vocalement (parce que c'est cool :) ) mais apparement il faut mettre un mot entre deux variable.... c'est embetant je me vois pas dire : 

"dis et a et ma et femme et que et je et vais et rentrer"

bref t'as compris c'est embetant... une solution ?

**Comment by alexylem** [comment]
Le "et" était juste pour l'exemple.
```
DIS A (*) QUE (*)==./ton_script.sh (1) (2)
```
"Dis à ma femme que je vais rentrer"
```
$> ./tonscript.sh "ma femme" "je vais rentrer"
```

**Comment by remjou1** [comment]
euh... je comprend pas le truc du script... pk avoir besoin du script ??

**Comment by alexylem** [comment]
si tu es capable d'appeler ton API directement en une ligne, tu n'as pas besoin d'un script en effet.

**Comment by remjou1** [comment]
ah ok c'est pour ça le truc.... ok merci alex !!
