### ISSUE TITLE
Plugin IFTTT

### ISSUE THREAD

**Issue by NYGHOST** [alexylem/jarvis#240]
Encore un nouveau addon je viens de decouvrir une appli nommée IFTTT permettant de "programmer" de maniere simple des actions entre plusieurs logiciels.
Il s'avere quelle permettrait par exemple de demande a alexa d'eteindre des choses automatiquement lorsque que lon part de chez soit. Je vise ici les moins dev d'entre nous qui pourrait alors utiliser leur tel avec jarvis.

**Comment by Gilles76** [comment]
Perso iftt est un service externe. Je n'aime pas trop voir certaines donnees dehors. Idem pour Jarvis pour le moment, envoyer à bing ou autre pas cool... Mais bon tant qu'il n'y a pas de solution local fiable.

**Comment by NYGHOST** [comment]
Je suis d'accord avec toi dans l'ensemble d'autant plus que l'appli centralise tous tes comptes et localisations. Mais d'un autre cote avec un gmail pour envoyer les mails de jarvis donc neutre, aucun pb. Apres je donnais ca pour les moyens "bidouilleurs" qui pourrait alors eux aussi utiliser jarvis.

**Comment by NYGHOST** [comment]
Snowboy marche pas mal mais il fonction bien si tu utilises des mots courts. Je suis en hors ligne et @alexylem a corrig� r�cement un bug.

**Comment by alexylem** [comment]
IFTT est le leader dans son domaine. Je pense qu'il serait très intéressant que quelqu'un développe un plugin, libre à ceux qui le souhaitent après de l'installer et l'utiliser.

**Comment by NYGHOST** [comment]
En fait il existe deja quelque chose il suffirai alors d'envoyer par mail la commande en script correspondant a l'action ex: ./jarvis.sh "ferme porte" cf: voir "planification commande pour des exmples de script

https://github.com/enkydu/raspi_runner
Et le ifttt voir raspberry sur ifttt

**Comment by Gilles76** [comment]
@alexylem ,

Bien sûr qu'il faut développer ce genre de plugin, beaucoup de personnes utilisent ifft que ce soit par le téléphone ou la domotique.

@NYGHOST 

merci pour tes recherches. cela permettra d'ouvrir le champ aux personnes d'IFTT.

**Comment by Latlantis** [comment]
Bonjour, perso j'ai déjà essayé IFTTT avec Jarvis, en fait j'ai ajouté un lien Curl dans cron qui me permet de contacter IFTTT avec mon compte et d'être notifié par Jarvis en utilisant l'applet MAKER à une heure programmé. L'inconvénient c'est que la notification peut prendre jusqu'à 30 minutes voir plus de retard pour se déclencher; donc je ne recommande pas IFTTT pour l'enclenchement d'un événement immédiat comme peut l'être une "fermeture de porte"; mais pour un service gratuit on en vas pas s'en plaindre ;-)

**Comment by alexylem** [comment]
Ah vous souhaitez utiliser IFTTT pour déclencher Jarvis? Je pensais à l'inverse (déclencher une action IFTTT depuis un ordre reçu par Jarvis).
Dans ce cas je vous proposer d'utiliser le plugin Jarvis API JSON
http://domotiquefacile.fr/jarvis/plugins/jarvis-api
```shell
$> curl -d '{"say":"Hello World"}' http://192.168.1.20:8080
[{"Jarvis":"Hello World"}]
```
IFTTT doit pouvoir déclencher des requêtes HTTP POST...
PS: on peut aussi lui faire exécuter des commandes, voir le détail du plugin.

**Comment by wikijm** [comment]
Pas de retour depuis les solutions proposées @Latlantis et @alexylem en date du 19 Novembre 2016.
J'en conclus que cela a répondu au besoin initial.

Ne pas hésiter à ré-ouvrir la discussion si évolution 😉
