### ISSUE TITLE
Après avoir crée un plugin il me dit erreur de Command... si je renomme le dossier tout est ok !?!

### ISSUE THREAD

**Issue by Jean-Bernard-Hallez** [alexylem/jarvis#241]
Bonjour... je décide de partager avec vous des plugins pour jarvis... mon soucis actuel et avec une installation toute neuve sur un raspberry pi il se passe ceci:

Je lance Jarvis et lance une commande de mon plugin: ca me répond:

jibé: une citation
./jarvis.sh: ligne 523: *CITATION*==say : commande introuvable
jarvis: Erreur dans votre commande

 je modifie juste le répertoire complet:    jarvis-citations en jarvis-cequejeveux  en modifiant le fichier config.sh pour le chemin et tout rentre dans l'ordre... si je renomme mon répertoire avec l'ancien nom... ca rebug à nouveau !!!!!!!!!!!!!!!

Essayer de télécharger la St et dite moi si il fonctionne chez vous ?
Avez vous le même problème ??? (je me sentirais moins seul lol)

**Comment by alexylem** [comment]
Peux-tu partager l'URL du repo de ton plugin? Merci

**Comment by alexylem** [comment]
Ok d'après ton mail il s'agit de https://github.com/Jean-Bernard-Hallez/jarvis-lacitation
Essayons de corriger celui-ci, je l'installe et je teste...

**Comment by alexylem** [comment]
* A l'installation, j'ai l'erreur
```
-bash: ./install.sh: Permission denied
```
C'est parce que tes fichiers `install.sh` et `uninstall.sh` n'ont pas les flag d'execution, il faut:
```shell
$> chmod a+x install.sh uninstall.sh
```

Sinon j'ai installé le plugin pour moi ca marche:
![image](https://cloud.githubusercontent.com/assets/11017174/20445808/ec34c94e-add6-11e6-88ad-8c5e6ca3cfd8.png)

Je pense que tu t'es vraiment cassé la tête avec ton fichier `citationlunum.txt`, tu aurais pu simplement en choisir une au hasard à chaque fois:

**functions.sh**
```shell
jv_pg_ct_citation () {
    citations=("Première citation" "Deuxième citation" "Troisième citation" "Quatrième citation")
    say "${citation[$RANDOM % ${#citations[@]} ]}"
}
```

**Comment by Jean-Bernard-Hallez** [comment]
C'est vrai tu as raison...  j'y avais songé... mais l'utilisant deja avec Domoticz je me suis aperçu que  par le hasard  il te sort la même phrase...ou il en oublie...

J'ai fait le programme ainsi pour être sûr que chaque phrase soit dite  au moins une fois... lol...
Et 
Envoyé depuis mon appareil Samsung

-------- Message d'origine --------
De : Alexandre Mély <notifications@github.com> 
Date : 18/11/2016  21:39  (GMT+01:00) 
À : alexylem/jarvis <jarvis@noreply.github.com> 
Cc : Hallez <jbhallez@aol.com>, Author <author@noreply.github.com> 
Objet : Re: [alexylem/jarvis] Après avoir crée un plugin il me dit erreur de Command... si je renomme le dossier tout est ok !?! (#241) 


A l'installation, j'ai l'erreur


-bash: ./install.sh: Permission denied


C'est parce que tes fichiers install.sh et uninstall.sh n'ont pas les flag d'execution, il faut:

$> chmod a+x install.sh uninstall.sh

Sinon j'ai installé le plugin pour moi ca marche:



Je pense que tu t'es vraiment cassé la tête avec ton fichier citationlunum.txt, tu aurais pu simplement en choisir une au hasard à chaque fois:

functions.sh

jv_pg_ct_citation () {
    citations=("Première citation" "Deuxième citation" "Troisième citation" "Quatrième citation")
    say "${citation[$RANDOM % ${#citations[@]} ]}"
}

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/alexylem/jarvis","title":"alexylem/jarvis","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/alexylem/jarvis"}},"updates":{"snippets":[{"icon":"PERSON","message":"@alexylem in #241: * A l'installation, j'ai l'erreur\r\n```\r\n-bash: ./install.sh: Permission denied\r\n```\r\nC'est parce que tes fichiers `install.sh` et `uninstall.sh` n'ont pas les flag d'execution, il faut:\r\n```shell\r\n$\u003e chmod a+x install.sh uninstall.sh\r\n```\r\n\r\nSinon j'ai installé le plugin pour moi ca marche:\r\n![image](https://cloud.githubusercontent.com/assets/11017174/20445808/ec34c94e-add6-11e6-88ad-8c5e6ca3cfd8.png)\r\n\r\nJe pense que tu t'es vraiment cassé la tête avec ton fichier `citationlunum.txt`, tu aurais pu simplement en choisir une au hasard à chaque fois:\r\n\r\n**functions.sh**\r\n```shell\r\njv_pg_ct_citation () {\r\n    citations=(\"Première citation\" \"Deuxième citation\" \"Troisième citation\" \"Quatrième citation\")\r\n    say \"${citation[$RANDOM % ${#citations[@]} ]}\"\r\n}\r\n```"}],"action":{"name":"View Issue","url":"https://github.com/alexylem/jarvis/issues/241#issuecomment-261636074"}}}

**Comment by alexylem** [comment]
Vraiment bizarre, sache que normalement tu n'as pas besoin de supprimer un plugin pour re-télécharger, c'est mis à jour automatiquement.

Voici mes conseils pour développer un plugin Jarvis.

Il faut que ton plugin soit développé en dehors de ton dossier Jarvis (sinon ca va être la pagaille).
Par exemple tu peux avoir (c'est ce que je fais moi pour tous mes plugins):
```shell
$> cd; ls
jarvis/
jarvis-citation/
```
Ensuite pour le **tester** localement tu peux **temporairement** créer un lien symbolique dans le dossier plugins de Jarvis
```shell
$> cd jarvis/plugins/
$> ln -s ../../jarvis-citation ./
```
Il suffit de lancer Jarvis, c'est comme si ton plugin était installé, et tu peux modifier ton code les changements sont disponibles tout de suite.
**Attention** avant de publier les changements sur ton repository, il faudra remettre `config.sh` à son état d'origine (sans tes settings personnels). Il te faudra aussi tester l'installation et la configuration de ton plugin, pour cela, il te faut d'abord supprimer le lien symbolique et installer ton plugin comme un utilisateur:
```shell
$> cd jarvis/plugins/
$> rm -rf jarvis-citation # juste le lien :)
$> cd ../
$> ./jarvis.sh -p <GIT_URL_DE_TON_PLUGIN>
```
Si par la suite tu fais des modifications dans ton plugin et que tu les envoies sur ton repo, ton jarvis mettra automatiquement la version installée de ton plugin à jour, ce que tu peux forcer avec:
```shell
$> ./jarvis.sh -u
```
Voila j'espère que ca t'aidera pour tes prochains plugins.

**Comment by Jean-Bernard-Hallez** [comment]
oui tout cela j'en pu en faire un super big-mac bien sympathique...   ;-)
Merci de ton aide...
