### ISSUE TITLE
./jarvis.sh: line 584: _STT: command not found

### ISSUE THREAD

**Issue by Niunzag** [alexylem/jarvis#243]
![20161118_184731](https://cloud.githubusercontent.com/assets/23559672/20440282/a11be472-adbf-11e6-916e-7c51e1796c11.jpg)

**Comment by alexylem** [comment]
Looks like your Jarvis is not properly set-up (you miss the STT engine for the hotword).
Just restart the wizard (and go till the end):
```
$> ./jarvis.sh -i
```
And let me know if that works

**Comment by wikijm** [comment]
No answer from @Niunzag since 18 Nov 2016 => Closed
