### ISSUE TITLE
Réglages CM1000-USB ?

### ISSUE THREAD

**Issue by azertigrou** [alexylem/jarvis#244]
Bonjour Alexy,

Je viens de recevoir mon micro CM1000-USB. 
J'ai les mêmes soucis qu'avec un micro à 10€ , c'est à dire que je suis obligé de parler à 1m du micro max pour qu'il reconnaisse mes mots avec Bing.
J'ai beau joué sur le volume du micro dans alsamixer, si je le met trop haut il ne reconnait pas que je dis quelque chose et si je je mets top bas, il reconnait n'importe phrase et capte trop les bruits d'ambiance.
Une idée ? Est-ce que quelqu'un a déjà réussi à faire marcher le système a moins de 1m.

**Comment by alexylem** [comment]
>si je je mets top bas, il reconnait n'importe phrase et capte trop les bruits d'ambiance

C'est le rôle du hotword, tu utilises bien snowboy? Tu peux aussi jouer sur la sensibilité de snowboy dans les settings de Jarvis

**Comment by azertigrou** [comment]
pas mieux en jouant aux réglages:
max_noise_duration_to_kill="10" 
min_noise_duration_to_start="0.1" 
min_noise_perc_to_start="2%" # 
min_silence_duration_to_stop="0.5" # 
min_silence_level_to_stop="1%" 

Le snowbly sensibility est à 0.5
Cela fonctionne très bien mais à 10 cm. Dès que je m'éloigne de plus de 10cm, cela ne fonctionne plus. J'augmente le son du micro, cela fonctionne encore moins bien (il prend tous les bruits et ne reconnait rien).

J'utilise snowboy uniquement pour le maginc word. Ensuite, j'utilise bing

**Comment by alexylem** [comment]
Ok.
Est-ce que en augmentant le volume du micro la reconnaissance de snowboy fonctionne à distance?
* Si Oui tant mieux, donc dans ce cas c'est Bing qui ne reconnait pas? Que revoit-il?
* Si Non essaye de baisser la sensibilité de snowboy, ca donne quoi?

**Comment by alexylem** [comment]
@physicien je sais que tu as ce micro (c'est pour ca que je l'avais rajouté dans la liste). Tu peux partager tes réglages avec @azertigrou ?
Merci!

**Comment by azertigrou** [comment]
Quand je dis le magic word (en gros quand j'appelle Jarvis), il répond bien.
C'est la suite : aucune commande ne passe lorsque je suis à plus de 50cm du micro.

**Comment by physicien** [comment]
@azertigrou À Le problème ici est l'entraînement de Bing. Personnellement, j'utilise Wit et j'ai de moins en moins ce problème, car je peux le corriger depuis le site en allant vérifier les extraits sonores et en transcrivant ce que j'avais dit. Je ne sais pas si Bing a aussi cette fonction, mais l'apprentissage dirigé est la clef dans mon cas.

**Comment by azertigrou** [comment]
J'essaie Wit et je vous fais un retour

**Comment by jeedomclaude** [comment]
Bonjour a tous
En ce qui me concerne, cela fonctionne plutôt bien avec micro CM1000 USB ,et Jeedom
J'ai laissé les réglages sensibilité par défaut, j'ai juste modifié Le snowbly sensibility à 0.35, car j'avais beaucoup trop de déclenchement avec les bruits de fond.
 A  2 m, la compréhension reste acceptable. Je vais encore essayer d'affiner les réglages, je vous les ferai passer par la suite.

**Comment by azertigrou** [comment]
Bonjour,

Finalement, cela fonctionne de mieux en mieux (je ne sais pas trop pourquoi). Peut-être car je l'ai laissé m'écouter pendant une semaine et que wit me reconnait de mieux en mieux.
Bref, ce micro fonctionne bien à 6m (dans un salon de 50m²). En fait, le micro marche très bien. La difficulté est que le son résonne (pourtant mon salon est meublé ;) )
Pour snowboy, j'ai mis 0.45 , mais c'est vrai que parfois quand ma femme gueule un peu, ca se déclenche un peu tout seul; mais moins, Jarvis ne reconnait pas son nom.

Mon Jarvis (elle s'appelle Lydia) reconnait une 30aine de commandes, avec des commandes imbriquées et j'utilise 9 plugins.
Merci à toute la communauté et un grand merci à Alexy qui a été très patient avec moi ;)

**Comment by alexylem** [comment]
C'est un plaisir! 👍

**Comment by ghost** [comment]
Bonjour,

le prix est quand même canon lorsqu'on lit en ce jour qu'il est à 124 euros sur amazon.fr alors qu'il n'est qu'à 58 dollars sur amazon.com.

Ce micro a toutefois le grand avantage de pouvoir en connecter d'autres pour étendre alors la portée (le centrale au rez-de-chaussée et deux autres à l'étage).

**Comment by SebLeKlatz** [comment]
bonjour à tous, 

qui de vous pourrait svp partager les réglages de son CM-1000? Je n'arrive pas à améliorer significativement les reglages par défaut, à 3m je dois encore parler fort, en direction du micro, en ar-ti-cu-lant, pour être reconnu 1 fois sur 2.

je voudrais pouvoir donner mes commandes plus "naturellement"

mes réglages par défaut : 
min_noise_duration_to_start="0.2"
min_noise_perc_to_start="2.1%" #
min_silence_duration_to_stop="0.5" #
min_silence_level_to_stop="2.1%"

merci!
