### ISSUE TITLE
jabra 410

### ISSUE THREAD

**Issue by jbouziat** [alexylem/jarvis#245]
Jabra 410 n'est pas reconnu par mon raspberry pi 3. Quand j'utilise un microphone standard celui-ci est reconnu.
Avez vous une réponse à me donner
Merci

**Comment by wikijm** [comment]
Peux-tu nous donner le résultat de la commande `aplay -D` ?

Personnellement j'ai ça (concernant le JABRA 410 uniquement) : 

>null
    Discard all samples (playback) or generate zero samples (capture)
pulse
    PulseAudio Sound Server
default
sysdefault:CARD=USB
    Jabra SPEAK 410 USB, USB Audio
    Default Audio Device
front:CARD=USB,DEV=0
    Jabra SPEAK 410 USB, USB Audio
    Front speakers
surround21:CARD=USB,DEV=0
    Jabra SPEAK 410 USB, USB Audio
    2.1 Surround output to Front and Subwoofer speakers
surround40:CARD=USB,DEV=0
    Jabra SPEAK 410 USB, USB Audio
    4.0 Surround output to Front and Rear speakers
surround41:CARD=USB,DEV=0
    Jabra SPEAK 410 USB, USB Audio
    4.1 Surround output to Front, Rear and Subwoofer speakers
surround50:CARD=USB,DEV=0
    Jabra SPEAK 410 USB, USB Audio
    5.0 Surround output to Front, Center and Rear speakers
surround51:CARD=USB,DEV=0
    Jabra SPEAK 410 USB, USB Audio
    5.1 Surround output to Front, Center, Rear and Subwoofer speakers
surround71:CARD=USB,DEV=0
    Jabra SPEAK 410 USB, USB Audio
    7.1 Surround output to Front, Center, Side, Rear and Woofer speakers
iec958:CARD=USB,DEV=0
    Jabra SPEAK 410 USB, USB Audio
    IEC958 (S/PDIF) Digital Audio Output
dmix:CARD=USB,DEV=0
    Jabra SPEAK 410 USB, USB Audio
    Direct sample mixing device
dsnoop:CARD=USB,DEV=0
    Jabra SPEAK 410 USB, USB Audio
    Direct sample snooping device
hw:CARD=USB,DEV=0
    Jabra SPEAK 410 USB, USB Audio
    Direct hardware device without any conversions
plughw:CARD=USB,DEV=0
    Jabra SPEAK 410 USB, USB Audio
    Hardware device with all software conversions`

**Comment by taostaos** [comment]
Si tu viens de l'acheter, il est bon de faire la maj du firmware.

**Comment by wikijm** [comment]
Je t'invite également à aller voir du côté de l'issue #65 (Speed / High pitch sound issue with JABRA Speaker with Raspberry Pi)

**Comment by jbouziat** [comment]
Voici le résultat des commandes que j’ai passées

lsusb

Bus 001 Device 004: ID 0b0e:0410 GN Netcom

Bus 001 Device 003: ID 0424:ec00 Standard Microsystems Corp. SMSC9512/9514 Fast Ethernet Adapter

Bus 001 Device 002: ID 0424:9514 Standard Microsystems Corp.

Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub



aplay -l

**** Liste des Périphériques Matériels PLAYBACK ****

carte 0: ALSA [bcm2835 ALSA], périphérique 0: bcm2835 ALSA [bcm2835 ALSA]

Sous-périphériques: 8/8

Sous-périphérique #0: subdevice #0

Sous-périphérique #1: subdevice #1

Sous-périphérique #2: subdevice #2

Sous-périphérique #3: subdevice #3

Sous-périphérique #4: subdevice #4

Sous-périphérique #5: subdevice #5

Sous-périphérique #6: subdevice #6

Sous-périphérique #7: subdevice #7

carte 0: ALSA [bcm2835 ALSA], périphérique 1: bcm2835 ALSA [bcm2835 IEC958/HDMI]

Sous-périphériques: 1/1

Sous-périphérique #0: subdevice #0



aplay -L

null

Discard all samples (playback) or generate zero samples (capture)

pulse

PulseAudio Sound Server

sysdefault:CARD=ALSA

bcm2835 ALSA, bcm2835 ALSA

Default Audio Device

dmix:CARD=ALSA,DEV=0

bcm2835 ALSA, bcm2835 ALSA

Direct sample mixing device

dmix:CARD=ALSA,DEV=1

bcm2835 ALSA, bcm2835 IEC958/HDMI

Direct sample mixing device

dsnoop:CARD=ALSA,DEV=0

bcm2835 ALSA, bcm2835 ALSA

Direct sample snooping device

dsnoop:CARD=ALSA,DEV=1

bcm2835 ALSA, bcm2835 IEC958/HDMI

Direct sample snooping device

hw:CARD=ALSA,DEV=0

bcm2835 ALSA, bcm2835 ALSA

Direct hardware device without any conversions

hw:CARD=ALSA,DEV=1

bcm2835 ALSA, bcm2835 IEC958/HDMI

Direct hardware device without any conversions

plughw:CARD=ALSA,DEV=0

bcm2835 ALSA, bcm2835 ALSA

Hardware device with all software conversions

plughw:CARD=ALSA,DEV=1

bcm2835 ALSA, bcm2835 IEC958/HDMI

Hardware device with all software conversions



cat /proc/asound/cards

0 [ALSA ]: bcm2835 - bcm2835 ALSA

bcm2835 ALSA



sudo nano ~/.asoundrc



pcm.!default {

type hw

playback.pcm {

type hw

slave.pcm "hw:0,0"

}

capture.pcm {

type plug

slave.pcm "hw:0,0"

}

}





pcm.!default {

type hw

card 0

}



ctl.!default {

type hw

card 0

}

**Comment by wikijm** [comment]
Penses-tu que ton alimentation USB est assez puissante ?
As-tu moyen d'utiliser un câble Y USB afin de donner plus à ton enceinte et/ou ton Raspberry ?

**Comment by wikijm** [comment]
Pour info, sur Raspberry 2 et 3, aucun problème de reconnaissance avec les JABRA 410 et 510.

**Comment by taostaos** [comment]
Pour info sur les vieux firmware, il y avait un problème avec debian.

**Comment by jbouziat** [comment]
Je suis sous Raspian Jessie
J’ai effectué la mise a jour du firmware (sudo raspi-update).
Rien n’a changé.
Par contre lorsque je démarre mon raspbery avec un autre microphone USB tout est ok. Ensuite je
déconnecte le micro et connecte à la place le Jabra celui-ci est alors reconnu et fonctionne.
Comment expliquer cela.
Merci
f rom: taostaos 
Sent: Sunday, November 20, 2016 6:24 PM
To: alexylem/jarvis 
Cc: jbouziat ; Author 
Subject: Re: [alexylem/jarvis] jabra 410 (#245)

Pour info sur les vieux firmware, il y avait un problème avec debian.

**Comment by taostaos** [comment]
Bizarre.

Je parle d'une maj du firmware du jabra a faire avec le soft jabra : http://www.jabra.fr/supportpages/jabra-speak-410#/#7410-209  et non un update de raspbian...

**Comment by jbouziat** [comment]
J’ai fait une mise a jour du firmware.
J’ai suivi l’issue #85 et cela fonctionne.
Encore merci pour vos infos.
f rom: taostaos 
Sent: Monday, November 21, 2016 4:11 PM
To: alexylem/jarvis 
Cc: jbouziat ; Author 
Subject: Re: [alexylem/jarvis] jabra 410 (#245)

Bizarre.

Je parle d'une maj du firmware du jabra a faire avec le soft jabra : http://www.jabra.fr/supportpages/jabra-speak-410#/#7410-209 et non un update de raspbian...

**Comment by jbouziat** [comment]
J’ai fait une mise a jour du firmware.
J’ai suivi l’issue #85 et cela fonctionne.
Encore merci pour vos infos.

**Comment by taostaos** [comment]
Il faut éviter de répondre au mail envoyé par github pour les issues, et privilégier la discussion directement sur github

**Comment by alexylem** [comment]
J'avoue... je te dis pas le clean-up que je dois faire chaque jour sur les posts...
Depuis Gmail vous avez un bouton pour accéder directement au post, vous ne perdez même pas un clic et vous profitez de l'éditeur / prévisualisation:
![image](https://cloud.githubusercontent.com/assets/11017174/20574935/4a7a94d2-b1b7-11e6-99fc-b96940a6930f.png)
(oui j'ai bcp de notifs...)

**Comment by Jean-Bernard-Hallez** [comment]
Bonjour après avoir recherché aussi j'ai fait ce test:
aplay -Dsysdefault -c 2 -f cd test.wav --> Ca m'a permis de voir en effet que le son sortait à la vitesse normal j'ai donc modifié mon fichier:
sudo pico ~/.asoundrc
pcm.!sysdefault {
type asym
playback.pcm {
type hw
rate 48000
slave.pcm "hw:0,0"
}
capture.pcm {
type plug
slave.pcm "hw:1,0"
}
}

Et ca a marché desuite.... Merci tout le monde.... ;-)
