### ISSUE TITLE
Automatically set mic sensitivity and sox thresholds

### ISSUE THREAD

**Issue by alexylem** [alexylem/jarvis#246]
### Description

Detect ambiant noise and automatically adjust mic sensitivity and sox thresholds during installation and mic settings.
Idea is record two audio samples, 1 during which the user must not speak, and the other one during which he will. Then use sox to analyse audio levels.
This will avoid all the questions/complains about Jarvis not recognizing the user, when it only comes from audio settings.

**Comment by alexylem** [comment]
Starting working on this...

**Comment by alexylem** [comment]
I started to measure silence level
![fevr -19-2017 20-10-34](https://cloud.githubusercontent.com/assets/11017174/23105433/7ea844c6-f6df-11e6-9f95-2af34c0e8815.gif)

After I will check normal "voice" level and advise on mic sensitivity & automatically adjust sox levels.
I think i'm on good track 😄

**Comment by Lusitanos67** [comment]
nothing into menu Settings > Audio, with Audo-adjust levels

**Comment by alexylem** [comment]
Je réouvre afin de collecter vos avis.
Voici un aperçu du wizard complet chez moi:
http://asciinema.org/a/csrfs505z1l8ntbktyuajfuyn

@Lusitanos67 n'oublies pas de mettre à jour.

**Comment by alexylem** [comment]
C'est pas normal que tu ne l'aies pas dans le menu audio... un petit http://asciinema.org avec:
```shell
$> ./jarvis.sh -u
# puis
$> ./jarvis.sh
# Settings > Audio
```
stp?
Regarde chez moi:
http://asciinema.org/a/9tmibap1wnukptnv90hkehw9f

**Comment by Lusitanos67** [comment]
Petite remarque, impossible de sortir de l'assistant auto-adjust une fois rentré dedans.

**Comment by alexylem** [comment]
@Lusitanos67 tu as raison il faut aller jusqu'au bout. Si on ne veut/peut pas régler le gain, oui effectivement on ne peut plus continuer. Je vais rajouter une option "Exit" en cas d'échec.

**Comment by Lusitanos67** [comment]
Le menu apparaît une fois que tu passé l'assistant au moins une fois

**Comment by Lusitanos67** [comment]
A première vue, je suis passé en "parameters" de 1% à 11%, et idem pour le second.
J'ai testé et il coupe les premiers mots et derniers mots. Je refais un test plus tard, mais merci pour ce merveilleux outil ^^

**Comment by alexylem** [comment]
Je viens de rajouter l'option pour sortir au milieu du process.
11% ca me parait bien grand en effet.
La formule actuelle est:
```
silence_level (dans ton cas 5%) * 2 + 1 = 11%
```
Peut-être vaudrait-il mieux qqchose comme:
```
silence_level * 1.5 = 7.5 => 7 (arrondi)
```
Tu peux essayer de changer manuellement à 7 et me dire si c'est mieux pour:
```
min_noise_perc_to_start
min_silence_level_to_stop
```

**Comment by Lusitanos67** [comment]
Les 5% correspondent au gain micro ? Si oui j'ai mis 2 au lieu des paliers par 5 ^^, ca doit venir de là alors

**Comment by alexylem** [comment]
Non c'est le niveau sonore de ton silence :) (tu le vois dans le résumé à la fin du wizard)
Les paliers de 5 sur le gain c'est pour aller plus vite, si t'es allez au bout du process avec un gain de 2 alors pas de soucy.

**Comment by Lusitanos67** [comment]
Ok, je viens de refaire un test, alors la première étape et difficile pour moi car il y a un temps de latence entre le bruit, et le micro qui capte le bruit, ce qui fait que lorsque je fait "ok" au clavier, cela suffit à dépasser les 5% ^^, peut-être mettre un petite tempo de 1 sec ?
Je suis arriver aux même résultats:
results:
-silence:5%
-voice:72%
sox parameters:
-micro: 2 (default 0)
-min noise:11% (default 1%)
-min silence:11% (default 1%)

Bizarre, il me reprend des valeurs par défaut de 1% alors que j'étais déjà à 11% ?
Petite chose, pour quitter l'assistant, tu fais comment car le ctrl+c ne fonctionne pas, et l'échappe me remet au début de l'assistant ?

**Comment by alexylem** [comment]
>lorsque je fait "ok" au clavier, cela suffit à dépasser les 5% ^^, peut-être mettre un petite tempo de 1 sec ?

J'avais la même chose chez moi. Ca ne venait pas du clavier mais de l'activation du micro. J'ignore désormais les premières 0.5 secondes et c'est bon.

> il me reprend des valeurs par défaut de 1% alors que j'étais déjà à 11% ?

Il affiche les valeurs par défaut du système pour information. Comme je vois que ca prête à confusion je ne les affiche plus.

>pour quitter l'assistant, tu fais comment

J'ai rajouter une étape "Quitter" mais juste lorsque le test échoue, au cas ou l'utilisateur ne peut pas s'en sortir ni en parlant plus/moins fort, ni en jouant avec le gain:
![image](https://cloud.githubusercontent.com/assets/11017174/23116226/b5200ed4-f749-11e6-9392-67ef3eb8a7fc.png)

**Comment by Lusitanos67** [comment]
bug découvert: lorsque tu as une valeur négative dans "gain", impossible de modifier cette valeur.

**Comment by alexylem** [comment]
Bien vu, ca marche sur OSX c'est pour ca que je l'ai loupé.
Je corrige.
En attendant:
```shell
$> echo 0 >config/gain
```

**Comment by alexylem** [comment]
Bon on dirait que c'est un bug de `whiptail`, rien trouvé sur le net, ca va être dur à corriger:
```shell
$> man whiptail
--inputbox text height width [init]
              An input box is useful when  you  want  to  ask  questions  that
              require  the  user  to  input a string as the answer. If init is
              supplied it is used to initialize the input string.  When input‐
              ing  the string, the BACKSPACE key can be used to correct typing
              errors. If the input string is longer than the width of the dia‐
              log  box,  the  input field will be scrolled. On exit, the input
              string will be printed on stderr.
$> whiptail --inputbox "test" 20 76 "-5"
-5: unknown option
```
Une solution pourrie serait de rajouter un espace devant...
```
$> whiptail --inputbox "test" 20 76 " -5"
```
![image](https://cloud.githubusercontent.com/assets/11017174/23324002/9b4163dc-faeb-11e6-95f9-825eccd89b99.png)

**Comment by Lusitanos67** [comment]
Ouais moyen... Sauf si tu n'autorises pas les valeurs négatives. Exemple si tu est déjà à gain=0 et que tu dois descendre, tu demandes non pas de partir dans des valeurs négatives, mais plutôt de baisser la sensibilité du micro, ce que je suis obligé de faire, car je viens de me rendre compte qu'il y a constamment un bruit de fond qui est dû à une sensibilité trop élevé !

**Comment by alexylem** [comment]
@Lusitanos67 oui sauf que la sensibilité ne peut pas être gérée dans tous les cas. Pour bcp de micro (dont le mien), cela donne une erreur:
```
cannot load mixer controls: Invalid argument
```
Le gain est le seul moyen universel de gérer la sensibilité (y a-t-il vraiment une différence entre sensibilité et gain sur la qualité sonore? à tester...).
En attendant de trouver mieux j'ai mis l'espace, ca fonctionne...

**Comment by Lusitanos67** [comment]
Oui tu as peut-être raison, ok dans ce cas.
Je continu quand même mes tests avec une sensibilité plus faible, et ensuite forcer l'input avec le gain pour éviter de choper les bruits de fonds (bruit de pompe aquarium, frigo, etc...), ça à l'air de tourner ^^

**Comment by wichtounet** [comment]
Est-ce que c'est normal que ça ne marche pas tout le temps ? 

Dans mon cas, je n'ai trouvé aucune configuration de gain / sensitivité qui m'ont permis d'entrer dans les 5% silence et 50% silence. Soit j'étais très vite dans les 15-20%  pour le silence ou alors dans les 25-30 pour la voix si je réglais plus bas.

**Comment by alexylem** [comment]
@wichtounet Ah bon? même en parlant près du micro?
Après il faut peut-être que je revois les seuils mais ca ne me parait pas énorme 45 points de différence entre le silence et la voix.
