### ISSUE TITLE
Hotword Snowboy trop sensible

### ISSUE THREAD

**Issue by azertigrou** [alexylem/jarvis#249]
Bonjour,

Encore un soucis à régler. Le hotword (mon jarvis s'appelle Lydia) est trop sensible; c'est à dire qu'il suffit que je parle fort pour qu'il se mette à reconnaitre que je veuille lui parler alors que ce n'est pas le cas.

J'ai beau descendre la "snowboy sensivity" , il réagit alors que j'ai dis autre chose que mon hotword. Si je baisse trop , il ne comprend plus le hotword. Je n'arrive pas à trouver le juste milieu.

**Comment by alexylem** [comment]
Witt.ai recommande des hotwords d'au minimum 3 ou 4 syllabes.
Essayes de changer en "Hey Lydia".

👎  Pas conseillé
- Jarvis (2) Bon dans la pratique ca marche quand même pas trop mal 😄 
- Hé (1)
- Al (1)
- Bye (1)

👍  Conseillé
 - Salut Jarvis (4)
 - Hé Jarvis (3)
 - Tu es la? (3)
 - Tu m'écoutes? (3)
 - Allume le bar (4)
 - Au revoir (3)

**Comment by azertigrou** [comment]
J'ai réenregistré le bon lydia en "salut Lydia". Du coup, je ne sais pas pourquoi mais c'est le mot Lydia de mon fichier jarvis-command qui est pris et non plus le hotword. 
Mais ce n'est pas trop grave. Cela a l'air même de mieux fonctionner.

Quant à Jarvis, j'aurais bien aimé l'appeler comme ca; mais il confond pas mal avec Francis ou "la vis". De  plus; Jarvis pour une voix de femme, c'est pas top. C'est comme appeler Sylvester une femme ;)
J'ai vraiment hâte de pouvoir avoir une voix masculine qui me réponde . Ca fait moins misogyne, surtout quand on donne l'ordre de fermer les volets ou d'éteindre les lumières ;)

**Comment by alexylem** [comment]
`LYDIA` ne devrait pas être dans `jarvis-commands`, enfin plus depuis quelques mois...
Peux-tu t'assurer qu'il n'y est pas?

Voici le miens:
```shell
*AIDE*==jv_display_commands
*BONJOUR*|*SALUT*==say "Bonjour $username"
*COMMENT*APPELLE*==say "Je m'appelle $trigger"
*MERCI*==say "De rien"
*AU REVOIR*|*BYE*==say "Au revoir $username"; jv_exit
ANNULE*|TERMINE*==bypass=false; say "Ok"
ENCORE*==jv_repeat_last_command
*TEST*==say "Ca fonctionne!"
*VERSION*==say "Je suis en version $jv_version"
*REPETE (*) ET (*)==say "(1) (2)"
*CA VA*==say "Très bien et toi ça va?"
>*OUI*==say "ravi de l'entendre"
>*NON*==say "j'en suis navré"
```

Vérifies bien aussi que ton hotword est bien à jour dans `Settings > General > Magic word`

**Comment by azertigrou** [comment]
En fait, il n'y étais plus. C'est moi qui l'ai ajouté pour pouvoir mettre des commandes en plus dès qu'il entend précisément le hotword.
Comme parfois le système répond à son nom alors que je ne lui ai rien dit, j'ai dis de couper le son après chaque commande et de le remettre UP lorsque je dis LYDIA (puisque le hotword ne fonctionne pas bien chez moi).
Je sais, c'est de la bidouille....

**Comment by alexylem** [comment]
Pour faire ca je te conseille plutôt d'utiliser les `hooks` c'est fait pour ca.
`Settings > Hooks > Entering command mode`

**Entering command mode**
```
echo "J'ai entendu mon nom"
execute some more commands...
```

**Comment by azertigrou** [comment]
Apparement, ca ne change rien non plus. Tant pis, je ne comprends toujours pourquoi elle réagit à d'autres mots que le sien. Du coup, j'ai suivi ton conseil et j'ai enlevé son nom du fichier de commande et j'éteinds les hauts parleurs pour pas me faire polluer par son "oui, j'écoute" qui arrive alors que je ne l'appelle pas. Pourtant le hotword est "salut Lydia" et elle réagit quand je dis "c'est ici"...Allez comprendre.

Je pense que je n'arriverai pas à laisser le système UP comme je l'espérais. Je vais surement mettre un bouton et attendre que le STT fasse des progrès.

**Comment by alexylem** [comment]
C'est pas normal, chez moi je n'ai presque aucun problème de faux positif... à croire que Jarvis est éteins...
Tu peux essayer de trainer ton hotword depuis le site de witt.ai et voir comment il réagit lorsque tu le teste en ligne? Ca se trouve ca vient de la qualité de ton micro...
