### ISSUE TITLE
STT à distance avec  Kaldi

### ISSUE THREAD

**Issue by physicien** [alexylem/jarvis#25]
Surprise surprise, après une bonne grosse journée de travail j'ai réussi (à une petite erreur de _path_ près) à configurer Kaldi en ASR qui accepte de recevoir des fichiers en `.wav` pour les décoder.

Pour ce qui est de l'installation, très facile si on suit les [instructions](http://kaldi-asr.org/doc/install.html).
Pour ce qui est du online decoding, il y a un exemple fonctionnel [ici](http://www.danielpovey.com/kaldi-docs/online_decoding.html#online_decoding_nnet2_example) (à retravailler et adapter à un meilleur model)
ATTENTION: utilisateurs avancés seulement (et avec pas mal de CPU/GPU)
Pour ce qui est de la génération ou l'amélioration d'un décodeur, voici une excellent petit guide. Ça permet également de comprendre comment utiliser le modèle anglo `librispeech`. [kaldi_for_dummies.pdf](https://github.com/alexylem/jarvis/files/334049/kaldi_for_dummies.pdf)

Je compte également m'inspirer de ce petit guide et de l'article suivant afin de générer un décodeur francophone, à suivre...
[2015_icassp_librispeech.pdf](https://github.com/alexylem/jarvis/files/334059/2015_icassp_librispeech.pdf)

**Comment by physicien** [comment]
Je ne vois pas où mettre ça autrement qu'ici, mais voici une page de référence avec des tas d'outils: http://www.mi.parisdescartes.fr/~janiszek/recherche/rap/liens

**Comment by physicien** [comment]
Thèse possiblement utile à ajouter à la documentation
[thesis_oplatek.pdf](https://github.com/alexylem/jarvis/files/340042/thesis_oplatek.pdf)

**Comment by physicien** [comment]
J'ai finalement réussi à donner un `.wav` à Kaldi pour qu'il puisse transcrire l'audio en texte. Je me lance maintenant dans la compréhension du français et l'entraînement du réseau neuronal.

**Comment by alexylem** [comment]
Sera implémenté avec #9
