### ISSUE TITLE
Andoer Omni-Directional Stereo USB Microphone

### ISSUE THREAD

**Issue by sinedied** [alexylem/jarvis#250]
Désolé je n'ai pas trouvé de lien autre pour partager ma trouvaille, j'ai acheté ce micro sur amazon: https://www.amazon.fr/gp/product/B01LCIGY8U/ref=oh_aui_detailpage_o01_s00?ie=UTF8&psc=1 pour moins de 8e, et il marche du tonnerre pour jarvis: detection sans soucis a plus de 5m, et omnidirectionnel.

Je savais pas trop a quoi m'attendre, et pour le coup je pense que ca vaut la peine de partager :)

**Comment by alexylem** [comment]
Merci je partage sur le site!

**Comment by alexylem** [comment]
http://domotiquefacile.fr/jarvis/content/prerequisites
![image](https://cloud.githubusercontent.com/assets/11017174/20465461/fc30a0ce-af5d-11e6-865d-b0d1ec60055a.png)

**Comment by algeroth-jeedom** [comment]
@sinedied quel réglage as tu mis de sensibilité ? (de 0 à 100) ?
Et des autres réglages?
merci

**Comment by alexylem** [comment]
Pour les réglages, merci de partager ici: #226

**Comment by maisongauthierbesnard** [comment]
Bonjour,
J'ai un petit peu de temps libre et j'ai voulu me remettre à Jarvis sur mon MacOS Yosemite.

J'ai reçu ce micro cette semaine et j'ai en mode troubleshooting de très gros grésillement. Est-ce de mon côté ou quelque chose que vous avez eu aussi avec ce micro?

**Comment by sinedied** [comment]
Pas de grésillements chez moi, mais je l'ai utilisé uniquement avec un Pi. Par contre en général, l'apparition de grésillements ou de sifflements sur les micro ou enceintes USB sont liés à un problème de masse au niveau de la prise ou de l'alimentation.

**Comment by maisongauthierbesnard** [comment]
Sur un MacMini cela va être gênant...

Je vais tester sur un autre appareil.

Merci

**Comment by tigre-bleu** [comment]
Je viens de le recevoir, mais le connecteur est une sorte de mini usb qui n'en est pas un (j'ai un adaptateur mini usb femelle vers usb mâle et ça ne rentre pas).
Comment avez-vous fait? acheté un adaptateur particulier?

**Comment by sinedied** [comment]
@tigre-bleu tu es sur que tu as commandé le bon? Car sur le Andoer tu as directement une prise USB classique, et pas de connecteur intermédiaire.

**Comment by tigre-bleu** [comment]
Mmm, en effet je me suis fait avoir en commandant une version avec prise mini usb pour gopro.

https://www.amazon.fr/gp/product/B01LCIHCSG/ref=oh_aui_detailpage_o00_s00?ie=UTF8&psc=1

Ca m'apprendra à commander trop vite! heureusement que ça ne coute pas cher :)

**Comment by Lusitanos67** [comment]
Bonjour,

Est-il possible de partager vos configurations micros sur #226

**Comment by AntoineLyon** [comment]
Salut, j'ai acheté un Andoer Omni-Directional suite aux prérequis mais la configuration semble bloquer pour le micro, j'ai un raspberry 3b, faut il faire un autre setup avant ?

**Comment by tardistef** [comment]
Bonjour, j'ai acheter un micro andoer, mais lors de l'installation je n'entend pas le retour de l'enregistrement.

**Comment by vadumont** [comment]
Hello la commu OpenJarvis ! J'ai moi aussi acheté ce micro sur Amazon ! Et il fonctionne très bien sur Windows ! Par contre une fois connecté à ma Raspberry Pi voici les erreurs que j'obtiens au moment du choix du device input à l'install d'OpenJarvis ! Un petit coup de main ne serait pas de refus !

Merci par avance !

![pb_andoer](https://user-images.githubusercontent.com/26243880/45356666-2d1ea280-b5c4-11e8-8b74-f9af3217640f.PNG)

**Comment by juanpa669** [comment]
> Hello la commu OpenJarvis ! J'ai moi aussi acheté ce micro sur Amazon ! Et il fonctionne très bien sur Windows ! Par contre une fois connecté à ma Raspberry Pi voici les erreurs que j'obtiens au moment du choix du device input à l'install d'OpenJarvis ! 


Salut !

Est-ce que tu as trouvé une solution depuis ? je galère à installer jarvis, je bloque aussi micro également.
