### ISSUE TITLE
Please, commit your changes or stash them before you can merge.

### ISSUE THREAD

**Issue by teubize** [alexylem/jarvis#251]
Bonsoir,

je n'arrive plus a mettre a jours le programme. quand je lance la commande ./jarvis -u

voici le résultat :

Checking updates for jarvis...New version available
Recent changes:
- fixed #248 added scrollbar for long menus (plugins) (il y a 5 heures)
- improved install script (il y a 6 heures)
- bug fix on installation script (il y a 7 heures)
- automatically install missing dependencies (il y a 7 heures)
- bug fix (il y a 10 heures)
Updating jarvis...Depuis https://github.com/alexylem/jarvis
 * branch            master     -> FETCH_HEAD
error: Your local changes to the following files would be overwritten by merge:
 ISSUE_TEMPLATE
 jarvis-commands-default
 jarvis.sh
 restapi_server.py
 restapi_settings
 utils/utils.sh
 version.txt
Please, commit your changes or stash them before you can merge.
Aborting
Done
Checking updates for jarvis-home-control...Up-to-date
Checking updates for jarvis-kodi...Up-to-date

je ne sais pas trop quoi faire. j'ai vu que la fonction jv_check_updates utilisé, se trouve dans /utils/utils.sh.
j'ai tenté de la modifier, mais je ne mit connait pas assez.

si vous avez une info, je suis preneur.

**Comment by alexylem** [comment]
C'est parce que tes fichiers de Jarvis ont été modifiés localement (éditeur de texte qui rajoute/enlève des espaces?).
Il te suffit de lancer cette commande dans le dossier Jarvis:
```shell
$> git reset --hard
```
Puis relance la mise à jour de Jarvis:
```shell
$> ./jarvis.sh -u
```

**Comment by teubize** [comment]
j'ai encore un petit souci,avec la commande git, il me remet le fichier jarvis.sh par défaut. mais je suis obligé de le modifier pour le lancer sans le contrôle du compte root pour l'utiliser sous le compte pi.
Du coup j'ai toujours le même.

 Updating jarvis...error: Your local changes to the following files would be overwritten by merge:
        jarvis.sh
Please, commit your changes or stash them before you can merge.

**Comment by alexylem** [comment]
Pourquoi le lancer avec `sudo`? Tu peux m'expliquer afin qu'on trouve une solution appropriée?

**Comment by teubize** [comment]
Merci d'être aussi réactif dans les réponses.

Donc je me connecte en ssh, avec mon compte utilisateur PI.
je fais un sudo su et je lance Jarvis avec ./javis.sh.

Vu que dans le fichier jarvis .sh, il y a un contrôle du login root, du coup je mets en commentaire cette partie pour pouvoir exécuter le script.

**Comment by devauxa** [comment]
Pourquoi faire un sudo su ? Tu utilises quoi qui nécessite les droits root ? Tu peux tout faire sans en principe.

**Comment by alexylem** [comment]
Oui tu devrais pouvoir utiliser Jarvis sans root. J'ai justement rajouté le check sudo pour des raisons de sécurité avant tout (je vérifie tout les scripts des plugins publiés, mais on ne sait jamais...).
Si tu as installé Jarvis avec `sudo`, les fichiers générés ne t'appartiennent pas, il faut donc te réaproprier récursivement le dossier de Jarvis:
```shell
$> sudo chown -R pi jarvis
```

**Comment by teubize** [comment]
Merci ça fonctionne.
