### ISSUE TITLE
Plugin informations (cumul de commandes d'informations) par utilisateur

### ISSUE THREAD

**Issue by Gilles76** [alexylem/jarvis#252]
### Description

Plugin permettant de cumuler une suite de commandes basées sur une configuration par personne.

idée:

```
Jarvis: Oui ?
moi: Quel sont les nouvelles pour "user" ?

Jarvis: Nous sommes le ..... et la saint ...... , la météo est : .......

```

```
profil de user:

{"commande1": ephémérides, "commande2": meteo, ....}
```

**Comment by alexylem** [comment]
On peut déjà le faire (à tester):
```shell
*NOUVELLES*==handle_order "quel jour" && handle_order "ephemeride" && handle_order "meteo"
```

**Comment by Gilles76** [comment]
Ha ben oui !

Manque plus que trouver une commande élégante avec le user.

**Comment by alexylem** [comment]
Je pense plus tard renommer cette fonction `handle_order` en `jv_handle_order` et la documenter pour la rendre publique. Mais bous pouvez déjà l'utiliser telle quel.
Pour le user, je vous conseille d'upvoter #190 ca me semble lié.

**Comment by Gilles76** [comment]
OK c'est fonctionnel et vu pour #190 .

**Comment by alexylem** [comment]
`handle_order` sera renommé en `jv_handle_order` dans la prochaine version

**Comment by Jean-Bernard-Hallez** [comment]
Ouai j'adore !!!
