### ISSUE TITLE
créer une image de jarvis sous docker

### ISSUE THREAD

**Issue by ghost** [alexylem/jarvis#253]
### Description

Tout est dans le titre, je ne connais pas docker. Je suis actuellement en train de voir comment cela fonctionne.

Cela me parait pas mal pour un environnement de dev et ne pas pourrir sa prod.

et pourquoi pas une distribution puisque que docker est installable sur rpi.

Quelq'un s'y connais ?

**Comment by Gilles76** [comment]
Pour installer docker sur un rpi:
`curl -sSL https://get.docker.com | sh`

un container qui permet le controle: "portainer.io"

l'installer et le faire tourner sur un port 9000:

docker run -d -p 9000:9000 -v /var/run/docker.sock:/var/run/docker.sock --name portainer portainer/portainer:arm

**Comment by alexylem** [comment]
Voir #186 il semblerait que @taostaos utilise Jarvis sous docker...

**Comment by Gilles76** [comment]
Ok vu, je le contacterai sûrement.
Tu en penses quoi d'une image docker. Cela fait un bon moment que je voulais utiliser docker. Je trouve ça pas mal.
Cela peut faciliter le dev des plugins avec git, et offrir à d'autre un moyen de tester Jarvis.

**Comment by taostaos** [comment]
En effet, mais je n'ai toujours pas pris le temps de faire une image propre, vu que je suis parti d'une image debian et que j'ai fait l'install à la main, je pense que j'ai noté dans un coin toutes les commandes que j'avais tapé. 

Perso, je pense que l'image est le plus simple: pas de problèmes de compatibilité...

**Comment by Gilles76** [comment]
De mon coté, je suis parti d'une image raspbian (hyper light) en rapport au raspberry. J'ai ajouté ce qu'il faut mais manque quelques briques.

**Comment by taostaos** [comment]
Pas sûr que ce soit plus light, de plus j'avais regardé rapidement et je n'avais pas trouvé d'images étant encore maintenue.  

Et si tu veux vraiment faire light, il faut partir sur l'image alpine.

**Comment by wikijm** [comment]
Pas d'activité sur cette issue depuis le 22 Novembre 2016.
Si quelqu'un souhaite ré-attaquer le sujet, qu'il n'hésite pas à le ré-ouvrir 😉
