### ISSUE TITLE
Comment in commands?

### ISSUE THREAD

**Issue by sinedied** [alexylem/jarvis#254]
Maybe I missed something, but how should I comment a line in the commands file?

**Comment by alexylem** [comment]
For now you can't...
Would you like it to be possible?

**Comment by sinedied** [comment]
It would be nice, at least to perform quick tests by enabling/disabling commands easily

**Comment by alexylem** [comment]
I plan to implement it the `bash` way:
```shell
*BONJOUR*|*SALUT*==say "Bonjour $username"
*AU REVOIR*|*BYE*==say "Au revoir $username"; jv_exit
#*TEST*==say "Ca fonctionne!"
*VERSION*==say "Je suis en version $jv_version"
#*REPETE (*) ET (*)==say "(1) (2)"
#*SENS*VIE*==say "43"
```
