### ISSUE TITLE
Configurable number of snowboy training samples

### ISSUE THREAD

**Issue by sinedied** [alexylem/jarvis#255]
It would be nice to have an option for extensive training of snowboy: 3 samples leads to many false positive in my case, so making the number of training passes configurable would be able to resolve this.

I know than I could do it online and import the model, but the micro and conditions would not be the same, it would be best and easier to be performed directly. Maybe before the training phase, prompt for the number of sample, with the same default value (3)?

**Comment by taostaos** [comment]
Currently snowboy let you only use 3 samples to create a model, wether you do it with the api or the website. 

@alexylem Maybe can you see with them if it's possible to create a universal model for jarvis? I thought about getting the audio sample saying "jarvis" when it's a legit call -> there is a command after, and audio sample that should be rejected when there is no command after.  Then if all the user give you there audio files, that should be enough samples to train the Umodel. I know that they created one for "Alexa", I've tested it but it looks like I need to use an english accent to trigger.

**Comment by alexylem** [comment]
`jarvis` already has 145 samples, it needs to reach 500 to because a universal model.
https://snowboy.kitt.ai/dashboard
![image](https://cloud.githubusercontent.com/assets/11017174/20532449/5621c4aa-b0da-11e6-8006-b3f4d5845641.png)

However, they have an `improve` method, which could allow to improve an existing hotword with more samples... that could be an option, to be tested:
http://docs.kitt.ai/snowboy/#api-v1-improve

It has a `detection_score` which would allow to train on true positive but also false positive recognitions...
>The /api/v1/improve service can be used to collect voice samples for opportunities that in the future we can improve the model. This is especially useful when you get false alarms for a model and we can later add these false alarms to negative set of training data.
>Float, decoding score on this voice sample. Helps to roughly identify true positives, false positives and false negatives

**Comment by taostaos** [comment]
I think french ppl are using the word "jarviss" =)

> that in the future 

It looks like improve isn't available currently (I also saw that on their forum).

**Comment by alexylem** [comment]
>I think french ppl are using the word "jarviss" =)

:scream::scream::scream:

**Comment by wikijm** [comment]
@taostaos and @alexylem answered right.
There's no possibilty to extend personnaly training of snowboy to more than 3 samples. Sorry for this answer.
