### ISSUE TITLE
[Concept idea] - Make Jarvis compatible with "all microphones" -> Add a folder monitoring?

### ISSUE THREAD

**Issue by LengZai** [alexylem/jarvis#256]
Hi @alexylem 

Here the idea...
Use any connected device who will generate a wav file (in the correct format) and put it in that folder... Jarvis will monitor this folder to detect any new wav files
As soon he detects a wav files, it will send to Bing/Google/etc... (Maybe there will be an issue with snowboy hot word then)

Otherwise, alternative solution, put on that folder a text file with the recognized text.. So the connected device (smartphone, or any computer with a mic), will contact the voice recognition system to get the generated text and send it to Jarvis folder monitored

I don't know if it's worth it as it might increase delay to execute command but Jarvis will be multi-system then without impact Jarvis dependencies with frameworks/modules/libraries, etc.

**Comment by alexylem** [comment]
You can already use Jarvis from text using `-x` flag or even the `jarvis-api` plugin.
For the wav files sounds interesting but it would be much preferable to plug directly the microphone into jarvis for many reasons (performance, usability, snowboy...)
Do you have a concrete example of why a mic wouldn't work with Jarvis but still able to generate proper wave files?

**Comment by LengZai** [comment]
Well, ok i should change my topic then... but i imagine that i can use Jarvis from any devices (Phone, Windows, Linux, MacOS, smartwatch) which can send a wav,text file to Jarvis.

**Comment by alexylem** [comment]
Please also see #225 where i'm building a user interface to use Jarvis from any device. It will use embedded microphone and browser speech recognition too...
For the smartwatch, I only see `tasker/autovoice` (some Jarvis users are doing this already)

**Comment by LengZai** [comment]
Ok well noted.. Thanks
Well, except if someone wants to comment about Tasker/Autovoice but I heard that it can consume a lot of battery
