### ISSUE TITLE
Son haché avec SVOX Pico pico2wav

### ISSUE THREAD

**Issue by valentin8709** [alexylem/jarvis#257]
Salut!
Je viens de découvrir Jarvis (vaut mieux tard que jamais) et je trouve ça vraiment super, un énorme bravo! J'ai pu tout installer correctement, c'est simple et intuitif. Cependant, je remarque une différence de qualité non négligeable lors de l'utilisation de pico2wav  (nommé svox_pico dans Jarvis je crois).

Par exemple, lorsque je lance un: ./jarvis.sh -x "météo" la réponse vocal est haché / en canon (genre comme 2 voix en décalages...) enfin c'est plutôt bizarre. Par contre, quand je teste la commande directement: pico2wave -w meteo.wav --lang=fr-FR "Partiellement nuageux. Minimales : 9 degrés." et que je lis le fichier avec: omxplayer -o local meteo.wav tout va bien, le son est très clair.

Aurais-je loupé quelque chose? Est-ce que quelqu'un aurait une idée de où cela pourrait provenir?

Merci pour tout :)

**Comment by alexylem** [comment]
`svox_pico` utilise `pico2wav`, extrait du code:

*tts_engines/svox_pico/main.sh*
```shell
svox_pico_TTS () { # TTS () {} Speaks text $1
    wavfile="$tmp_folder/tts.wav"
    /usr/bin/pico2wave -l ${language//_/-} -w "$wavfile" "$1"
    PLAY "$wavfile"
}
```
Et voici pour `PLAY` qui utilise `play` de `sox`
*jarvis-functions.sh*
```shell
PLAY () { # PLAY () {} Play audio file $1
    [ $platform = "linux" ] && local play_export="AUDIODRIVER=alsa" || local play_export=''
    eval "$play_export play -V1 -q $1"
```
Tu peux tester de ton côté avec ces fonctions?
```shell
$> pico2wav -l fr-FR -w meteo.wav "Partiellement nuageux. Minimales : 9 degrés." && play meteo.wav
```

**Comment by valentin8709** [comment]
Désolé pour le temps de réponse. Je viens de trouver une solution à mon problème, j'ai remplacé la commande montré ci-dessus dans _jarvis-functions.sh_ par celle-ci:

`eval "$play_export aplay $1 >/dev/null 2>&1"
`
Maintenant, tout fonctionne à merveille =D J'ai aussi changé le contenu de "config/phrase-misunderstood" par une traduction en français (c'était pas très joli en anglais ^^). 

Maintenant, il ne me reste plus qu'à développer un petit plugin pour synchroniser les commandes vocales de Yana Server (interface domotique par Idleman) pour pouvoir discuter avec Jarvis et commander directement ma domotique installée via Yana. Il suffit juste de récupérer une liste de commandes via URL et de parser les réponses aux appels pour avoir une réponse Jarvis compréhensible =)

Un énorme merci pour le travail effectué sur ce projet, c'est juste excellent!!!

**Comment by alexylem** [comment]
Ok,
Tu as donc un problème avec `play` de `sox` mais je ne peux pas mettre `aplay` dans le code car sinon cela ne marchera plus pour tous les utilisateurs d'`OSX` (car il n'y a pas cette dépendance)
Le soucis est qu'à la prochaine mise à jour tu risque de perdre ta modification, et ca serait vraiment dommage de ne pas installer les mises à jour...
Il faudrait essayer de résoudre ton problème et rester sur `play`, peut-être faut-il préciser le rate?

Si tu veux proposer un plugin pour Yana, tu peux ouvrir un nouveau ticket, j'y mettrai la catégorie Plugin Request pour que les utilisateurs votent. Tu peux y décrire exactement ce que tu veux, et si tu es volontaire pour le faire, je pourrai d'y aider dans l'approche.
