### ISSUE TITLE
Gestion de plusieurs Jarvis dans jeedom

### ISSUE THREAD

**Issue by Choco7** [alexylem/jarvis#258]
Bonjour, 

Est il possible ou serait t'il possible d'avoir plusieurs Jarvis de connecté à Jeedom ?

Je m'explique j'aimerais obtenir le comportement suivant  : 

Un raspberry dans la cuisine avec Jarvis.
Un raspberry dans le salon avec Jarvis.
Un raspberry  ailleurs dans la maison avec Jeedom.

je suis dans **le salon** : 

moi : Jarvis ? 
Jarvis : oui ?
moi : allume **la lumière** 
<<Jarvis allume la lumiere **du salon**>> 
Jarvis : C'est bon la lumière du salon est allumé.

je suis dans **la cuisine** : 

moi : Jarvis ? 
Jarvis : oui ?
moi : allume **la lumière** 
<<Jarvis allume la lumière de **la cuisine**>> 
Jarvis : C'est bon la lumière de **la cuisine** est allumée.

Donc en passant par un Jeedom sans préciser la lumière à allumer.

Je pense qu'il faudrait que chaque Jarvis possède son propre identifiant et qu'il le transmette à Jeedom  mais je ne sais pas si c'est faisable.

Merci d'avance pour votre retour 

Cordialement Choco7 ;)

**Comment by alexylem** [comment]
Utilises-tu le plugin Jeedom de Jarvis?
https://github.com/alexylem/jarvis-jeedom
Si oui je te suggère de poster ce ticket sur le repot du plugin:
https://github.com/alexylem/jarvis-jeedom/issues/new

Manuellement, sans passer par le plugin, à priori c'est possible car chaque instance de Jarvis aura ses propres commandes:
**Jarvis Salon**
```shell
*ALLUME*LUMIERE*==say "$(curl "http://<IP_JEEDOM>:<PORT_JEEDOM>/core/api/jeeApi.php?apikey=<KEY_JEEDOM>&type=interact" --data-urlencode "query=ALLUME LUMIERE SALON")"
```

**Jarvis Cuisine**
```shell
*ALLUME*LUMIERE*==say "$(curl "http://<IP_JEEDOM>:<PORT_JEEDOM>/core/api/jeeApi.php?apikey=<KEY_JEEDOM>&type=interact" --data-urlencode "query=ALLUME LUMIERE CUISINE")"
```

**Comment by Bostoc** [comment]
Bonjour, Faut-il ajouter manuellement les commandes d'interaction jeedom dans Jarvis ?

**Comment by alexylem** [comment]
@Bostoc non le plugin de Jarvis transfère tous les ordre reçus à Jeedom. Jeedom se charge de les comparer et exécute les interactions correspondantes.

**Comment by wikijm** [comment]
@Choco7 : Est-ce que @alexylem a répondu à ta question ?
Si oui, je t'invite à clôturer le ticket ;-)

**Comment by wikijm** [comment]
Pas de réponse à ma relance, je clôture l'issue. 
Ne pas hésiter à rouvrir en cas d'avancée.
