### ISSUE TITLE
dire a heure créé

### ISSUE THREAD

**Issue by parrain27** [alexylem/jarvis#259]
bonjour je poser la question j'ai essaye de mettre le plugin de jeedom jarvis pour le faire avec un scénario mais pas moyen de faire cohabiter les deux jarvis et plugin jarvis ou suis pas douer ya des chance bref.
je souhaite par exemple faire dur a jarvis il et 8h ' de vous réveiller tous les jour a 8h comment je peut faire et et t'il possible dit inclure des info comme la température ou autre avec ma phrase

**Comment by parrain27** [comment]
problème régler en passant par push bullet d’ailleurs un plugin push bullet a jarvis faciliterez des chose^^

**Comment by alexylem** [comment]
Problème réglé visiblement 😄
