### ISSUE TITLE
Tests Microphones

### ISSUE THREAD

**Issue by NikoS34** [alexylem/jarvis#260]
Bonjour,

j'ai testé Jarvis avec les produits audio suivants 
- BLUE Snowball Ice  (~60E)
http://www.bluemic.com/products/snowball-ice/
pas réussi à le faire reconnaitre par mon Pi3 avec Raspbian full, même en passant par un hub usb alimenté... et aucun souci avec un pc.

MXL AC-404 (~100E)
http://www.mxlmics.com/microphones/web-conferencing/AC-404/
aucun souci sur mon Pi3, capte clairement mes ordres même à plusieurs mètres, c'est celui que j'utilise actuellement au quotidien avec Jarvis.

SAMSON UB1 (~100E)
http://www.samsontech.com/samson/products/microphones/usb-microphones/ub1/
aucun souci sur mon Pi3, capte aussi clairement les ordres  à plusieurs mètres, mais me semble un peu moins "sensible" que le MXL AC-404, avec les mêmes réglages par défaut dans Jarvis.

Par contre mon problème actuel c'est de pouvoir utiliser Jarvis dans un environnement "non-calme", j'utilise ce système en effet pour piloter entre autre mon système audio SONOS, et là ça se complique...
Pour démarrer le système audio ça roule mais pour l’arrêter faut crier et s’approcher du micro !!!
Et pour demander autre chose à Jarvis avec de la musique en cours (chansons/radio) même en jouant sur les settings audio on obtient souvent les fameux ####...
D’après les discussions en cours, le salut serait du côté des micros de type array comme ici 
https://www.kickstarter.com/projects/seeed/respeaker-an-open-modular-voice-interface-to-hack/posts/1679978

Je vais donc aussi m'orienter vers ce type de micro.

@+,
NikoS

**Comment by alexylem** [comment]
Merci pour le partage d'information @NikoS34

**Comment by alexylem** [comment]
Page des micros supportés mise à jour:
http://domotiquefacile.fr/jarvis/content/prerequisites
![image](https://cloud.githubusercontent.com/assets/11017174/20635933/d8eee1ce-b364-11e6-92ff-27f7c5eadefb.png)

**Comment by QuentinCG** [comment]
Je confirme, le "MXL AC-404" fonctionne plutôt bien à 3-4m / 180°.

**Comment by D-Kalck** [comment]
J'étais parti pour m'acheter le MXL AC-404, mais en voyant le ReSpeaker, ça me fait hésiter, surtout que ce n'est pas un simple micro, du coup, plein de questions se posent concernant son intégration avec Jarvis/Jeedom (pour moi).
