### ISSUE TITLE
Config micro: Permission denied

### ISSUE THREAD

**Issue by kevincaradant** [alexylem/jarvis#261]
Hi @alexylem 

I get this error. Any idea why I don't have access with the current user ? 

![image](https://cloud.githubusercontent.com/assets/6093175/20630984/a1cfab5e-b334-11e6-9efd-2e4f90902233.png)

Thank you = :)

Consequencies: I can't continue the installation because I'm in a loop where it ask me everytime to select the card and device ;)

**Comment by kevincaradant** [comment]
I don't know why but I remove and clone again your repository and it works ;)

**Comment by alexylem** [comment]
Yes most probably cloned wrongly with `sudo` thus Jarvis not able to create `jarvis-record.wav`
