### ISSUE TITLE
User Commands Manager (Sarah - Plugin-Creator like ?)

### ISSUE THREAD

**Issue by LengZai** [alexylem/jarvis#262]
Hi @alexylem,

As you are currently developing the web interface of Jarvis. #225 
I would like to know if you can add an import/export button on User commands web page?
![image](https://cloud.githubusercontent.com/assets/20622767/20636220/40cec1b6-b369-11e6-9537-a207021d819d.png)

And for example to be able to import (wget?) from a Google Drive link.
So we will be able to easily edit commands through a spreadsheet.

This is just an example but it will looks like this with a spreadsheet:
![image](https://cloud.githubusercontent.com/assets/20622767/20636135/9e3636ba-b367-11e6-88bf-8340b7c85f3a.png)

So the aim is to be able to make easier to generate Jarvis' commands like Sarah Plugin-Creator
[https://github.com/Tibus/SARAH-Plugin-pluginCreator](https://github.com/Tibus/SARAH-Plugin-pluginCreator)

At last but not least, to be able to ask Jarvis to update the User Commands with a voice command. 

```
User: Jarvis
Jarvis: Yes?
User: Please update the command list from Google Drive
Jarvis: Done, the command list is now updated
```

So we should have a user setting to save the Google Drive link, so Jarvis will know how to get the last user commands CSV file.

**Comment by alexylem** [comment]
Merci @LengZai pour cette suggestion.
Il faudrait idéalement que cette proposition d'amélioration soit sur le repo du plugin:
https://github.com/alexylem/jarvis-ui/issues/new
Et oui le plugin est dispo en version alpha (voir #225 )

Sinon je pensais justement présenter les commandes sous forme de tableau à 2 colonnes (en utilisant [Datatables Editable](https://editor.datatables.net/examples/inline-editing/simple)):
- Le pattern de l'ordre à matcher
- La commande

Si je comprends bien tu souhaites aller plus loin et pouvoir, comme illustrée dans ton screenshot, découper les phrases dites par morceau afin de faciliter la création de nombreuses commandes ayant des éléments communs?

Un exemple concret serait intéressant sachant que Jarvis propose déjà l'utilisation de "captures" d'information de l'ordre qui peuvent être réutilisés en tant que variable. Ce qui rend facile la création de commandes avec des paramètres dynamique (donc pas besoin de dupliquer une commande pour chaque valeur possible de pourcentage, comme c'est illustré dans ton exemple):
http://domotiquefacile.fr/jarvis/content/commands
>Utiliser (*) pour capturer du texte et le réutiliser avec (1) dans la partie commande
Vous pouvez capturer plusieurs groupes et y faire référence avec (1), (2),(3)...
```shell
AJOUTE (*) A LA LISTE DE COURSE*==./add_to_list "(1)" && say "Ok"
```

**Comment by alexylem** [comment]
@LengZai could you please get back to me on the concrete example? (please see my advise to use captures instead). If this is no longer needed, let's close the ticket.

**Comment by wikijm** [comment]
No answer of the issue creator since 25 Nov 2016 => Issue closed.
Don't hesitate to reopen the issue if there is some evolution.
