### ISSUE TITLE
Message d'erreur au lancement de jarvis.sh

### ISSUE THREAD

**Issue by koua29** [alexylem/jarvis#263]
### Description

Bonjour,
j'ai installé jarvis sur un PI 3 avec un kit d'enceinte usb et une webcam logitech qui intègre un micro.
L’installation via GIT, la configuration se sont bien passé ( test audio ok )

Quand je lance jarvis avec Snowboy pour la reconnaissance du mot magique (jarvis) et Bing pour la reconnaissance des commandes, il me retourne toujours la phrase " je ne comprends pas jarvees ( en disant jarvais ) .

J'ai remarqué qu'au lancement de jarvis.sh , j'ai le message d'erreur suivant qui ne l'empêche pas de tourner.

pi@raspberrypi:~/jarvis $ ./jarvis.sh
jarvis-config-default.sh: line 28: unexpected EOF while looking for matching `"'
jarvis-config-default.sh: line 30: syntax error: unexpected end of file

Cette erreur explique t elle mais problème ?
Le micro de ma caméra est peut être pas assez bon ? ( j'ai testé de jouer sur la sensibilité mais ça ne règle pas le problème, je suis à 0.4 ).

Merci d'avance.

arnaud

**Comment by alexylem** [comment]
Peux-tu s'il te plait coller l'ensemble de la console avec Jarvis lancé en mode troubleshooting, merci!
```
$> ./jarvis.sh -nv
```

**Comment by koua29** [comment]
./jarvis.sh -nv
jarvis-config-default.sh: line 28: unexpected EOF while looking for matching `"'
jarvis-config-default.sh: line 30: syntax error: unexpected end of file

------------ Config ------------
jv_version           16.11.23
system               Linux 4.4.34-v7+ armv7l
os                   "Raspbian GNU/Linux 8 (jessie)"
language             fr_FR
play_hw              hw:0,0
rec_hw               hw:1,0
speaker              ALSA
microphone           Logitech, Inc.
trigger_stt          snowboy
command_stt          bing
tts_engine           svox_pico
conversation_mode    true
--------------------------------

DEBUG: program_startup hook
jarvis: Bonjour Monsieur
User defined commands:
*AIDE*                  *BONJOUR*|*SALUT*       *COMMENT*APPELLE*
*MERCI*                 *AU REVOIR*|*BYE*       ANNULE*|TERMINE*
ENCORE*                 *TEST*                  *VERSION*
*REPETE (*) ET (*)      *CA VA*                 >*OUI*
>*NON*
jarvis: Waiting to hear 'jarvis'
arnaud: (listening...)
DEBUG: models=jarvees,jarvis,snowboy,toto
ALSA lib confmisc.c:1286:(snd_func_refer) Unable to find definition 'cards.bcm28                                                                                                                                                             35.pcm.front.0:CARD=0'
ALSA lib conf.c:4259:(_snd_config_evaluate) function snd_func_refer returned err                                                                                                                                                             or: No such file or directory
ALSA lib conf.c:4738:(snd_config_expand) Evaluate error: No such file or directo                                                                                                                                                             ry
ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM front
ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.rear
ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.center_lfe
ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.side
ALSA lib confmisc.c:1286:(snd_func_refer) Unable to find definition 'cards.bcm28                                                                                                                                                             35.pcm.surround51.0:CARD=0'
ALSA lib conf.c:4259:(_snd_config_evaluate) function snd_func_refer returned err                                                                                                                                                             or: No such file or directory
ALSA lib conf.c:4738:(snd_config_expand) Evaluate error: No such file or directo                                                                                                                                                             ry
ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM surround21
ALSA lib confmisc.c:1286:(snd_func_refer) Unable to find definition 'cards.bcm28                                                                                                                                                             35.pcm.surround51.0:CARD=0'
ALSA lib conf.c:4259:(_snd_config_evaluate) function snd_func_refer returned err                                                                                                                                                             or: No such file or directory
ALSA lib conf.c:4738:(snd_config_expand) Evaluate error: No such file or directo                                                                                                                                                             ry
ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM surround21
ALSA lib confmisc.c:1286:(snd_func_refer) Unable to find definition 'cards.bcm28                                                                                                                                                             35.pcm.surround40.0:CARD=0'
ALSA lib conf.c:4259:(_snd_config_evaluate) function snd_func_refer returned err                                                                                                                                                             or: No such file or directory
ALSA lib conf.c:4738:(snd_config_expand) Evaluate error: No such file or directo                                                                                                                                                             ry
ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM surround40
ALSA lib confmisc.c:1286:(snd_func_refer) Unable to find definition 'cards.bcm28                                                                                                                                                             35.pcm.surround51.0:CARD=0'
ALSA lib conf.c:4259:(_snd_config_evaluate) function snd_func_refer returned err                                                                                                                                                             or: No such file or directory
ALSA lib conf.c:4738:(snd_config_expand) Evaluate error: No such file or directo                                                                                                                                                             ry
ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM surround41
ALSA lib confmisc.c:1286:(snd_func_refer) Unable to find definition 'cards.bcm28                                                                                                                                                             35.pcm.surround51.0:CARD=0'
ALSA lib conf.c:4259:(_snd_config_evaluate) function snd_func_refer returned err                                                                                                                                                             or: No such file or directory
ALSA lib conf.c:4738:(snd_config_expand) Evaluate error: No such file or directo                                                                                                                                                             ry
ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM surround50
ALSA lib confmisc.c:1286:(snd_func_refer) Unable to find definition 'cards.bcm28                                                                                                                                                             35.pcm.surround51.0:CARD=0'
ALSA lib conf.c:4259:(_snd_config_evaluate) function snd_func_refer returned err                                                                                                                                                             or: No such file or directory
ALSA lib conf.c:4738:(snd_config_expand) Evaluate error: No such file or directo                                                                                                                                                             ry
ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM surround51
ALSA lib confmisc.c:1286:(snd_func_refer) Unable to find definition 'cards.bcm28                                                                                                                                                             35.pcm.surround71.0:CARD=0'
ALSA lib conf.c:4259:(_snd_config_evaluate) function snd_func_refer returned err                                                                                                                                                             or: No such file or directory
ALSA lib conf.c:4738:(snd_config_expand) Evaluate error: No such file or directo                                                                                                                                                             ry
ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM surround71
ALSA lib confmisc.c:1286:(snd_func_refer) Unable to find definition 'cards.bcm28                                                                                                                                                             35.pcm.iec958.0:CARD=0,AES0=4,AES1=130,AES2=0,AES3=2'
ALSA lib conf.c:4259:(_snd_config_evaluate) function snd_func_refer returned err                                                                                                                                                             or: No such file or directory
ALSA lib conf.c:4738:(snd_config_expand) Evaluate error: No such file or directo                                                                                                                                                             ry
ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM iec958
ALSA lib confmisc.c:1286:(snd_func_refer) Unable to find definition 'cards.bcm28                                                                                                                                                             35.pcm.iec958.0:CARD=0,AES0=4,AES1=130,AES2=0,AES3=2'
ALSA lib conf.c:4259:(_snd_config_evaluate) function snd_func_refer returned err                                                                                                                                                             or: No such file or directory
ALSA lib conf.c:4738:(snd_config_expand) Evaluate error: No such file or directo                                                                                                                                                             ry
ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM spdif
ALSA lib confmisc.c:1286:(snd_func_refer) Unable to find definition 'cards.bcm28                                                                                                                                                             35.pcm.iec958.0:CARD=0,AES0=4,AES1=130,AES2=0,AES3=2'
ALSA lib conf.c:4259:(_snd_config_evaluate) function snd_func_refer returned err                                                                                                                                                             or: No such file or directory
ALSA lib conf.c:4738:(snd_config_expand) Evaluate error: No such file or directo                                                                                                                                                             ry
ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM spdif
ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.hdmi
ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.hdmi
ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.modem
ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.modem
ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.phoneline
ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.phoneline
ALSA lib pulse.c:243:(pulse_connect) PulseAudio: Unable to connect: Connection r                                                                                                                                                             efused

ALSA lib pulse.c:243:(pulse_connect) PulseAudio: Unable to connect: Connection r                                                                                                                                                             efused

Cannot connect to server socket err = No such file or directory
Cannot connect to server request channel
jack server is not running or cannot be started
INFO:snowboy:Silence
INFO:snowboy:Keyword 2 detected at time: 2016-11-26 18:22:37
DEBUG: modelid=1
jarvis
DEBUG: entering_cmd hook
jarvis: OUI?
arnaud: (listening...)
utils/timeout.sh
DEBUG: speech duration was 85 (10 = 1 sec)
DEBUG: too long for a command (max 4 secs), ignoring...
utils/timeout.sh
^CDEBUG: program exit handler
DEBUG: program_exit hook


J'ai refait l'enregistrement du horword snowboy, il reconnait jarvis , mais pas les commandes :(

**Comment by koua29** [comment]
j'ai fais tellement de test dans tous les sens, je crois que je vais repartir sur une base propre.

**Comment by koua29** [comment]
Voila, j'ai refais une installation propre, je n'ai plus le message d'erreur "jarvis-config-default.sh: line 28:".
C'est déjà ça.
Il reconnait le mot jarvis et plus rien, jarvis ou les commandes ne font rien.
y'a pas mal de message d'erreur sur le Lib ALSA , je vais creuser de ce coté là.

pi@raspberrypi:~/jarvis $ ./jarvis.sh -nv

------------ Config ------------
jv_version           16.11.23
system               Linux 4.4.34-v7+ armv7l
os                   "Raspbian GNU/Linux 8 (jessie)"
language             fr_FR
play_hw              hw:0,0
rec_hw               hw:1,0
speaker              ALSA
microphone           Logitech, Inc.
trigger_stt          snowboy
command_stt          bing
tts_engine           svox_pico
conversation_mode    true
--------------------------------

DEBUG: program_startup hook
jarvis: bonjour
User defined commands:
*AIDE*                  *BONJOUR*|*SALUT*       *COMMENT*APPELLE*
*MERCI*                 *AU REVOIR*|*BYE*       ANNULE*|TERMINE*
ENCORE*                 *TEST*                  *VERSION*
*REPETE (*) ET (*)      *CA VA*                 >*OUI*
>*NON*
jarvis: Waiting to hear 'jarvis'
arnaud: (listening...)
DEBUG: models=jarvis,snowboy
ALSA lib confmisc.c:1286:(snd_func_refer) Unable to find definition 'cards.bcm2835.pcm.front.0:CARD=0'
ALSA lib conf.c:4259:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:4738:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM front
ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.rear
ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.center_lfe
ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.side
ALSA lib confmisc.c:1286:(snd_func_refer) Unable to find definition 'cards.bcm2835.pcm.surround51.0:CARD=0'
ALSA lib conf.c:4259:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:4738:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM surround21
ALSA lib confmisc.c:1286:(snd_func_refer) Unable to find definition 'cards.bcm2835.pcm.surround51.0:CARD=0'
ALSA lib conf.c:4259:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:4738:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM surround21
ALSA lib confmisc.c:1286:(snd_func_refer) Unable to find definition 'cards.bcm2835.pcm.surround40.0:CARD=0'
ALSA lib conf.c:4259:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:4738:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM surround40
ALSA lib confmisc.c:1286:(snd_func_refer) Unable to find definition 'cards.bcm2835.pcm.surround51.0:CARD=0'
ALSA lib conf.c:4259:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:4738:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM surround41
ALSA lib confmisc.c:1286:(snd_func_refer) Unable to find definition 'cards.bcm2835.pcm.surround51.0:CARD=0'
ALSA lib conf.c:4259:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:4738:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM surround50
ALSA lib confmisc.c:1286:(snd_func_refer) Unable to find definition 'cards.bcm2835.pcm.surround51.0:CARD=0'
ALSA lib conf.c:4259:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:4738:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM surround51
ALSA lib confmisc.c:1286:(snd_func_refer) Unable to find definition 'cards.bcm2835.pcm.surround71.0:CARD=0'
ALSA lib conf.c:4259:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:4738:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM surround71
ALSA lib confmisc.c:1286:(snd_func_refer) Unable to find definition 'cards.bcm2835.pcm.iec958.0:CARD=0,AES0=4,AES1=130,AES2=0,AES3=2'
ALSA lib conf.c:4259:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:4738:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM iec958
ALSA lib confmisc.c:1286:(snd_func_refer) Unable to find definition 'cards.bcm2835.pcm.iec958.0:CARD=0,AES0=4,AES1=130,AES2=0,AES3=2'
ALSA lib conf.c:4259:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:4738:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM spdif
ALSA lib confmisc.c:1286:(snd_func_refer) Unable to find definition 'cards.bcm2835.pcm.iec958.0:CARD=0,AES0=4,AES1=130,AES2=0,AES3=2'
ALSA lib conf.c:4259:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:4738:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM spdif
ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.hdmi
ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.hdmi
ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.modem
ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.modem
ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.phoneline
ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.phoneline
ALSA lib pulse.c:243:(pulse_connect) PulseAudio: Unable to connect: Connection refused

ALSA lib pulse.c:243:(pulse_connect) PulseAudio: Unable to connect: Connection refused

Cannot connect to server socket err = No such file or directory
Cannot connect to server request channel
jack server is not running or cannot be started
INFO:snowboy:Silence
INFO:snowboy:Keyword 1 detected at time: 2016-11-26 18:40:59
DEBUG: modelid=0
jarvis
DEBUG: entering_cmd hook
jarvis: Oui?
arnaud: (listening...)
utils/timeout.sh
^CDEBUG: program exit handler
DEBUG: program_exit hook

**Comment by koua29** [comment]
j'ai joué avec les paramétrages dans l'audio 
Min noise duration to start (0.1)                     │
                                                                                │                    Min noise perc to start (1%)                          │
                                                                                │                    Min silence duration to stop (0.2)                    │
                                                                                │                    Min silence level to stop (5%)                        │
                                                                                │                    Max noise duration to kill (5) 

et ça marche mieux.
Par contre, j'ai des timeout sur bing, c'est étrange.

DEBUG: speech duration was 02 (10 = 1 sec)
DEBUG: curl https://speech.platform.bing.com/recognize/query?version=3.0&requestid=ac9a8f42-8806-4d4b-98f1-d09282e9201a&appid=D4D52672-91D7-4C74-8AD8-42B1D98141A5&format=json&locale=fr-FR&device.os=linux&scenarios=ulm&instanceid=E043E4FE-51EF-4B74-8133-B728C4FEA8AA&result.profanitymarkup=0
DEBUG: json={"version":"3.0","header":{"status":"error","properties":{"requestid":"74cfd940-88b3-40f7-9db2-577a0e90a509","FALSERECO":"1"}}}
?(listening...)
utils/timeout.sh
DEBUG: speech duration was 00 (10 = 1 sec)
DEBUG: curl https://speech.platform.bing.com/recognize/query?version=3.0&requestid=e7bc2c64-f774-4b7e-87fb-7595151c406e&appid=D4D52672-91D7-4C74-8AD8-42B1D98141A5&format=json&locale=fr-FR&device.os=linux&scenarios=ulm&instanceid=E043E4FE-51EF-4B74-8133-B728C4FEA8AA&result.profanitymarkup=0
DEBUG: json={"version":"3.0","header":{"status":"error","properties":{"requestid":"89001e9e-188c-4b47-b672-c66a5ab365e1","NOSPEECH":"1"}}}
?(listening...)
utils/timeout.sh

une idée ?

**Comment by alexylem** [comment]
Attends laisse moi le temps de répondre 😄

**Comment by alexylem** [comment]
Tu n'as aucun timeout sur Bing, le vrai message d'erreur est dans le `json`:
```json
{"version":"3.0","header":{"status":"error","properties":{"requestid":"89001e9e-188c-4b47-b672-c66a5ab365e1","NOSPEECH":"1"}}}
```
Tout à la fin du as `"NOSPEECH":"1"`
Ce qui veut dire que le son reçu n'est pas de la parole.

Si tu regarde un peu plus haut tu peux lire:
```
DEBUG: speech duration was 02 (10 = 1 sec)
DEBUG: speech duration was 00 (10 = 1 sec)
```
Donc si tu fais le calcul, les sons enregistrés font 0.2 et 0 secondes... donc pas étonnant.
La cause est ton réglage audio sox, remets le par défaut.

Au tout début tu avais:
```
DEBUG: speech duration was 85 (10 = 1 sec)
DEBUG: too long for a command (max 4 secs), ignoring...
```
Essaye de parler moins longtemps, et de bien faire des pauses.

Ce sont des symptômes connus et tu peux en découvrir plus ici:
#33 
#135 
#118 

Conseil: lis bien les messages qui s'affiche en mode troubleshooting (ils sont la pour ca!!), et adapte ton début de parole et les bruits environnants en fonction. Tu y est presque!

**Comment by wikijm** [comment]
Pas de réponse de @koua29 depuis le 26 novembre 2016.
J'en conclus qu'une solution a été trouvée depuis;

Je clôture, mais ne pas hésiter à ré-ouvrir si nécessaire ;-)
