### ISSUE TITLE
Uniquement le mot magique reconnu et speaker

### ISSUE THREAD

**Issue by maisongauthierbesnard** [alexylem/jarvis#264]
Bonjour,

J'ai installé sur Mac OS X Yosemite.

L'installation se déroule bien. Je m'entends très bien (Voice Tracker II)
L'installation du plugin jeedom se déroule bien. 

Quand je démarre jarvis, le mot magique est entendu sans problème, mais le reste non:

> INFO:snowboy:Silence
INFO:snowboy:Keyword 1 detected at time: 2016-11-27 08:29:04
DEBUG: modelid=0
anita
$> say "$(curl "http://$jv_pg_jd_ip:$jv_pg_jd_port/${jv_pg_jd_path}core/api/jeeApi.php?apikey=$jv_pg_jd_apikey&type=interact" --data-urlencode "query=$order")"
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100    50    0    39  100    11     62     17 --:--:-- --:--:-- --:--:--    62
anita: Désolé je ne comprends pas la demande
commande: (listening...)
DEBUG: models=anita,ok anita,snowboy
INFO:snowboy:Silence
INFO:snowboy:Silence
>

Quand je dis quelque chose, je vois INFO:snowboy:Slience s'arrêter mais rien de plus, ça reprend l'écoute.

Et par la suite, seul le mot magique créé une réaction: "Désolé je ne comprends pas"

En revanche, quand je passe les instructions comme ceci:
>./jarvis.sh -vx "allume dans le salon"

Cela fonctionne parfaitement et plus rapide qu'aucun autre système!

Question subsidiaire, sur Mac OS X, comme changer le choix du speaker?
Car quand je vais dans les settings - audio il me dit:
>./jarvis.sh: line 192: aplay: command not found

J'ai un petit speaker usb que j'ailmerai dédié à jarvis et garder le kit 5.1 éteint.

aplay pour mac os x n'existant (peut-être j'ai mal cherché) une alternative ou une combine?

Merci d'avance
Merci pour votre travail
Et bonne journée!

**Comment by alexylem** [comment]
Ah enfin un utilisateur OSX, je crois qu'on est 2 😄 
Pour changer Le choix du speaker via `aplay` est pour les plateformes linux. Pour OSX, tu devrais avoir `default` et il ne faut pas changer ca. A la place il faut aller dans les préférences d'OSX mais le problème si j'ai bien compris est que tu ne veux utiliser ton speaker USB juste pour Jarvis?

Pour le problème de compréhension, d'après la log que tu m'as collé, et que tu as plusieurs `pmdl` Snowboy. Je ne sais pas quel est ton Hotword principal, mais si ce que tu dit n'est pas le hotword et a un `pmdl` correspondant, il va le considérer comme une quick command et l'envoyer à Jeedom car tu as ce plugin installé. Et j'imagine que tu n'as pas d'interaction pour cette quick command.

Donc mon conseil est de virer les `pmdl` en trop et ne garder que ton Hotword.
Plus d'info sur les quick commands ici:
http://domotiquefacile.fr/jarvis/content/snowboy#commandes-rapides

**Comment by maisongauthierbesnard** [comment]
Wahhhhou! Je pourrai presque dire que j'ai un support exclusif Mac OS X Jarvis! Je vais grave me la péter! 
Petite info en passant, jarvis et MacOS Sierra, n'ont pas l'air très ami, mon autre iMac m'a dit pas content quand j'ai voulu l'installer, un problème d'autorisation, mais je verrai plus tard.

Pour mon MacMini, j'ai viré les hotwords inutiles et uniquement garder anita, et malheureusement pas mieux. Même symptômes.

J'ai relu votre message de nombreuses fois pour bien comprendre. Mais cela m'échappe un peu en ce dimanche matin.

Quand j'écris au clavier les commandes fonctionnent parfaitement. Mais en vocal non. 

Je dis Anita. Elle me dit Oui? Après je dis par exemple, allume dans le salon, rien ne se passe, parfois quand je dis quelque chose, voir des noms d'oiseaux pour exprimer ma frustration, elle répond je ne comprends pas la demande (heureusement pour elle qu'elle ne comprend pas...)

Mon dernier log en date:
>------------ Config ------------
jv_version           16.11.23 
system               Darwin 14.5.0 x86_64 
os                   10.10.5 
language             fr_FR 
play_hw              hw:0,0 
rec_hw               hw:0,0 
speaker               
microphone            
trigger_stt          snowboy 
command_stt          snowboy 
tts_engine           osx_say 
conversation_mode    true 
DEBUG: program_startup hook
anita: Bonjour
User defined commands:
*AIDE*			*BONJOUR*|*SALUT*	*COMMENT*APPELLE*
*MERCI*			*AU REVOIR*|*BYE*	ANNULE*|TERMINE*
ENCORE*			*TEST*			*VERSION*
*REPETE (*) ET (*)	*CA VA*			*OUI*
*NON*
Commands from plugin jarvis-jeedom:
>*
anita: Waiting to hear 'anita'
commande: (listening...)
DEBUG: models=anita
INFO:snowboy:Silence
INFO:snowboy:Silence
INFO:snowboy:Silence
INFO:snowboy:Silence

C'est frustrant d'être si près du fonctionnement.
Merci d'avance,

**Comment by alexylem** [comment]
Ok déjà avec un peu plus de log je comprends mieux.
Il me manque la fin, la ou anita est reconnu, ou tu dis une commande et qu'il te dit qu'il ne comprend pas. Tu peux tout me mettre?

Aussi, je vois que tu as:
```
play_hw hw:0,0
rec_hw hw:0,0
```
Et sur OSX ils devraient être à `false`.
Sauf que la c'est trop tard, il n'y a pas de moyen pour le remettre à `false` depuis l'interface, donc il te faut faire (depuis le dossier de jarvis):
```
echo "false" > config/play_hw
echo "false" > config/rec_hw
```

**Comment by alexylem** [comment]
Pour les pb sur Sierra, ce sont des pbs connnus que j'ai aussi eu, il y a une manip mais je ne me rappelle plus. N'hésite pas à ouvrir un ticket avec le message d'erreur.

**Comment by maisongauthierbesnard** [comment]
Plus de log pour plus de plaisir:

Et là je lui ai dit allume dans le salon plusieurs fois

>Mac-Mini:jarvis macmini$ ./jarvis.sh 
>
>------------ Config ------------
>jv_version           16.11.23 
>system               Darwin 14.5.0 x86_64 
>os                   10.10.5 
language             fr_FR 
play_hw              false 
rec_hw               false 
speaker              Default 
microphone           Default 
trigger_stt          snowboy 
command_stt          snowboy 
tts_engine           osx_say 
conversation_mode    true 
>--------------------------------
>
>DEBUG: program_startup hook
anita: Bonjour
User defined commands:
*AIDE*			*BONJOUR*|*SALUT*	*COMMENT*APPELLE*
*MERCI*			*AU REVOIR*|*BYE*	ANNULE*|TERMINE*
ENCORE*			*TEST*			*VERSION*
*REPETE (*) ET (*)	*CA VA*			>*OUI*
>*NON*
Commands from plugin jarvis-jeedom:
>*
anita: Waiting to hear 'anita'
commande: (listening...)
DEBUG: models=anita
INFO:snowboy:Silence
INFO:snowboy:Silence
INFO:snowboy:Silence
INFO:snowboy:Silence
INFO:snowboy:Silence
INFO:snowboy:Silence
INFO:snowboy:Silence
INFO:snowboy:Silence
INFO:snowboy:Silence
INFO:snowboy:Silence
INFO:snowboy:Keyword 1 detected at time: 2016-11-27 10:57:05
DEBUG: modelid=0
anita
DEBUG: entering_cmd hook
anita: Oui?
commande: (listening...)
DEBUG: models=anita
INFO:snowboy:Silence
INFO:snowboy:Silence
INFO:snowboy:Silence
INFO:snowboy:Silence
INFO:snowboy:Silence
INFO:snowboy:Silence
INFO:snowboy:Silence
INFO:snowboy:Silence
INFO:snowboy:Silence
INFO:snowboy:Silence
INFO:snowboy:Silence
INFO:snowboy:Silence
INFO:snowboy:Silence
INFO:snowboy:Silence
INFO:snowboy:Silence
INFO:snowboy:Silence
INFO:snowboy:Silence
INFO:snowboy:Silence
INFO:snowboy:Silence
INFO:snowboy:Silence
INFO:snowboy:Silence
INFO:snowboy:Silence
INFO:snowboy:Silence
INFO:snowboy:Silence
INFO:snowboy:Silence
INFO:snowboy:Silence
INFO:snowboy:Silence
INFO:snowboy:Silence
INFO:snowboy:Silence
INFO:snowboy:Keyword 1 detected at time: 2016-11-27 10:57:12
DEBUG: modelid=0
anita
$> say "$(curl "http://$jv_pg_jd_ip:$jv_pg_jd_port/${jv_pg_jd_path}core/api/jeeApi.php?apikey=$jv_pg_jd_apikey&type=interact" --data-urlencode "query=$order")"
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100    30    0    19  100    11     28     16 --:--:-- --:--:-- --:--:--    28
anita: Je ne comprends pas
commande: (listening...)
DEBUG: models=anita
INFO:snowboy:Silence
INFO:snowboy:Silence
INFO:snowboy:Silence
INFO:snowboy:Silence
INFO:snowboy:Silence
INFO:snowboy:Silence
INFO:snowboy:Silence
INFO:snowboy:Silence
INFO:snowboy:Silence
INFO:snowboy:Silence
INFO:snowboy:Silence
INFO:snowboy:Silence
INFO:snowboy:Silence
INFO:snowboy:Silence
INFO:snowboy:Silence
INFO:snowboy:Silence
INFO:snowboy:Silence
INFO:snowboy:Silence
INFO:snowboy:Silence
INFO:snowboy:Silence
INFO:snowboy:Keyword 1 detected at time: 2016-11-27 10:57:20
DEBUG: modelid=0
anita
$> say "$(curl "http://$jv_pg_jd_ip:$jv_pg_jd_port/${jv_pg_jd_path}core/api/jeeApi.php?apikey=$jv_pg_jd_apikey&type=interact" --data-urlencode "query=$order")"
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100    50    0    39  100    11     57     16 --:--:-- --:--:-- --:--:--    57
anita: Désolé je ne comprends pas la demande
commande: (listening...)
DEBUG: models=anita
INFO:snowboy:Silence
INFO:snowboy:Silence
INFO:snowboy:Silence
INFO:snowboy:Silence
INFO:snowboy:Silence
^CDEBUG: program exit handler
DEBUG: program_exit hook

**Comment by alexylem** [comment]
Aaaaaaaaaahhhhhh!!!!!
Tu as:
```
command_stt          snowboy
```
Donc pas étonnant... si tu veux pouvoir donner des commandes arbitraires, il te faut utiliser `Bing` ou `Wit`. Je te conseille `Bing` pour commencer. Va dans Settings > Voice Recognition > Reco of Commands > Bing. Il te faudra créer et renseigner une clé Bing.

**Comment by maisongauthierbesnard** [comment]
Diantre! Toutes mes excuses pour ne pas avoir saisi la nuance, en relisant et avec votre remarque je pense comprendre. Corrigez-moi donc je me trompe:
Commandes arbitraire: Bing ou Wit
Si je voulais utiliser snowboy, il faudrait que je crée un hotword pour chaque interaction, ce qui serait proche de l'impossible vu le nombre, et le risque de dysfonctionnement. 

Donc je dois vendre mon âme au diable, choisir entre la peste et le choléra. Bing (Microsoft) ou Wit (Facebook). Même si ce n'est que de simple commande pour allumer la lumière par exemple, cela me fait un peu frissonner.

Une raison spécifique pour le choix de Bing par rapport à Wit? Wit c'est créer par un ingénieur français (cocorico?). 

J'attends votre observation pour choisir.

Merci

**Comment by alexylem** [comment]
Heu... toi tu n'as pas vu [ma vidéo sur youtube](https://www.youtube.com/watch?v=27E_BK1rUKI) 😄 

En fait Jarvis est conçu autour du principe qu'il faut utiliser les 2:
* Snowboy pour la reconnaissance du hotword (offline)
* Bing/Wit pour la reconnaissance des commandes

Ainsi tout ce qui est dit chez toi, télévision, etc... ne part pas sur internet 😉 
Plus d'info ici:
http://domotiquefacile.fr/jarvis/content/stt

Pour Bing et pas Wit... aucune raison en fait, si Wit fonctionne bien pour toi, go for it!

**Comment by maisongauthierbesnard** [comment]
Si justement j'avais vu la vidéo justement, c'est ce qui m'a donné envie il y a longtemps de cela.
C'est pour cela que j'ai écris que ce ne sont que les commandes qui sont envoyées et par conséquent le reste non. Mais j'ai mal exprimé à l'écrit ma pensée, mais là j'avais saisi!

Merci beaucoup, ça fonctionne enfin, j'ai eu du mal à allumer la lumière, mais c'est les réglages du micro maintenant.

Pour le speaker dédié pas d'idée ou une piste que je pourrais creuser?

Merci

**Comment by alexylem** [comment]
>Pour le speaker dédié pas d'idée ou une piste que je pourrais creuser?

Sur Linux c'est déjà prévu. Sur OSX je n'en ai jusqu'ici jamais eu le besoin. On peut garder ce ticket pour ca.
Juste pour vérifier avant que je me casse les dents dessus, tu utiliseras OSX à long terme pour Jarvis ou c'est juste pour tester avant de l'installer sur un raspberry pi (ou autre) ?

Merci.

**Comment by maisongauthierbesnard** [comment]
Ok avec Bing, ça ne fonctionne moyen, wit ca va mieux, mais j'ai l'impression que mon VoiceTracker II a une drôle de manière de fonctionner. Par exemple j'ai une interaction simple, éteint la lumière, très difficile de se faire comprendre, c'est surtout la fin de la commande qui est prise en compte, le premier mot à du mal à passer. "Fait chauffer l'eau" c'est impossible carrément. J'ai fait des modification dans le noise detection à 0,02 pour améliorer. Je pense que c'est le la matériel (Mais bord** un micro à 400€ ça devrait fonctionner jusqu'au bout de ma rue!)

Sinon pour ta question sur OSX, je suis plus qu'à long terme avec MacOS. C'est à la fois un ordinateur de travail, un ordinateur portable et aussi l'ordinateur pour le multimédia dans le côté privé. Et je serai ravi d'avoir Jarvis partout.

Si je trouve quelque chose pour le choix du speaker je reposterai.

Bon app' et merci!

**Comment by alexylem** [comment]
C'est normal que le premier mot se coupe sur les réglages d'origine, d'ou la nécessité de prendre l'habitude d'insister sur le premier mot ou d'en rajouter un autre.
Tu peux jour avec les réglages de `sox` dans Settings > Audio, notamment:
```
min_noise_duration_to_start
min_noise_perc_to_start
```
En mode troubleshooting Jarvis te répète ce qu'il a entendu avant de l'envoyer à Wit, ce qui peut s'avérer pratique pour ces réglages.

**Comment by wikijm** [comment]
Pas d'avancée depuis le 27 novembre 2016.
Je clôture histoire de faire un peu de ménage dans les tickets.

N'hésitez pas à ré-ouvrir si vous relancez la conversation ;-)
