### ISSUE TITLE
exemple de commande

### ISSUE THREAD

**Issue by koua29** [alexylem/jarvis#265]
Bonjour,

auriez-vous des exemples de commande  ?
Pour ma part, je viens de faire la première :)

*TEMPERATURE*==say "Le site de météo france indique quil fait $(curl -k --silent "http://wxdata.weather.com/wxdata/weather/local/FRXX2284?cc=*&unit=m"|grep -oPm1 "(?<=<tmp>)[^<]")  degrés celcius"

A vous d'adapter le bon code d'appel à l'API weather car la c'est la température en ile de france (95)

**Comment by alexylem** [comment]
Tu peux voir faire un tour du côté des plugins et accéder à leur code (lien repo) pour voir comment ils sont fait:
http://domotiquefacile.fr/jarvis/plugins
Il y a d'ailleurs un plugin météo qui existe déjà:
http://domotiquefacile.fr/jarvis/plugins/weather-wunderground
Plus d'info sur comment faire commandes ici:
http://domotiquefacile.fr/jarvis/content/commands
