### ISSUE TITLE
phrase a heure fixe

### ISSUE THREAD

**Issue by parrain27** [alexylem/jarvis#266]
bonjour a tous voila j'ai beaucoup de commande qui passe par jeedom et push bullet 

met je voudrais en passer quelle que une avec jarvis .

voila je voudrais pouvoir lui faire dire une phrase a heure fixe n’étant pas douer j'ai vu que l'ont pouvais si je me trompe pas avec se qui et d’écrit ici http://domotiquefacile.fr/jarvis/content/events

mais je n'y comprend rien du tous mdrr une âme charitable pourrais m'aider :)

**Comment by llaull** [comment]
salut @parrain27 ,

en ssh tu tappes;
crontab -e

puis dans la fenêtre ouverte tu écris :
0       *    *       *       *       ~/jarvis/jarvis.sh -x "phrase à répéter"

**Comment by alexylem** [comment]
@llaull `-x` est pour exécuter un ordre (et donc la commande correspondante à cet ordre).
@parrain27 si tu veux faire dire quelque chose à heure fixe, c'est effectivement dans les events.
Lance Jarvis et dans le menu sélectionne `Events`
Il va d'ouvrir un fichier à modifier, rajoute à la fin:
```
0 * * * * ~/jarvis/jarvis.sh -s "phrase à prononcer toute les heures"
```
Plus d'info sur le paramétrage du temps dans le fichier lui même:
```shell
#                                                 LEGEND
#    ____________________________________________ Minutes (0-59)
#   |        ____________________________________ Hours (0-23)
#   |       |        ____________________________ Days of Month (1-31)
#   |       |       |        ____________________ Months (1-12)
#   |       |       |       |        ____________ Days of Week (0-6, 0 is Sun)
#   |       |       |       |       |         ___ Command to execute
#___|_______|_______|_______|_______|________|_________________________________
#                            Examples
#---|-------|-------|-------|-------|--------|---------------------------------
#   0       0       1,15    *       *       echo "On 1st and 15th of every month at 0am"
#   30      6       *       *       1-5     echo "Every weekday at 6h30"
#   */10    *       *       *       *       echo "Every 10 mins"
#   0       8       30      7       *       echo "On July 30th at 8h"
#   @reboot                                 echo "At system startup"
```

**Comment by parrain27** [comment]
donc si je veut lui faire dire tous les jour a 20h ca donne ca

0 20 1 * * ~/jarvis/jarvis.sh -s "c'est l'heure des poubelles"

**Comment by alexylem** [comment]
Non ca ca sera tous les 1er jour du mois à 20h.
Pour tous les jours à 20h:
`0 20 * * * ~/jarvis/jarvis.sh -s "c'est l'heure des poubelles"`

**Comment by parrain27** [comment]
merci alex :)
