### ISSUE TITLE
ALSA lib pcm

### ISSUE THREAD

**Issue by physicien** [alexylem/jarvis#27]
Je ne sais pas ce qui se passe, mais depuis les 2 dernières updates j'ai ce problème avec le micro. J'arrive à configurer le micro comme avant et tout fonctionne jusqu'à temps que je lance Jarvis.
![capture d ecran - 2016-06-29 - 16 04 53](https://cloud.githubusercontent.com/assets/19982063/16467031/68733394-3e13-11e6-8a57-36339f1511fb.png)

**Comment by alexylem** [comment]
Ceci n'est pas une erreur, c'est juste le mode troubleshooting qui te montre les détails de ce qui se passe. Lance le en mode normal, et dit "SNOWBOY" la reconnaissance devrait fonctionner.
