### ISSUE TITLE
Etablir une priorité de fonctionnement du TTS

### ISSUE THREAD

**Issue by ghost** [alexylem/jarvis#270]
### Description

Tout d'abord super boulot pour voxygen, ça asseoit de suite.

Vu que voxygen est un système "online", et dans le but de toujours avoir une réponse vocale fonctionnelle, pourront-on envisager de définir:

 un premier TTS (online) et un second "offline" comme svox. Si pas d'accès web alors passage à svox.

Tu en penses quoi ?

**Comment by alexylem** [comment]
Pas bête. Mais as-tu as réel besoin aujourd'hui (ca t'es arrivé de te retrouver dans cette situation) ou c'est plus une idée potentielle à discuter?

**Comment by Gilles76** [comment]
Clairement non, j'aime bien évaluer tout les scenarios possible. C'est juste une faiblesse à tenir en compte.
De même pour le "STT" mais la c'est plus dur car il faut maitriser pocket-sphinx, mais c'est une autre histoire.

Pour résumer, à mettre de coté ou à cloturer si tu le souhaites, c'est juste un idée non prioritaire.

**Comment by alexylem** [comment]
Ok 😄

**Comment by wikijm** [comment]
@ghost Très bonne idée, ça permet de se faire de l'embarqué ou de prévoir les problèmes d'accès à Internet.
@alexylem Je viens de rajouter cette idée ici : https://github.com/alexylem/jarvis/projects/3

Je clôture, mais ne pas hésiter à ré-ouvrir pour continuer à en discuter ;-)
