### ISSUE TITLE
[Plugin] Synchronisation des commandes vocales avec Yana Server

### ISSUE THREAD

**Issue by valentin8709** [alexylem/jarvis#271]
## Description

Bonjour à tous, ce plugin est à destination des utilisateurs de Yana Server (coeur domotique par Idleman). L'idée est de synchroniser les commandes vocales de Yana dans Jarvis pour utiliser la puissance de ce dernier.

## Développement
Je pense que ce n'est pas très compliqué à réaliser, j'ai déjà commencé et si par hasard vous voulez me filer un coup de main, pas besoin de connaître Yana.

### Principe
Voici en simplifié l'algorithme que j'ai imaginé:

1. Je récupère via URL la liste des commandes vocales ainsi que les URL à appeler sur Yana Server
2. Je parse le résultat pour obtenir des lignes correspondants à ça:
"Yana, quelle heure est-il?":"yana.example.com/yana-server/action.php?action=vocalinfo_hour"
4. J'ajoute toutes ces commandes à celles de Jarvis
5. Lors du déclenchement d'une commande, l'URL est appelée via curl, et le retour est parsé puis synthétisé par Jarvis.

### Technique
J'ai déjà un script qui récupère les commandes Yana et les parse comme l'exemple donné ci-dessus. Maintenant il faut que je les ajoute au fichier _commands_, ce qui ne me paraît pas bien difficile. Là où je vais avoir sûrement besoin d'un peu d'aide:

- La synchro se fera à l'installation, mais est-il possible de prévoir une commande "*SYNCHRONISATION * YANA*" avec comme effet l'appel d'un script bash? (le _install.sh_ par exemple).
- Je vois que je peux appeler une URL via Curl, mais comment parser la réponse et comment dire à Jarvis de synthétiser le résultat comme réponse vocale?

Je vous remercie d'avance pour votre aide =)

**Comment by alexylem** [comment]
Salut @valentin8709 j'ai une petite question.
Pourquoi s'embêter à synchroniser (importer) les commandes de Yana et pas tout simplement tout transférer à Yana comme c'est fait pour Jeedom?
```shell
*==jv_curl "yana.example.com/yana-server/action.php?action=$order"
```
Enfin quelque chose dans le genre...

**Comment by valentin8709** [comment]
Je ne suis pas sûr de comprendre ta question... Si j'écris en dur directement les URL dans le fichier de commandes, il faudra que j'édite ce fichier à chaque ajout de composant etc... et le plugin sera valable pour moi, mais pas pour les autres qui n'auront pas les mêmes commandes vocales disponibles.

J'espère avoir répondu à ta question =)

**Comment by alexylem** [comment]
Heu on s'est pas compris.
En fait quand je vois l'url que tu proposes:
```
yana.example.com/yana-server/action.php?action=vocalinfo_hour
```
Il y a une variable `action` qui doit correspondre en quelque sorte à un ordre que tu donnes. Donc j'imagine que c'est cette partie de l'URL qui va changer selon les commandes.

Parce que si c'est le cas, justement l'idée c'est pas d'écrire en dur toutes les commandes, mais n'en écrire qu'une qui forwarde tout ce qui a été dit à Yana. Ca part bien sûr du principe que Yana va être capable d'interpréter ces commandes vocales (écrites) et lancer les actions correspondantes.

Sinon pour répondre quand même à tes questions:
>La synchro se fera à l'installation, mais est-il possible de prévoir une commande "SYNCHRONISATION * YANA" avec comme effet l'appel d'un script bash? (le install.sh par exemple).

Tu pourrais exécuter une synchronization à chaque lancement de Jarvis, via le fichier `functions.sh` de ton plugin. Si je comprends bien ton idée est de tout mettre dans le fichier de commandes, mais tu pourrais très bien, si tu fais un plugin, les garder dans le fichier de commandes du plugin. Si tu me donnes un exemple de commandes YANA et URLs correspondantes je peux te pondre vite fait un proto pour te mettre sur la voie.

>Je vois que je peux appeler une URL via Curl, mais comment parser la réponse et comment dire à Jarvis de synthétiser le résultat comme réponse vocale?

Il suffit d'utilise la fonction `say` et de lui passer ce qu'il doit dire (retour de la requête http dans ce cas précis):
```shell
*==say "$(curl "yana.example.com/yana-server/action.php?action=vocalinfo_hour)"
```
C'est d'ailleurs ce qui est fait pour jeedom. Au besoin tu peux parser avec `jq` (dépendance de Jarvis) s'il te retourne du `json`.

**Comment by valentin8709** [comment]
Ok je comprend mieux! Alors point par point:

Pour le paramètre à passer pour la variable "action", je suis bien d'accord avec toi. Seulement il faut bien que je récupère toutes les actions possibles, et Yana n'offre qu'une URL que je peux attaquer pour recevoir la liste des commandes vocales avec les URL correspondantes. Donc en fin de compte, je ne pense pas que ce soit plus facile de faire comme cela.

Quand je parlais du fichier commands, je parlais bien sûr du fichier du plugin. Pour un exemple de commandes Yana et URL correspondantes, en voici un:

```
"YANA, eteinds la chambre":"yana.example.com/yana-server/action.php?action=radioRelay_vocal_change_state&engine=7&state=0"
"YANA active la purge":"yana.example.com/yana-server/action.php?action=speech_execute&=1"
"YANA je suis ton pere":"yana.example.com/yana-server/action.php?action=speech_execute&=2"
"YANA dis bonjour":"yana.example.com/yana-server/action.php?action=speech_execute&=3"
"YANA surveille mon appart":"yana.example.com/yana-server/action.php?action=speech_execute&=4"
"YANA stop la surveillance":"yana.example.com/yana-server/action.php?action=speech_execute&=5"
"YANA eteinds tout":"yana.example.com/yana-server/action.php?action=speech_execute&=6"
"YANA rearme la surveillance":"yana.example.com/yana-server/action.php?action=speech_execute&=7"
"YANA temperature":"yana.example.com/yana-server/action.php?action=temperature_action"
"YANA enregistre une video":"yana.example.com/yana-server/action.php?action=video_record_vocal"
```

Pour le retour de l'URL, c'est bien du JSON :) Du coup, je pourrai balancer un truc comme ça j'imagine:
`*==say "$(curl "yana.example.com/yana-server/action.php?action=vocalinfo_hour | jq regexp)"`
C'est bien ça?

Mille merci pour ton aide =)

**Comment by alexylem** [comment]
Ca dépend du format du json, mais qqchose dans le genre:
```shell
*==say "$(curl -s "yana.example.com/yana-server/action.php?action=vocalinfo_hour" | jq -r '.property')"
```
Tu peux t'entrainer à `jq` ici:
http://jqplay.org

Bon courage pour ton plugin!

**Comment by valentin8709** [comment]
Super! J'ai tout ce qui me faut pour développer le plugin maintenant. Je reçois un micro compatible dans un quinzaine de jours, il me reste plus qu'à coder.

Merci bien pour ton aide =)

**Comment by alexylem** [comment]
Super je laisse le ticket ouvert pour que tu nous tiennes au courant de tes avancées

**Comment by valentin8709** [comment]
Hello again :) Je crois avoir fini mon plugin. Ca s'est fait assez bien, le gros du plugin étant dans le parsing de la réponse Yana. Par contre, tu m'avais parlé de la possibilité de lancer la fonction de synchro à chaque lancement de Jarvis, comment est-ce possible? (la synchro se fait via l'appel de jv_pg_yana_synchro() du fichier function.sh, et utilise des paramètres du fichier config.sh). Je peux aussi faire une commande vocale qui appelle la fonction mais ça me paraît moins "jolie".

Merci bien!

**Comment by alexylem** [comment]
Le fichier `functions.sh` de ton plugin est chargé à chaque démarrage de Jarvis.
Tu peux aller le lancer en y mettant l'exécution de ta fonction à la fin du fichier:

```shell
jv_pg_yana_synchro() {
}

jv_pg_yana_synchro # exécution au chargement du fichier
```

**Comment by valentin8709** [comment]
Super merci bien =)
Je viens de recevoir mon micro (un peu plus tôt que prévu!), je vais pouvoir commencer quelques tests!
