### ISSUE TITLE
Integrate AWS Polly STT ?

### ISSUE THREAD

**Issue by lasconic** [alexylem/jarvis#274]
### Description

Amazon just release Polly STT https://aws.amazon.com/fr/polly/pricing/

Pricing is almost free for the first 12 months. The Amazon Polly free tier includes 5 million characters per month (around 5 days of audio), for the first 12 months.

**Comment by alexylem** [comment]
Not sure people will be interested if they have to pay (free open-source project).
But let's see how many upvotes it generates.

**Comment by Gilles76** [comment]
As @alexylem said, I try too choose free opensource or anything else when it's possible. I prefer not to pay. But it's my choice.
