### ISSUE TITLE
Possibilité d'interrompre une conversation (commandes imbriquées)

### ISSUE THREAD

**Issue by Jean-Bernard-Hallez** [alexylem/jarvis#275]
### Description
Je suis entrain de finaliser un plugin pour l'envoie de SMS avec free mobile...
J'ai un léger soucis technique...

j'utilise les commandes imbriquées afin de choisir le destinataire... au travers une fonction dans le fichier config.sh, voici ce que ca donne aujourd'hui:

You: envoie un sms à JB
Jarvis: Ok quel est le message ?
You: N'oublie pas d'acheter du pain
Jarvis: le message est noublie pas dacheter du pain ok j'envoie ?
You: oui
Jarvis: c'est parti... (et là il exécute une fonction...)

ca fonctionne très bien, mais sil il y une erreur de nom il me dit seulement à la fin lol
jarvis: Désolé message non envoyé, pas de nom Pierre trouvé dans le fichier config.sh

ce qui est normal car si dès la première question si on lance une fonction et que l'on souhaite arrêter la commande imbriquée on ne peut pas... donc je l'ai mis à la fin...

J'aurai aimé traiter la problématique dès le départ... après plusieurs essais je vois que ce n'est pas possible...  enfin à mon niveau de petit bricoleur du dimanche lol...

Quelqu'un aurait une solution  ?

(il faut peut être modifier le programme JARVIS pour cette option de  commande imbriquée dans le config.sh... là un break pourrait l’arrêter...)

Merci... JB.

### Result
voici mon GIT:
https://github.com/Jean-Bernard-Hallez/jarvis-FREE-sms

```

**Comment by alexylem** [comment]
Effectivement pas possible. Je travaille sur une solution.

**Comment by alexylem** [comment]
Bon en fait c'est possible, voici la solution:
```shell
*ENVO* MESSAGE*==say "A qui voulez-vous envoyer un message?"
>*==if [ "$order" = "alex" ]; then say "Quel est le contenu du message pour $order"; else say "Je ne connais pas $order. Annulation."; commands="$(jv_get_commands)"; return; fi
>>*==say "Voici votre message: $order. L'envoyer?"
>>>*== say "Ok"
```
![image](https://cloud.githubusercontent.com/assets/11017174/20851713/4b3efe30-b8e2-11e6-9085-e23885f9843e.png)
A adapter dans une fonction 😄

**Comment by Jean-Bernard-Hallez** [comment]
EXcellllllllllent !
