### ISSUE TITLE
Comment sauter une commande imbriquée selon la réponse...

### ISSUE THREAD

**Issue by Jean-Bernard-Hallez** [alexylem/jarvis#276]
### Description
Déja je tenais a vous remercier VIVEMENT ...     :-)

Je souhaiterai pouvoir diriger la conversation selon le résultat sur une commande imbriqué qui se trouve un peu plus bas... je m'explique!
dans les commandes imbriqué si la réponse est positive il s'arrête... si elle est négative... il continue... mais j'aimerai le forcer à aller à la suite de après la réponse > oui j'aimerai le faire aller à >>> 
>
>>
>>oui
>>non
>>>oui
>>>non
>>>>oui
>>>>non

est ce possible ??

Merci JB... 

### Result
Exemple: 

You: On peut discuter ?
Jarvis : Oui est-ce bien pierre ?
You: Oui (--> et là il n'y a pas de suite aux événements si je réponds oui... mais si je dis non)
Jarvis: OK a qui ai-je l'honneur ?
You: Pierre
Jarvis: Enchanté Pierre, que jeux tu ? (et c'est là que je souhaite reprendre la main !!)

```

**Comment by alexylem** [comment]
Ca se complique... j'aime les défis, j'essaye...

**Comment by alexylem** [comment]
Voici une solution qui fonctionne, mais bon c'est pas très *user friendly*. Il faudrait que le core puisse permettre de faire ce genre de *jump* plus facilement...
```shell
*DISCUTER*==say "Oui, est-ce bien pierre ?"
>*OUI*==say "Ok Pierre"; commands="$(jv_get_commands)"; jv_handle_order "GOTO1"; return
>*NON*==say "OK a qui ai-je l'honneur ?"
>>*== say "Enchanté $order"; commands="$(jv_get_commands)"; jv_handle_order "GOTO1"; return
GOTO1==say "Que veux-tu ?"
>*==say "Ok pour: $order"
```
![image](https://cloud.githubusercontent.com/assets/11017174/20861427/853316fe-b990-11e6-932b-bf587b47dec0.png)

**Comment by Jean-Bernard-Hallez** [comment]
Ok j'avance a grand pas avec cela... mais j'ai encore un bug....
en effet ca me permet de sortir d'une commande imbriqué pour une simple commande direct... mais je vais plus loin:

Je fais la balle de ping pong entre plusieurs commande imbriqué... je passe et analyse les réponses par des fonctions de functions.sh... (pour faireun petit "Turing")

mais justement... si je souhaite stopper tout cela... (comme si j'arrêtais de jouer en plein jeu)  je passe par des fonctions (function.sh) qui analysent les réponses du $order et si il y a le mot STOP il me faut arrêter la conversation... et là je ne sais pas comment faire...
si je mets dans le config.sh:
jv_pg_ct_STOP () {
if [ "$order" = "stop" ]; then
echo "STOP enregistrÃ©... "; commands="$(jv_get_commands)"; jv_handle_order "GOTO4"; return
fi
}
il va bien au goto 4 mais il continu ensuite la commande précédente et réprend par exemple la suite du goto3 etc... sans... s'arrêter !

**Comment by alexylem** [comment]
Salut @Jean-Bernard-Hallez 
Il me faudrait plus d'information, peux-être pourrais-tu partager ton fichier de commandes? Parce que je ne sais pas ce qu'il y a dans tes GOTO..
Sinon pourquoi mettre des fonctions dans config.sh? functions.sh est fait pour ca 😄 
Il faudrait que je comprenne d'ou et comment est appelée ta fonction `jv_pg_ct_STOP`

**Comment by Jean-Bernard-Hallez** [comment]
ok je t'envoie cela par Email... Merci...

**Comment by alexylem** [comment]
Ok donc si je comprends bien, quelque-soit la conversation dans laquelle tu es, tu veux pouvoir identifier le terme "STOP" et tout arrêter c'est bien ca? Sans que la commande *STOP* ne soit écrite dans chaque niveau de conversation?

Parce que tu pourrais très bien:
```shell
*CA VA*==say "Très bien et toi ça va?"
>*OUI*==say "t'es sûr que ca va?"
>*NON*==say "t'es sûr que ca va pas?"
>*STOP*==say "ok j'arrête..."; bypass=false; break # à tester
>>*==say "ok on continue..."
```

**Comment by Jean-Bernard-Hallez** [comment]
Ok Snif...ca ne marche pas...

voici mon Git... je ne le mets pas encore dans les plugins Jarvis... il est en phase test...
C'est un peu comme un jeu sous forme de chatbot mais en français sous Jarvis même...

Installer le dans le répertoire Plugins de jarvis, lancez Jarvis puis dite à la commande: on discute
Jarvis va demander qui êtes vous, après cette question pouvez dire: stop et vous verrez ou ca bug... car ça continuera... lol

https://github.com/Jean-Bernard-Hallez/Jarvis-Turing

Second problème lors d'un choix multiple sur une commande imbriquée, quand on lance Jarvis dans les commande de ce plugin on voit par exemple:
 >*NON*|*PAS*

si à la commande vous tapez: pas il va répondre puis après plus aucune commande n'est possible... il répondra tout le temps:
"Je ne comprends pas on discute"
Merci... JB.

**Comment by alexylem** [comment]
C'est ca que tu veux faire?
```shell
*DISCUTER*==say "Ca va?"
>*STOP*==
>*OUI*==say "Veux-tu lire tes mails?"
>>*STOP*==
>>*OUI*==commands="$(jv_get_commands)"; jv_handle_order "emails"; return 
>>*NON*==say "Ok"
>*NON*==say "Ah mince, tu veux que je te raconte une blague?"
>>*STOP*==
>>*OUI*==say "Alors c'est toto qui rentre dans un bar…" 
>>*NON*==say "Ok"
```
![image](https://cloud.githubusercontent.com/assets/11017174/21195864/d7237e56-c235-11e6-8668-44464f02e2b3.png)

D'ailleurs le choix multiple marche chez moi:
```shell
*DISCUTER*==say "Ca va?"
>*STOP*==
>*OUI*==say "Veux-tu lire tes mails?"
>>*STOP*==
>>*OUI*==commands="$(jv_get_commands)"; jv_handle_order "emails"; return 
>>*NON*|*PAS*==say "Ok"
```
![image](https://cloud.githubusercontent.com/assets/11017174/21195931/24c82986-c236-11e6-9fab-83e06028bd27.png)

Dernier point: lorsqu'il "ne comprend plus rien" c'est qu'il est bloqué dans une conversation et attend une réponse précise. Je pense modifier Jarvis pour afficher les réponses possible lorsque l'on est au milieu d'une conversation, tu en penses quoi? (je peux le faire rapidement)

**Comment by Jean-Bernard-Hallez** [comment]
Ah oui il va falloir que je teste je ne suis pas à la maison aujourd'hui à suivre demain matin... mais en effet le fait qu'il puisse afficher en option bien sur les possibilités de conversation en cours de commande imbriqué serait une bonne idée


Envoyé depuis mon appareil Samsung

-------- Message d'origine --------
De : Alexandre Mély <notifications@github.com> 
Date : 14/12/2016  19:49  (GMT+01:00) 
À : alexylem/jarvis <jarvis@noreply.github.com> 
Cc : Hallez <jbhallez@aol.com>, Mention <mention@noreply.github.com> 
Objet : Re: [alexylem/jarvis] Comment sauter une commande imbriquée selon la réponse... (#276) 

C'est ca que tu veux faire?
*DISCUTER*==say "Ca va?"
>*STOP*==
>*OUI*==say "Veux-tu lire tes mails?"
>>*STOP*==
>>*OUI*==commands="$(jv_get_commands)"; jv_handle_order "emails"; return 
>>*NON*==say "Ok"
>*NON*==say "Ah mince, tu veux que je te raconte une blague?"
>>*STOP*==
>>*OUI*==say "Alors c'est toto qui rentre dans un bar…" 
>>*NON*==say "Ok"

D'ailleurs le choix multiple marche chez moi:
*DISCUTER*==say "Ca va?"
>*STOP*==
>*OUI*==say "Veux-tu lire tes mails?"
>>*STOP*==
>>*OUI*==commands="$(jv_get_commands)"; jv_handle_order "emails"; return 
>>*NON*|*PAS*==say "Ok"

Dernier point: lorsqu'il "ne comprend plus rien" c'est qu'il est bloqué dans une conversation et attend une réponse précise. Je pense modifier Jarvis pour afficher les réponses possible lorsque l'on est au milieu d'une conversation, tu en penses quoi? (je peux le faire rapidement)

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/alexylem/jarvis","title":"alexylem/jarvis","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/alexylem/jarvis"}},"updates":{"snippets":[{"icon":"PERSON","message":"@alexylem in #276: C'est ca que tu veux faire?\r\n```shell\r\n*DISCUTER*==say \"Ca va?\"\r\n\u003e*STOP*==\r\n\u003e*OUI*==say \"Veux-tu lire tes mails?\"\r\n\u003e\u003e*STOP*==\r\n\u003e\u003e*OUI*==commands=\"$(jv_get_commands)\"; jv_handle_order \"emails\"; return \r\n\u003e\u003e*NON*==say \"Ok\"\r\n\u003e*NON*==say \"Ah mince, tu veux que je te raconte une blague?\"\r\n\u003e\u003e*STOP*==\r\n\u003e\u003e*OUI*==say \"Alors c'est toto qui rentre dans un bar…\" \r\n\u003e\u003e*NON*==say \"Ok\"\r\n```\r\n![image](https://cloud.githubusercontent.com/assets/11017174/21195864/d7237e56-c235-11e6-8668-44464f02e2b3.png)\r\n\r\nD'ailleurs le choix multiple marche chez moi:\r\n```shell\r\n*DISCUTER*==say \"Ca va?\"\r\n\u003e*STOP*==\r\n\u003e*OUI*==say \"Veux-tu lire tes mails?\"\r\n\u003e\u003e*STOP*==\r\n\u003e\u003e*OUI*==commands=\"$(jv_get_commands)\"; jv_handle_order \"emails\"; return \r\n\u003e\u003e*NON*|*PAS*==say \"Ok\"\r\n```\r\n![image](https://cloud.githubusercontent.com/assets/11017174/21195931/24c82986-c236-11e6-9fab-83e06028bd27.png)\r\n\r\nDernier point: lorsqu'il \"ne comprend plus rien\" c'est qu'il est bloqué dans une conversation et attend une réponse précise. Je pense modifier Jarvis pour afficher les réponses possible lorsque l'on est au milieu d'une conversation, tu en penses quoi? (je peux le faire rapidement)"}],"action":{"name":"View Issue","url":"https://github.com/alexylem/jarvis/issues/276#issuecomment-267120512"}}}

**Comment by alexylem** [comment]
@Jean-Bernard-Hallez J'ai créé #295 pour ca.

**Comment by Jean-Bernard-Hallez** [comment]
Alexandre ne peux-tu pas inclure tout simplement à Jarvis l'arrêt de toute commande lorsque l'on prononce stop jarvis par exemple...  ça résoudrait pas mal de bugs

Envoyé depuis mon appareil Samsung

-------- Message d'origine --------
De : Alexandre Mély <notifications@github.com> 
Date : 14/12/2016  19:49  (GMT+01:00) 
À : alexylem/jarvis <jarvis@noreply.github.com> 
Cc : Hallez <jbhallez@aol.com>, Mention <mention@noreply.github.com> 
Objet : Re: [alexylem/jarvis] Comment sauter une commande imbriquée selon la réponse... (#276) 

C'est ca que tu veux faire?
*DISCUTER*==say "Ca va?"
>*STOP*==
>*OUI*==say "Veux-tu lire tes mails?"
>>*STOP*==
>>*OUI*==commands="$(jv_get_commands)"; jv_handle_order "emails"; return 
>>*NON*==say "Ok"
>*NON*==say "Ah mince, tu veux que je te raconte une blague?"
>>*STOP*==
>>*OUI*==say "Alors c'est toto qui rentre dans un bar…" 
>>*NON*==say "Ok"

D'ailleurs le choix multiple marche chez moi:
*DISCUTER*==say "Ca va?"
>*STOP*==
>*OUI*==say "Veux-tu lire tes mails?"
>>*STOP*==
>>*OUI*==commands="$(jv_get_commands)"; jv_handle_order "emails"; return 
>>*NON*|*PAS*==say "Ok"

Dernier point: lorsqu'il "ne comprend plus rien" c'est qu'il est bloqué dans une conversation et attend une réponse précise. Je pense modifier Jarvis pour afficher les réponses possible lorsque l'on est au milieu d'une conversation, tu en penses quoi? (je peux le faire rapidement)

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/alexylem/jarvis","title":"alexylem/jarvis","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/alexylem/jarvis"}},"updates":{"snippets":[{"icon":"PERSON","message":"@alexylem in #276: C'est ca que tu veux faire?\r\n```shell\r\n*DISCUTER*==say \"Ca va?\"\r\n\u003e*STOP*==\r\n\u003e*OUI*==say \"Veux-tu lire tes mails?\"\r\n\u003e\u003e*STOP*==\r\n\u003e\u003e*OUI*==commands=\"$(jv_get_commands)\"; jv_handle_order \"emails\"; return \r\n\u003e\u003e*NON*==say \"Ok\"\r\n\u003e*NON*==say \"Ah mince, tu veux que je te raconte une blague?\"\r\n\u003e\u003e*STOP*==\r\n\u003e\u003e*OUI*==say \"Alors c'est toto qui rentre dans un bar…\" \r\n\u003e\u003e*NON*==say \"Ok\"\r\n```\r\n![image](https://cloud.githubusercontent.com/assets/11017174/21195864/d7237e56-c235-11e6-8668-44464f02e2b3.png)\r\n\r\nD'ailleurs le choix multiple marche chez moi:\r\n```shell\r\n*DISCUTER*==say \"Ca va?\"\r\n\u003e*STOP*==\r\n\u003e*OUI*==say \"Veux-tu lire tes mails?\"\r\n\u003e\u003e*STOP*==\r\n\u003e\u003e*OUI*==commands=\"$(jv_get_commands)\"; jv_handle_order \"emails\"; return \r\n\u003e\u003e*NON*|*PAS*==say \"Ok\"\r\n```\r\n![image](https://cloud.githubusercontent.com/assets/11017174/21195931/24c82986-c236-11e6-9fab-83e06028bd27.png)\r\n\r\nDernier point: lorsqu'il \"ne comprend plus rien\" c'est qu'il est bloqué dans une conversation et attend une réponse précise. Je pense modifier Jarvis pour afficher les réponses possible lorsque l'on est au milieu d'une conversation, tu en penses quoi? (je peux le faire rapidement)"}],"action":{"name":"View Issue","url":"https://github.com/alexylem/jarvis/issues/276#issuecomment-267120512"}}}

**Comment by Jean-Bernard-Hallez** [comment]
Yes ça fonctionne, on peut l'arrêter ainsi  !!!!!

**Comment by Jean-Bernard-Hallez** [comment]
Et le dernier problème technique... enfin pour le moment lol....
Je sais maintenant faire un goto quand le me trouve dans le fichier de commands.
say "$(`$(echo cat $CHEMIN/choixquestion.txt)`) passons à toi..."; commands="$(jv_get_commands)"; jv_handle_order "GOTO1"; return


Mais je n'y arrive pas a faire un gotoXX quand je suis dans functions.sh qui me renverai sur le fichier commands au gotoXX.

Option N°2 Quand on a lancé une fonction type say "$(jv_pg_ct_QUESTIONHASARD)", il va au fichier functions.sh qui analyse l' $order, peut-on  poser une question selon le contenu à traiter directement dans le functions.sh ?

**Comment by Jean-Bernard-Hallez** [comment]
Et coucou.... je te propose d'utiliser teamviewer afin de te montrer la problématique..... 


Envoyé depuis mon appareil Samsung

-------- Message d'origine --------
De : Alexandre Mély <notifications@github.com> 
Date : 15/12/2016  15:52  (GMT+01:00) 
À : alexylem/jarvis <jarvis@noreply.github.com> 
Cc : Hallez <jbhallez@aol.com>, Mention <mention@noreply.github.com> 
Objet : Re: [alexylem/jarvis] Comment sauter une commande imbriquée selon la réponse... (#276) 

@Jean-Bernard-Hallez J'ai créé #295 pour ca.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/alexylem/jarvis","title":"alexylem/jarvis","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/alexylem/jarvis"}},"updates":{"snippets":[{"icon":"PERSON","message":"@alexylem in #276: @Jean-Bernard-Hallez J'ai créé #295 pour ca."}],"action":{"name":"View Issue","url":"https://github.com/alexylem/jarvis/issues/276#issuecomment-267346453"}}}

**Comment by Jean-Bernard-Hallez** [comment]
Il serait bien de pouvoir dire dans une commande imbriqué répète la dernière question.... car le fait de voir les réponses possibles à l'écrit certes on verra les réponses possible si on est en mode clavier....  mais si on est pas connecté avec et que l'on parle directement dans le micro    .... 

Envoyé depuis mon appareil Samsung

-------- Message d'origine --------
De : Alexandre Mély <notifications@github.com> 
Date : 14/12/2016  19:49  (GMT+01:00) 
À : alexylem/jarvis <jarvis@noreply.github.com> 
Cc : Hallez <jbhallez@aol.com>, Mention <mention@noreply.github.com> 
Objet : Re: [alexylem/jarvis] Comment sauter une commande imbriquée selon la réponse... (#276) 

C'est ca que tu veux faire?
*DISCUTER*==say "Ca va?"
>*STOP*==
>*OUI*==say "Veux-tu lire tes mails?"
>>*STOP*==
>>*OUI*==commands="$(jv_get_commands)"; jv_handle_order "emails"; return 
>>*NON*==say "Ok"
>*NON*==say "Ah mince, tu veux que je te raconte une blague?"
>>*STOP*==
>>*OUI*==say "Alors c'est toto qui rentre dans un bar…" 
>>*NON*==say "Ok"

D'ailleurs le choix multiple marche chez moi:
*DISCUTER*==say "Ca va?"
>*STOP*==
>*OUI*==say "Veux-tu lire tes mails?"
>>*STOP*==
>>*OUI*==commands="$(jv_get_commands)"; jv_handle_order "emails"; return 
>>*NON*|*PAS*==say "Ok"

Dernier point: lorsqu'il "ne comprend plus rien" c'est qu'il est bloqué dans une conversation et attend une réponse précise. Je pense modifier Jarvis pour afficher les réponses possible lorsque l'on est au milieu d'une conversation, tu en penses quoi? (je peux le faire rapidement)

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/alexylem/jarvis","title":"alexylem/jarvis","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/alexylem/jarvis"}},"updates":{"snippets":[{"icon":"PERSON","message":"@alexylem in #276: C'est ca que tu veux faire?\r\n```shell\r\n*DISCUTER*==say \"Ca va?\"\r\n\u003e*STOP*==\r\n\u003e*OUI*==say \"Veux-tu lire tes mails?\"\r\n\u003e\u003e*STOP*==\r\n\u003e\u003e*OUI*==commands=\"$(jv_get_commands)\"; jv_handle_order \"emails\"; return \r\n\u003e\u003e*NON*==say \"Ok\"\r\n\u003e*NON*==say \"Ah mince, tu veux que je te raconte une blague?\"\r\n\u003e\u003e*STOP*==\r\n\u003e\u003e*OUI*==say \"Alors c'est toto qui rentre dans un bar…\" \r\n\u003e\u003e*NON*==say \"Ok\"\r\n```\r\n![image](https://cloud.githubusercontent.com/assets/11017174/21195864/d7237e56-c235-11e6-8668-44464f02e2b3.png)\r\n\r\nD'ailleurs le choix multiple marche chez moi:\r\n```shell\r\n*DISCUTER*==say \"Ca va?\"\r\n\u003e*STOP*==\r\n\u003e*OUI*==say \"Veux-tu lire tes mails?\"\r\n\u003e\u003e*STOP*==\r\n\u003e\u003e*OUI*==commands=\"$(jv_get_commands)\"; jv_handle_order \"emails\"; return \r\n\u003e\u003e*NON*|*PAS*==say \"Ok\"\r\n```\r\n![image](https://cloud.githubusercontent.com/assets/11017174/21195931/24c82986-c236-11e6-9fab-83e06028bd27.png)\r\n\r\nDernier point: lorsqu'il \"ne comprend plus rien\" c'est qu'il est bloqué dans une conversation et attend une réponse précise. Je pense modifier Jarvis pour afficher les réponses possible lorsque l'on est au milieu d'une conversation, tu en penses quoi? (je peux le faire rapidement)"}],"action":{"name":"View Issue","url":"https://github.com/alexylem/jarvis/issues/276#issuecomment-267120512"}}}

**Comment by alexylem** [comment]
Oula ca fait bcp de questions d'un coup 😮  😄 

>Alexandre ne peux-tu pas inclure tout simplement à Jarvis l'arrêt de toute commande lorsque l'on prononce stop jarvis par exemple...  ça résoudrait pas mal de bugs

Oui mais ca du coup ce n'est plus multi-langues... à moins de le paramétrer. Par défaut ca pourrait être STOP. Mais il y a un risque... si dans la conversation le mot stop est prononcé (ex: envoi de SMS, prise de note, rappel...), tout va s'annuler... à voir...

>je n'y arrive pas a faire un gotoXX quand je suis dans functions.sh

Surement à cause du return qui quitte ta fonction mais pas la fonction `handle_order` de Jarvis. Faut que j'y réfléchisse...

>Il serait bien de pouvoir dire dans une commande imbriqué répète la dernière question....

Je te propose qu'on traite ce point directement dans #295

**Comment by Jean-Bernard-Hallez** [comment]
Désolé je me suis vite emballé et je t'ai posé plein de questions... Merci en tout cas encore pour toute cette superbe évolution !

**Comment by alexylem** [comment]
@Jean-Bernard-Hallez j'espère comprendre pourquoi tu utilises `functions.sh` pour traiter la reconnaissance des ordres.
Normalement tout ce processus est déjà intégré dans Jarvis afin vous faciliter la tâche. Ainsi les patterns à reconnaître sont définis dans `commands` (et pas ailleurs, sauf cas exceptionnel).
`functions.sh` quand à lui doit servir pour exécuter des commandes complexes (et pas reconnaître des ordres).
Ainsi, même dans le cas d'un conversational bot, tu devrais pouvoir gérer la discussion directement depuis le fichier de commandes:
```shell
*DISCUTER*==say "Ca va?"
>*OUI*==say "Veux-tu lire tes mails?"
>>*OUI*|*OK*==commands="$(jv_get_commands)"; jv_handle_order "emails"; return 
>>*NON*|*PAS*==say "Ok"
>*NON*|*PAS*==say "Ah mince, tu veux que je te raconte une blague?"
>>*OUI*|*OK*==say "Alors c'est toto qui rentre dans un bar…" 
>>*NON*|*PAS*==say "Ok"
```

**Comment by alexylem** [comment]
PS: évite de répondre depuis ta boite mail, car cela inclue tout l'historique et je passe bcp de temps à faire le clean-up. Pour répondre, clique dans le lien dans l'email ou directement sur le bouton quand gmail le propose:
![image](https://cloud.githubusercontent.com/assets/11017174/21286680/be0422f0-c45a-11e6-8303-a1ad978efecf.png)
Merci! 👍

**Comment by Jean-Bernard-Hallez** [comment]
Ok je ne répondrais plus par Email... je ne savais pas désolé Alex.... (j'ai encore fait la boulette en début d'après midi quand j'ai lu ton Email je me suis mordu les doigts lol)

**Comment by alexylem** [comment]
Merci @Jean-Bernard-Hallez j'espère que tu vas y arriver et que ca ne va pas trop te compliquer les choses. Si vraiment tu t'en sors pas, je te propose de partager l'ensemble des conversations que tu comptes mettre en place en brut, et je te conseillerai comment procéder.
