### ISSUE TITLE
Bonjour, comment faire pour sauter une commande imbriquée selon la réponse..

### ISSUE THREAD

**Issue by Jean-Bernard-Hallez** [alexylem/jarvis#278]
### Description

Déja je tenais a vous remercier VIVEMENT ... :-)
Je souhaiterai pouvoir diriger la conversation selon le résultat sur une commande imbriqué qui se trouve un peu plus bas... je m'explique!
dans les commandes imbriqué si la réponse est positive il s'arrête... si elle est négative... il continue... mais j'aimerai le forcer à aller à la suite de après la réponse > oui j'aimerai le faire aller à >>>

>oui
>non
>>oui
>>non
>>>oui
>>>non

est ce possible ??

En parallère, J'ai remarqué que lorsque l'on est sur une commande imbriquée on ne peut pas utiliser:
jv_handle_order "quel jour" par exemple... il y a t-il aussi une solution ?

Merci JB...
### Result
``
Exemple:
You: On peut discuter ?
Jarvis : Oui est-ce bien pierre ?
You: Oui (--> et là il n'y a pas de suite aux événements si je réponds oui... mais si je dis non)
Jarvis: OK a qui ai-je l'honneur ?
You: Pierre
Jarvis: Enchanté Pierre, que jeux tu ? (et c'est là que je souhaite reprendre la main !!)
```

**Comment by Jean-Bernard-Hallez** [comment]
En parallère, J'ai remarqué que lorsque l'on est sur une commande imbriquée on ne peut pas utiliser:
jv_handle_order "quel jour" par exemple... il y a t-il aussi une solution ?

**Comment by alexylem** [comment]
Dupplicate #276
