### ISSUE TITLE
Tuto parametrage plugin wikipedia

### ISSUE THREAD

**Issue by jeedomclaude** [alexylem/jarvis#279]
Bonjour
Est-ce qu'une âme charitable pourrait m'aider en me disant comment paramétrer le Plugin Wikipédia.
Je l'ai bien installé dans Jarvis, mais je ne comprends pas comment le paramétrer pour l'utiliser.
Auriez-vous un Tuto ?
Merci

**Comment by dud29** [comment]
Bonjour, pour moi il n'y a pas de paramétrage, une fois qu'on en mode conversation il suffit de dire donne moi la definition de .. et c'est bon.
Dud29

**Comment by alexylem** [comment]
Pour toute question ou problème lié à un plugin Jarvis, merci de créer un ticket sur le repository correspondant. Ainsi son auteur en sera informé et pourra vous aider.

**Ok, alors c'est où?**
* Depuis Jarvis, allez dans Plugins > Installed > The Plugin > Report an issue
* Depuis le site, allez sur la page du plugin et cliquez sur le lien "Open a ticket"

Autrement dit, je ne fait pas de support pour les plugins tiers.
Merci de votre compréhension.

https://github.com/Gilles76/jarvis-wikipedia/issues/new

**Comment by jeedomclaude** [comment]
Bonjour dud29
Après avoir installé le planning, il ne répond à aucune de mes commandes?
Exemple:
Moi: donne-moi la définition de Superman
Jarvis: désolé je ne comprends pas la demande
Pou info,le reste de mes commandes avec Jeedom fonctionne bien
J'ai ouvert un tickets ,au développeur du plugin
Merci

**Comment by dud29** [comment]
Bonjour,
le plugin jeedom capte toutes les demandes, donc si ton plugin wikipedia n'est pas devant le plugin jeedom, ça ne fonctionnera pas. Il faut aller dans le menu de Jarvis puis menu Plugins et enfin Matching Oder et la tu mets le plugin Jeedom en dernier. ça devrai fonctionner voir issue #220 de Jarvis.
Dud29

**Comment by alexylem** [comment]
@dud29 bien vu 👍

**Comment by jeedomclaude** [comment]
Merci dud29, cela fonctionne maintenant 👍
