### ISSUE TITLE
Intégration d'un chatterbot AIML

### ISSUE THREAD

**Issue by byackee** [alexylem/jarvis#281]
### Description
Intégrer dans le core ou sous forme de plugins un bot AIML

http://www.alicebot.org/aiml.html

**Comment by byackee** [comment]
Je suis entrain de créer un plugin rivescript, on peut clore le sujet 👍

**Comment by alexylem** [comment]
Super merci, d'ailleurs je t'ai ouvert un ticket 😉 
Merci pour ta contribution!
Alex.
