### ISSUE TITLE
Plugin recherche Web comme Google Now

### ISSUE THREAD

**Issue by cyril51100** [alexylem/jarvis#282]
Bonjour,

Félicitations pour ce travail de dingue. Je viens d'installer Jarvis sur mon Rpi3 ça fonctionne bien avec les plugin météo, heure sauf éphémérides il ne donne que la date et pas la saint bref un détail.
Ma question : Est il possible de poser une question a Jarvis comme avec Google now par exemple, qu'il fasse une recherche sur le net ?

Merci d'avance.

Bravo encore pour ce super boulot. 👍

Cyril

**Comment by alexylem** [comment]
Merci, 
J'aurais est avant tout un assistant vocal. Tu n'as pas de retour visuel sauf si tu as le terminal ouvert. Pour la recherche Google c'est bien entendu possible, il reste à faire le plugin, mais je vois mal comment on peut donner les résultats. C'est facile avec un écran qui peut en afficher la liste. Ça l'est moins à l'oral, pense tu lui faire dicter tous les résultats?

**Comment by alexylem** [comment]
Sauf si tu pense aux questions fermées auquel cas oui il doit y avoir des services web dans ce genre...

**Comment by cyril51100** [comment]
Merci pour ton retour, dsl je suis pas du tout développeur :-(  , je
pensais a une utilisation comme SIRI par exemple.

Le 5 décembre 2016 à 08:10, Alexandre Mély <notifications@github.com> a
écrit :

**Comment by alexylem** [comment]
Tu pourrais donner des exemples de question et de réponses tels que tu aimerais avoir? Ca m'aiderait bcp. Merci.

**Comment by etopit** [comment]
je ne sais pas ce que souhaite cyril51100 je pense qu'il a en tête les questions que l'on peux poser à google du genre "quel est le président de la france"

un lien au pif à la question à quoi répond google ? :p
http://www.outilsfroids.net/2015/09/quand-google-vous-repond-directement-les-questions-qui-marchent/

**Comment by cyril51100** [comment]
Oui c'est exactement ça.

**Comment by cyril51100** [comment]
Oui c'est exactement ça

**Comment by Jean-Bernard-Hallez** [comment]
Bonjour Cyril... je lis ton post et je vois que tu as un problème avec "éphémérides il ne donne que la date et pas la saint bref un détail."... Qu'as-tu comme problème afin que je puisse essayer de corriger un bug ??
Je te conseil de supprimer le plugin et de le réinstaller car j'avais fait des modifications... il faut savoir que si tu as modifié le fichier config.sh et qu'un apostrophe trainne dans la trame... ca le bloque.

**Comment by cyril51100** [comment]
Bonjour,

J'ai installé la le plugin éphéméride la semaine dernière et quand je dis
le mot "éphéméride" il donne juste la date. J'ai rien modifié.

Cyril

**Comment by Jean-Bernard-Hallez** [comment]
TU as raison... je viens moi même de le supprimer et de le réinstaller le plugins... il me donne que la date  !! je cherche...

**Comment by Jean-Bernard-Hallez** [comment]
Et voilà c'est à jour, peux tu vérifier en faisant 
./jarvis.sh -u 
qui force la mise à jour...

**Comment by cyril51100** [comment]
Au top je testerai .

**Comment by cyril51100** [comment]
Super ça marche merci

2016-12-07 14:04 GMT+01:00 Cyril Lemoine <lemcyril@gmail.com>:

> Au top je testerai .
>
>
>
