### ISSUE TITLE
Passer outre la detection du micro

### ISSUE THREAD

**Issue by tchoul** [alexylem/jarvis#284]
Bonjour,

Après avoir tester Jarvis sous debian et en attendant le micro et les enceintes pour mon raspberry, je souhaiterai l'installer sur mon Raspberry pi 3 qui est sous Raspian jessie full.

Le problème est qu'en voulant l'installer, il test le micro que je n'ai pas avant au minimum 1 semaine.
Comment passer outre? j'ai essayé avec 0/0 rien, une solution que je n'aurais pas vu?

merci

**Comment by byackee** [comment]
Pour le moment la seule solution est de modifier le fichier jarvis.sh et de commenter les lignes suivantes en ajoutant # devant chaque ligne:

`while true; do
                dialog_msg "Checking audio input, make sure your microphone is on, press [Ok] and say something"
                clear
                rec -r 16000 -c 1 -b 16 -e signed-integer $audiofile trim 0 3
                if [ $? -eq 0 ]; then
                    play $audiofile
                    dialog_yesno "Did you hear yourself?" true >/dev/null && break
                fi
                jv_warning "Selection of the microphone device"
                arecord -l
                read -p "Indicate the card # to use [0-9]: " card
                read -p "Indicate the device # to use [0-9]: " device
                rec_hw="hw:$card,$device"
                #IFS=$'\n'
                #devices=(`arecord -l | grep ^card`)
                #device=`dialog_select "Select a microphone" devices[@]`
                #rec_hw=`echo $device | sed -rn 's/card ([0-9]+)[^,]*, device ([0-9]+).*/hw:\1,\2/p'`
                update_alsa $play_hw $rec_hw
            done
            ;;`

**Comment by tchoul** [comment]
Super!!  Merci!! Au top!!

**Comment by alexylem** [comment]
Je viens de pousser une mise à jour qui permets de passer cette étape.

Mettez à jour:
```shell
$> ./jarvis.sh -u
```
