### ISSUE TITLE
Utiliser plusieurs micros - Using several microhpones

### ISSUE THREAD

**Issue by kiki51** [alexylem/jarvis#285]
Bonjour,

Je ne suis pas sur d'etre au bon endroit mais je ne trouve pas une section pour poser une question alors je me lance. 

Je voudrais commencer à installer **jarvis** mais j'ai une petite **interrogation**.
Mon raspberry devrait etre placé un peu près au milieu de ma maison, donc le **micro** pour la reconnaissance vocale aussi...

Cependant est il possible d'utiliser un deuxieme voir meme un troisieme micro, pour commander Jarvis dans les pièces eloignées par rapport au raspberry??

Tant qu'a faire, des micro sans fil, quoi que ma maison est cablée en RJ45 dans chaques pieces donc pourquoi ne pas utiliser ce cable??

Voial, si quelqu'un peu m'eclairer à ce sujet ca serait top avant de ce decider

Merci pour vos réponses.

Eric

**Comment by physicien** [comment]
Les micros de salle de conférences qu'on baptise amicalement les "pieuvres" sont faits pour être interconnectés et agir comme un seul micro. Tu devrais regarder dans cette direction. Le CM-1000, le Jabra 410 et le MXL AC-404 sont des exemples de tels micros.

**Comment by kiki51** [comment]
Merci de cette réponse rapide et précise.
je vas regarder de ce côté, l'idéal serait d'en avoir entre 3 et 6 selon leur portée...

**Comment by kiki51** [comment]
devant le prix des pieuvre, je pense que je vais me tourner vers une solution exotique! meme si ca me plait moyen...

A votre avis, en utilisant un convertisseur de ce genre : 

[https://www.google.fr/shopping/product/15960467638093460647?q=adaptateur+rj45+usb&safe=off&biw=1615&bih=917&bav=on.2,or.r_cp.&bvm=bv.140915558,d.d2s&tch=1&ech=1&psi=KnpJWJ6EEIOBacHokdAH.1481210411601.5&prds=paur:ClkAsKraX4rhlTXUUeBSxKkNmQ62ZF0eMh5np-OgGPoCKcm1TAyecpc6EmUnmzW0j4fCGDObcItlr8QwWS5g4BAjiwE-U3ZB3xKA2S9yj6THOHxFi9TNd3jc3RIZAFPVH7072cy-Wjham7I1kRgsf9Wn9YpCMQ&sa=X&ved=0ahUKEwi4vZLp8uTQAhVHORoKHW1_AbUQ8wII4QMwDw](url)

Je l'utilise dans chaque pièces ou je souhaitent avoir une reconnaissance vocale.
d'un coté j'ai un micro USB "basique" ( dans la pièce en faite), et de l'aurte j'arrive à mon compteur electrique au milieu de la maison, sur lequel je recoit tout les micro qui seront connectés au raspberry et a Jarvis!

ca me parait trop beau pour fonctionner.
j'ai un doute sur l'alimentation du micri USB par exemple.
Vous en penser quoi?

Merci

**Comment by alexylem** [comment]
Sujet intéressant! C'est sûr que je préfèrerais qu'il y ait un seul micro "logique". Il doit peut-être exister des concentrateurs de micro, genre Y jack 😄  Idéalement en bluetooth car les micros pourraient être dans plusieurs pièces...

**Comment by kiki51** [comment]
Salut
Effectivement ya plusieurs possibilités je pense.
Jaime quand meme mieux le filaire... Je pense au je vais prendre deux adaptateurs rj45 usb ( vu le prix je prend pas de risque ) et tester un micro dans les chambre en usb sur  mes prises réseaux.
Apres est ce que jarvis va pouvoir gérer plusieurs micro a la fois? Meme si ça n'est pas simultané.

Merci pour vos réponses, c'est top d'avoir un projet intéressant avec des personnes qui répondent et s'investissent.
Ca donne vraiment envie d'essayer nos idées.
Merci

**Comment by alexylem** [comment]
Plusieurs micros ca doit être techniquement possible, il faudrait modifier le fichier `.asoundrc` et reload alsa à la volée, mais si ce n'est pas simultané je ne vois pas trop l'intérêt...
Il doit bien exister des mixer ou un autre système équivalent, on doit pas être les premiers à se poser la question :)

**Comment by wikijm** [comment]
Le sujet a été abordé ici : [Home Automation Voice Control - Multi-Room Microphone Speech Analysis](http://www.instructables.com/id/Multi-Mic-Speech-To-Text-with-Python/)

**Comment by Jean-Bernard-Hallez** [comment]
kiki51 regarde ce plugin... c'est une alternative qui peut t'aider...
http://domotiquefacile.fr/jarvis/plugins/multi-jarvis-server-esclaves

**Comment by kiki51** [comment]
Bonjour,

Merci pour vos réponses, je viens de voir cela, et c'est bien interressant tout ca!
Du coup, on peut partir sur l'idée de placer un raspberry dans chaque piece que l'on souhaite domotiser.
Tant qu'a faire, un Raspberry Pi zero pour avoir moins de conso... ca peut etre une bonne idée.
Les esclaves lancent les commandes en direction du maitre et zou,.. pas bete du tout.
J'etudie tout ca car la solution des micros raccordés sur les prises RJ45 des pièces, et qui arrivent sur un Hub USB du Raspberry Pi principal me parait bancale.. mais faut tester tout ca!

Je regarde ca, merci de vos réponses, c'est vraiment très appréciable pour avancer sur le projet!

**Comment by kiki51** [comment]
Bonjour jean Bernard,

En attendant de recevoir mon Raspberry pi Zero je voulais un petit eclaircessement.
Si j'ai bien compris, tu installes un Raspian + Jarvis + ton plugin sur ton Raspberry esclave et sur ton raspberry maitre tu ajoute simplement le plugin que tu as crée ( en dernier )?
Au niveau du parametrage, IP de(s) esclaves et du maitre entre autre, cela se configure dans le plugin?

Merci d'avance

**Comment by Jean-Bernard-Hallez** [comment]
kiki51... J'ai bien peur que le PI Zéro ne corresponde pas à tes attentes... je ne vois pas de port ethernet... il n'est pas wifi non plus... il te faut rajouter une clef wifi en usb... au final ca coûte plus cher la sauce que le poisson non ? Comment vas-tu t'y prendre ? (si tu l'as commandé sur Amazon tu peux le renvoyer gratuitement... )

**Comment by Jean-Bernard-Hallez** [comment]
Pour l'esclave, oui effectivement, je l'ai installé sur un Raspian PI3 pour être en wifi (moins de cable) + Jarvis + le plugin-esclave + Micro Jabra400 
Sur le maitre il ne faut pas installer ce plugin mais jarvis-API.
Les deux plugins sont à mettre à la fin de tous les plugins.

**Comment by kiki51** [comment]
Avec ceci :
http://www.journaldulapin.com/2016/01/21/raspberry-pi-zero-google/

Au final on est pas loin du prix d'un pi2.... C'est plus pour la conso.

**Comment by Erim32** [comment]
Salut,  je profite que tu évoque ton setup,  pour le système maître esclave pour te demander le son qui provient d'une requête d'un esclave est il rédigé vers cet esclave ?  Si oui quel enceinte utilise tu personnellement ?

**Comment by Jean-Bernard-Hallez** [comment]
dans le config.sh je pose la question si on souhaite que le son soit répercuté sur le maitre (il est dans ma salle à manger).... personnellement le met met en mutting=true afin d'avoir le retour de son sur l'Esclave qui est dans la pièce ou je lance Jarvis (esclave dans une chambre). J'utilise le Micro JABRA400 car il y a le micro+hp incorporé et le tout sur 1 port USB. Le son est franchement super top !!!! le micro réponds super bien aussi, je n'ai pas besoin de parler prêt... (Je ne savais pas que l'on pouvait passer par un adaptateur pour récupérer l'ethernet !!! Excellent... mais je vais rester sur mon PI3 car mon objectif futur est la reconnaissance facial.. je ne suis pas passez fort en informatique pour cela... mais ca approche sur le Jarvis à grand pas d'après les tickets).

**Comment by Dom420** [comment]
Salut tt le monde!

Et si par exemple on part sur une maison neuve avec des micros encastrés comme celui la:
http://www.canford.fr/CANFORD-MICROPHONE-De-surface-a-encastrer

Vous en pensez quoi?

**Comment by wikijm** [comment]
@kiki51 As-tu trouvé les réponses que tu attendais ?

N'ayant pas d'activité depuis le 12 Février 2017, je clôture l'issue.
Si évolution, ne pas hésiter à la ré-ouvrir 😉

**Comment by kiki51** [comment]
Autant pour moi. J'aurais pu donner des News. 
Je ne me suis pas repenché sur le sujet par faute de temps mais je vais partir sur la solution de jarvis  esclave dans chaque pièces à domotiser.

**Comment by wikijm** [comment]
OK, merci du retour 😃

**Comment by Dom420** [comment]
Alors tu avancé sur ton projet kiki51? car ça m'interresse.


Avec un seul raspberry et plusieurs micro dans différentes pièces, si je mets cette carte son externe usb vers jack 3mm:
https://www.amazon.fr/UGREEN-Externe-Adaptateur-Portable-Rasperry/dp/B016CU2PEU/ref=sr_1_1_sspa?ie=UTF8&qid=1512674594&sr=8-1-spons&keywords=Prise+Jack+Usb&psc=1

Sera il possible de capturer simultanément le discours de différentes pièces sous forme de texte?

**Comment by kiki51** [comment]
Salut

Malheureusement je n'ai pas pu faire avancer mon jarvis...
Je pense que je vais partir sur la solution multi esclave maître avec plusieurs pieuvre micro haut parleur de type jabra

**Comment by Oliv4945** [comment]
Salut,

Espressif va faire une carte très intéressant pour ça !! [voir ici](https://twitter.com/EspressifSystem/status/952152302781046785?s=09).
Le microcontroleur sait faire de la reconnaissance de hotword et streamer l'audio, en plus ils font un mic array !!!!

**Comment by yoh0O** [comment]
Bonsoir,
Une petite question: pour justement pouvoir utiliser jarvis depuis n'importe quelle pièces (donc avec plusieurs micro) et simultanément (par exemple, l'utilisateur 1 n'a pas besoin d'attendre que l'utilisateur 2 finisse de donner son ordre, pour lui donner le sien), est-il possible de faire tourner plusieurs instance du jarvis service sur le même raspberry pi ? De cette manière, lors du set-up de chacun des jarvis, on spécifie le device de la carte son (limité à 10 par carte son sur le raspberry si je me trompe pas) en fonction de la pièce.
Est-ce possible ? et si oui, niveau ressources CPU c'est gourmand ou pas ?

Merci,
bonne soirée :)
