### ISSUE TITLE
orange pi lite

### ISSUE THREAD

**Issue by parrain27** [alexylem/jarvis#286]
bonsoir alex serait t'il possible d'installer jarvis sur orange pi lite vu le prix 
et de faire un plugin un peut a la jeedom un jarvis maître et des jarvis esclave 
genre le jarvis maître reçois la commande dit a sarah de descendre et il lance la parole sarah descend sur le jarvis dans la chambre de sarah pas sur les autre je sais pas si je m'exprime bien mais je pense que tu va comprendre ma demande

**Comment by alexylem** [comment]
@parrain27 J'ai vite fait regardé [Orange Pi Lite](http://orangepi.com/orange-pi-lite). A priori il peut tourner sur une image the Raspberry Pi donc pas de problème pour installer Jarvis.
Après faire parler une autre instance distante de Jarvis, ca aucun problème, tu peux déjà le faire en installant sur le Jarvis distant le plugin Jarvis-API:
```
DIS*SARAH (*)==say "Ok"; curl -s "http://ip_rpi_chambre_sarah:8080/?say=(1)"
```

**Comment by kiki51** [comment]
Bonjour,
j'ai une petite question.
Est ce que jarvis peux tourner sur une carte orange pi zero?
car vu le prix, comparé au raspberry c'est plutot pas mal.
Merci

**Comment by kiki51** [comment]
petite rectification, la orange pi one serait plus appropriée et pas enormément plus cher.
A ce prix, on a de l'ethernet, deux usb, et raspian de compatible!
