### ISSUE TITLE
Oreillette bluetooth

### ISSUE THREAD

**Issue by tchoul** [alexylem/jarvis#287]
Salut à tous,

Je me demande, puisque le Raspberry Pi 3 à le bluetooth, si il est possible de communiquer avec Jarvis via une oreillette bluetooth? 

Ca pourrait nous permettre de commander vocalement et d'avoir un retour de Jarvis direct dans l'oreille, avec tout les avantages que celà implique.

Moins de problème de bruit ambiant (pour que Jarvis capte la voix mais aussi pour que les personnes aux allentours ne l'entendent pas), avoir accès à Jarvis partout (dans la limite de la portée), moins encombrant ( micro par ci par là, enceinte) et moins cher.

Vous en pensez quoi?

**Comment by alexylem** [comment]
Tout à fait d'accord. Le support du bluetooth est déjà discuté ici: #110
