### ISSUE TITLE
Vitesse de diction pour voix Voxygen

### ISSUE THREAD

**Issue by parrain27** [alexylem/jarvis#294]
Bonjour alex j'utilise la voix de loic ce qui ce reproche le mieux de la voix de jarvis ça marche très bien.
Mon siucis c'est la vitesse de diction qui et super rapide comment puis-je la ralentir un peu

**Comment by alexylem** [comment]
Je ne pense pas que cela soit possible ca on utilise la version web (la démo en fait) du moteur. As-tu essayé avec d'autres voix pour voir si elles sont plus lentes? Tu peux les tester toutes sur leur site.

**Comment by parrain27** [comment]
bah en voix homme ya pas grand chose

**Comment by alexylem** [comment]
Il y a un moyen pour lire les fichier mp3 plus lentement:
```shell
$> ls /tmp/
bonjour_alex.mp3
$> mpg123 -q -h 2 /tmp/bonjour_alex.mp3 # répète chaque frame 2 fois, 2 fois plus lent
```
Mais c'est pas très beau. Tu peux toujours essayer et me dire si ca passe...

**Comment by parrain27** [comment]
effectivement sa fait peur c'est bien moche tant pi je vais rester avec la voix féminine pour le moment
