### ISSUE TITLE
Display possible answers if within nested commands

### ISSUE THREAD

**Issue by alexylem** [alexylem/jarvis#295]
### Description

Created from #276
```shell
*CA VA*==say "Très bien et toi ça va?"
>*OUI*==say "ravi de l'entendre"
>*NON*==say "j'en suis navré"
```
Current scenario:
```shell
You: Ca va?
Jarvis: Très bien et toi ça va?
You: Quel heure est-il?
Jarvis: Je ne comprends pas Quel heure est-il?
You: Oui
Jarvis: Ravi de l'entendre
You: Quelle heure est-il?
Jarvis: Il est 15h00
```

Idea is to show available answers if within nested commands:
```shell
You: Ca va?
Jarvis: Très bien et toi ça va?
#     *OUI*           *NON*
You: Oui
Jarvis: Ravi de l'entendre
```

There could also be a spoken hint, such as repeating the question is not answered.

**Comment by Jean-Bernard-Hallez** [comment]
J'adore,  je pense que ça va te compliquer le truc... mais...  systématiquement c'est pas top car il n'y a plus de suspense....

Est-ce possible que cela apparaisse que si on c'est trompé 2 fois de réponses par exemple ?

**Comment by Crali** [comment]
Euh ben non, dans ce cas là autant créer un paramètre tout simplement pour choisir si on l'affiche ou non. Personnelement je trouve ça plutôt cool et j'ai pas forcément envie que ça apparaisse après erreur, mais plutôt directement ^^

**Comment by alexylem** [comment]
Oui et justement je pensais aussi utiliser le paramètre qui affiche les commandes possibles au démarrage. Il sera aussi possible de définir un mot clé pour afficher les commandes dans le cas ou ce paramètre est désactivé (par défaut ca serait "AIDE" ou "HELP")

**Comment by alexylem** [comment]
![image](https://cloud.githubusercontent.com/assets/11017174/21275843/ee461e3c-c3ce-11e6-9467-b7c75d42d70d.png)

**Comment by alexylem** [comment]
Je laisse ouvert pour rajouter le paramètre. Pour le moment c'est systématique.

**Comment by Jean-Bernard-Hallez** [comment]
J'adore...   ;-)

**Comment by alexylem** [comment]
![image](https://cloud.githubusercontent.com/assets/11017174/21466685/26561b1a-c9d3-11e6-94f5-c19c971d2dd8.png)

![image](https://cloud.githubusercontent.com/assets/11017174/21466688/4cd4057c-c9d3-11e6-8376-88d399342884.png)
