### ISSUE TITLE
Jarvis not working if launched from another directory

### ISSUE THREAD

**Issue by byackee** [alexylem/jarvis#296]
Bonjour,

Je développe le plugin progtv, avec ce plugin j'ai besoin de downloader un fichier zip et j'utilise jarvis-event. 
Pour que le cron fonctionne je suis obliger de renseigner le chemin absolu du style /opt/jarvis/plugins/ ...
je ne peux pas rendre l'installation automatique et l'utilisateur devra modifier le fichier jarvis-event manuellement

Existe t il une solution pour que le cron lance ma commande peut importe le repertoire d'installation?

Merci

**Comment by alexylem** [comment]
A quelle fréquence as-tu besoin de télécharger le zip?
N'est-t-il pas envisageable d'effectuer ce téléchargement au moment de la demande?

**Comment by alexylem** [comment]
Sinon je pense, au moment de l'installation, rajouter un lien symbolic vers Jarvis depuis `/usr/local/bin`. Ainsi depuis n'importe ou on pourra:
```
jarvis -s "bonjour"
```

**Comment by byackee** [comment]
C'est un fichier zip de plusieurs dixaine de Mo, je voulais le faire tous les jours à minuit car en plus je dois le dezipper. Si je le fais à chaque demande cela risque d'être trop long et de télécharger le fichier pour rien 😉
Mais du coup meme avec un lien symbolique je ne sais pas comment tagé le répertoire de destination du fichier zip.

Envisage tu de figer un répertoire lors de l'installation de jarvis?

**Comment by byackee** [comment]
Si je code le téléchargement dans une procédure dans le fichier fonction.sh je pourrais la lancer avec jarvis.sh -s "donwloadtv" v

**Comment by alexylem** [comment]
Ok donc il faut partir sur les events.

Donc partons du principe que je rajoute dans l'installation un lien un lien symbolic vers `path/to/jarvis.sh` depuis `/usr/local/bin`.

Malheureusement aujourd'hui les plugins ne contiennent pas *encore* d'events. Mais je pourrais rajouter ça avec un fichier `events` dans chaque plugin.
En attendant tu peux toujours durant l'installation le rajouter manuellement dans le fichier `events` de Jarvis (jamais testé):

**install.sh**
```shell
echo "@midnight jarvis -x \"telecharge le programme tv\"" >> "$DIR/jarvis-events"
crontab jarvis-events -i
```
`$DIR` est le répertoire de Jarvis (lorsqu'il est lancé). Je pense le renommer plus tard par `$jv_dir`.

Il te faudra donc une commande pour télécharger le programme. Mais tu peux aussi appeler directement une fonction de ton plugin.

**commands**
```shell
*TELECHARGE*PROGRAMME*TV*==jv_pg_tv_download
```

Si le fichier est volumineux, tu peux aussi directement le télécharger dans `/tmp/` ainsi pas de problème d'accès:

**functions.sh**
```shell
jv_pg_tv_download() {
    wget -O /tmp/jarvis_programme_tv.zip http://...
}
```

T'en penses quoi?

**Comment by byackee** [comment]
je vais essayer de faire ca merci :)

je te tiens au courant

**Comment by byackee** [comment]
lors de l'install il ne reconnait pas la variable $DIR 

Dans le fichier install.sh lorsque je fais:
`echo "$DIR/jarvis-events"` il m'affiche `/jarvis-events`

cette variable est elle active lors de l'installation d'un plugin?

**Comment by alexylem** [comment]
Tu installes bien en lançant Jarvis (via le store ou l'option `-p`) ?
Car si tu lances le fichier `install.sh` directement c'est normal que `$DIR` soit vide.

**Comment by byackee** [comment]
non je le lance par jarvis, je viens d'essayer avec l'option `-p` ca ne fonctionne pas non plus, on dirait que la variable `$DIR`n'est pas déclarée

**Comment by alexylem** [comment]
Si elle l'est au tout début de `jarvis.sh`:
```shell
# Move to Jarvis directory
DIR="$(cd -P "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$DIR" # needed now for git used in automatic update
```
Je teste de mon côté...

**Comment by alexylem** [comment]
En attendant tu peux le faire en relatif (`install.sh` est lancé depuis son propre répertoire):
```shell
pwd
cat ../../jarvis-events
```

**Comment by alexylem** [comment]
Tu peux aussi me coller l'URL de ton repo que je teste? car je ne peux pas simuler l'installation localement...

**Comment by byackee** [comment]
https://github.com/byackee/jarvis-progtv

je ne peux pas mettre le chemin relatif dans le cron car lorsque le cron se lance il part de la racine il me faut le chemin absolu mais dans une variable :)

**Comment by alexylem** [comment]
Pour cron je suis d'accord. Il faut que je fasse le lien symbolique vers Jarvis à l'installation. Et je t'ai aussi proposé de télécharger et extraire le zip dans /tmp/. Ca t'irait?

**Comment by byackee** [comment]
j'avais pas compris l'histoire du tmp :) je vais faire ca :)

Merci

**Comment by alexylem** [comment]
Je reproduis le pb de $DIR. J'investigue...

**Comment by byackee** [comment]
pour info j'ai testé sous mac un rpi, j'ai la meme chose mais du coup avec le tmp ce n'est pas urgent

**Comment by alexylem** [comment]
Bon en fait c'est parce j'exécute un sous script et non une fonction, et donc les variables globale parente ne sont pas disponibles. Comme je vais pas demander à tout le monde de changer leur plugins, je vais voir côté EXPORT (et vais en profiter pour la renommer).

**Comment by byackee** [comment]
cool merci de ta réactivité

**Comment by alexylem** [comment]
Mets à jour. Dans ton script d'installation il faut utiliser:
```shell
echo $jv_dir
```

**Comment by byackee** [comment]
parfait ca fonctionne, le téléchargement est fonctionnel

Un grand merci

**Comment by alexylem** [comment]
Il reste quand même le lien symbolique à faire non? (parce que on n'a pas tout le même path d'installation Jarvis, donc les events ne marcheront pas toujours).
Aussi ton script d'installation a planté chez moi car je suis sur Mac (tu devrais peut-être tester la platforme), ex:
```shell
if [[ "$platform" == "linux" ]]; then
    jv_install python-pyaudio python3-pyaudio libatlas-base-dev
elif [[ "$platform" == "osx" ]]; then
    jv_install portaudio
else
    dialog_msg "Unknown platform"
    return 1
fi
```
`jv_install` te permets de faire `sudo apt-get install` ou `brew install` en fonction de la plateforme (vérifie que les packages que tu installes sont dispo sur brew).

**Comment by byackee** [comment]
effectivement meme avec ce cron, ca ne fonctionne pas:
`sh /opt/jarvis/jarvis.sh -x "telecharge le programme tv"`

en manuel non plus car si je lance la commande a partir d'un autre repertoire que celui de jarvis ca ne fonctionne pas, extrait du shell lorsque cette commande est lancée

```
MacBook-de-vincent:Documents vincentfresnel$ ./jarvis/jarvis.sh -x "telecharge le programme tv"
./jarvis/jarvis.sh: line 39: utils/utils.sh: No such file or directory
./jarvis/jarvis.sh: line 40: utils/store.sh: No such file or directory
./jarvis/jarvis.sh: line 41: utils/update.sh: No such file or directory
./jarvis/jarvis.sh: line 408: jv_sanitize: command not found
./jarvis/jarvis.sh: line 406: jv_ga_send_hit: command not found
./jarvis/jarvis.sh: line 489: jv_plugins_order_rebuild: command not found
./jarvis/jarvis.sh: line 506: jv_sanitize: command not found
./jarvis/jarvis.sh: line 551: jv_debug: command not found
vincent: ^Cstt_engines/bing/main.sh: line 80: jv_spinner: command not found
?^Cstt_engines/bing/main.sh: line 80: jv_spinner: command not found
?^Cstt_engines/bing/main.sh: line 80: jv_spinner: command not found
?
^Cjarvis: Waiting to hear 'jarvis'
```

**Comment by alexylem** [comment]
Ca marchait avant. Je regarde tout de suite... désolé...

**Comment by alexylem** [comment]
Corrigé, tu peux mettre à jour et re-tester?

**Comment by Jean-Bernard-Hallez** [comment]
echo $jv_dir Ca  m'âide beaucoup !!!! J'avais le même problème  que j'ai contourné mais là super cool...  ;-)

**Comment by byackee** [comment]
c'est parfait alex, peut importe le repertoire dans lequel je suis la commande fonctionne.

Merci et bravo pour jarvis!!!

**Comment by byackee** [comment]
Salut alex

Pour ma part tu peux clore ce sujet 👍
