### ISSUE TITLE
Python acces variable config & plantage du print

### ISSUE THREAD

**Issue by fatoldsun00** [alexylem/jarvis#297]
Bonjour a tous,

Genial le travail que tu as fourni Alexandre ! 

Sinon, si quelqu'un peut m aider ? Je rencontre un soucis avec le bif print de python "./jarvis.sh: line 533: Neo: command not found" Neo etant le nom de mon premier bulbe hue ... 

D'autres pour acceder aux variable de config je dois les passer en param depuis  le fichier de command ou y a plus simple ?

Merci, 

Encore bravo pour le soft, propre, sobre, fonctionnel et une communauté a l'air de prendre :)

**Comment by alexylem** [comment]
Quelle variable de config veux-tu accéder? Config Jarvis ? Config Plugin ?
Tu peux nous coller l'extrait de ton fichier de commande qui plante?
Merci!

**Comment by fatoldsun00** [comment]
Quel rapidité.. Config plugin

Pour le fichier c 'est le py qui plante, voici l'extrait, l'erreur se produit juste apres un print :
`
def toggle_lights():
	lights = b.get_light_objects()
	on = False
	for light in lights:
		print(str(light.name))
		print(light.on)
		if light.on:
			on = True
			break
		print(light.on)
	if on:
		b.set_group(0,'on',False)
	else:
		b.set_light(['Neo','Salon','Salle de bain'],'on',True)

toggle_lights()`

**Comment by alexylem** [comment]
@fatoldsun00 tu rencontres un problème sur un plugin Jarvis que tu as installé ou c'est toi qui développe un nouveau plugin?

**Comment by fatoldsun00** [comment]
Moi qui développe un nouveau plugin :$

**Comment by alexylem** [comment]
Mmhhhh, moi dans mes scripts python, je ne mets pas de parenthèse:
```python
print variable1, variable2
```

**Comment by alexylem** [comment]
Par contre pour l'erreur côté Jarvis, faudrait que tu me colles la commande complète pour que je comprenne le problème. Côté Python, je t'invite à tester ton script manuellement avant de le lancer depuis Jarvis, pour éviter les fausses pistes 😄 
```shell
$> python mon_script.py
```

**Comment by fatoldsun00** [comment]
Sans parenthese j avais la meme erreur ^^. De plus Ca fonctionne si je passe directement par l interpreteur

```
pi@raspSalon:/home/jarvis $ python plugins/jarvis-hue/api/ligths.py
[<phue.Light object "Neo" at 0x76a532b0>, <phue.Light object "Salon" at 0x76a57b90>, <phue.Light object "Salle de bain" at 0x76a57bf0>]
Neo
False
False
Salon
False
False
Salle de bain
False
False
```
Mais ne t'embete pas, je cherche et quand je trouve je poste la solution... si  je comprends l'erreur

**Comment by alexylem** [comment]
Tu peux coller la ligne de ton fichier de commande stp? Ca vient surement de la

**Comment by fatoldsun00** [comment]
J ai tenté :

`*LUMIERE (*)== $(python ./plugins/jarvis-hue/api/ligths.py "(1)")`

et

`*LUMIERE (*)== $(python ./plugins/jarvis-hue/api/ligths.py "(1)")`

Mais

`*LUMIERE (*)== "$(python ./plugins/jarvis-hue/api/ligths.py "(1)")"`

fonctionne mieux... Dans la derniere version il ne plante plus au premier print... mais au dernier

Ici on vois qu'il boulce sur mes lampes

`./jarvis.sh: line 533: [<phue.Light object "Neo" at 0x76a2f250>, <phue.Light object "Salon" at 0x76a33b50>, <phue.Light object "Salle de bain" at 0x76a33bb0>]: command not found`

**Comment by fatoldsun00** [comment]
Bon, une erreur est levé mais le programme s'execute jusqu au bout d'apres mes lampes :)

Ne passe plus de temps la dessus, je cherche :)

Merci

**Comment by alexylem** [comment]
Il faut mettre la commande directement:
```
*LUMIERE (*)==python ./plugins/jarvis-hue/api/ligths.py "(1)"
```
Après je sais pas comment tu gère l'argument, mais tu peux t'inspirer de ce que j'ai fait avec le plugin home-control (retrouve l'appareil avec expression régulière):
https://github.com/alexylem/jarvis-home-control

**Comment by wikijm** [comment]
@fatoldsun00 Vu que tu travailles dessus, je clôture le ticket.
Si jamais tu avances, n'hésites pas à y intégrer tes trouvailles :-)
