### ISSUE TITLE
Use custom voice from pre-generated audio files on specific phrases

### ISSUE THREAD

**Issue by TheAlkaloid** [alexylem/jarvis#3]
Après avoir collecté plusieurs phrases (toujours en cours, il y a beaucoup à faire) du maître d’hôtel d'une sitcom (une nounou d'enfer), j'ai pensé qu'il pouvait être intéressant d’intégrer ces voix au concept de domotique ou du moins de reconnaissance vocal.

Quelques-unes de ses phrases possèdent des intonations légèrement différentes mais signifient quasiment la même choses (liste non exhaustive de la banque) : 
- Oui monsieur
- Bien sûr
- Mission accomplie
- C'est parti monsieur

Et encore il bien d'autre phrase assez intéressante dans le contexte. Je pense qu'il y a de quoi reconstituer des mots avec un minimum de traficotage de la bande sonore (ce dont je suis capable) mais les intonations du personnage sont vraiment intéressantes et diverses, je pense qu'il serait intéressant de garder les phrase "telle quelles sont"

Pour bien faire, comme vous l'avez supposez, un choix aléatoire de ces documents pourrait-être envisageable : 
- Si l'on attend une affirmation 
- Piocher dans le document associé 
- Et selectionner, aléatoirement entre "Oui monsieur001.wav" "Bien sur001.wav" "Mission accomplie001.wav" "C'est pari monsieur001.wav"
- lancer le son

Ce genre de chose peut-être envisageable. (Même si on peut customiser et donner un sens précis à chacune de ces phrases).

**Avantage quant à la sélection aléatoire :** 
- Si la liste est assez grande, nous ne somme pas gavé par la lassitude du programme, avec un large choix on a déjà un peu plus la sensation de communiquer.
- On ne peut que être surpris par sa réponse, ce qui est similaire au "piquant" des réflexions de Jarvis, dans le sens où on ne sait jamais ce qu'il va dire

**Désavantage ;**
- On perds plusieurs phrases pour 1 seule utilité, alors que ce n'est pas forcément/strictement les "même" signification (_stricto sensu_)
- Il faut implémenter une fonction d'aléatoire, je sais pas si c'est toujours évident, on se débrouille bien avec les fonctions qui joue avec la date et l'heure...

/// C'est la première fois que je publie sur GitHub, j'ai fais en quelque sorte une présentation du projet, je ne sais pas si c'est ce qu'il faut faire, j'imagine ça comme un cahier des charges ? ///

**Comment by alexylem** [comment]
Je vois 2 besoins principaux:
- Choix aléatoire d'une réponse parmi une liste
- Choix d'une voix custom depuis des fichiers sons

Pour le choix aléatoire, je dois revoir la structure des commandes, mais tu n'es pas le premier à le demander, ca va impacter tout le monde mais je vais le faire.
Pour la voix custom, c'est possible. J'utilise déjà pour Google API la mise en cache des phrases les plus utilisées. Sauf qu'elles sont identifiées par un identifiant unique généré. Si elles l'étaient par la phrase prononcée, les fichiers pourraient être overridés facilement (à condition qu'ils ne soit pas effacés au redémarrage du PI comme c'est le cas aujourd'hui).

**Comment by alexylem** [comment]
Non mais on peut chercher d'autres synthèses vocales.
Ma question est simple: souhaites-tu avoir exactement la même voix que dans la série, ou avoir plus de choix (voix masculine, etc...) ?

**Comment by TheAlkaloid** [comment]
Pour ce que je veux en faire ; j'ai besoin d'utiliser strictement la voix que j'ai a disposition via fichier audio. Pas besoin d'une autre synthèse vocale (pour moi).

C'est gentil d'y porter de l'interet

**Comment by alexylem** [comment]
@TheAlkaloid tu attends toujours ce développement?

**Comment by alexylem** [comment]
timeout
