### ISSUE TITLE
Arrêter Jarvis depuis ligne de commande

### ISSUE THREAD

**Issue by Jean-Bernard-Hallez** [alexylem/jarvis#300]
### Description

Bonjour je souhaite quand ca bug pouvoir relancer Jarvis au travers de DOMOTICZ.... avec un inter virtuel je peux le démarrer mais je ne peux pas l'arrêter....
Je souhaite une commande du type ./jarvis.sh -s pour le stopper... sans passer par le menu de jarvis...
 
Merci.... 
### Result
Quand par exemple il y a du monde au domicile le micro fait un peu n'importe quoi et ca bip sur le haut parleur constamment.... il se bloque sur une commande imbriqué et on ne  peux plus rien faire... il ne reconnais plus le mot Jarvis... 

./jarvis.sh -s

Javis: Au revoir et j'espère à bientôt...
```

**Comment by alexylem** [comment]
`-s` est déjà utilisé pour faire dire qqchose à Jarvis. J'y travaille...

**Comment by alexylem** [comment]
```
./jarvis.sh -q
```
