### ISSUE TITLE
pb micro depuis mise à jour v16.12.18 

### ISSUE THREAD

**Issue by denisit29** [alexylem/jarvis#303]
### Description

Bonjour,

Depuis la mise à jour de jarvis en v16.12.18, jarvis ne semble plus capable d'enregistrer des sons provenant de mon micro. Je n'ai eu aucun pb auparavant mais depuis cette màJ plus rien. Lorsque je tente de reconfigurer celui ci via le menu setting, audio , mic (hw:,), il reste figé au niveau de la lecture du son enregistré (obligé de killer le processus). 
J'ai testé mon micro via la commande et les paramètres : "arecord -D plughw:1,0 -f cd test.wav" (Signed 16 bit Little Endian, FrÃ©quence 44100 Hz, StÃ©rÃ©o). => OK
lorsque j'effectue simplement la commande arecord sans paramètres je n'ai pas d'enregistrement non plus. Je pense qu'il s'agit donc d'un pb de paramètre d'enregistrement (j'ai tenté de modifier jarvis en dur pour mettre ces parametres sans succès).

```

**Comment by alexylem** [comment]
Essayes de le paramétrer directement dans le fichier de config (depuis le dossier `jarvis/`):
```shell
echo "hw:1,0" > config/rec_hw
```
Puis relance Jarvis.

**Comment by denisit29** [comment]
Non pas mieux. Jarvis ne détecte aucune commande vocale. J'ai également tenté de reconfigurer le micro via l'interface mais il reste bloqué a la lecture du fichier jarvis-record.wav. Lorsqu'il je lance un autre terminal et je lance la lecture de ce fichier ( aplay jarvis-record.wav) cela débloque le menu de jarvis. La dernière MàJ concernait-elle le micro ?

**Comment by alexylem** [comment]
Aucun rapport avec la mise à jour, tu peux voir les fichiers modifiés ici:
https://github.com/alexylem/jarvis/commits/master
Je n'ai rien changé qui puisse impacter cela depuis des mois...
Tu faire:
```
cat config/rec_hw
cat ~/.asoundrc
./jarvis.sh -lv
```
Et me coller le résultat de tout ca?

PS: maintenant que tu parles de freeze, ca me fait penser à ca:
https://github.com/alexylem/jarvis/issues/117

**Comment by denisit29** [comment]
Voici le resultat des commandes:
~/jarvis $ cat config/rec_hw
hw:1,0

:~/jarvis $ cat ~/.asoundrc
pcm.!default {
  type asym
   playback.pcm {
     type plug
     slave.pcm "false"
   }
   capture.pcm {
     type plug
     slave.pcm "hw:1,0"
   }
}

~/jarvis $ ./jarvis.sh -lv

------------ Config ------------
jv_version           16.12.18
system               Linux 4.4.34-v7+ armv7l
os                   "Raspbian GNU/Linux 8 (jessie)"
language             fr_FR
play_hw              false
rec_hw               hw:1,0
speaker              Default
microphone           Logitech, Inc. HD Webcam C910
trigger_stt          pocketsphinx
command_stt          pocketsphinx
tts_engine           espeak
conversation_mode    true
--------------------------------

DEBUG: program_startup hook
User defined commands:
*AIDE*                  *BONJOUR*|*SALUT*       *COMMENT*APPELLE*
*MERCI*                 *AU REVOIR*|*BYE*       ANNULE*|TERMINE*
ENCORE*                 *TEST*                  *VERSION*
*REPETE (*) ET (*)      *CA VA*                 >*OUI*
>*NON*
denis: (listening...)
utils/timeout.sh 10 rec -V1 -q -r 16000 -c 1 -b 16 -e signed-integer --endian little jarvis-record.wav silence 1 0.1 1% 1 0.5 1% trim 0 10
DEBUG: speech duration was  (10 = 1 sec)
DEBUG: timeout, end of conversation

J'utilise en effet une version lite de raspbian et un rpi3 (je voulais éviter d'installer une interface graphique pour gagner de la place) mais bon si le pb vient de là je veux bien installer une version full.

**Comment by alexylem** [comment]
Tiens tiens, tu as le même problème que #291 (la durée de l'enregistrement audio n'est pas affichée)
Tu me confirmes que ca marchait avant?
Par contre:
```
trigger_stt          pocketsphinx
command_stt          pocketsphinx
```
T'es sûr que c'est une bonne idée 😄  ?

**Comment by denisit29** [comment]
Du coup j'ai réinstallé le Rpi3 avec une version full de raspbian. L'enregistrement du micro fonctionne normalement ( avec arecord) mais pour une raison que j'ignore je dois lancer aplay avec sudo sinon cela ne fonctionne pas avec l'utilisateur pi (il fait pourtant bien parti du groupe audio). j'ai créé un utilisateur (jarvis) et avec lui les commandes fonctionnent aplay et arecord normalement. J'ai donc utilisé cet utilisateur pour installer jarvis et tout fonctionne (avec svox et bing comme stt 😄 ).
Merci.
