### ISSUE TITLE
Unable to locate package

### ISSUE THREAD

**Issue by anktababa** [alexylem/jarvis#304]
### Description

Bonjour,
Je viens de faire une fresh install de Debian Jessie pour tester Jarvis. J'ai ajouté sudo pour que le script puisse fonctionner. Je parviens désormais à lancer le script mais cependant lors de son lancement j'ai un retour d'erreur qui me dit : 

```
nuc@Jessie:~/jarvis$ ./jarvis.sh
You must install missing dependencies before going further
curl: Not found
jq: Not found
sox: Not found
mpg123: Not found
alsamixer: Not found
aplay: Not found
arecord: Not found
Attempt to automatically install the above packages? [Y/n] y
Reading package lists... Done
Building dependency tree
Reading state information... Done
E: Unable to locate package alsamixer
E: Unable to locate package aplay
E: Unable to locate package arecord
```

J'ai ajouté à mon fichier source.list les repo suivants : 
```
deb http://ftp.us.debian.org/debian/ jessie main non-free contrib
deb-src http://ftp.us.debian.org/debian/ jessie main non-free contrib

deb http://security.debian.org/ jessie/updates main non-free contrib
deb-src http://security.debian.org/ jessie/updates main non-free contrib
```

J'ai vu que la distribution d'origine est Raspian, je n'ai plus de Rasp et souhaiterais utiliser Jarvis dans une VM sur mon Nuc (ESXI) j'ai donc choisi une Debian pour être au plus proche mais est-ce possible finalement ?

Merci d'avance.

Cdlt

**Comment by alexylem** [comment]
Avec Debian/Ubuntu tu pourrais y arriver, cependant tu ne pourras pas utiliser snowboy tel quel, il te faudra compiler la librairie toi même depuis les sources: #79

**Comment by anktababa** [comment]
Bonjour,
Merci pour ta réponse.
Le seul moyen pour avoir une installation qui ne soit pas trop complexe est d'utiliser Raspian et donc d'utiliser Raspberry c'est bien ça ?
Je pensais que c'était plus "simple" même sur une autre distrib.
Merci.

**Comment by alexylem** [comment]
Ca fonctionne sur la majorité des distributions. Pour faciliter l'installation et l'utilisation de snowboy le script d'installation va automatiquement chercher les librairies pré-compilées pour Raspberry Pi et OSX. 
Je viens de voir que Snowboy met désormais aussi à disposition la librairie pré-compilée pour Ubuntu (64 bits):
https://github.com/Kitt-AI/snowboy#precompiled-binaries-with-python-demo
![image](https://cloud.githubusercontent.com/assets/11017174/21368305/54d900f2-c702-11e6-8682-6d9eacee73e4.png)
Si tu es en mesure de le tester sur cette nouvelle plateforme, j'aimerais bien que tu m'en fasses part afin que j'adapt le script d'installation automatique.
Merci!

**Comment by anktababa** [comment]
Je vais regarder demain pour l'installation de snowboy alors.
Juste pour vérifier ma compréhension, en fait le script essai de télécharger les différents packages qu'il ne trouve pas sur ma debian car ces packages sont utiles pour compiler snowboy c'est bien ça ? Ou bien je dois quand même chercher ces packages et installer snowboy à l'aide du binary précompilé ?
Merci

**Comment by alexylem** [comment]
Les packages en question sont pour le core de Jarvis. Il te les faut quand même.
Ensuite dans le processus d'installation, lorsque tu choisiras Snowboy comme STT pour le hotword, il va tenter de l'installer (et ca va marcher) mais comme il utilisera la librairie pour raspberry pi, ben snowboy va planter (avec le message d'erreur cité dans #79 .

**Comment by wikijm** [comment]
Bonjour @anktababa,

As-tu pu essayer la solution proposée par @alexylem ?

**Comment by wikijm** [comment]
Pas de réponse à ma relance, je clôture l'issue. 
Ne pas hésiter à rouvrir en cas d'avancée.

**Comment by QuentinCG** [comment]
Désolé de déterrer ce sujet mais je voulais juste donner la solution à ce problème: 

J'ai eu le même problème sur un serveur sous Debian que @anktababa .

La solution qui marche de mon coté:
`sudo apt install alsa-utils`
