### ISSUE TITLE
Bug pour créer des alternatives dans les commandes imbriquées...

### ISSUE THREAD

**Issue by Jean-Bernard-Hallez** [alexylem/jarvis#305]
### Description

Il y a un bug lorsque l'on veut avoir  des alternatives dans les commandes imbriquées.
Si je dis ailleurs de la commande imbriqué une des options possible il me renvoie à elle:

Exemple dans commands:
*QUESTION*==say "Oui, que préfères-tu ?"
>*PAIN*|*BRIOCHE*|*CROISSANT*==say "Ok, tu aimes les viennoiseries..."
...
...

### Result
You: j'ai une question ?
Jarvis: Oui, que préfères-tu ?
You du pain
Jarvis: Ok, tu aimes les viennoiseries...

Mais si je ne suis pas dans la commande imbriquée et que je tape par exemple:
You: Tu vas bien ?
Jarvis: Oui
You: brioche
Jarvis :Ok, tu aimes les viennoiseries...

Alors qu'il devrait me dire Je ne comprends pas: brioche !!!

**Comment by alexylem** [comment]
Bien vu, c'est un bug, je corrige

**Comment by alexylem** [comment]
Voila c'est corrigé. Mettez à jour:
```shell
$> ./jarvis.sh -u
```
