### ISSUE TITLE
Je n'entends pas le début de la synthèse vocale

### ISSUE THREAD

**Issue by NanakiFire** [alexylem/jarvis#308]
Bonjour,

Tout d'abord je voulais dire bravo pour tout le boulot qui est accompli sur ce projet, ça fait vraiment avancer les choses dans le domaine de l'assistance vocale à porté de tous!

J'ai donc voulu m'y essayer mais je rencontre quelques difficultés à le faire fonctionner correctement.
J'arrive parfaitement à utiliser le mot-clé 'Jarvis' avec Snowboy, mais la commande dictée derrière n'est jamais reconnu (testé avec Bing ou autre). Voilà ce que j'ai en log : 

> Monsieur: (listening...)
utils/timeout.sh 10 rec -V1 -q -r 16000 -c 1 -b 16 -e signed-integer --endian little jarvis-record.wav silence 1 0.1 1% 1 0.5 1% trim 0 10
DEBUG: speech duration was 48 (10 = 1 sec)
DEBUG: too long for a command (max 4 secs), ignoring...
utils/timeout.sh 10 rec -V1 -q -r 16000 -c 1 -b 16 -e signed-integer --endian little jarvis-record.wav silence 1 0.1 1% 1 0.5 1% trim 0 10
DEBUG: speech duration was 05 (10 = 1 sec)
DEBUG: token missing or expired
DEBUG: json=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzY29wZSI6Imh0dHBzOi8vc3BlZWNoLnBsYXRmb3JtLmJpbmcuY29tIiwic3Vic2NyaXB0aW9uLWlkIjoiOTE1OTFlYzI5NmNlNDdmMmFjNjcwZWUxN2Q2YzI5NjgiLCJwcm9kdWN0LWlkIjoiQmluZy5TcGVlY2guUHJldmlldyIsImNvZ25pdGl2ZS1zZXJ2aWNlcy1lbmRwb2ludCI6Imh0dHBzOi8vYXBpLmNvZ25pdGl2ZS5taWNyb3NvZnQuY29tL2ludGVybmFsL3YxLjAvIiwiYXp1cmUtcmVzb3VyY2UtaWQiOiIiLCJpc3MiOiJ1cm46bXMuY29nbml0aXZlc2VydmljZXMiLCJhdWQiOiJ1cm46bXMuc3BlZWNoIiwiZXhwIjoxNDgyNDM4MDg2fQ.kg0sfirGpIQ7E5HJFMfac7niEhqNtzyZtGw4G6TiD-U
DEBUG: token will expire in 590 seconds
DEBUG: curl https://speech.platform.bing.com/recognize/query?version=3.0&requestid=69223743-1b97-4767-82d1-66b2787d3173&appid=D4D52672-91D7-4C74-8AD8-42B1D98141A5&format=json&locale=fr-FR&device.os=linux&scenarios=ulm&instanceid=E043E4FE-51EF-4B74-8133-B728C4FEA8AA&result.profanitymarkup=0
DEBUG: json={"version":"3.0","header":{"status":"error","properties":{"requestid":"3fd568a6-b060-4eb0-850a-c8e5c5dcc949","NOSPEECH":"1"}}}

De plus, je ne sais pas si c'est lié, mais j'entend toujours que la fin des réponse. Par exemple si je fais simplement : ./jarvis.sh -s "un deux trois quatre cinq six sept huit neuf dix"
Je vais entendre à partir du chiffre cinq.

J'ai peut être mal configuré quelque chose ?

>  ./jarvis.sh
------------ Config ------------
jv_version           16.12.21
system               Linux 4.4.34-v7+ armv7l
os                   "Raspbian GNU/Linux 8 (jessie)"
language             fr_FR
play_hw              false
rec_hw               false
speaker              Default
microphone           Default
trigger_stt          snowboy
command_stt          bing
tts_engine           svox_pico
conversation_mode    true
--------------------------------

> stt_engines/bing $ ./test.sh
cat: version.txt: No such file or directory
{"debug":"DEBUG: curl https://speech.platform.bing.com/recognize/query?version=3.0&requestid=3f311f8d-0712-42ce-bfae-012aec679777&appid=D4D52672-91D7-4C74-8AD8-42B1D98141A5&format=json&locale=en-US&device.os=osx&scenarios=ulm&instanceid=E043E4FE-51EF-4B74-8133-B728C4FEA8AA&result.profanitymarkup=0"},{"debug":"DEBUG: json={\"version\":\"3.0\",\"header\":{\"status\":\"success\",\"scenario\":\"ulm\",\"name\":\"hello\",\"lexical\":\"hello\",\"properties\":{\"requestid\":\"8383618a-767e-446e-9c85-0a0f0edfb9e8\",\"HIGHCONF\":\"1\"}},\"results\":[{\"scenario\":\"ulm\",\"name\":\"hello\",\"lexical\":\"hello\",\"confidence\":\"0.9443262\",\"properties\":{\"HIGHCONF\":\"1\"}}]}"}hello

Cordialement.

**Comment by alexylem** [comment]
Donc 2 problèmes:
* NOSPEECH avec Bing: voir #118 
* Tu n'entends que la fin de la synthèse vocale. Quel moteur / speaker utilises-tu?

**Comment by NanakiFire** [comment]
Je ne sais pas si c'est lié, mais quand je vais dans Settings>Audio>Sensitivity ou Volume j'ai l'erreur suivante : 
> invalid card index: s
try `alsamixer --help' for more information
ERROR: check above

Pour le moteur de synthèse vocal, j'ai essayé avec Svox Pico, Google et eSpeak, mais les trois ont cette même latence.

**Comment by alexylem** [comment]
Tu peux essayer avec Voxygen ou Google?

**Comment by fatoldsun00** [comment]
J avais ce soucis avec la sortie son en HDMI, je suis passé sur une carte son externe usb et plus de probleme

**Comment by NanakiFire** [comment]
J'ai essayé Voxygen, même résultat que Svox Pico, Google ou eSpeak.

Moi je suis avec une enceinte Bluetooth, ça pourrait être la cause de l'erreur dans les options sensibilité et volume ?

**Comment by alexylem** [comment]
Ah enceinte bluetooth... ça doit être ca.
Rien à voir avec sensibilité et volume.
Peux-tu partager avec nous comment tu as installé ton enceinte bluetooth? Il y a un ticket ou l'on essaie de regrouper les tutos qui marchent bien pour l'automatiser: #200 
D'ailleurs je pense que si tu essayes de jouer n'importe quel son depuis ton raspberry pi (avec `aplay`, `sox` ou `mpg123`) tu auras le même problème. A priori rien à voir avec Jarvis.

**Comment by mikagouzee** [comment]
Hello Alex, je me permets de continuer sur ce fil parce que mon problème est similaire. 
J'ai installé hier J.A.R.V.I.S. avec un certain contentement (deux heures de bidouillage, après plusieurs semaines à essayer de configurer JASPER, ça fait plaisir).

Mais lors des premiers tests, j'ai constaté le même genre d'erreur :
--Je n'entends pas le début de ce que me dit Jarvis (il doit dire "hello" au démarrage, c'est le setup de base que je n'ai pas modifié, j'entends juste "lo")
--Je pense qu'il entend mon trigger word, car il affiche "Yes?" à l'écran, mais je ne l'entends pas et sur la ligne suivante, bien qu'il y ait mon username, rien ne s'affiche, quoi que je puisse dire (/murmurer/crier) dans le micro...

J'utilise snowboy pour la reconnaissance des mots clefs et des commandes, et sVox pico pour la synthèse vocale. Je pense avoir suivi l'installation d'aussi près que possible mais j'ai peut être fait une erreur qqpart.

Une idée/un conseil?

**Comment by alexylem** [comment]
@mikagouzee pour ton première problème, essaye d'augmenter la sensibilité de ton micro. Si ca ne suffit pas, il faudra jouer avec les paramètres de sox pour baisser le seuil de détection de bruit #112 .
Pour ton 2ème problème, merci de créer un ticket avec une copie du terminal de Jarvis lancé en mode troubleshooting. Merci.
