### ISSUE TITLE
Bug entre UFt-8 et ANSI

### ISSUE THREAD

**Issue by Jean-Bernard-Hallez** [alexylem/jarvis#309]
### Description

Bonjour... Jarvis utilise l'encodage ANSI alors que le Raspberry et le PC eux sont sous l'encodage UFT-8
Peut-on remedier à cela ???
### Result
Lorsque je créer un plugin je suis obligé de jongler entre les deux formats pour corriger les erreurs avec les accents... j'utiliser WinSCP avec mon PC et les commande Shell Pour rattraper le Tir sur le Raspberry pi:
local -a =
C
C.UTF-8
fr_FR.utf8
POSIX

**Comment by alexylem** [comment]
Jarvis utilise l'encodage du système.
Sur l'OS (Raspbian par exemple), il faut installer et utiliser les locales en UTF-8.
Sur le miens:
```shell
$> pi@jarvis:~ $ locale
LANG=en_GB.UTF-8
LANGUAGE=
LC_CTYPE="en_GB.UTF-8"
LC_NUMERIC="en_GB.UTF-8"
LC_TIME="en_GB.UTF-8"
LC_COLLATE="en_GB.UTF-8"
LC_MONETARY="en_GB.UTF-8"
LC_MESSAGES="en_GB.UTF-8"
LC_PAPER="en_GB.UTF-8"
LC_NAME="en_GB.UTF-8"
LC_ADDRESS="en_GB.UTF-8"
LC_TELEPHONE="en_GB.UTF-8"
LC_MEASUREMENT="en_GB.UTF-8"
LC_IDENTIFICATION="en_GB.UTF-8"
LC_ALL=
```
