### ISSUE TITLE
Could not resolve host: github.com

### ISSUE THREAD

**Issue by jeedomclaude** [alexylem/jarvis#310]
Bonjour a tous
Ci dessous ,le message d'erreur pour la mise a jour de Jarvis
```
Up-to-date
Checking updates for jarvis-jeedom...
fatal: unable to access 'https://github.com/Jean-Bernard-Hallez/jarvis-math.git/': Could not resolve host: github.com
```

**Comment by alexylem** [comment]
Pb de connexion internet?
Le repo semble toujours la...
Peux-tu vérifier?
```shell
$> ping github.com
```

**Comment by jeedomclaude** [comment]
Bonjour Alex
Exact, j'ai reparamétré avec une IP fixe.
Problème résolu.
Bonne fête a tous
