### ISSUE TITLE
Mac OSx Card ID et Channel à l'install + Blue Micro

### ISSUE THREAD

**Issue by NiackBuster** [alexylem/jarvis#312]
Hello aux 2 macUsers que j'ai vu dans ces issues !

J'ai la snowBall de chez Blue, et je cherche l'ID de la carte et son channel... Vu que sur Mac OSx il n'existe arecord -list, j'ai sox mais qui ne me dit pas l'ID de la carte.
Donc je suis bloqué à l'install car il ne trouve pas le micro du macpro.

Une idée ?

++

**Comment by alexylem** [comment]
Salut à toi @NiackBuster. A priori tu n'as pas besoin d'entrer ces informations, car si ta carte est bien configurée dans OSX, les tests sonores et d'enregistrement devraient fonctionner du premier coup. Ce n'est pas le cas?
Vérifie dans Préférences Système > Son > Entrée
![image](https://cloud.githubusercontent.com/assets/11017174/21581336/a0c90e0a-d02e-11e6-8832-16a41ead96f6.png)

**Comment by NiackBuster** [comment]
Yes en fait j'ai fait #0 #0 ca à fonctionné :)
