### ISSUE TITLE
Variables config.sh non prises en charge (plugin jarvis-freebox)

### ISSUE THREAD

**Issue by wikijm** [alexylem/jarvis#315]
### Description

Repository : https://github.com/wikijm/jarvis-freeboxplayer

Les variables ci-dessous ont été définies dans le fichier [config.sh](https://github.com/wikijm/jarvis-freeboxplayer/blob/master/config.sh), mais ne sont pas prises en compte par les commandes présentes dans le fichier [fr/functions.sh](https://github.com/wikijm/jarvis-freeboxplayer/blob/master/fr/functions.sh).

Lorsque que les variables sont remplacées par des informations en dur, les commandes fonctionnent.
Les issues suivantes ont été crées dans le repository : 
[erreur avec plugin Freebox](https://github.com/wikijm/jarvis-freeboxplayer/issues/2)
[commande non reconnu ?](https://github.com/wikijm/jarvis-freeboxplayer/issues/4)

**Comment by alexylem** [comment]
J'ai répondu dans l'autre (tu m'avais mentionné du coup j'ai été notifié):
https://github.com/wikijm/jarvis-freeboxplayer/issues/4
