### ISSUE TITLE
speech duration was 00

### ISSUE THREAD

**Issue by clem2k** [alexylem/jarvis#316]
Salut,
Très bon travail avec Jarvis, je galère un peu depuis quelques temps et j'ai pas trouvé d'issue qui me corresponde, donc je tente ... 

Ma config : 
- R Pi2B+
- Jabra Speak 410 (tout est ok de ce coté là avec le fix)

Niveau setup Jarvis m'entend et je l'entends très bien dans le Wizard. 
J'ai essayé snowboy pour le STT mais j'ai pas réussi à le faire marcher, donc je suis passé par Bing qui a l'air d'aller plus loin, en troubleshoot le truc me dit que la durée est de 00
J'ai testé le fichier de test STT de Bing et ça m'a l'air plutot correct du coup je seche un peu, après j'ai ptet raté un truc ...

Et sinon bonnes fêtes ;-)
Clem

### Description

DEBUG: speech duration was 00 (10 = 1 sec)
DEBUG: too short for a trigger (min 0.2 max 1.5 sec), ignoring...

### Result
pi@raspberrypi:~/jarvis/stt_engines/bing $ ./test.sh
cat: version.txt: No such file or directory
{"debug":"DEBUG: token missing or expired"},{"debug":"DEBUG: json=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzY29wZSI6Imh0dHBzOi8vc3BlZWNoLnBsYXRmb3JtLmJpbmcuY29tIiwic3Vic2NyaXB0aW9uLWlkIjoiNjI3M2Y5M2VhYzRlNDZkOTlhNzM0MjY3NjdlMmQwYTIiLCJwcm9kdWN0LWlkIjoiQmluZy5TcGVlY2guUHJldmlldyIsImNvZ25pdGl2ZS1zZXJ2aWNlcy1lbmRwb2ludCI6Imh0dHBzOi8vYXBpLmNvZ25pdGl2ZS5taWNyb3NvZnQuY29tL2ludGVybmFsL3YxLjAvIiwiYXp1cmUtcmVzb3VyY2UtaWQiOiIiLCJpc3MiOiJ1cm46bXMuY29nbml0aXZlc2VydmljZXMiLCJhdWQiOiJ1cm46bXMuc3BlZWNoIiwiZXhwIjoxNDgzMTEyNTc4fQ._A7vPbSaVgBQXauJrim9BArwDlMeFijOJ89yUwIQGM4"},{"debug":"DEBUG: token will expire in 590 seconds"},{"debug":"DEBUG: curl https://speech.platform.bing.com/recognize/query?version=3.0&requestid=XXXXXXXXXXXXXXXXXXXXXXXXXXX&appid=XXXXXXXXXXXXXXXXXXXXXXXXXXX&format=json&locale=en-US&device.os=osx&scenarios=ulm&instanceid=XXXXXXXXXXXXXXXXXXXXXXXXXXX&result.profanitymarkup=0"},{"debug":"DEBUG: json={\"version\":\"3.0\",\"header\":{\"status\":\"success\",\"scenario\":\"ulm\",\"name\":\"hello\",\"lexical\":\"hello\",\"properties\":{\"requestid\":\"XXXXXXXXXXXXXXXXXXXXXXXXXXX\",\"HIGHCONF\":\"1\"}},\"results\":[{\"scenario\":\"ulm\",\"name\":\"hello\",\"lexical\":\"hello\",\"confidence\":\"0.9443262\",\"properties\":{\"HIGHCONF\":\"1\"}}]}"}hello

Mon ecran de config (moins mes tokens  que j'ai remplacé par des XXXXXXXXXXXXXXXXXXXXXXXXXXX)

  ┌────────────────────────────────┤ Jarvis ├────────────────────────────────┐
  │ Configuration > Voice recognition                                        │
  │                                                                          │
  │  Recognition of magic word (bing)                                        │
  │  Recognition of commands (bing)                                          │
  │  Snowboy sensitivity (0.5)                                               │
  │  Snowboy token (XXXXXXXXXXXXXXXXXXXXXXXXXXX)                │
  │  Snowboy train a hotword/command                                         │
  │  Bing key (XXXXXXXXXXXXXXXXXXXXXXXXXXX)                             │
  │  Wit key ()                                                              │
  │  PocketSphinx dictionary (stt_engines/pocketsphinx/jarvis-dictionary.di  │
  │  PocketSphinx language model (stt_engines/pocketsphinx/jarvis-languagem  │
  │  PocketSphinx logs (/dev/null)                                           │
  │                                                                          │
  │                                                                          │
  │                                                                          │
  │                                                                          │
  │                   <Ok>                       <Cancel>                    │
  │                                                                          │
  └──────────────────────────────────────────────────────────────────────────┘

**Comment by alexylem** [comment]
Tu peux s'il te plait faire l'essai plusieurs fois de suite et coller le résultat de la console en mode troubleshooting?
```shell
$> ./jarvis.sh -lv
```
* `-l` pour passer directement en mode écoute d'une commande (bypass du hotword)
* `-v` pour le mode troubleshooting

Pour vérifier que c'est bien toujours `00`. Mets-toi au calme, évite les bruits parasites.

**Comment by wikijm** [comment]
Pas de nouvelle de @clem2k depuis le 30 décembre 2016.
Je suppose donc que le problème est résolu.

Ne pas hésiter à ré-ouvrir le ticket d'incident pour y intégrer le résultat du mode troubleshooting si ce n'est pas le cas :-)
