### ISSUE TITLE
Bonjour j'ai un soucis avec le MagicWord beaucoup trop sensible et testé avec 2 micros.

### ISSUE THREAD

**Issue by Jean-Bernard-Hallez** [alexylem/jarvis#317]
### Description
Bonjour j'ai 2 raspberry pi3 équipés de Jarvis dans 2 pièces différentes... l'installation toute neuve avec un micro JABRA 410 et hotward "Jarvis" et aussi "coucou Jarvis"  et la première installation avec le micro Trixes et comme hotword "Héjolicoeur".

A chaque fois que l'on discute de tout est de rien il s'enclenche comme si j'avais prononcé le hotword...

Je ne sais plus quoi faire... j'ai essayé d'effacer le fichier hotword et de réenregistré un nom de 4 syllabes et même problème....

**Comment by alexylem** [comment]
Salut JB, plusieurs pistes:

1) Snowboy recommande d'utiliser des hotwords d'au moins 3 ou 4 syllabes. Donc Jarvis n'est pas recommandé, même si moi j'arrive à l'utiliser sans trop de faux positif.
2) Il te faut régler la sensibilité du hotword, par défaut il est sur 0.5 mais bcp d'utilisateurs le descendent à 0.4 voir 0.35. (dans Jarvis > Settings > Voice Reco > Snowboy sensitivity). Je pensais même changer la valeur par défaut à 0.4.
3) On parle sur un autre ticket d'utiliser l'API de snowboy pour continuellement améliorer son hotword. Voir #255 tu pourrais upvoter si ca t'intéresse.

**Comment by NiackBuster** [comment]
J'ai mis 0.4 avec le Jabra 510 et le mot clé "Jarvisse" ca passe pas mal perso...

**Comment by wikijm** [comment]
@NiackBuster Merci pour la partage de ton paramètre 👍 
Personnellement, j'ai laissé le paramétrage par défaut et ça fonctionne très bien jusqu'à 5m environ, mais dans un petit appartement.

@Jean-Bernard-Hallez Ton problème est toujours d'actualité ?

**Comment by NiackBuster** [comment]
En fait ca dépend surtout de la qualité du micro. Tu as pris lequel @wikijm  ?

**Comment by wikijm** [comment]
Le même que le tien, un JABRA 510.
D'un point de vue micro, c'est le même qu'un JABRA 410 avec lequel j'avais commencé à utiliser Jarvis, avec le même paramétrage.

**Comment by Jean-Bernard-Hallez** [comment]
Et coucou @wikijm... je sus super ravi de la qualité sonore du jabra410 ainsi que du micro qui en effet fonctionne à 5mètres... mon hotword est de 6 syllabes etjarvistuesla, ma sensibilité était à 0.35 mais le matin il fallait en avoir envie pour le reveiller... je suis donc remonter à 0.5... et quand il y a du monde dans la piece c'est toujours la quata....

**Comment by wikijm** [comment]
Euh ... j'ai du mal à comprendre.

A part le matin et quand tu as du monde, ça fonctionne bien ?

**Comment by Jean-Bernard-Hallez** [comment]
Oui ça fonctionne à merveille même le matin... c'est uniquement quand il y a du monde... sans même prononcer le mot magic de 6 syllabes il s'enclenche quand même et si je baisse le niveau de sensibilité ça marche mieux oui il s'enclenche moins souvent mais je dois super bien prononcer le mot magique.... c'est à dire que de mon lit il me faut gueuler pour qu'il s'enclenche lol

**Comment by Jean-Bernard-Hallez** [comment]
Oui ça fonctionne à merveille même le matin... c'est uniquement quand il y a du monde... sans même prononcer le mot magic de 6 syllabes il s'enclenche quand même et si je baisse le niveau de sensibilité ça marche mieux oui il s'enclenche moins souvent mais je dois super bien prononcer le mot magique.... c'est à dire que de mon lit il me faut gueuler pour qu'il s'enclenche lol

**Comment by wikijm** [comment]
@Jean-Bernard-Hallez Que fait-on de cette issue ?
Est ce qu'il y a du nouveau ?

**Comment by Jean-Bernard-Hallez** [comment]
Oups je clôture... j'ai toujours le même problème mais je suis le seul à me plaindre... lol   ca doit être de mon coté je ne sais pas où...

**Comment by alexylem** [comment]
Normalement avec les dernières évolutions mise en place sur snowboy (système de ticks) le hotword ne devrait plus de déclencher à tout va comme avant.

**Comment by wikijm** [comment]
Bonsoir @takouakh,

Je t'invite à créer une nouvelle issue pour ton problème, en fournissant les éléments demandés.
Cette issue ayant été clôturée, je me permets de supprimer ton message.

Cordialement,
@wikijm
