### ISSUE TITLE
Bing

### ISSUE THREAD

**Issue by fredericrefano** [alexylem/jarvis#318]
Bonjour,

La reconnaissance vocale ne fonctionne pas avec BING pouvez-vous m'aider

**Comment by fredericrefano** [comment]
Bonjour,

La reconnaissance vocale ne fonctionne pas avec BING pouvez-vous m'aider

**Comment by alexylem** [comment]
As-tu bien mis ta clé Bing dans les settings de Jarvis?
Peux-tu nous coller un copie de ton terminal avec Jarvis lancé en mode troubleshooting ca nous aidera, merci.

**Comment by wikijm** [comment]
Utilises-tu Bing ou Azure ?
Regarde le #272

**Comment by alexylem** [comment]
Perso je suis toujours sur Bing... tant que ca marche... @fredericrefano ?

**Comment by fredericrefano** [comment]
Bonjour,

Voici ce que j'ai

*pi@raspberrypi*:*~/jarvis $* ./jarvis.sh


------------ Config ------------

jv_version           16.12.24

system               Linux 4.4.38-v7+ armv7l

os                   "Raspbian GNU/Linux 8 (jessie)"

language             fr_FR

play_hw              hw:0,1

rec_hw               hw:1,0

speaker              ALSA

microphone           C-Media Electronics, Inc. Audio Adapter

trigger_stt          snowboy

command_stt          bing

tts_engine           google

conversation_mode    true

--------------------------------


DEBUG: program_startup hook

snowboy: Bonjour

User defined commands:

*AIDE* *BONJOUR*|*SALUT* *COMMENT*APPELLE*

*MERCI* *AU REVOIR*|*BYE* ANNULE*|TERMINE*

ENCORE* *TEST* *VERSION*

*REPETE (*) ET (*) *CA VA* >*OUI*

>*NON*

snowboy: Waiting to hear 'snowboy'

Fred: (listening...)

DEBUG: models=snowboy

ALSA lib confmisc.c:1286:(snd_func_refer) Unable to find definition
'cards.bcm2835.pcm.front.0:CARD=0'

ALSA lib conf.c:4259:(_snd_config_evaluate) function snd_func_refer
returned error: No such file or directory

ALSA lib conf.c:4738:(snd_config_expand) Evaluate error: No such file or
directory

ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM front

ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.rear

ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.center_lfe

ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.side

ALSA lib confmisc.c:1286:(snd_func_refer) Unable to find definition
'cards.bcm2835.pcm.surround51.0:CARD=0'

ALSA lib conf.c:4259:(_snd_config_evaluate) function snd_func_refer
returned error: No such file or directory

ALSA lib conf.c:4738:(snd_config_expand) Evaluate error: No such file or
directory

ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM surround21

ALSA lib confmisc.c:1286:(snd_func_refer) Unable to find definition
'cards.bcm2835.pcm.surround51.0:CARD=0'

ALSA lib conf.c:4259:(_snd_config_evaluate) function snd_func_refer
returned error: No such file or directory

ALSA lib conf.c:4738:(snd_config_expand) Evaluate error: No such file or
directory

ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM surround21

ALSA lib confmisc.c:1286:(snd_func_refer) Unable to find definition
'cards.bcm2835.pcm.surround40.0:CARD=0'

ALSA lib conf.c:4259:(_snd_config_evaluate) function snd_func_refer
returned error: No such file or directory

ALSA lib conf.c:4738:(snd_config_expand) Evaluate error: No such file or
directory

ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM surround40

ALSA lib confmisc.c:1286:(snd_func_refer) Unable to find definition
'cards.bcm2835.pcm.surround51.0:CARD=0'

ALSA lib conf.c:4259:(_snd_config_evaluate) function snd_func_refer
returned error: No such file or directory

ALSA lib conf.c:4738:(snd_config_expand) Evaluate error: No such file or
directory

ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM surround41

ALSA lib confmisc.c:1286:(snd_func_refer) Unable to find definition
'cards.bcm2835.pcm.surround51.0:CARD=0'

ALSA lib conf.c:4259:(_snd_config_evaluate) function snd_func_refer
returned error: No such file or directory

ALSA lib conf.c:4738:(snd_config_expand) Evaluate error: No such file or
directory

ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM surround50

ALSA lib confmisc.c:1286:(snd_func_refer) Unable to find definition
'cards.bcm2835.pcm.surround51.0:CARD=0'

ALSA lib conf.c:4259:(_snd_config_evaluate) function snd_func_refer
returned error: No such file or directory

ALSA lib conf.c:4738:(snd_config_expand) Evaluate error: No such file or
directory

ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM surround51

ALSA lib confmisc.c:1286:(snd_func_refer) Unable to find definition
'cards.bcm2835.pcm.surround71.0:CARD=0'

ALSA lib conf.c:4259:(_snd_config_evaluate) function snd_func_refer
returned error: No such file or directory

ALSA lib conf.c:4738:(snd_config_expand) Evaluate error: No such file or
directory

ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM surround71

ALSA lib confmisc.c:1286:(snd_func_refer) Unable to find definition
'cards.bcm2835.pcm.iec958.0:CARD=0,AES0=4,AES1=130,AES2=0,AES3=2'

ALSA lib conf.c:4259:(_snd_config_evaluate) function snd_func_refer
returned error: No such file or directory

ALSA lib conf.c:4738:(snd_config_expand) Evaluate error: No such file or
directory

ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM iec958

ALSA lib confmisc.c:1286:(snd_func_refer) Unable to find definition
'cards.bcm2835.pcm.iec958.0:CARD=0,AES0=4,AES1=130,AES2=0,AES3=2'

ALSA lib conf.c:4259:(_snd_config_evaluate) function snd_func_refer
returned error: No such file or directory

ALSA lib conf.c:4738:(snd_config_expand) Evaluate error: No such file or
directory

ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM spdif

ALSA lib confmisc.c:1286:(snd_func_refer) Unable to find definition
'cards.bcm2835.pcm.iec958.0:CARD=0,AES0=4,AES1=130,AES2=0,AES3=2'

ALSA lib conf.c:4259:(_snd_config_evaluate) function snd_func_refer
returned error: No such file or directory

ALSA lib conf.c:4738:(snd_config_expand) Evaluate error: No such file or
directory

ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM spdif

ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.hdmi

ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.hdmi

ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.modem

ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.modem

ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.phoneline

ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.phoneline

ALSA lib pulse.c:243:(pulse_connect) PulseAudio: Unable to connect:
Connection refused


ALSA lib pulse.c:243:(pulse_connect) PulseAudio: Unable to connect:
Connection refused


Cannot connect to server socket err = No such file or directory

Cannot connect to server request channel

jack server is not running or cannot be started

INFO:snowboy:Silence

INFO:snowboy:Silence

INFO:snowboy:Silence

INFO:snowboy:Silence

INFO:snowboy:Silence

INFO:snowboy:Silence

INFO:snowboy:Silence

INFO:snowboy:Silence

INFO:snowboy:Silence

INFO:snowboy:Silence

INFO:snowboy:Silence

INFO:snowboy:Silence

INFO:snowboy:Silence

INFO:snowboy:Silence

INFO:snowboy:Silence

INFO:snowboy:Silence

INFO:snowboy:Silence

INFO:snowboy:Silence

INFO:snowboy:Silence

INFO:snowboy:Silence

INFO:snowboy:Silence

INFO:snowboy:Silence

INFO:snowboy:Silence

INFO:snowboy:Silence

INFO:snowboy:Silence

INFO:snowboy:Silence

INFO:snowboy:Silence

INFO:snowboy:Silence

INFO:snowboy:Silence

INFO:snowboy:Silence

INFO:snowboy:Silence

INFO:snowboy:Silence

INFO:snowboy:Silence

INFO:snowboy:Silence

INFO:snowboy:Silence

INFO:snowboy:Silence

INFO:snowboy:Silence

INFO:snowboy:Silence

INFO:snowboy:Silence

INFO:snowboy:Silence

INFO:snowboy:Silence

INFO:snowboy:Silence

INFO:snowboy:Silence

INFO:snowboy:Silence

INFO:snowboy:Silence

INFO:snowboy:Silence

INFO:snowboy:Silence

INFO:snowboy:Silence

INFO:snowboy:Silence

INFO:snowboy:Silence

INFO:snowboy:Silence

INFO:snowboy:Silence

^XINFO:snowboy:Silence

INFO:snowboy:Silence

^X^CDEBUG: program exit handler

DEBUG: program_exit hook

*pi@raspberrypi*:*~/jarvis $*

Frédéric Refano
GSM : 0475/55-98-86


2017-01-03 19:09 GMT+01:00 Alexandre Mély <notifications@github.com>:

**Comment by alexylem** [comment]
La ce que tu as collé c'est juste Snowboy qui attend le hotword (ici dans ton cas "snowboy"). Il te faut donc dire "snowboy".

**Comment by fredericrefano** [comment]
Je sais mais lorsque je dis Snowboy, il ne reconnait pas son nom.
Je viens de mettre BING, il ne me reconnait pas non plus

voici

*pi@raspberrypi*:*~/jarvis $* ./jarvis.sh

utils/menu.sh: ligne 297: stt_sb_train : commande introuvable

snowboy: Bonjour

User defined commands:

*AIDE* *BONJOUR*|*SALUT* *COMMENT*APPELLE*

*MERCI* *AU REVOIR*|*BYE* ANNULE*|TERMINE*

ENCORE* *TEST* *VERSION*

*REPETE (*) ET (*) *CA VA* >*OUI*

>*NON*

snowboy: Waiting to hear 'snowboy'

Fred: ###^X^C*pi@raspberrypi*:*~/jarvis $* ./jarvis.sh

utils/menu.sh: ligne 297: stt_sb_train : commande introuvable

utils/menu.sh: ligne 297: stt_sb_train : commande introuvable


------------ Config ------------

jv_version           16.12.24

system               Linux 4.4.38-v7+ armv7l

os                   "Raspbian GNU/Linux 8 (jessie)"

language             fr_FR

play_hw              hw:0,1

rec_hw               hw:1,0

speaker              ALSA

microphone           C-Media Electronics, Inc. Audio Adapter

trigger_stt          bing

command_stt          bing

tts_engine           google

conversation_mode    true

--------------------------------


DEBUG: program_startup hook

snowboy: Bonjour

User defined commands:

*AIDE* *BONJOUR*|*SALUT* *COMMENT*APPELLE*

*MERCI* *AU REVOIR*|*BYE* ANNULE*|TERMINE*

ENCORE* *TEST* *VERSION*

*REPETE (*) ET (*) *CA VA* >*OUI*

>*NON*

snowboy: Waiting to hear 'snowboy'

Fred: (listening...)

 rec -V1 -q -r 16000 -c 1 -b 16 -e signed-integer --endian little
jarvis-record.wav silence 1 0.1 1% 1 0.5 1% trim 0 10

DEBUG: speech duration was 100 (10 = 1 sec)

DEBUG: too long for a trigger (min 0.5 max 1.5 sec), ignoring...

 rec -V1 -q -r 16000 -c 1 -b 16 -e signed-integer --endian little
jarvis-record.wav silence 1 0.1 1% 1 0.5 1% trim 0 10

DEBUG: speech duration was 100 (10 = 1 sec)

DEBUG: too long for a trigger (min 0.5 max 1.5 sec), ignoring...

 rec -V1 -q -r 16000 -c 1 -b 16 -e signed-integer --endian little
jarvis-record.wav silence 1 0.1 1% 1 0.5 1% trim 0 10



Frédéric Refano
GSM : 0475/55-98-86


2017-01-03 22:51 GMT+01:00 Alexandre Mély <notifications@github.com>:

**Comment by alexylem** [comment]
Tu as 2 problèmes:
```
utils/menu.sh: ligne 297: stt_sb_train : commande introuvable
```
* tu as le même message d'erreur en choisissant snowboy pour moteur pour la reconnaissance du mot clé?

et
```
DEBUG: too long for a trigger (min 0.5 max 1.5 sec), ignoring...
```
Pour cela, voir #33 et #135

**Comment by wikijm** [comment]
Pas de réponse de @fredericrefano depuis le 3 janvier 2017, je clôture pour nettoyer un peu les tickets.

Ne pas hésiter à le ré-ouvrir s'il y a du nouveau ;-)
