### ISSUE TITLE
Vitesse de lecture avec Jabra 510 Rpi3

### ISSUE THREAD

**Issue by NiackBuster** [alexylem/jarvis#319]
Hello,

J'ai un bug assez bizare:
Quand je fais passer le son par le HDMI (donc l'ampli) et que je fais :
./jarvis.sh -s "bonjour comment ca va"
La vitesse est bonne
En revanche si je passe par le 510 pour faire écouter le son, alors la vitesse de lecture est ........ x1000 ? On ne comprend vraiment rien.
Si je me mets en mode Troubleshooting, je m'entend parler en super accéléré.
Si je débranche le HDMI et que je reboot, idem.
Si je fais rec test.wav et que je le play , idem

Une piste ? :)
PS : les applaudissement sont toujours à la bonne vitesse dans toute conditions.

La sortie de aplay -L est: 

null
    Discard all samples (playback) or generate zero samples (capture)
pulse
    PulseAudio Sound Server
default
sysdefault:CARD=ALSA
    bcm2835 ALSA, bcm2835 ALSA
    Default Audio Device
dmix:CARD=ALSA,DEV=0
    bcm2835 ALSA, bcm2835 ALSA
    Direct sample mixing device
dmix:CARD=ALSA,DEV=1
    bcm2835 ALSA, bcm2835 IEC958/HDMI
    Direct sample mixing device
dsnoop:CARD=ALSA,DEV=0
    bcm2835 ALSA, bcm2835 ALSA
    Direct sample snooping device
dsnoop:CARD=ALSA,DEV=1
    bcm2835 ALSA, bcm2835 IEC958/HDMI
    Direct sample snooping device
hw:CARD=ALSA,DEV=0
    bcm2835 ALSA, bcm2835 ALSA
    Direct hardware device without any conversions
hw:CARD=ALSA,DEV=1
    bcm2835 ALSA, bcm2835 IEC958/HDMI
    Direct hardware device without any conversions
plughw:CARD=ALSA,DEV=0
    bcm2835 ALSA, bcm2835 ALSA
    Hardware device with all software conversions
plughw:CARD=ALSA,DEV=1
    bcm2835 ALSA, bcm2835 IEC958/HDMI
    Hardware device with all software conversions
sysdefault:CARD=USB
    Jabra SPEAK 510 USB, USB Audio
    Default Audio Device
front:CARD=USB,DEV=0
    Jabra SPEAK 510 USB, USB Audio
    Front speakers
surround21:CARD=USB,DEV=0
    Jabra SPEAK 510 USB, USB Audio
    2.1 Surround output to Front and Subwoofer speakers
surround40:CARD=USB,DEV=0
    Jabra SPEAK 510 USB, USB Audio
    4.0 Surround output to Front and Rear speakers
surround41:CARD=USB,DEV=0
    Jabra SPEAK 510 USB, USB Audio
    4.1 Surround output to Front, Rear and Subwoofer speakers
surround50:CARD=USB,DEV=0
    Jabra SPEAK 510 USB, USB Audio
    5.0 Surround output to Front, Center and Rear speakers
surround51:CARD=USB,DEV=0
    Jabra SPEAK 510 USB, USB Audio
    5.1 Surround output to Front, Center, Rear and Subwoofer speakers
surround71:CARD=USB,DEV=0
    Jabra SPEAK 510 USB, USB Audio
    7.1 Surround output to Front, Center, Side, Rear and Woofer speakers
iec958:CARD=USB,DEV=0
    Jabra SPEAK 510 USB, USB Audio
    IEC958 (S/PDIF) Digital Audio Output
dmix:CARD=USB,DEV=0
    Jabra SPEAK 510 USB, USB Audio
    Direct sample mixing device
dsnoop:CARD=USB,DEV=0
    Jabra SPEAK 510 USB, USB Audio
    Direct sample snooping device
hw:CARD=USB,DEV=0
    Jabra SPEAK 510 USB, USB Audio
    Direct hardware device without any conversions
plughw:CARD=USB,DEV=0
    Jabra SPEAK 510 USB, USB Audio
    Hardware device with all software conversions
pi@raspberrypi:~/jarvis/sounds $

**Comment by NiackBuster** [comment]
Ok dsl de l'issue, résolu tout seul après avoir trouvé (trop tard) l'issue [https://github.com/alexylem/jarvis/issues/65](url)

**Comment by Jean-Bernard-Hallez** [comment]
Bonjour j'ai exactement le même problème... tu as fait quoi pour résoudre le tien ??? Merci....

**Comment by NiackBuster** [comment]
J'ai mis la configuration suivante dans le .asoundrc :

pcm.jabbra {
type hw
card 1
device 0
rate 48000
}
pcm.!default {
type asym
playback.pcm {
type plug
slave.pcm "jabbra"
}
capture.pcm {
type plug
slave.pcm "hw:1,0"
}
}

**Comment by wikijm** [comment]
Il faut également modifier le fichier suivant, afin de lui mettre la valeur "jabbra" (uniquement) :
/home/pi/config/play_hw

Note : "jabbra" peut être remplacée par une autre valeur textuelle. Pour ma part, j'ai plutôt mis "jabra" 😄

**Comment by NiackBuster** [comment]
J'ai pas eu besoin Perso.
Il m'a fait écouter et j'ai mis #1 #0  ça marche direct


Le mar. 3 janv. 2017 à 15:31, PGP 2F93D5AF <notifications@github.com> a
écrit :

**Comment by Jean-Bernard-Hallez** [comment]
Bonjour après avoir recherché aussi j'ai fait ce test:
aplay -Dsysdefault -c 2 -f cd test.wav --> Ca m'a permis de voir en effet que le son sortait à la vitesse normal j'ai donc modifié mon fichier:
sudo pico ./.asoundrc
pcm.!sysdefault {
  type asym
   playback.pcm {
     type plug
     slave.pcm "hw:0,0"
   }
   capture.pcm {
     type plug
     slave.pcm "hw:0,0"
   }
}
Et ca a marché desuite....    Merci tout le monde....   ;-)
