### ISSUE TITLE
Crash lorsqu'il y a trop de bruit de fond

### ISSUE THREAD

**Issue by physicien** [alexylem/jarvis#32]
Depuis quelques jours, je suis confronté au problème suivant: lorsqu'il y a trop de bruit de fond, Jarvis crash tout simplement. Afin d'isoler le problème, j'ai expérimenté plusieurs situations (détecteur de mot clé, STT engine, avec ou sans bruit de fond et différentes intensités de bruit de fond) et bonne nouvelle, Snowboy fonctionne peu importe le bruit, il faut simplement augmenter le delta dB  s'il ne comprend pas (donc parler plus fort).
Le problème vient donc après la reconnaissance du hotword. Les messages d'erreurs semblent aussi confirmer que c'est à l'enregistrement du fichier `.wav` que survient le bug.

Pistes de solutions: 

- [Real-time background noise cancellation of Microphone](https://cubethethird.wordpress.com/2015/07/26/real-time-background-noise-cancellation-of-microphone-input-on-linux/) (en prenant des échantillons de bruits à une certaine fréquence)
- Solution [PulseAudio](https://www.reddit.com/r/linux/comments/2yqfqp/just_found_that_pulseaudio_have_noise/) avec plus de détails [ici](https://wiki.archlinux.org/index.php/PulseAudio/Troubleshooting#Enable_Echo.2FNoise-Cancelation)
- Implémentation manuelle d'un AGC? [Ref 1](http://www.ti.com/lit/wp/spraal1/spraal1.pdf), [Ref 2](http://www.ti.com/lit/wp/spraaj4/spraaj4.pdf)

![capture d ecran - 2016-07-05 - 14 06 58](https://cloud.githubusercontent.com/assets/19982063/16594807/17c37cb4-42ba-11e6-8379-827afd601e7a.png)

P.S.: La dernière solution est faisable, mais ça me prendrait un peu de temps.

**Comment by alexylem** [comment]
Quel micro utilises-tu? ca me fait penser à #12

**Comment by physicien** [comment]
Ouais, j'avais vu cette erreur aussi. J'utilise le micro de ma webcam _Logitech C920_.

**Comment by alexylem** [comment]
Je serai étonné que le micro se plante juste à cause du bruit de fond. Pourrais-tu tester sans bruit de fond? juste pour vérifier que tu ne rencontres pas le même problème à terme (avec utilisation similaire)

**Comment by physicien** [comment]
C'est vraiment spécial en effet. Je viens de test en coupant absolument tout bruit de fond (pas facile avec les travaux pas loin et à la chaleur qu'il fait, mes ventilateurs sont utiles, mais j'ai tout coupé). Je n'avais plus aucun problème et j'ai pu parler pendant plusieurs minutes sans aucun crash. En mode Troubleshooting, je n'ai jamais réussi à le faire crash, même avec un ventilateur au plafond. Pour ce qui est du mode normal, il arrive qu'il plante lorsque le ventilateur fonctionne, mais de façon générale c'est lorsque que j'ajoute plus de bruits qu'il crash.
J'ai fais quelques captures pour la forme.
![1](https://cloud.githubusercontent.com/assets/19982063/16596897/0a1b75f8-42c4-11e6-863c-3ce1f5be7dff.png)
![2](https://cloud.githubusercontent.com/assets/19982063/16596898/0a1f5218-42c4-11e6-8e10-a82215405f93.png)
![3](https://cloud.githubusercontent.com/assets/19982063/16596899/0a22f936-42c4-11e6-8f24-5056190ce154.png)
![4](https://cloud.githubusercontent.com/assets/19982063/16596900/0a29239c-42c4-11e6-8974-b83fdc42b8b5.png)
![5](https://cloud.githubusercontent.com/assets/19982063/16596901/0a32acaa-42c4-11e6-9fbf-a615211276d2.png)
![6](https://cloud.githubusercontent.com/assets/19982063/16596902/0a37765e-42c4-11e6-80a1-c106ccb89578.png)

**Comment by alexylem** [comment]
Il m'est arrivé la même chose hier:
```
Alex: jarvis
jarvis: Oui?
Alex: ?#?###?##########################################
rec FAIL formats: can't open input  `default': snd_pcm_open error: Device or resource busy
ERROR: rec command failed
HELP: Verify your mic in Settings > Audio > Mic
pi@jarvis:~/jarvis $ 
```

**Comment by physicien** [comment]
Alors, quelle est l'hypothèse pour le moment?

**Comment by alexylem** [comment]
Il se peut que le micro a besoin d'un peu plus de temps pour se releaser suite à la commande `rec` avec le module `silence` pour automatiquement stopper au bout de 10 secondes de bruit.  
Je vais essayer d'introduire un petit délai si bruit de fond détecter entre chaque tentatives pour que le micro ne soit pas trop sollicité.

**Comment by alexylem** [comment]
Je viens de mettre une mise à jour, @physicien peux-tu voir si tu arrives à reproduire le problème? Si oui merci de me ressortir une trace (pas besoin de mode troubleshooting).
Merci.

**Comment by physicien** [comment]
Là il ne comprend plus rien :laughing: 
![capture d ecran - 2016-07-14 - 14 34 16](https://cloud.githubusercontent.com/assets/19982063/16851103/0f0bd3a6-49d0-11e6-874a-3329b57d5477.png)

**Comment by alexylem** [comment]
Ça n'a rien à voir avec la modification que j'ai faite. Vérifie sensitivité
du micro et bruit de fond.

**Comment by physicien** [comment]
Tout semble beau pour le moment.

**Comment by alexylem** [comment]
Si c'est bon pour toi je ferme le ticket, merci de confirmer

**Comment by physicien** [comment]
Je confirme!

**Comment by physicien** [comment]
UPDATE: Ne sachant pas où écrire ça et ne voulant pas lancer une nouvelle _Issue_, j'update ce post pour faire une recommandation de micro. 
Je me suis récemment procuré le [Soundtech CM-1000USB](http://www.amazon.ca/dp/B008BS3CF8) et je le recommande chaudement. Étant un micro de conférence, il capte très bien à une distance de plusieurs mètres. 
De plus, étant 100% hardware, ce micro n'éprouve aucun problème de compatibilité, car il n'a besoin d'aucun software, firmware ou driver. Il suffit d'avoir un port USB et un mixer sur la machine. 
Finalement, le micro comporte certaines capacités de prétraitement du signal telles que le _echo cancellation, noise reduction and full duplex communication_. Ces modules étant 100% hardware, ils ne nécessitent aucun calcul de la machine, ce qui est un net avantage.

J'ajoute ici un résumé des specs:

- Micro omnidirectionnel stéréo;
- Échantillonnage audio de 48000 Hz;
- ~8.5 cm de diamètre et 1.5 cm d'épaisseur;
- Built-in echo cancellation, noise reduction and full duplex communication.

**Comment by alexylem** [comment]
Merci bcp pour ce retour, page des micros recommandés mise à jour:
https://github.com/alexylem/jarvis/wiki/prerequisites
