### ISSUE TITLE
Proposer des profils de matériel audio

### ISSUE THREAD

**Issue by wikijm** [alexylem/jarvis#320]
### Description

Plusieurs personnes rencontrent des difficultés à paramétrer convenablement :

- Un périphérique de sortie audio
- Un périphérique d'entrée audio
- Une sensibilité d'écoute
- ...

Je me demande s'il ne serait pas intéressant de créer un catalogue de périphérique, au même titre que le catalogue de plugins, afin de pré-paramétrer tous ces éléments de configuration.
Cela éviterait pas mal d'issues, comme on a pu en voir pour la matériel de la marque Jabra ou les faux-positifs de détection d'hotword (Exemple : #319 et #65).

**Comment by alexylem** [comment]
Déjà discuté ici: #226 et pourrait être résolu par #246

**Comment by wikijm** [comment]
C'est noté, merci d'avoir répondu :-)
