### ISSUE TITLE
Snowboy failure

### ISSUE THREAD

**Issue by actarus33** [alexylem/jarvis#324]
Hi everybody, happy new year!

I have some problems with snowboy. Snowboy randomly fail after hotword detection (often after the first launch) and jarvis stop unexpectedly. 
Latest version of jarvis used on a RASPB 3, jarvis is launched from web dashboard on the local machine. Does anybody is experiencing the same issue?

Bonjour tout le monde, bonne année!

J'ai des problemes avec snowboy. Il plante aléatoirement apres la detection du hotword (souvent juste apres le 1er lancement) et le process jarvis s'arrete alors... obligé de le relancer.
J'utilise un raspb 3 avec la derniere version de jarvis avec bcp de choses qui tourne dessus (ecran tactile, micro jabra 510, rfxcom 433e, emetteur IR, domoticz). J'ai codé un dashbord html5 javascript/php pour afficher des infos de la maison et lancer des commandes en tactile et lancer jarvis depiis cette interface web. Tout fonctionne tres bien hormis snowboy qui du coup n'est pas fiable... ce qui n'est pas fiable est alors difficilement utilisable.
Quelqu'un rencontre t'il ce probleme?

**Comment by alexylem** [comment]
Tu peux partager avec nous une copie de ton terminal avec Jarvis lancé en mode troubleshooting pour mieux comprendre ce qu'il se passe? Merci.

**Comment by wikijm** [comment]
@actarus33 Je suis à peu de chose près dans le même cas que toi (Écran tactile Waveshare 7" capacitif LCD HDMI 800*480 + JABRA 510).

Peux-tu être plus précis dans ce que tu appelle 'pas fiable' ? As-tu pu récupérer les résultats du mode troubleshooting ?
Donne-moi quelques exemples de ce que tu fais et j'essaierai de les reproduire (tu peux également faire une démo avec https://asciinema.org/ ou [ScreenToGIF](http://www.screentogif.com/)).

P.S  : Ça serait super si tu pouvais partager ton dashbord html5 javascript/php, c'est ce que je cherche à utiliser ;-)

**Comment by wikijm** [comment]
Pas de nouvelle depuis le 3 janvier 2017, j'imagine que l'incident est résolu depuis.

Ne pas hésiter à ré-ouvrir le ticket et nous transmettre les résultats du mode troubleshooting et/ou captures faites avec asciinema/ScreenToGIF si ce n'est pas le cas.
