### ISSUE TITLE
permission non arccordée

### ISSUE THREAD

**Issue by ledarvite** [alexylem/jarvis#326]
utils/update.sh: ligne 18: config/version: Permission non accordée
touch: impossible de faire un touch 'config/last_update_check': Permission non accordée

**Comment by ledarvite** [comment]
utils/update.sh: ligne 18: config/version: Permission non accordée
touch: impossible de faire un touch 'config/last_update_check': Permission non accordée

**Comment by alexylem** [comment]
Mmmmh, tu as installé Jarvis ou?
Tu as bien fait git clone sans sudo et jamais utilisé Jarvis avec sudo?
Si ton utilisateur est `pi` et Jarvis installé dans le répertoire utilisateur, je te conseille:
```
chown pi:pi -R ~/jarvis
```

**Comment by ledarvite** [comment]
merci de ta réponse il faut pas utiliser suis pour l installation
Ça marche nickel
