### ISSUE TITLE
Audio group re-login + tar (child): bzip2 : exec impossible: Aucun fichier ou dossier de ce type

### ISSUE THREAD

**Issue by Lins59** [alexylem/jarvis#327]
Bonjour,

Après l'ajout au groupe audio fait par le script d'installation, il faut déloguer et reloguer l'utilisateur pour recharger ses droits ... Sinon, impossible de lire les cartes sons.

Deuxième problème un peu plus loin :

Sauvegarde en : « rpi-arm-raspbian-8.0-1.0.2.tar.bz2 »

rpi-arm-raspbian-8.0-1.0.2.t 100%[===============================================>]   1,52M   102KB/s   ds 23s

2017-01-04 19:07:04 (67,8 KB/s) — « rpi-arm-raspbian-8.0-1.0.2.tar.bz2 » sauvegardé [1594126/1594126]

tar (child): bzip2 : exec impossible: Aucun fichier ou dossier de ce type

Il faut installer préalablement le paquet bzip2 ;)
Cdlt

**Comment by alexylem** [comment]
Merci bcp @Lins59 ca va m'être très utile pour améliorer les scripts d'installation de Jarvis et Snowboy.
