### ISSUE TITLE
Gestion du gain du micro dans sox et snowboy

### ISSUE THREAD

**Issue by oeildefeu** [alexylem/jarvis#328]
Salut,
j'utilise Jarvis avec un kinect 1 et le souci du Kinect est qu'on ne peut pas ajuster le gain "facilement" (apparemment en trifouillant la asoundrc ça semble possible mais je n'y arrive pas !)
Du coup, j'ai trouvé 2 solutions qui pourraient être facilement (normalement) implémentables dans Jarvis:
1- ajouter "gain +XX" dans la commande rec, avec +xx étant une variable de config ce qui donne ceci
jarvis-functions.sh
`local cmd="$timeout rec -V1 -q -r 16000 -c 1 -b 16 -e signed-integer --endian little $1 gain +22 silence 1 $min_noise_duration_to_start $min_noise_perc_to_start 1 $min_silence_duration_to_stop $min_silence_level_to_stop trim 0 $max_noise_duration_to_kill"`

2 - ajouter le gain dans decoder snowboy dans le main.py

Merci :)

**Comment by oeildefeu** [comment]
Il semble, d'après la documentation que oui! Pas testé par contre... Mais y'a pas de raison

**Comment by Qweetttuu** [comment]
Bonjour, je suis nouveau. Jarvis détecte le micro Kinect. J'essai d'augmenter le grain de celui-ci. Pouvez vous me détailler comment ajouter le gain dans decoder snowboy dans le main.py? merci

**Comment by Qweetttuu** [comment]
Merci pour l'astuce

**Comment by alexylem** [comment]
Le gain est désormais géré dans Sox.
Vous pouvez le paramétrer automatiquement, voir #246.
