### ISSUE TITLE
failed to connect to snowboy.kitt.ai port 443 : Network is unreachable

### ISSUE THREAD

**Issue by sbnair** [alexylem/jarvis#329]
Hi

After installing jarvis i choose snowboy and added the token of my profile in snowboy and trainned a hotword in web and added the same hotword to train here, jarvis was asking three sample questions to say the hotword and press ctrl + c, after the third time i am getting this message :

    Aborted
    Training model...
    curl : (7) Failed to connect to snowboy.kitt.ai port 443 : Network is unreachable
    cat: /tmp/model.pmdl: No such file or directory
    Error : error occured while training the model. 

Please help me in this, is der any settings in jasper to solve 443 port issue, i am using dongle and internet connection is available in raspberry pi 3.

Thanks,
sbnair.

**Comment by alexylem** [comment]
You have a local network issue. Please check your router/proxy configuration.

**Comment by wikijm** [comment]
@sbnair Is it still happening?
If not, please close the ticket :-)

**Comment by wikijm** [comment]
No answer of the issue creator since 5 Jan 2017 => Issue closed.
Don't hesitate to reopen the issue if there is some evolution.
