### ISSUE TITLE
jarvis ne prends pas en compte l'intégralité de ma commande sur jabra 410

### ISSUE THREAD

**Issue by Sellig28** [alexylem/jarvis#330]
J'essai de trouver le réglage optimal mais ce n'est pas simple du tout. Vivement que beaucoup d'autres utilisateurs fassent des retours !

Le symptome est le suivant, en troubleshooting, ma commande est bien retrounée sur le haut parleur et en entier alors que jarvis ne la comprend pas en entier.

exemple:

Je demande:  "qu'elle est la température extérieure"

il prends en compte "qu'elle est la température"

```
gilles: (listening...)
utils/timeout.sh 10 rec -V1 -q -r 16000 -c 1 -b 16 -e signed-integer --endian little jarvis-record.wav silence 1 0.2 0.4% 1 0.85 2% trim 0 10
DEBUG: speech duration was 18 (10 = 1 sec)
DEBUG: curl https://speech.platform.bing.com/recognize/query?version=3.0&requestid=edf22beb-90fe-4dce-ab81-31864d802004&appid=D4D52672-91D7-4C74-8AD8-42B1D98141A5&format=json&locale=fr-FR&device.os=linux&scenarios=ulm&instanceid=E043E4FE-51EF-4B74-8133-B728C4FEA8AA&result.profanitymarkup=0
DEBUG: json={"version":"3.0","header":{"status":"error","properties":{"requestid":"4b84022f-0b07-4b39-947f-caeb85879ad7","FALSERECO":"1"}}}
?(listening...)
utils/timeout.sh 10 rec -V1 -q -r 16000 -c 1 -b 16 -e signed-integer --endian little jarvis-record.wav silence 1 0.2 0.4% 1 0.85 2% trim 0 10
DEBUG: speech duration was 15 (10 = 1 sec)
DEBUG: curl https://speech.platform.bing.com/recognize/query?version=3.0&requestid=68831a45-04e8-48df-bc85-cedcc96c75a1&appid=D4D52672-91D7-4C74-8AD8-42B1D98141A5&format=json&locale=fr-FR&device.os=linux&scenarios=ulm&instanceid=E043E4FE-51EF-4B74-8133-B728C4FEA8AA&result.profanitymarkup=0
DEBUG: json={"version":"3.0","header":{"status":"success","scenario":"ulm","name":"quelle est la température","lexical":"quelle est la température","properties":{"requestid":"a206a097-0ec1-4114-b57c-5fbd737d81f3","HIGHCONF":"1"}},"results":[{"scenario":"ulm","name":"quelle est la température","lexical":"quelle est la température","confidence":"0.7140934","properties":{"HIGHCONF":"1"}}]}
quelle est la température
jarvis: Je n ai pas compris !: quelle est la température
gilles: (listening...)
utils/timeout.sh 10 rec -V1 -q -r 16000 -c 1 -b 16 -e signed-integer --endian little jarvis-record.wav silence 1 0.2 0.4% 1 0.85 2% trim 0 10
```
J'avoue que les réglages sont un peu obscur pour moi, même si après réglage on comprend mieux l'effet réalisé.

mes nouveaux réglages sont:

sensitivity: 71
Min noise duration to start: 0.2
Min noise perc to start: 0.4%
Min silence duration to stop : 0.85
Min silence level  to stop: 2%
Max noise duration to kill: 10

Si quelqu'un à une idée, je suis preneur.

Merci.

**Comment by alexylem** [comment]
Les réglages micro sont discutés ici: #226

**Comment by Sellig28** [comment]
ok grand chef, merci.

**Comment by kiki51** [comment]
Salut Sellig28,
Je voudrais juste savoir quel réglages definitifs tu as adopter pour eviter ce problème?
Je rencontre le meme soucis avec le meme micro et je galere pas mal.

Merci

**Comment by Jean-Bernard-Hallez** [comment]
Bonjour après avoir recherché aussi j'ai fait ce test:
aplay -Dsysdefault -c 2 -f cd test.wav --> Ca m'a permis de voir en effet que le son sortait à la vitesse normal j'ai donc modifié mon fichier:
sudo pico ./.asoundrc
pcm.!sysdefault {
type asym
playback.pcm {
type plug
slave.pcm "hw:0,0"
}
capture.pcm {
type plug
slave.pcm "hw:0,0"
}
}
Et ca a marché desuite.... Merci tout le monde.... ;-)
