### ISSUE TITLE
iOS App: Parse JSON array response

### ISSUE THREAD

**Issue by barbapapa021** [alexylem/jarvis#332]
Bravo pour ce project !! Il est très bien conçu.
J'essaye de créer un application IOS pour faire comme google now ... mais je me prends la tête.
Mon problème est le suivant:
Je n'arrive pas lire la réponse du webservice en JSON. Mon code fonctionne très bien avec un autre webservice mais pas Jarvis.
Avez-vous une idée ?
guard let json = try JSONSerialization.jsonObject(with: data, options: []) as? NSDictionary else {
throw JSONError.ConversionFailed}

Fonctionne très bien avec ce webservice "https://httpbin.org/ip"

J'ai une idée du problème:
Javis retour ces informations [{"jarvis": "Bonjour"}]
Mais l'autre web service {
"origin": "83.79.30.120"
}
Dans safari. Je démarre Jarvis avec la commende -J mais es-ce que je dois faire autre chose pour que l'API retourne le bon format.

Merci de votre aide je débute avec JSON

**Comment by alexylem** [comment]
C'est parce que Jarvis ne retourne pas un objet JSON
```json
{"property":"value"}
```
mais une liste (ou tableau) d'objets JSON
```json
[{"property":"value1"},{"property":"value2"},...]
```
C'est bien du JSON valide:
![image](https://cloud.githubusercontent.com/assets/11017174/21727578/49a76ca8-d442-11e6-8f50-a99f1ab94558.png)
A mon avis tu dois juste te renseigner sur comment parser un tableau JSON dans ton language de programmation. Moi j'y arrive très bien en Jarvascript (jQuery) pour le plugin Jarvis-UI.
Ca n'a rien à voir avec Jarvis, mais je laisse le ticket ouvert au cas où quelqu'un puisse t'aider.

PS: j'ai en tête dans le cadre de Jarvis-UI d'intégrer la reconnaissance vocale directement sur la page web (et d'en faire une webApp). Ainsi on pourra l'utiliser sur iOS.

**Comment by barbapapa021** [comment]
Merci beaucoup pour ton aide. C'était effectivement très simple je devais
juste changer le type en Array:

guard let json = try JSONSerialization.jsonObject(with: data, options: [])
as? Array<Any> else


Je fini mon prototype est je l'ajoute dans ce poste

Le 6 janvier 2017 à 19:01, Alexandre Mély <notifications@github.com> a
écrit :

**Comment by alexylem** [comment]
Ok merci!
