### ISSUE TITLE
Can Jarvis run OFF_line? and PulseAudio : connection is refused

### ISSUE THREAD

**Issue by winelectric** [alexylem/jarvis#333]
### Can Jarvis run off_line? 

1. I experimented that bing token fail during internet interrupted? The system only responded back with HELLO? and ERROR shown up? Is system set up to work offline possible?
2. ALSA lib pulse sometime give me errors while service is running. it returns "paTimedOut" and "PaUnixThread_New failed? Sometime, it kicks out my playback set up on ~/.asoundrc file:
I am using Logitech C270  as you listed, 
From:
pcm.!default {
  type asym
   playback.pcm {
     type plug
     slave.pcm "hw:0,0"
   }
   capture.pcm {
     type plug
     slave.pcm "hw:1,0"
   }
} 

To:
pcm.!default {
  type asym
   playback.pcm {
     type plug
     slave.pcm "false"
   }
   capture.pcm {
     type plug
     slave.pcm "hw:1,0"
   }
}

Also, it almost did not recognize my voice. When it starts, it was doing good, then it failed so many time. I also made sure that all asoundrc file be fixed before staring running again, but it still happens 
Please help, I feel so noobie here
Regard
Thank you so much

**Comment by alexylem** [comment]
1. Jarvis can run offline only with Snowboy for recognition of commands (predictive, no untrained sentences). To use Bing you need to be online.
2. Support of PulseAudio is planned here: #200. It's normal you have PA related error messages with Snowboy but it should work anyway. Please paste full terminal with Jarvis in troubleshooting mode.

**Comment by alexylem** [comment]
Any update?

**Comment by wikijm** [comment]
No answer of the issue creator since 5 Jan 2017 => Issue closed.
Don't hesitate to reopen the issue if there is some evolution.
