### ISSUE TITLE
[jv_sanitize] Utilisation / Assainissement variables avec espace passées dans une url

### ISSUE THREAD

**Issue by AlkaYoda** [alexylem/jarvis#334]
Bonjour à tous,

Pour commencer un grand bravo pour le développement de jarvis, installation facile, tout de suite fonctionnel.

Pour mon usage, j'ai besoin de renvoyer la phrase de commande en variable dans l'url d'un curl, et de faire lire à Jarvis le résultat de l'exécution de cette page.

Or, comme la phrase contient des espaces, cela ne se passe pas comme prévu 

La commande de base est la suivante : 
*==jv_curl "http://ip/script.php?ordre=$order"

Mais il faut assainir $order en remplaçant les espaces par un autre caractère ou par le code html de l'espace avant de faire le jv_curl.

J'ai tenté : 

*==jv_sanitize($order,"_"); jv_curl "http://ip/script.php?ordre=$order"
*==jv_curl "http://ip/script.php?ordre="jv_sanitize($order,"_")""

et bien d'autres choses sans succès (avec curl par exemple).

Quelqu'un utilise-t-il quelque chose de similaire et si oui comment faut il formater la commande ?

Je vous remercie pour votre aide !

**Comment by AlkaYoda** [comment]
je me réponds à moi même car j'ai trouvé la solution en parcourant plusieurs Issues 👍 

La solution est en fait la suivante, sans devoir utiliser jv_sanitize() : 

*==say "$(curl "http://ip/scripts/script.php" --data-urlencode "ordre=$order")"

et de récupérer order en $_POST via l'option  --data-urlencode de curl

**Comment by alexylem** [comment]
Bien joué. J'en profite juste pour confirmer que `jv_sanitize` est pour supprimer les accents et caractères spéciaux, voir même remplacer les espaces par un autre caractère (utile pour faire de la comparaison de chaines, nommage de fichier...). Dans ton cas tu as besoin d'encoder ton URL ce qui est différent. Ta solution est la bonne.

**Comment by alexylem** [comment]
PS: tu pourrais aussi utiliser `jv_curl` pour te faciliter les tests. Plus d'information (ainsi que pour `jv_sanitize`) ici:
http://domotiquefacile.fr/jarvis/content/public-api-reference
