### ISSUE TITLE
Snowboy hotword pas reconnu

### ISSUE THREAD

**Issue by lutoele** [alexylem/jarvis#336]
### Probleme lancement Jarvis

J' ai réinstallé JARVIS en me disant que je n'avait pas respecté quelques choses mais toujours la même chose 
snowboy: Waiting to hear 'snowboy'
Et la j'ai beau essayer d'appeler JARVIS ou snowboy rien ...

J'ai testé mon micro OK 
Mes HP ok

snowboy: Waiting to hear 'snowboy'
CHERS-HABITANT: (listening...)

![prb jarvis 2](https://cloud.githubusercontent.com/assets/24940220/21718046/0235033a-d415-11e6-9769-50963bbbe631.jpg)
![prb jarvis 3](https://cloud.githubusercontent.com/assets/24940220/21718045/0231cf44-d415-11e6-917d-0c7c4150a18e.jpg)
![prb jarvis](https://cloud.githubusercontent.com/assets/24940220/21718047/02382b8c-d415-11e6-923c-7f49dd2b2f02.jpg)

Merci d'avance pour votre aide.

PS je suis novice et débutant désolé.

**Comment by wikijm** [comment]
Bonjour @lutoele,

Tu semble rencontrer un problème avec le module 433 Mhz.
Peux-tu le désinstaller et réessayer ?

**Comment by lutoele** [comment]
Bonjour,

je n'ai installé aucun module 433MHZ mon RASPBERRY et tel que je l'ai déballé

**Comment by wikijm** [comment]
Je parle de ce module pour Jarvis : http://domotiquefacile.fr/jarvis/plugins/domotique-433mhz
On voit sur ta 3e capture d'écran qu'il rencontre un problème avec le fichier `plugins/jarvis-fr_domotique_433Mhz/config.sh`

**Comment by wikijm** [comment]
Regarde la documentation suivante pour visualiser les plugins installés sur Jarvis : http://domotiquefacile.fr/jarvis/content/plugins

**Comment by lutoele** [comment]
Merci je vais faire le nécessaire mais pourquoi lors du lancement j ai "snowboy" et non JARVIS?
Et pourquoi lorsque je dit "SNOWBOY" il ne s active pas?

**Comment by wikijm** [comment]
Certainement parce que tu as passé trop vite le 1er assistant de configuration.
Relance-le et dis-nous si cela va mieux après suppression du plugin 433 et cette action.

**Comment by lutoele** [comment]
Bon tout desintallé.
J ai réinstallé en faisant attention à toute les infos, je n ai installé aucun plugins et la ...
Toujours la même chose :
snowboy: Waiting to hear 'snowboy'
CHERS-HABITANT: (listening...)
Ou est le souci je deviens fou !!!!

**Comment by wikijm** [comment]
Pourrais-tu faire une capture d'écran à chaque étape d'installation ?
Tu dois sûrement manquer une petite subtilité.

**Comment by alexylem** [comment]
Tu n'as que le hotword "snowboy" configuré. Donc il te faut dire "snowboy".
Il faut bien le dire à l'anglaise, dans un environnement calme "Snaaoboyi"
Normalement quand tu parles, l'ajout de ligne "Silence" devrait se stopper très rapidement le temps d'analyser l'audio. C'est déjà un bon signe qu'il entend.
Tu es bien sur un Raspberry Pi avec Jessy full?

**Comment by lutoele** [comment]
Jessy full??

**Comment by alexylem** [comment]
Pardon Jessie Full dans le sens pas Jessie Lite :)
Mais je vois que les dernières distributions full incluent Pixel... ca devrait pas être un problème à priori.

**Comment by lutoele** [comment]
J'ai installé raspian et après avoir regarder les vidéo avec JARVIS j'ai suivit pas à pas l'installation posté. 
Comment changer snowboy par JARVIS car même en accentuant sur le snaaoboyi ça ne fonctionne pas :-(

**Comment by alexylem** [comment]
Les vidéos datent, il faut vraiment que j'en fasse des nouvelles. N'hésites pas à t'abonner pour ne pas les louper.
Lors de l'installation ou reconfiguration (Settings > Step by step wizard) tu peux changer le Magic word:
![image](https://cloud.githubusercontent.com/assets/11017174/21731493/e9055e06-d454-11e6-82bd-d37f40d13ab2.png)
Tu peux mettre par exemple... "Jarvis" 😄 
Alors l'application t'invitera à trainer ton hotword: il va te faire enregistrer 3 fois ton magic word qu'il faudra prononcer et automatiquement créer le hotword pour snowboy.

**Comment by alexylem** [comment]
Attends, je viens de réaliser que tu as l'erreur PulseAudio. C'est un pb connu, voir #122.
Essaye de désinstaller PulseAudio.

**Comment by lutoele** [comment]
Bonjour,

Bon me revoilà après avoir fait un RAZ et racheté du matériel adéquat comme le micro et des Hp auto alimentée je recommence à partir d'une page blanche.
1 raspberry pi 3
2 cartes Arduino Uno
1 carte 433 Mhz (émetteur et recepteur)
1 carte 4 relais
1 rfxcom (en commande)

**Comment by lutoele** [comment]
Je souhaiterais brancher et bien sur parametrer tout ça correctement avec Jarvis (ex:"jarvis allume la lumière"( contact lumière branché sur carte relais) "lumière allumée ") et ensuite rajouter les micros modules Z wave etc petit à petit. 
Merci à toutes et à tous pour votre collaboration et surtout votre aide.
