### ISSUE TITLE
ERROR OCCURED WHILE TRAINING THE MODEL

### ISSUE THREAD

**Issue by VietFrench** [alexylem/jarvis#337]
### 
Lorsque que l'on me demande de parler 3 fois ds le micro a la fin une erreur apparait

### Result
```shell
<ERROR OCCURED WHILE TRAINING THE MODEL>
```

**Comment by alexylem** [comment]
Aucune autre erreur de s'affiche? tu peux coller le contenu du terminal en entier? Tu bien renseigné le token snowboy?
Merci

**Comment by VietFrench** [comment]
Aucune autre erreur s'affiche, mais je n'ai pas pas vraiment compris ce que etait le token snowboy ?

**Comment by alexylem** [comment]
Ah ben si tu n'as pas mis le token, ca ne marchera pas. Normalement Jarvis le demande à l'installation mais c'est étonnant qu'il ne te montre pas un message d'erreur lié à ça (surement à truc que je dois corriger).
Alors voila comment faire:
Settings > Voice Reco > Snowboy token (ca te donnera l'URL pour l'obtenir)

**Comment by alexylem** [comment]
Pour info je viens de tester, moi ca me mets bien une erreur en l'absence de ce token:
![image](https://cloud.githubusercontent.com/assets/11017174/21751161/bb88180a-d5c2-11e6-9b5a-53606a12c3b0.png)
Bon ok ca pourrait être plus clair...

**Comment by earyende** [comment]
J'ai la même erreur ! Pourtant j'ai créé un token sur Snowboy. Est ce-que je dois toucher à quelque chose sur le site Snowboy ou est ce je dois toucher à des fichiers sur mon raspberry ? Merci pour la réponse

**Comment by rebelkov** [comment]
j'avais eu le même cas: c'est un probleme d'autorisation sur l'api training online de snowboy. il faut rajouter dans le stt_engines/snowboy/main.sh au niveau du curl (api/training/v1)  un header d'autorisation que tu auras recupéré.  `curl "https://snowboy.kitt.ai/api/v1/train/" -H  "Authorization: Token 8ae4b6790fecd81be6430fea995cb071b7abbd8b`

**Comment by wikijm** [comment]
Merci @rebelkov pour la solution :-)
@VietFrench et @earyende Pas de vos nouvelles depuis 20 jours, je suppose donc que votre problème est résolu ;-)

N'hésitez pas à revenir par ici pour nous faire un petit retour :-)

**Comment by alexylem** [comment]
En revérifiant sur:
http://docs.kitt.ai/snowboy/#api-v1-train
Il n'y a pas besoin de passer le token dans le header car il est déjà présent dans data. Les différents samples de code le confirment.
