### ISSUE TITLE
jarvis-hue

### ISSUE THREAD

**Issue by ledarvite** [alexylem/jarvis#340]
Salut 
comment configurer jarvis-hue 

J ai installer mais impossible d inseré l api
merci

**Comment by ledarvite** [comment]
Salut
comment configurer jarvis-hue

J ai installer mais impossible d inseré l api
merci

**Comment by fatoldsun00** [comment]
Bonjour,

Par api tu entends la clé d accès à l api ? Si oui elle est inutile puisque la librairie python hue que j utilise enregistre l application auprès du pont lors du 1er appel. Il faut appuyer sur le bouton du pont puis lancer une commande via jarvis.

Il faut par contre installer l api python d accès au hue. Dans le fichier install.et ( qui est lancer en automatique je suppose mais bon) via la commande pip install phue.

Je reste à ta dispo, mon premier testeur sur mon premier projet github, tu parles que j suis au taqué ;)

**Comment by ledarvite** [comment]
je n' arrive pas avec api hue sur Jarvis

**Comment by ledarvite** [comment]
avec mi light c est nickel

**Comment by fatoldsun00** [comment]
Mais c est le fichier de config qui te pose soucis ?

`#Avant le premier appel appuez sur le bouton du bridge pour que l'appli puisse recuperer une clé d'acces a l'api
HUEIP="192.168.1.11" #Bridge ip
mapWordLigth="{'ca va':'salon','salope':'salon','salaud':'salon','salons':'salon','salle de bains':'salle de bain'}"
mapColor="{'rose': {'hue':322,'sat':200,'bri':100},'orange': {'hue':49,'sat':200,'bri':240}}"`

Tu dois inbdiquer l'ip de ton pont.
mapWordLigth c est pour mapper des mots qui ne seraient pas bien compris par le STT
mapColor c est pour mapper des couleur sur des noms.

Ensuite tu lance jarvis, tu appuies sur le bouton du pont et tu lances ta premier commande. ca devrait fonctionner :(

Sinon verifier que tu a phue d'installer --> sudo pip install phue

**Comment by alexylem** [comment]
Pour toute question ou problème lié à un plugin Jarvis, merci de créer un ticket sur le repository correspondant. Ainsi son auteur en sera informé et pourra vous aider.

**Ok, alors c'est où?**
* Depuis Jarvis, allez dans Plugins > Installed > The Plugin > Report an issue
* Depuis le site, allez sur la page du plugin et cliquez sur le lien "Open a ticket"

Autrement dit, je ne fait pas de support pour les plugins tiers.
Merci de votre compréhension.

**Comment by plano51** [comment]
Bonjour,
j'ai un souci aussi avec Hue!
phue est bien installé, quand je demande "lumière salon", Jarvis me répond "lumière inconnue".
Qu'ais-je mal fait?

**Comment by fatoldsun00** [comment]
Je t'invite a ouvrir un ticket comme indiqué ci-dessus et on voit ca ensemble si ca te dis ;)

**Comment by wikijm** [comment]
Merci pour la prise en compte @fatoldsun00 :-)
