### ISSUE TITLE
Rien ne se passe après l'initialisation / Nothing happens after init

### ISSUE THREAD

**Issue by Lins59** [alexylem/jarvis#341]
Désolé, c'est encore moi ...

J'ai refait une installation sur une rasbian lite, destinée à être utilisée comme serveur headless.
Après avoir fait la configuration et démarrer le programme, plus rien ne se passe.
Pulseaudio n'est pas installé non plus.
Une idée ?

Bonne soirée,

LOG :
```
~/jarvis$ ./jarvis.sh

------------ Config ------------
jv_version           17.01.07
jv_arch              armv6l
jv_os_name           raspbian
jv_os_version        8
language             fr_FR
play_hw              hw:0,0
rec_hw               hw:1,0
speaker              ALSA
microphone           Trust
trigger_stt          snowboy
command_stt          bing
tts_engine           svox_pico
--------------------------------

DEBUG: program_startup hook
george: Hello
User defined commands:
*AIDE*                  *BONJOUR*|*SALUT*       *COMMENT*APPELLE*
*MERCI*                 *AU REVOIR*|*BYE*       ANNULE*|TERMINE*
ENCORE*                 *TEST*                  *VERSION*
*REPETE (*) ET (*)      *CA VA*                 >*OUI*
>*NON*
george: Waiting to hear 'george'
Maitre: (listening...)
DEBUG: models=alexa,george,snowboy
ALSA lib confmisc.c:1286:(snd_func_refer) Unable to find definition 'cards.bcm2835.pcm.front.0:CARD=0'
ALSA lib conf.c:4259:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:4738:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM front
ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.rear
ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.center_lfe
ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.side
ALSA lib confmisc.c:1286:(snd_func_refer) Unable to find definition 'cards.bcm2835.pcm.surround51.0:CARD=0'
ALSA lib conf.c:4259:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:4738:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM surround21
ALSA lib confmisc.c:1286:(snd_func_refer) Unable to find definition 'cards.bcm2835.pcm.surround51.0:CARD=0'
ALSA lib conf.c:4259:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:4738:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM surround21
ALSA lib confmisc.c:1286:(snd_func_refer) Unable to find definition 'cards.bcm2835.pcm.surround40.0:CARD=0'
ALSA lib conf.c:4259:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:4738:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM surround40
ALSA lib confmisc.c:1286:(snd_func_refer) Unable to find definition 'cards.bcm2835.pcm.surround51.0:CARD=0'
ALSA lib conf.c:4259:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:4738:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM surround41
ALSA lib confmisc.c:1286:(snd_func_refer) Unable to find definition 'cards.bcm2835.pcm.surround51.0:CARD=0'
ALSA lib conf.c:4259:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:4738:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM surround50
ALSA lib confmisc.c:1286:(snd_func_refer) Unable to find definition 'cards.bcm2835.pcm.surround51.0:CARD=0'
ALSA lib conf.c:4259:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:4738:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM surround51
ALSA lib confmisc.c:1286:(snd_func_refer) Unable to find definition 'cards.bcm2835.pcm.surround71.0:CARD=0'
ALSA lib conf.c:4259:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:4738:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM surround71
ALSA lib confmisc.c:1286:(snd_func_refer) Unable to find definition 'cards.bcm2835.pcm.iec958.0:CARD=0,AES0=4,AES1=130,AES2=0,AES3=2'
ALSA lib conf.c:4259:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:4738:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM iec958
ALSA lib confmisc.c:1286:(snd_func_refer) Unable to find definition 'cards.bcm2835.pcm.iec958.0:CARD=0,AES0=4,AES1=130,AES2=0,AES3=2'
ALSA lib conf.c:4259:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:4738:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM spdif
ALSA lib confmisc.c:1286:(snd_func_refer) Unable to find definition 'cards.bcm2835.pcm.iec958.0:CARD=0,AES0=4,AES1=130,AES2=0,AES3=2'
ALSA lib conf.c:4259:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:4738:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM spdif
ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.hdmi
ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.hdmi
ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.modem
ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.modem
ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.phoneline
ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.phoneline
Cannot connect to server socket err = No such file or directory
Cannot connect to server request channel
jack server is not running or cannot be started
```

**Comment by oeildefeu** [comment]
Quand tu as fait la config, tu as entendu du son et tu t'es entendu parlé dans le micro ?

**Comment by Lins59** [comment]
Oui, tout à fait.
J'ai même redémarré plusieurs fois pour être sûr.

Tout à l'air correct dans les paramètres, Jarvis me dit bien "Hello" dans les enceintes

**Comment by alexylem** [comment]
C'est normal que "Silence" ne s'affiche plus (c'est la dernière version de snowboy que j'ai mis à jour hier).
Essaye de bien prononcer alexa, george ou snowboy.

**Comment by Lins59** [comment]
Bonjour,

J'ai changé le magic word de George à Alexa.
Même problème : rien ne se passe quand je prononce "Alexa" ...

Une idée ?

**Comment by alexylem** [comment]
Pas besoin de changer le magic word. Snowboy charge tous les modèles existants, et la tu as les 3, il devrait afficher quelque-chose s'il reconnait l'un des 3.
C'est vraiment étonnant, et assez rare que cela ne fonctionne pas sans plus de message d'erreur.
Essaye ceci:
```
$> rec /tmp/test.wav; play /tmp/test.wav
```
Dis qqchose et fais Ctrl+C pour arrêter l'enregistrement. Tu devrais t'entendre. Tu peux confirmer?

Aussi par curiosité: dans ma dernière version de snowboy, j'ai rajouté un bout de coder pour cacher tous les messages d'erreur ALSA, et chez toi on les voit toujours. Peux-tu tourner le code suivant:
```python
python
from ctypes import *
cdll.LoadLibrary('libasound.so')
Ctrl+D # pour quitter python
```
Merci!

**Comment by Lins59** [comment]
Je confirme que je m'entends bien parler

Par contre, pour python, j'ai des erreurs :

python
Python 2.7.9 (default, Sep 17 2016, 20:26:04)
[GCC 4.9.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> from ctypes import *
>>> cdll.LoadLibrary('libasound.so')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.7/ctypes/__init__.py", line 443, in LoadLibrary
    return self._dlltype(name)
  File "/usr/lib/python2.7/ctypes/__init__.py", line 365, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: libasound.so: cannot open shared object file: No such file or directory

**Comment by alexylem** [comment]
Ok merci je change en `libasound.so.2`.
Pour ton problème je sèche...
T'as bien la sensibilité Snowboy d'origine? (0.4 ou 0.5 dans Settings > Voice Reco)
Tu es bien sur Raspbian 8 Jessie Full (pas Lite)?
Il faudrait que j'inclue dans Jarvis un fichier de test pour Snowboy comme pour Bing. C'est ce que je ferai si on ne progresse pas plus la dessus.
Tu peux aussi tenter de réinstaller Snowboy:
```shell
cd stt_engines/snowboy/
./uninstall
cd ../../
./jarvis.sh
```

**Comment by Lins59** [comment]
Je pense que ton changement en libasound.so.2 a été salvateur !
Après update & redémarrage, c'est bon pour moi !
J'ai un peu augmenté la sensibilité, également, passant de 0.4 à 0.5

Pour info, Jarvis marche sur Raspbian 8 Jessie Lite 👍

**Comment by alexylem** [comment]
2 bonnes nouvelles en même temps, ça fait plaisir 😄

**Comment by idem2lyon** [comment]
Je ne comprends pas ce que tu as fait de plus pour que cela fonctionne @Lins59 ?
@alexylem de mon coté, j ai aucun message d erreurs alsa.

Qu'est ce qu il y a en plus dans la full qui empeche le fonctionnement en lite?

**Comment by idem2lyon** [comment]
lorsque j'essaye d'augemnter la sensibilité 👍 
pi@raspberrypi:/opt/jarvis $ ./jarvis.sh
index de carte invalide: s
essayez `alsamixer --help' pour plus d'information
ERROR: check above

**Comment by idem2lyon** [comment]
pareil lorsque je veux augmenter le volume 👍 index de carte invalide: s
essayez `alsamixer --help' pour plus d'information
ERROR: check above

**Comment by Lins59** [comment]
@idem2lyon 
Je n'ai rien installé de plus que ce qui a été mentionné là : https://github.com/alexylem/jarvis/issues/327
Enfin, il me semble ;)

Tu n'as pas d'erreurs ?
Essaye de désinstaller et réinstaller Jarvis, ça regénérera des fichiers de conf corrects.

Pour info, j'étais partie sur une Jessie 8 Lite prise sur le site raspberry. Les debian minimales sont trop lite sans avoir à installer 40 paquets ;)

**Comment by idem2lyon** [comment]
J'ai pris aussi une jessie lite, et je fais deja la manip pour la partie audio :(

**Comment by alexylem** [comment]
>@alexylem de mon coté, j ai aucun message d erreurs alsa.

Normal j'ai corrigé ce pb depuis

>essayez `alsamixer --help' pour plus d'information

Oui pour certains cartes on ne peut pas gérer gérer la sensibilité dans alsamixer. J'ai une autre piste pour gérer la sensibilité directement depuis sox (mais ca ne marcherait pas pour snowboy).

**Comment by alexylem** [comment]
En fait c'est la: #328 et la solution existe aussi pour snowboy. Il n'y a plus qu'à 😄
