### ISSUE TITLE
Snowboy error: {"detail":"Authentication credentials were not provided."}

### ISSUE THREAD

**Issue by lucast21** [alexylem/jarvis#342]
Bonjour,

Deja mercimde mettre Jarvis a disposition gratuitement, même si pour l'instant je n'ai pas encore eu l'honneur de l'essayer. Quand j'enregistre les 3 samples ce message s'affiche; ERROR: error occured while training the model. Je pense que je le fait mal mais j'ai essaye tout les possibilité d'enregistrement et ce message continue d'apparaître. Pourrais tu m'expliquer la méthode a suivre pour enregistrer les 3 samples.

Merci

**Comment by alexylem** [comment]
Tu peux coller le contenu du terminal? Il doit y avoir une erreur qui s'affiche au dessus normalement.

**Comment by lucast21** [comment]
In:0.00% 00:00:02.09 [00:00:00.00] Out:32.4k [      |      ] Hd:0.0 Clip:930  ^C
rec WARN rate: rate clipped 80 samples; decrease volume?
rec WARN dither: dither clipped 70 samples; decrease volume?
rec WARN sox: `coreaudio' input clipped 780 samples
Aborted.
rec WARN formats: can't set sample rate 16000; using 44100
rec WARN formats: can't set 1 channels; using 2

Input File     : 'default' (coreaudio)
Channels       : 2
Sample Rate    : 44100
Precision      : 32-bit
Sample Encoding: 32-bit Signed Integer PCM

In:0.00% 00:00:02.35 [00:00:00.00] Out:36.2k [      |      ] Hd:0.0 Clip:608  ^C
rec WARN rate: rate clipped 49 samples; decrease volume?
rec WARN dither: dither clipped 39 samples; decrease volume?
rec WARN sox: `coreaudio' input clipped 520 samples
Aborted.
rec WARN formats: can't set sample rate 16000; using 44100
rec WARN formats: can't set 1 channels; using 2

Input File     : 'default' (coreaudio)
Channels       : 2
Sample Rate    : 44100
Precision      : 32-bit
Sample Encoding: 32-bit Signed Integer PCM

In:0.00% 00:00:01.58 [00:00:00.00] Out:24.3k [      |      ] Hd:0.8 Clip:0    ^C
Aborted.
Training model...
######################################################################## 100,0%
{"detail":"Authentication credentials were not provided."}
ERROR: error occured while training the model

**Comment by alexylem** [comment]
```
{"detail":"Authentication credentials were not provided."}
```
Tu n'as pas mis le token Snowboy.
Settings > Voice Reco > Snowboy Token

**Comment by lucast21** [comment]
Et c'est quoi le snowboy token ? Je ne peut pas accéder au settings sans passer cette étape.

**Comment by alexylem** [comment]
A l'installation Jarvis devrait te le demander.
Si il ne te le demande pas, c'est que tu as déjà rentré une valeur (peut-être une fausse).
1. Récupère un token Snowboy valide en t'inscrivant sur: https://snowboy.kitt.ai
2. Modifie manuellement la valeur de ton token ainsi:
```shell
echo "TOKENSNOWBOY" > config/snowboy_token
```

**Comment by lucast21** [comment]
Merci ça marche. Par contre maintenant il me demande une clé Bing
speech alors j'ai créer un compte microsoft mais je ne trouve pas
speech preview.

Le 08/01/2017, Alexandre Mély<notifications@github.com> a écrit :

**Comment by alexylem** [comment]
Ok tu peux créer un autre ticket?
