### ISSUE TITLE
play FAIL formats: can't open output file `default': snd_pcm_open error: No such file or directory

### ISSUE THREAD

**Issue by rexave** [alexylem/jarvis#343]
Bonjour,

Jarvis fonctionne normalement; puis après une interaction, il plante 

``` bash
Monsieur: merci
Alexa: De rien
play FAIL formats: can't open output file `default': snd_pcm_open error: No such file or directory
ERROR: play command failed
HELP: Verify your speaker in Settings > Audio > Speaker
```

Constaté plusieurs fois avec jarvis en mode ligne de commande (pas en mode service) avec un jabra510.

**Comment by rexave** [comment]
Note : j'ai modifié la commande merci pour qu'elle arrete l'interaction ainsi 

`*MERCI*==say "De rien"; bypass=false`

Je ne sais pas si c'est la bonne méthode. Le pb peut venir de là ?

**Comment by rexave** [comment]
Note : j'ai modifié la commande merci pour qu'elle arrete l'interaction ainsi 

`*MERCI*==say "De rien"; bypass=false`

Je ne sais pas si c'est la bonne méthode. Le pb peut venir de là ?

**Comment by alexylem** [comment]
Pour répondre à ta question, non ce que tu fais le fait juste sortir du mode conversation. Il va te redemander de prononcer le hotword. Ca n'a pas de lien avec ton problème.
L'erreur:
```shell
play FAIL formats: can't open output file `default': snd_pcm_open error: No such file or directory
```
 a été discutée ici: #61 . Peux-tu réouvrir le ticket #61 et y partager ton `~/.asoundrc` ainsi que ta config (le header de Jarvis lancé en mode troubleshooting). Merci!
