### ISSUE TITLE
Possibilité de choisir la sortie audio en ligne a de commande

### ISSUE THREAD

**Issue by Sopalin06** [alexylem/jarvis#344]
### Description

L'objectif serait de pouvoir lancer jarvis en ligne de commande en utilisant une sortie audio différente de celle par défaut.
On aurait ainsi un système opérationnel dans le salon avec la possibilité de faire parler jarvis sur une enceinte bluetooth dans la salle de bain le matin.

**Comment by alexylem** [comment]
On dirait que c'est dépendant de #200 (en tout cas pour l'utilisation du bluetooth).
Tu peux aussi aujourd'hui, en utilisant Jarvis-API faire parler un autre Jarvis lié à une autre enceinte.

**Comment by Sopalin06** [comment]
Malheuresement l'installation de PulseAudio dérégle Jarvis chez moi, aucune reco n'est possible, surement une incompatibilité entre les deux systèmes.

**Comment by wikijm** [comment]
@Sopalin06 De grandes avancées sont en cours avec Pulse Audio (voir [Jarvis avec PulseAudio #200](https://github.com/alexylem/jarvis/issues/200)).

Teste ce qui est proposé, et ré-ouvre cette issue uniquement si cela ne répond pas à ton besoin 😉
