### ISSUE TITLE
Erreur sur site internet /  control from  smartch Android wear 

### ISSUE THREAD

**Issue by Sellig28** [alexylem/jarvis#345]
@alexylem,

Une erreur c'est glissée sur ton tutoriel. La variable n'est pas "%awcomm" mais "%awmessage".

De plus, je ne sais pas si ça le fait chez toi, mais avant  la première diction, jarvis prononce une erreur car %Appopened semble envoyé. Je vais investiguer.

**Comment by alexylem** [comment]
J'ai corrigé le nom de variable ici:
http://domotiquefacile.fr/jarvis/content/voice-control-from-smartwatch
Je suis passé depuis sous iOS donc peux pas tester pour le moment.

**Comment by Sellig28** [comment]
Désolé pour ma réponse tardive, mais c'est bon ça fonctionne.
merci pour ta correction sur le site.

**Comment by Jean-Bernard-Hallez** [comment]
Personnellement j'ai voulu essayé ton tutoriel... j'ai effacé tout ce que j'avais fait en relation avec la montre et sincèrement je ne suis absolument pas convaincu ce ta procédure qui est bien si on utilise pas d'autre variante de autowear. En effet a chaque foi que l'ou clique sur cette icone sur le montre il envoie la requête vide à jarvis (donc jarvis ne comprends pas) puis après oui il traduit ce qu'on lui demande avec une seconde requête. De plus si on rajoute par exemple un Four  Screens sur la montre à l'ouverture et à l'appuis de chaque bouton il envoie une requête vide ce qui est le but de %APPOPENED%.
Voici ma procédure est beaucoup plus longue c'est sur, 
1) j'ai créé un Voice Screen qui s'ouvre si j'appuis sur un bouton situé au milieu de l'écran, je le nomme Jarvis Micro. 
2) Puis dans tasker j'ajoute un événement provenant de AutoApps Tasker dans lequel le met Jarvis Micro dans Command Filter puis comme tâche j'ouvre Autowear Voice Screnn sur la montre. 
3) Sur Tasker à nouveau je rajoute un événement provenant de Voice Screnn qui ouvre une tache Get HTTP et là je n'ai plus de commande intempestive... Je n'arrive pas à faire plus simple lol.
