### ISSUE TITLE
opt-out from Google Analytics

### ISSUE THREAD

**Issue by tigre-bleu** [alexylem/jarvis#346]
En me plongeant dans le code de jarvis.sh j'ai constaté qu'on envoyait un ping à google analytics à chaque démarrage:

```
# send google analytics hit
( jv_ga_send_hit & )
```
**jarvis.sh ligne 416**

Je ne suis pas très à l'aise avec ça, je n'ai pas envie d'informer Google de mon utilisation ou non de Jarvis.

J'imagine que ce code est là pour avoir des stats sur les utilisations de Jarvis, et je peux le comprendre mais ce serait bien d'avoir une possbilité de refuser l'envoi des stats (opt-out).

**Comment by alexylem** [comment]
Tout à fait d'accord. C'était prévu 😄 
C'est bien pour mesurer l'utilisation de Jarvis, c'est bien entendu totalement anonyme. Je vais rajouter un option opt-out dans les réglages.
Pour info aujourd'hui j'envoi la langue et la version utilisée.

**Comment by alexylem** [comment]
![image](https://cloud.githubusercontent.com/assets/11017174/21786703/91883d38-d6c5-11e6-9101-9ad8e3bd2fef.png)

**Comment by tigre-bleu** [comment]
C'est du rapide! :)
