### ISSUE TITLE
Sondage / Contest: Nouveau Nom pour Jarvis?!

### ISSUE THREAD

**Issue by alexylem** [alexylem/jarvis#347]
Cher contributeur de Jarvis,

J'ai toujours eu en tête qu'il faudrait bien un jour changer le nom de Jarvis.
Pas parce que Zuckerberg a nommé ainsi son projet d'assistant vocal (*Big Brother is watching you*) mais simplement car il est trop générique et vulgarisé dans de nombreuses autres initiatives du genre. Il est même assez difficile de trouver sur le net des articles qui parlent de notre projet pour cette simple raison.

![weneedyousmall](https://cloud.githubusercontent.com/assets/11017174/21780183/e6317734-d6aa-11e6-97fa-b779ed6f2bf0.jpg)

Voici comment j'aimerais procéder:
1. On utilise ce ticket pour faire des propositions et en discuter. J'utilise volontairement Github pour ça et pas le site car j'aimerais limiter l'audience à ceux qui contribuent vraiment au projet, il vous appartient autant qu'à moi 👍 .
2. Une fois qu'on a une bonne liste (et que j'aurais appliqué mon veto sur les propositions les plus exotiques 😈 ) je créerai un sondage afin que nous votions tous et que toutes les propositions retenues ait une chance. Je publierai probablement (mais pas sûr) ce sondage sur le site. Il faudra juste que je trouve un moyen pour éviter les doubles votes.
3. Je sélectionnerai le nom final parmi les 3 propositions les plus populaires.
4. Les auteurs de ces 3 propositions les plus populaires se verront accordés la publication d'un article à propos de leur projet sur le site de Jarvis (4k visites / jour) et seront mentionnés dans une prochaine vidéo sur la chaine Youtube  (2k abonnés).
5. Pour ceux qui se posent la question: je ne pense pas renommer le repo (pour ne pas faire planter les milliers d'installations de Jarvis à travers le monde). Je renommerai l'exécutable (`jarvis.sh => xxx.sh`) ainsi que tout ce qui fait référence à "Jarvis" sur le repo, le site, disqus et la chaine youtube. J'achèterai aussi un nouveau nom de domaine dédié au projet (grâce à [vos dons](http://domotiquefacile.fr/jarvis/content/credits)).

Conseils pour le nom:
* Soyez original, pas de nom trop commun (maison, assistant, ...)
* Trouvez des noms qui ne sont pas déjà utilisés dans d'autres initiatives similaires (sarah, siri, alexa, ...)
* Snowboy recommande des hotwords d'au moins 3 ou 4 syllabes, évitez les noms trop courts (hall, pi, ...)

Il y aura dans le sondage une option "Keep Jarvis".
Proposez vos noms, discutez-en, mais vous l'aurez compris, ca ne sert à rien de voter ici 😄 

Alex.

**Comment by alexylem** [comment]
**Nestor**

(De la part d'Yvan, par mail)
>Pour ma part, étant francophone et belge, j’ai préféré faire référence à Nestor, le majordome du capitaine Haddock, infiniment plus “vieille France” que tous ceux des comics américains...

Nestor n'est aujourd'hui ni associé au raspberry pi, ni à un quelconque assistant vocal 👍

**Comment by fatoldsun00** [comment]
Il me semble que tu as ecrit que snowboy recommande des noms de 4 syllabes et mon esprit un peu tordu a directement pensé a geronimo ... Et puis ca serait un comic killer a sa facon 8-).

Bon j'dis ca, j'dis rien

**Comment by alexylem** [comment]
@fatoldsun00 oui tu as raison, j'ai mis à jour les règles de nommage. Merci 😄

**Comment by alexylem** [comment]
Top 20 contributeurs du projet (par nombre de post) pour notification 😄 
@physicien(113) @remjou1(75) @Sellig28(64) @francoismartin(63) @kevincaradant(47) @wikijm(47) @Jean-Bernard-Hallez(43) @Smanar(36) @NYGHOST(34) @taostaos(34) @LengZai(30) @diyfr(29) @dud29(24) @Benfosse(22) @parrain27(19) @devauxa(17) @byackee(17) @azertigrou(16) @stackgil(16) @kiki51(13)

**Comment by wikijm** [comment]
"Pixel" donne de bons résultats avec snowboy. 
C'est également un mot qui ne devrait pas trop faire de faux-positif avec des gens parlant à côté.

**Comment by NYGHOST** [comment]
J'utilisais pour ma part "eva" tres court et sans accent

**Comment by kiki51** [comment]
Nous c'est Roger. Mais on a beaucoup de faux positifs. Donc on réfléchit a autre choses.

**Comment by mbl-35** [comment]
Que dites vous de ALEX ? Très court, rends hommage à son createur @alexylem , pas d'accents, convient tout à fait à une voix masculine ou féminine. Qui plus est, c'est un diminutif international...
Bien sûr, ce nom peut être changé au niveau configuration afin de piloter à la voix avec 'bernard' ou 'geronimo' ,... Mais dans ce post, on recherche un nom de diffusion du projet actuel ( pas forcément le nom utilisé par chaque pour piloter sa domotique...)
Donc, pour moi, +1 pour _alex.sh_

**Comment by tigre-bleu** [comment]
J'ai peur de la confusion entre Alex et Aller, qui est un mot très courant.

Je suis plutôt d'accord avec  le fait d'avoir 3 syllabes, même si ça réduit le champ des possibilités.

Moi j'utilise **Lapinou** car c'est couplé avec une Karotz, mais je ne suis pas sur que ce soit un super nom pour prendre le projet au sérieux :-)

**Comment by Lins59** [comment]
J'utilise "George", prononcé à l'anglaise.
Ca fait très majordome anglais et le hotword marche bien (pas de risque de le trouver dans une conversation "normale" :)

**Comment by ydellis** [comment]
Je pense essentiellement qu'il s'agit ici de donner au projet un nom qui le démarque des autres et soit suffisamment attrayant, reconnaissable et mémorisable par le plus grand nombre.
Ce nom ne doit pas forcément être efficace en tant que mot clé, ce dernier restant à la discrétion de l'utilisateur.
Pour ma part, "Nestor" est mon majordome, certainement attrayant pour les amoureux des bandes dessinées 'vintage' mais pas pour la majorité et certainement pas internationale.
Il faudrait donc choisir un nom qui fasse rêver et que tout le monde connait (ou presque). 
Je propose par exemple 'Yoda' (si le nom n'est pas protégé).

**Comment by AlkaYoda** [comment]
Cétautomatix en référence à Asterix & Obelix

**Comment by physicien** [comment]
Intéressant les statistiques, je ne pensais pas avoir écrit autant. Sinon, je trouve que Nestor est un nom convenant parfaitement à un assistant personnel. Nestor est également le nom qu'Asimov donne à ses robots NS-2 dans la nouvelle _Little Lost Robot_, et ce sont également des robots d'assistance personnelle dans le film _I, Robot_ :robot:

**Comment by tigre-bleu** [comment]
Même si ça ne fait pas 3 syllabes, j'aime bien `Nestor`. :-)

**Comment by Crali** [comment]
Je pense que le plus sympa serait un nom qui pourrait être un acronyme, après c'est pas évident à trouver... 
Sinon en majordome je pensais plus à **Alfred** qu'à Nestor, je trouve qu'il sonne un peu mieux :p

**Comment by godinperson** [comment]
J’aimais aussi Alfred mais après quelques recherches, un projet existe déjà sous ce nom, acheté par Google, de mémoire en 2009 ☹

**Comment by byackee** [comment]
Salut la team :)

J'aime bien Nestor, je n'ai pas testé la reco mais j'aime bien le mot.
 Nestor +1

**Comment by Sellig28** [comment]
Pourquoi pas "AVA" (tiré du film ex machina) ?

**Comment by Jean-Bernard-Hallez** [comment]
Bonjour tout le monde... Je pensais avoir trouvé les réglages et c'est à chaque fois pareil... Je passe pour un bricoleur du dimanche car quand il y a des invité Jarvis fait n'importe quoi même si je mets des noms tordu lol... Du coup je coupe le micro et passe uniquement avec la montre Wear... Personnellement j'utilisais 
HéJoliCoeur 4 syllabes et c'est la meilleure à présent...

**Comment by AlkaYoda** [comment]
Archibald ? Un peu plus compliqué que Nestor ou Alfred pour que la détection soit plus fiable ?

**Comment by Jean-Bernard-Hallez** [comment]
C'est un peu domage de changer le nom à ton projet... pourquoi ne pas tourner autour du mot j'avais en tout simplement jarvistela ? 4 syllabes ou jarvistelaoupas 6 syllabes ;-) je le mets en test en ce moment... au moins quand ça plante on est dans la logique de se réponse: Oui je t'écoute...

**Comment by Crali** [comment]
"jarvistela" ? Sérieux c'est quand même super moche :-/

**Comment by tuxme** [comment]
moi je l'ai appelé Esteban ... parce que "Esteban zia tao les cité d'or " (The IA ) :) ok je sorts :)

**Comment by kiki51** [comment]
Excellent!
En tout cas eviter "Roger"
Il se declenche a tout va!

Sinon autre idée : Jasper?

**Comment by Crali** [comment]
Jasper est déjà utilisé pour ce projet : [https://howchoo.com/g/yti5mmq0ntu/add-voice-controls-to-your-raspberry-pi-using-jasper](https://howchoo.com/g/yti5mmq0ntu/add-voice-controls-to-your-raspberry-pi-using-jasper)

**Comment by Sellig28** [comment]
Est-ce que l'on ne s'écarte pas du sujet initiale ? C'est bien de donner les noms que nous utilisons pour activer notre assistant, mais là il est question de nom de projet, vous pourrez toujours garder votre mot clef.

Je ne suis pas spécialiste, je trouve que c'est diificile de trouver des noms aux projets, mais peut-on tenter un "brainstorming" de ce que l'on peut faire avec le projet et tentons de sortir un nom ou anagrame.

Qu'en pensez-vous ?

Ps: je n'ai pas trop innover, étant fan de iron man, j'ai choisi "Jarvis" pour mot clef !

**Comment by Sellig28** [comment]
Je me lance: 

- assistant
- vocal
- domotique
- facile
- plugin

**Comment by Sellig28** [comment]
C'est pas de la pub, mais une piste.

http://www.veazio.com/marketing/les-5-meilleurs-generateurs-de-noms-de-domaine-ou-de-marques/

**Comment by tuxme** [comment]
le vrai jarvis dans le comics marvel iron man c'est un major d'homme ... et qui qui c'est qu on connait comme major d'homme d'un super heros super riche ? .. Alfred  :)

**Comment by tchoul** [comment]
Alors perso j'adore Jarvis! Mais faut il qu'il soit reconnu de la même façon sur snowboy que sur google now? ou uniquement snowboy?

**Comment by hazenote** [comment]
Pierre,moi j'aime bien comme nom

**Comment by LemarinelNet** [comment]
Nestor, Alfred et Jarvis sont mes preferés (sans ordre de préférence!)

**Comment by brutooss** [comment]
Ada ?
En référence au roman d'Antoine Bello.
Je l'utilise actuellement et fonctionne plutôt bien.

**Comment by rebelkov** [comment]
en 3 syllabes, je trouve albator discriminant. bon ok, cela fait un peu 80s mais pour un hotword, cela marche.

**Comment by alexylem** [comment]
Merci pour vos contributions, voici la liste totale finale:
- Eva
- Nestor (tintin, little lost robot, i robot)
- Geronimo
- Pixel
- Alex
- Lapinou
- George
- Yoda
- Cétautomatix
- Alfred (majordome de batman)
- Marvin (robot du guide du voyageur galactique)
- Ava (ex machina)
- Héjolicoeur
- Archibald
- Jasper (déjà utilisé)
- Jarvis (iron man)
- Talkbotic
- Alexotic
- Ada
- Albator

Je dois malheureusement écarter quelques propositions:
- Eva, Roger (sujet à faux positif)
- Ava, Ada (trop court)
- Alex, Alexotic (merci quand même, ca me touche)
- Jasper (déjà utilisé pour initiative similaire)
- Lapinou, Hélojolicoeur (veto sur proposition exotique 😈 )
- George (trop commun)

Il nous reste donc:
- Nestor (tintin, little lost robot, i robot)
- Geronimo
- Pixel
- Yoda
- Cétautomatix
- Alfred (majordome de batman)
- Marvin (robot du guide du voyageur galactique)
- Archibald
- Jarvis (aussi utilisé pour initiative similaire, merci Mark...)
- Talkbotic
- Albator

Les votes sont ouverts! C'est par ici:
http://domotiquefacile.fr/jarvis/content/nouveau-nom-pour-jarvis

**Comment by Jean-Bernard-Hallez** [comment]
Je n'arrive pas à choisir... rien ne pourrait à mes yeux la reconnaissance vocal... comme par exemple 
Vocalix,  SayWord, ExecuteVoix, ExecuteSay, AlexSay, SayAlex... il faut bien te rendre home tu es l'inventeur de ce projet là il devrai y avoir une consonance en ton nom... ;-)

**Comment by Jean-Bernard-Hallez** [comment]
Je n'arrive pas à choisir... rien ne pourrait à mes yeux la reconnaissance vocal... comme par exemple
Vocalix, SayWord, ExecuteVoix, ExecuteSay, AlexSay, SayAlex, Alexice,Alexdit, Dizalex... il faut bien te rendre hommage. .. tu es l'inventeur de ce projet là il devrai y avoir une consonance en ton nom... ;-)

**Comment by alexylem** [comment]
Petit statut... pour l'instant le nom en tête est... Jarvis 😓 

![image](https://cloud.githubusercontent.com/assets/11017174/22898856/198cdd14-f229-11e6-8a0c-9fb055cfcaba.png)

**Comment by ydellis** [comment]
Bonjour à tous.
Je voudrais rappeler que le nom de Jarvis est déjà utilisé par Zuckerberg qui commercialise son assistant. Ce nom est probablement protégé mais de toute façon au niveau marketing il n'est pas raisonnable, à mon avis, de garder ce nom de projet. C'était la raison de mon premier message à ce sujet.
Je pense donc qu'il est préférable de trouver une autre identité au projet.

Yvan

**Comment by Crali** [comment]
Euh, je ne vois aucune trace de la commercialisation du jarvis de Zuckerberg sur le net. Source ?

Sinon Alex, si tu ne veux pas de Jarvis, retire le tout simplement de la liste du sondage, tu forceras les gens à choisir quelque chose comme ça ^^

**Comment by godinperson** [comment]
https://www.facebook.com/notes/mark-zuckerberg/building-jarvis/10154361492931634/

**Comment by tuxme** [comment]
allez .. histoire de troller :) pourqoi pas NILES dans une nounou d'enfer  ?

2017-02-14 13:49 GMT+01:00 godinperson <notifications@github.com>:

**Comment by ydellis** [comment]
@ Crali,
En effet, j'ai extrapolé en parlant de commercialisation. Mais le "teasing" que fait Zuckerberg sur son Jarvis (avec invitation de la presse, vidéo etc..) n'est certainement pas "innocent". Suite à ses communications, il est vraisemblable que le nom Jarvis, en tant qu'assistant domestique, soit associé à Zuckerberg voire même qu'il l'ait protégé. En tous les cas, je pense que cela déforce un autre produit qui porterait le même nom et créerait une certaine confusion. 
Yvan

**Comment by alexylem** [comment]
Alfred a pris l'avantage, devant Jarvis et Nestor. Marvin est challenger.
![image](https://cloud.githubusercontent.com/assets/11017174/23030340/cad6d6c4-f46d-11e6-88c8-04d3680d7c22.png)

**Comment by wikijm** [comment]
https://www.namecheckr.com/
Site pouvant nous servir à voir si le nom que l'on choisira est disponible sur différents services Internet (Facebook, Twitter, Reddit, ...)

**Comment by Oliv4945** [comment]
Arf, j'avais loupé ça. Je vote pour Nestor aussi :+1: 
Sinon c'est un peu tard j'avais fait des essais avec R2, de R2D2 qui a très peu de faux positifs sous Snowboy, à voir ce que ça donne en référencement, surement pas mieux que Jarvis...

**Comment by Oliv4945** [comment]
@alexylem Où en es-tu de tes réflexions sur le nom ? Penses-tu laisser `Jarvis`, parce-que bon même si c'est plus sur à trouver, c'est bien adapté :+1: 
Je demande car je vais publier l'application Android sur le Play store donc autant éviter de changer de nom par la suite. Merci :)

**Comment by alexylem** [comment]
Je viens de regarder:
![image](https://cloud.githubusercontent.com/assets/11017174/25568765/8433e9b0-2e0a-11e7-8a57-067fd091bb44.png)
On dirait vraiment que la communauté n'est pas prête à voir le nom changer pour le moment.
J'ai envie de respecter ce choix, en tout cas pour le moment tu peux publier ton application sous ce nom, je ne compte pas le changer demain 😄

**Comment by Oliv4945** [comment]
Ok je fais ça.

Par contre au niveau référencement vu que tu n'as rien au niveau de la racine de domotiquefacile, ça aiderai de changer le nom de domaine avec quelque chose comme `jarvis-pa` (Personnal Assistant) ou équivalent

**Comment by alexylem** [comment]
@Oliv4945 complètement d'accord, j'ai payé pour l'année (avec les dons) alors je commence à y penser pour l'année prochaine!

**Comment by alexylem** [comment]
Tu as raison faudra avoir une période de recouvrement d'autant plus que Jarvis point sur domotiquefacile.fr pour le store des plugins. Je vais chercher des domaines dispos autour de "Jarvis".

**Comment by alexylem** [comment]
Voici les noms de domaines qui sont dispos pour le moment:
- http://jarvis-pa.com (personal assistant)
- http://project-jarvis.com
- http://openjarvis.com
- http://jarvis-sh.com (sh pour bash)
- http://jarvis-bot.com
- http://simplejarvis.com
- http://myjarvisassistant.com
- http://pijarvis.com (pi pour raspberry pi)
- http://j4rv1s.com
- http://myjarvis.net
- http://home-assistant.net

D'autres idées? Des préférences?

**Comment by Oliv4945** [comment]
Je vote pour http://jarvis-pa.com ou http://openjarvis.com.

Du coup une idée du délai ? J'attendrais bien ce nom pour publier l'application Android.

**Comment by alexylem** [comment]
J'ai mis à jour [mon post](https://github.com/alexylem/jarvis/issues/347#issuecomment-299706054) avec un tableau de votes.
Pourquoi attendre pour publier ton application? Tu veux la nommer comme le domaine? Tu ne peux pas le renommer plus tard?

**Comment by alexylem** [comment]
Notification top 20 contributeurs pour [vote sur le nom de domaine](https://github.com/alexylem/jarvis/issues/347#issuecomment-299706054):
@wikijm(299) @Jean-Bernard-Hallez(151) @physicien(118) @remjou1(79) @tchoul(70) @kevincaradant(68) @Oliv4945(67) @francoismartin(63) @Lusitanos67(54) @NYGHOST(43) @Smanar(38) @taostaos(35) @trarizakaria(35) @LengZai(30) @RobyBioloid(29) @diyfr(29) @oeildefeu(24) @idem2lyon(24) @dud29(24) @tigre-bleu(23)

**Comment by Oliv4945** [comment]
> Pourquoi attendre pour publier ton application? Tu veux la nommer comme le domaine? Tu ne peux pas le renommer plus tard?

ça ne m'a l'air possible de renommer une appli, et il y a déjà un paquet d'applications qui s'appellent Jarvis dans le [play store](https://play.google.com/store/search?q=jarvis&c=apps&hl=fr), dont une qui a déjà pris le nom "Jarvis" tout court, donc oui je pensais à utiliser le nom de domaine.

**Comment by francoismartin** [comment]
je vote pour http://openjarvis.com ;)

**Comment by Sellig28** [comment]
openjarvis.com, pour ouvrir sur le monde anglophone.

**Comment by trarizakaria** [comment]
Je vote pour openjarvis.com

**Comment by oeildefeu** [comment]
Pareil que le précédent : open Jarvis

**Comment by Jean-Bernard-Hallez** [comment]
OK aussi pour Open... ouvrons la porte à jarvis.... ;-)

**Comment by Lusitanos67** [comment]
+1 openjarvis

**Comment by kevincaradant** [comment]
Hello, je vote aussi pour openJarvis ;)

**Comment by kiki51** [comment]
+1 pour openjarvis

**Comment by wikijm** [comment]
+1 pour openjarvis.com

**Comment by alexylem** [comment]
Bon va pour http://openjarvis.com, avec ou sans tiret? Les 2 sont dispos:
http://open-jarvis.com

**Comment by Jean-Bernard-Hallez** [comment]
Avec le tiret...

**Comment by Oliv4945** [comment]
Pareil, http://open-jarvis.com/

**Comment by wikijm** [comment]
Je dirais plutôt sans, car :
- Plus simple pour les utilisateurs
- Permettant une plus grande liberté de représentation (si création de logo, bannière ou autre, on pourra faire des formats carrés sans avoir besoin de placer un trait d'union)
- Se rapprochant du nommage d'application Android (généralement de la forme com.nomdudev.nomdelapp, et sans caractères spéciaux)

**Comment by kevincaradant** [comment]
Hello, pareil que @wikjim, je préfère sans le tiret pour les mêmes raisons, dont juste celle de l'utilisateur qui reste déjà majeure  ')

**Comment by Oliv4945** [comment]
@wikijm : Les règles java préconisent effectivement de ne pas mettre le `-`, mais pour une URL je trouve ça moins lisible.
Après c'est vraiment au ressenti: dans gros sites web on a du pole-emploi.fr, voyages-sncf.fr ou jeuxvideo.com, societegenerale.fr

**Comment by alexylem** [comment]
Bon après quelques recherches sur internet, il semble que la version sans tiret soit en effet la plus fréquemment conseillée/recommandée.
J'ai donc acheté le domaine http://openjarvis.com, ça c'est fait!
J'ai mis à jour la page des dons pour référencer le paiement (ce que je m'engage à faire pour toute dépense avec les dons des utilisateurs)
http://domotiquefacile.fr/jarvis/content/credits
Un grand merci à eux!

**Comment by Oliv4945** [comment]
@alexylem. Super !
Quand penses-tu le mettre en service ?

**Comment by alexylem** [comment]
Bientôt, peut-être ce weekend si j'ai le temps. Il y aura pas mal de changements à faire...

**Comment by RAKAKA34070** [comment]
RAKAKA

**Comment by RAKAKA34070** [comment]
@luiaussi

**Comment by RAKAKA34070** [comment]
@Iutklr thc ci
