### ISSUE TITLE
Enhancement : use plugin functions in hooks

### ISSUE THREAD

**Issue by Lins59** [alexylem/jarvis#348]
Bonjour,

Serait-il possible dans un avenir proche d'utiliser les fonctions définies dans les plugins dans les hooks ?

J'ai créé un plugin jarvis-gpio (que je partagerai dès finalisation) et j'aimerai, dans le hook hooks/program_startup, allumer une lampe (sans devoir utiliser un script externe)

Bonne journée,

**Comment by Lins59** [comment]
A priori, il faut juste inverser les lignes :

ligne 493 jusqu'à 499
`source hooks/program_startup`

`# Include installed plugins
shopt -s nullglob
for f in plugins/*/config.sh; do source $f; done # plugin configuration
for f in plugins/*/functions.sh; do source $f; done # plugin functions
for f in plugins/*/${language:0:2}/functions.sh; do source $f; done # plugin language specific functions`

**Comment by alexylem** [comment]
En fait je pense même qu'il faut aller plus loin.
Il faudrait que les plugins puissent avoir leur propres hooks. Ainsi un plugin pourra allumer une led en mode écoute commande, faire bouger un nabaztag au démarrage, bref tu vois l'idée.
C'est dans l'esprit de ce que tu aimerais faire?

**Comment by Lins59** [comment]
Exécuter une fonction d'un plug-in directement au démarrage me suffirait, c'est juste pour éviter de dupliquer du code. 
Après, dans l'idée, un hook de démarrage par plug-in permettrait d'initialiser des modules plus complexes que ceux actuels.

**Comment by alexylem** [comment]
Heu... l'idée du plugin c'est quand même de partager avec les autres non? Il faut donc que eux aussi rajoutent dans leur hook la fonction du plugin? (d'ou ma proposition).
Après si tu veux juste lancer une fonction de ton plugin au démarrage (pas d'utilisation des autres hooks), tu peux juste l'exécuter dans ton fichier `functions.sh` car il est "sourcé" au démarrage de Jarvis:

**functions.sh**
```shell
pg_gipo_startup() {
   echo "démarrage..."
}

pg_gipo_startup # execute on startup
```

**Comment by Lins59** [comment]
Tout à fait d'accord avec l'idée du plug-in mais mon cas est assez particulier. Je souhaite allumer une lampe avec le module Gpio que j'ai développé et que je vais partager quand il sera fini. Tu peux déjà voir le début dans mon Github. 
Le problème avec la solution que tu proposes, c'est que le hook de start est exécuté PUIS ET SEULEMENT APRÈS les plug-ins sont chargés (cf ligne 497)

**Comment by alexylem** [comment]
Oui j'ai compris.
Mais si tu lis bien mon post d'au dessus, tu peux très bien te passer du hook et exécuter une fonction de ton plugin directement depuis le fichier functions.sh de ton plugin (qui est exécuté au démarrage). Pas besoin de hook 😄 
Regarde dans le code que j'ai mis au dessus.

**Comment by Jean-Bernard-Hallez** [comment]
Bonjour j'ai un soucis en lien avec tout cela... J'ai une Led qui s'allume quand le Programme Tourne, et il ne devrais jamais s'éteindre... il est dans le hook program_startup... il fonctionne bien jusqu'à ce qu'une commande quelconque en provenance de l'API vienne me le couper... snif... que peut-on faire ?

**Comment by alexylem** [comment]
@Jean-Bernard-Hallez tu peux créer un autre ticket? Je pense pas que ca soit le même problème. Ca serait aussi bien de partager ton hook ainsi ca m'aidera à investiger.
Merci.

**Comment by Jean-Bernard-Hallez** [comment]
ok...
