### ISSUE TITLE
possibilité de zapper la reco du mot magique

### ISSUE THREAD

**Issue by remjou1** [alexylem/jarvis#35]
alors voila pour des test j'aurai besoin d'une option (en -quelque-chose ou dans le menu de lancement) qui permettrai de zapper la reco du mot magique... un peu comme l'option -l pour le bouton mais ça permettrais de voir ce qu'il ce passe sur l'écran

**Comment by alexylem** [comment]
Je ne comprends pas l'intérêt de ne plus avoir de mot magique. Car en utilisation normale, avec la reconnaissance permanente Google API, les 50 requêtes par jour seraient vite dépassées.
Pourrais-tu expliquer?
Merci.

**Comment by remjou1** [comment]
ce serait plutot pour une utilisation personnel... travaillant sur beaucoup de script le soir car la journée je n'en ai pas la possibilité, j'aimerais lors de mes test avec jarvis évité de réveillé toute la maison... et devoir répéter "jarvis" plusieurs fois en chuchotant pour que ma femme ne m'entende pas (le bureau est juste a coté de la chambre...), c'est plutôt embêtant... ce serait un peu comme l'option -l pour le bouton mais en mode console...

**Comment by alexylem** [comment]
Pour les tests, les modes Clavier et Muet sont fait pour ca.
