### ISSUE TITLE
Pas de prise en compte du fichier install.sh lors d'un update de plugin

### ISSUE THREAD

**Issue by byackee** [alexylem/jarvis#350]
### Description
Sur le plugin progtv j'ai du modifier le fichier install.sh mais les utilisateurs qui avaient déjà installé ce plugin ne profite pas des améliorations.
Dans mon cas j'ai ajouter une ligne le fichier jarvis-event

Il faudrait réfléchir a prendre en compte peut être pas systématiquement les modifications dans ce fichier install.sh et le lancer dans les updates.

Toujours dans mon cas si on le relance a chaque update ca ajoutera plusieurs fois la ligne dans le fichier jarvis-event

On peut echanger sur ce point :)

**Comment by alexylem** [comment]
@byackee bien sûr qu'on peux. Désolé pour la réponse tardive 😞 
La comme ca je vois 2 possibilités:
* J'exécute le fichier `install.sh` à chaque mise à jour (et tu te charges "remplacer" la ligne au lieu de l'ajouter). Bonjour les dégâts si c'est pas prévu par les auteurs des plugins existants.
* On rajoute un nouveau fichier `update.sh` au modèle des plugins. Et j'exécute ce fichier (s'il existe) à chaque mise à jour. A chacun de l'utiliser comme il se doit. Pour Jarvis j'ai un [script similaire](https://github.com/alexylem/jarvis/blob/master/utils/update.sh) qui regarde la version pour effectuer les tâches nécessaires.
