### ISSUE TITLE
jarvis freeze quand il démarre

### ISSUE THREAD

**Issue by Lemmings15** [alexylem/jarvis#351]
Salut,
j'ai un petit problème avec jarvis ;-) voila ce qu'il se passe

Je lance jarvis avec la commande ./jarvis.sh -v
puis je choisi le mode troubleshooting.

J'entends jarvis me dire "hello" puis fini ;-)

Mon matos :
- raspberry pi 1
- haut parleur noname branché avec un cable
- webcam trust pour le micro

Merci pour l'aide ;-)
Pierre

voila ce que me sort jarvis
------------ Config ------------
jv_version           17.01.09
jv_arch              armv6l
jv_os_name           raspbian
jv_os_version        8
language             fr_FR
play_hw              hw:0,0
rec_hw               hw:1,0
speaker              ALSA
microphone           Trust
trigger_stt          snowboy
command_stt          bing
tts_engine           svox_pico
--------------------------------

DEBUG: program_startup hook
jarvis: Hello
User defined commands:
*AIDE*                  *BONJOUR*|*SALUT*       *COMMENT*APPELLE*
*MERCI*                 *AU REVOIR*|*BYE*       ANNULE*|TERMINE*
ENCORE*                 *TEST*                  *VERSION*
*REPETE (*) ET (*)      *CA VA*                 >*OUI*
>*NON*
Commands from plugin jarvis-time:
*QUELLE HEURE*          *QUEL JOUR*
Commands from plugin jarvis-weather-wunderground-fr:
*METEO*DEMAIN*          *METEO*
jarvis: Waiting to hear 'jarvis'
Sophie: (listening...)
DEBUG: models=alexa,hal,jarvis,snowboy
Cannot connect to server socket err = No such file or directory
Cannot connect to server request channel
jack server is not running or cannot be started
Expression 'paTimedOut' failed in 'src/os/unix/pa_unix_util.c', line: 387
Expression 'PaUnixThread_New( &stream->thread, &CallbackThreadFunc, stream, 1.,                                            stream->rtSched )' failed in 'src/hostapi/alsa/pa_linux_alsa.c', line: 2998
Expression 'pthread_join( self->thread, &pret )' failed in 'src/os/unix/pa_unix_                                           util.c', line: 441

**Comment by Lusitanos67** [comment]
ton speaker et micro son bien paramétré ? Je vois play_hw hw:0,0, ca ne serait pas plutôt play_hw hw:0,1 ?
Lorsque tu lances alsamixer, des soucis particuliers ?

**Comment by Lemmings15** [comment]
Salut,
J'ai remplacé mon micro webcam usb par une carte  DAC USB de chez electrodepot
maintenant ça "fonctionne" il faut juste configurer la sensibilité pour la reconnaissance.

@+
