### ISSUE TITLE
Comment envoyer un mail avec pièce jointe automatiquement

### ISSUE THREAD

**Issue by tchoul** [alexylem/jarvis#352]
Salut à tous!

Voilà j'ai trouvé le système de la liste des courses très interessante, du coup avec les mêmes commandes, j'en ai fais un pense-bête.

Ce que je voudrais, c'est qu'au lieux de dire à Jarvis via Tasker de demander à m'envoyer le mail contenant le pense-bête de me l'envoyer automatiquement tous les 2 jours par exemple.

Je sais que c'est possible avec les évenements déclencheurs, j'ai compris le principe mais je n'arrive pas à l'utilisé. Vous pourriez me donner un exemple pour cette commande ci-dessous?

`*ENVOI*PENSE*==mpack -s "Contenu du pense-bête" /home/pi/pensebete.txt adresse@gmail.com && say "Le pense-bête a été envoyer"`

Merci d'avance!
Thomas

**Comment by oeildefeu** [comment]
la commande mpack fonctionne dans bash ?

**Comment by tchoul** [comment]
Oui nickel! 
Et du coup c'est Domoticz et non jarvis qui m'envoi le message automatiquement

**Comment by oeildefeu** [comment]
au fait, la commande ce ne serait pas plutôt ?
`ENVOI*|PENSE*==...`

**Comment by tchoul** [comment]
Oui! effctivement! en fait c'est : 
*PENSE (*) TERMINE*==....
et
*ENVOI*PENSE*==....
après il y a aussi 
*LI*PENSE*==say ....
*SUPPRIME*PENSE*==...

**Comment by oeildefeu** [comment]
et t'as essayé une commande plus simple a exécuter voir si le problème vient de l'éxécution ou de la reconnaissance de la commande ?

**Comment by tchoul** [comment]
Pour ce qu'il le voudrait, c'est comme la liste des courses!

`*PENSE (*) TERMINE*|*PENSE (*) FIN*|*PENSE (*) STOP*|*PENSE (*) ARRET*==echo "Pense(1)" >> ~/pensebete.txt && say "J'ai ajouté (1) aux pense bête"`
`*SUPPRIME*PENSE*|*VIDE*PENSE*==say "Veux tu confirmer la supression du pense-bête?"`
`>*OUI*==echo "" > ~/pensebete.txt && say "Ok les pense bête sont effacés"`
`>*NON*==say "OK Je ne la supprime pas"`
`*LI*PENSE*|*QUOI*DANS*PENSE*==say "elle contient $(cat ~/pensebete.txt)" `
`*ENVOI*PENSE*MAUD*|*EVOI*PENSE*MOD*==mpack -s "Contenu du pense-bête" /home/pi/pensebete.txt sonmail@gmail.com && say "Les pense bête ont été envoyer à Maud"`
`*ENVOI*PENSE*==mpack -s "Contenu du pense-bête" /home/pi/pensebete.txt monmail@gmail.com && say "Les pense bête ont été envoyer à Thomas"`

**Comment by godinperson** [comment]
Pour ceux qui s'y connaissent moins, est-ce possible pour vous de créer un plugin qu'on aurait simplement à ajouter? On pourrait rajouter les termes: liste d'épicerie, liste d'achats, etc.

Merci!

**Comment by tchoul** [comment]
@godinperson 
Je sais pas faire de plugin désolé, peut être que quelqu'un en fera un... sinon c'est adaptable pour la liste des courses c'est d'ailleur à partir de ça que je suis parti.
Sinon il suffit de le copier/coller dans "jarvis-commands" pour que ça marche, il faut bien évidemment modifier le mail, les mots clé de commande vocale, le nom du fichier.txt et les retours "say"
Il faut aussi installer ssmtp : 
`sudo apt-get install ssmpt`
Ouvrir le fichier ssmtp.conf:
`nano /etc/ssmpt/ssmtp.conf`
Puis le configurer en ajoutant c'est quelque ligne avec tes infos (là c'est pour gmail):
root=adresse@gmail.com
mailhub=smtp.gmail.com:587
hostname=raspberry
AuthUser=adresse@gmail.com
AuthPass=MotDePasseGmail
FromLineOverride=YES
UseSTARTTLS=YES
Puis sauvegarder : Ctrl+X puis O pour oui et entrer

**Comment by godinperson** [comment]
Je vais essayer de créer le plugin avec les instructions. Si je réussis, je vais te mettre une mention spéciale :)

**Comment by tchoul** [comment]
Travail d'équipe :+1: 
Il serait intérressant de faire au moins 2 plugins, 1 pour la listes des courses et un pour le pense-bête
Une fois l'un de créer, l'autre ce fera facilement :-D

**Comment by godinperson** [comment]
Tu ne le verrais pas dans le même toi? Un genre de listeur où plusieurs listes sont disponible

**Comment by tchoul** [comment]
Pourquoi pas!

**Comment by godinperson** [comment]
À tester :)  http://domotiquefacile.fr/jarvis/plugins/pense-b%C3%AAte

**Comment by tchoul** [comment]
C'est vierge ^c^

**Comment by godinperson** [comment]
Haha, j'avais oublié de faire Sync. Là, les infos sont là, je l'ai même traduis pour en Anglais. Sauf que je n'arrives pas à peupler les infos sur le site (qui se fait automatiquement à partir du repo je crois)

**Comment by tchoul** [comment]
fait aussi fr

**Comment by godinperson** [comment]
Bon, j'ai refais le lien sur le site, ça semble beau là! Ouais, j'ai mis En et Fr (si je l'ai fais comme il faut)

**Comment by tchoul** [comment]
pas de fr

**Comment by godinperson** [comment]
Refresh, d'après moi, tu ne dois pas voir la même chose que moi.

https://github.com/godinperson/jarvis-pense-bete

Si tu vas sur ce lien, vois-tu le dossier Fr?

**Comment by tchoul** [comment]
Ah c'est bon avec la mise à jour, je passe par le terminal en ssh c'est pour ça!
Nickel!
Merci de m'avoir mis en en co-auteur ;-)

**Comment by godinperson** [comment]
ça marches alors? On pourra l'améliorer. Pour la liste d'épicerie ou autre, il faudrait qu'on crée d'autres fichiers et qu'on sépares les commandes

**Comment by godinperson** [comment]
Je sais pas si tu as Skype ou autre? Pour les futures collaborations :)

godinperson@ h o t m a i l .com si tu veux m'ajouter.

**Comment by tchoul** [comment]
Va dans tes mails pour contact si tu veux.
Sinon je sais pas ce qui est le mieux... 1 plugin ou plusieurs, certaines personnes ne voudront peut être que l'un ou l'autre, je te laisse voir ça.
Sinon pour la liste des courses :

`*AJOUTE (*) A LA LISTE*==echo "(1)" >> ~/listedescourses.txt && say "J'ai ajouté (1) à la liste"`
`*SUPPRIME*LA LISTE*|*VIDE*LA LISTE*==say "Veux tu confirmer la supression de la liste des courses?"`
`>*OUI*==echo "" > ~/listedescourses.txt && say "Ok la liste est effacée"`
`>*NON*==say "Je ne la supprime pas"`
`*LIS LA LISTE*|*QUOI*DANS*LA*LIS*COUR*==say "elle contient $(cat ~/listedescourses.txt)" `
`*SUPPRIME*LA LISTE*|*VIDE*LA LISTE*==echo "" > ~/listedescourses.txt && say "Voilà c'est vidé"`
`*ENVOI*LA*LIST*MAIL*==mpack -s "Contenu de la liste des courses" /home/pi/listedescourses.txt VOTREMAIL@hotmail.com && say "La liste des courses a été envoyer à VOTREPRENOM"`

**Comment by wikijm** [comment]
Le plugin [jarvis-liste-des-courses](http://domotiquefacile.fr/jarvis/plugins/jarvis-liste-des-courses) semble désormais répondre au besoin.

Ne pas hésitez à ré-ouvrir si besoin :-)
