### ISSUE TITLE
ouvrir un programme sur DISPLAY=:0 et rendre la main à jarvis

### ISSUE THREAD

**Issue by tuxme** [alexylem/jarvis#353]
Je m'explique avec un example : 

voici la partie dans jarvis-commands :

```
*DERNIER*FILM*==lastfilm.sh &
*FERME*NAVIGATEUR*== killall surf && say "navigateur surf fermé"
```

lastfilm.sh a pour boulot de généré un html qui est ouvert (toujours pas lastfilm) avec surf (http://surf.suckless.org/) . Jusqu'a la tout fonctionne ... à part que j'ai beau lui indiqué des '&' dans jarvis-commands ou dans le script (/usr/bin/surf /tmp/$listetmp &) rien n'y fait il ne rend pas la main à jarvis . 

Le but étant de pouvoir continuer à communiquer avec jarvis tout en visualisant un fichier. d'ou le 

```*FERME*NAVIGATEUR* ```

...

Bref ... si quelqu'un a une idée ?

**Comment by tuxme** [comment]
bon j'ai trouvé une méthode ... mais c'est un peu moche quand même. L'idée c'est que les commandes qui ont besoin de rester en vie et en fg doivent être tué par killall mais ne peuvent pas être un porcessus enfant de jarvis. Du coup les script commande que j'utilise génère la commande de lancement et la stock dans un fichier dans /tmp/execute.

A côté de ça au démarrage un script se lance et tourne en arrière plan : 
```#!/bin/bash

while true
	do
		if [[ -f /tmp/execute ]]
			then
				DATA=`cat /tmp/execute`
				if  [[ ! -z $DATA ]]
					then
						echo "[$(date "+%Y%m%d %H%M%s")] : $DATA" > /tmp/debug_watch_and_launch
						bash /tmp/execute
						rm -f /tmp/execute
				fi
		fi
		sleep 3
		echo "."
	 done```

Du coup toutes les X secondes si le fichier existe il l'execute mais jarvis s'en fou puisque ce n'est pas son enfant (l'enfoiré quand même )

Voila c'est pas bien beau mais ça tiens la route. 

Si quelqu'un a une autre idée ...

**Comment by lelive** [comment]
Tu as essayé avec un nohup ?

**Comment by tuxme** [comment]
yep ... je pense que jarvis attend le code retour d'un enfant (même en nohup) pour pouvoir passer à la suite. Du coup : on reste en attente tant que le files n'est pas terminée.

**Comment by alexylem** [comment]
Je regarde, très étonné que le & ne fonctionne pas.
Si c'est effectivement le cas, gros méchant bug...

**Comment by alexylem** [comment]
Le & fonctionne bien chez moi:
```shell
*TEST*==sleep 1 && echo 2 & echo 1
```
Il me rend bien la main avant d'afficher 2.
```yml
Alex: test
1
Alex: blabla2
```

**Comment by wikijm** [comment]
Pas de réponse depuis plusieurs mois, je clôture l'issue.
@tuxme S'il y a de l'évolution, n'hésites pas à le ré-ouvrir 😉
