### ISSUE TITLE
Jarvis via Tasker et Autovoice en écran de veille du téléphone

### ISSUE THREAD

**Issue by tchoul** [alexylem/jarvis#354]
Salut à tous,

Encore moi :-D 2ème ticket de la journée

Voilà, quand j'active "ok google" en mode veille de mon téléphone, et que je dis par exemple"Jarvis allume la lumière du salon", il ne communique pas avec Autovoice/Tasker. 
Pourtant la reconnaissance de "ok google" ce fait même avec une securité, (je l'ai configuré pour en connaissance de cause) mais il va juste chercher sur google alors que si l'appareil n'est pas en veille, celà fonctionne depuis n'importe quelle application.

Est ce que Autovoice, Tasker ou les 2 ne fonctionnent pas en étant en veille?

Il faut dire que l'utilisation serait parfaite si nous n'avions pas besoin de toucher au téléphone.

Merci
Thomas

**Comment by tchoul** [comment]
Régler!
J'ai mis en charge le téléphone, j'avais que 5% de batterie et maintenant ça fonctionne bien en veille et verouillé! trop bien!

**Comment by wikijm** [comment]
Bonjour @tchoul,

Content de voir que tu as pu résoudre ton problème, encore un utilisateur de Jarvis heureux 👍 
Je clôture donc ton ticket.
