### ISSUE TITLE
Problème conf hotword snowboy

### ISSUE THREAD

**Issue by algeroth-jeedom** [alexylem/jarvis#357]
### Description

Bonjour

J'ai enregistré sur le site de snowboy un fichier jarvisse.pmdl
Je l'ai transféré comme écrit sur la doc dans jarvis/stt_engines/snowboy/ressources
J'ai configuré le magic world à "jarvisse"
et dans voice recognition, pour le magic world j'ai selectionné snwoboy
Mais quand je lance jarvis il dit ne pas trouver de fichier mdl...

### Result
jarvisse: Waiting to hear 'jarvisse'
mathieu: (listening...)
DEBUG: models=*mdl

ERROR: personal model for 'jarvisse' not found
HELP: See how to create 'jarvisse.pmdl' here:
HELP: http://domotiquefacile.fr/jarvis/content/snowboy
HELP: Or change your hotword to default model 'snowboy':
HELP: Settings > General > Magic word
DEBUG: program exit handler
DEBUG: program_exit hook

merci ;)

**Comment by algeroth-jeedom** [comment]
Bon en fait pour les ressources, c'est resources avec un seul S et non 2 comme sur la doc ;) 
http://domotiquefacile.fr/jarvis/content/snowboy
@alexylem ;)

Par contre j'ai une erreur il ne trouve pas le fichier snowboydecoder.py
Normal il n'y est pas... lors de la compilation il n'a créé que snowboydetect.py
DEBUG: models=alexa,jarvisse,snowboy
Traceback (most recent call last):
  File "stt_engines/snowboy/main.py", line 1, in <module>
    import snowboydecoder
ImportError: No module named snowboydecoder

Si je pique le snowboydecoder.py dans les fichier exemple de snowboy j'ai cette erreur 
DEBUG: models=alexa,jarvisse,snowboy
Traceback (most recent call last):
  File "stt_engines/snowboy/main.py", line 51, in <module>
    detector = snowboydecoder.HotwordDetector(models, sensitivity=sensitivities)
  File "/home/fa/jarvis/stt_engines/snowboy/snowboydecoder.py", line 91, in __init__
TypeError: __init__() got an unexpected keyword argument 'model_str'

Merci !

**Comment by wikijm** [comment]
Bonjour @algeroth-jeedom,

Est-ce qu'une réinstallation complète est envisageable ?
Cela devrait te permettre de réinstaller l'application snowboy.

**Comment by alexylem** [comment]
@algeroth-jeedom merci j'ai corrigé la doc.
Sinon plus besoin d'enrengistrer le hotword sur le site. On peut désormais directement le faire depuis Jarvis, ce que je te conseille fortement. Soit en modifiant le trigger dans Jarvis. Soit dans le menu:
`Configuration > Voice Reco > Snowboy train a hotword`

**Comment by wikijm** [comment]
Pas de réponse à ma relance et la solution proposée, je clôture l'issue. 
Ne pas hésiter à rouvrir en cas d'avancée.
