### ISSUE TITLE
Jarvis sur ESXi

### ISSUE THREAD

**Issue by Sim7b** [alexylem/jarvis#359]
Bonjour !
Impossible d'installer jarvis sur une VM Esxi, essayé sur debian et ubuntu server.
Toujours le même problème : 
Impossible de trouver le paquet alsamixer
Impossible de trouver le paquet aplay
Impossible de trouver le paquet arecord

Je pense que c'est parce qu'il n'y pas de carte audio..
![image](https://cloud.githubusercontent.com/assets/6420502/21925821/6e8c03ac-d97f-11e6-8fd4-48c9d7cbff3b.png)

Merci !

**Comment by taostaos** [comment]
version de debian?

**Comment by Sim7b** [comment]
8.6.0 netinstall

**Comment by Sim7b** [comment]
Même chose sur une version classique d'Ubuntu

**Comment by wikijm** [comment]
Bonjour @Sim7b,

Ton problème est-il toujours d'actualité ?
Est-ce qu'installer cela pourrait répondre à ton besoin ? https://www.raspberrypi.org/magpi/debian-pixel-mac-pc/

**Comment by wikijm** [comment]
Pas de réponse à ma relance, je clôture l'issue. 
Ne pas hésiter à rouvrir en cas d'avancée.
