### ISSUE TITLE
Utilisation de la reconnaissance vocal

### ISSUE THREAD

**Issue by Ne0ratek** [alexylem/jarvis#36]
Bonsoir,

Je me posais la question est ce que ce serai possible de mettre le dictionnaire de pocket shpinx ailleurs que sur la raspberry pi on pourrait ainsi mettre plus de vocabulaire et ne plus utiliser google qui limite le nombre de requête.
Sinon super taff bravo :+1: 

Cordialement

**Comment by alexylem** [comment]
Oui ici: #9
