### ISSUE TITLE
Failed to install Ubuntu 14.04

### ISSUE THREAD

**Issue by oregapam** [alexylem/jarvis#360]
### Description

Hello,
The problem is, when i want to install with jarvis.sh, the proccess will stop with error 403.
It try to download snowboy by this url:

https://s3-us-west-2.amazonaws.com/snowboy/snowboy-releases/ubuntu1404-x86_64-1.1.0**.tar.bz2.tar.bz2**

I didn't find the line which make the "tar.bz2" written by two times.

### Result
```shell
Requirement already satisfied: pyaudio in /usr/lib/python2.7/dist-packages
2/2 Installation of Snowboy
--2017-01-13 11:29:53--  https://s3-us-west-2.amazonaws.com/snowboy/snowboy-releases/ubuntu1404-x86_64-1.1.0.tar.bz2.tar.bz2
s3-us-west-2.amazonaws.com (s3-us-west-2.amazonaws.com) feloldása… 52.218.144.0
Csatlakozás a következőhöz: s3-us-west-2.amazonaws.com (s3-us-west-2.amazonaws.com)[52.218.144.0]:443… kapcsolódva.
HTTP kérés elküldve, várakozás válaszra… 403 Forbidden
2017-01-13 11:29:54 HIBA 403: Forbidden.
```

**Comment by alexylem** [comment]
It has been fixed since then. Please retry.

**Comment by oregapam** [comment]
Yes it's okay, sorry for the late answer.
