### ISSUE TITLE
Erreur en mode troubleshooting - Please help

### ISSUE THREAD

**Issue by test86** [alexylem/jarvis#362]
Bonjour,

Tout d'abord félicitation pour cet outil qui semble remarquable.
Ceci dit, j'aimerai tellement qu'il fonctionne chez moi !

Dès que je règle un problème, j'en est un nouveau derrière...
Configuration:
Raspberry pi 3.
Raspbian jessie last update.
Jarvis last update.
Ecran pc HDMI (sans enceinte)
Ecouteur apple sur prise jack en guise de son pour le moment.

Après avoir galéré à avoir le son sur mes écouteurs, j'ai de nouveau un problème.
D'après les réglages, tout semble bien configuré.
J'entends bien dans mes écouteur, mon micro semble fonctionner aussi
J'ai mis ma clé token snowboy, et ma clé Bing speech.

Et pourtant en mode Troubleshooting, voici l’erreur que j'ai:

pi@Raspberry:~/jarvis $ ./jarvis.sh

------------ Config ------------
jv_version           17.01.09 
jv_arch              armv7l 
jv_os_name           raspbian 
jv_os_version        8 
language             fr_FR 
play_hw              false 
rec_hw               false 
speaker              Default 
microphone           Default 
trigger_stt          snowboy 
command_stt          bing 
tts_engine           svox_pico 
--------------------------------

DEBUG: program_startup hook
jarvis: Hello
User defined commands:
*AIDE*			*BONJOUR*|*SALUT*	*COMMENT*APPELLE*
*MERCI*			*AU REVOIR*|*BYE*	ANNULE*|TERMINE*
ENCORE*			*TEST*			*VERSION*
*REPETE (*) ET (*)	*CA VA*			>*OUI*
>*NON*
jarvis: Waiting to hear 'jarvis'
Napster: (listening...)
DEBUG: models=alexa,jarvis,snowboy
Cannot connect to server socket err = No such file or directory
Cannot connect to server request channel
jack server is not running or cannot be started

J'en peux plus !!! Please help.
Merci d'avance

**Comment by tigre-bleu** [comment]
```
play_hw false
rec_hw false
```
Ca, ça ne semble pas très bon... Ton audio n'est pas configuré comme il faut.

Soit tu dois le reconfigurer directement dans jarvis (mais attention, ça va écraser ton fichier .asoundrc donc si tu l'avais modifié tu vas perdre le contenu.)
Soit tu mets à la main dans config/rec_hw et config/play_hw les bonnes valeurs de ton périphérique son

**Comment by valentinval90** [comment]
j'ai la meme erreur avec un ecrant tv et en gise de micro une logitec c270.

**Comment by test86** [comment]
Voici le récap.
Je n'ai absolument rien modifié dans les configurations Raspbian ou Jarvis.
Raspbian à été installé ya pas longtemps. Il y a seulement quelques serveurs installés, qui tournent derrières (ssh, vnc, samba, owncloud, vpn)

Je viens de recevoir mon micro (Andoer Omni-Directional) donc première utilisation.
Comme mon ecran (hdmi) n'a pas d'enceinte, je branche mes écouteurs apple sur la prise jack.

Installation de Jarvis, puis configuration.
Là je constate que j'ai pas de son (ni de micro) j'apprends à ce moment là que Jessie envoi le son sur le hdmi car s'est le port qui est détecté par default.
Après de multiples recherches, dont l'installation suivante:
sudo apt-get install alsa-utils & alsamixer
sudo modprobe snd_bcm2835
J'arrive désormais à forcer le son sur la sortie jack.
Et par la même occasion, le micro fonctionne (va savoir pourquoi)

Je reviens donc à la configuration de Jarvis.
J'entends les applaudissements.
J'entends ma douce voix.
Suivant, suivant, je rentre la clé snowboy, suivant, je rentre la clé bing, suivant, terminé.

Bim, je lance Jarvis tout content.
et là, c'est le drame.

jarvis: Waiting to hear 'jarvis'
Napster: (listening...)
DEBUG: models=alexa,jarvis,snowboy
Cannot connect to server socket err = No such file or directory
Cannot connect to server request channel
jack server is not running or cannot be started

Maintenant que tout est clair, du moins je l'espère, pouvez vous me dire ce que je dois faire exactement?
Quel fichier de configuration doit être modifier? pour y mettre quoi ? Que dois-je installer ?
Ou dois-je peut être désinstaller quelque chose puis recommencer ?
Merci pour votre aide.

**Comment by 1nom155** [comment]
Bonjour,

Je rencontre quasiment le même problème que Test86.

J'ai installé Jarvis le 15/01/2017 sur un Raspberry pi 3 en Release: 8.0 et Codename: jessie . 
J'utilise snowboy et bing j'ai rajouter les deux clés des apis pendant l'installation.

Pendant la phase de configuration des enceintes et du micro aucun problème.
Enceinte :  Enceinte USB classique.
Micro : Logitech, Inc. Webcam C210


**test réalisés :** 

**1er test :** 

Je lance jarvis en mode normal. 
Jarvis attend le hotword et j'ai beau parler il ne se passe rien.

**2eme test :** 

Je lance jarvis en mode troubleshooting. 
Je parle il ne se passe rien non plus.

Voici ce qu'il m'affiche :

------------ Config ------------
jv_version           17.01.09
jv_arch              armv7l
jv_os_name           raspbian
jv_os_version        8
language             fr_FR
play_hw              hw:2,0
rec_hw               hw:1,0
speaker              C-Media Electronics, Inc. CM102-A+/102S+ Audio Controller
microphone           Logitech, Inc. Webcam C210
trigger_stt          snowboy
command_stt          bing
tts_engine           svox_pico
--------------------------------

DEBUG: program_startup hook
Starting RestAPI server on http://192.168.1.101:8080
Starting User Interface on http://192.168.1.101:8081
snowboy: Hello
User defined commands:
*AIDE*                  *BONJOUR*|*SALUT*       *COMMENT*APPELLE*
*MERCI*                 *AU REVOIR*|*BYE*       ANNULE*|TERMINE*
ENCORE*                 *TEST*                  *VERSION*
*REPETE (*) ET (*)      *CA VA*                 >*OUI*
>*NON*
Commands from plugin jarvis-ui:
*OUVR*INTERFACE*
Commands from plugin jarvis-api:

snowboy: Waiting to hear 'snowboy'
christophe: (listening...)
DEBUG: models=alexa,snowboy
Cannot connect to server socket err = No such file or directory
Cannot connect to server request channel
jack server is not running or cannot be started

**Enfin 3eme test :** 

 Je lance jarvis avec la commande suivante : ./jarvis.sh -lv

------------ Config ------------
jv_version           17.01.09
jv_arch              armv7l
jv_os_name           raspbian
jv_os_version        8
language             fr_FR
play_hw              hw:2,0
rec_hw               hw:1,0
speaker              C-Media Electronics, Inc. CM102-A+/102S+ Audio Controller
microphone           Logitech, Inc. Webcam C210
trigger_stt          snowboy
command_stt          bing
tts_engine           svox_pico
--------------------------------

DEBUG: program_startup hook
Starting RestAPI server on http://192.168.1.101:8080
Starting User Interface on http://192.168.1.101:8081
User defined commands:
*AIDE*                  *BONJOUR*|*SALUT*       *COMMENT*APPELLE*
*MERCI*                 *AU REVOIR*|*BYE*       ANNULE*|TERMINE*
ENCORE*                 *TEST*                  *VERSION*
*REPETE (*) ET (*)      *CA VA*                 >*OUI*
>*NON*
Commands from plugin jarvis-ui:
*OUVR*INTERFACE*
Commands from plugin jarvis-api:

christophe: (listening...)
utils/timeout.sh 10 rec -V1 -q -r 16000 -c 1 -b 16 -e signed-integer --endian little jarvis-record.wav silence 1 0.1 1% 1 0.5 1% trim 0 10
DEBUG: speech duration was 00 (10 = 1 sec)
DEBUG: token missing or expired
DEBUG: json=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzY29wZSI6Imh0dHBzOi8vc3BlZWNoLnBsYXRmb3JtLmJpbmcuY29tIiwic3Vic2NyaXB0aW9uLWlkIjoiOTllOWI0Y2M2MTYzNDY1MGI4NTI1MzIyODI5YjgyNmIiLCJwcm9kdWN0LWlkIjoiQmluZy5TcGVlY2guUHJldmlldyIsImNvZ25pdGl2ZS1zZXJ2aWNlcy1lbmRwb2ludCI6Imh0dHBzOi8vYXBpLmNvZ25pdGl2ZS5taWNyb3NvZnQuY29tL2ludGVybmFsL3YxLjAvIiwiYXp1cmUtcmVzb3VyY2UtaWQiOiIiLCJpc3MiOiJ1cm46bXMuY29nbml0aXZlc2VydmljZXMiLCJhdWQiOiJ1cm46bXMuc3BlZWNoIiwiZXhwIjoxNDg0NDk1Nzg3fQ.R0KDXPgIEVI6vODbRnvy3GR03tfrIRtzSb4bSAotETI
DEBUG: token will expire in 590 seconds
DEBUG: curl https://speech.platform.bing.com/recognize/query?version=3.0&requestid=f99398ee-68cc-4b89-89a0-9ec6883eef83&appid=D4D52672-91D7-4C74-8AD8-42B1D98141A5&format=json&locale=fr-FR&device.os=linux&scenarios=ulm&instanceid=E043E4FE-51EF-4B74-8133-B728C4FEA8AA&result.profanitymarkup=0
DEBUG: json={"version":"3.0","header":{"status":"success","scenario":"ulm","name":"bonjour","lexical":"bonjour","properties":{"requestid":"56fad3d4-e607-44bb-8fd2-c6a88877fe91","HIGHCONF":"1"}},"results":[{"scenario":"ulm","name":"bonjour","lexical":"bonjour","confidence":"0.9461012","properties":{"HIGHCONF":"1"}}]}
bonjour
$> say "Bonjour $username"
snowboy: Bonjour christophe

**En moyenne il entend une commande puis il m'affiche les messages suivant :** 

christophe: (listening...)
utils/timeout.sh 10 rec -V1 -q -r 16000 -c 1 -b 16 -e signed-integer --endian little jarvis-record.wav silence 1 0.1 1% 1 0.5 1% trim 0 10
DEBUG: speech duration was  (10 = 1 sec)
DEBUG: timeout, end of conversation
DEBUG: exiting_cmd hook
DEBUG: exiting_cmd hook
DEBUG: program exit handler
DEBUG: program_exit hook
pi@Yana:~ $ rec FAIL sox: `default' Device or resource busy: Operation not permitted

J’espère pouvoir faire avancer un peu le problème.

**Comment by tchoul** [comment]
@test86 
Tu as bien enregistré ton Hotword avec le micro 3 fois avec snowboy?

**Comment by tchoul** [comment]
@1nom155 
J'ai vu ça dans ton troubleshooting
```
DEBUG: token missing or expired
DEBUG: token will expire in 590 seconds
```
Tu as bien mis le token?

**Comment by 1nom155** [comment]
@tchoul 
Je viens de vérifier via jarvis UI est les deux token sont bien renseignés.

**Comment by test86** [comment]
@tchoul 
Je viens de vérifié, le mode keyboard fonctionne très bien. (aucune erreur)
Lors de la configuration, j'ai bien renseigné le mot "jarvis" 3x.

**Comment by tchoul** [comment]
Mets bing par exemple en hotword ça devrait marcher en attendant.
Sinon, c'est peut être une erreur de frappe quand tu as mis le token.
Si c'est pas pas le cas, je pense que tu devrais aller voir là ou tu t'es inscris pour avoir le token snowboy et regarder dans : profile settings > Your API token si tu n'as pas dépasser ton quota "You have used 2/1000 of your monthly quota." au cas ou!
Sinon au même endroit, clique sur les flèches bleus pour changer de token et rentres le dans jarvis.

**Comment by test86** [comment]
Après moulte recherche, cela ne marche toujours pas.
Je m'entends très bien dans jarvis lors de la configuration, Il reconnais bien mes écouteur/casque... et mon micro USB Andoer.
Pour les Token, j'ai fais un copier coller, donc aucune erreur.

Je viens de faire la dernière mise à jour Jarvis en 17.01.26.
Et cela ne marche toujours pas en vocal.

Lorsque je fais ./jarvis.sh -v j'obtiens:

pi@Raspberry:~/jarvis $ ./jarvis.sh -v
------------ Config ------------
jv_version           17.01.26 
jv_arch              armv7l 
jv_os_name           raspbian 
jv_os_version        8 
language             fr_FR 
play_hw              false 
rec_hw               false 
speaker              Default 
microphone           Default 
trigger_stt          snowboy 
command_stt          bing 
tts_engine           svox_pico 
--------------------------------


Et en mode Troubleshooting
J'ai toujours l'erreur suivante:

jarvis: Waiting to hear 'jarvis'
Napster: (listening...)
DEBUG: models=alexa,jarvis,snowboy
Cannot connect to server socket err = No such file or directory
Cannot connect to server request channel
jack server is not running or cannot be started

Que dois-je faire svp?

**Comment by mikagouzee** [comment]
Commence par essayer "Jack_control start". Ca lancera le jack server (me demande pas ce que c'est)

Par contre on est nooooombreux dans cette situation.

**Comment by alexylem** [comment]
Salut les gens
Bon déjà:
```
DEBUG: token missing or expired
DEBUG: token will expire in 590 seconds
```
Ce n'est pas un problème. C'est juste que le token doit être re-généré, et il va donc l'être grâce à la clé. Peut-être que je devrais changer le message pour éviter la confusion.

```
jack_control start
```
Va permettre d'éviter l'affichage du message d'erreur
```
jack server is not running or cannot be started
```
Mais même avec ce message d'erreur ca devrait marcher.

Bizarre sur raspberry pi que ca fonctionne avec:
```
play_hw false
rec_hw false
```

Tu peux faire ceci stp:
```
$> cat ~/.asoundrc
```

**Comment by wikijm** [comment]
Clôture du ticket jusqu'à obtention d'une réponse de la part de l'auteur de l'issue.
Closing of the ticket until a valid answer from the applicant is obtained.
