### ISSUE TITLE
Cannot connect to server socket err = No such file or directory

### ISSUE THREAD

**Issue by valentinval90** [alexylem/jarvis#364]
la commande vocal ne se lance pas. apres le demarage de jarvis

copi  

pi@raspberrypi:~/jarvis $ ./jarvis.sh -v

------------ Config ------------
jv_version           17.01.09
jv_arch              armv7l
jv_os_name           raspbian
jv_os_version        8
language             fr_FR
play_hw              false
rec_hw               false
speaker              Default
microphone           Default
trigger_stt          snowboy
command_stt          bing
tts_engine           svox_pico
--------------------------------

DEBUG: program_startup hook
snowboy: salut
User defined commands:
*AIDE*                  *BONJOUR*|*SALUT*       *COMMENT*APPELLE*
*MERCI*                 *AU REVOIR*|*BYE*       ANNULE*|TERMINE*
ENCORE*                 *TEST*                  *VERSION*
*REPETE (*) ET (*)      *CA VA*                 >*OUI*
>*NON*
snowboy: Waiting to hear 'snowboy'
valentin: (listening...)
DEBUG: models=alexa,snowboy
Cannot connect to server socket err = No such file or directory
Cannot connect to server request channel
jack server is not running or cannot be started

**Comment by rebelkov** [comment]
le play_hw et rec_hw est false.
Même si ton pi reconnait le micro et les hauts parleurs, il est necessaire de mettre à jour les valeurs dans le settings>audio (microphone et enceinte )

**Comment by Erim32** [comment]
Bojour, de mon coté, j'ai le meme probleme mais il ne semble pas venir de la:

`
------------ Config ------------
jv_version           17.01.09
jv_arch              armv7l
jv_os_name           raspbian
jv_os_version        8
language             fr_FR
play_hw              hw:0,1
rec_hw               hw:1,0
speaker              ALSA
microphone           Asahi Kasei Microsystems Co., Ltd
trigger_stt          snowboy
command_stt          bing
tts_engine           voxygen
--------------------------------

DEBUG: program_startup hook
Starting RestAPI server on http://172.17.145.19
192.168.1.1:8080
Starting User Interface on http://172.17.145.19
192.168.1.1:8081
snowboy: Bonjour
User defined commands:
*AIDE*                  *BONJOUR*|*SALUT*       *COMMENT*APPELLE*
*MERCI*                 *AU REVOIR*|*BYE*       ANNULE*|TERMINE*
ENCORE*                 *TEST*                  *VERSION*
*REPETE (*) ET (*)      *CA VA*                 >*OUI*
>*NON*
Commands from plugin jarvis-ui:
*OUVR*INTERFACE*
Commands from plugin jarvis-time:
*QUELLE HEURE*          *QUEL JOUR*
Commands from plugin jarvis-minuterie:
*EFFACE*MINUTE*         *MINUTE*                >(*)
Commands from plugin jarvis-api:

snowboy: Waiting to hear 'snowboy'
Rémi: (listening...)
DEBUG: models=alexa,jarvis,snowboy
Cannot connect to server socket err = No such file or directory
Cannot connect to server request channel
jack server is not running or cannot be started`

pi@raspberry:~ $ cat ~/.asoundrc
pcm.!default {
  type asym
   playback.pcm {
     type plug
     slave.pcm "hw:0,1"
   }
   capture.pcm {
     type plug
     slave.pcm "hw:1,0"
   }
}`

**Comment by Lusitanos67** [comment]
Idem même soucis, les hp et le micro sont bien paramétrés, tout fonctionne, mais le fait que ce message d'erreur s'affiche m'intrigue

**Comment by mikagouzee** [comment]
Same problem (j'ai ouvert une issue aussi mais visiblement on est plusieurs avec ce souci)

**Comment by alexylem** [comment]
Voir https://github.com/Kitt-AI/snowboy/issues/9#issuecomment-241577381
```
Cannot connect to server socket err = No such file or directory
Cannot connect to server request channel
jack server is not running or cannot be started
```
**Solution**
```
jack_control start
```
Vous pouvez tester et me dire si ca marche?

**Comment by Lusitanos67** [comment]
Pas installé chez moi... hum... Je suis parti d'une raspbian lite, c'est peut-être normal ?

**Comment by mikagouzee** [comment]
Je ferai les tests ce soir, je suis au taf la.

2017-01-28 23:42 GMT+01:00 Lusitanos67 <notifications@github.com>:

**Comment by Lusitanos67** [comment]
Quelqu'un a pu tester ?

**Comment by mikagouzee** [comment]
Noooooon sorry j'ai été super pris par le taf.

Je ferai le test ce soir, promis craché.

Si ça ne marche pas, tu as déjà une autre piste?

**Comment by Lusitanos67** [comment]
Non, j'ai tenté d'installé jack, mais rien de très probant sur quoi/comment installer...
J'ai testé d'installé jackd, et qjackctl, il ne reconnait pas "jack_control", alors bon j'ai désinstallé, mais je crois que mon os est pourri maintenant, car même en ayant désinstallé les paquets que je venais d'installer, il me retrouve toujours la commande "jack_xxxxx"...

Là j'avoue être perdu

**Comment by mikagouzee** [comment]
Je viens de tester : 

pi@madmanwithabox:~ $ jack_control start
--- start
pi@madmanwithabox:~ $ 
pi@madmanwithabox:~ $ 
pi@madmanwithabox:~ $ cd jarvis/
pi@madmanwithabox:~/jarvis $ ./jarvis.sh

------------ Config ------------
jv_version           17.01.26 
jv_arch              armv7l 
jv_os_name           raspbian 
jv_os_version        8 
language             en_GB 
play_hw              hw:0,1 
rec_hw               hw:1,0 
speaker              ALSA 
microphone           Texas Instruments PCM2900 Audio Codec 
trigger_stt          snowboy 
command_stt          snowboy 
tts_engine           svox_pico 
--------------------------------

DEBUG: program_startup hook
canine: Yes, Master ?
User defined commands:
*AIDE*			*BONJOUR*|*SALUT*	*COMMENT*APPELLE*
*MERCI*			*AU REVOIR*|*BYE*	ANNULE*|TERMINE*
ENCORE*			*TEST*			*VERSION*
*REPETE (*) ET (*)	*CA VA*			>*OUI*
>*NON*
canine: Waiting to hear 'canine'
Doctor: (listening...)
DEBUG: models=alexa,canine,snowboy
INFO:snowboy:Keyword 2 detected at time: 2017-02-01 17:28:13
DEBUG: modelid=1
canine
DEBUG: entering_cmd hook
canine: Yes?
Doctor: (listening...)
DEBUG: models=alexa,canine,snowboy
INFO:snowboy:Keyword 2 detected at time: 2017-02-01 17:28:17
DEBUG: modelid=1
canine
canine: I did not understand: canine
Doctor: (listening...)
DEBUG: models=alexa,canine,snowboy
INFO:snowboy:Keyword 2 detected at time: 2017-02-01 17:28:22
DEBUG: modelid=1
canine
canine: I did not understand: canine
Doctor: (listening...)
DEBUG: models=alexa,canine,snowboy
^CDEBUG: program exit handler
DEBUG: program_exit hook


j'ai quitté le prog ensuite en mode ctrl + C mais je peux attendre à mon avis TRES longtemps (j'ai attendu min montre en main, il ne se passe rien...)

Une idée?

**Comment by Lusitanos67** [comment]
Sais-tu quel dépendance il faut installer pour avoir la command jack_control qui fonctionne ?

C'est normal que tu es: language en_GB
As-tu fais raspi-config pour le changer en FR ?

**Comment by Lusitanos67** [comment]
Bon après avoir installé jackd2, puis lancer jack_control via une interface graphique (sinon jack ne se lance pas), je n'ai plus le message d'erreur. 
Par contre y a t-il une solution pour éviter de lancer l'interface graphique, et utiliser des ressources inutiles dans mon cas, je fais tout via ssh et putty ?

**Comment by idem2lyon** [comment]
meme probleme ici sur une install raspbian lite propre.

**Comment by Lusitanos67** [comment]
J'avais dû installer le serveur graphique @idem2lyon , puis jackd2, et l'installer via l'interface graphique...
Mais je ne comprends pas pourquoi...

**Comment by mikagouzee** [comment]
J'ai essayé en mettant Jarvis en fr, mais ça ne marche pas mieux. (Et comme
il parle quand même en anglais, c'est assez horrible en fait xD "iesse
masté?" )

J'ai déjà fait la réinstall de ma machine deux fois, donc je préfèrerais
une autre solution. Je veux bien chercher un peu, mais installer un GUI
pour jarvis ne me semble pas lié au problème rencontré...

**Comment by idem2lyon** [comment]
Je rejoins ton point de vue.
J'ai fait l install il y a 1 mois, et je n'avais pas rencontré ce problème.
Cette semaine, en reprenant tout depuis zero, j'ai ce message etrange.

**Comment by Lusitanos67** [comment]
Je n'ai pas dis que le GUI était la solution, cependant pour moi cela a été une seconde cause du non lancement de jack. La solution étant de lancer jack comme l'a précisé Alex.
Dans mon cas et depuis une install fresh raspbian, si je tente de lancer jack, il m'indique qu'il ne peut pas car le mode graphique n'est pas lancé, c'est ce que je partageais.


A part la

**Comment by idem2lyon** [comment]
oui, j'entends bien !!
Mais mes précedentes install, je n'avais pas besoin de X pour faire fonctionner jarvis.
etrange...

**Comment by idem2lyon** [comment]
Bon, je viens de refaire une raspbian jessie fraiche.
J'ai créé un user, avec les meme droit que le user pi (meme groupes).
Je refais la procédure, et toujours pareil.

idem@raspberrypi:/opt/jarvis $ ./jarvis.sh -nv
Checking updates for jarvis...Up-to-date

------------ Config ------------
jv_version           17.01.26
jv_arch              armv6l
jv_os_name           raspbian
jv_os_version        8
language             fr_FR
play_hw              hw:0,0
rec_hw               hw:1,0
speaker              ALSA
microphone           Asahi Kasei Microsystems Co., Ltd
trigger_stt          snowboy
command_stt          bing
tts_engine           svox_pico
--------------------------------

DEBUG: program_startup hook
julia: Hello
User defined commands:
*AIDE*                  *BONJOUR*|*SALUT*       *COMMENT*APPELLE*
*MERCI*                 *AU REVOIR*|*BYE*       ANNULE*|TERMINE*
ENCORE*                 *TEST*                  *VERSION*
*REPETE (*) ET (*)      *CA VA*                 >*OUI*
>*NON*
julia: Waiting to hear 'julia'
idem: (listening...)
DEBUG: models=alexa,julia,snowboy
Cannot connect to server socket err = No such file or directory
Cannot connect to server request channel
jack server is not running or cannot be started

Il y a vraiment un bug quelque part.
Quelqu'un a essayé de refaire le test?

**Comment by Lusitanos67** [comment]
Ben à priori la dernière release de raspbian en est la cause non ?
Il faudra pouvoir tenter avec une plus ancienne

**Comment by idem2lyon** [comment]
tu veux plutot dire que Jarvis c'est plus compatible avec les dernieres mise à jour de Debian Jessie?
@alexylem as tu pu faire un test dis-moi ?

**Comment by Lusitanos67** [comment]
Surement une dépendance qui n'est plus présente dans les dernières versions à priori.

**Comment by idem2lyon** [comment]
Je teste dans la soirée avec les 3 dernières release, on verra bien....

**Comment by alexylem** [comment]
Le tuto d'install recommande raspbian full.
Certains on réussi à faire marcher sur lite, comme ici: https://github.com/alexylem/jarvis/issues/341

**Comment by idem2lyon** [comment]
bon, ben pas mieux puisque lors de la conf de jarvis, il fait les mises à jour :(

**Comment by alexylem** [comment]
Bon je télécharge les dernières version de Jessie (lite et full) afin de retester l'installation complète de Jarvis sur un raspberry pi 1 que j'ai sous la main.

**Comment by Lusitanos67** [comment]
c'est cool merci Alex

**Comment by idem2lyon** [comment]
super, merci @alexylem

**Comment by themask38** [comment]
# bonjour, j'ai une erreur qui se rapproche de la votre, cependant, je ne sais pas comment la résoudre voici mon erreur :

snowboy: Waiting to hear 'snowboy'
nicolas: (listening...)
DEBUG: models=alexa,snowboy

**Comment by wikijm** [comment]
Bonjour @themask38,

Peux-tu créer une "capture" de ton terminal avec https://asciinema.org/ ou le logiciel [ScreenToGIF](http://www.screentogif.com/) ?
Il serait également intéressant que tu fasse des tests en mode troubleshooting, pour ensuite en partager les résultats.

**Comment by themask38** [comment]
bonjour @wikijm 

j'étais en mode troubleshooting et j'ai réussi a installer pocketsphinx et ca marche très bien alors je ne vois pas l'interet a utiliser snowboy  ?

**Comment by Stan92** [comment]
Suis également preneur de solutions :-) 
J'ai essayé de faire ce qui a été précisé à travers les différents posts mais en vain..

**Comment by alexylem** [comment]
>je ne pense pas que c'est vraiment une erreur mais "snowboy" n'est pas compris alors que je dis snowboy. ???
Rien ne s'affiche d'autre dans le terminal?
Tu es bien sur raspberry pi avec raspbian jessie full?
Si ca ne marche pas, essaye de bien le prononcer à l'anglaise (snaoubohii)
Sinon vérifie les réglages de ton micro, sensibilité par exemple... parle proche et clairement.

**Comment by idem2lyon** [comment]
@alexylem alors, tu as pu refaire le test?

**Comment by alexylem** [comment]
Pas encore j'étais occupé à #366 ... Dès que j'ai un moment je me lance la dedans.

**Comment by alexylem** [comment]
Je suis en train de refaire une installation raspbian jessie lite (latest) sur un raspberry pi 1 qui traine. Je vous tiens au courant.

**Comment by alexylem** [comment]
Bon ca y est j'ai fini l'installe sur un Raspberry Pi 1 avec Raspbian Jessie Lite.
* Raspberry Pi 1, modèle B
* Distribution: `2017-01-11-raspbian-jessie-lite`

A part `git` je n'avais installé aucun paquet, même pas de `sudo apt-get update`.

Tout s'est bien passé jusqu'à l'installation de `snowboy` qui lors de:
```shell
$> apt-get install -y python-pyaudio python3-pyaudio libatlas-base-dev
```
m'a craché un beau
```shell
E: Le pilote pour la méthode /usr/lib/apt/methods/https n'a pu être trouvé.
N: Is the package apt-transport-https installed?
```
J'ai commencé à chercher comment résoudre ça, mais en relançant l'installation (pour récupérer le message/moment exact...), tout s'est bien passé 😡 

Snowboy a parfaitement fonctionné du premier coup avec mon micro Yeti:
```
snowboy: Waiting to hear 'snowboy'
pi: (listening...)
DEBUG: models=alexa,snowboy
Cannot connect to server socket err = No such file or directory
Cannot connect to server request channel
jack server is not running or cannot be started
INFO:snowboy:Keyword 2 detected at time: 2017-02-24 21:05:05
DEBUG: modelid=1
snowboy
DEBUG: entering_cmd hook
snowboy: Yes?
```
à part qu'il affiche ces lignes dont je dois essayer de me débarrasser automatiquement:
```
Cannot connect to server socket err = No such file or directory
Cannot connect to server request channel
jack server is not running or cannot be started
```

Il faudrait que je reflash ma carte SD pour repartir de zéro et essayer d'éviter l'erreur `apt-transport-https`, mais pour le moment trop la flemme 😄 

**Bottom line** c'est 👍  pour Rasbpian Jessie Lite.

**Comment by wikijm** [comment]
@alexylem Question idiote, mais as-tu iinstallé le package apt-transport-https ?
Si tu pars d'un NOOBS ou Raspbian Lite/Full, le package n'est pas installé par défaut.

**Comment by alexylem** [comment]
@wikijm non comme je disais je suis parti d'une installe toute propre comme le ferait la plupart des utilisateurs noobs de Jarvis. Je tiens donc à ce que ce soit el plus facile possible et éviter ce genre de désagrément. Je vais donc l'ajouter au script d'installation de snowboy.

**Comment by alexylem** [comment]
Todo:
- [ ] résoudre / masquer les messages d'erreur:
```
Cannot connect to server socket err = No such file or directory
Cannot connect to server request channel
jack server is not running or cannot be started
```
- [ ] ajouter `apt-transport-https` au script d'installation de snowboy.

**Comment by wikijm** [comment]
@alexylem Je viens d'intégrer l'issue dans https://github.com/alexylem/jarvis/projects/1 ;-)

**Comment by MulhollandDr** [comment]
Bonjour à tous,

j'ai moi aussi le même problème à savoir : 

```
Cannot connect to server socket err = No such file or directory
Cannot connect to server request channel
jack server is not running or cannot be started
```

Si j'ai bien compris il s'agit d'un problème de priorités de carte son ? Quand j'utilise la bonne entrée (en mode graphique) Jarvis semble fonctionner en mode normal. Par contre si j'utilise le mode "Trouble" Jarvis me donne l'erreur citée plus haut et ce même si je viens de configurer graphiquement la bonne carte son. (En gros j'ai l'impression que le mode "trouble" force le retour à la carte son par défaut.)

J'ai tenté de modifier le fichier asoundrc, ça ne change rien (le problème est réglé temporairement en mode normal mais il suffit de lancer le mode "Trouble" ou de relancer Jarvis pour que la carte par défaut réapparaisse.  

Edit : En fait la carte son par défaut revient également au bout d'un certain temps en mode normal.

Y a t il un moyen de changer définitivement les priorités des cartes sons ?

Merci à tous.

**Comment by alexylem** [comment]
J'avais réussi à résoudre (manuellement) tous ces message d'erreur sur mon install de Jarvis principale. Je vais me replonger dedans et tenter de vous proposer une solution automatisée.

**Comment by MulhollandDr** [comment]
Wahou quelle rapidité !
Merci beaucoup pour l'aide.

**Comment by alexylem** [comment]
Bon la solution pour virer:
```shell
Cannot connect to server socket err = No such file or directory
Cannot connect to server request channel
jack server is not running or cannot be started
```
Est de:
```shell
$> jack_control start
```
Or sur un Raspbian lite:
```shell
-bash: jack_control: command not found
```
J'ai donc installé 25 Mo de packets...
```
$> sudo apt-get install jackd2
```
Mais:
```shell
$> jack_control start
[...]
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.NotSupported: Unable to autolaunch a dbus-daemon without a $DISPLAY for X11
```
Ce qui confirme [ce que disait](https://github.com/alexylem/jarvis/issues/364#issuecomment-277202277) @Lusitanos67 
Donc à part une solution pourrie (cacher tout l'output de snowboy), je sèche...

**Comment by Jean-Bernard-Hallez** [comment]
Bonjour suite à un bug de mon coté qui n' a rien a voir a la base, le passe par le troubeshotting et il me renvoie le même message que vous:  (la source de mon mproblème n'est pas là... mais il est vrai que je me suis posé des question et j'ai vu ce ticket...).

Cannot connect to server socket err = No such file or directory
Cannot connect to server request channel
jack server is not running or cannot be started

j'ai bien le même message sur les 2 raspberry lorsque je passe en troubeshotting  ....

**Comment by alexylem** [comment]
Oui et comme je l'ai expliqué, tu peux les enlever avec:
```shell
$> jack_control start
```
Si toutefois tu as cette commande disponible.

**Comment by MulhollandDr** [comment]
Bonjour,

la commande jack_control était dispo pour moi et ça a bien réglé le problème. (Bon j'ai maintenant un autre problème mais je vais fouiller dans le coin voir si quelqu'un a pas déjà eu la même chose).

Merci.

**Comment by Jean-Bernard-Hallez** [comment]
jack_control start se lance mais sans résultat... le retour: (a savoir que j'ai un micro jabra410 un peu particulier)

Traceback (most recent call last):
  File "/usr/bin/jack_control", line 399, in <module>
    main()
  File "/usr/bin/jack_control", line 158, in main
    bus = dbus.SessionBus()
  File "/usr/lib/python2.7/dist-packages/dbus/_dbus.py", line 211, in __new__
    mainloop=mainloop)
  File "/usr/lib/python2.7/dist-packages/dbus/_dbus.py", line 100, in __new__
    bus = BusConnection.__new__(subclass, bus_type, mainloop=mainloop)
  File "/usr/lib/python2.7/dist-packages/dbus/bus.py", line 122, in __new__
    bus = cls._new_for_bus(address_or_type, mainloop=mainloop)
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.NotSupported: Unable t                                                                                                                                                             o autolaunch a dbus-daemon without a $DISPLAY for X11

**Comment by alexylem** [comment]
@Jean-Bernard-Hallez regarde ce que j'ai écris [4 posts plus haut](https://github.com/alexylem/jarvis/issues/364#issuecomment-283106216), j'ai eu la même erreur

**Comment by Jean-Bernard-Hallez** [comment]
@alexylem Oui je l'ai vu et j'ai essayé..
jack_control start
sudo apt-get install jackd2

ca bug toujours... ou j'ai pas suivi un truc désolé...

**Comment by MulhollandDr** [comment]
Bonjour à tous,

je ne sais pas si je vais faire avancer le truc mais voila a priori chez moi le jack_control je l'ai pas en ssh mais je l'ai si je suis directement sur le pi.

**Comment by alexylem** [comment]
Commme je l'ai écris plus haut, en référence au post de @Lusitanos67, il faut avoir l'interface X installée pour que ca marche.

**Comment by Jean-Bernard-Hallez** [comment]
Oups... je n'avais pas bien lu.... Il faut le mettre en gras pour les gas comme moi... lol... j'essayerai cela.... Grave...   ;-)

**Comment by colas31** [comment]
Voila la procédure qui a résolu le problème quand vous êtes seulement en ssh : 
sudo apt-get install dbus-x11
sudo apt-get install jackd2
dbus-launch jack_control start

**Comment by Jean-Bernard-Hallez** [comment]
Yes ça a marché pour moi aussi avec cette méthode !!! Merci @colas31   !!!!!

**Comment by alexylem** [comment]
Marché sur Raspbian lite? Ou avec X11 installé?
Voir [mon post](https://github.com/alexylem/jarvis/issues/364#issuecomment-283106216) ci-dessus.

**Comment by colas31** [comment]
@alexylem  De mémoire c'était un Raspbian lite. Aucun écran connecté sur mon rasp.

Et oui j'avais lu toute la conversation avant de poster. Ma réponse permet d'éviter l'erreur que tu avais cité. 
Comme tu as pu le voir dans les commandes j'ai dû installer x11.

En fait le dbus-launch : permet de démarrer un bus session depuis un script shell et donc d'éviter l'erreur

**Comment by NYGHOST** [comment]
salut a tous pareil pour moi tout marchait nikel avec l'ancien jarvis (avant UI et API) meme erreur, une solution non ssh?

**Comment by alexylem** [comment]
@NYGHOST comment ca non ssh ?

**Comment by NYGHOST** [comment]
je reprends, j'ai jack2d déja installé, j'ai lancé jack les messages d'erreurs sont bien supprimé mais je n'ai toujours rien niveau vocal alors que l'ancienne version fonctionne bien des idées?

**Comment by NYGHOST** [comment]
ok une autre cause d'erreur peut etre due ( dans mon cas) au fonctionnemeent en parrallele d'un serveur node occupant en plus le port 8080. 
pb résolu de mon coté. merci @alexylem

**Comment by alexylem** [comment]
Pour info sur la branch beta j'ai mis une nouvelle version de snowboy utilisant rec au lieu de pyaudio. Donc à priori il ne devrait plus y avoir aucune erreur ALSA.
