### ISSUE TITLE
Plugin Google search

### ISSUE THREAD

**Issue by alex67000** [alexylem/jarvis#365]
Bonjour, je viens de découvrir un plugin qui s'avère être très intéressant, il est en fonction sur assistant virtuel theadrianproject, c'est le plugin Google search, on peut demander ce qu'on veut comme OK google, serait il possible de l'adapter pour Jarvis? On se rapproche de Amazon écho, réponse à tout ;)

**Comment by oeildefeu** [comment]
Salut,
j'ai jeté un oeil à leur "module" [ici](https://github.com/TheAdrianProject/AdrianSmartAssistant/blob/master/Modules/Google/Google.js) en fait c'est un peu bof (peut être efficace mais bof).
En résumé: ils lancent une requête vers google du type`https://www.google.fr/search?hl=_LANG_&oe=utf8&q=_QUESTION_&num=1`
Ensuite ils sauvegardent le résultat de la page dans un fichier puis le parse pour détecter la réponse. La méthode de détection de la réponse me semble vraiment bof... 
un moyen peut-être plus propre au niveau de la détection de la réponse serait de détecter plutôt la balise "card-section" qui semble contenir tout le temps la réponse, quand elle est connue de google search

**Comment by alex67000** [comment]
Merci pour ta réponse oeildefeu, disons que le principe est intéressant, style OK google ou cortana,  et ça serait plutôt du genre Amazon echo, hélas mes connaissances sont assez limité pour la création de ce plugin

**Comment by wikijm** [comment]
#282 existe déjà sur ce sujet. Je clôture histoire d'éviter les doublons.
