### ISSUE TITLE
Snowboy recognition failed

### ISSUE THREAD

**Issue by hazenote** [alexylem/jarvis#367]
Bonjour j'ai commencer a bosser depuis hier soir sur jarvis et pendant la configuration les haut parleur marcher trés bien le micro aussi mais quand je lance jarvis 2 erreur arrivent 

soit il attend que je dise 'snowboy' et ne le detecte jamais 
soit il me fait une erreure directe 'snowboy recognition failed'

voila le troubleshooting

Je ne comprends pas vraiment d'où le problème peut venir. J'espère que vous pourrez m'aider.

Merci d'avance

------------ Config ------------
jv_version           17.01.09
jv_arch              armv7l
jv_os_name           raspbian
jv_os_version        8
language             en_GB
play_hw              hw:0,1
rec_hw               hw:1,0
speaker              ALSA
microphone
trigger_stt          snowboy
command_stt          bing
tts_engine           svox_pico
--------------------------------

DEBUG: program_startup hook
snowboy: Hello
User defined commands:
*AIDE*                  *BONJOUR*|*SALUT*       *COMMENT*APPELLE*
*MERCI*                 *AU REVOIR*|*BYE*       ANNULE*|TERMINE*
ENCORE*                 *TEST*                  *VERSION*
*REPETE (*) ET (*)      *CA VA*                 >*OUI*
>*NON*                  *METEO*
snowboy: Waiting to hear 'snowboy'
jerome: (listening...)
DEBUG: models=alexa,snowboy
Cannot connect to server socket err = No such file or directory
Cannot connect to server request channel
jack server is not running or cannot be started
Traceback (most recent call last):
  File "stt_engines/snowboy/main.py", line 51, in <module>
    detector = snowboydecoder.HotwordDetector(models, sensitivity=sensitivities)
  File "/home/pi/jarvis/stt_engines/snowboy/snowboydecoder.py", line 115, in __i                                                                                                                     nit__
    stream_callback=audio_callback)
  File "/usr/lib/python2.7/dist-packages/pyaudio.py", line 747, in open
    stream = Stream(self, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/pyaudio.py", line 442, in __init__
    self._stream = pa.open(**arguments)
IOError: [Errno Invalid input device (no default output device)] -9996
DEBUG: modelid=-10
ERROR: snowboy recognition failed
DEBUG: program exit handler
DEBUG: program_exit hook

**Comment by hazenote** [comment]
Tout vas mieux je sais pas pourquoi toutes les erreurs sont plus la !

**Comment by alexylem** [comment]
#415
