### ISSUE TITLE
lanceur de commande

### ISSUE THREAD

**Issue by NYGHOST** [alexylem/jarvis#37]
question peut être conne mais je souhaite a la manière de Jasper, lancer un fichier .py en fonction de la commande vocale.
super projet, ton outils offre de nombreuses possibilités.

**Comment by remjou1** [comment]
c'est-a-dire ? t'as juste a faire
```
*LANCE*FICHIER*== sudo python le_fichier.py
```

**Comment by NYGHOST** [comment]
Okk je voyais ca genre say"'lefichier.py'" 

Envoyé de mon iPhone

**Comment by remjou1** [comment]
je pense que tu peu le faire en suivant cette structure : 
```
*LANCE (*)== python (1).py
```
par contre ton fichier devra etre composé d'un seul mot... Essaye et dis moi si ça marche ;)

**Comment by NYGHOST** [comment]
Bien sur je te tiens au courant 

Envoyé de mon iPhone

**Comment by alexylem** [comment]
Si tu veux faire dire le résultat du fichier python, c'est plutôt:
```
TA COMMANDE==say "`python lefichier.py`"
```
Attention ne pas oublier les quotes inversées > **\`** <

**Comment by NYGHOST** [comment]
#remjou1
nikel c'est ce que je voyais marche nikel a voir avec plus de test merci encore
