### ISSUE TITLE
Jarvis s'allume meme quand je ne lui parle pas 

### ISSUE THREAD

**Issue by hazenote** [alexylem/jarvis#370]
Bonjour ! je viens pour vous demander des conseils,en effet cela fait quelques jours que j'utilise jarvis 
et un des soucis,voir le seul que j'ai est que 

'alexa' c'est son nom devrait ne s'allumer que quand son hotkey est prononcé,
le soucis est justement la du moment que elle entend un son elle s'allume alors que justement je ne veux que elle s'allume que si je lui adresse la parole.

Je ne peux pas publier le troubleshooting tout de suite je suis au boulot mais si vous avez deja quelques conseils  je suis preneur, merci et bonne journee

**Comment by tchoul** [comment]
Peut être un mauvais enregistrement du hotword avec snowboy, essaye de le refaire. Sinon peut être un faux positif, par exemple avec la télé "alex"

**Comment by hazenote** [comment]
Merci mais du coup  le probleme c'est que j'ai deja refait le hotword 3 fois :'(

**Comment by tchoul** [comment]
Réglage du micro peut être... test en troubshooting voir si il entend correctement ta voix

**Comment by hazenote** [comment]
Ah oui d'accord je le fais ce soir. je vous enverrais aussi le troubleshooting
