### ISSUE TITLE
Commande pour faire parler jarvis.

### ISSUE THREAD

**Issue by hazenote** [alexylem/jarvis#371]
Ce n'est pas vraiment un probleme mais j'aimerais juste savoir si cela existe ou est possible :D 

a distance j'arrive a rentrer en ssh a l'interface de jarvis 

du coup j'aimerais savoir si en mode keyboard par exemple il existerais une commande pour dire a jarvis de dire tel ou tel phrase a voix haute ?

Par exemple pour faire une blague,si je sais que tel personne est dans mon salon j'aimerais pouvoir dire a jarvis de dire '*nom de la personne* comment vas tu ?' vraiment que je puisse faire dire n'importe quoi a jarvis a distance via ssh

Merci
desolé si la commande est simple ou si vous trouver ma question debile mais je debarque vraiment dans ce petit monde 💃 
```

**Comment by Andes2k** [comment]
`say "Je vais dire ceci à voix haute"`

Je te laisse voir plus de commandes ici : 
http://domotiquefacile.fr/jarvis/content/commands

**Comment by kiki51** [comment]
Via jarvis UI, tu peux le faire.
Regarde le plug in en detailles ( j'ai fais la blague la semaine derniere !)

**Comment by tchoul** [comment]
Je confirme ça marche très bien à distance avec le téléphone.

Il faut installer Jarvis-API et suivre le tuto sur le site : "contrôle Jarvis from" puis "android device"

**Comment by hazenote** [comment]
d'accord je vais voir tout ca mais chez moi j'ai que des termiaux ios :'(

**Comment by kiki51** [comment]
Pas grave. C'est du http.... Du moment que tu as un navigateur internet c'est bon.
Ca marche dans mon cas sur Windows phone avec le navigateur de base.
Jai essaye sur iPad c'est ok aussi.

**Comment by hazenote** [comment]
Merci a tous je vais allez voir tous ca

**Comment by LordDarkneo** [comment]
Hello! Je déterre un peu le ticket pour savoir si on peut lancer une commande Say via une requête http... 
En gros, j'ai un scenario Domoticz quand je rentre et quand je pars, et j'aimerai que Jarvis me dise les commandes qui sont lancées. Genre quand je pars:
say = "Au revoir. Je m'occupe de lancer l'alarme, la surveillance vidéo et je passe l chauffage en mode éco. Bonne journée".

un truc du style http://IpduRPIJarvis/action.json?say="Au revoir. Je m'occupe de lancer l'alarme, la surveillance vidéo et je passe l chauffage en mode éco. Bonne journée"

EDIT: Ah ben en fait trouvé sur #273... j'étais pas loin! http://IpduRPIJarvis/?say="Au revoir. Je m'occupe de lancer l'alarme, la surveillance vidéo et je passe l chauffage en mode éco. Bonne journée"
Je teste ce soir 👍
