### ISSUE TITLE
LiveboxTv avec jarvis

### ISSUE THREAD

**Issue by hazenote** [alexylem/jarvis#372]
Re-Bonjour tout le monde j'espere ne pas trop polluer depuis hier avec mes nombreuses question 
mais voila 

Aujourdhui j'ai voulu bosser avec le plugin liveboxTV pour controler avec jarvis 
et enfaite tout betement j'ai pas compris comment ca marcher ?

J'ai editer le .sh pour y mettre l'ip de ma box mais je ne comprend pas ce que il faut faire par la suite ?

Merci beaucoup

**Comment by hazenote** [comment]
Car tout betement j'ai par la suite allumer jarvis et demander 'allume' ou 'change de chaine' et a chaque fois il ne comprenais pas et j'ai éte supris que dans doc sur le 'store' il n'y aie pas une liste ou du moins un exemple de commandes :-/

**Comment by tchoul** [comment]
Moi j'ai freeboxtv mais ça doit être le même principe. Il faut le configurer avant, donc mettre ton IP mais aussi ta clé de la télécommande dans l'url http....key=TaClé
Après pour voir ou modifier les commandes, il faut dans /home/pi/jarvis/plungins/fr_liveboxtv/ et taper 
`nano commands`

**Comment by hazenote** [comment]
Merci c'est ca qui me manquer :-)

**Comment by hazenote** [comment]
Alors d'accord avec ton chemin d'accee j'ai trouver les commandes j'ai fait expres de dire ce qui avait ecrit 
c'etait *allume la laveboxe* je l'ai dit tel quel et jarvis me retourne une erreur car il ne comprend pas l'action

**Comment by tchoul** [comment]
J'ai installé le plugin pour voir et il y a un problème apparemment... il m'a mis le dossier commande dans /home/pi/jarvis/plugins/fr_liveboxtv/ au lieu de /home/pi/jarvis/plugins/fr_liveboxtv/fr
Du coup tape :
`cd /home/pi/jarvis/plugins/fr_liveboxtv/`
`mkdir fr`
`cp commands /home/pi/jarvis/plugins/fr_liveboxtv/fr/`

**Comment by hazenote** [comment]
Merci beaucoup la le plugin me repond merci beaucoup !

je laisse le sujet ouvert car la je retourne bosser et j'ai pas tester en situation reele j'ai fait que du ssh !!

Bonne apres midi et encore merci

**Comment by tchoul** [comment]
De rien, après pour la clé je suis ne pas sur! J'ai pas de livebox moi, vois avec le créateur du plugins, je lui ai laissé un message sur son github pour le problème de dossier

**Comment by hazenote** [comment]
Ok merci encore @tchoul nan mais la tout vas bien puis sur le coup tout de suite je peux pas tester je suis encore au boulot bloquer je controle en SSH mais ce soir je verrais bien comment repond la box  merci encore 

Je laisse le topic ouvert pour tenir au courant

**Comment by wikijm** [comment]
@hazenote Il faudrait créer un incident sur le dépôt du plugin, ton problème ne semblant pas être dû à Jarvis directement.

**Comment by hazenote** [comment]
@wikijm Je viens de le faire justement mais je laisse ouvert celui la comme ca ca as autant de chance de toucher les utilisateur direct de jarvis

**Comment by tchoul** [comment]
Un truc en passant. Normalement en cas de problème avec un plugin, il faut céer un ticket sur le github de celui-ci. Là ou tu es aller [Erim32](https://github.com/Erim32/fr_liveboxtv/issues) car celui-ci a créer le plugin et sera le plus à même de t'aider.
Ici c'est pour ce qui concerne ce que @alexylem a fait, Jarvis et ses plugins.
Bonne continuation

**Comment by hazenote** [comment]
Ok je suis desolé je suis tout nouveau sur ce qui est raspberry debian et donc justement jarvis et plus principalement nouveau sur ce site donc c'est vraie que j'ai une prise en main assez difficile.

je devrais fermer celui ci de topic  ?

**Comment by wikijm** [comment]
Le mieux serait de clôturer cet issue, mais uniquement après avoir renseigné un lien vers celui que tu auras crée sur le repository du plugin.

Ainsi, si quelqu'un fait une recherche sur l'un des 2 repository, il pourra facilement retrouver ce que tu as demandé, et comment tu as résolu tes problèmes ;-)

**Comment by hazenote** [comment]
Suite aux conseils de tous je clot ce topic et redirige tout ceux qui voudraient suivre l'affaire sur le nouveau   topic 

https://github.com/Erim32/fr_liveboxtv/issues/3
