### ISSUE TITLE
Pour filer un coup de main :)

### ISSUE THREAD

**Issue by tuxme** [alexylem/jarvis#373]
Bon en attendant que je traduise mes scripts en plugins  je vous file le repo ou j'ai codé tout ça :)

https://github.com/tuxme/jarvis

et pour ceux qui on envie d'avoir un petit signal visuel de quand faut parler ou pas :) c'est hal9000.sh qu'il faut coupler au démarrage de jarvis avec un fichier de log dans /tmp/ (voir screen_jarvis_start.sh)

https://www.youtube.com/watch?v=Xi-DevQuHA8 (video en cours de up )

Voila ... see ya all !!!!

**Comment by tchoul** [comment]
Génial ce que tu as fais là ! C'est de toi tout ça ou tu as suivi des tutos ? Car ça m'intéresse même si ça ne doit pas être évident...
C'est donc un mirroir ? On dirait juste un ecran sur la vidéo.
Sinon penses-tu que je puisse récupérer "l'animation de jarvis" pour l'adapter sur mon ecran 3.5 ? 
PS  : Excellent ! 😄
if TEL == "tony stark":

**Comment by tuxme** [comment]
la partie arrière c'est le projet magic mirror (https://magicmirror.builders) la partie avec hal9000 c'est moi :) en fait tout ce qui a dans bin ... c'est moi :)

En effet c'est pas encore un miroir, mais je me débrouille en menuiserie donc c'est pas trop un problème .

Pour ton ecran 3.5 c'est juste une histoire de résolution et de calcul de base :+1: 


feh -x -g 192x266+$((816-192)) /home/pi/bin/img/button_red.png 

ici 192x266 c'est la taille de ton image (X x Y) puis le "+[0-9]"  qui suit (ici $((816-192))) c'est ton emplacemnt de X . pour Y il te suffit de rajouter "+[0-9]"

Voila

**Comment by tchoul** [comment]
Merci beaucoup je test dès que j'ai un peu de temps! sinon screen_jarvis_start.sh faut juste le mettre dans /tmp/ ou faut le mettre en executable?

**Comment by tuxme** [comment]
Pour ma part je l'ai mis dans /home/pi/bin/ et il est lancé au démarrage avec jarvis_start.sh : 

`/usr/bin/screen -d -m -S JARVIS "/home/pi/bin/screen_jarvis_start.sh
`

**Comment by tuxme** [comment]
et oui c'est un executable :)

**Comment by alexylem** [comment]
Je travaille sur une initiative similaire, voir #366 
![fevr -12-2017 21-21-19](https://cloud.githubusercontent.com/assets/11017174/22865669/50e77d3e-f169-11e6-986a-570b4b13d507.gif)
On pourra créer ses propres thèmes/faces. Possibilité de merger les 2 initiatives?
@tuxme ca serait sympa si tu pouvais partager ton projet/vidéo sur:
http://domotiquefacile.fr/jarvis/projects
Si tu n'as pas le temps je peux le faire en ton nom.
Merci 👍

**Comment by tuxme** [comment]
Salut !!! Alors aucun soucis pour partager les projets ... par contre en ce
moment je suis un peu raz la gueule :)

Donc tu peux allègrement récupérer toutes mes sources ... c'est fait pour
ça. Quand j'aurrais un peu de bande passante je ferai une petite doc

:)

see ya

Le 13 février 2017 à 18:34, Alexandre Mély <notifications@github.com> a
écrit :

**Comment by alexylem** [comment]
J'ai publié ton projet ainsi que ta vidéo sur le site de Jarvis:
http://domotiquefacile.fr/jarvis/content/hal9000-de-guillaume
J'espère que tu es ok, si tu veux modifier la page pour y mettre ta doc n'hésites pas, donne moi juste ton login domotiquefacile.fr et je te mettrai en auteur.

**Comment by tuxme** [comment]
Cool ... Mais tu va encore plus kiffer ce qu j ai préparé ;)

Le 16 févr. 2017 17:30, "Alexandre Mély" <notifications@github.com> a
écrit :

**Comment by tuxme** [comment]
C est pas encore au point mais c est du full HTML/PHP/myssl . Et ça marche
avec Midori en fullscreen

http://home.tuxme.net:8084
