### ISSUE TITLE
Plugin Ampoule MiPow

### ISSUE THREAD

**Issue by fpstudios9** [alexylem/jarvis#375]
Bonjour à tous, j'ai crée un plugin pour Jarvis qui permet de contrôler les ampoules de la marque MiPow facilement. Mon problème est c'est que je n'arrive pas à l'ajouter sur GitHub. Au lieu d'uploader mon plugin, ca upload celui qui a servi de base... [ICI](https://github.com/fpstudios9/mipow-playbulb)

Vous avez une idée ? je précise que c'est la première fois que j'envoie du code sur GitHub ;)
Merci.

**Comment by godinperson** [comment]
Bonjour,

N’oublies pas de faire Commit to Master et Sync!

Merci!

**Comment by fpstudios9** [comment]
Merci de la réponse, c'est à dire ?

**Comment by godinperson** [comment]
Tu as pris un clone du projet, que tu as mis sur ton ordinateur. Tu as modifié les fichiers. GitHub a vu le changement et tu as pu mettre un sommaire, une description et faire Commit to master (le bouton dans GitHub? Si tu t'es rendu jusque là, ensuite, tu peux faire Sync (en haut à droite) pour qu'il envoit ton plugin sur le Github. Une fois que tout est en place, tu pourras créer le plugin sur le site domotique

**Comment by fpstudios9** [comment]
Re, désolé du temps de réponse. Non je ne trouve pas le bouton commit to master...

**Comment by godinperson** [comment]
Envoie des prises d'écrans si tu veux qu'on puisses t'aider. Si tu as pris GitHub Desktop, tu auras ça:
![image](https://cloud.githubusercontent.com/assets/24859095/22293478/b0e0ed1e-e2dd-11e6-9759-d46c471b804c.png). Commit to Master est le bouton en bas à gauche. Une fois cliquer, tu fais le bouton en haut à droite Sync

**Comment by alexylem** [comment]
Il faut Forker le plugin de base et non pas Cloner. Ensuite il faut committer sur ton Fork à toi.
Normalement si tu suis les instructions suivantes à la lettre ca devrait fonctionner:
http://domotiquefacile.fr/jarvis/content/publish-your-plugin

**Comment by wikijm** [comment]
Bonjour @godinperson,

Je vois que ton [plugin ](https://github.com/fpstudios9/jarvis-mipow-playbulb) n'est pas encore publié, et que ton fichier README.md n'est pas complété correctement.

Besoin d'un coup de main ?

**Comment by wikijm** [comment]
Pas de réponse à ma relance, je clôture l'issue. 
Ne pas hésiter à rouvrir en cas d'avancée.
