### ISSUE TITLE
Script to control Kinect led + hook

### ISSUE THREAD

**Issue by oeildefeu** [alexylem/jarvis#376]
Hi,
I just want to share my script (adapted from somewhere [else](https://learn.adafruit.com/hacking-the-kinect/command-number-1-and-2-led-blinky) allowing to change the led status of the kinect

> #! /usr/bin/env python
> import usb.core
> import usb.util
> import sys
>  
> # find our device
> dev = usb.core.find(idVendor=0x045e, idProduct=0x02B0)
>  
> # was it found?
> if dev is None:
>     raise ValueError('Device not found')
>  
> # set the active configuration. With no arguments, the first configuration will be the active one
> dev.set_configuration()
> 
> if sys.argv[1] == 'off':
> 	led_value = 0x0
> elif sys.argv[1] == 'green':
> 	led_value = 0x1
> elif sys.argv[1] == 'red':
>         led_value = 0x2
> elif sys.argv[1] == 'orange':
>         led_value = 0x3
> elif sys.argv[1] == 'blink_yellow':
>         led_value = 0x4
> elif sys.argv[1] == 'blink_green':
>         led_value = 0x5
> elif sys.argv[1] == 'blink_red_yellow':
>         led_value = 0x6
> else:
> 	led_value = 0x4
> 
> ret = dev.ctrl_transfer(0x40, 0x6, led_value, 0, [])
> #print ret

then, you can create hook
on startup: /home/path/to/led_kinect.py green
on exit: /home/path/to/led_kinect.py off
on command : /home/path/to/led_kinect.py orange
etc...

all the colors are not working on my kinect (blinking orange for instance...) but this can give you a visual aspect of what is going on

**Comment by alexylem** [comment]
Merci, c'est maintenant référencé sur le site:
http://domotiquefacile.fr/jarvis/content/hooks
![image](https://cloud.githubusercontent.com/assets/11017174/22346786/9950c1d2-e405-11e6-8a0d-c06019f6a7a0.png)
