### ISSUE TITLE
Notification spontanée 

### ISSUE THREAD

**Issue by plano51** [alexylem/jarvis#377]
Bonjour Alexylem.
Je voudrais faire en sorte que jarvis me prévienne pour ce lever, pour mes rendez vous, etc...
Existe-t-il un plugin?
Comment dois-je m'y prendre?

**Comment by Jean-Bernard-Hallez** [comment]
ET coucou... Pour se lever il faut simplement mettre dans crontab -e (Réveil à 7h30 puis une minute après:)
 30       7    *       *       *       ~/jarvis/jarvis.sh -x "quelle heure est-il?" il faut installer le plugin "Time" [http://domotiquefacile.fr/jarvis/plugins/time](url)
 31       7    *       *       *       ~/jarvis/jarvis.sh -s "Alors il faut se lever maintenant ! aller debout !"


Et par exemple pour tes RDV... il y a le plugin CESTQUAND [,](http://domotiquefacile.fr/jarvis/plugins/cest-quand-lanniversaire-de-ou-le-rdv-de) mais il n'est pas en syncho avec gmail... à toi de mettre tes RDV très important dans le config.sh ou tu peux encore utiliser la commande avec crontab voir ce lien:
[http://domotiquefacile.fr/jarvis/content/events](url)

**Comment by plano51** [comment]
Merci Hallez.
Je te remercie de ton aide. Cela fonctionne très bien.
J'ai un souci avec un autre plugin "HUE", te serait-il possible de me
renseigné?

**Comment by Jean-Bernard-Hallez** [comment]
Désolé là je ne peux pas t'aider... j'utilise les ampoules MyLight au travers de Domoticz, et avec la commande vocale du plugin [HomeControl](http://domotiquefacile.fr/jarvis/plugins/home-control).

**Comment by wikijm** [comment]
@plano51 Je t'invite à contacter directement le créateur du plugin Hue (https://github.com/fatoldsun00/jarvis-hue), il saura certainement t'aider :-)
