### ISSUE TITLE
Erreur 403 : Forbidden

### ISSUE THREAD

**Issue by dark20100vie** [alexylem/jarvis#378]
### Description

Bonjour,
j'essaye d'installer jarvis sur un ubuntu 14.04 et quand je lance l'installation il me met cette erreur j'aimerai avoir un peu d'aide afin de la resoudre.
merci.

### Result
2/2 Installation of Snowboy
--2017-01-20 21:18:17--  https://s3-us-west-2.amazonaws.com/snowboy/snowboy-releases/ubuntu1404-x86_64-1.1.0.tar.bz2.tar.bz2
Résolution de s3-us-west-2.amazonaws.com (s3-us-west-2.amazonaws.com)… 54.231.168.224
Connexion à s3-us-west-2.amazonaws.com (s3-us-west-2.amazonaws.com)|54.231.168.224|:443… connecté.
requête HTTP transmise, en attente de la réponse… 403 Forbidden
2017-01-20 21:18:18 erreur 403 : Forbidden.

**Comment by oeildefeu** [comment]
modifie le script en enlevant .tar.bz2
il est en double à la fin du fichier à télécharger

**Comment by dark20100vie** [comment]
merci j'essaye.

**Comment by dark20100vie** [comment]
Ca fonctionne merci beaucoup !!
