### ISSUE TITLE
probleme audio ???

### ISSUE THREAD

**Issue by jempromene** [alexylem/jarvis#379]
### Description

bonjour a tous , et merci a Alex pour son travail .
jarvis se lance et semble fonctionner malgrés un premier message d'erreur.
je peux apeler "sarah" ou "alexa" mais aprés aucune commande ne passe.
jarvis fini par s'arreter avec un message d'erreur.
j'ai reinstaller un raspbian complet sur ma sd et je rencontre le meme probleme.
rapbian et dependance a jour , jarvis aussi .
la config audio, enceinte et micro est ok .
j'ai beau chercher je ne comprend pas le soucis.

### Result

pi@raspberrypi:~ $ cd jarvis/
pi@raspberrypi:~/jarvis $ ./jarvis.sh

------------ Config ------------
jv_version           17.01.09 
jv_arch              armv7l 
jv_os_name           raspbian 
jv_os_version        8 
language             fr_FR 
play_hw              hw:0,1 
rec_hw               hw:1,0 
speaker              ALSA 
microphone           Logitech, Inc. Webcam C270 
trigger_stt          snowboy 
command_stt          snowboy 
tts_engine           svox_pico 
--------------------------------

DEBUG: program_startup hook
sarah: Hello
User defined commands:
*AIDE*			*BONJOUR*|*SALUT*	*COMMENT*APPELLE*
*MERCI*			*AU REVOIR*|*BYE*	ANNULE*|TERMINE*
ENCORE*			*TEST*			*VERSION*
*REPETE (*) ET (*)	*CA VA*			>*OUI*
>*NON*
sarah: Waiting to hear 'sarah'
bab: (listening...)
DEBUG: models=alexa,sarah,snowboy
Cannot connect to server socket err = No such file or directory
Cannot connect to server request channel
jack server is not running or cannot be started
INFO:snowboy:Keyword 2 detected at time: 2017-01-21 11:17:37
DEBUG: modelid=1
sarah
DEBUG: entering_cmd hook
sarah: Yes?
bab: (listening...)
DEBUG: models=alexa,sarah,snowboy
Cannot connect to server socket err = No such file or directory
Cannot connect to server request channel
jack server is not running or cannot be started
INFO:snowboy:Keyword 2 detected at time: 2017-01-21 11:18:48
DEBUG: modelid=1
sarah
sarah: I did not understand: sarah
bab: (listening...)
DEBUG: models=alexa,sarah,snowboy
Cannot connect to server socket err = No such file or directory
Cannot connect to server request channel
jack server is not running or cannot be started
INFO:snowboy:Keyword 2 detected at time: 2017-01-21 11:19:01
DEBUG: modelid=1
sarah
sarah: I did not understand: sarah
bab: (listening...)
DEBUG: models=alexa,sarah,snowboy
Cannot connect to server socket err = No such file or directory
Cannot connect to server request channel
jack server is not running or cannot be started
INFO:snowboy:Keyword 1 detected at time: 2017-01-21 11:20:32
DEBUG: modelid=0
alexa
sarah: I did not understand: alexa
bab: (listening...)
DEBUG: models=alexa,sarah,snowboy
Cannot connect to server socket err = No such file or directory
Cannot connect to server request channel
jack server is not running or cannot be started
INFO:snowboy:Keyword 2 detected at time: 2017-01-21 11:22:01
DEBUG: modelid=1
sarah
sarah: I did not understand: sarah
bab: (listening...)
DEBUG: models=alexa,sarah,snowboy
Cannot connect to server socket err = No such file or directory
Cannot connect to server request channel
jack server is not running or cannot be started
Expression 'paTimedOut' failed in 'src/os/unix/pa_unix_util.c', line: 387
Expression 'PaUnixThread_New( &stream->thread, &CallbackThreadFunc, stream, 1., stream->rtSched )' failed in 'src/hostapi/alsa/pa_linux_alsa.c', line: 2998
Expression 'pthread_join( self->thread, &pret )' failed in 'src/os/unix/pa_unix_util.c', line: 441

**Comment by mikagouzee** [comment]
commande jack_control start --> ça va régler ton problème de jack server is not running or cannot be started.

Ensuite Alex m'a dit de mettre un autre tool que snowboy pour reconnaitre les commandes, donc regarde de ce côté la.

**Comment by alexylem** [comment]
```
trigger_stt snowboy
command_stt snowboy
```
Arrêtez de mettre snowboy pour les commandes 😄  qu'est-ce qui vous prend à tous? Je crois que je vais finir par l'enlever de la liste pour les commandes...
Pour les commandes, suivre l'installation qui recommande d'utiliser "bing".

**Comment by wikijm** [comment]
@jempromene Tu as pu essayer Bing comme moteur de reconnaissance des commandes ?

**Comment by jempromene** [comment]
Merci pour vos réponses, mais non je n'ai pas essayé Bing, j'essayer avec snowboy parce qu'il est hors ligne et en français.je tiens à ce que mon système domotique fonctionne hors ligne. 
Je poursuit donc mes recherches.

**Comment by alexylem** [comment]
@jempromene tu peux utiliser snowboy pour les commandes mais il te faudra "trainer" toutes les commandes avec snowboy ("allume la chambre", "éteins la chambre", ...) et bien entendu créer les commandes correspondantes.

**Comment by wikijm** [comment]
@jempromene Je clôture l'issue jusqu'à ce tu prenne le temps de faire tes tests.
Si nécessaire, n'hésites pas à le ré-ouvrir :-)
