### ISSUE TITLE
Demander plusieurs ordres à la fois

### ISSUE THREAD

**Issue by remjou1** [alexylem/jarvis#38]
voila je voulais savoir si c'était possible d'executer plusieurs commande en une seul phrase par exemple : 
```
MOI: "allume la lampe et allume la ventlation"
JARVIS: "ok"
(et il fait les deux commandes)
```
en structure ça pourrait donner : 
```
(*) ET (*)==
```
mais cette structure et aussi utilisé pour les envoie de message ou la répétition d'un mot donc du coup est-ce possible ?

**Comment by physicien** [comment]
Personnellement, je ne vois pas ce qui empêcherais de faire quelque chose comme ça. Par contre, il faudrait peut-être revoir la structure des commandes. Je voulais justement me pencher sur la questions des commandes prochainement, je vais penser à ça en même temps.

**Comment by remjou1** [comment]
je pense exactement comme toi... le plus chiant ça risque d'être la sructure...

**Comment by alexylem** [comment]
En fait ca serait assez facile si le séparateur entre les commandes est peu commun, donc pas utilisé dans d'autres commandes. Je pense à `PUIS` ou `ENSUITE` (ca serait configurable dans Settings)

```
User: "Allume la lampe puis allume la ventilation"
```

**Algorithme `jarvis.sh`**
```
set $orders to split $order by `(space)PUIS(space)`
for each $orders as $order
    handle_command ($order)
```

Limitation, si une commande contient `PUIS` ou `ENSUITE` elle sera découpée. Donc vous ne pourrez pas dicter à la première commande un texte contenant `PUIS` ou `ENSUITE`:

```
User: Rappelle moi de ranger l'appart puis faire les courses
Jarvis: Ok je te rappelerai de ranger l'appart
Jarvis: Je ne comprends pas "Faire les courses"
```

Mais on pourrait toujours s'en sortir avec les commandes imbriquée (#1) :
```
User: Note un rappel
Jarvis: Que dois-je te rappeler?
User: Ranger l'appart puis faire les courses
Jarvis: Ok je te rappelerai de ranger l'appart puis faire les courses
```

**Comment by alexylem** [comment]
@remjou1 peux-tu me dire si tu es d'accord avec cette approche avant que je l'implémente?
Merci.

**Comment by remjou1** [comment]
ouais c'est nickel ;)

**Comment by alexylem** [comment]
Implémenté, mettez à jour.
Pour l'utiliser, il suffit de **configurer votre séparateur** dans
Settings > General > Multi-command separator
et le mettre par exemple à `puis` (par défaut il est vide = désactivé)
```
Alex: test puis quelle heure
jarvis: Ca fonctionne!
jarvis: il est 21:41
```
