### ISSUE TITLE
jarvis 

### ISSUE THREAD

**Issue by ledarvite** [alexylem/jarvis#380]
jarvis: Waiting to hear 'jarvis'
javis: ?#??

j ai changer de micro mais toujours le  ?#??

**Comment by tchoul** [comment]
alsamixer! baisse le volume du micro, il est trop haut et il enregistre sans cesse

**Comment by ledarvite** [comment]
Merci pour ta réponse
Mais toujours le même problème
Je peu savoir quel micro que tu utilise

**Comment by tchoul** [comment]
Micro chinois à 20€ mais ça c'était avant maintenant j'utilise une smartwatch :-D
Pour t'orienter un peu tu as le choix entre :
-le micro
-[téléphone android](http://domotiquefacile.fr/jarvis/content/voice-control-from-android-device)
-[téléphone android avec google now (ok google)](http://domotiquefacile.fr/jarvis/content/voice-control-with-google-now)
-[smartwatch avec android wear](http://domotiquefacile.fr/jarvis/content/voice-control-from-smartwatch)

Pour celà il te faut le plugin Jarvis-API!

Pour la [smartwatch avec android wear](http://domotiquefacile.fr/jarvis/content/voice-control-from-smartwatch) il y a un problème que je viens de contourner à l'instant! [Voir #368](https://github.com/alexylem/jarvis/issues/368)

**Comment by ledarvite** [comment]
merci
je vais essayer demain

**Comment by oeildefeu** [comment]
tu as essyé en mode troubleshooting, voir comment tu t'entends?
Une astuce aussi c'est de configurer la longueur max de l'enregistrement à 4s qui est la longueur maximale d'une commande... du coup ça tentera de reconnaitre une commande à tous les coups.

**Comment by alexylem** [comment]
Merci de coller le contenu du terminal en mode troubleshooting. Déjà on verra quels moteur de reconnaissance vocal tu utilises.

**Comment by wikijm** [comment]
Pas de nouvelle de @ledarvite  depuis 18 jours.
Je clôture le ticket, mais ne pas hésiter à le ré-ouvrir s'il y a de l'avancée dessus ;-)
