### ISSUE TITLE
Phrase Mélangé 

### ISSUE THREAD

**Issue by Qweetttuu** [alexylem/jarvis#382]
Bonjour,
Voila mon problème, Jarvis comprend le mot clé et lance le mode conversation . Mais la phrase prononcer n'est plus Yes?

snowboy: Waiting to hear 'snowboy'
Vincent: jarvis
snowboy: Ordre non reconnu: jarvis
Vincent: .snowboy: Waiting to hear 'snowboy'

**Comment by tchoul** [comment]
waiting for snowboy... ila attend snowboy pas jarvis il faut que tu changes dans setting > general > magic word pour mettre jarvis

**Comment by Qweetttuu** [comment]
Merci de ton aide. Mais même soucis.

Vincen: terminé
jarvis: Ok
jarvis: Waiting to hear 'jarvis'
Vincen: jarvis
jarvis: Je n'ai pas compris: jarvis  <====== Il ne répond pas Oui ou Yes
Vincen: au revoir
jarvis: Au revoir Vincen
pi@raspberrypi:~/jarvis $

**Comment by tchoul** [comment]
"Au revoir" c'est une commande donc si il te repond à cette commande normalement c'est qu'il a compris le hotword, vu qu'il t'as repondu au revoir aussi...tu n'aurais pas remplacé "oui ou yes " par "je n'ai pas compris"  ?

**Comment by Qweetttuu** [comment]
J'ai même réinstaller. Même soucis. 
Se marin j 'installe quelque plugins et tout refonctionne. A voir si sa recommence. Merci de ton aide
