### ISSUE TITLE
jarvis

### ISSUE THREAD

**Issue by ledarvite** [alexylem/jarvis#383]
jarvis: (listening...)
 rec -V1 -q -r 16000 -c 1 -b 16 -e signed-integer --endian little jarvis-record.wav silence 1 0.1 1% 1 0.5 1% trim 0 10
DEBUG: speech duration was 100 (10 = 1 sec)
DEBUG: too long for a trigger (min 0.5 max 1.5 sec), ignoring...
 rec -V1 -q -r 16000 -c 1 -b 16 -e signed-integer --endian little jarvis-record.wav silence 1 0.1 1% 1 0.5 1% trim 0 10
DEBUG: speech duration was 100 (10 = 1 sec)
DEBUG: too long for a trigger (min 0.5 max 1.5 sec), ignoring...
 rec -V1 -q -r 16000 -c 1 -b 16 -e signed-integer --endian little jarvis-record.wav silence 1 0.1 1% 1 0.5 1% trim 0 10

**Comment by wikijm** [comment]
@ledarvite I don't understand, what is your issue?

**Comment by tchoul** [comment]
Il a un enregistrement trop long, micro trop sensible ou commande trop longue

**Comment by ledarvite** [comment]
ok merci je vais régler tout ça

Le 23 Jan. 2017 00:02, "tchoul" <notifications@github.com> a écrit :

Il a un enregistrement trop long, micro trop sensible ou commande trop
longue

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/alexylem/jarvis/issues/383#issuecomment-274367438>, or mute
the thread
