### ISSUE TITLE
Question bete

### ISSUE THREAD

**Issue by attorney90** [alexylem/jarvis#384]
Bonjour
je viens d’installer jarvis c'est vraiement top avec jeedom, par contre jai une question bête, comment puis je faire pour faire baisser et augmenter le volume de jarvis via une commande vocal comme par exemple:

parle plus fort (le volume de jarvis augmente de x)
parls moins fort (le volume de jarvis diminue de x)

Merci d'avance

**Comment by oeildefeu** [comment]
http://www.dronkert.net/rpi/vol.html  ?

**Comment by attorney90** [comment]
merci pour la reponse mais je suis niveau novice xD, donc si j'ai bien compris je dois associer les commande amixer set Master +2db à une demande pour augmenter et
amixer set Master -2db à une autre demande pour diminuer?

**Comment by oeildefeu** [comment]
Oui, tu peux déjà essayer de les taper dans une console pour voir si elles marchent ! Tu peux aussi changer la valeur, 2, c'est peut-être léger comme changement...

**Comment by attorney90** [comment]
dpnc j'ai taper dans la console et j'ai la réponse suivante: amixer: Unable to find simple control 'master',0

je suis sur un pi3

**Comment by attorney90** [comment]
ah j'ai trouvé mon périphérique ne s appel pas Master mais PCM, reste plus qu'a creer la commande

**Comment by Jean-Bernard-Hallez** [comment]
il y a aussi  le plugin que j'ai fait pour cela ! [http://domotiquefacile.fr/jarvis/plugins/alasamixer-volume](url)

**Comment by wikijm** [comment]
Attention @Jean-Bernard-Hallez, ton URL n'est pas bon. Il devrait plutôt pointer vers http://domotiquefacile.fr/jarvis/plugins/alasamixer-volume ;-)

**Comment by attorney90** [comment]
ah merci si jaurais su avant :D

**Comment by Jean-Bernard-Hallez** [comment]
Merci @wikijm... Tous ensemble oui !

**Comment by wikijm** [comment]
@attorney90 Si tu as la réponse à ta question, je t'invite à clôturer ce ticket d'incident. On frôle la 100aine, ça ferait du bien de nettoyer un peu ;-)
