### ISSUE TITLE
Suggestion: Plugin nouvelle catégorie GUI

### ISSUE THREAD

**Issue by Erim32** [alexylem/jarvis#385]
Bonjour,
petite suggestion, pour jarvis offre la possibilité de l'utiliser avec un affichage, pour faire la différence avec les plugins standard de controle il serrait possible de créer une nouvelle catégorie de Plugin "GUI"

**Comment by alexylem** [comment]
Sur le site c'est ca? dans cette liste?
![image](https://cloud.githubusercontent.com/assets/11017174/22380710/aa6b9d7a-e4be-11e6-9360-4f36a4f1ff37.png)

Combien de plugins il y aurait la dedans, à part "Jarvis-UI" ?

**Comment by Erim32** [comment]
Oui dans cette liste, Jarvis-UI, Jarvis console et bien d'autres on peux supposer tous les plugins qui auront une intéraction visuelle, comme afficher les mails, ouvir youtube, ouvrir ...., , une version visuelle d'un lecteur de musique, etc ... 
Tout est possible à mon avis.

**Comment by alexylem** [comment]
Bonne idée, grace à #394 je pense travailler sur un plugin pour donner un visage à Jarvis 😄 
J'ajoute ca.

**Comment by alexylem** [comment]
Voila c'est rajouté
![image](https://cloud.githubusercontent.com/assets/11017174/22629199/d23908cc-ebe1-11e6-9c42-95008d885972.png)
