### ISSUE TITLE
Voici comment avoir le tetour TTS avec Tasker sur son téléphone ou tablette

### ISSUE THREAD

**Issue by Jean-Bernard-Hallez** [alexylem/jarvis#386]
Donc voila avec une tablette ou un téléphone l'avoir comme un micro avec retour tts (Retour réponse sur Haut-parleur de la tablette ou du téléphone):

il faut avoir le plugin Parse Task https://play.google.com/store/apps/details?id=com.balda.parsetask

Mise ne place:

Quand vous cliquez sur + en bas à droite, donnez un nom de projet "Ex Retour tts jarvis" puis + en bas au milieu dans le menu tout en bas il y a filtre là commencez à taper le bédut de chaque A1 à Ax... ex Obtenir il il ne vous reste plus qu'a copier la suite:
(en A2 adresse de Jarvis + port 8080 plugin API)
(en A3 "jarvistuesla" c'est votre Username )

A1: Obtenir depuis la voix [ Titre: Modèle de langage:Saisie libre Langue: Résultats max:1 Délai (Secondes):30 ]
A2: Post HTTP [ Serveur:Port:192.160.0.22:8080 Chemin: Données / Fichier:{"order":"%VOICE","mute":"true"} Cookies: User Agent: Délai:29 Type de contenu:text/json Fichier de sortie: Faire confiance à tout certificat:Désactivé ]
A3: JavaScriptlet [ Code:var arr=[]; arr = JSON.parse(global('HTTPD'))[0].jarvistuesla Bibliothèques: Sortie auto:Activé Délai (Secondes):45 ]
A4: Flash [ Texte:%arr Long:Activé ]
A5: Dire [ Texte:%arr Moteur:Voix:com.google.android.tts:fra-fra Flux:3 Ton:5 Vitesse:5 Respecter le focus Audio:Activé Réseau:Désactivé Continuer la tâche immédiatement:Désactivé ]

**Comment by tchoul** [comment]
Super! ça fonctionne! Encore une option en + pour Jarvis 
Merci pour les explications précises!
Et merci tout court!

**Comment by alexylem** [comment]
Merci @Jean-Bernard-Hallez j'ai référencé ton post sur le site:
http://domotiquefacile.fr/jarvis/content/voice-control-from-android-device

**Comment by Jean-Bernard-Hallez** [comment]
AU DESSUS c'est la version simple... mais si on a le plugins comme météo avec 2 retours de ligne vocal, il faut le modifier comme l'avait mis @GHOST sur un post, j'ai rajouté juste une petite option quand on prononce DIRE et ce que l'on veut derrière, si dit simplement la phrase si on a un haut parleur branché sur le raspberry sans le retour.
Quand vous cliquez sur + en bas à droite de tasker, donnez un nom de projet "Ex Retour tts jarvis" puis + en bas au milieu dans le menu tout en bas il y a filtre là commencez à taper le dédut de chaque A1 à Ax... ex Obtenir il il ne vous reste plus qu'a copier la suite:
(en A3 adresse de Jarvis + port 8080 plugin API)
(en A6 "jarvistuesla" c'est votre Username et à chaque ";" il y a un retour à ligne touche ENTREE du clavier)
(En A7 attention de mettre un "espace" (sans les guillemets) à l'endroit indiqué

A1: Obtenir depuis la voix [ Titre:Jarvis À Ton Écoute Modèle de langage:Saisie libre Langue: Résultats max:1 Délai (Secondes):30 ]
A2: Flash [ Texte:%VOICE Long:Activé ]
A3: Post HTTP [ Serveur:Port:192.160.0.22:8080 Chemin: Données / Fichier:{"order":"%VOICE","mute":"true"} Cookies: User Agent: Délai:29 Type de contenu:text/json Fichier de sortie: Faire confiance à tout certificat:Désactivé ] Si [ %VOICE !~R dire ]
A4: Post HTTP [ Serveur:Port:192.160.0.22:8080 Chemin: Données / Fichier:{"say":"%VOICE"} Cookies: User Agent: Délai:29 Type de contenu:text/json Fichier de sortie: Faire confiance à tout certificat:Désactivé ] Si [ %VOICE ~R dire ]
A5: Vibrer [ Heure:555 ]
A6: JavaScriptlet [ Code:var arr=[]; arr = JSON.parse(global('HTTPD'));
var answer1= arr[0].jarvistuesla;
var answer2= arr[1].jarvistuesla; Bibliothèques: Sortie auto:Activé Délai (Secondes):45 ]
A7: Concaténer des variables [ Nom:%answer Jointure: IL Y A UN ESPACE Supprimer les parties:Désactivé ]
A8: Vibrer [ Heure:555 ]
A9: Flash [ Texte:%answer Long:Activé ]
A10: Dire [ Texte:%answer Moteur:Voix:com.google.android.tts:fra-fra Flux:3 Ton:5 Vitesse:5 Respecter le focus Audio:Activé Réseau:Désactivé Continuer la tâche immédiatement:Désactivé ] Si [ %VOICE !~R dire ]

Pour l'importer directement dans tasker, envoyez moi votre Email je vous fais parvenir le fichier à charger directement dans votre téléphone ou tablette..

**Comment by Jean-Bernard-Hallez** [comment]
Version III   l'avantage de cette dernière version c'est qu'il me récupère touts les retours jarvis alors que la version II m'en récupère ue 2. Mais attention il faut acheter "Tasker AutoTools" à presque 4€ c'est un choix.
il y a toujours la possibilité en disant DIRE quelque-chose de ne pas avoir de retour sur son téléphone ou tablette mais de l'avoir sur son raspberry.

(en A2 et A3 adresse de Jarvis + port 8080 plugin API)
(en A6  A7 A8 Remplacer "jarvistuesla" par votre Username)

A1: Obtenir depuis la voix [ Titre:Jarvis À Ton Écoute Modèle de langage:Saisie libre Langue: Résultats max:1 Délai (Secondes):30 ] 
A2: Post HTTP [ Serveur:Port:192.160.0.22:8080  Chemin: Données / Fichier:{"order":"%VOICE","mute":"true"} Cookies: User Agent: Délai:29 Type de contenu:text/json Fichier de sortie:.jarvis-json.txt Faire confiance à tout certificat:Activé ] Si [ %VOICE !~R dire ]
A3: Post HTTP [ Serveur:Port:192.160.0.22:8080  Chemin: Données / Fichier:{"say":"%VOICE"} Cookies: User Agent: Délai:29 Type de contenu:text/json Fichier de sortie:.jarvis-json.txt Faire confiance à tout certificat:Désactivé ] Si [ %VOICE ~R dire ]
A4: Lire un fichier [ Fichier:.jarvis-json.txt Dans une variable:%JSON ] 
A5: AutoTools Json Read [ Configuration:Input Format: Json
Simple Mode: true
Json: %JSON
Json Root Variable: %answer
Separator: , Délai (Secondes):60 ] 
A6: AutoTools Json Read [ Configuration:Simple Mode: true
Json: %answer
Fields: jarvistuesla()
Json Root Variable: %answer
Separator: ,
Join Output Arrays:   Délai (Secondes):60 ] 
A7: Flash [ Texte:%jarvistuesla Long:Désactivé ] 
A8: Dire [ Texte:%jarvistuesla Moteur:Voix:com.google.android.tts:fra-fra Flux:3 Ton:5 Vitesse:5 Respecter le focus Audio:Activé Réseau:Désactivé Continuer la tâche immédiatement:Désactivé ] Si [ %VOICE !~R dire ]

**Comment by trarizakaria** [comment]
Merci beaucoup. excellent

**Comment by kevincaradant** [comment]
Hello

J'ai essayé de suivre cette procédure mais je ne comprends pas cette phrase.
`Quand vous cliquez sur + en bas à droite, donnez un nom de projet "Ex Retour tts jarvis" puis + en bas au milieu dans le menu tout en bas il y a filtre là commencez à taper le bédut de chaque A1 à Ax... ex Obtenir il il ne vous reste plus qu'a copier la suite:`

Une fois dans l'appli parseTask => J'ai cliqué  sur Tasker dans la partie Information. Puis cela m'ouvre l'application Tasker mais je vois pas le A1, A2 etc. Ai-je raté un truc ? 

Une petite capture d'ecran si tu peux, je veux bien.

Merci :)

**Comment by Jean-Bernard-Hallez** [comment]
Et coucou...Ce n'est pas " parseTask " qu'il faut lancer... c'est un plugin à tasker. (ce plugin à une icone grise avec un flash blanc)
Il te faut lancer l'appli Tasker même...  qui est représenté par une grosse roue cranté avec un flash orange au milieu.[https://play.google.com/store/apps/details?id=net.dinglisch.android.taskerm&hl=fr](https://play.google.com/store/apps/details?id=net.dinglisch.android.taskerm&hl=fr)

**Comment by trarizakaria** [comment]
Oui oui. Voilà des screenchots qui vont t'aider. Mais attend as tu testé la
méthode simple sans retour ( sur le site jarvis non github) ?? C'est la
méthode la plus facile. Il simule un micro et tu dois branché les hauts
parleurs pour entendre jarvis. Voila les screenchots pour la méthode facile
que tu dois testé d'abord. Ensuite tu test la méthode avec retour vocale
sur portable que je t'enverrai ses screenchots aussi

**Comment by kevincaradant** [comment]
@trarizakaria,  je suis en train d'essayer laborieusement la méthode simple sur le site de Jarvis.  Je ne sais pas si c'est mon téléphone qui est sourd ou quoi mais je n'arrive pas à dire des commandes simples comme GAUCHE etc avec Tasker en mode vocale.  

Et c'est moi ou à chaque fois que je dis un truc,  faut que je clique à nouveau sur l'icône raccourci Tasker pour pouvoir redire un truc ? 
J'ai jamais de retour vocale aussi de base,  d'où le fait que je voulais essayer la technique d'ici,  c'est bien pour ça non ? Avoir Jarvis qui répond.  

Aussi,  savez vous si je dois brancher un micro ou non pour que je puisse utiliser le tel.  En effet,  si je débranche le micro du raspberry pi,  je ne peux utiliser Jarvis qu'en mode clavier car  en normal j'obtiens une erreur snowboy recognition failed.  Faudra faire une issue peut être je ne sais pas.  Mais je veux utiliser que le tel comme micro au final et il semble que Jarvis refuse si il y a pas au moins un micro branché même si il ne sert pas...   

Désolé pour le pavé ')

**Comment by trarizakaria** [comment]
Je suis entrain de chercher ton email pour t'envoyer les screenchots.  je suis débutant github et je suis sur mobile. Je sais pas si je peux les partager ici  j'ai fait des screenchots numéroté pour faciliter la tache

**Comment by kevincaradant** [comment]
Oui tu peux les faire glisser directement dans le champ de texte ou tu écris les messages.  Tu as un onglets preview aussi à côté de celui de Write qui te permet de voir la tête de ton message avant de cliquer sur le bouton comment

**Comment by trarizakaria** [comment]
Je ne suis pas sur pc maintenant. J'ai fait les screenchots sur mon mobile. Tu les aura d'ici une heure

**Comment by Jean-Bernard-Hallez** [comment]
20/20 !!! Merci je clôture...

**Comment by trarizakaria** [comment]
Pas encore stp . Je poste les screenchots pour aider les autres et puis on
clôture

**Comment by Jean-Bernard-Hallez** [comment]
@kevincaradant oui en suivant les procédure ci dessus, il te faut cliquer à nouveau sur l'icône raccourci Tasker pour pouvoir redire un truc .
Pour la version sans avoir à cliquer sur le bouton il faut passer par Ok Google puis Jarvis Fais ceci...
voir ici:   [http://domotiquefacile.fr/jarvis/content/voice-control-with-google-now](http://domotiquefacile.fr/jarvis/content/voice-control-with-google-now)

**Comment by kevincaradant** [comment]
@trarizakaria,  tu peux tout faire même si l'issue est close.  C'est juste un principe de la fermer puisqu'elle est résolue mais tu peux continuer à écrire ne t'inquiète pas.  

@Jean-Bernard-Hallez,  coll merci pour le lien.  Je regarde tout ça demain :)

**Comment by trarizakaria** [comment]
![sketch01](https://cloud.githubusercontent.com/assets/25395296/23235544/cf0f5fce-f94d-11e6-9d02-f04e4d19143d.jpg)
![sketch02](https://cloud.githubusercontent.com/assets/25395296/23235571/eac4f378-f94d-11e6-9d82-0a10b580b115.jpg)
![sketch03](https://cloud.githubusercontent.com/assets/25395296/23235582/f1ff2186-f94d-11e6-96d8-1dd2fd839a22.jpg)
![sketch04](https://cloud.githubusercontent.com/assets/25395296/23235595/fbe80b22-f94d-11e6-920d-bef291220d37.jpg)
![sketch05](https://cloud.githubusercontent.com/assets/25395296/23235607/05fec1fa-f94e-11e6-8c5d-755f0f6fad05.jpg)
![sketch06](https://cloud.githubusercontent.com/assets/25395296/23235619/0ead55a0-f94e-11e6-8127-6dc7e4023e3b.jpg)
![sketch07](https://cloud.githubusercontent.com/assets/25395296/23235626/171295e8-f94e-11e6-8a0a-11a52a6fb68e.jpg)
![sketch08](https://cloud.githubusercontent.com/assets/25395296/23235632/1f68d108-f94e-11e6-82a5-45b8d27455c9.jpg)
![sketch09](https://cloud.githubusercontent.com/assets/25395296/23235641/29daa8be-f94e-11e6-9a21-9a1170fdc221.jpg)
![sketch10](https://cloud.githubusercontent.com/assets/25395296/23235644/2e47a316-f94e-11e6-931f-27cbaa5c5230.jpg)
![sketch11](https://cloud.githubusercontent.com/assets/25395296/23235647/3300de54-f94e-11e6-8725-ac302d6d2ba2.jpg)

**Comment by Jean-Bernard-Hallez** [comment]
Merci encore @trarizakaria pour les screenchots... je le remet à la bonne place...

**Comment by aancel** [comment]
Bonjour,

Voulant expérimenter avec Tasker et Jarvis, je suis tombé sur cette issue github.
J'ai trouvé une solution permettant de se passer d'AutoTools et si jamais cela peut être utile à quelqu'un, je la poste ici.

Il faut donc suivre le tutoriel: [https://openjarvis.com/content/voice-control-from-android-device](https://openjarvis.com/content/voice-control-from-android-device).

Vous devriez donc avoir dans Tasker:
- A1: Obtenir depuis la voix
- A2: Flash
- A3: Get HTTP

Pour récupérer la réponse de Jarvis avec le TTS, vous devez tout d'abord écrire le résultat retourné par Jarvis en A3, en rajoutant un fichier de sortie dans l'action (A3 donc), par exemple .jarvis-json.txt

Rajouter ensuite les actions suivantes:
- A4: Lire un fichier:
  - Fichier: .jarvis-json.txt
  - Dans une variable: %JSON
- A5: JavaScriptlet:
  - Code:
```
var json = JSON.parse(global("JSON"));
setGlobal("%ANSWER", json[2].answer);
```
- A6: Dire
  - Texte: %ANSWER

Et votre téléphone devrait vous donner la réponse retournée par Jarvis.    
Si cela ne fonctionne pas, vous pouvez rajouter des actions flash pour vérifier les valeurs des variables. Cette configuration devrait fonctionner tant qu'il n'y aura pas de changement dans le json retourné par l'API: Le champ réponse est actuellement dans le 3ème élément du tableau pour ce que j'ai pu expérimenter.

**Comment by Oliv4945** [comment]
Merci, quel est l'avantage de cette méthode par rapport aux applications ?

**Comment by trarizakaria** [comment]
c'était une ancienne méthode avant d'apparition de l'application android.

**Comment by aancel** [comment]
Pour le contexte, j'ai aussi testé l'application, mais je suis tombé sur cette issue par l'intermédiaire de la page décrivant la procédure pour Tasker, en voulant tester cette procédure.
Je ne pense pas qu'il y ait d'avantage particulier, ça peut éventuellement être une alternative pour les gens qui veulent intercepter les messages via Tasker et les traiter sur leur téléphone.

**Comment by Oliv4945** [comment]
@aancel : Ok merci, c'était surtout pour savoir si il y avait des fonctions intéressantes à ajouter à l'application Android

**Comment by aancel** [comment]
Je suis un peu en phase d'expérimentation avec Jarvis.
J'ai découvert son existence récemment par l’intermédiaire de l'application. Je n'hésiterais pas à faire remonter d'éventuelles fonctionnalités quand j'aurais un peu plus d'expérience avec l'assistant !
