### ISSUE TITLE
modifier commandes dans plugin

### ISSUE THREAD

**Issue by attorney90** [alexylem/jarvis#387]
Bonjour
Je debute sur le pi et je voulais savoir comment modifier les commandes des plugins dans jarvis?
Merci

**Comment by tchoul** [comment]
Pour le plugin jarvis-freeboxplayer par exemple :
`cd /home/pi/jarvis/plugins/jarvis-freeboxplayer/fr/`
puis
`nano commands`

**Comment by attorney90** [comment]
merci

**Comment by attorney90** [comment]
je viens de tester j ai retiré l'alimentation puis remis, jarvis c'est bien relancé automatiquement
