### ISSUE TITLE
comment lancer jarvis automatiquement

### ISSUE THREAD

**Issue by attorney90** [alexylem/jarvis#389]
Bonjour
Je voulais savoir comment lancer jarvish automatiquement au demmarage du pi, sans avoir à le lancer manuellement via ssh.?
Merci d'avance

**Comment by tchoul** [comment]
Dans le terminal :
`crontab -e`
et ajoute cette ligne :
`@reboot ~/jarvis/jarvis.sh -b`
En bas du fichier

Au redémarrage, il se lancera automatiquement!

Voir aussi [#369](https://github.com/alexylem/jarvis/issues/369) pour redémarrer via domoticz

**Comment by attorney90** [comment]
je comprend pas car dans le fichier jai deja la ligne:
 @reboot ~/jarvis/jarvis.sh -s

pourtant lorsque je redémarre jarvis ne se lance pas automatiquement

**Comment by tchoul** [comment]
-b pas  -s

**Comment by tchoul** [comment]
Tu peux aussi redémmarer le raspberry par commande vocal
`*REDEMARRE*RASPBERRY|*REBOOT*RASPBERRY==say "Je redémarre le raspberry" && sudo reboot now`

**Comment by attorney90** [comment]
Merci beaucoup j'ai reussi

**Comment by godinperson** [comment]
Je ne veux pas être gâcheux de party mais ça, c’est bon juste pour les redémarrages. Si tu éteins et allumes, ça ne marches plus ☹

**Comment by attorney90** [comment]
A mince :(

**Comment by tchoul** [comment]
Je viens de faire le test sudo shutdown now, débrancher et rebrancher le rpi et ça fonctionne...

**Comment by tchoul** [comment]
Peut être que via un interrupteur ça ne fonctionne pas... Cela dit j'ai 2 boutons sur domoticz,1 pour redémarrer jarvis et 1 pour le raspberry je  ne redemarre pas par interrupteur

**Comment by attorney90** [comment]
je viens de tester j'ai retiré l'alimentation du pi puis jai remis, jarvis c'est bien relancé automatiquement

**Comment by yannstross** [comment]
ok et finalment comment on annule le demarage auto de jarvis?

**Comment by satana888** [comment]
Bonjour,

 

Le démarrage automatique de Jarvis se fait avec le plugin  «  jarvis-systemd-startup ».

Tu peux lancer Jarvis via le terminal, lancer Jarvis.sh et dans les paramètres de configuration, tu va sur plugins et tu enlève celui-ci ( unistall ).

Tu sera tranquille, plus de Jarvis au démarrage J

 

Bonne journée

 

 

 

De : yannstross [mailto:notifications@github.com] 
Envoyé : samedi 7 juillet 2018 01:33
À : alexylem/jarvis
Cc : Subscribed
Objet : Re: [alexylem/jarvis] comment lancer jarvis automatiquement (#389)

 

ok et finalment comment on annule le demarage auto de jarvis?
