### ISSUE TITLE
Executer commandes avec délai

### ISSUE THREAD

**Issue by remjou1** [alexylem/jarvis#39]
voila c'est asser compliqué... en fait j'ai récemment crée un script qui me permet de lancer une seul et unique commande après un certain temps : 
```
*DANS (*) EXTINCTION*== ./extinction.sh (1)
```
le script : 
```
#!/bin/bash
./jarvis.sh -s "d'accord"
echo "1 : $1"
delai=$1
echo "delai : $delai"
compte=$[delai*60]
echo "compte : $compte"
sleep $compte
./jarvis.sh -s "ok" && cd /home/pi && sudo ./src/chacon-rpi/emit -d 0136CA46 -b A1 -x && sudo ./src/chacon-rpi/emit -d 0136CA46 -b A2 -x && sudo ./src/chacon-rpi/emit -d 0136CA46 -b A3 -x &&  cd /home/pi/jarvis
```
mais voila je voudrais faire plusieurs scipt dans ce gnere et je me vois pas créer 10scipts (même en copier coller) pour executer une commande chacune donc c'est pour savoir si il était ps possible de rajouter une option -... a jarvis ou je ne sais quoi qui permettent de lancer une commande stocké dans une variable....

je sais pas si je suis très clair...

**Comment by remjou1** [comment]
up !!

**Comment by alexylem** [comment]
Si je comprends bien tu veux demander à Jarvis d'exécuter une commande mais plus tard?

**Comment by alexylem** [comment]
@remjou1 peux-tu confirmer s'il te plait?

**Comment by remjou1** [comment]
pas exactement en faite je le fait déja mais j'aimerais, comme j'ai crée un script, pouvoir rentrer n'importe quelle commande dans ce scipt ce qui m'éviterais de faire un script par commande....

**Comment by alexylem** [comment]
Ok donc si je comprends bien quelque chose comme ca:
```
EXECUTE (*)==./mon_script.sh "(1)" && say "c'est fait"
```

*mon_script.sh*
```
eval $@
```

**Comment by remjou1** [comment]
c'est bon ferme la discussion je viens de me créer un petit scipt qui me permet de le faire ;) merci quand même...

**Comment by alexylem** [comment]
Ok
