### ISSUE TITLE
plugin kodi

### ISSUE THREAD

**Issue by attorney90** [alexylem/jarvis#390]
Bonjour
j'ai installé le plug in kody, jai bien renseigner l'ip ainsi que le port de kody, met lirsque je lance une commande il ne se passe rien.
voici mon fichier conig:

#!/bin/bash
kodiIpEn=192.168.0.50
kodiPortEn=8080
kodiIpFr=192.168.0.50
kodiPortFr=8080

Pourtant quand je rentre dans mon navigateur la fonction api http PAUSE:
http://192.168.0.50:8080/jsonrpc?request={%22jsonrpc%22:%20%222.0%22,%20%22method%22:%20%22Player.PlayPause%22,%20%22params%22:%20{%20%22playerid%22:%201%20},%20%22id%22:%201}

Ca fonctionne

**Comment by Jean-Bernard-Hallez** [comment]
Bonjour tout simplement que ton Port ne correspond pas !!  il faut mettre 80 au lieu de 8080... tiens moi au Jus...

**Comment by attorney90** [comment]
merci pour la réponse, mais pourtant lorsque je tape lurl direct dans le navigateur c'est bien le port 8080 et ça fonctionne

**Comment by Jean-Bernard-Hallez** [comment]
Oui c'est normal... Ce n'est pas le même protocole... Alors c'est ok ???    ;-)

**Comment by attorney90** [comment]
non pas du tout fonctionne pas, mais sur KODY c'est bien le port 8080 qui est ouvert pas 80 , sur jeedom j ai mis 8080 ca fonctionne

**Comment by Jean-Bernard-Hallez** [comment]
Chez moi ca fonctionne très bien... 
- as-tu essayé de supprimer le plugin et de le réinstallé ? il y a eu une mise à jour il y a quelque temps qui plantait...
- Ensuite si tu as plusieurs plugins comme API et que Kodi se trouve en dessous de lui dans son exécution ca ne marche pas... Essaye de le  remonter en premier va dans le menu, plugins et Matching Order.
- Qaund tu es en mode Keyboard Mode et tape:  cody droite
Est-ce ce qu'il te répond erreur de commande ? ou rien du tout ? ou l'erreur que tu as programmé dans ton   menu/Setting/Phrases/Command failed ?

**Comment by wikijm** [comment]
@attorney90 Pourrais-tu créer un ticket sur le repo du plugin ?
Comme ça, l'auteur pourras t'aider directement : https://github.com/kevincaradant/jarvis-kodi/issues/new

**Comment by attorney90** [comment]
Alors j'ai désinstallé et réinstallé
j'ai monter remonter jarvis-kody en premier dans le menu matching order
en mode keybord quand je tape cody droite, avec le port 8080, aucune réponse avec le port 80 il met: erreur de commande.
Dans le menu serveur web de kody je vais verifié lorsque je serai devant l’écran car c'est sur une box android tv, mais si mais souvenir sont bon j'avais mis le port 8080 pour le serveur web car le port 80 était utilisé pour une autre app dans l'android tv.
Le serveur proxy je l'avais désactivé, je vais le réactiver dès que je serai devant, je  tiens au courant

**Comment by Jean-Bernard-Hallez** [comment]
Du remue ménage... mais c'est bien à cause Du menu System Serveur Web: Autoriser port à distance HTTP Coché avec le Port 80 !

**Comment by attorney90** [comment]
Ok je vais faire ainsi merci pour l'aide, je te tiens au courant,  en espérant que ça fonctionne

**Comment by attorney90** [comment]
marche toujours pas kodi refuse le port 80.., je laisse tombé merci quand même.
