### ISSUE TITLE
Changer la voix de SVOX Pico

### ISSUE THREAD

**Issue by Lusitanos67** [alexylem/jarvis#391]
Bonjour,

J'aimerai savoir comment faire pour ajouter/modifier une voix de svox par exemple celle de Luc ?
Les voix de robot ne sont pas très atrayantes :)
Merci

**Comment by alexylem** [comment]
Je peux ajouter toutes celles que vous voulez. Tu peux me faire une petite listes des voix intéressantes à rajouter?

**Comment by Lusitanos67** [comment]
Je suis tombé sur ce site qui liste quelques voix dont les deux en FR Luc et Aurélie, par contre il me semble que c'est payant.

Merci à toi

**Comment by alexylem** [comment]
Pardon j'ai confondu avec voxygen. J'ai l'impression que les voix que tu références sont pour SVOX mobile (android). Je ne crois pas qu'on puisses les utiliser sur linux. En tout cas j'ai pas trouvé.

**Comment by Lusitanos67** [comment]
Oui pardon, excuse moi.
Sinon la liste des voix pour voxygen:
Hélène	Féminine	Voix douce, claire et accompagnante
Agnès	Féminine	Voix mature, très intelligible, institutionnelle et naturelle
Philippe	Masculine	Voix mature, très intelligible, institutionnelle et naturelle
Loïc	Masculine	Voix mature, naturelle et posée
Eva	Féminine	Voix grave et posée
Damien	Masculine	Voix jeune, active et dynamique
Guy	Masculine	Voix multi-expressive (enjouée, colérique, triste...)

Tu peux aisément rajouter la liste ? J'aimerais bien tester mais pas trouvé comment faire ?

**Comment by alexylem** [comment]
Tu peux toutes les tester ici: https://www.voxygen.fr/

Voici les voix déjà intégrées dans Jarvis:
![image](https://cloud.githubusercontent.com/assets/11017174/22628990/47e9914e-ebde-11e6-8d0b-bc7812f9ebb1.png)

J'avais volontairement choisi de pas toutes les mettre pour que ca reste simple et équilibré avec les autres langues. Mais si c'est vraiment important pour toi, je les rajoute.
Go?

**Comment by Lusitanos67** [comment]
Important c'est un grand mot, mais si tu as une manip simple pour je puisse tester d'autres voix hommes je veux bien oui.

Merci

**Comment by alexylem** [comment]
>Tu as un retour sur les voix sélectionnées ? J'ai un doute sur l'utilisation de babacool ou electra (pour les non célibataire...)

Babacool ca passe, c'est marrant. Electra oui je déconseille pour les non célibataires ^^

>si tu as une manip simple pour je puisse tester d'autres voix hommes je veux bien oui.

Pour les tester, c'est soit sur le site:
https://www.voxygen.fr/
Si tu veux tester avec Jarvis, tu peux écrire directement dans le fichier de config:
```shell
$> echo "Philippe" > config/voxygen_voice
```

Un fois tester, dis-moi celle que je peux ajouter "officiellement"

**Comment by Lusitanos67** [comment]
Ok pour philippe, merci

**Comment by olivierpayet974** [comment]
Intéressant

**Comment by bouba830** [comment]
bonjour , je n'arrive pas a installer un module TTS pour jarvis, j'ai lu que vous parliez de voxygen comment faire pour l'incrémenté ?
merci
