### ISSUE TITLE
Impossible de faire fonctionner Jarvis

### ISSUE THREAD

**Issue by pvodoz** [alexylem/jarvis#393]
Bonjour,

Je bataille depuis une semaine en vain pour faire fonctionner Jarvis sur un PI3 avec micro Andoer Omni-Directional. Le son sort depuis la TV qui est branchée en HDMI sur le PI.
Lorsque j'essaye d'enregistrer mon hotword, j'ai:
./jarvis.sh
rec WARN formats: can't set sample rate 16000; using 11025

Input File     : 'default' (alsa)
Channels       : 1
Sample Rate    : 11025
Precision      : 16-bit
Sample Encoding: 16-bit Signed Integer PCM

In:0.00% 00:00:03.72 [00:00:00.00] Out:44.0k [======|======] Hd:2.3 Clip:0    ^C
Aborted.
rec WARN formats: can't set sample rate 16000; using 11025

Input File     : 'default' (alsa)
Channels       : 1
Sample Rate    : 11025
Precision      : 16-bit
Sample Encoding: 16-bit Signed Integer PCM

In:0.00% 00:00:02.97 [00:00:00.00] Out:20.0k [      |      ]        Clip:0    ^C
Aborted.
rec WARN formats: can't set sample rate 16000; using 11025

Input File     : 'default' (alsa)
Channels       : 1
Sample Rate    : 11025
Precision      : 16-bit
Sample Encoding: 16-bit Signed Integer PCM

In:0.00% 00:00:02.97 [00:00:00.00] Out:20.0k [      |      ] Hd:3.0 Clip:0    ^C
Aborted.
Training model...
######################################################################## 100,0%
{"voice_samples":[{},{"wave":["Hotword is too short"]},{}]}
ERROR: error occured while training the model

Une idée?

**Comment by alexylem** [comment]
"Hotword is too short"
Tu enregistres quoi comme hotword? (quel est ton trigger)

**Comment by pvodoz** [comment]
je tente "Ok Jeedom" mais rien à faire....

**Comment by alexylem** [comment]
Si tu as toujours "Hotword is too short", alors essaye avec qqchose de différent / plus long. C'est quand même bizarre je n'ai jamais eu moi même ce message d'erreur de snowboy.
Tu peux faire un:
```
$> cat config/trigger
```

**Comment by pvodoz** [comment]
Bon j'ai changé avec "OK jeedom"
Mais la détection est très aléatoire...
Je n'ai pas encore eu le temps mais je pense que je vais devoir jouer avec les paramètres audio.
Ce qui m'étonne, c'est que la config par défaut semble bien fonctionner pour un des utilisateurs avec le même micro...

**Comment by alexylem** [comment]
Tu as essayé avec les hotwords d'origine (snowboy et alexa). Comme ca tu seras fixé si ca vient du micro ou de tes entrainements de hotword.

**Comment by pvodoz** [comment]
Alors, je viens de tester en remettant tout en config d'origine.
Resultat, snowboy ne passe pas.... En revanche, il comprends "alexa" mais me dit qu'il ne connait pas... cf la log:
pi@raspberrypi:~/jarvis $ ./jarvis.sh

------------ Config ------------
jv_version           17.02.12
jv_arch              armv7l
jv_os_name           raspbian
jv_os_version        8
language             fr_FR
play_hw              hw:0,1
rec_hw               hw:1,0
speaker              ALSA
microphone           Asahi Kasei Microsystems Co., Ltd
trigger_stt          snowboy
command_stt          bing
tts_engine           svox_pico
--------------------------------

snowboy: Salut
User defined commands:
*AIDE*                  *BONJOUR*|*SALUT*       *COMMENT*APPELLE*
*MERCI*                 *AU REVOIR*|*BYE*       ANNULE*|TERMINE*
ENCORE*                 *TEST*                  *VERSION*
*REPETE (*) ET (*)      *CA VA*                 >*OUI*
>*NON*
snowboy: Waiting to hear 'snowboy'
Pierrick: (listening...)
DEBUG: models=alexa,snowboy
Cannot connect to server socket err = No such file or directory
Cannot connect to server request channel
jack server is not running or cannot be started
INFO:snowboy:Keyword 1 detected at time: 2017-02-12 16:40:23
DEBUG: modelid=0
alexa
snowboy: Je ne comprends pas: alexa
Pierrick: (listening...)
utils/timeout.sh 10 rec -V1 -q -r 16000 -c 1 -b 16 -e signed-integer --endian li                                                                                                 ttle jarvis-record.wav silence 1 0.1 1% 1 0.5 1% trim 0 10
DEBUG: speech duration was 85 (10 = 1 sec)
DEBUG: too long for a command (max 4 secs), ignoring...
utils/timeout.sh 10 rec -V1 -q -r 16000 -c 1 -b 16 -e signed-integer --endian li                                                                                                 ttle jarvis-record.wav silence 1 0.1 1% 1 0.5 1% trim 0 10
^CDEBUG: program exit handler
DEBUG: program_exit hook

**Comment by alexylem** [comment]
Normal il faut appeler ton Jarvis "Alexa" dans Settings > General > Magic word.

**Comment by pvodoz** [comment]
Sauf que j'ai laissé snowboy en Magic word et qu'il ne veut rien entendre avec ce mot clé...
Alexa semble mieux fonctionner effectivement...

**Comment by wikijm** [comment]
@pvodoz Est-ce que du coup on clôture l'issue ?

**Comment by wikijm** [comment]
Pas de nouvelles depuis 12 jours, je clôture.
Ne pas hésiter à ré-ouvrir le ticket si avancée.
