### ISSUE TITLE
Ajouter des hooks pour chaque étape

### ISSUE THREAD

**Issue by chsalmon** [alexylem/jarvis#394]
Bonjour,

désolé, je ne sais pas si c'est la bonne méthode pour faire des demandes d'évolutions...

Jarvis fonctionne nickel pour moi. 
Je l'utilise avec jeedom en affichant une page "design", et sur cette page j'ai un widget qui affiche un bonhomme animé (récupéré [ici](http://nokians.fr/2014/08/des-nouvelles-animations-pour-cortana-en-chine-et-aux-usa/)    )    
J'utilise les hooks pour changer l'animation du bonhomme, mais il me manque d'autres hook.

Il faudrait un hook à chaque étape du traitement , par exemple :
- juste avant la reconnaissance vocale
- juste apres  
     + un si il a compris
     + un s'il n'a pas compris (ou rien entendu)
- quand il va parler
- quand il a fini de parler
- ...  pas d'autre idée...

Voilà.
Merci pour ton travail.

**Comment by tigre-bleu** [comment]
Aussi en lien avec ce ticket: https://github.com/alexylem/jarvis/issues/335

**Comment by alexylem** [comment]
Super les animations, tu pourrais partager des aperçu de ta page "design"?
Ca sera génial d'avoir une "face" virtuelle de Jarvis avec de telles animations en tant que plugin pour Jarvis, tu serais partant pour m'aider à le faire?
J'ajouterai tous les hooks qu'il faut, j'ai des questions:
> juste avant la reconnaissance vocale

donc après reconnaissance du hotword? Ca existe déjà: `entering_cmd`

>juste apres
>>s'il a compris

La il risque de dire quelque chose (commande qu'il exécute), donc ca risque d'interférer avec *quand il va parler*. Sauf si l'animation est "bloquante" (les hooks le sont de toute façon).

>>un s'il n'a pas compris (ou rien entendu)

La il risque de dire quelque chose (je n'ai pas compris ...), donc ca risque d'interférer avec *quand il va parler*. Sauf si l'animation est "bloquante" (les hooks le sont de toute façon).

> quand il va parler

Ok pas de soucis j'ajoute

> quand il a fini de parler

Ok pas de soucis j'ajoute

**Comment by alexylem** [comment]
@chsalmon j'ai commencé à faire un **plugin jarvis-face** sur la base des images que tu as partagé:
![fevr -12-2017 21-21-19](https://cloud.githubusercontent.com/assets/11017174/22865710/17b4ddee-f16a-11e6-8df6-6890b66d32c6.gif)
Plus d'infos ici: #366. Si tu es intéressé pour qu'on avance dessus ensemble, n'hésites pas à te manifester 👍 
Je viens d'ajouter pour l'occasion 2 hooks `start_listening` et `stop_listening`.
Il me reste encore à rajouter `start_speaking` et `stop_speaking`. Tu avais déjà une animation en stock pour ça?

**Comment by chsalmon** [comment]
Salut,
désolé du retard, j'étais en vacances...

du coup, je n'ai pas encore testé avec tes nouveaux hook, ça à l'air complet.
Je n'ai pas d'autre animation, j'avais juste trouvé celles là sur un site, mais finalement l'idée du gif animé est pas mal, peut être qu'il y a des artistes parmi nous pour faire des gif animés !?
J'utilise mon design jeedom via chrome sur mon miroir connecté.

Ce n'est pas forcement l'endroit ici pour parler de jeedom, mais pour info je poste quelques fichiers.

- Le design, qui ressemble a ton plugin, affiche un virtuel perso qui affiche la bonne image en fonction d'un code (variable "Face" )
![design jeedom](https://cloud.githubusercontent.com/assets/25372078/22883543/fa3f88b8-f1f0-11e6-9ec2-2cdca9be5c35.JPG)

-Le virtuel, avec sa variable info "Face" et des actions pour changer la valeur de cette variable (CALM, BLINK,...) et une variable "Texte" qui affiche ce que jarvis a compris et ce qu'il répond.
![virtuel1](https://cloud.githubusercontent.com/assets/25372078/22883706/bb903954-f1f1-11e6-9f26-6c3927eb2c6d.JPG)
![virtuel2](https://cloud.githubusercontent.com/assets/25372078/22883713/bf700298-f1f1-11e6-8020-932eb75cbcee.JPG)


- Le widget "EAI_Jarvis", avec les fichiers ajoutés pour chaque images (bouton "Fichiers" en haut de la page du widget)
![widget jarvis](https://cloud.githubusercontent.com/assets/25372078/22883624/57b4f794-f1f1-11e6-8519-44dedb12ec9a.JPG)
![widget jarvis fichiers](https://cloud.githubusercontent.com/assets/25372078/22883628/5b116ddc-f1f1-11e6-958b-a86c1f154364.JPG)

Le code du widget 
`<div class="cmd tooltips cmd-widget cursor" data-type="info" data-subtype="numeric" data-cmd_id="#id#" data-cmd_uid="#uid#">
    <center>
        <span class="action iconCmd#uid#"></span>
    </center>
    <script>
       // $('.iconCmd#uid#').empty();
        if ('#state#' == '1') {
            $('.iconCmd#uid#').html('<img src="plugins/widget/core/template/dashboard/cmd.info.numeric.EAI_Jarvis/MOCHI_CALM1_3.gif" />');            
        } 
        else
        if ('#state#' == '2') {
            $('.iconCmd#uid#').html('<img src="plugins/widget/core/template/dashboard/cmd.info.numeric.EAI_Jarvis/MOCHI_BLINK1_3.gif" />');            
        } 
        else
        if ('#state#' == '3') {
            $('.iconCmd#uid#').html('<img src="plugins/widget/core/template/dashboard/cmd.info.numeric.EAI_Jarvis/MOCHI_BOUNCY1_3.gif" />');            
        }  
        else
        if ('#state#' == '4') {
            $('.iconCmd#uid#').html('<img src="plugins/widget/core/template/dashboard/cmd.info.numeric.EAI_Jarvis/MOCHI_CONSIDERATE1_3.gif" />');            
        } 
       else
        if ('#state#' == '5') {
            $('.iconCmd#uid#').html('<img src="plugins/widget/core/template/dashboard/cmd.info.numeric.EAI_Jarvis/MOCHI_ELATED1_3.gif" />');            
        } 
       else
        if ('#state#' == '6') {
            $('.iconCmd#uid#').html('<img src="plugins/widget/core/template/dashboard/cmd.info.numeric.EAI_Jarvis/MOCHI_HEART1_3.gif" />');            
        } 
       else
        if ('#state#' == '7') {
            $('.iconCmd#uid#').html('<img src="plugins/widget/core/template/dashboard/cmd.info.numeric.EAI_Jarvis/MOCHI_HOLIDAY1_3.gif" />');            
        } 
       else
        if ('#state#' == '8') {
            $('.iconCmd#uid#').html('<img src="plugins/widget/core/template/dashboard/cmd.info.numeric.EAI_Jarvis/MOCHI_LOOK1_3.gif" />');            
        } 
       else
        if ('#state#' == '9') {
            $('.iconCmd#uid#').html('<img src="plugins/widget/core/template/dashboard/cmd.info.numeric.EAI_Jarvis/MOCHI_OPTIMISTIC1_3.gif" />');            
        } 
       else
        if ('#state#' == '10') {
            $('.iconCmd#uid#').html('<img src="plugins/widget/core/template/dashboard/cmd.info.numeric.EAI_Jarvis/MOCHI_SATISFIED1_3.gif" />');            
        } 
       else
        if ('#state#' == '11') {
            $('.iconCmd#uid#').html('<img src="plugins/widget/core/template/dashboard/cmd.info.numeric.EAI_Jarvis/MOCHI_SPEAKING1_3.gif" />');            
        } 
       else
        if ('#state#' == '12') {
            $('.iconCmd#uid#').html('<img src="plugins/widget/core/template/dashboard/cmd.info.numeric.EAI_Jarvis/MOCHI_THINKING1_3.gif" />');            
        } 
      else
        if ('#state#' == '13') {
            $('.iconCmd#uid#').html('<img src="plugins/widget/core/template/dashboard/cmd.info.numeric.EAI_Jarvis/MOCHI_WINK1_3.gif" />');            
        } 
       else
        if ('#state#' == '14') {
            $('.iconCmd#uid#').html('<img src="plugins/widget/core/template/dashboard/cmd.info.numeric.EAI_Jarvis/GOLLUM1_3.gif" />');            
        } 
    </script>
</div>
`
 

par exemple , dans exiting_cmd, j'ai mis 

`jv_curl "http://192.168.1.106/jeedom/core/api/jeeApi.php?apikey=xxxxxxxxxxxxxxxxx&type=cmd&id=2829"
say "ok, j'attend qu'on me demande."
sleep 1
jv_curl "http://192.168.1.106/jeedom/core/api/jeeApi.php?apikey=xxxxxxxxxxxxxxxxx&type=scenario&id=71&action=start"`

le premier jv_curl  appel la commande 2829 du virtuel, pour mettre l'image "HOLIDAY"
le deuxieme jv_curl appel un scenario de jeedom qui met un autre design sur mon miroir, Jarvis est caché et attend qu'on l'appel.

voilà pour la partie Jeedom.

**Comment by alexylem** [comment]
Merci pour le partage. J'aime bien l'idée du texte affiché. Je vais y réfléchir pour mon plugin.
Du coup je te laisse tester les 2 nouveaux hooks, et en attendant je travaille pour l'ajout de `start_speaking` et `stop_speaking`. Donc si je comprends bien tu n'as pas d'animation particulière pour ceux-là. Juste l'affichage du texte.

**Comment by alexylem** [comment]
Voila les 2 nouveaux hooks sont la. Voici ces 2 nouveaux hooks illustrés dans mon plugin en cours de dev:
![speaking](https://cloud.githubusercontent.com/assets/11017174/22897525/4ac9cac2-f224-11e6-91b2-6c41de17ba13.gif)
Je te laisse tester les 4 hooks du coup et tu me diras si ca suffit pour tes besoins.

**Comment by wikijm** [comment]
@chsalmon Pas d'avancées ?

**Comment by chsalmon** [comment]
oui, ça marche pas mal. 
Mais je dépend trop de la réactivité de jeedom pour afficher l'image, il faut un truc plus indépendant, comme ton plugin Face.
(Je ne peux pas trop d'aider sur raspberry pour afficher les images pour ton plugin, je ne maitrise pas trop le python ou bash. )  

j'ai l'impression que les hooks "start_listening"  et  "stop_listening"  sont appelés trop souvent ou alors il faudrait un flag pour savoir si il a entendu un truc ou pas.
Par exemple dans "stop_listening",  j'ai mis un say "je regarde..."  pour dire qu'il regarde la commande demandée, mais comme il boucle sur l'écoute un certain nombre de fois, si on ne dit rien il dit quand meme "je regarde..." parce qu'il passe dans "stop_listening". Je ne sais pas si on peut tester une variable pour savoir si il a entendu un truc ou pas ? il faut quand meme que ce fois appelé avant la reconnaissance vocale parce qu'elle peut prendre du temps et comme ça on sait qu'il a compris un truc et qu'il regarde quoi.


Sinon, rien a voir, je me demandais si on pouvait imaginer un truc pour lui apprendre des commandes ?
Des fois on peut faire des demandes à Jarvis qu'il ne peut pas comprendre parce qu'on n'a pas programmé la même phrase, ce qui serait bien c'est qu'on lui dise "ce que je vient de dire, c'est comme ....."  pour lui dire que c'est la même commande.

**Comment by wikijm** [comment]
> Sinon, rien a voir, je me demandais si on pouvait imaginer un truc pour lui apprendre des commandes ?
Des fois on peut faire des demandes à Jarvis qu'il ne peut pas comprendre parce qu'on n'a pas programmé la même phrase, ce qui serait bien c'est qu'on lui dise "ce que je vient de dire, c'est comme ....." pour lui dire que c'est la même commande.

Crée un nouveau ticket pour cela, histoire de mieux suivre cette demande et ne pas polluer le ticket actuel.

**Comment by alexylem** [comment]
@chsalmon 
>Je ne sais pas si on peut tester une variable pour savoir si il a entendu un truc ou pas ?

Qu'est-ce que tu aimerais faire exactement et pourquoi? Certaines commandes sont rapides et n'ont pas besoin d'un "je regarde...".

**Comment by chsalmon** [comment]
c'est pour être sur qu'il a bien entendu la fin de ma demande.
Si il dit "je regarde" dès que j'ai fini de parler, c'est qu'il a bien fini d'enregistrer sans le bruit de fond.
Et des fois, les commandes passées à jeedom peuvent mettre un certain temps a être exécuter.
Il faudrait juste que je sache si il termine l'écoute à cause d'un timeout, ou si il a bien entendu un truc, peut importe quoi

**Comment by alexylem** [comment]
Il y a des déjà des effets sonores différent pour timeout, et son non compris.
Tu aimerais rajouter un petit son entre le moment ou il arrête d'écouter ta voix et le moment ou il commencer à transcrire le son en texte?
Il y avait ca avant, mais ca faisait un peu trop de son alors je l'ai envoyé. Mais je pense que tu peux facilement le remettre grâce au hook `stop_listening`. Mais il vaut mieux un petit son discret que dire lui faire dire "Je regarde". Enfin c'est mon avis perso.

**Comment by chsalmon** [comment]
oui c'est bien ça.
Les sons c'est un peu trop "technique", ça oblige a connaitre la signification de chaque son, je préfère mettre une parole compréhensible qui valide la fin de la demande. 
Comme quand on parle a quelqu'un, si l'autre ne réagit pas, on croit qu'il n'a rien entendu.
Les autres petits sons sont suffisants.

**Comment by alexylem** [comment]
J'ai bien essayé avec le code actuel, tu ne peux pas savoir dans `stop_listening` si tu es en timeout / erreur / ou si la voix a bien été enregistrée.
Par contre avec un léger changement ca serait possible, mais je me demande s'il ne vaudrait pas mieux que je créé une nouvelle "phrase" qui serait vide par défaut, et "lue" à chaque fin d'enregistrement vocal "valide".
Sinon avec le plugin Jarvis Face #366 , tu le verras de visu.

**Comment by wikijm** [comment]
@chsalmon Je joue également avec Jeedom en ce moment. Est ce que tu pourrais partager ton widget ?

**Comment by alexylem** [comment]
@chsalmon  J'y pense, je peux aussi modifier le plugin Jeedom de Jarvis pour qu'il dise "un instant" avant d'envoyer la commande à Jeedom. Comme ca si Jeedom prend du temps à répondre, au moins tu sais que la commande vocale (valide) a été reçu et transmise à Jeedom.

**Comment by colas31** [comment]
Hello,

Dans mon cas, un hook de timeout serait appréciable ;) 

Merci 

ps : @chsalmon  : top l'idée du miroir connecté (du fait maison ? ) et l'animation

**Comment by alexylem** [comment]
@colas31 `listening_hook` ajouté sur la branche bêta.
Tu peux tester tout de suite en activant la bêta dans Settings > General > Branch > Beta
Sinon attends ce soir ou demain soir que je merge sur master.
Alex.

**Comment by colas31** [comment]
Je viens de tester je valide fonctionnellement.

Merci :)

(Déformation professionnelle pour l'ensemble de mes propos :) )

**Comment by alexylem** [comment]
@chsalmon pour info j'ai modifié le plugin Jeedom tu peux maintenant lui faire dire "Un instant" lorsqu'il va interroger Jeedom.

**Comment by colas31** [comment]
Au top, je confirme que c'est un plus ;)
