### ISSUE TITLE
Zone d'échange pour fichiers temporaires

### ISSUE THREAD

**Issue by alexylem** [alexylem/jarvis#395]
De la part d'Olivier, reçu par mail:

>j'ai remarqué que les accès bing genèrent un fichier wav pour chaque reponse. Sachant que le pi fonctionne sur une SD, il serait judicieux de faire une zone d'echange en tmpfs pour toutes les ecritures. L'objectif est d'augmenter la duree de vie de la SD et d'augmenter par la meme occasion les perfs lecture/ecriture

> Pour cela, rajouter:
```
tmpfs /tmp tmpfs defaults,size=250M 0 0
```
> dans le /etc/fstab

**Comment by tchoul** [comment]
Bien vu!

**Comment by alexylem** [comment]
Je vais l'implémenter bientôt, plus d'infos ici:
https://doc.ubuntu-fr.org/tmpfs

**Comment by Smanar** [comment]
Sinon encore plus simple, ecrire directement dans /dev/shm/

**Comment by alexylem** [comment]
Merci @Smanar c'est d'ailleurs ce que je fais déjà pour l'échange du texte venant de la reconnaissance vocale (sauf sur Mac).
