### ISSUE TITLE
Bug si je souhaite ouvrir un fichier bash externe à jarvis

### ISSUE THREAD

**Issue by Jean-Bernard-Hallez** [alexylem/jarvis#396]
### Description

Bonjour si j'essaye par exemple d'ouvrir un fichier bash pour un usage externe par une commande vocale type:
*XXX*==/home/pi/jarvis/plugins/fichierx.sh
### Result
Il s'ouvre en boucle et je ne peux rien faire...

J'ai le même problème si je place dans un hooks un fichier bash type
/home/pi/jarvis/plugins/fichierx.sh
il l'ouvre aussi en boucle  en permanence .

**Comment by oeildefeu** [comment]
Un exit ou un truc équivalent à la fin du script ?

**Comment by Jean-Bernard-Hallez** [comment]
Et bien bonjour.... alors oui j'avais dans mon bash du exit et reset... même si je le supprime ca bug de la même manière...

**Comment by Jean-Bernard-Hallez** [comment]
Je vais rentrer un peu plus dans le détail.... Si par exemple on utilise mon plugin que je viens de mettre à jour pour ce test... : [http://domotiquefacile.fr/jarvis/plugins/jarvis-crontab](http://domotiquefacile.fr/jarvis/plugins/jarvis-crontab) 
et qu'on essaye de le lancer avec jarvis en mode Keyboard avec la commande XXXXXX vous verrez le problème... et ca fait cela avec n'importe quel fichier bash externe....

**Comment by alexylem** [comment]
Bizarre...
tu as essayé avec:
```shell
TEST==/bin/bash /path/to/my/script.sh
```
voir
```shell
TEST==/bin/bash /path/to/my/script.sh &
```
Ca ne devrait en aucun cas boucler, sauf si dans ton script tu fais des appels à Jarvis...

**Comment by Jean-Bernard-Hallez** [comment]
Je viens de faire l 'essai...et ça fait exactement pareil dans les 2 cas....

**Comment by Jean-Bernard-Hallez** [comment]
Par contre il y a une différence avec le & sur un autre script qui fonciotnne.... ca avance...

**Comment by alexylem** [comment]
Pour le problème de la boucle ca pourrait aussi être un `continue` dans le script.
En tout cas ca doit venir du script, essaye avec un autre script qui contiendrait juste:
```shell
echo "test"
```

**Comment by wikijm** [comment]
Salut @Jean-Bernard-Hallez,

Si tu as toujours le problème malgré la proposition d'@alexylem, crée une "capture" de ton terminal avec https://asciinema.org/ ou le logiciel [ScreenToGIF](http://www.screentogif.com/). Ça nous aidera peut-être à trouver d'où vient le problème :-)

**Comment by Jean-Bernard-Hallez** [comment]
Bonjour ça vient bien de la manière de créer le script... il y a des commandes qu'il n'accepte pas comme un read par exemple... je clôture en attendant de le bidouiller différemment... merci encore...
