### ISSUE TITLE
Command doublons entre différents plugins

### ISSUE THREAD

**Issue by Lusitanos67** [alexylem/jarvis#399]
Bonjour,

Je viens de m’apercevoir en éditant tous les fichiers de command des différents plugin, que beaucoup de hotwords sont en doublons.
Par la même occasion j'ai supprimé ceux qui ne pouvait jamais être détecté, car la command vocale est intercepté par un autre plugin avant, et gérant lui aussi le même hotword (j'ai fais le trie sur les hotwords les plus pertinents et qui me convenaient le mieux).

Du coup je me dis, qu'avec toutes ces imperfections, la lectures sera plus longue par Jarvis, et ou créer des anomalie/non détection...

Mais pour optimiser tout cela, mise à part aller fouiller manuellement dans chaque fichier command...

**Comment by tigre-bleu** [comment]
Tu peux voir ce ticket qui est un peu lié: https://github.com/alexylem/jarvis/issues/331

**Comment by Lusitanos67** [comment]
Ah même en relisant plusieurs fois je ne vois pas ?

**Comment by tigre-bleu** [comment]
Voir le commentaire https://github.com/alexylem/jarvis/issues/331#issuecomment-270970372

Ca donne une astuce pour pouvoir utiliser le même hotword et qu'il fasse des choses différentes en fonction de ce qu'on a dit avant.

Il faut tout mettre dans le fichier command principal, c'est pas super mais ça marche.

**Comment by Lusitanos67** [comment]
Ah ok merci je vois.
Par contre je ne trouve pas ça très clean que plusieurs plugins ai les mêmes fonctions en soit (demander heure, le saint, etc...), ça oblige à refaire une passe sur tous les hotwords...

Merci pour l'info

**Comment by alexylem** [comment]
Oui effectivement, si on installe bcp de plugin on risque de se retrouver avec des commandes en doublons. Alors dans ce cas c'est le plugin le plus prioritaire (le plus haut dans la liste, et on peut changer cet ordre) qui l'emporte.
Sinon on pourrait implémenter un système qui permettre de forcer l'entrée dans un plugin avant que ses commandes ne soit éligibles (comme le commentaire référencé plus haut).
Mais ca a ses inconvénients...
