### ISSUE TITLE
line 192: update_alsa: command not found

### ISSUE THREAD

**Issue by alexylem** [alexylem/jarvis#40]
Bonjour,
Tout d'abord merci pour tout ce bon boulot sur ce Jarvis. Très intéressant !!!
J'ai essayé de réinstaller tout sur une nouvelle image de Raspbian Jessie. J'ai update et upgrade puis re-installer Jarvis (utilisation de snowboy). Quand je déroule l'install, je suis bloqué au niveau du micro (qui est une webcam C170).
J'ai ce message d'erreur
```
**** List of CAPTURE Hardware Devices ****
card 1: C170 [Webcam C170], device 0: USB Audio [USB Audio]
Subdevices: 1/1
Subdevice #0: subdevice #0
Indicate the card # to use [0-9]: 1
Indicate the device # to use [0-9]: 0
./jarvis.sh: line 192: update_alsa: command not found
rec FAIL formats: can't open input `default': snd_pcm_open error: No such file or directory
play FAIL formats: can't open input file `jarvis-reco rd.wav': No such file or directory
true
```
Pourtant j'ai bien choisi la bonne card et device...
La cam fonctionne bien sur un PC.
Merci pour ton aide
Nico

**Comment by alexylem** [comment]
Corrigé, merci de mettre à jour.

**Comment by adsofts** [comment]
Bonjour,

J'ai exactement le même problème à ceci près que c'est sur la ligne 210 de jarvis.sh
Pour info, c'est une installation fraiche d'aujourd'hui (clone git)
