### ISSUE TITLE
Probleme audition voxygen

### ISSUE THREAD

**Issue by jbouziat** [alexylem/jarvis#400]
### Description

Je n'arrive pas entendre le texte en utilisant voxygen. Avec Google pas de problème mais avec voxygen j'entend un bruit. J'utilise un Jabra 410.
En vous remerciant pour votre aide 

### Result
```shell
<paste here> content of the terminal after using Jarvis in troubleshooting mode
or delete this section if not applicable
```

**Comment by Lusitanos67** [comment]
Tu dois paramétrer la voix voxygen, luc, etc...

**Comment by jbouziat** [comment]
J'ai bien parametré la voix dans jarvis mais rien n'y fait.
Merci

**Comment by Lusitanos67** [comment]
Quand tu lance jarvis en mode trouble, colle le résultat de la lecture ou réponse de jarvis lorsque tu lui demandes une action.

**Comment by alexylem** [comment]
Quel genre de bruit?
Voir #65 
Sinon oui comme indiqué par @Lusitanos67 merci de coller le résultat de la console avec Jarvis lancé en mode troubleshooting. Merci.

**Comment by jbouziat** [comment]
pi@raspberrypi:~/jarvis $ ./jarvis.sh

------------ Config ------------
jv_version           17.02.04
jv_arch              armv7l
jv_os_name           raspbian
jv_os_version        8
language             fr_FR
play_hw              hw:0,0
rec_hw               hw:0,0
speaker              GN Netcom
microphone           GN Netcom
trigger_stt          snowboy
command_stt          bing
tts_engine           voxygen
--------------------------------

karl: Bonjour
User defined commands:
*AIDE*                  *BONJOUR*|*SALUT*       *COMMENT*APPELLE*
*MERCI*                 *AU REVOIR*|*BYE*       ANNULE*|TERMINE*
ENCORE*                 *TEST*                  *VERSION*
*REPETE (*) ET (*)      *CA VA*                 *AVANCE *
>*OUI*                  >*NON*
karl: Waiting to hear 'karl'
Jack: (listening...)
DEBUG: models=alexa,avance bras droit,karl,snowboy
Cannot connect to server socket err = No such file or directory
Cannot connect to server request channel
jack server is not running or cannot be started
INFO:snowboy:Keyword 3 detected at time: 2017-02-09 14:14:17
DEBUG: modelid=2
karl
DEBUG: entering_cmd hook
karl: Oui?
Jack: (listening...)
utils/timeout.sh 10 rec -V1 -q -r 16000 -c 1 -b 16 -e signed-integer --endian little jarvis-record.wav silence 1 0.1 1% 1 0.5 1% trim 0 10
DEBUG: speech duration was 00 (10 = 1 sec)
DEBUG: curl https://speech.platform.bing.com/recognize/query?version=3.0&requestid=cde0461b-d85c-4f85-9065-d4cd3dbccc44&appid=D4D52672-91D7-4C74-8AD8-42B1D98141A5&format=json&locale=fr-FR&device.os=linux&scenarios=ulm&instanceid=E043E4FE-51EF-4B74-8133-B728C4FEA8AA&result.profanitymarkup=0
DEBUG: json={"version":"3.0","header":{"status":"success","scenario":"ulm","name":"au revoir","lexical":"au revoir","properties":{"requestid":"cafc6ca0-de9e-495a-931f-ae33d5552608","HIGHCONF":"1"}},"results":[{"scenario":"ulm","name":"au revoir","lexical":"au revoir","confidence":"0.9206827","properties":{"HIGHCONF":"1"}}]}
au revoir
$> say "Au revoir $username"; jv_exit
karl: Au revoir Jack
DEBUG: program exit handler
DEBUG: program_exit hook

**Comment by Lusitanos67** [comment]
Cette ligne m'interpelle 
DEBUG: speech duration was 00 (10 = 1 sec)

**Comment by alexylem** [comment]
Pas de pb avec la reco vocale apparement. Même si le speech duration est "bizarre" en effet...
Si le pb de synthèse vocale est avec voxygen, tu peux coller le terminal (ou utiliser http://asciinema.org) et attacher le fichier mp3 généré (dans /tmp) pour qu'on entende ca?

**Comment by wikijm** [comment]
Ce sujet n'est plus d'actualité.

Le support de Voxygen a été supprimé avec le commit 3282dcb, et par conséquent sur la dernière mise à jour.
Regarde l'issue #446 pour plus d'informations.
