### ISSUE TITLE
Problème de son

### ISSUE THREAD

**Issue by Yukikko** [alexylem/jarvis#402]
### Description
Bonjour, j'ai un soucis lors de la configuration des enceintes et du micro aucun son ne sort de mes enceintes (je les ai tester elles fonctionnent) mon raspberry 2 est connecté en hdmi pour l'écran et en jack pour les enceintes. Est-ce que vous auriez une idée pour moi svp ? 
Merci d'avance, Bonne journée.

Description of your request/issue
NB: for issues with plugins, please create in the corresponding repository

### Result
```shell
<paste here> content of the terminal after using Jarvis in troubleshooting mode
or delete this section if not applicable
```

**Comment by tchoul** [comment]
Le son est pris par le hdmi, debranche le hdmi et reboot le son sera sur tes enceintes

**Comment by Yukikko** [comment]
Merci pour la réponse rapide, je débute sur raspberry, comment reboot si je n'ai pas d'écran ? Et surtout pour faire démarrer jarvis après le démarrage ? Par putty peut-être ?

**Comment by tchoul** [comment]
oui via putty en ssh 
pour redemarrer jarvis au demarrage [#389](https://github.com/alexylem/jarvis/issues/389)

**Comment by Yukikko** [comment]
Merci beaucoup je test tout ça.

**Comment by alexylem** [comment]
@Yukikko j'espère que tu as pu résoudre ton pb. Si c'est le cas merci de fermer le ticket.
Alex.
