### ISSUE TITLE
jv_sanitize des ordres

### ISSUE THREAD

**Issue by ydellis** [alexylem/jarvis#403]
### Description
@alexylem 
Bonjour, j'écris un plugin qui permet d'obtenir les horaires des trains de la SNCB (Belgique) à la demande.
Il fonctionne correctement, sauf lorsque la gare demandée s'écrit avec des tirets (ex: Villers-la-Ville)
dans ce cas, comme l'ordre passe par la fonction 
jv_handle_order()
    local sanitized="$(jv_sanitize "$order")"
la ville devient villerslaville qui n'est alors pas reconnue par l'API de la SNCB.
Est-il possible de modifier cette fonction si on souhaite que l'ordre ne soit pas sanitizé.
l'ordre est le suivant:
```
*HORAIRE*TRAIN(*)== say "Les prochaines heures de depart sont" && say "$(jv_pg_cb_timetable "(1)")"
```
Merci

Yvan

**Comment by alexylem** [comment]
Petite question bête, lorsque tu dictes la ville, la reconnaissance vocale te mets les tirets?
Ca va être compliqué de ne pas utiliser le sanitize car c'est ca qui permets d'ignorer les accents et autres dans la reconnaissance des commandes.
En contournement, tu peux parser l'ordre reconnu original `$order` et en extraire la chaine après `train`
```shell
$> order="horaires train cagnes-sur-mer"
$> echo ${order#*train}
cagnes-sur-mer
```

```shell
*HORAIRE*TRAIN(*)== say "Les prochaines heures de depart sont" && say "$(jv_pg_cb_timetable "${order#*train}")"
```

**Comment by ydellis** [comment]
Merci pour ta réponse Alex,
J'ai détouné le problème en décomposant la requête pour récupérer l'appellation officielle de la gare dans le fichier de la SCNB et c'est avec cette appellation que j'effectue la requête des horaires.
J'allais te le signaler quand j'ai vu ton mail.
Pour répondre à ta question, effectivement, la reconnaissance vocale mets les tirets.
Le plugin fonctionne, je l'enregistre
