### ISSUE TITLE
Jarvis avec google now

### ISSUE THREAD

**Issue by Darkjeje** [alexylem/jarvis#404]
Bonjour à tous,

J'ai suivi les différentes étapes de ce tuto : http://domotiquefacile.fr/jarvis/content/voice-control-with-google-now
Malheureusement, lorsque je dis "OK google" puis : "Jarvis allume la lampe du bureau", google me lance une page internet avec des lampes de bureau,...
J'ai donc l'impression que autovoice n'intercepte pas ma commande malgré que j'annonce jarvis,...

Auriez-vous une idée de ce qui poserait problème ?

Merci à tous.
Jérem

**Comment by tchoul** [comment]
As tu bien fais cette étape?
 Ouvrir le menu de paramètres du téléphone
    Se rendre dans le menu « Accessibilité »
    Se rendre dans « AutoVoice » Google Now Integration
    Autoriser l’interception des recherches Google Now avec le bouton en haut du menu

**Comment by Darkjeje** [comment]
Salut tchoul et merci pour ta réponse.
Oui le service est activé ainsi que tasker.

Dois-je configurer quelque chose dans AutoVoice ?

**Comment by Jean-Bernard-Hallez** [comment]
Et cette étape qui est la clef de tout:
Dans Tasker, Appuyez sur Command Filter pour indiquer un mot qui doit être présent dans les requêtes à intercepter, ex: jarvis

**Comment by Darkjeje** [comment]
Merci pour ton retour.
J'ai en effet le mot jarvis dans command filter, mais pour autant il ne filtre rien.
Lorsque je dis Ok google puis jarvis allume le couloir, je vois google now écrire parfaitement ce que je dis et je vois un pop up s'ouvrir que je suppose être autovoice avec seulement écrit jarv,...

Je n'ai pas payé la version complète d'autovoice, mais je n'ai pas l'impression que ce soit nécessaire.

Merci pour ton lien, mais je n'ai pas tout compris.
J'ai l'impression que tu as donné une autre technique et un autre paramétrage.

**Comment by Darkjeje** [comment]
Je viens de voir que jarv était dû au fait que j'ai la version lite qui se limite à 4 lettres,...

**Comment by Jean-Bernard-Hallez** [comment]
C'est  exactement

**Comment by Jean-Bernard-Hallez** [comment]
Ce que j'allais te dire.... 4 lettres=lite...

**Comment by Jean-Bernard-Hallez** [comment]
C'est  exactement ce que j'allais te dire.... 4 lettres=lite

**Comment by alexylem** [comment]
Oui il faut la version payante. C'est indiqué dans le tuto 😄

**Comment by Darkjeje** [comment]
Non justement ce n'est pas marqué.
C'est même tout l'inverse : 
<Sur votre appareil Android
Un launcher qui détecte "Ok Google", ex: Google Now Launcher (gratuit)
Tasker (2,99€) pour envoyer des requêtes HTTP à Jarvis depuis votre appareil Android
AutoVoice (gratuit) pour intercepter vos requêtes Google Now et les transmettre à Tasker
>

**Comment by alexylem** [comment]
Ah mince pardon. Je ne me rappelle pas avoir payé autovoice... mais je me trompe peut-être. Mon telephone android est HS, alors un peu dûr pour moi de vérifier.
Et toi @Jean-Bernard-Hallez ?

**Comment by Jean-Bernard-Hallez** [comment]
Bonjour il y a en effet 2 version.s... Autovoice qui fonctionne si il y a moins de 4 lettres puis AutovoicePro qui débloque l'intégralité de notre filtre. 
Personnellement j'ai la version gratuite... et je n'utilise pas de filtre dans autovoice...
Si je passe par ma tablette je passe par ce script; #386 
Si je passe au travers de ma montre je passe par ce script:
Dans Profils j'utilise Autovoice Command "all'
puis dans une tache;
A1: Get HTTP [ Serveur:Port:192.160.0.22:8080 Chemin: Attributs:order=%avcomm Cookies: User Agent: Délai:10 Type Mime: Fichier de sortie: Faire confiance à tout certificat:Désactivé ]

**Comment by alexylem** [comment]
>Si je passe par ma tablette je passe par ce script; #386

Donc ca veut dire que depuis la tablette tu dois lancer ton "app" tasker n'est-ce pas? Tu ne peux pas juste dire "Ok Google" sans AutoVoice.

**Comment by Jean-Bernard-Hallez** [comment]
Oui c'est bien cela... il me faut le lancer et je ne passe pas au travers de 'ok google' qui m'est pénible car il faut en effet prononcer 'ok google' puis mettre un filtre comme 'jarvis lance... ' ... trop long pour moi... à mes oreilles.... lol

**Comment by alexylem** [comment]
Ok donc finalement c'est ce qui est proposé ici:
http://domotiquefacile.fr/jarvis/content/voice-control-from-android-device
Le tuto "Google Now" c'est vraiment pour utiliser Google Now. Il faudra peut-être que j'indique qu'il faut la version pro (à vérifier).

**Comment by wikijm** [comment]
@Darkjeje Est-ce que les informations apportées par @tchoul, @Jean-Bernard-Hallez et @alexylem t'ont aidé à résoudre ton problème ?

Si oui, pense à nous faire un petit retour puis clôturer l'issue. Merci :-)

**Comment by Darkjeje** [comment]
Désolé je n'ai pas eu beaucoup de temps à moi ces derniers jours.
Si je comprends bien, utiliser autovoice+tesker+ok google, et dire ok google puis jarvis allume le couloir cela entrainera toujours l'ouverture d'une page web par google et grâce à autovoice pro, ma commande "jarvis allume le couloir" sera envoyée à l'api ?

N'y a t'il pas un autre moyen pour pouvoir sans déverrouiller le téléphone dire jarvis allume le couloir ?

**Comment by alexylem** [comment]
@Darkjeje heu non tasker n'est pas censé ouvrir une page web. Il doit tout envoyer à l'API. Après autovoice pro c'est pour utiliser le mot clé "Ok google" sans devoir lancer une "app" tasker pour initier la reco vocale.

**Comment by Jean-Bernard-Hallez** [comment]
Je confirme sur ce que dir @alexylem

**Comment by Darkjeje** [comment]
Je comprends bien que tasker n'est pas censé ouvrir une page web, mais google now réagit à ok google et il réagit en lançant une page web non ?
Dans le tuto http://domotiquefacile.fr/jarvis/content/voice-control-with-google-now il est indiqué qu'il faut google now.
Est ce que autovoice permet de capturer le ok google afin de l'envoyer à tasker sans qu'il passe par google now et donc que google now ne puisse pas lancer la page web ?
Dans ce cas qu'est ce qui ne fonctionnerait pas, pour que la page web s'ouvre quand même ?
Et comment puis je vérifier qu'une commande même fausse a bien été envoyé à Jarvis ?
Car bien sûr la lumière du couloir ne s'allume pas.
Autre question est ce qu'il faut aussi prononcer le mot Snowboy (ou jarvis dans mon cas) pour que la commande soit prise en compte par jarvis api ?

**Comment by alexylem** [comment]
>Est ce que autovoice permet de capturer le ok google afin de l'envoyer à tasker sans qu'il passe par google now et donc que google now ne puisse pas lancer la page web ?

Oui

>Dans ce cas qu'est ce qui ne fonctionnerait pas, pour que la page web s'ouvre quand même ?
Et comment puis je vérifier qu'une commande même fausse a bien été envoyé à Jarvis ?

Autovoice se configure avec un filtre. Il peut tout capter ou uniquement ce qui comprends un ou plusieurs mots clés. C'est expliqué dans le tuto. Lis le bien.

>Autre question est ce qu'il faut aussi prononcer le mot Snowboy (ou jarvis dans mon cas) pour que la commande soit prise en compte par jarvis api ?

Via Google Now? Il faut absolument dire "Ok Google". Après le filtre en question peut être ce que tu veux. Par exemple "Jarvis". C'est dans le tuto.

**Comment by Jean-Bernard-Hallez** [comment]
Un truc très important me passe par la tête... si tu utilise le pluton home-contrôle il doit être placé en haut de la liste et api et ui si tu l'as installé tout en bas de la liste des plugins.... (menu de jarvis, dans plugins... order)

**Comment by Jean-Bernard-Hallez** [comment]
Un truc très important me passe par la tête... si tu utilise le plugins home-contrôle il doit être placé en haut de la liste et api et ui si tu l'as installé tout en bas de la liste des plugins.... (menu de jarvis, dans plugins... order)

**Comment by Darkjeje** [comment]
> Via Google Now? Il faut absolument dire "Ok Google". Après le filtre en question peut être ce que tu veux. Par exemple "Jarvis". C'est dans le tuto.

Oui mais là tu parles du filtre pour que autovoice me reconnaisse.
Donc si je met "all" comme filtre, quoi que je dise après ok google est transféré vers jarvis api.
Ma question était plutôt, si on met "all" comme filtre doit on redire jarvis derrière ok google où jarvis api se fiche d'entendre Snowboy (ou jarvis dans mon cas) pour exécuter la commande demandé (allumer le couloir dans mon cas) ?

Dans tous les cas, j'ai un soucis vue que dès que je dis ok google, google affiche ce que je dis et lance une page web correspondant à ma demande.

**Comment by Darkjeje** [comment]
> Un truc très important me passe par la tête... si tu utilise le plugins home-contrôle il doit être placé en haut de la liste et api et ui si tu l'as installé tout en bas de la liste des plugins.... (menu de jarvis, dans plugins... order)

Merci pour l'info Jean-Bernard, mais je n'utilise pas home-contrôle, j'ai rentré dans les mots clés allumer et couloir ce qui déclenche la page web correspondant à cette tâche sur ma domotique.

**Comment by Jean-Bernard-Hallez** [comment]
Ok C'est pour cela alors que tu as un page Web qui s'ouvre... a mon avis jarcis te  renvoie la page... expliques un peu plus cela ? 
Dans les commandes de jarvis tu as un renvoi type curl qui ouvre une page Web c'est cela ??

**Comment by Darkjeje** [comment]
Oui en effet : 
`*ALLUME*COULOIR*==say "Ok" && jv_curl "http://192.168.1.6/Jarvis/Commande_lampe.php?action=1&device=11"
*ETEIND*COULOIR*==say "Ok" && jv_curl "http://192.168.1.6/Jarvis/Commande_lampe.php?action=0&device=11"
`
Mais je ne pense pas que ce soit ça, j'ai plus l'impression que c'est juste google now qui ouvre normalement une page web avec ma demande. Et jarvis allume la lumière du couloir me sort une recherche de lampe sur google,...

**Comment by Jean-Bernard-Hallez** [comment]
Si quand ca plante je fais un play fichier wav  le son ressort bien de mon haut-parleur...

**Comment by Oliv4945** [comment]
Vu son age, je ferme l'issue.
Pour ce simplifier la vie il y a désormais deux applications Android utilisables
