### ISSUE TITLE
'No such file or directory' lors du lancement d'une commande cURL complexe

### ISSUE THREAD

**Issue by wikijm** [alexylem/jarvis#405]
### Description

Erreur lors de l'éxecution de la commande curl suivante :
`curl "http://192.168.0.XX/setSystemMotion" -H "Host: 192.168.0.XX" -H "Re                                                               ferer: http://192.168.0.XX/setSystemMotion" -H "Authorization: Basic BestPasswordEver" -H "Connection: keep-alive" -H "Upgrade-Insecure-Requests: 1" --d                                                                ata "ReplySuccessPage=motion.htm&ReplyErrorPage=motion.htm&MotionDetectionEnable                                                                =1&MotionDetectionScheduleDay=127&MotionDetectionScheduleMode=0&MotionDetectionS                                                                ensitivity=70&ConfigSystemMotion=Save"`

Cette commande fonctionne parfaitement lorsque lancée en console.

### Result
```shell
Commands from plugin jarvis-motiondetectiondlink:
*ALLUM*DETECTION*|*LANC *ETEIN*DETECTION*|*ARRE
Jean-Marc: lance detection
jarvis: La détection de mouvement sera active d'ici 15 secondes. Bonne journée.
./jarvis/jarvis.sh: line 551: curl "http://192.168.0.XX/setSystemMotion" -H "Host: 192.168.0.XX" -H "Referer: http://192.168.0.XX/setSystemMotion" -H "Authorization: Basic BestPasswordEver" -H "Connection: keep-alive" -H "Upgrade-Insecure-Requests: 1" --data "ReplySuccessPage=motion.htm&ReplyErrorPage=motion.htm&MotionDetectionEnable=1&MotionDetectionScheduleDay=127&MotionDetectionScheduleMode=0&MotionDetectionSensitivity=70&ConfigSystemMotion=Save": No such file or directory
jarvis: Cette commande a retourné une erreur
Jean-Marc: bye
```

Ce problème intervient dans le cadre du plugin https://github.com/wikijm/jarvis-motiondetectiondlink dont je suis l'auteur. Ne pas trop se fier à la version sur GitHub, car je n'ai pas poussé toutes mes modifications en ligne.
Vidéo du problème : https://asciinema.org/a/cnallpv00ssd5es2m77yz76yf => Possibilité de copier-coller le texte présent dans la "vidéo" 👍

**Comment by Jean-Bernard-Hallez** [comment]
Et coucou... je suppose que tu as aussi essayé de mettre cette commande dans un fichier bash... et de le lancer via la commande lance detection plutôt que de mettre en une commande direct ??

**Comment by wikijm** [comment]
Besoin de faire plus de tests avant d'appeler à l'aide.

**Comment by wikijm** [comment]
Bon ... malgré des tests complémentaires, je me retrouve toujours avec le même problème.
Depuis la 1ère clôture du ticket j'ai fais une fresh install et bien vérifié que les variables étaient remplacées par les bonnes valeurs (présentes dans config.sh).

Un coup de main serait apprécié :-)

**Comment by alexylem** [comment]
Ok je vois. Bon je pense que l'architecture de ton plugin est à revoir. Il est fortement déconseillé et mettre des commandes dans des variables pour ensuite les exécuter.
Pourquoi ne pas simplement faire:
**commands**
```shell
*ALLUM*DETECTION*|*LANC*DETECTION*|*DEMARR*DETECTION*==say "La détection de mouv
ement sera active d'ici 15 secondes. Bonne journée." && sleep 1 && pg_mdd_cmdenable
```

**functions.sh**
```shell
pg_mdd_cmdenable () {
    curl "http://'"$motiondetectiondlink_camip"'/set
SystemMotion" -H "Host: '"$pg_mdd_camip"'" -H "Referer: http://'"$
motiondetectiondlink_camip"'/setSystemMotion" -H "Authorization: Basic '"$pg_mdd_camauthcode"'" -H "Connection: keep-alive" -H "Upgrade-Insecure-R
equests: 1" --data "ReplySuccessPage=motion.htm&ReplyErrorPage=motion.htm&Motion
DetectionEnable=1&MotionDetectionScheduleDay=127&MotionDetectionScheduleMode=0&M
otionDetectionSensitivity=70&ConfigSystemMotion=Save"
}
```

**config.sh**
```shell
pg_mdd_camip='192.168.0.xx'                                       
pg_mdd_camauthcode='BestPasswordEver'
```

**Comment by wikijm** [comment]
Parce que tu ne me l'as pas dit avant ;-)
Je teste ça ce soir et je te redis (j'espère avec clôture à la clé) 👍

**Comment by wikijm** [comment]
https://github.com/wikijm/jarvis-motiondetectiondlink/releases/tag/1.0
Corrigé, il n'aimait pas 

> '"$variablequelconque"'

Il préfère directement
> $variablequelconque

J'en ai profité pour intégrer la version anglaise du plugin.

Merci @alexylem :-)
