### ISSUE TITLE
Pas de reconnaissance à la diction de "snowboy"

### ISSUE THREAD

**Issue by stefanekz** [alexylem/jarvis#406]
Bonjour et merci pour ce formidable projet !

Je viens d'installer Jarvis sur mon pi3, 
Tout fonctionne à l'installation, il reconnait mon micro, HP et au moment où je lance jarvis en mode troubleshooting, voici ce que la console me renvoie :

> stef@raspberrypi:~/jarvis $ ./jarvis.sh
> 
> ------------ Config ------------
> jv_version           17.01.26 
> jv_arch              armv7l 
> jv_os_name           raspbian 
> jv_os_version        8 
> language             fr_FR 
> play_hw              false 
> rec_hw               false 
> speaker              Default 
> microphone           Default 
> trigger_stt          snowboy 
> command_stt          snowboy 
> tts_engine           svox_pico 
> --------------------------------
> 
> DEBUG: program_startup hook
> snowboy: Hello
> User defined commands:
> *AIDE*			*BONJOUR*|*SALUT*	*COMMENT*APPELLE*
> *MERCI*			*AU REVOIR*|*BYE*	ANNULE*|TERMINE*
> ENCORE*			*TEST*			*VERSION*
> *REPETE (*) ET (*)	*CA VA*			>*OUI*
> >*NON*
> snowboy: Waiting to hear 'snowboy'
> stephane: (listening...)
> DEBUG: models=alexa,snowboy
> Cannot connect to server socket err = No such file or directory
> Cannot connect to server request channel
> jack server is not running or cannot be started
> Expression 'paTimedOut' failed in 'src/os/unix/pa_unix_util.c', line: 387
> Expression 'PaUnixThread_New( &stream->thread, &CallbackThreadFunc, stream, 1., stream->rtSched )' failed in 'src/hostapi/alsa/pa_linux_alsa.c', line: 2998
> Expression 'pthread_join( self->thread, &pret )' failed in 'src/os/unix/pa_unix_util.c', line: 441

Et il ne se passe rien... 

Une idée ? 
Merci par avance

**Comment by stefanekz** [comment]
Problem resolved ! 
          Il suffit de renseigner les deux clés après inscription, 32 caractères pour bing et 40 pour snowboy.

Un copie de l'écran de configuration ci-dessous :)                                                                 
  ┌────────────────────────────────┤ Jarvis ├────────────────────────────────┐  
  │ Configuration > Voice recognition                                        │  
  │                                                                          │  
  │  Recognition of magic word (snowboy)                                     │  
  │  Recognition of commands (bing)                                          │  
  │  Snowboy sensitivity (0.4)                                               │  
  │  Snowboy token (***************************************)                │  
  │  Snowboy train a hotword/command                                         │  
  │  Bing key (******************************)                             │  
  │  Wit key ()                                                              │  
  │  PocketSphinx dictionary (stt_engines/pocketsphinx/jarvis-dictionary.di  │  
  │  PocketSphinx language model (stt_engines/pocketsphinx/jarvis-languagem  │  
  │  PocketSphinx logs (/dev/null)                                           │  
  │                                                                          │  
  │                                                                          │  
  │                                                                          │  
  │                                                                          │  
  │                   <Ok>                       <Cancel>

**Comment by alexylem** [comment]
Les clés sont normalement demandées lors de l'installation 😄
