### ISSUE TITLE
Comment enlever le micro à jarvis

### ISSUE THREAD

**Issue by manattom** [alexylem/jarvis#407]
Bonjour,
je commande jarvis depuis ma tablette avec OK google, et j'aimerais enlever le micro.
si je le débranche cela provoque des erreurs.
comment faire ? merci pour votre aide
```

**Comment by Jean-Bernard-Hallez** [comment]
le plus simple si ca te provoque des erreurs et de mettre le réglage de la sensibilité à 0. comme ca il ne se déclenchera pas... (setting, audio, sensibivity=0).

**Comment by manattom** [comment]
Si j' enlève le micro de la prise usb du rasperry, et que je lance jarvis, il se met en erreure et ne se lance pas.

**Comment by alexylem** [comment]
Tu peux coller ce qui s'affiche à l'écran en mode troubleshooting, ainsi je pourrais mieux t'aider.
Sinon je pense qu'en le lançant en mode clavier ca devrait passer sans soucis:
```
$> ./jarvis -k
```

**Comment by wikijm** [comment]
Bonsoir @manattom, 

Si tu as toujours le problème malgré le lancement en mode clavier, crée une "capture" de ton terminal avec https://asciinema.org/ ou le logiciel ScreenToGIF.

**Comment by manattom** [comment]
Merci pour votre aide.
en lançant Jarvis avec la commande ./jarvis.sh -b:k   ça fonctionne sans micro branché
