### ISSUE TITLE
commande multi Hotword jamais reconnus

### ISSUE THREAD

**Issue by giova-fr** [alexylem/jarvis#408]
J'utilise snowboy sur un raspberry pi3, sous jessie, avec un micro branché sur une carte son USB.
si je crée les commandes suivantes : 
```
ALLUME==say "test1"
SALON==say "test2" 
```

Tout va bien lors des essais

maintenant si je repart sur un fichier vierge où j'écris juste : 
`*ALLUME*SALON*==say "encore test"`
J'obtiens aléatoirement :
"unknown command allume"
ou
"unknown command salon"

en fait des qu'il entend le hotword ALLUME il arrette l'écoute immédiatement...
J'ai essayé en virant les asterix ;
J'ai essayé de jouer dans les réglages, en augmentant le "noise duration to stop" à 1.5 (au lieu de 0.1) mais rien n'y fait.

que faire SVP?

PS : je ne vous parle pas des segmentation fault que j'obtiens aléatoirement avec snowboy, c'est une autre histoire ;)

**Comment by tigre-bleu** [comment]
Je pense que c'est normal si tu as configuré 2 hotwords "Allume" et "Salon", snowboy va matcher le premier qu'il comprend et lancer la commande approriée.

Si tu veux matcher "Allume le salon" il faut enregistrer un hotword "Allume le salon" mais ça ne déclenchera pas avec quelque chose comme "Allume la lumière du salon".

**Comment by alexylem** [comment]
Je plussoie @tigre-bleu. Si tu veux utiliser snowboy pour les quick commands, alors il faut trainer l'ordre entier (dont le nom doit matcher dans tes commandes). Sinon utiliser un autre moteur comme bing pour des ordres non déterministes.

**Comment by wikijm** [comment]
@giova-fr Est-ce que les réponses de @tigre-bleu et @alexylem a répondu à ta question ?

Enfin, peux-tu nous confirmer que tu utilise ce modèle ? http://support.logitech.fr/fr_fr/product/quickcam-zoom
Cela nous permettra de faire évoluer la page http://domotiquefacile.fr/jarvis/content/prerequisites contenant le matériel testé avec Jarvis.

**Comment by wikijm** [comment]
Pas de réponse à ma relance, je clôture l'issue. 
Ne pas hésiter à rouvrir en cas d'avancée.
