### ISSUE TITLE
Liste des plugins en cours de développement

### ISSUE THREAD

**Issue by mbl-35** [alexylem/jarvis#409]
Je propose que les personnes qui sont en cours de développement de plugins puissent référencer leur repos afin de pouvoir contribuer ensemble ou tester les nouvelles fonctionnalités.
Pour ma part, je suis intéressé par la partie interprétation des commandes en RiveScript (mais je sais qu'il y a déjà quelqu'un dessus...).

**Comment by alexylem** [comment]
Pour ceux qui veulent suggérer ou partager un plugin en cours de développement, créer un ticket. Je les tag avec le label "Plugin request". Ainsi on peut facilement voir les plugins en cours et l'auteur peut y partager son repo pour les tests.

**Comment by wikijm** [comment]
Ne pourrait-on pas plutôt les référencer dans ce ticket ?
1 ticket par proposition, ça va faire beaucoup.

**Comment by alexylem** [comment]
L'avantage d'un ticket par plugin est qu'on peut discuter des idées, réunir des bêta testeurs, faire des retour sur les version alpha non publiées, discuter des détails, ...
Pour les lister tous, il suffit d'aller sur l'URL:
https://github.com/alexylem/jarvis/labels/plugin%20request
T'en penses quoi?

**Comment by wikijm** [comment]
Vendu 👍 
Désolé, j'aime pas voir un nombre trop important de tickets ouverts.
Déformation professionnelle sans doute ;-)

**Comment by alexylem** [comment]
Je me suis fait une raison 😄 .
Du moment qu'ils ne sont pas libellés "Bug" alors ça va 👍
