### ISSUE TITLE
Nouveau TTS avec Ivona Speech Could

### ISSUE THREAD

**Issue by alexylem** [alexylem/jarvis#41]
Hello, je viens de tomber sur un nouveau moteur de synthese vocale Ivona Speech Could.

Démo ici:
https://www.ivona.com/us/

Documentation ici:
http://developer.ivona.com/en/speechcloud/introduction.html

Moi il ne me motive pas trop car je prefere fonctionner en local, mais le resulat est pas mal, voix masculine et feminine, peu de latence, en fait tu streames le resultat, mais oblige d'etre connecte.

Aeliss

**Comment by alexylem** [comment]
Limitation à 50,000 units/month:

> You can use Speech Cloud for development purposes for free, up to 50,000 units/month per development account. If you wish to use Speech Cloud for commercial purposes, there is a $1,000 USD non-refundable, monthly flat fee for up to 250k units (see definition of a unit below). Any additional units (rounded down to the nearest 1,000 units) in a given month will incur an additional charge of $0.003 per unit.

Ce qui fait environ 1600 appels par jour.

**Comment by remjou1** [comment]
mouais je suis pas trop convaincus... pas très naturelle le voix

**Comment by alexylem** [comment]
Le gros avantage est qu'il y a une voix masculine.
Beaucoup d'utilisateurs de Jarvis le demandent.

**Comment by remjou1** [comment]
oui moi compris mdr ^^

**Comment by Smanar** [comment]
Et il a un autre gros avantage, la latence.
Avec picoTTS, ca prend du temps pour creer le fichier WAV, surtout pour des phrases longues comme quand tu demandes une definition de mot. En passant par ivona c'est beaucoup plus rapide.
Par contre je n'ai pas vu la limite de caracteres pour la phrase a envoyer ? La demo est limitee a 250 caracteres, mais rien vu pour l'api directe ?

**Comment by alexylem** [comment]
@Smanar j'ai fait la comparaison et sur raspberry pi 3, picoTTS semble bien plus plus rapide que Google voice (sauf si les wav sont dispo en cache). Il faudrait faire un vrai benchmark pour en être sûr, car doit doit aussi beaucoup dépendre de la connection internet (latence).

**Comment by Smanar** [comment]
Nope, pour google voice, c'est comme picoTTS, le serveur genere le fichier et te renvois un fichier son complet (de memoire).
Pour Ivona, tu streames le resultats, elle continue a generer ton fichier alors que tu commences deja a le lire.
Apres comme tu dis ca va dependre de la connexion, la ca va etre pire si le debit ne suis pas, coupure ou deconnexion durant la phrase ....

**Comment by alexylem** [comment]
@Smanar Ah ok j'ai compris, je suis d'accord, au lieu de générer le fichier son entièrement puis de le faire lire, on pourrait lire le stream au fur et à mesure qu'il est générer.
Je pense même que ca doit être possible avec Google, à tester.

J'ai créé le ticket #59 pour suivre l'implémentation de cette idée. Merci @Smanar

**Comment by alexylem** [comment]
Voix masculine désormais disponible (online) avec #267
