### ISSUE TITLE
Mise a jour impossible

### ISSUE THREAD

**Issue by Qweetttuu** [alexylem/jarvis#412]
bonjour, voila le problème. Une idée ?

Checking updates for jarvis...New version available
Updating jarvis...error: Your local changes to the following files would be overwritten by merge:
	jarvis-functions.sh
Please, commit your changes or stash them before you can merge.
Aborting
Done
Checking updates for jarvis-api...Up-to-date
Checking updates for jarvis-kodi...Up-to-date
Checking updates for jarvis-minuterie...Up-to-date
Checking updates for jarvis-plugin-ai...Up-to-date
Checking updates for jarvis-radio...Up-to-date
Checking updates for jarvis-time...Up-to-date
Checking updates for jarvis-ui...Up-to-date
Checking updates for jarvis-weather-wunderground-fr...Up-to-date
Checking updates for jarvis-wikipedia...Up-to-date

**Comment by oeildefeu** [comment]
t'as fait une modif dans le fichier jarvis-functions.sh et du coup git ne veut pas mettre à jour pour ne pas écraser tes modifs

**Comment by alexylem** [comment]
#251

**Comment by Qweetttuu** [comment]
Merci je testerai .
