### ISSUE TITLE
Utiliser des Leds sur le Port GPIO .... Voici comment on fait:

### ISSUE THREAD

**Issue by Jean-Bernard-Hallez** [alexylem/jarvis#413]
Pour ceux qui veulent bricoler leur Jarvis avec un peu de lumière.... afin de le rendre un peu plus  vivant...

https://github.com/Jean-Bernard-Hallez/jarvis-testjb/blob/master/Jarvis%20de%20JB.pdf

![image](https://cloud.githubusercontent.com/assets/11017174/22706320/11fd818e-ed6f-11e6-91f7-282c8455d438.png)

**Comment by Lusitanos67** [comment]
L'idée est vraiment sympa

**Comment by alexylem** [comment]
@Jean-Bernard-Hallez  Ouuuaaaaaaaaaaahhhhhh!!!  👍  👍 
Je peux publier ton PDF sur le site de Jarvis? Ou je créé une page et je te donne les droits d'édition comme ca tu peux la faire évoluer 😄 
J'adore!!!

**Comment by Jean-Bernard-Hallez** [comment]
Oui bien sûr @alexylem ...   ;-)

**Comment by trarizakaria** [comment]
@alexylem,  pouvez vous mettre le lien de ce post sur le site de jarvis. Page des hook ?http://domotiquefacile.fr/jarvis/content/hooks

**Comment by alexylem** [comment]
@trarizakaria Voilà c'est fait.
Je pense aussi que je vais créer une nouvelle section "Projects" afin que chacun puisse publier sur le site des photos/vidéos de son projet utilisant Jarvis.

**Comment by trarizakaria** [comment]
@alexlylem oui tout a fait. D'autre part,  Jarvis mérite d'être très reconnu et les vidéos des membres sont importants,  j'ai vu beaucoup de vidéos sur le net qui font démonstration d'un certain jarvis/sarah mais pas ce jarvis, qui est normalement le plus simple et facile à  utiliser. Il y a seulement tes deux videos qui font référence à  ce jarvis. D'où  la nécessité de changer le nom à  mon avis. Et mettre dans les prochains videos "le_nouveau_non"/jarvis ou ex jarvis.  Personnellement la découverte de ce jarvis était une très belle surprise car je l'utilise sur une raspberry qui tourne déjà  en plein régime et fait bcp de tâches à  la fois. Alors que pour les autres il faut avoir du materiel puissants. Une fois achevé mes bidouilles je vais faire une vidéo hommage à  notre jarvis :) le meilleur au monde :) salutations à  alex et à  tout les membres qui font évoluer ce projet 👍

**Comment by alexylem** [comment]
@trarizakaria merci bcp!
Je viens de créer la page Projects:
http://domotiquefacile.fr/jarvis/projects
Tous les membres du site (il suffit de s'enregistrer) peuvent soumettre leur projet. Derrière j'ai une notif pour publier.
J'ai ajouté un projet sous le nom de @Jean-Bernard-Hallez je l'ai associé à ton utilisateur, pour que tu puisses le modifier/compléter. @Jean-Bernard-Hallez si tu as besoin d'aide la dessus n'hésites pas!
Alex.

**Comment by Jean-Bernard-Hallez** [comment]
Je peux donc clôturer ce ticket...
