### ISSUE TITLE
Problème snowboy

### ISSUE THREAD

**Issue by Leflemmard** [alexylem/jarvis#414]
### Description

Bonjours,
J'ai un petit souci. A la fin de l’installation de Javis je doit dicter Jarvis plusieur fois a snowbol et a chaque fois a la fin je tombe sur aborted.
J'utilise le micro d'une webcam (quickcam zoom) sur raspberry.

### Result
Input File     : 'default' (alsa)
Channels       : 1
Sample Rate    : 11025
Precision      : 16-bit
Sample Encoding: 16-bit Signed Integer PCM

In:0.00% 00:00:06.69 [00:00:00.00] Out:92.1k [      |      ]        Clip:0    ^C
Aborted.

**Comment by alexylem** [comment]
mmmmh c'est normal car tu dois faire Ctrl+X pour le stopper.
Normalement il te demande de le refaire 2 fois (3 samples en tout) pour trainer le hotword.
Tu as bien les étapes suivantes?

**Comment by wikijm** [comment]
Bonsoir @Leflemmard,

Si tu as toujours le problème malgré l'explication d'@alexylem, crée une "capture" de ton terminal avec https://asciinema.org/ ou le logiciel [ScreenToGIF](http://www.screentogif.com/)

Enfin, peux-tu nous confirmer que tu utilise ce modèle ? http://support.logitech.fr/fr_fr/product/quickcam-zoom
Cela nous permettra de faire évoluer la page http://domotiquefacile.fr/jarvis/content/prerequisites contenant le matériel testé avec Jarvis.

**Comment by wikijm** [comment]
Pas de réponse à ma relance, je clôture l'issue. 
Ne pas hésiter à rouvrir en cas d'avancée.
