### ISSUE TITLE
IOError: [Errno Invalid input device (no default output device)] -9996

### ISSUE THREAD

**Issue by rberenger** [alexylem/jarvis#415]
### Description

Bonjour, Au lancement de ./jarvis.sh, j'ai une erreur : " ERROR: snowboy recognition failed "
En troubleshooting, voila ce qu'il me donne (j'ai l'impression que c'est un probleme avec python... mais je ne vois pas quoi

### Result
DEBUG: models=alexa,snowboy
Cannot connect to server socket err = No such file or directory
Cannot connect to server request channel
jack server is not running or cannot be started
Traceback (most recent call last):
  File "stt_engines/snowboy/main.py", line 51, in <module>
    detector = snowboydecoder.HotwordDetector(models, sensitivity=sensitivities)
  File "/home/pi/jarvis/stt_engines/snowboy/snowboydecoder.py", line 115, in __init__
    stream_callback=audio_callback)
  File "/usr/lib/python2.7/dist-packages/pyaudio.py", line 747, in open
    stream = Stream(self, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/pyaudio.py", line 442, in __init__
    self._stream = pa.open(**arguments)
IOError: [Errno Invalid input device (no default output device)] -9996
DEBUG: modelid=-10
ERROR: snowboy recognition failed
DEBUG: program exit handler
DEBUG: program_exit hook

Merci d'avance pour vos lumières

**Comment by alexylem** [comment]
Tu peux coller le résultat de la console avec Jarvis lancé en mode troubleshooting (c'est surtout le header avec la config qui m'intéresse).
Aussi si tu peux coller le résultat de:
```
$> cat ~/.asoundrc
```

**Comment by rberenger** [comment]
Bonjour :-)

Tu as raison, le problème venait bien de la définition de mes périphériques audio (entrée et sortie)
Après une réinstallation, mais surtout un bon paramétrage, ça fonctionne !

Maintenant, je vais m'attaquer à la reconnaissance vocale.

Merci beaucoup en tout cas, pour le projet, et pour le temps passé à nous aider !

**Comment by wikijm** [comment]
@rberenger Pense à clôturer le ticket si ton problème est résolu ;-)

**Comment by rberenger** [comment]
Oui, c'est vrai :-)
je débute........ avec Jarvis, mais aussi avec Github !

**Comment by alexylem** [comment]
I had the same issue today and rebooting my raspberry pi fixed the pb
