### ISSUE TITLE
Il y a t-il une variable dans jarvis qui permet de savoir si la commande est lancée par le micro ou par l'API ??

### ISSUE THREAD

**Issue by Jean-Bernard-Hallez** [alexylem/jarvis#416]
Je souhaite savoir au travers d'une variable et reconnaître d'où vient une commande... au travers du micro ou par l'externe via l'API... je ne sais pas si c'est possible...

**Comment by alexylem** [comment]
```shell
if $jv_json; then
    # via API
else
    # via Jarvis
fi
```
Si tu considère que le flag `-x` est aussi de l'API:
```shell
if $jv_json || $just_execute; then
    # via API
else
    # via Jarvis
fi
```

**Comment by Jean-Bernard-Hallez** [comment]
Ho Yes ça marche !!!!! Merci !!!!
