### ISSUE TITLE
Quelles lampes/ampoules utiliser avec Jarvis?

### ISSUE THREAD

**Issue by AlexandreAgrn** [alexylem/jarvis#417]
Bonjour,

Quelles sont les ampoules à utiliser ou le système pour contrôler l'éclairage des pièces avec Jarvis?
Et comment les configurer pour que Jarvis reconnaissance les différents pièces?

Merci
Cordialement, Alexandre

**Comment by rberenger** [comment]
Bonjour,
Je ne suis pas du tout expert, je donne juste mon avis de débutant : 
-Soit tu utilises un plugin de jarvis et donc tu t'équipes en conséquence (par exemple j'ai trouvé : Mi-light, light-lifx, hue). C'est peut être la solution pour contrôler que quelques ampoules, et si tu dois t'équiper de A à Z
-Soit tu as un système de domotique (par exemple jeedom ou domoticz qui va lui gérer l'allumage (et le reste : volet, température....)) et tu l'interfaces avec jarvis (via là aussi un plugin)

J'étais tombé sur ce tuto, ( https://easydomoticz.com/commandes-vocales-via-jarvis/ ) (et c'est comme ça que j'ai connu Jarvis, d'ailleurs). Je pense donc que je vais essayer de le suivre pour interfacer jarvis à mon domoticz.

**Comment by wikijm** [comment]
@rberenger C'est exact, Jarvis a pour vocation de lancer des actions après avoir détecté et reconnu certains mots-clés.
Pour piloter du matériel ou des logiciels spécifiques, il faudra se tourner vers la boutique de plugins.

**Comment by trarizakaria** [comment]
@Alexandreagrn  il faut acheter le controleur wifi avec les lampes. Le système domotique communique avec le controleur qui communique avec les lampes. Jarvis ne fait que transmettre des commandes au controlleur ou boitier domotique. Si tu veux du low cost tu peux acheter des ampoules mi light avec leur contrôleur wifi ibox1 ou des yeelight de xiaomi bien sur avec leur controleur.

**Comment by alexylem** [comment]
Pour info j'ai aussi récemment publié un plugin pour les systèmes domotique X10:
http://domotiquefacile.fr/jarvis/plugins/x10-mochad

**Comment by wikijm** [comment]
## Si l'on résume :

### Par Plugin dédié (protocole spécifique)

- [ ] [X10 Mochad](http://domotiquefacile.fr/jarvis/plugins/x10-mochad)
- [ ] [Philips Hue](http://domotiquefacile.fr/jarvis/plugins/hue)
- [ ] [Light-lifx](http://domotiquefacile.fr/jarvis/plugins/light-lifx)

### Par l’interfaçage avec des solutions de domotique

- [ ] [Jeedom](http://domotiquefacile.fr/jarvis/plugins/jeedom)
- [ ] Domoticz (voir plugin [Home Control](http://domotiquefacile.fr/jarvis/categories/home-automation))
