### ISSUE TITLE
Apache/jarvis

### ISSUE THREAD

**Issue by Lusitanos67** [alexylem/jarvis#418]
Bonjour,

J'aimerais savoir quel est le paramètre à modifier dans le service apache2 pour autoriser le flux sur le port 8080 et 8081 vers jarvis.
Lorsque je tente d'accéder à l'interface web en local, il refuse la connexion. Idem pour l'api jarvis.

Edit: je vais essayer avec .htaccess et une redirection vers 127.0.0.1:8081 depuis la config apache2

Merci

**Comment by wikijm** [comment]
Bonsoir @Lusitanos67,

Ce que tu demande est lié aux plugins https://github.com/alexylem/jarvis-ui et https://github.com/alexylem/jarvis-api. Il serait donc intéressant de créer un ticket à cet endroit-là.

Pour te répondre, il faut modifier pour chacun de ces plugins le fichier config.sh (cela peut être fait en lançant ./jarvis/jarvis.sh puis Store).

**Comment by Lusitanos67** [comment]
ok désolé je ferai attention.

Par contre je ne vois pas comment en modifiant un fichier config.sh, je vais indiquer à apache de rediriger le flux vers jarvis ?

**Comment by wikijm** [comment]
Pas de soucis, c'est juste qu'on essaye, au vu des nombreuses tickets d'incidents en cours, de ranger un peu tout ça ;-) 

Je me rends compte que je n'ai peut être pas compris ta question.
Jarvis-UI et Jarvis-API vont chacun se mettre en écoute sur le port qui leur est défini, et ce, en lançant leur propre 'instance web'. Ils ne passent pas par apache2.

**Comment by Lusitanos67** [comment]
Ok suite au reboot tout est ok, merci
