### ISSUE TITLE
Mots clés plugin non reconnu

### ISSUE THREAD

**Issue by Lusitanos67** [alexylem/jarvis#419]
Bonsoir,

Depuis une réinstallation toute fraîche de jarvis, les seuls commandes reconnus sont les natives, toutes les autres commandes qui proviennent de plugins ne sont plus reconnu, ai-je mal paramétré quelque chose ?

**Comment by wikijm** [comment]
Bonjour @Lusitanos67,

Peux-tu créer une "capture" de ton terminal avec https://asciinema.org/ ou le logiciel ScreenToGIF ?
Il serait également intéressant que tu fasse des tests en mode troubleshooting, pour ensuite en partager les résultats.

**Comment by Lusitanos67** [comment]
Petite précision, c'est en mode troubleshooting qu'il ne reconnaît aucun mot clé plugin.
J'ai démarré jarvis en mode normal (je ne l'avais encore jamais fait suite à l'installation), et la tout est revenu normal.

**Comment by alexylem** [comment]
Comme demandé par @wikijm merci de fournir des exemples d'utilisation en mode troubleshooting. Merci 👍

**Comment by Lusitanos67** [comment]
Impossible à te fournir, le problème ne se produit plus, à moins de réinstaller jarvis à nouveau

**Comment by alexylem** [comment]
Tant mieux alors 😄
