### ISSUE TITLE
Démarrer en domotique

### ISSUE THREAD

**Issue by 20-100-times** [alexylem/jarvis#420]
Bonjour,

Je viens d'installer Jarvis, et les possibilités présentées me paraissent énormes.

Je souhaiterais notamment faire de la domotique avec Jarvis, mais je ne sais pas du tout par où commencer... 

Auriez vous des prises à me conseiller, pour un budget de ~50€ ? Cela serait pour allumer des appareils basiques, chaîne Hifi, lampe, ordinateur...

J'ai vu qu'il existe beaucoup de plugin pour la domotique, quelles sont leur différences ?

Merci beaucoup

**Comment by alexylem** [comment]
On est à la limite du hors sujet. Jarvis permet se s'interfacer avec à priori n'importe quel système domotique qui peut être controlé de l'extérieur (http requests, ....). Tu pourrais faire un petit tour des plugins et te renseigner sur les prix des différentes solutions intégrées.
Moi perso j'utilise le X10 (depuis longtemps). Mais si c'était à refaire je partirais sur qqchose de plus moderne: chacon par exemple...
Un peu de lecture:
https://www.zodianet.com/la-toolbox/protocols-comparison.html
