### ISSUE TITLE
Probleme d'instalation

### ISSUE THREAD

**Issue by Propheet** [alexylem/jarvis#421]
Bonjour
je en sais pas si je suis on bon endroit pour poser la question j'ai un Raspberry pi 

j'ai installer "2017-01-11-raspbian-jessie"
et quand je fais l’installation de Jarvis sa ne fonctionne pas une idée

voici les donner
merci beaucoupp

**

**> login as: pi
> pi@192.168.1.9's password:
> 
> The programs included with the Debian GNU/Linux system are free software;
> the exact distribution terms for each program are described in the
> individual files in /usr/share/doc/*/copyright.
> 
> Debian GNU/Linux comes with ABSOLUTELY NO WARRANTY, to the extent
> permitted by applicable law.
> Last login: Fri Feb 10 21:27:05 2017
> 
> SSH is enabled and the default password for the 'pi' user has not been changed.
> This is a security risk - please login as the 'pi' user and type 'passwd' to set                                          a new password.
> 
> pi@raspberrypi:~ $ git clone https://github.com/alexylem/jarvis.git
> Cloning into 'jarvis'...
> remote: Counting objects: 2050, done.
> remote: Compressing objects: 100% (9/9), done.
> remote: Total 2050 (delta 1), reused 0 (delta 0), pack-reused 2040
> Receiving objects: 100% (2050/2050), 3.14 MiB | 757.00 KiB/s, done.
> Resolving deltas: 100% (1188/1188), done.
> Checking connectivity... done.
> pi@raspberrypi:~ $ cd jarvis/
> pi@raspberrypi:~/jarvis $ ./jarvis.sh
> You must install missing dependencies before going further
> jq: Not found
> sox: Not found
> mpg123: Not found
> Attempt to automatically install the above packages? [Y/n] y
> Reading package lists... Done
> Building dependency tree
> Reading state information... Done
> The following extra packages will be installed:
>   libopencore-amrnb0 libopencore-amrwb0 libsox-fmt-alsa libsox-fmt-base
>   libsox2
> Suggested packages:
>   libsox-fmt-all nas oss-compat oss4-base
> The following NEW packages will be installed:
>   jq libopencore-amrnb0 libopencore-amrwb0 libsox-fmt-alsa libsox-fmt-base
>   libsox2 mpg123 sox
> 0 upgraded, 8 newly installed, 0 to remove and 0 not upgraded.
> Need to get 847 kB of archives.
> After this operation, 1,792 kB of additional disk space will be used.
> Get:1 http://mirrordirector.raspbian.org/raspbian/ jessie/main libopencore-amrnb                                         0 armhf 0.1.3-2.1 [80.4 kB]
> Err http://mirrordirector.raspbian.org/raspbian/ jessie/main jq armhf 1.4-2.1
>   404  Not Found [IP: 2001:41c9:1:3ce::11 80]
> Get:2 http://mirrordirector.raspbian.org/raspbian/ jessie/main libsox2 armhf 14.                                         4.1-5 [231 kB]
> Err http://mirrordirector.raspbian.org/raspbian/ jessie/main mpg123 armhf 1.20.1                                         -2
>   404  Not Found [IP: 2001:41c9:1:3ce::11 80]
> Get:3 http://mirrordirector.raspbian.org/raspbian/ jessie/main libopencore-amrwb                                         0 armhf 0.1.3-2.1 [42.0 kB]
> Get:4 http://mirrordirector.raspbian.org/raspbian/ jessie/main libsox-fmt-alsa a                                         rmhf 14.4.1-5 [47.0 kB]
> Get:5 http://mirrordirector.raspbian.org/raspbian/ jessie/main libsox-fmt-base a                                         rmhf 14.4.1-5 [63.8 kB]
> Get:6 http://mirrordirector.raspbian.org/raspbian/ jessie/main sox armhf 14.4.1-                                         5 [135 kB]
> Fetched 599 kB in 1s (507 kB/s)
> E: Failed to fetch http://mirrordirector.raspbian.org/raspbian/pool/main/j/jq/jq                                         _1.4-2.1_armhf.deb  404  Not Found [IP: 2001:41c9:1:3ce::11 80]
> 
> E: Failed to fetch http://mirrordirector.raspbian.org/raspbian/pool/main/m/mpg12                                         3/mpg123_1.20.1-2_armhf.deb  404  Not Found [IP: 2001:41c9:1:3ce::11 80]
> 
> E: Unable to fetch some archives, maybe run apt-get update or try with --fix-mis                                         sing?**

**

### Description

PLEASE SEARCH BEFORE existing tickets and in the docs
NB: for issues with plugins, please create in the corresponding repository

### Result
```shell
<paste here> content of the terminal after using Jarvis in troubleshooting mode
or attach a session recording using https://asciinema.org/
```

**Comment by Propheet** [comment]
je suis vrais en la matière mais je crois je peux me tromper que les liens de Jarvis ne sont plus a jours pour l’installation possible ?

http://mirrordirector.raspbian.org/raspbian/ jessie/main jq armhf 1.4-2.1
http://mirrordirector.raspbian.org/raspbian/ jessie/main mpg123 armhf 1.20.1-2
http://mirrordirector.raspbian.org/raspbian/pool/main/j/jq/jq_1.4-2.1_armh
http://mirrordirector.raspbian.org/raspbian/pool/main/m/mpg123/mpg123_1.20.1-2_armhf.deb

**Comment by alexylem** [comment]
Bonjour,
c'est quoi ces liens? Ca n'a rien à voir avec Jarvis...
Fais comme conseillé par ton erreur:
```
$> sudo apt-get update
$> sudo apt-get upgrade
```
Puis relance l'installation de Jarvis.

**Comment by Propheet** [comment]
Bonjour
alexylem voila comme tu la dis avec 
$> sudo apt-get update
$> sudo apt-get upgrade

sa fonctionne !!! :) ( je suis trop heureux)

PS :les liens je l'es ai trouver dans le msg d'erreur mais j'ai surement mal compris l'erreur :p dsl.
je vais me cacher dans un petit trou lol

j' en profite pour te dire que je suis vraiment épater par de ton travail avec Jarvis 

merci pour tout
