### ISSUE TITLE
Plugin google Calendar

### ISSUE THREAD

**Issue by RobyBioloid** [alexylem/jarvis#422]
Bonjour,

Serait il possible d'intégrer à JARVIS la gestion de calendrier du style Google Calendar.

On pourrait ainsi demander à JARVIS d'ajouter des événements à des dates et des heures précises (repas chez la belle-mère, rendez-vous chez le dentiste, etc ...)

JARVIS se chargerait de nous rappeler nos rendez-vous, anniversaire, planning du jour au démarrage ou à la demande.
On pourrait également demander les événements de la semaine ou du mois

Rob: Jarvis?
JARVIS: Oui Rob?
Rob: Donne moi les événements de la journée s'il te plait
JARVIS: Aujourd'hui, vous avez deux événements
JARVIS: Rendez vous chez le dentiste à 16h30.
JARVIS: Repas chez la belle-mère à 19H00

Rob: Ajoute un événement
JARVIS: Quel événement voulez vous ajouter?
Rob: Allez chercher des fleurs pour la saint valentin.
JARVIS: Donner moi le jour et l'heure de l'événement
Rob: Le 14 février 2017 à 8H30
JARVIS: Ok l'événement Aller chercher des fleurs pour la saint valentin le 14 février 2017 à 8H30 à bien été ajouté.

**Comment by wikijm** [comment]
Bonjour @RobyBioloid,

Pour information, une conversation concernant la demande de plugins est visible ici : https://github.com/alexylem/jarvis/issues/230

Comme tu pourras le voir, @ghost était également intéressé par ce genre de plugin, et @alexylem a donné le processus à suivre pour cela. En espérant que quelqu'un s'occupe de créer le plugin que tu demande ;-)

**Comment by Jean-Bernard-Hallez** [comment]
http://www.scripts-sharers.com/Tutos/GoogleCalendarApi.aspx
Le lien est mort sur #230... il y a ici la démarche à suivre mais c'est trop compliqué pour moi... snif....

**Comment by Dens26** [comment]
Merci pour ta participation.

Je suis tombé sur ce tuto ici qui explique comment récupérer les événement du calendrier
https://developers.google.com/google-apps/calendar/quickstart/python

**Comment by Jean-Bernard-Hallez** [comment]
Perso même avec ca qui a l'air beaucoup plus simple... Je sèche... il me dit
 File "quickstart.py", line 80
    from __future__ import print_function
SyntaxError: from __future__ imports must occur at the beginning of the file

**Comment by Dens26** [comment]
Je n'ai pas ce problème la!

J'arrive à récupérer mes événements en ayant suivi le tuto

Si je comprends bien
Ton erreur est à la ligne 80 ou il y aurait ton import from__future__ import print_function alors que cet appel doit être fait au tout début du code

**Comment by Dens26** [comment]
Bon j'arrive bien à gérer le programme en python. Le hic c'est que Jarvis est programmé en Bash et j'avoue être un peu perdu sur le coup

**Comment by Jean-Bernard-Hallez** [comment]
Je t'encourage....   ;-)

**Comment by RobyBioloid** [comment]
J'ai posté un plugin jarvis-calendar si ça intéresse. 

N'étant pas expert en bash , j'ai un peu contourné le problème.

Voici comment le plugin fonctionne:
- commands enregistre si nécessaire les info utile dans événement.txt puis appel une fonction dans function.sh
- function.sh:
  - appel un script python qui récupère les info nécessaire si besoin et enregistre le résultat dans événement. txt
  - lit le fichier événement.txt

**Comment by wikijm** [comment]
@Dens26 Que penses-tu de ce qu'a fait @RobyBioloid ?
Vous étiez parti sur la même chose ?

**Comment by RobyBioloid** [comment]
Désolé, j'ai créé deux compte sans m'en rendre compte. Du coup selon le PC avec lequel je post, je ne suis pas loger sur le même compte.

En gros @Dens26 et @RobyBioloid, c'est moi même

**Comment by wikijm** [comment]
Ceci explique cela. J’imagine donc que tu ne pense que du bien de ce que tu as fait ;-)

Je clôture ce ticket, et j'invite les gens qui souhaitent discuter de ton plugin d'aller sur son repository : https://github.com/RobyBioloid/jarvis-calendar

Merci beaucoup pour le travail que tu as fait @RobyBioloid

**Comment by Jean-Bernard-Hallez** [comment]
Excellent @RobyBioloid... !!!! Merci encore...
J'ai un léger soucis à l'installation, quoi que je demande ca me dit:

python: can't open file 'python/nextEvent.py': [Errno 2] No such file or directory
plugins/jarvis-calendar/fr/functions.sh: ligne 26: python/evenement.txt: Aucun fichier ou dossier de ce type

As-tu une idée ?

**Comment by wikijm** [comment]
Roh @Jean-Bernard-Hallez, tu devrais le savoir depuis le temps que tu apporte tes compétences et conseils sur le projet :trollface: :

> Pour toute question ou problème lié à un plugin Jarvis, merci de créer un ticket sur le repository correspondant. Ainsi son auteur en sera informé et pourra vous aider.
> 
> Ok, alors c'est où?
> 
>     Depuis Jarvis, allez dans Plugins > Installed > The Plugin > Report an issue
>     Depuis le site, allez sur la page du plugin et cliquez sur le lien "Open a ticket"
> 
> Autrement dit, je ne fait pas de support pour les plugins tiers.
> Merci de votre compréhension.

**Comment by Jean-Bernard-Hallez** [comment]
Oui c'est vrai @wikijm...

**Comment by RobyBioloid** [comment]
J'ai mis à jour le plugin.  Ça devrait être bon
