### ISSUE TITLE
Google Calendar

### ISSUE THREAD

**Issue by RobyBioloid** [alexylem/jarvis#423]
Bonjour,

Serait il possible d'intégrer à JARVIS la gestion de calendrier du style Google Calandar.

On pourrait ainsi demander à JARVIS d'ajouter des événements à des dates et des heures précises (repas chez la belle-mère, rendez-vous chez le dentiste, etc ...)

JARVIS se chargerait de nous rappeler nos rendez-vous, anniversaire, planning du jour au démarrage ou à la demande.
On pourrait également demander les événements de la semaine ou du mois

Rob: Jarvis?
JARVIS: Oui Rob?
Rob: Donne moi les événements de la journée s'il te plait
JARVIS: Aujourd'hui, vous avez deux événements
JARVIS: Rendez vous chez le dentiste à 16h30.
JARVIS: Repas chez la belle-mère à 19H00

Rob: Ajoute un événement
JARVIS: Quel événement voulez vous ajouter?
Rob: Allez chercher des fleurs pour la saint valentin.
JARVIS: Donner moi le jour et l'heure de l'événement
Rob: Le 14 février 2017 à 8H30
JARVIS: Ok l'événement Aller chercher des fleurs pour la saint valentin le 14 février 2017 à 8H30 à bien été ajouté.

**Comment by alexylem** [comment]
Dupplicate #422
