### ISSUE TITLE
executer un fichier depuis plugin

### ISSUE THREAD

**Issue by Lusitanos67** [alexylem/jarvis#424]
Bonjour,

J'ai suivi la procédure d'Alex pour la création d'un plugin (avec un lien répertoire à l'exterieur de l'install jarvis + lien symbolique). Tout se passe bien, mais j'ai un soucis pour exécuter un fichier, dois-je mettre le chemin complet depuis le répertoire jarvis ? Impossible à exécuter ce fichier, pourtant depuis la console pas de soucis.

Des idées ?

**Comment by alexylem** [comment]
Oui, que ce soit dans les commandes utilisateurs, ou commandes plugin (installé ou lien symbolique), le dossier courant est celui de Jarvis. Tu peux vérifier avec un:
```shell
REPERTOIRE*COURANT==pwd
```
Si tu veux exécuter un fichier à l'intérieur de ton plugin, tu pourrais référencer le répertoire de ton plugin, mais le plus simple est encore de faire (dans functions.sh par exemple):
```shell
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
$DIR/my_file.sh
```

**Comment by Lusitanos67** [comment]
µOk, je teste ça et vous tiens au courant avec mes prises chacon ^^

**Comment by alexylem** [comment]
Un plugin Chacon? 😄

**Comment by Lusitanos67** [comment]
Tout à fait, mais tiré du tiens ^^ . Le truc c'est que je bossais dessus depuis un petit moment, mais le bash et moi on est pas pote, je me démerde plus en php et .net, chacun son truc :)

**Comment by Lusitanos67** [comment]
C'est ok ca fonctionne merci !
