### ISSUE TITLE
How to make jarvis stop listening in conversation mode

### ISSUE THREAD

**Issue by pckeller29** [alexylem/jarvis#425]
I am wondering how to reduce the time to exit conversation mode after a command has been run.
According to my watch, it takes 10s to leave this mode.
Does it have something related with 
`Max noise duration to kill`
Thank you

**Comment by alexylem** [comment]
>Does it have something related with

No.

You have two options:
* Disable the conversation mode in settings / general
* Create a command "Over" or so like this:
```
ANNULE*|TERMINE*==bypass=false; say "Ok"
```

**Comment by pckeller29** [comment]
OK Thank you.
