### ISSUE TITLE
Tutoriel pour le réglage audio ? 

### ISSUE THREAD

**Issue by wichtounet** [alexylem/jarvis#426]
Bonjour, 

Je suis en train de me battre avec la configuration audio pour avoir une bonne reconnaissance, mais sans trop de succès. Pleins de mes phrases ne sont pas comprises ou alors sont coupées entre deux mots et j'ai une quantité énorme de "Duration too long" dans le terminal. 

J'utilise snowboy pour le hotword et bing pour la reconnaissance. 

Le retour audio en mode debug me semble presque toujours très bien, mais malgré cela, il semble que les mots soient coupés ou alors que la reconnaissance soit mauvaise. J'ai plein de NOSPEECH et FALSERECO aussi. Certaines commandes marchent très bien, mais d'autres, c'est vraiment mauvais. Dans l'ensemble, j'arrive peut-être à 20% de reconnaissance, est-ce que c'est normal comme qualité ?

Est-ce qu'il existe un tutoriel pour le réglage des paramètres audio (min noise, mini silence, max, ...) ?

Merci

Baptiste

**Comment by alexylem** [comment]
Salut Baptiste,
Non c'est pas normal. Chez moi je suis à plus de 90% sans pb avec les réglages de base (micro PsEye).
Tu utilises quoi comme micro?
Pour les réglages de Sox tu peux voir #112 mais pas de tuto à proprement parler.
Sinon il y a aussi un set-up automatique dans les cartons #246

**Comment by wichtounet** [comment]
Salut, 

Merci pour ta réponse. 

J'utilises un micro Trust Mico. 

J'ai regardé plusieurs issues ici, et j'ai amélioré un peu les résultats avec les paramètres suivants:

Min noise duration 0.2
Min noise perc to start 2.4
Min silence duration 0.6
Min silence level 3.5

C'est pas encore parfait, mais au moins il me semble que tout ce qui est envoyé comme commande en ligne est correct. 

J'ai aussi changé de bing à wit.ai et j'ai de bien meilleurs résultats, je dois être prêt de 60% de reconnaissance complète. Avec wit.ai est-ce que je suis censé utiliser les intent au niveau de la configuration bot ou alors simplement me baser sur la reconnaissance ? 

Un set-up automatique serait d'une grande aide à mon avis. Ou au moins un tutoriel qui indique avec quelles options jouer dans quel cas. 

Je vais continuer à essayer d'optimiser cela. 

Baptiste

**Comment by alexylem** [comment]
>Avec wit.ai est-ce que je suis censé utiliser les intent au niveau de la configuration bot ou alors simplement me baser sur la reconnaissance ?

Non pas besoin. La reco est juste utilisée pour matcher tes commandes et celles des plugins.

**Comment by alexylem** [comment]
Je viens d'implémenter le setup automatique #246.
Il peut être lancé depuis:
* Settings > Audio > Audo-adjust levels

ou depuis le wizard:
* Settings > Wizard

ou encore:
```
$> ./jarvis.sh -i
```

J'aurais besoin de vos avis pour ajuster les minimums/maximums recommandés.
Merci de faire vos retours sur #246.
