### ISSUE TITLE
utils/utils.sh: ligne 261: plugins/*/hooks/program_exit: Aucun fichier ou dossier de ce type

### ISSUE THREAD

**Issue by wikijm** [alexylem/jarvis#427]
### Description

Message d'erreur suivant lors de l'ouverture ou de la fermeture de Jarvis :
`utils/utils.sh: ligne 261: plugins/*/hooks/program_exit: Aucun fichier ou dossier de ce type`

Je me demande si cela n'est pas du au commit https://github.com/alexylem/jarvis/commit/3a232bc3c431547a68002516622b2acc0bf9a343

Comme visible dans la vidéo ASCIINEMA ci-dessous, tout semble à jour.
La vidéo a été faite à partir d'une fresh install, mais le problème se produit également sur une installation moins récente.

### Result
https://asciinema.org/a/7lkkssalhoddvf15m8tfgdbgj

**Comment by alexylem** [comment]
Super pratique cet asciinema. Je corrige...
