### ISSUE TITLE
Compréhension mots/phrases faible

### ISSUE THREAD

**Issue by Lusitanos67** [alexylem/jarvis#429]
Bonsoir,

J'ouvre ce ticket dans le but de comprendre un peu ce qui se passe au moment de l'enregistrement (paramétrage), lecture de l'enregistrement, et retour (en fonction de wit ou bing dans mon cas). Je vois beaucoup de posts également qui parlent de reconnaissance très hasardeuses ou peu précises, certains évoquent 20% de compréhension, Alex plutôt 90% ^^.
Bref j'aime bien comprendre pourquoi, et puis je pense que la finalité de ces échanges permettra d'actualiser les docs concernant soit le paramétrage des micros, etc...

Ma config:
micro: Andoer
snowboy sensibility: 0.4
sensibilité: 64
min noise duration to start: 0.1
min noise % to start: 2.8%
min silence duration to stop: 0.5
min silence level to stop: 3.5%
Max noise duration to kill: 14

Je teste le hotword, à différentes distances: 1m, 2m, 5m
résultat: pas concluant peu importe la distance, même le bruit des pâtes de mes chiens déclenchent le hotword qui est "Alfred"... Je pense baisser vers 0.35

Je teste quelques phrases toujours sur différentes distances:1m, 2m, 5m
résultat: cata... Le seul cas ou j'ai pu avoir un positif à la reconnaissance c'est en parlant très doucement (pourtant je suis Alsacien ou c'est mon accent ^^), et en arrrrttttiiiiiiccccuuuullllant correctement les mots.
Il doit y avoir des recommandations d'enregistrement des voix depuis wit ou bing, afin d'optimiser la reconnaissance, mais cela m’échappe (exemple, envoyer une bande son, puis en résultat savoir si le son est ok, pas assez, fort, trop de bruit présent etc...). D’ailleurs le faite que nous ayons une licence "gratuite" par exemple sur bing ne jouerais pas sur la "détection" des mots en jouant un algorithme plus "light" ? 
Faut-il plutôt mettre la sensibilité du micro à son maximum quitte à augmenter le bruit aux alentours, ou/et de saturer la bande son avec sa voix ?
Est-il possible de rajouter une couche applicative, qui supprimerait ou viendrait rendre plus lisible, ou "accessible" la phrase envoyé au serveur (suppression des bruits de fonds) ?

J'envoie un enregistrement exemple, pour vous permettre de vous faire une idée de ce que je vie à la maison ^^. L'action étant de dire "allume le salon", ou "allume l'aquarium", ou "allume la cuisine", pareil avec le mot éteint. L'ensemble pilote des prises commandées (chacon).

https://drive.google.com/file/d/0BwztqWrYgkcTR2RKYmxZakZ1SjA/view?usp=sharing

**Comment by alexylem** [comment]
Salut à toi @Lusitanos67 et merci pour le partage.
En effet c'est pas du tout normal...
J'ai vraiment l'impression que c'est un pb avec le micro. A l'écoute du retour, on dirait qu'il y a de la résonnance/écho, comme si tu parlais dans une grande pièce vide.
A quelle distance parles-tu de ton micro?

Je pense de plus en plus travailler sur une détection automatique et réglage des niveaux en analysant le son, voir #246. Mais ca demande pas mal de boulot et je ne suis pas un spécialiste, même si je pense pouvoir arriver à qqchose.

Pour répondre à tes questions:
>D’ailleurs le faite que nous ayons une licence "gratuite" par exemple sur bing ne jouerais pas sur la "détection" des mots en jouant un algorithme plus "light" ?

Non. Franchement moi j'ai aucun pb donc ca ne vient pas de la.

>Faut-il plutôt mettre la sensibilité du micro à son maximum quitte à augmenter le bruit aux alentours, ou/et de saturer la bande son avec sa voix ?

Il faut éviter de saturer. Mais arriver le level doit arriver au dessus des 75%, sans pour autant dépasser les 100% (pas de saturation).

>Est-il possible de rajouter une couche applicative, qui supprimerait ou viendrait rendre plus lisible, ou "accessible" la phrase envoyé au serveur (suppression des bruits de fonds) ?

Pourquoi pas. Mais je pense que la qualité du micro est primordiale. D'après ce que je vois chez moi et les retours des autres utilisateurs. En gros plus le micro est de mauvaise qualité, plus il faut parler clairement et proche du micro. (quand je dis proche c'est moins de 30 cm...)

**Comment by Lusitanos67** [comment]
Merci pour ta réponse Alex,

Pour la saturation, comment sais-tu qu'applicativement parlant, pour bing tu es à la bonne valeur (son pas trop faible/saturé) ?  
Car visuellement côté jarvis, je pense que lors des tests d'enregistrement tant que tu ne vois pas le "!" c'est que ça ne sature pas c'est ça ?
Au moment des tests j'étais à ~3m, avec une sensibilité du micro "Andoer Omni-Directional" (qui fait parti de la liste ^^) à 43. En effet je note aussi cette effet de résonance, pourtant la pièce n'est pas vide... Il y a peut-être une piste là....

C'est con que le code retour ne t'indique pas ce que le serveur n'a pas "aimé", style son trop faible, trop saturé, trop echo, mauvaise qualité ^^

**Comment by alexylem** [comment]
Je viens d'implémenter le setup automatique #246.
Il peut être lancé depuis:
* Settings > Audio > Audo-adjust levels

ou depuis le wizard:
* Settings > Wizard

ou encore:
```
$> ./jarvis.sh -i
```

J'aurais besoin de vos avis pour ajuster les minimums/maximums recommandés.
Merci de faire vos retours sur #246.

**Comment by Lusitanos67** [comment]
Merci
