### ISSUE TITLE
Probleme avec snowboy et Soundblasteraxx 20

### ISSUE THREAD

**Issue by dviance47** [alexylem/jarvis#431]
Bonjour,

Tout nouveau sur Jarvis, je l'ai installé sur un RPI3 et j'ai connecté en usb une enceinte sound blasteraxx 20.

Lors du paramétrage de jarvis, j'ai entendu les applaudissements et l'enregistrement de ma voix.

Tout c'est bien passé jusqu'à ce que j’exécute jarvis.sh avec snowboy. Çà plante.
avec bing en reconnaissance du nom çà ne plante pas, mais çà ne détecte rien et rien ne se passe. aucun enregistrement ne se produit. (Alors qu'au moment de la configuration de jarvis l'enregistrement c’était bien  passé et a été bien restitué).

Aprés la lecture de tout ce qui peut etre lu ici et sur google, j'ai désactivé la carte interne de la rpi, ce qui fait que la sb20 est en Card0.
j'ai désinstallé pulseaudio. etc. etc.

Voici ce que j'ai avec aplay -l : 
```
**** Liste des Périphériques Matériels PLAYBACK ****
carte 0: S20 [Sound BlasterAxx SBX 20], périphérique 0: USB Audio [USB Audio]
  Sous-périphériques: 1/1
  Sous-périphérique #0: subdevice #0
```

Voici ce que j'ai dans .asoundrc :
```
pcm.!default {
	type hw
	card 0
}

ctl.!default {
	type hw
	card 0
}
```
Voici ce qui se passe quand j'execute jarvis avec snowboy : 
```
------------ Config ------------
jv_version           17.02.13 
jv_arch              armv7l 
jv_os_name           raspbian 
jv_os_version        8 
language             fr_FR 
play_hw              false 
rec_hw               false 
speaker              Default 
microphone           Default 
trigger_stt          snowboy 
command_stt          bing 
tts_engine           voxygen 
--------------------------------

Starting RestAPI server on http://192.168.1.20:8082
Starting User Interface on http://192.168.1.20:8081
DEBUG: program_startup hook
jarvis: bonjour maitre
DEBUG: start_speaking hook
DEBUG: stop_speaking hook
User defined commands:
*AIDE*			*BONJOUR*|*SALUT*	*COMMENT*APPELLE*
*MERCI*			*AU REVOIR*|*BYE*	ANNULE*|TERMINE*
ENCORE*			*TEST*			*VERSION*
*REPETE (*) ET (*)	*CA VA*			>*OUI*
>*NON*
Commands from plugin jarvis-plugin-ai:
*
Commands from plugin jarvis-ui:
*OUVR*INTERFACE*
Commands from plugin jarvis-api:

jarvis: Waiting to hear 'jarvis'
daniel: (listening...)
DEBUG: models=jarvis,snowboy
Expression 'paInvalidSampleRate' failed in 'src/hostapi/alsa/pa_linux_alsa.c', line: 2048
Expression 'PaAlsaStreamComponent_InitialConfigure( &self->capture, inParams, self->primeBuffers, hwParamsCapture, &realSr )' failed in 'src/hostapi/alsa/pa_linux_alsa.c', line: 2719
Expression 'PaAlsaStream_Configure( stream, inputParameters, outputParameters, sampleRate, framesPerBuffer, &inputLatency, &outputLatency, &hostBufferSizeMode )' failed in 'src/hostapi/alsa/pa_linux_alsa.c', line: 2843
Traceback (most recent call last):
  File "stt_engines/snowboy/main.py", line 51, in <module>
    detector = snowboydecoder.HotwordDetector(models, sensitivity=sensitivities)
  File "/home/pi/jarvis/stt_engines/snowboy/snowboydecoder.py", line 115, in __init__
    stream_callback=audio_callback)
  File "/usr/lib/python2.7/dist-packages/pyaudio.py", line 747, in open
    stream = Stream(self, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/pyaudio.py", line 442, in __init__
    self._stream = pa.open(**arguments)
IOError: [Errno Invalid sample rate] -9997
DEBUG: modelid=-10
ERROR: snowboy recognition failed
DEBUG: program_exit hook
```

Pourriez-vous m'aider et c'est l'enceinte qui n'ai pas reconnu ?
En sachant que la SB20 est reconnu en natif par raspbian et pixel.

Merci pour votre aide.

**Comment by alexylem** [comment]
T'as la même erreur que la: #311 ca vaudrait le coup d'oeil 😉

**Comment by alexylem** [comment]
D'ailleurs ton `~/.asoundrc` devrait ressembler à ca:
```shell
pcm.!default {
  type asym
   playback.pcm {
     type plug
     slave.pcm "hw:0,0"
   }
   capture.pcm {
     type plug
     slave.pcm "hw:1,0"
   }
}
```

**Comment by dviance47** [comment]
Merci. Je les avais tous lus... 
je regarde cela et je te tiens au courant.

**Comment by dviance47** [comment]
bon.
Je viens de tester la modification de .asoundrc et redémarrer. rien n'y fait. ca ne fonctionne pas.
C'est pas grave.
Maintenant il ne reste plus qu'à trouver le meilleur ensemble micro array qui pourra m'entendre assez loin (mon salon fait 40m²  et ca m'embete de devoir me lever pour changer les chaines de la télé, autant utiliser une tecommande) et qui m'entendra également s'il y a du bruit. Une petite idée de ce qu'il me faudrait ??

Encore merci et bravo pour ce projet, qui, au fil du temps, devient de plus en plus une tuerie.

**Comment by wikijm** [comment]
http://domotiquefacile.fr/jarvis/content/prerequisites
Ayant le JABRA 410/510, je ne pense pas que cela conviendrait à ton besoin.
[Andoer Omni-Directional](http://amzn.eu/5QyCqkQ) peut-être ?

**Comment by dviance47** [comment]
Merci pour ta réponse. Peut être que ce micro me conviendrait. vu le prix ça vaut le cout de le tester.
Quand tu dis que le Jabra ne conviendrait pas à mes besoins, qu'entends-tu par là? Car à ce prix là il devrait être mieux qu'un petit micro à 7€, non ?
En gros mes besoins sont assez génériques.
Je veux coupler la rpi3 à un ensemble micro/ enceinte et que le tout soit transportable et sans trop de fils apparent. (je fait attention au côté WAF). En gros je pose l'ensemble sur un meuble qui se trouve au mieux du salon et puisse couvrir un rayon assez important. En sachant que j'ai des enfants qui aiment bien parler (ou crier) en même temps que je souhaite donner un ordre domotique, j'aimerai qu'il y est une efficacité accrue.
J'ai commencé à essayé le principe de l'assistant vocal avec Sarah, mais beaucoup trop de faux positif, et la reconnaissance d'une seule voix la mienne (le côté WAF est tombé à zéro quand ma faite à fait une crise de jalousie car Sarah ne voulait parler qu'à une seule personne et bizarrement cette personne c'était moi !!!). Voilà en gros mes besoins, qui, je pense, sont les besoins de 98% des personnes en couple qui se lancent dans l'aventure de la domotique...lol

**Comment by wikijm** [comment]
J'ai juste peur que le JABRA 510 ne couvre pas tes 40 m2.
A voir si tu peux le placer au milieu de la salle.

**Comment by Oliv4945** [comment]
@dviance47, n'ayant pas de tes nouvelles depuis un moment, je ferme n'hésites pas à rouvrir si besoin.

Sinon pour être sur qu'Alexy t'as donné le bon conseil avec ton micro, est-ce que tu pourrais donner le résultat de `arecord -l` ?
