### ISSUE TITLE
Micro encastré

### ISSUE THREAD

**Issue by Dom420** [alexylem/jarvis#432]
Bonjour à tous,

Pour faire suite à la conversation de kiki51 : 
https://github.com/alexylem/jarvis/issues/285

Si on veut réaliser un système avec un micro par pièce pour avoir un accès à jarvis n'importe où et piloter pièce par pièce, que pensez vous d'un micro encastré de ce type:
http://www.canford.fr/CANFORD-MICROPHONE-De-surface-a-encastrer

En attente de vos avis !

**Comment by alexylem** [comment]
Ce micro n'a pas l'air d'être prévu pour de la reco vocale à distance. J'ai un doute sur la qualité de l'enregistrement et donc de la reconnaissance (pour cela il faut mieux les micro type mic array, ou comme le Jabra). De plus il faudra bien le brancher à qqchose, genre le système de @Jean-Bernard-Hallez avec ton plugin Maitre/Esclave?

**Comment by Dom420** [comment]
dac, par contre les micros type mic array ou jabra, c'est uniquement pour une utilisation proche se sera pas en encastré. J'en ai trouvé d'autres comme :

http://www.sononet.fr/FR/AUDIO%20TECHNICA-ES945%20Micro%20de%20surface%20omni%20encastrable-Produit-Fiche.awp?Sku=ES945

ou

http://www.sononet.fr/FR/AUDIO%20TECHNICA-ES947%20Micro%20de%20surface%20cardio%C3%AFde%20encastrable-Produit-Fiche.awp?Sku=ES947&AWPIDD6118E0F=C0FDD19D0B43017C47D0108FC3B096FB0979730D


Pas facile de comparer quand on y connait rien en micro, il faudrait je demande directement au constructeur ou à quelqu'un qui maitrise.

Il y a personne qui a fait une installation de ce genre?

**Comment by Dom420** [comment]
Si ça intéresse du monde, voici la réponse de Sononet :

"Pour faire suite à votre demande : 

Si vous souhaitez utiliser un microphone pour de la reconnaissance vocale, sachez que votre problème principale sera le bruit ambiant. 

Le modèle que vous nous avez communiqué est un microphone à directivité omnidirectionnelle. Autrement dit, une fois encastré le microphone va reproduire tous les sons captés autour de lui (captation à 360°).
Cela pourra être votre voix mais également des bruits parasites aux alentours. Je ne vous conseillerais donc pas ce modèle.  

Si vous optez pour un microphone avec une directivité Cardioïde, autrement dit une captation beaucoup plus ciblée. Ce modèle par exemple : http://tinyurl.com/j7ubntw (disponible en version noir ou blanche)
Vous allez pouvoir éliminer un niveau important de bruits parasites par rapport au modèle précédent. Ce microphone est conçu pour être utilisé lors d’enregistrements. Sa reproduction sonore est de très bonne qualité. 

Il faut également prendre en compte la sensibilité du microphone. 
A savoir qu’un microphone statique est très sensible aux manipulations. Si vous souhaitez l’encastrer veillez à choisir une zone où l’ambiance sonore sera plutôt faible. 
S’il s’agit d’un mur, prenez en compte que la moindre vibration de la paroi risque d’avoir des conséquences sur la captation du micro. 

Par ailleurs, les microphones statiques comme ce modèle nécessitent une alimentation fantôme de 48V. il faudra que l’interface soit pourvu d’une alimentation de ce type. "

**Comment by wikijm** [comment]
Merci pour ces infos @Dom420 :-)

**Comment by Oliv4945** [comment]
Je pense que la question est close, je ferme.
Ne pas hésiter à rouvrir si besoin
