### ISSUE TITLE
aide sur jarvis raspberry

### ISSUE THREAD

**Issue by madmax59860** [alexylem/jarvis#433]
### Description
bonjour je suis novice en programmation mais j'ai trouver le projet jarvis extraordinaire , voila apres plus d'une semaine d'essais rien ni fait , la reconnaissance vocale ne fonctionne pas , j'ai pensé a abondonner et a recycler mon raspberry en emulateur lol , mais apres beaucoup d'encouragement de ma femmes et de mes enfants je ne peu pas me resoudre a baisser les bras , pouvez vous m'apporter votre aide , je suis perdu dans le monde de linux et de ses programme , cordialement max

**Comment by oeildefeu** [comment]
Salut, tu peux nous en dire un peu plus ?
Quelle est la sortie du mode troubleshooting ?

**Comment by alexylem** [comment]
Bonjour à toi @madmax59860. Jarvis a été pensé pour les nulls qui n'ont pas peur de mettre les mains dans le cambouis, tu es au bon endroit 😄 
As-tu suivi pas à pas la procédure d'installation?
http://domotiquefacile.fr/jarvis/content/installation
Tu as bien installé Raspbian Jessie Full?
Tu bloques à quelle étape?
Une copie de ton terminal nous serait très utile.

**Comment by wikijm** [comment]
Bonsoir Max,

Il n'est pas nécessaire d'avoir de compétences en développement pour l'utiliser, seulement pour créer des plugins et participer à son évolution.

Je t'invite à utiliser https://asciinema.org/ ou http://www.screentogif.com/ pour nous montrer là où tu bloques, voire nous partager les logs lorsque tu lance Jarvis en [mode troubleshooting](http://domotiquefacile.fr/jarvis/content/usage)

**Comment by madmax59860** [comment]
​bonjour a tous et merci de votre reponse et de votre aide , dans un
premier temp je lance jarvis depuis une liaison ssh via le logiciel PUTTY
,  je vous met 3 screen , celui du lancement de la liaison ssh , celui du
mode troubleshooting et celui du lancement de jarvis en mode normal , merci
de votre aide
​

Le 16 février 2017 à 21:17, PGP 2F93D5AF <notifications@github.com> a écrit
:

**Comment by madmax59860** [comment]
a preciser q"en mode clavier , jarvis repond et execute correctement les
tache demander, ou presque , lol

**Comment by wikijm** [comment]
@madmax59860 Pour faciliter la lecture, est ce que tu pourrais te connecter à GitHub plutôt que répondre par mail ?
Je t'embête pour pas grand chose, mais c'est quand même plus sympa à lire et traiter 😁

**Comment by madmax59860** [comment]
voila ce que le mode trouble shooting me donne 

bouboule: Waiting to hear 'bouboule'
max: (listening...)
 rec -V1 -q -r 16000 -c 1 -b 16 -e signed-integer --endian little jarvis-record.wav silence 1 0.1 1% 1 0.5 1% trim 0 10
DEBUG: speech duration was 100 (10 = 1 sec)
DEBUG: too long for a trigger (min 0.5 max 1.5 sec), ignoring...
 rec -V1 -q -r 16000 -c 1 -b 16 -e signed-integer --endian little jarvis-record.wav silence 1 0.1 1% 1 0.5 1% trim 0 10
DEBUG: speech duration was 100 (10 = 1 sec)
DEBUG: too long for a trigger (min 0.5 max 1.5 sec), ignoring...
 rec -V1 -q -r 16000 -c 1 -b 16 -e signed-integer --endian little jarvis-record.wav silence 1 0.1 1% 1 0.5 1% trim 0 10

**Comment by madmax59860** [comment]
DEBUG: speech duration was 100 (10 = 1 sec)
DEBUG: too long for a trigger (min 0.5 max 1.5 sec), ignoring...
 rec -V1 -q -r 16000 -c 1 -b 16 -e signed-integer --endian little jarvis-record.wav silence 1 0.1 1% 1 0.5 1% trim 0 10
DEBUG: speech duration was 100 (10 = 1 sec)
DEBUG: too long for a trigger (min 0.5 max 1.5 sec), ignoring...
 rec -V1 -q -r 16000 -c 1 -b 16 -e signed-integer --endian little jarvis-record.wav silence 1 0.1 1% 1 0.5 1% trim 0 10
DEBUG: speech duration was 100 (10 = 1 sec)
DEBUG: too long for a trigger (min 0.5 max 1.5 sec), ignoring...
 rec -V1 -q -r 16000 -c 1 -b 16 -e signed-integer --endian little jarvis-record.wav silence 1 0.1 1% 1 0.5 1% trim 0 10
DEBUG: speech duration was  (10 = 1 sec)
jarvis-functions.sh: ligne 67 : [:  : nombre entier attendu comme expression
jarvis-functions.sh: ligne 70 : [:  : nombre entier attendu comme expression
play FAIL formats: can't open input file `jarvis-record.wav': No such file or directory
ERROR: play command failed
HELP: Verify your speaker in Settings > Audio > Speaker
DEBUG: program_exit hook
pi@raspberrypi:~/jarvis$ bouboule: Waiting to hear 'bouboule'
-bash: bouboule: : commande introuvable
pi@raspberrypi:~/jarvis$ max: (listening...)
-bash: erreur de syntaxe près du symbole inattendu « listening... »
pi@raspberrypi:~/jarvis$  rec -V1 -q -r 16000 -c 1 -b 16 -e signed-integer --endian little jarvis-record.wav silence 1 0.1 1% 1 0.5 1% trim 0 10
pi@raspberrypi:~/jarvis$ DEBUG: speech duration was 100 (10 = 1 sec)
-bash: erreur de syntaxe près du symbole inattendu « ( »
pi@raspberrypi:~/jarvis$ DEBUG: too long for a trigger (min 0.5 max 1.5 sec), ignoring...
-bash: erreur de syntaxe près du symbole inattendu « ( »
pi@raspberrypi:~/jarvis$  rec -V1 -q -r 16000 -c 1 -b 16 -e signed-integer --endian little jarvis-record.wav silence 1 0.1 1% 1 0.5 1% trim 0 10
pi@raspberrypi:~/jarvis$ DEBUG: speech duration was 100 (10 = 1 sec)
-bash: erreur de syntaxe près du symbole inattendu « ( »
pi@raspberrypi:~/jarvis$ DEBUG: too long for a trigger (min 0.5 max 1.5 sec), ignoring...
-bash: erreur de syntaxe près du symbole inattendu « ( »
pi@raspberrypi:~/jarvis$  rec -V1 -q -r 16000 -c 1 -b 16 -e signed-integer --endian little jarvis-record.wav silence 1 0.1 1% 1 0.5 1% trim 0 10

**Comment by madmax59860** [comment]
et voila ce que j'obtiens en le lançant en mode normal

bouboule: Waiting to hear 'bouboule'
max: #############

**Comment by wikijm** [comment]
@madmax59860 Il faudrait également afficher le début du troubleshooting mode, qui contient des infos sur ta configuration.

Exemple :
`pi@RaspAP2:~ $ ./jarvis/jarvis.sh -vk

------------ Config ------------
jv_version           17.02.16
jv_arch              armv7l
jv_os_name           raspbian
jv_os_version        8
language             fr_FR
play_hw              false
rec_hw               false
speaker              Default
microphone           Default
trigger_stt          snowboy
command_stt          bing
tts_engine           svox_pico
--------------------------------

Starting RestAPI server on http://192.168.0.60
192.168.0.61:8080
Starting User Interface on http://192.168.0.60
192.168.0.61:8081
DEBUG: program_startup hook
Jarvis: Bonjour
DEBUG: start_speaking hook
DEBUG: stop_speaking hook
User defined commands:
*AIDE*                  *BONJOUR*|*SALUT*       *COMMENT*APPELLE*
*MERCI*                 *AU REVOIR*|*BYE*       ANNULE*|TERMINE*
ENCORE*                 *TEST*                  *VERSION*
*REPETE (*) ET (*)      *CA VA*                 >*OUI*
>*NON*
`

P.S : Appeler `jarvis.sh -vk` permet de le lancer à la fois en mode troubleshooting et keyboard.

**Comment by madmax59860** [comment]
aussitôt dit aussitôt fait


------------ Config ------------
jv_version           17.02.16
jv_arch              armv7l
jv_os_name           raspbian
jv_os_version        8
language             fr_FR
play_hw              hw:1,0
rec_hw               hw:1,0
speaker              Logitech, Inc.
microphone           Logitech, Inc.
trigger_stt          bing
command_stt          bing
tts_engine           osx_say
--------------------------------

plugins/jarvis-radio/config.sh: ligne 12: caractère de fin de fichier (EOF) prématuré lors de la recherche du « ' » correspondant
plugins/jarvis-radio/config.sh: ligne 18: erreur de syntaxe : fin de fichier prématurée
Starting RestAPI server on http://192.168.1.20:8080
DEBUG: program_startup hook
bouboule: bonjour  max
DEBUG: start_speaking hook
tts_engines/osx_say/main.sh: ligne 18: /usr/bin/say: Aucun fichier ou dossier de ce type
DEBUG: stop_speaking hook
User defined commands:
X*AIDE*                 *BONJOUR*|*SALUT*       *COMMENT*APPELLE*
*MERCI*                 *AU REVOIR*|*BYE*       ANNULE*|TERMINE*
ENCORE*                 *TEST*                  *VERSION*
*REPETE (*) ET (*)      *CA VA*                 >*OUI*
>*NON*                  *COMMENT*ME*TROUVE*TU*  *QUELLE*HEURE*EST*IL*
*ME*VOIS*TU*            >*NON*                  >*OUI*
*JE*PAS*MAX             >*JE*ANGELIQUE*         >*JE*EMILIE*
>*JE*SAMI*              >JE*SYLVIE*             >*JE*PASCAL*
>*JE*CACAL*             >*JE*ChRISTOPHE*        >*JE*SEBASTIEN*
Commands from plugin jarvis-blagues:
*RACONT*BLAGUE*
Commands from plugin jarvis-google-map-traffic:
*TRAFIC*
Commands from plugin jarvis-wikipedia:
*DONNE*DEFINITION*DE (*
Commands from plugin fr_liveboxtv:
####################### #                       #######################
*allume la laveboxe*    *éteindre la laveboxe*  *coupe le son de la lav
*remets le son de la la *baisse le son de la la *monte le son de la lav
*chaine suivante*       *chaine précédente*     *augmente le son de la
*mets la laveboxe sur p *mets sur pause la lave *mets la lavebox en lec
*mets en lecture la lav *mets en avance rapide  *mets en retour rapide
*les infos du programme *enléve les infos*      *laveboxe OK*
*laveboxe menu*         *laveboxe droit*        *laveboxe gauche*
*laveboxe haut*         *laveboxe bas*          *laveboxe retour*
*laveboxe v.o.d*        *mets la laveboxe en en
                                ###############         #
        ############### #Code: Touche           #512 : 0
#513 : 1                #514 : 2                #515 : 3
#516 : 4                #517 : 5                #518 : 6
#519 : 7                #520 : 8                #521 : 9

*TF1*                   *France 2*              *France 3*
*Canal plus*            *France 5*              *M6*
*Arte*                  *D8*                    *W9*
*TMC*                   *NT1*                   *NRJ 12*
*LCP*                                           *La Chaine Parlementair
*France 4*              *BFM TV*                *I-Télé*
*D17*                   *Gulli*                 *France O*
*HD1*                   *L équipe*              *6 ter*
Commands from plugin jarvis-lacitation:
*PROVERBE*|*CITATION*
Commands from plugin jarvis-motiondetectiondlink:
*ALLUM*DETECTION*|*LANC *ETEIN*DETECTION*|*ARRE
Commands from plugin jarvis-music-player:

Commands from plugin jarvis-temperature:
*TEMPERATURE*
Commands from plugin jarvis-math:
*CALCUL* (*)
Commands from plugin jarvis-api:

Commands from plugin jarvis-radio:
*STOP*RADIO*            *LISTE*RADIO*           *VOLUME*MOINS*RADIO
*VOLUME*PLUS*RADIO      *LANCE*RADIO*           >(*)

Commands from plugin jarvis-home-control:
*ALLUME*                *ETEIN*
bouboule: Waiting to hear 'bouboule'
max: (listening...)
 rec -V1 -q -r 16000 -c 1 -b 16 -e signed-integer --endian little jarvis-record.wav silence 1 0.1 1% 1 0.5 1% trim 0 10
DEBUG: speech duration was 100 (10 = 1 sec)
DEBUG: too long for a trigger (min 0.5 max 1.5 sec), ignoring...
 rec -V1 -q -r 16000 -c 1 -b 16 -e signed-integer --endian little jarvis-record.wav silence 1 0.1 1% 1 0.5 1% trim 0 10
DEBUG: speech duration was 100 (10 = 1 sec)
DEBUG: too long for a trigger (min 0.5 max 1.5 sec), ignoring...
 rec -V1 -q -r 16000 -c 1 -b 16 -e signed-integer --endian little jarvis-record.wav silence 1 0.1 1% 1 0.5 1% trim 0 10

**Comment by wikijm** [comment]
> plugins/jarvis-radio/config.sh: ligne 12: caractère de fin de fichier (EOF) prématuré lors de la recherche du « ' » correspondant
> plugins/jarvis-radio/config.sh: ligne 18: erreur de syntaxe : fin de fichier prématurée

Tu as un problème avec le plugin jarvis-radio (lignes 12). Désinstalle-le ou corrige l'erreur si tu sais comment faire.

**Comment by madmax59860** [comment]
je vais desinstaller les plugin pour qu'on y voit plus claire

**Comment by madmax59860** [comment]
------------ Config ------------
jv_version           17.02.16
jv_arch              armv7l
jv_os_name           raspbian
jv_os_version        8
language             fr_FR
play_hw              hw:1,0
rec_hw               hw:1,0
speaker              Logitech, Inc.
microphone           Logitech, Inc.
trigger_stt          bing
command_stt          bing
tts_engine           osx_say
--------------------------------

Starting RestAPI server on http://192.168.1.20:8080
DEBUG: program_startup hook
bouboule: bonjour  max
DEBUG: start_speaking hook
tts_engines/osx_say/main.sh: ligne 18: /usr/bin/say: Aucun fichier ou dossier de ce type
DEBUG: stop_speaking hook
User defined commands:
X*AIDE*                 *BONJOUR*|*SALUT*       *COMMENT*APPELLE*
*MERCI*                 *AU REVOIR*|*BYE*       ANNULE*|TERMINE*
ENCORE*                 *TEST*                  *VERSION*
*REPETE (*) ET (*)      *CA VA*                 >*OUI*
>*NON*                  *COMMENT*ME*TROUVE*TU*  *QUELLE*HEURE*EST*IL*
*ME*VOIS*TU*            >*NON*                  >*OUI*
*JE*PAS*MAX             >*JE*ANGELIQUE*         >*JE*EMILIE*
>*JE*SAMI*              >JE*SYLVIE*             >*JE*PASCAL*
>*JE*CACAL*             >*JE*ChRISTOPHE*        >*JE*SEBASTIEN*
Commands from plugin jarvis-api:

bouboule: Waiting to hear 'bouboule'
max: (listening...)
 rec -V1 -q -r 16000 -c 1 -b 16 -e signed-integer --endian little jarvis-record.wav silence 1 0.1 1% 1 0.5 1% trim 0 10
DEBUG: speech duration was 100 (10 = 1 sec)
DEBUG: too long for a trigger (min 0.5 max 1.5 sec), ignoring...
 rec -V1 -q -r 16000 -c 1 -b 16 -e signed-integer --endian little jarvis-record.wav silence 1 0.1 1% 1 0.5 1% trim 0 10
DEBUG: speech duration was 100 (10 = 1 sec)
DEBUG: too long for a trigger (min 0.5 max 1.5 sec), ignoring...
 rec -V1 -q -r 16000 -c 1 -b 16 -e signed-integer --endian little jarvis-record.wav silence 1 0.1 1% 1 0.5 1% trim 0 10

**Comment by madmax59860** [comment]
voila j'ai virer les plugin

**Comment by wikijm** [comment]
> ------------ Config ------------
> jv_os_name raspbian
> jv_os_version 8
> trigger_stt bing
> command_stt bing
> tts_engine osx_say

Tu semble être sous Raspbian.
Pourquoi dans ce cas utilises-tu osx_say (réservé à ceux sur Mac OS) ?
Je t'invite plutôt à utiliser svox_pico ou espeak.

En règle générale, essaye d'utiliser les choix par défaut avant d'essayer quelque chose de plus exotique ;-)

**Comment by madmax59860** [comment]
c'est parce que j'ai tout essayer et du fait c'est le dernier que j'ai essayer , je vais remettre svox_pico

**Comment by madmax59860** [comment]
------------ Config ------------
jv_version           17.02.16
jv_arch              armv7l
jv_os_name           raspbian
jv_os_version        8
language             fr_FR
play_hw              hw:1,0
rec_hw               hw:1,0
speaker              Logitech, Inc.
microphone           Logitech, Inc.
trigger_stt          bing
command_stt          bing
tts_engine           svox_pico
--------------------------------

Starting RestAPI server on http://192.168.1.20:8080
DEBUG: program_startup hook
bouboule: bonjour  max
DEBUG: start_speaking hook
DEBUG: stop_speaking hook
User defined commands:
X*AIDE*                 *BONJOUR*|*SALUT*       *COMMENT*APPELLE*
*MERCI*                 *AU REVOIR*|*BYE*       ANNULE*|TERMINE*
ENCORE*                 *TEST*                  *VERSION*
*REPETE (*) ET (*)      *CA VA*                 >*OUI*
>*NON*                  *COMMENT*ME*TROUVE*TU*  *QUELLE*HEURE*EST*IL*
*ME*VOIS*TU*            >*NON*                  >*OUI*
*JE*PAS*MAX             >*JE*ANGELIQUE*         >*JE*EMILIE*
>*JE*SAMI*              >JE*SYLVIE*             >*JE*PASCAL*
>*JE*CACAL*             >*JE*ChRISTOPHE*        >*JE*SEBASTIEN*
Commands from plugin jarvis-api:

bouboule: Waiting to hear 'bouboule'
max: (listening...)
 rec -V1 -q -r 16000 -c 1 -b 16 -e signed-integer --endian little jarvis-record.wav silence 1 0.1 1% 1 0.5 1% trim 0 10
DEBUG: speech duration was 100 (10 = 1 sec)
DEBUG: too long for a trigger (min 0.5 max 1.5 sec), ignoring...
 rec -V1 -q -r 16000 -c 1 -b 16 -e signed-integer --endian little jarvis-record.wav silence 1 0.1 1% 1 0.5 1% trim 0 10
DEBUG: speech duration was 100 (10 = 1 sec)
DEBUG: too long for a trigger (min 0.5 max 1.5 sec), ignoring...
 rec -V1 -q -r 16000 -c 1 -b 16 -e signed-integer --endian little jarvis-record.wav silence 1 0.1 1% 1 0.5 1% trim 0 10
   voila j'ai remis pico et sa change rien amon probleme

**Comment by wikijm** [comment]
> DEBUG: too long for a trigger (min 0.5 max 1.5 sec), ignoring...
Pour ça, je penserais à un problème de compréhension du terme 'bouboule' par Bing.

Essaye pour l'instant d'utiliser Snowboy en tant que trigger_stt

**Comment by madmax59860** [comment]
bon voici se que j'obtiens lorsque j'utilise snowboy 



------------ Config ------------
jv_version           17.02.16
jv_arch              armv7l
jv_os_name           raspbian
jv_os_version        8
language             fr_FR
play_hw              hw:1,0
rec_hw               hw:1,0
speaker              Logitech, Inc.
microphone           Logitech, Inc.
trigger_stt          snowboy
command_stt          snowboy
tts_engine           svox_pico
--------------------------------

Starting RestAPI server on http://192.168.1.20:8080
DEBUG: program_startup hook
snowboy: bonjour  max
DEBUG: start_speaking hook
DEBUG: stop_speaking hook
User defined commands:
X*AIDE*                 *BONJOUR*|*SALUT*       *COMMENT*APPELLE*
*MERCI*                 *AU REVOIR*|*BYE*       ANNULE*|TERMINE*
ENCORE*                 *TEST*                  *VERSION*
*REPETE (*) ET (*)      *CA VA*                 >*OUI*
>*NON*                  *COMMENT*ME*TROUVE*TU*  *QUELLE*HEURE*EST*IL*
*ME*VOIS*TU*            >*NON*                  >*OUI*
*JE*PAS*MAX             >*JE*ANGELIQUE*         >*JE*EMILIE*
>*JE*SAMI*              >JE*SYLVIE*             >*JE*PASCAL*
>*JE*CACAL*             >*JE*ChRISTOPHE*        >*JE*SEBASTIEN*
Commands from plugin jarvis-api:

snowboy: Waiting to hear 'snowboy'
max: (listening...)
DEBUG: models=alexa,snowboy
Cannot connect to server socket err = No such file or directory
Cannot connect to server request channel
jack server is not running or cannot be started

**Comment by madmax59860** [comment]
j'ai deja essayer de changer ou d'intervertir les trigger et stt , mais rien ne change par contre la il est ecrit Cannot connect to server socket err = No such file or directory
Cannot connect to server request channel
jack server is not running or cannot be started
ca c'est nouveau

**Comment by madmax59860** [comment]
sur mon raspberry via l'interface grafique je tape 17.0.0.1 j'obtients la page serveur apache2 , sur mon pc lorque je tape l'IP 192.168.1.20 je suis rediriger sur un server "phpinfo0" (PHP Version 5.6.29-0+deb8u1)  et si je tape 192.168.1.20:8080 j'obtient la page " sarah ", je sais pas si cela peu aidder a resoudre mon probléme

**Comment by wikijm** [comment]
127.0.0.1                  =>       apache2 en local
192.168.1.20            =>       Sans doute apache2 qui t'affiche un fichier phpinfo.php (à supprimer car contient des données intéressantes en cas d'attaque)
192.168.1.20:8080   =>       Jarvis-API, c'est normal

Tout cela n'a aucun rapport avec tes problèmes je pense.
As-tu regardé dans les isssues en cours et clôturés ? Il me semble que tu n'as pas été le seul à rencontrer ces problèmes.

**Comment by madmax59860** [comment]
oui j'ai regarder mais aucune des solutions ne fonctionne ,

**Comment by madmax59860** [comment]
The programs included with the Debian GNU/Linux system are free software;
the exact distribution terms for each program are described in the
individual files in /usr/share/doc/*/copyright.

Debian GNU/Linux comes with ABSOLUTELY NO WARRANTY, to the extent
permitted by applicable law.
Last login: Mon Feb 20 09:40:06 2017 from t.home
-bash: rt : commande introuvable
-bash: /home/pi/.bashrc: ligne 5: erreur de syntaxe près du symbole inattendu «  ( »
-bash: /home/pi/.bashrc: ligne 5: `export PATH# ~/.bashrc: executed by bash(1) f or non-login shells.'
pi@raspberrypi:~$

j'ai egalement des erreurs mais je ne sais pas comment les corriger , merci de votre aide

**Comment by alexylem** [comment]
@madmax59860 tu as bcp d'erreurs non liées à Jarvis. Là par exemple elles se trouve dans ton .bashrc.

**Comment by madmax59860** [comment]
ok ,

**Comment by wikijm** [comment]
@madmax59860 Je clôture le ticket vu que les problèmes n'ont pas rapport avec Jarvis.
Si jamais tu as de nouveau des problèmes, n'hésites pas à ré-ouvrir ce ticket s'ils sont dans sa continuité, ou en ouvrir un nouveau si le problème est nouveau et qu'il n'a pas été traité par d'autres utilisateurs.
