### ISSUE TITLE
Add Sonia voice for voxygen

### ISSUE THREAD

**Issue by wormch** [alexylem/jarvis#434]
Hello,
can you please add the Sonia voice to the options of voxygen?
It is for the italian language.

Thank you,
Sergio

**Comment by wikijm** [comment]
Please follow https://github.com/alexylem/jarvis/pull/435 and https://github.com/alexylem/jarvis-ui/pull/7

**Comment by alexylem** [comment]
Thanks @wikijm for the pull requests. Merged.

**Comment by wikijm** [comment]
@wormch A feedback will be appreciated ;-)

**Comment by wormch** [comment]
@wikijm thank you it works :)
