### ISSUE TITLE
Probleme "error occured while training the model" 

### ISSUE THREAD

**Issue by Robinson128** [alexylem/jarvis#436]
Bonsoir tout le monde.
Voila, j'aimerais installer Jarvis sur mon raspberry pi zero  et controlé les différentes lumieres qui sont branché dessus via un relais, mais voila, je rencontre pour cela plusieurs probleme lors de l'instalation.
Bon, dans un premier temps, l'anglais, et oui, je suis une quiche en anglais.
En deux, je ne comprends pas a quoi sert snowboy... et au cour de l'installation et de "l'initialisation" de la reconaissance vocal (enfin, je crois), j'ai ce message d'erreur aprés avoir répété 3 fois le nom que j'ai donné au systéme Jarvis (dans mon cas, "Maman" en référence a Alien).
Le message, le voici : "error occured while training the model"
Un nouveau tuto vidéo Fr serait je pense tellement plus simple. Je suis completement perdu. Help me. ;(

**Comment by wikijm** [comment]
Bonjour @Robinson128,

Premièrement, je ne pense pas que le Pi Zero soit suffisamment performant pour gérer Jarvis et ce qui gravite autour.
Ensuite, snowboy est un moteur de détection de "hotword", c'est à dire qu'il a pour rôle de détecter un mot-clé parmi tous les sons que ton micro entend en continu.

As-tu ajouté la clé API pour snowboy, ou même testé un autre hotword que "Maman" ?

Une mauvaise maitrise de l'anglais ne devrait pas trop poser de problème, car le créateur de Jarvis et la communauté actuelle est plutôt francophone. La preuve, la procédure suivante est en français : http://domotiquefacile.fr/jarvis/content/prerequisites

**Comment by Robinson128** [comment]
Une clé API pour snowboy?! On la trouve ou?! Sur le site de snowboy?! Je ne vois rien qui resemble a une clé ou quoi que ce soit d'autre. A moins que ce soit dans un menu caché...

**Comment by alexylem** [comment]
Bonjour @Robinson128. Il te faut bien suivre les indications à l'installation de Jarvis:
![image](https://cloud.githubusercontent.com/assets/11017174/23092767/54da3860-f5d2-11e6-9f0a-1b6df0ad9164.png)
Ton token sera visible dans ton profile Wit.ai.

**Comment by Robinson128** [comment]
Ho la vache. Je n'avais pas vue du tout. Un grand merci a vous deux. J'ai pu finir l'installation. Bon, maintenent je vais voir pour que "Maman" me donne l'heure et faire mes petite magouille dans mon coin. Encore merci a vous deux.
Cordiallement. :)

**Comment by wikijm** [comment]
@Robinson128 Je clôture ton ticket, mais pense à le faire la prochaine fois :simple_smile:

**Comment by Robinson128** [comment]
Ha yes. Pardon. Merci.

**Comment by alexylem** [comment]
I have modified to code to make this token (and other settings) mandatory. So that it's not possible to skip this step by mistake.

**Comment by Marcreed48** [comment]
I’m sorry for bothering, I set the hotword to ‘Jarvis’ and got my token from snowboy. I’m getting the same error message after my third utterance “Jarvis”. ‘Error occurred while training the model ‘. What should I do to proceed? I’ll keep trying in the meantime. Thanks.
