### ISSUE TITLE
How to install libraries with install.sh for multiple distributions

### ISSUE THREAD

**Issue by kevincaradant** [alexylem/jarvis#437]
Hi

I see in the install.sh that we add a command to be executed before to install a plugin but that can work only with one distribution, isn't it ?. 

I think at two possibilities:

1-  Analyze which OS Jarvis is installed and apply a yum install or a apt-get install with that. 
But we can be very quickly limited if the command are not the same between distributions and version of the OS... 

2 -  We have a kind of json object where we say:` [{'ubuntu': [{'14.04': 'apt-get install X'}, {'16.04': 'apt-get install X'}], 'fedora':[{.......}]] `

What do you think ? @alexylem

**Comment by alexylem** [comment]
You mean for plugins?
Yes it's up to you to check the platform to install corresponding dependancies or even block the install if not supported.
I provide several variables / functions to facilitate this, ex:
```shell
$platform
$jv_os_name
$jv_os_version
$jv_arch
$jv_install

# example of usage (extract from snowboy install)
if [ "$platform" = "linux" ]; then
    if [ "$jv_os_name" == "raspbian" ]; then
        if [ "$jv_os_version" == 8 ]; then
            sb_supported_os=true
            binaries="rpi-arm-raspbian-8.0-1.1.0"
        fi
    elif [ "$jv_os_name" == "ubuntu" ]; then
        if [ "$jv_arch" == "x86_64" ] && ([ "$jv_os_version" == "12.04" ] || [ "$jv_os_version" == "14.04" ]); then
            sb_supported_os=true
            binaries="ubuntu${jv_os_version/.}-x86_64-1.1.0" # 12.04 => 1204
        fi
    fi
    $sb_supported_os && jv_install python-pyaudio python3-pyaudio libatlas-base-dev
elif [ "$platform" = "osx" ]; then
    sb_supported_os=true
    binaries="osx-x86_64-1.1.0"
    jv_install portaudio
fi
if [ "$sb_supported_os" == false ]; then
    dialog_msg <<EOM
Pre-packaged Snowboy binaries only available for:
- Rasbpian 8 Jessie on Raspberry Pi
- Ubuntu 12.04 and 14.04 on x86 64bits
- Mac OS X
Please use correct distribution or compile your own version of Snowboy:
https://github.com/kitt-ai/snowboy
EOM
    exit 1
fi
```
Indeed we could implement a kind of json to list dependencies to install, why not.

**Comment by kevincaradant** [comment]
Yes, I'm talking about plugins.
Ok thanks. For the moment, I will take your example to do that I want.
I can write that in install.sh without any problem ?

**Comment by alexylem** [comment]
Normally yes, but this example if for snowboy, so you have to adapt it to your needs / supported platforms. It's more to give you an idea of how to use the built in variables / functions.

**Comment by kevincaradant** [comment]
@alexylem , I come again to talk about of this variable $jv_install

What is it exactly, Is it like a apt-get ou brew ou yum install en fonction de l'OS ? 

Thank you

**Comment by kevincaradant** [comment]
To try, I write this script but I didn't have jq installed after to install the Kodi plugin ...
How can I see my mistake ? I don't have any log about this execution ? 

```
#!/bin/bash
# Use only if you need to perform changes on the user system such as installing software
if [ "$platform" = "linux" ]; then
    if [ "$jv_os_name" == "raspbian" ]; then
        sudo apt-get install -y jq
    elif [ "$jv_os_name" == "ubuntu" ]; then
        sudo apt-get install -y jq
    elif [ "$jv_os_name" == "fedora" ]; then
        sudo dnf install -y jq
    elif [ "$jv_os_name" == "openSUSE" ]; then
        sudo dnf install -y jq
    fi
elif [ "$platform" = "osx" ]; then
    brew install -y jq
elif [ "$platform" = "windows" ]; then
        dialog_msg <<EOM
Windows is not manage by default.
Please look: https://stedolan.github.io/jq/download/
EOM
fi

if [ "$sb_supported_os" == false ]; then
git clone https://github.com/stedolan/jq.git
cd jq
autoreconf -i
./configure --disable-maintainer-mode
make
sudo make install
    dialog_msg <<EOM
Auto-compilation of JQ library done.
If something wrong, please have a look on Google about the installtion of JQ for your OS.
You can start to look this link: https://stedolan.github.io/jq/download/
EOM
    exit 1
fi
```

**Comment by alexylem** [comment]
`$sb_supported_os` is a local variable used in the install script of snowboy (that's why it's not documented ^^). (sb is for SnowBoy). I used is to say whether the OS is supported or not (based on various if conditions) so that I display an error message at the end (and avoid dupplicating the error message itself).

`jv_install` is exactly what you think, see extract of:
**dialog_linux.sh**
```shell
# Public: install packages, used for dependencies
#
# args: list of packages to install
jv_install () {
    sudo apt-get update -y #421
    sudo apt-get install -y $@
}
```

**dialog_osx.sh**
```shell
# Public: install packages, used for dependencies
#
# args: list of packages to install
jv_install () {
    if ! hash brew 2>/dev/null; then
        if jv_yesno "You need Homebrew package manager, install it?"; then
            ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)" < /dev/null 2> /dev/null
        fi
    fi
    brew install $@
}
```

**Comment by alexylem** [comment]
You are right it's missing in the documentation. I will add this (and other useful functions I did that are missing too).

**Comment by kevincaradant** [comment]
Can you tell me if you think something can be wrong with this code.
Actually, it's useless because it's seems Jarvis needs itself this library ( JQ ) 

My code:

```
#!/bin/bash
# Use only if you need to perform changes on the user system such as installing software
if [ "$platform" = "linux" ]; then
    if [ "$jv_os_name" == "raspbian" ]; then
        sudo apt-get install -y jq
    elif [ "$jv_os_name" == "ubuntu" ]; then
        sudo apt-get install -y jq
    elif [ "$jv_os_name" == "fedora" ]; then
        sudo dnf install -y jq
    elif [ "$jv_os_name" == "openSUSE" ]; then
        sudo dnf install -y jq
    fi
elif [ "$platform" = "osx" ]; then
    brew install -y jq
elif [ "$platform" = "windows" ]; then
        dialog_msg <<EOM
Windows is not manage by default.
Please look: https://stedolan.github.io/jq/download/
EOM
fi

if [ "$sb_supported_os" == false ]; then
git clone https://github.com/stedolan/jq.git
cd jq
autoreconf -i
./configure --disable-maintainer-mode
make
sudo make install
    dialog_msg <<EOM
Auto-compilation of JQ library done.
If something wrong, please have a look on Google about the installtion of JQ for your OS.
You can start to look this link: https://stedolan.github.io/jq/download/
EOM
    exit 1
fi
```

But I don't know when this code is executed. I don't see it at any time :/

**Comment by alexylem** [comment]
Please do not use variable name "sb_supported_os" because it is already used by snowboy. You maybe have weird results. If you want to use your own variables, prefix them with your plugin shortcode like advised in the plugin tutorial.

Yes jq is a pre-requisite of Jarvis, no need to install it.

It depends where you placed the code, if it's to install dependencies for your plugin, place it into your plugin's `install.sh` file and it will be executed once during the installation of your plugin.
