### ISSUE TITLE
"null" pour quasi toutes les commandes de plugins

### ISSUE THREAD

**Issue by Patruche** [alexylem/jarvis#438]
Bonjour à tous ! 

Je me suis lancé dans la merveilleuse aventure de Jarvis, je le test actuellement sur OSX avant d'investir un petit Rasp.. Cependant je suis dégoûté car pas mal de plugins me retournent que "null" 

Exemple pour le plugin jarvis-time, je lui demande "quelle heure" comme indiqué dans la commande et il me répond "null", pareil pour la date. Jarvis-Turing, impossible à faire fonctionner aussi. 

Et pour terminer avec les blagues, il commence à me poser une question genre : quel est le comble d'un cyclope ? 

Il attend puis me retourne une erreur... 

J'ai essayé pas mal de trucs mais je sèche... 

Merci beaucoup d'avance et merci pour le travail que vous apportez à ce petit monstre de Jarvis qui mérite que l'on s'y intéresse :-)

**Comment by alexylem** [comment]
C'est pas normal. Je développe Jarvis et Jarvis-Time sur Mac 😄 .

Merci de coller le résultat complet de la console après avoir lancé Jarvis en mode Troubleshooting, ou partage une session de ton terminal en utilisant http://asciinema.org.

**Comment by Patruche** [comment]
J'imagine... ^^

Voilà le résultat en keyboard mode si ça peut aider ? Sinon je le refais en troubleshot

https://asciinema.org/a/21snxjjt59m66nb54qpg5cqqc

**Comment by alexylem** [comment]
essayes:
```shell
$> ./jarvis.sh -kv
```

**Comment by Patruche** [comment]
https://asciinema.org/a/7ibi9tkn20tkgrd6gq6nu17sk

Voilà voilà :)

**Comment by alexylem** [comment]
```
$> say "$(curl -s "http://www.cleverbot.com/getreply?key=$jv_pg_ai_key&input=$or
der" | jq -r '.output')"   
```
C'est le plugin cleverbot qui intercepte toutes tes commandes.
Commence par le mettre en bas de la liste des priorités de plugins dans Plugins > Matching Order.
Puis contacte l'auteur pour remonter ton problème ou désinstalle-le.

**Comment by Patruche** [comment]
Effectivement c'est ça Alex ! 

Du coup comment ça se fait que j'arrive pas à faire fonctionner les plugins IA genre Cleverbot (Jarvis IA je crois) et Blagues ? 

En tous cas déjà pour ça merci beaucoup, j'aurais jamais soupçonné un problème d'ordres o_O

**Comment by alexylem** [comment]
Certains plugins comme ceux-la interceptent tous les ordres. Il suffit qu'ils fonctionnent mal / soient mal paramétrés et donc aucune de tes commandes ne fonctionnera.
C'est pour ca que l'ordre des plugins est crutial 😄 
Et surtout commencer simple avec aucun plugin, tester, puis les rajouter et tester 1 par 1.

**Comment by Patruche** [comment]
Okkkkkkkkkkk d'accord, le sketch xD 

Je vais essayer ça, merci beaucoup Alex et encore bravo pour ton travail

**Comment by alexylem** [comment]
Merci!
