### ISSUE TITLE
Probleme chargement Release

### ISSUE THREAD

**Issue by olivier-nolhan** [alexylem/jarvis#439]
### Description

Bonjour, j'ai un gros soucis sur le chargement des Release de Jarvis.

Je m'explique je commence a rentrer les 1er paramètre dans la console, tout va bien mais des que je choisi Snowboy ou n'importe quel autre ça ne charge pas.

Pour Info j'ai charger 587 Release en plus de 48H.

Mon RPi 3 livré avec Noobs préinstallé est tout neuf ( je l'ai reçu ya environ 5 jours.

A part Jarvis j'ai rien fait avec encore

j'ai relancer un test  le temps d'ecrire c'est quelque ligne et je n'ai charger que 4 Release.

Quelqu'un peux me dire se qu'il se passe SVP, je commence a désespéré.

Un grand merci a tous

**Comment by wikijm** [comment]
Bonjour @olivier-nolhan,

Merci de respecter ce qui est demandé dans le modèle de création de ticket,  à savoir filmer ce qui se passe dans ta console avec ASCIINEMA (voire ScreenToGIF). 

Ainsi,  on verra précisément ce qui se passe sur ton écran :-)

**Comment by alexylem** [comment]
@olivier-nolhan, fais ceci:
```shell
# installe asciinema
$> sudo apt-get install asciinema
# démarre l'enregistrement
$> asciinema rec
# reproduis ton problème:
$> ./jarvis.sh -i
# et quand tu as finis, arrête l'enregistrement
$> exit
# puis sélectionne Y pour uploader et copie le lien ici
```

**Comment by olivier-nolhan** [comment]
Merci @alexylem  pour l'explication je début avec Raspberry. 

comme demandé voici le lien:

http://asciinema.org/a/2wx55zwg6i0icmybn7ykknukz

4min38 pour la 7eme release alors imaginer au bout de 2 jour j'en été qu'a 700 ^^

**Comment by alexylem** [comment]
Ok donc ton problème arrive à l'installation de snowboy, au moment de la mise à jour des paquets.
On va essayer de le faire manuellement.
Peux-tu faire ceci avec asciinema:
```shell
$> sudo apt-get update -y
```
J'ai le sentiment que tu as un soucis de débit internet au vue de ce que tu as partagé...

**Comment by olivier-nolhan** [comment]
Je viens de lancer la cmd et  j'ai fait le test de débit j'ai actuellement 15 Mb en réception .

Ci-joint l'enregistrement de 12Min pour 12 Release

http://asciinema.org/a/d8e0amw73qp6hjtp4u67mhxe8

**Comment by alexylem** [comment]
Bon et bien rien à voir avec Jarvis.
J'ai regardé ton asciinema, et ca rame en fetchant les infos de deb.gateweb.fr.
Comme ca ne me semblait pas être une source originale, j'ai fait vite fait une recherche sur google et on dirait que c'est une source utilisée pour... "Sarah" (concurrent de Jarvis...):
http://www.planete-domotique.com/blog/2016/11/02/installation-serveur-de-commande-vocale-sarah/
Donc je te laisse faire le ménage dans tes sources, puis tu pourras relancer l'installation de Jarvis en toute tranquillité 😄

**Comment by olivier-nolhan** [comment]
S.a.r.a.h oui j'ai vu de video mais  mon choix c'est vite porter sur JARVIS par contre je n'ai jamais installer S.A.R.A.H sur mon RPI. Je vais regarder ca aussi de mon coté et je reviens vers toi.

En tout cas merci de t'es reponse

**Comment by alexylem** [comment]
Il faudrait que tu vires deb.gateweb.fr de ton /etc/apt/sources*
Puis refaire:
```shell
$> sudo apt-get clean
$> sudo apt-get update
```

**Comment by olivier-nolhan** [comment]
Bonjour @alexylem j'ai lancer une restaure du l'os via la touche shift se matin. Je rentre à la maison dans environ 2h donc je recommencerai à zéro ton tuto. Et je reviens vers toi dès que j'y suis. En tout cas merci pour tes réponses.

**Comment by olivier-nolhan** [comment]
Bonjour @alexylem 

Après avoir fait un reboot de l'os j'ai pu installer Jarvis avec quelques déboire mais j'y suis arrivé ^^

Il me reste néanmoins un soucis.

http://asciinema.org/a/bckr0uqkscmlxye8cjncvop8x

Il ne reconnait que la cmd "jarvis" et aucune autre sinon il me dit "null"

Y-a-t'il quelque chose que j'ai mal fait ?

**Comment by alexylem** [comment]
Voir #438
