### ISSUE TITLE
enregistrer une phrase dans une seul variable

### ISSUE THREAD

**Issue by remjou1** [alexylem/jarvis#44]
voila mon idée est toute simple : enregistrer une phrase complète dans un variable...
Bien sûr il y a la solution : 
```
*ENVOIE A (*) QUE (*) ET (*)==...
```
mais ce n'est pas ce que je veux car je voudrais dire une phrase sans avoir une structure pariculière...
Je me demandais si il était possible de faire
MOI:"envoie un mail"
(une fenêtre d'enregistrement s'ouvre et je peu dire mon texte jusqu'a ce que je ne dise plus rien un peu a la manière de la vérification de micro...)

**Comment by alexylem** [comment]
Cela me fait penser à #42 
```
ENVOIE UN MAIL==say "Je t'écoute"
    (*)==echo "(1)" > mon_fichier.txt
```
Ou alors passer en paramètre d'un autre script
```
ENVOIE UN MAIL==say "Je t'écoute"
    (*)==mon_script.sh "(1)"
```
Ou alors mettre dans une variable comme tu dis mais je vois pas trop ce que tu vas en faire
```
ENVOIE UN MAIL==say "Je t'écoute"
    (*)==ma_variable="(1)"
```
Si cela répondrait à ton besoin, je ferme cette issue et on se concentre sur #42

**Comment by remjou1** [comment]
bah en fait ça ne m'enregistreras que 1 seul mot non ?

**Comment by alexylem** [comment]
Non les exemples ci-dessous enregistrerons tout ce que tu diras après qu'il te dise "Je t'écoute". D'ailleurs la fonctionnalité #42 est presque prête, j'ai fait d'autres gros changement je fini de tester avant de mettre à dispo la mise à jour.

**Comment by remjou1** [comment]
ok... pour l'implémantation j'ai vu ça.... euh je test et je te dis ensuite si tu peu fermer l'issue...

**Comment by alexylem** [comment]
ok

**Comment by remjou1** [comment]
c'est bon tu peu fermer ;) merci c'est vrai que je n'y avais pas penser.... en même temps je pensais que ça n'enregistrait qu'un seul mot et j'ai toujours tendance a me compliquer la vie... mon fils me le dit souvent...

**Comment by alexylem** [comment]
😄
