### ISSUE TITLE
Jarvis // Moonlight Steam Streamer

### ISSUE THREAD

**Issue by crychaor** [alexylem/jarvis#441]
Bonjour, 

Un grand merci à toi Alex pour le super taff que tu as réalisé, c'est juste génial, facile à comprendre et facile à paramétrer, malgré que je sois un novice dans le domaine de la programmation de linux et c'est grâce à toi que je me suis lancé dans le projet Raspberry. 

Ce week end et plus précisément samedi matin entre 1heure et 4 heure ( crise d'insomnie oblige) j'ai réussis a faire exécuter par commande vocal Moonlight ( Steam Streamer ). Il s'agit simplement de lancer l'interface et c'est déjà pas mal. pour le reste une manette filaire ou sans fil fonctionne tout aussi bien  

Si ca intéresse des personnes pour que je fasse un petit tuto. 

Moonlight étant déjà un projet existant sous raspberry.

**Comment by wikijm** [comment]
Bonjour @crychaor,

Merci pour la proposition 😄 
Tu aurais une URL, une photo ou une capture d'écran à partager ?

**Comment by crychaor** [comment]
pour l'URL du programme moonlight: http://moonlight-stream.com/

Fonctionne parfaitement avec Jarvis. Je compte bien faire des photos voir des vidéos ( déjà pour faire baver un ami ^^ )

**Comment by wikijm** [comment]
N'hésites pas à créer un plugin pour Jarvis en suivant ce lien :
http://domotiquefacile.fr/jarvis/content/publish-your-plugin

**Comment by crychaor** [comment]
bah pour créer le plugin je suis tellement une quiche en programmation, je pense que je vais avoir besoin d'un coup de main, d'une boite d'aspirine, de 20 bouteille de bière et d'un long week end !!

**Comment by crychaor** [comment]
alors voila une petite video que ma femme a fait !!!! bon c'est mon lien sur mon facebook mais je t'avoue que j'ai pas de chaine youtube pas d'endroit ou l'upploader donc voila 

https://www.facebook.com/thegent.crows?hc_ref=NEWSFEED

je me suis basé sur le tuto de controle de jarvis via Tasker d'ailleur un grand merci a celui qui a fait le tuto . 

ensuite installation et utilisation de moonlight. 

j'espère que vous arriverez à voir la video.

**Comment by crychaor** [comment]
le pc a coté de moi c'estm on pc portable sur lequel je travaille sur mon raspberry au cas ou se demande pourquoi le pc est coté ... vive putty pour les feignasses comme moi

**Comment by alexylem** [comment]
J'ai ajouté une page projet avec ta vidéo:
http://domotiquefacile.fr/jarvis/content/jarvis-et-moonlight
Si tu es enregistré sur le site domotiquefacile.fr je peux te mettre auteur comme ca tu pourras y rajouter ton tuto.
Encore bravo pour ton travail, j'ai aimé et commenté ta video :)

**Comment by crychaor** [comment]
bah j'ai pas fait grand chose  c'est surtout grace a toi et au créateur de moonlight

**Comment by crychaor** [comment]
apres j'ai compilé et je t'avoue m'étre inspirer de la personne qui avait fait magic mirror sur son jarvis donc ca aussi je vais le rajouter mais je veux d'abord avancer sur toute les programmation

**Comment by crychaor** [comment]
voila je suis inscit et heureux de pouvoir apporter ma pierre à l'édifice

**Comment by wikijm** [comment]
Plugin crée et fonctionnel, présentation du projet faite sur le site, tout est fait.
Je clôture le ticket. Merci @crychaor pour ton investissement et le travail accompli 👍
