### ISSUE TITLE
jv_repeat_last_command doesn't work if we are "encapsulated" in a command

### ISSUE THREAD

**Issue by kevincaradant** [alexylem/jarvis#442]
Hi @alexylem 

I don't know how to call the situation but if we apply the folowing code, the `AGAIN`  command doesn't work properly. 

Case:
```
*CODY CONTROL*==say "begin of the kodi control"
>*CONFIRM*==callUrlKodi '{"jsonrpc":"2.0","method":"Input.Select","id":1}'; return
>*START*MOVIE(*)==playMovieSearched (1); return
>AGAIN*==jv_repeat_last_command; return
>FINISH*WITH*CODI==say "end of the kodi control"
*LEAVE CODI*==callUrlKodi '{"jsonrpc":"2.0","method":"Application.Quit","params":{"playerid":'$(getActivePlayerId)'},"id":1}'

```

I want repeat one of the commands inside the `CODY CONTROL` but it repeats `CODY CONTROL` everytime because it believes that it was the last command, even if I said `CONFIRM` or `START MOVIE` after the `CODY CONTROL`.

Any idea why ? 

Thank you

**Comment by alexylem** [comment]
Hello, it is because of the return. Evaluating the action exits the function and then skips the next line which is to remember the last command.
![image](https://cloud.githubusercontent.com/assets/11017174/23134570/99b5d93e-f795-11e6-8ba2-49409207550d.png)
I'll work to fix this.

**Comment by alexylem** [comment]
I fixed it, but I wait some other feedback on #440 to commit everything.

**Comment by alexylem** [comment]
Voila c'est corrigé. Mettez à jour:
```shell
$> ./jarvis.sh -u
```

**Comment by kevincaradant** [comment]
ok super merci. Je teste dessuite
