### ISSUE TITLE
jarvis se met en pause quand il execute un plugin en python

### ISSUE THREAD

**Issue by themask38** [alexylem/jarvis#444]
Bonjour, je souhaiterai créé une interface graphique en python j'execute mon fichier avec la commande :
python ./plugins/jarvis-interface/fr/jarvis.py
quand je lui dit :
demarre l'interface, ca fonctione mais jarvis se met en pause et il n'écoute plus. j'aimerai que l'interface et python fonctione en meme temps, comment faire ?
PS: dès que je ferme ma fenetre python, jarvis refonctione

**Comment by alexylem** [comment]
Il faut le lancer en processus parallèle avec `&`.
Regarde ce que j'ai fais avec le [plugin "Jarvis-UI"](http://domotiquefacile.fr/jarvis/plugins/jarvis-ui) il apporte exactement ce que tu veux faire. De plus je l'ai aussi codé en Python et il répond à la commande "Ouvre l'interface" 😄

**Comment by alexylem** [comment]
La ligne en question:
https://github.com/alexylem/jarvis-ui/blob/master/fr/functions.sh#L19

**Comment by themask38** [comment]
merci
