### ISSUE TITLE
Questions avec le plugin  Milight

### ISSUE THREAD

**Issue by FougereBle** [alexylem/jarvis#445]
Bonsoir à tous ! :)

Je compte prendre plusieurs ampoules Milight (deux dans le salon et trois dans la cuisine), et utiliser ce plugin :
http://domotiquefacile.fr/jarvis/plugins/gestion-des-ampoules-mi-light#comment-183

Par contre, dans le fichier de configuration (config.sh) il n'y à que deux ligne (l'IP et le Port), donc qu'une seule ampoule.

Comment faire lorsque j'ai plusieurs ampoules ?
Comment faire pour allumer/éteindre plusieurs ampoule avec une seule commande ?

Merci beaucoup ! :)

**Comment by wikijm** [comment]
@Benfosse Pourrais-tu activer la fonctionnalité "Issue" sur ton (repository)[https://github.com/Benfosse/jarvis-milight] ?
Cela permettrait à @FougereBle de communiquer avec toi, créer un ticket chez toi et ainsi fermer celui-ci ;-)

**Comment by trarizakaria** [comment]
Pour éteindre et allumer plusieurs ampoule c'est le controller qui se charge de ça. Le plugin ne fait que communiquer avec le controller. Et c'est le controller qui communique avec les lampe. J'ai juste reçu aujourd'hui mon controller milight. 
J'ai commandé une lampe une télécommande et un controller pour tester avant d'investir dans bcp de lampes. Et j'en suis satisfait. 
Donc en bref l'ip et le port c'est pour le controller et non pas pour les ampoules. 
Les ampoule ne peuvent pas avoir une ip. Ils fonctionne en radio-frequency. 
Voila tu peux cloturer ce ticket

**Comment by FougereBle** [comment]
Je reouvre l'issue.

N'ayant pas de réponse de la part de l'auteur du plugin, je me retrouve obligé de poster ici en esperant que quelqu'un puisse me répondre.

J'ai reçu mes ampoules et j'ai installé le plugin.
J'ai mit l'IP "192.168.1.7" et le port "8899" dans la configuration.

Cependant, quand je demande à Jarvis d’allumer la lumière, j'ai l'erreur :

nc: invalid option -- q
usage; nc [-.........] [-K tc] (-b boundif] [-i interval] [-p source_port] [--apple-delegate-pid pid] [--apple-delegate-uuid uuid] [-s source_ip_address] [-w timeout] [-X proxy_version] [-x procy_address[:port]] [hostname] [port[s]]

Comment faire ?

Merci ! 👍

**Comment by trarizakaria** [comment]
Quelle est la version de ton controlleur milght ? Tape l'ip dans un navigateur login admin mdp admin. Moi aussi ça  fonctionne pas chez moi.car la dernière version des controlleurs n'est pas encore pris en charge.

**Comment by trarizakaria** [comment]
Une autre question. As tu réussi à  commander les ampoules via l'application android dédiée ??

**Comment by FougereBle** [comment]
Je n'ai toujours pas réussi à contrôler mes ampoules grâce à ce plugin.

Par contre, je peux très bien les contrôler avec mon iPhone et ma télécommande MiLight.

Du coup, j'ai installé Jeedom sur mon RPi, j'ai acheté le plugin Wifilight V2 pour 4€ et tout fonctionne très bien ! Jeedom et ce plugin, c'est un pur bonheur !

Alors c'est vrai, ça coûte 4€... mais je ne regrette pas mon achat !

**Comment by trarizakaria** [comment]
Idem pour moi aussi. J'utilise jeedom avec le plugin. Et ça  marche nickel. J'ai la ibox v6 celui sous forme de veilleuse. Je crois que la version et la plus récente et il faut voir avec l'auteur du plugin. En attendant tu peut utiliser le plugin jarvis-jeedom et configurer les interactions pour allumer les lampes depuis jarvis via jeedom. Je vais essayer ça  ce soir et je te tiens au courant.

**Comment by FougereBle** [comment]
C'est ce que j'ai fait. J'ai installé jarvis-jeedom, j'ai créer des interactions Jeedom et tout fonctionne avec la reconnaissance vocale.

Pour le moment, j'ai configurer les commandes suivantes :

Allume la lumière du bureau
Éteint la lumière du bureau
Met la lumière du bureau en vert
Met la lumière du bureau en blanc

C'était juste pour tester, et tout fonctionne. En plus, je peux même contrôler mes ampoules avec l'interface Jeedom sur mon PC.

Je compte ajouter d'autre commandes, comme par exemple :
Mettre la lumière d'une couleur aléatoire
Mettre la lumière de la couleur (rouge/bleue/jaune/violet/....)
Mettre en mode disco.
Mettre en mode normal.
Changer l'intensité.
.....

Ca va être long, mais une fois tout terminé, ça va être vraiment super !

Par contre, j'ai installé Jeedom sur mon RPi et Jarvis sur mon Mac car je n'ai pas encore de microphone (celui que j'ai commandé ne fonctionne pas, et je suis en litige avec le vendeur). Du coup, je me sert de mon Mac pour faire la commande vocale.

Mon Mac envois à mon RPi la commande vocale, puis la RPi envois au contrôleur Wifi l'action correspondante, et le contrôleur Wifi envois un signal à mes ampoules.

Quand j'aurais commandé un autre micro, je pourrais ne plus passer par mon Mac, et uniquement par la RPi, ce qui va être beaucoup plus pratique.

Si tu as besoin d'aide pour les actions, je pourrais t'aider.
Par exemple, voici une interaction que j'ai ajouté à Jeedom :

[] [allume|allumer] [la|les|] [lumières|lumière] [du|de|d'|] bureau

Ca permet de dire :
"Allume la lumière du bureau"
"Allumer lumière bureau"
"..."

En fait, ce qui est entre crochets permet de dire soit l'un, soit l'autre. Par exemple :
[allumer|allume] bureau

On pourrais donc dire :
Allumer bureau OU Allume bureau

L'astuce, si tu veut rendre ce mot optionnel, c'est de rajouter un | à la fin, juste avant le ].

Du coup, [allumer|allume|] fonctionne lorsque l'on dit :
Allumer bureau
Allume bureau
bureau

C'est assez galère au début, mais quand on à compris ça va tout seul. ;)

**Comment by trarizakaria** [comment]
Cool. Merci pour les explications. Je suis entrain de configurer mes premières interactions à  l'instant. Ça  serai une vrai galère. 

Tu peux  utiliser ton smartphone pour donner des commandes vocale à  jarvis et ce, via Tasker. C'est super pratique et la reconnaissance vocale et meilleure. 
Je suis déçu avec la reconnaissance vocale de bing. J'ai un micro qui fonctionne bien mais la reconnaissance est mauvaise.

**Comment by FougereBle** [comment]
Ah, je n'ai jamais eu de problème avec Bing.

Je vais voir pour Tasker, mais à vrai dire la reconnaissance vocale avec le smartphone, je trouve ça moyen.

Devoir aller chercher son smartphone posé sur la table, ouvrir l'app, et parler, c'est plus vite fait de prendre la télécommande et allumer la lumière. :p

**Comment by trarizakaria** [comment]
oui c'est vrai, mais c'est pratique comme meme,  par exemple quand tu regarde la tele et il y a du bruit.

Moi j'ai deux jarvis sur rpi. j'ai laisser celui du salon en mode keyboard que je commandes via smartphone que j'ai tjr en main :) , et l'autre est placé dans la cuisine avec un micro,  c'est pratique pour ma femme quand elle a les main ocupées dans la cuisine :).

**Comment by FougereBle** [comment]
Quel microphone à tu utilisé pour ta domotique ?

Je cherche un microphone longue portée compatible Raspberry Pi, mais je n'en trouve pas.

Merci !

**Comment by trarizakaria** [comment]
Je ne voulais pas investir dans un micro coûteux, histoire de tester jarvis d'abord. alors j'ai acheté un micro low cost "Andoer" le 2ème  dans cette liste 
http://domotiquefacile.fr/jarvis/content/prerequisites
 Pour seulement 5€ de Aliexpress. 
Il est vraiment pas mal vu son coût. Il détecte le magic word 'snowboy' à  4m de loin  mais pour les commandes via bing il faut parler plus proche.

**Comment by FougereBle** [comment]
Je me suis acheté [ce micro](https://www.amazon.fr/gp/product/B01D4I2UM0/), en espérant que ça va aller.

Sinon, je m'amuse un peu avec ma domotique, et j'ai configuté Jeedom avec deux comptes :

- Un compte Administrateur où l'on peut s'y connecter depuis l’extérieur. Il faut donc un identifiant et un mot de passe AINSI qu'un code d'accès, que l'on peut avoir uniquement si on possède mon téléphone (donc ce code d'accès change toutes les 5 sec, ce qui veut dire que même moi je ne le connais pas. Je dois ouvrir l'app sur mon iPhone pour le connaître).

- Un autre compte Administrateur qui ne requière pas de code d'accès. Cependant, on peut s'y connecter uniquement si la machine avec laquelle on s'y connecte est connecté au réseau locale de la maison.

J'ai aussi créé deux Scénarios :

- Un premier qui éteint les lumières si il fait jour (les lumières la journée, ça sert à rien. Autant les éteindre). Seul problème : Si un jour je souhaite allumer les lumières en pleinne journée, et bien elles s'éteindrons automatiquement dans une minute. Il faut donc que je fasse en sorte qu'une fois le jour levé, elle s'éteignent, mais que si je les rallumes, et restent allumées. Ca, je sais exactement comment faire, je le ferais donc demain.

- Un deuxième qui allume automatiquement les lumières dès qu'il fait nuit. Là par contre, si j'éteins les lumières la nuit, elles ne se rallumes pas.

Maintenant, j'ai plus trop d'idée... je vais donc chercher sur le net ce qu'il est possible de faire. :p

**Comment by wikijm** [comment]
> @FougereBle :
> Je reouvre l'issue.
> 
> N'ayant pas de réponse de la part de l'auteur du plugin, je me retrouve obligé de poster ici en esperant que quelqu'un puisse me répondre.

@alexylem Aurais-tu moyen de demander (par mail ?) à @Benfosse pour lui demander d'activer la fonctionnalité "Issue" sur son repo ?

**Comment by wikijm** [comment]
@Benfosse As-tu vu ma demande du 26/03/2017, afin d'activer la fonctionnalité "Issue" sur ton repository ?
@alexylem Même question, as-tu moyen de joindre @Benfosse par un autre biais ?

**Comment by wikijm** [comment]
@FougereBle Ton besoin est-il toujours d'actualité ?

**Comment by wikijm** [comment]
Pas de réponse depuis le 6 juin, soit plus d'un mois.
Le besoin ne semble plus d'actualité, je clôture l'issue.

**Comment by trarizakaria** [comment]
bonjour. @jbsystem76. 
pour pouvoir contrôler les milight en vocal y a un pluguin jarvis-milight si tu veux passer les commandes via jarvis. 
sinon tu peux les commander en vocal via les interactions  en utilisant un plugins milight de jeedom qui coute 4€ sur leur market.
MAIS dans les 2 cas tu aura besoin d'acheter le controler milight (qui reçoit en http et envoie au ampoules en 2.4g) ce dernier coûte environs 17€ sur aliexpress.
SINON ( si tu veux te casser la tete un peu) tu peu construire ton propre controler en utilisant un tranceiver 2.4mhz avec un arduino mega. ça s'appelle le RFLINK c'est pratique si tu utilises d'autres modules domotique en 433mhz ça sera plus économique pour toi.mais si c juste pour les milight alors acheter un controller c mieu.

**Comment by jbsystem76** [comment]
Super ça fait plaisir une réponse rapide 😉 je possède déjà le petit module
qui permet de contrôler les lumières.

Si je comprends bien je dois acheter un raspberry pour y installer jeedom
ensuite y a installé le script et le tour est joué?

**Comment by trarizakaria** [comment]
oui c'est ça mais si tu compte utiliser jeedom tu devrais acheter le pluguin wifilight v2 à 4€. quand à jarvis tout est gratuit  : )

**Comment by jbsystem76** [comment]
Jarvis on peut l'utiliser sur Android? Je comprends pas trop comment
l'installer en fait.

**Comment by trarizakaria** [comment]
non  !  openjarvis.com tout est là
