### ISSUE TITLE
Vidéo Démonstration Jarvis avec Smartwatch, Domoticz et Rfxcom

### ISSUE THREAD

**Issue by tchoul** [alexylem/jarvis#447]
Bonjour tout le monde!

Une petite démo des possibilités (non exhaustive) de Jarvis pour ceux que ça interessent, à la base pour montrer sur un groupe facebook donc pourquoi pas ici ;-) désolé pour la qualité...
[Jarvis démonstration ](https://www.youtube.com/watch?v=Gm0ml8fgTU0)

**Comment by wikijm** [comment]
Bonjour @tchoul,

Tout va bien avec le plugin Freebox ? Est ce qu'à l'usage tu as vu des choses à ajouter ?

**Comment by tchoul** [comment]
Salut @wikijm 

J'ai rajouté quelques trucs en combinant des comandes pour aller dans les téléchargement, vidéos, revenir à la télé, mettre en vostfr remettre en français, pause, revenir au direct, enregistré, zap tout seul lol, baisse ou monte un peu ou beaucoup le volume je crois que c'est tout ;-)

**Comment by wikijm** [comment]
Est-ce que tu peux partager tes commandes ?
Comme cela, je pourrais les rajouter à [ce fichier](https://github.com/wikijm/jarvis-freeboxplayer/blob/master/fr/commands), histoire que la communauté (et moi aussi ^^) puissions en profiter :-)

**Comment by wikijm** [comment]
Ah super @tchoul, merci beaucoup 😃 
J'essaye d'intégrer ça dans la semaine.

**Comment by Jean-Bernard-Hallez** [comment]
bonjour @tchoul, tu as fais comme moi des bruitages divers... je partage donc mon plugin qui peut t’intéresser...
[(https://github.com/Jean-Bernard-Hallez/jarvis-bruitages)]

**Comment by Jean-Bernard-Hallez** [comment]
@tchoul, je m'interesse aussi à la machine à café... l'as tu déja fait ? j'ai vu ce projet:
http://ispresso.net/ispresso-modification-mounting-components/
J'aurai aimé l'adapter à une philips senseo juste version simple les deux boutons...

Qu'as ou que vas tu faire ??? Merci....

**Comment by alexylem** [comment]
@tchoul géniale ta vidéo, merci bcp pour la belle promotion de Jarvis!
Quel est le groupe facebook en question?
Pourrais-je poster ta vidéo sur le site domotiquefacile?

**Comment by tchoul** [comment]
@Jean-Bernard-Hallez je vais voir pour ton pluggin dès que j'ai un peu de temps, sinon j'avais vu celui là [Domotiser sa Senséo](http://www.domotique-info.fr/2014/09/domotiser-senseo/) mais je ne vais pas faire ça avec un fibaro (car 868mhz et trop cher) mais avec un [module 3 commutateurs DIO](https://www.leroymerlin.fr/v3/p/produits/module-dio-e186675) j'attends d'avoir un peu de sous comme pour le detecteur de mouvement et ipcam ;-)

@alexylem 
Salut Alex!
Avant tout merci surtout à toi sans quoi rien aurrai était possible ;-)
Le groupe, c'est Raspberry FR (de florent poux qui et aussi ici) entre autre sur lesquelles je suis.
Et tu peux évidemment utilisé tout ce que tu veux sans demander pas de problème! Le partage y a que ça de vrai ;-)

**Comment by wikijm** [comment]
La vidéo a été intégrée à la page http://domotiquefacile.fr/jarvis/projects
