### ISSUE TITLE
Forcer le hotword avant les commandes rapides ?

### ISSUE THREAD

**Issue by jcabillot** [alexylem/jarvis#448]
Bonjour,

Je suis en train de tester ce projet bien sympathique.
Je ne désire faire que de l'analyse locale pour des raisons de vie privée et j'utilise donc snowboy.
Je suis passé par leur site pour récupérer un échantillon de "snowboy" et cela fonctionne ma foi plutôt bien.
J'ai rajouté une des commandes rapides pour tester VERSION / ANNULE et je me rends compte que cela ne fonctionne pas comme je l'imaginais.
Si je comprends bien : puisque je passe par snowboy et que j'ai placé mes fichiers version.pmdl/annule.pmdl dans stt_engines/snowboy/resources/,
alors tout mes commandes deviennent des commandes rapides qui ne nécessite pas le hotword, est-ce exact ?
En gros si je dis simplement "version" sans dire au préalable "snowboy", cela fonctionne.
Mais est-ce que je peut empêcher ce fonctionnement ?
En effet, forcer la détection du hotword permettrait de limiter les faux positifs ou les actions indésirées.
Est-ce possible actuellement ?

Merci

**Comment by alexylem** [comment]
>alors tout mes commandes deviennent des commandes rapides qui ne nécessite pas le hotword, est-ce exact ?

Exact. Voir:
http://domotiquefacile.fr/jarvis/content/snowboy#commandes-rapides

>Mais est-ce que je peut empêcher ce fonctionnement ?

Pas pour l'instant mais si c'est important pour toi je peux l'implémenter. C'est d'ailleurs une bonne idée, il faut juste que je trouve un moyen pour ne pas impacter ceux qui souhaitent vraiment avec des commandes rapides.

J'attends ton GO.

**Comment by jcabillot** [comment]
Ce serait avec plaisir : j'ai peur qu'avec une TV toute proche, mon jarvis ne soit trop bavare sans ça.

**Comment by alexylem** [comment]
Bon voici ce que je propose:
* Si le moteur de reconnaissance pour les commandes est `snowboy` alors il faudra dire le hotword d'abord pour que les commandes soient prises en compte.
* Si le moteur de reconnaissance pour les commandes est autre (`bing`, `wit`...) alors les hotwords trainés et disponibles seront des quick commandes, activables sans dire le hotword.

J'essaierai de rentre tout ca facilement compréhensible lors de l'installation. Je me rends compte qu'encore beaucoup de personne mettent snowboy en moteur de reco pour les commandes sans faire exprès (ex: #449 ). 

@jcabillot c'est ok pour toi?

**Comment by jcabillot** [comment]
> Si le moteur de reconnaissance pour les commandes est snowboy alors il faudra dire le hotword d'abord pour que les commandes soient prises en compte.
C'est bien là le comportement que j'aimerais, mais peut-être que ce n'est pas au gout de tout les utilisateurs.
Peut-être qu'une option pour activer ou non le hotword avant les commandes rapides serait préférable ? Cela complexifierait peut-être le processus de configuration pour l'utilisateur, mais permettrais de garder le comportement actuel pour vos utilisateurs qui le désirent.

**Comment by banditFlex** [comment]
Bonjour Alexy,

Tout d'abord super boulot avec ce jarvis. Je suis également en phase de test pour ma domotique maison, et pour l'instant je suis très content de l'évolution de la reconnaissance vocale depuis le raspberry Pi grace a toi.
Pour cette feature j'aimerai également qu'elle apparaisse, et ce exactement comme tu le prévois, si moteur de reconnaissance des commandes configuré a snowboy alors on bypass les commandes rapides sinon on garde le comportement actuel!

Merci et surtout continue ce super boulot.
Ben

**Comment by alexylem** [comment]
J'ai du changé pas mal de code pour implémenter ca. J'ai beau avoir testé (tests automatiques et manuels) il se peut qu'il y ait des régressions. Merci de mettre à jour et de me dire si tout est bon.

**Comment by banditFlex** [comment]
je test ca ce soir et je te fais un retour rapidement, merci beaucoup!

**Comment by jcabillot** [comment]
Je viens de tester, je confirme que cela fonctionne comme attendu :  
  * snowboy > version : me retourne sa version
  * version : ne retourne rien

Parfait et vraiment chapeau pour la réactivité ! :+1:
