### ISSUE TITLE
Jarvis n'écoute qu'un seul mot : Jarvis

### ISSUE THREAD

**Issue by FougereBle** [alexylem/jarvis#449]
Bonjour !

J'ai installé Jarvis sur mon Mac Mini (OS X Sierra), et l'installation c'est bien passée.

Lorsque je démarre Jarvis normalement, c'est écrit "Waiting to hear 'Jarvis'".
Lorsque je prononce "Jarvis", il me répond "Oui ?".

Par contre, à partir de ce moment là, j'ai beau dire ce que je veut, rien ne se passe, SAUF si je dit "Jarvis".
Mais quand je redit "Jarvis", il me répond "Je ne comprend pas: Jarvis".

Bref, si il n'y à que ce mot que je peut prononcer et qu'il me dit qu'il ne comprend pas, c'est pas très cool. :p

Une solution ?

**Comment by alexylem** [comment]
Merci de coller le résultat complet de la console après avoir lancé Jarvis en mode Troubleshooting, ou partage une session de ton terminal en utilisant http://asciinema.org.

**Comment by FougereBle** [comment]
J'ai fait une réinstallation (sans changer "Snowboy" en "Jarvis"), mais c'est pire. On dirais qu'il faut un accent américain pour que ça détecte quoi que ce soit (maintenant, j'arrive à peine à lui faire entendre "Snowboy").

Voici le contenu du Terminal :

----
Last login: Fri Feb 24 11:12:49 on ttys000
Mini-de-Romain:~ romainsimon$ cd ./jarvis
Mini-de-Romain:jarvis romainsimon$ ./jarvis.sh

------------ Config ------------
jv_version           17.02.24 
jv_arch              x86_64 
jv_os_name           Mac OS X 
jv_os_version        10.12.3 
language             fr_FR 
play_hw              false 
rec_hw               false 
speaker              Default 
microphone           Default 
trigger_stt          snowboy 
command_stt          snowboy 
tts_engine           osx_say 
--------------------------------

DEBUG: program_startup hook
snowboy: Hello
DEBUG: start_speaking hook
DEBUG: stop_speaking hook
User defined commands:
*AIDE*			*BONJOUR*|*SALUT*	*COMMENT*APPELLE*
*MERCI*			*AU REVOIR*|*BYE*	ANNULE*|TERMINE*
ENCORE*			*TEST*			*VERSION*
*REPETE (*) ET (*)	*CA VA*			>*OUI*
>*NON*
snowboy: Waiting to hear 'snowboy'
romain: (listening...)
DEBUG: models=alexa,snowboy
INFO:snowboy:Keyword 2 detected at time: 2017-02-24 11:18:24
DEBUG: modelid=1
snowboy
DEBUG: entering_cmd hook
snowboy: Yes?
DEBUG: start_speaking hook
DEBUG: stop_speaking hook
romain: (listening...)
DEBUG: models=alexa,snowboy
----

Merci !

**Comment by alexylem** [comment]
>Par contre c'est normal que les phrases par défaut soit en anglais quand il me répond ?

Il faut les changer dans Settings > Phrases

>On dirais qu'il faut un accent américain

Pour Snowboy, oui 😄 

>rien ne se passe, SAUF si je dit "Jarvis".

```shell
command_stt          snowboy 
```
Maintenant je comprends, car parce que tu as mis `snowboy` pour la reconnaissance des commandes. Essaye avec Bing comme recommandé lors de l'installation.

**Comment by FougereBle** [comment]
La première fois, j'avais mit "Jarvis" pour la reconnaissance des commandes. C'est après avoir recommencer l'installation que j'ai mit "Snowboy".

Bing, je suis pas trop pour. Déjà, il y à une limite de commandes, et puis c'est en ligne.
Après, je fait ça sur mon Mac pour tester la reconnaissance vocale (j'ai installé Jarvis sur ma RP mais je n'ai pas encore reçu mon micro USB, et je n'arrive pas à faire fonctionner mon Micro standard (donc pas une prise USB)).

Par contre, sur le RP, je pourrais utiliser Snowboy ? Ca va fonctionner ou ça va me faire la même chose que sur mon Mac ?

Merci !

**Comment by alexylem** [comment]
@FougereBle tu as lu la doc?
http://domotiquefacile.fr/jarvis/content/stt
Snowboy ne peut reconnaitre que les mots / expressions que tu as trainé avec ta voix.
Si tu veux du 100% hors ligne sur Raspberry pi tu n'as pas trop le choix, il te faudra trainer toutes les commandes que tu voudras dire à l'avance, et tu ne pourras dire que ces commandes statiques.
Si tu regardes ta log, aujourd'hui ton Snowboy ne sait reconnaitre que 2 mots (ceux qui viennent avec l'installation par défaut):
```
DEBUG: models=alexa,snowboy
```
Pour trainer un nouveau mot / expression, tu peux le faire dans Settings > Voice Reco > Snowboy Train...
Par exemple tu peux trainer "Au revoir", et il reconnaitra "Au revoir". (Pas "Au" ni "Revoir" séparément).

**Comment by FougereBle** [comment]
Ah, merci beaucoup !

Je ne savais pas qu'il fallait enregistrer les mots soi-même pour faire du 100 offline.

Sinon, la reconnaissance en ligne, c'est vraiment un danger pour la vie privée ? (même si je me doute un peu de la réponse).

**Comment by alexylem** [comment]
>Sinon, la reconnaissance en ligne, c'est vraiment un danger pour la vie privée ?

J'explique ca dans ma première vidéo sur youtube:
https://youtu.be/27E_BK1rUKI
En fait c'est tout le but d'utiliser un hotword, tu sais exactement ce qui va être envoyé sur le cloud.

**Comment by FougereBle** [comment]
Merci !

Juste une dernière question, après c'est bon, je ne t'embête plus ! :p

Dans mon compte Snowboy, il y à écrit "You have used 4/1000 of your monthly quota.".
Ca représente quoi ? Le nombre de mot que je peut enregistrer ou le nombre de commande que je peut passer à Jarvis ?

**Comment by alexylem** [comment]
C'est le nombre de mot que tu peux trainer/enregistrer (utilisation de l'API). L'utilisation de Snowboy (parmi les mots que tu as enregistrés) est bien entendu gratuit et illimité, Snowboy ne peut pas savoir combien de fois tu l'utilises (hors ligne).

**Comment by FougereBle** [comment]
Merci !

**Comment by brunoloison** [comment]
Bonjour à tous, bonjour Alex.
Je vais le faire vite mais je vais le faire quand-même. Ton travail est absolument génial, et je pèse mes mots!
Voilà, ça c'est fait :-)
Je pense être à peu près au bon endroit pour ma question...  je ne pense pas avoir besoin d'un mode multi-utilisateur, mais plutôt (j'ai envie de dire "plus simplement"), de plusieurs hotwords, pour plusieurs personnes, pour faire la même chose. En gros, puisque après le hotword, c'est Bing (en tout cas pour moi) qui gère la reconnaissance vocale, il n'y a que cet hotword unique qui empêche les autres membres de la famille d'utiliser ton Jarvis. 
Le mien s'appelle simplement "Opérateur", et évidemment, quand ma femme dit "Opérateur", il ne se passe rien... normal. Alors ce qui est ouf (ouf ouf ouf), c'est que dans les settings, elle peut entraîner son hotword (une autre voix qui dit le même "Opérateur"), mais que... ça ne sert à rien, puisque le fichier pmdl n'est pas pris en compte, puisque (pardon pour la longueur) mon magic word s'orthographie d'une seule façon, donc un seul fichier pmdl.
Bref, possible ou pas de faire reconnaître deux hotwords pour faire strictement la même chose, sans individuakisation des commandes ni rien de ce genre???

Merci d'avoir tenu jusqu'au bout de mon message, et merci pour le travail de dingue que tu as fait... ha oui... sinon je suis venu à Jarvis pour "manipuler" Jeedom... et ça cartonne.

**Comment by wikijm** [comment]
@FougereBle Vu que semble avoir reçu réponses à tes questions, je clôture cette issue. N'hésites pas à le rouvrir si ce n'est pas le cas.
Bonjjour @brunoloison, je t'invite à créer une nouvelle issue afin que @alexylem (entre autre) puisse prendre en considération ta demande.

**Comment by brunoloison** [comment]
@wikijm Merci du conseil, je viens de créer une nouvelle Issue :-)
