### ISSUE TITLE
Voice recognition & speech synthesis in German

### ISSUE THREAD

**Issue by wassereimer86** [alexylem/jarvis#450]
Hi,

first i want to thank you for the great project!

My question: What can I do to add the German language to jarvis?

One comment: It would be great if the whole project and the main language would be in English. I nearly couldn´t use the issue section here on Github and search for something. Also the complete site on http://domotiquefacile.fr/jarvis/ is not helpful because i don´t speak French. I think you would get a much bigger community when you change this. And you definitly deserve a way bigger community!

Best regards
Jens

**Comment by wikijm** [comment]
Hi @wassereimer86,

You will receive some help in English, but I understand your concern about usage of French on this project.
I'll let @alexylem answer to your question.

**Comment by alexylem** [comment]
Morgen @wassereimer86 and hanks for your comment, I agree with you, however most of the users are french for now as my youtube channel is in french.
However the program itself (menus, api documentation) is in english.
Translation of the program in other languages is covered by #55 
Translation of the whole site is not planned yet (huge work) unless I do something with Google Translate...
I will add support for German for voice recognition & synthesis now, just give me a min...

**Comment by alexylem** [comment]
Done, you can use Jarvis in German. Select de_DE in Settings > General.
You can use Google for voice synthesis (works). Am now adding Voxygen voice for German.

**Comment by wassereimer86** [comment]
Hi @alexylem ,

ofcourse i was happy to see that the program is complete in english and i can understand your situation. Just wanted to say what i was thinking. :)

Thank you very much for adding the support for the German language so fast! :)

Best regards
Jens
