### ISSUE TITLE
Snowboy error with selected German language

### ISSUE THREAD

**Issue by wassereimer86** [alexylem/jarvis#451]
This error occures when the hotword should be trained with snowball after recording the three samples

`{"universal_hotword":{"language":["\"de\" is not a valid choice."]}}`

**Comment by alexylem** [comment]
According to the kitt.ai docs, language code for Deutsch is `dt`
![image](https://cloud.githubusercontent.com/assets/11017174/23329166/53b70d90-fb32-11e6-9dcc-bee04e64f998.png)
Changing this...

**Comment by alexylem** [comment]
Fixed. Please update:
```shell
$> ./jarvis.sh -u
```
