### ISSUE TITLE
Error "Permission denied" after starting Jarvis

### ISSUE THREAD

**Issue by wassereimer86** [alexylem/jarvis#452]
When i start Jarvis i get the following error. The target folder is owned by root and the permissions are "rwx only by owner".

`Failed to create secure directory (/run/user/0/pulse): Permission denied`

**Comment by alexylem** [comment]
Jarvis is not supposed to create anything in `/run/user/0/puls`
Could you please paste the whole terminal output with Jarvis in troubleshooting mode?
Also please make sure you have installed Jarvis with you normal user (not sudo) in a folder accessible/writeable by your user.

**Comment by wassereimer86** [comment]
I give you the needed information when i install Jarvis again in a few hours.

But i can already tell you that i´ve installed it with a normal user (which is in the sudoers). I only entered my sudo password at the moment i was asked to do it.

**Comment by wassereimer86** [comment]
Funny, i dind´t changed anything but this time i didn´t get the error. Perhaps because this time i didn´t hat problems with my audio devices. Idk.... We can close this ticket.
