### ISSUE TITLE
Installer Jarvis sans micro

### ISSUE THREAD

**Issue by FougereBle** [alexylem/jarvis#453]
Bonjour !

Suite à une réinstallation de Raspbian (avec mode graphique), j'essaye d'installer Jarvis.

Je n'ai pas encore de micro USB.

Lorsque je lance la commande :
cd ./jarvis/
./jarvis/sh

L'installation démarre.

Cependant, au moment de choisir si je possède un micro, je met "No" mais il me dit qu'il va réglé le niveau audio du micro. Hors, j'ai bien dit que je n'en avais pas.

Ce qui me donne l'erreur suivante :

ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknow PCM false
rec FAIL formats: can't open input 'default': snd_pcm_open error: No such file or directory
ERROR: rec command failed
HELP: Verify your mic in Settings > Audio > Mic

Comment faire ?

Merci !

**Comment by wikijm** [comment]
Bonjour @FougereBle,

Bien vu, j'arrive à reproduire le même problème.
Cela est certainement lié au commit https://github.com/alexylem/jarvis/commit/283b6c74ad8604cff92e5ba873e9e64af1e14944

**Comment by FougereBle** [comment]
Ce qui est étrange, c'est que j'avais réussi à installer Jarvis avec Raspbian Lite, toujours sans micro. ^^

Une prochaine mise à jour pourra résoudre ce problème ?

Merci !

**Comment by alexylem** [comment]
Confirmé, je corrige...

**Comment by alexylem** [comment]
Voila c'est corrigé. Mettez à jour:
```shell
$> ./jarvis.sh -u
```
