### ISSUE TITLE
(*) replaced by ${BASH_REMATCH[1]}

### ISSUE THREAD

**Issue by kevincaradant** [alexylem/jarvis#454]
Hi

I use it without problem (*) with (1) when I passed the arguments in a function.

But when I want use it directly, I'm lost .... I tied many things but this command:

`*LANCE*|*EXECUTE(*)==callUrlKodi '{"jsonrpc":"2.0","method":"Addons.ExecuteAddon","params":{"addonid":"plugin.video.$("(1)")},"id":1}'; return`

Give me something like:
`{"jsonrpc":"2.0","method":"Addons.ExecuteAddon","params":"addonid":"plugin.video.$("${BASH_REMATCH[1]}")},"id":1}`

I want the value of `(1)` and not `${BASH_REMATCH[1]}. I miss something but I don't know what .

Thank you :)

**Comment by alexylem** [comment]
Hmmm it should work, there is maybe a bug.
I think it is related to the fact that you use pipe `|` in your command. The `(*)` should be in both places:
```
*LANCE(*)|*EXECUTE(*)==callUrlKodi '{"jsonrpc":"2.0","method":"Addons.ExecuteAddon","params":{"addonid":"plugin.video.$("(1)")},"id":1}'; return
```

**Comment by kevincaradant** [comment]
I don't think so. 
Even like that:
`>*EXECUTE(*)==callUrlKodi '{"jsonrpc":"2.0","method":"Addons.ExecuteAddon","params":{"addonid":"plugin.video.$("(1)")},"id":1}'; return`

The echo give me:
`{"jsonrpc":"2.0","method":"Addons.ExecuteAddon","params":{"addonid":"plugin.video.$("${BASH_REMATCH[1]}")},"id":1}`

**Comment by alexylem** [comment]
Just to make sure, in the standard installation, there is a command:
```shell
*REPETE (*) ET (*)==say "(1) (2)"
```
So can you please try:
```shell
$> ./jarvis.sh -x "repete tic et tac"
Jarvis: tic tac
```
Maybe it's because it's a nested order?

**Comment by kevincaradant** [comment]
This is the output:

```
./jarvis.sh -x "repete tic et tac"
jarvisse: tic tac
ERROR: Jarvis is not running
HELP: Start Jarvis using ./jarvis.sh -b
```

It's working in this case ?

**Comment by alexylem** [comment]
Do as it says, you now need to have Jarvis running in the background to use `-x` command (and others):
```shell
$> ./jarvis.sh -b
$> ./jarvis.sh -x "repete tic et tac"
```

**Comment by alexylem** [comment]
Sorry I read too fast, yes it worked:
```
jarvisse: tic tac
```
So I would say it's either because it's from a plugin or it's a nested command (starts with `>`). I need to investigate further...

**Comment by alexylem** [comment]
Ok j'ai trouvé, en fait c'est normal que `(1)` soit remplacé par `${BASH_REMATCH[1]}`.
L'interprétation (le remplacement de `${BASH_REMATCH[1]}` par la valeur finale) est faite par `bash` mais il faut que `${BASH_REMATCH[1]}` soit entre guillemets doubles. Et ton argument de `callUrlKodi` est entre guillements simples.
Essaye donc de remplacer:
```shell
>*EXECUTE(*)==callUrlKodi '{"jsonrpc":"2.0","method":"Addons.ExecuteAddon","params":{"addonid":"plugin.video.$("(1)")},"id":1}'; return
```
par
```shell
>*EXECUTE(*)==callUrlKodi "{\"jsonrpc\":\"2.0\",\"method\":\"Addons.ExecuteAddon\",\"params\":{\"addonid\":\"plugin.video.(1)\",\"id\":1}"; return
```

**Comment by kevincaradant** [comment]
Welldone @alexylem !

The problem is resolved.

Thank you very much

NB: I rewrote my message because we started in english but we finish in french ^^

**Comment by kevincaradant** [comment]
Just last thing. It's a little bit a topic off but I hope you can help me @alexylem :) 

If you look my jarvis-kodi plugin, I make ` ' ` instead of `"` because otherwise I have this error with Kodi
`{"error":{"code":-32700,"message":"Parse error."},"id":null,"jsonrpc":"2.0"}`

My NEW command thanks to your help( I wrote EXECUTE YOUTUBE ) :
`>*EXECUTE (*)==callUrlKodi "{\"jsonrpc\":\"2.0\",\"method\":\"Addons.ExecuteAddon\",\"params\":{\"addonid\":\"plugin.video.(1)\",\"id\":1}"; return`

My function callUrlKodi:
```
callUrlKodi(){
    echo ${1}
    curl -s -H "Content-Type: application/json" -X POST -d ${1} http://$kodiIp:$kodiPort/jsonrpc
}
```

the result seems good: 
`{"jsonrpc":"2.0","method":"Addons.ExecuteAddon","params":{"addonid":"plugin.video.youtube","id":1}`


It's not the first I get that, I miss something that I don't understand about the escaping of character I guess. 

Thank you ;)

**Comment by alexylem** [comment]
I guess it's you who have added the carriage return in the command / result?
My advice to debug your plugin is to add some traces in troubleshooting mode, ex:
```shell
local cmd="curl..."
$verbose && jv_debug "$cmd"
eval "$cmd"
```
This way you will understand better where is the issue, copy the debug line in the terminal and try to have it working to get the exact syntax to generate.

**Comment by kevincaradant** [comment]
I edited the last message, about the carriage return, I'm not sure what do you try to say. 
Otherwise, I tried to write that:
```
callUrlKodi(){
    local cmd='curl -s -H "Content-Type: application/json" -X POST -d ${1} http://$kodiIp:$kodiPort/jsonrpc'
    $verbose && jv_debug "$cmd"
    eval "$cmd"
}
```

The only output is the error of Kodi:
`{"error":{"code":-32700,"message":"Parse error."},"id":null,"jsonrpc":"2.0"}`

IS it something I forgot ?

**Comment by alexylem** [comment]
```shell
$> ./jarvis.sh -kv # keyboard + troubleshooting modes
```

**Comment by kevincaradant** [comment]
Ah yes indeed. thank you

In fact, it doesn't matter but I took your command that you give me here: https://github.com/alexylem/jarvis/issues/454#issuecomment-282566424

You omitted the character `}` in your answer ;)

Problem fixed :) Thanks
