### ISSUE TITLE
Snowboy token Get one at: https://snowboy.kitt.ai (in profile settings)

### ISSUE THREAD

**Issue by majemle** [alexylem/jarvis#455]
Bonjour à tous,

En cours d'installation et le choix de SnowBoy, j'ai un message : 
Snowboy token
Get one at: https://snowboy.kitt.ai (in profile settings)

Que dois-je mettre dans la zone ?

Merci de votre aide
Cordialement

**Comment by alexylem** [comment]
Il suffit de faire ce qu'il demande, à savoir
1) Aller sur https://snowboy.kitt.ai
2) Créer un compte
3) Récupérer sa clé dans la page profile
Tu peux passer cette étape en utilisant un des hotwords déjà installés par défaut (snowboy ou alexa)
