### ISSUE TITLE
Prblème avec plugins_order.txt qui se remet seul dans l'ordre alphabétique...

### ISSUE THREAD

**Issue by Jean-Bernard-Hallez** [alexylem/jarvis#456]
### Description

Bonjour, je pensais avvoir un bug de mon coté, j'ai supprimer le dossier jarvis et j'ai tout réinstallé... et je ne comprends pas pourquoi le fichier de base plugins-order.txt se remets seul dans l'ordre aphabétique, ce qui me plante mes plugins....

J'ai beau le mettre à jour en passaant par la menu Jarvis, plugins, matching order au bout de 2 ou 3 heures, ca repasse dans l'odre chronologique de A a Z.

Le truc c'est que j'ai 2 Rasperry pi et sur le second je n'ai pas ce problème !!!!

Merci de votre aide...

**Comment by alexylem** [comment]
Voici le bout de code qui corrige/regénère ce fichier:
```shell
# Internal: Rebuild plugins_order.txt following added/removed plugins
jv_plugins_order_rebuild () {
    # Append new plugins to plugins_order
    cat plugins_order.txt <( ls plugins ) 2>/dev/null | awk '!x[$0]++' > /tmp/plugins_order.tmp
    # Remove uninstalled plugins from plugins_order
    grep -xf <( ls plugins ) /tmp/plugins_order.tmp > plugins_order.txt
}
```
Il compare ligne par ligne et dès qu'il mangue un plugin il le rajoute (dans l'ordre alphabétique). Puis il enlève tout ce qui ne correspond pas à un vrai plugin installé.
Je te conseille par commencer de regarder si lorsque tu réarranges tu ne rajoutes pas des espaces malencontreux. Modifie bien ce fichier depuis le terminal, pas en ftp.

Si ca n'aide pas, un petit asciinema serait fort utile dans ton cas précis.

**Comment by alexylem** [comment]
```shell
sudo apt-get install -y asciinema && asciinema rec # start session recording
./jarvish.sh -nv # start jarvis directly in troubleshooting mode
Ctrl+D # stop recording
y # yes to upload and get URL to paste here
```

**Comment by Jean-Bernard-Hallez** [comment]
Je pense que mon problème venait d'un espace car je faisais du copier coller... pour déplacer mes ordres... a suivre...

**Comment by alexylem** [comment]
ok tiens nous au courant, merci

**Comment by Jean-Bernard-Hallez** [comment]
Hélas j'ai le même problème... j'ai supprimé tous les plugins pour laisser que celui qui bosse et ca fait pareil.
J'ai mais un # dans le crontab pour voir si ca vient de là à suivre... si ca continue en effet je vais passer par asciinema.

**Comment by Jean-Bernard-Hallez** [comment]
Le bout de code est clair et il ne doit pas me modifier mon order... je souhaite installer asciienema et juste en faisant (ou la ligne entière) cela me dit:
sudo apt-get install asciinema:
Err http://mirrordirector.raspbian.org/raspbian/ jessie/main asciinema all 0.9.8-1
  Impossible d'initialiser la connexion à mirrordirector.raspbian.org: 80 (2a00:1098:0:80:1000:75:0:3). - connect (101: Le réseau n'est pas accessible) [IP : 2a00:1098:0:80:1000:75:0:3 80]
E: Impossible de récupérer http://mirrordirector.raspbian.org/raspbian/pool/main/a/asciinema/asciinema_0.9.8-1_all.deb  Impossible d'initialiser la connexion à mirrordirector.raspbian.org: 80 (2a00:1098:0:80:1000:75:0:3). - connect (101: Le réseau n'est pas accessible) [IP : 2a00:1098:0:80:1000:75:0:3 80]

Un bug du server peut-être je le retesterai un peu plus tard... A suivre...

**Comment by Jean-Bernard-Hallez** [comment]
Bon j'ai accélérer mon bug... j'ai modifié mon crontab de manière a ce qu'il me donne l'heure toute les 3 minutes, 
https://asciinema.org/a/8bnc9b5yfjkcww59vnaqe49zv
Au bout de 12min 29 plugins_order.txt c'est remis dans l'ordre mais on ne voit rien qui s'y passe...

mon crontab:
*/3       7-21    *       *       1-5       ~/jarvis/jarvis.sh -x "quelle heure est-il?"
*/5       8-21    *       *       1-5       ~/jarvis/jarvis.sh -x "mesurepir"

Mon plugin order:
jarvis-plug-pir
jarvis-api
jarvis-ui
jarvis-esclave

Je continue mes test en supprimant la demande externe de l'heure pour voir si j'ai le même problème en interne et j''essaye d’accélérer le problème en lançant ma commande toute les minutes... a suivre...

**Comment by alexylem** [comment]
Je ne pense pas que cela puisse venir du crontab.
Ton asciinema n'illustre pas le problème, juste une utilisation normale de Jarvis.
Peux-tu simplement avec asciinema aller dans Plugins / Change Order, montrer l'ordre correct, utiliser Jarvis, puis retourner dans Change Order pour voir qu'il a été changé?

**Comment by Jean-Bernard-Hallez** [comment]
Et voilà
Je l'ai mis en ordre, puis quitté jarvis, relancé jarvis pour montrer qu'il est bien resté dans l'ordre, j'ai lancée une commande et là du premier coup il a planté une chance pour cette courte vidéo:
(derrière il y avait dans le crontab)
*/2       7-21    *       *       1-5       ~/jarvis/jarvis.sh -x "quelle heure est-il?"
*/1       8-21    *       *       1-5       ~/jarvis/jarvis.sh -x "mesurepir"
http://asciinema.org/a/7ly8iies63xf00gog19x8jrof

**Comment by alexylem** [comment]
Merci... c'est carrément bizarre et rien ne peut me l'expliquer pour le moment, je vais creuser ca... merci bcp pour l'exemple c'est flagrant.

**Comment by alexylem** [comment]
Juste une astuce, avec Nano tu peux facilement couper-coller, va sur la ligne et fait "Ctrl+K" pour la couper puis mets toi ou tu veux la coller et fait "Ctrl+U" 😄

**Comment by Jean-Bernard-Hallez** [comment]
Oui je connaissais l'astuce avec nano... mais j'avais peur que tu me dises l'inverse lol qu'il ne fallait pas le faire... j'ai donc pris le chemin des écoliers...   ;-)

**Comment by alexylem** [comment]
Tu peux vérifier les droits sur le fichier `plugins_order.txt`?
```shell
$> ls -l plugins_order.txt
-rw-r--r-- 1 pi pi 105 Mar  2 20:32 plugins_order.txt
```
Ensuite peux-tu le modifier dans Jarvis puis exécuter cette commande:
```shell
$> cat plugins_order.txt <( ls plugins ) 2>/dev/null | awk '!x[$0]++'
```
Ca devrait te retourner le contenu du fichier non altéré, tu confirmes?

**Comment by Jean-Bernard-Hallez** [comment]
Et recoucou...
Mes droits sont comme les tiens:
-rw-r--r-- 1 pi pi 149 mars   2 22:29 plugins_order.txt

si je mets en place mes order puis 
cat plugins_order.txt <( ls plugins ) 2>/dev/null | awk '!x[$0]++'
j'ai le même ordre que j'ai demandé...

En fait j'ai cherché aussi de mon coté, je ne sais pas pourquoi mais c'est quand j'utilise mon jarvis avec le plugin esclave (qui par jarvis -x me rechercher des infos sur le jarvis server) que de temps en temps j'ai un retour de bug...

C'est a dire que si dans mon ctrontab j'utilise que des commande local, il ne plante jamais, et dès que je combine les deux... ca bug...

Il me fait tester en commande crontab et curl pour voir ce que ca donne si je n'utilise pas mon plugin...

A suivre...

**Comment by Jean-Bernard-Hallez** [comment]
Ma dernière réponse était un peu stupide.... si je passe par le crontab pour exécuter une commande qui se trouve sur un autre rapsberry c'est sur ca fonctionne... car je ne solicite pas le jarvis en question...

J'ai donc mis dans jarvis.commands:
*CHEMISE*==say "Ok $(curl -s "http://192.168.0.11:8088?order=quelle%20heure%20est%20t-il%20?")"
Et là je le lance par le crontab...
*/1       8-21    *       *       1-5       ~/jarvis/jarvis.sh -x "mesurepir"
*/2      8-21    *       *       1-5       ~/jarvis/jarvis.sh -x "chemise"

Je test à suivre....
J'ai le même problème !! donc ca ne vient pas d'un de mes plugins qui va planter le system...

**Comment by Jean-Bernard-Hallez** [comment]
J'ai exactement le même problème.... je vais tenter encore autre chose... j'ai testé que ce ne vient pas de mon plugin esclave, je vais maintenant tester si va vient de mesurepir:

J'ai donc créer un plugin bison nommé victoire dans lequel j'ai mis juste dans command pantalon==say "il est bien mis"
puis 
*/1 8-21 * * 1-5 ~/jarvis/jarvis.sh -x "pantalon"
*/2 8-21 * * 1-5 ~/jarvis/jarvis.sh -x "chemise"

A suivre...

**Comment by Jean-Bernard-Hallez** [comment]
Même problème... ca ne vient pas de mes plugins... afin de boucler cette certitude, je vais laisser juste pantalon, et api,  rien d'autre... et supprimer tous les autres plugins.
A suivre....

**Comment by Jean-Bernard-Hallez** [comment]
Je pense avoir trouvé.... C'est un bug de mon coté... à suivre....

**Comment by alexylem** [comment]
Ok 👍  ca me rassure car je voyais vraiment pas d'où ca pouvait venir de mon côté...

**Comment by wikijm** [comment]
@Jean-Bernard-Hallez Content que tu ai pu trouver la source du problème, et j'espère la solution 😄 
Le problème n'étant semble-t'il pas lié à Jarvis Core, je clôture le ticket.

Si tu as besoin de plus d'explications, n'hésites pas à le ré-ouvrir ;-)
