### ISSUE TITLE
jarvis api

### ISSUE THREAD

**Issue by NYGHOST** [alexylem/jarvis#457]
petit souci en lancant l'interface web de jarvis
{"error":"don't know what to do with"{}}

je viens de reprendre jarvis et fait la MAJ, je ne parviens pas a utiliser les commandes.

**Comment by Jean-Bernard-Hallez** [comment]
Quelle commande envois-tu ? chez moi ca fonctionne.... ne confonds tu pas API et interface UI ?

{"error": "Don't know what to do with: {}"} signifie que tu n'as rien envoyé dans ta commande...
Si tu fais:
http://192.168.X.X:YYYY/?order=Bonjour 
tu as quoi ?

**Comment by NYGHOST** [comment]
je te dis ca demain sans faute
en tous cas bravo pour les avancées.

Envoyé de mon iPhone

Le 27 févr. 2017 à 17:44, Hallez <notifications@github.com<mailto:notifications@github.com>> a écrit :


Quelle commande envois-tu ? chez moi ca fonctionne.... ne confonds tu pas API et interface UI ?

{"error": "Don't know what to do with: {}"} signifie que tu n'as rien envoyé dans ta commande...
Si tu fais:
http://192.168.X.X:YYYY/?order=Bonjour
tu as quoi ?

**Comment by wikijm** [comment]
@NYGHOST Pas de nouvelle depuis 6 jours.
Je clôture, mais n'hésites pas à nous faire part de la résolution de ton problème, ou le ré-ouvrir si encore d'actualité.
