### ISSUE TITLE
Qui parmi-vous a intallé in écrant 3.5 inch RPI XPT2046 Touch Controller pour raspberrypi3

### ISSUE THREAD

**Issue by Jean-Bernard-Hallez** [alexylem/jarvis#460]
Bonjour, je l'ai reçu hier et depuis je m'acharne dans tous les sens pour l'installation... le cd livré avec les drivers me plante ma SD, sur le site il propose une mise à jour mais  même problème...

Je vois sur les blogs que je ne suis pas le seul a voir ce problème...
Je suis sur une installation toute neuve Raspberry PI 3
Linux 4.4.48V7+  ARMV71

Et vous, comment avez vous pu le contourner ? ?

**Comment by Jean-Bernard-Hallez** [comment]
dur dur mais j'y suis arrivé... il faut installer cette image:
[https://docs.google.com/uc?id=0B-Z1UZhyKaZ0YXhZMnpaLU5COGs&export=download](https://docs.google.com/uc?id=0B-Z1UZhyKaZ0YXhZMnpaLU5COGs&export=download)

**Comment by tchoul** [comment]
Pour mon ecran 3.5 perso je l'avais juste brancher et utiliser  [ça](http://www.waveshare.com/wiki/3.5inch_RPi_LCD_%28A%29)

**Comment by Jean-Bernard-Hallez** [comment]
C'est ce que j'ai fait... mais il m'a fallu comme je le disais... chercher...   ;-) et oui ca fonctionne...  Merci... ca pourra aider peut-être quelqu'un d'autre...
