### ISSUE TITLE
Script pour désinstaller jarvis et ses dépendances 

### ISSUE THREAD

**Issue by trarizakaria** [alexylem/jarvis#461]
Parfois, suite à des disfonctionnements de jarvis on se trouve obligé de faire une désinstallation et repartir de  zero. Pourtant on ne sais pas quelles sonts les dépendances de jarvis ou comment les désinstaller. Il serait souhaitable d'avoir un script uninstall.sh qui désinstalle jarvis et toutes ses dépendances.

**Comment by alexylem** [comment]
Merci @trarizakaria.
Si je désinstalle toutes les dépendances de Jarvis alors je pourrais désinstaller une dépendances qui était déjà présente et nécessaire pour d'autres logiciels installés.
L'idéal serait lors de l'installation de stocker la liste des paquets manquants et installés, et désinstaller uniquement ceux-la (avec confirmation) lors de la désinstallation de Jarvis.
Pour ceux qui ont déjà installé Jarvis (donc cette liste n'existe pas), je peux proposer de désinstaller les paquets les paquets suivants (normalement non présents sur install fresh de Raspbian lite):
```
jq
sox
mpg123
pocketsphinx (bison libasound2-dev python-dev swig)
snowboy (python-pyaudio python3-pyaudio libatlas-base-dev)
espeak
libttspico-utils
```
Mais il y aura un risque de casser des dépendances pour d'autres logiciels installés après-coup.
Tu en penses quoi?

**Comment by alexylem** [comment]
En fait je crois qu'il doit être possible de vérifier s'il existe des dépendances avant de supprimer un paquet. Je vais vérifier ca...

**Comment by alexylem** [comment]
```shell
$> aptitude why --show-summary mpg123
Packages requiring mpg123:
$>
```
Je pourrais donc proposer de désinstaller tous les paquets (après confirmation) qui ne sont pas une  dépendance pour un autre paquet installé.

**Comment by trarizakaria** [comment]
Oui je te comprends parfaitement.  même  si on désinstalle les paquets qui n'était pas présente lors de l'ajout de jarvis on pourrai casser le fonctionnement d'un autre programme qui a été installé après  jarvis. Mais je crois qu'il existe une solution pour ça. 
Vu que je ne suis pas expert en linux, quand je rencontre un problème la solution pour moi c'est désinstaller et réinstaller et parfois même  en faisant ça  il se peut que le problème se trouve dans une dépendance. 
Mais si je me rappelle il m'est arrivé au cours d'une désinstallation d'un programme x un message disant : 
Cette dépendance  est utilisé par un programme y

En tous cas si on arrive  à  avoir ce script ça  sera un atout pour jarvis

**Comment by trarizakaria** [comment]
Merci @alexylem pour la nouvelle option -r
