### ISSUE TITLE
Variable pour répéter une commande n fois. 

### ISSUE THREAD

**Issue by trarizakaria** [alexylem/jarvis#462]
Est il possible de lancer une commande 2 3 ou 4 fois en faisant qu'une seule commande ? 
Je m'explique : 
Dans le plugin jarvis-kodi il y a des commandes pour naviguer sur kodi. Pour choisir un film dans la liste on dois répèter la commande "bas" plusieurs fois pour descendre jusqu'au film. 
L'idée c'est  de dire "quatrième" au lieu de répéter 4 fois la commande  "bas" 
"quatrième" = 4 x "bas"

**Comment by tchoul** [comment]
oui avec  &&
Par exemple : 
`*HELLO*WORLD*TROIS*FOIS==say "Hello world" && say "Hello world" && say "Hello world" `

**Comment by alexylem** [comment]
Ou
```shell
BAS==for run in {1..10}; do my_pg_kodi_cmd "bas"; done
```

**Comment by trarizakaria** [comment]
@kevincaradant  que penses tu ?

**Comment by wikijm** [comment]
@trarizakaria Si je comprends bien, tu souhaites que @kevincaradant fasse évoluer son plugin en intégrant la solution de @alexymel ?

Si c'est le cas, je t'invite à créer une issue sur le [repository du plugin](https://github.com/kevincaradant/jarvis-kodi/issues) ou proposer un [pull request](https://github.com/kevincaradant/jarvis-kodi/pulls).
Si ce n'est pas le cas, n'hésite pas à ré-ouvrir le ticket et nous expliquer ton attente :-)

**Comment by kevincaradant** [comment]
Hello tout le monde,

Je n'ai pas trop le temps de regarder @trarizakaria. En effet, nous en avions discuter sur gitter. Je pense que c'est une très bonne idée mais qu'il faut voir comment l'implémenter et je n'ai pas trouvé quelque chose de satisfaisant pour l'instant. C'est peut-être simple mais j'ai pas eu le déclic pour l'instant.

N'ayant pas trop le temps, si tout l'algorithme m'est fourni, je pourrais l'implémenter sinon il faudra attendre que j'ai plus de temps :)

**Comment by trarizakaria** [comment]
@wikijim Oui,  j'ai donné un exemple avec le plugin kodi et je voulais intégrer cette fonctionnalité dans ce plugin. Et utiliser ça  pour d'autres plugins ou autre commande dans le future. Donc j'ai ouvert cet issue ici parceque c'est quelque-chose qui ne concerne pas seulement kodi et peut être utilisé par tout le monde :) 
@kevincaradant tu as déjà  fait un grand effort,  ton plugin et devenu plus pratique et l'un des meilleurs pour jarvis.

Merci à  tous.
