### ISSUE TITLE
Aucune commande ne marche

### ISSUE THREAD

**Issue by Docktor66** [alexylem/jarvis#464]
J'ai installé sans problème jarvis et sélectioné PocketSphinx pour le hotword et wit pour les commande mais ça ne marche pas le hotword est détecté correctement mais la commande résulte en un bruit et aucune réponse ( erreur de compréhension), j'aimerai savoir où je fais fausse route étant débutant.
merci en avance :)

**Comment by wikijm** [comment]
Bonjour @Docktor66,

Peux-tu faire les actions demandées lorsque tu crée un ticket ou comme marqué dans la [présentation de Jarvis](https://github.com/alexylem/jarvis) (tester en mode troubleshooting, "filmer" ton terminal avec asciinema, ...) ?

**Comment by alexylem** [comment]
Merci de coller le résultat complet de la console après avoir lancé Jarvis en mode Troubleshooting, ou partage une session de ton terminal en utilisant [asciinema](http://asciinema.org):

**Comment by Docktor66** [comment]
------------ Config ------------
jv_version           17.03.03 
jv_arch              armv7l 
jv_os_name           raspbian 
jv_os_version        8 
language             fr_FR 
play_hw              hw:0,1 
rec_hw               hw:1,0 
speaker              ALSA 
microphone           C-Media Electronics, Inc. CM108 Audio Controller 
trigger_stt          pocketsphinx 
command_stt          wit 
tts_engine           google 
--------------------------------

DEBUG: program_startup hook
jarvis: Bonjour paul en quoi je peux vous être utile ?
DEBUG: start_speaking hook
iconv: séquence d'échappement non permise à la position 34
DEBUG: stop_speaking hook
User defined commands:
*AIDE*			*BONJOUR*|*SALUT*	*COMMENT*APPELLE*
*MERCI*			*AU REVOIR*|*BYE*	ANNULE*|TERMINE*
ENCORE*			*TEST*			*VERSION*
*REPETE (*) ET (*)	*CA VA*			>*OUI*
>*NON*
Commands from plugin jarvis-minuterie:
*EFFACE*MINUTE*		*MINUTE*		>(*)
jarvis: Waiting to hear 'jarvis'
paul: (listening...)
 rec -V1 -q -r 16000 -c 1 -b 16 -e signed-integer --endian little /dev/shm/jarvis-record.wav gain 28 silence 1 0.1 11 1 0.5 11 trim 0 10

**Comment by wikijm** [comment]
Il est possible que tu ai un problème d'encodage de l'un de te fichiers (voir https://forum.ubuntu-fr.org/viewtopic.php?id=293552).
Je t'invite à désactiver tous tes modules, puis les réactiver un par un pour voir si l'un deux provoque cette erreur.

**Comment by Docktor66** [comment]
je vais essayer ça en fin de soirée ( je ne suis pas aec ma raspberry là ) et je vous tiens au courant :) merci :)

**Comment by alexylem** [comment]
On peut avoir la copie du terminal avec Jarvis dans ton scénario au complet? Parce que la je ne vois que le début avant la reconnaissance du hotword. Ta description du problème indique qu'il survient après la détection du hotword, au niveau de la commande.
Merci.

**Comment by Docktor66** [comment]
------------ Config ------------
jv_version           17.03.05 
jv_arch              armv7l 
jv_os_name           raspbian 
jv_os_version        8 
language             fr_FR 
play_hw              hw:0,1 
rec_hw               hw:1,0 
speaker              ALSA 
microphone           C-Media Electronics, Inc. CM108 Audio Controller 
trigger_stt          pocketsphinx 
command_stt          wit 
tts_engine           google 
--------------------------------

DEBUG: program_startup hook
jarvis: Bonjour paul en quoi je peux vous être utile ?
DEBUG: start_speaking hook
iconv: séquence d'échappement non permise à la position 34
DEBUG: stop_speaking hook
User defined commands:
*AIDE*			*BONJOUR*|*SALUT*	*COMMENT*APPELLE*
*MERCI*			*AU REVOIR*|*BYE*	ANNULE*|TERMINE*
ENCORE*			*TEST*			*VERSION*
*REPETE (*) ET (*)	*CA VA*			>*OUI*
>*NON*
Commands from plugin jarvis-minuterie:
*EFFACE*MINUTE*		*MINUTE*		>(*)
jarvis: Waiting to hear 'jarvis'
paul: (listening...)
 rec -V1 -q -r 16000 -c 1 -b 16 -e signed-integer --endian little /dev/shm/jarvis-record.wav gain 28 silence 1 0.1 9 1 0.5 9 trim 0 10
DEBUG: speech duration was 00 (10 = 1 sec)
DEBUG: too short for a trigger (min 0.2 max 1.5 sec), ignoring...
 rec -V1 -q -r 16000 -c 1 -b 16 -e signed-integer --endian little /dev/shm/jarvis-record.wav gain 28 silence 1 0.1 9 1 0.5 9 trim 0 10
DEBUG: speech duration was 08 (10 = 1 sec)
(listening...)
 rec -V1 -q -r 16000 -c 1 -b 16 -e signed-integer --endian little /dev/shm/jarvis-record.wav gain 28 silence 1 0.1 9 1 0.5 9 trim 0 10

**Comment by wikijm** [comment]
Bonjour @Docktor66,

Plusieurs versions sont sorties depuis ton problème.
Est-ce que tu peux mettre à jour et réessayer ?

**Comment by alexylem** [comment]
@Docktor66 
Ca fait longtemps que je n'ai pas utilisé PocketSphinx pour la reconnaissance du mot clé. Je te conseille d'utiliser Snowboy qui est aussi Hors ligne et bien plus efficace.
Peux-tu changer le moteur du hotword à Snowboy ou tu tiens vraiment à utiliser PocketSphinx?

**Comment by wikijm** [comment]
Pas de retour depuis 11 jours, j'en conclus que le problème est résolu.
Ne pas hésiter à ré-ouvrir l'issue si ce n'est pas le cas 😉
