### ISSUE TITLE
Besoin d'aide pour le plugin HUE

### ISSUE THREAD

**Issue by crychaor** [alexylem/jarvis#465]
Bonjour,
Voila je me suis équipé du pont et de lampe philips HUE et j'aurai besoin d'aide pour comprendre comment configurer le plugin HUE. je seche j'ai beau chercher, faire plusieur tentative mais la je bloque. 
5 sahcant que l'appli sur mon smartphone fonctionne correctement.

Merci par avance de votre aide.

**Comment by wikijm** [comment]
Bonjour @crychaor,

Je t'invite à créer un ticket sur le repository du plugin, à cette adresse : https://github.com/fatoldsun00/jarvis-hue/issues
Les informations concernant le plugin sont visibles à cette adresse : http://domotiquefacile.fr/jarvis/plugins/hue
