### ISSUE TITLE
Connection refusée : Erreur 403 Forbidden

### ISSUE THREAD

**Issue by Locnes84** [alexylem/jarvis#466]
### Description
Bonjour, 
J'éspère que vous pourrez m'aider. Je débute avec Jarvis que je veux coupler à mon Jeedom.
J'ai donc téléchargé le plugin jeedom de Jarvis, que j'ai bien configuré (IP, port, et ApiKey).

Le problème, je crois que la requête est bloqué car j'ai le résultat connexion refusée. (403 Forbidden)
J'ai essayé également par une requête curl http directement dans les commandes mais idem.

Si vous avez une idée ?

Merci d'avance
PS : Je ne peux pas mettre en mode trouble shooting (Problème de son en boucle car je n'ai pas de micro je pense).
### Result
```shell
Loïc: fermer volet salon est
ERROR: curl: (22) The requested URL returned error: 403 Forbidden
JARVIS: Erreur
Loïc: 
```

**Comment by wikijm** [comment]
Bonjour @Locnes84,

Je t'invite à créer un ticket sur le repository du plugin plutôt que celui de Jarvis Core (voir
https://github.com/alexylem/jarvis-jeedom/issues).

Tu peux te mettre en troubleshooting mode en le couplant avec le keyboard mode en lançant jarvis comme ceci : `./jarvis/jarvis.sh -kv` (`k` pour keyboard, `v` pour verbose/troubleshooting)

**Comment by Locnes84** [comment]
Bon ben du coup merci.
J'ai pu mettre le mode troubles shooting et j'ai trouvé le problème.
C'était le plugin freeboxplayer qui prenait le pas et bloquait. (Je l'ai supprimé et c'est réglé).

**Comment by wikijm** [comment]
Si tu as besoin d'un coup de main pour le plugin [jarvis-freeboxplayer](https://github.com/wikijm/jarvis-freeboxplayer/), n'hésites pas à me faire un ticket, je suis son créateur 😄
