### ISSUE TITLE
Voxygen, extinction de voix?

### ISSUE THREAD

**Issue by tchoul** [alexylem/jarvis#468]
Salut à tous!

Voxygen ne fonctionne plus chez moi après MAJ... Il y a que moi?
Du coup j'utilise svox_pico en attendant

Paix, partage et prospérité `.\\ //`

**Comment by wikijm** [comment]
Le support de Voxygen a été supprimé avec le commit https://github.com/alexylem/jarvis/commit/3282dcb1f984124aae0dd562e6774f8bd68341a6, et par conséquent sur la dernière mise à jour.

Regarde l'issue #446 pour plus d'informations.

**Comment by tchoul** [comment]
Ok je comprends mieux merci pour l'info
