### ISSUE TITLE
Snowboy actually supports more than one word

### ISSUE THREAD

**Issue by xuchen** [alexylem/jarvis#47]
First of all, awesome writeup here!

https://github.com/alexylem/jarvis/wiki/stt

In https://snowboy.kitt.ai/docs there is the "Multiple Models and Callbacks" section detailing how to use it. So I think a more accurate version of "1 Mot" should be the French version of "Several". ;-)

**Comment by alexylem** [comment]
You are totally right, Jarvis supports personal models for the trigger detection and #15 aims at introducing multiple personal models for quick commands detection (without going through the trigger detection).
* I modified "1 Mot" by "Personnel" for the DIctionary
* I added a link for future usage of Snowboy for commands

![capture d ecran 2016-07-14 a 10 40 06](https://cloud.githubusercontent.com/assets/11017174/16833396/75deae3a-49af-11e6-9ff5-e2c070b7ccad.png)

Thanks for your contribution!
