### ISSUE TITLE
sourcer un ou des fichiers pour prise en compte dans jarvis

### ISSUE THREAD

**Issue by Sellig28** [alexylem/jarvis#470]
Vu avec @alexylem 

### Description
Fais suite au ticket:  #335 

J'utilisai le système des hooks au démarrage de jarvis pour sourcer un fichier qui sert pour simplifier la syntaxe de jarvis-commands et surtout faciliter l'intégration de ma domotique Openhab. Comme les hook ne sont plus pris en compte lorsque cela vient de l'api, mes fonctions bash ne sont plus accessibles.

### Result
Du fait de la modification du comportement des hooks et de l'api, mes fonctions ne sont plus appelées.

Suggestion:
Pour ne pas poser de problème en rapport aux hooks de l'issue 335 pourquoi ne pas intégrer dans jarvis une option qui permette de sourcer des fichiers. Exemple ajouter dans le répertoire config un fichier qui en tienne compte.

Ton avis @alexylem et les autres ?

**Comment by alexylem** [comment]
En attendant une solution propre, voici mes suggestions:
1) Fais un plugin Openhab, comme ca tout le monde en profite 😄 
2) Fais un plugin "fake" afin que ton fichier soit sourcé:
Regroupe tes fonctions dans un fichier `functions.php` placé dans `plugins/my_functions/`
Juste celà devrait suffire, mais à tester quand même 😉

**Comment by wikijm** [comment]
@Sellig28 Un avis sur les propositions faites par @alexylem ? 
P.S : Un grand merci pour la clarte de ton ticket. Le contexte et les sources sont là, en plus d'apporter un sujet intéressant :smile:

**Comment by Sellig28** [comment]
Salut @wikijm, @alexylem,

Désolé je n'aime pas faire attendre une issue, mais j'ai pas touché terre.

@wikijm: J'essai d'être clair mais c'est pas toujours le cas :sweat_smile: 

Bon, pour le plugin, ça viendra car Openhab2 est beaucoup plus accessible pour faire une cartographie des éléments présent avec leur type (style volet roulant etc ...). Cependant cela demande du temps, que je n'ai pas pour le moment. Donc pas un plugin openhab :smile:

L'idée d'un plugin dummy ne serait pas mal, non ?

@alexylem 
Tu proposes un fichier  functions.php ! Pas possible avec bash  ou c'est juste pour l'exemple ?

@+

**Comment by alexylem** [comment]
@Sellig28 `functions.sh` bien sûr 👍 
 `.php` ne marcherait pas je sais pas pourquoi j'ai écrit ca 😄

**Comment by Sellig28** [comment]
OK va pour un plugin, je testerai ça demain.

**Comment by Sellig28** [comment]
Heu j'ai menti, je suis claqué, je le ferai ce week-end.

**Comment by Sellig28** [comment]
En fait, j'avais pas dit quel week-end ! :sweat_smile: 

La solution d'un plugin "fake"ou "dummy" fonctionne, j'ai retrouvé mes fonctions personnalisé chargée au démarrage de Jarvis. POur moi c'est tout bon.

Maintenant que le test est concluant, on l'intègre comment dans jarvis.

On fait un plugin ? une autre idée ?

**Comment by alexylem** [comment]
Faire un plugin juste pour sourcer des fichiers, peut-être pas.
Je vois 2 options (non mutuellement exclusives):
1) Tu publies ton plugin OpenHAB comme ca tout le monde en profite 👍 
2) J'ajoute un fichier `my-functions.sh` que les utilisateurs pourront utiliser pour créer des fonctions / sourcer d'autres fichiers externes au démarrage de Jarvis

**Comment by Oliv4945** [comment]
Je n'utilise pas OoenHAB mais l'option 2 me paraît bien pratique dans d'autres cas :-)

**Comment by alexylem** [comment]
Implémenté sur la branch `beta`. Pour le tester dès à présent:
Menu `Settings > General > Branch > beta`
Sinon attendre la mise à jour de ce weekend.

**Comment by Sellig28** [comment]
Ok Alex,
Je publierai un plugin Openhab, a condition qu'il y ai d'autres personnes qui le veulent, car en france c'est plutôt jeedom :smile
Par contre, merci pour la deuxième solution, d'autres personnes pourront l'utiliser.
Merci encore.
