### ISSUE TITLE
Installer snowboy sur ARMBIAN 

### ISSUE THREAD

**Issue by yoan1005** [alexylem/jarvis#473]
### Description
Bonjour, 
Je dispose d'un orange pi avec armbian dessus, toutes l'installation de jarvis s'est bien déroulé (config du mic ok, config des HP aussi tous est bon.) par contre lorsque que je lui dicte une commande il ne la comprends pas, je vous poste le résultat de la console ci dessous.
Si je veux utiliser snowboy pour détecter, il me dis comme quoi je n'utilise pas raspbian et me dis de compiler snowboy via le Git, je ne vois pas comment faire ? 

Merci de votre aide

Comme détecte
### Result
```shell
<paste here> 
------------ Config ------------
jv_version           17.03.08
jv_arch              armv7l
jv_os_name           debian
jv_os_version        8
language             fr_FR
play_hw              hw:0,0
rec_hw               hw:2,0
speaker              audiocodec
microphone           Asahi Kasei Microsystems Co., Ltd
trigger_stt          pocketsphinx
command_stt          bing
tts_engine           svox_pico
--------------------------------

DEBUG: program_startup hook
JARVIS: Hello
DEBUG: start_speaking hook
DEBUG: stop_speaking hook
User defined commands:
*AIDE*                  *BONJOUR*|*SALUT*       *COMMENT*APPELLE*
*MERCI*                 *AU REVOIR*|*BYE*       ANNULE*|TERMINE*
ENCORE*                 *TEST*                  *VERSION*
*REPETE (*) ET (*)      *CA VA*                 >*OUI*
>*NON*
JARVIS: Waiting to hear 'JARVIS'
BOSS: (listening...)
 rec -V1 -q -r 16000 -c 1 -b 16 -e signed-integer --endian little /dev/shm/jarvis-record.wav gain -5 silence 1 0.1 7 1 0.5 7 trim 0 10
DEBUG: speech duration was 02 (10 = 1 sec)
(listening...)
 rec -V1 -q -r 16000 -c 1 -b 16 -e signed-integer --endian little /dev/shm/jarvis-record.wav gain -5 silence 1 0.1 7 1 0.5 7 trim 0 10
DEBUG: speech duration was 00 (10 = 1 sec)
DEBUG: too short for a trigger (min 0.2 max 1.5 sec), ignoring...
 rec -V1 -q -r 16000 -c 1 -b 16 -e signed-integer --endian little /dev/shm/jarvis-record.wav gain -5 silence 1 0.1 7 1 0.5 7 trim 0 10
DEBUG: speech duration was 02 (10 = 1 sec)
?(listening...)
 rec -V1 -q -r 16000 -c 1 -b 16 -e signed-integer --endian little /dev/shm/jarvis-record.wav gain -5 silence 1 0.1 7 1 0.5 7 trim 0 10
DEBUG: speech duration was 13 (10 = 1 sec)
(listening...)
 rec -V1 -q -r 16000 -c 1 -b 16 -e signed-integer --endian little /dev/shm/jarvis-record.wav gain -5 silence 1 0.1 7 1 0.5 7 trim 0 10
```

**Comment by alexylem** [comment]
Je ne te conseille pas d'utiliser PocketSphinx pour la détection du Keyword (à moins que tu parles Anglais). Je te conseille fortement de partir sur Snowboy.
http://docs.kitt.ai/snowboy/#downloads
Si ta carte n'est pas supportée, il faut compiler:
https://github.com/kitt-ai/snowboy#compile-a-python-wrapper
Sinon je crois que tu peux installer Raspbian dessus, ca serait pas plus simple?
Sinon:
>If you want support on other hardware/OS, please send your request to snowboy@kitt.ai

**Comment by davi-domo** [comment]
Bonjour,

je sais que le sujet est clos mais ça peut servir 
voulant a tous prie faire fonctionner JARVIS sur ARMBIAN (Debian jessie en mode console) j'ai cherché, bidouillé et ça fonctionne sur une orange pi+
je vais créer une image fonctionnel dès que j'ai 5 minutes ainsi qu'une petite explication des étapes pour l’installation de SNOWBOY

**Comment by wikijm** [comment]
Réouverture de l'issue suite à la proposition de @davi-domo

**Comment by Oliv4945** [comment]
Pour installer Snowboy vous pouvez aller voir [ici](https://github.com/alexylem/jarvis/issues/660#issue-240023900)

**Comment by davi-domo** [comment]
bonjour,
mon probleme vient de la lib libpython2.7.so.1.0 manquante sur armbian
étant un bidouilleur je ne sais pas si c'est la bonne solution mais cela fonctionne

donc voici ce que je fait
`
#  clone jarvis

> git clone https://github.com/alexylem/jarvis.git

# on installe les dependance
> sudo apt-get install python-pyaudio python3-pyaudio sox libatlas-base-dev swig python-pip

> pip install --upgrade pip

> pip install pyaudio

# acces au dossier snowboy
> cd jarvis/stt_engines/snowboy/

# on télécharge et dcompresse snowboy
> wget https://s3-us-west-2.amazonaws.com/snowboy/snowboy-releases/rpi-arm-raspbian-8.0-1.2.0.tar.bz2 && tar xvjf rpi-arm-raspbian-8.0-1.2.0.tar.bz2 && rm rpi-arm-raspbian-8.0-1.2.0.tar.bz2

> cp -r rpi-arm-raspbian-8.0-1.2.0/* //home/$USER/jarvis/stt_engines/snowboy/

> rm -r rpi-arm-raspbian-8.0-1.2.0

# retour à la racine
cd

# compilation de python2.7
solution venant de ce site https://stackoverflow.com/a/26597848

> wget http://www.python.org/ftp/python/2.7.5/Python-2.7.5.tar.bz2

> tar -xvjf Python-2.7.5.tar.bz2

> cd Python-2.7.5

> ./configure --prefix=/usr/local/python2.7 --with-threads --enable-shared

> make

> sudo make install altinstall

> sudo ln -s /usr/local/python2.7/lib/libpython2.7.so /usr/lib

> sudo ln -s /usr/local/python2.7/lib/libpython2.7.so.1.0 /usr/lib

> sudo ln -s /usr/local/python2.7/bin/python2.7 /usr/local/bin

> echo "alias python='/usr/local/python2.7/bin/python2.7'" >> ~/.bashrc

> source ~/.bashrc
> python -V    

# je reprends le cours normal de l'installation
> cd jarvis

> ./javis.sh
`

tous fonctionne correctement

**Comment by Oliv4945** [comment]
>mon probleme vient de la lib libpython2.7.so.1.0 manquante sur armbian

Dans ta première étape tu utilises Python3 (`apt-get install ... python3-pyaudio ...`), du coup pourquoi ne pas utiliser python3 pour tout ?

**Comment by davi-domo** [comment]
bonjour,

comme je vous l'ai dit je suis un bidouilleur mais tenace
au démarrage de jarvis j'avais l’erreur de lib inexistante libpython2.7.so.1.0 voila pourquoi je suis parti sur la piste après de python 2.7
comme je débutes avec python je ne suis pas encore très copain avec
je vais essayer tout en python 3 des que j'a un peut de temps

**Comment by Oliv4945** [comment]
Bonjour

N'ayant pas de nouvelles je ferme pour l'instant, ne pas hésiter à rouvrir.
