### ISSUE TITLE
Il y a t-il une variable dans Jarvis qui me permette de savoir si il à fini de parler afin d’exécuter seulement une autre commande derrière ?

### ISSUE THREAD

**Issue by Jean-Bernard-Hallez** [alexylem/jarvis#477]
Bonjour Alex,une simple question...

Il y a t-il une variable dans Jarvis qui me permette de savoir si il à fini de parler afin d’exécuter seulement une autre commande derrière ?

(Je sais qu'il y la les hooks ca marche très bien, mais c'est pour l'intégrer dans un plugin)

Merci beaucoup... JB.

**Comment by alexylem** [comment]
Bonjour @Jean-Bernard-Hallez 
Depuis quelques-temps les plugins ont aussi leurs hooks. Mais je suis très surpris de voir que je n'ai pas poussé ces évolutions sur [le modèle de plugin](https://github.com/alexylem/jarvis-plugin).
En attendant, essaye de copier le dossier `hooks` de Jarvis à la racine de ton plugin. Enlève les `.default`.
Il suffit de les remplir comme les hooks de Jarvis, et ils se déclencheront au moment opportun.

**Comment by Jean-Bernard-Hallez** [comment]
Aie....j'ai bien fait un répertoire dans ma base de mon plugin, mais ca ne va pas.... il me le prend comme pour un plugin général.

j'ai mis ceci dans "stop_speaking" 
gpio write 2 0 
gpio write 0 0

contrab me lance toutes les 5 minutes ceci:
*/5       8-21    *       *       1-5       ~/jarvis/jarvis.sh -x "mesurepir"

Il ne se passe rien après cela, ca reste allumé... idem si je déplace ces lignes ailleurs dans les hooks

Ce que j'aurai souhaiter c'était lire une variable qui puise me dire si jarvis parle ou pas en live, pour que je puisse éteindre mes yeux que quand elle a vraiment fini de discuter...

**Comment by alexylem** [comment]
J'ai committé les hooks dans le template de plugin.
Pour rester sur le sujet des hooks, est-ce que tu peux mettre des echos dans tous les hooks de ton plugins et tester pour vérifier s'ils sont bien déclenchés au bon moment?

>Il ne se passe pas ce que je souhaite, ca ne reste pas allumé jusqu'a la fin de la conversation.

Tu veux dire qu'il est exécuté trop tôt? ou pas du tout?

>Il agit comme un plugin standard... c'est a dire qu'il agit à la place de tous les autres plugins, hors je souhaite qu'il fonctionne que pour ce plugin

Je ne comprends pas, tu peux clarifier/illustrer?

Dernier conseil, oublie ton histoire de variable. Tu ne vas quand même pas faire une boucle sur cette variable jusqu'à ce qu'elle change... les hooks sont la pour ça. Je préfère les corriger / améliorer plutôt que de t'amener sur cette piste...

Merci.

**Comment by alexylem** [comment]
Si je comprends bien tu ne veux pas déclencher cette commande à chaque fois qu'il finis de dire un truc, mais plutôt une fois qu'il a fini de dire ce que tu lui a demandé de dire dans un ordre de ton plugin?
Le mieux c'est que tu donne un exemple concret, stp 😄

**Comment by Jean-Bernard-Hallez** [comment]
Oui c'est exactement cela... je souhaite finir uniquement quand moi je l'ai décidé car il peut annoncer plein de trucs... actuellement mon détecteur PIR m'annonce à toute heure de la journée différents événements...
Par exemple:
au réveil il me dit: la météo, un événement, un proverbe, la saint du jour.... 

Le problème c'est qu'a la fin de ma fonction  je lui demande de fermer les yeux, mais il anticipe bien longtemps à l'avance. Je souhaitais donc que la variable qui détecte la fin de say me prévienne pour couper les yeux uniquement à ce moment là... Les Say sont dissociés et ne sont pas regroupés car par exemple, si il n'y a pas d’événement il ne me le dit pas, etc...

**Comment by alexylem** [comment]
Juste pour être sûr... tu te rappelles que les hooks ne sont pas déclenchés depuis l'API?

Si tu n'utilises pas l'API (donc pas les events), tu peux toujours essayer ça:
Tu défini une variable et la testes dans le hook `stop_speaking`

**commands**
```shell
NE FERME PAS LES YEUX==say "d'accord" && say "je ne fermerai pas les yeux"
FERME LES YEUX==say "d'accord" && my_var=true && say "je ferme les yeux"
```
**stop_speaking hook**
```shell
$my_var && commande_fermer_les_yeux && my_var=false
```

**Comment by Jean-Bernard-Hallez** [comment]
J'ai mis les echo dans mes hook ca fonctionne bien en  Troubleshooting mode, mais pas en mode jarvis -x rien n'apparait ni en keyboard je n 'ai pas de retour...
je vais tester la variable dans hook stop-speaking

**Comment by Jean-Bernard-Hallez** [comment]
J'ai trouvé ma solution... merci tu m'as bien aiguillé....
Je suis revenu sur le chemin des écoliers... et j'ai tout simplement fait ceci:
a la fin de ma fonction j'ai mis: 
jv_handle_order "LESYEUXOFF" 

et dans command:
LESYEUXOFF==gpio write 2 0; gpio write 0 0

**Comment by alexylem** [comment]
Tu aurais pu mettre directement le code à la fin de la fonction non?
En tout cas content pour toi que tu aies pu trouver ta solution.

Au fait tu as du voir quand j'ai écrit:
>Juste pour être sûr... tu te rappelles que les hooks ne sont pas déclenchés depuis l'API?

Donc c'est pour ca que ca ne marche pas avec le flag `-x`

**Comment by Jean-Bernard-Hallez** [comment]
Et recoucou... Hélas si je mets directement cela à la fin de la fonction c'est de-suite court-circuité !!!!
C'est à dire que les yeux se ferment avant qu'elle est finit de parler...
Au travers le say il attend que me say précédent soit fini...

A oui API et -X c'est identique.... il faudrait que je m'en souvienne...
