### ISSUE TITLE
Bonjour, comment faire une commande aplay que quand le say est fini...

### ISSUE THREAD

**Issue by Jean-Bernard-Hallez** [alexylem/jarvis#479]
Bonjour, comment faire une commande aplay que, quand le say est fini...
car les deux se mélangent et c'est la pagaille...

Avec mon Pir, je lance une commande de bruitage autour de R2D2 puis il faudrai qu'il parle...
Hors il fait tout en même temps...

jv_handle_order "fais R2D2"  
say "Bienvenue, ca fais X temps que je ne t'avais pas vu..."

Merci....

**Comment by alexylem** [comment]
Si tu fais d'abord le bruitage puis say, ca devrait fonctionner:
```
play "bruitage.wav"; say "Bienvenue, ca fais X temps que je ne t'avais pas vu..."
```

**Comment by Jean-Bernard-Hallez** [comment]
Et bien non ça se fusionne.... bizarre...

**Comment by alexylem** [comment]
Ok on va pas trop tergiverser la dessus, mais c'est aussi une des raisons pour lesquelles j'ai récemment complètement réécrit le code de la fonction `say`.
J'avais justement pas mal d'events qui font dire des trucs à Jarvis (l'heure, les emails, la météo, la domotique...) et lorsqu'ils sont déclenchés en même temps, Jarvis parlait par dessus lui même et j'en loupais les 3/4.
Je donc changé et l'ai re-développé sous forme de FIFO. Tout ce qui est dit par la fonction `say` est mis en file indienne dans une queue, et un process (`say.sh`) tourne en background et dit à voir haute ce qui est mis en la queue, ligne par ligne (First In First Out).
C'est pour ca d'ailleurs que maintenant Jarvis doit tourner pour que l'API fonctionne.
Ca a donc résolu le pb de parler en parallèle. Maintenant si 100 actions se déclenchent d'un coup, il dira les 100 les un après les autres.
Mais je ne peux pas deviner lorsque tu utilises les enceintes par d'autres moyens (`aplay`).
Le mieux serait que tu trouves un moyen de réarranger ton code pour n'utiliser say que lorsque que tu es sûr que le bruitage est terminé.

Attention il y a quand même une subtilité, si tu regardes le code de la fonction `say`:
```shell
if $jv_api; then # if using API, put in queue
    if jv_is_started; then
        echo "$1" > $jv_say_queue # put in queue (read by say.sh)
    else
        jv_error "ERROR: Jarvis is not running"
        jv_success "HELP: Start Jarvis using ./jarvis.sh -b"
    fi
else # if using Jarvis, speak synchronously
    jv_hook "start_speaking"
    $tts_engine'_TTS' "$1"
    jv_hook "stop_speaking"
fi
```
Tu verras que si Jarvis en utilisé en API il utilise la queue. Si Jarvis utilisé depuis l'application, il parle de manière synchrone.
Tout ceci a été implémenté & expliqué dans #440 .
