### ISSUE TITLE
question sur le Pulgin Jeedom

### ISSUE THREAD

**Issue by Propheet** [alexylem/jarvis#480]
### Description
je n'arrive pas a donner un ordre sur le jeedom
j'ai bien installer le plugin 

petite question : Quelle type d'ordre on peux demande un scenario,un bouton ou une commande type homebridge ?

merci pour tout je suis dessoler de vous redéranger 

voici une petite vidéo
http://asciinema.org/a/51m8nv9gmroz10uvkq19slzrn

------------ Config ------------
jv_version           17.03.12
jv_arch              armv7l
jv_os_name           raspbian
jv_os_version        8
language             fr_FR
play_hw              hw:1,0
rec_hw               hw:1,0
speaker              C-Media Electronics, Inc. Audio Adapter
microphone           C-Media Electronics, Inc. Audio Adapter
trigger_stt          snowboy
command_stt          bing
tts_engine           svox_pico
--------------------------------

DEBUG: program_startup hook
jarvis: Bonjour Paco
DEBUG: start_speaking hook
DEBUG: stop_speaking hook
User defined commands:
                        *AIDE*                  *BONJOUR*|*SALUT*
*COMMENT*APPELLE*       *MERCI*                 *AU REVOIR*|*BYE*
ANNULE*|TERMINE*        ENCORE*                 *TEST*
*VERSION*               *REPETE (*) ET (*)      *CA VA*
>*OUI*                  >*NON*
*QUI*EST*GABRIEL*                               >*OUI*
>*NON*
Commands from plugin jarvis-jeedom:
*

PLEASE SEARCH BEFORE existing tickets and in the docs
NB: for issues with plugins, please create in the corresponding repository

### Result
```shell
<paste here> content of the terminal after using Jarvis in troubleshooting mode
or attach a session recording using https://asciinema.org/
```

**Comment by wikijm** [comment]
Bonjour @Propheet,

Je t'invite à aller créer ton ticket sur le repo du plugin, à savoir https://github.com/alexylem/jarvis-jeedom/issues/new

Cela permet à son créateur de te répondre plus rapidement et de ne pas polluer la liste d'incidents Jarvis Core avec ceux des plugins ;-)

**Comment by alexylem** [comment]
Vu dans ton asciinema:
```shell
say "$(curl "http://$jv_pg_jd_ip:$jv_pg_jd_port/${jv_pg_jd_path}core/api/jeeA
pi.php?apikey=$jv_pg_jd_apikey&type=interact" --data-urlencode "query=$order")" 
curl: (6) Could not resolve host: <192.168.1.37>
```
On dirait que tu n'as pas mis le bon IP de Jeedom, ou qu'il n'est pas accessible depuis ton Jarvis.
