### ISSUE TITLE
Meilleur compréhension d'une ligne de code

### ISSUE THREAD

**Issue by Falcoriders** [alexylem/jarvis#481]
Bonjour à tous. Voila, je me suis lancé dans le projet depuis très peu de temps et ayant une idée assez précise de ce que je veux, je peine à avoir certains résultats. J'ai déjà posté ma question dans le fil de discussion, et j'ai obtenu une réponse d'Alex, j'aimerais juste en savoir un peu plus sur cette ligne de commande. Ci-après la copie du fil de discussion : 

Bla bla bla..."Ma question est, comment faire pour qu'un meme mot déclenche deux réponse différentes ? En effet, si je dis salut une premiere fois, j'aimerais qu'elle me reponde (oui, j'ai travesti Jarvis ;) ) "bonjour", et si je devais dire salut une deuxieme fois, qu'elle me dise au revoir. J'ai bien essayé de la maniere la plus logique avec un petit if else et un booleen, mais rien. Merci pour la réponse :)."

Réponse : ">si je devais dire salut une deuxième fois, qu'elle me dise au revoir
Avec une simple variable:

SALUT==if $deja_dit; then say "au revoir"; jv_exit; else say "bonjour"; deja_dit=true; fi"

Donc si je comprend bien, le "$" est un "non" n'est ce pas ?
Et qu'est ce que le "fi" ?

Merci

**Comment by alexylem** [comment]
@Falcoriders 
Oula... ok donc la programmation `bash` et toi ça fait 4 😄 

Je ne suis pas sûr si je dois te faire une formation complète de Bash. Le mieux c'est quand même d'aller te renseigner, il y a plein de sites pour s'initier.

Mais pour rapidement répondre à tes questions:
* $ c'est pour les noms de variables.
* `fi` c'est la fin de la condition `if` (c'est un `fi` à l'envers)

La elle est écrit en une ligne (on appelle ca un one-liner). Mais de manière plus visuelle ca donne:
```shell
if $deja_dit; then # si la variable $deja_dit est à true (par défaut c'est non car non définie)
  say "au revoir" # faire dire "au revoir" à Jarvis
  jv_exit # puis quitter Jarvis proprement (fonction interne de Jarvis)
else # sinon
  say "bonjour" # lui faire dire "bonjour"
  deja_dit=true # et définir la variable à true pour que la prochaine fois ca quitte...
fi # fin du if/then/else
``` 

Si t'as besoin de plus d'info, Google est ton meilleur ami 👍

**Comment by Falcoriders** [comment]
Oui, j'ai pas encore eu le temps de me plonger dans le bash :). J'ai compris plus tard que c'etait  pour les variables, et le fi pour le FinSi. Il me reste cependant un soucis, c'est pour initialiser ma variable à false...

**Comment by alexylem** [comment]
pas besoin comme je disais si elle n'est pas définie c'est considéré comme false.

**Comment by Falcoriders** [comment]
Okay, faut que je me replonge dans le code, si j'ai un soucis je reviendrais ici. Merci :)
