### ISSUE TITLE
Enter lirc command?

### ISSUE THREAD

**Issue by DJuanillo** [alexylem/jarvis#482]
Can you enter a command to jarvis, eg "irsend SEND_ONCE tv KEY_POWER" to turn on the TV?

**Comment by wikijm** [comment]
Hi @DJuanillo,

You are able to launch all commands that work on bash.
I invite you to take a look on [Plugins](http://domotiquefacile.fr/jarvis/plugins) to get some examples.

If this answers your question, please close the issue 😄

**Comment by DJuanillo** [comment]
Ok thank you very much, it's that I'm quite new to these subjects

**Comment by wikijm** [comment]
No problem, we are here to make it usable to everyone ;-)

**Comment by DJuanillo** [comment]
I'm sorry, but I've been reading the plugins theme but I'm too new to understand. I think I'll wait and see if anyone can get it, thank you.

**Comment by alexylem** [comment]
@DJuanillo as long as you are able to run this command by youself on the terminal (using whatever IR software you found on the internet), Jarvis can do it. Just create a new order in Commands menu and add this command line for corresponding pattern.

**Comment by DJuanillo** [comment]
Thank you very much, I did not think it was going to be so easy
