### ISSUE TITLE
The headers or library files could not be found for jpeg,   a required dependency when compiling Pillow from source.

### ISSUE THREAD

**Issue by Garawa** [alexylem/jarvis#483]
Bonjour,

Je n'arrive pas à lancer à partir d'un hook un script python.
Le problème vient d'un module que je veux créer un lecteur de musique. Une fois la musique lancé, je ne peux plus la couper et jarvis ne répond plus.
Sa me fait une erreur où il me signale que les haut-parleurs ne peuvent être utilisés.
Si vous avez une idée je suis preneur.

Bonne journée,
```

**Comment by alexylem** [comment]
- Assures toi que le script python est bien lancé en processus parallèle (avec un & à la fin) pour ne pas bloquer Jarvis
- Pour l'erreur sur les haut parleurs, une copie du terminal nous aiderait

**Comment by Garawa** [comment]
jarvis: Bonjour maitre
Traceback (most recent call last):
  File "/home/pi/jarvis/plugins/jarvis-face/gifduration.py", line 17, in <module>
    from PIL import Image, ImageSequence
ImportError: No module named PIL
play FAIL formats: can't open output file `default': snd_pcm_open error: Device or resource busy
ERROR: play command failed
HELP: Verify your speaker in Settings > Audio > Speaker
sleep: opérande manquant
Saisissez « sleep --help » pour plus d'informations.
Traceback (most recent call last):
  File "/home/pi/jarvis/plugins/jarvis-face/gifduration.py", line 17, in <module>
    from PIL import Image, ImageSequence
ImportError: No module named PIL
sleep: opérande manquant
Saisissez « sleep --help » pour plus d'informations.
pi@raspberrypi:~ $

voilà pour l'erreur

**Comment by Garawa** [comment]
Voici le script en question

#!/usr/bin/python3.4
# -*- coding: utf-8 -*-

import calendar
import time
import datetime
import os

import subprocess

musictest=os.popen('ps ax | grep -v grep | grep -v -i SCREEN | grep mpg123', 'r').read()

if musictest != '':
	os.system("screen -p 0 -S lecteur -X kill")
else:
	print("")

**Comment by alexylem** [comment]
Tu as 2 erreurs:
```shell
ImportError: No module named PIL
```
Bizarre ca aurait du l'installer avec le script d'installation de Jarvis-face (sauf si il était déjà installé avant la grosse mise à jour).
Essaye de faire Menu > Plugins > Installed > Face > Reinstall

Et
```
play FAIL formats: can't open output file `default': snd_pcm_open error: Device or resource busy
```
Est-ce que le son marche sur Jarvis sans ton script Python?
On dirait que ton script python utilise tes enceintes et donc c'est Jarvis qui plante en essayant de les utiliser en même temps.
Il faudrait que tu essayes de trouver un autre moyen de faire ton lecteur, ou alors de voir du côté de PulseAudio (sachant qu'il n'est pas encore compatible avec Jarvis), voir #200 .

**Comment by Garawa** [comment]
je vais voir pulseaudio et je vais désinstaller le face et reinstalle

**Comment by Garawa** [comment]
Bonjour,

J'ai toujours le probleme de:
ImportError: No module named PIL

Malgré la réinstallation.

**Comment by alexylem** [comment]
Lors de l'installation du plugin tu n'as pas eu d'erreur?
Tu es sur quelle archi / distribution?
Essaye manuellement:
```shell
sudo pip install pillow
```

**Comment by Garawa** [comment]
j'ai un raspberry pi2 avec raspbian

**Comment by alexylem** [comment]
I feel I am missing information, have you copied the full terminal?
Please copy from the `sudo pip install pillow` until the end.

**Comment by alexylem** [comment]
Désolé pour l'anglais, réflexe:
J'ai l'impression que je n'ai pas tout, tu peux copier le terminal en entier?
Depuis `sudo pip install pillow` jusqu'à la fin, merci!

**Comment by Garawa** [comment]
pi@raspberrypi:~ $ sudo pip install pillow
Collecting pillow
  Using cached Pillow-4.0.0.tar.gz
Requirement already satisfied: olefile in /usr/local/lib/python2.7/dist-packages (from pillow)
Building wheels for collected packages: pillow
  Running setup.py bdist_wheel for pillow ... error
  Complete output from command /usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-rS8Gs8/pillow/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /tmp/tmptaqCb5pip-wheel- --python-tag cp27:
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.linux-armv7l-2.7
  creating build/lib.linux-armv7l-2.7/PIL
  copying PIL/ImageTransform.py -> build/lib.linux-armv7l-2.7/PIL
  copying PIL/__init__.py -> build/lib.linux-armv7l-2.7/PIL
  copying PIL/ImageWin.py -> build/lib.linux-armv7l-2.7/PIL
  copying PIL/ImImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
  copying PIL/_binary.py -> build/lib.linux-armv7l-2.7/PIL
  copying PIL/TiffTags.py -> build/lib.linux-armv7l-2.7/PIL
  copying PIL/ImageDraw2.py -> build/lib.linux-armv7l-2.7/PIL
  copying PIL/IptcImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
  copying PIL/ImageGrab.py -> build/lib.linux-armv7l-2.7/PIL
  copying PIL/GifImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
  copying PIL/ImageColor.py -> build/lib.linux-armv7l-2.7/PIL
  copying PIL/JpegPresets.py -> build/lib.linux-armv7l-2.7/PIL
  copying PIL/FliImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
  copying PIL/ImageEnhance.py -> build/lib.linux-armv7l-2.7/PIL
  copying PIL/ImageOps.py -> build/lib.linux-armv7l-2.7/PIL
  copying PIL/ImagePath.py -> build/lib.linux-armv7l-2.7/PIL
  copying PIL/PyAccess.py -> build/lib.linux-armv7l-2.7/PIL
  copying PIL/DdsImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
  copying PIL/GimpPaletteFile.py -> build/lib.linux-armv7l-2.7/PIL
  copying PIL/SpiderImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
  copying PIL/EpsImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
  copying PIL/XpmImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
  copying PIL/GimpGradientFile.py -> build/lib.linux-armv7l-2.7/PIL
  copying PIL/TarIO.py -> build/lib.linux-armv7l-2.7/PIL
  copying PIL/MicImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
  copying PIL/ImagePalette.py -> build/lib.linux-armv7l-2.7/PIL
  copying PIL/GdImageFile.py -> build/lib.linux-armv7l-2.7/PIL
  copying PIL/Image.py -> build/lib.linux-armv7l-2.7/PIL
  copying PIL/JpegImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
  copying PIL/Hdf5StubImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
  copying PIL/SunImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
  copying PIL/PngImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
  copying PIL/ImageStat.py -> build/lib.linux-armv7l-2.7/PIL
  copying PIL/ImageSequence.py -> build/lib.linux-armv7l-2.7/PIL
  copying PIL/ImageMath.py -> build/lib.linux-armv7l-2.7/PIL
  copying PIL/CurImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
  copying PIL/ImageTk.py -> build/lib.linux-armv7l-2.7/PIL
  copying PIL/PdfImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
  copying PIL/ImageFilter.py -> build/lib.linux-armv7l-2.7/PIL
  copying PIL/WmfImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
  copying PIL/ContainerIO.py -> build/lib.linux-armv7l-2.7/PIL
  copying PIL/PcxImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
  copying PIL/MpegImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
  copying PIL/PalmImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
  copying PIL/DcxImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
  copying PIL/ImageQt.py -> build/lib.linux-armv7l-2.7/PIL
  copying PIL/TiffImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
  copying PIL/FtexImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
  copying PIL/BdfFontFile.py -> build/lib.linux-armv7l-2.7/PIL
  copying PIL/MpoImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
  copying PIL/IcnsImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
  copying PIL/FpxImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
  copying PIL/PsdImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
  copying PIL/WalImageFile.py -> build/lib.linux-armv7l-2.7/PIL
  copying PIL/GbrImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
  copying PIL/FitsStubImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
  copying PIL/ImageFile.py -> build/lib.linux-armv7l-2.7/PIL
  copying PIL/OleFileIO.py -> build/lib.linux-armv7l-2.7/PIL
  copying PIL/_tkinter_finder.py -> build/lib.linux-armv7l-2.7/PIL
  copying PIL/ImtImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
  copying PIL/ImageMorph.py -> build/lib.linux-armv7l-2.7/PIL
  copying PIL/PaletteFile.py -> build/lib.linux-armv7l-2.7/PIL
  copying PIL/features.py -> build/lib.linux-armv7l-2.7/PIL
  copying PIL/PpmImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
  copying PIL/ImageChops.py -> build/lib.linux-armv7l-2.7/PIL
  copying PIL/SgiImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
  copying PIL/ExifTags.py -> build/lib.linux-armv7l-2.7/PIL
  copying PIL/ImageShow.py -> build/lib.linux-armv7l-2.7/PIL
  copying PIL/GribStubImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
  copying PIL/PixarImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
  copying PIL/XbmImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
  copying PIL/Jpeg2KImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
  copying PIL/McIdasImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
  copying PIL/XVThumbImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
  copying PIL/BufrStubImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
  copying PIL/IcoImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
  copying PIL/WebPImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
  copying PIL/ImageFont.py -> build/lib.linux-armv7l-2.7/PIL
  copying PIL/FontFile.py -> build/lib.linux-armv7l-2.7/PIL
  copying PIL/ImageDraw.py -> build/lib.linux-armv7l-2.7/PIL
  copying PIL/TgaImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
  copying PIL/_util.py -> build/lib.linux-armv7l-2.7/PIL
  copying PIL/BmpImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
  copying PIL/PSDraw.py -> build/lib.linux-armv7l-2.7/PIL
  copying PIL/PcfFontFile.py -> build/lib.linux-armv7l-2.7/PIL
  copying PIL/MspImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
  copying PIL/ImageMode.py -> build/lib.linux-armv7l-2.7/PIL
  copying PIL/PcdImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
  copying PIL/ImageCms.py -> build/lib.linux-armv7l-2.7/PIL
  running egg_info
  writing requirements to Pillow.egg-info/requires.txt
  writing Pillow.egg-info/PKG-INFO
  writing top-level names to Pillow.egg-info/top_level.txt
  writing dependency_links to Pillow.egg-info/dependency_links.txt
  reading manifest file 'Pillow.egg-info/SOURCES.txt'
  reading manifest template 'MANIFEST.in'
  warning: no files found matching '*.sh'
  no previously-included directories found matching 'docs/_static'
  warning: no previously-included files found matching '.coveragerc'
  warning: no previously-included files found matching '.editorconfig'
  warning: no previously-included files found matching '.landscape.yaml'
  warning: no previously-included files found matching 'appveyor.yml'
  warning: no previously-included files found matching 'build_children.sh'
  warning: no previously-included files found matching 'tox.ini'
  warning: no previously-included files matching '.git*' found anywhere in distribution
  warning: no previously-included files matching '*.pyc' found anywhere in distribution
  warning: no previously-included files matching '*.so' found anywhere in distribution
  writing manifest file 'Pillow.egg-info/SOURCES.txt'
  running build_ext


  The headers or library files could not be found for jpeg,
  a required dependency when compiling Pillow from source.

  Please see the install instructions at:
     http://pillow.readthedocs.io/en/latest/installation.html

  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/tmp/pip-build-rS8Gs8/pillow/setup.py", line 791, in <module>
      raise RequiredDependencyException(msg)
  __main__.RequiredDependencyException:

  The headers or library files could not be found for jpeg,
  a required dependency when compiling Pillow from source.

  Please see the install instructions at:
     http://pillow.readthedocs.io/en/latest/installation.html



  ----------------------------------------
  Failed building wheel for pillow
  Running setup.py clean for pillow
Failed to build pillow
Installing collected packages: pillow
  Running setup.py install for pillow ... error
    Complete output from command /usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-rS8Gs8/pillow/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-ePaZs9-record/install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    running build_py
    creating build
    creating build/lib.linux-armv7l-2.7
    creating build/lib.linux-armv7l-2.7/PIL
    copying PIL/ImageTransform.py -> build/lib.linux-armv7l-2.7/PIL
    copying PIL/__init__.py -> build/lib.linux-armv7l-2.7/PIL
    copying PIL/ImageWin.py -> build/lib.linux-armv7l-2.7/PIL
    copying PIL/ImImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
    copying PIL/_binary.py -> build/lib.linux-armv7l-2.7/PIL
    copying PIL/TiffTags.py -> build/lib.linux-armv7l-2.7/PIL
    copying PIL/ImageDraw2.py -> build/lib.linux-armv7l-2.7/PIL
    copying PIL/IptcImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
    copying PIL/ImageGrab.py -> build/lib.linux-armv7l-2.7/PIL
    copying PIL/GifImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
    copying PIL/ImageColor.py -> build/lib.linux-armv7l-2.7/PIL
    copying PIL/JpegPresets.py -> build/lib.linux-armv7l-2.7/PIL
    copying PIL/FliImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
    copying PIL/ImageEnhance.py -> build/lib.linux-armv7l-2.7/PIL
    copying PIL/ImageOps.py -> build/lib.linux-armv7l-2.7/PIL
    copying PIL/ImagePath.py -> build/lib.linux-armv7l-2.7/PIL
    copying PIL/PyAccess.py -> build/lib.linux-armv7l-2.7/PIL
    copying PIL/DdsImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
    copying PIL/GimpPaletteFile.py -> build/lib.linux-armv7l-2.7/PIL
    copying PIL/SpiderImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
    copying PIL/EpsImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
    copying PIL/XpmImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
    copying PIL/GimpGradientFile.py -> build/lib.linux-armv7l-2.7/PIL
    copying PIL/TarIO.py -> build/lib.linux-armv7l-2.7/PIL
    copying PIL/MicImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
    copying PIL/ImagePalette.py -> build/lib.linux-armv7l-2.7/PIL
    copying PIL/GdImageFile.py -> build/lib.linux-armv7l-2.7/PIL
    copying PIL/Image.py -> build/lib.linux-armv7l-2.7/PIL
    copying PIL/JpegImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
    copying PIL/Hdf5StubImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
    copying PIL/SunImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
    copying PIL/PngImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
    copying PIL/ImageStat.py -> build/lib.linux-armv7l-2.7/PIL
    copying PIL/ImageSequence.py -> build/lib.linux-armv7l-2.7/PIL
    copying PIL/ImageMath.py -> build/lib.linux-armv7l-2.7/PIL
    copying PIL/CurImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
    copying PIL/ImageTk.py -> build/lib.linux-armv7l-2.7/PIL
    copying PIL/PdfImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
    copying PIL/ImageFilter.py -> build/lib.linux-armv7l-2.7/PIL
    copying PIL/WmfImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
    copying PIL/ContainerIO.py -> build/lib.linux-armv7l-2.7/PIL
    copying PIL/PcxImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
    copying PIL/MpegImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
    copying PIL/PalmImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
    copying PIL/DcxImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
    copying PIL/ImageQt.py -> build/lib.linux-armv7l-2.7/PIL
    copying PIL/TiffImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
    copying PIL/FtexImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
    copying PIL/BdfFontFile.py -> build/lib.linux-armv7l-2.7/PIL
    copying PIL/MpoImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
    copying PIL/IcnsImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
    copying PIL/FpxImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
    copying PIL/PsdImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
    copying PIL/WalImageFile.py -> build/lib.linux-armv7l-2.7/PIL
    copying PIL/GbrImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
    copying PIL/FitsStubImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
    copying PIL/ImageFile.py -> build/lib.linux-armv7l-2.7/PIL
    copying PIL/OleFileIO.py -> build/lib.linux-armv7l-2.7/PIL
    copying PIL/_tkinter_finder.py -> build/lib.linux-armv7l-2.7/PIL
    copying PIL/ImtImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
    copying PIL/ImageMorph.py -> build/lib.linux-armv7l-2.7/PIL
    copying PIL/PaletteFile.py -> build/lib.linux-armv7l-2.7/PIL
    copying PIL/features.py -> build/lib.linux-armv7l-2.7/PIL
    copying PIL/PpmImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
    copying PIL/ImageChops.py -> build/lib.linux-armv7l-2.7/PIL
    copying PIL/SgiImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
    copying PIL/ExifTags.py -> build/lib.linux-armv7l-2.7/PIL
    copying PIL/ImageShow.py -> build/lib.linux-armv7l-2.7/PIL
    copying PIL/GribStubImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
    copying PIL/PixarImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
    copying PIL/XbmImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
    copying PIL/Jpeg2KImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
    copying PIL/McIdasImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
    copying PIL/XVThumbImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
    copying PIL/BufrStubImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
    copying PIL/IcoImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
    copying PIL/WebPImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
    copying PIL/ImageFont.py -> build/lib.linux-armv7l-2.7/PIL
    copying PIL/FontFile.py -> build/lib.linux-armv7l-2.7/PIL
    copying PIL/ImageDraw.py -> build/lib.linux-armv7l-2.7/PIL
    copying PIL/TgaImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
    copying PIL/_util.py -> build/lib.linux-armv7l-2.7/PIL
    copying PIL/BmpImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
    copying PIL/PSDraw.py -> build/lib.linux-armv7l-2.7/PIL
    copying PIL/PcfFontFile.py -> build/lib.linux-armv7l-2.7/PIL
    copying PIL/MspImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
    copying PIL/ImageMode.py -> build/lib.linux-armv7l-2.7/PIL
    copying PIL/PcdImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
    copying PIL/ImageCms.py -> build/lib.linux-armv7l-2.7/PIL
    running egg_info
    writing requirements to Pillow.egg-info/requires.txt
    writing Pillow.egg-info/PKG-INFO
    writing top-level names to Pillow.egg-info/top_level.txt
    writing dependency_links to Pillow.egg-info/dependency_links.txt
    reading manifest file 'Pillow.egg-info/SOURCES.txt'
    reading manifest template 'MANIFEST.in'
    warning: no files found matching '*.sh'
    no previously-included directories found matching 'docs/_static'
    warning: no previously-included files found matching '.coveragerc'
    warning: no previously-included files found matching '.editorconfig'
    warning: no previously-included files found matching '.landscape.yaml'
    warning: no previously-included files found matching 'appveyor.yml'
    warning: no previously-included files found matching 'build_children.sh'
    warning: no previously-included files found matching 'tox.ini'
    warning: no previously-included files matching '.git*' found anywhere in distribution
    warning: no previously-included files matching '*.pyc' found anywhere in distribution
    warning: no previously-included files matching '*.so' found anywhere in distribution
    writing manifest file 'Pillow.egg-info/SOURCES.txt'
    running build_ext


    The headers or library files could not be found for jpeg,
    a required dependency when compiling Pillow from source.

    Please see the install instructions at:
       http://pillow.readthedocs.io/en/latest/installation.html

    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-rS8Gs8/pillow/setup.py", line 791, in <module>
        raise RequiredDependencyException(msg)
    __main__.RequiredDependencyException:

    The headers or library files could not be found for jpeg,
    a required dependency when compiling Pillow from source.

    Please see the install instructions at:
       http://pillow.readthedocs.io/en/latest/installation.html



    ----------------------------------------
Command "/usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-rS8Gs8/pillow/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-ePaZs9-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-rS8Gs8/pillow/

**Comment by alexylem** [comment]
>j'ai un raspberry pi2 avec raspbian jessie lite

Tu sais qu'il faut avoir l'environnement graphique pour utiliser Jarvis-Face? Tu as installé Pixel manuellement?

Sinon merci pour le Log, on dirait que ton problème vient de:
```
The headers or library files could not be found for jpeg,
  a required dependency when compiling Pillow from source.
```

En cherchant un peu sur les forum, j'ai vu ça:
```shell
sudo apt-get update
sudo apt-get install libjpeg-dev
sudo pip install pillow
```
En espérant que ca t'aide

**Comment by Garawa** [comment]
j'ai installé pixel manuellement

**Comment by alexylem** [comment]
Ok et pour pillow ca donne quoi avec ce que je t'ai donné?

**Comment by Garawa** [comment]
plus d'erreur

**Comment by alexylem** [comment]
J'ai modifié le script d'install pour rajouter cette dépendance.

**Comment by Garawa** [comment]
J'ai trouvé un ptit truc pour mixer plusieurs sons et palier aux problèmes des haut parleurs.
https://www.rezine.org/documentation/auto-hebergement/multimedia/son/

je testerai sa un peu plus tard

**Comment by wikijm** [comment]
@Garawa Je clôture le temps que tu teste la solution proposée. N'hésites pas nous faire un retour ou à ré-ouvrir l'issue si le problème persiste :-)

**Comment by sairohithA007** [comment]
I have faced the similar issue on mac OS High Sierra. Then I followed the solution from this [link](https://stackoverflow.com/questions/34631806/fail-during-installation-of-pillow-python-module-in-linux/34631976).
