### ISSUE TITLE
Jarvis répète la dernière syllabe 

### ISSUE THREAD

**Issue by jec44** [alexylem/jarvis#489]
Bonjour,
Lorsque je lance Jarvis, tout se passe bien, mais lorsqu'elle me parle (on dit il ou elle ??), elle répète toujours la dernière syllabe du mot, comme une réminiscence des dernières lettres . Avez vous le même problème, comment le résoudre ? J'utilise un jabra 510

merci de votre aide  

```

**Comment by wikijm** [comment]
Bonjour @jec44,

J'utilise également un JABRA 510, et devrait pouvoir faire un test ce soir.

Il nous faut le plus de détails possible concernant ton contexte d'utilisation afin de tenter de reproduire ton point de blocage.
Peux-tu nous donner le résultat du troubleshooting mode (partagé sur [ASCIInema](https://asciinema.org/) ou à défaut le texte du rendu de la console) ?

**Comment by alexylem** [comment]
Je crois qu'il faut un config spécifique pour les JABRA, voir #245 #319 #65

**Comment by Jean-Bernard-Hallez** [comment]
Je confirme j'avais le même problème... fais ca:
Bonjour après avoir recherché aussi j'ai fait ce test:
aplay -Dsysdefault -c 2 -f cd test.wav --> Ca m'a permis de voir en effet que le son sortait à la vitesse normal j'ai donc modifié mon fichier:
sudo pico ~/.asoundrc
pcm.!sysdefault {
type asym
playback.pcm {
type hw
rate 48000
slave.pcm "hw:0,0"
}
capture.pcm {
type plug
slave.pcm "hw:1,0"
}
}

Et ca a marché desuite....  ;-)

**Comment by wikijm** [comment]
@jec44 Je clôture le temps que tu teste les solutions proposées. N'hésites pas nous faire un retour ou à ré-ouvrir l'issue si le problème persiste :-)
