### ISSUE TITLE
bluetooth émetteur-récepteur

### ISSUE THREAD

**Issue by DebBibiPi** [alexylem/jarvis#492]
bonjour,
je souhaite savoir s'il est possible d' utiliser JARVIS via une enceinte bluetooth munie d' un micro integré.
possédant, pour ce projet un Raspberry pi2, il me faut donc un dongle bluetooth.
je souhaite savoir si un dongle bluetooth émetteur-récepteur peut faire l' affaire, Jarvis le gère t' il ?
merci par avance pour vos retours.
DebbibiPi

**Comment by wikijm** [comment]
@DebBibiPi Extrait de la page [Pré-requis](http://domotiquefacile.fr/jarvis/content/prerequisites) :

> Sur Raspberry Pi vous devez utiliser un Microphone USB ou un Webcam USB avec micro intégré. La plupart des Micro USB fonctionnent sans problème. Le support du bluetooth est expérimental et est [discuté ici](https://github.com/alexylem/jarvis/issues/110).

**Comment by DebBibiPi** [comment]
je vais faire des essais avec différents accessoires et reviendrai poster les résultats, positifs ou non.

**Comment by alexylem** [comment]
Voir #287
