### ISSUE TITLE
Jarvis AI uniquement en anglais

### ISSUE THREAD

**Issue by RobyBioloid** [alexylem/jarvis#493]
Bonjour,

Je viens d'installer Jarvis AI et je constate qu'il ne parle pas le français.

Il n'y a pas beaucoup d'information dans le readme du plugin. Il n'est pas précisé ou aller pour se procurer la clé "api key". Pour ma part je me suis connecté sur ce site afin d'avoir une clef d'activation : https://www.cleverbot.com/api/.

J'ai juste installé le plugin est entré la clé dans le fichier config. Je pense pas qu'il y ait autre chose à faire. :s

**Comment by alexylem** [comment]
Pour toute question ou problème lié à un plugin Jarvis, merci de créer un ticket sur le repository correspondant. Ainsi son auteur en sera informé et pourra vous aider.

**Ok, alors c'est où?**
* Depuis Jarvis, allez dans Plugins > Installed > The Plugin > Report an issue
* Depuis le site, allez sur la page du plugin et cliquez sur le lien "Open a ticket"

Autrement dit, je ne fait pas de support pour les plugins tiers.
Merci de votre compréhension.

**Comment by wikijm** [comment]
@RobyBioloid L'auteur vient d'activer la fonctionnalité "Issues" sur le dépôt du plugin, profites-en pour lui créer une issue ;-)
