### ISSUE TITLE
Speak two language+Face recognition

### ISSUE THREAD

**Issue by DomoAI** [alexylem/jarvis#495]
Hi Everyone,

I'm french and my wife Dutch ( Pays-bas ) I was wonder if it will be possible to have two instance of Jarvis on the same hardware that will use the same micro and speaker. That way I could get Jarvis in French and one in Dutch. That will be awesome. I did not try anything yet, actually I'm just starting with Jarvis.
Also I saw some post regarding Face recognition, I'm very interesting to it. Alexy do you think a plugins will be available soon?

This is not really an issue more general request sorry if that is not at the right place.

DomoAI

**Comment by wikijm** [comment]
I guess you are on the right place, regarding to the fact that your need must be related to a Jarvis Core adaptation request.

Related to:
 - Multi-user usage => https://github.com/alexylem/jarvis/issues/190
 - Detection and facial recognition => https://github.com/alexylem/jarvis/issues/56

I invite you to add your request/question/concern directly on these issues.

**Comment by DomoAI** [comment]
Thank you. I will close this issue.

**Comment by wikijm** [comment]
Thanks for the good sense to close this issue and swap to the others.  :thumbsup:
It's hard to manage and keep conversations alive with too much issues object.  :pensive:

**Comment by alexylem** [comment]
@DomoAI please also request Dutch as new language in a separate ticket. I think this one can be done quite easily.
