### ISSUE TITLE
mpg123.c access error

### ISSUE THREAD

**Issue by Lusitanos67** [alexylem/jarvis#497]
Bonjour,

Quelqu'un a t-il déjà eu cette erreur avec le plugin wheather ? 
`[mpg123.c:634] error: Cannot open ciel_plutot_degage_maximales__18: File access error. (code 22)`

Pourtant le répertoire ou il dépose les fichiers mp3 est bien accessible en écriture puis qu'il y a plein d'autres fichiers correspond à d'autres phrases, mais certaines ne fonctionnent pas.

**Comment by alexylem** [comment]
Le mode troubleshooting aurait été utile pour vérifier quel fichier il essaye de lire exactement...
Il se pourrait aussi que ton `/dev/shm` soit full?
```
$> df -h
```

**Comment by wikijm** [comment]
Bonjour @Lusitanos67,

Pour que la communauté puisse efficacement fournir de l'aide, il faut respecter les règles suivantes :
- Fournir les éléments demandés lors de la création de l'issue (résultat du troubleshooting mode, enregistrement ASCIInema)
- Créer une issue sur le repo correspondant au plugin si le problème est lié à un plugin

En conséquence, je t'invite à créer une nouvelle issue en suivant le lien suivant : https://github.com/alexylem/jarvis-weather-wunderground-fr/issues

Il n'y a aucune méchanceté dans mes propos, je m'assure simplement que l'auteur de Jarvis puisse utiliser son temps libre au développement et à l'évolution du projet, plutôt que de le passer à gérer des incidents qui ne concerne pas Jarvis directement.

**Comment by Lusitanos67** [comment]
Bonjour,

J'ai effectivement hésité à poster sur le plugin en question, vu mes soucis depuis les dernières mise à jour jarvis.
Pas de soucis
