### ISSUE TITLE
Nouveau moteur de reconnaissance de Hotword: Sopare

### ISSUE THREAD

**Issue by Smanar** [alexylem/jarvis#50]
Bon j'ai pas teste non plus vu que c'est inutilisable pour moi le code est en python.
https://github.com/bishoph/sopare

**Comment by alexylem** [comment]
Pas encore testé, mais principaux avantages que je vois:
* Hors ligne (comme PocketSphinx et Snowboy)
* Concu pour Raspberry Pi (comme Snowboy)
* Besoin de trainer les mots clés à détecter (comme Snowboy, mais hors ligne 😄 )

Je ne vais pas implémenter tous les STT et TTS qui existent mais je me concentrerai sur ceux qui sont les plus simple à utiliser et qui donnent les meilleurs résultats afin d'offrir un choix de qualité aux utilisateurs de Jarvis.

Donc à tester avant de décider si j'implémente ou pas 😉

**Comment by Smanar** [comment]
Par contre d'apres ce que j'ai compris c'est plus un Hotword detector qu'un STT engine.
Tu peux y programmer quelques mots, mais il ne lira jamais une phrase complete.

**Comment by wikijm** [comment]
Pas d'avancée sur le sujet pour le moment.

@alexylem Je clôture cette issue, mais l'ai intégré au projet [Jarvis Core](https://github.com/alexylem/jarvis/projects/1) histoire que tu en garde une trace.
