### ISSUE TITLE
Réponse multiple Jarvis

### ISSUE THREAD

**Issue by Lusitanos67** [alexylem/jarvis#500]
Je voulais savoir s'il était possible de définir une liste de réponses par défauts, par exemple après la détection du hotword, avoir soit oui/je t'écoute/c'est moi/ etc... 
Ça rendrait Jarvis plus convivial ?

**Comment by alexylem** [comment]
Aujourd'hui la réponse au hotword de Jarvis peut-être définie dans Settings / Phrases.
Si je comprends bien, tu aimerais qu'il y ait la possibilité d'en définir plusieurs, donc Jarvis en dira une aléatoirement?

**Comment by Lusitanos67** [comment]
Oui c'est ça

**Comment by alexylem** [comment]
Bon j'ai plusieurs idées dans la tête qui tournent autour de ça:

**Approche simple**
Au lieu d'une boite de dialog "input", ouvrir un fichier (comme les hooks), une ligne par phrase possible.

**Approche plus compliquée mais plus flexible/puissante**
Utiliser les `hooks` au lieu des `phrases`
Pour ton exemple, dans `entering_cmd` on peut y mettre par défaut:
```
say "Oui?"
```
que tu pourrais facilement remplacer par:
```shell
answers=("Oui?" "C'est moi" "Je t'écoute" "Quoi encore?")
say "${answers[$RANDOM % ${#answers[@]} ]}"
```
Et on peut aussi utiliser `program_startup` pour:
```shell
say "Bonjour"
```
Et il faudrait donc rajouter les hooks suivants:
* `unknown_order`
* `command_failed`

Avantages:
* Tu peux déjà le faire (pour le welcome et réponse au hotword - à tester)
* On pourrait utiliser le hook `program_exit` pour lui faire dire "Au revoir"
* Jarvis-face #366 pourrait utiliser ces 2 nouveaux hooks pour afficher une émotion adéquate.

Inconvénients:
* Moins facile à comprendre/utiliser pour les débutants

**Traductions des phrases**
Ca fait un petit moment que je me dis qu'il faut que je traduise ces phrases. Par défaut elles sont en anglais et ca doit être un peu déroutant pour ceux qui installent Jarvis. Ca je peux le faire quelque-soit la solution choisie.

**Comment by Lusitanos67** [comment]
Je teste la méthode complexe, elle me va :)
Comme tu dis, pour les débutants, la compréhension risque de se faire difficilement, il faudrait rajouter de l'aide sur la partie "hook", ou repenser l'accès paramétrage  de cette partie (ou paramétrage accessible en mode soit "simple" avec un assistant,  ou en mode "expert").

**Comment by Lusitanos67** [comment]
Ca fonctionne nickel
