### ISSUE TITLE
Variable dejaVu

### ISSUE THREAD

**Issue by RobyBioloid** [alexylem/jarvis#504]
### Description

Bonjour,

Est il possible de créer une variable pour informer si on a déjà communiqué avec Jarvis aujourd'hui ?

On pourrai ainsi consulter cette variable afin de réagir différemment avec l'utilisateur.

Exemple avec le plugin Éphéméride' si pas déjà vu dire la fête du jour sinon ne rien dire.

**Comment by alexylem** [comment]
Rien ne t'empêche d'utiliser un hook pour ca.
Par exemple `entering_cmd`:
```shell
already_discussed=true
```
Puis dans tes commandes:
```shell
*BONJOUR*==$already_discussed && say "Re bonjour" || say "Bonjour"
```
A affiner pour utiliser comme valeur la date du jour pour ajuster la fréquence.
Possibilité de passer par un fichier au cas ou Jarvis est arrêté entre temps.

**Comment by RobyBioloid** [comment]
Je regarderai dans cette direction :)

**Comment by RobyBioloid** [comment]
Peux tu me donner un exemple avec la date comme valeur?

je ne connai pas du tout la programmation shell

**Comment by alexylem** [comment]
Je ne donne pas de formation shell. Ton meilleure ami ci-dessous:
https://www.google.fr/#q=shell+get+date
