### ISSUE TITLE
Core Création de profil matériel dans l'assistant de configuration

### ISSUE THREAD

**Issue by wikijm** [alexylem/jarvis#505]
Bonjour,

Afin d'éviter au maximum les erreurs liées à la configuration du matériel audio, serait-il possible de proposer une configuration globale, comprenant :
- Sélection micro et/ou enceinte
- Définition de la sensibilité
- Modification du fichier ~/.asoundrc
- ...

On pourrait se baser sur les retours faits par la communauté, et se focaliser en priorité sur le matériel le plus utilisé (PS Eye, JABRA 410/510) et reconnu comme ayant de bons résultats.

**Comment by alexylem** [comment]
Je ne suis pas sûr de comprendre exactement ce qu'il faudrait changer par rapport à aujourd'hui.
Il y a déjà un assistant de configuration (step-by-step wizard) qui fait:
* détection / sélection / test micro/enteintes
* génération du `~/.asoundrc`
* définition automatique du gain et des seuils de déclenchements

Pensais-tu plus particulièrement à la génération du `~/.asoundrc` spécifique pour les JABRA ?

**Comment by wikijm** [comment]
Oui, un `~/.asoundrc` spécifique pour le JABRA, voire d'autres marques/modèles si nécessaire.

**Comment by wikijm** [comment]
Après plusieurs essais, je me rend compte que ton assistant de configuration couvre à la fois le matériel ainsi que l'ambiance sonore propre à chacun.

Besoin couvert => Clôture de l'issue.
Merci @alexylem 😃
