### ISSUE TITLE
Access denied due to invalid subscription key. Make sure to provide a valid key for an active subscription

### ISSUE THREAD

**Issue by DavidFromRouen** [alexylem/jarvis#506]
Bonjour,

Depuis 2 jours maintenant que j'essaie de me débrouiller seul, je ne trouve pas.
J'ai effacé ma SD, réinstallé au moins 3 fois.. etc... utilisé Bing puis Snowboy ...
Bref, je sèche.

Mon wakeword est bien détecté, mais ensuite plus rien, j'ai essayé les mots clés existants, comme "test" ou "version" ou "bonjour" etc...    voici une capture 

pi@raspberrypi:~/jarvis $ ./jarvis.sh

------------ Config ------------
jv_branch            master
jv_version           17.03.26
jv_arch              armv7l
jv_os_name           raspbian
jv_os_version        8
language             fr_FR
play_hw              hw:0,1
rec_hw               hw:1,0
speaker              ALSA
microphone           C-Media Electronics, Inc. CM108 Audio Controller
recorder             sox
trigger_stt          snowboy
command_stt          snowboy
tts_engine           svox_pico
--------------------------------

DEBUG: program_startup hook
Jarvis: Bonjour David
DEBUG: start_speaking hook
DEBUG: stop_speaking hook
User defined commands:
*AIDE*                  *BONJOUR*|*SALUT*       *COMMENT*APPELLE*
*MERCI*                 *AU REVOIR*|*BYE*       ANNULE*|TERMINE*
ENCORE*                 *TEST*                  *VERSION*
*REPETE (*) ET (*)      *CA VA*                 >*OUI*
>*NON*|*PAS*
Jarvis: Waiting to hear 'Jarvis'
David: (listening...)
DEBUG: models=jarvis
Cannot connect to server socket err = No such file or directory
Cannot connect to server request channel
jack server is not running or cannot be started
INFO:snowboy:Ticks: [2, 20, 5, -1]
INFO:snowboy:Keyword 1 detected at time: 2017-03-27 10:44:31
INFO:snowboy:Ticks status: 2 4 4 1
DEBUG: modelid=0
Jarvis
DEBUG: entering_cmd hook
David: (listening...)
DEBUG: models=alexa
Cannot connect to server socket err = No such file or directory
Cannot connect to server request channel
jack server is not running or cannot be started
INFO:snowboy:Ticks: [2, 20, 5, -1]
DEBUG: timeout, end of conversation
DEBUG: exiting_cmd hook
Jarvis: Waiting to hear 'Jarvis'
David: (listening...)
DEBUG: models=jarvis
Cannot connect to server socket err = No such file or directory
Cannot connect to server request channel
jack server is not running or cannot be started
INFO:snowboy:Ticks: [2, 20, 5, -1]

**Comment by wikijm** [comment]
Bonjour @DavidFromRouen,

As-tu exactement les mêmes erreurs avec Bing ?
Je t'invite à nous "filmer" ce que tu fais à l'aide de [ASCIInema](https://asciinema.org/) avec Bing.

Même si disponible car pouvant fonctionner hors-ligne, il n'est franchement pas conseillé d'utiliser SnowBoy pour le speech-to-text (transcription de la voix en texte).

**Comment by DavidFromRouen** [comment]
Ha ok, Merci pour ta réponse rapide. Je vais faire ça, mais de mémoire j'ai la même erreur avec Bing.

**Comment by wikijm** [comment]
Autre astuce pour débuter :

Avant de t'aventurer dans l'utilisation de ta voix pour piloter, tu as la possibilité de lancer Jarvis en mode keyboard :
- Avec troubleshooting : `./jarvis/jarvis.sh -kv`
- Sans troubleshooting : `./jarvis/jarvis.sh -k`

Ainsi, tu peux voir plus rapidement si ton installation est fonctionnelle, en écartant matériel audio et paramétrage de sensibilité de ton micro.

**Comment by DavidFromRouen** [comment]
J'ai fais rapidement un test avec Bing, et il me dit que ma clé API n'est pas bonne...

Jarvis: Waiting to hear 'Jarvis'
David: Jarvis
David: ERROR: Access denied due to invalid subscription key. Make sure to provide a valid key for an active subscription.
(timeout)
Jarvis: Waiting to hear 'Jarvis'
David: Jarvis
David: ERROR: Access denied due to invalid subscription key. Make sure to provide a valid key for an active subscription.
(timeout)
Jarvis: Waiting to hear 'Jarvis'
David:


J'ai pourtant vérifié et utilisé la 2e clef aussi mais sans succès...

**Comment by DavidFromRouen** [comment]
Wikijm j'ai fais avec Troubleshooting et clavier, tout fonctionne au poil

DEBUG: program_startup hook
Jarvis: Bonjour David
DEBUG: start_speaking hook
DEBUG: stop_speaking hook
User defined commands:
*AIDE*                  *BONJOUR*|*SALUT*       *COMMENT*APPELLE*
*MERCI*                 *AU REVOIR*|*BYE*       ANNULE*|TERMINE*
ENCORE*                 *TEST*                  *VERSION*
*REPETE (*) ET (*)      *CA VA*                 >*OUI*
>*NON*|*PAS*
David: merci
$> say "De rien"
Jarvis: De rien
DEBUG: start_speaking hook
DEBUG: stop_speaking hook
David: aide
$> jv_display_commands
User defined commands:
*AIDE*                  *BONJOUR*|*SALUT*       *COMMENT*APPELLE*
*MERCI*                 *AU REVOIR*|*BYE*       ANNULE*|TERMINE*
ENCORE*                 *TEST*                  *VERSION*
*REPETE (*) ET (*)      *CA VA*                 >*OUI*
>*NON*|*PAS*
David: test
$> say "Ca fonctionne!"
Jarvis: Ca fonctionne!
DEBUG: start_speaking hook
DEBUG: stop_speaking hook
David: version
$> say "Je suis en version $jv_version"
Jarvis: Je suis en version 17.03.26
DEBUG: start_speaking hook
DEBUG: stop_speaking hook
David: ca va
$> say "Très bien et toi ça va?"
Jarvis: Très bien et toi ça va?
DEBUG: start_speaking hook
DEBUG: stop_speaking hook
*OUI*                   *NON*|*PAS*

**Comment by wikijm** [comment]
Ta clé Bing fait-elle bien 32 caractères ?

**Comment by DavidFromRouen** [comment]
Oui j'ai bien mes 32 caractères.  ;-)

**Comment by wikijm** [comment]
Je peux tester ta clé si tu le souhaites.
Je suis joignable sur twitter en suivant l'adresse suivante : https://twitter.com/WikiJM
Fais un message privé hein 😜

**Comment by DavidFromRouen** [comment]
Désolé je n'ai pas Twitter. Y'a pas moyen par GitHub ?

**Comment by DavidFromRouen** [comment]
pas grave, je peux la mettre ici, je ferai un regenerate après, non ?

**Comment by wikijm** [comment]
Régénérer ou m'envoyer un mail à l'adresse kswp9u4yp632bkvy@hmamail.com (valable 6 jours).

**Comment by wikijm** [comment]
Regénère-la, j'ai aussi une erreur. Attention aux espaces avant et après.

**Comment by DavidFromRouen** [comment]
J'appuie sur le bouton "COPY" en bout de ligne, donc pas de risque d'espace. J'en ai régénéré une.

**Comment by wikijm** [comment]
La 2e fonctionne.
Je ne pourrais pas t'aider de nouveau avant ce soir.

N'hésites pas à renseigner ton avancée dans ce ticket en attendant.

**Comment by DavidFromRouen** [comment]
Merci !     ;-)

**Comment by DavidFromRouen** [comment]
C'est OK ! It Works !!   ^^
