### ISSUE TITLE
WAVE: RIFF header not found

### ISSUE THREAD

**Issue by Amonbofils** [alexylem/jarvis#508]
### Description

Bonjour,

J'espere que je ne suis pas en doublon, mais je n'ai pas réussi a trouver de réponse ... Apres ma premiere installation de Jarvis, j'essai de lancer la reconnaissance mais rien ne se passe... Comme si mon micro n'était pas activé, alors que tout la configuration s'est bien passée... Ce dessous le retour du monde troubleshooting :  

### Result
```shell

------------ Config ------------
jv_branch            master
jv_version           17.03.26
jv_arch              armv7l
jv_os_name           raspbian
jv_os_version        8
language             fr_FR
play_hw              hw:0,0
rec_hw               hw:1,0
speaker              ALSA
microphone           Plantronics, Inc.
recorder             sox
trigger_stt          snowboy
command_stt          bing
tts_engine           svox_pico
--------------------------------

DEBUG: program_startup hook
snowboy: Hello
DEBUG: start_speaking hook
DEBUG: stop_speaking hook
User defined commands:
*AIDE*                  *BONJOUR*|*SALUT*       *COMMENT*APPELLE*
*MERCI*                 *AU REVOIR*|*BYE*       ANNULE*|TERMINE*
ENCORE*                 *TEST*                  *VERSION*
*REPETE (*) ET (*)      *CA VA*                 >*OUI*
>*NON*|*PAS*
Commands from plugin jarvis-time:
*QUELLE HEURE*          *QUEL JOUR*
Commands from plugin jarvis-weather-wunderground-fr:
*METEO*DEMAIN*          *METEO*
Commands from plugin jarvis-jeedom:
*
snowboy: Waiting to hear 'snowboy'
Benoit: (listening...)
DEBUG: models=snowboy
INFO:snowboy:Ticks: [2, 20, 5, -1]


```
et à la fin, il se bloque... rien ne se passe même après plusieurs longues minutes d'attente. Si quelqu'un a une idée ...

Merci d'avance

**Comment by schnibel** [comment]
hello, 
On a eu exactement le même problème. C'est traité ici #507 
Je t'invite à regarder...

**Comment by Amonbofils** [comment]
Le soucis c'est que pour ma part, je n'ai aps du tout du tout d'écoute une fois jarvis allumé . Exemple sur l'issue citée, la personne annonce ceci en débug :"

``
INFO:snowboy:Ticks: [2, 20, 5, -1]
INFO:snowboy:Keyword 1 detected at time: 2017-03-28 14:25:12
INFO:snowboy:Ticks status: 2 7 0 1
DEBUG: modelid=0
jarviss
DEBUG: entering_cmd hook
jarviss: Je vous écoute !
DEBUG: start_speaking hook
DEBUG: stop_speaking hook
christophe: (listening...)
DEBUG: start_listening hook
utils/timeout.sh 10 rec -V1 -q -r 16000 -c 1 -b 16 -e signed-integer --endian little /dev/shm/jarvis-record.wav gain 10 silence 1 0.1 1 1 0.5 1 trim 0 5
DEBUG: speech duration was 20 (10 = 1 sec)
DEBUG: stop_listening hook
DEBUG: curl https://speech.platform.bing.com/recognize/query?version=3.0&requestid=20f5f7b2-fb2c-4ae7-8ec3-66053b5e2404&appid=D4D52672-91D7-4C74-8AD8-42B1D98141A5&format=json&locale=fr-FR&device.os=linux&scenarios=ulm&instanceid=E043E4FE-51EF-4B74-8133-B728C4FEA8AA&result.profanitymarkup=0
DEBUG: json={"version":"3.0","header":{"status":"success","scenario":"ulm","name":"ajoute le message suivant coucou comment ça va","lexical":"ajoute le message suivant coucou comment ça va","properties":{"requestid":"3ff5eb5f-ca4a-400c-9db7-ec63504e6b74","HIGHCONF":"1"}},"results":[{"scenario":"ulm","name":"ajoute le message suivant coucou comment ça va","lexical":"ajoute le message suivant coucou comment ça va","confidence":"0.9451393","properties":{"HIGHCONF":"1"}}]}
ajoute le message suivant coucou comment ça va
$> say "Message ajouté" && "$(curl -G --fail --silent "http://127.0.0.1:8080/AddMemo?memoTitle=messages" --data-urlencode "item=${BASH_REMATCH[1]}")"
jarviss: Message ajouté
DEBUG: start_speaking hook
DEBUG: stop_speaking hook
./jarvis.sh: ligne 626: {"status":"success","item":{"memoTitle":"messages","level":"INFO","item":"coucou comment ca va","timestamp":"2017-03-28T12:25:25.896Z"}} : commande introuvable
jarviss: Ouh là là, il y a eu une erreur
DEBUG: start_speaking hook
DEBUG: stop_speaking hook
christophe: (listening...)
DEBUG: start_listening hook
utils/timeout.sh 10 rec -V1 -q -r 16000 -c 1 -b 16 -e signed-integer --endian little /dev/shm/jarvis-record.wav gain 10 silence 1 0.1 1 1 0.5 1 trim 0 5
DEBUG: speech duration was 18 (10 = 1 sec)
DEBUG: stop_listening hook
play FAIL formats: can't open output file `default': snd_pcm_hw_params error: Input/output error
ERROR: play command failed
HELP: Verify your speaker in Settings > Audio > Speaker
``

Hors moi je n'ai rien, meme pas une petite ligne pour me dire qu'il passe en recording... Je vais tenter les commandes données dans le #507 mais j'en ai deja essayé plusieurs sans pour autant avoir une quelconque avancée ...

**Comment by wikijm** [comment]
@Amonbofils Ton résultat de troubleshooting mode est très peu lisible.
Peux-tu utiliser [ASCIInema](https://asciinema.org/) à la place (et idem pour tes futurs tests) ?

**Comment by Amonbofils** [comment]
Alors en fait le report au dessus c'est celui de schnibel dans le probleme #507 ,

 et justement moi je n'ai rien de rien, pas une seule ligne après ce que j'ai mis en premier post, pas un truc pour me mettre sur la voie d'une éventuelle résolution ... c'est justement ca le gros problème 

J'edite mon précédent post pour que ce soit plus lisible, bien que ca n'ai aucun rapport avec moi :D

**Comment by alexylem** [comment]
@Amonbofils Jarvis est en attente du hotword. Tu dis bien "snowboy" à l'américaine?
"Snaaoboohi"
Dans ton post suivant tu as bien réussi à le déclenché, et il est passé en mode écoute d'une commande.
Je ne comprends pas trop ou est ton problème...

>Hors moi je n'ai rien, meme pas une petite ligne pour me dire qu'il passe en recording...

Si tu l'as:
```
christophe: (listening...)
```

**Comment by Amonbofils** [comment]
Le 2eme message est une reprise de la citation de l'erreur #507, qui montre
que normalement il devrait y avoir au moins listening à un moment, mais moi
je n'ai pas ca

Ce que moi j'ai, c'est juste ce qu'il y a dans mon premier post, il
s'arrête après la ligne INFO:snowboy:TRICKS:BLABLABLA

D'ou mon problème, il ne passe pas en mode listening... Il fige comme un
fond de sauce sur une fenêtre en hiver...

Le 28 mars 2017 6:43 PM, "Alexandre Mély" <notifications@github.com> a
écrit :

**Comment by alexylem** [comment]
>Il fige comme un fond de sauce sur une fenêtre en hiver...

🤣 

Ok donc il ne réagit pas au hotword.
Je vois que tu utilises "snowboy". Tu dis bien "snowboy" à l'américaine?
"Snaaoboohi"

Tu peux aussi essayer avec "alexa" ou trainer ton propre hotword.

**Comment by Amonbofils** [comment]
j'ai essayé avec de multiples mot. Rien a faire j'ai pas une ligne qui s'affiche apres comme si au moment de passe en listening il plantait avant meme de metre mon micro sur ON.

J'ai testé : 

###
```shell
rec /tmp/test.wav
# parle quelques seconds puis Ctrl+C
play /tmp/test.wav
```


Et la ! Impeccable tout marche ... merde c'est pas mon micro ! 

Alors après dites moi si je me trompe mais en mode troubleshooting, je dois pas avoir des lignes qui s'affichent pour me dire hotword trop court, trop long, pas entendu, arrêtes avec ton accent de français qui se la joue américain ??? 

Non parce que si effectivement c'est normal qu'il n'y ai pas une seule ligne après, j’arrête de vous embêter pour rien, et je balance mon RPI au fin fond de mon four et je le regarde se calciner lentement en affichant un rictus sadique ... 

Je vais tenter le coup du record de session pour voir si ca aide plus ou pas.

**Comment by Amonbofils** [comment]
Alors en ajout je vous met ceci : 
https://asciinema.org/a/79th0sgm17zt0pcfczirelsym

après le lancement de Jarvis j'ai dit d'une bonne 10ene de façon différente le hotword snowboy a l'américaine, a l’armoricaine , a la marocaine... rien a faire, puis je fini par un magnifique ctrl+c pour me barrer de ce traquenard !

**Comment by Amonbofils** [comment]
Question : y'a moyen de tout desisntaller et reinstaller ? ou a minima snowboy ?

**Comment by Amonbofils** [comment]
Ah j'ai du nouveau ! Alors j'ai procédé a une desisntall complete puis reinstall de jarvis, j'ai tout reconfiguré, et la magie !!!!! Ca a maché !

Puis d'un coup d'un seul ... boom, crash de jarvis:
### Result
```shell
DEBUG: entering_cmd hook
Benoit: (listening...)
DEBUG: start_listening hook
utils/timeout.sh 10 rec -V1 -q -r 16000 -c 1 -b 16 -e signed-integer --endian little /dev/shm/jarvis-record.wav gain  -3 silence 1 0.1 11 1 0.5 11 trim 0 5
DEBUG: stop_listening hook
play FAIL formats: can't open input file `/dev/shm/jarvis-record.wav': WAVE: RIFF header not found
ERROR: play command failed
HELP: Verify your speaker in Settings > Audio > Speaker


```

Je relance jarvis, et la : reproduction de mon probleme original ! Plus un seul mouvement après démarrage

Une idée ?

**Comment by alexylem** [comment]
T'en fais pas pour `max_noise_duration_to_kill` ce paramètre n'existe plus. Je viens de l'enlever du menu (beta).

```shell
play FAIL formats: can't open input file `/dev/shm/jarvis-record.wav': WAVE: RIFF header not found
ERROR: play command failed
```
Essaye de redémarrer, c'est la première fois que je vois ce message d'erreur.

**Comment by Amonbofils** [comment]
J'ai chmodé le doffier en question, reboot, et ca marche ... Bon bah on va dire que c'est clos ! Merci pour votre aide !

**Comment by alexylem** [comment]
@Amonbofils  Attends attends 😄  si tu as du chmoder c'est probablement que qqun d'autre devra le faire à l'avenir. Autant prévenir que guérir.
Donc pour confirmer:
* Tu as du chmoder `/dev/shm` ?
* Quels étaient les droits avant ?
* Quels doit lui as-tu mis ?

Merci!

**Comment by wikijm** [comment]
@Amonbofils As-tu eu le temps de récupérer les infos demandées par @alexylem ?

**Comment by wikijm** [comment]
Pas de réponse depuis 12 jours, je clôture le ticket.
Si besoin, ne pas hésiter à le ré-ouvrir 😉

**Comment by alexylem** [comment]
Je rencontre le problème régulièrement avec le timeout:
```shell
Alex: (listening...)
DEBUG: start_listening hook
utils/timeout.sh 10 rec -V1 -r 16000 -c 1 -b 16 -e signed-integer --endian little /dev/shm/jarvis-record.wav gain 5 silence 1 0.1 9 1 0.5 9 trim 0 5

Input File     : 'default' (alsa)
Channels       : 1
Sample Rate    : 16000
Precision      : 16-bit
Sample Encoding: 16-bit Signed Integer PCM

In:0.00% 00:00:09.22 [00:00:00.00] Out:0     [      |      ]        Clip:0    
retcode=124 # timeout
DEBUG: stop_listening hook
play FAIL formats: can't open input file `/dev/shm/jarvis-record.wav': WAVE: RIFF header not found
# should not be played
ERROR: play command failed
HELP: Verify your speaker in Settings > Audio > Speaker
```

**Comment by alexylem** [comment]
Corrigé sur la branch `beta`
