### ISSUE TITLE
Probleme d'accent et de majuscule

### ISSUE THREAD

**Issue by RobyBioloid** [alexylem/jarvis#509]
Bonjour,

Dans mon fichier commands, j'ai besoin d'enregistrer la saisie utilisateur dans un fichier.

J'utilise donc cette ligne:
(*)==echo "(1)" > fichier.txt

Le problème est que l'enregistrement ne prend pas en compte les majuscules et les accents.

Une phrase comme:
Aujourd'hui je suis arrivé avec Emilie sera enregisté en:
aujourdhui je suis arrive avec emilie.

**Comment by alexylem** [comment]
C'est un bug.
Pas facile à résoudre, en attendant, tu peux faire:
```shell
(*)==echo "$order" > fichier.txt
```
