### ISSUE TITLE
On parle de nous sur la toile

### ISSUE THREAD

**Issue by wikijm** [alexylem/jarvis#510]
Ce ticket est simplement pour signaler les personnes et articles qui parlent du projet.

A ce jour :

- [ [@Sarakha63](https://twitter.com/sarakha63)]
https://twitter.com/sarakha63/status/847012704204324865 
http://sarakha63-domotique.fr/jarvis-lassistant-vocal-open-source-pour-votre-domotique-la-veille-de-sarakha63/
- [[blog.domadoo.fr](http://blog.domadoo.fr)]
http://blog.domadoo.fr/65342-jarvis-lassistant-vocal-open-source-domotique/

**Comment by alexylem** [comment]
On peut dire Merci à @Sellig28 pour m'avoir mis en relation avec Laurent de chez Domadoo 😉

**Comment by alexylem** [comment]
Section **on en parle** mise à jour:
http://domotiquefacile.fr/jarvis/content/credits

**Comment by Sellig28** [comment]
Oui bien, content que l'on en parle tu mérites, c'est un beau projet.
