### ISSUE TITLE
jarvis 100% offline

### ISSUE THREAD

**Issue by phenixar** [alexylem/jarvis#511]
Bonjour Alexandre,
Comment est-il possible d'avoir Jarvis en francais et 100% offline pour STT et TTS stp ?

Merci pour ton aide.

**Comment by wikijm** [comment]
**Français** => Sélectionner cette langue durant l'assistant de configuration initial. Langue sélectionnable aussi dans Jarvis-UI. Il faut ensuite que les plugins proposent cette langue, ce qui est généralement le cas.
**Utilisation offline** => Snowboy ou PocketSphink en [STT](http://domotiquefacile.fr/jarvis/content/stt), SVOX Pico, eSpeak ou  OSX Say en [TTS](http://domotiquefacile.fr/jarvis/content/tts).

**Comment by alexylem** [comment]
@phenixar 
Voici ma reco pour Jarvis 100% hors ligne en Français
STT Engine: Snowboy
TTS Engine: Snowboy (attention, il te faudra trainer toutes tes commandes à l'avancer, pas de possibilité d'avoir des commandes dont les mots ne sont pas connus à l'avance).

**Comment by phenixar** [comment]
Merci Alexandre je vais potassé Snowboy.
