### ISSUE TITLE
Lecture de la version au format de la date

### ISSUE THREAD

**Issue by colas31** [alexylem/jarvis#512]
Hello,

je suis en train de tester Jarvis que je lui demande sa version, il écrit : 

> Je suis en version 17.03.26

Mais prononce : 

> je suis en version 17 Mars 2026

J'utilise SVOX Pico en TTS. 

Merci

**Comment by alexylem** [comment]
C'est interprétation du moteur de synthèse vocal du texte "17.03.26".
J'ai choisi de nommer mes versions ainsi.
Si ca pose un problème, tu peux changer cette commande pour lui faire dire une version modifiée:
```
*VERSION*==say "Je suis en version ${jv_version//./ }"
```

**Comment by colas31** [comment]
C'est ce qui me semblait, ce n'était pas du tout un bug mais le fonctionnement par défaut du TTS. 

Merci pour la confirmation, et désolé pour le dérangement

**Comment by alexylem** [comment]
Pas de soucis 👍
