### ISSUE TITLE
ERROR: bing recognition curl failed

### ISSUE THREAD

**Issue by vinceHH** [alexylem/jarvis#513]
Bonjour,

J'ai expérimenté jarvis hier soir. Toute la config fonctionne bien, son ok, micro ok.
La reconnaissance du mot clé "jarvis" fonctionne correctement avec snowboy.

Par contre, la reconnaissance des commande avec Bing ne fonctionne pas.
J'ai bien créé mon environnement bing speech (maintenant hosté sur Azure), j'ai bien renseigné l'API key mais j'obtiens constamment la même erreur "ERROR: bing recognition curl failed".

Je sais que Microsoft a fait évoluer ses services "cognitive services" récemment.

Microsoft fourni un exemple de script (recent de 15 jours) pour accéder à ses API depuis un raspberry : https://gallery.technet.microsoft.com/How-to-Use-Bing-Speech-API-3b9c1b58

Peut être pourriez vous y jeter un œil pour voir si votre implémentation dans jarvis correspond ?
Je ne suis malheureusement pas développeur mais je comprend vite ;)

Je pourrais fournir un log du mode debug ce soir, n'ayant pas accès à la plateforme en journée.

Merci, bonne journée

**Comment by wikijm** [comment]
L'utilisant tous les jours, je confirme que Bing Speech API fonctionne autant sur l'environnement "classique" que Azure.
Les logs du mode troubleshooting devraient en effet nous en dire plus.

**Comment by wikijm** [comment]
Pour être un peu plus précis dans ma réponse, les commandes cURL effectuées par Jarvis sont visibles dans ce fichier : https://github.com/alexylem/jarvis/blob/master/stt_engines/bing/main.sh

En lecture rapide, j'ai l'impression qu'elles sont identiques.

**Comment by vinceHH** [comment]
C'est ce que j'ai regardé également, mais le diable se cachant dans les détails...
Je vous envoie le log ce soir

**Comment by alexylem** [comment]
@vinceHH chez moi ca fonctionne toujours très bien. J'attends ton log avec impatience.

**Comment by vinceHH** [comment]
Hello,

Et bien, je me trouve bête .. tout fonctionne aujourd'hui ...

Ma seule explication est que mon environnement bing speech a mis un peu de temps à s'initialiser, bien plus que les 10 minutes annoncées.

Bref, désolé du dérangement ! 
J’espère à mimina vous avoir informé du script mis à dispo par MS.
J'ai plus qu'à "jouer" maintenant. L'idée étant de commande mon installation KNX via un superviseur (linknx)

**Comment by alexylem** [comment]
Super ca va aider les autres qui se trouveront dans ta situation!

**Comment by satana888** [comment]
bonjour,

voila j'arrive avec ce même problème exposé ultérieurement tout allait bien jusqu'à il y a quelques minutes sans raisons bien précises... 
le hotword fonctionne puis quand je veux demander une de mes commandes j'ai ce message d'erreur : ERROR: bing recognition curl failed
Il y a une limite avec une key API? si oui comment réactiver une nouvelle? car déjà fait et elle me renvoi la même KEY
J'avoue que je panique, car j'ai fais pas mal de choses avec , il a une super config pour mes propres besoin, mais qu'il ne réponde plus me démoralise...

**Comment by alexylem** [comment]
dupplicate #646
