### ISSUE TITLE
Mettre en place le SST de Google Speech

### ISSUE THREAD

**Issue by colas31** [alexylem/jarvis#514]
Actuellement le STT de Google n'est pas disponible lors de l'installation de Jarvis.

Si on en crois la page de prix de Google Speech, ils autorisent 60 minutes gratuites par mois  : https://cloud.google.com/speech/pricing
et les quotas associés semblent correcte : https://cloud.google.com/speech/limits

Merci pour la futur MAJ

Nico

**Comment by alexylem** [comment]
En effet ca a évolué.
Voir:
https://github.com/alexylem/jarvis/pull/95
>A priori les inscriptions sur Google Speech Api sont closes. Il faut utiliser Cloud Speech Api qui permet 240 appels /mois de maxi 15 secondes chacun.

>Serieusement ?
Ca fait meme pas 10 par jours ?

Disons une commande dure 4 secondes (max). Ca fait 1h = 3600s = 900 commands = 30 / jour
Ca peut passer dans la majorité des utilisations "normales". Moins pour ceux qui testent de manière intensive.
Et pas encore à la hauteur de Bing avec ses 5000 reconnaissances par mois...

**Comment by colas31** [comment]
Vu comme ça, j'avoue que l'utilité est moindre. 
Honnêtement autant abandonner cette solution tant qu'ils reverront pas à la hausse leur quota. ;) 
Sinon tu vas bosser pour pas grand chose
