### ISSUE TITLE
Utilisation de hook

### ISSUE THREAD

**Issue by pacanou** [alexylem/jarvis#515]
Bonjour,

J'ai un problème de paramétrage avec hook, je voudrais lancer un fichier allumTV.sh mais je n'y arrive pas.
Dans mon fichier de commande, je ne sais pas quoi mettre à la suite du ; 
ALLUME*==say "tout de suite"; ??????
1ère question : 
Ou dois je copier mon fichier allumTV.sh ? actullement, je l'ai copié dans le dossier /jarvis et jarvis/utils
2ème questions : 
Que dois-je mettre dans : 
program startup: 
entering command mode: 
exiting command mode: 
program exit: 

J'ai suivi la procédure : en remplaçant le nom du fichier par le mien.
program startup: my_led.sh blink
entering command mode: my_led.sh on
exiting command mode: my_led.sh blink
program exit: my_led.sh off
### Result
eva: Waiting to hear 'eva'
pascal: (listening...)
DEBUG: models=eva
Cannot connect to server socket err = No such file or directory
Cannot connect to server request channel
jack server is not running or cannot be started
INFO:snowboy:Ticks: [2, 20, 5, -1]
INFO:snowboy:Keyword 1 detected at time: 2017-04-01 09:57:56
INFO:snowboy:Ticks status: 2 4 2 1
DEBUG: modelid=0
eva
DEBUG: entering_cmd hook
eva: Oui
DEBUG: start_speaking hook
DEBUG: stop_speaking hook
pascal: (listening...)
DEBUG: start_listening hook
utils/timeout.sh 10 python  recorders/snowboy/main.py 0 /dev/shm/jarvis-record.wav
Cannot connect to server socket err = No such file or directory
Cannot connect to server request channel
jack server is not running or cannot be started
___________||||||||___INFO:recorder:Ticks status: 11 8 3
DEBUG: speech duration was 10 (10 = 1 sec)
DEBUG: stop_listening hook
DEBUG: token missing or expired
DEBUG: json=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzY29wZSI6Imh0dHBzOi8vc3BlZWNoLnBsYXRmb3JtLmJpbmcuY29tIiwic3Vic2NyaXB0aW9uLWlkIjoiNzc1NDIxMmJkOGZjNGU4M2I0MTM1NGI3NjFkMTE3ZjMiLCJwcm9kdWN0LWlkIjoiQmluZy5TcGVlY2guUHJldmlldyIsImNvZ25pdGl2ZS1zZXJ2aWNlcy1lbmRwb2ludCI6Imh0dHBzOi8vYXBpLmNvZ25pdGl2ZS5taWNyb3NvZnQuY29tL2ludGVybmFsL3YxLjAvIiwiYXp1cmUtcmVzb3VyY2UtaWQiOiIiLCJpc3MiOiJ1cm46bXMuY29nbml0aXZlc2VydmljZXMiLCJhdWQiOiJ1cm46bXMuc3BlZWNoIiwiZXhwIjoxNDkxMDQxMjgzfQ.CvaSl0-RcIOdL0bHHg128Iryl8Bz5NE2XZVFhtiztuE
DEBUG: token will expire in 590 seconds
DEBUG: curl https://speech.platform.bing.com/recognize/query?version=3.0&requestid=3971945b-ee60-4fe2-8889-c4c8d34ac680&appid=D4D52672-91D7-4C74-8AD8-42B1D98141A5&format=json&locale=fr-FR&device.os=linux&scenarios=ulm&instanceid=E043E4FE-51EF-4B74-8133-B728C4FEA8AA&result.profanitymarkup=0
DEBUG: json={"version":"3.0","header":{"status":"success","scenario":"ulm","name":"allume","lexical":"allume","properties":{"requestid":"1a738f37-d50f-4c60-ad42-56041453d7ae","HIGHCONF":"1"}},"results":[{"scenario":"ulm","name":"allume","lexical":"allume","confidence":"0.8815792","properties":{"HIGHCONF":"1"}}]}
allume
$> say "tout de suite"; entering_cmd
eva: tout de suite
DEBUG: start_speaking hook
DEBUG: stop_speaking hook
./jarvis.sh: line 626: entering_cmd: command not found
eva: Il ya une erreur
DEBUG: start_speaking hook
DEBUG: stop_speaking hook
pascal: (listening...)
DEBUG: start_listening hook
utils/timeout.sh 10 python  recorders/snowboy/main.py 0 /dev/shm/jarvis-record.wav
Cannot connect to server socket err = No such file or directory
Cannot connect to server request channel
jack server is not running or cannot be started
____________________________________________________________________________DEBUG: stop_listening hook
![1](https://cloud.githubusercontent.com/assets/26834894/24577722/4f4c4e52-16d3-11e7-8d60-0c1ecb05b9cb.jpg)

**Comment by alexylem** [comment]
Qu'est-ce que tu veux faire exactement?
Lancer ton fichier à la demande (via une commande) ?
Ou au démarrage de Jarvis ?
Ou à un autre moment ?

**Comment by pacanou** [comment]
Je veux juste exécuter mon fichier via une commande vocale depuis jarvis. Voici le contenu de mon fichier allumTV.sh : 

#!/bin/bash
cd ~/
sudo irsend SEND_ONCE tv BTN_0

Merci de ton aide.

**Comment by alexylem** [comment]
```shell
*MA*COMMANDE*==source /path/to/your/script.sh && say "Voilà"
```
Sinon encore mieux:
```shell
*MA*COMMANDE*==sudo irsend SEND_ONCE tv BTN_0 && say "Voilà"
```

**Comment by pacanou** [comment]
Argh c'était aussi simple que cà lol, j'avais essayé mais avec le "say" au début. En tout cas Merci, çà fonctionne.
Je te dois une bière ;-).

**Comment by pacanou** [comment]
juste une autre question j'ai un problème de caractère quand j'écris "Voilà" dans la commande le "à" est traduit en ï¿½ , idem avec le é.

**Comment by alexylem** [comment]
@pacanou peux-tu créer un nouveau ticket et y coller le log de Jarvis lancé en mode troubleshooting?
Merci.
