### ISSUE TITLE
besoin d'aide pour installation jarvis

### ISSUE THREAD

**Issue by littlesinse** [alexylem/jarvis#516]
salut tous le monde,

je sais pas si c'est comme ca qu'il faut proceder mais j'aimerais avoir une aide pour installer jarvis.

pour la reconnaisance vocal je ne sais pas quoi choisir.    ca ne me derange pas que cela soit toujours connecter a internet.  j'aimerais quelque chose de simple a mettre en place.
pour commencer demander l'heure la meteo etc.

bref si quelqu'un voudrais bien m'aider ce serait sympa

**Comment by wikijm** [comment]
Bonjour @littlesinse, 

Pour faire au plus simple et efficace quand on débute avec Jarvis :
* Which engine to use for the recognition of the hotword (Jarvis) : **snowboy**
* Which engine to use for the recognition of commands : **bing**
* Which engine to use for the speech synthesis : svox_**pico**

**Comment by wikijm** [comment]
Je t'invite à suivre la doc suivante : http://domotiquefacile.fr/jarvis/content/prerequisites

**Comment by littlesinse** [comment]
Ok, ca cest bon jai tout fait deja une premiere fois
Configurer le son (jai entendu les applaudissements) mais pour la phase reconnaissance ,lorsque j'essaie de enregistrée au troisieme essaie lorsque je fais ctrl c ca sarrete et ca marque aborted.
Est ce que il faut des cle api ou autre choses?
Je sais que c'est abuses de te demander un tuto récent.
Sympa de repondre si rapidement

**Comment by littlesinse** [comment]
Pour la cle bing il fautpas passer par azure?

**Comment by wikijm** [comment]
En t'appuyant sur Bing, il faut en effet créer un compte sur Portal Azure pour obtenir une clé d'API.

**Comment by wikijm** [comment]
http://domotiquefacile.fr/jarvis/content/bing à suivre pour récupérer une clé API.

**Comment by littlesinse** [comment]
Et qpres j'en fait quoi de la cle

**Comment by wikijm** [comment]
Applique la procédure suivante : https://asciinema.org/a/awe92v43wxvyy5izrt9vbv783
@alexylem N'hésites pas à intégrer cette mini-vidéo aux procédures.

**Comment by alexylem** [comment]
J'ai déjà publié une vidéo d'installation complète sur le site:
http://domotiquefacile.fr/jarvis/content/installation
@littlesinse ton histoire d'aborted je crois que tu parles de l'entrainement du hotword. Et le token du coup c'est plutôt snowboy.
Quand tu as un doutes et que tu demandes de l'aide, merci de donner un maximum d'information, et surtout des copies de terminal. Sans ca impossible de savoir ce que tu as devant les yeux.
Ah oui et aussi... lis bien TOUTES les instructions / messages affichés à l'écran.

**Comment by littlesinse** [comment]
Ok, il y a un moment dans snowboy token tu met une liste de chiffre et lettre, mais sur le site de snowboy je cherche untruc du genre meme si jenregistre jarvis je le triuve nul part

**Comment by alexylem** [comment]
Lis TOUTES les instructions, c'est écrit:
![image](https://cloud.githubusercontent.com/assets/11017174/24582243/76a0a4b4-172b-11e7-90e1-7621671a4c4b.png)
Dans Profile settings

**Comment by littlesinse** [comment]
merci , desole entre mon anglais scolaire college et precipitation ça aide pas

c'est plus clair comme ça
