### ISSUE TITLE
Pb jarvis ligne 729

### ISSUE THREAD

**Issue by Rano85** [alexylem/jarvis#517]
Bonjour, voici le log du mode debug, jarvis marche en mode keyboard seulement

DEBUG: exiting_cmd hook
Jarvis: Waiting to hear 'Jarvis'
Monsieur: (listening...)
./jarvis.sh: ligne 729: _STT : commande introuvable
(listening...)
./jarvis.sh: ligne 729: _STT : commande introuvable
(listening...)
./jarvis.sh: ligne 729: _STT : commande introuvable
DEBUG: 3 attempts failed, end of conversation

**Comment by wikijm** [comment]
J'ai rencontré le même type de soucis à l'instant.
Vérifie que ton STT est toujours bien défini dans la configuration.

J'attends ton retour 😃

**Comment by alexylem** [comment]
Oui vérifie dans Settings > Voice Reco > of magic word (ca devrait être snowboy)

**Comment by wikijm** [comment]
Pas de retour depuis 5 jours, j'en conclus que le problème est résolu.
Ne pas hésiter à ré-ouvrir l'issue si ce n'est pas le cas 😉
