### ISSUE TITLE
Jarvis ne comprend pas mes ordres vocaux lorsque j'écoute de la musique

### ISSUE THREAD

**Issue by Clems126** [alexylem/jarvis#518]
Je ne peux pas faire de commande lorseque j ecoute une musique avec jarvis sur une autre page de forum de github il parlait de hook je ne comprends pas comment faire donc pour mon pb. Merci d avance pour tous ceux qui me repondront1

**Comment by wikijm** [comment]
Bonjour @Clems126,

Écrire en majuscules équivaut à l'écrit à montrer que l'on crie.
J'imagine que cela n'était la façon dont tu voulais transmettre ton message.
J'ai donc renommé quelque peu le titre de ton issue.

**Comment by wikijm** [comment]
Pour ton problème, je pense que c'est tout simplement parce que Jarvis ne t'entends pas à cause du bruit ambiant généré par ta musique.

Essaye donc de parler à quelqu'un quand ce dernier écoute de la musique un peu forte.

**Comment by wikijm** [comment]
A noter :
- Il n'existe pas de fonctionnalité "forum" sur GitHub
- Afin que l'on puisse t'aider convenablement, merci de respecter le travail du créateur et des contributeurs en prenant un temps minime afin de lire les docs et fournir les éléments demandés lors de la création d'une issue

**Comment by alexylem** [comment]
Petite astuce: certains utilisateurs on utilisé les hooks pour mettre la musique en pause lorsque Jarvis le mot clé est reconnu et passe en mode commande (`entering_cmd`) puis la remettre ensuite (`exiting_cmd`).

**Comment by Clems126** [comment]
Desolez mais mon probleme etait que jarvis se mettait en mode "no conversation " lorseque je faisais la commande pour ecouter de la musique avec jarvis qui est *PLAY MUSIC*==play /home/pi/Music/mamusique.wav
