### ISSUE TITLE
Multiple réponses faite par jarvis

### ISSUE THREAD

**Issue by Desaydrone** [alexylem/jarvis#519]
Bonjour,

Est-il possible de faire en sorte que jarvis, lorsqu'on lui adresse la parole pour qu'il se mette en mode commande, puisse avoir plusieurs réponses ou qu'il interroge un plugin qui générera des réponses ?

J'aimerai pouvoir le rendre un peu plus interactif, voir émotionnel car avec l'utilisation d'un plugin on pourrais imaginer beaucoup de chose

**Comment by alexylem** [comment]
Parle-tu de ca #500 ?

**Comment by Desaydrone** [comment]
Ha ben oui je n'étais pas tombé dessus désolé, on peut clore alors, navré vraiment
