### ISSUE TITLE
Problème de compréhension avec webcam Logitech B910 

### ISSUE THREAD

**Issue by titoo92** [alexylem/jarvis#520]
Bonjour,

Tout d'abord, bravo Alex, je bidouille beaucoup avec mes raspberry, et c'est souvent beaucoup d'heures avant que cela ne fonctionne.
J'ai fait mes premiers tests Jarvis avec un microcasque logitech => tout marche nickel du premier coup !!!... alors je fonce, j'installe dans la foulée le plugin jeedom ... et la c'est l'effet waouw ... interactions, commandes, pareil du premier coup tout fonctionne :-) :-)
Il faut que j'aille au bout ... il me faut les plugins face, freebox, le weather, le SMS,etc, et comme je viens de finir quelques picoreplayer, il va falloir que je trouve le moyen de piloter mes squeezebox a la voix ... mais avant tout, il me faut un vrai Jarvis, plus de microcasque, il faut que je puisse piloter en parlant normalement dans la salon... ca tombe bien, j'ai une webcam logitechB910 qui traine, elle a un  bon micro ... ca va le faire. 
Mais la je patauge , même problème que propheet sur le #467, obligé de baisser le gain, sur le test silence, et obligé de le monter pour qu'il m'entende sur les commandes ... je tourne en boucle et reste sur le Warning too long en debug.
Ma config qui fonctionne c'est la préco : raspian full sur RPI3, microcasque logitech sur carte connectland usb, mot clef via snowboy, commande via bing, et speech via svox.
Celle qui ne fonctionne pas (enfin pas encore :-)), la même, mais avec la camera logitechB910 en usb.
Si certains utilisent cette camera, peuvent ils partager leurs réglages ? Dans le cas contraire je posterai les miens, une fois que j'aurai trouvé le bon reglage.
Encore bravo Alex.

**Comment by wikijm** [comment]
Bonsoir @titoo92,

Pour que l'on puisse t'aider au mieux, merci de faire une vidéo [ASCIInema](https://asciinema.org/).

**Comment by alexylem** [comment]
D'abord merci à toi @titoo92 !
Avant que l'on passe du temps sur ta webcam, est-ce bien le matériel que tu souhaites utiliser à long terme? Généralement les micros de webcam sont pas les meilleurs du monde 😄 
Pour "parler normalement dans le salon" pour reprendre des mots, il te faudra un micro array avec réduction active de bruit.

**Comment by titoo92** [comment]
Non, tu as raison, pas le bon matos, trop sensible le micro. Même en ayant déplacé ma petite installation dans un endroit silencieux, je suis obligé de passer le gain à -15 sur le test silence, alors forcément après cela marche moins bien .. le magic word passe, mais bing lui ne comprend rien.
Je vais voir si je peux trouver un des micro de la liste des prérequis et je vous tiens au courant
