### ISSUE TITLE
Jarvis passe en mode no commande lorse que je fait la commande *PLAY MYSIC*==play home/pi/Music/mymusic.wav

### ISSUE THREAD

**Issue by Clems126** [alexylem/jarvis#521]
### Description

PLEASE SEARCH BEFORE existing tickets and in the docs
NB: for issues with plugins, please create in the corresponding repository

### Result
```shell
<paste here> content of the terminal after using Jarvis in troubleshooting mode
or attach a session recording using https://asciinema.org/
```

**Comment by Clems126** [comment]
mon probleme etait que jarvis se mettait en mode "no conversation " lorseque je faisais la commande pour ecouter de la musique avec jarvis qui est PLAY MUSIC==play /home/pi/Music/mymusic.wav

**Comment by alexylem** [comment]
Tu reportes un nouveau problème ou c'est une erreur?

**Comment by Clems126** [comment]
Non c est juste que je suis un terrible noob et donc je n ai pas compris ce que tu as dit par rapport a certains utilisateur qui utilisent des "hooks" je narrive pas a comprendre a quoi ca sert

**Comment by alexylem** [comment]
Lis la doc:
http://domotiquefacile.fr/jarvis/content/hooks
