### ISSUE TITLE
PARAMETRAGE JARVIS & JEEDOM

### ISSUE THREAD

**Issue by pacanou** [alexylem/jarvis#523]
Bonjour,
J'essaie de paramétrer jarvis et jeedom : 
1. J'ai installé le plugin jeedom et paramétré IP,port,api.
![1](https://cloud.githubusercontent.com/assets/26834894/24586713/7361bf6e-17a7-11e7-9de6-4d26ef1b31a1.jpg)

2. J'ai crée une intéraction en suivant le tuto du plugin, voir 2.jpg (côté jeedom, ouverture\fermeture du volet fonctionne)
![2](https://cloud.githubusercontent.com/assets/26834894/24586684/c46b0772-17a6-11e7-8695-727aa79c19ea.jpg)

3. J'ai crée la commande d'ouverture, voir 3.jpg en récupérant la ligne qu'il y'avait dans le fichier /home/pi/plugins/jarvis-jeedom/fr/commands
![3](https://cloud.githubusercontent.com/assets/26834894/24586697/199afdb0-17a7-11e7-93b4-0d78412c946a.jpg)

Mon problème lorsque je dicte ma commande, il va me lire le contenu d'un fichier DOCUMENT.HTML
Est ce que j'ai oublié de faire qq chose ? Merci.
```
### Result
------------ Config ------------
jv_branch            master
jv_version           17.03.26
jv_arch              armv7l
jv_os_name           raspbian
jv_os_version        8
language             fr_FR
play_hw              hw:1,0
rec_hw               hw:1,0
speaker              GN Netcom
microphone           GN Netcom
recorder             snowboy
trigger_stt          snowboy
command_stt          bing
tts_engine           svox_pico
--------------------------------

DEBUG: program_startup hook
eva: Bonjour
DEBUG: start_speaking hook
DEBUG: stop_speaking hook
User defined commands:
*AIDE*                  *BONJOUR*|*SALUT*       *COMMENT*APPELLE*
*AU REVOIR*|*BYE*       TERMINE*                ENCORE*
*TEST*                  *VERSION*               *REPETE (*) ET (*)
*ETEINT*                *TEST UN*               *OUVRE*VOLET*
Commands from plugin jarvis-jeedom:
*
eva: Waiting to hear 'eva'
pascal: (listening...)
DEBUG: models=eva
Cannot connect to server socket err = No such file or directory
Cannot connect to server request channel
jack server is not running or cannot be started
INFO:snowboy:Ticks: [2, 20, 5, -1]
INFO:snowboy:Keyword 1 detected at time: 2017-04-02 12:54:19
INFO:snowboy:Ticks status: 2 3 3 1
DEBUG: modelid=0
eva
DEBUG: entering_cmd hook
eva: Oui
DEBUG: start_speaking hook
DEBUG: stop_speaking hook
pascal: (listening...)
DEBUG: start_listening hook
utils/timeout.sh 10 python  recorders/snowboy/main.py 0 /dev/shm/jarvis-record.wav
Cannot connect to server socket err = No such file or directory
Cannot connect to server request channel
jack server is not running or cannot be started
_____||||||||||||||||||||||___INFO:recorder:Ticks status: 5 22 3
DEBUG: speech duration was 30 (10 = 1 sec)
DEBUG: stop_listening hook
DEBUG: curl https://speech.platform.bing.com/recognize/query?version=3.0&requestid=76601629-da48-4a37-a812-08b0b06121cb&appid=D4D52672-91D7-4C74-8AD8-42B1D98141A5&format=json&locale=fr-FR&device.os=linux&scenarios=ulm&instanceid=E043E4FE-51EF-4B74-8133-B728C4FEA8AA&result.profanitymarkup=0
DEBUG: json={"version":"3.0","header":{"status":"success","scenario":"ulm","name":"ouvre les volets","lexical":"ouvre les volets","properties":{"requestid":"fbf52b65-3596-4337-86be-ffda841c2044","HIGHCONF":"1"}},"results":[{"scenario":"ulm","name":"ouvre les volets","lexical":"ouvre les volets","confidence":"0.8938602","properties":{"HIGHCONF":"1"}}]}
ouvre les volets
$> say "$(curl "http://$jv_pg_jd_ip:$jv_pg_jd_port/${jv_pg_jd_path}core/api/jeeApi.php?apikey=$jv_pg_jd_apikey&type=interact" --data-urlencode "query=$order")"
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   251  100   225  100    26  10023   1158 --:--:-- --:--:-- --:--:-- 10714
eva: <!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>404 Not Found</title>
</head><body>
<h1>Not Found</h1>
<p>The requested URL /pacanou/core/api/jeeApi.php was not found on this server.</p>
</body></html>
DEBUG: start_speaking hook
^C
DEBUG: program_exit hook
```

**Comment by alexylem** [comment]
Pour toute question ou problème lié à un plugin Jarvis, merci de créer un ticket sur le repository correspondant. Ainsi son auteur en sera informé et pourra vous aider.

**Ok, alors c'est où?**
* Depuis Jarvis, allez dans Plugins > Installed > The Plugin > Report an issue
* Depuis le site, allez sur la page du plugin et cliquez sur le lien "Open a ticket"

Sinon question:
Pourquoi créer une commande dans ton fichier de commande alors que le plugin est déjà censé tout forwarder à Jeedom?
Sinon vu l'erreur c'est surement un pb dans ta config du plugin jeedom.
Essaye dans le terminal de directement lancer:
```shell
curl "http://$jv_pg_jd_ip:$jv_pg_jd_port/${jv_pg_jd_path}core/api/jeeApi.php?apikey=$jv_pg_jd_apikey&type=interact" --data-urlencode "query=$order"
```
En replacement les variables par leur valeur correspondante.

**Comment by alexylem** [comment]
Je viens de faire une modification du plugin jeedom pour faciliter le troubleshooting. Mets à jour et recolle nous les logs en mode troubleshooting.

**Comment by pacanou** [comment]
J'ai crée la commande dans mon fichier de commande car je ne sais pas comment çà fonctionne ;-( . Du coup je l'ai enlevé de mon fichier de commande. 

J'ai mis à jour jeedom et maintenant : 
------------ Config ------------
jv_branch            master
jv_version           17.04.01
jv_arch              armv7l
jv_os_name           raspbian
jv_os_version        8
language             fr_FR
play_hw              hw:1,0
rec_hw               hw:1,0
speaker              GN Netcom
microphone           GN Netcom
recorder             snowboy
trigger_stt          snowboy
command_stt          bing
tts_engine           svox_pico
--------------------------------

DEBUG: program_startup hook
eva: Bonjour
DEBUG: start_speaking hook
DEBUG: stop_speaking hook
User defined commands:
*AIDE*                  *BONJOUR*|*SALUT*       *COMMENT*APPELLE*
*AU REVOIR*|*BYE*       TERMINE*                ENCORE*
*TEST*                  *VERSION*               *REPETE (*) ET (*)
*ETEINT*                *TEST UN*
Commands from plugin jarvis-jeedom:
*
eva: Waiting to hear 'eva'
pascal: (listening...)
DEBUG: models=eva
Cannot connect to server socket err = No such file or directory
Cannot connect to server request channel
jack server is not running or cannot be started
INFO:snowboy:Ticks: [2, 20, 5, -1]
INFO:snowboy:Keyword 1 detected at time: 2017-04-02 15:22:41
INFO:snowboy:Ticks status: 2 4 2 1
DEBUG: modelid=0
eva
DEBUG: entering_cmd hook
eva: Oui
DEBUG: start_speaking hook
DEBUG: stop_speaking hook
pascal: (listening...)
DEBUG: start_listening hook
utils/timeout.sh 10 python  recorders/snowboy/main.py 0 /dev/shm/jarvis-record.w                                                                                      av
Cannot connect to server socket err = No such file or directory
Cannot connect to server request channel
jack server is not running or cannot be started
_______||||||||||||||___INFO:recorder:Ticks status: 7 14 3
DEBUG: speech duration was 20 (10 = 1 sec)
DEBUG: stop_listening hook
DEBUG: token missing or expired
DEBUG: json=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzY29wZSI6Imh0dHBzOi8vc3BlZWN                                                                                      oLnBsYXRmb3JtLmJpbmcuY29tIiwic3Vic2NyaXB0aW9uLWlkIjoiNzc1NDIxMmJkOGZjNGU4M2I0MTM                                                                                      1NGI3NjFkMTE3ZjMiLCJwcm9kdWN0LWlkIjoiQmluZy5TcGVlY2guUHJldmlldyIsImNvZ25pdGl2ZS1                                                                                      zZXJ2aWNlcy1lbmRwb2ludCI6Imh0dHBzOi8vYXBpLmNvZ25pdGl2ZS5taWNyb3NvZnQuY29tL2ludGV                                                                                      ybmFsL3YxLjAvIiwiYXp1cmUtcmVzb3VyY2UtaWQiOiIiLCJpc3MiOiJ1cm46bXMuY29nbml0aXZlc2V                                                                                      ydmljZXMiLCJhdWQiOiJ1cm46bXMuc3BlZWNoIiwiZXhwIjoxNDkxMTM5OTY4fQ.wVfeSmMVehhdDZiY                                                                                      zdTFsMc-yKNF0Xizf29KDDTur6w
DEBUG: token will expire in 590 seconds
DEBUG: curl https://speech.platform.bing.com/recognize/query?version=3.0&request                                                                                      id=1f963f2e-9b1e-4fcf-979c-f0cffbac9db3&appid=D4D52672-91D7-4C74-8AD8-42B1D98141                                                                                      A5&format=json&locale=fr-FR&device.os=linux&scenarios=ulm&instanceid=E043E4FE-51                                                                                      EF-4B74-8133-B728C4FEA8AA&result.profanitymarkup=0
DEBUG: json={"version":"3.0","header":{"status":"success","scenario":"ulm","name                                                                                      ":"ferme le volet trois","lexical":"ferme le volet trois","properties":{"request                                                                                      id":"7c6692f5-ebf4-48c7-be33-5c6de9fbf179","HIGHCONF":"1"}},"results":[{"scenari                                                                                      o":"ulm","name":"ferme le volet trois","lexical":"ferme le volet trois","confide                                                                                      nce":"0.9049219","properties":{"HIGHCONF":"1"}}]}
ferme le volet trois
$> $jv_pg_jd_waiting && say "Un instant..."; jeedom_call "$order"
curl --silent --fail --show-error "http://192.168.0.33:80/pacanou/core/api/jeeAp                                                                                      i.php?apikey=0R175dxq0fBNrTNIkxSmDKW59shDZ5uAlmsAfw6hbE1OI1tM&type=interact" --d                                                                                      ata-urlencode "query=ferme le volet trois"
ERROR: curl: (22) The requested URL returned error: 404 Not Found
HELP: verify jeedom plugin configuration
HELP: troubleshoot by running above curl command in terminal
eva: Il ya une erreur
DEBUG: start_speaking hook
DEBUG: stop_speaking hook
pascal: (listening...)
DEBUG: start_listening hook
utils/timeout.sh 10 python  recorders/snowboy/main.py 0 /dev/shm/jarvis-record.w                                                                                      av
Cannot connect to server socket err = No such file or directory
Cannot connect to server request channel
jack server is not running or cannot be started
____________________________________________________________________________DEBU

**Comment by alexylem** [comment]
```shell
curl --silent --fail --show-error "http://192.168.0.33:80/pacanou/core/api/jeeAp                                                                                      i.php?apikey=0R175dxq0fBNrTNIkxSmDKW59shDZ5uAlmsAfw6hbE1OI1tM&type=interact" --d                                                                                      ata-urlencode "query=ferme le volet trois"
ERROR: curl: (22) The requested URL returned error: 404 Not Found
HELP: verify jeedom plugin configuration
HELP: troubleshoot by running above curl command in terminal
```
Donc ca veut dire que l'URL de ton Jeedom est incorrecte.
Essaye de le faire marcher directement dans le terminal en adaptant la commande CURL ci-dessous:
```shell
curl --silent --fail --show-error "http://192.168.0.33:80/pacanou/core/api/jeeAp                                                                                      i.php?apikey=0R175dxq0fBNrTNIkxSmDKW59shDZ5uAlmsAfw6hbE1OI1tM&type=interact" --d                                                                                      ata-urlencode "query=ferme le volet trois"
```
Tu es sûr que ton Jeedom est installé à cette adresse?

**Comment by pacanou** [comment]
J'ai ce message : 

 curl --silent --fail --show-error "http://192.168.0.33:80/pacanou/core/api/jeeApi.php?apikey=0R175dxq0fBNrTNIkxSmDKW59shDZ5uAlmsAfw6hbE1OI1tM&type=interact" --data-urlencode "query=ferme le volet trois"
curl: (22) The requested URL returned error: 404 Not Found

Pour me connecter sur l'interface de jeedom, j'utilise http://192.168.0.33:80 et je me connecte en admin/admin
J'ai un doute sur le path "pacanou" il correspond au nom du jeedom, est ce bien çà ?

**Comment by alexylem** [comment]
Ca correspond à la variable:
```
jv_pg_jd_path="" # default is "". Set for ex: "jeedom/" if your jeedom is not at root
```
Comme indiqué dans la config, c'est vide par défaut. Sauf si tu installes Jeedom dans un path spécifique.

**Comment by pacanou** [comment]
OK, c'était bien çà en mettant à vide et sans avoir besoin de créer de commande 👍 .
Encore merci.
