### ISSUE TITLE
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 398: ordinal not in range(128)

### ISSUE THREAD

**Issue by NYGHOST** [alexylem/jarvis#527]
### Description
lorsque que je dicte ma commande ( snowboy) la commande est reconnue, mais au moment de la validé j'obtient "error",
j'ai redémarrer mis a jour et vérifize ma config son rien a faire.
la commande en question fonctionnait hier.

### Result
DEBUG: models=alexa,envoi,eva,snowboy,trois,un,véhicule

Traceback (most recent call last):
  
File "stt_engines/snowboy/main.py", line 66,in <module>
 
   trigger_ticks=trigger_ticks)

  File "/home/pi/jarvis/stt_engines/snowboy/maindecoder.py", line 63, in __init__
    
resource_filename=resource.encode(), model_str=model_str.encode())
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 398: ordinal not in range(128)

DEBUG: modelid=-10
ERROR: snowboy recognition failed

**Comment by alexylem** [comment]
Très étrange, tu as bien copié la totalité de la console en mode troubleshooting?
On dirait une corruption de carde SD...

**Comment by NYGHOST** [comment]
a non! me dit pas ca c'est déja la deuzieme ce mois ci!!!!!

**Comment by alexylem** [comment]
@NYGHOST c'est bon j'ai trouvé, c'est à cause de l'accent dans ton `école.pmdl`. Jarvis enlève les accents des modèles trainés, à mon avis tu l'as rajouté toi même manuellement...
Renomme le et enlève l'accent.

**Comment by wikijm** [comment]
Clôture du ticket le temps que tu puisse tester @NYGHOST.
N'hésites pas à réouvrir si cela ne résout pas ton problème 😉
