### ISSUE TITLE
Comment optimiser/régler la fausse interprétation des commandes sur jarvis ?

### ISSUE THREAD

**Issue by samwel89** [alexylem/jarvis#529]
Bonjour,

@alexylem Je profite d'ouvrir ce issue, je pense que les autres pourraient rencontrer le même problème.
Comment régler (optimiser) le problème de fausse interprétation du jarvis, par exemple, il a bien écrit (entendu) la commande comme "ajouter la liste de quoi" et il a répondu "Allumage de la musique salon effectué" c'est la réponse d'une autre question (ainsi plugin)....des fois çà m'arrive des cas comme cela.
Merci.

**Comment by alexylem** [comment]
Merci de coller le résultat complet de la console après avoir lancé Jarvis en mode Troubleshooting, ou partage une session de ton terminal en utilisant [asciinema](http://asciinema.org):
```shell
sudo apt-get install -y asciinema && asciinema rec # start session recording
./jarvish.sh -nv # start jarvis directly in troubleshooting mode
Ctrl+D # stop recording
y # yes to upload and get URL to paste here
```

**Comment by samwel89** [comment]
Voici:
http://asciinema.org/a/7zdkqoipye05dyiipvzia079c

**Comment by alexylem** [comment]
Quand tu as l'erreur sinon ca va pas trop m'aider 😄  Et lance en mode clavier ca sera plus facile:
```shell
$> ./jarvis.sh -k
```

**Comment by samwel89** [comment]
Ok, 😄!
Je t'enverrai dès que cela m'arrive encore.

**Comment by RobyBioloid** [comment]
Salut @samwel89 ,

Ca m'est déjà arrivé ce même genre de problème. Il faut faire attention au mot clé que tu donne pour la détection de commandes. Je m'explique

J'ai une commande qui met 'Jarvis' à jour:
\*MET\*A\*JOUR*==jv_update_config && say "Mise à jour effectuée."

Et j'ai également une commande météo du plugins jarvis_weather
\*METEO\*JOUR*== ..

Quand je disais : "Donne moi la météo pour aujourd'hui"
Jarvis me répondais : "Mise à jour effectuée"

Si on regarde bien ma phrase : "donne moi la **MET**éo pour **A**u**JOUR**d'hui", on voit bien qu'il comprend MET A JOUR et non METEO JOUR

Voici un exemple flagrant de problème de 'mot clé'.
Pour ma part j'ai modifer ma commande "\*MET\*A\*JOUR*" par "\*MET\*SYSTEM\*A\*JOUR*"

A toi de voir donc quand tu pense que 'Jarvis' répond à coté si il n'y a pas un problème dans tes 'mots clé'

**Comment by samwel89** [comment]
Salut @RobyBioloid 

C'est tout à fait çà j'avais pensé....merci pour ton exemple bien expliqué! Oui je vais bien améliorer mes commandes "mot clé" et observer. Merci.
