### ISSUE TITLE
play FAIL formats: can't open input file `/dev/shm/tts.wav': No such file or dir ectory  

### ISSUE THREAD

**Issue by maelade** [alexylem/jarvis#531]
Bonjour Alexandre,

Tout d abord merci  our ce superbe assistant, il m'a donné envie d acheter mon premier Rpbi ( 3B) , l'idée me titillait depuis des années mais le projet m'a tout a fait convaincu... 
J'ai suivi ton super tuto détaillé , j'ai installé Jessy en full . J'ai retenté 4 fois en reformatant la carte Sd et jusqu'à la fin de ton tuto tout de passe bien mais je n'arrive à avoir aucune interaction avec Jarvis je ne peux même pas le lancer .Je vois bien mon Rpi fans le finder et dans Screens mais c'est tout . Le mal doit être profond car quand je lance en mode troubleshooting :+1:  

pi@raspberrypi:~ $ git clone https://github.com/alexylem/jarvis.git
fatal: le chemin de destination 'jarvis' existe déjà et n'est pas un répertoire vide.
pi@raspberrypi:~ $ cd jarvis/
pi@raspberrypi:~/jarvis $ ./jarvish.sh -nv
bash: ./jarvish.sh: Aucun fichier ou dossier de ce type
pi@raspberrypi:~/jarvis $ 

Je n 'y connais rien donc je ne suis peut etre pas dans le bon dossier ou je n'ai peut etre pas la bonne commande de lancement.

Merci en tout cas de m'ouvrir les yeux

Bon we sous le soleil

Maël

**Comment by Oliv4945** [comment]
Que donne la commande `ls -al` quand tu es dans le dossier Jarvis ?
Sinon dans le doute tu peux supprimer le dossier avec `rm -rf jarvis` et refaire un git clone.

**Comment by alexylem** [comment]
Oui à mon avis tu as eu un soucis avec ton installation.
Fais comme suggère @Oliv4945 
```shell
$> cd
$> rm -rf jarvis
$> git clone https://github.com/alexylem/jarvis.git
$> cd jarvis
$> ./jarvis.sh

**Comment by maelade** [comment]
Merci pour vos conseils , je fais une clean install de rasbian et recommence le tuto , je vous tiens au courant , merci et profitez bien de ce beau soleil.

**Comment by alexylem** [comment]
Ok n'hésites pas à réouvrir le ticket si tu rencontres à nouveau ce pb!

**Comment by maelade** [comment]
merci

**Comment by maelade** [comment]
Je suis désolé de réouvrir ce ticket mais apres une réinstallation complete de rasbian et de jarvis , à nouveau j'ai un Jarvis à l'encéphalogramme plat...voila ce que j'ai avec la commande ls -alTraining model...
######################################################################## 100,0%
Completed
Updating...
Upgrading...
Downloading & Installing...
Checking updates for jarvis...pi@raspberrypi:~/jarvis $ 
pi@raspberrypi:~/jarvis $ ls -al
total 156
drwxr-xr-x 14 pi pi  4096 avril  9 22:54 .
drwxr-xr-x 19 pi pi  4096 avril  9 22:50 ..
-rw-r--r--  1 pi pi  3640 avril  9 22:47 CHANGELOG.md
drwxr-xr-x  2 pi pi  4096 avril  9 23:00 config
-rw-r--r--  1 pi pi  3960 avril  9 22:47 CONTRIBUTING.md
drwxr-xr-x  2 pi pi  4096 avril  9 22:47 docs
drwxr-xr-x  8 pi pi  4096 avril  9 22:48 .git
-rw-r--r--  1 pi pi   550 avril  9 22:47 .gitignore
drwxr-xr-x  2 pi pi  4096 avril  9 22:48 hooks
drwxr-xr-x  5 pi pi  4096 avril  9 22:47 imgs
-rw-r--r--  1 pi pi   310 avril  9 22:47 ISSUE_TEMPLATE
-rw-r--r--  1 pi pi   490 avril  9 22:48 jarvis-commands
-rw-r--r--  1 pi pi   490 avril  9 22:47 jarvis-commands-default
-rw-r--r--  1 pi pi   949 avril  9 22:47 jarvis-config-default.sh
-rw-r--r--  1 pi pi  2090 avril  9 22:48 jarvis-events
-rw-r--r--  1 pi pi  2090 avril  9 22:47 jarvis-events-default
-rwxr-xr-x  1 pi pi 34354 avril  9 22:47 jarvis.sh
-rw-r--r--  1 pi pi  1082 avril  9 22:47 LICENSE.md
drwxr-xr-x  2 pi pi  4096 avril  9 22:47 plugins
-rw-r--r--  1 pi pi  3922 avril  9 22:47 README.md
drwxr-xr-x  4 pi pi  4096 avril  9 22:47 recorders
drwxr-xr-x  2 pi pi  4096 avril  9 22:47 sounds
drwxr-xr-x  7 pi pi  4096 avril  9 22:47 stt_engines
drwxr-xr-x  2 pi pi  4096 avril  9 22:47 test
-rw-r--r--  1 pi pi   914 avril  9 22:47 TODO.md
drwxr-xr-x  7 pi pi  4096 avril  9 22:47 tts_engines
-rwxr-xr-x  1 pi pi  1186 avril  9 22:47 uninstall.sh
-rwxr-xr-x  1 pi pi  6636 avril  9 22:47 usbreset
drwxr-xr-x  2 pi pi  4096 avril  9 22:47 utils
-rw-r--r--  1 pi pi     9 avril  9 22:47 version.txt
pi@raspberrypi:~/jarvis $ 

Je veux bien tout refaire mais visiblement je loupe quelque chose de fondamental.

Merci du temps que vous passez à m'aider

**Comment by maelade** [comment]
j'ai réussi à avoir un Hello puis à nouveau ECG plat!!! et depuis que je suis resorti du terminal et relancé je n'ai à nouveau plus rien

 ~ Asciicast recording started.
~ Hit ctrl+d or type "exit" to finish.

pi@raspberrypi:~ $  ./jarvis.sh -v
bash: ./jarvis.sh: Aucun fichier ou dossier de ce type
pi@raspberrypi:~ $ 

Au moins les erreurs me font apprendre , je regarde les différents tickets , je teste je tente mais sans succes , je pense que seule votre lecture apportera vie à mon Jarvis .

Maël

**Comment by wikijm** [comment]
Bonjour @maleade,

Bienvenue dans la communauté :-)

Je vois que tu as lancé un enregistrement ASCIINEMA. C'est très bien, mais je pense que tu as oublié de nous donner le lien dé la vidéo ainsi créé :wink:

Je vois dans ton dernier log que tu utilise SnowBoy pour comprendre les ordres vocaux donnés à Jarvis (command_stt snowboy). Pour débuter, je te recommande fortement d'utiliser Bing, qui certes est une solution en ligne (connexion Internet obligatoire) mais qui rend ce processus bien plus simple et fonctionnel.

On attend ton retour :wink:

**Comment by Oliv4945** [comment]
Salut @maelade,

>pi@raspberrypi:~ $ ./jarvis.sh -v
bash: ./jarvis.sh: Aucun fichier ou dossier de ce type
pi@raspberrypi:~ $

Tu n'es pas dans le dossier jarvis, c'est donc normal que tu aies l'erreur. Il faut te déplacer dedans avec `cd jarvis/` à chaque fois que tu te reconnectes au Raspberry ;).
Pour savoir où tu te trouves tu peux taper `pwd ` (Print Working Directory) sinon ça ce voit après "raspberrypi:" sur l'invite. `~` tu es dans ton répertoire utilisateur, `~/jarvis` tu es dans le répertoire jarvis.

**Comment by maelade** [comment]
Merci à vous 3 de votre aide utile car mon " esclave " avance mais il ne s'est pas encore affranchi de ses chaines... 
wikijm je ne savais pas que je faisais du cinéma et je crois que je ne vais pas postuler à la statuette americaine !!! Je suis passé sous bing sur tes bons conseils

------------ Config ------------
jv_branch            master 
jv_version           17.04.08 
jv_arch              armv7l 
jv_os_name           raspbian 
jv_os_version        8 
language             fr_FR 
play_hw              hw:0,1 
rec_hw               hw:1,0 
speaker              ALSA 
microphone           Asahi Kasei Microsystems Co., Ltd  
recorder             snowboy 
trigger_stt          snowboy 
command_stt          bing 
tts_engine           svox_pico 
-------------------------------
Oliv4945 dans le bon dossier c'est clair qu'il trouve les bons fichiers , merci .

Ca avance mais j'ai toujours un Jarvis mutique 
hey jarvis: Waiting to hear 'hey jarvis'
Maeyl: (listening...)
DEBUG: models=hey jarvis
INFO:snowboy:Ticks: [2, 20, 5, -1]
INFO:snowboy:Keyword 1 detected at time: 2017-04-10 14:06:22
INFO:snowboy:No match - no voice before hotword
INFO:snowboy:Keyword 1 detected at time: 2017-04-10 14:07:07
INFO:snowboy:Keyword 1 detected at time: 2017-04-10 14:07:09
INFO:snowboy:Ticks status: 1 2 0 1
WARNING:snowboy:No match silence_before
INFO:snowboy:Keyword 1 detected at time: 2017-04-10 14:07:19
INFO:snowboy:No match - no voice before hotword
INFO:snowboy:Keyword 1 detected at time: 2017-04-10 14:07:27
INFO:snowboy:Ticks status: 2 1 0 1
DEBUG: modelid=0
hey jarvis
DEBUG: entering_cmd hook
Maeyl: (listening...)
DEBUG: start_listening hook
utils/timeout.sh 10 python  recorders/snowboy/main.py 05 /dev/shm/jarvis-record.wav 
Cannot connect to server socket err = No such file or directory
Cannot connect to server request channel
jack server is not running or cannot be started
__________________________________________________________________________DEBUG: stop_listening hook
play FAIL formats: can't open input file `/dev/shm/jarvis-record.wav': No such file or directory
ERROR: play command failed
HELP: Verify your speaker in Settings > Audio > Speaker

DEBUG: program_exit hook
pi@raspberrypi:~/jarvis $ 

Merci beaucoup pour votre aide à tous les 3 en espérant avoir un Jarvis vivant prochainement et surtout que d'autres s'inspirent de vos réponses quand ils reproduisent mes erreurs .

Merci

Mael

**Comment by wikijm** [comment]
C'est cette partie de ton log qui m'a mis la puce à l'oreille :
```
~ Asciicast recording started.
~ Hit ctrl+d or type "exit" to finish.
```

**Comment by alexylem** [comment]
```shell
recorder             snowboy 
```
Qu'est-ce que vous avez tous à utiliser les options "Underground" 😄 
Utilise `sox` stp dans `Settings > Audio > Record > sox`

**Comment by maelade** [comment]
Un pied devant l'autre Jarvis avance ( enfin plutot Alexa) car la reconnaissance se fait mieux. Je n'ai pas encore pu dépasser une interaction , je teste toutes les config audio ( sauf la bonne ...) je pense que mon micro n'est peut etre pas le top ( pourtant celui qui marche bien pour certains Andoer omni directional ) 
DEBUG: program_exit hook
pi@raspberrypi:~/jarvis $ ./jarvis.sh

------------ Config ------------
jv_branch            master 
jv_version           17.04.08 
jv_arch              armv7l 
jv_os_name           raspbian 
jv_os_version        8 
language             fr_FR 
play_hw              hw:0,1 
rec_hw               hw:1,0 
speaker              ALSA 
microphone           Asahi Kasei Microsystems Co., Ltd  
recorder             sox 
trigger_stt          snowboy 
command_stt          bing 
tts_engine           svox_pico 
--------------------------------

DEBUG: program_startup hook
alexa: Bonjour
DEBUG: start_speaking hook
DEBUG: stop_speaking hook
User defined commands:
*AIDE*			*BONJOUR*|*SALUT*	*COMMENT*APPELLE*
*MERCI*			*AU REVOIR*|*BYE*	ANNULE*|TERMINE*
ENCORE*			*TEST*			*VERSION*
*REPETE (*) ET (*)	*CA VA*			>*OUI*
>*NON*|*PAS*
alexa: Waiting to hear 'alexa'
Mael: (listening...)
DEBUG: models=alexa,alexa
INFO:snowboy:Ticks: [-1, -1, -1, -1]
INFO:snowboy:Keyword 2 detected at time: 2017-04-11 12:00:31
DEBUG: modelid=1
alexa
DEBUG: entering_cmd hook
alexa: oui
DEBUG: start_speaking hook
DEBUG: stop_speaking hook
Mael: (listening...)
DEBUG: start_listening hook
utils/timeout.sh 10 rec -V1 -q -r 16000 -c 1 -b 16 -e signed-integer --endian little /dev/shm/jarvis-record.wav gain 010 silence 1 0.1 7 1 0.6 10 trim 0 5
DEBUG: stop_listening hook
play FAIL formats: can't open input file `/dev/shm/jarvis-record.wav': WAVE: RIFF header not found
ERROR: play command failed
HELP: Verify your speaker in Settings > Audio > Speaker

DEBUG: program_exit hook
pi@raspberrypi:~/jarvis $ 


Je ne sais pas comment remedier à "play FAIL formats: can't open input file `/dev/shm/jarvis-record.wav': WAVE: RIFF header not found
ERROR: play command failed "

J'ai beau tester differentes choses dans settings /audio il foit y avoir autre chose qui échappe à un néophyte comme moi .

Merci encore pour votre aide à donner vie à mon esclave électronique .

Maël

**Comment by alexylem** [comment]
2 choses pour m'aider à t'aider:
1. Supprimer ce fichier pour qu'il soit recréé proprement
`$> rm /dev/shm/jarvis-record.wav`
2. un asciinema pour comprendre la dynamique
```shell
sudo apt-get install -y asciinema && asciinema rec # start session recording
./jarvish.sh -nv # start jarvis directly in troubleshooting mode
Ctrl+D # stop recording
y # yes to upload and get URL to paste here
```

**Comment by maelade** [comment]
Noobs je suis mais j'apprends... 
$> rm /dev/shm/jarvis-record.wav  comment dois je faire pour supprimer?
Question sans doute stupide mais je ne vois pas dans le finder , vu que depuis j'ai rebidouillé et changé et quand je teste cette ligne de commande j'ai comme réponse "fichier introuvable".

et voici la cinématique ( PS si d'autres ont le même problème  commande à taper ./jarvis.sh -nv et non ./jarvish.sh -nv pour lancer en mode troubleshooting) 

http://asciinema.org/a/5jowcdvqnso29h0mxpkt3tl7g

Je te remercie de passer ton temps à essayer de comprendre mes erreurs .

Cordialement Mael

**Comment by alexylem** [comment]
```shell
language                        
```
Dans ton log il n'y a pas de language.
Remets le dans Settings > General > Language

**Comment by maelade** [comment]
C'est génial , j'ai pu avoir un début de conversation avec snowboy !!!! merci beaucoup Alexandre pour ta patience . Visiblement , j'ai encore un petit bug car j'ai beau faire " $> rm /dev/shm/jarvis-record.wav " , il me l'enleve bien et si tu regardes tout en bas de la retranscription , il me remet le meme probleme. Mais que c'est bon de voir que cela avance . Encore merci

------------ Config ------------
jv_branch            master 
jv_version           17.04.12 
jv_arch              armv7l 
jv_os_name           raspbian 
jv_os_version        8 
language             fr_FR 
play_hw              hw:0,1 
rec_hw               hw:1,0 
speaker              ALSA 
microphone           Asahi Kasei Microsystems Co., Ltd  
recorder             sox 
trigger_stt          snowboy 
command_stt          bing 
tts_engine           svox_pico 
--------------------------------

DEBUG: program_startup hook
snowboy: Bonjour
DEBUG: start_speaking hook
DEBUG: stop_speaking hook
User defined commands:
*AIDE*			*BONJOUR*|*SALUT*	*COMMENT*APPELLE*
*MERCI*			*AU REVOIR*|*BYE*	ANNULE*|TERMINE*
ENCORE*			*TEST*			*VERSION*
*REPETE (*) ET (*)	*CA VA*			>*OUI*
>*NON*|*PAS*
snowboy: Waiting to hear 'snowboy'
Mael: (listening...)
DEBUG: models=snowboy,snowboy
INFO:snowboy:Ticks: [-1, -1, -1, -1]
INFO:snowboy:Keyword 2 detected at time: 2017-04-13 14:10:18
DEBUG: modelid=1
snowboy
DEBUG: entering_cmd hook
snowboy: oui
DEBUG: start_speaking hook
DEBUG: stop_speaking hook
Mael: (listening...)
DEBUG: start_listening hook
utils/timeout.sh 10 rec -V1 -q -r 16000 -c 1 -b 16 -e signed-integer --endian little /dev/shm/jarvis-record.wav gain 05 silence 1 0.1 7 1 0.6 7 trim 0 5
DEBUG: speech duration was 07 (10 = 1 sec)
DEBUG: stop_listening hook
DEBUG: curl https://speech.platform.bing.com/recognize/query?version=3.0&requestid=425c9e5c-4b28-44fc-9119-5f8418968fa7&appid=D4D52672-91D7-4C74-8AD8-42B1D98141A5&format=json&locale=fr-FR&device.os=linux&scenarios=ulm&instanceid=E043E4FE-51EF-4B74-8133-B728C4FEA8AA&result.profanitymarkup=0
DEBUG: json={"version":"3.0","header":{"status":"error","properties":{"requestid":"28eceed6-a9fd-4286-8ac1-fc57fcfaa1e3","NOSPEECH":"1"}}}
?(listening...)
DEBUG: start_listening hook
utils/timeout.sh 10 rec -V1 -q -r 16000 -c 1 -b 16 -e signed-integer --endian little /dev/shm/jarvis-record.wav gain 05 silence 1 0.1 7 1 0.6 7 trim 0 5
DEBUG: stop_listening hook
DEBUG: timeout, end of conversation
DEBUG: listening_timeout hook
DEBUG: exiting_cmd hook
snowboy: Waiting to hear 'snowboy'
Mael: (listening...)

...
yo boy quelle heure est-il
snowboy: je ne comprends pas: yo boy quelle heure est-il
DEBUG: start_speaking hook
DEBUG: stop_speaking hook
*OUI*			*NON*|*PAS*
Mael: (listening...)
DEBUG: start_listening hook
utils/timeout.sh 10 rec -V1 -q -r 16000 -c 1 -b 16 -e signed-integer --endian little /dev/shm/jarvis-record.wav gain 05 silence 1 0.1 7 1 0.6 7 trim 0 5
DEBUG: stop_listening hook
play FAIL formats: can't open input file `/dev/shm/jarvis-record.wav': WAVE: RIFF header not found
ERROR: play command failed
HELP: Verify your speaker in Settings > Audio > Speaker

Merci à nouveau et j'ai l'impression qu'il ne reste qu'une petite marche à franchir pour une totale indépendance et apres à moi les commandes https à defaut de pouvoir piloter ma zibase , imperihome et autre domotique. J'ai vu aussi que Jarvis pouvait fonctionner avec ma freebox. Merci à tous.

**Comment by alexylem** [comment]
Laisse tomber le `rm`, ton pb est ailleurs.
Bon déjà je vois que tu as 2 modèles nommmés "snowboy"
```
DEBUG: models=snowboy,snowboy
```
Je sais pas comment tu t'es débrouillé mais bon... ca sent que t'as pas mal bidouillé 😄 

C'est vraiment bizarre cette histoire de `RIFF header not found`. Un autre utilisateur a eu ce pb (voir #508) et l'a résolu en "*chmodant*" le répertoire `/dev/shm`
J'ai pas plus de détail que ca.

Tu peux:
```shell
$> ls -al /dev/shm
```

**Comment by maelade** [comment]
Bonjour Alexandre , 
et bien j'ai un Jarvis qui fonctionne sur 3 pattes ( il ne reconnait pas tout ce que je lui dis) mais qui fonctionne : il écoute , il entend , il répond et il execute ( un véritable petit esclave) . Nous allons tous les 2 nous apprivoiser , le lancement des ordres et l'exécution https..zibase fonctionne bien et rapidement . 
Je vais maintenant prendre mon temps pour découvrir tout ce que la communauté met à disposition. Je tenais à te remercier non seulement pour la patience que tu as à répondre à nos problèmes mais aussi pour ce superbe projet que tu as créé et que tu fais vivre . Je remercie aussi les autres contributeurs ( Oliv4945 et wikijm ) pour vos réponses .

Je propose que tu fermes le ticket .

Cordialement

Mael

**Comment by alexylem** [comment]
Tout le plaisir est pour nous, merci d'avoir cité @Oliv4945 et @wikijm qui font en effet un travail remarquable!

**Comment by wikijm** [comment]
@maelade Comme l'a dit @alexylem, tout le plaisir est pour nous 😄 

Si jamais tu souhaites participer aux frais liés à la conduite du projet (notamment le nom de domaine domotiquefacile.fr), il est possible de faire un don en passant par la page http://domotiquefacile.fr/jarvis/ (comme tu peux le voir, @alexylem ne demande rien, mais je pense que reconnaitre son travail de la sorte est naturel).

Sinon, un coup de pub sur les forum et réseaux sociaux est toujours apprécié 😉

**Comment by maelade** [comment]
Et je pense comme vous pour les frais , donc don sera fait😋

Envoyé de mon iPhone
