### ISSUE TITLE
hooks : start_speaking

### ISSUE THREAD

**Issue by energy01** [alexylem/jarvis#533]
### Description

il manque une info en paramètre du hooks start_speaking dans le script utils/utils.sh
dans la fonction say () 
il fait appel à jv_hook "start_speaking"
mais on ne dispose pas dans ce "hooks" de variable avec l'ensemble de la phrase "dite"
si c'est un ordre on aura avec $order l'ordre interprété mais pas la phrase complète qui va être dite surtout si cela utilise une des phrases configurée par défaut ou utilisant le $username

### Result
une proposition de modification ajouter en paramètre la texte complet comme cela par exemple :
jv_hook "start_speaking" "$1"

permet ensuite dans le hooks d'utiliser le paramètre $2 pour récupérer la phrase entière

PS : super boulot et vraiment bien conçu et relativement simple a mettre en oeuvre et même a rentrer dans le code qui est très propre bravo et merci

@+
Anthony.

**Comment by alexylem** [comment]
@energy01 excellente idée, j'ajoute ca de suite

**Comment by alexylem** [comment]
Note: j'ai fait un `shift`, donc utilise `$1` au lieu de `$2`

**Comment by energy01** [comment]
Super merci super réactif nickel 
PS : je viens de faire un update du master et du coup jarvis ne me reconnais plus ... du coup j'ai essayer en beta aussi et rien non plus

je n'ai semble-t-il plus de soucis
au départ la langue était à blanc et donc le pico2wave posais problème
mais là en debug : 
------------ Config ------------
jv_branch            master
jv_version           17.04.08
jv_arch              armv7l
jv_os_name           raspbian
jv_os_version        8
language             fr_FR
play_hw              hw:0,0
rec_hw               hw:1,0
speaker              ALSA
microphone           Intel Corp.
recorder             snowboy
trigger_stt          snowboy
command_stt          bing
tts_engine           svox_pico
--------------------------------

Starting RestAPI server on http://192.168.1.20
192.168.1.46:8082
Starting User Interface on http://192.168.1.20
192.168.1.46:8081


j'ai refait la config step by step mais toujours rien ...

je devrais peut-être ouvrir un autre ticket ?

merci encore
@+
Anthony.

**Comment by alexylem** [comment]
heu... quoi ca s'arrête la?
dans le doute essaye:
```shell
$> git pull
```
Un asciinema serait appréciable:
```shell
sudo apt-get install -y asciinema && asciinema rec # start session recording
./jarvish.sh -nv # start jarvis directly in troubleshooting mode
Ctrl+D # stop recording
y # yes to upload and get URL to paste here
```

**Comment by energy01** [comment]
euh non c'est un peu plus long 
sympa le asciinema connaissais pas !!
[http://asciinema.org/a/67dh4dpou4hlq12dxk0xv91sv](url)

**Comment by alexylem** [comment]
Aucune réaction au hotword Jarvis? Alors que ca marchait avant?
Tu avais modifié le gain? Peut-être que tu l'as perdu, tu peux le refaire dans Settings > Audio > Auto-adjust.

**Comment by energy01** [comment]
oui aucune réaction au hotword et ça marchais avant c'est exactement mon
problème

j'avais pourtant tout refait via "step-by-step" donc cette étape de config
du gain aussi et là ça fonctionne l'option

mais après rien ne reconnais plus "Jarvis"

je viens de refaire toute la conf step-by-step" une fois de plus
et toujours rien ...

pour le gain j'ai ça :
`
  │
Results:                                                                 │
  │ - Silence level: 4% (max
5%)                                             │
  │ - Voice volume: 68% (min 50%, max
95%)                                   │
  │ Sox
parameters:                                                          │
  │ - Microphone gain:
23                                                    │
  │ - Min noise percentage to start:
9%                                      │
  │ - Min silence percentage to stop:
9%                                     │
`
j'ai aussi refait le "train hotword" pour Jarvis !!

une idée comme ça : j'ai l'impression pour refaire le hotword cela ne prend
pas le gain du micro


<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Garanti
sans virus. www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

Le 10 avril 2017 à 21:25, Alexandre Mély <notifications@github.com> a écrit
:

**Comment by energy01** [comment]
j'ai du jouer avec les paramètres du micro et donc 
en mettant tout par défaut et recommencer "propre" toute la procédure et le train hotword ça refonctionne ...
merci pour ton aide 
et pour revenir au sujet de l'issue donc ta modif pour le paramètre du hook
cela fonctionne très bien merci 
j'en avais besoin car je m'amuse a faire une "interface" avec une matrice led branché sur le pi 
comme ça : https://images-na.ssl-images-amazon.com/images/I/61Tc9OUYwdL._SX522_.jpg
permet d'afficher ce que l'on veux soit le texte soit ce que j'essaye de faire une "bouche" qui donne l'impression de parler ...
et donc il me fallait le texte complet qui est dit pour l'analyser et afficher la bouche suffisamment longtemps en fonction de la longueur de la phrase
@+
Anthony

**Comment by alexylem** [comment]
>une idée comme ça : j'ai l'impression pour refaire le hotword cela ne prend
pas le gain du micro

Tu as raison c'est un bug, je vais corriger.

>j'en avais besoin car je m'amuse a faire une "interface"

Super, tu peux aussi jeter un oeil à:
http://domotiquefacile.fr/jarvis/plugins/face

**Comment by alexylem** [comment]
Implémenté sur la branch `beta`. Pour le tester dès à présent:
Menu `Settings > General > Branch > beta`
Sinon attendre la mise à jour de ce weekend.
