### ISSUE TITLE
Jarvis Android app

### ISSUE THREAD

**Issue by Oliv4945** [alexylem/jarvis#534]
Hi,
I thought it would be nice to have an Android app in order to be more dedicated than the non open-source Tasker, so I am working on it.

~~If you can test the very preliminary beta to confirm that it works on most installations.~~
~~1. Download it  [here](https://iopush.net/temp/170409_Jarvis.apk).[...]~~
Please find installation instruction [here](https://github.com/Oliv4945/jarvis-android-app#installation)

Their is a lot of work still required:

- [x] Conversation display like Jarvis-ui
- [x] Mute & un-mute local/remote TTS
- [ ] Set TTS voice regarding Jarvis' locale instead of phone's locale
- [x] Add possibility to use a secret key
- [x] Add a return button in PreferencesActivity
- [x] Add a preference to start STT with the app
- [ ] Any other idea ?

**Comment by alexylem** [comment]
@Oliv4945 wow thanks for this great initiative!
Do you plan to publish it on Google Play? Do you need to pay for this?
Any screenshot?
Please also consider embedding "Jarvis-UI" which already has most of your TODO list.

**Comment by Oliv4945** [comment]
Thanks @alexylem 
>Do you plan to publish it on Google Play? Do you need to pay for this?

If it is useful, yes I can publish it.
I think there is a (small?) one time fee, I never did it but I will check.

>Please also consider embedding "Jarvis-UI" which already has most of your TODO list.

I considered it but I don't think it can be ported to Android Java, or at least I don't know how.
I  updated the todo list in my first post. Please find today's release [here](https://iopush.net/temp/170410_Jarvis.apk)

What application name should I use ? Jarvis ?
Do you have an higher resolution icon than [this one](http://domotiquefacile.fr/jarvis/sites/default/files/jarvis_logo_icon.png) ?

>Any screenshot?

Here you go, but the best way is to try it if you have an Android device :p
![screenshot_2017-04-10-22-12-55_net iopush jarvis](https://cloud.githubusercontent.com/assets/6248122/24880889/5fe6d398-1e3c-11e7-9bab-9a74bea8b6ad.png)

**Comment by alexylem** [comment]
>I think there is a (small?) one time fee

Depending on the price, I can sponsor using donation of users

>I don't think it can be ported to Android Java

I was not proposing to port it, but to embed it (there must be a way to display a web page in an app). If needed I can evolve this plugin so that you can pass the recognized voice order in parameter, so that you keep your mic button native.

>Do you have an higher resolution icon

![jarvis_logo_red](https://cloud.githubusercontent.com/assets/11017174/24894758/b14f7b54-1e8c-11e7-998b-330fb2cda66e.png)

>best way is to try it if you have an Android device

I don't that's why I asked 😄

**Comment by Oliv4945** [comment]
>Depending on the price, I can sponsor using donation of users

Thank you for the proposition. It is $25... consider it as my donation :-)
I will publish the app when it will be more polished and I have feedback confirming that it works for others. Maybe you can put a message on this [page](http://domotiquefacile.fr/jarvis/content/voice-control-from-android-device) to request beta testers ?

>I was not proposing to port it, but to embed it (there must be a way to display a web page in an app). If needed I can evolve this plugin so that you can pass the recognized voice order in parameter, so that you keep your mic button native.

There is a way to embed a navigator inside an app, but it seems that jQuery/Ajax does not run well inside, moreover the app will be simple because everything is handled by jarvis-api. I added a basic "conversation view" yesterday, so now it is just about adding few parameters and a good looking UI.

Maybe adding Jarvis-face in a second time might be fun :p

**Comment by wikijm** [comment]
This is very generous, thanks a lot @Oliv4945, I'm pretty sure that the community will appreciate a lot your gesture  :kissing_heart:

**Comment by alexylem** [comment]
@Oliv4945 wow thanks a lot for this donation!! it is the highest recorded to-date ❤️ 👏 
I have added your name in:
http://domotiquefacile.fr/jarvis/content/credits

>Maybe you can put a message on this page to request beta testers ?

Added new page:
http://domotiquefacile.fr/jarvis/content/control-jarvis-using-android-app
Give me your domotiquefacile username if you want to have write access.

**Comment by Oliv4945** [comment]
>I have added your name in:

Thanks, but it is not done for now, and it is because your project worth it !

>Added new page:

Great, I just registered with `Oliv4945`

The app have now a conversation mode... Had to fight with Android themes but it works, just some cosmetics to finish !! Apk available [here](https://iopush.net/temp/170412_Jarvis.apk)

Screenshot:
![screenshot_2017-04-13-00-18-25_net iopush jarvis](https://cloud.githubusercontent.com/assets/6248122/24982126/2855c4ca-1fe0-11e7-92a2-29aac11c64c2.png)

**Comment by wikijm** [comment]
Last version crash directly at startup.
I try to using it on SAMSUNG GALAXY S5 with you Android 6.0.1.
I'll be able to test on S3 later.

Is your app generate some log?

**Comment by alexylem** [comment]
@Oliv4945 you now have write access to:
http://domotiquefacile.fr/jarvis/content/control-jarvis-using-android-app

**Comment by Oliv4945** [comment]
> I try to using it on SAMSUNG GALAXY S5 with you Android 6.0.1.

I tried yesterday on Android 5 & 7, so I hoped it should be ok for 6 :'(

> Is your app generate some log?

There is no specific error handling for now, neverthelless I lived debug options enables in the apk so:
- If use use ADB (Android Debug Bridge) it is easy thanks to `adb -d logcat "net.iopush.Jarvis:*" *:S`
- If not, you need to
  - Install [this application](https://play.google.com/store/apps/details?id=com.tortel.syslog&hl=fr)
  - Start Jarvis (wait for the crash)
  - Start Syslog, then `Take log`
  - It will allow you to send an email, inside the zip please send me the file named logcat.txt.
  - Data should be anonymous (I did not verified) so if you fear about it before `Take log` you can select `grep the following log:`->`All logs` and in `Grep string` field put `Jarvis` and have should have enough info... never tested it :p
I know it is lot of steps but it can help me a lot, thank you for your help. Did the [previous apk](https://iopush.net/temp/170410_Jarvis.apk) worked ?

I have created a Github repo, so issues can be reported [there](https://github.com/Oliv4945/jarvis-android-app).

**Comment by wikijm** [comment]
The previous apk worked like a charm.
Don't worry about all those steps, i'll do it with pleasure 😉 (certainly with results on your repo).

**Comment by PsykonoyaK** [comment]
The same for me. Crash when launching the app.
Tested on Samsung S7 Edge - Android 7.0

I also catched logcat.txt using "all logs" mode but there is no "Jarvis" or "iopush" strings in it.

**Comment by Oliv4945** [comment]
Ok, simple anwer : the apk file is corrupted :/
The file size is 500 ko instead of a bit more than 2 Mo for the previous versions. I just tried on my phone and it does not work if I install it from the apk too. Please wait the evening I will regenerate it :) Sorry.

It seems that we can not see full log with Syslog app if we are not root. So @wikijm are you root user, and @PsykonoyaK not ?

> I invite you to use "Release" functionnality, to share few version of .apk.
I'll try, thanks

**Comment by PsykonoyaK** [comment]
Indeed, my phone isn't rooted. :)
I can not wait to test your app tonight!
++

**Comment by wikijm** [comment]
A root user, I use, on the dark side I am 😜

**Comment by Oliv4945** [comment]
Ok, non corrupted apk uploaded in the [same place](https://iopush.net/temp/170412_Jarvis.apk), tried it on my phone and it works now,. Keep me [updated in this issue please](https://github.com/Oliv4945/jarvis-android-app/issues/3),
Sorry for the delay it will be better with Google Play :p

**Comment by Oliv4945** [comment]
>@Oliv4945 you now have write access
@alexylem : Thank you but how can I edit the page ? I do not see any button or link for that. Thank you

**Comment by PsykonoyaK** [comment]
I tried the app after reupload and it works perfectly.
I also appreciate the voice return. 
Good job!

**Comment by Oliv4945** [comment]
New release [v0.1.2](https://github.com/Oliv4945/jarvis-android-app/releases/tag/v0.1.2)

@wikijm : Thank you for your device report. Would you mind to fill an issue for your HP Touchpad ?

**Comment by wikijm** [comment]
@Oliv4945 Fixed for HP Touchpad. I was using an OS without Google Apps, including Google Voice Recognition. After installing [OpenGApps.org](http://opengapps.org/) nano package, everything's works fine.

**Comment by alexylem** [comment]
@Oliv4945 I'm so sad not being able to test it out, would you consider sharing a demo video?

**Comment by Oliv4945** [comment]
@wikijim: ok, thank you
@alexylem: I'll check how to make a screencast in Android. You can test it thanks to an Android emulator or maybe try http://anbox.io

The app has been reported to work on phones and some tablets, so I have some minor cosmetic upgrades to do and will publish it on play store.

**Comment by Oliv4945** [comment]
Hi, [v0.1.3 is released](https://github.com/Oliv4945/jarvis-android-app/releases/tag/v0.1.3), please check release page for the change log.
If I sort out @jean-luc18 issue it should be the first release for Google Play store.

Also, I am [still looking ](https://github.com/Oliv4945/jarvis-android-app/issues/4)for translators :p

@alexylem : How can I edit [this](http://domotiquefacile.fr/jarvis/content/control-jarvis-using-android-app) page ? I do not see any "edit" link. Thanks

**Comment by alexylem** [comment]
@Oliv4945 try again with your "Oliv4945" user. It was an issue on my side.

**Comment by jean-luc18** [comment]
Bonjours,

V.0.1.3 installed but no changes.
Works correctly, misses written feedback and oral feedback.
Message at the bottom of the screen: "Json parsing error: No value for Jarvis"

Slts

**Comment by Oliv4945** [comment]
@jean-luc18 : New issue started [here](https://github.com/Oliv4945/jarvis-android-app/issues/9), could you please answer ?
@alexylem : It works, thank you

**Comment by Oliv4945** [comment]
New release fixing two issues : [v0.1.4](https://github.com/Oliv4945/jarvis-android-app/releases/tag/v0.1.4)

**Comment by RobyBioloid** [comment]
Has you publish it on google play store ?

I don't find it

**Comment by Oliv4945** [comment]
@RobyBioloid : Not yet. I am still solving bug reports.
You have to manually download it, instructions [here](https://github.com/Oliv4945/jarvis-android-app).

**Comment by Oliv4945** [comment]
New release [v0.1.5](https://github.com/Oliv4945/jarvis-android-app/releases/tag/v0.1.5).
Fix a huge bug when using 'Start STT with the app' option.

**Comment by Oliv4945** [comment]
New release [v0.2.0](https://github.com/Oliv4945/jarvis-android-app/releases/tag/v0.2.0)
Application prepared for Play Store, account opened, just waiting for Alexylem answer on future name :-)

**Comment by Oliv4945** [comment]
New release [v0.2.1](https://github.com/Oliv4945/jarvis-android-app/releases/tag/v0.2.1)
Bug correction on big screens.

**Comment by benoit34000** [comment]
Bonjour,
une appli android, c'est vraiment une super bonne idee !  Bravo au dev !

Moi j'ai un soucis, j'arrive pas a communiquer avec le plugin, je comprend pas.
le plugin jarvis-api est bien installé, il fonctionne bien avec le plugin jarvis-ui.
Par contre, je n'arrive pas a le faire communiquer avec l'apk. J'ai essayé avec mon telephone et ma tablette. J'ai des logs (cf ci-dessous), donc la requete part bien du telephone vers jarvis, mais l'appli me repond a chaque fois "verifier le port et l'ip du serveur".
Les parametres sont bon, j'ai essayer de changer le port, de mettre ou pas un cle (cote client et cote plugin, bien sur). Bref, je comprend pas..
J'ai la release v0.2.1
Et c'est normal que dans le get ou le post, on ne voit pas le contenu de ma phrase ?
Bref, j'ai du raté un truc, mais je vois pas quoi...Si vous avez une idee merci d'avance !
Benoit.


192.168.0.50 - - [08/May/2017 16:38:43] "GET /?action=get_config&key=1234567890 HTTP/1.1" 200 -
192.168.0.50 - - [08/May/2017 16:38:53] "POST / HTTP/1.1" 200 -
192.168.0.50 - - [08/May/2017 16:38:53] "GET /?action=get_config&key=1234567890 HTTP/1.1" 200 -
192.168.0.50 - - [08/May/2017 16:38:53] "GET /?action=get_config&key=1234567890 HTTP/1.1" 200 -
192.168.0.50 - - [08/May/2017 16:38:58] "POST / HTTP/1.1" 200 -

**Comment by Oliv4945** [comment]
Bonjour Benoît, merci de ton retour encourageant.
Pour ton problème j'ai ouvert un ticket [ici](https://github.com/Oliv4945/jarvis-android-app/issues/13), si on peut y continuer la discussion ça permet d'isoler les soucis. Merci :)

**Comment by NikoS34** [comment]
Bonjour Oliv', c'est du très bon boulot et une telle appli mobile manquait vraiment pour ce super projet qu'est Jarvis !
J'ai testé sans souci ta version v0.2.1 sur plusieurs devices Android (post correspondant mis à jour), quelques petites remarques :
- dans les "Preferences" (qui d'ailleurs s'appelle "Options" dans le menu...) ça serait cool de pouvoir gérer plusieurs profils (ip/port/...) pour choisir le PI à "piloter" avec ton appli ?
- "Ne pas répondre dans l'application" coupe effectivement le TTS dans l'appli mobile, mais je m'attendais donc à retrouver le TTS sur le PI or ce n'est à priori pas le cas, normal ou pas ?
- Je n'ai pas trouvé d'effet visible à "Ne pas répondre sur le serveur" ?
- l'affichage de l'historique des questions/réponses peut être sympa mais ça serait mieux si on pouvait choisir ou pas cet affichage (avec une limite ?) dans les "Preferences".
- une petite proposition pour activer le micro sans toucher le bouton : détecter un "shake"...
- le support du mode "conversation" de Jarvis est-il envisagé ???

Merci.

**Comment by Oliv4945** [comment]
@NikoS34 
>Bonjour Oliv', c'est du très bon boulot et une telle appli mobile manquait vraiment pour ce super projet qu'est Jarvis !

merci :-)

De bonnes idées, j'ai créé un sujet [ici ](Bonjour Oliv', c'est du très bon boulot et une telle appli mobile manquait vraiment pour ce super projet qu'est Jarvis !) pour en discuter. Si d'autres veulent en parler ou proposer d'autres sujets

**Comment by alexylem** [comment]
Je rêvais de pouvoir tester ton app et je n'ai pas android.
Mais j'ai trouvé un émulateur en ligne qui me permet de le faire:
https://www.manymo.com
![image](https://cloud.githubusercontent.com/assets/11017174/25916011/93477938-35c3-11e7-8981-2abc85522ef3.png)

**Comment by Oliv4945** [comment]
@NikoS34 : Deux soucis de réglés dans la nouvelle version [v0.2.2](https://github.com/Oliv4945/jarvis-android-app/releases/tag/v0.2.2)
@alexylem : Super ! J'avais essayé pour voir, les émulateurs était toujours occupés :/ ça fonctionne du coup ? Reconnaissance et audio inclus ?

**Comment by Oliv4945** [comment]
Application is available on Google Play Store :p
See [it here](https://play.google.com/store/apps/details?id=net.iopush.jarvis)

**Comment by alexylem** [comment]
Site page updated:
http://domotiquefacile.fr/jarvis/content/control-jarvis-using-android-app
![image](https://cloud.githubusercontent.com/assets/11017174/26218917/08bed07c-3c0d-11e7-881e-20d66abcddac.png)

**Comment by sebogoss11** [comment]
J'ai un problème avec l'application mais aussi en API sur un navigateur..et même problème avec le tuto sur TASK.
Mon problème est le suivant : je mets bien l'adresse ip et le port et ensuite je test : "Bonjour" il est censé me répondre "bonjour sebastien" sur la raspberry pi3 sauf qu'il me dit : "erreur je ne cromprends pas 'bonjour' " (franchement j'espère que c'est une blague)  et il m'affiche : ERROR: No JSON object could be decoded
Et quand j'écris dans la console "Bonjour" il me répond bien "bonjour sebastien"

C'est très embêtant :/

**Comment by Oliv4945** [comment]
Bonsoir @sebogoss11 

Si le problème est aussi présent sur le navigateur, c'est donc Jarvis API. Merci de poster la question [ici](https://github.com/alexylem/jarvis-api/issues), et de ne pas faire deux issues pour la même chose.

**Comment by NathanCrombez** [comment]
Hi, 
Great work, it works like a charm on my Nexus 5 :)
Just one thing that I didn't check, does it work on conversation mode ? You know when yo first press the vocal command button, say a command, Jarvis say or do something and then Jarvis is waiting for another answer. How does it work in that case, do you have to press the vocal command button once again ?
 I mean in this case : 
*CA VA*==say "très bien et toi?"
>*OUI*==say "ravi de l'entendre"
>*NON*==say "j'en suis navré, dois-je te laisser tranquille?"
>>*OUI*==say "Au revoir $username"; exit
>>*NON*==say "Ok je reste"

Thanks

**Comment by Oliv4945** [comment]
@NathanCrombez good question...
I never tried but it should work by pressing the mic button each time you want to answer. Test and tell me :-)

**Comment by NathanCrombez** [comment]
@Oliv4945 I just tried and it works perfectly :) You just have to press the mic button for each answer. Very good work, thank you ;)

**Comment by RobyBioloid** [comment]
Salut!

Super boulot :)

Est-il possible d'ajouter la fonctionnalité "say" pour faire parler Jarvis ?

**Comment by domotic-29** [comment]
Bonjour,

Merci  Oliv pour cette application qui fonctionne bien sur un appareil récent.
Serait-il possible de la rendre compatible avec Android version 1.6 ?

**Comment by Oliv4945** [comment]
Salut,

Android 1.6 date d'il y a...8 ans. J’essaierai la prochaine fois que je
recompile, mais je n'y crois pas trop

**Comment by fredericsuretat** [comment]
bonjour j'ai egalement un petit soucis. applicatio  installée, jarvis installe sur une raspberry pi le plugin ui fonctionne impec mais quand je test avec l'appli android j'ai le desormais celebre message flash "ERROR: No JSON object could be decoded" (samsung galaxy s8 avec option ne pas repondre sur le serveur activée)

**Comment by Oliv4945** [comment]
@fredericsuretat : sujet traité dans une autre issue que vous avez ouverte.

Je ferme ce sujet vu que l'application est publiée
