### ISSUE TITLE
Commandes vocales

### ISSUE THREAD

**Issue by funky80000** [alexylem/jarvis#535]
Bonjour,

je m'arrache les cheveux et je crois que je suis un peu bête...

J'ai installé le plugin jarvis sur jeedom.
J'avais déjà installé jarvis manuellement sur ma debian (raspberry pi3), je l'ai écrasé depuis via le plugin jeedom.
Mon hotword (jarvis) est bien reconnu par mon micro, aucune commande n'est reconnue ensuite.
J'ai essayé avec snowboy, bing et google pour la reconnaissance vocale, aucun ne fonctionne.
A part snowboy qui prend des commandes enregistrées, bing et google devraient être capable de répondre à n'importe quelles questions ?
Concernant les commandes dans jeedom, il s'agit des intéractions ?

Merci de votre aide

**Comment by wikijm** [comment]
@funky80000 Je ne connais pas ce plugin Jarvis dans Jeedom, tu peux communiquer le lien ?

**Comment by wikijm** [comment]
![jeedom-plugin-jarvis](https://cloud.githubusercontent.com/assets/10724809/24852695/b9623aca-1dd8-11e7-8ce6-e0bde2a78fc1.png)
Si tu parle de ce plugin, celui-ci n'a pas de rapport avec Jarvis fait par @alexylem

**Comment by wikijm** [comment]
Les commandes sont à intégrer dans le fichier ./jarvis/jarvis-commands

**Comment by funky80000** [comment]
sous quelle forme avez vous un exemple ?

**Comment by wikijm** [comment]
J'en connais un qui n'a pas lu les docs 😜 
http://domotiquefacile.fr/jarvis/content/commands

**Comment by funky80000** [comment]
Merci pour ton aide très gentil.
je regarde ça ce soir merci encore

**Comment by alexylem** [comment]
@wikijm en fait le plugin Jarvis de Jeedom est bien lié à Jarvis, il installe Jarvis et permet de le configurer depuis Jeedom. Je suis en contact avec son auteur pour en reprendre le développement.
En attendant, je recommande d'installer Jarvis manuellement et d'utiliser le plugin Jeedom de Jarvis.

**Comment by funky80000** [comment]
merci, j'avais fait l'installation manuellement et n'arrivant pas à le faire fonctionner je l'ai écrasé à partir du plugin.
je n'arrive pas à ajouter de commandes dans le plugin jarvis, dans la partie commandes je n'arrive pas à ajouter d'interactions.
dans jarvis-commands, je n'ai rien du coup quand je l'interroge il ne comprends rien.
je pensais également que la reconnaissance vocale avec bin g permette de poser n'importe quelles questions...

**Comment by funky80000** [comment]
![capture](https://cloud.githubusercontent.com/assets/27192738/24896445/4084c9a2-1e95-11e7-8422-f1254e8691ad.JPG)

**Comment by funky80000** [comment]
User defined commands:
                        (*)                     *MERCI*
*COMMENT*APPELLE*       *BONJOUR*|*SALUT*       *AU REVOIR*|*BYE*
*TEST*
Commands from plugin jarvis-jeedom:
*
Benoit: MERCI
jarvis: Désolé je n'ai pas compris
Benoit: TEST
jarvis: Je ne comprends pas

**Comment by funky80000** [comment]
c'est ok j'ai enfin pigé...

merci a tous

**Comment by wikijm** [comment]
@funky80000 Un petit retour sur la solution que tu as trouvé ?
Qu'est ce qui clochait ?

**Comment by funky80000** [comment]
euh probleme avec le fichier jarvis-commands et probleme avec mes interactions.
je n'avais pas saisi la différence entre les commandes que l'on apprend à jarvis du genre bonjour etc et les commandes qu'il utilise venant de jeedom avec leurs noms exactes.

**Comment by wikijm** [comment]
OK, merci 👍
