### ISSUE TITLE
snowboy_stt command not found et play_hw mal défini

### ISSUE THREAD

**Issue by d31r** [alexylem/jarvis#536]
Bonjour,

Voici l'erreur que j'ai en essayant de faire tourner jarvis:

![image](https://cloud.githubusercontent.com/assets/26969691/24865518/d04d306c-1e07-11e7-826c-421491b94f26.png)

pourtant le fichier .asoundrc est bien configuré, j'entend et j'arrive à enregistrer ma voix correctement.
![image](https://cloud.githubusercontent.com/assets/26969691/24865567/effa7dca-1e07-11e7-8a54-2993e4784cb1.png)

Je suis nouveau dans tout cela, alors ça peut être un erreur débile de débutant!
Dans le fichier jarvis.sh, je n'ai rien modifié (erreur ligne 736)

![image](https://cloud.githubusercontent.com/assets/26969691/24865696/4c619b0c-1e08-11e7-8fd6-2a57c8b45312.png)

Merci !

**Comment by wikijm** [comment]
Bonjour @d31r,

Tout d'abord, merci de respecter ce qui est demandé lors de la création d'issue, à savoir :
- Coller le résultat du mode troubleshooting
OU
- Créer une vidéo à l'aide d'ASCIINEMA et partager le lien de la vidéo

Sinon, tes erreurs Snowboy sont liées au fait que le périphérique servant à jouer le son est mal défini (voir ligne 11 de ta 1ère capture, `play_hw   hw:` qui devrait ressembler à `play_hw   hw0:0`)

**Comment by d31r** [comment]
Salut @wikijm ,

Merci de ta réponse.

Excuse moi, c'est mon premier poste sur github et je viens de débuter avec linux et raspberry pi.

Pourrais-tu me montrer comment changer le play_hw stp?

Cela peut avoir l'air débile mais comme je t'ai dit, je suis débutant! 

merci encore

ps: la première capture est l'écran qd j'ai lancé jarvis en troubleshoot

**Comment by d31r** [comment]
@wikijm ,

Voici les options pour sélectionner les haut parleurs : 
`Selection of the speaker device
**** List of PLAYBACK Hardware Devices ****
card 0: ALSA [bcm2835 ALSA], device 0: bcm2835 ALSA [bcm2835 ALSA]
  Subdevices: 8/8
  Subdevice #0: subdevice #0
  Subdevice #1: subdevice #1
  Subdevice #2: subdevice #2
  Subdevice #3: subdevice #3
  Subdevice #4: subdevice #4
  Subdevice #5: subdevice #5
  Subdevice #6: subdevice #6
  Subdevice #7: subdevice #7
card 0: ALSA [bcm2835 ALSA], device 1: bcm2835 ALSA [bcm2835 IEC958/HDMI]
  Subdevices: 1/1
  Subdevice #0: subdevice #0
Indicate the card # to use [0-9]: 0
Indicate the device # to use [0-9]: 1
Updating ~/.asoundrc...
utils/utils.sh: line 170: /home/pi/.asoundrc: Permission denied
Reloading Alsa...

sounds/applause.wav:

 File Size: 463k      Bit Rate: 1.41M
  Encoding: Signed PCM
  Channels: 2 @ 16-bit
Samplerate: 44100Hz
Replaygain: off
  Duration: 00:00:02.62

In:35.4% 00:00:00.93 [00:00:01.69] Out:41.0k [-=====|=====-] Hd:3.7 Clip:0

`

J'arrive quand même à entendre le son

**Comment by wikijm** [comment]
@d31r Pas de soucis, c'est juste que beaucoup d'issues l'ont été et sont encore à traiter, avec pas toujours beaucoup de bonne volonté de la part de ceux qui demandent de l'aide.

Manuellement, tu peux modifier cette valeur dans le fichier `/home/pi/jarvis/config/play_hw`
Voici une vidéo ASCIINEMA qui te montre comment procéder : http://asciinema.org/a/c36lf4qahqc4heo2ec6o1ghei

**Comment by wikijm** [comment]
Ouch ...
Ton problème vient surement de ça :

> utils/utils.sh: line 170: /home/pi/.asoundrc: Permission denied

Tu as bien installé Jarvis avec le compte pi, et non root ?

**Comment by d31r** [comment]
Oui, comme écrit sur le site, je n'ai pas sudo.

Je l'ai reinstallé pour être sur de ne m'être pas trompé.

Voici le nouveau code obtenu après le troubleshooting:
```
 ./jarvis.sh -nv
./jarvis.sh: line 507: stt_engines//main.sh: No such file or directory

------------ Config ------------
jv_branch            master
jv_version           17.04.08
jv_arch              armv6l
jv_os_name           raspbian
jv_os_version        8
language             fr_FR
play_hw              hw:1,0
rec_hw               hw:1,0
speaker              Nam Tai E&E Products Ltd. or OmniVision Technologies, Inc. Sony Playstation Eye
microphone           Nam Tai E&E Products Ltd. or OmniVision Technologies, Inc. Sony Playstation Eye
recorder
trigger_stt          snowboy
command_stt
tts_engine           svox_pico
--------------------------------

DEBUG: program_startup hook
snowboy: Welcome back, Old Friend
DEBUG: start_speaking hook
DEBUG: stop_speaking hook
Use "?" to display possible commands (in keyboard mode)
snowboy: Waiting to hear 'snowboy'
patron: (listening...)
./jarvis.sh: line 736: snowboy_STT: command not found
(listening...)
./jarvis.sh: line 736: snowboy_STT: command not found
(listening...)
./jarvis.sh: line 736: snowboy_STT: command not found
DEBUG: 3 attempts failed, end of conversation

DEBUG: exiting_cmd hook
snowboy: Waiting to hear 'snowboy'
patron: ^X(listening...)
./jarvis.sh: line 736: snowboy_STT: command not found
(listening...)
./jarvis.sh: line 736: snowboy_STT: command not found
(listening...)
./jarvis.sh: line 736: snowboy_STT: command not found
DEBUG: 3 attempts failed, end of conversation

^C
DEBUG: program_exit hook
```

Que pourrais-je t'envoyer d'autre pour que tu ai plus d'info?

**Comment by Oliv4945** [comment]
>./jarvis.sh: line 507: stt_engines//main.sh: No such file or directory
Est-ce que tu as bien configuré la partie reconnaissance audio ? (Settings-> Wizard)

>utils/utils.sh: line 170: /home/pi/.asoundrc: Permission denied
Réinstaller Jarvis n'a pas d'impact sur ce fichier. Que donne `ln -al /home/pi` ?

**Comment by alexylem** [comment]
Je confirme les dires d' @Oliv4945 👍 

>./jarvis.sh: line 507: stt_engines//main.sh: No such file or directory

Menu Settings > Step by step wizard, aller jusqu'au bout, suivre les recommendations.

>utils/utils.sh: line 170: /home/pi/.asoundrc: Permission denied

```shell
$> chown pi:pi ~/.asoundrc
```
