### ISSUE TITLE
SetAudioGain():gain-control-stream.cc:61) GainControlStream: audio gain must be non-negative.

### ISSUE THREAD

**Issue by pacanou** [alexylem/jarvis#537]
### Description
Suite dernière maj de Jarvis, je n'arrive plus a faire reconnaitre le mot clé. J'ai directement une erreur. J'ai un Raspberry 3 avec Jessie, j'ai formaté ma carte SD et tout réinstallé, idem. J'utilise un micro JABRA 510, il est bien paramétré et tout est OK. Pas de problème au niveau de l'assistant de paramétrage.

J'ai déjà consulté les posts : 
Issues : #415 - #311 - #20 - #411

```shell
### Result
------------ Config ------------
jv_branch            master
jv_version           17.04.08
jv_arch              armv7l
jv_os_name           raspbian
jv_os_version        8
language             fr_FR
play_hw              hw:▒1,0
rec_hw               hw:1,0
speaker
microphone           GN Netcom
recorder             sox
trigger_stt          snowboy
command_stt          bing
tts_engine           svox_pico
--------------------------------

DEBUG: program_startup hook
eva: Hello
DEBUG: start_speaking hook
DEBUG: stop_speaking hook
User defined commands:
*AIDE*                  *BONJOUR*|*SALUT*       *COMMENT*APPELLE*
*MERCI*                 *AU REVOIR*|*BYE*       ANNULE*|TERMINE*
ENCORE*                 *TEST*                  *VERSION*
*REPETE (*) ET (*)      *CA VA*                 >*OUI*
>*NON*|*PAS*
eva: Waiting to hear 'eva'
pascal: (listening...)
DEBUG: models=eva
ERROR (SetAudioGain():gain-control-stream.cc:61) GainControlStream: audio gain must be non-negative.
terminate called after throwing an instance of 'std::runtime_error'
  what():  ERROR (SetAudioGain():gain-control-stream.cc:61) GainControlStream: audio gain must be non-negative.

[stack trace: ]
/home/pi/jarvis/stt_engines/snowboy/_snowboydetect.so(_ZN7snowboy13GetStackTraceEv+0x34) [0x767c2ad4]
/home/pi/jarvis/stt_engines/snowboy/_snowboydetect.so(_ZN7snowboy13SnowboyLogMsgD1Ev+0x4b8) [0x767c3114]
/home/pi/jarvis/stt_engines/snowboy/_snowboydetect.so(_ZN7snowboy17GainControlStream12SetAudioGainEf+0x104) [0x767c8674]
/home/pi/jarvis/stt_engines/snowboy/_snowboydetect.so(+0x17568) [0x7679b568]

stt_engines/snowboy/main.sh : ligne 109 :  4114 Abandon                 python stt_engines/snowboy/main.py --models "stt_engines/snowboy/resources/eva.pmdl" --sensitivity 0.4 --gain 0 --tick
DEBUG: modelid=123
ERROR: snowboy recognition failed
HELP: check error message above, if:
IOError: [Errno Invalid input device (no default output device)] -9996
  1) check your mic in Settings / Audio / Mic
  2) reboot your device
  3) report at: https://github.com/alexylem/jarvis/issues/415
IOError: [Errno Invalid sample rate] -9997
  1) check your mic in Settings / Audio / Mic
  2) try uninstalling pulseaudio
  3) try fresh OS install
  4) your mic does not support 16k sampling rate, change mic
  5) report at: https://github.com/alexylem/jarvis/issues/311
IOError: [Errno Unanticipated host error] -9999
  1) your mic is in error state, unplug/replug it
  2) report at https://github.com/alexylem/jarvis/issues/20
Other
  1) report at https://github.com/alexylem/jarvis/issues/new

DEBUG: program_exit hook
```

**Comment by wikijm** [comment]
Bonsoir @pacanou,

Est-ce que tu peux essayer avec la version précédente ? https://github.com/alexylem/jarvis/releases

**Comment by wikijm** [comment]
> play_hw hw:▒1,0

C'est normal ce caractère ▒ ?

**Comment by Eliasdekiniweek** [comment]
Bonjour @pacanou,
J'ai eu le meme souci, j'ai du changer le gain. Au lieu de mettre 0, j'ai du mettre 1.
Peut etre un bug dans snowboy qui n'accepte plus un gain de 0 ...

**Comment by alexylem** [comment]
```
SetAudioGain():gain-control-stream.cc:61) GainControlStream: audio gain must be non-negative.
```
Wow ca c'est nouveau, notre gain peut être négatif... il faut probablement que je fasse une conversion, je vais lire la doc..

**Comment by alexylem** [comment]
Doc:
>Set audio_gain to be larger than 1 if your test recording’s volume is too low, or smaller than 1 if too high.

**Comment by pacanou** [comment]
Bonsoir,
J'ai remis la version du 17.03.26, pas de problème. 
C'était bien un problèmr de gain à 0 (merci Eliasdekiniweek ) qui marchait avec la version du 17.03.26 et qui ne fonctionne plus avec la dernière version du 17.04.08, dans cette version il faut au minima mettre 1.

**Comment by alexylem** [comment]
Voila c'est corrigé. Mettez à jour:
```shell
$> ./jarvis.sh -u
```

**Comment by energy01** [comment]
la master comme la version beta, on ne peut plus le " Train a hotword/command" de snowboy 
il ne fait plus,l'enregistrement
j'avais des problèmes hier tel que indiqué dans cette issue que je n'arrive pas a résoudre avec la version master ou beta car des éléments ne fonctionnent plus ...
un bout de l'erreur : 

> `rec FAIL sox: missing filename

Usage summary: [gopts] [[fopts] infile]... [fopts] outfile [effect [effopt]]...

`

merci

**Comment by alexylem** [comment]
>la master comme la version beta, on ne peut plus le " Train a hotword/command" de snowboy
il ne fait plus,l'enregistrement

Relevé dans #540 et désormais corrigé.
