### ISSUE TITLE
Utilisation de snowboy et commandes rapides

### ISSUE THREAD

**Issue by pacanou** [alexylem/jarvis#539]
### Description
Bonsoir,
J'utilise snowboy pour le mot clé et çà fonctionne très bien même avec quelques petit bruits de fond (TV). Par contre pas le cas avec bing pour les commandes vocales, il faut répéter...
Donc je voulais tester snowboy avec les commandes rapides, j'ai suivi les tutos, je suis allé dans train command/hotword et il ma généré un fichier "allume la tele.pmdl" dans ..../resources.
Dans mon fichier de commande, j'ai mis : 

*ALLUME*LA*TELE*==sudo irsend SEND_ONCE tv BTN_0 && say "ok, j'allume la télé" 

Il ne comprend pas la commande.
Est ce que ma commande est correcte ? Merci.

### Result
------------ Config ------------
jv_branch            master
jv_version           17.03.26
jv_arch              armv7l
jv_os_name           raspbian
jv_os_version        8
language             fr_FR
play_hw              hw:1,0
rec_hw               hw:1,0
speaker              GN Netcom
microphone           GN Netcom
recorder             sox
trigger_stt          snowboy
command_stt          snowboy
tts_engine           svox_pico
--------------------------------

DEBUG: program_startup hook
eva: Hello
DEBUG: start_speaking hook
DEBUG: stop_speaking hook
User defined commands:
*CHAINE*UNE*            *CHAINE*DEUX*           *CHAINE*TROIS*
*CHAINE*QUATRE*         *CHAINE*CINQ*           *CHAINE*SIX*
*CHAINE*SEPT*           *CHAINE*HUIT*           *CHAINE*NEUF*
*CHAINE*DIX*            *CHAINE*10*             *ALLUME*LA*TELE*
*ETEINS*TELE*           *ETEINDRE*TELE*         ;*ALLUME*VIDEO*PROJECTE
*VIDE*POINT*FR          *ETEINS*VIDEO*PROJECTEU
                        *AIDE*                  *BONJOUR*|*SALUT*
*ET*TOI*                *COMMENT*APPELLE*       *AU REVOIR*|*BYE*
*CA*SERA*               MERCI*                  ENCORE*
*TEST*                  *VERSION*               *REPETE (*) ET (*)
*TEST UN*               *MANGE*                 *SERS*
eva: Waiting to hear 'eva'
pascal: (listening...)
DEBUG: models=eva
Cannot connect to server socket err = No such file or directory
Cannot connect to server request channel
jack server is not running or cannot be started
INFO:snowboy:Ticks: [2, 20, 5, -1]
INFO:snowboy:Keyword 1 detected at time: 2017-04-11 20:27:03
INFO:snowboy:Ticks status: 2 3 2 1
DEBUG: modelid=0
eva
DEBUG: entering_cmd hook
pascal: (listening...)
DEBUG: models=alexa
Cannot connect to server socket err = No such file or directory
Cannot connect to server request channel
jack server is not running or cannot be started
INFO:snowboy:Ticks: [2, 20, 5, -1]
INFO:snowboy:Keyword 2 detected at time: 2017-04-11 20:27:06
INFO:snowboy:Ticks status: 2 8 2 1
DEBUG: modelid=1
?(listening...)
DEBUG: models=alexa
Cannot connect to server socket err = No such file or directory
Cannot connect to server request channel
jack server is not running or cannot be started
INFO:snowboy:Ticks: [2, 20, 5, -1]
INFO:snowboy:Keyword 2 detected at time: 2017-04-11 20:27:10
INFO:snowboy:Ticks status: 2 8 2 1
DEBUG: modelid=1
?(listening...)
DEBUG: models=alexa
Cannot connect to server socket err = No such file or directory
Cannot connect to server request channel
jack server is not running or cannot be started
INFO:snowboy:Ticks: [2, 20, 5, -1]
INFO:snowboy:Keyword 2 detected at time: 2017-04-11 20:27:13
INFO:snowboy:Ticks status: 2 8 2 1
DEBUG: modelid=1
?DEBUG: 3 attempts failed, end of conversation

DEBUG: exiting_cmd hook

**Comment by energy01** [comment]
essaye plutôt la commande en mettant des "*" : 
`*ALLUME*TELE*==sudo irsend SEND_ONCE tv BTN_0 && say "ok, j'allume la télé"`

comme décrit dans le wiki [http://domotiquefacile.fr/jarvis/content/commands](url)
c'est une commande "classique" qu'il faut définir
@+
Anthony.

**Comment by pacanou** [comment]
Merci, pour la réponse, le copier\coller de ma commande n' a pas pris en compte les *, c'était bien 
*ALLUME*LA*TELE*==sudo irsend SEND_ONCE tv BTN_0 && say "ok, j'allume la télé"

donc la commande est bonne ? çà devrait marcher ?

**Comment by PsykonoyaK** [comment]
Salut Pacanou,
je crois bien qu'il manque encore des "*" comme te l'a indiqué energy01.
Essaie ça:
`*ALLUME*LA*TELE*`
Juste au cas où, ta TV est-elle compatible HDMI-CEC?
Si oui il existe ce plugin qui fonctionne à merveille: [jarvis-cec](http://domotiquefacile.fr/jarvis/plugins/jarvis-cec-hdmi)

Tchô

**Comment by wikijm** [comment]
@energy01 Message en OFF : Peux-tu activer la fonctionnalité "Issues" sur ton repo https://github.com/energy01/jarvis_led_matrix ? je supprimerais ce message une fois fait 😉 Merci 😃

**Comment by energy01** [comment]
@wikijm c'est fait 😉

**Comment by alexylem** [comment]
Attention au formatage automatique sur github. Un texte entouré de `*` sera en italique et les `*` disparaissent.
Pour partager des commandes, utiliser le formating `code block`
![image](https://cloud.githubusercontent.com/assets/11017174/24969481/3fc0b09a-1fb1-11e7-9f8f-f574696dd409.png)

Sans formatting:
*COMMAND*==
Avec formatting:
`*COMMAND*==`

**Comment by pacanou** [comment]
en faite la commande a contient bien les astérix mais je ne sais pas comment on insère code block (avec formatting) pour que çà s'affiche correctement.

**Comment by alexylem** [comment]
Dans github sélectionne ton texte (1 ou plusieurs lignes) et cliques sur l'icône 
![image](https://cloud.githubusercontent.com/assets/11017174/24976149/9c1c62c8-1fc8-11e7-9493-a3fad1acf6c3.png)

**Comment by pacanou** [comment]
Merci, voici la commande utilisé `*ALLUME*LA*TELE*==sudo irsend SEND_ONCE tv BTN_0 && say "ok, j'allume la télé"` est elle correcte ?

**Comment by alexylem** [comment]
La commande est correcte mais c'est pas normal que Jarvis ne t'affiche pas ton nouveau modèle trainé en mode debug:
```shell
DEBUG: models=alexa
```
Tu peux mettre à jour à la dernière version? Je crois que j'ai récemment corrigé un bug à ce sujet.

**Comment by NYGHOST** [comment]
j'ai eu ce souci ca peut aussi venir du fait que ton modele ai des accents. autre pb que j'ai eu c'était que snowboy c'était mal installé, recorder j'ai mis snowboy. a part ca je vois pas. les commandes ont l'air bien.

**Comment by pacanou** [comment]
OK avec la dernière version
