### ISSUE TITLE
Bug enregistrement hotword

### ISSUE THREAD

**Issue by energy01** [alexylem/jarvis#540]
### Description
l'issue #537 étant close mais il y a toujours un problème j'en ouvre une autre

la master, comme la version beta avant, on ne peut plus faire le " Train a hotword/command" de snowboy
il ne fait plus,l'enregistrement
j'avais des problèmes hier tel que indiqué dans cette issue #537 que je n'arrive pas a résoudre avec la version master (ou beta) car des éléments ne fonctionnent plus ...
un bout de l'erreur :
```
rec FAIL sox: missing filename

Usage summary: [gopts] [[fopts] infile]... [fopts] outfile [effect [effopt]]...
```

### Result

le problème viens de l'ajout du gain dans la commande rec dans : stt_engines/snowboy/main.sh 

`rec -r 16000 -c 1 -b 16 -e signed-integer gain $gain /tmp/1.wav`

le gain est un "effect" et doit donc être après le fichier son

`rec -r 16000 -c 1 -b 16 -e signed-integer /tmp/1.wav gain $gain`
et cela fonctionne bien sur a faire pour les 3 wavs
je ne sais pas si cela va "tout résoudre" ...
@+
Anthony.

**Comment by alexylem** [comment]
Merci @energy01 bien vu c'état bien ça.
Voila c'est corrigé. Mettez à jour:
```shell
$> ./jarvis.sh -u
```
