### ISSUE TITLE
Modifier la vitesse du tts

### ISSUE THREAD

**Issue by Xavier74** [alexylem/jarvis#541]
Bonjour Alex,
Je trouve qu'il serait intéressant de pouvoir modifier la vitesse du tts.
comme ceci dépend de chaque tts et que Google par exemple ne le propose pas dans son API, il est préférable de le faire par traitement audio
au moment de l'appel du player il faut simplement faire
sox $audio_file -t mp3 - tempo 1.X | mpg123 -
La vitesse peut donc être facilement intégrée dans une variable.

merci pour ton travail

**Comment by Xavier74** [comment]
Petite précision il est nécessaire d'installer libsox-fnt-mp3 pour que sox gère le mp3.

**Comment by alexylem** [comment]
Excellente idée.
Est-ce que ca résoudrait aussi ton problème mentionné dans #542 ? (sox au lieu de mpg123)

**Comment by Xavier74** [comment]
non malheureusement ce sont deux problèmes distincts que je rencontre. la vitesse est vraiment un plus, alors que mon autre demande est plus un bug qui éviterait que je modifie le code source à chaque pull.

**Comment by alexylem** [comment]
Oui mais si je remplace `mpg123` par `sox` globalement dans tout Jarvis (avec l'option playback speed), ca ferait d'une pierre 2 coups. Tu en penses quoi?

**Comment by Xavier74** [comment]
en effet, ça permet une plus grande souplesse pour pas mal de chose. je viens de tester avec sox et ça résoud en effet mon problème.

**Comment by alexylem** [comment]
Ok je vérifie d'abord que:
* la librairie est dispo sur OSX via `brew`
* pas d'impact sur la performance de lecture (temps de réaction)

**Comment by alexylem** [comment]
Bon sur OSX il faut installer lame et réinstaller sox avec le support lame.
```shell
$> brew install lame
$> brew reinstall sox --with-lame
```
Sur mon Mac j'ai aussi du:
```shell
$> brew link --overwrite sox
```
Pas si simple surtout pour des installations déjà existantes.
Par contre derrière ca marche très bien:
```shell
$> play /tmp/bonjour.mp3
```
Peux-tu confirmer que lancer `play` directement marche bien aussi chez toi @Xavier74 ?

**Comment by Xavier74** [comment]
oui ça fonctionne parfaitement
et pour modifier le tempo
play /dev/shm/test.mp3 tempo 1.3
ou modifier le pitch avec speed

**Comment by alexylem** [comment]
Implémenté sur la branch `beta`. Pour le tester dès à présent:
Menu `Settings > General > Branch > beta`
Sinon attendre la mise à jour de ce weekend.
