### ISSUE TITLE
End of spoken phrases are repeated in my soundcard

### ISSUE THREAD

**Issue by Xavier74** [alexylem/jarvis#542]
Salut Alex,

Serait-il possible d'intégrer le choix du player au travers d'une variable ?
De mon côté mpg123 répète sans arrêt la fin des sons que je lui fait lire, ce qui n'est pas le cas avec mpg321.

**Comment by alexylem** [comment]
mpg321 nest plus maintenu depuis 2012 alors que mgp123 l'est encore et régulièrement.
Peux-tu nous indiquer sur quelle distrib tu es et quels TTS tu utilises (affichés au début en mode troubleshooting de Jarvis.
Merci

**Comment by Xavier74** [comment]
je suis sur un pi3 avec raspbian dernière version, tts Google.
c'est je pense un problème lié à ma carte son usb car en hdmi je n'ai pas ce problème.
mais si ya quand même moyen d'offrir cette possibilité, que ce soit mpg321 ou d'autres, je pense qu'il y aurait d'autres outils que mpg123.

**Comment by alexylem** [comment]
Implémenté sur la branch `beta`. Pour le tester dès à présent:
Menu `Settings > General > Branch > beta`
Sinon attendre la mise à jour de ce weekend.
