### ISSUE TITLE
Pas de reconnaissance vocale avec jarvis jeedom

### ISSUE THREAD

**Issue by funky80000** [alexylem/jarvis#544]
Benoit: (listening...)
 python  recorders/snowboy/main.py 30 /dev/shm/jarvis-record.wav 
Cannot connect to server socket err = No such file or directory
Cannot connect to server request channel
jack server is not running or cannot be started

**Comment by pacanou** [comment]
consult cette url.
https://github.com/alexylem/jarvis/issues/523

**Comment by alexylem** [comment]
Je dirais plutôt:
#364 
Sinon changer de recorder (sox au lieu de snowboy dans Settings > Audio > Recorder)
