### ISSUE TITLE
lampe hue

### ISSUE THREAD

**Issue by ledarvite** [alexylem/jarvis#548]
j ai installer plugin hue
j ai ce message iconv: séquence d'échappement non permise � la position 4

merci pour ta réponse

**Comment by wikijm** [comment]
Bonjour à toi aussi.

Comme marqué dans le modèle d'issue : 

> NB : Pour les incidents et demandes concernant les plugins, merci d'ouvrir un ticket sur son propre dépôt.

Je t'invite donc à créer une issue sur le repo du plugin HUE ici : https://github.com/fatoldsun00/jarvis-hue/issues?utf8=%E2%9C%93&q=is%3Aissue

Bon dimanche.
