### ISSUE TITLE
Recommended Plugins

### ISSUE THREAD

**Issue by alexylem** [alexylem/jarvis#550]
- [ ] Add a "recommended" badge on plugins in the store (and a "recommended" section in the app)
- [ ] Propose to install "recommended" plugins at the end of the wizard (or at least view them)

Exemple of recommended plugins:
* Systemd Startup
* Jarvis API
* Jarvis UI

**Comment by alexylem** [comment]
- [X] Recommended plugins section in the website
- [ ] Recommended plugins section in Jarvis integrated store
- [ ] Propose to install "recommended" plugins at the end of the wizard (or at least view them)

http://domotiquefacile.fr/jarvis/recommended-plugins

**Comment by Oliv4945** [comment]
Do you plan to filter plugins regarding system compatibility inside Jarvis integrated store ?
I am thinking about people trying to use systemd startup without systemd.

**Comment by alexylem** [comment]
@Oliv4945 not for the moment as this would require each plugin so run commands in user's system to check compatibility before user installs it, which I find a bit risky (I don't always read the code of all published plugins). I would need to put in place a structure system compatibility checker, like architecture / os / version, TBC is this is sufficient for systemd check.

**Comment by alexylem** [comment]
I would recommend you to make the checkin the `install.sh` of the systemd startup plugin instead for the moment.

**Comment by Oliv4945** [comment]
Ok. I will add this.
Nevertheless I think that the easiest implementation for you might be to run a `dependency.sh` script in plugin directory and check if plugins programmer to returns 0 if nok or 1 if ok

**Comment by alexylem** [comment]
>run a dependency.sh script 

Yes but like I said, the script would run before the user choose to install the plugin to filter it out from plugin listings... and I find this risky because this script could contain malicious code. So it should be after user action to verify compatibility for this plugin. Also today I run the install.sh script after cloning the repo (to have all files). Here I would need to manually retrieve this dependency_check.sh script from the repo to execute it before cloning (installing) the repo.

**Comment by alexylem** [comment]
I chose not to propose recommended plugins at installation because I think the user should first try Jarvis "vanilla" before installing third party plugins.
However new "Recommended plugins" option is available on the store.

Implémenté sur la branch `beta`. Pour le tester dès à présent:
Menu `Settings > General > Branch > beta`
Sinon attendre la mise à jour de ce weekend.

**Comment by Oliv4945** [comment]
>and I find this risky because this script could contain malicious code
Ok got it ! You have a point :-)
