### ISSUE TITLE
voix homme 

### ISSUE THREAD

**Issue by davidjr972** [alexylem/jarvis#552]
bonjour
comment faire pour avoir une voix d'homme, je n'ai pas le choix il n'y a qu'une voix de femme quand j'installe Jarvis dans la synthese vole j'utilise svox_pico (systeme raspbian)
merci

**Comment by wikijm** [comment]
Bonsoir,

Si tu souhaites une voix d'homme, je t'invite à utiliser **espeak**.

**Comment by davidjr972** [comment]
merci de la reponse rapide
j'ai choisis espeak mais j'ai plus de voix les commande passe bien mais sans voix 
il me mets ça :+1: 
David: quelle heure est-il
Jarvis: il est 22 heures 28
utils/utils.sh: ligne 109: _TTS : commande introuvable

**Comment by davidjr972** [comment]
ça fonctionne...avec une voix de robot
