### ISSUE TITLE
j'ai pas pu installer snowboy :(

### ISSUE THREAD

**Issue by mamoun21** [alexylem/jarvis#554]
Salut, alors je voulais installer jarvis sur ma raspberry pi 3 model b et quand j'essaye de configurer /jarvis.sh en suivant les étapes, il me demander d'installer snowboy 
"Snowboy doesn't seem to be installed.                                               
            Do you want to install it?"
Et quand je choisis "yes" 
ça me retourne le code suivant
```
1/2 Preparation of dependencies
Reading package lists... Done
Building dependency tree       
Reading state information... Done
bzip2 is already the newest version (1.0.6-7).
libatlas-base-dev is already the newest version (3.10.2-7+rpi1).
python-pyaudio is already the newest version (0.2.8-1).
python3-pyaudio is already the newest version (0.2.10-1).
The following package was automatically installed and is no longer required:
  libllvm3.7
Use 'sudo apt autoremove' to remove it.
0 upgraded, 0 newly installed, 0 to remove and 3 not upgraded.
--2017-04-20 16:58:33--  https://bootstrap.pypa.io/get-pip.py
Resolving bootstrap.pypa.io (bootstrap.pypa.io)... 151.101.12.175
Connecting to bootstrap.pypa.io (bootstrap.pypa.io)|151.101.12.175|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 1595408 (1.5M) [text/x-python]
get-pip.py: Permission denied

Cannot write to ‘get-pip.py’ (Permission denied).
```

**Comment by alexylem** [comment]
Bonjour @mamoun21 
Où essayes-tu d'installer Jarvis?
Aurais-tu par hasard utilisé `sudo` lors du clone de Jarvis ou lors de l'installation? Il faut surtout éviter.
Peux-tu partager le résultat des commandes suivantes depuis le dossier de Jarvis?
```shell
pwd
whoami
ls -ld .
```
PS: En fait techniquement `pyaudio` n'est plus requis par Jarvis, il faudrait que j'enlève cette étape du script d'installation.

**Comment by mamoun21** [comment]
si lors du clonage j'ai utilisé sudo maos lors de l'installation non
alors le résultat de 
pwd est "/home/pi/jarvis"
whoami est "pi"
et ls -ld est "drwxr-xr-x 16 root root 4096 Apr 19 23:34 . "

**Comment by mamoun21** [comment]
j'ai re-essayé l'installation en choisissant no pour l'installation de snowboy alors quand j'essaye de "start jarvis normally" ça me retourne ceci 
" Up-to-date
Applying updates of version 16.10.31...cat: config/check_updates: No such file or directory
Done
utils/update.sh: line 18: config/version: Permission denied
touch: cannot touch ‘config/last_update_check’: Permission denied
utils/utils.sh: line 398: plugins_order.txt: Permission denied
snowboy: Salut
User defined commands:
grep: jarvis-commands: No such file or directory

utils/utils.sh: line 65: plugins_order.txt: No such file or directory
snowboy: Waiting to hear 'snowboy'
isimm: 
ERROR: personal model for 'snowboy' not found
HELP: Train 'snowboy.pmdl' in:
HELP: Settings > Voice Recognition > Snowboy settings > Train
HELP: Or change your hotword to default model 'snowboy' in:
HELP: Settings > General > Magic word"

jarvis me dit salut (c'est ce que j'ai configurer) puis le programme s'arrete il n'attend meme pas que je lui dise snowboy sachant que j'ai deja un personal model dans snowboy! 

J'ai aussi essayé le "keyboard mode" quelque soit la commande que je tape la réponse est toujours j'ai pas compris :(

**Comment by Oliv4945** [comment]
Il ne faut pas cloner avec sudo ;-)
Du coup soit tu effaces Jarvis et recommence sans sudo sinon `chown pi:pi -R jarvis/`

**Comment by mamoun21** [comment]
merciiiiiii ça marche à merveille! mais j'ai un nouveau probleme maintenant le miroir me dit salut et attend que je lui dit snowboy et c'est ce que j'ai fait mais aucune de sa part..

**Comment by alexylem** [comment]
@mamoun21 peux-tu créer un nouveau ticket et y coller le résultat de la console avec Jarvis lancé en mode troubleshooting? Merci.
