### ISSUE TITLE
Option to disable / re-enable plugins

### ISSUE THREAD

**Issue by alexylem** [alexylem/jarvis#556]
Need an option to temporarily de-activate a plugin (and keep it installed included its configuration) for testing purposes.

**Comment by alexylem** [comment]
There will be a new `plugins-enabled/` folder with symbolic links to `plugins/` folder that may be renamed to `plugins-installed`.

**Comment by Oliv4945** [comment]
Really good idea ! I like the installed/enable folder names :-)

**Comment by alexylem** [comment]
Implémenté sur la branch `beta`. Pour le tester dès à présent:
Menu `Settings > General > Branch > beta`
Sinon attendre la mise à jour de ce weekend.

**Comment by QuentinCG** [comment]
I have a question linked to this option:
Some of my plugins are using path to plugin folders ( example in function.sh: ```result='python3 plugins/jarvis-email-sender/script/send_email.py'```
Should I use path "plugins_enabled" or "plugins_installed" in my function.sh file ?

**Comment by alexylem** [comment]
@QuentinCG voir https://github.com/alexylem/jarvis-weather-wunderground/issues/9#issuecomment-296457626

**Comment by QuentinCG** [comment]
Ok merci ;)
