### ISSUE TITLE
Mettre Jarvis en mode écoute depuis l'API

### ISSUE THREAD

**Issue by RobyBioloid** [alexylem/jarvis#557]
Bonjour,

Y a t'il une commande permettant à Jarvis de passer en mode écoute sans pour autant dire "le mot magique" ?

**Comment by alexylem** [comment]
Oui à condition que Jarvis ne soit pas déjà lancé:
```shell
./jarvis.sh -l
```
Sinon depuis ma trouvaille sur les signaux (voir #547) ca sera possible à l'avenir. On pourrait garder ce ticket pour ca (si nécessaire).

**Comment by RobyBioloid** [comment]
J'ai besoin de cette commande 'Jarvis déjà lancé' donc je vais attendre cette mise à jour ;)

**Comment by alexylem** [comment]
Un cas d'utilisation serait utile (pour ma connaissance). Peux-tu décrire l'utilisation que tu en feras? Merci.

**Comment by RobyBioloid** [comment]
Oui bien sur!
C'est de la "bidouille" car je ne suis pas expert en code ;)

J'utilise "Jarvis" pour donner la parole à un robot et essais de le rendre autant utile pour moi qu'amusant pour mes filles.

Du coup je suis en train de coder en python un petit jeu bien connu qui est le pendu.
Voici comment cela fonctionne

J'ai un script Python qui tourne en boucle et qui lit toutes les 5 secondes un fichier de commandes à exécuter.
Le jeu commence des que la commande "pendu" est enregistré dans le fichier par Jarvis
\*JEU\*PENDU\*==echo "pendu" > /dev/shm/data/commands.txt

Je fais parler Jarvis avec des ~/jarvis/jarvis.sh s " blablabla" et au moment de récupérer la lettre du joueur je met le script en pause.

La commande Jarvis est celle-ci : \*PROPOSE\*LETTRE (*)==echo "(1)" > /dev/shm/data/lettre.txt

Seulement il faut activer le micros pour que cela marche (j'arrive à le faire marcher en entrant moi même la lettre dans le fichier à la main pour le moment)

**Comment by energy01** [comment]
Je me joint à cette "demande" 
aujourd'hui il est possible de lancer "jarvis en écoute" soit avec un hotword ou à priori (pas testé) aussi avec un BP sur les GPIO
je n'ai pas encore creusé pour savoir si on peut faire les 2 "modes" en même temps ?

sinon un "exemple" d'utilisation du besoin exprimé : 
un système domotique, fait dire à la maison (jarvis) quelque chose via l'api genre une question : "dois-je fermer les volets ? "
et donc attend une réponse "Oui/Non" voir décaler la fermeture *NON*DANS(*)== decaler_fermeture_volet((1))
après le système domotique gère l'intelligence de cette "question" et de la "réponse" ou non qui lui est retourné

l'idée est que la maison (jarvis) puisse dans certains cas poser des questions et attendre une réponse sans que l'on soit obliger de "l'appeler" avant pour répondre ...

merci d'avance

PS : @RobyBioloid ton projet de robot à l'air sympa, j'ai dans l'idée d'en construire un également et serait curieux de "voir" ce que tu fais
@+

**Comment by alexylem** [comment]
@RobyBioloid dans ton cas tu pourrais presque développer le Pendu sous forme de plugin:
```shell
*JOUER*PENDU*==say "c'est parti"; $le_mot==$(pendu_get_mot)
*PROPOSE*LETTRE (*)==say "$(pendu_lettre "(1)")"
```
Avec les bonnes fonctions qui vont bien. Mais ton archi fait aussi sens.

@energy01 merci pour ton exemple d'utilisation. Ca ressemble bien à la demande de @RobyBioloid.
Une petite précision, mettre Jarvis en mode écoute ne peut pas se faire via les 2 en même temps. Soit il est lancé et il faut dire le hotword (ou appuyer sur Entrée en fonction des paramètres). Soit il n'est pas lancé et on peut l'évoquer en mode écoute avec le flag `-l` (à partir d'un script qui détecte l'appui sur un bouton relié au GPIO).

Aujourd'hui ca ouvre une boite de dialogue:
```
$> ./jarvis.sh -b
# jarvis lancé, en attente du hotword
$> ./jarvis.sh -l
```
![image](https://cloud.githubusercontent.com/assets/11017174/25307501/3cc3e0c6-27a2-11e7-9372-6d088c177341.png)

Donc là l'idée de ce ticket ca serait de pouvoir faire les 2, à savoir lancer Jarvis en background, et mettre le processus de Jarvis en mode écoute d'une commande en lançant:
```shell
$> ./jarvis.sh -b
# jarvis lancé, en attente du hotword
$> ./jarvis.sh -l
# "Oui?" (attente d'une commande)
```

**Comment by RobyBioloid** [comment]
Oui c'est exactement la demande :)

J'ai une camera avec opencv d'installé. Du coup quand "Roby" détecte un visage il regarde dans sa direction.

Grace à cette option, on pourrait le faire parler et demander si on a besoin de quelque chose.
'
Jarvis repére le visage de quelqu'un
Jarvis : Bonjour, on ne sait pas encore vu aujourd'hui! Avez vous besoin de moi?
"Activation du micros pour connaitre la réponse"
You: Non merci Jarvis
Jarvis: Ok, je reste à votre disposition
'

**Comment by alexylem** [comment]
```shell
$> ./jarvis.sh -b
# jarvis lancé, en attente du hotword
$> ./jarvis.sh -l
# "Oui?" (attente d'une commande)
```
ou
```
$> ./jarvis.sh
```
![image](https://cloud.githubusercontent.com/assets/11017174/25436651/3ac1d27a-2a94-11e7-9e9c-3e701ad5831b.png)

Implémenté sur la branch `beta`. Pour le tester dès à présent:
Menu `Settings > General > Branch > beta`
Sinon attendre la mise à jour de ce weekend.

Je travaille sur une option pour le déclencher depuis le plugin jarvis-api

**Comment by RobyBioloid** [comment]
Cool j'atends la mise à jour ;)

**Comment by alexylem** [comment]
La mise à jour est déjà en ligne sur `master`, tu peux l'essayer:
```shell
$> ./jarvis.sh -b
# jarvis lancé, en attente du hotword
$> ./jarvis.sh -l
# "Oui?" (attente d'une commande)
```

**Comment by RobyBioloid** [comment]
Super
Ça marche nickel

Par contre est-il possible qu'il ne dise pas oui?

**Comment by alexylem** [comment]
Oui, met à vide Settings > Phrase > Trigger reply

**Comment by alexylem** [comment]
En fait je me rends compte derrière ta question que c'est ton plugin qui pose déjà une question... il ne devrait pas y avoir de oui.
Je me demande finalement si ce n'est pas plus simple de propose une fonction du style:
`jv_get_from_voice` qui renvoie le texte donné par l'utilisateur... 

Ainsi dans un script de plugin:
```shell
say "C'est parti pour un pendu, prochaine lettre?"
letter="$(jv_get_from_voice)"
say "Ok la lettre est $letter"
```

ca ne serait pas plus simple pour vous?

**Comment by Oliv4945** [comment]
ça me parait sympa cette fonction pour d'autres applications, si ce n'est pas dur à faire
