### ISSUE TITLE
mot clé

### ISSUE THREAD

**Issue by davidjr972** [alexylem/jarvis#561]
bonjour
mon jarvis répond a tout les noms pas spécifiquement au nom que je lui est donné
je ne vois pas ou se trouve le problème.
merci pour l'aide

**Comment by Oliv4945** [comment]
Salut,
Comme dit la Doc quand tu crées une issue, il faut mettre le log sinon dur de t'aider. 
Lances `./jarvis.sh -nv`

**Comment by wikijm** [comment]
Bonjour @davidjr972,

Comme énoncé par @Oliv4945, certaines informations sont demandées lors de l'ouverture d'une issue.
Je clôture ce dernier, et te laisse en ouvrir un autre, cette fois-ci en supprimant uniquement la partie en anglais et en complétant la partie en français.

La communauté ne sera en mesure de t'aider que lorsque que ses règles seront respectées.
