### ISSUE TITLE
 wri

### ISSUE THREAD

**Issue by mning95** [alexylem/jarvis#562]
## ![English][English] English
>
### Description

PLEASE SEARCH BEFORE [existing tickets](https://github.com/alexylem/jarvis/issues?utf8=%E2%9C%93&q=is%3Aissue) and in the [docs](http://domotiquefacile.fr/jarvis/).

NB: For issues with plugins, please create in the corresponding repository

### Result
`<Paste here>` content of the terminal after using Jarvis in troubleshooting mode.
To use it:
```shell
./jarvish.sh -nv # Start Jarvis directly in troubleshooting mode
```

OR

Attach a session recording using [ASCIINEMA](https://asciinema.org/).
To use it:
```shell
sudo apt-get install -y asciinema && asciinema rec # start session recording
./jarvish.sh -nv # start jarvis directly in troubleshooting mode
Ctrl+D # stop recording
y # yes to upload and get URL to paste here
```

---

### Description

MERCI DE COMMENCER PAR RECHERCHER dans les [tickets existants](https://github.com/alexylem/jarvis/issues?utf8=%E2%9C%93&q=is%3Aissue) ainsi que la documentation sur [http://domotiquefacile.fr/jarvis/](http://domotiquefacile.fr/jarvis/)

NB : Pour les incidents et demandes concernant les plugins, merci d'ouvrir un ticket sur son propre dépôt.

### Résultat
`<Coller ici>` le résultat du terminal lors de l'utilisation de Jarvis en mode troubleshooting.
Pour le lancer :
```shell
./jarvish.sh -nv
```

OU

Fournir un lien vers une vidéo de votre terminal enregistrée avec [ASCIINEMA](https://asciinema.org/).
Pour l'installer et lancer un enregistrement :
```shell
sudo apt-get install -y asciinema && asciinema rec # Démarre l'enregistrement
./jarvish.sh -nv # Exécute Jarvis directement en mode troubleshooting
Ctrl+D # Arrête l'enregistrement
y # 'yes' ('oui') pour envoyer l'enregistrement sur la plateforme ASCIINEMA et obtenir son adresse d'accès
```

[English]: /imgs/flags/us.png "English"
[French]: /imgs/flags/fr.png "French"

**Comment by wikijm** [comment]
Hi @mning95,

Your issue is "empty" (no information coming from you).
Could you please edit it to fill your context?

**Comment by mning95** [comment]
I don't remember opening this issue.  I will close it immediately. Sorry for any inconvenience.

**Comment by wikijm** [comment]
No problem, thanks 😃
