### ISSUE TITLE
jv_update_config commande introuvable

### ISSUE THREAD

**Issue by RobyBioloid** [alexylem/jarvis#563]
J'ai depuis quelques jour un plantage de la commande jv_update_config
`
jarvis/jarvis.sh: ligne 647 jv_update_config : commande introuvable
`

**Comment by alexylem** [comment]
J'ai enlevé cette fonction en tout cas sous cette forme.
A priori tu n'as pas besoin de l'exécuter, c'est une fonction interne pour les mises à jour structurantes de Jarvis (ex: renommage de dossier, etc...).
Que souhaitais-tu accomplir avec cette fonction?
Pour info maintenant il faut:
```shell
source utils/update.sh
```
Mais encore une fois tu ne devrais pas avoir besoin de l'utiliser.

**Comment by RobyBioloid** [comment]
C'est à dire que je modifie assez réguliérement les commandes pour corriger les mauvaise interprétations de la reconnaissance vocale

Du coup, j'ai créer une commande \*MET\*SYSTEM\*A\*JOUR\*==jv_update_config && say "Mise à jour du systéme ok"

**Comment by RobyBioloid** [comment]
la commande utils/update.sh provoque cette erreur
`
jarvis/jarvis.sh: ligne 658 utils/update.sh : Permission non accordée
`

**Comment by alexylem** [comment]
Je peux t'aider à corriger cette erreur, mais cette fonction n'a rien à voir avec les commandes de Jarvis, c'est pour la mise à jour du système:
https://github.com/alexylem/jarvis/blob/master/utils/update.sh
Tu modifies dynamiquement iles commandes du fichier `jarvis-commands` ?
Ca devrait être pris automatiquement en compte (sauf si tu es dans une sous conversation, mais c'est très rare).
Dans le doute tu peux vérifier:
```
*MONTRE*COMMANDE*==echo "$commands"
```

**Comment by wikijm** [comment]
Pas de réponse depuis plus de 2 mois, j'en conclus que le problème n'est plus rencontré.
Ne pas hésiter à ré-ouvrir si nécessaire.
