### ISSUE TITLE
How to avoid first ms chopped off the sound

### ISSUE THREAD

**Issue by ybizeul** [alexylem/jarvis#567]
Voice recording chops a few milliseconds at the beginning on the sound.

"Active something" is played back as "ctive something" in debug mode, obviously Bing doesn't understand.

    utils/timeout.sh 10 rec -V1 -q -r 16000 -c 1 -b 16 -e signed-integer --endian little /tmp/jarvis-record.wav gain 0 silence 1 0.1 3 1 0.5 3 trim 0 5

**Comment by Oliv4945** [comment]
I did not had time to explore it for now but I have the same issue on the Respeaker, I was thinking it was the platform but if you have the same on macos...

**Comment by alexylem** [comment]
This is related to sow audio levels, which is not always perfect even if you did the auto-adjust level well.
@ybizeul just for the sake of experimentation, please change recorder to Snowboy in:
Menu > Settings > Audio > Recorder > Snowboy
And let me know if you face the same issue.

**Comment by Oliv4945** [comment]
@alexylem: Is there any other workaround than using Snowboy ?
We cannot on the Respeaker

**Comment by alexylem** [comment]
@ybizeul this is because of sox audio levels.
You min noice perc to start recording seems to be 3. Try to put it at 1% or less in Settings > Audio 
![image](https://cloud.githubusercontent.com/assets/11017174/25533696/c612a2de-2c31-11e7-9db0-156595d39a37.png)

**Comment by alexylem** [comment]
I think I found a way to improve this, testing now...

**Comment by ybizeul** [comment]
I will do additional tests tonight :
- Set noise level to 1%
- Switch recorder to Snowboy
- Whatever @alexylem comes up with :-)

I'm actually surprised, I thought the recorder what smart enough to maintain a buffer and include a few milliseconds before the level crosses the threshold to account for that.

**Comment by alexylem** [comment]
@ybizeul 
It's my formula to calculate thresholds that is not correct, keep sox and try even:
* min noice perc to start to 0.1%

I'm adding a new parameter to keep the silence at the beginning, will definitely help bing.
Give me an hour to finish my testing and push the update.

**Comment by alexylem** [comment]
J'ai fait les changements sur la bêta:
Pour le tester dès à présent:
1. Menu > Settings > General > Branch > beta
2. Menu > Search for updates
3. Relancer Jarvis
4. Refaire l'auto-adjust levels dans Menu > Settings > Audio > Auto-adjust levels
Et dis moi si ca va mieux

**Comment by ybizeul** [comment]
Same problem, unless I missed something

```
------------ Config ------------
jv_branch            beta 
jv_version           17.04.28 
jv_arch              x86_64 
jv_os_name           Mac OS X 
jv_os_version        10.12.4 
language             fr_FR 
play_hw              false 
rec_hw               false 
speaker              Default 
microphone           Default 
recorder             sox 
trigger_stt          snowboy 
command_stt          bing 
tts_engine           osx_say 
--------------------------------
```

```
DEBUG: start_listening hook
utils/timeout.sh 10 rec -V1 -q -r 16000 -c 1 -b 16 -e signed-integer --endian little /tmp/jarvis-record.wav gain 0 silence 1 0.1 2.1% 1 0.5 2.1% pad 0.5 0.5 trim 0 5
DEBUG: speech duration was 15 (10 = 1 sec)
DEBUG: stop_listening hook
```

**Comment by ybizeul** [comment]
Snowboy works much better indeed as a recorder

**Comment by alexylem** [comment]
@ybizeul you are still with min noise perc to start at 2.1%
Try to lower it manually to 0.1% but if after that the sound is still chopped off, stay with snowboy as recorder...

**Comment by ybizeul** [comment]
Ok, I thought I didn't need to with the code change.

It's better now, sound recording isn't chopped anymore but it's recording permanently as the room noise is above 0.1%

**Comment by alexylem** [comment]
Ok then try to find the best value.
New formula I use for auto-adjust levels in Settings > Audio should do it for you, but manual finetuning is better.
Do you confirm you don't have the issue with snowboy recorder at all?

**Comment by ybizeul** [comment]
Yep, Snowboy recorder doesn't have that problem. It's hard to make bing recognize anything if too far from the mic though but I guess that's another problem, I would need specific omnidirectional mic with noise cancellation, that's for another day :-)

**Comment by ybizeul** [comment]
I would be great if sox had an option to include additional time (half a second) before the threshold is crossed

**Comment by alexylem** [comment]
@ybizeul this is what I did, I added half a second before and after the recorded sound. Should be better now.
And yes, for far end recognition, you need an array mic 😄

**Comment by Oliv4945** [comment]
@alexylem : Thanks you, it is not 100% ok but helps with the respeaker (without mic array for now)

**Comment by ybizeul** [comment]
The MicArray module of the ReSpeaker alone would work with any generic device ? (My mac, a Raspberry pi 3, etc)

**Comment by alexylem** [comment]
No idea, you'd better check out with the vendor.

**Comment by Oliv4945** [comment]
Mine is seen as a USB microphone, so it should work but I never tested it yet. Someone tried it [here](https://github.com/alexylem/jarvis/issues/525), but we don't know if it is actually working.
