### ISSUE TITLE
Control Jarvis using Siri on iPhone, iPad, Apple Watch and Mac

### ISSUE THREAD

**Issue by alexylem** [alexylem/jarvis#569]
Be able to send orders to Jarvis using Siri on iOS devices:
* iPhone
* iPad
* Apple Watch
* Mac

I have a simple approach to use the "Note" operation:
```yml
Vous: Note éteins la véranda
Siri: D'accord
```
![image](https://cloud.githubusercontent.com/assets/11017174/25504238/6c5d7c9e-2b9d-11e7-9b11-b044faeead5e.png)

Assuming you have setup gmail as your default Notes account, it will create a Note "éteins la véranda" and immediately sync it as an email in your gmail Account.
This plugin will watch your "Notes" labelled emails every X seconds and make Jarvis execute that order.

**Comment by Oliv4945** [comment]
I don't know if you saw it, just in case : https://hackaday.com/2017/04/27/how-to-use-siri-to-control-your-pc/

**Comment by alexylem** [comment]
That is exactly what I was looking at. Different tutorial but same mechanism / python script behind.

**Comment by alexylem** [comment]
http://domotiquefacile.fr/jarvis/plugins/siri
