### ISSUE TITLE
PocketSphinx ne fonctionne pour avec la reconnaissance des commandes

### ISSUE THREAD

**Issue by NYGHOST** [alexylem/jarvis#57]
### impossible de reconnaitre les mots 

configuration:
reco magic world snoboy ( nikel)
reco of commands (poketsphinx)

### attente d'un mot et remplissage de "#"
```
DEBUG:too log for a command max 4sec ignoring
```

**Comment by alexylem** [comment]
Ok alors voici 2 pistes:
* Pocketsphinx ne peut pas être utilisé pour la reconnaissance des commandes (pour le moment), voir:
https://github.com/alexylem/jarvis/wiki/stt

```
DEBUG:too log for a command max 4sec ignoring
```
Comme indiqué, Jarvis attends une ordre vocal de moins de 4 secondes pour le considérer comme une commande. Assures-toi que l'ordre que tu donnes est dure bien moins de 4 secondes. Sinon il se peut que tu aies des bruits de fonds ou un pb de sensibilité avec ton micro, voir #33 

Sinon, dans la FAQ:
> Que veulent dire les caractères `-` `?` `.` et `#` qui s'affichent quand je parle?
> `-` le son détecté était trop court (si en attente d'entendre "JARVIS")
> `#` le son détecté est trop long pour un mot clé ou une commande
> `.` pas de son entendu lors de l'écoute d'une commande (timeout)
> `?` le son enregistré n'a pas pu être transcrit en texte valide (clé Google manquante?)

**Comment by NYGHOST** [comment]
je vais me tourner alors vers snowboy mais ca m'oblige a modifier ton code source

**Comment by alexylem** [comment]
Pourquoi? avec snowboy tu peux utiliser tes propres triggers dans Jarvis, regarde:
https://github.com/alexylem/jarvis/wiki/snowboy

**Comment by NYGHOST** [comment]
J'ai essaye tout les moteurs.
Google je l'exclue car en ligne
Wit en ligne

Ensuite poketsphinx j'ai toujours le probleme de la commande non prise en compte et pas entendu

Reste snowboy j'ai deja enregistrer mon hotword marche nikel mais ensuite plus rien

Envoy? de mon iPhone

Le 19 juil. 2016 ? 15:34, Alexandre M?ly <notifications@github.com<mailto:notifications@github.com>> a ?crit :


Pourquoi? avec snowboy tu peux utiliser tes propres triggers dans Jarvis, regarde:
https://github.com/alexylem/jarvis/wiki/snowboy

-

**Comment by alexylem** [comment]
J'ai modifié mon précédent commentaire:
>Sauf si tu parles des commandes, alors c'est prévu: #15 (rajoute un +1 sur l'issue dans ce cas)

**Comment by physicien** [comment]
@NYGHOST Éventuellement, il sera aussi possible d'utiliser un serveur distant que l'utilisateur configurera où il voudra. C'est une solution de remplacement aux moteurs en ligne, car pour le moment la RP3 n'est pas assez puissante pour rouler un STT engine avec un compréhension langagière convenable (dictionnaire + language model + acoustic model trop lourds).
Actuellement, j'ai entrepris de configurer Kaldi: #25 (ce n'est pas simple du tout, mais j'ai réussi à lui faire décoder de l'anglais et il ne me resterait plus qu'à l'entraîner pour qu'il comprenne le français)
Nous a aussi déjà été question de faire la même chose avec PocketSphinx #9

**Comment by NYGHOST** [comment]
J'ai commenc? a jeter un coup d'oeil mais je bloque sur L impl?mentation des "hotsword multiple"

Envoy? de mon iPhone

Le 19 juil. 2016 ? 16:08, Alexandre M?ly <notifications@github.com<mailto:notifications@github.com>> a ?crit :


J'ai modifi? mon pr?c?dent commentaire:

Sauf si tu parles des commandes, alors c'est pr?vu: #15<https://github.com/alexylem/jarvis/issues/15> (rajoute un +1 sur l'issue dans ce cas)

-

**Comment by NYGHOST** [comment]
Poketsphinx peut gerer le francais mais sur ma RP3 je coince avec.

Envoy? de mon iPhone

Le 19 juil. 2016 ? 16:22, Esteban <notifications@github.com<mailto:notifications@github.com>> a ?crit :


@NYGHOST<https://github.com/NYGHOST> ?ventuellement, il sera aussi possible d'utiliser un serveur distant que l'utilisateur configurera o? il voudra. C'est une solution de remplacement aux moteurs en ligne, car pour le moment la RP3 n'est pas assez puissante pour rouler un STT engine avec un compr?hension langagi?re convenable (dictionnaire + language model + acoustic model trop lourds).
Actuellement, j'ai entrepris de configurer Kaldi: #25<https://github.com/alexylem/jarvis/issues/25> (ce n'est pas simple du tout, mais j'ai r?ussi ? lui faire d?coder de l'anglais et il ne me resterait plus qu'? l'entra?ner pour qu'il comprenne le fran?ais)
Nous a aussi d?j? ?t? question de faire la m?me chose avec PocketSphinx #9<https://github.com/alexylem/jarvis/issues/9>

-

**Comment by alexylem** [comment]
@NYGHOST regarde #15 j'ai déjà prévu de travailler dessus. Rajoute un +1 à cet issue pour dire que tu es intéressé.

**Comment by NYGHOST** [comment]
chef oui chef

**Comment by alexylem** [comment]
Je propose qu'on ferme ce ticket vu que le besoin est adressé par:
- #9 Utilisation de PocketSphinx sur un serveur distant (pour les commandes)
- #15 Utilisation de Snowboy pour des commandes rapides (sans besoin de dire le mot clé)
