### ISSUE TITLE
Soucis divers lors de l'installation

### ISSUE THREAD

**Issue by Nowwis** [alexylem/jarvis#572]
Bonjour,

J'ai un soucis lors de l'installation, ça bloque aléatoirement entre la lecture d'applause.wav, ou de la lecture de mon enregistrement perso juste après...
J'installe via SSH sur mon RPI3, à jour avec un update && upgrade.
Je ne comprends pas du tout :(

Quelqu'un pour m'aider ?

Merci d'avance !
![jarvis](https://cloud.githubusercontent.com/assets/1506118/25541040/79995f26-2c4d-11e7-8bc6-8565e2315d0f.PNG)

**Comment by alexylem** [comment]
Bonjour à toi @Nowwis 
Normalement il suffit de suivre les instructions, l'applause est pour vérifier que le son fonctionne, puis vient le test du micro.
Tu peux voir la vidéo complète d'installation ici:
http://domotiquefacile.fr/jarvis/content/installation

Tu peux aussi partager une session de ton terminal en utilisant [asciinema](http://asciinema.org):
```shell
sudo apt-get install -y asciinema && asciinema rec # start session recording
./jarvish.sh # start jarvis
Ctrl+D # stop recording
y # yes to upload and get URL to paste here
```
Ca nous aidera à mieux comprendre où ca bloque.
Merci!

**Comment by Nowwis** [comment]
Merci pour ta réponse hyper rapide !

En fait, mon putty plante complétement, ça ne bouge plus, parfois au moment de l'applause (je n'entends rien et putty ne veut plus rien entendre), donc je dois redémarrer putty et relancer l'installation, parfois c'est au moment d'écoute l'enregistrement que je viens de faire, ça ne lit rien et ça plante comme le applause.
J'ai réussi seulement une fois à passer ces 2 étapes sur les 15 tentatives d'installation...

j'essaie de record mais je pense que je n'arriverais pas à faire le CTRL+D pour finaliser.

**Comment by alexylem** [comment]
Ca me fait penser à ca: #117 
Regarde mon commentaire ici:
https://github.com/alexylem/jarvis/issues/117#issuecomment-246956655
Tu es sur Jessie Lite? La personne qui a eu ce pb a du repartir sur une base Jessie Full...

**Comment by alexylem** [comment]
Si tu as le courage, une vidéo filmée avec ton tel serait très utile, je pense que ca vient du VU meter (la bar qui grandit quand il y a du son), on pourrait tester de le désactiver dans le script d'install pour voir si ca résout ton problème...

**Comment by Nowwis** [comment]
Effectivement, c'est bien la lite, je télécharge la full et je réinstalle le tout !

Merci !

**Comment by wikijm** [comment]
@Nowwis Je clôture l'issue le temps que tu teste tout ça.
N'hésites pas à nous faire un retour ici, voire la ré-ouvrir si le problème persiste avec une version full 😉

**Comment by matrottier** [comment]
une idée de ce qui manque à la version lite ?  
retropie est monté sur celle-ci, et j'aimerai bien utiliser les deux sans me taper une réinstallation.

**Comment by Oliv4945** [comment]
Il me semble avoir vu des issues récentes sur Jessie Lite qui fonctionnent, quel est le soucis exact ?

**Comment by wikijm** [comment]
Bonjour @matrottier,

Il serait plus judicieux de créer un nouveau ticket, histoire d'avoir d'en avoir un dédié aux problèmes relatifs à l'utilisation de la version Lite.

**Comment by matrottier** [comment]
c'était une question éclaire si on veut =p voir si quelqu'un avait une réponse rapide.  
je vais réinstaller avec Jessie full, et voir si cela fonctionne.  
je voulais pas vraiment créer un nouveau ticket, car j'ai fait plusieurs tests pour faire fonctionner un enceinte bluetooth et j'ai p-e briser un truc.  
Mon problème était similaire, lors d'un test de micro, le traitement gelait au niveau de la lecture du test micro et quelques fois au niveau du test de son (applause), mais rarement.
