### ISSUE TITLE
Problème mise à jour

### ISSUE THREAD

**Issue by magicdvil** [alexylem/jarvis#577]
je suis dans la branche master

┌─ pi@dvilpi
│  17:03 ~/
└─▶$ jarvis/jarvis.sh -u
jarvis/jarvis.sh: line 143: configure: command not found
Checking updates for jarvis...fatal: ambiguous argument 'HEAD...origin/': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
Error
Checking updates for jarvis-api...Up-to-date
Checking updates for jarvis-math...Up-to-date
Checking updates for jarvis-minuterie...Up-to-date
Checking updates for jarvis-time...Up-to-date
Checking updates for jarvis-ui...Up-to-date
Checking updates for jarvis-weather-wunderground-fr...Up-to-date
Checking updates for jarvis-wikipedia...Up-to-date

**Comment by alexylem** [comment]
Bien vu, corrigé.
Pour mettre à jour s'il y a une erreur:
```shell
$> git pull # depuis le dossier jarvis
```
