### ISSUE TITLE
lire les mails

### ISSUE THREAD

**Issue by remjou1** [alexylem/jarvis#58]
tout simplement : comment jarvis peut-il lire les mail ? tu y fait référence ici [#56](https://github.com/alexylem/jarvis/issues/56)

**Comment by NYGHOST** [comment]
je dirai grace a urllib3 ou un parser html mais faudra avoir le compte gmail toujours activé.

**Comment by Smanar** [comment]
Pour gmail c'est pas dur en passant par https://mail.google.com/mail/feed/atom
Par contre effectivement, il faut baisser le niveau de securite pour certaines mailbox, mais je sais pas encore pkoi, doit me manquer des infos.

**Comment by alexylem** [comment]
Désolé @remjou1 mais je vais devoir fermer ce ticket, car on parle des commandes et ce n'est pas lié au coeur de Jarvis (il faut que je fasse un page "philosophie du projet" à ce sujet).
Je propose déjà dans les Event un exemple pour donner le nombre d'emails Gmail non lus, mais il est très simple (et il y a plein d'exemples sur le net) de les faire lire.
