### ISSUE TITLE
Erreur de cle

### ISSUE THREAD

**Issue by polbru40** [alexylem/jarvis#580]
Bonjour,
J'ai depuis peu un RPI3, et je m'intéresse a la domotique mais aussi au commande vocal. J'ai regardé plusieurs programme et Jarvis m'a séduit. Merci pour votre travail et le partage.
Je suis parvenu a installé Jarvis et le faire fonctionné ( suis pas doué en Linux et programmation).
J'ai une clé snowboy et Bing. Mais voilà Jarvis me dis qu'il y a une erreur.

.
![jarvis_erreur](https://cloud.githubusercontent.com/assets/28238098/25568972/a4f4f66e-2e0d-11e7-85d1-bbea3b2d30ac.PNG)

J'ai vérifié plusieurs fois les clés et elle sont correct.
Merci de votre aide

**Comment by Oliv4945** [comment]
Bonjour, est ce que tu peux relancer avec 'jarvis -nv' et coller le résultat ?

Merci

**Comment by polbru40** [comment]
Bonjour, merci pour la réponse. Voici le résultat :
![jarvis_erreur1](https://cloud.githubusercontent.com/assets/28238098/25575710/ef7782c8-2e59-11e7-9d3f-8741440a06bc.PNG)

**Comment by Oliv4945** [comment]
Merci, mais avec la commande qui fait planter ça aidera  :)

**Comment by polbru40** [comment]
Oui :) me suis rendu compte qu'il manquais quelque choses 
![jarvis_erreur2](https://cloud.githubusercontent.com/assets/28238098/25576025/3a5c2b5c-2e5c-11e7-9a5b-9ead0b0d2f99.PNG)

**Comment by polbru40** [comment]
Suis pas programmeur ni connaisseur de linux mais j'ai l'impression que c'est snowboy qui fait erreur. J'ai pourtant suivi la manip . Peut on recommencer pour avoir une autre clé ?

**Comment by polbru40** [comment]
Voilà j'ai tout refait a zéro. Avec une nouvelle clé Snowboy fait avec un autre compte. Toujours le même problème . En mode clavier pas soucis. Je ne comprends pas :(

**Comment by alexylem** [comment]
@polbru40 bonjour à toi.
Ton problème semble être lié à ta clé Bing. Tu as fait une recherche sur les tickets précédents?
- #506 
- #145 

Vérifie qu'elle est bonne dans Settings > Voice Reco > Bing Settings > Key
Ensuite je vois que tu as changé le recorder à snowboy, je te conseille de le remettre à sox dans Settings > Audio > Recorder > Sox.

**Comment by polbru40** [comment]
@alexylem 
Salut, j'ai tout refait ;).
J'ai déjà avancé , jarvis me repond YES. J'ai changé la clé Bing et remit Sox.
J'ai maintenant ceci :  ( un peu long désolé)

`pi@raspberrypi:~/jarvis $ ./jarvis.sh -nv

------------ Config ------------
jv_branch            master 
jv_version           17.04.30 
jv_arch              armv7l 
jv_os_name           raspbian 
jv_os_version        8 
language             fr_FR 
play_hw              hw:0,1 
rec_hw               hw:1,0 
speaker              ALSA 
microphone           Logitech, Inc. Webcam C270 
recorder             sox 
trigger_stt          snowboy 
command_stt          bing 
tts_engine           svox_pico 
--------------------------------

DEBUG: program_startup hook
DEBUG: start_speaking hook
jarvis: Bonjour 
DEBUG: stop_speaking hook
User defined commands:
*AIDE*			*BONJOUR*|*SALUT*	*COMMENT*APPELLE*
*MERCI*			*AU REVOIR*|*BYE*	ANNULE*|TERMINE*
ENCORE*			*TEST*			*VERSION*
*REPETE (*) ET (*)	*CA VA*			>*OUI*
>*NON*|*PAS*
jarvis: Waiting to hear 'jarvis'
fred: (listening...)
DEBUG: models=jarvis
INFO:snowboy:Ticks: [2, 20, 5, -1]
INFO:snowboy:Keyword 1 detected at time: 2017-05-01 15:43:39
INFO:snowboy:Ticks status: 1 1 1 1
WARNING:snowboy:No match silence_before
INFO:snowboy:Keyword 1 detected at time: 2017-05-01 15:43:51
INFO:snowboy:Ticks status: 2 1 0 1
DEBUG: modelid=0
jarvis
DEBUG: entering_cmd hook
DEBUG: start_speaking hook
jarvis: Yes
DEBUG: stop_speaking hook
fred: (listening...)
DEBUG: start_listening hook
utils/timeout.sh 10 rec -V1 -q -r 16000 -c 1 -b 16 -e signed-integer --endian little /dev/shm/jarvis-record.wav gain  -08 silence 1 0.1 0.1% 1 0.5 0.1% pad 0.5 0.5 trim 0 5
DEBUG: speech duration was 50 (10 = 1 sec)
WARNING: too long for a command (max 4 secs), ignoring...
HELP: try in order the following options
1) wait longer between voice commands
2) reduce ambiant background noise
3) decrease mic sensitivity in Settings > Audio
4) increase Min Silence Level to Stop
DEBUG: stop_listening hook
(listening...)
DEBUG: start_listening hook
utils/timeout.sh 10 rec -V1 -q -r 16000 -c 1 -b 16 -e signed-integer --endian little /dev/shm/jarvis-record.wav gain  -08 silence 1 0.1 0.1% 1 0.5 0.1% pad 0.5 0.5 trim 0 5
DEBUG: speech duration was 50 (10 = 1 sec)
WARNING: too long for a command (max 4 secs), ignoring...
HELP: try in order the following options
1) wait longer between voice commands
2) reduce ambiant background noise
3) decrease mic sensitivity in Settings > Audio
4) increase Min Silence Level to Stop
DEBUG: stop_listening hook
(listening...)
DEBUG: start_listening hook
utils/timeout.sh 10 rec -V1 -q -r 16000 -c 1 -b 16 -e signed-integer --endian little /dev/shm/jarvis-record.wav gain  -08 silence 1 0.1 0.1% 1 0.5 0.1% pad 0.5 0.5 trim 0 5
DEBUG: speech duration was 50 (10 = 1 sec)
WARNING: too long for a command (max 4 secs), ignoring...
HELP: try in order the following options
1) wait longer between voice commands
2) reduce ambiant background noise
3) decrease mic sensitivity in Settings > Audio
4) increase Min Silence Level to Stop
DEBUG: stop_listening hook
DEBUG: 3 attempts failed, end of conversation

DEBUG: exiting_cmd hook
jarvis: Waiting to hear 'jarvis'
fred: (listening...)
DEBUG: models=jarvis
INFO:snowboy:Ticks: [2, 20, 5, -1]
INFO:snowboy:Keyword 1 detected at time: 2017-05-01 15:44:35
INFO:snowboy:Ticks status: 2 1 0 1
DEBUG: modelid=0
jarvis
DEBUG: entering_cmd hook
DEBUG: start_speaking hook
jarvis: Yes
DEBUG: stop_speaking hook
fred: (listening...)
DEBUG: start_listening hook
utils/timeout.sh 10 rec -V1 -q -r 16000 -c 1 -b 16 -e signed-integer --endian little /dev/shm/jarvis-record.wav gain  -08 silence 1 0.1 0.1% 1 0.5 0.1% pad 0.5 0.5 trim 0 5
DEBUG: speech duration was 50 (10 = 1 sec)
WARNING: too long for a command (max 4 secs), ignoring...
HELP: try in order the following options
1) wait longer between voice commands
2) reduce ambiant background noise
3) decrease mic sensitivity in Settings > Audio
4) increase Min Silence Level to Stop
DEBUG: stop_listening hook
(listening...)
DEBUG: start_listening hook
utils/timeout.sh 10 rec -V1 -q -r 16000 -c 1 -b 16 -e signed-integer --endian little /dev/shm/jarvis-record.wav gain  -08 silence 1 0.1 0.1% 1 0.5 0.1% pad 0.5 0.5 trim 0 5
DEBUG: speech duration was 50 (10 = 1 sec)
WARNING: too long for a command (max 4 secs), ignoring...
HELP: try in order the following options
1) wait longer between voice commands
2) reduce ambiant background noise
3) decrease mic sensitivity in Settings > Audio
4) increase Min Silence Level to Stop
DEBUG: stop_listening hook
(listening...)
DEBUG: start_listening hook
utils/timeout.sh 10 rec -V1 -q -r 16000 -c 1 -b 16 -e signed-integer --endian little /dev/shm/jarvis-record.wav gain  -08 silence 1 0.1 0.1% 1 0.5 0.1% pad 0.5 0.5 trim 0 5
DEBUG: speech duration was 50 (10 = 1 sec)
WARNING: too long for a command (max 4 secs), ignoring...
HELP: try in order the following options
1) wait longer between voice commands
2) reduce ambiant background noise
3) decrease mic sensitivity in Settings > Audio
4) increase Min Silence Level to Stop
DEBUG: stop_listening hook
DEBUG: 3 attempts failed, end of conversation

DEBUG: exiting_cmd hook
jarvis: Waiting to hear 'jarvis'
fred: (listening...)
DEBUG: models=jarvis
INFO:snowboy:Ticks: [2, 20, 5, -1]
INFO:snowboy:Keyword 1 detected at time: 2017-05-01 15:45:01
INFO:snowboy:Ticks status: 1 1 0 1
WARNING:snowboy:No match silence_before
INFO:snowboy:Keyword 1 detected at time: 2017-05-01 15:45:04
INFO:snowboy:Keyword 1 detected at time: 2017-05-01 15:45:06
INFO:snowboy:Keyword 1 detected at time: 2017-05-01 15:45:06
INFO:snowboy:Keyword 1 detected at time: 2017-05-01 15:45:07
INFO:snowboy:Ticks status: 2 6 0 1
DEBUG: modelid=0
jarvis
DEBUG: entering_cmd hook
DEBUG: start_speaking hook
jarvis: Yes
DEBUG: stop_speaking hook
fred: (listening...)
DEBUG: start_listening hook
utils/timeout.sh 10 rec -V1 -q -r 16000 -c 1 -b 16 -e signed-integer --endian little /dev/shm/jarvis-record.wav gain  -08 silence 1 0.1 0.1% 1 0.5 0.1% pad 0.5 0.5 trim 0 5
DEBUG: speech duration was 50 (10 = 1 sec)
WARNING: too long for a command (max 4 secs), ignoring...
HELP: try in order the following options
1) wait longer between voice commands
2) reduce ambiant background noise
3) decrease mic sensitivity in Settings > Audio
4) increase Min Silence Level to Stop
DEBUG: stop_listening hook
(listening...)
DEBUG: start_listening hook
utils/timeout.sh 10 rec -V1 -q -r 16000 -c 1 -b 16 -e signed-integer --endian little /dev/shm/jarvis-record.wav gain  -08 silence 1 0.1 0.1% 1 0.5 0.1% pad 0.5 0.5 trim 0 5
^C
DEBUG: program_exit hook
pi@raspberrypi:~/jarvis $ 
`

**Comment by alexylem** [comment]
Il suffit de faire ce qui est écrit :) tu comprends un peu l'´anglais ?

**Comment by polbru40** [comment]
@alexylem Merci de ta réponse . Non je ne comprends l'anglais, néanmoins j'arrive a comprendre généralement l'anglais technique. je n'ai pas pu regarder a cela aujourd'hui mais je le fait au plus vite et te tient au courant de l'avancement :)

**Comment by polbru40** [comment]
Je vais attendre d'avoir acheté un autre micro pour continuer plus loin avec le vocal. Je vais donc fermer le ticket. J'ai une autre question a propos d'autre choses j'ouvre donc un autre ticket mais avant je vais voir si la réponse n'est pas dans les autres post. :)
