### ISSUE TITLE
Provide an update.sh hook to plugins ?

### ISSUE THREAD

**Issue by Oliv4945** [alexylem/jarvis#581]
Hi,

Following the [issue](https://github.com/Oliv4945/jarvis-systemd-startup/issues/1) of jarvis-systemd plugin an update is made to `jarvis.service` file. The file should be copied to `/etc/systemd/system`, and systemd dameon should be reloaded but I don't see how to do it.
In addition to `install.sh` and `uninstall.sh`, could we have `update.sh` ?

It might be done thanks to git hooks but not the cleanest way to do it...

**Comment by alexylem** [comment]
What a coincidence, I was thinking about it, and by chance (or greatness of your code 😄 ), for your systemd plugin the Reinstall option worked fine for me:
![image](https://cloud.githubusercontent.com/assets/11017174/25634416/d64cd16e-2f7a-11e7-8db8-9b96f38600a9.png)
What it does is only run the install.sh script again.
But I prefer your update option over the Reinstall. (less randomness, more control & flexibility)
I will add an `update.sh` script (empty by default) that will be ran (if exists - retrocompability) at every update of the plugin. Always. So be careful and make the needful checks...
And then I will remove the Reinstall menu option.

Note: In your plugin's `update.sh` you may want to add:
```shell
sudo systemctl daemon-reload
```
But that I'm sure you know already 😄

**Comment by alexylem** [comment]
**jarvis-siri/update.sh**
```shell
#!/bin/bash
# This file will be automatically sourced each time your plugin is updated
# Use only if you need to perform updates on the user systems to support evolution of your plugin
jv_debug "test update (please ignore)"
```
![image](https://cloud.githubusercontent.com/assets/11017174/25635460/7faffd46-2f7e-11e7-9a29-8916015d6edc.png)

Implémenté sur la branch `beta`. Pour le tester dès à présent:
Menu `Settings > General > Branch > beta`
Sinon attendre la mise à jour de ce weekend.

**Comment by Oliv4945** [comment]
Great, thank you. I will add it to jarvis-systemd as soon as we agree on it, because most user will never know they need to use reinstall.

> Note: In your plugin's update.sh you may want to add: `sudo systemctl daemon-reload`

Sure, that's what I meant by `and systemd dameon should be reloaded ` ;-p

**Comment by alexylem** [comment]
>Sure, that's what I meant by and systemd dameon should be reloaded ;-p

Ah I missed it 😄 

>I will add it to jarvis-systemd as soon as we agree on it, because most user will never know they need to use reinstall.

There is no more Reinstall as I have implemented your `update.sh` idea. So you can go ahead.

**Comment by Oliv4945** [comment]
Ok, just tried it.
One minor [mistake](https://github.com/alexylem/jarvis/pull/585) but it works well ! Thank you
