### ISSUE TITLE
Tip: How to simply use bluetooth without PulseAudio?

### ISSUE THREAD

**Issue by NYGHOST** [alexylem/jarvis#582]
petit post pour ceux qui souhaite utiliser JARVIS dans leur maison sans fils et cable partout 
un emeteur recpteur bt https://www.amazon.fr/Inateck-R%C3%A9cepteur-Transmetteur-Adaptateur-dAutonomie/dp/B01FU5QKZS.
coupler avec un USB-JAck ca me permet te coupler mon micro bluetooth et mon enceinte JBL clip 2

**Comment by alexylem** [comment]
Pas mal.
Mais gardez en tête que le support du bluetooth a été confirmé, et est en attente d'implémentation de ma part, voir https://github.com/alexylem/jarvis/issues/200#issuecomment-291012525

**Comment by miguipda** [comment]
Bonjour à tous,

Je ne compte utiliser que Jarvis comme coeur domotique de ma maison.
De ce fait, pas de possibilité de disposer d'un serveur PulseAudio (par exemple sur Jeedom ou autre).
Ayant investi dans un RPi3 pour accueillir Jarvis, je ne compte pas réinjecter de l'argent dans une box domotique.
Du coup, à mon sens, Jarvis (dans son coeur) doit permettre un usage PuseAudio comme serveur ou comme client. Je vous lis en parfait progression pour son usage en client, mais phase 2, en mode serveur, svp ;-) Vous allez mieux me comprendre avec ce qui suit. 

@alexylem : je te rejoins dans la complexité de Pulseaudio que je n'ai pas non plus encore creusée, mais l'intérêt que je crois y avoir lu est entre autre qu'on peut orienter l'envoi de son vers un client précis lorsque c'est nécessaire. Resterait alors à voir si il peut aussi malgré tout orienter certains sons vers tous les clients disponibles.
Voici alors l'intérêt envisage : 
1) en considérant qu'on rentre à la maison et que seul le haut-parleur Bluetooth est (toujours) connecté. Alors tout envoi son se fait vers ce client (défaut) PulseAudio.
2) je suis réntré et j'ai connecté mon ordinateur portable sur mon réseau local (devenant alors également client PulseAudio).
A considérer (filtrer) suivant le type de message (son) transmis, le son serait alors précisément (voire uniquement) orienté vers le client PulseAudio (de l'ordinateur portable : exemple, une synchronization de fichiers de celui-ci avec un serveur). A contrario, des messages génériques (sécurité, ...) seraient eux diffuses vers tous les clients (enceinte Bluetooth, ordinateur (portable, ...)).

 D'où à mon sens l'intérêt de prévoir l'usage de PulseAudio comme client ou comme serveur pour le coeur de Jarvis. Comme mentionné au début de cette requête.

En espérant également pouvoir disposer de Jarvis avec (un coeur-serveur) PulseAudio pour mes clients (enceinte Bluetooth centralisée (défaut), mais mobile), je vous remercie à tous pour ce magnifique travail qui enrichi Jarvis (pour notre plus grand comfort et plaisir).

Excellente journée.

Miguipda ;-)

**Comment by alexylem** [comment]
#200 est maintenant implémenté.
