### ISSUE TITLE
Infinite loop with `./jarvis.sh -x ""`

### ISSUE THREAD

**Issue by QuentinCG** [alexylem/jarvis#583]
### Description

Sending an empty request to Jarvis will create an infinite loop of fail...
This has impact on all plugins using ```./jarvis.sh -x```.

Maybe plugins should check if the command is empty and then not send it, but a check in jarvis should be added too.

If I have time, I'll check this bug myself ;)

### Logs
```shell
pi@raspberrypi:~/jarvis $ ./jarvis.sh -x ""
./jarvis.sh: ligne 174: recorders//main.sh: Aucun fichier ou dossier de ce type
./jarvis.sh: ligne 175: stt_engines/false/main.sh: Aucun fichier ou dossier de ce type
./jarvis.sh: ligne 176: stt_engines//main.sh: Aucun fichier ou dossier de ce type
maitre: ./jarvis.sh: ligne 404: _STT : commande introuvable
./jarvis.sh: ligne 404: _STT : commande introuvable
./jarvis.sh: ligne 404: _STT : commande introuvable

jarvis: Waiting to hear 'jarvis'
maitre: ./jarvis.sh: ligne 406: false_STT : commande introuvable
./jarvis.sh: ligne 406: false_STT : commande introuvable
./jarvis.sh: ligne 406: false_STT : commande introuvable

jarvis: Waiting to hear 'jarvis'
maitre: ./jarvis.sh: ligne 406: false_STT : commande introuvable
./jarvis.sh: ligne 406: false_STT : commande introuvable
./jarvis.sh: ligne 406: false_STT : commande introuvable
```

**Comment by alexylem** [comment]
I have a slightly different behavior:
```shell
$> ./jarvis.sh -b # jarvis needs to run
$> ./jarvis.sh -x ""
Alex: ???
Jarvis: Waiting to hear 'Jarvis'
```
It should not behave this way so I'll fix it but I don't have your error messages. Let's see if my fix resolves your issues.

**Comment by alexylem** [comment]
Implémenté sur la branch `beta`. Pour le tester dès à présent:
Menu `Settings > General > Branch > beta`
Sinon attendre la mise à jour de ce weekend.

**Comment by QuentinCG** [comment]
Works fine with the fix ;)

pi@raspberrypi:~/jarvis $ ./jarvis.sh -x ""
ERROR: Order cannot be empty
pi@raspberrypi:~/jarvis $

Thanks

Note: We don't have the same error because I didn't specify audio input/output for now ;)
