### ISSUE TITLE
Depuis mise à jour Bug play FAIL formats: can't open input file `pourcents.mp3': No such file or directory

### ISSUE THREAD

**Issue by Jean-Bernard-Hallez** [alexylem/jarvis#584]
### Description
J'ai le même problème sur mes 2 raspberrys...
sur l'un j'ai tout supprimé, mise à jour mon raspberry,  et réinstallé... même problème... lorsque je demande la météo il me dit:
Un dessin vaut mieux qu'un long discourt:
http://asciinema.org/a/7j85z7kvw8q8c5kaj0fvuniu5

(ce me le fait aussi sur d'autre plugin...)

**Comment by alexylem** [comment]
Je regarde ça ce soir. D'autres personnes ont remonté un pb similaire faudrait le référencer.

**Comment by alexylem** [comment]
dupplicate #574
