### ISSUE TITLE
Plugin Wikipedia

### ISSUE THREAD

**Issue by ducati34** [alexylem/jarvis#586]
Bonjour,

J'ai un problème avec ce plugin. Quand je prononce "donne moi la définition de XXXX" j'ai Jarvis qui me dis " désolé je ne comprend pas la question". Les commandes natives de Jarvis fonctionnent, les interactions avec Jeedom également, mais pas le plugin Wikipedia. D'après l'installation, il n'y a rien à parametrer. J'ai raté un truc? Vous savez pourquoi ca ne marche pas chez moi? J'ai la meme chose avec le plugin Bruitage, je ne sais pas si cela peut vous mettre sur une piste...
Merci pour votre aide

**Comment by wikijm** [comment]
Bonjour @ducati34,

Comme marqué dans le modèle d'issue : 

> NB : Pour les incidents et demandes concernant les plugins, merci d'ouvrir un ticket sur son propre dépôt.

Je t'invite donc à créer une issue sur le repo du plugin ici : https://github.com/Sellig28/jarvis-wikipedia/issues

**Comment by alexylem** [comment]
Problème résolu comme vu ici:
https://github.com/alexylem/jarvis-weather-wunderground/issues/10#issuecomment-299643033
