### ISSUE TITLE
plus de son sur carte son USB Ugreen 

### ISSUE THREAD

**Issue by yala37** [alexylem/jarvis#589]
### Description
Bonjour à tous,

je n'arrive plus a avoir le son sur ma carte USB Ugreen, j'ai beau tester différentes conf ./asoundrc pas mieux... ma conf asoundrc est la suivante : 
```
pcm.!default {
  type asym
   playback.pcm {
     type plug
     slave.pcm "hw:2,0"
   }
   capture.pcm {
     type plug
     slave.pcm "hw:1,0"
   }
}
```
ma carte fonctionne bien car les commandes suivantes produisent du son : 
```
 aplay -D plughw:CARD=Device test2.wav
speaker-test -D sysdefault:CARD=2
```
Le micro lui semble bien fonctionner.

Merci d'avance pour votre aide.

Yann

**Comment by yala37** [comment]
en fait aucun de mes micro ne fonctionnent plus sur mon Pi, cependant ils sont bien visibles et detectés par exemple avec la commande "record -l" cependant lors du test du micro via "jarvis.sh" aucun son n'est capté ni enregistré.

merci.

**Comment by alexylem** [comment]
Le Wizard de Jarvis te permet de détecter, choisir et tester tes enceintes.
Va dans Settings > Audio > Speaker et suis les instructions.

**Comment by yala37** [comment]
j'ai testé la procédure plusieures fois mais pas de son avec la procédure du wizard. e fait malgré le fait que je précide bien d'utiliser la carte (positionnée en 2:0), jarvis utilise toujours le port par défaut (0:0) donc j'ai du son sur la sortie Jack du raspi, mais pas sur ma carte son usb.

J'utilise aussi le programme shareport qui trouve bien la bonne carte son.

**Comment by alexylem** [comment]
tu peux tester:
```shell
$> aplay -D hw:2,0 sounds/applause.wav
```

**Comment by yala37** [comment]
en effet : 
jeedom@jeedom:~ $ aplay -D hw:2,0 test2.wav
Lecture WAVE 'test2.wav' : Signed 16 bit Little Endian, FrÃ©quence 16000 Hz, Mono
aplay: set_params:1239: Nombre de canaux non disponible

par contre :  aplay -D plughw:2,0 test2.wav fonctionne bien.

**Comment by alexylem** [comment]
maintenant avec sox:
```
$> AUDIODEV=plughw:2,0 play test2.wav
```
Ton `~/.asoundrc` a l'air correct. Tu as bien redémarré comme indiqué lors de l'installation?
Tu dis que tu n'as plus de son... tu l'avais avant? Qu'as-tu changé?

**Comment by yala37** [comment]
ça fonctionne! 

oui j'ai bien redémarré. 

En fait voici l'historique : 

depuis quelques semaines je me suis aperçu que mon micro USB ne fonctionnait plus (peut être a cause d'une maj de jarvis...je n'en ai aucune idée car je l'utilise finalement assez rarement mon micro n'est pas terrible). ma carte son elle fonctionnait encore.
J'ai donc fait plusieurs choses  : mettre a jour jarvis, mettre a jour les package (apt-get ...), débranché rebranché les équipements usb, modifié le fichier asoundrc....
depuis ni ma carte son ni mon micro ne fonctionne plus avec jarvis (ni avec le plugin JeeTTS de Jeedom d'ailleurs qui utilise mplayer), le son fonctionne uniquement avec SharePort et les commandes que je t'ai indiqué.

Dans les wizard de jarvis, j'arrive cependant bien a modifier le volume et le gain du micro.

**Comment by yala37** [comment]
la commande suivante fonctionne : mplayer test2.wav -ao alsa:device=hw=2.0

**Comment by alexylem** [comment]
On dirait que ton `~/.asoundrc` n'est pas pris en compte.
Juste pour être sûr tu as bien fait un:
```shell
sudo /etc/init.d/alsa-utils restart
```
après avoir modifié ce fichier? Jarvis le fait automatiquement, mais si tu modifies le fichier manuellement tu dois le faire toi.

**Comment by yala37** [comment]
j'ai rétablie le fonctionnement du plugin jeetts de jeedom en ajoutant la ligne suivante dans la config mplayer (/home/jeedom/.mplayer/config) :

ao="alsa:device=hw=2.0"

Pour Jarvis, pas mieux..

**Comment by alexylem** [comment]
Je peux te donner un fix très rapide, mais à la prochaine mise à jour de Jarvis tu vas le perdre... je préfère t'aider à résoudre le pb à la racine.
Tu n'aurais pas installé PulseAudio par hasard?
Essaye
```
pgrep pulseaudio
```

**Comment by yala37** [comment]
oui je pense qu'il est installé :  voici le résultat de la commande : 

29532

**Comment by yala37** [comment]
a mon avis je n'ai pas besoin de pulseaudio je vais tenter de le désinstaller

**Comment by alexylem** [comment]
Le support de PulseAudio sera bientôt la, je travaille dessus en ce moment #200 pour le support du bluetooth.
