### ISSUE TITLE
Lire le stream de synthèse vocale directement sans passer par fichier intermédiaire

### ISSUE THREAD

**Issue by alexylem** [alexylem/jarvis#59]
### Description

Proposé par Smanar depuis #41 
>Nope, pour google voice, c'est comme picoTTS, le serveur genere le fichier et te renvois un fichier son complet (de memoire, je peux me planter).
Pour Ivona, tu streames le resultats, elle continue a generer ton fichier alors que tu commences deja a le lire.

Au lieu de générer le fichier son entièrement puis de le faire lire, on pourrait lire le stream au fur et à mesure qu'il est généré.
Je pense même que ca doit être possible avec Google, et d'autres synthèses vocales hors ligne.

**Comment by Smanar** [comment]
Pour les moteurs hors ligne, j'ai deja jete un oeuil du cote de PicoTTS, le code de pico2wave est en C et dispo, donc facilement modifiable, apres ce n'est pas du tout prevu pour et y a du boulot pour des raisons de synchronisation (on ne peut pas lire les datas au fur et a mesure qu'on les recoit).

Sinon comme la generation du fichier wav est plus rapide que sa lecture, en shell si on lance la generation en fond de tache, attend 1s, et lance la lecture, ca devrait accelerer la diffusion du son ? (Des que je recupere le PI, je te dis ca).

**Comment by alexylem** [comment]
@Smanar Je pense qu'il est tout à fait possible de lire au fur et à mesure qu'on reçoit, c'est toute la base du streaming :wink: 
Voici le principe général en utilisant le pipe `|`:
```
$> generate_wav | aplay
```

**Comment by Smanar** [comment]
Nope, ce que je voulais dire c'est que le plus simple etait de simplement inserer une fonction pour lire les datas juste apres la fonction qui les genere dans le code de pico2wave, et ca ce n'est pas possible, il faut mettre les datas dans un tampon (qui va se remplir tres vite) et utiliser un second thread qui va le lire mais a vitesse normale de lecture du son (beaucoup plus lent), donc plus de boulot.

Sinon j'ai teste ta commande, ca marche, (enfin presque, il y a un message d'erreur mais le fonctionnement est bon), il y a pas moyen d'inserer une commande pr attendre 0.5/1s  entre les deux ?

Edit :
Sinon j'ai teste ">/dev/null 2>&1 &" a la fin de la commande, suivi de sleep 1 avant de lire le fichier.

Meme erreur, il me faut minimum 1.5s pour que cela marche, bon 1.5s c'est mieux que 4 ou 5, mais rien ne me garanti que pour une ligne plus longue ca ne passe pas a 2s.

**Comment by alexylem** [comment]
Tu as tout à fait raison dans ce cas, ca ne marchera que si la génération est plus rapide que la lecture (comme pour le streaming, sinon ca lag :smile: )
Idéalement il faut que le programme qui encore le fichier son le lise directement (comme le fait `espeak` nativement ou `say` d'OSX). A voir si `picoTTS` le propose.
Sinon il faut faire comme tu dis, lancer la génération en tâche de fond et checker la vitesse de création du fichier et interpoler à partir de quand on peut le lire sans risquer de lag. Pas évident...

**Comment by Smanar** [comment]
Bon j'ai finallement craque, et me suis fait une version speciale de pico2wave, pico2play ^^.
https://github.com/Smanar/Pico2play

Tu devrais pouvoir la compiler sans problemes, sauf si ma version precomplilee de libpico et portaudio ne marchent pas sur ton raspberry. J'ai utilise ces versions pour gagner du temps (15/20 mn pr les compiler) mais du coup elle correspondent surtout a mon systeme (mais je ne pense pas qu'il y a trop de differences).

Elle ne genere aucun fichiers wav, et commence a diffuser le son avant de calculer toute la phrase.

**Comment by alexylem** [comment]
Génial, à partir de quel moment tu commencer à diffuser?
Quel player utilises-tu?
Sur quel device tu envoies?

**Comment by alexylem** [comment]
J'ai cherché par curiosité si qqun n'avait pas déjà pensé à faire ca et je suis tombé sur:
https://github.com/ch3ll0v3k/picoPi2

>You can compile picoPi2Wav to output text into .wav file of you can compile picoPi2Std to output it directly in STD

Ca s'utilise comme ca:
```
./picoPi2Std | aplay -f S16_LE -r 16000
```

**Comment by Smanar** [comment]
Il y a gave de trucs interessant sur son code, j'y jetterais un oeuil demain, il l'a converti en c++, a rajoute des fonctions, enfin je pense, y a des bouts de code que j'ai pas vu sur ma version.

Par contre, je ne suis pas du tout du monde unix, c'est quoi le STD, un tampon 100% en memoire virtuelle ?

Je commence a diffuser a la seconde mise en tampon "if start == 2" histoire d'etre sur d'avoir quelques datas avant de demarrer, mais c'est quasi immediat.

Il me reste encore a supprimer toute la partie qui genere le fichier wav, vu que ne m'en sert pas du tout, les donnees etant directement lues sans mises en forme. Pour le moment c'est la version test, elle ecrit encore un fichier wav, mais ca va grandement alleger l'appli une fois supprime.

**Comment by alexylem** [comment]
J'attends que tu me donnes ton GO pour l'intégrer dans Jarvis. Je tiens à ce que ca reste ultra simple pour les utilisateurs, donc on ne doit pas leur demander de compiler quoi que ce soit. Au mieux on utilise ton executable compilé, au pire on faire tourner un script d'installation automatique.
Voici, lorsque Jarvis détecte que PicoTTS n'est pas installé, ce qu'il exécute:

tts_engines/svox_pico/main.sh
```bash
hash 'pico2wave' 2>/dev/null || {
    dialog_yesno "SVOX Pico doesn't seem to be installed.\nDo you want to install it?" true >/dev/null && {
        if [[ "$platform" == "linux" ]]; then
            echo -e "Updating..."
            sudo apt-get -qq update || exit 1
            echo -e "Upgrading..."
            sudo apt-get -qq upgrade -y || exit 1
            echo -e "Downloading & Installing..."
            sudo apt-get install -y libttspico-utils >/dev/null || exit 1
            dialog_msg "Installation Completed"
        elif [[ "$platform" == "osx" ]]; then
            dialog_msg "SVOX Pico is not available on your platform"
        else
            dialog_msg "Unknown platform"
            exit 1
        fi
    }
}
```

Je ne propose pas PicoTTS sur OSX comme tu peux voir.
Donc je te laisse trouver les bons paramètres de compilation pour que ca tourne sur un maximum de plateformes (les 3 raspberry sur Jessie minimum, + débian si possible, voir [prérequis](https://github.com/alexylem/jarvis/wiki/prerequisites) ) et je l'influerai dans le repo. Ou tu préfères faire compiler? (risque de dépendances manquantes...)

T'en penses quoi?

**Comment by alexylem** [comment]
Au fait j'aimerais te rajouter à la liste des contributeur de Jarvis sur [la page remerciements](https://github.com/alexylem/jarvis/wiki/credits). Tu préfères Smanar ou ton nom complet?

**Comment by Smanar** [comment]
Je sais pas si je te l'avais dis, mais je suis Aeliss sur Disqu. Et tu m'avais deja propose, en fait non j'ai pas "prevu de le faire evoluer", je l'ai juste mit en ligne pour ne pas le laisser mourir sur un vieux disque dur, et qu'il puisse servir a d'autres, mais je suis sur pas mal de projets et celui la n'est pas ma prioritee. Je fais ca pour moi en priorite, c'est pr ca qu'il est en FR et regle pr mon usage, je le modifi juste quand j'ai besoin d'un truc special ou quand j'ai du temps libre.

Jarvis m'interesse, d'ailleurs c'est a cause de toi que j'ai mit en ligne rhonda, je passe regulierement regarder l'avancer de ton projet, et j'attend par exemple le "Store de commandes" pour piller tes scripts shell ^^. Mais Rhonda est aussi en "libre-service" (meme si j'ai pas encore choisis la licence a cause des parties qui ne sont pas de moi) si un bloc t'interesse je peux t'en faire un executable C ou C++ utilisable via shell.

Pour le nom "Smanar" c'est parfait, merci, mais dans tout les cas je vais etre plutot discret, Jarvis est surtout en shell et moi de ce cote je m'y connais autant qu'en danse classique donc je vais pas pouvoir faire grand chose, donc compte moi plutot comme "touriste" :).

Sinon pour en revenir a pico2play, j'avais pas pense au probleme de l'install.
Pour la lib pico pas de soucis c'est la meme pr debian et jessie (teste) et la meme pour tout les raspberry, c'est la version armhf sur les depots.
Pour la lib portaudio, il y a plein d'options (alsa ou pas, Jack ou pas) qui peuvent foutre le bordel, si snowboy tourne, la version qu'ils utilsent doit etre bonne (mais elle est recompilée lors de l'install si je me souvient bien).
Faire recompiler la lib pico, pour moi ca sert a rien, elle ne change pas et demande 10/15 mn.
Faire compiler la lib portaudio et du coup pico2play, je ne sais pas, mais je ne pense pas que cela soit utile.
Et de memoire ce sont les seules dependances.
>gcc -o pico2play pico2play.o -lpopt -lm lib/libttspico.a portaudio/libportaudio.a -lpthread -lasound -ljack 

Tout est deja par defaut sur raspberry (meme si j'ai un doute pour popt https://packages.debian.org/jessie/libpopt0 elle est en dependance lors de l'install de libttspico-utils, donc je ne sais comment faire pr savoir si elle y est a la base ou pas, au pire je peux refaire le code sans elle)

Apres c'est une histoire de mentalite, certains ne veulent pas d'executable sans code source, de taille, le fichier fait plus d'un mega (je peux reduire avec les options de compil, mais y'aura pas de miracles).

Tu peux aussi heberger les fichiers sur ton github, et les faire DL par ton installateur, honnettement je pense que c'est le plus simple, et tu pourras avoir plus facilement la main dessus.

C'est toi qui choisis, demain je nettoie le code, je teste d'autres options de compilation, mais je n'aurais pas plusieurs raspberry pr tester, tous sont configures pareil. (je bidouille sur un B+). Mais comme tu pars sur un raspberry vierge, tous vont etre pareil, si ca marche sur un, ca marchera sur l'autre.

**Comment by Smanar** [comment]
Bon c'est bon fini.
Tout est clean, meme plus d'erreurs lors de la compil, j'ai meme fait un makefile et j'ai vire la dependance a la lib popt.
Sinon pour t'aider a chosir j'ai fais plusieurs tests.

Pour la lib pico, pas le choix, "impossible de trouver le paquet", c'est pas nouveau faut installer svox-1.0+git20130326, gave de lignes de commande et de temps perdu. Surtout que suis sur a 99% que cette lib ne change pas. Le fichier actuel est teste sur debian/jessie PI B+.

Pour la lib portaudio, j'ai mis la dependance a installer sachant qu'il y a de forte chance qu'elle soit deja presente ou installe avec  snowboy. J'ai regarde ou le package s'installe et je recupere ces liens, du coup le repertoire "portaudio" de pico2play ne sert plus a rien.

Tu peux compiler avec les libs *.a, fichier avec lib statiques, ou les libs *.so lib dynamique (dans le makefile). Difference de taille, mais franchement suis pas sur de voir la diff niveau perf.

Beaucoup de fichier dans le repertoire lib, ne servent que a generer le fichier *.a, si tu choisis de le faire compiler, je peux t'alleger le nbre de fichiers (tout les *.c degagent).

De toi a moi, meme si la version de processeur a change entre le PI B+ et le 3, c'est tjours un processeur ARM, pour portaudio, tu fais demarrer d'une install clean, donc pour moi tu peux precompiler l'appli, en statique > 1M, ou en dynamique 800ko. Et si tu la laisses en option avec pico2wave, tu n'as rien a perdre, si elle marche pas, il suffira de repasser sous pico2wave si prb.

**Comment by alexylem** [comment]
Il faut laisser la lib portaudio car snowboy n'est pas installé par défaut. Je le récupère à la volée pour la compile si l'utilisateur choisi snowboy.
Ok je suis partant pour la version pré-compilée (avec .so si c'est plus léger, car il faut l'inclure dans le repo ou le faire télécharger depuis le tient).
Je vais commencer à tester sur mes raspberry pi.

**Comment by alexylem** [comment]
Pour l'instant ton repo fait 5.57M, c'est déjà amaigri au maximum?

**Comment by alexylem** [comment]
Voila le script d'installation:
```bash
sudo apt-get install portaudio19-dev
wget https://github.com/Smanar/Pico2play/archive/master.zip # 5.57M
unzip master.zip
cd Pico2play-master/pico
make # rapide
```
Utilisation:
```
./pico2play -l fr-FR "bonjour comment ca va"
```
**Problème:** c'est rapide 😄  mais très haché. Tu sais d'où ca peut venir? Je peux t'envoyer un aperçu si nécessaire.

**Comment by alexylem** [comment]
Sinon j'ai fait quelques tests de performance avec `pico2wav` juste pour m'assurer qu'on va bien gagner avec `pico2play`, voici ce que ca donne:
```
time pico2wave -l fr-FR -w /tmp/test.wav "Oui?"
real	0m0.058s
time pico2wave -l fr-FR -w /tmp/test.wav "Bonjour, comment ça va?"
real	0m0.120s
time pico2wave -l fr-FR -w /tmp/test.wav "Au lieu de générer le fichier son entièrement puis de le faire lire, on pourrait lire le stream au fur et à mesure qu'il est généré."
real	0m0.325s
```
Ca me semble pas si horrible que ca. Mais bon c'est sur un raspberry pi 3, faudrait voir sur les autres modèles 😕

**Comment by Smanar** [comment]
Je pense que tu as mis le doigt sur le probleme.
Sur Raspberry B+
> time pico2wave -l fr-FR -w /tmp/test.wav "Au lieu de générer le fichier son entièrement puis de le faire lire, on pourrait lire le stream au fur et à mesure qu'il est généré."
real    0m1.328s

Et c'est pour ca que ca doit etre hache, sur raspberry 3 la generation doit se faire a la meme vitesse que la lecture, c'est pour ca que cela ne t'a pas choque avant. Et si les deux threads vont a la meme vitesse, il faut faire prendre plus d'avance a celui qui rempli le buffer.

Il faudrait faire un sondage pour savoir avec quoi tournent les utilisateurs (pas forcement pour ca, ca sert tjours) si tu as moins de 50% sur vieux raspberry, pico2play ne sert a rien apparement, enfin a tester mais 0.3s pour une phrase de 30 mots, suis pas sur que ce soit bien flagrant. Tu peux ralentir le thread de lecture en modifiant la ligne "if (start == 2)" mais au final, suis pas sur que cette appli te soit utile.

Pour la taille, c'est a cause du dossier "lang" (6M), inutile si tu as deja installe pico2wave (soit on recupere le chemin lang de pico2wave, soit on copie le fichier au meme endroit que pico2wave).

Apres tant pis, si au final elle ne sert pas, j'aurais pas perdu mon temps, moi je vais en avoir besoin, enfin sauf si je passe finallement sur un raspberry 3.

Sinon a propos d'application qui servent a rien, si tu te decides a utiliser une matrice led 8*8 (15/25 euros selon les modeles), plus sympa qu'une led, je peux te faire une appli a appeller via shell du style
>matriceLed 00GGGG00 0G0000G0 G0G00G0G G000000G G0G00G0G G00GG00G 0G0000G0 00GGGG00

C'est sur, tout tes utilisateurs ne vont pas investir la dedans, mais franchement, moi je m'en sert, et je trouve ca plus qu'utile.

**Comment by Smanar** [comment]
Bon je devais vraiment etre ailleurs ce jour la, j'ai fais quelques modifs, mais j'ai raconte n'importe quoi. Si le raspberry 3 est plus rapide, il y a encore moins de chance pour que le thread de mise en buffer aille plus vite que le thread de lecture.

Quand tu dis que c'est hache, tu as des vides ou ca parle comme un rappeur de banlieu ?

La j'ai le meme resultat qu'avec pico2wave, mais j'ai peu etre pas la version la plus optimise sur ce Raspberry, vais tester sur le vierge.

**Comment by alexylem** [comment]
Je vais refaire un test et t'envoyer le son

**Comment by Smanar** [comment]
Te prend pas la tete, ca m'etonnerait que cela te serve au final, donc passes pas ton temps la dessus. C'est pas une priorite pour moi non plus.

**Comment by alexylem** [comment]
Je viens d'implémenter un gros truc #49 j'attends vos retours 😄

**Comment by alexylem** [comment]
Suite à nos discussions et résultats des tests de perf, je ferme le ticket. 
On verra pas si ca ressort un jour 😄
