### ISSUE TITLE
say "...", say " " and say ""

### ISSUE THREAD

**Issue by Jean-Bernard-Hallez** [alexylem/jarvis#591]
Et coucou... la correction a apporté une augmentation considérable sur l'ensemble des plugins... cependant j'en ai encore 1 qui bug... celui des blagues.... même problème qu'avant... il manque le .mp3
Problème identifié de la même manière que l'espace d'avant mais cette fois si, si il n'y a que "...":

http://asciinema.org/a/55qba6b3t1bi63pk48er015d8

**Comment by alexylem** [comment]
```shell
say "..."
```
Après "sanitization" il n'y a plus rien... Et je ne sais pas comment ton TTS synthétise "...".
Rien à voir avec les noms trop longs tu l'auras compris...

**Comment by alexylem** [comment]
Implémenté sur la branch `beta`. Pour le tester dès à présent:
Menu `Settings > General > Branch > beta`
Sinon attendre la mise à jour de ce weekend.

**Comment by Jean-Bernard-Hallez** [comment]
Ok ca fonctionne...   ;-)

**Comment by Jean-Bernard-Hallez** [comment]
J'ai encore un bug sur un de mes plugins qui fonctionnait avant... Jarvis turing mais je ne sais pas encore ou est le problème... à suivre

**Comment by Jean-Bernard-Hallez** [comment]
J'ai encore un problème avec mon plugin Turin... là je sèche un peu... le problème c'est qu'il me tire des phrase aléatoirement par ci et par là... un simple copier coller fonctionne... dur dur... voici ce qu'il me dit;
jarvis: Salut JB,
lundi 8 mai 2017, 18:36:47 (UTC+0200) (standard_in) 1: illegal character: '
lundi 8 mai 2017, 18:36:47 (UTC+0200) (standard_in) 1: syntax error
lundi 8 mai 2017, 18:36:47 (UTC+0200) jarvis:
lundi 8 mai 2017, 18:36:47 (UTC+0200) Te souviens-tu quand tu m'as répondu à ma question: que ta couleur préféré était le: bleu ciel, pour quelle raison as tu fais ce choix ? ?

**Comment by alexylem** [comment]
@Jean-Bernard-Hallez j'aimerais t'aider mais je ne sais pas si l'erreur est dans Jarvis ou dans ton plugin.
Je vois `illegal character: '` c'est sûrement le point de départ. Tu sais ou cette erreur arrive? A quelle ligne?

**Comment by Jean-Bernard-Hallez** [comment]
C'est exactement ce que je recherche... mais je ne sais pas encore ou ca bug... je n'arrive pas à le reproduire... lol

**Comment by Jean-Bernard-Hallez** [comment]
Il y a d'autre bug sur le même principe qu"avant...

jarvis: Tu as combien de frères et sœurs ? ?
mardi 9 mai 2017, 09:42:18 (UTC+0200) jibé: j'ai quatre frère et sœur
mardi 9 mai 2017, 09:42:18 (UTC+0200) jarvis: Vos parents ont eu le choix du roi, ils doivent êtres les plus heureux !!
mardi 9 mai 2017, 09:42:18 (UTC+0200) belle famille ! tu as 4 soeurs ! et  tu as 4 frères !
mardi 9 mai 2017, 09:42:18 (UTC+0200) Une famille nombreuse... est-ce vraiment possible... je doute car ca fait beaucuop lol
mardi 9 mai 2017, 09:42:18 (UTC+0200) Comment s'appellent tes soeurs ?

le fichier dev/shm/vos_parents_ont_eu_le_choix_du_roi_ils_doivent_etres_les_plus_heureux__

il manque encore le mp3...

Et je n'arrive pas encore a trouver pourquoi... je continu ma recherche...

**Comment by Jean-Bernard-Hallez** [comment]
OK... dans mon déroulé du turing il y a des echo "blablabla" et say "blablabla"... avant les echo passaient sans problème... j'ai remarqué que si je les remplacent tous pas say... je n'ai plus ce problème...  !!! Je cloture...

**Comment by Jean-Bernard-Hallez** [comment]
Il m'a fallut modifier tout mon plug... la commande était 
GOTO1==say "$(jv_pg_ct_auchoixquestion)"
transformé en 
GOTO1==jv_pg_ct_auchoixquestion
avecm modif de tous mes echo en say dans le fichier functions.sh...
car à l'intérieur il y a des variable qui vont rechercher une réf dans un autre plugin et ca causait des problème qu'il n'y avait pas avant
resultat1=`echo $(jv_pg_wk_search "$order")   qui allait checher dans le plug dictionnaire a quoi correspond la couleur que l'on aime... soit il y avait 2 say et ca lui plaisait pas...

**Comment by Jean-Bernard-Hallez** [comment]
Du coup... Ca me fait tout chambouler... j'utilisais dans la fonction du turing:
eval echo "\$QUESTIONHASARD$number"
qui fonctionne bien en echo... 
mais plus en say snif...

**Comment by Jean-Bernard-Hallez** [comment]
J'abandonne pour le moment il y a top d'erreur que je n'avais pas... j'attends de voir si il y a d'autre retour que moi...

**Comment by Jean-Bernard-Hallez** [comment]
Encore un indice de bug:
http://asciinema.org/a/7wsq1tzf8mozx2oboaicdqmjl
lorsque dans un plugin on mélange de l'echo + say il répète 2 fois la fonction avec un truc du genre:
blaguebug1 () {
order="bleu"
say "la couleur est le bleu"
echo "beaucoup de chance"
say "jaime ca"
}
 il va bien tout écrire mais il va dire verbalement et presque double:

la couleur est le bleu, j'aime ca, 95 M J arvis 0 mètre 
la couleur est le bleu beaucoup de chance  95 M J arvis 0 mètre j'aime ca

Il va me sortie des truc de je ne sais ou !!!!! 

Et c'est ca qui me bug des plugins car ça n’apparaît pas dans les log !!!!!!!!!!!!!!!!!!!!!

**Comment by alexylem** [comment]
Je reproduis le pb chez moi...
![image](https://cloud.githubusercontent.com/assets/11017174/25864526/0ad5157a-34f0-11e7-9aea-6c761021939a.png)

Les 95 M & co viennent du code couleur de Jarvis:
```shell
_pink="\033[95m"
```
Il ne devrait pas afficher `Jarvis:` dans la phrase prononcée, c'est ça le pb... je regarde...

**Comment by alexylem** [comment]
Ah c'est bon j'ai compris.
Dans la commande tu fais `say` de l'output de `blaguebug1`:
```
*BLAGUE*==say "$(blaguebug1)"
```
Et dans la la fonction `blaguebug1` tu fais des says... Il faut choisir!!

Change simplement ta commande en:
```
*BLAGUE*==blaguebug1
```
Et ca devrait marcher 😄

**Comment by Jean-Bernard-Hallez** [comment]
Oui ca,  ca marche... j'ai passé l'après-midi en modifiant cela ainsi alors qu'avant ca marchait bien...
mon gros problème c'est que j'ai besoin des deux... j'utilise des sous variable avec la fonction eval echo...
sui ne marche pas en say quelquechose... lol et autres...

**Comment by alexylem** [comment]
Tu n'as pas besoin des deux.
Si tu veux que ta fonction fasse plusieurs say ou des echo, appelle juste ta fonction comme je t'ai montré plus haut, ca devrait suffire.

**Comment by Jean-Bernard-Hallez** [comment]
Je suis d'accord avec toi... mais on a tous des manières de faire des plugin différent...
C'est à dire dans mon turing je pose la question quel est ton sport préféré... puis il va rechercher dans le plugin wikipedia la définition du sport qui lui est ecrit avec la commande say "($XXXX)"
et donc si de mon coté je fais par commande say XXXX" je suis donc obligé de mettre dans la fonction un say... il le dit donc 2 fois !!!! Lol... etc...

**Comment by alexylem** [comment]
Ah ok je comprends mieux.
Si tu veux pouvoir faire interagir plusieurs plugins, il va falloir y réfléchir.
Peut-être utiliser l'API en `json` pour ca, et parser le retour de Jarvis.
A tester...

**Comment by Jean-Bernard-Hallez** [comment]
blaguebug1 () {
say "$(blaguebug2) voilà c'est fini"
say "$(blaguebug3)"
say "$(blaguebug4)"
}

blaguebug2 () {
order="ball"
resultat1=$(jv_pg_wk_search "$order")
echo "$resultat1"
}

blaguebug3 () {
say "tou va bien maintennant"
}

blaguebug4 () {
say "ceci est ok"
}

**Comment by Jean-Bernard-Hallez** [comment]
même comme ça... ca bug encore quand on fait des renvois sur des fonctions:
*TEST*==blaguebug1

blaguebug1 () {
say "$(blaguebug2) voilà c'est fini"
say "$(blaguebug3) enfin presque"
say "$(blaguebug4) dernier essai"
}

blaguebug2 () {
order="ball"
resultat1=$(jv_pg_wk_search "$order")
echo "$resultat1"
}

blaguebug3 () {
say "tout va bien maintennant"
}

blaguebug4 () {
say "ceci est ok"
}

**Comment by alexylem** [comment]
C'est normal je t'ai expliqué que tu ne peux pas faire un say du résultat d'une fonction qui fait déjà un say.
C'est ce que tu fais dans bug3 et bug4.

**Comment by Jean-Bernard-Hallez** [comment]
OK oups...

**Comment by alexylem** [comment]
Je pense que c'est pke tu fais un say d'un texte multiligne. Essaye de ne faire qu'un seul echo par function (notamment dans bug3).

**Comment by Jean-Bernard-Hallez** [comment]
Je ne peux pas faire qu'un echo... oui en effet si je fais ca, bien sur que ca marche... mais ca fontionnait bien avant la mise a jour snif...

**Comment by Jean-Bernard-Hallez** [comment]
J'ai pensé à mettre aussi dans des variable mes echos puis de le ressortir en 1 fois !
La "cata" car il n"y a plus de ponctuation... Jarvis ne respire plus lol...

**Comment by alexylem** [comment]
Quelle mise à jour?
Essaye de le faire par l'API il y a des chances que ca marche:
```
$> ./jarvis.sh -b
$> ./jarvis.sh -x "TEST"
```

**Comment by Jean-Bernard-Hallez** [comment]
Oui ca fonctionne... mais si je parle directement au micro...

**Comment by alexylem** [comment]
Ok je vais voir ce que je peux faire...

**Comment by alexylem** [comment]
Implémenté sur la branch `beta`. Pour le tester dès à présent:
Menu `Settings > General > Branch > beta`
Sinon attendre la mise à jour de ce weekend.

**Comment by Jean-Bernard-Hallez** [comment]
Encore une erreur snif... lorsque qu'il lit un vide comme juste un espace... 

*TEST*==blaguebug1

blaguebug1 () {
say " "
}

en effet par tirage au sort j'utilise des phrases ou... rien justement... et là ca bug...

A la question depuis quelle mise à jour... je ne sais pas trop de pense que c'est depuis qu'il y a les bug avec les caractères 'spéciaux' justement.

**Comment by alexylem** [comment]
C'est quoi le message d'erreur?

**Comment by Jean-Bernard-Hallez** [comment]
jibé: test
jarvis:
ERROR: play command failed
HELP: Verify your speaker in Settings > Audio > Speaker

jarvis: J'ai rencontré une erreur, relancez-moi!
pi@raspberrypi:~/jarvis $

**Comment by alexylem** [comment]
En effet `say " "` et `say ""` plantent. Je vais voir ce que je peux faire.

**Comment by alexylem** [comment]
Implémenté sur la branch `beta`. Pour le tester dès à présent:
Menu `Settings > General > Branch > beta`
Sinon attendre la mise à jour de ce weekend.

**Comment by Jean-Bernard-Hallez** [comment]
Et coucou.... C'est tout bon ca fonctionne très bien en version bêta...  merci... je re-teste tout...

**Comment by Jean-Bernard-Hallez** [comment]
Désolé Alex... il y a encore un bug...
lorsque l'on utilise le  "Multi-command separator" (j'utilise 'puis') avec jarvis "-x température chambre puis météo puis fête à qui puis prochainevenement puis une citation"" ok ca fonctionne...:
lundi 15 mai 2017, 13:20:11 (UTC+0200) [95mjarvis[0m: je mesure,... température chambre est de  22.6 degrés
lundi 15 mai 2017, 13:20:11 (UTC+0200) [91mERROR: Jarvis is not running[0m
lundi 15 mai 2017, 13:20:11 (UTC+0200) [92mHELP: Start Jarvis using jarvis -b[0m
lundi 15 mai 2017, 13:20:12 (UTC+0200) [95mjarvis[0m: La météo aujourd'hui,...
lundi 15 mai 2017, 13:20:12 (UTC+0200) [91mERROR: Jarvis is not running[0m
lundi 15 mai 2017, 13:20:12 (UTC+0200) [92mHELP: Start Jarvis using jarvis -b[0m
lundi 15 mai 2017, 13:20:13 (UTC+0200) [95mjarvis[0m: Ciel plutôt dégagé et vent. Maximales : 27 degrés. Vents Nord soufflant de 30 à 50 km/h.
lundi 15 mai 2017, 13:20:13 (UTC+0200) [91mERROR: Jarvis is not running[0m
lundi 15 mai 2017, 13:20:13 (UTC+0200) [92mHELP: Start Jarvis using jarvis -b[0m
lundi 15 mai 2017, 13:20:13 (UTC+0200) [95mjarvis[0m: on est le 15 Mai C'est la Saint Denise
lundi 15 mai 2017, 13:20:13 (UTC+0200) [91mERROR: Jarvis is not running[0m
lundi 15 mai 2017, 13:20:13 (UTC+0200) [92mHELP: Start Jarvis using jarvis -b[0m
lundi 15 mai 2017, 13:20:14 (UTC+0200) [95mjarvis[0m: C'est aujourd'hui et c'est l'anniversaire de Justine...
lundi 15 mai 2017, 13:20:14 (UTC+0200) [91mERROR: Jarvis is not running[0m
lundi 15 mai 2017, 13:20:14 (UTC+0200) [92mHELP: Start Jarvis using jarvis -b[0m
lundi 15 mai 2017, 13:20:14 (UTC+0200) [95mjarvis[0m: le jeudi 30 mai  dans 15 jours et ça sera les 43 ans de l'anniversaire de Sousou.
lundi 15 mai 2017, 13:20:14 (UTC+0200) [91mERROR: Jarvis is not running[0m
lundi 15 mai 2017, 13:20:14 (UTC+0200) [92mHELP: Start Jarvis using jarvis -b[0m
lundi 15 mai 2017, 13:20:14 (UTC+0200) 
lundi 15 mai 2017, 13:20:14 (UTC+0200) [95mjarvis[0m: Voici une citation:  Conquérir sa joie vaut mieux que de s'abandonner à la tristesse
lundi 15 mai 2017, 13:20:14 (UTC+0200) [91mERROR: Jarvis is not running[0m
lundi 15 mai 2017, 13:20:14 (UTC+0200) [92mHELP: Start Jarvis using jarvis -b[0m


Mais quand on le mets dans une fonction comme ceci:
*TEST*==testprog

testprog() {
jv_handle_order "température chambre puis météo puis fête à qui puis prochainevenement puis une citation"
}

Il me sort que la météo et pas le reste....

lundi 15 mai 2017, 13:22:03 (UTC+0200) [2mUse "?" to display possible commands (in keyboard mode)[0m
lundi 15 mai 2017, 13:22:03 (UTC+0200) [95mjarvis[0m: Waiting to hear 'jarvis'
lundi 15 mai 2017, 13:22:11 (UTC+0200) [96mjibé[0m: [2m[0mjarvis
lundi 15 mai 2017, 13:22:12 (UTC+0200) [95mjarvis[0m: Oui ?
lundi 15 mai 2017, 13:22:17 (UTC+0200) [96mjibé[0m: |/-\|/-\|/-\|/-\un test
lundi 15 mai 2017, 13:22:17 (UTC+0200) [95mjarvis[0m: C'est aujourd'hui et c'est l'anniversaire de Justine...
lundi 15 mai 2017, 13:22:21 (UTC+0200) [95mjarvis[0m: le jeudi 30 mai  dans 15 jours et ça sera les 43 ans de l'anniversaire de Sousou.
lundi 15 mai 2017, 13:22:38 (UTC+0200) [96mjibé[0m: [2m(timeout)[0m
lundi 15 mai 2017, 13:22:39 (UTC+0200) [95mjarvis[0m: Waiting to hear 'jarvis'



je te fais une copie du débug il n'y a aucun bug:
DEBUG: curl https://speech.platform.bing.com/recognize/query?version=3.0&requestid=f8e40c83-ea6a-4b72-baef-767d8730c54a&appid=D4D52672-91D7-4C74-8AD8-42B1D98141A5&format=json&locale=fr-FR&device.os=linux&scenarios=ulm&instanceid=E043E4FE-51EF-4B74-8133-B728C4FEA8AA&result.profanitymarkup=0
DEBUG: json={"version":"3.0","header":{"status":"success","scenario":"ulm","name":"une pomme","lexical":"une pomme","properties":{"requestid":"5cc05902-7917-46d0-ac0b-d42915c37724","HIGHCONF":"1"}},"results":[{"scenario":"ulm","name":"une pomme","lexical":"une pomme","confidence":"0.8886437","properties":{"HIGHCONF":"1"}}]}
une pomme
$> fais le test
$> jv_pg_ct_prochainevenement
DEBUG: start_speaking hook
jarvis: C'est aujourd'hui et c'est l'anniversaire de Justine...
DEBUG: using cache /dev/shm/cest_aujourdhui_et_cest_lanniversaire_de_justine.mp3
DEBUG: stop_speaking hook
DEBUG: start_speaking hook
jarvis: le jeudi 30 mai  dans 15 jours et ça sera les 43 ans de l'anniversaire de Sousou.
DEBUG: using cache /dev/shm/le_jeudi_30_mai__dans_15_jours_et_ca_sera_les_43_ans_de_lanniversaire_de_sousou.mp3
DEBUG: stop_speaking hook
jibé: (listening...)
DEBUG: start_listening hook
utils/timeout.sh 10 rec -V1 -q -r 16000 -c 1 -b 16 -e signed-integer --endian little /dev/shm/jarvis-record.wav gain  -5 silence 1 0.1 2.1% 1 0.7 2.1% pad 0.5 0.5 trim 0 5

**Comment by Jean-Bernard-Hallez** [comment]
Oups/
