### ISSUE TITLE
Annoncer une commande avec un mot clef pour des commandes sensibles

### ISSUE THREAD

**Issue by Sellig28** [alexylem/jarvis#593]
### Description

Amazon have some problem with alexia with an ad which tell alexia to order some toys.

Perhaps it will be good to think about a simple security for specials  commands.

For example:

me: Could you activate the alarm ?
Jarvis: password is needed for this action.
me: bluesky
jarvis: Alarm activated

Not a bad idea ?

**Comment by alexylem** [comment]
Already possible with nested commands:
```
*ACTIVAT*ALARM*==say "password is needed for this action."
>(*)==[ "(1)" == "bluesky" ] && say "Alarm activated" || say "wrong password"
```
