### ISSUE TITLE
Il y a t-il la possibilité de modifier le TEMPO dans une fonction .... ?

### ISSUE THREAD

**Issue by Jean-Bernard-Hallez** [alexylem/jarvis#595]
En faisant des essais sur le TEMPO dans le fichier de configuration de jarvis une idée m'est venue....

Il peut être intéressant de pouvoir dans une fonction le modifier afin d’altérer l'état de la voix... quand elle est en colère par exemple, en augmentant la vitesse ... (ça me serai utile pour le plugin jarvis-tirung).

**Comment by alexylem** [comment]
Belle idée...
Tu peux le faire ainsi:
```shell
local old_tempo=$tempo
tempo=1.5
say "je parle rapidement"
tempo=$old_tempo
say "je reparle normalement"
```

**Comment by Jean-Bernard-Hallez** [comment]
Merci ca marche bien...  ;-)

**Comment by Jean-Bernard-Hallez** [comment]
Oui ca marche super bien...   ;-) je clôture... Merci...
