### ISSUE TITLE
plugin FB-MESSENGER

### ISSUE THREAD

**Issue by polbru40** [alexylem/jarvis#596]
plugin FB-MESSENGER

J'arrive pas a configurer le plugin. J'ai créé une page facebook, j'ai spécifié dans le fichier de configuration l'adresse émail et le mot passe. Pour le reste je ne vois pas se que je dois mettre. Je met si dessous se que je reçois sur le terminal et je comprends pas pourquoi j'ai l'erreur sur le login ?

jarvis: Bonjour monsieur
DEBUG:root:Initializing Facebook messenger server with email 'anneberthol1977@gmail.com', getId='False', verbose='True',  mute='True', allowAll='False' and allowedList='['id_1_here', 'id_2_here', 'id_3_here', '...']'.
**ERROR:root:Login failed, check email/password.**
WARNING:root:Facebook Messenger server crashed. Restarting...
Traceback (most recent call last):
  File "/home/pi/jarvis/plugins_enabled/jarvis-fb-messenger/script/facebook_server.py", line 160, in <module>
    jarvis_fb_server.listen()
  File "/usr/local/lib/python3.4/dist-packages/fbchat/client.py", line 935, in listen
    self.startListening()
  File "/usr/local/lib/python3.4/dist-packages/fbchat/client.py", line 911, in startListening
    self.sticky, self.pool = self._getSticky()
  File "/usr/local/lib/python3.4/dist-packages/fbchat/client.py", line 740, in _getSticky
    "channel": self.user_channel,
AttributeError: 'JarvisFacebookMessengerServer' object has no attribute 'user_channel'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/pi/jarvis/plugins_enabled/jarvis-fb-messenger/script/facebook_server.py", line 170, in <module>
    jarvis_fb_server.stop_listening()
AttributeError: 'JarvisFacebookMessengerServer' object has no attribute 'stop_listening'

**Comment by alexylem** [comment]
Pour toute question ou problème lié à un plugin Jarvis, merci de créer un ticket sur le repository correspondant. Ainsi son auteur en sera informé et pourra vous aider.

**Ok, alors c'est où?**
* Depuis Jarvis, allez dans Plugins > Installed > The Plugin > Report an issue
* Depuis le site, allez sur la page du plugin et cliquez sur le lien "Open a ticket"

Autrement dit, je ne fait pas de support pour les plugins tiers.
Merci de votre compréhension.
