### ISSUE TITLE
Missing execution rights on some plugin scripts

### ISSUE THREAD

**Issue by Jean-Bernard-Hallez** [alexylem/jarvis#597]
### Description
Lorsque l'on désactive un plugin pour le remettre en service et que ce plugin comporte des sous fichiers avec extention.sh,  il enlève les droits d’exécution  (chmod +x XXXX.sh) et donc il ne fonctionne plus...
Comment y remédier ?

**Comment by alexylem** [comment]
On dirait en effet qu'il y a quelques fichiers sans les droits d'exécution dans le modèle de plugin... je vais corriger ca:
![image](https://cloud.githubusercontent.com/assets/11017174/25863097/bcd51956-34ea-11e7-9fd6-35c650bff0be.png)
En attendant, après avoir installé le plugin, il faut:
```shell
chmod -R a+x *.sh
```
