### ISSUE TITLE
probleme Android et tasker

### ISSUE THREAD

**Issue by kevin532** [alexylem/jarvis#599]
Bonjour à tous,

j'ai installé Jarvis et j'aimerai pouvoir l'utiliser sur mon android (Samsung galaxy s4 Mini). 
J'ai donc suivi le tuto ( [domotiquefacile.fr](http://domotiquefacile.fr/jarvis/content/voice-control-from-android-device)) mais j'ai une erreur que je n'arrive pas à résoudre seul avec l'aide de mon ami Google.
Donc en faites quand j'ai fini de créer la tache pour donner un ordre à Jarvis ( Alicia pour moi) depuis mon mobile je tente donc de la tester et ça m'affiche ceci :

![erreur tasker](https://cloud.githubusercontent.com/assets/28564933/25873852/4f165cb0-3510-11e7-91a7-38f67124650a.png)

je ne trouve rien au sujet de cette erreur donc je m'en remets a vous

merci d'avance 
Kevin

**Comment by alexylem** [comment]
Timeout, on dirait que l'IP/Port n'est pas accessible depuis ton tel.
Tu es bien sur le même réseau que Jarvis? Il est bien démarré avec le plugin API activé?
Essaye directement d'entrer l'url de l'API depuis un navigateur pour voir...

**Comment by kevin532** [comment]
Merci pour ta réponse rapide alors quand je tape directement dans mon
navigateur ou est installer jarvis ça fonctionne mais pas sur un autre pc
sur le même réseau et oui jarvis est lancer et le plugin api activité.
Je tourne en rond 😩

**Comment by Oliv4945** [comment]
Quel est le résultat de `jarvis -nv` et `sudo iptables --list` ?
Quand tu utilises le navigateur sur le PC où Jarvis est installé, que tapes
tu comme adresse ? localhost, 127.0.0.1 ou l'IP du PC ?

**Comment by kevin532** [comment]
Alors je comprend pas a quoi ca correspond mais ca t'aidera peu etre 
kevin@Kevin:~/jarvis$ sudo iptables --list
[sudo] password for kevin: 
Chain INPUT (policy ACCEPT)
target     prot opt source               destination         

Chain FORWARD (policy ACCEPT)
target     prot opt source               destination         

Chain OUTPUT (policy ACCEPT)
target     prot opt source               destination

**Comment by kevin532** [comment]
et pas de resultat pour l' autre 
kevin@Kevin:~/jarvis$ jarvis -nv
bash: jarvis : commande introuvable

**Comment by Oliv4945** [comment]
Pour iptables c'est le firewall de Linux, qui aurait pu empêcher Jarvis de communiquer avec les autres PC.
Pardon, c'est `./jarvis.sh -nv` :-)

**Comment by kevin532** [comment]
kevin@Kevin:~/jarvis$ ./jarvis.sh -nv
cat: /proc/asound/card0/usbid: Aucun fichier ou dossier de ce type
lsusb: option requires an argument -- 'd'
Usage: lsusb [options]...
List USB devices
  -v, --verbose
      Increase verbosity (show descriptors)
  -s [[bus]:][devnum]
      Show only devices with specified device and/or
      bus numbers (in decimal)
  -d vendor:[product]
      Show only devices with the specified vendor and
      product ID numbers (in hexadecimal)
  -D device
      Selects which device lsusb will examine
  -t, --tree
      Dump the physical USB device hierarchy as a tree
  -V, --version
      Show version of program
  -h, --help
      Show usage and help

------------ Config ------------
jv_branch            master 
jv_version            
jv_arch              x86_64 
jv_os_name           debian 
jv_os_version        8 
language             fr_FR 
play_hw              false 
rec_hw               hw:0,0 
speaker              Default 
microphone            
recorder             sox 
trigger_stt          bing 
command_stt          bing 
tts_engine           google 
--------------------------------

DEBUG: program_startup hook
Starting RestAPI server on http://192.148.63.217:8080
DEBUG: start_speaking hook
alicia: Salut

**Comment by Oliv4945** [comment]
>  Starting RestAPI server on http://192.148.63.217:8080

Merci, est-ce que c'est la bonne adresse IP pour ta machine ? Car c'est peu courant sur un réseau interne. Que donne un ping du PC qui ne fonctionne pas vers le PC où Jarvis est installé ?

Sinon je ne sais pas si tu as vu l'[application Android](https://github.com/Oliv4945/jarvis-android-app) ? Si c'est le cas est-ce que tu préfères Tasker pour l'intégration à Google Now ?

**Comment by kevin532** [comment]
non c'est pas la bonne je l'ai changer pour le post ! l'autre pc est sur windows est ce que tu sais ce que je dois taper ?
non je ne connais pas je vais essayer

**Comment by kevin532** [comment]
avec l'app que tu m'as propose ca ne fonctionne pas non plus

**Comment by kevin532** [comment]
Bonjour,
Juste pour d'autre a qui ce problème pourrait arriver, après des heures j'ai enfin trouvé.
J'utilisais un téléphone avec partage de connections wifi pour avoir le net sur mon ordi depuis quelques mois car mon dongle wifi est instable avec Debian, et étant au bout de mon désespoir je me suis dit ça me coûte rien d'essayer en rebranchant celui ci au première essai ça a marcher direct :smiley: ! 
Je ne comprend pas trop pourquoi, sûrement un conflit avec l'adresse ip du téléphone mais au moins maintenant je sais pourquoi et j'ai plu qu’a acheter un dongle compatible Linux.
Merci pour votre aide
kevin

**Comment by Oliv4945** [comment]
Super, effectivement le téléphone ne permet pas aux équipements connectés dessus de discuter entre eux.
