### ISSUE TITLE
Micro plante à cause du timeout. Obligé de dire annuler à chaque fois.

### ISSUE THREAD

**Issue by alexylem** [alexylem/jarvis#6]
concernant le problème de MIC que je t'ai reporté, en fait si tu sors du mode conversation par toi même par annulé , tout va bien,

mais si après la dernière commande tu ne dis rien , on obtient toujours l'erreur : rec FAIL formats: can't open input `hw:1,0': snd_pcm_open error: Device or resource busy

ERROR: rec command failed

Patrick

**Comment by alexylem** [comment]
C'est peut-être le timeout de 10 secs (avec un kill derrière) qui fait bugger le micro. Il faut que je trouve un autre moyen de stopper la reconnaissance proprement...
En attendant, dans la config, tu peux désactiver le mode conversation pour qu'il n'écoute qu'une seule commande.
Alex.

**Comment by alexylem** [comment]
*Temporairement* voici la procédure à suivre:
- Solution 1) 

> Rébrancher et rebrancher le micro, puis relancer Jarvis.

- Solution 2)

```
pkill jarvis.sh # exit jarvis
lsusb # identify Bus XXX Device YYY of your mic
sudo ./usbreset /dev/bus/usb/XXX/YYY # with XXX and YYY from above
```

**Comment by remjou1** [comment]
oui c vrai qu'il serait pas mal qu'il y ait une option pour stopper proprement la reco...

**Comment by patrick95470** [comment]
Alex,

en fait même si je désactive le mode conversation, j'ai toujours un plantage 


SNOWBOY: Bonsoir YODA
SNOWBOY: Waiting to hear 'SNOWBOY'
YODA: SNOWBOY
SNOWBOY: Oui?
YODA: .
SNOWBOY: Waiting to hear 'SNOWBOY'
YODA: ERROR: snowboy recognition failed


PS: merci pour ta remarque sur mon Anglais, ( je bosse pour une boite Danoise, donc tu imagines que l'anglais est aussi pour moi comme une seconde langue :-0 )

**Comment by alexylem** [comment]
Désolé pour la remarque, je pensais que c'était à cause de ca. C'est peut-être le micro alors car chez moi c'est 100%.
C'est normal que le scenario ci-dessus plante car tu n'as pas dit de commande, donc timeout.
Si tu dis une commande, il va se remettre en mode attente de mot clé.

**Comment by patrick95470** [comment]
je t’en prie, en fait ce qui est étrange c’est la première fois que tu as introduit SNOWBOY la reconnaissance était vraiment hyper rapide, et que maintenant c’est plus lent…

rien de logique tout cela, 

et je te confirme avoir toujours le même problème si je tape

> alsamixer -c 1 -V capture

j’obtiens le message d’erreur 

les commandes de mixage ne peuvent pas être chargés: Argument invalide

on va y arriver :-)

Patrick

**Comment by alexylem** [comment]
Problème avec `alsamixer` à suivre dans ce ticket: #26

**Comment by alexylem** [comment]
Le problème devrait enfin être résolu avec cette mise à jour. Merci de vérifier et n'oubliez pas d'enlever la solution de contournement et remettre le mode conversation à `on` si nécessaire.
