### ISSUE TITLE
mode conversation false auto avec l'option -l

### ISSUE THREAD

**Issue by remjou1** [alexylem/jarvis#60]
voila j'utilise fréquemment les deux "méthodes" principale utilisables avec jarvis (la méthode bouton et terminal) mais voila :
-lorsque je suis en mode terminal je veux etre en mode conversation (logique)  mais,
-lorsqu je suis en mode bouton je voudrais etre en mode non-conversation (logique aussi)

donc comme mon script utilise l'option -l de jarvis je voudrais savoir si c'était possible que lorsque l'on utilise l'option -l ça mette automatiquement le mode conversation en false

merci

**Comment by alexylem** [comment]
J'aimerais ne pas faire ca car il doit y avoir des gens qui voudraient lancer depuis un bouton mais malgré tout bénéficier du mode conversation. Et puis ce n'est pas logique car ca ne suit pas ce qui est mis dans les settings / general / conversation mode. Au pire je peux ajouter un flag pour overrider la préférence utilisateur, ex:
```
./jarvis.sh -l -c false
-c    override conversation mode (true/false)
```

**Comment by remjou1** [comment]
oui ce serait géniaal merci beaucoup !!

**Comment by remjou1** [comment]
oui ce serait génial !! merci

**Comment by remjou1** [comment]
euh coucou... je viens de voir que tu l'a implementé mais ça ne marche pas :(

**Comment by alexylem** [comment]
Tu peux me donner une exemple? Voici comment l'utiliser:
```
./jarvis.sh -l -c false
```

**Comment by remjou1** [comment]
bah je le lance exactement comme ça :

```
sudo ./jarvis.sh -l -c false
```
mais une fois qu'il a executé une commande il ne s'arrète pas

**Comment by alexylem** [comment]
En effet, je corrige

**Comment by remjou1** [comment]
nickel ça marche merci
