### ISSUE TITLE
lecture en accélerée

### ISSUE THREAD

**Issue by xmeslin** [alexylem/jarvis#600]
Bonjour,

Quand j'ai fait l'install j'ai bien enregistré ma voix pour tester et au moment de la lecture a lecture était comme en accélérer. Quand la lecture s'est faite, j'entendais une sorte de mer pas en accélérer.
J'utilise un jabra PHS002W comme micro et haut-parleur et un rasp1b comme linux.

Merci

Xavier

**Comment by alexylem** [comment]
Ca me dit qqchose... voir #319 and #65

**Comment by xmeslin** [comment]
oui je viens de tomber dessus :) Ca marche presque. pardon pour le dup
