### ISSUE TITLE
Utilisation basique de Jarvis - Probleme avec la synthese vocale

### ISSUE THREAD

**Issue by ThomasTRUILHE** [alexylem/jarvis#601]
Bonjour,

je viens d'installer Jarvis sur une carte Raspberry 3 et je voudrais dans un premier temps
pouvoir lui faire dire des phrases toutes simples en utilisant la synthèse vocale.  Cependant,
j'arrive simplement à entendre la phrase "Hello" en démarrant Jarvis, mais je ne parviens
pas à entendre d'autres sons/phrases lors de son utilisation.

Sauriez-vous me dire s'il y a une manière simple de configurer Jarvis pour pouvoir lui faire
dire quelques phrases simples par la suite en utilisant la synthèse vocale ?

Cordialement,

**Comment by alexylem** [comment]
D'après la doc:
```shell
$> ./jarvis.sh -h
...
    -s  just say something and exit, ex: jarvis.sh -s 'hello world'
...
$> ./jarvis.sh -b # Jarvis doit être lancé
$> ./jarvis.sh -s "bonjour ceci est un test"
Jarvis: bonjour ceci est un test
$> 
```
Plus d'info sur le site:
http://domotiquefacile.fr/jarvis

**Comment by ThomasTRUILHE** [comment]
Bonjour,

merci pour votre réponse, c'est bien ce que j'ai essayé,
sauf que lorsque j'utilise cette commande, Jarvis répond correctement
uniquement par l'écriture d'un message à l'écran.
J'aurais voulu qu'il réponde via les enceintes en utilisant la synthese vocale.

Sauriez-vous comment faire svp ?

Cordialement,

**Comment by wikijm** [comment]
Bonjour @ThomasTRUILHE 

Je pense que tu n'as pas compris la réponse de @alexylem.

Il te demandait d'utiliser `./jarvis.sh -h` pour afficher l'aide.
Cette dernière t’annonce qu'il faut donc utiliser `./jarvis.sh -s "bonjour ceci est un test"` pour faire dire "bonjour ceci est un test" de façon orale (par synthèse vocale).

**Comment by ThomasTRUILHE** [comment]
Oui, c'est bien ce que je fais, j'ai utilisé la commande  ./jarvis.sh -s "bonjour ceci est un test"
sauf que la synthese vocale ne fonctionne pas et aucun son n'est émis.
C'est la raison pour laquelle je vous demandais s'il pouvait y avoir un probleme de configuration ?

**Comment by wikijm** [comment]
`./jarvish.sh -nv` te permettra de lancer Jarvis en troubleshooting mode (affichage de messages d'erreur et d'information plus complets).

Il faudra nous transmettre le résultat de cette commande afin de t'aider.

P.S : Je viens de ré-ouvrir l'issue pour toi, mais j'insiste sur le fait que tu es en mesure de le faire par toi-même directement sur GitHub.

**Comment by ThomasTRUILHE** [comment]
alors étrangement en lancant jarvis avec l'option

-nv -k, j'arrive à entendre le son par synthese vocale


------------ Config ------------
jv_branch            master 
jv_version            
jv_arch              armv7l 
jv_os_name           raspbian 
jv_os_version        8 
language             fr_FR 
play_hw              false 
rec_hw               false 
speaker              Default 
microphone           Default 
recorder             sox 
trigger_stt          snowboy 
command_stt          bing 
tts_engine           espeak 
--------------------------------

DEBUG: program_startup hook
DEBUG: start_speaking hook
jarvis: Hello
DEBUG: stop_speaking hook
Use "?" to display possible commands (in keyboard mode)
pi: merci
$> say "De rien"
DEBUG: start_speaking hook
jarvis: De rien

**Comment by ThomasTRUILHE** [comment]
Ce que je souhaiterais pouvoir faire à présent est faire la meme chose avec la commande -s

**Comment by Oliv4945** [comment]
@ThomasTRUILHE, quel est le résultat de `./jarvis.sh -vs "bonjour ceci est un test"` ?

**Comment by ThomasTRUILHE** [comment]
Je vais essayer ceci.
Sauriez-vous aussi me dire à quoi correspond trigger_stt et command_stt ?
C'est la partie qui consiste à pouvoir déclencher la réception d'une commande par le micro c'est cela ?

Que faudrait-il parametrer à ce niveau pour mettre jarvis en attente d'une commande audio
et que celui-ci se déclenche sans que l'on ait besoin de presser une touche (en fonction de la commande en fait) ? C'est ce qu'on appelle hotword ? Ceci consiste à déclencher Jarvis par un mot ou des mots clefs que l'on passe par la voix ?

**Comment by ThomasTRUILHE** [comment]
Idem, je ne parviens pas à avoir le son. Voici ce que jarvis renvoi :

DEBUG: start_speaking hook
jarvis: bonjour ceci est un test
ERROR: Jarvis is not running
HELP: Start Jarvis using ./jarvis.sh -b
DEBUG: stop_speaking hook

**Comment by Oliv4945** [comment]
> Sauriez-vous aussi me dire à quoi correspond trigger_stt et command_stt ?
C'est la partie qui consiste à pouvoir déclencher la réception d'une commande par le micro c'est cela ?

Oui, trigger_stt pour le hotword (généralement Snowboy) et command_stt pour la reconnaissance de la commande.

>Que faudrait-il parametrer à ce niveau pour mettre jarvis en attente d'une commande audio
et que celui-ci se déclenche sans que l'on ait besoin de presser une touche (en fonction de la commande en fait) ? C'est ce qu'on appelle hotword ? Ceci consiste à déclencher Jarvis par un mot ou des mots clefs que l'on passe par la voix ?

Un micro et configurer Jarvis. Je vous invite à lire l'aide [ici](http://domotiquefacile.fr/jarvis/content/prerequisites)


Pour votre problème on voit que Jarvis n'est pas démarré dans votre dernière commande. Il faut le lancer avec ` ./jarvis.sh -b` avant de l'appeler avec l'option `-s`

**Comment by ThomasTRUILHE** [comment]
Très bien, j'aurais encore une question svp,
sauriez-vous si il est possible d'interfacer Jarvis avec Python ou un autre langage ?
Je souhaiterais pouvoir depuis Jarvis envoyer des commandes à un programme sous Python
pour déclencher des actions.

Pour l'instant, Jarvis est lancé depuis Python via une commande.
    status = subprocess.call('sudo -u pi /home/pi/XXXXX/jarvis/jarvis.sh -n -k', shell = True)

Pensez-vous qu'il soit possible que Jarvis mette à jour une variable ? Ou ecrive dans un fichier ? ou autre ? Afin que le programme python qui l'ait lancé puisse déclencher des actions ?

**Comment by Oliv4945** [comment]
> sauriez-vous si il est possible d'interfacer Jarvis avec Python ou un autre langage ?

Il est possible d'écrire dans un fichier mais le plus simple est peut-être de définir un serveur `BaseHTTPServer ` dans votre application qui appelle Jarvis, et demander à Jarvis d'y faire appel grâce à curl avec une commande du type `*modifie*parametre==say "parametre modifié" && curl -s "http://localhost:port?parametre=5")`

Je clos le ticket vu que le problème initial est résolu, ne pas hésiter à le rouvrir si ce n'est pas le cas

**Comment by ThomasTRUILHE** [comment]
Bonjour,

je souhaiterais utiliser snowboy pour la reconnaissance vocale
et je tente de récupérer un "snowboy token" à l'adresse :
https://snowboy.kitt.ai
Malhereusement, je ne parviens pas jusqu'à la récupération du fichier.
J'arrive à faire les étapes Hotword détails, Record my voice and Test the model,
mais à la fin de l'étape Test the model, le bouton "Save" n'est jamais accessible.
Sauriez-vous pourquoi ?

**Comment by wikijm** [comment]
@ThomasTRUILHE Merci de créer un autre ticket pour ce problème, il n'est pas en lien avec le sujet initial.
Avant toute nouvelle question, je t'invite à suivre la procédure d'installation présente à cette adresse : http://domotiquefacile.fr/jarvis/content/installation

**Comment by wikijm** [comment]
@ThomasTRUILHE Merci de créer un autre ticket pour ce problème, il n'est pas en lien avec le sujet initial.
Avant toute nouvelle question, je t'invite à suivre la procédure d'installation présente à cette adresse : http://domotiquefacile.fr/jarvis/content/installation

**Comment by Oliv4945** [comment]
@ThomasTRUILHE : ça me faisait ça sur Safari je crois, en passant sous Chrome ça va mieux. Mais comme le dit @wikijm il vaut mieux créer un sujet pour ça, et ton soucis est avec Snowboy, donc [ici](https://github.com/Kitt-AI/snowboy/issues)
