### ISSUE TITLE
Problème du démarrage de Jarvis 

### ISSUE THREAD

**Issue by Mathieu6111** [alexylem/jarvis#603]
### Description

Je n'arrive pas à faire fonctionner Jarvis,Des que je fait Start Jarvis &  Start normally ça m'affiche des erreurs.

### Message d'erreur 
ALSA lib conf.c:4722:(snd_config_expand) Parse arguments error: Invalid argument
ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM hw:,
play FAIL formats: can't open output file `default': snd_pcm_open error: Invalid argument
ERROR: play command failed
HELP: Verify your speaker in Settings > Audio > Speaker  .

Pouvez-vous m'aider S.V.P ?.

Merci d'avance.

**Comment by alexylem** [comment]
@Mathieu6111 bizarre première fois que je vois cette erreur (enfin qui fini par Invalid argument).
Regarde déjà du côté de #61 ca ressemble pas mal.
Colle nous ton ~/.asoundrc et la log de démarrage de Jarvis en mode troubleshooting.

**Comment by Mathieu6111** [comment]
Voilà 
```
pcm.!default {
  type asym
   playback.pcm {
     type plug
     slave.pcm "hw:,"
   }
   capture.pcm {
     type plug
     slave.pcm "hw:,"
   }
}

```

```
`jarvis/jarvis.sh:` line 177: stt_engines/false/main.sh: No such file or directory
cat: /proc/asound/card,/id: No such file or directory
cat: /proc/asound/card,/usbid: No such file or directory
lsusb: option requires an argument -- 'd'
Usage: lsusb [options]...
List USB devices
  -v, --verbose
      Increase verbosity (show descriptors)
  -s [[bus]:][devnum]
      Show only devices with specified device and/or
      bus numbers (in decimal)
  -d vendor:[product]
      Show only devices with the specified vendor and
      product ID numbers (in hexadecimal)
  -D device
      Selects which device lsusb will examine
  -t, --tree
      Dump the physical USB device hierarchy as a tree
  -V, --version
      Show version of program
  -h, --help
      Show usage and help

------------ Config ------------
jv_branch            master
jv_version
jv_arch              armv7l
jv_os_name           raspbian
jv_os_version        8
language             fr_FR
play_hw              hw:,
rec_hw               hw:,
speaker
microphone
recorder             sox
trigger_stt          false
command_stt          bing
tts_engine           svox_pico
--------------------------------

DEBUG: program_startup hook
DEBUG: start_speaking hook
Jarvis: Hello
ALSA lib conf.c:4722:(snd_config_expand) Parse arguments error: Invalid argument
ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM hw:,
play FAIL formats: can't open output file `default': snd_pcm_open error: Invalid argument
ERROR: play command failed
HELP: Verify your speaker in Settings > Audio > Speaker

DEBUG: program_exit hook

```

Merci pour votre aide.

**Comment by Oliv4945** [comment]
Tes interfaces son ne sont pas définies, essaye de faire ./jarvis.sh->Settings->Step by step wizard

**Comment by Mathieu6111** [comment]
Merci ça fonctionne !,mais maintenant j'ai des erreurs comme ça qui s'affiche:
```
pi@raspberrypi:~/jarvis $ ./jarvis.sh
tts_engines/osx_say/main.sh: line 15: /usr/bin/say: No such file or directory
Jarvis: Hello
tts_engines/osx_say/main.sh: line 18: /usr/bin/say: No such file or directory
```
Merci pour votre aide.

**Comment by alexylem** [comment]
Ton text to speech engine est celui d'OSX normal... choisi picoTTS dans Setting > Speech Synthesis. Tu as bien lu et suivi toutes les étapes d'installation du Wizard ? Ou tu as répondu au hasard ^^

**Comment by wikijm** [comment]
@Mathieu6111 Pas de réponse depuis 27 jours, j'en conclus que le problème est résolu.
Ne pas hésiter à ré-ouvrir le ticket s'il y a une quelconque évolution 😉
