### ISSUE TITLE
Utilisation basique de Jarvis - Probleme avec la synthese vocale  #601 (suite)

### ISSUE THREAD

**Issue by ThomasTRUILHE** [alexylem/jarvis#605]
Bonjour,

merci pour votre réponse, j'ai bien essayé d'utiliser Jarvis via les commandes :

$> ./jarvis.sh -h
...
    -s  just say something and exit, ex: jarvis.sh -s 'hello world'
...
$> ./jarvis.sh -b # Jarvis doit être lancé
$> ./jarvis.sh -s "bonjour ceci est un test"
Jarvis: bonjour ceci est un test
$> 

 sauf que lorsque j'utilise cette commande, Jarvis répond correctement
 uniquement par l'écriture d'un message à l'écran.
 J'aurais voulu qu'il réponde via les enceintes en utilisant la synthese vocale.

Sauriez-vous comment faire svp ?

Cordialement,

**Comment by wikijm** [comment]
En doublon avec le #601.
Merci de ré-ouvrir ce dernier, mais pas d'en ouvrir un nouveau si même sujet et même contexte.
