### ISSUE TITLE
`program_exit` hook triggered 2 times in some cases

### ISSUE THREAD

**Issue by Oliv4945** [alexylem/jarvis#607]
Since 6a53d6766c7e9dc048217cd18fa5ea7c79e48a24, `program_exit` hook is triggered inside `jv_kill_jarvis()`, but in some case we can use `jarvis -q` while not started with `jarvis -b`
- Jarvis is running inside a terminal, we use `jarvis -q` in another terminal
- Jarvis is started thanks to `jarvis-systemd` plugin (so with `-q` option) and we close it with `jarvis -q`, `service stop` or `service restart`

And, when Jarvis is not started with `-b` option, SIGTERM signal send [here](https://github.com/alexylem/jarvis/blob/7ef015d18fe76d7f2e5c571e69fd80f516aa627c/utils/utils.sh#L348) is caught by jarvis.sh and `program_exit` hook is called another time

**Comment by alexylem** [comment]
Indeed, if you refer to my previous comment on your PR, this is because I use a dirty workaround in -q because when jarvis is started with -b the TERM is not properly caught.
I have to intevestigate further and make this work, removing this workaround (and so your PR) will avoid this situation...

**Comment by alexylem** [comment]
Ok I think I found a solution... for some reason the killing simply the parent process instead of the whole group works, and doesn't leave orpheans as it used to in the past.
Will push that to `beta` for you to test

**Comment by alexylem** [comment]
Implémenté sur la branch `beta`. Pour le tester dès à présent:
Menu `Settings > General > Branch > beta`
Sinon attendre la mise à jour de ce weekend.

**Comment by Oliv4945** [comment]
Nice, I test it soon

**Comment by Oliv4945** [comment]
Tested with success, thank you
