### ISSUE TITLE
snowboy token

### ISSUE THREAD

**Issue by Philmasse50** [alexylem/jarvis#610]
Bonjour;
Très intéressé par votre projet "jarvis", j'ai fais l'acquisition du matériel, avec hate j'ai commencer à suivre votre tuto pour l'installation, mais j'ai un problème.
la clef de snowboy token n'est pas reconnu et l'installation s’arrête, n'étant pas un grand spécialiste, je fais appel à vous pour me guider.
Je vais sur "https://snowboy.kitt.ai/", je m'identifie, j'ai bien un API token que je saisie lors de l'installation, mais rien n'y fait.
Merci de votre aide.
Philippe

**Comment by alexylem** [comment]
Ca nous aiderait que tu partages une session de ton terminal en utilisant [asciinema](http://asciinema.org) pour que l'ont voit exactement ce que tu fais et le message d'erreur:
```shell
sudo apt-get install -y asciinema && asciinema rec # start session recording
jarvis # start jarvis
Ctrl+D # stop recording
y # yes to upload and get URL to paste here
```

**Comment by Philmasse50** [comment]
Bonjour
Je reste bloqué sur la fenêtre "snowboy token", merci de bien vouloir m'aider.
ps : je suis débutant
Merci encore

**Comment by wikijm** [comment]
Bonjour @Philmasse50,

@alexylem t'as communiqué des choses à faire afin que l'on puisse voir où et comment tu te retrouve bloqué. Sans les suivre, difficile de t'aider.

**Comment by Philmasse50** [comment]
Rebonjour 
j'ai saisi ma clef et le je penses que cela fonctionne. 
Merci et bon courage pour ce très bon projet. 
Philippe
