### ISSUE TITLE
Jarvis- Utilisation de snowboy

### ISSUE THREAD

**Issue by ThomasTRUILHE** [alexylem/jarvis#611]
Bonjour,

     je tente d'utiliser snowboy avec Jarvis.
Pour cela, je viens de réaliser la configuration de Jarvis, et le téléchargement du
model snowboy correspondant au keyword "Jarvis".
Lorsque je lance Jarvis en mode troubleshooting, celui-ci se met correctement en attente du
keyword "Jarvis", apparemment il reconnait le mot clef, sauf qu'il ne réagit pas à la phrase suivante.

Par exemple, lorsque je prononce "Jarvis, bonjour", voici l'affichage :

jarvis: Waiting to hear 'jarvis'
thomastruilhe: (listening...)
DEBUG: models=jarvis
INFO:snowboy:Ticks: [2, 20, 5, -1]
INFO:snowboy:Keyword 1 detected at time: 2017-05-15 08:07:18
INFO:snowboy:Ticks status: 2 2 21 1
WARNING:snowboy:No match voice_after
INFO:snowboy:Keyword 1 detected at time: 2017-05-15 08:07:35
INFO:snowboy:Ticks status: 2 1 1 1
DEBUG: modelid=0
jarvis
DEBUG: entering_cmd hook
thomastruilhe: (listening...)
DEBUG: models=alexa,jarvis,snowboy
INFO:snowboy:Ticks: [2, 20, 5, -1]
DEBUG: timeout, end of conversation
DEBUG: listening_timeout hook
DEBUG: exiting_cmd hook
jarvis: Waiting to hear 'jarvis'
thomastruilhe: (listening...)
DEBUG: models=jarvis
INFO:snowboy:Ticks: [2, 20, 5, -1]

Jarvis ne répond pas à la commande.
Par contre, Jarvis fonctionne très bien au clavier.

Sauriez-vous m'aider ?

**Comment by alexylem** [comment]
Je peux avoir le début du log troubleshooting? (notamment le dump de la config).
Merci.

**Comment by ThomasTRUILHE** [comment]
Oui,

comment est-il possible de trouver le log ainsi que le log de la config ?

**Comment by alexylem** [comment]
Lance juste Jarvis en mode troubleshooting et copie/colle le contenu de la console. (Jarvis > Start > Troubleshooting mode). La config s'affiche au début.

**Comment by wikijm** [comment]
@ThomasTRUILHE Je clôture l'issue le temps que tu puisse fournir la vidéo ASCIINEMA et/ou avec le mode troubleshooting.
N'hésites pas à le rouvrir une fois fait 😉

**Comment by Mousseron** [comment]
Bonsoir 

etant dans le meme cas que lui, hotword reconnu mais timeout pour la commande, puis-je reouvrir le poste ? sinon si vous le souhaitez j'en ouvre un new

Voici un max d'info qui je pense vous sera utile


Results:                                                                 │                                     
                                     │ - Silence level: 0% (max 5%)                                             │                                     
                                     │ - Voice volume: 47% (min 30%, max 95%)                                   │                                     
                                     │ Sox parameters:                                                          │                                     
                                     │ - Microphone gain: 20                                                    │                                     
                                     │ - Min noise percentage to start: 0.1%                                    │                                     
                                     │ - Min silence percentage to stop: 0.1%                                   │                                     
                                     │                                           


snowboy comme moteur pour le hotword et pour les commandes
svox_pico pour le STT

et voici la capture du terminal

------------ Config ------------
jv_branch            master 
jv_version            
jv_arch              armv7l 
jv_os_name           raspbian 
jv_os_version        8 
language             fr_FR 
play_hw              false 
rec_hw               hw:1,0 
speaker              Default 
microphone           GN Netcom  
recorder             sox 
trigger_stt          snowboy 
command_stt          snowboy 
tts_engine           svox_pico 
--------------------------------

DEBUG: program_startup hook
Starting RestAPI server on http://192.168.1.39:8080
Starting User Interface on http://192.168.1.39:8081
DEBUG: start_speaking hook
jarvis: Bonjour Monsieur
DEBUG: stop_speaking hook
*/jai supprimé la partie aide avec les cmds:/*

jarvis: Waiting to hear 'jarvis'
Monsieur: (listening...)
DEBUG: models=jarvis
INFO:snowboy:Ticks: [2, 20, 5, -1]
INFO:snowboy:Keyword 1 detected at time: 2017-07-12 23:10:52
INFO:snowboy:Ticks status: 2 2 0 1
DEBUG: modelid=0
jarvis
DEBUG: entering_cmd hook
DEBUG: start_speaking hook
jarvis: oui monsieur
DEBUG: stop_speaking hook
Monsieur: (listening...)
DEBUG: models=alexa,jarvis,snowboy
INFO:snowboy:Ticks: [2, 20, 5, -1]
DEBUG: timeout, end of conversation
DEBUG: listening_timeout hook
DEBUG: exiting_cmd hook
jarvis: Waiting to hear 'jarvis'

merci d'avance .

**Comment by Oliv4945** [comment]
@Mousseron Dans les paramètres STT, essaie de basculer le command stt pour Bing à la place de Snowboy ;-)

**Comment by Mousseron** [comment]
@Oliv4945  top mille merci cela fonctionne parfaitement.
j'ai quelques questions je peux ? 
Pouquoi  snowboy en STT commande dysfonctionne ?
Pourquoi bing ? car plus performant ? 
par contre sur open jarvis en protection de la vie privée il est en ligne, cela veut dire que bill & friend's m’écoute en permanence lol :)
Ou tant que je ne dis pas mon hotword géré par snowboy par de soucis de mur aillant des oreilles ? 
Merci et desolé pour ses questions qui peuvent te paraître un peu stupides

**Comment by wikijm** [comment]
@Mousseron 
Snowboy est destiné à détecter des mots-clés, qui à son niveau sont reconnus sous la forme de son, et pas de texte. Snowboy n'est pas par conséquent pas un STT. En très simplifié, Il a pour rôle de dire "OK je connais ce son" ou  "KO, j'ai entendu du son, mais rien que je connaisse".

Bing est fait pour reconnaitre des mots dans un enregistrement/flux audio. Son catalogue de mots/phrases/expressions est bien plus fourni que celui de Snowboy. A performances réseaux égales, Bing sera plus performant pour comprendre des séquences de mots "longues", et Snowboy des séquences de mots "courtes".

**Comment by Oliv4945** [comment]
Pour compléter la réponse de wikijm il y a PocketSphinx en hors ligne, mais qui fonctionne moins bien.
