### ISSUE TITLE
"./jarvis.sh -j" command does not return valid JSON format

### ISSUE THREAD

**Issue by QuentinCG** [alexylem/jarvis#616]
### Description
Using `./jarvis.sh -j` command does not return valid JSON format.
This implies only one Jarvis instance can be used with some plugins... (jarvis-fb-messenger, jarvis-api, ...).
If we can have multi-users with Jarvis, this would not be a bug =P

I changed `./jarvis.sh` to `jarvis` in "jarvis-fb-messenger" plugin in order to have a working plugin: https://github.com/QuentinCG/jarvis-fb-messenger/commit/c16392ecdace01980d10ae09b1aace3e93369ab9

### Logs
```shell
pi@raspberrypi:~/jarvis $ ./jarvis.sh -j -x "test"
Notice: you can use 'jarvis' instead of './jarvis.sh'
[{"answer":"Ça fonctionne!"}]

pi@raspberrypi:~/jarvis $ jarvis -j -x "test"
[{"answer":"Ça fonctionne!"}]
```

**Comment by alexylem** [comment]
Implémenté sur la branch `beta`. Pour le tester dès à présent:
Menu `Settings > General > Branch > beta`
Sinon attendre la mise à jour de ce weekend.
