### ISSUE TITLE
Unsecured website (invalid HTTPS certificate or HTTP used by default)

### ISSUE THREAD

**Issue by QuentinCG** [alexylem/jarvis#617]
Hey,

This is not a "Jarvis bug" but a warning about the Jarvis website security:

openjarvis.com website doesn't use valid certificate and domotiquefacile.fr doesn't use https by default (http is the default) but uses a valid certificate.

If the server is under linux, [`let's encrypt` ](https://www.grafikart.fr/formations/serveur-linux/apache-ssl-letsencrypt)is the solution (really easy to install, free and valid certificate).

![login_warning](https://cloud.githubusercontent.com/assets/16922101/26309696/455caee8-3efe-11e7-9a8d-d98b94e70478.png)

**Comment by alexylem** [comment]
Certificate re-generation requested on OVH for some reason has still not ran:
![image](https://cloud.githubusercontent.com/assets/11017174/26520071/e529fa18-42cb-11e7-9d4b-bba570a19515.png)

**Comment by alexylem** [comment]
Certificate now generated:
![image](https://cloud.githubusercontent.com/assets/11017174/26645981/3ea04144-463a-11e7-9e0e-c75b95094892.png)

Shall I really force redirection to https?

**Comment by QuentinCG** [comment]
Nice 👍 

By default with Firefox (not tested with chrome or IE):
 - I write "openjarvis.com" in the address bar
 - Firefox redirects me to "http://openjarvis.com" (not https...)
 - I get the "unsecured connection" when I want to write my password and I get an "unsecured lock".
 - If I write "https://openjarvis.com", I have a secured connection.

--> If I were you, I would force redirection to https (or at least force it when logging in).

**Comment by alexylem** [comment]
Done, now forcing https
