### ISSUE TITLE
Comment créé un plugin pour envoyer un signal bleutooth ?

### ISSUE THREAD

**Issue by Dorian49770** [alexylem/jarvis#618]
### Description

Bonjour,

Je voudrais créé un plugin pour Jarvis pour qu'il envoi des info en bluetooth à un arduino connecté avec un module HC-06.

Je n'y connais rien :(

Est ce que qq pourrais m'aider?

Dorian

**Comment by Dorian49770** [comment]
Help

**Comment by alexylem** [comment]
Comme discuté par email je n'ai pas non plus d'expérience sur l'échange avec Arduino en bluetooth. J'ai un Arduino pour commander des relais, mais la communication est faite en ethernet (via shield ethernet), photo ci-dessous de mon installation:
![img_0711](https://cloud.githubusercontent.com/assets/11017174/26422110/ceae99ce-40c8-11e7-9ad0-55734512f1c7.JPG)
Le plugin est en cours de développement et sera bientôt disponible.

**Comment by Oliv4945** [comment]
Je ne peux que te conseiller de passer par Node red pour gérer le bluetooth, et faire un appel http de Jarvis vers Node red

**Comment by wikijm** [comment]
@Dorian49770 Je t'invite à faire des recherches avec les retours faits par @alexylem et @Oliv4945.
N'hésites pas à rouvrir l'issue pour nous exposer tes avancées 😉
