### ISSUE TITLE
executer un script python avec jarvis

### ISSUE THREAD

**Issue by ludoboss7** [alexylem/jarvis#619]
bonjour,
comment lancer un script python à partir de la commande vocale

la commande 
*ALLUM*CUISINE==say "ok" && / Desktop/test.sh
ou
*ALLUM*CUISINE==say "ok" && python3 Desktop/test.py

ne marche pas

**Comment by alexylem** [comment]
Il faut pas faire de retour à la ligne. Aussi le chemin du script à exécuter doit être absolu ou relatif au dossier de Jarvis. Idéalement /home/pi...

**Comment by oeildefeu** [comment]
Salut,
au passage si tu rends ton script exécutable (chmod +x test.py) et que tu rajoutes 
`#! /usr/bin/env python`
à la première de ton script tu peux te passer du "python3" pour éxécuter ton script

**Comment by wikijm** [comment]
@ludoboss7 Clôture du ticket le temps que tu puisse tester la solution de @oeildefeu.
N'hésites pas à nous en faire un retour ou rouvrir le ticket si nécessaire 😉
