### ISSUE TITLE
Moderniser les "bips" de Jarvis

### ISSUE THREAD

**Issue by alexylem** [alexylem/jarvis#62]
### Description

J'aimerais remplacer les "bips" de Jarvis (mode commande, écoute, timeout...) par des sons un peu plus modernes, peut-être aussi rajouter un nouveau son lorsqu'une commande n'est pas comprise (genre "HEIN-HEIN").

**Comment by physicien** [comment]
Je viens d'en faire un juste pour toi. Tu me diras ce que tu en penses: [Nouveau son super génial](https://mega.nz/#!794zXDJK!ecbShSeCEvyi5-GmfKDFER_ofje7kaz-WJLvLyhgxC4).

**Comment by alexylem** [comment]
Hahaha pas mal mais pas sur que ma femme apprécié sur le long terme :smile:

**Comment by physicien** [comment]
Cependant, si tu veux armer Jarvis d'un laser un de ces jours, tu as ton bruitage! :laughing: 
Sur une note plus sérieuse (note... lol), je ne suis pas trop certain de capter ce que serait un bit moderne...

**Comment by alexylem** [comment]
Pas forcément un "bip" mais un son plus agréable à l'oreille, je vais vous proposer des samples vous me direz.

**Comment by Smanar** [comment]
Style le bip de Siri mais en plus original (parce que la, trop reconnaissable) ?

**Comment by alexylem** [comment]
Ex:
http://soundbible.com/1682-Robot-Blip.html
et
http://soundbible.com/1669-Robot-Blip-2.html

**Comment by Smanar** [comment]
Je prefere largement le premier.

**Comment by physicien** [comment]
Le premier est mieux que le deuxièmes, mais je trouve que les deux font saigner mes oreilles.

**Comment by alexylem** [comment]
Oui il y un truc strident que je n'aime pas non plus, c'était juste pour montrer l'esprit, je continue de chercher

**Comment by alexylem** [comment]
Voici ce que je vous propose, pour certains évènements il y a plusieurs choix, j'ai mis mes préférences dans l'ordre:
* [Mode écoute](https://dl.dropboxusercontent.com/u/1137163/jarvis%20sounds/listening.wav)
* [Mot clé entendu](https://dl.dropboxusercontent.com/u/1137163/jarvis%20sounds/triggered.wav)
* [Mot clé entendu 2](https://dl.dropboxusercontent.com/u/1137163/jarvis%20sounds/triggered2.wav)
* [Mot clé entendu 3](https://dl.dropboxusercontent.com/u/1137163/jarvis%20sounds/triggered3.wav)
* [Erreur](https://dl.dropboxusercontent.com/u/1137163/jarvis%20sounds/error.wav)
* [Erreur 2](https://dl.dropboxusercontent.com/u/1137163/jarvis%20sounds/error%202.wav)
* [Erreur 3](https://dl.dropboxusercontent.com/u/1137163/jarvis%20sounds/error%203.wav)
* [Timeout](https://dl.dropboxusercontent.com/u/1137163/jarvis%20sounds/timeout.wav)

**Comment by physicien** [comment]
Excepter le son `error.wav`, ils sont tous agréables à l'oreille.
