### ISSUE TITLE
Installation sur Mac

### ISSUE THREAD

**Issue by polbru40** [alexylem/jarvis#620]
Comment dois je faire pour installé Jarvis sur mon Mac ?
Merci pour l'aide

**Comment by polbru40** [comment]
Suis arrivé a installer jarvis mais j'arrive pas a configurer le speaker ni le micro.
J'ai une erreur lors de la configuration : 
Selection of the speaker device
utils/configure.sh: line 138: aplay: command not found
Indicate the card # to use [0-9]: 1
Indicate the device # to use [0-9]: 1
Updating ~/.asoundrc...
Reloading Alsa...
sudo: /etc/init.d/alsa-utils: command not found
utils/configure.sh: line 134: play: command not found

J'entends pourtant Jarvis me dire Hello puis il quitte l'appli.

**Comment by alexylem** [comment]
Normalement ça marche du premier coup il faut répondre oui que tu as bien entendu le son. Dans le doute il fait remettre les fichiers play_hw et rec_hw a "false" dans le dossier config/

**Comment by polbru40** [comment]
Merci . Je vais faire cela au plus vite :)

**Comment by wikijm** [comment]
Clôture du ticket le temps que tu fasse les tests prévus.
N'hésites pas à nous en faire un retour 😉
