### ISSUE TITLE
problème de fonctionnement snowboy depuis la mise à jour (17.05.26)

### ISSUE THREAD

**Issue by yala37** [alexylem/jarvis#623]
### Description

Bonjour, 

depuis la dernière mise à jour, les fonctions de snowboy pour enregistrer un "hot word" ne fonctionnent plus.

cela n’empêche pas le fonctionnement de jarvis, mais empêche la modification ou l'ajout de tt nouveau hot Word

J'ai notamment l'erreur suivante : utils/menu.sh: ligne 159: stt_sb_train : commande introuvable

je ne sais pas si les droits sont correctes sur les fichiers snowboy, (manque par exemple le droit d’exécuter sur les .sh et .py)

-rw-r--r-- 1 jeedom root  10478 avril 15 13:29 maindecoder.py
-rw-r--r-- 1 jeedom root   8309 mars  13 00:01 maindecoder.pyc
-rw-r--r-- 1 jeedom root  11375 mai    7 18:49 maindecoder_sox.py
-rw-r--r-- 1 jeedom root   9452 mai    7 19:56 maindecoder_sox.pyc
-rw-r--r-- 1 jeedom root   3106 avril 15 13:29 main.py
-rw-r--r-- 1 jeedom root  11300 mai    4 17:16 main.sh
drwxrwxrwx 2 jeedom root   4096 mai   22 21:34 resources
-rwxrwxrwx 1 jeedom root   6856 nov.  15  2016 snowboydecoder.py
-rw-r--r-- 1 jeedom root   7693 nov.  15  2016 snowboydecoder.pyc
-rwxrwxrwx 1 jeedom root   4265 nov.  15  2016 snowboydetect.py
-rw-r--r-- 1 jeedom root   6087 nov.  15  2016 snowboydetect.pyc
-rwxrwxrwx 1 jeedom 1000 691052 mai   24  2016 _snowboydetect.so
-rwxr-xr-x 1 jeedom root    264 mars   5 22:56 uninstall.sh

merci d'avance,

**Comment by alexylem** [comment]
Je confirme, je corrige de suite...

**Comment by alexylem** [comment]
Voila c'est corrigé. Mettez à jour:
```shell
$> ./jarvis.sh -u
```

**Comment by yala37** [comment]
merci pour ton retour, cependant chez moi pas mieux avec ta dernière mise à jour.

**Comment by alexylem** [comment]
@yala37 désolé pour ma réponse tardive. A quel moment exactement tu as ce problème? Un petit asciinema pourrait m'aider:
Merci de coller le résultat complet de la console après avoir lancé Jarvis en mode Troubleshooting, ou partage une session de ton terminal en utilisant [asciinema](http://asciinema.org):
```shell
sudo apt-get install -y asciinema && asciinema rec # start session recording
jarvish -nv # start jarvis directly in troubleshooting mode
Ctrl+D # stop recording
y # yes to upload and get URL to paste here
```

**Comment by wikijm** [comment]
@yala37 Je clôture l'issue le temps que tu puisse fournir la vidéo ASCIINEMA.
N'hésites pas à le rouvrir une fois fait 😉

**Comment by yala37** [comment]
@alexylem désolé moi aussi pas beaucoup de temps en ce moment. en fait ce message apparaît au moment ou je tente d'enregistrer un hotword snowboy. 

Et quand je tente d'afficher la liste des hotword enregistrés aucun ne s'affiche dans le GUI. j'ai bien un fichiers dans snowboy/ressources/ : 
 ls -l /opt/jarvis/stt_engines/snowboy/resources/
total 1340
-rwxrwxrwx 1 jeedom root 486922 nov.  15  2016 common.res
-rwxrwxrwx 1 jeedom root  15782 nov.  15  2016 ding.wav
-rwxrwxrwx 1 jeedom root  12996 nov.  15  2016 dong.wav
-rwxrwxrwx 1 jeedom root  13867 mai   22 21:34 hey jarvis.pmdl
-rwxrwxrwx 1 jeedom root 832346 nov.  15  2016 snowboy.umdl

merci d'avance

**Comment by alexylem** [comment]
>Et quand je tente d'afficher la liste des hotword enregistrés aucun ne s'affiche dans le GUI

C'est un bug on dirait, je corrige.

Sinon pour ton autre problème (`utils/menu.sh: ligne 159: stt_sb_train : commande introuvable`), tu l'as toujours? Si oui, un petit asciinema stp.

**Comment by alexylem** [comment]
Implémenté sur la branch `beta`. Pour le tester dès à présent:
Menu `Settings > General > Branch > beta`
Sinon attendre la mise à jour de ce weekend.

**Comment by yala37** [comment]
Merci, j'ai tenté de passer sur la branche beta, mais pas d'update dispo.

je suis en : v17.05.27

sinon je repasserai sur la branche master.

**Comment by alexylem** [comment]
>Merci, j'ai tenté de passer sur la branche beta, mais pas d'update dispo.

C'est pas normal, la version en beta est `17.06.08`
Essaye depuis le répertoire `jarvis/`:
```shell
$> cat config/jv_branch
$> cat version.txt
$> jarvis -u
$> cat version.txt
```

**Comment by yala37** [comment]
Bonjour, merci la correction est ok chez moi!

**Comment by satana888** [comment]
Bonjour, je voudrai savoir si le site speech platform bing com est remis en ordre ?

Car à ce jour je n’ai toujours rien de mon côté, j’en désespère…

 

Merci d’avance

 

 

 

Cordialement

 

 

 

 

 

De : yala37 [mailto:notifications@github.com] 
Envoyé : dimanche 18 juin 2017 16:26
À : alexylem/jarvis
Cc : Subscribed
Objet : Re: [alexylem/jarvis] problème de fonctionnement snowboy depuis la mise à jour (17.05.26) (#623)

 

Bonjour, merci la correction est ok chez moi!
