### ISSUE TITLE
Réponse aléatoire pour plus d'humanité ?

### ISSUE THREAD

**Issue by SwithFr** [alexylem/jarvis#625]
### Description

Bonjour, Je me demandais, s'il était possible de modifier la fonction `say` afin de lui donné plutôt un fichier texte avec une phrase par ligne et la fonction ferait dire à Jarvis l'une d'entre elles.

Par exemple `say "./hello.txt"` avec le fichier suivant `hello.txt`: 
```
Bonjour
Bonjour Monsieur
Bonjour que puis-je pour vous
Je suis à votre service
...
```

Ainsi on ne serait pas cantonné à une seule réponse qui serait répétée à chaque fois qu'on lance une même commande.

**Comment by alexylem** [comment]
Le tout premier ticket de Jarvis parle exactement de ca: #1 👍
