### ISSUE TITLE
Félicitation

### ISSUE THREAD

**Issue by LaboleRigole** [alexylem/jarvis#627]
Désolé de passer par un issue , mais je ne sais pas trop comment faire pour vous envoyer un petit message de félicitation. Ce projet est très bien fait, facile d'utilisation et vous avez prévu beaucoup de fonctions, comme le petit fichier my-functions.sh pour pouvoir intégrer nos propres fonctions pour dans mon cas simplifier l'action des commandes.
Bravo et merci

**Comment by alexylem** [comment]
Merci bcp! Su tu as des idées d'améliorations n'hésites pas 👍
