### ISSUE TITLE
Bravo Alex 

### ISSUE THREAD

**Issue by GeniusLeroy** [alexylem/jarvis#629]
Salut Alex,

As tu pu réfléchir à mon projet pour le développement de Jarvis ?

Bonne journée :)

**Comment by alexylem** [comment]
Qui es-tu?

**Comment by GeniusLeroy** [comment]
C’est Loïc, je tai contacté il y a quelques jours à propos d’un projet :)

**Comment by IPv777** [comment]
@GeniusLeroy pourrait-tu expliciter ton projet? :) Les idées sont toujours intéressantes à étudier dans le monde "libre" ;p

**Comment by Oliv4945** [comment]
Je ferme vu le manque d'infos.
@GeniusLeroy: ne pas hésiter à publier les infos ici
