### ISSUE TITLE
Smartplug CHACON Wifi

### ISSUE THREAD

**Issue by satana888** [alexylem/jarvis#630]
bonjour, je suis tout nouveau, j'ai découvert votre site en surfant, et j'ai cru que ce que je pensais mettre en place ne pouvait pas se réaliser, je recommande ce site pour ses explications et la simplicité a mettre en place, j'ai déjà essayer quelques plugins et c'est top....
Franchement chapeau...
Par contre, en explorant les diverses choses a réaliser, j'aurai voulu savoir comment il serait possible ou via quel script, allumer et éteindre une prise WIFI de chez chacon? SMARTPLUG ... je ne trouve rien par rapport a cela, sur ios c'est nickel, mais le commander par la vois via jarvis? est-ce possible? 
```

**Comment by alexylem** [comment]
Il y a un plugin dispo pour Chacon:
https://www.openjarvis.com/plugins/chacon

**Comment by satana888** [comment]
Le plugin prend en charge le 433mhz et aussi le WIFI ?

Si je me trompe pas, les prises 433mhz sont alimentées par l’émetteur que l’on peut rajouter au Pi avec de l’arduino, alors que la prise que j’ai moi, c’est une via le WIFI que je la contrôle..

 

 

De : Alexandre Mély [mailto:notifications@github.com] 
Envoyé : lundi 5 juin 2017 15:51
À : alexylem/jarvis
Cc : satana888; Author
Objet : Re: [alexylem/jarvis] Chacon smartplug... (#630)

 

Il y a un plugin dispo pour Chacon:
https://www.openjarvis.com/plugins/chacon

**Comment by alexylem** [comment]
Ah non en effet ce n'est pas la même chose, c'est celle la?
http://www.domotique-info.fr/2014/07/neo-prise-commandee-wifi-chez-chacon/

**Comment by wikijm** [comment]
Pas de réponse depuis 1 mois, j'en conclus que le besoin n'est plus rencontré.
Ne pas hésiter à ré-ouvrir si nécessaire.
