### ISSUE TITLE
Lancement d'une impression...

### ISSUE THREAD

**Issue by satana888** [alexylem/jarvis#631]
Re-bonjour,

Je reviens encore pour demander quelques choses, a vrai dire, je sais qu'il est possible de faire de tout et n'importe quoi avec ce projet, et biensure, de le modeler en fonction de chacun de nos besoins personnel.
Je me titillais une question, Peux t'on via un script, faire l'envoi d'une liste comme le fait le plugins de la liste des courses ( vers l'adresse mail ), mais vers une imprimante en direct, que ce soit en réseau sur un autre post ou simplement sur une imprimante connectée sur le Raspberry pi?

En vous remerciant d'avance

**Comment by alexylem** [comment]
Je ne connais pas les lignes de commande pour l'impression, mais à mon avis une petite recherche google devrait pouvoir t'orienter:
https://www.google.fr/search?q=raspberry+pi+print+from+command+line

**Comment by satana888** [comment]
Bonjour,

 

Merci, je recherchais déjà J …

Je trouverai pas mal de lister quelques choses niveau vocal et de l’envoyer direct sur l’impression… en même temps Jarvis peux aussi faire office de serveur d’impression pour toute la maison…

On fais d’une pierre deux coups J

 

Et point de vue des prises en WIFI ? les Smartplug… Il existe des lignes de commandes qui peuvent juste les allumer et éteindre tout simple ? Car je suis juste bloqué smartphone actuellement, ce qui marche très bien mais bon…. J’aime bien quand Jarvis le fait aussi lol

 

Au fait, j’ai commandé Du Mi Light, une ampoule et le contrôleur, pour essayer J j’en dirai des nouvelles…Pour le moment je suis juste avec le contrôleur que j’ai reçu avant le W-E et l’ampoule qui arrivera en décalé cette semaine.

Bonjour le W-E dans l’impatience L 

 

Je vous tiens au courant aussi pour ceci…

 

En tout ça, encore félicitation pour tout ce projet …. C’est clair, c’est facile a mettre en place même pour un débutant sous linux… woawww rien a dire…. Continues car sa à du mérite…

 

Cordialement

 

 

 

 

 

 

De : Alexandre Mély [mailto:notifications@github.com] 
Envoyé : lundi 5 juin 2017 15:55
À : alexylem/jarvis
Cc : satana888; Author
Objet : Re: [alexylem/jarvis] Lancement d'une impression... (#631)

 

Je ne connais pas les lignes de commande pour l'impression, mais à mon avis une petite recherche google devrait pouvoir t'orienter:
https://www.google.fr/search?q=raspberry+pi+print+from+command+line

**Comment by wikijm** [comment]
@satana888 Tu trouveras à l'adresse ci-dessous des plugins qui devraient répondre à tes besoins (utilisation ampoules et interrupteurs Wifi, ...) :
https://openjarvis.com/plugins

De plus, je t'invite à ne pas répondre par e-mail à une issue, mais plutôt à passer par https://github.com, car sinon on est obligé d'éditer tes commentaires pour les rendre un tant soit peu lisible.

Je clôture ton issue le temps que tu puisse procéder aux recherches proposées par @alexylem
