### ISSUE TITLE
Impossible d'accéder au menu

### ISSUE THREAD

**Issue by asmrct** [alexylem/jarvis#632]
Bonjour,

J'essaye en vain d'accéder au menu de configuration de Jarvis (notamment la partie Commands). Lorsque je lance la commande "jarvis" ou "./jarvis.sh" je tombe sur un menu minimaliste avec 4 options (voir video) avec un message expliquant que jarvis est déjà lancé.
Lorsque je sélectionne "Stop Jarvis" et que je relance ./jarvis.sh, retour au même menu. Impossible d'accéder aux Settings ou aux Commands. Comment appeler ce menu ?

https://asciinema.org/a/693bo7jmfmi6actgt4496er6k

**Comment by asmrct** [comment]
Petite avancée, en tuant les processus (3 au total) Jarvis, j'ai pu accéder au menu complet. Par contre, la fonction "Stop Jarvis" ne fonctionnait donc pas. Cela vient-il du fait que plusieurs processus Jarvis tournaient en parallèle ? Est-il possible d'empêcher cela ?

**Comment by wikijm** [comment]
Un redémarrage du Pi a-t'il été testé ?

**Comment by asmrct** [comment]
Le problème semble résolu depuis en effet, je ne sais pas comment j'avais pu lancer deux processus mais je pense que cela venait de là.

**Comment by asmrct** [comment]
Ok, j'ai compris mon erreur. J'avais stoppé Jarvis avec CTRL+Z (ce qui n'a que suspendu le processus) au lieu de CTRL+C, donc impossible derrière cela de réaccéder au menu de Jarvis sans killer le processus.

**Comment by alexylem** [comment]
Aaaah oui en effet 😄 
Bon je pense qu'on peut cloturer alors.

**Comment by Vjournot** [comment]
Bonjour, j’ai le problème énoncé ci-dessus car jarvis se lance 2 fois au moment du démarrage. J’ai probablement créé moi meme cette situation en installant des plugins mais je ne sais pas comment résoudre ce probleme. Une re-installation n’a rien changé. Si je « kill » les process jarvis en cours, ca fonctionne à nouveau notmalement jusqu’au prochain reboot ou 2 jarvis sont démarré par defaut. Merci de votre aide.

**Comment by Sh1n1x** [comment]
@Vjournot si tu donnes pas plus de détail sur ce que tu as fait, les plugins que tu as on va pas pouvoir t'aider hein :)
