### ISSUE TITLE
Suggestion: Interactions des plugins.

### ISSUE THREAD

**Issue by Erim32** [alexylem/jarvis#633]
Petit suggestion,
au fil du développement de mon Jarvis, j'ai remarqué que les plugins sont tous indépendants, mais ça serrait intéressant de leurs permettre d'intéragir. 
Mais ça nécessiterait 2 étapes:

- Ajouter une petite fonction au core de jarvis (jv_plugin_installed(nom_plugin_dans_dossier)) qui testerait juste si le dossier des plugin contient le dossier en paramètre. return 0 ou 1.

- Permettre aux fonctions des plugins de s'appeler entre elles, je ne sais pas si c'est déjà le cas. 

Exemple dans le plugin XXX on propose des fonctions classiques puis si le plugin YYY est présent,  certaines commandes sont possibles.

**Comment by Jean-Bernard-Hallez** [comment]
Et coucou... je l'utilise avec mes propres plugins... il suffit simplement d'appeler une function externe même si tu n'es pas dans le plugin concerné...

**Comment by Erim32** [comment]
Merci @Jean-Bernard-Hallez pour ton retour je ne pensais pas que c'était possible. 
Mais je me demande, cette solution marche bien pour une installation locale mais si tu commence a publier tes plugins, quel est le comportement de jarvis si tu appelles une fonction qu'il ne va pas connaitre ???

**Comment by Jean-Bernard-Hallez** [comment]
Je vérifie le retour de la variable... si elle est nul alors je n'applique pas la suite..
fonction_test (){
fonction_test $partieA $partieB $partieC
say "le premier mot est $1 le second $2 le troisième $3
fi
}

function_B() {
partieA="bonjour"
partieB="au revoir"
partieC=""
}


command:
*lance*le*test*==function_B

résultat: 
le premier mot est bonjour le second au revoir le troisième

**Comment by alexylem** [comment]
Il y a une fonction (privée, bientôt documentée) pour ca:
```shell
jv_plugin_is_enabled {
    [ -d "plugins_enabled/$1" ]
}
```
utilisation:
```shell
if jv_plugin_is_enabled "jarvis-time"; then
   blablabla
else
   blablabla
fi
```
