### ISSUE TITLE
cron '@reboot ~/jarvis/jarvis.sh -b' ne fonctionne plus

### ISSUE THREAD

**Issue by Jean-Bernard-Hallez** [alexylem/jarvis#634]
Bonjour... depuis quelque temps cette commande ne fonctionne plus:
@reboot ~/jarvis/jarvis.sh -b 
et sur mes 2 rasbperry...

Puis quand je vais dans jarvis, plugin, browse, all... c'est vide...
et sur mes 2 raspberry...

Je pense que c'est bien 2 bugs...

**Comment by Oliv4945** [comment]
Je n'ai pas tenté le reboot mais je confirme la liste de plugin vide, est ce lié au changement de nom de domaine ?

**Comment by alexylem** [comment]
Ca devrait être corrigé depuis, vous pouvez forcer la mise à jour de la liste des plugins dans Plugins / Update:
![image](https://user-images.githubusercontent.com/11017174/27009396-26b97342-4e8d-11e7-9e5d-f9bbd35f091b.png)

Pour le reboot, tu peux vérifier tes logs cron ou faire:
```shell
@reboot ~/jarvis/jarvis.sh -b >~/log.txt 2>&1
```
Puis vérifier `log.txt` après le reboot ? merci

**Comment by Jean-Bernard-Hallez** [comment]
Résultat Crontab:
Jarvis has been launched in background

To view Jarvis output:
jarvis and select "View output"
To check if jarvis is running:
pgrep -laf jarvis.sh
To stop Jarvis:
jarvis and select "Stop Jarvis"

You can now close this terminal

(Maisi il n'est pas lancé...)
Le Log de Jarvis:
dimanche 11 juin 2017, 10:45:10 (UTC+0200) nohup: impossible d'exécuter la commande « jarvis »: Aucun fichier ou dossier de ce type

**Comment by Jean-Bernard-Hallez** [comment]
Et oui la liste des plugins est bien corrigée...

**Comment by alexylem** [comment]
Ok je comprends d'ou ca vient, essaye de mettre le PATH tout en haut de ton crontab:
```shell
$> crontab -e
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
@reboot        ~/jarvis/jarvis.sh -b
```
Mais je vais essayer de trouver une meilleure solution.
Sinon il y a le plugin d'Olivier:
https://www.openjarvis.com/plugins/systemd-startup

**Comment by Jean-Bernard-Hallez** [comment]
En effet le path n'est pas très esthétique lol... Celui d'Olivier Bug il me plante Jarvis et au reboot il ne fonctionne pas sur mes 2 raspberry... en attendant je rajoute le Path...
