### ISSUE TITLE
Jarvis + Google Assistant API

### ISSUE THREAD

**Issue by Erim32** [alexylem/jarvis#635]
Bonjour;
avec la sortie prochaine de google assistant en France, et les scripts apportés par google au travers du projet AIY pour rpi3.
Je souhaiterais lancer cette proposition pour créer un plugin qui a pour vocation d'être le plugin en bas de la liste qui va simplement traiter la requette de l'utilisateur par google assistant, avant de retourner le résultat avec le moteur TTS de Jarvis.

Ça apporterais du contenu au dialogue avec jarvis dans le cas ou l'on ne le traiterait pas avant, de plus le déclenchement sur demande de jarvis permet de garantir un respect de la vie privée.

D'après mes premières recherches,  ça semble être un projet d'envergure, qui malheureusement dépasse mes compétences mais peut être que quelqu'un sera intéressé.

**Comment by Smanar** [comment]
Je decouvre, y avait meme un kit pr raspberry avec les cartes pr le son
Par contre j'arrive pas a trouver d'infos si ca marche en francais Tu as de meilleures sources que moi ?

Parce que y a aussi alexa d'amazon qui devait arriver en france, j'ai tout stoppe pour l'attendre, et j'attend encore ...

**Comment by Erim32** [comment]
Salut @Smanar, pour le français  pas d'infos, mais comme à son d'hab avec google se sera surement un petit paramètre à définir 'blablablaAssistant.lang("FR-fr")'.
Mais pour l'instant tant qu'il n'est pas arrivé en France ils ne l'ajoutent pas au SDK.
Mais je pense que préparer un plugin pour  l'intégration même en anglais semble déjà envisageable.
D'après les rumeur, GA sortirait en FR dans le pire cas pour septembre, mais rien d’officiel (sur le twitter de google france, ils ont déja annoncé depuis début juin qu'ils débutaient le déploiement sur Android).

Concernant Alexa, d'apres le dernier comparatif:
[ici](http://www.zdnet.fr/actualites/quel-est-le-plus-fute-des-assistants-personnels-cortana-siri-alexa-ou-google-39853400.htm) , Alexa semble bonne dernière, je ne pense pas qu'ils vont se risquer sur le marché européen dans une langue étrangère (non anglais) avant d'avoir un produit capable de rivaliser avec la concurrence dans sa langue natale de conception (anglais).

**Comment by Smanar** [comment]
Yep, mais il faut voir aussi les "services", les partenariats commerciaux/logiciels qu'il vont avoir. C'est bien beau que ca reponde bien, mais si ca peut servir c'est mieux.
De ce cote la Google est en train de mettre les bouchees doubles, ca a vraiment avance depuis la derniere fois que j'ai regarde, mais si j'etais americain, je prendrais alexa sans hesiter.

**Comment by ahyear** [comment]
Hello,
maintenant que GA est bien sorti en France et que les google home fleurissent, peut on s'autoriser a réver a l'arrivée du plugin associé? ^^

**Comment by Sh1n1x** [comment]
J'avais regardé mais assez complexe à mettre en place. je trouve bien dommage qu'il ne fasse pas comme YT une simple api REST qui retourne la réponse à la requête...

**Comment by Oliv4945** [comment]
Jarvis et Google Assistant sont des concurrents, je vois mal pourquoi Google ouvrirait une API...
Et même dans ce cas Jarvis ne serait là que pour enregistrer la diction, l'envoyer à Google et lire la réponse, ce qui n'est pas la philosophie du projet.
