### ISSUE TITLE
Site: captcha erreur suite au changement de nom de domaine.

### ISSUE THREAD

**Issue by Erim32** [alexylem/jarvis#636]
Petite erreur sur le site, je poste ici car je ne sais pas ou le signaler sinon:
Avec le changement du nom de domaine, il faudra modifier le nom de domaine spécifié dans l'api google pour les captcha

![download](https://user-images.githubusercontent.com/8769532/27002160-e5dc6e32-4dd9-11e7-9546-2e0238fc5e00.png)

**Comment by wikijm** [comment]
Merci pour la remontée @Erim32 😃

**Comment by alexylem** [comment]
Oups désolé je vais ca de suite, merci

**Comment by alexylem** [comment]
Corrigé
