### ISSUE TITLE
Site: demande droit edition ancien plugin

### ISSUE THREAD

**Issue by Erim32** [alexylem/jarvis#637]
Bonjour, désolé de poster ça ici, mais je ne sais pas ou poster les problemes liés au site.

@alexylem 
J'avais développé un plugin a l'apparition du systeme de plugin, (avant la mise en place des comptes sur le site) et l'auteur du plugin est donc référencé comme Anonymous, le problème est que je vais bientot remanier mon github et modifier le nom du plugin pour rester cohérent.

**Serrait il possible que vous me donniez le droit d'édition sur mon plugin, ou est ce impossible ?**
mon ancien plugin:  [LiveboxTV](https://openjarvis.com/plugins/liveboxtv)
mon username sur le site: "erim" 

Merci

**Comment by alexylem** [comment]
C'est fait

**Comment by Erim32** [comment]
Merci
