### ISSUE TITLE
Détection automatique d'erreurs enceintes/micro à l'installation

### ISSUE THREAD

**Issue by alexylem** [alexylem/jarvis#64]
### Description

Créé depuis #63 
Lors de l'installation de Jarvis, si les enceintes ou micro sont mal configurés (erreur play ou rec), le détecter automatiquement plutôt que de demander à l'utilisateur s'il a rencontré une erreur.

### Résultat
```shell
ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM false
rec FAIL formats: can't open input  `default': snd_pcm_open error: No such file or directory
play FAIL formats: can't open input file `jarvis-record.wav': No such file or directory
true # mauvaise réponse de l'utilisateur
```

**Comment by remjou1** [comment]
oui ce serait cool ça ! ça faciliterais la tache a beaucoup de monde
