### ISSUE TITLE
Micro numerique sur port I2S

### ISSUE THREAD

**Issue by leto3** [alexylem/jarvis#641]
Bonjour,

J'ai ajouté deux micros mems sur l'interface I2S du Raspberry pi (voir [https://learn.adafruit.com/adafruit-i2s-mems-microphone-breakout/raspberry-pi-wiring-and-test](https://learn.adafruit.com/adafruit-i2s-mems-microphone-breakout/raspberry-pi-wiring-and-test) ).
Le son est parfait, très peu de bruit, même de loin.
Le problème est que je dois utiliser le plugin softvol pour le volume et que donc mon micro n'est accessible que par son identifiant alsa  (ici mic_sv): 
arecord -Dmic_sv -c2 -r 48000 -f S32_LE -t wav -V stereo -v file_stereo.wav fonctionne.

Le problème est que Jarvis n'accepte que les micros hardware (hw).

Est-il possible de configurer Jarvis pour qu'il utilise mic_sv ?

**Comment by Jean-Bernard-Hallez** [comment]
Je trouve ça Génial ! moins il y a de fil mieux c'est... si on peut le mettre dans le boitier de RPI 25/20... il n'y a plus que le haut parleur à connecté... coût moindre aussi... Test à pousser.... lol
Perso j'avais déja commandé le Sound Sensor https://www.amazon.fr/gp/product/B013QR8ZT6/ref=od_aui_detailpages00?ie=UTF8&psc=1 hélas sortie analogique ... lol... puis j'ai pris le PCF8591 https://www.amazon.fr/gp/product/B01N1H3V4D/ref=oh_aui_detailpage_o02_s00?ie=UTF8&psc=1... mais je me suis vite découragé... impossible a paramétrer de mon coté...

**Comment by Jean-Bernard-Hallez** [comment]
Bon j'ai reçu mon micro mini usb MI-305
https://www.amazon.fr/MI-305-Plug-Play-Mini-Microphone/dp/B00N72S7O4
Je peux vous garantir que ca marche à merveille !!!

**Comment by Jean-Bernard-Hallez** [comment]
Remoi... lol J'ai recu aussi le micro mems sur l'interface I2S... et je confirme que ca ne marche pas... je pensais pouvoir contourner le problème... ca m'aurait libéré un port USB... 
Mais la qualité sonore en enregistrement manuel n'est pas aussi clair qu'avec le MI-305

**Comment by alexylem** [comment]
@leto3 ca doit pouvoir se faire 👍  
Tu as suivi le tuto que tu as mentionné? Car à la fin le code d'exemple utilise un hw:
```
arecord -D plughw:1 -c1 -r 48000 -f S32_LE -t wav -V mono -v file.wav
```

@Jean-Bernard-Hallez si le mini-usb fonctionne bien on pourrait le rajouter à la liste des micro supportés sur le site? Ca marche à quelle distance? Il n'est pas disponible sur le lien amazon que tu as donné, tu en aurais un autre? Tarif?

**Comment by Jean-Bernard-Hallez** [comment]
Et coucou... l'ayant aussi installé ce micros mems, jarvis reconnais celui-ci dans la configuration... mais il ne le valide pas... on ne peut pas avancer... il revient sur veuillez choisir la bonne carte et le sous périphérique....

Pour le mini-usb oui absolument on peut le rajouter sur la liste des micro supportés, Au niveau de la distance, ca marche aussi bien que le micro jabra 510 !!! 

En effet il n'est plus disponible sur amazon mais ici oui et au même prix:
http://www.dx.com/fr/p/mi-305-the-world-s-smallest-usb-2-0-microphone-black-285812#.WVD6GWjyiUk

**Comment by Jean-Bernard-Hallez** [comment]
Et coucou Alex, je vois que tu n'as pas mis le micro MI-305 dans les Pré-requis... il ne coûte pas cher et fonctionne vraiment bien...   ;-)

**Comment by Oliv4945** [comment]
@Jean-Bernard-Hallez , intéressant ce micro. Avec un rPi zero et un haut parelur USB comme [celui-ci](http://www.ebay.fr/itm/Portable-USB-Multimedia-Mini-Speaker-for-Computer-Desktop-PC-Laptop-Notebook-/162149152955?hash=item25c0d7b8bb:g:MQcAAOSwfVpYwgaO) on doit pouvoir s'en sortir pour 20 à 25€ ...
A méditer et tester ! :p

**Comment by Oliv4945** [comment]
Salut,

La demande initiale est d'utiliser les noms plutôt que les identifiants Alsa. Du coup je ferme au profit de #496
