### ISSUE TITLE
Erreur d'affichage d'images suite à changement de nom de domaine

### ISSUE THREAD

**Issue by miguipda** [alexylem/jarvis#643]
Bonjour,

l'image du point 1. de la page créer votre plugin ne s'affiche pas : [https://www.openjarvis.com/content/publish-your-plugin](url)

A corriger rapidement, car j'ai envoyé cette page à un module d'activation des stores pour **leur demander de créer un plugin pour Jarvis** : [https://somasmarthome.com/](url)

A+

**Comment by wikijm** [comment]
Bonjour @miguipda,

Pourrais-tu nous transmettre l'image manquante et/ou son chemin (adresse URL) ?

**Comment by wikijm** [comment]
Ligne 248 :
`<ol><li>Create a new Plugin from Jarvis in <strong>Menu &gt; Plugins &gt; Create a Plugin</strong><br /><img alt="" height="432" src="/jarvis/sites/default/files/paste_1493485401.png" width="452" /><br />`

A remplacer par :
`<ol><li>Create a new Plugin from Jarvis in <strong>Menu &gt; Plugins &gt; Create a Plugin</strong><br /><img alt="" height="432" src="/sites/default/files/paste_1493485401.png" width="452" /><br />`

L'urgence de ta requête est relative car il est possible de suivre la procédure sans avoir la capture d'écran, les instructions étant également définies à l'écrit.

**Comment by alexylem** [comment]
C'est fait, merci et désolé pour le retard
