### ISSUE TITLE
ERROR: bing recognition curl failed

### ISSUE THREAD

**Issue by satana888** [alexylem/jarvis#646]
Bonjour,
J’étais entrain de configurer Mon Jarvis :)  et d'une fois, plus rien point de vue de la reconnaissance vocal... Il reconnaissait le HOTWORD mais après plus rien de reconnu...
J'ai fais des recherche sur le net car j'avoue que je suis en panique total... j'ai configuré pas mal de trucs dessus et boum plus rien :(
Alors voila, j'ai recherché par moi même un peu et j'ai vu que pour la reconnaissance, le script fait appel a ce site : http://speech.platform.bing.com/
J'ai été dessus pour voir ce que sa raconte et j'ai vu ceci dessus : 

### Our services aren't available right now

We're working to restore all services as soon as possible. Please check back soon.
Ref A: 0CA55BF6039D4AEEB80D2A87130E1DB8 Ref B: BRU30EDGE0114 Ref C: Sat Jun 17 11:46:32 2017 PST

Je suppose que le problème vient de là? que je doit sagement attendre qu'ils interviennent sur leur matos et que je retrouverai mon petit jarvis avec toutes ses gentilles réponses et fonctions comme il y a quelques heures? 

En vous remerciant d'avance

Cordialement

p.s. si jamais mon Jarvis est foutu... j'avais mis comme tâches : le tout en vocal bien sure, 6 commandes de prises chacon, un lancement d'impression , envoi d'un fichier par mail, météo, jour et date, j'avais configuré tout le CRONTAB pour plein de dates d'annif et des rappel en veux tu en voilà et des mise en route de fonctions automatisées dedans aussi, il avais deux yeux qui s'allumaient en fonction de certain besoin, une liste de mots avec des réponses automatisées également dans jarvis-commands, une minuterie avec l'annonce du diner prêt ou repas + un allumage de lampe pour bien être sur de le voir ou l'entendre, la mise en route et l'extinction de mon alarme de maison dans CRONTAB et par la voix...l'allumage de mon aquarium automatisé .... j'allais envisager de connecter le PIR que j'ai commandé pour effectuer des tache de reconnaissance motion.... et la tout à basculé ........ j’attends de voir si tout est perdu ou si c'est juste bing qui doit être réparé...

**Comment by satana888** [comment]
Re-bonjour, a tous
Voila le lendemain, ce site m'affiche toujours la même chose et aucune possibilité de retrouver jarvis en réponse...
quelqu'un a t'il ce problème aussi? et quelles sont les autres alternatives possibles? jarvis est censé aller en continu, une heure de maintenance, je peux comprendre mais tout le w-e c'est pas normal!
speech bing a réellement des problèmes? ou alors c'est mon jarvis qui c'est mis a ne plus rien vouloir faire d'un coup? sachant que je n'ai bougé a aucune de ses configuration niveau de la reconnaissance des voix...

**Comment by alexylem** [comment]
A première vue ca fonctionne chez moi,
tu peux partager le terminal avec jarvis lancé en mode troubelshooting?
Merci

**Comment by alexylem** [comment]
Tu peux vérifier en lançant le script de test bing de Jarvis:
```shell
$ cd stt_engines/bing/
$ ./test.sh
#DEBUG: curl https://speech.platform.bing.com/recognize/query?version=3.0&requestid=4BEE0E99-0A6E-4A64-8359-720EED904FB3&appid=D4D52672-91D7-4C74-8AD8-42B1D98141A5&format=json&locale=en-US&device.os=osx&scenarios=ulm&instanceid=E043E4FE-51EF-4B74-8133-B728C4FEA8AA&result.profanitymarkup=0
#DEBUG: json={"version":"3.0","header":{"status":"success","scenario":"ulm","name":"hello","lexical":"hello","properties":{"requestid":"cf3b5694-67f4-4f19-aacf-beef149c80bb","HIGHCONF":"1"}},"results":[{"scenario":"ulm","name":"hello","lexical":"hello","confidence":"0.9463161","properties":{"HIGHCONF":"1"}}]}
hello
```
Il devrait d'afficher comme moi "hello" tout à la fin.

**Comment by satana888** [comment]
Voila j’ai effectué le test et ça me renvoi ceci :

 

pi@raspberrypi:~ $ cd stt_engines/bing/

-bash: cd: stt_engines/bing/: Aucun fichier ou dossier de ce type

pi@raspberrypi:~ $ cd jarvis

pi@raspberrypi:~/jarvis $ cd stt_engines/bing/

pi@raspberrypi:~/jarvis/stt_engines/bing $ ./test.sh

DEBUG: token missing or expired

DEBUG: json=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzY29wZSI6Imh0dHBzOi8vc3BlZWNoLnBsYXRmb3JtLmJpbmcuY29tIiwic3Vic2NyaXB0aW9uLWlkIjoiYzA5YmViN2EwMWE5NGNkYmIwYmY0NTc0NzYxOTdkYTAiLCJwcm9kdWN0LWlkIjoiQmluZy5TcGVlY2guUHJldmlldyIsImNvZ25pdGl2ZS1zZXJ2aWNlcy1lbmRwb2ludCI6Imh0dHBzOi8vYXBpLmNvZ25pdGl2ZS5taWNyb3NvZnQuY29tL2ludGVybmFsL3YxLjAvIiwiYXp1cmUtcmVzb3VyY2UtaWQiOiIiLCJpc3MiOiJ1cm46bXMuY29nbml0aXZlc2VydmljZXMiLCJhdWQiOiJ1cm46bXMuc3BlZWNoIiwiZXhwIjoxNDk3OTE1MTU4fQ.kGABUjEzHrdg32XsGxdvF8kHQkCBy5H8aVXOiwlT5oQ

DEBUG: token will expire in 590 seconds

DEBUG: curl https://speech.platform.bing.com/recognize/query?version=3.0&requestid=eb15c9ec-fc7e-4477-9c4c-4329954523fd&appid=D4D52672-91D7-4C74-8AD8-42B1D98141A5&format=json&locale=en-US&device.os=osx&scenarios=ulm&instanceid=E043E4FE-51EF-4B74-8133-B728C4FEA8AA&result.profanitymarkup=0

ERROR: bing recognition curl failed

pi@raspberrypi:~/jarvis/stt_engines/bing $

 

par hazard ? cela n’aurai pas a voir avec le fait des 5000 translations par mois ? un quota depassé ?

 

je me suis posé cette question dans la journée…

 

 

 

 

 

De : Alexandre Mély [mailto:notifications@github.com] 
Envoyé : lundi 19 juin 2017 20:24
À : alexylem/jarvis
Cc : satana888; Author
Objet : Re: [alexylem/jarvis] ERROR: bing recognition curl failed (#646)

 

Tu peux vérifier en lançant le script de test bing de Jarvis:

$ cd stt_engines/bing/
$ ./test.sh
#DEBUG: curl https://speech.platform.bing.com/recognize/query?version=3.0 <https://speech.platform.bing.com/recognize/query?version=3.0&requestid=4BEE0E99-0A6E-4A64-8359-720EED904FB3&appid=D4D52672-91D7-4C74-8AD8-42B1D98141A5&format=json&locale=en-US&device.os=osx&scenarios=ulm&instanceid=E043E4FE-51EF-4B74-8133-B728C4FEA8AA&result.profanitymarkup=0> &requestid=4BEE0E99-0A6E-4A64-8359-720EED904FB3&appid=D4D52672-91D7-4C74-8AD8-42B1D98141A5&format=json&locale=en-US&device.os=osx&scenarios=ulm&instanceid=E043E4FE-51EF-4B74-8133-B728C4FEA8AA&result.profanitymarkup=0
#DEBUG: json={"version":"3.0","header":{"status":"success","scenario":"ulm","name":"hello","lexical":"hello","properties":{"requestid":"cf3b5694-67f4-4f19-aacf-beef149c80bb","HIGHCONF":"1"}},"results":[{"scenario":"ulm","name":"hello","lexical":"hello","confidence":"0.9463161","properties":{"HIGHCONF":"1"}}]}
hello

Il devrait d'afficher comme moi "hello" tout à la fin.

**Comment by Jean-Bernard-Hallez** [comment]
Pour info... chez moi ca fonctionne j'ai:
DEBUG: curl https://speech.platform.bing.com/recognize/query?version=3.0&requestid=4b8500b5-56e7-4f66-b243-fda681ade585&appid=D4D52672-91D7-4C74-8AD8-42B1D98141A5&format=json&locale=en-US&device.os=osx&scenarios=ulm&instanceid=E043E4FE-51EF-4B74-8133-B728C4FEA8AA&result.profanitymarkup=0
DEBUG: json={"version":"3.0","header":{"status":"success","scenario":"ulm","name":"hello","lexical":"hello","properties":{"requestid":"4d166973-9f5c-4f18-aa03-b5bc55aedff1","HIGHCONF":"1"}},"results":[{"scenario":"ulm","name":"hello","lexical":"hello","confidence":"0.9463161","properties":{"HIGHCONF":"1"}}]}
hello

**Comment by alexylem** [comment]
@satana888 il y a des chances que tu aies dépassé le quote.
Tu utiliserais pas bing comme moteur de reconnaissance du mot clé? Si oui pas étonnant, il faudrait que tu utilises snowboy.

**Comment by satana888** [comment]
Bonjour, 

 

Merci de la réponse, je recherche justement la meilleure manière de ne plus avoir ce problème…

 

Seulement, je voulais tenter Snow boy, mais je ne trouve aucun tuto bien détaillé en français…

 

Aurai-tu un tuto bien facile à comprendre ? sur Snow boy ? 

 

Actuellement, avec bing, ça reviens puis ça repart et tout le temps comme ça… j’avoue que c’est très gênant pour bosser dessus.

 

 

 

D’avance merci

 

cordialement

**Comment by alexylem** [comment]
Pour snowboy il suffit de le choisir dans la config de Jarvis et il va s'installer tout seul... il suffit de suivre les instructions affichées.

**Comment by satana888** [comment]
Bonjour,

 

En fait, pour la reconnaissance du mot clé, j’utilise SnowBoy, mais une fois fait ( car ça marche super), quand je lui indique les différentes commandes, là il passe par bing comme recommandé sur l’installation. Quand il fonctionne, c’est super top,  mais le problème est qu’il marche une fois sur deux, c’est aléatoire et c’est pour cela que c’est stressant…

Alors je me demandais, si on pouvait avoir le bing speech d’une autre façon ? 

Ou une façon sur ?

Car WIT speech on ne connait pas le temps exacte, et il ne fonctionne pas j’ai essayé

Snow Boy, c’est un dictionnaire personnel et en hotword ( je l’utilise pour le réveiller c’est tout et ça marche bien )

Pocketsphinx, C’est en anglais…

 

Alors je recherchais justement une solution pour qu’il réponde après le hotword  à toutes mes commandes sans aucune hésitation… ??????? et de manière certaine à chaque fois !!!!!

 

 

D’avance merci

 

 

Cordialement

**Comment by SebastienVProject** [comment]
Hello, si tu veux tester l'application iOS en cours de dev, donne moi ton e-mail. L'avantage est que tu pourras (normalement) pouvoir faire fonctionner ton jarvis sans le pb de Bing, car l'application utilise Siri pour le speech-to-text, puis l api jarvis, et enfin de nouveau Siri pour le text-to-speech. L'inconvénient est de devoir avoir son tel à portée de main

**Comment by satana888** [comment]
Re-bonjour,

D’accord, je vais tenter cette voie-là mon mail est gmilliau@brutele.be

Une petite question encore ? j’ai entendu dire que tout ce qui passe chez SIRI « notre vie privée complète » est stocké et utilisé a d’autre fins…

En passant par-là on ouvre plein de porte sur notre vie privée, n’était-ce pas le contraire que l’on cherchait à viser à la base avec ce projet JARVIS ?

Ou il n’utilise qu’un speech texte ? rien de plus ?

Comment il pratique a vrai dire ?

 

Merci d’avance

 

Cordialement

**Comment by SebastienVProject** [comment]
Hello, lorsque je dis que j'utilise Siri, c'est uniquement que j'utilise le framework utilisé par Siri pour le stt et tts. Rien des ordres transmis n'est "applelisé". Et le déclenchement se fait par clic sur bouton. Le tel n'est jamais en mode écoute. Le clic déclenche l'enregistrement, un autre clic le stoppe, conversion en texte, et appel à openjarvis api. Donc soit rassuré !

**Comment by satana888** [comment]
Ha d’accord, alors je veux bien tenter J

**Comment by SebastienVProject** [comment]
Tu devrais recevoir un mail t'indiquant d'installer l'application testflight. Tu pourras alors tester l'application. N'hésite pas à me faire des retours via le formulaire aide, car je n'ai pas testé du tout encore sur petit format (j'ai une tablette et un 6Splus)

**Comment by satana888** [comment]
Bonsoir,

L’app pour SIRI c’est celle qui est le plugin dans le site ? ou c’est une toute autre app différente ? j’ai toujours rien reçu actuellement…

Merci d ‘avance

 

 

BAV

**Comment by SebastienVProject** [comment]
Je t'ai décrit dans mon message ce qu'il en est. Tu as dû avoir un mail

**Comment by wikijm** [comment]
Clôture du ticket jusqu'à obtention d'une réponse de la part de l'auteur de l'issue.
Closing of the ticket until a valid answer from the applicant is obtained.
