### ISSUE TITLE
Reconnaissance échec

### ISSUE THREAD

**Issue by Lusitanos67** [alexylem/jarvis#647]
Bonsoir, 

Après quelques temps, je reviens voir un peu ce que donne le projet. Après quelques mises à jour, et plusieurs nouvelles installations, j'arrive enfin à faire détecté le hotword, sauf qu'il le détecte 10sec après que j'ai fini... Il n'y a que moi qui rencontre se soucis ? Je n'ai rien changé de ma config, et cela n'a plus fonctionné. J'ai du supprimer le répertoire et relancer l'installation.

Merci

**Comment by D-Kalck** [comment]
Quel est le moteur utilisé pour la détection du hotword ?

**Comment by Lusitanos67** [comment]
Bonjour D-Kalck, 
J'ai testé avec sox et snowboy, les hp et micro fonctionnent bien via le test Jarvis.
Au début je me suis fait avoir car lors d'une mise à jour jarvis, il ne répondait plus lors de la détection du hotword, le champs dans la config s'est mis à blanc.
Lorsque je lance le mode trouble, il m'indique que le hotword est détecté, puis 10s après je peux lancer une commande.
Alors ça c'est lors des dernier essais, car les précédents m'indiquait un hotword détecté toutes les secondes. C'est là que je me suis arraché les cheveux car j'ai recommencé la config micro au moins 15 fois et toujours avec succès.

**Comment by D-Kalck** [comment]
Quelle est la distribution qui tourne sur le Raspberry ? Quels sont les autres logiciels qui tournent sur la machine ? Faudrait voir avec un "sudo top" si y'a pas éventuellement des process qui bouffent des ressources.

**Comment by alexylem** [comment]
@Lusitanos67 tu es sur quelle machine? Raspberry Pi ? Quelle version ?
Oui en effet comme indiqué par @D-Kalck un petit `top` ou `htop` serait utile, tu dois avoir un truc qui te bouffe les ressources.

**Comment by Lusitanos67** [comment]
derniere version de raspbian (version complète pas la lite).
Je vais regarder ça et je vous dis.

**Comment by Lusitanos67** [comment]
RAS côté ressources, voici les logs.

------------ Config ------------
jv_branch            master
jv_version
jv_arch              armv7l
jv_os_name           raspbian
jv_os_version        8
language             fr_FR
play_hw              hw:0,1
rec_hw               hw:1,0
speaker              ALSA
microphone           Asahi Kasei Microsystems Co., Ltd
recorder             sox
trigger_stt          snowboy
command_stt          bing
tts_engine           google
--------------------------------

DEBUG: program_startup hook
DEBUG: start_speaking hook
Jarvis: Hello
--2017-06-24 17:28:53--  http://translate.google.com/translate_tts?tl=fr&client=tw-ob&ie=UTF-8&q=Hello
Résolution de translate.google.com (translate.google.com)… 216.58.201.238, 2a00:1450:4007:816::200e
Connexion à translate.google.com (translate.google.com)|216.58.201.238|:80… connecté.
requête HTTP transmise, en attente de la réponse… 200 OK
Taille : 2688 (2,6K) [audio/mpeg]
Sauvegarde en : « /dev/shm/hello.mp3 »

/dev/shm/hello.mp3  100%[=====================>]   2,62K  --.-KB/s   ds 0,001s

2017-06-24 17:28:53 (1,81 MB/s) — « /dev/shm/hello.mp3 » sauvegardé [2688/2688]

DEBUG: stop_speaking hook
User defined commands:
*AIDE*                  *BONJOUR*|*SALUT*       *COMMENT*APPELLE*
*MERCI*                 *AU REVOIR*|*BYE*       ANNULE*|TERMINE*
ENCORE*                 *TEST*                  *VERSION*
*REPETE (*) ET (*)      *CA VA*                 >*OUI*
>*NON*|*PAS*
Jarvis: Waiting to hear 'Jarvis'
Lionel: (listening...)
DEBUG: models=jarvis
INFO:snowboy:Ticks: [2, 20, 5, -1]
INFO:snowboy:Keyword 1 detected at time: 2017-06-24 17:29:02
INFO:snowboy:Ticks status: 2 2 4 1
DEBUG: modelid=0
Jarvis
DEBUG: entering_cmd hook
Lionel: (listening...)
DEBUG: start_speaking hook ""
utils/timeout.sh 10 rec -V1 -q -r 16000 -c 1 -b 16 -e signed-integer --endian little /dev/shm/jarvis-record.wav gain 0 silence 1 0.1 8.1% 1 0.5 8.1% pad 0.5 0.5 trim 0 5
DEBUG: stop_listening hook
DEBUG: timeout, end of conversation
DEBUG: listening_timeout hook
DEBUG: exiting_cmd hook
Jarvis: Waiting to hear 'Jarvis'
Lionel: (listening...)
DEBUG: models=jarvis
INFO:snowboy:Ticks: [2, 20, 5, -1]
INFO:snowboy:Keyword 1 detected at time: 2017-06-24 17:29:43
INFO:snowboy:Keyword 1 detected at time: 2017-06-24 17:29:48
INFO:snowboy:Keyword 1 detected at time: 2017-06-24 17:29:52
^C
DEBUG: program_exit hook

**Comment by alexylem** [comment]
@Lusitanos67 tu peux essayer de désactiver les ticks dans Settings > Voice Reco > Snowboy settings > Check ticks. La reco du hotword sera un peu plus rapide.

**Comment by Lusitanos67** [comment]
Voici le retour de mes tests:
- même en désactivant les ticks => latence
- refaire la configuration stepbystep => latence
- changer la partie reconnaissance & speech => latence

C'est ding ça, je ne comprends pas. Le pire c'est que même en mode debug, les logs figes un moment, puis tout d'un coup j'ai 6-5 lignes qui apparaissent d'un seul coup 10 secondes plus tard en m'indiquant que le keyword a été détecté... Sauf qu'entre temps je l'ai déjà répété 6 fois :(

Edit: j'avais un htop sur une seconde fenêtre à côté, et rien d'affolant niveau mémoire et proc.

**Comment by D-Kalck** [comment]
À moins d'avoir une carte SD lente ou à moitié corrompue, je vois pas trop ce que ça pourrait être d'autre.
Quel est ton micro, sinon ?

**Comment by Lusitanos67** [comment]
Mon système boot sur un hdd. Il boot en moins de 5sec donc je ne pense pas que ça soit ça.
Le micro est un Andoer Omni-Directional, mais je vais me tourner vers un ps eye, pour voir si c'est mieux par contre j'ai peur de devoir parler super proche du micro.

**Comment by Lusitanos67** [comment]
Pb resolu, j'ai mis la sensibilité du micro à 100% (syst.) Et ca fonctionne beaucoup mieux
