### ISSUE TITLE
Ability to change timeout duration

### ISSUE THREAD

**Issue by clemsii1998** [alexylem/jarvis#648]
Bonjour, Jarvis se met en mode conversation une fois le "hotword" prononcé mais on a un temps limité pour lui donner un ordre. J'aimerais donc savoir comment faire pour modifier voir supprimer ce timeout.

**Comment by Jean-Bernard-Hallez** [comment]
Oui ca m’intéresse aussi car j'ai un plugin qui pose des questions... on a pas le temps de réfléchir.... qu' il quitte trop vite le mode conversation...

**Comment by alexylem** [comment]
Ca vous irait qu'on puisse modifier ce timeout dans la configuration de Jarvis?

**Comment by clemsii1998** [comment]
oui, ça serait plus pratique pour ceux qui ont besoin de plus de temps entre les différentes questions dans le mode conversation.

**Comment by alexylem** [comment]
Implémenté sur la branch `beta`. Pour le tester dès à présent:
Menu `Settings > General > Branch > beta`
Sinon attendre la mise à jour de ce weekend.

**Comment by alexylem** [comment]
![image](https://user-images.githubusercontent.com/11017174/27517556-f15ba498-59ce-11e7-8638-919025d7e398.png)

**Comment by clemsii1998** [comment]
merci ! je test ça dès demain

**Comment by clemsii1998** [comment]
je te pose la question ici mais je peux créer une nouvelle issue si tu veux.
J'aimerais avoir quelques infos sur le système de trigger : physical_button , j'en ai besoin pour le projet que je crée actuellement mais je ne vois pas comment je peux utiliser un bouton pour lancer le mode conversation de jarvis plutôt qu'avec un hotword.

**Comment by alexylem** [comment]
Il y a un exemple sur le site
https://www.openjarvis.com/content/prerequisites

**Comment by clemsii1998** [comment]
sur le site il est dit que l'on doit lancer jarvis avec un -l mais cette option permet juste de lancer le mode conversation sans passer par le hotword.

**Comment by alexylem** [comment]
@clemsii1998 c'est justement l'idée. Il te suffit de construire un script qui détecte l'appui sur un bouton, et lance la commande `jarvis -l` ce qui passera jarvis directement en mode conversation. Comme tu l'as demandé plus haut.

**Comment by Jean-Bernard-Hallez** [comment]
Voir ici https://github.com/alexylem/jarvis/issues/656
#650
