### ISSUE TITLE
Jeedom et Jarvis en Docker sur Synology

### ISSUE THREAD

**Issue by Didier3L** [alexylem/jarvis#649]
Bonjour
Je fais fonctionner Jeedom via Docker sur mon Synology DS216+.
Je voulais savoir si Jarvis pouvais également être installé de la même manière ?

**Comment by Didier3L** [comment]
Bonjour
Je fais fonctionner Jeedom via Docker sur mon Synology DS216+.
Je voulais savoir si Jarvis pouvais également être installé de la même manière ?

**Comment by alexylem** [comment]
Jarvis n'est pas disponible sur Docker, mais je pourrais jeter un coup voir si c'est facilement faisable. Je ne connais pas (encore) Docker.

**Comment by Didier3L** [comment]
Quand on a un Synology avec Docker, cela permet d'avoir un système complétement intégré et autonome.
Même si bien sur le Raspberry Pi permet d'avoir un petit PC autonome.

**Comment by Hecatonchyr** [comment]
Avez-vous essayé de pull l'image zaraki673/docker-jarvis ?

https://hub.docker.com/r/zaraki673/docker-jarvis/~/dockerfile/

**Comment by Didier3L** [comment]
Non. merci pour l'info.
Mais je pense que c'est mieux de commencer à tester **Jarvis** sur **Virtualbox** avec Debian Jessie.

**Comment by Didier3L** [comment]
Problème avec installation sur sur Virtualbox
L'installation s’arrête avec un message d'avertissement concernant SNOWBOY
Pré-packaged Snowboy binaries only available for 
Rasbpian 8 Jessie on Raspberry Pi .....
......

**Comment by Oliv4945** [comment]
Ça veut dire qu'il faut compiler snowboy car il n'y a pas de librairies toutes prêtes pour PC. De mémoire je l'avais fait sur une machine virtuelle debian aussi et les instructions du site de snowboy étaient bien faites

**Comment by Didier3L** [comment]
J'ai installé une image debian avec Docker
[](https://hub.docker.com/_/debian/)

J'ai réussi à installer Jarvis sans micro et audio
Quand je veux sauvegarder le fichier de commande Jarvis, j'ai une erreur  [ Error writing jarvis-commands: Permission denied ]

j'ai pourtant crréé un utilisateur (didier) avec des droits root
`#                                                                                                            
# This file MUST be edited with the 'visudo' command as root.                                                
#                                                                                                            
# Please consider adding local content in /etc/sudoers.d/ instead of                                         
# directly modifying this file.                                                                              
#                                                                                                            
# See the man page for details on how to write a sudoers file.                                               
#                                                                                                            
Defaults        env_reset                                                                                    
Defaults        mail_badpass                                                                                 
Defaults        secure_path="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"                   
                                                                                                             
# Host alias specification                                                                                   
                                                                                                             
# User alias specification                                                                                   
                                                                                                             
# Cmnd alias specification                                                                                   
                                                                                                             
# User privilege specification                                                                               
root    ALL=(ALL:ALL) ALL                                                                                    
didier ALL=(ALL:ALL) ALL                                                                                     
                                                                                                             
# Allow members of group sudo to execute any command                                                         
%sudo   ALL=(ALL:ALL) ALL                                                                                    
%didier ALL=(ALL:ALL) ALL                                                                                    
                                                                                                             
                                                                                                             
# See sudoers(5) for more information on "#include" directives:                                              
                                                                                                             
#includedir /etc/sudoers.d    `

Peux être un problème de droit ?

Enfin est il possible de lancer Jarvis sans refaire toute la partie configuration ?

**Comment by Didier3L** [comment]
J'ai trouvé d’où venait le problème !
Il faut faire l'installation avec un utilisateur autre que root
Il faudra que l'utilisateur ait des privilèges root
Cela passe par la modification du fichier /etc/sudoers

Pour finir, j'ai pu utiliser Jarvis uniquement avec le clavier. 
Mon micro n'est pas reconnu sur le port USB de mon Synology

**Comment by Didier3L** [comment]
J'ai voulu refaire une installation 

> didier@debian1:/$ su didier                                                                                  
> Password:                                                                                                    
> didier@debian1:/$ git clone https://github.com/alexylem/jarvis.git                                           
> fatal: could not create work tree dir 'jarvis': Permission denied                                            
> 
????

**Comment by Oliv4945** [comment]
Je suppose que c'est le même sujet qu'en #658, donc je ferme pour l'instant mais tu peux rouvrir si besoin
