### ISSUE TITLE
Speed / High pitch sound issue with JABRA Speaker with Raspberry Pi

### ISSUE THREAD

**Issue by LengZai** [alexylem/jarvis#65]
### Description

Hi,

At first, thanks for your project, I really like it and I have started to test your project.
I use a Raspberry Pi 3 and a Jabra Speaker MS510
I got an issue to play 16000Hz sound.
It was very annoying because all my voices and Jarvis voice were very fast with a high pitched

I finally found a fix to make it worked and i hope it will help someone else. Maybe you can add it to your code but i suppose you need to check the impact.

At first i told to my raspberry that i want my USB audio device as default
So i create (as i don't have it) the file alsa-base.conf

```
$cat /etc/modprobe.d/alsa-base.conf
# This sets the index value of the cards but doesn't reorder.
options snd_usb_audio index=0
options snd_bcm2835 index=1

# Does the reordering.
options snd slots=snd_usb_audio,snd_bcm2835
```

So by default my audio device will be the Jabra speaker, even after rebooting the device

With the command $aplay -L
I listed all my "audio devices" and i found that there is a line named sysdefault

```
$ aplay -L
null
    Discard all samples (playback) or generate zero samples (capture)
pulse
    PulseAudio Sound Server
sysdefault
default:CARD=USB
    Jabra SPEAK 510 USB, USB Audio
    Default Audio Device
front:CARD=USB,DEV=0
    Jabra SPEAK 510 USB, USB Audio
    Front speakers
surround21:CARD=USB,DEV=0
    Jabra SPEAK 510 USB, USB Audio
    2.1 Surround output to Front and Subwoofer speakers
surround40:CARD=USB,DEV=0
    Jabra SPEAK 510 USB, USB Audio
    4.0 Surround output to Front and Rear speakers
surround41:CARD=USB,DEV=0
........
```

So to find my issue i used "aplay" with -D option until i got the correct sound
Example: `$aplay -Dsysdefault:CARD=USB -c 2 -f cd audio_test_from_pico2wave.wav`
(it also works like this: `$aplay -Dsysdefault -c 2 -f cd audio_test_from_pico2wave.wav`)

So to fix my issue, i changed the file (generated and cleaned by jarvis.sh) `.asoundrc` by replacing **pcm.!default** by **pcm.!sysdefault**
to get something like this

```
$cat ./.asoundrc
pcm.!sysdefault {
  type asym
   playback.pcm {
     type plug
     slave.pcm "hw:0,0"
   }
   capture.pcm {
     type plug
     slave.pcm "hw:0,0"
   }
}
```

As you can see, even I plugged an USB audio device, I put hw:0,0 and not hw:1,0 as i set my USB audio device as default (to load the audio usb driver first) on the file alsa-base.conf

**Comment by alexylem** [comment]
I will leave it open until I test the impact & probably integrate it in the code.
Thanks for raising this and for your testings.

**Comment by alexylem** [comment]
Couldn't find anything obvious about the different between `default` & `sysdefault` in Alsa.
However I tested on my raspberry pi and replacing `default` by `sysdefault` as you suggested still works (even after a reboot).
I'll commit this and see reaction from the community 😄

**Comment by alexylem** [comment]
I had to fallback this one. My mic was no longer working with this config for some reason (although it was working during my tests).

**Comment by wikijm** [comment]
I have exactly the the same on a fresh new Raspberry Pi 3 installation, except that I have a [JABRA SPEAK 410](http://www.jabra.fr/business/speakerphones/jabra-speak-series/jabra-speak-410).

J'ai exactement le même problème sur un e installation toute fraîche sur un Raspberry Pi 3, excepté que j'utilise un [JABRA SPEAK 410](http://www.jabra.fr/business/speakerphones/jabra-speak-series/jabra-speak-410).

**Comment by alexylem** [comment]
Hi @wikijm, is fix also working for you?
>So to fix my issue, i changed the file (generated and cleaned by jarvis.sh) .asoundrc by replacing pcm.!default by pcm.!sysdefault

**Comment by wikijm** [comment]
Badly, no. With `pcm.!sysdefault`, I stop hearing sound, on Jarvis and for every sounds.

Hélas non. Avec `pcm.!sysdefault`, je n'entends plus aucun son, que ce soit pour Jarvis et tout le reste.

**Comment by LengZai** [comment]
Hi @wikijm

Can you show us the ouput of the command $aplay -L
Thanks

**Comment by wikijm** [comment]
Sorry for the late response.
Here's the result:

pi@RaspAP3:~ $ aplay -L
null
    Discard all samples (playback) or generate zero samples (capture)
pulse
    PulseAudio Sound Server
default
sysdefault:CARD=USB
    Jabra SPEAK 410 USB, USB Audio
    Default Audio Device
front:CARD=USB,DEV=0
    Jabra SPEAK 410 USB, USB Audio
    Front speakers
surround21:CARD=USB,DEV=0
    Jabra SPEAK 410 USB, USB Audio
    2.1 Surround output to Front and Subwoofer speakers
surround40:CARD=USB,DEV=0
    Jabra SPEAK 410 USB, USB Audio
    4.0 Surround output to Front and Rear speakers
surround41:CARD=USB,DEV=0
    Jabra SPEAK 410 USB, USB Audio
    4.1 Surround output to Front, Rear and Subwoofer speakers
surround50:CARD=USB,DEV=0
    Jabra SPEAK 410 USB, USB Audio
    5.0 Surround output to Front, Center and Rear speakers
surround51:CARD=USB,DEV=0
    Jabra SPEAK 410 USB, USB Audio
    5.1 Surround output to Front, Center, Rear and Subwoofer speakers
surround71:CARD=USB,DEV=0
    Jabra SPEAK 410 USB, USB Audio
    7.1 Surround output to Front, Center, Side, Rear and Woofer speakers
iec958:CARD=USB,DEV=0
    Jabra SPEAK 410 USB, USB Audio
    IEC958 (S/PDIF) Digital Audio Output
dmix:CARD=USB,DEV=0
    Jabra SPEAK 410 USB, USB Audio
    Direct sample mixing device
dsnoop:CARD=USB,DEV=0
    Jabra SPEAK 410 USB, USB Audio
    Direct sample snooping device
hw:CARD=USB,DEV=0
    Jabra SPEAK 410 USB, USB Audio
    Direct hardware device without any conversions
plughw:CARD=USB,DEV=0
    Jabra SPEAK 410 USB, USB Audio
    Hardware device with all software conversions
sysdefault:CARD=ALSA
    bcm2835 ALSA, bcm2835 ALSA
    Default Audio Device
dmix:CARD=ALSA,DEV=0
    bcm2835 ALSA, bcm2835 ALSA
    Direct sample mixing device
dmix:CARD=ALSA,DEV=1
    bcm2835 ALSA, bcm2835 IEC958/HDMI
    Direct sample mixing device
dsnoop:CARD=ALSA,DEV=0
    bcm2835 ALSA, bcm2835 ALSA
    Direct sample snooping device
dsnoop:CARD=ALSA,DEV=1
    bcm2835 ALSA, bcm2835 IEC958/HDMI
    Direct sample snooping device
hw:CARD=ALSA,DEV=0
    bcm2835 ALSA, bcm2835 ALSA
    Direct hardware device without any conversions
hw:CARD=ALSA,DEV=1
    bcm2835 ALSA, bcm2835 IEC958/HDMI
    Direct hardware device without any conversions
plughw:CARD=ALSA,DEV=0
    bcm2835 ALSA, bcm2835 ALSA
    Hardware device with all software conversions
plughw:CARD=ALSA,DEV=1
    bcm2835 ALSA, bcm2835 IEC958/HDMI
    Hardware device with all software conversions

**Comment by wikijm** [comment]
After Jarvis and Raspbian update, everything Workstation fine.

**Comment by wikijm** [comment]
After verification, the problem do not appear when I start Jarvis normally, but this problem still appear with the "Troubleshooting mode"

**Comment by taostaos** [comment]
Had the same issue on my debian jessie home server with a Jabra 410.  It looks like the tts.wav tmp file created by Pico have a 16000hz sample rate. As I didn't found a solution to change alsa default sample rate, I just convert the tmp file with avconv to 44100hz. Quick and dirty, but it's seamless on my server.

**Comment by alexylem** [comment]
Does it work is you pass the format to aplay?
```
aplay --rate=16000 --channels=1 --format=S16_LE tts.wav
```
You can also use sox to convert:
```shell
sox tts.wav.wav -r 44100 tts.wav
```

**Comment by taostaos** [comment]
> 
> 
> Does it work is you pass the format to aplay?
> 
> `aplay --rate=16000 --channels=1 --format=S16_LE tts.wav`
Nop, this doesn't work
> 
> You can also use sox to convert:
> 
> `sox tts.wav -r 44100 tts.wav`
> 
Yep this work.
>

**Comment by rikigeek** [comment]
I had exactly the same issue. I use a Jabra SPEAKER 510

```
hw:CARD=USB,DEV=0
    Jabra SPEAK 510 USB, USB Audio
    Direct hardware device without any conversions
plughw:CARD=USB,DEV=0
    Jabra SPEAK 510 USB, USB Audio
    Hardware device with all software conversions
```
And I use the following `~/.asoundrc`:
```
pcm.jabbra {
	type hw
	card 1
	device 0
	rate 48000
}
pcm.!default {
  type asym
   playback.pcm {
     type plug
     slave.pcm "jabbra"
   }
   capture.pcm {
     type plug
     slave.pcm "hw:1,0"
   }
}
```
The important point is to set the rate to 48KHz for the Jabbra playback. From my different testing results, only 16000 and 48000 values allow aplay to send something. And only 48000 allow aplay to send something **correctly**!
Hope it will also work for you.

**Comment by wikijm** [comment]
@rikigeek With your solution I'm able to use a virtual "jabra" audio device, but the issue still remain.

**Comment by wikijm** [comment]
To resolve this issue:

- Follow @rikigeek solution (create "jabra" audio device, https://github.com/alexylem/jarvis/issues/65#issuecomment-257472419)
- Replace all text from ./config/play_hw to "jabra" value

**Comment by wikijm** [comment]
@LengZai Could you try solution below? (https://github.com/alexylem/jarvis/issues/65#issuecomment-267454129)

**Comment by yaazzz** [comment]
Bonjour,

Cela fonctionne avec la configuration suivante dans le .asoundrc :

pcm.jabbra {
    type hw
    card 1
    device 0
    rate 48000
}
pcm.!default {
  type asym
   playback.pcm {
     type plug
     slave.pcm "jabbra"
   }
   capture.pcm {
     type plug
     slave.pcm "hw:1,0"
   }
}

**Comment by esilky** [comment]
Since the Jabra (410 in my case) works fine when I use it on my PC, it seems like a configuration issue that should be able to be detected.  If I plug in my Logitech USB headset into the Raspberry Pi, it works fine.  If I plug either of these into my PC they both work fine - so again, it seems like something the driver or configuration should be able to handle.

I need the Jabra to work with my Raspberry Pi, so I am interested to a solution to this problem.

**Comment by wikijm** [comment]
Hi @esilky, 
Did you try solution below? 

    Follow @rikigeek solution (create "jabra" audio device, #65 (comment))
    Replace all text from ./config/play_hw to "jabra" value

**Comment by wikijm** [comment]
A solution was provided by @rikigeek and @yaazzz.
Please follow it, and eventualy re-open the ticket if problem still remains.

**Comment by claudioita** [comment]
I tried all and still have the problem

**Comment by claudioita** [comment]
I did follow step 65

**Comment by alexylem** [comment]
@claudioita please paste here the config header of Jarvis (beginning of troubleshooting mode) as well as your ~/.asoudrc file. Thanks.

**Comment by claudioita** [comment]
Please note that it did work in the past.
In the meantime I installed AlecaPi and AssistantPi .. and those might have changed something?

pcm.jabbra {
    type hw
    card 1
    device 0
    rate 48000
}
pcm.!default {
  type asym
   playback.pcm {
     type plug
     slave.pcm "jabbra"
   }
   capture.pcm {
     type plug
     slave.pcm "hw:1,0"
   }
}

pi@raspberrypi:~ $ aplay -L
null
    Discard all samples (playback) or generate zero samples (capture)
pulse
    PulseAudio Sound Server
default
    Playback/recording through the PulseAudio sound server
sysdefault:CARD=USB
    Jabra SPEAK 510 USB, USB Audio
    Default Audio Device
front:CARD=USB,DEV=0
    Jabra SPEAK 510 USB, USB Audio
    Front speakers
surround21:CARD=USB,DEV=0
    Jabra SPEAK 510 USB, USB Audio
    2.1 Surround output to Front and Subwoofer speakers
surround40:CARD=USB,DEV=0
    Jabra SPEAK 510 USB, USB Audio
    4.0 Surround output to Front and Rear speakers
surround41:CARD=USB,DEV=0
    Jabra SPEAK 510 USB, USB Audio
    4.1 Surround output to Front, Rear and Subwoofer speakers
surround50:CARD=USB,DEV=0
    Jabra SPEAK 510 USB, USB Audio
    5.0 Surround output to Front, Center and Rear speakers
surround51:CARD=USB,DEV=0
    Jabra SPEAK 510 USB, USB Audio
    5.1 Surround output to Front, Center, Rear and Subwoofer speakers
surround71:CARD=USB,DEV=0
    Jabra SPEAK 510 USB, USB Audio
    7.1 Surround output to Front, Center, Side, Rear and Woofer speakers
iec958:CARD=USB,DEV=0
    Jabra SPEAK 510 USB, USB Audio
    IEC958 (S/PDIF) Digital Audio Output
dmix:CARD=USB,DEV=0
    Jabra SPEAK 510 USB, USB Audio
    Direct sample mixing device
dsnoop:CARD=USB,DEV=0
    Jabra SPEAK 510 USB, USB Audio
    Direct sample snooping device
hw:CARD=USB,DEV=0
    Jabra SPEAK 510 USB, USB Audio
    Direct hardware device without any conversions
plughw:CARD=USB,DEV=0
    Jabra SPEAK 510 USB, USB Audio
    Hardware device with all software conversions
sysdefault:CARD=ALSA
    bcm2835 ALSA, bcm2835 ALSA
    Default Audio Device
dmix:CARD=ALSA,DEV=0
    bcm2835 ALSA, bcm2835 ALSA
    Direct sample mixing device
dmix:CARD=ALSA,DEV=1
    bcm2835 ALSA, bcm2835 IEC958/HDMI
    Direct sample mixing device
dsnoop:CARD=ALSA,DEV=0
    bcm2835 ALSA, bcm2835 ALSA
    Direct sample snooping device
dsnoop:CARD=ALSA,DEV=1
    bcm2835 ALSA, bcm2835 IEC958/HDMI
    Direct sample snooping device
hw:CARD=ALSA,DEV=0
    bcm2835 ALSA, bcm2835 ALSA
    Direct hardware device without any conversions
hw:CARD=ALSA,DEV=1
    bcm2835 ALSA, bcm2835 IEC958/HDMI
    Direct hardware device without any conversions
plughw:CARD=ALSA,DEV=0
    bcm2835 ALSA, bcm2835 ALSA
    Hardware device with all software conversions
plughw:CARD=ALSA,DEV=1
    bcm2835 ALSA, bcm2835 IEC958/HDMI
    Hardware device with all software conversions
pi@raspberrypi:~ $

**Comment by alexylem** [comment]
@claudioita did you set your `jarvis/config/play_hw` to "jabbra" [as suggested](https://github.com/alexylem/jarvis/issues/65#issuecomment-267454129) by @wikijm ?

**Comment by claudioita** [comment]
in /home/pi/jarvis/config

its empty directory (just file .gitkeep empty)

**Comment by alexylem** [comment]
@claudioita it's not normal, Jarvis is not configured.
Please run:
```
$> jarvis -i
```
Then once completed, set your `play_hw` to `jabbra`:
```shell
$> echo "jabbra" > /home/pi/jarvis/config/play_hw
```

**Comment by claudioita** [comment]
Mmmh it seems to work. Although the audio is not totally clear, but maybe that's how it should sound (difficult to write how it is).
WHile with Jarvis seems ok, I still have the same high pitch, using the Google Assistant SDK ... you know by any chance what and where shall I look?

Must be the same problem

**Comment by claudioita** [comment]
Although the audio is not totally clear, but maybe that's how it should sound (difficult to write how it is)?
Other issue, I still have the same high pitch, using the Google Assistant SDK ... you know by any chance what and where shall I look?

Must be the same problem

**Comment by claudioita** [comment]
this is the log


ON_CONVERSATION_TURN_STARTED
ON_END_OF_UTTERANCE
ON_RECOGNIZING_SPEECH_FINISHED:
  {'text': 'what time is it'}
ON_RESPONDING_STARTED:
  {'is_error_response': False}
WriteDataToAlsa: Under-run occurred; attempting to recover.
ALSA lib pcm.c:7843:(snd_pcm_recover) underrun occurred
WriteDataToAlsa: Under-run occurred; attempting to recover.
ALSA lib pcm.c:7843:(snd_pcm_recover) underrun occurred
WriteDataToAlsa: Under-run occurred; attempting to recover.
ALSA lib pcm.c:7843:(snd_pcm_recover) underrun occurred
WriteDataToAlsa: Under-run occurred; attempting to recover.
ALSA lib pcm.c:7843:(snd_pcm_recover) underrun occurred
WriteDataToAlsa: Under-run occurred; attempting to recover.
ALSA lib pcm.c:7843:(snd_pcm_recover) underrun occurred
WriteDataToAlsa: Under-run occurred; attempting to recover.
ALSA lib pcm.c:7843:(snd_pcm_recover) underrun occurred
WriteDataToAlsa: Under-run occurred; attempting to recover.
ALSA lib pcm.c:7843:(snd_pcm_recover) underrun occurred
WriteDataToAlsa: Under-run occurred; attempting to recover.
ALSA lib pcm.c:7843:(snd_pcm_recover) underrun occurred
WriteDataToAlsa: Under-run occurred; attempting to recover.
ALSA lib pcm.c:7843:(snd_pcm_recover) underrun occurred
WriteDataToAlsa: Under-run occurred; attempting to recover.
ALSA lib pcm.c:7843:(snd_pcm_recover) underrun occurred
WriteDataToAlsa: Under-run occurred; attempting to recover.
ALSA lib pcm.c:7843:(snd_pcm_recover) underrun occurred
WriteDataToAlsa: Under-run occurred; attempting to recover.
ALSA lib pcm.c:7843:(snd_pcm_recover) underrun occurred
WriteDataToAlsa: Under-run occurred; attempting to recover.
ALSA lib pcm.c:7843:(snd_pcm_recover) underrun occurred
WriteDataToAlsa: Under-run occurred; attempting to recover.
ALSA lib pcm.c:7843:(snd_pcm_recover) underrun occurred
WriteDataToAlsa: Under-run occurred; attempting to recover.
ALSA lib pcm.c:7843:(snd_pcm_recover) underrun occurred
WriteDataToAlsa: Under-run occurred; attempting to recover.
ALSA lib pcm.c:7843:(snd_pcm_recover) underrun occurred
WriteDataToAlsa: Under-run occurred; attempting to recover.
ALSA lib pcm.c:7843:(snd_pcm_recover) underrun occurred
WriteDataToAlsa: Under-run occurred; attempting to recover.
ALSA lib pcm.c:7843:(snd_pcm_recover) underrun occurred
WriteDataToAlsa: Under-run occurred; attempting to recover.
ALSA lib pcm.c:7843:(snd_pcm_recover) underrun occurred
WriteDataToAlsa: Under-run occurred; attempting to recover.
ALSA lib pcm.c:7843:(snd_pcm_recover) underrun occurred
WriteDataToAlsa: Under-run occurred; attempting to recover.
ALSA lib pcm.c:7843:(snd_pcm_recover) underrun occurred
ON_RESPONDING_FINISHED
ON_CONVERSATION_TURN_FINISHED:
  {'with_follow_on_turn': False}

**Comment by alexylem** [comment]
We don't provide support here for Google Assistant SDK. Thank you for your understanding.

**Comment by jycoma** [comment]
Hi,

I'm sorry but it is not possible to create the file alsa-base.conf. 
I have this message when i want to create : 
"modprobe.d/alsa-base.conf"
"modprobe.d/alsa-base.conf" E212: Can't open file for writing
Press ENTER or type command to continue

**Comment by Oliv4945** [comment]
Hi @jycoma, are you trying with sufficient privileges ?
As it seems to be an issue related to Alsa, you should ask Alsa developers ;)
