### ISSUE TITLE
Trigger mode : physical_button

### ISSUE THREAD

**Issue by clemsii1998** [alexylem/jarvis#650]
Salut, je ne sais pas si c'est moi qui ai mal compris ou fait mais je ne vois pas comment lancer la conversation avec Jarvis avec un bouton.
jarvis -l ne permet que de passer dans le mode conversation sans passer par le hotword, et ne demande jamais l'utilisation d'un bouton( même si on met trigger mode : physical_button ).
Es-ce que quelqu'un pourrait m'expliquer ?

**Comment by alexylem** [comment]
@clemsii1998 comme discuté dans #648 c'est à toi de faire le script qui détectera l'appui sur le bouton. Le script doit lancer la commande `jarvis -l` qui lancera Jarvis en mode conversation. Tu dois facilement pouvoir trouver ce genre de script sur le net.
