### ISSUE TITLE
Le C cédille dans une commande

### ISSUE THREAD

**Issue by D-Kalck** [alexylem/jarvis#651]
Dans mon fichier jarvis-commandes j'avais (entre autres) :
`*CA VA*==say "Très bien et toi ça va?"`
à part en tapant la commande "comment ca va" au clavier, je n'ai jamais pu lui faire comprendre, quand je dis "ça va", il le traduit bien en "ça va", du coup j'ai transformé ma commande en :
`*CA VA*|*çA VA*|*ÇA VA*==say "Très bien et toi ça va?"`
Et ça n'a rien changé, du coup je dirais qu'il y a une fonction dans Jarvis qui transforme les accents en caractères non accentués mais visiblement le "ç" ne fait pas partie des caractères transformés.

J'utilise bing pour le stt

EDIT :
après quelques tests, j'ai fait un script en UTF8 pour tester la fonction jv_sanitize, en fait, au lieu de convertir les lettres accentuées en lettres non accentuées, elle les supprime.

**Comment by Civodul72** [comment]
Salut,
J'utilise aussi BING en STT et je n'ai pas ce problème.
Dans la config des "locales", j'ai juste mis le FR UTF8, pas d'autres FR utilisé.

**Comment by wikijm** [comment]
Clôture du ticket jusqu'à obtention d'une réponse de la part de l'auteur de l'issue.
Closing of the ticket until a valid answer from the applicant is obtained.
