### ISSUE TITLE
Can't see plugins information in website

### ISSUE THREAD

**Issue by QuentinCG** [alexylem/jarvis#653]
### Description

When trying to go to any plugin (example: https://www.openjarvis.com/plugins/youtube-player) this
error message is displayed:

> Error message
PDOException: SQLSTATE[42000]: Syntax error or access violation: 1142 INSERT command denied to user 'domotiqulbdd'@'10.0.118.65' for table 'captcha_sessions': INSERT INTO {captcha_sessions} (uid, sid, ip_address, timestamp, form_id, solution, status, attempts) VALUES (:db_insert_placeholder_0, :db_insert_placeholder_1, :db_insert_placeholder_2, :db_insert_placeholder_3, :db_insert_placeholder_4, :db_insert_placeholder_5, :db_insert_placeholder_6, :db_insert_placeholder_7); Array ( [:db_insert_placeholder_0] => 0 [:db_insert_placeholder_1] => QdHgJ9poUttSN0fWdI13eWhsuDv2W_BP-jVlTw4nbvI [:db_insert_placeholder_2] => 89.90.214.145 [:db_insert_placeholder_3] => 1498728650 [:db_insert_placeholder_4] => comment_node_plugin_form [:db_insert_placeholder_5] => 55287b3fd282c60bab4fb99ece1913ba [:db_insert_placeholder_6] => 0 [:db_insert_placeholder_7] => 0 ) in _captcha_generate_captcha_session() (line 175 of /home/domotiqul/www/jarvis/sites/all/modules/captcha/captcha.inc).

![Error message](https://user-images.githubusercontent.com/16922101/27681228-cf738da8-5cbe-11e7-8522-ffb5eaeac3dc.png)

**Comment by alexylem** [comment]
Fixed. Will be recovered in coming minutes...

**Comment by Oliv4945** [comment]
Fixed by @alexylem, I am closing the issue
