### ISSUE TITLE
google_TTS : commande introuvable

### ISSUE THREAD

**Issue by catmanng** [alexylem/jarvis#654]
Bonjour Alexandre,

suite à l'installaton de jarvis,
lors d'une demande à jarvis,
celui ci me répond mais ne peut pas me répondre "vocalement" et m'indique une erreur :google_TTS : commande introuvable

voici le détails :
```

pi: ca va
jarvis: Très bien et toi ça va?
utils/utils.sh: ligne 172: google_TTS : commande introuvable
*OUI*			*NON*|*PAS*
```

pourriez vous m'aidez ?

merci d'avance,

Catmanng

**Comment by catmanng** [comment]
Bonjour,

Est ce que ce problème parle à quelqu'un!?

Merci d'avance ,

Catmanng

**Comment by wikijm** [comment]
Bonjour,

Merci de fournir ce qui est demandé lors de la création d'une issue, à savoir :
- Résultat des logs générés par Jarvis en troubleshooting mode
- (Facultatif) Enregistrement ASCIINEMA

Ne pas hésiter à rouvrir l'issue une fois fait.

**Comment by catmanng** [comment]
Bonjour,
merci de la réponse.

voici le message en lancant jarvis en   troubleshooting mode

pi@raspberrypi:~/jarvis $ ./jarvis.sh -v
Notice: you can use 'jarvis' instead of './jarvis.sh'
utils/configure.sh: ligne 209: stt_engines/false/main.sh: Aucun fichier ou dossier de ce type

------------ Config ------------
jv_branch            master 
jv_version            
jv_arch              armv7l 
jv_os_name           raspbian 
jv_os_version        8 
language             fr_FR 
play_hw              false 
rec_hw                
speaker              Default 
microphone           Default 
recorder             sox 
trigger_stt          snowboy 
command_stt          bing 
tts_engine           google 
--------------------------------

No mic configured, forcing keyboard mode
DEBUG: program_startup hook
DEBUG: start_speaking hook
jarvis: Hello
utils/utils.sh: ligne 172: google_TTS : commande introuvable
DEBUG: stop_speaking hook
User defined commands:
*AIDE*			*BONJOUR*|*SALUT*	*COMMENT*APPELLE*
*MERCI*			*AU REVOIR*|*BYE*	ANNULE*|TERMINE*
ENCORE*			*TEST*			*VERSION*
*REPETE (*) ET (*)	*CA VA*			>*OUI*
>*NON*|*PAS*
pi: ca va
$> say "Très bien et toi ça va?"
DEBUG: start_speaking hook
jarvis: Très bien et toi ça va?
utils/utils.sh: ligne 172: google_TTS : commande introuvable
DEBUG: stop_speaking hook
*OUI*			*NON*|*PAS*


si vous avez besoin, voici le lien de mon dossier jarvis complet
http://dl.free.fr/jLVf5Duhw


Merci d'avance de votre aide,

Catmanng

**Comment by satana888** [comment]
Bonjour

 

 

De : catmanng [mailto:notifications@github.com] 
Envoyé : jeudi 6 juillet 2017 21:07
À : alexylem/jarvis
Cc : Subscribed
Objet : Re: [alexylem/jarvis] google_TTS : commande introuvable (#654)

 

Bonjour,
merci de la réponse.

voici le message en lancant jarvis en troubleshooting mode

pi@raspberrypi:~/jarvis $ ./jarvis.sh -v
Notice: you can use 'jarvis' instead of './jarvis.sh'
utils/configure.sh: ligne 209: stt_engines/false/main.sh: Aucun fichier ou dossier de ce type


------------ Config ------------
jv_branch master
jv_version
jv_arch armv7l
jv_os_name raspbian
jv_os_version 8
language fr_FR
play_hw false
rec_hw
speaker Default
microphone Default
recorder sox
trigger_stt snowboy
command_stt bing
tts_engine google


No mic configured, forcing keyboard mode
DEBUG: program_startup hook
DEBUG: start_speaking hook
jarvis: Hello
utils/utils.sh: ligne 172: google_TTS : commande introuvable
DEBUG: stop_speaking hook
User defined commands:
AIDE BONJOUR|SALUT COMMENTAPPELLE*
MERCI AU REVOIR|BYE ANNULE*|TERMINE*
ENCORE* TEST VERSION
REPETE () ET (*) CA VA >OUI

NON|PAS
pi: ca va
$> say "Très bien et toi ça va?"
DEBUG: start_speaking hook
jarvis: Très bien et toi ça va?
utils/utils.sh: ligne 172: google_TTS : commande introuvable
DEBUG: stop_speaking hook
OUI NON|PAS

si vous avez besoin, voici le lien de mon dossier jarvis complet
http://dl.free.fr/jLVf5Duhw

Merci d'avance de votre aide,

Catmanng

**Comment by Oliv4945** [comment]
>si vous avez besoin, voici le lien de mon dossier jarvis complet


Bonne idée :-)
Ce qui nous amène à...pourquoi dans stt_engines le dossier s'appelle "google_old" ?
En le renommant en "google" ça devrait aller mieux !

**Comment by catmanng** [comment]
Bonjour,

Est ce que ce problème parle à quelqu'un!? 
Je suis bloqué et je comprends pas pourquoi.

Merci d'avance ,

Catmanng

**Comment by Oliv4945** [comment]
Bonjour @catmanng, as-tu lu ma réponse d'il y a deux jours ?

**Comment by Oliv4945** [comment]
Oops, désolé j'ai confondu TTS et STT, le problème est ailleurs.
Est-ce que tu peux essayer de refaire une config complète (Step-by-step wizard) et poster le résulat car je suis perturbé par ton log:
`utils/configure.sh: ligne 209: stt_engines/false/main.sh: Aucun fichier ou dossier de ce type`

**Comment by wikijm** [comment]
Clôture du ticket jusqu'à obtention d'une réponse de la part de l'auteur de l'issue.
Closing of the ticket until a valid answer from the applicant is obtained.

**Comment by tutsisback** [comment]
Bonjour,
Je suis désolé, je suis un newbie et je déterre ce sujet...
J'ai le même problème. J'ai réinstallé plusieurs fois jarvis mais j'obtiens toujours cette fameuse ligne :
`utilis/utils.sh: ligne 172: svox_pivo_TTS : commande introuvable`
ou
`utilis/utils.sh: ligne 172: google_TTS : commande introuvable`

si je définis google comme speech synthesis...

J'ai pu lire dans un autre sujet qu'il fallait regarder dans jarvis/config/tts_engine et bien j'ai une seule ligne :
`google`

Une idée ?
Merci à vous

**Comment by Oliv4945** [comment]
Salut,
Quel est le résultat de `jarvis -nv` ?

**Comment by tutsisback** [comment]
Résultat de la commande `jarvis -nv`
`
------------ Config ------------
jv_branch            master
jv_version
jv_arch              armv7l
jv_os_name           raspbian
jv_os_version        8
language             fr_FR
play_hw              false
rec_hw
speaker              Default
microphone           Default
recorder             sox
trigger_stt          snowboy
command_stt          snowboy
tts_engine           google
--------------------------------

No mic configured, forcing keyboard mode
DEBUG: program_startup hook
DEBUG: start_speaking hook
Jarvis: Bonjour
utils/utils.sh: ligne 172: google_TTS : commande introuvable
DEBUG: stop_speaking hook
User defined commands:
*AIDE*                  *BONJOUR*|*SALUT*       *COMMENT*APPELLE*
*MERCI*                 *AU REVOIR*|*BYE*       ANNULE*|TERMINE*
ENCORE*                 *TEST*                  *VERSION*
*REPETE (*) ET (*)      *CA VA*                 >*OUI*
>*NON*|*PAS*
Pierre:`

**Comment by Oliv4945** [comment]
Salut,

Dans ton log comme celui de @catmanng on voit `play_hw              false`, j'ai donc l'impression que la carte son n'est pas configurée.
Quel est le résultat de `more ~./asoundrc` ?
Que ce passe-t-il en refaisant une configuration avec le wizard ?

Sinon tu as un autre soucis dans ta config, le `command_stt` doit être `sox `pas `snowboy`

**Comment by tutsisback** [comment]
Oliv4945,

Oui je n'avais pas re-paramétré ma carte correctement mais le problème existait également lorsqu'elle était bien configurée. D'ailleurs je viens de le faire et ça ne marche toujours pas (voir mon `jarvis -nv`)
```
------------ Config ------------
jv_branch            master
jv_version
jv_arch              armv7l
jv_os_name           raspbian
jv_os_version        8
language             fr_FR
play_hw              hw:0,0
rec_hw
speaker              ALSA
microphone           Default
recorder             sox
trigger_stt          snowboy
command_stt          snowboy
tts_engine           google
--------------------------------

No mic configured, forcing keyboard mode
DEBUG: program_startup hook
DEBUG: start_speaking hook
Jarvis: Bonjour
utils/utils.sh: ligne 172: google_TTS : commande introuvable
DEBUG: stop_speaking hook
User defined commands:
*AIDE*                  *BONJOUR*|*SALUT*       *COMMENT*APPELLE*
*MERCI*                 *AU REVOIR*|*BYE*       ANNULE*|TERMINE*
ENCORE*                 *TEST*                  *VERSION*
*REPETE (*) ET (*)      *CA VA*                 >*OUI*
>*NON*|*PAS*
Pierre:
```

Par contre pour `command_stt` je ne vois pas comment mettre `sox`, je ne l'ai pas dans les choix dans Settings --> Voice recognition...

et j'ai `Aucun fichier ou dossier de ce type` en retour de `more ~./asoundrc`

**Comment by Oliv4945** [comment]
Ok, que donne `ln -l tts_engines/google` ainsi que `more tts_engines/google/main.sh` ?

Pour `command_stt` c'est une erreur de ma part, essaie Bing ;) . Snowboy ne peut faire que de la détection de mots clefs, pas de reconnaissance de phrase.

Concernant le asoundrc c'était `more ~./.asoundrc` mais ce n'est plus la peine

**Comment by tutsisback** [comment]
Oliv4945,

Quand je tape `ln -L tts_engines/google` j'obtiens `▒▒tts_engines/google▒▒▒: lien direct non permis pour un r▒pertoire`

Pour `more tts_engines/google/main.sh` : 
```
#!/bin/bash
rawurlencode() { # here because used in TTS
    local string="${1}"
    local strlen=${#string}
    local encoded=""

    for (( pos=0 ; pos<strlen ; pos++ )); do
        c=${string:$pos:1}
        case "$c" in
            [-_.~a-zA-Z0-9] ) o="${c}" ;;
            * )               printf -v o '%%%02x' "'$c"
        esac
        encoded+="${o}"
    done
    echo "${encoded}"
}

google_TTS () { # TTS () {} Speaks text $1
    [ -n "$1" ] || return #591
    local audio_file="$jv_cache_folder/$(jv_sanitize "$1" _).mp3"
    if [ ! -f "$audio_file" ]; then
        $verbose && printf "$_gray" # output in verbose mode will be displayed i
n gray
        wget $($verbose || echo -q) -U Mozilla -O $audio_file "http://translate.google.com/translate_tts?tl=${language:0:2}&client=tw-ob&ie=UTF-8&q=$1"
        $verbose && printf "$_reset"
    else
        $verbose && jv_debug "DEBUG: using cache $audio_file"
    fi
    jv_play "$audio_file"
}
```
Et j'ai mis Bing à la place de Snowboy.

**Comment by Oliv4945** [comment]
Arf, je vais essayer de répondre plus posément pour faire moins de bêtises :)
`ls -l tts_engines/google`

Mais je pense avoir trouvé le soucis. Peux-tu essayer d'éditer [`jarvis.sh`](https://github.com/alexylem/jarvis/blob/4cdd001130e8c07607939a68ed29aaaa4b6ae0b2/jarvis.sh#L275) et remplacer les lignes 275 à 300 inclues par le code ci-dessous ?
Si ça fonctionne je modifie pour tout le monde

```
if [ -n "$rec_hw" ]; then
    source stt_engines/$trigger_stt/main.sh || {
        jv_error "ERROR: invalid hotword recognition engine ($trigger_stt)"
        jv_warning "HELP: jarvis > Settings > Voice Reco > Reco of hotword"
        jv_exit 1
    }
    source stt_engines/$command_stt/main.sh || {
        jv_error "ERROR: invalid command recognition engine ($trigger_stt)"
        jv_warning "HELP: jarvis > Settings > Voice Reco > Reco of commands"
        jv_exit 1
    }
else
    quiet=true
    jv_warning "No speaker configured, forcing mute mode"
fi
if [ -n "$play_hw" ]; then
    source recorders/$recorder/main.sh
    source tts_engines/$tts_engine/main.sh || {
        jv_error "ERROR: invalid speech synthesis engine ($trigger_stt)"
        jv_warning "HELP: jarvis > Settings > Speech synthesis > Engine"
        jv_exit 1
    }
else
    keyboard=true
    jv_warning "No mic configured, forcing keyboard mode"
fi
```

**Comment by tutsisback** [comment]
Je me disais que la commande `ln` était bizarre :).

J'ai remplacé le code dans jarvis.sh et maintenant quand je lance jarvis j'ai ceci indéfiniment dans la console : 
```
No speaker configured, forcing mute mode
Jarvis: Bonjour
User defined commands:
*AIDE*                  *BONJOUR*|*SALUT*       *COMMENT*APPELLE*
*MERCI*                 *AU REVOIR*|*BYE*       ANNULE*|TERMINE*
ENCORE*                 *TEST*                  *VERSION*
*REPETE (*) ET (*)      *CA VA*                 >*OUI*
>*NON*|*PAS*
Jarvis: Waiting to hear 'Jarvis'
Pierre: /usr/local/bin/jarvis: ligne 467: bing_STT : commande introuvable
/usr/local/bin/jarvis: ligne 467: bing_STT : commande introuvable
/usr/local/bin/jarvis: ligne 467: bing_STT : commande introuvable

Jarvis: Waiting to hear 'Jarvis'
Pierre: /usr/local/bin/jarvis: ligne 467: bing_STT : commande introuvable
/usr/local/bin/jarvis: ligne 467: bing_STT : commande introuvable
/usr/local/bin/jarvis: ligne 467: bing_STT : commande introuvable

Jarvis: Waiting to hear 'Jarvis'
Pierre: /usr/local/bin/jarvis: ligne 467: bing_STT : commande introuvable
/usr/local/bin/jarvis: ligne 467: bing_STT : commande introuvable
/usr/local/bin/jarvis: ligne 467: bing_STT : commande introuvable

Jarvis: Waiting to hear 'Jarvis'
Pierre: /usr/local/bin/jarvis: ligne 467: bing_STT : commande introuvable
/usr/local/bin/jarvis: ligne 467: bing_STT : commande introuvable
/usr/local/bin/jarvis: ligne 467: bing_STT : commande introuvable
```

**Comment by Oliv4945** [comment]
On avance, est-ce que tu as bien entendu le "Hello" dans les haut parleurs ?
Est-ce possible d'avoir le log complet (avec le début) ?

**Comment by tutsisback** [comment]
Non je n'entends pas "Hello", j'entends des bruits d'erreur en boucle.
Voici le log : 
```
pi@tutspi:~ $ jarvis -nv

------------ Config ------------
jv_branch            master 
jv_version            
jv_arch              armv7l 
jv_os_name           raspbian 
jv_os_version        8 
language             fr_FR 
play_hw              hw:0,0 
rec_hw                
speaker              ALSA 
microphone           Default 
recorder             sox 
trigger_stt          bing 
command_stt          bing 
tts_engine           google 
--------------------------------

No speaker configured, forcing mute mode
DEBUG: program_startup hook
DEBUG: start_speaking hook
Jarvis: Bonjour
DEBUG: stop_speaking hook
User defined commands:
*AIDE*			*BONJOUR*|*SALUT*	*COMMENT*APPELLE*
*MERCI*			*AU REVOIR*|*BYE*	ANNULE*|TERMINE*
ENCORE*			*TEST*			*VERSION*
*REPETE (*) ET (*)	*CA VA*			>*OUI*
>*NON*|*PAS*
Jarvis: Waiting to hear 'Jarvis'
Pierre: (listening...)
/usr/local/bin/jarvis: ligne 467: bing_STT : commande introuvable
(listening...)
/usr/local/bin/jarvis: ligne 467: bing_STT : commande introuvable
(listening...)
/usr/local/bin/jarvis: ligne 467: bing_STT : commande introuvable
DEBUG: 3 attempts failed, end of conversation

DEBUG: exiting_cmd hook
Jarvis: Waiting to hear 'Jarvis'
Pierre: (listening...)
/usr/local/bin/jarvis: ligne 467: bing_STT : commande introuvable
(listening...)
/usr/local/bin/jarvis: ligne 467: bing_STT : commande introuvable
(listening...)
/usr/local/bin/jarvis: ligne 467: bing_STT : commande introuvable
DEBUG: 3 attempts failed, end of conversation

DEBUG: exiting_cmd hook
Jarvis: Waiting to hear 'Jarvis'
Pierre: (listening...)
/usr/local/bin/jarvis: ligne 467: bing_STT : commande introuvable
(listening...)
/usr/local/bin/jarvis: ligne 467: bing_STT : commande introuvable
(listening...)
/usr/local/bin/jarvis: ligne 467: bing_STT : commande introuvable
DEBUG: 3 attempts failed, end of conversation

^C
DEBUG: program_exit hook
```

**Comment by Oliv4945** [comment]
Ok, on va chercher après pourquoi il ne passe pas en mode keyboard, surement ma modif. D'abord...pourquoi tu n'entends rien. Tu devrais avoir "Bonjour" au démarrage.
Que donne `play /dev/shm/bonjour.mp3` ?
Quand tu as fait le wizard tu t'entendais bien ?

**Comment by tutsisback** [comment]
Oui je n'entends rien même au démarrage.
Par contre lorsque je fais l'installation par le wizard j'entends bien les bruits d'applaudissement.

et la commande play me retourne ceci : 
```
pi@tutspi:~ $ play /dev/shm/bonjour.mp3
play FAIL formats: can't open input file `/dev/shm/bonjour.mp3': No such file or directory

```

**Comment by Oliv4945** [comment]
Ahh, décidément je viens de voir le soucis. Encore de ma faute.
Vivement qu'Alexis revienne :-)

Du coup les modifications que je t'ai demandées ne sont pas bonnes. Cette fois j'espère que ça va le faire:

Peux-tu essayer d'éditer [`jarvis.sh`](https://github.com/alexylem/jarvis/blob/4cdd001130e8c07607939a68ed29aaaa4b6ae0b2/jarvis.sh#L275) et remplacer les lignes 275 à 300 inclues par le code ci-dessous ?
Si ça fonctionne je modifie pour tout le monde

```
if [ -n "$play_hw" ]; then
    source tts_engines/$tts_engine/main.sh || {
        jv_error "ERROR: invalid speech synthesis engine ($trigger_stt)"
        jv_warning "HELP: jarvis > Settings > Speech synthesis > Engine"
        jv_exit 1
    }
else
    quiet=true
    jv_warning "No speaker configured, forcing mute mode"
fi
if [ -n "$rec_hw" ]; then
    source recorders/$recorder/main.sh
    source stt_engines/$trigger_stt/main.sh || {
        jv_error "ERROR: invalid hotword recognition engine ($trigger_stt)"
        jv_warning "HELP: jarvis > Settings > Voice Reco > Reco of hotword"
        jv_exit 1
    }
    source stt_engines/$command_stt/main.sh || {
        jv_error "ERROR: invalid command recognition engine ($trigger_stt)"
        jv_warning "HELP: jarvis > Settings > Voice Reco > Reco of commands"
        jv_exit 1
    }
else
    keyboard=true
    jv_warning "No mic configured, forcing keyboard mode"
fi
```

**Comment by tutsisback** [comment]
ça y est ça fonctionne !
Merci Oliv4945 !

Par contre il me reste un petit souci avec les accents : 
```
No mic configured, forcing keyboard mode
Jarvis: Bonjour
User defined commands:
*AIDE*			*BONJOUR*|*SALUT*	*COMMENT*APPELLE*
*MERCI*			*AU REVOIR*|*BYE*	ANNULE*|TERMINE*
ENCORE*			*TEST*			*VERSION*
*REPETE (*) ET (*)	*CA VA*			>*OUI*
>*NON*|*PAS*
Pierre: *ca va*
Jarvis: TrÃ¨s bien et toi Ã§a va?
iconv: séquence d'échappement non permise à la position 2
*OUI*			*NON*|*PAS*
Pierre: 
```

**Comment by YoyoAitw** [comment]
bonjour, 
j'avais le même problème, 
je viens de faire la modif, ca à l'air de marcher..
merci

@tutsisback 
pour les accents, j'ai vu un autre post sur github, il faut modifier la langue dans le systeme raspbian, mais là je le retrouve plus..

**Comment by Oliv4945** [comment]
Closed by #744
