### ISSUE TITLE
Plugin jeedom

### ISSUE THREAD

**Issue by Latlantis** [alexylem/jarvis#657]
Bonjour,
alors que ce plugin a toujours fonctionné, voilà que soudainement il ne fonctionne plus et ce pour chaque intération demandée j'ai ce message retourné par Jarvis: "Vous n'etes pas autorisé à effectuer cette action". C'est étrange l'IP est la clé API de Jeedom ont bien été configuré dans le plugin mais rien n'y fait. Pouvez-vous me donner une piste où chercher svp?

Merci

**Comment by wikijm** [comment]
Bonjour,

Merci de créer une issue sur le repository du plugin :
https://github.com/alexylem/jarvis-jeedom
