### ISSUE TITLE
Pré-requis à l'installation de Jarvis

### ISSUE THREAD

**Issue by Didier3L** [alexylem/jarvis#658]
Bonjour
dans la vidéo de l'installation de Jarvis, on voit l'utilisateur pi@raspberrypi:~ $
Cet utilisateur doit certainement avoir des privilèges élevés comme super-administrateur comme ceux de Root.
Pourrais tu nous indiquer la procédure pour que l'utilisateur puisse réaliser l'installation sans problème ?
exécution de sudo, écriture des fichiers, etc ...

**Comment by wikijm** [comment]
Tout est procéduré, il suffit de suivre toutes étapes décrites à partir d'ici :
https://openjarvis.com/content/prerequisites

**Comment by Didier3L** [comment]
J'ai vu l'article, mais on ne parle pas des privilèges de l'utilisateur non root ...

**Comment by wikijm** [comment]
Les procédures sont faites pour Raspbian Lite et Full, avec lesquelles viennent un compte par défaut, à savoir **pi**.
Quand cela est nécessaire, il faut utiliser la commande `sudo` afin d'obtenir les droits suffisants.
Par conséquent, nul besoin d'utiliser le compte **root**.

**Comment by Didier3L** [comment]
J'utilise une image Debian Docker 
[](https://hub.docker.com/_/debian/)
j'ai créé un utilisateur didier
J'ai modifié le fichier /etc/sudoers

> User privilege specification                                                                               
> root    ALL=(ALL:ALL) ALL                                                                                    
> didier  ALL=(ALL) ALL                                                                                        
>                                                                                                              
> # Allow members of group sudo to execute any command                                                         
> %sudo   ALL=(ALL:ALL) ALL                                                                                    

-
> didier@debian1:/$ su didier
> Password:
> didier@debian1:/$ git clone https://github.com/alexylem/jarvis.git
> fatal: could not create work tree dir 'jarvis': Permission denied

**Comment by Oliv4945** [comment]
Jarvis contient déjà les commandes sudo où il faut. À quoi sert `su didier` vu que tu est déjà loggé en Didier ?
Que donne le résultat de `ls -al` et `pwd` à l'endroit où tu essaie de cloner Jarvis ? Car là on dirait que tu n'as pas les droits sur le répertoire, donc avant même d'exécuter l'installation de Jarvis

**Comment by Didier3L** [comment]
> didier@debian:/jarvis$ ls -all
> total 116
> drwxr-xr-x 14 root root  4096 Jul  1 15:25 .  
>   
> drwxr-xr-x 30 root root  4096 Jul  1 15:25 ..   
> drwxr-xr-x  8 root root  4096 Jul  1 15:25 .git 
> -rw-r--r--  1 root root   595 Jul  1 15:25 .gitignore
> -rw-r--r--  1 root root  4215 Jul  1 15:25 CHANGELOG.md      
> -rw-r--r--  1 root root   118 Jul  1 15:25 CONTRIBUTING.md   
> -rw-r--r--  1 root root   619 Jul  1 15:25 ISSUE_TEMPLATE.md 
> -rw-r--r--  1 root root  1082 Jul  1 15:25 LICENSE.md
> -rw-r--r--  1 root root  2983 Jul  1 15:25 README.md 
> drwxr-xr-x  2 root root  4096 Jul  1 15:25 config    
> drwxr-xr-x  2 root root  4096 Jul  1 15:25 defaults  
> drwxr-xr-x  2 root root  4096 Jul  1 15:25 docs 
> drwxr-xr-x  2 root root  4096 Jul  1 15:25 hooks
> drwxr-xr-x  5 root root  4096 Jul  1 15:25 imgs 
> -rwxr-xr-x  1 root root 20081 Jul  1 15:25 jarvis.sh 
> drwxr-xr-x  4 root root  4096 Jul  1 15:25 recorders 
> drwxr-xr-x  2 root root  4096 Jul  1 15:25 sounds    
> drwxr-xr-x  7 root root  4096 Jul  1 15:25 stt_engines       
> drwxr-xr-x  2 root root  4096 Jul  1 15:25 test 
> drwxr-xr-x  7 root root  4096 Jul  1 15:25 tts_engines       
> -rwxr-xr-x  1 root root  1199 Jul  1 15:25 uninstall.sh      
> -rw-r--r--  1 root root   521 Jul  1 15:25 update.sh 
> drwxr-xr-x  2 root root  4096 Jul  1 15:25 utils
> -rw-r--r--  1 root root     9 Jul  1 15:25 version.txt 
>

**Comment by Didier3L** [comment]
didier@debian:/jarvis$ pwd                                  
/jarvis                                                                                                      
didier@debian:/jarvis$

**Comment by Oliv4945** [comment]
C'est bien ça ton soucis : tu n'as pas les droits là où tu t'es placé (tes fichier appartiennent à root), tu as du faire le git clone en tant que root ou avec sudo. Plusieurs solutions, si tu as créé ton utilisateur avec les bonnes options tu as un repertoire /home/didier où ça doit pouvoir fonctionner.
Sinon tu peux donner les droits à ton utilisateur `didier` sur tes fichiers actuels avec `chown -R didier:didier /jarvis`
