### ISSUE TITLE
Auto-detect missing locales & install them if needed (like with raspi-config)

### ISSUE THREAD

**Issue by LengZai** [alexylem/jarvis#66]
### Description

Hi,

I use the latest version of Raspbian Jessie in English
If you launch Jarvis in French for the first time and you ask him the date/time. He will say something like.. Il est Sunday, July 24 2016....

To let Jarvis to speak your language, you need to add language pack through raspi-config

```
$ sudo raspi-config
Generating locales (this might take a while)...
  en_GB.UTF-8... done
  fr_FR.UTF-8... done
Generation complete.
```

Then in the jarvis-commands
`*QUEL JOUR*==say "nous sommes le`LC_TIME='fr_FR.UTF-8' date +"%A %d %h %Y"`"`

@Alexylem, I suppose it's possible to dynamically set this during the setup like you did for $username

**Comment by alexylem** [comment]
Yes you are right, many french native people just forget to `raspi-config` to install locales. I'll check if there is a way to auto-detect it's not installed and will propose to do it automatically.

**Comment by alexylem** [comment]
I'm thinking on checking:
```
env | grep LANG
```
and advise, depending on chosen language in Jarvis, to:
```
sudo raspi-config
```
It's kind of obvious though... what do you guys think?

**Comment by alexylem** [comment]
@LengZai Do you think Jarvis should recommend to `sudo raspi-config` when language selected is not the main locale?
Please let me know and I'll implement if you think it makes sense, sounds too obvious to me to code it, but may not be that obvious to others...

**Comment by LengZai** [comment]
Well, I like to set all my system in English, it's not a priority and you can just put a note during Jarvis setup wizard to let the user know that if he needs a local language.. please use sudo raspi-config then.

**Comment by alexylem** [comment]
Okay I'll do that, hopefully no one will install jarvis on a non-raspberry-pi linux machine and complain because `raspi-config: command not found` 😄

**Comment by wikijm** [comment]
@LengZai I closed this issue due to the fact that this issue was added to 'To be discussed' in 'Jarvis Core' project.

**Comment by alexylem** [comment]
@wikijm I prefer to keep tickets open until they are implemented if you agree.
However I think we should close because the time / dates are now managed via the time plugin 😄

**Comment by wikijm** [comment]
Understood.
