### ISSUE TITLE
Reprise du plugin "Liste des courses" intialement crée par @tchoul

### ISSUE THREAD

**Issue by Jean-Bernard-Hallez** [alexylem/jarvis#662]
Demande autorisation de modifier le plugin de @tchoul, je ne sais pas si il est encore actif...
C'est sur ce plugin:
https://www.openjarvis.com/plugins/jarvis-liste-des-courses

**Comment by wikijm** [comment]
Bonjour @Jean-Bernard-Hallez,

La fonctionnalité Issues n'est pas active sur le repo de @tchoul, ce qui ne te permets en effet pas de le contacter.

En revanche, tu peux toujours lui passer une pull request et voir si tu as une réponse.
Tu peux également contacter @godinperson avec qui le plugin semble avoir été écrit (voir https://github.com/tchoul/jarvis-liste-des-courses et https://www.openjarvis.com/plugins/jarvis-liste-des-courses).

Si tu n'en a pas dans un délai convenable, il serait intéressant que tu en fasse un fork et le soumette ensuite à @alexylem pour intégration.

**Comment by Jean-Bernard-Hallez** [comment]
Je n'arrive pas à faire le pull request....

**Comment by wikijm** [comment]
Qu'est ce qui te pose problème ?
Quelle méthode emploie-tu ?

**Comment by Jean-Bernard-Hallez** [comment]
je vais sur le repo: https://github.com/tchoul/jarvis-liste-des-courses
puis je clique sur Clone ou Download afin de téléchager l'original qui s'ouvre avec GitHub.
Je fais mes modifs
Et là....
je clique sur New pull request puis... puis... je n'y arrive plus...
en fait quand le veux renvoyer le paquet il me dit que je n'ai pas l'accord...

**Comment by wikijm** [comment]
Pour répondre à ton besoin j'ai :

1. Crée un nouveau repo local sur mon poste Windows
2. Publié ce repo sur GitHub
3. Transferé sa propriété sur le compte GitHub @Jean-Bernard-Hallez

**Comment by Jean-Bernard-Hallez** [comment]
Cela a toujours fonctionné... je viens de faire encore un test... jusque là Ok...
![image](https://user-images.githubusercontent.com/23117522/27899218-98416ab0-6229-11e7-8ddd-66f92e7ae198.png)
![image](https://user-images.githubusercontent.com/23117522/27899221-9d078bec-6229-11e7-8fd1-22619c42762b.png)

**Comment by wikijm** [comment]
Si possible, fais une capture d'écran vidéo et partage-là.

**Comment by wikijm** [comment]
http://www.screentogif.com/ afin d'intégrer facilement un GIF dans l'issue.

**Comment by Jean-Bernard-Hallez** [comment]
Ok le New pull request...  je cloture en attendant pour éviter d'avoir trop d'issues...
