### ISSUE TITLE
pas de reconnaissance de hotword

### ISSUE THREAD

**Issue by SmallLeandre** [alexylem/jarvis#663]
Bonjour,
Tout d'abord, je souhaite remercier et féliciter l'ensemble de l'équipe qui a développé cette appli.
j'utilise un rapsberry B+ et viens d'installer openjarvis.
J'ai un microphone de type Andoer Omni-Directional.

Lors de la configuration, le micro est bien reconnu et lorsque je reviens dans le menu setting /audio, j'entends parfaitement les mots prononcés dans le micro.

Ne voulant pas utiliser le mode "on line", j'ai configuré Jarvis en langue GB et comme STT, le couple SNOWBOY/PocketSphinx.

Mon problème est que le hotword "Snowboy" n'est jamais reconnu.
En lançant Jarvis en mode debug, voici le texte que j'obtiens.

snowboy: Waiting to hear 'snowboy'
caramel: (listening...)
DEBUG: models=snowboy
INFO:snowboy:Ticks: [2, 20, 5, -1]

J'ai vérifié qque la version utilisée est bien la dernière version.
je ne sais plus trop quoi faire pour poursuivre mon investigation.

Serait-il possible d'avoir de l'aide svp?
Cordialement,
Thierry

**Comment by Oliv4945** [comment]
Bonsoir,

Pourquoi avoir mis en langue Anglaise ? Snowboy fonctionne avec les mots que tu as énoncé donc tu n'as pas besoin de changer de langue. Concernant pocketSphink il y a un dictionnaire de phonèmes, donc c'est même mieux de laisser Français car les Anglais utilisent des mots... Anglais ;-)
Est-ce que tu peux essayer de le configurer pour utiliser Bing pour le hotword et la reconnaissance, le lancer un mode verbose (jarvis -nv) le temps de voir d'où ça vient ?

**Comment by SmallLeandre** [comment]
Bonsoir,
j'ai mis la langue anglaise car sur le site d'openjarvis, il est indiqué que pocketsphinxx ne fonctionne qu'en langue anglaise.
je viens de remettre en français.
Voilà ce que me donnent les traces de jarvis -nv avec Bing
 rec -V1 -q -r 16000 -c 1 -b 16 -e signed-integer --endian little /dev/shm/jarvis-record.wav gain -5 silence 1 0.1 6.1% 1 0.5 6.1% pad 0.5 0.5 trim 0 5
DEBUG: speech duration was 50 (10 = 1 sec)
DEBUG: too long for a trigger (min 0.5 max 1.5 sec), ignoring...
 rec -V1 -q -r 16000 -c 1 -b 16 -e signed-integer --endian little /dev/shm/jarvis-record.wav gain -5 silence 1 0.1 6.1% 1 0.5 6.1% pad 0.5 0.5 trim 0 5
DEBUG: speech duration was 50 (10 = 1 sec)
DEBUG: too long for a trigger (min 0.5 max 1.5 sec), ignoring...
 rec -V1 -q -r 16000 -c 1 -b 16 -e signed-integer --endian little /dev/shm/jarvis-record.wav gain -5 silence 1 0.1 6.1% 1 0.5 6.1% pad 0.5 0.5 trim 0 5

Merci pour ton aide

**Comment by SmallLeandre** [comment]
J'ai modifiier le code pyhton pour que la commande "rec" me soit affichée en mode début.
Voilà ce que cela m'a sorti : rec -q -r 16000 -c 1 -b 16 -e signed-integer --endian little -t wav - gain -5
Du coup, j'ai lancé cette commande dans un terminal et boum!
Je crois que c'est un bug.
Désolé

**Comment by SmallLeandre** [comment]
Faux espoirs...
ça ne marche pas mieux...

**Comment by SmallLeandre** [comment]
En plus clair, j'ai modifié le code python pour que la commande passe, entre autre j'ai enlevé le -q.
Le résultat reste identique, pas de détection de hotword.

**Comment by wikijm** [comment]
Est-ce que le training du hotword a bien fonctionné ? Tu as pu enregistrer et valider les 3 essais ?

**Comment by SmallLeandre** [comment]
J'étais parti au plus simple avec un hotword universel. Du coup, je n'ai pas encore essayé de personnalisé le mot.
J'essaye ce soir et te tiens au courant.
Bonne journée

**Comment by Oliv4945** [comment]
@SmallLeandre 
>Voilà ce que me donnent les traces de jarvis -nv avec Bing

D'une manière générale mettre tout le log, à partir du moment où tu lances Jarvis, ça permet de connaître tes paramètres. Est-ce que tu t'es entendu en echo à ce que disais ? Si non c'est un soucis de micro, le gain à -5 peut-être ?

>rec -q -r 16000 -c 1 -b 16 -e signed-integer --endian little -t wav - gain -5

Bien vu, mais il faut rajouter le nom du fichier pour l'utiliser en dehors de Jarvis. Est-ce que `rec -q -r 16000 -c 1 -b 16 -e signed-integer --endian little -t wav - gain -5 test.wav` puis `play test.wav` tu t'entends ? ça confirmerai le soucis de micro

> J'étais parti au plus simple avec un hotword universel.

Selon ton accent Anglais, ce n'est pas le bon plan ;)

**Comment by SmallLeandre** [comment]
voici donc les retours : 
1. j'ai bien réussi à creer un hotword (caramel) à l'aide de l'interface jarvis. Il est à noter que j'ai du m'y reprendre à plusieurs fois et contrôler les fichiers audio car parfois l'enregistrement avait été coupé trop tôt, parfois trop tard. 
2. je me suis aperçu que mon problème venait en fait de la sensibilité que j'avais réglé trop fort (0.8); Je pensais avoir beaucoup de fausses alarmes mais au moins des résultats. Dans les faits, ce réglage ne sortait rien du tout, pourquoi? 
3. je n'ai pas compris comment marche "check ticks". Je vois bien que l'objectif est de limiter les fausses alarmes mais je n'arrive pas à le maîtriser.
4. avec une sensibilité à 0.45 et sans l'option "check ticks", ça à l'air de fonctionner même avec la tv en bruit de fond.
Du coup, je continue mon apprentissage et passe à la problématique pocketsphinx.
Merci!

**Comment by SmallLeandre** [comment]
A un moment, tu appelais à contribuer au hotword Jarvis.
Est-ce qu'en utilisant l'interface openjarvis et non pas l'interface du site snwoboy, cela permettra de répondre à ton appel?

**Comment by wikijm** [comment]
@SmallLeandre Je pense que oui. Les avantages à trainer ton hotword dans OpenJarvis sont :
- De prendre en compte ta voix
- De prendre en compte ton micro
- De valider le bon fonctionnement de ton installation Snowboy avant de l'utiliser dans Jarvis
- D'améliorer la reconnaissance du hotword choisi pour l'ensemble des utilisateurs Snowboy

**Comment by SmallLeandre** [comment]
ok. je vais entrainer le hotword "jarvis".
peux tu me dire comment marche la fonction "ticks"?

**Comment by Oliv4945** [comment]
D'après le [code](https://github.com/alexylem/jarvis/blob/c15691213e403c3319d6c81d94d1d468d7f81951/stt_engines/snowboy/main.py#L51):

```
Trigger ticks:
+#   a tick is the sleep time of snowboy - argument of start()
+#   [0] ticks_silence_before_detect:
+#       min silence ticks before detection
+#   [1] param ticks_voice_before_detect:
+#       max voice ticks before detection
+#   [2] ticks_voice_after_detect:
+#       max voice ticks after detection
+#   [3] ticks_silence_after_detect:
+#       min silence ticks after detection
```
