### ISSUE TITLE
Configuration micro

### ISSUE THREAD

**Issue by Didier3L** [alexylem/jarvis#665]
Bonjour
Lors de la configuration, partie micro, le système me propose cela : 

> pi@raspberrypi:~/jarvis $ ./jarvis.sh
> Notice: you can use 'jarvis' instead of './jarvis.sh'
> Checking updates for jarvis...Up-to-date
> ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM
> rec FAIL formats: can't open input  `default': snd_pcm_open error: No such file or directory
> Selection of the microphone device
> **** Liste des Périphériques Matériels CAPTURE ****
> carte 1: Microphone [Logitech USB Microphone], périphérique 0: USB Audio [USB Audio]
>   Sous-périphériques: 1/1
>   Sous-périphérique #0: subdevice #0
> Indicate the card # to use [0-9]: 1
> Indicate the device # to use [0-9]: 1
> 

J'ai saisi 1 pour les deux valeurs demandés mais le test du micro n'est pas proposé et je retourne à chaque fois sur ce menu ?

**Comment by Oliv4945** [comment]
Bonsoir,

Il faut mettre 1, puis 0. pour "Carte 1", puis "sous-périphérique #0"
