### ISSUE TITLE
Voice recognition

### ISSUE THREAD

**Issue by bowlingdude2** [alexylem/jarvis#667]
### Description Jarvis does not seem to recognize my voice he says hello but whenever I say something Jarvis doesn't respond 

Français and English are allowed.
Detailed description of your problem.
In case of feature request, please provide justification & example of usage.

### Logs
```shell
<PASTE HERE> full content of the terminal with Jarvis in troubleshooting mode
(keep triple quotes above and below to preserve formatting) 
```
Alternatively attach a terminal session recording using asciinema:
```shell
sudo apt-get install -y asciinema && asciinema rec # start session recording
./jarvish.sh -nv # start jarvis directly in troubleshooting mode
Ctrl+D # stop recording
y # yes to upload and get URL to paste here
```

**Comment by Oliv4945** [comment]
Please read the content of your issue and send a log

**Comment by wikijm** [comment]
Closing of the ticket until a valid answer from the applicant is obtained.
