### ISSUE TITLE
Problèmes multiples avec Jarvis (plusieurs se reconnaîtrons je pense)

### ISSUE THREAD

**Issue by seboss1111** [alexylem/jarvis#668]
Salut tout le monde, déjà merci beaucoup pour la création de Jarvis et son développement continu mais surtout de l'aide que vous allez m'apporter je l'espère..  :)
J'ai essayé d'être très clair et rapide dans les explications ;)
J'ai plusieurs problèmes (j'utilise Jarvis sur ma raspberry pi 3) : 

1- J'aimerais tellement pouvoir utiliser la voix qui ressemble à Jarvis dans iron man et je sais qu'elle 
    existe (voir vidéo) cependant je n'ai aucun choix de voix dans le menu speech synthesis en essayant 
    chaque moteur.. est-ce normal?
    vidéo : https://www.youtube.com/watch?v=DGnuBOzSJig&t=396s

2- Je vais bientôt recevoir le petit micro qui a une portée de 5 mètre mais pour le moment je ne peux 
     connecter Jarvis qu'aux enceintes ou en API (voir problème API en 3) . 
     Dès que je quitte et que je relance Jarvis impossible d'entendre la voix sur mes enceintes et je suis 
     obliger de faire un STEP-BY-STEP pour pouvoir utiliser mes enceintes (les options audio ne changent 
     rien à part le step-by step). Vous remarquerez d'ailleurs que j'ai du faire un step by step au début..

3- Je ne peux pas utiliser les fonctions en API donc via l'url ou via l'application sachant que j'ai bien 
     paramètré les deux (appli android et depuis l'ordi via navigateur google) .. ça me renvois une erreur. 
     En bref l'API marche une fois sur dix et en plus ça a l'air limité à deux mots max ou je me trompe? 
     exemple :  je dis "Allume télé" sur mon ordi en API puis il enregistre juste "télé" donc évidement l 
     l'ordre ne s'exécute pas alors que dans l'invite de commande quand je tape Allume la télé ça marche..

En vue de régler tous ces problèmes je vous mets ce qui se passe au démarrage de Jarvis et lorsque que je lance des commande vocales sur l'API. Vous pourrez remarquer d'ailleurs que la dernière commande vocal lancée a marchée.. tout n'est pas perdu :P 

```
pi@raspberrypi:~/jarvis $ jarvis
sudo: rfkill: command not found
Checking updates for jarvis...Up-to-date

sounds/applause.wav:

 File Size: 463k      Bit Rate: 1.41M
  Encoding: Signed PCM
  Channels: 2 @ 16-bit
Samplerate: 44100Hz
Replaygain: off
  Duration: 00:00:02.62

In:100%  00:00:02.62 [00:00:00.00] Out:116k  [      |      ] Hd:0.0 Clip:0
Done.
Checking updates for jarvis...Up-to-date

sounds/applause.wav:

 File Size: 463k      Bit Rate: 1.41M
  Encoding: Signed PCM
  Channels: 2 @ 16-bit
Samplerate: 44100Hz
Replaygain: off
  Duration: 00:00:02.62

In:100%  00:00:02.62 [00:00:00.00] Out:116k  [      |      ] Hd:0.0 Clip:0
Done.
No mic configured, forcing keyboard mode
Starting RestAPI server on http://192.168.1.18:8080
cp: « /home/pi/jarvis/plugins_enabled/jarvis-face/faces/cortana/abashed.gif » et « /home/pi/jarvis/plugins_enabled/jarvis-face/faces/cortana/abashed.gif » identifient le même fichier
cp: « /home/pi/jarvis/plugins_enabled/jarvis-face/faces/cortana/exit » et « /home/pi/jarvis/plugins_enabled/jarvis-face/faces/cortana/exit » identifient le même fichier
cp: « /home/pi/jarvis/plugins_enabled/jarvis-face/faces/cortana/happy » et « /home/pi/jarvis/plugins_enabled/jarvis-face/faces/cortana/happy » identifient le même fichier
cp: « /home/pi/jarvis/plugins_enabled/jarvis-face/faces/cortana/listening » et « /home/pi/jarvis/plugins_enabled/jarvis-face/faces/cortana/listening » identifient le même fichier
cp: « /home/pi/jarvis/plugins_enabled/jarvis-face/faces/cortana/needmore.gif » et « /home/pi/jarvis/plugins_enabled/jarvis-face/faces/cortana/needmore.gif » identifient le même fichier
cp: « /home/pi/jarvis/plugins_enabled/jarvis-face/faces/cortana/neutral » et « /home/pi/jarvis/plugins_enabled/jarvis-face/faces/cortana/neutral » identifient le même fichier
cp: « /home/pi/jarvis/plugins_enabled/jarvis-face/faces/cortana/sensitive.gif » et « /home/pi/jarvis/plugins_enabled/jarvis-face/faces/cortana/sensitive.gif » identifient le même fichier
cp: « /home/pi/jarvis/plugins_enabled/jarvis-face/faces/cortana/sleeping » et « /home/pi/jarvis/plugins_enabled/jarvis-face/faces/cortana/sleeping » identifient le même fichier
cp: « /home/pi/jarvis/plugins_enabled/jarvis-face/faces/cortana/speaking » et « /home/pi/jarvis/plugins_enabled/jarvis-face/faces/cortana/speaking » identifient le même fichier
cp: « /home/pi/jarvis/plugins_enabled/jarvis-face/faces/cortana/start » et « /home/pi/jarvis/plugins_enabled/jarvis-face/faces/cortana/start » identifient le même fichier
cp: « /home/pi/jarvis/plugins_enabled/jarvis-face/faces/cortana/thinking » et « /home/pi/jarvis/plugins_enabled/jarvis-face/faces/cortana/thinking » identifient le même fichier
cp: « /home/pi/jarvis/plugins_enabled/jarvis-face/faces/cortana/understood » et « /home/pi/jarvis/plugins_enabled/jarvis-face/faces/cortana/understood » identifient le même fichier
plugins_enabled/jarvis-music-player/functions.sh: ligne 12: jv_pg_mp_lang : commande introuvable

Failed in file ../src/lib/xmmstypes/value.c on  row 1861
Starting User Interface on http://192.168.1.18:8081
plugins_enabled/jarvis-xscreensaver/hooks/program_startup: ligne 1: xscreensaver-command : commande introuvable
Jarvis: Bonjour monsieur
User defined commands:
*ETEIND*TOI*MAINTENANT*                         *ETEIND*TOI*
>*RESTE*|*ANNULE*|*NE*E                         *REDEMARRE*
                                                *AIDE*
*BONJOUR*|*SALUT*|*HEY* *COMMENT*TU*APPELLE*    *COMMENT*JE*APPELLE*
*MERCI*                 *AU REVOIR*|*BYE*|*A PL *TERMINE*
*ENCORE*                *TEST*|*1 2 1 2*        *VERSION*
*REPETE (*) ET (*)                              *CA VA*
>*OUI*|*CA VA*          >*NON*                  >>*OUI*
>>*NON*                 *JARVIS*
*BONNE* *BLAGUE*        *MAUVAISE* *BLAGUE*
                                                *AS* *COMPTE* *FACEBOOK
*ES* *ROBOT*|*MACHINE*  *AS* *PETITE COPINE*|*P *ES* *BEAU*|*MIGNON*
*ME* *TROUVE BELLE*|*TR *JE* *SUIS* *FATIGU*    *ES* *AGAC*


*ETEIND*LA*TELE*                                *ALLUME*LA*TELE*
Commands from plugin jarvis-api:

Commands from plugin jarvis-ui:
*OUVR*INTERFACE*
Commands from plugin jarvis-fruitsetlegumessaison:
*FRUIT*SAISON*          *LEGUME*SAISON*         *QUEL*SAISON*
                        GOTOFINOK
Commands from plugin jarvis-blagues:
*RACONT*BLAGUE*         *REPETE*BLAGUE*         *RETIEN*BLAGUE*
*LI*BLAGUE*NUM* (*)     *COMBIEN*BLAGUE*
Commands from plugin jarvis-console:
*AFFICHE*CONSOLE*|*REVE
Commands from plugin jarvis-cestquand:
*PROCHAIN*EVENEMENT*|*P AVERTIRSILENCEEVENEMENT
*EST QUAN[^ ] (*)       *EST*JOUR*LE (*)        POURPLUGINPIRESCLAVE
Commands from plugin jarvis-lacitation:
*RAJOUTE*PROVERBE*|*RAJ >*                      >>*OUI*
>>*NON*                 *PROVERBE*|*CITATION*
Commands from plugin jarvis-ephemeride:
*FETE*JOUR*|*LA*SAINT*|
Commands from plugin jarvis-math:
*CALCUL* (*)
Commands from plugin jarvis-time:
*QUELLE HEURE*          *QUEL JOUR*
Commands from plugin jarvis-calendar:
*AJOUTE*EVENEMENT*      > (*)                   >> (*)
>>> (*)                 >>>> (*)                >>>>> (*)
>>>>>> (*)              >>>>>>> (*)             >>>>>>>> *OUI*
>>>>>>>> *NON*                                  *QUAND*EVENEMENT (*)
*EVENEMENT*JOUR*        *EVENEMENT*DEMAIN*      *PROCH*EVENEMENT*
Commands from plugin jarvis-gmail:
*MAIL*
Commands from plugin jarvis-music-player:

Commands from plugin jarvis-minuterie:
*EFFACE*MINUTE*         *MINUTE*                >(*)
Commands from plugin jarvis-kodi:
*CONTROLE*KODI|*CODI*|* >*VOLUME*FAIBLE*        >*VOLUME*NORMAL*
>*VOLUME*FORT*          >*VALIDE*               >*GAUCHE*
>*DROITE*               >*HAUT*                 >*BAS*
>*PAUSE*|*LIRE*|*REPREN >*ARRET*                >*RETOUR*
>*MENU*PRINCIPAL*       >*NON*MUET*             >*MUET*
>*AFFICHE*INFORMATION*F >*SOUS*TITRE*SUIVANT*   >*DESACTIVE*SOUS*TITRE*
>*ACTIVE*SOUS*TITRE*    >*PLEIN*ECRAN*          >*AFFICHE*LISTE*FILM*
>*AFFICHE*LISTE*MUSIQUE >*AFFICHE*LISTE*FAVORI* >*AFFICHE*LISTE*PHOTO*
>*AFFICHE*CODEC*VIDEO*  >*CACHE*CODEC*VIDEO*    >*MET*A*JOUR*MEDIATHEQU
>*NETTOYAGE*MEDIATHEQUE >*MET*A*JOUR*MEDIATHEQU >*NETTOYAGE*MEDIATHEQUE
>*AFFICHE*OSD*          >*CACHE*OSD*            >*PISTE*SUIVANTE*
>*PISTE*PRECEDENTE*     >*LANCE*FILM (*)        >*EXECUTE*EXTENSION (*)
>*LANCE*SERIE (*) SAISO >ENCORE*                >TERMINE*KODI|*CODI*|*C
*QUITTE*KODI|*CODI*|*CO *LANCE*KODI|*CODI*|*COD *RELANCE*KODI|*CODI*|*C
Commands from plugin jarvis_liveboxtv.git:

Commands from plugin jarvis_liveboxtv:
####################### #                       #######################
*allume la laveboxe*|*ét *coupe le son de la lav *remets le son de la la
*baisse le son de la la *monte le son de la lav *chaine suivante*
*chaine précédente*     *augmente le son de la  *mets la laveboxe sur p
*mets sur pause la lave *mets la lavebox en lec *mets en lecture la lav
*mets en avance rapide  *mets en retour rapide  *les infos du programme
*enléve les infos*      *laveboxe OK*           *laveboxe menu*
*laveboxe droit*        *laveboxe gauche*       *laveboxe haut*
*laveboxe bas*          *laveboxe retour*       *laveboxe v.o.d*
*mets la laveboxe en en
        ###############         #                       ###############
#Code: Touche           #512 : 0                #513 : 1
#514 : 2                #515 : 3                #516 : 4
#517 : 5                #518 : 6                #519 : 7
#520 : 8                #521 : 9
                                                        *TF1*
*France 2*              *France 3*              *Canal plus*
*France 5*              *M6*                    *Arte*
*D8*                    *W9*                    *TMC*
*NT1*                   *NRJ 12*                *LCP*
*La Chaine Parlementair *France 4*              *BFM TV*
*I-Télé*                        *D17*                   *Gulli*
*France O*              *HD1*                   *L équipe*
*6 ter*
Commands from plugin jarvis-chromium:
*GOOLGE*                *AFFICHE*MESSAGE*
Commands from plugin jarvis-livebox.git:

Commands from plugin jarvis-livebox:
*REDEMARE*              *REBOOT*                *NUMERO*
*RELANCE*INTERNET*      *PARTAGE*               *ACTIVER*WIFI*
*DESACTIVER*WIFI*       *ADRESSE*IP*            *MOT DE PASSE*LIVEBOX*
Commands from plugin jarvis-face:

Commands from plugin jarvis-wol:
*DEMARRE*PC (*)
Commands from plugin jarvis-xscreensaver:

Commands from plugin jarvis-leMonde:
*ACTUALITE*JOUR*        *ACTUALITE*BRIQUE (*)   *AJOUTE*FAVORI*BRIQUE (
*ENLEVE*FAVORI*BRIQUE ( *LIST*BRIQUE*FAVORI*    *LIST*BRIQUE*
Commands from plugin jarvis-wikipedia:
*DONNE*DEFINITION*DE*LA *DONNE*DEFINITION*DU (* *DONNE*DEFINITION*DUNE
*DONNE*DEFINITION*DUN ( *DONNE*DEFINITION*DE (*
*QUEST*CE*QUUN (*)      *QUEST*CE*QUUNE (*)     *QUEST*CE*QUE*LE (*)
*QUEST*CE*QUE*LA (*)
Commands from plugin jarvis-spell:
COMMENT*ECRIRE (*)      COMMENT*ECRIT*ON (*)    COMMENT*ON*ECRIT (*)
EPPELLE*MOI*LE*MOT (*)  EPPELLE*MOI (*)
Commands from plugin jarvis-weather-wunderground-fr:
*METEO*DEMAIN*          *METEO*
Commands from plugin jarvis-youtube-player:
*MUSIQUE*YOUTUBE*|*YOUT >(*)                    *YOUTUBE*VIDEO*|*VIDEO*
>(*)                    *ARRET*VIDEO*|*VIDEO*AR *ARRET*MUSIQUE*|*MUSIQU
Commands from plugin jarvis-deezer:
*LIST*PLAYLIST*DEEZER*  *PLAYLIST*DEEZER* (*)   *ARRETE*DEEZER*|*STOP*D
*PAUSE*DEEZER*          *LECTURE*DEEZER*        *VOLUME*DEFAU*DEEZER*
*VOLUME*FOND*DEEZER*    *VOLUME*DEEZER*A (*)
Sébastien: bonjour
Jarvis: Bonjour Sébastien
Sébastien: 192.168.1.14 - - [06/Jul/2017 20:58:53] "GET /?action=get_config&key= HTTP/1.1" 200 -
192.168.1.14 - - [06/Jul/2017 20:59:12] "POST / HTTP/1.1" 400 -
ERROR: No JSON object could be decoded
192.168.1.14 - - [06/Jul/2017 20:59:12] "GET /?action=get_config&key= HTTP/1.1" 200 -
bonjour
Jarvis: Bonjour Sébastien
192.168.1.14 - - [06/Jul/2017 20:59:51] "POST / HTTP/1.1" 400 -
ERROR: No JSON object could be decoded
192.168.1.14 - - [06/Jul/2017 20:59:51] "GET /?action=get_config&key= HTTP/1.1" 200 -
Sébastien: 192.168.1.14 - - [06/Jul/2017 20:59:52] "POST / HTTP/1.1" 400 -
ERROR: No JSON object could be decoded
192.168.1.14 - - [06/Jul/2017 20:59:52] "GET /?action=get_config&key= HTTP/1.1" 200 -
192.168.1.14 - - [06/Jul/2017 20:59:53] "POST / HTTP/1.1" 400 -
ERROR: No JSON object could be decoded
192.168.1.14 - - [06/Jul/2017 20:59:53] "GET /?action=get_config&key= HTTP/1.1" 200 -
192.168.1.14 - - [06/Jul/2017 20:59:54] "POST / HTTP/1.1" 400 -
ERROR: No JSON object could be decoded
192.168.1.14 - - [06/Jul/2017 20:59:55] "POST / HTTP/1.1" 400 -
ERROR: No JSON object could be decoded
192.168.1.14 - - [06/Jul/2017 20:59:55] "GET /?action=get_config&key= HTTP/1.1" 200 -
192.168.1.14 - - [06/Jul/2017 20:59:56] "POST / HTTP/1.1" 400 -
ERROR: No JSON object could be decoded
192.168.1.14 - - [06/Jul/2017 21:00:02] "GET /?action=get_config&key= HTTP/1.1" 200 -
192.168.1.14 - - [06/Jul/2017 21:00:05] "GET /?action=get_config&key= HTTP/1.1" 200 -
192.168.1.14 - - [06/Jul/2017 21:00:48] "POST / HTTP/1.1" 400 -
ERROR: No JSON object could be decoded
192.168.1.14 - - [06/Jul/2017 21:00:48] "GET /?action=get_config&key= HTTP/1.1" 200 -
bonjour
Jarvis: Bonjour Sébastien
```

**Comment by wikijm** [comment]
Bonjour @seboss1111,

Fais-nous des vidéos [ASCIINEMA](https://asciinema.org/) que l'on puisse constater ce qui ne va pas dans ton contexte.

Commence par petit, à savoir utiliser Jarvis sans plugin, et en utilisant Snowboy pour la reconnaissance du mot-clé de mise en écoute (hotword) avec le mot-clé "Jarvis", Bing pour la transformation de la parole en texte (speech to text) et Pico pour la synthèse vocale.

**Comment by Oliv4945** [comment]
Salut @seboss1111 

> 1- J'aimerais tellement pouvoir utiliser la voix qui ressemble à Jarvis dans iron man et je sais qu'elle
existe (voir vidéo)

De ce que j'en comprends il utilise Jarvis comme mot cléf, mais ce qui tourne derrière est S.A.R.A.H. Selon [la doc](https://github.com/JpEncausse/SARAH-Documentation/wiki/Voice-TTS) ça utilise la synthèse vocale Windows, donc impossible à utiliser pour ce projet. Plus de détails par le même auteur [ici](https://www.youtube.com/watch?v=NxV6BLm3gtU).
Cependant tout espoir n'est pas perdu, je suis entrain de regarder pour intégrer la synthèse Amazon qui offre beaucoup plus de possibilités, pour un coût très faible.

>2- Dès que je quitte et que je relance Jarvis impossible d'entendre la voix sur mes enceintes et je suis
obliger de faire un STEP-BY-STEP

Est-ce que fichier ~./asoundrc change entre les deux ?

> 3- Je ne peux pas utiliser les fonctions en API 

A partir du téléphone/tablette que tu utilises, que ce passe-t-il si tu entres `http://192.168.0.50:8080/?order=192.168.1.18&key=1234567890` dans un navigateur ?

Sinon je pense qu'il y a eu un soucis avec ton log de débug, il y manque des infos. Soit le recommencer soit faire un ASCIICinema comme demandé par wikijim aiderait :)

**Comment by seboss1111** [comment]
Je ne comprends pas ACIIENA et je ne veux pas tout désinstaller comme ça désolé @wikijm  :/
Pour le problème du step by step allez voir https://github.com/alexylem/jarvis/issues/661   je ne suis pas le seul visiblement c'est pour quelques personnes dont moi..

A partir d'un autre périphérique @Oliv4945 la console donne : 
Sébastien: 192.168.1.27 - - [07/Jul/2017 23:28:07] "GET /?order=192.168.1.18&key=1234567890 HTTP/1.1" 400 -
ERROR: No JSON object could be decoded
192.168.1.27 - - [07/Jul/2017 23:28:07] "GET /favicon.ico HTTP/1.1" 400 -
ERROR: Don't know what to do with: {}

Et sur le navigateur sur lequel j'ai envoyé l'ordre: 
http://192.168.1.18:8080/?order=192.168.1.18&key=1234567890

il m'affiche seulement un texte  : 
{"error": "No JSON object could be decoded"}

ET C'EST EXACTEMENT LE FOUTU MEME MSG D'ERREUR QUE J'AI SUR MON TEL..et qui s'affiche quand l'api ne veut pas marcher  👎 le NO jSON tatatitatata.. --'
Et quand ça marche (rarement) c'est limité à deux mots max en API donc c'est vraiment embétant..

Et pour la voix ce serait tellement coooool *---* de pouvoir la changer parce que pour le moment c'est une fille avec un balais dans les fesses xD

**Comment by wikijm** [comment]
Tuto ASCIINEMA : http://www.lafermeduweb.net/billet/asciinema-enregistrez-votre-session-de-terminal-en-screencast-1826.html

La communauté OpenJarvis investit du temps personnel pour répondre à ses utilisateurs et les aider en cas de problème. Il serait bien que tu en fasse de même et que tu prenne un peu de temps pour essayer les solutions que l'on te propose.

@Oliv4945 et moi-même avons décidé de te donner un coup de main, et ce, malgré le fait que tu n'ai pas pris le temps de fournir ce qui t'a été demandé lors de l'ouverture de ton issue.

Dans mon domaine professionnel, lorsque que je traite des tickets d'incidents et demandes de service et qu'ils ne sont pas conforme, ils sont immédiatement cloturés. C'est ce que j'ai envie de faire quand de nouvelles issues arrivent ici sans fournir ce qu'il faut, mais cela n'engage que moi.

J'espère que tu ne prendras pas mal mon message, mais les issues s'accumulent, et à la longue le manque d'implication peut être pesant, surtout au vu du nombre d'issues en cours.

**Comment by Lusitanos67** [comment]
Curieux de voir la réponse...

**Comment by seboss1111** [comment]
Je comprend tout à fait ton point de vue @wikijm et je suis désolé si je n'ai pas accepter de tourner un  ASCIINEMA.
Je ne vois vraiment pas du tout (pour mon problème) en quoi ça aiderait car c'est tout simplement un copier coller de l'invite de commande que j'ai déjà fait.
Le problème dont je vous parle est bien plus profond que ça : en effet il semble (simplement) que Jarvis ne veut pas "mémoriser" un haut parleur une fois qu'il est arrêté.
Et donc un ASCIINEMA ne sert à rien..il n'y a aucun messages d'erreurs, rien...
On doit donc tout refaire au redémarrage.. et je ne suis pas le seul, c'est un bug généralisé je pense.
C'est aussi pour cela que je ne vois pas comment un "~./asoundrc" servira vu que : avant le step by step, il ne doit pas être correcte et qu'après démarrage il m'est impossible de le consulter vu que l'on est dans Jarvis et que dès que l'on quitte il doit revenir au "pas correcte". @Oliv4945 

Et pour ta gouverne, @wikijm , je ne serait pas là si je n'avais pas chercher moi même un minimum mais c'est dans le coeur même de Jarvis que réside le problème (hors de mes compétences).
Je ne suis pas n'importe qui qui vient ici juste pour parler de son petit problème perso, je tente tant bien que mal d'ailleurs, d'amener aussi ma pierre à l'édifice comme vous par exemple en voulant améliorer significativement Chrome-browser..malgré mes faibles connaissances.. J'ai même appris à me servir de Photoshop tout seul et j'ai bientôt fini de créer des animations gifs (à rajouter dans le plugin "Face") fidèles au fameux film Iron man : un VRAI Jarvis quoi :D (ça arrivera bientôt pour les intéressés :P). Voilà un avant goût (perso je trouve ça méga stylé et avec des annimations... Je garde la surprise ^-^ : [http://zupimages.net/up/17/27/5rft.png](url)

**Comment by wikijm** [comment]
Pour compléter mon propos :

1. @seboss1111 J'apprécie que ta réponse soit tout à fait respectueuse, malgré mon intervention je l'avoue un peu rentre-dedans.

2. Les plugins peuvent être simplement désactivés, cela évite leur suppression. Étapes à suivre :
    - Lancer Jarvis avec `./jarvis.sh`
    - Entrer dans _Plugins (commands from community)_
    - Entrer dans _Installed (*)_
    - Entrer dans le(s) plugin(s) à désactiver
    - Entrer sur l'option _Disable_
    - Sur le menu de sélection des plugins, celui désactivé se nomme désormais _NomPlugin (disabled)_
   Je propose cette solution car plusieurs personnes ont rencontrés des problèmes dû à des plugins chargés en mémoire en amont du passage de Jarvis en écoute.

3. ASCIINEMA est utile car l'on peut rejouer aisément les étapes que tu as suivi, et visualiser les temps de traitement de chaque tâche par lesquelles tu passe. Si tu le souhaites, tu peux également partager une capture vidéo de ton écran ou te filmer (afin d'entendre tes ordres vocaux).

4. Tu rencontres peu ou pas de message d'erreur car au vu des logs fournis dans https://github.com/alexylem/jarvis/issues/668#issue-241062135 et https://github.com/alexylem/jarvis/issues/668#issuecomment-313799413, tu ne lance pas Jarvis en troubleshooting mode. En regardant l'aide https://openjarvis.com/content/usage, on peut y voir qu'il faut utiliser la commande ./jarvis.sh -v pour cela. Tu auras ainsi des logs avec énormément de détails, et pas limité à des retours d'informations habituelles.

5. Tu énonces, ainsi que tes logs, plusieurs problèmes. Le mieux est de faire une issue/problème, ou compléter une issue existante pour un problème déjà connu, comme cela semble être le cas pour ta perte de configuration audio. Cela permet aux contributeurs de mieux cerner les contextes dans lesquelles apparaissent un même problème.

**Comment by Oliv4945** [comment]
@seboss1111 je t'avoue que j'ai relu plusieurs fois ton message en me demandant si c'était juste de l'excitation et de la déception que ça ne fonctionne pas, visiblement oui mais je comprends la réaction de @wikijm .

> On doit donc tout refaire au redémarrage.. et je ne suis pas le seul, c'est un bug généralisé je pense.

Pour l'instant il est encore difficile de confirmer que vous avez le même soucis tous les deux, mais j'essaie. On a pas de chance Alexy ne doit pas être là en ce moment, donc on va tâtoner un peu :-)

>C'est aussi pour cela que je ne vois pas comment un "~./asoundrc" servira vu que : avant le step by step, il ne doit pas être correcte et qu'après démarrage il m'est impossible de le consulter vu que l'on est dans Jarvis et que dès que l'on quitte Jarvis il doit revenir au "pas correcte". @Oliv4945

J'essaie juste de comprendre, si tu sais d'où vient le problème n'hésites pas à le résoudre :-). Je fais une boutade exprès, ne le prends pas mal mais ça aiderait vraiment de savoir quand le fichier change, si il change.
Es-tu sur que c'est quand tu quittes Jarvis ? De plus, normalement, pour que les changements dans le fichier soient pris en compte il faut redémarrer Alsa. **Si** ton fichier .asoundrc ne change pas essaie de redémarrer Alsa justement, juste pour voir: `sudo /etc/init.d/alsa-utils restart`. C'est aussi pour ça que j'ai besoin d'une copie complète du log de Jarvis démarré avec `jarvis -v`, ça permet de voir les interfaces utilisées.
L'autre piste est que le logiciel `play` ne se ferme pas pour une raison inconnue, d'où ma demande sur #661 , qui est restée sans réponse. Si on peut continuer là bas sur ce problème ça permettrai de ne pas se perdre.

Pour Jarvis-api erreur de ma part, peux-tu exécuter `http://192.168.1.18:8080/?order=test&key=1234567890` j'avais mis l'IP au lieu de l'ordre désolé. Quel est le contenu du fichier jarvis.log ?
De plus, que ce passe-t-il si tu lances Jarvis, et dans un autre terminal tu exécutes `jarvis -x test`, normalement ça devrait le faire, mais au cas où...
Sur quoi exécutes-tu Jarvis ? Un rPi ? Quelle est ta version de Python ?

**Comment by seboss1111** [comment]
Merci encore pour vos réponse
Je run Jarvis sur un Raspberry pi et je viens de checker ma version python : 
Python 2.7.9 (default, Sep 17 2016, 20:26:04)
[GCC 4.9.2] on linux2

*Pour Jarvis-api erreur de ma part, peux-tu exécuter http://192.168.1.18:8080/?order=test&key=1234567890 j'avais mis l'IP au lieu de l'ordre désolé. 

J'avais déjà compris que tu t'étais tromper, donc j'avais bien mis  http://192.168.1.18:8080/?order=test&key=1234567890


voilà pour le reste,  il va me falloir quelques jours pour faire tout ce que vous m'avez demander je vais faire au plus vite :)

**Comment by wikijm** [comment]
Bonjour @seboss1111,

As-tu reçu ton micro ? Est ce que c'est mieux de ton côté ?

**Comment by wikijm** [comment]
Clôture du ticket jusqu'à obtention d'une réponse de la part de l'auteur de l'issue.
Closing of the ticket until a valid answer from the applicant is obtained.
