### ISSUE TITLE
snowboy / Hotword Library

### ISSUE THREAD

**Issue by Didier3L** [alexylem/jarvis#669]
Bonjour,
Je voulais savoir si c'était normal d'avoir deux jarvis sur le site de snowboy ?
J'ai aussi un nestor, mais je ne l'utilise plus. Et je ne sais pas comment le supprimer ?
<a href="https://www.hostingpics.net/viewer.php?id=898161MyPicture174.jpg"><img src="https://img4.hostingpics.net/thumbs/mini_898161MyPicture174.jpg" alt="Heberger image" /></a>

**Comment by Oliv4945** [comment]
@Didier3L , ton lien ne renvoie sur rien.
J'ai du mal à comprendre ton soucis, mais je pense que tu veux supprimer les fichiers pmdl qui sont dans stt_engines/snowboy

**Comment by Didier3L** [comment]
[http://hpics.li/e29e243](url)

**Comment by Oliv4945** [comment]
Ah, pas de soucis, c'est juste l'interface web de Snowboy où tu peux télécharger tes mots clefs, c'est indépendant de ton Jarvis ;)
