### ISSUE TITLE
config folder not exist after doing a git. So configuration never saved then setup on each launch

### ISSUE THREAD

**Issue by LengZai** [alexylem/jarvis#67]
### Description

Jarvis.sh doesn't save the configuration because he cannot find the folder config.
So on the first launch, Jarvis should create a folder config otherwise everytime we launch jarvis.sh we need to do the installation setup all the time.

Workaround until next update... `mkdir config` on jarvis folder

**Comment by alexylem** [comment]
I'm so chocked I never noticed or heard about this before!! Will just create an empty file for now in the repository so that it comes with the clone.
