### ISSUE TITLE
Amélioration de JARVIS-CHROMIUM-BROWSER

### ISSUE THREAD

**Issue by seboss1111** [alexylem/jarvis#671]
Salut à tous,
J'ai (je pense) améliorer jarvis-chromium mais me trouve dans une impasse.
Je ne connais pas bien la programmation et j'ai besoin d'aide.. Allez tester mon amélioration pour mieux comprendre et pouvoir m'aider : sebogoss11/jarvis-chromium
L'amélioration permettrait de rechercher uniquement grâce à la voix les grandes lignes d'un mot : sa définition, un site le concernant, des news le concernant, des images, des vidéos et enfin le shop.
Ca peut s'avérer très utile je pense..il utilise d'ailleurs le plugin de wikipédia..
Néanmoins lorsque je lance ma commande "recherche multiple Facebook" par ex; il me donne la définition bien, mais il lance le site en plein écran et ne veut plus écouter aucune autre commande tant que je n'ai pas quitter la page chrome manuellement avec alt+F4.
Cela bloque donc toute les fonctions étant donné que l'utilisateur ne va pas quitter avec sa souris à chaque fois qu'il veut faire un recherche..

J'ai donc besoin de savoir:
1-Comment empêcher les pages de se lancer en mode plein écran

2-Comment, au lieu de quitter chrome manuellement à chaque 'bug' (la machine n'entend plus rien tant qu'on ne fais pas alt+F4 dans le raspberry pi) on pourrait la faire écouter les commande suivantes qui elles permettent de quitter ou de faire des recherches plus poussées. En gros, comment débloquer le blocage sur une page à la fois?

3-Est-il possible lorsque tous ces pb seront réglés de simplement ajouter des onglets au lieu de devoir quitter chrome pour faire de nouvelles recherches avec *$(jv_plugin_affichage_fermer_naviguateur)*

4-Littéralement tout dirigé par la voix : descendre dans la page, sélectionner des choses dans la page etc..

PS : Je n'ai pas besoin de vous dire que je m'en fiche totalement de la commande pour afficher un message je pense vue que c'est la seule que je n'ai pas touchée
Merci d'avance de votre aide, des bisous :D

**Comment by Oliv4945** [comment]
Comme discuté plusieurs fois merci de poster dans le repo du plugin, ça permet de s'y retrouver. Donc tu peux aller [ici](https://github.com/Erim32/jarvis-chromium/issues/new).
