### ISSUE TITLE
pocketsphinx en français

### ISSUE THREAD

**Issue by SmallLeandre** [alexylem/jarvis#672]
bonjour,
j'ai voulu tester jarvis et pocketsphinx.
je suis parti du fichier test.sh qui se trouve dans le répertoire pocketsphinx et l'ai adapté au français (en téléchargeant le modèle de langue de cmusphinx, et en adaptant le dictionnaire. Le résultat n'est pas extraordinaire et je me demande s'il l'adaptation du modèle à partir du tuto donne des résultats probant. 
Est-ce que quelqun a déjà essayé?
merci

**Comment by Oliv4945** [comment]
J'avais essayé PocketSphinx en créant mon fichier de phonèmes, ça permet de limiter à quelques mots (un peu plus rapide) mais surtout d'adapter à la prononciation si ça ne marche pas.
PocketSphinx a le mérite d'exister mais ne fonctionne pas aussi bien que Bing ou Snowboy ;-)

**Comment by SmallLeandre** [comment]
Peux tu partager tes fichiers et scripts?
Merci

**Comment by Oliv4945** [comment]
@SmallLeandre : Désolé c'était juste des tests je n'ai rien gardé.

**Comment by satana888** [comment]
Bonjour,

 

Je voulais te demander comment procéder pour lui insérer 2 HOTWORD ?

 

Je te remercie d ‘avance

 

Cordialement

 

 

De : SmallLeandre [mailto:notifications@github.com] 
Envoyé : dimanche 9 juillet 2017 23:41
À : alexylem/jarvis
Cc : Subscribed
Objet : [alexylem/jarvis] pocketsphinx en français (#672)

 

bonjour,
j'ai voulu tester jarvis et pocketsphinx.
je suis parti du fichier test.sh qui se trouve dans le répertoire pocketsphinx et l'ai adapté au français (en téléchargeant le modèle de langue de cmusphinx, et en adaptant le dictionnaire. Le résultat n'est pas extraordinaire et je me demande s'il l'adaptation du modèle à partir du tuto donne des résultats probant.
Est-ce que quelqun a déjà essayé?
merci

**Comment by wikijm** [comment]
https://github.com/alexylem/jarvis/issues/672#issuecomment-317205668

Bonjour @satana888,

Peux-tu faire une autre issue pour ta requête ? Elle ne semble pas être liée à cette issue.
N'hésite pas à y écrire les pseudo @SmallLeandre et @Oliv4945 vu que ce sont des utilisateus de PocketSphinx 😜
