### ISSUE TITLE
Problème microphone + reconnaissance sujet 664 V2

### ISSUE THREAD

**Issue by Toadman13680** [alexylem/jarvis#673]
J'aimerais réouvrir le sujet 664
Hier soir, en ayant mis bing en tant que commande vocale je me suis aperçu que j'avais le même problème. 
![image](https://user-images.githubusercontent.com/29925666/27984927-10cb6e40-63e2-11e7-8f45-8a259d6232ae.png)

En énonçant le mot-clé JARVIS, cela a déclenché l'écoute de ce dernier. J'ai eu beau parler rien ne se passait.
En passant en mode debug, j'ai constaté que j'ai une erreur de connexion au serveur...

Avez-vous des idées quant à la résolution du problème ?
Merci :)

**Comment by wikijm** [comment]
Tu devrais être en mesure de le ré-ouvrir par toi-même (bouton "Reopen issue" en bas de page).
Si ce n'est pas, n'hésites pas à me le signaler 😜 

Astuce : Tu peux citer une issue en mettant un `#` suivi de son code. Exemple : #664
