### ISSUE TITLE
Requête json => Domoticz + jarvis

### ISSUE THREAD

**Issue by Toadman13680** [alexylem/jarvis#674]
Bonjour à tous,

J'ai un petit problème avec domoticz couplé à Jarvis.
Tout d'abord, j'ai commencé à ajouter une simple ligne dans le fichier commande de Jarvis précisant : 
![image](https://user-images.githubusercontent.com/29925666/28019120-0bf79d68-6580-11e7-8c50-15f8086b0d09.png)
Lorsque j'exécute cette commande, j'ai une erreur 
![image](https://user-images.githubusercontent.com/29925666/28019149-2899bc26-6580-11e7-868a-1491bcb6932e.png)

Avant de demander de l'aide, j'ai utilisé une seconde méthode. J'ai installé le plugin Home Control et je l'ai réadapté comme il est précisé sur le site : https://easydomoticz.com/commandes-vocales-via-jarvis/
Malheureusement, j'ai la même erreur qui est apparue....
![image](https://user-images.githubusercontent.com/29925666/28019325-e08c04a6-6580-11e7-94a6-5bb62c4e862b.png)

Quelques pistes : 
- Est-ce que cela a un rapport avec Domoticz qui exécute les commandes en root ? mais je trouve cela bizarre car je fais une simple requête...
- Au départ, avant de mettre mon IP local, j'avais mis mon adresse IP externe. Ayant eu cette erreur, je me suis dit que c'était dû à l'IP externe, mais en passant en IP local j'ai le même problème...
- Est-ce que cela est dû à l'interface de sécurité ? En effet, lorsque je me connecte à Domoticz je dois saisir un nom d'utilisateur puis un mot de passe. Je pense plus à cette hypothèse.

Merci du temps que vous prendrez pour moi :+1: 

Toto.

**Comment by Toadman13680** [comment]
Je viens d'enlever provisoirement le mot de passe sur Domoticz puis j'ai exécuté la commande "Allume chambre".
Cela a fonctionné...
![image](https://user-images.githubusercontent.com/29925666/28020115-7e76f96c-6583-11e7-8db0-a2c7df9c2d38.png)

Quelqu'un pourrait-il me guider quant à l'intégration du nom d'utilisateur puis mot de passe sur le plugin Home Control ?
Il a été réadapté comme sur le site : https://easydomoticz.com/commandes-vocales-via-jarvis/

Toto.

**Comment by Oliv4945** [comment]
Je suppose que tu peux faire
`allume==say "ok" && curl -u username:password http://192.168...`

Sinon tu tu peux faire un copier/coller du texte plutôt que des images ça serait plus pratique, merci.

**Comment by Toadman13680** [comment]
Oliv je te remercie de ta réponse cela fonctionne pour les commandes directes dans le fichier Jarvis-commands.
J'ai mis : 
`*ALLUME*LAMPE*SALON*==say "Ok" && curl -u nomd'utilisateur:motdepasse  "http://XX.XX.XX.XX:XXXX/json.htm?type=command&param=switchlight&idx=1&switchcmd=On"`


Pour aller plus loin j'ai effectué la modification sur le plugin Jarvis-home-control


```
pg_hc_turn () {
    # $1: action [on|off]
    # $2: received order
    [ "$1" == "off" ] && local url="$pg_hc_turnoff_url" || local url="$pg_hc_turnon_url"
    local -r order="$(jv_sanitize "$2")"
    while read device; do
        local sdevice="$(jv_sanitize "$device" ".*")"
        if [[ "$order" =~ .*$sdevice.* ]]; then
            local address="$(echo $pg_hc_config | jq -r ".devices[] | select(.name==\"$device\") | .address")"
            say "$(pg_hc_lg "switching_$1" "$2")"
            **curl -u nomd'utilisateur:motdepasse** "${url//\[ADDRESS\]/$address}"
            return $?
        fi
    done <<< "$(echo $pg_hc_config | jq -r '.devices[].name')"
    say "$(pg_hc_lg "no_device_matching" "$2")"
    return 0 # error already said above, no need to trigger error phrase
}

```

J'ai remplacé ce qui été écrit : `jv-curl` par `curl -u nomd'utilisateur:motdepasse` mais j'ai une remonté d'erreur.

Tout est niquel, Oliv tu es mon sauveur ce soir, merci infiniment.
Toto.
