### ISSUE TITLE
Auto-adjust et micro compatible

### ISSUE THREAD

**Issue by Lusitanos67** [alexylem/jarvis#675]
Bonjour,

Je me demandais si quelqu'un avait eu de bon résultat avec la fonction "d'auto adjust", car pour ma part je suis obligé de toucher au paramétrage défini en automatique afin d'arriver à .... Presque rien mais bon je ne lâche pas l'affaire.
Je tourne avec le micro "ander usb", et franchement je pense qu'on peux l'enlever de la liste des micro compatible car chez moi ca n'a jamais fonctionné correctement malheureusement.
Quelqu'un aurait-il essayé de nouveaux micro pas cher, et quand je dis pas cher c'est en dessous de 50€ ?

Idem si quelqu'un aurait des tips sur la position du micro, le paramétrage, plugin a éviter. Ce qui me déçois le plus en faite, c'est que les première version de Jarvis fonctionnait mieux que maintenant, ou quand je vois matrix voice, qui détecte le hotword et les phrases sur plusieurs mètres, c'est impressionnant, et vu le prix pas besoin d'un micro à 100€ !

Merci

**Comment by wikijm** [comment]
Bonjour @Lusitanos67,

Je t'invite à faire des recherches dans les issues précédentes.
Si ce micro a été mis dans la liste, c'est que des membres de la communauté l'ont testé et approuvé.

Ils pourront sans doute te faire un retour d'expérience et te proposer des réglages fonctionnels 😃 
Si malgré leur aidre tu rencontre toujours des problèmes, n'hésites pas à rouvrir cette issue 😉

**Comment by wikijm** [comment]
Désolé @Lusitanos67, je suis allé un peu trop vite.

Je viens de voir que tu avait déjà fait ce qu'il fallait, à savoir demander une configuration fonctionnelle dans l'issue https://github.com/alexylem/jarvis/issues/250.
Apparement, @sinedied dit dans #226 qu'il n'a rien fait de particulier niveau configuration hormis utiliser Wit.

**Comment by Lusitanos67** [comment]
Ok très bien

**Comment by Oliv4945** [comment]
@wikijm , @alexylem : Que diriez vous d'une page du site qui liste les différents réglages pour chaque micro ? on voit souvent cette question ressortir donc ça pourrait guider le gens ?
