### ISSUE TITLE
désynchronisation avec crontab ?

### ISSUE THREAD

**Issue by remjou1** [alexylem/jarvis#68]
je ne sais pas trop ce qui ce passe mais lorsque j'utilise jarvis-events je met une tache programmé (mon réveil :p ) mais lorsqu'il est l'heure le réveil ne se lance pas.... j'ai essayé pas mal de truc par rapport a la commande du réveil puis j'ai décidé de fair ```crontab -l``` et ```crontab -e``` et je remarque que le crontab est celui que j'utilisais il y a déja une semaine... bref le bordel... je sais pas si c'est normal (je n'utilisais pas le crontab avant)... bref tout ça pou dire que ce n'est pas le même résultat entre le jarvis events et le crontab... que faire ??

**Comment by alexylem** [comment]
Jarvis passe par un fichier intermédiaire `jarvis-events` puis (si l'utilisateur enregistre) l'installe dans le crontab sur l'utilisateur actif avec:
```
crontab jarvis-events -i
```
Vérifie donc qu'après avoir édité tes commandes depuis le menu de Jarvis, tu enregistres bien dans nano avec Ctrl+X > Y > [Enter]

Je viens de tester et ca fonctionne bien. Tu as peux-être utilisé Jarvis avec un autre utilisateur, du genre `root` ?

**Comment by remjou1** [comment]
non rien de tout ça... bizarre.... c'est pas grave je vais continuer en utilisant crontab... merci quand même
