### ISSUE TITLE
Commandes "par défaut" envoyées à Jeedom

### ISSUE THREAD

**Issue by brunoloison** [alexylem/jarvis#680]
Bonjour à tous,
j'ai un léger soucis. Jarvis fonctionne plutôt pas mal avec mon hotword "opérateur". Quelques fois, il s'arrête d'écouter mes commandes, et donc il manque la fin de ma phrase (pourtant pas si longue) genre "Allume le lampadaire de la salle à manger", comprise en "Allume le lampadaire". Ou alors des fois il manque le début. Je vais essayer de me débrouiller pour ça. 
Mon vrai problème est que parfois Jarvis ne me comprends pas bien, des fois même très mal, et de fois même je fais exprès... et.... voilà le résultat:

> Mon maître: opérateur
opérateur: Oui?
Mon maître: non
opérateur:
opérateur: C'est fait (Salon Lumière On)

(Oui... "Mon maître"... )
Alors ma question: pourquoi il m'allume la lumière du salon?? et des fois c'est une autre commande qui est envoyée, je ne comprends pas pourquoi!!!

Si quelqu'un a une idée, je préfèrerai qu'il me dise qu'il ne comprends pas (ce qui se passe lorsque je désinstalle le plugin-jeedom).

MERCI !

**Comment by brunoloison** [comment]
Salut, je me réponds tout seul, j'ai fini par trouver que c'et pas de la faute à notre gentil Jarvis, mais c'est un réglage dans Jeedom......   désolé.

**Comment by Oliv4945** [comment]
Super ! Est-ce que tu pourrais mettre la solution pour ceux qui auront le même soucis ?

**Comment by brunoloison** [comment]
Oui bien sûr, désolé d'avoir oublié. 
Donc c'est dans les engrenages > configuration > configuration des interactions. 
Là Jeedom propose plusieurs options qui visent à être tolérant avec les demandes faites par l'utilisateur. En gros, si une phrase n'est pas prononcée pile-poil comme c'est prévu, il peut de lui-même tenter de l'interpréter.... bonne idée, mais dans mon cas, ça ne va pas. Donc j'ai décoché toutes ces options, en particulier "Activer les réponses contextuelle", j'ai baissé à 1 la sensibilité, et j'ai coché la case "Ne pas répondre si l'interaction n'est pas comprise".
En contrepartie, mes interactions sont construites de telle sorte qu'elle sont tout de même tolérante: j'ai joué avec les synonymes, du coup, pour allumer une lumière, je peux:
allumer la lumière de....
mettre en route la lampe de...

et je ne mets pas toutes la liste sinon internet va lâcher.

Bonne journée à tous ^^
