### ISSUE TITLE
[STT] Ajouter Julius

### ISSUE THREAD

**Issue by IPv777** [alexylem/jarvis#682]
Hello,

une petite issue rapide pour demander l'ajout du SST Julius (fonctionne hors-ligne) : http://julius.osdn.jp/en_index.php

Merci d'avance ;p

**Comment by wikijm** [comment]
Bonjour @GuillaumeSX,

Peux-tu nous donner les avantages de cet STT ?
Est ce qu'il est compilable sur une architecture ARM (pour Raspberry) ?

Je vois que la [dernière release](http://julius.osdn.jp/en_index.php?q=index-en.html#latest_version) date du 15/01/2014, le projet est-il toujours maintenu ?

**Comment by wikijm** [comment]
Si tu souhaites commencer son intégration, je t'invite à aller voir l'issue https://github.com/alexylem/jarvis/issues/677, qui concerne l'ajout du STT KALDI.

**Comment by Smanar** [comment]
Oui il marche sur Raspberry, teste sur un Raspberry 1 a l'epoque.
Mais gros boulot pour l'installer.

**Comment by Oliv4945** [comment]
ça ne semble pas si difficile, cf [cette page](https://gist.github.com/UedaTakeyuki/788667086f5c3fcb7d40)
Il faudrait que je l'essaie à l'occasion, si il fonctionne bien pourquoi pas :-)

**Comment by GuillaumeSX** [comment]
J'essaie l'integration vers septembre ;)

**Comment by alexylem** [comment]
Before I investigate this further... does it work in french?

**Comment by Smanar** [comment]
You can make all you want with it, but like I said previously, lot of work.
Take a look for a more complete tutorial
http://archive.is/XplIK (I don't find the original page)
To use french you need to train it and make your own grammar file.

**Comment by IPv777** [comment]
Like Snowboy...

**Comment by IPv777** [comment]
Je viens de lire un petit article sympa :
https://blog.mozfr.org/post/2017/07/Mozilla-ouvre-la-voix-reconnaissance-vocale
J'ai hâte ^^ Rien que l'idée que n'importe qui puisse contribuer me plait :)
