### ISSUE TITLE
Caractères spéciaux dans le hotword et dans le nom d'utilisateur

### ISSUE THREAD

**Issue by rindraloic** [alexylem/jarvis#683]
Bonjour,
Comme indiqué dans le titre, j'ai utilisé des caractères spéciaux lors du step by step wizard. J'essaie de refaire le wizard, mais je ne peux rien modifier une fois arrivé sur les écrans concernés. 

Y'a-t-il une solution?

**Comment by Oliv4945** [comment]
Si tu n'as encore rien paramétré tu peux effacer le dossier et refaire une
copie de Github :)

**Comment by rindraloic** [comment]
Merci @Oliv4945, ta réponse m'a  donné une piste. 
J'ai fouillé dans le dossier `/path-to-jarvis/jarvis/config` et j'ai pu les renommer depuis les fichiers `trigger` et `username`.

**Comment by wikijm** [comment]
Bonjour @rindraloic 
Est ce que cela a résolu ton problème ?

**Comment by rindraloic** [comment]
Hello @wikijm 
C'est bon pour moi, je ferme ce thread. Merci!

**Comment by wikijm** [comment]
Je prends ta clôture pour un 'oui' 😜
