### ISSUE TITLE
[Errno 98] Address already in use

### ISSUE THREAD

**Issue by rindraloic** [alexylem/jarvis#684]
Bonjour,
J'ai installé jarvis-api et jarvis-ui sur mon raspberry sans micro/carte audio.
J'ai voulu me connecter à l'UI depuis mon smartphone pour lui donner des ordres vocaux, mais:
- Lors du démarrage de jarvis, il est démarré en keyboard mode.
- Après le démarrage, il m'affiche une erreur "[Errno 98] Address already in use", mais il écoute quand même mes conversations
- Lorsque je me connecte dans le navigateur de mon smartphone, l'erreur "Connexion error, Verify Jarvis is started, has jarvis-api installed and check api port in client settings.". Le port utilisé par les API est 8080, il n'y a pas de conflits avec d'autres applications.

Oú est le problème?

Merci

**Comment by Oliv4945** [comment]
Salut,
Comme demandé à l'ouverture de l'issue, merci de donner le résultat de `jarvis -nv`.  
Pour ton soucis, que donne `sudo netstat -lupate | grep 8081` ? En remplaçant 8081 le port que tu as défini par Jarvis API.

**Comment by rindraloic** [comment]
Voici le résultat de `jarvis -nv`

------------ Config ------------
jv_branch            master 
jv_version            
jv_arch              armv7l 
jv_os_name           raspbian 
jv_os_version        8 
language             fr_FR 
play_hw              false 
rec_hw                
speaker              Default 
microphone           Default 
recorder             sox 
trigger_stt          snowboy 
command_stt          snowboy 
tts_engine           svox_pico 
--------------------------------

No mic configured, forcing keyboard mode
DEBUG: program_startup hook
Starting RestAPI server on http://192.168.2.104:8080
Starting User Interface on http://192.168.2.104:8081
DEBUG: start_speaking hook
Rab: Bonjour
utils/utils.sh: line 172: svox_pico_TTS: command not found
DEBUG: stop_speaking hook
User defined commands:
*AIDE*			*BONJOUR*|*SALUT*	*COMMENT*APPELLE*
*MERCI*			*AU REVOIR*|*BYE*	ANNULE*|TERMINE*
ENCORE*			*TEST*			*VERSION*
*REPETE (*) ET (*)	*CA VA*			>*OUI*
>*NON*|*PAS*
Commands from plugin jarvis-face:

Commands from plugin jarvis-time:
*QUELLE HEURE*		*QUEL JOUR*
Commands from plugin jarvis-ui:
*OUVR*INTERFACE*
Commands from plugin jarvis-api:

Lo: ERROR:  [Errno 98] Address already in use

La deuxième commande ne retourne rien

**Comment by Oliv4945** [comment]
Salut, du coup Jarvis API est en 8080, donc il faudrait plutôt faire `sudo netstat -lupate | grep 8080`.
Au cas où, après avoir quitté Jarvis, est-ce que `sudo ps -A | grep jarvis` te donne quelque chose ?

**Comment by rindraloic** [comment]
Oui `sudo netstat -lupate | grep 8080` c'est la commande que j'ai éxecutée, elle ne retourne rien. De même pour `sudo ps -A | grep jarvis`

**Comment by Oliv4945** [comment]
C'est surprenant, à moins que Jarvis API essaie de démarrer deux fois, mais
je ne comprends pas pourquoi.
Que donne `http://127.0.0.1:8080/?order=test&key=YOUR_KEY` sur la machine
où est installé Jarvis ? Au cas où, est-ce que tu peux faire `sudo netstat
-lupate` quand Jarvis fonctionne est quand il est arrêté ?

**Comment by rindraloic** [comment]
@Oliv4945 C'est bon, j'ai testé cette URL sur la machine et ça m'a ouvert une page d'erreur d'openhab --'. J'ai modifié le port des api de jarvis. Mais ça m'étonne quand même que `netstat` n'aie pas eu de résultats.

@wikijm oui je comprends ça, c'est pourquoi je veux parler depuis le navigateur sous android. 
Je ferme la thread, merci à tous!

**Comment by Oliv4945** [comment]
Super !
Pour info tu as une application pour Android : https://play.google.com/store/apps/details?id=net.iopush.jarvis&hl=fr
