### ISSUE TITLE
"..._TTS: command not found" au deuxième lancement après configuration du TTS

### ISSUE THREAD

**Issue by GuillaumeSX** [alexylem/jarvis#686]
Hello :D

J'ai un petit problème : TTS manquant (j'ai un micro et un casque)
J'ai réussi à discerner le probleme : 
je définit le TTS, je démarre jarvis, aucun problème.
Je stoppe, puis redémarre : 
`utils/utils.sh: line 172: google_TTS: command not found`
Je stoppe, switche de TTS (google -> svox), et cela fonctionne à nouveau.
Je stoppe, puis redémarre : 
`utils/utils.sh: line 172: svox_pico_TTS: command not found`
Et ainsi de suite...

```
pi@raspberrypi:~/jarvis $ ls -la tts_engines
total 28
drwxr-xr-x  7 pi pi 4096 Jul 27 17:00 .
drwxr-xr-x 16 pi pi 4096 Jul 27 17:41 ..
drwxr-xr-x  2 pi pi 4096 Jul 27 17:00 espeak
drwxr-xr-x  2 pi pi 4096 Jul 27 17:00 google
drwxr-xr-x  2 pi pi 4096 Jul 27 17:00 osx_say
drwxr-xr-x  2 pi pi 4096 Jul 27 17:00 svox_pico
drwxr-xr-x  2 pi pi 4096 Jul 27 17:00 voxygen_old
```

Ils sont là, dans les villes, dans les campagnes, ...peut être des mauvais droits linux (755)?

jarvis -nv :
```
pi@raspberrypi:~/jarvis $ jarvis -nv
------------ Config ------------
jv_branch master
jv_version
jv_arch armv7l
jv_os_name raspbian
jv_os_version 8
language fr_FR
play_hw false
rec_hw
speaker Default
microphone Default
recorder sox
trigger_stt snowboy
command_stt snowboy
tts_engine svox_pico

No mic configured, forcing keyboard mode
DEBUG: program_startup hook
Starting RestAPI server on http://192.168.1.90:8081
Starting User Interface on http://192.168.1.90:8080
DEBUG: start_speaking hook
Melody: Bonjour Guillaume. serveur domotique actif
utils/utils.sh: line 172: svox_pico_TTS: command not found
DEBUG: stop_speaking hook
User defined commands:
AIDE	BONJOUR|SALUT	COMMENTAPPELLE*
MERCI	AU REVOIR|BYE	ANNULE*|TERMINE*
ENCORE* TEST	VERSION
REPETE () ET (*) CA VA	>OUI

    NON|PAS	>>OUI	>>NON|REST
    HEURE
    Commands from plugin jarvis-api:

Commands from plugin jarvis-ui:
OUVRINTERFACE*
Commands from plugin jarvis-systemd-startup:

Commands from plugin jarvis-testdebitadsl:
DEBITINTERNET|ADSL DEBITMINIMUM	DEBITMAXIMUM*
Commands from plugin jarvis-weather-wunderground-fr:
METEODEMAIN* METEO
Guillaume: ^CStopping HTTP server

DEBUG: program_exit hook
pi@raspberrypi:~/jarvis $
```

@Oliv4945 

Merci d'avance à tous pour vos suggestions :)

**Comment by GuillaumeSX** [comment]
EDIT : problème de mise en forme, correction en cours

**Comment by Oliv4945** [comment]
Tu as un soucis de configuration qui peut amener à ça.
```
play_hw false
rec_hw
```
Essaie de refaire le `step by step wizard` dans les paramètres.

Sinon pour la mise en forme, si tu veux utiliser le caractère "`" pour faire une mise en forme multi-ligne il faut le mettre 3 fois, regardes ton premier message si tu veux un exemple, je l'ai éditer.

**Comment by GuillaumeSX** [comment]
Okay thx, je teste ça :) et merci pour l'info des 3 caractères :)

**Comment by GuillaumeSX** [comment]
Ca me parait réglé...okay merci 👍
