### ISSUE TITLE
Support financier

### ISSUE THREAD

**Issue by IPv777** [alexylem/jarvis#688]
Je propose au développeur principal de ce projet de mettre des liens de parrainnage (reflink) Amazon (ou autre) sur cette page dans la catégorie Microphone : https://openjarvis.com/content/prerequisites.
Afin d'aider au financement.

**Comment by alexylem** [comment]
Merci Guillaume de ton intérêt pour le projet. Que proposes-tu comme lien de parrainage? Je n'ai pas été contacté par des constructeurs / marques mais si c'est le cas oui ca serait une bonne idée. Alternativement, il y a un système de donation qui marche plutôt bien et suffit à financer pour le moment l'hébergement du site.

**Comment by GuillaumeSX** [comment]
J'ai mal exprimé mon idée, je voulais parler des liens d'affiliation, qui te font gagner un pourcentage du produit quand qqn achète un micro (par exemple) via le site openjarvis.com.

https://affiliate-program.amazon.com/
https://www.shoutmeloud.com/how-to-create-affiliate-link-for-amazon-product-tutorial.html

Je te propose donc de remplacer les liens de la page micros par des liens amazon (ou un autre site) affiliés.

**Comment by GuillaumeSX** [comment]
Pour ma part si j'en avait les moyens je ferais un don pour le projet, mais étant étudiant mon bidget est assez...serré :/
Donc j'essaie de trouver des alternatives :)

**Comment by IPv777** [comment]
@alexylem je clos le ticket, mon idée à été exprimée :)
