### ISSUE TITLE
Git demande un nom d'utilisateur durant l'installation

### ISSUE THREAD

**Issue by alexylem** [alexylem/jarvis#69]
### Description

Bonjour, projet avec un énorme potentiel mais je bloque sur la 1er étape. Lors de l'installation de Jarvis cella me demande un mot de passe et un identifiant sous github.com. Pouvez vous m'aider ?!

![image](https://cloud.githubusercontent.com/assets/11017174/17085694/a24445e8-51de-11e6-847f-1f54b0a807b0.png)

**Comment by alexylem** [comment]
Apparement c'est un soucy lié au fait qu'on clone depuis https:
http://stackoverflow.com/questions/10909221/why-is-github-asking-for-username-password-when-following-the-instructions-on-sc

**Comment by stackgil** [comment]
moi je n'ai pas rencontré ce soucis

**Comment by alexylem** [comment]
Non mais laisse tomber, je viens de re-regarder la capture d'écran et l'URL est fausse...
`alexislen` au lieu de `alexylem`
