### ISSUE TITLE
🤖💡 | 🇫🇷 Ajouter une IA | 🇬🇧 Adding an AI

### ISSUE THREAD

**Issue by IPv777** [alexylem/jarvis#690]
🇫🇷 Après avoir fait un tour rapide des tickets ouverts, je me suis rendu compte que beaucoup de personne avançaient l'idée d'ajouter une Intelligence Artificielle à Jarvis.
Je propose donc de centraliser le sujet ici, en recensant les développeurs prêts à contribuer au projet, et en recensant les différentes solutions libres disponibles pour une possible intégration.
Et pour débattre sur les aspects positifs et négatifs de chaque solution.
___
🇬🇧 After making a quick tour of the open issues, I realized that many people were advancing the idea of adding an Artificial Intelligence to Jarvis.
I propose to centralize the subject here, by identifying the developers willing to contribute to the project, and by identifying the different open-source solutions available for a possible integration.
And to discuss the positive and negative aspects of each solution.
___

# Projects
- [TensorFlow](https://www.tensorflow.org/) Moteur de deep learning par G00gle, Python
- [Mycroft AI](https://mycroft.ai/) Open Source Artificial Intelligence, Python
- [API.AI](https://api.ai/) Build delightful and natural conversational experiences, Multi-languages 👍 
___
# [AI Cheatsheet](https://github.com/kailashahirwar/cheatsheets-ai)

@+ :)

**Comment by physicien** [comment]
J'utilise déjà pas mal TensorFlow, et je ne pense pas qu'un RP3 soit assez puissant pour que ça en vaille la peine.

**Comment by IPv777** [comment]
@physicien déjà merci pour une réponse si rapide 🥇 
après une petite recherche G00gle, voici quelque résultats qui ont attiré mon attention :
- [Installing TensorFlow on Raspberry Pi 3](https://github.com/samjabrahams/tensorflow-on-raspberry-pi)
- [Installation of TensorFlow on the Raspberry Pi 3 for Machine Learning](http://manmade2.com/installation-of-tensorflow-on-the-raspberry-pi-3-for-machine-learning/)
- [Google Tensorflow on Raspberry Pi](http://www.instructables.com/id/Google-Tensorflow-on-Rapsberry-Pi/)
- [TensorFlow on Raspberry Pi 3](https://www.reddit.com/r/MachineLearning/comments/4act9a/tensorflow_on_raspberry_pi_3/)

Sinon au delà de l'aspect technique, penses-tu que TensorFlow pourrait être adapté à l'utilisation voulue (dialogue + machine learning) ?

**Comment by physicien** [comment]
Tensorflow est une librarie très généraliste, donc oui on peut facilement l'utiliser pour ce que tu proposes. Cependant, il y a deux principaux problèmes:

1.  Il faudrait vérifier quelle est l'utilisation de ressources sur un RP3 lors de l'utilisation d'un réseau déjà entraîné;
2. Il n'y a pas assez de ressources sur un RP3 pour effectuer l'entraînement dans un temps raisonnable.

Personnellement, j'utilise Tensorflow avec mon GPU, et même pour un FFNN dont la couche d'entrée est de 13 neurones l'entraînement peut prendre un bon moment.

**Comment by IPv777** [comment]
🇫🇷 @physicien Quel est le niveau requis pour adapter [TensorFlow](https://www.tensorflow.org/) à Jarvis (le tiens)? Car même en ayant des bases, le vocabulaire tel que "FFNN" ou "couche d'entrée de 13 neurones" m'est assez compliqué à saisir.
(il faut que je lise les documents de la cheatsheet que j'ai posté dans le premier message ^^)

En attendant d'autres retours, après avoir un peu exploré [API.AI](https://api.ai/), j'ai trouvé des exemples similaires à l'utilisation voulue...à explorer plus ;)
___
🇬🇧 @physicien What is the level required to adapt [TensorFlow] (https://www.tensorflow.org/) to Jarvis (yours)? Because even having bases, the vocabulary such as "FFNN" or "input layer of 13 neurons" is quite complicated to understand.
(I have to read the documents of the cheatsheet that I posted in the first message ^^)

Waiting for other feedback, after a little exploring of [API.AI] (https://api.ai/), I found examples similar to the intended use ... to explore more ;)

**Comment by physicien** [comment]
@IPv777 Pour ce qui est du niveau requis (je me considère actuellement comme un débutant en apprentissage machine), j'arriverais certainement à coder quelque chose de fonctionnel (tout dépendant de l'objectif recherché), mais je ne garantie pas que ça va être ce qu'il y a de plus efficace.

Pour le vocabulaire, ces termes se rapportent principalement au type d'architecture utilisé pour le réseau à entraîner. Un _feedforward neural network_ (FFNN) est une des architectures les plus simples. Si tu souhaites comprendre un peu mieux, voici un [chapitre](https://github.com/alexylem/jarvis/files/1185817/chapitre6.pdf) des notes d'un cours que j'ai suivi cet hiver. Si tu te plonges un peu dans le sujet, tu réaliseras que le choix de l'architecture n'est généralement pas trivial et j'ignore encore s'il existe des critères autres que l'expérience et l'intuition pour faire ce choix.

**Comment by Oliv4945** [comment]
Pour info je viens de publier un plugin [api.ai](https://api.ai) [ici](https://github.com/Oliv4945/jarvis-api-ai). ça fonctionne, l'interface graphique du site est sympa à utiliser et ça ouvre pas mal de possibilités mais ça me laisse un peu sur ma faim :/  
De plus, c'est une techno proprio rachetée par Google récemment donc dur de savoir ce que ça va devenir.

Du coup je suis passé sur [Rasa NLU](https://rasa.ai/), un framework open source dédié au language. Contrairement à ce qui est dit sur le site ce n'est pas qu'Anglais et Français, plein de langues ont été ajoutées dernièrement à [Spacy](https://spacy.io/), un des moteurs en dessous.  
Du coup j'ai fait un plugin basique pour Jarvis, et je suis entrain de faire le "sous plugin" météo. Il faut tout redévelopper mais les possibilities sont immenses et ça éviter de ce tordre la tête sur les enchaînements/différents prononciations possibles comme actuellement.

**Comment by benoit34000** [comment]
@Oliv4945 tu as publié le plugin ou pas encore ? J'en vois un sur le store, mais ca n'a pas l'air d'etre le tien...
Merci !

**Comment by IPv777** [comment]
Désolé d'avoir initié ce sujet et de faire le mort.
Mais contrairement va ce que je pensais, je n'ai pas le temps pour y participer...
Ni même le temps de domotiser mon appart :S

**Comment by lakadev** [comment]
Bonjour,

Est-ce qu’il serait possible de lister des cas d’usages concrets de ce que ferait cette IA ?

Voici un exemple…
Faire en sorte que lorsqu’on dit le matin : 
>> « Fais du café » ou « Prépare le petit déjeuné » ou « J’ai faim »

cela lance le plugin qui fait le café sans que le plugin n’ait à traiter toutes les formes de commandes.

Et si on demande : 
>> « combien coute un kilo de café ? » 

cela ne lance pas le café.

L’IA servirait donc à mieux comprendre les commandes.

Quels seraient les autres usages que vous voyez ?

Merci.

**Comment by Potjoe-97** [comment]
Bonjour à tous, je viens de sortir une première version d'un plugin pour Dialoflow, anciennement api.ai. Il y a encore du travail, mais le principe de base fonctionne très bien !

**Comment by ZakourYounse** [comment]
Bonjour , j'ai la conversation sur IA sur Jarvis, et je suis vraiment curieux d'avoir un AI Jarvis.
pour ma part je pense qu'on a une solution . c'est entrainer un système hors RP3 et après avoir le modèle on va l'installer sur raspberry ! comme ca on garde les performances de RP3 utile pour d'autres choses.

**Comment by IPv777** [comment]
En réponse à @Youunesse , il y a [snips.ai](https://snips.ai/) qui peut faire l'affaire :)
J'ai pour ma part migré sur Home-Assistant, donc je ne continue pas ici.
