### ISSUE TITLE
Compatibilité Xiaomi Mi AI Speaker

### ISSUE THREAD

**Issue by kayoo123** [alexylem/jarvis#692]
### Question :

Pensez-vous qu'il soit un jour possible de voir tourner jarvis avec des boitiers dédiés aux assistants vocaux. 
Je pense notamment a la sortie récente de **XIAOMI MI AI SPEAKER** 
[http://www.minimachines.net/actu/xiaomi-mi-ai-speaker-53067](http://www.minimachines.net/actu/xiaomi-mi-ai-speaker-53067)

Juste savoir si le projet est réalisable ou alors il y a trop de contrainte qui font qu'il sera impossible de voir arriver ce projet sur ce genre de périphérique...

**Comment by Oliv4945** [comment]
Salut, je n'avais pas vu l'annonce. Ce n'est pas impossible à faire je pense, mais le temps à y passer dépend beaucoup du matériel employé par Xiaomi.
J'ai hâte de voir les premiers démontages pour avoir plus d'informations :-)

**Comment by wikijm** [comment]
En attendant d'avoir des avancées sur le hack de ce matériel, je clôture l'issue.
Ne pas hésiter à ré-ouvrir si cela évolue 😉
