### ISSUE TITLE
Installer Jarvis via SSH ?

### ISSUE THREAD

**Issue by Hecatonchyr** [alexylem/jarvis#693]
Bonjour, ma question est plutôt simple : est-ce que tout le processus d'installation peut être fait via SSH ? Notamment la fenêtre d'installation grise.

**Comment by wikijm** [comment]
Bonjour @Hecatonchyr,

L'installation et l'utilisation peuvent se faire par SSH car ne nécessitant d'utiliser écran, clavier et/ou suris directement sur le Raspberry ou affilié.

Pour les anglophones, on parlera d'utilisation headless.

**Comment by Hecatonchyr** [comment]
Merci beaucoup pour ces précisions.

Je rencontre un problème probablement du niveau maternel : je suis sur un debian Jessie avec backports Stretch (Linux 4.9), plus précisément un serveur OpenMediaVault (v. 3.0.86). J'ai tout configuré jusqu'à présent en SSH et en étant connecté en tant que root. Ça a toujours marché sauf jusqu'à présent je rencontre deux problèmes :

-J'ai un Jabra Speak 510 connecté en Bluetooth sur le serveur, avec bluez et puleseaudio (j'ai suivi à la lettre l'issue #200 où @alexylem  a décrit toute la procédure qu'il a utilisé. Je suis bien connecté sur le Jabra, mais à chaque fois que je fais une commande pulseaudio (par ex pacmd) le process pulseaudio est tué et je dois le restart à chaque fois avec pulseaudio --start. Je pense que c'est dû au fait que je lance le process en root.

-Je peux pas lancer jarvis.sh en tant que root...

Ma question niveau maternel est donc la suivante : comment je peux me connecter avec un autre user ? J'ai bien créé d'autres users avec permissions ssh, sudo, mais lorsque je me connecte avec en ssh, je n'ai aucun home dir (par ex je vois dans la vidéo d'installation de Jarvis qu' @alexylem  est connecté en tant que pi@raspberry; quand je me connecte avec un user je n'ai aucune info, juste $ (en revanche quand je me connecte en tant que root j'ai root@server avant $) et si je tente de lancer par ex pulseaudio --start, cela ne marche pas avec une erreur de création de home dir. Bref je me noie dans un verre d'eau.

**Comment by Oliv4945** [comment]
Salut @Hecatonchyr, tu peux essayer [cette branche](https://github.com/oliv4945/jarvis/tree/pulesaudio) si tu veux: j'ai fait des modifications pour la compatibilité PulseAudio; il faut par contre installer `mplayer`.

Pour ton soucis de 'root', une solution moche mais rapide est de suprimer le test [ici](https://github.com/alexylem/jarvis/blob/master/jarvis.sh#L64). Sinon tu n'as pas de dossier home créé avec tes utilisateurs car tu ne dois pas utiliser les bon arguments lors de la création, il faut utiliser `-m`, voir [ici](http://www.delafond.org/traducmanfr/man/man8/useradd.8.html)

**Comment by Hecatonchyr** [comment]
Salut @Oliv4945, je n'ai pas de problèmes particuliers avec pulseaudio, mon Jabra se connecte bien automatiquement au serveur "connected to mobile device" dit la voix et reste connecté. Je pense que tous mes problèmes sont liés au fait que je lance tout en root, je vais essayer de créer un user avec le CLI. J'utilise le WebGUI d'OMV pour créer mes users mais il semble terriblement limité et peut être pas tout à fait adapté.

**Comment by Hecatonchyr** [comment]
Bon j'avance avec mon user, j'ai mon home directory, j'ai mon accès ssh.

Quand je lance jarvis.sh, je vais pas plus loin que l'installation des packages manquants, car 3 ne sont pas trouvés par apt-get install : alsamixer aplay et arecord. C'est la première fois que ça me fait ça j'ai pourtant pu installer tous les packages que je voulais avant.

**Comment by Oliv4945** [comment]
Salut, il y a des chances que la solution soit la même qu'[ici](https://github.com/alexylem/jarvis/issues/703#issuecomment-323935632) : `apt-get install alsa-utils`

**Comment by Oliv4945** [comment]
Salut, je clos en attendant ton retour, n'hésites pas à rouvrir
