### ISSUE TITLE
Seul le mot clé est reconnu

### ISSUE THREAD

**Issue by KLF-29** [alexylem/jarvis#694]
Bonjour, 

Avant tout, merci pour le travail effectué, c'est un super outil. Enfin, d'après ce que j'en ai vu sur différents sites, car tout noob que je suis, j'ai du manquer quelque chose pour le faire fonctionner chez moi... :)

Installé sur un Rpi3, avec un micro Asahi Kasei (recommandé sur le site) et un casque (jack).

Problème : Quand je lance Jarvis en mode normal :
1) il ne reconnait pas mon hotword ("un deux trois" pour mes tests), sauf si je met quelque chose devant (genre "bonjour un deux trois"). J'ai compris cela grace au mode "debug" qui m'a permis de voir "no voice before hotword", mais ca m'étonne un peu tout de même.
2) Une fois le mot clé reconnu, il ne reconnait aucun autre mot clé "comment t'appelles tu?" "bonjour" "ca va ?"... => zéro réponse. Même si je met autre chose devant et/ou derriere.

Je le lance donc en mode débug. Et j'ai il me semble une erreur (ou "info" pour le coup) :
`INFO:snowboy:No match - no voice before hotword`

Pour info, voici ce qui est affiché en entier (au début : en mode normal, second lancement en mode débug) : 

> Input File     : 'default' (alsa)
> Channels       : 2
> Sample Rate    : 48000
> Precision      : 16-bit
> Sample Encoding: 16-bit Signed Integer PCM
> 
> In:0.00% 00:00:03.58 [00:00:00.00] Out:144k  [      |      ]        Clip:0
> Done.
> 
> Input File     : 'default' (alsa)
> Channels       : 2
> Sample Rate    : 48000
> Precision      : 16-bit
> Sample Encoding: 16-bit Signed Integer PCM
> 
> In:0.00% 00:00:03.58 [00:00:00.00] Out:144k  [      |      ] Hd:2.6 Clip:0
> Done.
> un deux trois: Hello
> User defined commands:
> *AIDE*                  *BONJOUR*|*SALUT*       *COMMENT*APPELLE*
> *MERCI*                 *AU REVOIR*|*BYE*       ANNULE*|TERMINE*
> ENCORE*                 *TEST*                  *VERSION*
> *REPETE (*) ET (*)      *CA VA*                 >*OUI*
> >*NON*|*PAS*
> un deux trois: Waiting to hear 'un deux trois'
> Maitre: un deux trois
> Maitre: un deux trois
> un deux trois: I did not understand: un deux trois
> Maitre: (timeout)
> un deux trois: Waiting to hear 'un deux trois'
> Maitre: un deux trois
> Maitre: (timeout)
> un deux trois: Waiting to hear 'un deux trois'
> Maitre: un deux trois
> Maitre: (timeout)
> un deux trois: Waiting to hear 'un deux trois'
> Maitre: ^C
> pi@raspberrypi:~/jarvis $ jarvis
> 
> ------------ Config ------------
> jv_branch            master
> jv_version
> jv_arch              armv7l
> jv_os_name           raspbian
> jv_os_version        8
> language             fr_FR
> play_hw              hw:0,0
> rec_hw               hw:1,0
> speaker              ALSA
> microphone           Asahi Kasei Microsystems Co., Ltd
> recorder             sox
> trigger_stt          snowboy
> command_stt          snowboy
> tts_engine           svox_pico
> --------------------------------
> 
> DEBUG: program_startup hook
> DEBUG: start_speaking hook
> un deux trois: Hello
> DEBUG: stop_speaking hook
> User defined commands:
> *AIDE*                  *BONJOUR*|*SALUT*       *COMMENT*APPELLE*
> *MERCI*                 *AU REVOIR*|*BYE*       ANNULE*|TERMINE*
> ENCORE*                 *TEST*                  *VERSION*
> *REPETE (*) ET (*)      *CA VA*                 >*OUI*
> >*NON*|*PAS*
> un deux trois: Waiting to hear 'un deux trois'
> Maitre: (listening...)
> DEBUG: models=un deux trois
> INFO:snowboy:Ticks: [2, 20, 5, -1]
> INFO:snowboy:Keyword 1 detected at time: 2017-08-06 11:33:56
> INFO:snowboy:No match - no voice before hotword
> INFO:snowboy:Keyword 1 detected at time: 2017-08-06 11:34:04
> INFO:snowboy:Keyword 1 detected at time: 2017-08-06 11:34:04
> INFO:snowboy:Keyword 1 detected at time: 2017-08-06 11:34:10
> INFO:snowboy:Ticks status: 2 9 0 1
> DEBUG: modelid=0
> un deux trois
> DEBUG: entering_cmd hook
> Maitre: (listening...)
> DEBUG: models=alexa,georges,snowboy,un deux trois
> INFO:snowboy:Ticks: [2, 20, 5, -1]
> DEBUG: timeout, end of conversation
> DEBUG: listening_timeout hook
> DEBUG: exiting_cmd hook
> un deux trois: Waiting to hear 'un deux trois'
> Maitre: (listening...)
> DEBUG: models=un deux trois
> INFO:snowboy:Ticks: [2, 20, 5, -1]
> INFO:snowboy:Keyword 1 detected at time: 2017-08-06 11:34:32
> INFO:snowboy:Ticks status: 2 1 2 1
> DEBUG: modelid=0
> un deux trois
> DEBUG: entering_cmd hook
> Maitre: (listening...)
> DEBUG: models=alexa,georges,snowboy,un deux trois
> INFO:snowboy:Ticks: [2, 20, 5, -1]
> INFO:snowboy:Keyword 2 detected at time: 2017-08-06 11:34:45
> INFO:snowboy:No match - no voice before hotword
> INFO:snowboy:Keyword 4 detected at time: 2017-08-06 11:34:45
> DEBUG: timeout, end of conversation
> DEBUG: listening_timeout hook
> DEBUG: exiting_cmd hook
> un deux trois: Waiting to hear 'un deux trois'
> Maitre: (listening...)
> DEBUG: models=un deux trois
> INFO:snowboy:Ticks: [2, 20, 5, -1]

Si quelqu'un a une idée de ce que j'ai pu rater, je suis preneur !!
Merci encore pour l'outil, mon objectif est de le pluguer à Jeedom :)

**Comment by Oliv4945** [comment]
Pour ton premier soucis, il faut relancer le wizard pour régler de nouveau les paramètres audio, ou jouer avec 'min_noise_duration_to_start' ou 'min_noise_perc_to_start'.
Pour le deuxième il faut sélectionner autre chose que Snowboy en tant que 'command_stt' car Snowboy ne peut reconnaître qu'un nombre limité de mots pré enregistrés, commence par Bing :)

**Comment by KLF-29** [comment]
Bonjour Oliv4945,
Merci pour ces deux pistes !
J'essaye ça ce soir.
Bonne journée :)
