### ISSUE TITLE
vitesse TTS svox

### ISSUE THREAD

**Issue by Sanyogit** [alexylem/jarvis#696]
Bonjour,

Installé tout fraichement, je viens de mettre en place Jarvis, cependant quand je fais appels aux fonctions TTS, via svox Pico ça parle à 210km/h du coup  je comprend rien...
Testé avec Espeak la vitesse est bonne.
Je n'arrive pas à trouver comment réduire la vitesse de dictée du Svox Pico.
Merci pour ton aide.

**Comment by wikijm** [comment]
Bonjour @Sanyogit,

Merci de transmettre le log comme demandé lors de la création de l'issue.

**Comment by wikijm** [comment]
Je t'invite également à aller voir ces issues :
https://github.com/alexylem/jarvis/issues/319
https://github.com/alexylem/jarvis/issues/245
https://github.com/alexylem/jarvis/issues/218

**Comment by Oliv4945** [comment]
Tu peux essayer de diminuer le paramètres "tempo"

**Comment by Sanyogit** [comment]
Bonjour,
Cela a effectivement résolu mon problème. désolé pour le post et merci beaucoup.
