### ISSUE TITLE
Probleme avec snowboy

### ISSUE THREAD

**Issue by Seeyko** [alexylem/jarvis#698]
Salut alex, en attendant mon raspberry je voulais essayer de l'installer sur une machine virtuelle, j'utilise VMWARE avec debian 8 Jessie.

Aprés l'installation voila ce que j'obtient, je pense que ça vient d'une erreur d'installation de snowboy, j'ai telechargé le wrapper pour python sur le github et je l'ai copié dans /stt_engines/snowboy.

Merci de ton aide !

Waiting to hear 'snowboy'
jarvis: (listening...)
DEBUG: models=snowboy
Traceback (most recent call last):
  File "stt_engines/snowboy/main.py", line 2, in <module>
    import maindecoder_sox as maindecoder # snowboy decoder
  File "/home/jarvis/jarvis/stt_engines/snowboy/maindecoder_sox.py", line 3, in <module>
    import snowboydetect
ImportError: No module named snowboydetect
DEBUG: modelid=-10
ERROR: snowboy recognition failed
HELP: check error message above, if:
IOError: [Errno Invalid input device (no default output device)] -9996
  1) check your mic in Settings / Audio / Mic
  2) reboot your device
  3) report at: https://github.com/alexylem/jarvis/issues/415
IOError: [Errno Invalid sample rate] -9997
  1) check your mic in Settings / Audio / Mic
  2) try uninstalling pulseaudio
  3) try fresh OS install
  4) your mic does not support 16k sampling rate, change mic
  5) report at: https://github.com/alexylem/jarvis/issues/311
IOError: [Errno Unanticipated host error] -9999
  1) your mic is in error state, unplug/replug it
  2) report at https://github.com/alexylem/jarvis/issues/20
Other
  1) report at https://github.com/alexylem/jarvis/issues/new

DEBUG: program_exit hook

**Comment by Oliv4945** [comment]
Comme demandé quand l'issue a été ouverte...Que donne `jarvis -nv` ?

2017-08-12 19:38 GMT+02:00 Seeyko <notifications@github.com>:

**Comment by Seeyko** [comment]
Désolé je pensais que  l'erreur en troubleshooting suffirais...
Malheuresement la vm sur laquel je faisais les test a crash et ne veut plus demarrer, mon raspberry arrive dans 2 jours alors je l'attendrais pour continuais les test avec jarvis..
Désolé pour le thread inutile, a bientot j'espere !
