### ISSUE TITLE
Temps apres trigger

### ISSUE THREAD

**Issue by touf26** [alexylem/jarvis#699]
Bonjour,
j'utilise snowboy et bing et je voulais savoir si on peut réduire le temps entre la détection du hotword et la prise en compte de celui-ci. J 'ai presque 3s avec le / qui s'affiche avant qu'il soit pris en compte.
Merci

**Comment by Oliv4945** [comment]
Comme demandé lors de l'ouverture de l'issue... que donne `jarvis -nv`?

**Comment by touf26** [comment]
![image](https://user-images.githubusercontent.com/4242961/29252564-63396ce6-806a-11e7-9490-42e11eb126d4.png)

**Comment by Oliv4945** [comment]
Est ce que tu peux copier le log complet ? Les infos du début sont importantes aussi. Pour info tu peux copier coller du texte, c'est plus facile 
-- 
Envoyé de mon appareil Android avec K-9 Mail. Veuillez excuser ma brièveté.

**Comment by touf26** [comment]
Je suis sur VNC et le copier coller bug. Je te copie tout le log demain.
Merci

**Comment by Oliv4945** [comment]
Ok, peut-être peux-tu t'y connecter via SSH ?

**Comment by touf26** [comment]
The programs included with the Debian GNU/Linux system are free software;
the exact distribution terms for each program are described in the
individual files in /usr/share/doc/*/copyright.

Debian GNU/Linux comes with ABSOLUTELY NO WARRANTY, to the extent
permitted by applicable law.
Last login: Sat Aug 12 18:43:58 2017 from 192.168.0.12

SSH is enabled and the default password for the 'pi' user has not been changed.
This is a security risk - please login as the 'pi' user and type 'passwd' to set        a new password.

pi@raspberrypi:~ $ jarvis -nv

------------ Config ------------
jv_branch            master
jv_version
jv_arch              armv6l
jv_os_name           raspbian
jv_os_version        8
language             fr_FR
play_hw              false
rec_hw               hw:1,0
speaker              Default
microphone           Asahi Kasei Microsystems Co., Ltd
recorder             sox
trigger_stt          snowboy
command_stt          bing
tts_engine           espeak
--------------------------------

DEBUG: program_startup hook
DEBUG: start_speaking hook
sarah: Bonjour
DEBUG: stop_speaking hook
User defined commands:
*AIDE*                  *BONJOUR*|*SALUT*       *COMMENT*APPELLE*
*MERCI*                 *AU REVOIR*|*BYE*       ANNULE*|TERMINE*
ENCORE*                 *TEST*                  *VERSION*
*REPETE (*) ET (*)      *CA VA*                 >*OUI*
>*NON*|*PAS*
sarah: Waiting to hear 'sarah'
David: (listening...)
DEBUG: models=sarah
INFO:snowboy:Ticks: [2, 20, 5, -1]
INFO:snowboy:Keyword 1 detected at time: 2017-08-14 19:18:11
INFO:snowboy:Ticks status: 2 16 64 1
WARNING:snowboy:No match voice_after

**Comment by touf26** [comment]
voilà par ssh

**Comment by Oliv4945** [comment]
Pas évident, peut-être essayer de descendre le paramètre audio->min_silence_level_to_stop

**Comment by Lusitanos67** [comment]
Hello, j'avais le même soucis.
La seule solution, c'est de désactiver le TICK.

**Comment by touf26** [comment]
Ok merci je vais tester ça
