### ISSUE TITLE
arret jarvis non-voulu

### ISSUE THREAD

**Issue by remjou1** [alexylem/jarvis#70]
depuis quelques temps des fois quand j'utilise jarvis pendant une "conversation" elle m'affiche un "." et s'arrète... par exemple :
```
rèmjou: Bonjour
leia: Bonjour Monsieur vous allez bien ?
rèmjou: .
leia: Waiting to hear 'leia'
```
est-ce du as une mauvaise reconaissance a cause de moi ou est-ce un bug ? merci

**Comment by alexylem** [comment]
Pas un bug, juste le timeout, voir:
https://github.com/alexylem/jarvis/wiki/faq
