### ISSUE TITLE
Problème d'ouverture de _snowboydetect.so 

### ISSUE THREAD

**Issue by Seeyko** [alexylem/jarvis#700]
### Description

Salut, j'ai reçu mon raspberry et j'essaye d'installer jarvis, je préfere utiliser snowboy pour la detection de hotword, j'ai telecharger sur leurs site le package pour raspbian Jessie, je l'ai extrait puis deplacer dans /home/pi/jarvis/stt_engines/snowboy/
Maintenant lorsque je lance Jarvis il ne detecte pas le _snowboydetect.so alors que dans le dossier /home/pi/jarvis/stt_engines/snowboy/ ce fichier est bien présent..

Merci de votre aide !
### Logs
```shell
------------ Config ------------
jv_branch            master 
jv_version            
jv_arch              i686 
jv_os_name           debian 
jv_os_version        8 
language             fr_FR 
play_hw              hw:0,0 
rec_hw               hw:0,0 
speaker              AudioPCI 
microphone            
recorder             sox 
trigger_stt          snowboy 
command_stt          bing 
tts_engine           svox_pico 
--------------------------------

DEBUG: program_startup hook
DEBUG: start_speaking hook
jarvis: Bonjour Tom
DEBUG: stop_speaking hook
User defined commands:
*AIDE*			*BONJOUR*|*SALUT*	*COMMENT*APPELLE*
*MERCI*			*AU REVOIR*|*BYE*	ANNULE*|TERMINE*
ENCORE*			*TEST*			*VERSION*
*REPETE (*) ET (*)	*CA VA*			>*OUI*
>*NON*|*PAS*
jarvis: Waiting to hear 'jarvis'
Tom: (listening...)
DEBUG: models=jarvis
Traceback (most recent call last):
  File "stt_engines/snowboy/main.py", line 2, in <module>
    import maindecoder_sox as maindecoder # snowboy decoder
  File "/home/pi/jarvis/stt_engines/snowboy/maindecoder_sox.py", line 3, in <module>
    import snowboydetect
  File "/home/pi/jarvis/stt_engines/snowboy/snowboydetect.py", line 28, in <module>
    _snowboydetect = swig_import_helper()
  File "/home/pi/jarvis/stt_engines/snowboy/snowboydetect.py", line 24, in swig_import_helper
    _mod = imp.load_module('_snowboydetect', fp, pathname, description)
ImportError: /home/pi/jarvis/stt_engines/snowboy/_snowboydetect.so: cannot open shared object file: No such file or directory
DEBUG: modelid=-10
ERROR: snowboy recognition failed

```

**Comment by wikijm** [comment]
Bonjour @Seeyko,

Pourquoi ne pas utiliser le processus d'installation de Snowboy intégré à Jarvis ?

**Comment by Seeyko** [comment]
Bonjour @wikijm 
Au moment de l'installation il m'a effectivement proposer d'installer jarvis j'ai donc cliquer sur ok mais celui çi m'a répondu qu'il était disponible pour tel tel et tel OS (Raspbian Jessie 8, Mac OSX et un autre je crois) et que si je n'avais pas un de ses os je pouvais le compiler moi-même avec un lien vers le repo github de snowboy. J'ai donc cliqué sur ok et c'est passez a autre chose. (J'ai Raspbian Jessie moi)
Je ne sais pas si c'est de cette installation que tu parle mais elle ne m'a rien installé du tout pour moi...

**Comment by wikijm** [comment]
Jarvis a commencé à être utilisé sur Raspbian Jessie (Full & Lite).
Le plus simple pour toi serait de refaire une installation de zéro, en profitant de l'installation de Snowboy proposée par Jarvis.

Je t'invite également à "filmer" ta ré-installation avec [ASCIINEMA](https://asciinema.org/).
Comme ça, si tu as un soucis on pourra plus facilement l'analyser 😉

**Comment by Seeyko** [comment]
Ok J'vais refaire ça, t'aurais un lien pour l'os le plus probable de fonctionner ?

**Comment by wikijm** [comment]
Oui bien sûr 😃 
https://www.raspberrypi.org/downloads/raspbian/ pour la page de téléchargement.
- Si tu souhaites une version Full (avec le bureau) : https://downloads.raspberrypi.org/raspbian_latest
- Si tu souhaites une version Lite (sans le bureau) : https://downloads.raspberrypi.org/raspbian_lite_latest
