### ISSUE TITLE
Problème à la sortie des Cron avec Jarvis Face!!!

### ISSUE THREAD

**Issue by satana888** [alexylem/jarvis#701]
Plugin parfait! J'ai juste une question a poser? Quand le Cron se met en route le visage reste en mode " speaking"... même après que le message dit dans le Cron soit fini...... il passe en speaking en continu... Que peut on faire ou rajouter dans Cron pour qu'il revienne sur le mode "neutral"? Ou si jamais, j'ai l'intention de passer tout mes Cron sur lecture de fichier .sh.... y'aurai t'il une commande a insèrer dans le fichier .sh pour qu'il retombe chaque fois sur le mode "neutral"? merci d'avance Cordialement

**Comment by wikijm** [comment]
Bonsoir @satana888,

Je t'invite à cliquer sur [ce lien](https://github.com/alexylem/jarvis-face/issues/new) pour créer une nouvelle issue sur le [repo jarvis-face](https://github.com/alexylem/jarvis-face/).

Bonne soirée 😃
