### ISSUE TITLE
Jarvis face et les Cron

### ISSUE THREAD

**Issue by satana888** [alexylem/jarvis#702]
# Plugin parfait!
J'ai juste une question a poser? Quand le Cron se met en route le visage reste en mode " speaking"... même après que le message dit dans le Cron soit fini...... il passe en speaking en continu... Que peut on faire ou rajouter dans Cron pour qu'il revienne sur le mode "neutral"? Ou si jamais, j'ai l'intention de passer tout mes Cron sur lecture de fichier .sh.... y'aurai t'il une commande a insèrer dans le fichier .sh pour qu'il retombe chaque fois sur le mode "neutral"? 

merci d'avance 
 
```

**Comment by Oliv4945** [comment]
Question à demander dans le git du plugin, [ici](https://github.com/alexylem/jarvis-face).

MErci
