### ISSUE TITLE
Unable to locate package Installation Jarvis sur OSMC

### ISSUE THREAD

**Issue by RomainGOU** [alexylem/jarvis#703]
Bonjour,
Je suis actuellement en train d'essayer d'installer Jarvis sur mon raspberry pi sous OSMC mais lors de l'installation, impossible de trouver les packages suivants : 
alsamixer
aplay
arecord

Je reçois l'erreur : 

E: Unable to locate package alsamixer
E: Unable to locate package aplay
E: Unable to locate package arecord

est-ce que quelqu'un pourrait me donner un coup de main ?
En vous remerciant,
Romain

PS : J'ai vu passer quelques messages sur le forum de gents qui ont bien réussi a installer Jarvis sur OSMC.
PS : Oui j'ai cherché des solutions sur le forum et sur internet mais aucunes n'ont marchées (notemment ajouter des dépots dans source.list)

**Comment by Oliv4945** [comment]
Que donne `apt-cache search aplay` ?

**Comment by RomainGOU** [comment]
Lors que je lance la recherche sur les 3 ils n'y sont pas.

*Example pour aplay : 

alsa-utils - Utilities for configuring and using ALSA
alsaplayer-alsa - alsaplayer output module for ALSA
alsaplayer-common - audio player (common files)
alsaplayer-daemon - alsaplayer daemon
alsaplayer-esd - alsaplayer output module for EsounD
alsaplayer-gtk - alsaplayer gtk interface
alsaplayer-jack - alsaplayer output module for JACK
alsaplayer-nas - alsaplayer output module for NAS
alsaplayer-oss - alsaplayer output module for OSS
alsaplayer-text - alsaplayer text interface
alsaplayer-xosd - alsaplayer XOSD display module
libalsaplayer-dev - alsaplayer plugin library (development files)
libalsaplayer0 - alsaplayer plugin library
ecatools - multitrack-capable audio recorder and effect processor (tools)
gecko-mediaplayer - Multimedia plug-in for Gecko browsers
libgmlib-dev - gnome-mplayer library (development files)
libgmlib1 - gnome-mplayer library (shared library)
libgmlib1-dbg - gnome-mplayer library (debugging symbols)
gnome-mplayer - GTK+ interface for MPlayer
gnome-mplayer-dbg - GTK+ interface for MPlayer (debugging symbols)
libkmediaplayer4 - KMediaPlayer Interface for the KDE Platform
pulseaudio-utils - Command line tools for the PulseAudio sound server
splay - Sound player for MPEG-1,2 layer 1,2,3
mahara-mediaplayer - Electronic portfolio, weblog, and resume builder - internal media player

**Comment by RomainGOU** [comment]
Du coup je me doute que le problème viens du fait que je n'ai pas le bon dépot, pourriez vous m'indiquer quel est le dépot a utiliser et comment bien l'ajouter au cas ou je le fasse mal ?

**Comment by Oliv4945** [comment]
Pour t'aider il va falloir tes dépôts actuels :-)
Sur quelle distribution est-ce basé ?

**Comment by RomainGOU** [comment]
OSMC est basé sur Raspbian
Et mes depots sont : 
deb http://ftp.debian.org/debian jessie main contrib non-free
deb http://ftp.debian.org/debian/ jessie-updates main contrib non-free
deb http://security.debian.org/ jessie/updates main contrib non-free
deb http://apt.osmc.tv jessie main
deb http://mirrordirector.raspbian.org/raspbian jessie main contrib non-free rpi
deb http://apt.osmc.tv jessie main
deb http://mirror.internode.on.net/pub/raspbian/raspbian jessie main contrib non-free rpi

**Comment by RomainGOU** [comment]
Personne n'a de solution ?

**Comment by wikijm** [comment]
@RomainGOU Tu as les bons dépôts à mon sens, car je me contente du dépôt en ligne 5 :
> deb http://mirrordirector.raspbian.org/raspbian jessie main contrib non-free rpi)

Les 3 paquets que tu cite sont installables grâce à la commande `sudo apt install alsa-utils`.
Est-ce que tu peux la jouer et nous faire un retour ?

**Comment by RomainGOU** [comment]
You're a genius! ;-)
Ça a marché ! Il ma bien installé les dépendances et Jarvis à réussi a se lancer ! 
Merci mille fois ! 

Pour résumer pour ceux qui essayent d'installer Jarvis sur OSMC : 
Ajouter la ligne :
deb http://mirrordirector.raspbian.org/raspbian jessie main contrib non-free rpi
Dans le fichier /etc/apt/source.list

Lancer le commande :
sudo apt install alsa-utils

Démarrer Jarvis comme indiqué dans le tuto ;-)

**Comment by wikijm** [comment]
Je te conseillerais plutôt de jouer les commandes suivantes :
```bash
echo "Création d'un nouveau fichier listing de dépôt"
echo 'deb deb http://mirrordirector.raspbian.org/raspbian jessie main contrib non-free rpi' >/tmp/myppa.list
echo "Copie du nouveau fichier de dépôt dans /etc/apt/sources.list.d/"
sudo mv /tmp/myppa.list /etc/apt/sources.list.d/
echo "Mise à jour des informations de dépôt "
sudo apt update
echo "Installation du paquet 'alsa-utils' (dont alsamixer, aplay et arecord)"
sudo apt install -y alsa-utils
```
