### ISSUE TITLE
eedomus

### ISSUE THREAD

**Issue by annarol** [alexylem/jarvis#704]
bonjour alex et a tous,

merci pour ce formidable projet opensource.
Une petite question : existe-til un tuto pour integrer/ou piloter une eedomus avec JARVIS ?

Je ne suis ni developpeur ni infor, et a mon age on passe plus de temps dans le jardin que devant son ordi...

en tout cas merci a tous pour vos eclairages

annarol

**Comment by Oliv4945** [comment]
@renault1669 semble avoir fait des choses.
Sinon selon la doc [Eedomus ](http://doc.eedomus.com/index.php/API_eedomus) tu peux utiliser les requêtes HTTP pour contrôler tes périphériques.
par exemple `curl -s https://api.eedomus.com/[request_type]?action=[service.action]&[parameters]`

**Comment by annarol** [comment]
bonjour olivier,4945,
Effectivement j'utilise une requette HTTP /
*ALLUME*CHAUFFAGE==say "Ok" && jv_curl -s https://api.eedomus.com/set?action=periph.value&periph_id=xxxx&value=x&api_user=xxxx&api_secret=xxxxx

periph_id= le code api de mon periph zwave qui controle mon chauffage.
quand j'essaie cette requette dans un navigateur pas de souci cela fonction par contre quand je l'insere dans les commande Jarvis j'ai un message d'erreur : 
DEBUG: stop_speaking hook
DEBUG: curl --silent --fail --show-error -s https://api.eedomus.com/set?action=periph.value
DEBUG: {
   "success": "0",
   "body":
   {
     "error_code": "2",
     "error_msg": "Missing parameter [periph_id]."
   }
j'ai l'impression que ma requete se bloque des le depart 
si toi ou un autre peut aider a reecrire ma requete je lui en serai connaissant;

merci

**Comment by renault1669** [comment]
Effectivement, intégration très simple.

1- A partir du compte EEDOMUS récuper l'URL - API associée à l'action que tu souhaites lancer

--> ACCUEIL --> CONFIGURATION --> MON COMPTE --> Consulter vos identifiants

![capture](https://user-images.githubusercontent.com/7784681/29674313-157a6f24-88f2-11e7-9fb8-dab12083e8ed.PNG)


2- Une fois sur la page 'consulter identifiant', DESTINATION = CLOUD | Direction = SET | ...

![capture1](https://user-images.githubusercontent.com/7784681/29674458-8f3f43e8-88f2-11e7-907a-62abc05735e7.PNG)

3- Copier l'url d'appel de l'API

4- Sous Jarvis : associer à la commande CURL l'url de l'API récupérée depuis EEDOMUS

répéter le processus pour chaque action

Cdlt,
Laurent.

**Comment by renault1669** [comment]
Pour éviter les erreurs de sémantique dans l'appel de l'API, utilises le moteur EEDOMUS de génération automatique. Jamais eu d'erreur de mon côté.
Cdlt,
Laurent.

**Comment by annarol** [comment]
bonsoir laurent,
c'est exactement ce que j'ai fait et j'ai toujours ce msg d'erreur : 
DEBUG: stop_speaking hook
DEBUG: curl --silent --fail --show-error -s https://api.eedomus.com/set?api_user=2S6N8C
DEBUG: {
   "success": "0",
   "body":
   {
     "error_code": "2",
     "error_msg": "Missing parameter [api_secret]."
   }
	}
la tu remarqueras lqu'il manque l'api_secret et lorsque tu lis ma requete c'est la deuxieme parametre qui bloque tout comme lors de ma requete precedente. 
j'en perds mon latin
en tout cas merci de m'aiguiller
roland

**Comment by annarol** [comment]
bonjour a tous,

J'ai ecrit les parametres de ma requete dans tous les sens et teste dans un navigateur web. Elle fonctionne bien. Par contre quand je l'associe a la commande CURL de Jarvis, la commande ne prends pas en compte le 2me parametre de la requete (quelque soit l'ordre des parametres)
Est-ce qu'il n'y aurait pas un argument a ajouter a la commande pour qu'elle prenne en compte tous les parametres ? (style $> en debut de ligne ?)
Pour memoire voila la ligne incriminee dans le fichier Jarvis-commads : 
*ALLUME*CHAUFFAGE==say "Ok" && jv_curl -s https://api.eedomus.com/set?action=periph.value&periph_id=xxxx&value=x&api_user=xxxx&api_secret=xxxxx

Merci de votre soutien 
annarol

**Comment by Oliv4945** [comment]
Essaie de la mettre entre guillemets simples: `'`
Si tu exécutes curl -s http://_ta_requete dans un terminal, est-ce que ça
fonctionne ?

**Comment by annarol** [comment]
Bonjour Olive

Je dois m'absenter je vais essayer vers midi et vous tiens au jus.
merci
annarol

**Comment by annarol** [comment]
rebonjour a tous,
solution trouvéé ; merci olive4945.
en fait il faut encadree la requete par des guillemets et cela fonctionne parfaitement.
voila maintenant je peux jouer avec mon jarvis et ma eedomus!

Un grand merci a tous

annarol 

ps : comment fait on pour clore l'issue ?

**Comment by Oliv4945** [comment]
Il faut cliquer sur "close issue", je l'ai fait.
D'une manière générale sous Linux il est bon d'entourer les paramètres contenant des charactère spéciaux par des quotes

**Comment by annarol** [comment]
ok comme quoi on apprend a tout age
merci pour le coup de main
kenavo
