### ISSUE TITLE
multiple problème lors de l'installation..

### ISSUE THREAD

**Issue by adoublard** [alexylem/jarvis#705]
### Description

Précision : je n'ai pas de micro pour le moment, suis sous Jessie Full.

Lors de l'installation de jarvis, à l'étape TTS, il me dit que svox_pico n'est pas installé et me demande si je veux le faire, donc je lui <oui> et là (1), donc passage sur google.

Choix pour le hotword (il me demande d'en choisir un pour le mode troubleshooting), snowboy non installé et .. (2) donc passage à pocketsphinx.

Lancement en troubleshooting (3) aucun son, passage à espeak pour TTS, relancement du troubleshooting (4) et là il parle, mais ne dit pas le début des phrases.. 
(exemple : 
```
Alex: ca va ?
$> say "Très bien et toi ça va?" => on entend "et toi ça va?"
DEBUG: start_speaking hook
Jarvis: Très bien et toi ça va?
DEBUG: stop_speaking hook
*OUI*                   *NON*|*PAS*
Alex: oui
$> say "ravi de l'entendre" => on entend "l'entendre"
DEBUG: start_speaking hook
Jarvis: ravi de l'entendre
DEBUG: stop_speaking hook
Alex:
)
```
passage à osx_say (pour test), troubleshooting => (5) (rien ne sort)
repassage à google => fonctionne mais comme espeak, que la fin des phrases qui sort..
je ne comprend plus rien, j'arrive à les faire parlers (google et espeak) mais soit j'etend que la fin soit c'est trop lent.. help please :s

### Logs
(1)
```
Updating...
Upgrading...
E: Impossible de récupérer http://archive.raspberrypi.org/debian/pool/main/c/chromium-browser/chromium-browser_60.0.3112.89-0ubuntu0.14.04.1.1010_armhf.deb  Somme de contrôle de hachage incohérente
Hashes of expected file:
SHA256:aeb0d3344a85515adb75e94558325306e9576e54dabf3a83db500e30f5f13c0e
SHA1:865126029b5ceb86f58863f3c41378c446814e55 [weak]
MD5Sum:21ded675fd32def8f6e823b7735e5974 [weak]
Filesize:58358584 [weak]
Hashes of received file:
SHA256:2914431a3a6a10dbb7b76c1b98c4826a50be337d6ab09b946c91fa4856ad5891
SHA1:b0e2f68578f60c5396ad6330e7b1d69461427365 [weak]
MD5Sum:ffc675f81eb1b518b6f7928e4739c7af [weak]
Filesize:43744768 [weak]
Last modification reported: Wed, 23 Aug 2017 15:16:38 +0000
E: Impossible de récupérer certaines archives, peut-être devrez-vous lancer apt-get update ou essayer avec --fix-missing ?
```
(2)
```
Pre-packaged Snowboy binaries only available for: 
Rasbpian 8 Jessie on Raspberry Pi
Ubuntu 12.04 and 14.04 on x86 64bits
Mac OS X
Please use correct distribution or compile your own version of Snowboy:
https://github.com/kitt-ai/snowboy
```
(3)
```
Alex: repete coucou et ok
$> say "${BASH_REMATCH[1]} ${BASH_REMATCH[2]}"
DEBUG: start_speaking hook
Jarvis: coucou ok
utils/utils.sh: ligne 172: google_TTS : commande introuvable
DEBUG: stop_speaking hook
Alex:
```
(4)
```
Alex: repete ok et coucou
$> say "${BASH_REMATCH[1]} ${BASH_REMATCH[2]}"
DEBUG: start_speaking hook
Jarvis: ok coucou
DEBUG: stop_speaking hook
```
(5)
```
Alex: ca va
$> say "Très bien et toi ça va?"
DEBUG: start_speaking hook
Jarvis: Très bien et toi ça va?
utils/utils.sh: ligne 172: osx_say_TTS : commande introuvable
DEBUG: stop_speaking hook
*OUI*                   *NON*|*PAS*
Alex: oui
$> say "ravi de l'entendre"
DEBUG: start_speaking hook
Jarvis: ravi de l'entendre
utils/utils.sh: ligne 172: osx_say_TTS : commande introuvable
DEBUG: stop_speaking hook
Alex:
```

**Comment by adoublard** [comment]
Et lorsque je met le plugin, il ne parle plus du tout..
No mic configured, forcing keyboard mode
DEBUG: program_startup hook
DEBUG: start_speaking hook
Jarvis: Salut !
utils/utils.sh: ligne 172: espeak_TTS : commande introuvable
DEBUG: stop_speaking hook
User defined commands:
*AIDE*                  *BONJOUR*|*SALUT*       *COMMENT*APPELLE*
*MERCI*                 *AU REVOIR*|*BYE*       ANNULE*|TERMINE*
ENCORE*                 *TEST*                  *VERSION*
*REPETE (*) ET (*)      *CA VA*                 >*OUI*
>*NON*|*PAS*
Commands from plugin jarvis-music-player:
*MUSIQUE(*)             *MUSIQUE*
                        *STOP*                  *SUIVANT*
*PRECEDENT*             *ALEATOIRE*             *MAJ*
*DEMUTE*                *MUTE*
Alex:

**Comment by Oliv4945** [comment]
Après avoir fait un essai avec Google en TTS, quel est le contenu de /dev/shm ?
Si tu essais de faire un `aplay /dev.shm/*.mp3` est-ce que tu entends les commandes complètes ?

Est-ce que tu as d'autres logiciels qui tournent ?

**Comment by adoublard** [comment]
pi@raspberrypi:/dev/shm $ ls
au_revoir_alex.mp3                      ravi_de_lentendre.mp3
jarvis.lock                             salut_.mp3
jarvis-say                              tres_bien_et_toi_ca_va.mp3




pi@raspberrypi:/dev/shm $ aplay /dev/shm/*.mp3
Lecture données brutes '/dev/shm/au_revoir_alex.mp3' : Unsigned 8 bit, Fréquence 8000 Hz, Mono
Lecture données brutes '/dev/shm/je_nai_pas_compris_aplay_devshmmp3.mp3' : Unsigned 8 bit, Fréquence 8000 Hz, Mono
Lecture données brutes '/dev/shm/ravi_de_lentendre.mp3' : Unsigned 8 bit, Fréquence 8000 Hz, Mono
Lecture données brutes '/dev/shm/salut_.mp3' : Unsigned 8 bit, Fréquence 8000 Hz, Mono
Lecture données brutes '/dev/shm/tres_bien_et_toi_ca_va.mp3' : Unsigned 8 bit, Fréquence 8000 Hz, Mono
=> je n'entend que des grésillements :(

> Est-ce que tu as d'autres logiciels qui tournent ?
=> nope, rien du tout, même pas le terminal vu que je suis en ssh

**Comment by adoublard** [comment]
J'ai trouvé la cause du problème : le SSH, quand je le fais depuis la rasp direct aucun soucis, j’entends tout.. me reste plus qu'à mettre mon enceinte bluetooth désolé du dérangement..
