### ISSUE TITLE
Aucune sortie de son

### ISSUE THREAD

**Issue by adoublard** [alexylem/jarvis#706]
Salut,

Je cherche à obtenir du son par prise jack ou par bluetooth or, ni l'un ni l'autre ne fonctionne (que cela soit sous jarvis ou sur la rasp en générale..).

Raspberry sous jessie full.

**Comment by wikijm** [comment]
Bonsoir @adoublard,

Le problème apparaissant en dehors de Jarvis, il serait intéressant de commencer par faire des recherches sur les forums spécialisés.
Si tu as rencontré des erreurs ou autres éléments concernant le son après installation de Jarvis, je t'invite alors à :
* Tenter une réinstallation de Jarvis
OU/PUIS
* Tenter une réinstallation complète de Raspbian Jessie Full
OU/PUIS
* Mettre à jour ton système en passant à [Raspbian Stretch Full](https://www.raspberrypi.org/downloads/raspbian/) (2017-08-16)
* Nous fournir les logs comme demandé à la création de l'issue afin que l'on puisse t'aider à analyser la situation

**Comment by adoublard** [comment]
Bonsoir, pour les logs, je ne vois pas lesquels fournir vu que je ne trouve même pas la sortie jack ou que ce soit.. j'arrive à me connecter en bluetooth (depuis l'icone sur raspberry pi 3b) mais pas moyen d'obtenir un son sortant.. je regarderais tout à l'heure pour réinstallation de raspbian puis de jarvis..

**Comment by wikijm** [comment]
Pour la génération de logs, il suffit de lancer Jarvis en mode troubleshooting de cette façon :
`./jarvish.sh -nv`

**Comment by adoublard** [comment]
ah, oui je vois mais vu que le son ne sort que du HDMI je ne vois pas en quoi ça peux aider pour le bluetooth ou prise jack, fin bref, je vais remettre à zéro pour voir, je tiens au courant.

**Comment by wikijm** [comment]
Dans ce cas tu trouveras la réponse ici : https://github.com/alexylem/jarvis/issues/670

**Comment by adoublard** [comment]
Remise à zéro suivie de forcer la sortie en analogique AVANT d'installer jarvis et ça passe.. Merci
