### ISSUE TITLE
Règlage STT

### ISSUE THREAD

**Issue by adoublard** [alexylem/jarvis#707]
### Description
Bonjour,

Après avoir (enfin) reçus mon micro (andoer de la liste), j'ai voulu essayer de suite en vocal, l'installation de snowboy ne marchant pas, je me suis donc tourné vers pocketsphinx (pour le hotword et la reconnaissance des commandes également, j'ai fais aussi des test avec wit pour reconnaissance mais le problème est le même)
Je m'entend bien, mais jarvis n'exécute rien hormis un petit son, en écrivant un "?" dans la console.
Je pense avoir raté une étape mais je ne sais pas laquelle ..

### Logs
```

Jarvis: Waiting to hear 'Jarvis'
Alex: (listening...)
 rec -V1 -q -r 16000 -c 1 -b 16 -e signed-integer --endian little /dev/shm/jarvis-record.wav gain 13 silence 1 0.1 10% 1 0.5 7% pad 0.5 0.5 trim 0 5
DEBUG: speech duration was 15 (10 = 1 sec)
(listening...)
 rec -V1 -q -r 16000 -c 1 -b 16 -e signed-integer --endian little /dev/shm/jarvis-record.wav gain 13 silence 1 0.1 10% 1 0.5 7% pad 0.5 0.5 trim 0 5
DEBUG: speech duration was 13 (10 = 1 sec)
(listening...)
 rec -V1 -q -r 16000 -c 1 -b 16 -e signed-integer --endian little /dev/shm/jarvis-record.wav gain 13 silence 1 0.1 10% 1 0.5 7% pad 0.5 0.5 trim 0 5
DEBUG: speech duration was 17 (10 = 1 sec)
(listening...)
 rec -V1 -q -r 16000 -c 1 -b 16 -e signed-integer --endian little /dev/shm/jarvis-record.wav gain 13 silence 1 0.1 10% 1 0.5 7% pad 0.5 0.5 trim 0 5
DEBUG: speech duration was 12 (10 = 1 sec)
(listening...)
 rec -V1 -q -r 16000 -c 1 -b 16 -e signed-integer --endian little /dev/shm/jarvis-record.wav gain 13 silence 1 0.1 10% 1 0.5 7% pad 0.5 0.5 trim 0 5
DEBUG: speech duration was 17 (10 = 1 sec)
(listening...)
 rec -V1 -q -r 16000 -c 1 -b 16 -e signed-integer --endian little /dev/shm/jarvis-record.wav gain 13 silence 1 0.1 10% 1 0.5 7% pad 0.5 0.5 trim 0 5

```

Merci d'avance à ceux qui essayerons de m'aider :)

**Comment by adoublard** [comment]
Même problèmes avec bing en reconnaissance de commande (qui est en plus limité dans le temps ? :s )

**Comment by adoublard** [comment]
Jarvis: Waiting to hear 'Jarvis'
Alex: (listening...)
 rec -V1 -q -r 16000 -c 1 -b 16 -e signed-integer --endian little /dev/shm/jarvis-record.wav gain 13 silence 1 0.1 10.1% 1 0.5 10.1% pad 0.5 0.5 trim 0 5
DEBUG: speech duration was 15 (10 = 1 sec)
(listening...)
 rec -V1 -q -r 16000 -c 1 -b 16 -e signed-integer --endian little /dev/shm/jarvis-record.wav gain 13 silence 1 0.1 10.1% 1 0.5 10.1% pad 0.5 0.5 trim 0 5
DEBUG: speech duration was 10 (10 = 1 sec)
?(listening...)
 rec -V1 -q -r 16000 -c 1 -b 16 -e signed-integer --endian little /dev/shm/jarvis-record.wav gain 13 silence 1 0.1 10.1% 1 0.5 10.1% pad 0.5 0.5 trim 0 5
DEBUG: speech duration was 15 (10 = 1 sec)
?(listening...)
 rec -V1 -q -r 16000 -c 1 -b 16 -e signed-integer --endian little /dev/shm/jarvis-record.wav gain 13 silence 1 0.1 10.1% 1 0.5 10.1% pad 0.5 0.5 trim 0 5
DEBUG: speech duration was 13 (10 = 1 sec)
?DEBUG: 3 attempts failed, end of conversation

DEBUG: exiting_cmd hook
Jarvis: Waiting to hear 'Jarvis'
Alex: (listening...)


ne marche toujours pas, help svp sinon je tente une remise à zéro :'(

**Comment by adoublard** [comment]
Petit détail que je viens de remarquer, lorsque le micro est branché, jarvis ne parle plus (même en mode keyboard) hormis le fameux "salut" lorsqu'il se lance..

**Comment by adoublard** [comment]
Après une remise à zéro, ne fonctionne toujours pas, j'ai l'impression qu'il ne détecte même pas le "Jarvis", pourtant lors de la config je m'entend bien après avoir parler dans le micro..

De plus, impossible d'installer snowboy pour le hotword (dont, comme j'ai dis plus haut, j'ai l'impression qui n'est pas entendu)
![capture](https://user-images.githubusercontent.com/31312065/29755084-4421c65e-8b92-11e7-9ec8-0d85bcbd0e30.JPG)

pi@raspberrypi:~/jarvis $ jarvis
1/2 Preparation of dependencies
pi@raspberrypi:~/jarvis $


P.S : j'ai ouvert le fichier debian_version dans /etc/ et il me dit version 9.1
S.V.P, j'ai besoin d'aide, depuis deux jours sur le même soucis :/

**Comment by adoublard** [comment]
@alexylem Est-ce normal que l’installation ne fonctionne pas pour raspbian 9.1 ?

**Comment by Oliv4945** [comment]
>Est-ce normal que l’installation ne fonctionne pas pour raspbian 9.1 ?

Oui et non. Raspbian vient juste de passer en version 9, et pour instant Jarvis n'autorise que 8. Est-ce que tu peux essayer de
1. Faire un clone dans un nouveau répertoire. `git clone `
2. Entrer dans ce repertoire
3. Modifier le fichier [stt_engines/snowboy/main.sh, L8](https://github.com/alexylem/jarvis/blob/3abe4dd0f5d4ff1c7807716d120924e9e3c76038/stt_engines/snowboy/main.sh#L8) pour remplacer `"$jv_os_version" == 8` par >= `"$jv_os_version" -ge 8` ?
4. Lancer jarvis avec `./jarvis.sh`

Si ça fonctionne je pousse la modification pour tout le monde. Merci :-)

**Comment by adoublard** [comment]
L'installation se lance ! Je fais de suite les réglages et test.

Merci beaucoup !

**Comment by adoublard** [comment]
Fonctionne, un peu de mal à reconnaitre mon "Jarvis" et il veut que je parle avant de dire la commande MAIS ça fonctionne :) encore merci !

**Comment by Oliv4945** [comment]
@adoublard  super j'ai fait la modif, merci.
Pour ton soucis de détection tu peux essayer de diminuer un peu 'min_noise_duration_to_start/stop'
