### ISSUE TITLE
Only my initial voice commands are working

### ISSUE THREAD

**Issue by FawkseyLady** [alexylem/jarvis#708]
My Jarvis is named Augustus.  

I have set the settings up where I say Hey Augustus and it responds.
However, when I try to speak my second command it isn't working.

I have tried using bing, snowboy (and training the additional commands), and pocketspinx

I know it's not my microphone, because it recognizes when i say Hey Augustus.

I double checked the API keys.

Additionally I tried installing plugins (which should be configured correctly by default) and those aren't working either.  

Can you guys provide advice on how I should proceed here?

**Comment by Oliv4945** [comment]
Hi, as asked when you opened the issue, what is the complete log of `jarvis -nv` ?
When doing that command, do you hear yourself in echo ?

**Comment by olivierpayet974** [comment]
Hi,
For hotword, you have made it on local or on the site https://snowboy.kitt.ai/ ?
On the site you can hear what you said and check that he take all workds said and if voice's record quality is good. 
I sometimes saw that I was saturating during recording during pronunciation.  So I adjusted the volume of recording and I had a better hotword.

**Comment by Oliv4945** [comment]
Given the activity in the issue I close it for now. Please reopen it if you have still have the issue
