### ISSUE TITLE
Jarvis - Problème avec Snowboy

### ISSUE THREAD

**Issue by Valentin02** [alexylem/jarvis#709]
Salut à tous !
Je viens d'installer jarvis (au passage super projet, j'ai hâte que ça marche !), et j'ai voulu paramétrer SNOWBOY pour le magicword Jarvis.
Mais lorsque je lance jarvis en troubleshooting, j'ai l'erreur suivante :
![error](https://user-images.githubusercontent.com/31391455/29816922-6284888c-8cb6-11e7-8e8b-139623658f49.JPG)
Pourtant j'ai bien vérifié mon micro (WEBCAM LOGITECH), il est branché, configuré, et j'entends bien ma voix !
SOX est installé, PULSEAUDIO est lui aussi installé.
Avez-vous une idée d'où cela pourrait venir ? Merci de votre aide !

**Comment by Oliv4945** [comment]
Salut,

On dirait que Snowboy n'est pas installé.
Que donnent les commandes `ls -al stt_engines/snowboy/`, `sudo find / -name 'snowboydetect.py'` et `sudo find / -name '_snowboydetect.so'`

**Comment by Valentin02** [comment]
Salut, merci de ta réponse,
Pour la commande `ls -al stt_engines/snowboy/` :
`ls : cannot access 'stt_engines/snowboy' : No such file or directory`
Pour la commande `sudo find / -name 'snowboydetect.py` :
`/home/pi/snowboy/example/Python3/snowboydetect.py`
`/home/pi/snowboy/example/Python/snowboydetect.py`
Et pour la commande `sudo find / -name '_snowboydetect.so'` :
`/home/pi/snowboy/example/Python3/_snowboydetect.py`
`/home/pi/snowboy/example/Python/_snowboydetect.py`

En fait, en lançant jarvis pour la 1ère fois et en indiquant snowboy comme voice recognition, il m'avait dit qu'il ne le trouvait pas. Il m'a proposé de l'installer. Lorsque j'ai cliqué sur Ok, il m'a dit qu'il n'existait pas pour cette version de raspbian, et que je devais le compiler moi-même.
J'ai donc essayé de l'installer en le clonant à partir de github, et il m'a créé un dossier snowboy dans /home/pi/.
J'ai remarqué qu'un dossier snowboy était aussi présent dans /home/pi/stt_engines/ . 
Dois-je déplacer le dossier snowboy dans ce dernier ?

**Comment by lionelsebert** [comment]
bonjour ,
je rejoint valentin02 super projet et trés beau travail merci.
j'ai exactement le même problème cela fais deux jour que j'essais d'intaller jarvis  je suis votre tuto a la lettre tout ce passe trés bien au debut tout est reconnu micro,hp, etc  mais au moment de l'installation de snowboy  plus rien ,cela s'arrête la il reste bloqué a 1/2 quelque chose et fini il faut dire que suis vraiment vraiment nul en informatique grr je suis perdu 
pourriez vous m'aider Ps:j'ai installé la derniére version de rasbian comme demandé et mise a jour effectué

**Comment by Oliv4945** [comment]
@lionelsebert, @Valentin02 .
Je viens de faire les modifs, je pense que c'était lié à #707 aussi.

Le plus simple est d'effacer le dossier et de recommencez, tenez moi au courant

**Comment by lionelsebert** [comment]
Encore un grand merci je teste cela ce soir

**Comment by Valentin02** [comment]
Merci beaucoup, je teste tout de suite, je te dis quoi...

**Comment by Valentin02** [comment]
Alors je viens de tester, effectivement l'installation se passe très bien, aucun message d'erreur.
Un tout petit peu long au niveau de la reconnaissance vocale, mais on peut dire, CA MARCHE !
Merci beaucoup !!!!!
