### ISSUE TITLE
Parfois les retours à la ligne ne fonctionne plus (en console via ssh)

### ISSUE THREAD

**Issue by pixocode** [alexylem/jarvis#712]
### Description

Parfois les retours à la ligne ne fonctionne plus (en console via ssh)
De plus j'ai l'impression que le script a planté

### Logs
![capture du 2017-08-31 19-01-21](https://user-images.githubusercontent.com/293229/29935414-fc7c2534-8e7e-11e7-9e1d-9508238ee8e2.png)

**Comment by Oliv4945** [comment]
Est-ce que Jarvis fonctionne encore ?
Quel client SSH utilises-tu ?

**Comment by pixocode** [comment]
Oui il fonctionnait, et je n'utilise aucun client ssh en particulier, juste un outil de commande sur ubuntu (terminator)

**Comment by Oliv4945** [comment]
Quel est le shell utilisé ?

**Comment by pixocode** [comment]
Terminator sous Ubuntu

**Comment by Oliv4945** [comment]
Non shell pas terminal ;)
Bash ? Sh ? Je pense que `echo $0` doit pouvoir le dire

**Comment by Oliv4945** [comment]
Clos en attendant une réponse de l'auteur
