### ISSUE TITLE
Sélection du moteur de synthèse vocale au démarrage

### ISSUE THREAD

**Issue by pixocode** [alexylem/jarvis#713]
### Description

Si je lance le script et que je démarre directement Jarvis, j'ai cette erreur.
Par contre si je vais dans le choix du moteur de synthèse vocale et que je reselectionne le moteur déjà sélectionné, là ça fonctionne.

### Logs
```
komassane: Bonjour
utils/utils.sh: ligne 172: google_TTS : commande introuvable
```

**Comment by Oliv4945** [comment]
@catmanng avait eu le même problème dans #654, est-ce que ça a été résolu ?
Avant de lancer Jarvis, quel est le contenu du fichier config/tts_engine ? (`more config/tts_engine`)

**Comment by pixocode** [comment]
Désolé je ne sais plus, j'ai supprimé mon install de jarvis, j'avais vraiment trop de problème avec, je suis parti sur un développement perso de 0 :/
