### ISSUE TITLE
installation ( microphone echo)

### ISSUE THREAD

**Issue by SergeKlutchenko** [alexylem/jarvis#714]
Input File     : 'default' (alsa)
Channels       : 1
Sample Rate    : 16000
Precision      : 16-bit
Sample Encoding: 16-bit Signed Integer PCM

In:0.00% 00:00:03.07 [00:00:00.00] Out:48.0k [-=====|=====-] Hd:0.0 Clip:0    
Done.
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM false
play FAIL formats: can't open output file `default': snd_pcm_open error: No such file or directory

**Comment by Oliv4945** [comment]
As requested when you opened the issue, what is the log of `jarvis -nv` ?

**Comment by wikijm** [comment]
Clôture du ticket jusqu'à obtention d'une réponse de la part de l'auteur de l'issue.
Closing of the ticket until a valid answer from the applicant is obtained.
