### ISSUE TITLE
Accès config en mode service auto

### ISSUE THREAD

**Issue by metamax91** [alexylem/jarvis#715]
Bonjour,

Tout d'abord, merci pour cette excellente solution que j'utilise déjà depuis quelques mois.

Dernièrement, j'avais configuré JARVIS en démarrage automatique en mode service.

Aujourd'hui, je voulais me remettre dans le paramétrage mais impossible d'y accéder.
Lorsque je lance la commande jarvis.sh, le menu ne me permet que de "Show javis output / Listen now for acommand / Pause - Resume / Stop Jarvis".

Une idée sur la façon dont accéder au menu classique et éventuellement de la façon dont stopper le démarrage auto en mode service ?

Merci pour votre aide,

Max

**Comment by Oliv4945** [comment]
Il faut faire "sudo service jarvis stop" ;-)

**Comment by metamax91** [comment]
Merci !! :-)
