### ISSUE TITLE
Snowboy with Respeaker

### ISSUE THREAD

**Issue by marth1974** [alexylem/jarvis#716]
### Description
Bonjour,

je viens d'installer Jarvis sur un Raspberry Zero W sur une image Debian Stretch.
J'utilise un micro ReSpeaker Mic Array (https://www.seeedstudio.com/ReSpeaker-Mic-Array-Far-field-w%2F-7-PDM-Microphones-p-2719.html)

La configuration initiale est faite et semble correcte,
- reconnaissance du magic word par snowboy configuré

Lors du démarrage de Jarvis, j'ai un message d'erreur "snowboy recognition failed"

J'ai essayé avec un autre micro/haut parleur type Polycom en USB, après configuration initiale, même message d'erreur.

Merci pour votre aide.

Mathieu

### Logs
```shell

------------ Config ------------
jv_branch            master
jv_version
jv_arch              armv6l
jv_os_name           raspbian
jv_os_version        9
language             fr_FR
play_hw              hw:1,0
rec_hw               hw:1,0
speaker
microphone
recorder             sox
trigger_stt          snowboy
command_stt          bing
tts_engine           google
--------------------------------

DEBUG: program_startup hook
DEBUG: start_speaking hook
Jarvis: Hello
DEBUG: using cache /dev/shm/hello.mp3
DEBUG: stop_speaking hook
User defined commands:
*AIDE*                  *BONJOUR*|*SALUT*       *COMMENT*APPELLE*
*MERCI*                 *AU REVOIR*|*BYE*       ANNULE*|TERMINE*
ENCORE*                 *TEST*                  *VERSION*
*REPETE (*) ET (*)      *CA VA*                 >*OUI*
>*NON*|*PAS*
Jarvis: Waiting to hear 'Jarvis'
Mathieu: (listening...)
DEBUG: models=jarvis
Traceback (most recent call last):
  File "stt_engines/snowboy/main.py", line 2, in <module>
    import maindecoder_sox as maindecoder # snowboy decoder
  File "/home/pi/jarvis/stt_engines/snowboy/maindecoder_sox.py", line 3, in <module>
    import snowboydetect
  File "/home/pi/jarvis/stt_engines/snowboy/snowboydetect.py", line 28, in <module>
    _snowboydetect = swig_import_helper()
  File "/home/pi/jarvis/stt_engines/snowboy/snowboydetect.py", line 24, in swig_import_helper
    _mod = imp.load_module('_snowboydetect', fp, pathname, description)
ImportError: libpython2.7.so.1.0: cannot open shared object file: No such file or directory
DEBUG: modelid=-10
ERROR: snowboy recognition failed
HELP: check error message above, if:
IOError: [Errno Invalid input device (no default output device)] -9996
  1) check your mic in Settings / Audio / Mic
  2) reboot your device
  3) report at: https://github.com/alexylem/jarvis/issues/415
IOError: [Errno Invalid sample rate] -9997
  1) check your mic in Settings / Audio / Mic
  2) try uninstalling pulseaudio
  3) try fresh OS install
  4) your mic does not support 16k sampling rate, change mic
  5) report at: https://github.com/alexylem/jarvis/issues/311
IOError: [Errno Unanticipated host error] -9999
  1) your mic is in error state, unplug/replug it
  2) report at https://github.com/alexylem/jarvis/issues/20
Other
  1) report at https://github.com/alexylem/jarvis/issues/new

DEBUG: program_exit hook
```
Alternatively attach a terminal session recording using asciinema:
```shell
sudo apt-get install -y asciinema && asciinema rec # start session recording
./jarvish.sh -nv # start jarvis directly in troubleshooting mode
Ctrl+D # stop recording
y # yes to upload and get URL to paste here
```

**Comment by Oliv4945** [comment]
>ImportError: libpython2.7.so.1.0: cannot open shared object file: No such file or directory

It seems that you have not python 2.7 installed, could you try `sudo apt-get install python2.7` ?

**Comment by marth1974** [comment]
Hello, thanks for your answer, i just tried and got:

pi@raspberrypi:~ $ sudo apt-get install python2.7
Reading package lists... Done
Building dependency tree
Reading state information... Done
python2.7 is already the newest version (2.7.13-2).
python2.7 set to manually installed.
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.

Could it e related to Stretch? and to newer version of the package?

Best regards,

Mathieu

**Comment by Oliv4945** [comment]
Salut, je ne pense pas que ce soit lié à Stretch, mais vu que c'est tout nouveau on ne sait jamais...
Quel est le résultat de `sudo find / -name 'libpython2.7.so.1.0'` et `echo $LD_LIBRARY_PATH` ?

**Comment by marth1974** [comment]
Hello,

je viens de faire les test demandé et voici les résultats:

'''shell
root@raspberrypi:/home/pi# find / -name 'libpython2.7.so.1.0'
/usr/lib/arm-linux-gnueabihf/libpython2.7.so.1.0
root@raspberrypi:/home/pi# echo $LD_LIBRARY_PATH

root@raspberrypi:/home/pi#

**Comment by Oliv4945** [comment]
Le problème n'est pas lié à Jarvis là, tu peux essayer [ça](https://stackoverflow.com/questions/20842732/libpython2-7-so-1-0-cannot-open-shared-object-file-no-such-file-or-directory?answertab=active#tab-top)
Sinon il faut chercher sur google `ImportError: libpython2.7.so.1.0: cannot open shared object file: No such file or directory`

**Comment by NYGHOST** [comment]
salut pb lié a strech puisque alsa mixer a été virer ainsi que plusieur driver audio.
repars d'un raspbian de mars ou avril ca marchera par contre la w est moins rapide donc vire les ticks.

**Comment by NYGHOST** [comment]
@alexylem peux tu clores?

**Comment by marth1974** [comment]
Bonjour,

après avoir fait un nouveau apt-get update il a installé de nouveau package qui semble avoir résolu le problème, je n'ai plus de message d'erreur lors du lancement de Jarvis et l'utilisation de snowboy.
La reconnaissance est également fonctionnelle, maintenant il ne me reste plus qu'a trouvé les bon réglage pour une utilization correcte.

Merci pour votre aide.

Mathieu
