### ISSUE TITLE
Jarvis - Répondrait-il à des attaques ultrason ?

### ISSUE THREAD

**Issue by miguipda1** [alexylem/jarvis#717]
Bonjour,

au vu de cet article, Jarvis serait-il concerné par ce genre d'attaque ?
[DolphinAttack](https://korben.info/siri-ultrason-smartphone.htmlurl)

**Comment by Oliv4945** [comment]
Vu que c'est lié à la technologie d'acquisition numérique de la voix, plus communément appelé "micro" oui ça doit fonctionner avec Jarvis.
Si tu veux t'en prémunir il faut que tu arrives à intercaler un filtre 20 kHz sur ton micro ;-)

**Comment by wikijm** [comment]
@miguipda1 J'espère que la réponse apportée par @Oliv4945 répond à ta question 😄
