### ISSUE TITLE
Utiliser le hardware du google home avec Jarvis

### ISSUE THREAD

**Issue by scsifox12** [alexylem/jarvis#718]
Bonjour,
Voici l'idée : J'ai Jeedom sur un NUC dans mon sous-sol. Je voudrais Jarvis au R+1 dans mon salon.
Les solutions : rallonge USB (je pense pas), Bluetooth (même avec la la super clé bluetooth Sena UD100 et une antenne déportée, il m'arrive de perdre temporairement des mi plants). le wifi (à creuser)...
Revenons sur le Bluetooth, après avoir chercher le micro/enceinte qui va bien, émetteur récepteur BT etc...
Le tarif est similaire au Google Home! Bon alors je me dit : le Google Home à quand même 2 micros, un woofer, un tweeter et deux radiateurs passifs, bref du matos pas mal.
Heureux utilisateur de l'aspi Xiaomi grâce au Dr Sarakha63 et l'énorme travail réalisé, c'est que du bonheur.
J'ai donc pensé que "l'on" pourrait faire la même chose avec le Google Home.
Mais je ne suis qu'un utilisateur, je n'ai pas de compétence en hack et détournement d'objet connectée ni en programmation (j'ai déjà du mal à m'en sortir avec les scenarios de Jeedom). Je peux éventuellement faire des tutos (J'ai été rédacteur Technique pendant quelques temps).

Pourquoi ne pas utiliser le Google home comme il a été conçu me direz vous? Hé bien simplement que l'idée du cloud + Google qui écoute et/ou enregistre mes conversations ne me plaît pas du tout!

Mes premières recherche m'ont conduit naturellement sur le forum de Jeedom et il y à déjà des choses qui fonctionnent pour l'interaction avec Jeedom : https://www.jeedom.com/forum/viewtopic.php?f=59&t=28590&start=340.
Ce n'est que le début, mais déjà prometteur!
Je ne possède pas le Google Home mais je pense sérieusement à investir.
J'ai failli acheter le Xiaomi Mi AI speaker (oui, même en mandarin je l'aurais pris, pour 50€...) et le Google Home est arrivé en France alors...
Voilà l'idée, je suis prés à m'investir avec mes maigres capacités, et vous?

Et pour répondre à Oliv4945 : 
ça : https://api.ai/docs/integrations/actions-on-google. Cela devrait aider non?

Et puis ceci : 
https://medium.com/google-cloud/how-to-create-a-custom-private-google-home-action-260e2c512fc
Il est indiqué : (ie. you can use the Action in your own Google Home device, but it will be not publicly available).  (c.-à-d., Vous pouvez utiliser l'Action dans votre propre appareil Google Home, mais ce ne sera pas disponible au public).

Merci
Cdt

**Comment by Oliv4945** [comment]
Bonjour,
>J'ai Jeedom sur un NUC dans mon sous-sol. [...] Bluetooth[...]
Le tarif est similaire au Google Home! 

Tu peux aussi partir sur un rPi 0 + micro + enceinte en solde chez Boulanger si tu veux rogner sur les coûts

>Bon alors je me dit : le Google Home à quand même 2 micros, un woofer, un tweeter et deux radiateurs passifs, bref du matos pas mal.

C'est clair que réutiliser leur matos doit être cool, car fait pour et pas moche. Je suis sur que certains travaillent déjà à essayer de prendre la main dessus (rooter), j'espère que ça arrivera vite. 
J'en achèterai bien un pour lui ouvrir les entrailles mais je manque de temps en ce moment...


>Pourquoi ne pas utiliser le Google home comme il a été conçu me direz vous? Hé bien simplement que l'idée du cloud + Google qui écoute et/ou enregistre mes conversations ne me plaît pas du tout!

Avec Jarvis tu peux utiliser Pocket Sphinx qui permet la reconnaissance offline mais il ne fonctionne pas aussi bien que les serveurs de Google/Microsoft (Bing)/ Amazon.
A tel point que je suis entrain de mettre à jour le STT Google qui m'a l'air plus performant que celui de Microsoft.

>https://www.jeedom.com/forum/viewtopic.php?f=59&t=28590&start=340.
Ce n'est que le début, mais déjà prometteur!

Dans cette intégration le Google Home remplace Jarvis ;-)
Ceci dit tu peux faire pareil dans Jarvis en appelant l'URL Jeedom qui va bien comme [ici](https://github.com/alexylem/jarvis/issues/704) pour Eedomus

Et pour répondre à Oliv4945 :
ça : https://api.ai/docs/integrations/actions-on-google. Cela devrait aider non?
J'avais déjà vu cette vidéo en m'intéressant à api.ai, de mémoire il explique comment remplacer Jarvis, à peu près de la même façon que ton lien précédent mais en utilisant api.ai à la place de IFTTT.

Dans tous les cas si tu veux utiliser le Google Home sans Google les deux moyens que je vois sont:
1. Intercepter les requêtes aux serveurs de Google => Certainement chiffrés donc impossible
2. Rooter le Google Home

**Comment by scsifox12** [comment]
Hello,
Bon c'est clair, c'est que le début, mais j'ai l'impression que beaucoup de monde planche sur le sujet! Donc cool pour la suite j’espère. 
Je suis pas fan de PI a cause des corruptions de carte sd... Je serais plus partant pour un Odroid...
Après avoir lu cet article : https://medium.com/google-cloud/how-to-create-a-custom-private-google-home-action-260e2c512fc
J'ai craqué et acheté une version US pour 97€. Y aura juste à indiquer les paramètres France lors de l'installation avec une adresse gmail toute neuve crée spécialement( Google pourra toujours surveiller une adresse sans activité (mdr) si cela lui fait plaisir).
Je suis allé lire ton lien pour l'Eedomus, Ok, mais mon souci premier, c'est déporter micro/HP de mon NUC...
Après, effectivement dans les premières applications que j'ai pu voir Google Homme remplace Jarvis, mais il me semble avoir lu (Hélas, je ne sais plus où) que quelqu'un avait mélangé les deux, cela donnait une commande du genre : "Ok Google, dis à Jarvis de ...". Même si c'est un peu lourd comme commande, c'est déjà ça...
Bon, plus qu'a attendre de recevoir "mon précieux" dans une dizaine de jours, après on verra ce qu'on peut faire avec...
Quand au root, je suis persuadé qu'il arrivera tôt ou tard...

**Comment by Oliv4945** [comment]
Je ferme en attendant que des solutions existent pour avoir un accès root ou détourner des requêtes. Ne pas hésiter à poster si quelqu'un croise ça.

**Comment by Jean-Bernard-Hallez** [comment]
https://www.androidpit.fr/comment-fabriquer-votre-propre-google-home
