### ISSUE TITLE
snowboy 

### ISSUE THREAD

**Issue by EliottDown** [alexylem/jarvis#719]
### Description

Bonjour, j'ai installer jarvis sur mon raspberry pi 2 dans un premier temp mais snowboy ne detecte pas ou quasi jamais le mots "jarvis" , j'ai déjà tenté de faire le fichier via le site plusieurs fois , sans changement :/ j'ai donc installé jarvis sur mon pi 3 et pareil :/ 
mon microhpone est un conseillé sur ton site  "Andoer Omni-Directional" 
et quand je mets check ticks sur false il active jarvis des que je parle !

### Logs
pi@raspberrypi:~/jarvis $ ./jarvis.sh
Notice: you can use 'jarvis' instead of './jarvis.sh'

------------ Config ------------
jv_branch            master
jv_version
jv_arch              armv7l
jv_os_name           raspbian
jv_os_version        9
language             fr_FR
play_hw              hw:0,1
rec_hw               hw:1,0
speaker              ALSA
microphone           Asahi Kasei Microsystems Co., Ltd
recorder             sox
trigger_stt          snowboy
command_stt          bing
tts_engine           google
--------------------------------

DEBUG: program_startup hook
DEBUG: start_speaking hook
jarvis: Bonjour
DEBUG: using cache /dev/shm/bonjour.mp3
DEBUG: stop_speaking hook
User defined commands:
*AIDE*                  *BONJOUR*|*SALUT*       *COMMENT*APPELLE*
*MERCI*                 *AU REVOIR*|*BYE*       ANNULE*|TERMINE*
ENCORE*                 *TEST*                  *VERSION*
*REPETE (*) ET (*)      *CA VA*                 >*OUI*
>*NON*|*PAS*
jarvis: Waiting to hear 'jarvis'
eliott: (listening...)
DEBUG: models=jarvis
INFO:snowboy:Ticks: [2, 20, 5, -1]
INFO:snowboy:Keyword 1 detected at time: 2017-09-10 07:25:30
INFO:snowboy:Keyword 1 detected at time: 2017-09-10 07:25:33
INFO:snowboy:Keyword 1 detected at time: 2017-09-10 07:25:36
INFO:snowboy:Keyword 1 detected at time: 2017-09-10 07:25:39
INFO:snowboy:Keyword 1 detected at time: 2017-09-10 07:25:43
INFO:snowboy:Keyword 1 detected at time: 2017-09-10 07:25:46
INFO:snowboy:Keyword 1 detected at time: 2017-09-10 07:25:49

jarvis: Waiting to hear 'jarvis'
eliott: (listening...)
DEBUG: models=jarvis
INFO:snowboy:Ticks: [2, 20, 5, -1]
INFO:snowboy:Keyword 1 detected at time: 2017-09-10 07:25:30
INFO:snowboy:Keyword 1 detected at time: 2017-09-10 07:25:33
INFO:snowboy:Keyword 1 detected at time: 2017-09-10 07:25:36
INFO:snowboy:Keyword 1 detected at time: 2017-09-10 07:25:39
INFO:snowboy:Keyword 1 detected at time: 2017-09-10 07:25:52
INFO:snowboy:Keyword 1 detected at time: 2017-09-10 07:25:55
INFO:snowboy:Keyword 1 detected at time: 2017-09-10 07:25:58

**Comment by matrottier** [comment]
j'ai la meme chose.  
du nouveau ?

**Comment by Oliv4945** [comment]
Si vous mettez Bing en trigger stt etc que vous démarrez Jarvis avec `jarvis -nv` est-ce que vous vous entendez bien ?

**Comment by doodz** [comment]
Bonjour,
j'ai le même problème.
je viens de tester avec Bing c'est mieux.

**Comment by wikijm** [comment]
Clôture du ticket jusqu'à obtention d'une réponse de la part de l'auteur de l'issue.
Closing of the ticket until a valid answer from the applicant is obtained.
