### ISSUE TITLE
Peux-ton enlever la répétition de la commande vocale en "mode normale" ?

### ISSUE THREAD

**Issue by olivierpayet974** [alexylem/jarvis#720]
### Description

J'utilise
Hotword : Snowboy
Command : Bing

Lorsque Jarvis reçoit ma commande, il rejoue ce que j'ai dit dans les HP avant de lancé la reconnaissance de la commande.

Je voulais savoir si c'est possible de désactiver cela pour le mode "Normale" ou "Service". 
C'est utile en mode "Troubleshooting" mais pas trop a mon avis pour les autres modes.

**Comment by Oliv4945** [comment]
Salut,

Normalement ça ne devrait pas être le cas , comment lances tu Jarvis ?

**Comment by olivierpayet974** [comment]
./jarvis.sh -v

Puis je précise en mode normale dans le menu.

**Comment by Oliv4945** [comment]
Je pense qu'avec l'option -v il se met en mode débug quelque soit le choix
du menu. Enlève l'option et c'est tout bon :)
Si tu ne veux pas du menu c'est `jarvis -n`

**Comment by olivierpayet974** [comment]
J'ai testé le lancement sans le "-v" et effectivement c'est mieux.

Merci.
