### ISSUE TITLE
Webcam créative live! 

### ISSUE THREAD

**Issue by UsusPhabrys** [alexylem/jarvis#721]
Bonsoir,
En guise de micro je souhaite passer par une webcam Creative labs live! HD en USB ... ce que j'ai sous la main dans l'immédiat mais le wizzard ne reconnait pas le micro

Selection of the microphone device
**** Liste des Périphériques Matériels CAPTURE ****
carte 1: VF0770 [Live! Cam Sync HD VF0770], périphérique 0: USB Audio [USB Audio]
  Sous-périphériques: 1/1
  Sous-périphérique #0: subdevice #0
Indicate the card # to use [0-9]: 1
Indicate the device # to use [0-9]: 0

quand je teste, le micro ne semble pas écouter ...

Quelqu'un a t il une idée ....? OU dois je m'orienter vers un autre micro (pas trop cher) ...

Merci par avance

PS : Superbe projet, mon fils de 11 ans qui découvre a hâte que son papa finalise de tout configurer !

A bientôt

UsusPhabrys

**Comment by olivierpayet974** [comment]
C'est une webcam qui fonctionne bien sur un pc ?

**Comment by UsusPhabrys** [comment]
Bonsoir,
pi@USUS001PI:~ $ lsusb
Bus 001 Device 004: ID 041e:4095 Creative Technology, Ltd Live! Cam Sync HD [VF0770]


elle fonctionne bien sur PC Windows, sur Mac et en GUI sur Raspberry ... mais Jarvis ne semble pas en vouloir ....

un peu comme si on devait initialiser quelque chose pour que le voyant s'allume ... précision en effet le voyant ne s'allume pas... désolé pour l'oubli de cette information.

merci

**Comment by olivierpayet974** [comment]
Hmm,
Le voyant n'est pas important ici. 
Regarde dans l'interface graphique dans les paramètres de son.
En haut tu sélectionnes la webcam et verfie que le niveau n'est pas couper ou sur très faible.
Ca m'est déjà arrivé.

**Comment by UsusPhabrys** [comment]
en effet dans le menu indiqué, je trouve bien la webcam et en allant dans "contrôle" l'option "mic" n'était pas coché.
je re contrôle et je vous redis.

merci pour le tuyau

**Comment by UsusPhabrys** [comment]
pas mieux ... je formate et je repars de zéro ...
je vous tiens au jus

**Comment by UsusPhabrys** [comment]
bonsoir,
je suis reparti de 0 et avec l'adaptateur USB dispo chez electrodepot qui était référencé comme ok... et c'est donc effectivement ok.
encore merci.
Au plaisir

Bonne soirée
Fabrice

**Comment by UsusPhabrys** [comment]
donc je clôture
