### ISSUE TITLE
Changer la langue de Jarvis

### ISSUE THREAD

**Issue by hafidaMAARAF** [alexylem/jarvis#722]
SVP Comment changer le language utilisé par jarvis à partir d'une commande ?!!

**Comment by Oliv4945** [comment]
Bonjour,
Je ne comprends pas bien ce que vous souhaitez faire, pourriez-vous détailler ?

**Comment by hafidaMAARAF** [comment]
Bonjour,
Ce que je veux c'est de changer la langue du français à l'anglais lorsque je dis "Jarvis change de langue" ou un truc pareil.
Merci d'avance

**Comment by hafidaMAARAF** [comment]
*CHANGE LANGUE EN ANGLAIS*== language="$(cat english.txt)" && echo "$language" > config/language && say "xxxxxx" && phrase_misunderstood="I can not understand this command" && echo "$phrase_misunderstood" > config/phrase_misunderstood
