### ISSUE TITLE
erreur 13 sur jarvis API

### ISSUE THREAD

**Issue by julienrat** [alexylem/jarvis#724]
bonjour j'ai une erreur 13 quand je lance la requête 

http://192.168.1.45:8080/?say=coucou
`
{"error": "[Errno 13] Permission denied"}`

**Comment by wikijm** [comment]
Bonjour @julienrat 

Il faudrait commencer par nous dire ce qui tourne sur cette IP et port.

**Comment by julienrat** [comment]
Bonjour !
à cette adresse j'ai le serveur jarvis avec le plugin jarvis api 
 https://github.com/alexylem/jarvis-api

**Comment by wikijm** [comment]
@julienrat 
Peux-tu lancer Jarvis en troubleshooting mode (`./jarvis.sh -v`), retester ta requête et nous transmettre le log généré ?

**Comment by julienrat** [comment]
et hop !

dietpi@DietPi:~/jarvis$ ./jarvis.sh -v
Notice: you can use 'jarvis' instead of './jarvis.sh'
Checking updates for jarvis...Up-to-date
Checking updates for jarvis-api...Up-to-date
Checking updates for jarvis-ephemeride...Up-to-date
Checking updates for jarvis-minuterie...Up-to-date
Checking updates for jarvis-radio...Up-to-date
Checking updates for jarvis-systemd-startup...Up-to-date
Checking updates for jarvis-ui...Up-to-date
Checking updates for jarvis-weather-wunderground-fr...Up-to-date
Checking updates for jarvis-wikipedia...Up-to-date
cat: /proc/asound/card0/usbid: No such file or directory
lsusb: option requires an argument -- 'd'
Usage: lsusb [options]...
List USB devices
  -v, --verbose
      Increase verbosity (show descriptors)
  -s [[bus]:][devnum]
      Show only devices with specified device and/or
      bus numbers (in decimal)
  -d vendor:[product]
      Show only devices with the specified vendor and
      product ID numbers (in hexadecimal)
  -D device
      Selects which device lsusb will examine
  -t, --tree
      Dump the physical USB device hierarchy as a tree
  -V, --version
      Show version of program
  -h, --help
      Show usage and help

------------ Config ------------
jv_branch            master 
jv_version            
jv_arch              armv7l 
jv_os_name           debian 
jv_os_version        8 
language             fr_FR 
play_hw              hw:0,0 
rec_hw               hw:0,0 
speaker              audiocodec 
microphone            
recorder             sox 
trigger_stt          snowboy 
command_stt          bing 
tts_engine           svox_pico 
--------------------------------

DEBUG: program_startup hook
Starting RestAPI server on http://192.168.1.45:8080
Starting User Interface on http://192.168.1.45:8081
DEBUG: start_speaking hook
madame bidouille: Bonjour !
DEBUG: stop_speaking hook
User defined commands:
*AIDE*			*BONJOUR*|*SALUT*	*COMMENT*APPELLE*
*MERCI*			*AU REVOIR*|*BYE*	ANNULE*|TERMINE*
ENCORE*			*TEST*			*VERSION*
*REPETE (*) ET (*)	*CA VA*			>*OUI*
>*NON*|*PAS*		*ALLUME LE BAR*
Commands from plugin jarvis-ephemeride:
*FETE*JOUR*|*LA*SAINT*|
Commands from plugin jarvis-radio:
*STOP*RADIO*		*LISTE*RADIO*		*VOLUME*MOINS*RADIO
*VOLUME*PLUS*RADIO	*LANCE*RADIO*		>(*)
			
Commands from plugin jarvis-api:

Commands from plugin jarvis-systemd-startup:

Commands from plugin jarvis-minuterie:
*EFFACE*MINUTE*		*MINUTE*		>(*)
Commands from plugin jarvis-ui:
*OUVR*INTERFACE*
Commands from plugin jarvis-weather-wunderground-fr:
*METEO*DEMAIN*		*METEO*
Commands from plugin jarvis-wikipedia:
*DONNE*DEFINITION*DE (*
madame bidouille: Waiting to hear 'madame bidouille'
julien: (listening...)
DEBUG: models=madame bidouille
INFO:snowboy:Ticks: [2, 20, 5, -1]
192.168.1.39 - - [22/Sep/2017 08:01:46] "GET /?say=coucou HTTP/1.1" 400 -
ERROR: [Errno 13] Permission denied
192.168.1.39 - - [22/Sep/2017 08:01:46] "GET /favicon.ico HTTP/1.1" 400 -
ERROR: Don't know what to do with: {}
^CStopping HTTP server

DEBUG: program_exit hook

**Comment by olivierpayet974** [comment]
Tu as quoi quand tu fais http://192.168.1.39/ depuis ton navigateur ?

**Comment by julienrat** [comment]
c'est mon adresse ip

**Comment by olivierpayet974** [comment]
Pardon.
C'est ca, tu as quoi pour la http://192.168.1.45:8080/
Depuis un navigateur ?

**Comment by julienrat** [comment]
Ce site est inaccessible

192.168.1.45 n'autorise pas la connexion.
Effectuez une recherche Google sur 192 168 8080.
ERR_CONNECTION_REFUSED

**Comment by julienrat** [comment]
plus clairement, 
quad je fais cette requête http://192.168.1.45:8080/
j'obtiens dans mon navigateur 
{"error": "Don't know what to do with: {}"}

**Comment by julienrat** [comment]
en cherchant un peu et en lançant jarvis en root pour tester ces histoires de permissions  (j'ai shunté la vérif dans le code) j'obtiens des choses intéressantes 
à la commande `http://192.168.1.45:8080/?say=coucou`
j'obtiens 

 `{"error": "Command '['jarvis', '-j', '-s', 'coucou']' returned non-zero exit status 1"}`

**Comment by julienrat** [comment]
et le log 

dietpi@DietPi:~/jarvis$ sudo ./jarvis.sh -v
Notice: you can use 'jarvis' instead of './jarvis.sh'
cat: /proc/asound/card0/usbid: No such file or directory
lsusb: option requires an argument -- 'd'
Usage: lsusb [options]...
List USB devices
  -v, --verbose
      Increase verbosity (show descriptors)
  -s [[bus]:][devnum]
      Show only devices with specified device and/or
      bus numbers (in decimal)
  -d vendor:[product]
      Show only devices with the specified vendor and
      product ID numbers (in hexadecimal)
  -D device
      Selects which device lsusb will examine
  -t, --tree
      Dump the physical USB device hierarchy as a tree
  -V, --version
      Show version of program
  -h, --help
      Show usage and help

------------ Config ------------
jv_branch            master 
jv_version           17.08.29 
jv_arch              armv7l 
jv_os_name           debian 
jv_os_version        8 
language             fr_FR 
play_hw              hw:0,0 
rec_hw               hw:0,0 
speaker              audiocodec 
microphone            
recorder             sox 
trigger_stt          snowboy 
command_stt          bing 
tts_engine           svox_pico 
--------------------------------

DEBUG: program_startup hook
Starting RestAPI server on http://192.168.1.45:8080
Starting User Interface on http://192.168.1.45:8081
DEBUG: start_speaking hook
madame bidouille: Bonjour !
DEBUG: stop_speaking hook
User defined commands:
*AIDE*			*BONJOUR*|*SALUT*	*COMMENT*APPELLE*
*MERCI*			*AU REVOIR*|*BYE*	ANNULE*|TERMINE*
ENCORE*			*TEST*			*VERSION*
*REPETE (*) ET (*)	*CA VA*			>*OUI*
>*NON*|*PAS*		*ALLUME LE BAR*
Commands from plugin jarvis-ephemeride:
*FETE*JOUR*|*LA*SAINT*|
Commands from plugin jarvis-radio:
*STOP*RADIO*		*LISTE*RADIO*		*VOLUME*MOINS*RADIO
*VOLUME*PLUS*RADIO	*LANCE*RADIO*		>(*)
			
Commands from plugin jarvis-api:

Commands from plugin jarvis-systemd-startup:

Commands from plugin jarvis-minuterie:
*EFFACE*MINUTE*		*MINUTE*		>(*)
Commands from plugin jarvis-ui:
*OUVR*INTERFACE*
Commands from plugin jarvis-weather-wunderground-fr:
*METEO*DEMAIN*		*METEO*
Commands from plugin jarvis-wikipedia:
*DONNE*DEFINITION*DE (*
madame bidouille: Waiting to hear 'madame bidouille'
julien: (listening...)
DEBUG: models=madame bidouille
INFO:snowboy:Ticks: [2, 20, 5, -1]
ERROR: Jarvis must not be used as root
192.168.1.97 - - [22/Sep/2017 10:39:42] "GET /?say=coucou HTTP/1.1" 400 -
ERROR: Command '['jarvis', '-j', '-s', 'coucou']' returned non-zero exit status 1
192.168.1.97 - - [22/Sep/2017 10:39:42] "GET /favicon.ico HTTP/1.1" 400 -
ERROR: Don't know what to do with: {}

**Comment by julienrat** [comment]
La fonction "get commands" fonctionne pourtant
 `http://192.168.1.45:8080/?action=get_commands`

réponse dans le navigateur 
`{"commands": "*AIDE*==jv_display_commands\n*BONJOUR*|*SALUT*==say \"Bonjour $username\"\n*COMMENT*APPELLE*==say \"Je m'appelle $trigger\"\n*MERCI*==say \"De rien\"\n*AU REVOIR*|*BYE*==say \"Au revoir $username\"; jv_exit\nANNULE*|TERMINE*==bypass=false; say \"Ok\"\nENCORE*==jv_repeat_last_command\n*TEST*==say \"Ca fonctionne!\"\n*VERSION*==say \"Je suis en version $jv_version\"\n*REPETE (*) ET (*)==say \"(1) (2)\"\n*CA VA*==say \"Tr\u00e8s bien et toi \u00e7a va?\"\n>*OUI*==say \"ravi de l'entendre\"\n>*NON*|*PAS*==say \"j'en suis navr\u00e9\"\n*ALLUME LE BAR*==say \"oui le bar c'est une superbe id\u00e9e\"\n"}`


On dirait que l'erreur 13 vient du fait que jarvis n'autorise pas la lecture de la voix sur l'audio
 ...

**Comment by Oliv4945** [comment]
Que donnent la commande `jarvis -j -s coucou` ?

**Comment by julienrat** [comment]
Jarvis me répond coucou  ;-)

dietpi@DietPi:~/jarvis$ ./jarvis.sh -j -s coucou
[{"debug":"Notice: you can use 'jarvis' instead of './jarvis.sh'"},{"answer":"coucou"}]

**Comment by julienrat** [comment]
c'est ici que bloque `{"error": "[Errno 13] Permission denied"}`
https://github.com/alexylem/jarvis-api/blob/ee7d0139b87846130d3f7833db89403b9f0086df/server.py#L145

**Comment by Oliv4945** [comment]
C'est marrant on dirait un problème de droits. Que donnent les commandes suivantes, dans le répertoire de Jarvis:
`
ls -al ./
ls -al /dev/shm/
sudo ps -aux | grep inet_gehost # Avec jarvis démarré dans un autre terminal
`

**Comment by julienrat** [comment]
dietpi@DietPi:~/jarvis$ ls -al ./ ls -al /dev/shm/
ls: cannot access ls: No such file or directory
./:
total 6864
drwxrwxrwx 21 www-data dietpi    4096 Sep 22 11:06 .
drwxrwxrwx  8 dietpi   dietpi    4096 Sep 22 10:25 ..
-rwxrwxrwx  1 www-data dietpi    4215 Sep 20 14:28 CHANGELOG.md
drwxrwxrwx  2 www-data dietpi    4096 Sep 22 10:34 config
-rwxrwxrwx  1 www-data dietpi     118 Sep 20 14:28 CONTRIBUTING.md
drwxrwxrwx  2 www-data dietpi    4096 Sep 20 14:28 defaults
drwxrwxrwx  2 www-data dietpi    4096 Sep 20 14:28 docs
drwxrwxrwx  8 www-data dietpi    4096 Sep 20 14:37 .git
-rwxrwxrwx  1 www-data dietpi     595 Sep 20 14:28 .gitignore
drwxrwxrwx  2 www-data dietpi    4096 Sep 20 14:37 hooks
drwxrwxrwx  5 www-data dietpi    4096 Sep 20 14:28 imgs
-rwxrwxrwx  1 www-data dietpi     619 Sep 20 14:28 ISSUE_TEMPLATE.md
-rwxrwxrwx  1 www-data dietpi     548 Sep 20 19:21 jarvis-commands
-rwxrwxrwx  1 www-data dietpi    2090 Sep 20 14:37 jarvis-events
-rw-r--r--  1 dietpi   dietpi     717 Sep 22 11:09 jarvis.log
-rwxrwxrwx  1 www-data dietpi   20065 Sep 22 10:25 jarvis.sh
-rwxrwxrwx  1 www-data dietpi    1082 Sep 20 14:28 LICENSE.md
-rwxrwxrwx  1 www-data dietpi     187 Sep 20 14:46 my-functions.sh
drwxrwxrwx  3 www-data dietpi    4096 Sep 20 15:30 node_modules
drwxrwxrwx  2 www-data dietpi    4096 Sep 22 10:48 plugins_enabled
drwxrwxrwx  3 www-data dietpi    4096 Sep 22 10:48 plugins_installed
-rwxrwxrwx  1 www-data dietpi      11 Sep 22 11:20 plugins_order.txt
-rwxrwxrwx  1 www-data dietpi    2983 Sep 20 14:28 README.md
drwxrwxrwx  4 www-data dietpi    4096 Sep 20 14:28 recorders
-rwxrwxrwx  1 www-data dietpi     222 Mar 24 18:23 ._rpi-arm-raspbian-8.0-1.1.1
drwxrwxrwx  3 www-data dietpi    4096 Mar 24 18:23 rpi-arm-raspbian-8.0-1.1.1
-rwxrwxrwx  1 www-data dietpi 3452360 Mar 24 18:26 rpi-arm-raspbian-8.0-1.1.1.tar.bz2
drwxrwxrwx 11 www-data dietpi    4096 Sep 20 15:54 snowboy
drwxrwxrwx  2 www-data dietpi    4096 Sep 20 14:28 sounds
drwxrwxrwx  9 www-data dietpi    4096 Sep 20 16:39 sphinxbase-5prealpha
-rwxrwxrwx  1 www-data dietpi 3401241 Sep 25  2016 sphinxbase-5prealpha.tar.gz
drwxrwxrwx  7 www-data dietpi    4096 Sep 20 16:34 stt_engines
drwxrwxrwx 12 www-data dietpi    4096 Sep 20 16:57 swig
drwxrwxrwx  2 www-data dietpi    4096 Sep 20 14:28 test
drwxrwxrwx  7 www-data dietpi    4096 Sep 20 14:28 tts_engines
-rwxrwxrwx  1 www-data dietpi    1199 Sep 20 14:28 uninstall.sh
-rwxrwxrwx  1 www-data dietpi     521 Sep 20 14:28 update.sh
drwxrwxrwx  2 www-data dietpi    4096 Sep 20 14:28 utils
-rwxrwxrwx  1 www-data dietpi       9 Sep 20 14:28 version.txt

/dev/shm/:
total 48
drwxrwxrwt  2 dietpi root     120 Sep 22 10:59 .
drwxr-xr-x 13 dietpi root    3620 Sep 22 10:57 ..
-rw-r--r--  1 dietpi dietpi     5 Sep 22 11:20 jarvis.lock
-rw-r--r--  1 dietpi dietpi     0 Sep 22 11:20 jarvis-order
prw-r--r--  1 dietpi dietpi     0 Sep 22 11:09 jarvis-say
-rw-r--r--  1 dietpi dietpi 41260 Sep 22 11:20 tts.wav
dietpi@DietPi:~/jarvis$

**Comment by julienrat** [comment]
dietpi@DietPi:~/jarvis$ sudo ps -aux | grep inet_gehost 
dietpi    4111  0.0  0.1   3668   752 pts/1    S+   11:32   0:00 grep inet_gehost
dietpi@DietPi:~/jarvis$

**Comment by julienrat** [comment]
`dietpi@DietPi:~/jarvis$ sudo ps -aux | grep inet_gehost `
`dietpi    4111  0.0  0.1   3668   752 pts/1    S+   11:32   0:00 grep inet_gehost`

**Comment by julienrat** [comment]
bon je réinstalle le tout ...

**Comment by Oliv4945** [comment]
Ooops, j'ai fait le copier coller un peu vite : `sudo ps -aux | grep jarvis`. Pour les ls c'est deux distincts `ls -al ./` et `ls -al /dev/shm/`, je ne sais pas pourquoi les retours à la ligne de mon message ne sont pas passés

**Comment by wikijm** [comment]
Clôture du ticket jusqu'à obtention d'une réponse de la part de l'auteur de l'issue.
Closing of the ticket until a valid answer from the applicant is obtained.
