### ISSUE TITLE
micro non reconnu

### ISSUE THREAD

**Issue by titi4516** [alexylem/jarvis#726]
### Description

Français and English are allowed.
Detailed description of your problem.
In case of feature request, please provide justification & example of usage.

### Logs
```shell
<PASTE HERE> full content of the terminal with Jarvis in troubleshooting mode
(keep triple quotes above and below to preserve formatting) 
```
Alternatively attach a terminal session recording using asciinema:
```shell
sudo apt-get install -y asciinema && asciinema rec # start session recording
./jarvish.sh -nv # start jarvis directly in troubleshooting mode
Ctrl+D # stop recording
y # yes to upload and get URL to paste here
```

**Comment by titi4516** [comment]
bonjour,
comme conseillé, j'ai acheté le micro Andoer 150cm Portable Mini Clip-on Omni-Directional.
mais lors de l'installation, le micro n'a pas l"air d'être détecté, avez-vous une idée?

**Comment by wikijm** [comment]
Bonsoir @titi4516
Merci de fournir le log comme demandé lors de la création de l'issue.

**Comment by wikijm** [comment]
Clôture du ticket jusqu'à obtention d'une réponse de la part de l'auteur de l'issue.
Closing of the ticket until a valid answer from the applicant is obtained.
