### ISSUE TITLE
Problème de reconnaissance de commandes avec SOX

### ISSUE THREAD

**Issue by jerem945** [alexylem/jarvis#728]
Hello,

Tout d'abord merci pour ce formidable projet, je pense que je vais m'éclater :)

Voici mon problème : 
La reconnaissance vocale de mon hotword ainsi que les commandes au clavier fonctionnent.
En revanche, pour la reconnaissance vocale des commandes, c'est plus difficile.

### Cas 1 : 
avec snowboy comme "recorder" : OK
J'arrive à lui donner les commandes de bases (test, bonjour...) mais ça se limite à ça puisqu'on ne bénéficie pas de Bing (si j'ai bien compris ?)

Voici la configuration : 
```------------ Config ------------
jv_branch            master 
jv_version            
jv_arch              armv7l 
jv_os_name           raspbian 
jv_os_version        9 
language             fr_FR 
play_hw              false 
rec_hw               false 
speaker              Default 
microphone           Default 
recorder             snowboy 
trigger_stt          snowboy 
command_stt          bing 
tts_engine           svox_pico 
--------------------------------
```

### Cas 2 : 
avec sox comme "recorder" : KO 
Le hotword est reconnu, jarvis passe en mode LISTENING mais aucune commande ne semble être entendue...
Voici la configuration  : 

```------------ Config ------------
jv_branch            master 
jv_version            
jv_arch              armv7l 
jv_os_name           raspbian 
jv_os_version        9 
language             fr_FR 
play_hw              false 
rec_hw               false 
speaker              Default 
microphone           Default 
recorder             sox
trigger_stt          snowboy 
command_stt          bing 
tts_engine           svox_pico 
--------------------------------
```

Ainsi que l'output en mode debug : 

```DEBUG: program_startup hook
ERROR: Jarvis-UI requires Jarvis-API plugin to be installed and enabled
DEBUG: start_speaking hook
norda: Salut
DEBUG: stop_speaking hook
User defined commands:
*AIDE*			*BONJOUR*|*SALUT*	*COMMENT*APPELLE*
*MERCI*			*AU REVOIR*|*BYE*	ANNULE*|TERMINE*
ENCORE*			*TEST*			*VERSION*
*REPETE (*) ET (*)	*CA VA*			>*OUI*
>*NON*|*PAS*
Commands from plugin jarvis-ui:
*OUVR*INTERFACE*
norda: Waiting to hear 'norda'
jeremy: (listening...)
DEBUG: models=norda
INFO:snowboy:Ticks: [2, 20, 5, -1]
INFO:snowboy:Keyword 1 detected at time: 2017-09-30 17:24:59
INFO:snowboy:Ticks status: 2 1 0 1
DEBUG: modelid=0
norda
DEBUG: entering_cmd hook
DEBUG: start_speaking hook
norda: Oui?
DEBUG: stop_speaking hook
jeremy: (listening...)
DEBUG: start_speaking hook ""
utils/timeout.sh 10 rec -V1 -q -r 16000 -c 1 -b 16 -e signed-integer --endian li
ttle /dev/shm/jarvis-record.wav gain 0 silence 1 0.1 0.1% 1 0.5 0.1% pad 0.5 0.5
 trim 0 5
DEBUG: speech duration was 50 (10 = 1 sec)
WARNING: too long for a command (max 4 secs), ignoring...
HELP: try in order the following options
1) wait longer between voice commands
2) reduce ambiant background noise
3) decrease mic sensitivity in Settings > Audio
4) increase Min Silence Level to Stop
DEBUG: stop_listening hook
(listening...)
DEBUG: start_speaking hook ""
utils/timeout.sh 10 rec -V1 -q -r 16000 -c 1 -b 16 -e signed-integer --endian li
ttle /dev/shm/jarvis-record.wav gain 0 silence 1 0.1 0.1% 1 0.5 0.1% pad 0.5 0.5
 trim 0 5
^C
```

Voilà...si quelqu'un a une idée, je suis preneur ! 

Par avance, merci :)

Jerem945

**Comment by Oliv4945** [comment]
Salut,
Il y a un petit indice dans le log :)
```
3) decrease mic sensitivity in Settings > Audio
4) increase Min Silence Level to Stop
```
3) Diminuer le paramètre "sensivity" dans settings-> audio
4) Augmenter "min silence level to stop" au même endroit.

Globalement il doit y avoir un peu trop de bruit de fond et Jarvis ne sait pas vraiment quand est la fin du texte.
Sinon tu peux aussi tenter de faire `play /dev/shm/jarvis-record.wav` pour écouter ce que Jarvis a entendu

**Comment by jerem945** [comment]
Salut ! 

Merci pour ton aide.
Je ne peux pas régler la sensibilité, j'ai un message d'erreur : 
```pi@raspberrypi:~ $ jarvis
index de carte invalide: s
essayez `alsamixer --help' pour plus d'information
ERROR: check above
```

En revanche je commence à avoir des résultats en jouant avec le "min silence level to start" et le "min silence level to stop", Thank's ! :)

Pas mal l'astuce du jarvis-record.wav c'est vraiment pratique, ça permet de mieux cerner le réglage à effectuer.

**Comment by Oliv4945** [comment]
Est-ce que tu peux nous donner le résultat de `jarvis -nv` avec ta configuration actuelle ?

**Comment by Oliv4945** [comment]
Je ferme en attendant une réponse, ne pas hésiter à rouvrir

**Comment by ze4lk** [comment]
Moi j'obtient ça
`jarvis: Waiting to hear 'jarvis'
Gaspard: (listening...)
DEBUG: models=jarvis
INFO:snowboy:Ticks: [2, 20, 5, -1]
INFO:snowboy:Keyword 1 detected at time: 2018-01-08 18:53:24
INFO:snowboy:Ticks status: 2 2 13 1
WARNING:snowboy:No match voice_after
INFO:snowboy:Keyword 1 detected at time: 2018-01-08 18:53:50
INFO:snowboy:Ticks status: 2 1 1 1
DEBUG: modelid=0
jarvis
DEBUG: entering_cmd hook
Gaspard: (listening...)
DEBUG: start_speaking hook ""
utils/timeout.sh 10 rec -V1 -q -r 16000 -c 1 -b 16 -e signed-integer --endian little /dev/shm/jarvis-record.wav gain 20 silence 1 0.1 0.1% 1 0.5 0.1% pad 0.5 0.5 trim 0 5
DEBUG: speech duration was 50 (10 = 1 sec)
WARNING: too long for a command (max 4 secs), ignoring...
HELP: try in order the following options
1) wait longer between voice commands
2) reduce ambiant background noise
3) decrease mic sensitivity in Settings > Audio
4) increase Min Silence Level to Stop
DEBUG: stop_listening hook
(listening...)
DEBUG: start_speaking hook ""
utils/timeout.sh 10 rec -V1 -q -r 16000 -c 1 -b 16 -e signed-integer --endian little /dev/shm/jarvis-record.wav gain 20 silence 1 0.1 0.1% 1 0.5 0.1% pad 0.5 0.5 trim 0 5
DEBUG: speech duration was 50 (10 = 1 sec)
WARNING: too long for a command (max 4 secs), ignoring...
HELP: try in order the following options
1) wait longer between voice commands
2) reduce ambiant background noise
3) decrease mic sensitivity in Settings > Audio
4) increase Min Silence Level to Stop
DEBUG: stop_listening hook
(listening...)
DEBUG: start_speaking hook ""
utils/timeout.sh 10 rec -V1 -q -r 16000 -c 1 -b 16 -e signed-integer --endian little /dev/shm/jarvis-record.wav gain 20 silence 1 0.1 0.1% 1 0.5 0.1% pad 0.5 0.5 trim 0 5
DEBUG: speech duration was 50 (10 = 1 sec)
WARNING: too long for a command (max 4 secs), ignoring...
HELP: try in order the following options
1) wait longer between voice commands
2) reduce ambiant background noise
3) decrease mic sensitivity in Settings > Audio
4) increase Min Silence Level to Stop
DEBUG: stop_listening hook
DEBUG: 3 attempts failed, end of conversation

DEBUG: exiting_cmd hook
jarvis: Waiting to hear 'jarvis'
Gaspard: (listening...)
DEBUG: models=jarvis
INFO:snowboy:Ticks: [2, 20, 5, -1]

`
