### ISSUE TITLE
Ou est Alex ?

### ISSUE THREAD

**Issue by Lusitanos67** [alexylem/jarvis#729]
Bonjour,

Cela fait un moment qu'Alex a disparu ?!
J'ai l'impression que Oliv le remplace mais c'est vrai que l'on a moins de mise à jours, corrections ou nouvelles fonctionnalités et je reprends que cela doit prendre énormément de temps.

N'ayant pas trouvé comment contacter directement les personnes concernées j'écris ici mon message, en espérant que quelqu'un puisse m'expliquer pourquoi ?
(Surtout pas peur également que le projet finisse sous l'eau).

Merci

**Comment by wikijm** [comment]
Bonsoir @Lusitanos67,

Je comprends ton inquiétude, mais de mémoire la dernière fois où la question s'était posée, notre cher @alexylem avait pris un repos bien mérité 😉 

Qu'appelle tu un moment ?

**Comment by wikijm** [comment]
Simple curiosité :
Sais-tu que sur GitHub, tout utilisateur recevra ton message par e-mail si tu écrit '@' suivi de son pseudo ?

**Comment by Oliv4945** [comment]
Salut,

Effectivement je lui ai demandé récemment aussi et il n'a pas disparu, mais il y a des moments ou les priorités changent temporairement :-)
Pour ma part j'essaie d'aider un peu et de fixer quelques bugs mais j'ai du mal à faire plus, c'est con y'a tellement d'idées à ajouter...

**Comment by Lusitanos67** [comment]
MErci pour l'info @wikijm .
@Oliv4945 merci d'avoir pris le temps également de me répondre. C'est bête en effet, car on voit tellement de chose, nouvelle techno à côté de ce projet qui prolifère à gauche à droite, c'est bête de ne pas accroché le wagon. Je conçois qu'il y a des priorités, j'ai d'ailleurs moi aussi dû apprendre à en faire, et au delà d'un acte égoïste qui voudrait juste que les "autres" se bougent pour que cela avance, je ne peux moi non plus consacrer du temps à ce projet (je suis également dev, sur d'autre plateforme).

Mais c'est une change que tu sois là avec @wikijm afin de continuer à faire évolué le truc. J'ai vu tellement de sujet sur de nouvelles fonctionnalités, mais cela n'avance guère ou alors le pas n'a jamais été franchi. @wikijm peux-tu relancer les personnes qui s'étaient avancés sur du testing, ou développement de nouvelles fonctionnalités, on arrivera peut-être malgré tout à avancer à un bon rythme ?

Merci encore à vous.

**Comment by Oliv4945** [comment]
@Lusitanos67 : Tu peux toi aussi relancer le sujet que tu trouves intéressants, ça peut motiver l'auteur. Concernant les "nouvelles techno alamode" j'ai publié 2 plugins dédiés au "machine learning" [api.ai](https://github.com/Oliv4945/jarvis-api-ai) et [Rasa NLU](https://github.com/Oliv4945/jarvis-yajarvis)

Y'a encore du boulot mais ça fonctionne :-)

**Comment by Lusitanos67** [comment]
Justement, je ne suis pas du tout à l'aise avec ces technos (que je ne connais pas en faite). PAr exemple api.ai est une sorte d'api que je peux programmer pour en faire un bot ? Pourquoi tu indiques passer à autre chose sur le plugin ? et Rasa NLU ? En faite il faut assez pointu avec ces technos...

**Comment by Oliv4945** [comment]
api.ai (comme Rasa NLU) te permets de donner quelques exemples de commandes
et s'occupe automatiquement de chercher les correspondances avec d'autres
commandes que tu pourrais faire après. Par exemple:
 * Quelle est à météo à Brest ?
 * Quel est le temps à Paris ?
 * Va-t-il faire beau à Grenoble ?

Ils vont parser tout seul les nouvelles formulations/villes et te passer
une structure du type {commande=météo, ville=Grenoble}.  Avec Jarvis si on
dit "Quelle est la météo de Brest ?" c'est une commande différente de
"Quelle est à météo à Brest ?", du coup il faut faire sacrément attention à
la façon dont on construit les commandes. En se basant sur Rasa NLU il
suffit de donner quelques exemples et les variations sont comprises.
ça permet aussi des modes conversation plus naturels comme 'Quelle est la
météo à Paris ? Et demain ? Combien de temps faut-il pour y aller en
voiture ?". Avec l'interface actuelle de Jarvis c'est plutôt pénible à
faire.


api.ai est une startup rachetée par Google avec un code fermé qui tourne
sur leurs serveurs, donc on ne sait pas comment ça va évoluer pour les
hobbyistes. Du coup quand j'ai vu découvert Rasa NLU (une plateforme Open
Source) j'ai sauté dessus, ce qui donne le plugin YaJarvis

Oliv'

**Comment by Lusitanos67** [comment]
superbe explication :)
Merci beaucoup je vais y jeter un œil de plus près.

**Comment by Lusitanos67** [comment]
@Oliv4945 , c'est moi ou le plugin est vierge ?

**Comment by Oliv4945** [comment]
> @Oliv4945 , c'est moi ou le plugin est vierge ?

Lequel ?

**Comment by Lusitanos67** [comment]
Ben le YaJarvis, je regarde les fichiers dans github mais ils sont tous comme d'origine, le code n'est pas implémenté.

**Comment by Oliv4945** [comment]
Effectivement je n'avais pas poussé le code :/
Du coup je me demande si il fonctionne bien...

**Comment by Lusitanos67** [comment]
Je vais tester
