### ISSUE TITLE
How to compile on Debian Stretch

### ISSUE THREAD

**Issue by jbsky** [alexylem/jarvis#730]
Bonjour,

Je souhaiterai compiler les sources pour stretch, soit je ne trouve pas les sources soit un peu d'aide pour y arriver. En général, je compile à peu près tout ce qui est à base de C/Makefile. Mais là, j'ai un peu de mal pour Snowboy, une petite explication quelque part avec l’entête "How to compiling on Debian Stretch" serait vraiment bien la bienvenue. Pourquoi Stretch, je vous dirai pour VMWARE et la possibilité d'avoir le micro/enceinte du PC. Sous Jessie/Ubuntu 14.04, y a rien qui sort.

Merci de prendre en compte ma requête.

**Comment by Oliv4945** [comment]
Salut @jbsky 

C'est déjà fait ;) https://github.com/alexylem/jarvis/issues/660
Il reste à l'intégrer sur le site web mais il faut attendre @alexylem pour ça. 

Sinon nous ne sommes qu'utilisateurs de Snowboy, si tu as des soucis avec il vaut mieux leur demander [ici](https://github.com/Kitt-AI/snowboy#compile-a-python-wrapper)

**Comment by jbsky** [comment]
Bon,

Merci de ton retour, en faite, j'ai réussit à configurer un peu le truc sans avoir compiler quoi que ce soit, il me manqué audioport19-dev.
J'entends "hello" mais ça bug :
 

  | ------------   Config ------------
-- | --
  | jv_branch            master
  | jv_version |  
  | jv_arch              x86_64
  | jv_os_name           debian
  | jv_os_version        9
  | language             fr_FR
  | play_hw              false
  | rec_hw               false
  | speaker              Default
  | microphone           Default
  | recorder             sox
  | trigger_stt          snowboy
  | command_stt          bing
  | tts_engine           svox_pico
  | --------------------------------
  |   |  
  | DEBUG: program_startup hook
  | DEBUG: start_speaking hook
  | Snowboy: Hello
  | DEBUG: stop_speaking hook
  | User defined commands:
  | *AIDE*                  *BONJOUR*\|*SALUT*       *COMMENT*APPELLE*
  | *MERCI*                 *AU REVOIR*\|*BYE*       ANNULE*\|TERMINE*
  | ENCORE*                 *TEST*                  *VERSION*
  | *REPETE (*) ET (*)      *CA VA*                 >*OUI*
  | >*NON*\|*PAS*
  | Snowboy: Waiting to hear 'Snowboy'
  | Snowboy: (listening...)
  | DEBUG: models=snowboy
  | Traceback (most recent call last):
  | File "stt_engines/snowboy/main.py", line 2, in   <module>
  | import maindecoder_sox as maindecoder # snowboy decoder
  | File   "/home/jarvis/jarvis/stt_engines/snowboy/maindecoder_sox.py", line   3, in <module>
  | import snowboydetect
  | File   "/home/jarvis/jarvis/stt_engines/snowboy/snowboydetect.py", line   28, in <module>
  | _snowboydetect = swig_import_helper()
  | File   "/home/jarvis/jarvis/stt_engines/snowboy/snowboydetect.py", line   24, in swig_import_helper
  | _mod = imp.load_module('_snowboydetect', fp, pathname, description)
  | ImportError: libcblas.so.3: cannot   open shared object file: No such file or directory
  | DEBUG: modelid=-10
  | ERROR: snowboy recognition failed
  | HELP: check error message above, if:
  | IOError: [Errno Invalid input device   (no default output device)] -9996
  | 1) check your mic in Settings / Audio / Mic
  | 2) reboot your device
  | 3) report at: https://github.com/alexylem/jarvis/issues/415
  | IOError: [Errno Invalid sample rate]   -9997
  | 1) check your mic in Settings / Audio / Mic
  | 2) try uninstalling pulseaudio
  | 3) try fresh OS install
  | 4) your mic does not support 16k sampling rate, change mic
  | 5) report at: https://github.com/alexylem/jarvis/issues/311
  | IOError: [Errno Unanticipated host   error] -9999
  | 1) your mic is in error state, unplug/replug it
  | 2) report at https://github.com/alexylem/jarvis/issues/20
  | Other |  
  | 1) report at https://github.com/alexylem/jarvis/issues/new
  |   |  
  | DEBUG: program_exit hook


En mode clavier, ça fonctionne.

**Comment by jbsky** [comment]
Je suis pas sur mais la révif ligne 138 du modelid dans le fichier stt_engine / snowboy/main.sh  à l'air de ne pas être correct.
Je l'ai forcé à 11 et maintenant j'ai jarvis qui me répond. Il n'a pas l'air de comprendre quelquechose mais c'est déjà.

Merci

**Comment by Oliv4945** [comment]
```
 play_hw              false
 rec_hw               false
```
Tu as visiblement un soucis de configuration, essaie de refaire le wizard dans les paramètres

**Comment by jbsky** [comment]
Merci @Oliv4945, ça fait un paquet de fois que je refais le wizard.
Sur une Debian, je suis obligé de modifier le script pour lui faire croire que je suis sur Ubuntu...

**Comment by Oliv4945** [comment]
Je n'ai pas eu de soucis quand je l'ai fait, je regarderai sur la machine à l'occasion.

**Comment by Oliv4945** [comment]
@jbsky : Quelle est la modification que tu as du faire ?

**Comment by Oliv4945** [comment]
Clos en attendant une réponse de l'auteur
