### ISSUE TITLE
Plantage lors de la configuration micro ANDOER Omni-Directionnal

### ISSUE THREAD

**Issue by boboz2** [alexylem/jarvis#731]
Bonjour,
J'essai de configurer jarvis avec le micro andoer Omni-Directionnal.
Malheureusement quand je veux configurer le micro dans jarvis (Settings / Audio / Mic) cela lance la procédure puis plante.
J'arrive avec l'écran qui m'affiche le code suivant et je suis obligé de fermer ma session SSH car plus rien ne réponds.
```
Input File     : 'default' (alsa)
Channels       : 1
Sample Rate    : 16000
Precision      : 16-bit
Sample Encoding: 16-bit Signed Integer PCM

In:0.00% 00:00:03.07 [00:00:00.00] Out:48.0k [      |      ]        Clip:0
Done.

/dev/shm/jarvis-record.wav:

 File Size: 96.0k     Bit Rate: 256k
  Encoding: Signed PCM
  Channels: 1 @ 16-bit
Samplerate: 16000Hz
Replaygain: off
  Duration: 00:00:03.00

In:85.3% 00:00:02.56 [00:00:00.44] Out:41.0k [      |      ]        Clip:0
```

Pour information, voici aussi la configuration de mon fichier "~/.asoundrc":
`pcm.!default {
  type asym
   playback.pcm {
     type plug
     slave.pcm "false"
   }
   capture.pcm {
     type plug
     slave.pcm { type hw card AK5371 }
   }
}
ctl.!default {
type hw card AK5371
}
`

Merci de votre aide.

**Comment by wikijm** [comment]
Bonjour @boboz2,

Question/Réponse très rapide d'avant travail : 
As-tu regardé les autres issues concernant ce matériel ? Au même titre que les JABRA 410/510 il semble bien utilisé par la communauté. Si oui, quelles solutions as-tu essayé ?

**Comment by boboz2** [comment]
Merci de ta réponse rapide.
Alors j'ai fait pas mal de petit test. Lorsque je joue un son je l'entend sur les enceintes. J'arrive à enregistrer via arecord et écouter le message entendu.
J'ai réussi cette nuit à aller un peu plus loin. Mais à aucun moment je n'arrive à configurer le micro via jarvis. Lors de la configuration on doit faire un bruit pour le micro et ensuite l'écouter. A ce moment la je n'entends jamais rien même en ayant joué sur le gain.

**Comment by boboz2** [comment]
Bon, je viens de trouver la solution.
Il faut désinstaller "pulseaudio" et la configuration se passe bien.
Par contre à aucun moment jarvis ne détecte ma voix

**Comment by Oliv4945** [comment]
Quand tu fais le wizard tu t'entends ?
Que donne `jarvis -nv` ?

**Comment by boboz2** [comment]
Quand je fais le wizard, je m'entends sans problème.
J'ai réussi avec `jarvis -nv` à le faire fonctionner.
Par contre seul soucis, je n'arrive pas à terminer la session jarvis une fois qu'elle a été initié. Même en faisaint `jarvis -q`, il tourne toujours en arrière plan. Et donc ne fonctionne plus.

**Comment by Oliv4945** [comment]
Bonjour,
Si il y avait PulseAudio peut-être essayer de supprimer le `~/.asoundrc` et refaire un wizard.
Comme demandé à l'ouverture de l'issue, merci de poster le résultat de la commande `jarvis -nv`.

**Comment by boboz2** [comment]
Hello,
Désolé du retard mais je n'ai pas pu faire les tests.
J'ai donc refait une installe, puis supprimer le `~/.asoundrc` et refaire un wizard.
Voici le résultat de la commande `jarvis -nv`.
`jarvis -nv

------------ Config ------------
jv_branch            master 
jv_version            
jv_arch              armv6l 
jv_os_name           raspbian 
jv_os_version        8 
language             fr_FR 
play_hw              hw:0,0 
rec_hw               hw:1,0 
speaker              ALSA 
microphone           Asahi Kasei Microsystems Co., Ltd  
recorder             sox 
trigger_stt          snowboy 
command_stt          bing 
tts_engine           svox_pico 
--------------------------------

DEBUG: program_startup hook
DEBUG: start_speaking hook
jarvis: Hello
DEBUG: stop_speaking hook
User defined commands:
*AIDE*			*BONJOUR*|*SALUT*	*COMMENT*APPELLE*
*MERCI*			*AU REVOIR*|*BYE*	ANNULE*|TERMINE*
ENCORE*			*TEST*			*VERSION*
*REPETE (*) ET (*)	*CA VA*			>*OUI*
>*NON*|*PAS*
jarvis: Waiting to hear 'jarvis'
aurelien: (listening...)
DEBUG: models=jarvis
INFO:snowboy:Ticks: [2, 20, 5, -1]
INFO:snowboy:Keyword 1 detected at time: 2017-10-26 19:17:41
INFO:snowboy:Keyword 1 detected at time: 2017-10-26 19:17:45
INFO:snowboy:Keyword 1 detected at time: 2017-10-26 19:17:48
INFO:snowboy:Keyword 1 detected at time: 2017-10-26 19:17:50`

**Comment by Oliv4945** [comment]
Du coup as-tu réussi à faire la configuration du micro ?

**Comment by boboz2** [comment]
La configuration du micro fonctionne maintenant.
Mais par contre impossible de communiquer avec jarvis à aucun moment il ne détecte le mot clef ou autre. Je me demande si cela ne vient pas du fait que je sois sur un raspberry pi de première génération qui manquerait de puissance.

**Comment by Oliv4945** [comment]
Je ne pense pas que ça vienne de là, mais je n'ai jamais essayé. Que donne `top` pendant que tu essaies d'utiliser Jarvis ?
Si tu essaies de t'enregistrer avec `rec test.wav` puis rejouer avec `play test.wav` est-ce que tu t'entends bien ?

**Comment by boboz2** [comment]
Alors quand j'arrete jarvis je peux m'enregistrer et quand je rejoue je m'entends bien.
Voici le résultat de top : 
`top - 22:58:53 up 18:58,  2 users,  load average: 0,24, 0,57, 0,96
Tasks: 115 total,   1 running, 114 sleeping,   0 stopped,   0 zombie
%Cpu(s):  4,1 us,  2,2 sy,  0,0 ni, 93,4 id,  0,0 wa,  0,0 hi,  0,4 si,  0,0 st
KiB Mem:    444520 total,   403508 used,    41012 free,    75268 buffers
KiB Swap:   102396 total,     5084 used,    97312 free.   135120 cached Mem

  PID USER      PR  NI    VIRT    RES    SHR S %CPU %MEM     TIME+ COMMAND                                                                                                          
 1226 aurelien  20   0    5596   2624   2192 R  2,3  0,6   0:09.14 top                                                                                                              
  820 root      20   0  277012  23696  10356 S  1,6  5,3  89:37.32 domoticz                                                                                                         
 1380 root      20   0  222552  87308   6056 S  1,6 19,6  23:19.96 java                                                                                                             
29573 root      20   0       0      0      0 S  1,0  0,0   0:04.67 kworker/u2:2                                                                                                     
 1625 mysql     20   0  319100  37852   5472 S  0,6  8,5   6:46.12 mysqld                                                                                                           
    3 root      20   0       0      0      0 S  0,3  0,0   2:10.03 ksoftirqd/0                                                                                                      
  356 mosquit+  20   0    5504   3500   3352 S  0,3  0,8   2:39.56 mosquitto                                                                                                        
  533 aurelien  20   0   12456   3808   3064 S  0,3  0,9   0:02.35 sshd                                                                                                             
 1111 root      20   0  106316  19792  15616 S  0,3  4,5   0:11.93 apache2                                                                                                          
 1752 gammu     20   0   26744   4384   2632 S  0,3  1,0   6:54.83 gammu-smsd                                                                                                       
    1 root      20   0    5456   3540   2616 S  0,0  0,8   0:13.41 systemd                                                                                                          
    2 root      20   0       0      0      0 S  0,0  0,0   0:00.06 kthreadd                                                                                                         
    5 root       0 -20       0      0      0 S  0,0  0,0   0:00.00 kworker/0:0H                                                                                                     
    7 root       0 -20       0      0      0 S  0,0  0,0   0:00.00 lru-add-drain                                                                                                    
    8 root      20   0       0      0      0 S  0,0  0,0   0:00.01 kdevtmpfs                                                                                                        
    9 root       0 -20       0      0      0 S  0,0  0,0   0:00.00 netns                                                                                                            
   10 root      20   0       0      0      0 S  0,0  0,0   0:00.12 khungtaskd                                                                                                       
   11 root      20   0       0      0      0 S  0,0  0,0   0:00.00 oom_reaper                                                                                                       
   12 root       0 -20       0      0      0 S  0,0  0,0   0:00.00 writeback                                                                                                        
   13 root      20   0       0      0      0 S  0,0  0,0   0:00.00 kcompactd0                                                                                                       
   14 root       0 -20       0      0      0 S  0,0  0,0   0:00.00 crypto                                                                                                           
   15 root       0 -20       0      0      0 S  0,0  0,0   0:00.00 bioset                                                                                                           
   16 root       0 -20       0      0      0 S  0,0  0,0   0:00.00 kblockd                                                                                                          
   17 root       0 -20       0      0      0 S  0,0  0,0   0:00.00 watchdogd                                                                                                        
   19 root       0 -20       0      0      0 S  0,0  0,0   0:00.00 rpciod                                                                                                           
   20 root       0 -20       0      0      0 S  0,0  0,0   0:00.00 xprtiod                                                                                                          
   21 root      20   0       0      0      0 S  0,0  0,0   0:00.79 kswapd0                                                                                                          
   22 root       0 -20       0      0      0 S  0,0  0,0   0:00.00 nfsiod                                                                                                           
   32 root       0 -20       0      0      0 S  0,0  0,0   0:00.00 kthrotld                                                                                                         
   33 root       0 -20       0      0      0 S  0,0  0,0   0:00.00 bioset                                                                                                           
   34 root       0 -20       0      0      0 S  0,0  0,0   0:00.00 bioset                                                                                                           
   35 root       0 -20       0      0      0 S  0,0  0,0   0:00.00 bioset                                                                                                           
   36 root       0 -20       0      0      0 S  0,0  0,0   0:00.00 bioset                                                                                                           
   37 root       0 -20       0      0      0 S  0,0  0,0   0:00.00 bioset                                                                                                           
   38 root       0 -20       0      0      0 S  0,0  0,0   0:00.00 bioset                                                                                                           
   39 root       0 -20       0      0      0 S  0,0  0,0   0:00.00 bioset                                                                                                           
   40 root       0 -20       0      0      0 S  0,0  0,0   0:00.00 bioset                                                                                                           
   41 root       0 -20       0      0      0 S  0,0  0,0   0:00.00 bioset                                                                                                           
   42 root       0 -20       0      0      0 S  0,0  0,0   0:00.00 bioset                                                                                                           
   43 root       0 -20       0      0      0 S  0,0  0,0   0:00.00 bioset                                                                                                           
   44 root       0 -20       0      0      0 S  0,0  0,0   0:00.00 bioset                                                                                                           
   45 root       0 -20       0      0      0 S  0,0  0,0   0:00.00 bioset                                                                                                           
   46 root       0 -20       0      0      0 S  0,0  0,0   0:00.00 bioset                                                                                                           
   47 root       0 -20       0      0      0 S  0,0  0,0   0:00.00 bioset                                                                                                           
   48 root       0 -20       0      0      0 S  0,0  0,0   0:00.00 bioset                                                                                                           
   49 root       0 -20       0      0      0 S  0,0  0,0   0:00.00 bioset                                                                                                           
   50 root       0 -20       0      0      0 S  0,0  0,0   0:00.00 bioset                                                                                                           
   51 root       0 -20       0      0      0 S  0,0  0,0   0:00.00 bioset                                                                                                           
   52 root       0 -20       0      0      0 S  0,0  0,0   0:00.00 bioset  `

**Comment by wikijm** [comment]
Bonjour @boboz2,

Le problème est-il toujours d'actualité ?

**Comment by boboz2** [comment]
Bonjour,

Je n'ai jamais réussi a résoudre le problème du micro et j'ai pour
l'instant un peu abandonné le projet.

Cordialement,

Aurélien Bosson
06-78-89-49-49
bosson.aurelien@gmail.com

2018-03-23 13:35 GMT+01:00 PGP 2F93D5AF <notifications@github.com>:

**Comment by wikijm** [comment]
Avec ton accord, je propose de clôturer l'issue.

Comme ça, et si tu le souhaites, tu vas pouvoir retester avec la dernière version d'OpenJarvis, ton issue initiale datant d'octobre 2017.

**Comment by boboz2** [comment]
Pas de problème.

Cordialement,

Aurélien Bosson
06-78-89-49-49
bosson.aurelien@gmail.com

2018-03-23 13:47 GMT+01:00 PGP 2F93D5AF <notifications@github.com>:
