### ISSUE TITLE
Jarvis don't stop Jarvis if running in background

### ISSUE THREAD

**Issue by nicoxygen** [alexylem/jarvis#732]
### Description

In background mode wen i want to stop jarvis all it's ok but jarvis don't stop really
with ./jarvis.sh -q, it's the same problem.

**Comment by Oliv4945** [comment]
Do you use Systemd plugin ?
If so you have to use `sudo systemctl stop jarvis.service`, it is a known
limitation which can be corrected but I need some time :)

**Comment by nicoxygen** [comment]
Ok thanks i have not look this plugin thank you
