### ISSUE TITLE
Problem: execv() arg 2 must contain only strings

### ISSUE THREAD

**Issue by nicoxygen** [alexylem/jarvis#733]
### Description

when i execute command with é è .. i have as error execv() arg 2 must contain only strings.
Example: éteins la lumière ==>>>> execv() arg 2 must contain only strings
i use jeedom plugin for information.

**Comment by Oliv4945** [comment]
Do you speak French ? There might be a solution [here](https://github.com/alexylem/jarvis/issues/524)
If not I can translate it for you

**Comment by nicoxygen** [comment]
merci je n'y avais pas pensé

**Comment by Oliv4945** [comment]
Bonjour,
Est-ce que ça a fonctionné ? Ne pas hésiter à rouvrir l'issue au cas où.
