### ISSUE TITLE
Ampoule Philips 

### ISSUE THREAD

**Issue by Denvise** [alexylem/jarvis#735]
Bonjour,  je vais acheter des ampoules connectées. Cependant je vois que dans les plugins il y a seulement les marques lixf et milight. Est ce qu'une ampoule connectée WiFi Philips fonctionnerait aisément ?

**Comment by Oliv4945** [comment]
Bonjour,
Est-ce les Phillips Hue ? Voir [ici](https://www.openjarvis.com/plugins/hue)

**Comment by Denvise** [comment]
C'est une Philips hue wireless oui donc je pense que tu as répondu à ma question je te remercie

**Comment by Sh1n1x** [comment]
Si tu cherches à les configurer avec ce plugins il y a de grande chance que ça ne fonctionne pas. Si jamais demande moi j'ai créé des ordres maison avec le package npm hue.
