### ISSUE TITLE
Supprimer error.wav

### ISSUE THREAD

**Issue by Calaves** [alexylem/jarvis#736]
Bonsoir,

Comme beaucoup le disent, vraiment beau travail, je ne manquerai pas de faire un don car ça mérite amplement.

Je viens d'installer Jarvis sur un Rasperry dans mon salon, soucis c'est que lorsque je passe en mode conversation et qu'un moment je m'arrete il test ### donc trois fois la fameux error.wav puis le timout.wav, j'ai essayé de les supprimés mais ça engendre toujours des problèmes que se soit dans le code ou dans le dossier sounds.

Connaissant pas la python je ne peux pas vraiment manipuler grand chose.

Merci par avance.

**Comment by Oliv4945** [comment]
Bonjour,

Je ne suis pas sur de comprendre votre soucis... Pourquoi vouloir le supprimer ?
Au cas où, il est possible de ne pas utiliser le mode conversation via le paramètre "conversation_mode" ou en lançant Jarvis avec `-c true/false`

**Comment by Calaves** [comment]
Et bien lorsque je dis Jarvis je passe en mode conversation, je lui donne un ordre mais une fois que j'ia passé mon ordre et qu'il la exécuté, j'ai donc # + son error # + son error # + son error. C'est vite gênant en fait. Je veux maintenir le mode conversation mais je veux enlever le son d'error lorsque Jarvis attend un nouvel ordre avant de revenir en attente du magic word.

Merci à vous.

**Comment by Oliv4945** [comment]
Si je comprends bien tu veux maintenir le mode conversation indéfiniment sans timeout ?

**Comment by Denvise** [comment]
Haha navré je suis pas clair mais j'ai l'impression que sur le raspberry ça ne le fait pas. Jarvis attend une qu'on dise son nom et ensuite une fois qu'on lui a dit le nom il attend une commande au bout d'un mini temps timout mais entre temps il lance un son d'error ajoute un # et ça trois fois avant de passer en timout.

Mais j'ai l'impression qu'il ne le fait pas sur rpi3. 

Par contre depuis les mises à jour j'entends pas la fin des phrases de jarvis.

**Comment by Oliv4945** [comment]
Je ferme en attendant un réponse de l'auteur
