### ISSUE TITLE
Jarvis ne reconnais pas les commades

### ISSUE THREAD

**Issue by fred439** [alexylem/jarvis#737]
Bonjour,
Voila mon problème, Jarvis reconnais bien le mot magique mais ensuite plus rien du tout. 
Même en essayant de jouer avec le gain...
Merci d'avance

**Comment by wikijm** [comment]
Bonsoir @fred439,

Merci de fournir les logs comme demandé lors de la création de l'issue

**Comment by Calaves** [comment]
Il se peut que se soit juste un soucis de volume micro, ça m'ai arrivé il reconnaissait le mot magique mais pas les commandes, j'ai changé le volume du micro ou je me suis éloigné et ça a fonctionné.

**Comment by Oliv4945** [comment]
Salut,

Pas de log, je ferme. Tu peux réouvrir en postant les log.
