### ISSUE TITLE
Commande non reconnue mais sortie STT correcte

### ISSUE THREAD

**Issue by iamlionem** [alexylem/jarvis#738]
### Description

Bonjour, je ne sais pas si mon titre est vraiment clair mais mon soucis est le suivant, c'est la première fois que je développe un plugin et le soucis est que les mots pour trigger la commande sont bien reconnus par Jarvis, mais il ne les comprends pas alors qu'il devrait exécuter la commande associée aux mots. Dans la capture asciinema on voit bien les mots de mon plugin au démarrage dans le listing. J'ai aussi ajouté un screenshot du fichier command du plugin. Merci d'avance pour votre aide

### Logs

https://asciinema.org/a/cip9pTidUfjBgusVnaXQhByGr
![image](https://user-images.githubusercontent.com/33125777/32065007-cd0145cc-ba7b-11e7-8359-d7073e1fa1f3.png)

**Comment by Oliv4945** [comment]
Salut,

En regardant rapidement ça devait fonctionner.
Tu peux essayer:

1. Ne dire que "Adresse publique"
2. Voir ce qui se passe en ligne de commande avec `jarvis -x "adresse publique"`
3. La casse ne devrait pas jouer mais au cas où:  `jarvis -x "ADRESSE PUBLIQUE"`
4. Essayer avec un mot tout seul, par exemple 'adresse'
5. Mettre adresse publique en laisser juste `Je regarde...` et enlever le `&...`
6. Tentative désespérée, mais au cas où tu aies un autre plugin qui met le boxon: remonter le plug-in plus haut dans la liste

**Comment by iamlionem** [comment]
J'ai déjà essayé la première proposition sans succès, je vais essayer les
autres surtout la 6ème j'ai déjà eu des plugins conflictuels entre eux.
Merci beaucoup.

Le 27 oct. 2017 2:04 PM, "Oliv4945" <notifications@github.com> a écrit :

Salut,

En regardant rapidement ça devait fonctionner.
Tu peux essayer:

   1. Ne dire que "Adresse publique"
   2. Voir ce qui se passe en ligne de commande avec jarvis -x "adresse
   publique"
   3. La casse ne devrait pas jouer mais au cas où: jarvis -x "ADRESSE
   PUBLIQUE"
   4. Essayer avec un mot tout seul, par exemple 'adresse'
   5. Mettre adresse publique en laisser juste Je regarde... et enlever le
   &...
   6. Tentative désespérée, mais au cas où tu aies un autre plugin qui met
   le boxon: remonter le plug-in plus haut dans la liste

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/alexylem/jarvis/issues/738#issuecomment-339952896>, or mute
the thread

**Comment by iamlionem** [comment]
Merci beaucoup, le problème venait bien de l'ordre des plugins, le plugin alarm posait problème merci de votre aide.
