### ISSUE TITLE
Home command/Domoticz : parse error, Expected another array element

### ISSUE THREAD

**Issue by ggaetan1** [alexylem/jarvis#739]
Bonjour,

Ayant installé le plugin home control, j'ai modifié le fichier de configuration comme ci-dessous :

pg_hc_turnon_url="http://192.168.0.5:8082/json.htm?type=command&param=switchlight&idx=[ADDRESS]&switchcmd=On"
pg_hc_turnoff_url="http://192.168.0.5:8082/json.htm?type=command&param=switchlight&idx=[ADDRESS]&switchcmd=Off"

pg_hc_config='{ "devices":[
    { "name": "salon", "address": "1"},
]}'

Lorsque je donne la commande "Allume Salon" à Jarvis, il m'affiche 

> Parse error : Expected another array element at line 1, column 51

et la commande ne s’exécute pas.

Tests effectués : 

- si je mets directement dans mon navigateur http: //192.168.0.5:8082/json.htm?type=command&param=switchlight&idx=1&switchcmd=On
(j'ai enlevé address pour mettre 1) alors la commande s'effectue bien ;

- si dans le fichier de config de home control, je mets pg_hc_turnon_url="http://192.168.0.5:8082/json.htm?type=command&param=switchlight&idx=1&switchcmd=On", (idem : j'ai enlevé address pour mettre 1)

l'erreur "Expected another array element at line 1, column 51" s'affiche toujours mais la commande s'effectue.

- si je mets cette commande dans le fichier des commandes vocales de jarvis directement avec un curl, ça fonctionne.

Bref, je ne vois pas ce qui bloque.

Merci de votre aide.

**Comment by ggaetan1** [comment]
C'est la virgule à la fin de { "name": "salon", "address": "1"},   qui posait problème (je suis dessus depuis 2 heures mais un peu débutant sur le sujet aussi !)

Je m'excuse du bruit pour rien (mais je n'ai pas trouvé comment supprimer le sujet).

**Comment by wikijm** [comment]
Salut @ggaetan1

Aucun soucis, tu as bien fait en clôturant l'issue :smile:
Si j'avais juste une remarque à faire, pense plutôt à faire un ticket sur le repo du plugin quand ça ne concerne pas directement Jarvis Core ;-)

**Comment by Oliv4945** [comment]
Deux remarques de plus:
* Ne jamais supprimer un sujet quand tu fournis la solution, ça peut aider les autres :)
* Sur du JSON tu peux utiliser un validateur en ligne pour vérifier que tout va bien, par exemple [celui-ci](https://jsonlint.com/) te montre tout de suite le soucis.
