### ISSUE TITLE
Reprendre dernière commande utilisée ?

### ISSUE THREAD

**Issue by Sh1n1x** [alexylem/jarvis#740]
Salut,

Y a t'il déjà la possibilité de reprendre la dernière commande effectuée ?

Exemple si je lui dis "baisse la lumière du salon" mais que c'est pas assez à mon goût, j'aimerai lui dire "encore" et quelle répète l'action.
Merci d'avance pour votre réponse.

EDIT vu que ça stock dans les logs logiquement on pourrait reprendre et relancer non ? Genre `awk '/./{line=$0} END{print line}' /home/pi/jarvis/jarvis.log` on recup la dernière ligne

**Comment by Oliv4945** [comment]
Salut, l'idée est bonne !

En façon facile tu pourrais faire une conversation avec `>` car ce n'est pas implémenté en natif.
En façon difficile tu dois effectivement pouvoir parser les log ou juste faire une variable qui mémorise la dernière commande... PR bienvenue :)

**Comment by Sh1n1x** [comment]
En faite, j'ai vu après coup qu'elle est déjà implémentée ^^. Donc c'est tout bon.
