### ISSUE TITLE
Pocket Sphinx décentralisé

### ISSUE THREAD

**Issue by jodumont** [alexylem/jarvis#742]
Tout d'abord merci Alex de t'avoir creusé un peu la tête sur le sujet de la vie privé et de ne pas simplement balancer des API sous prétexte qu'ils sont libre et gratuites.
 
### Description
Secondo; c'est pas vraiment un problème car j'ai pas encore essayé mais...
j'avais pas de compte Disqus, FB et machin truc sous la main pour laisser un commentaire donc...

Est-ce que tu crois que c'est possible la base de reconnaissance PocketSphinx sur une machine plus puissante (voir faire son propre cloud) et si oui, comment s'y référer dans ta config ;)

**Comment by Oliv4945** [comment]
Salut,

ça a été discuté en #9 , mais jamais allé au bout... manque de temps :/
