### ISSUE TITLE
Matrix Creator compatible ?

### ISSUE THREAD

**Issue by tutur1004** [alexylem/jarvis#743]
Bonjour,

Je suis actuellement entrain de dimensionner mon futur système (choix des composants, emplacement chez moi, etc...) J'ai donc pris connaissance de la liste des microphone compatible, mais aucun ne convient à mes besoins, j'ai donc effectué des recherches sur le net et il s'avère que celui dont j'ai besoin serait le Matrix Creator ! (De plus j'aime beaucoup son design).

Ma question est donc toute simple, le Matrix Creator est il compatible avec Jarvis ?
Question bonus (Si personne n'a la réponse je trouvais moi même pas de problèmes) quelqu'un sait il comment je vais pouvoir contrôler des séquences d'animations du ring de leds?

Merci par avance pour vos réponses :D
-MileKat-

**Comment by Oliv4945** [comment]
Salut,

Une petite recherche permet de grandes choses ;-)
https://github.com/alexylem/jarvis/issues/103#issuecomment-255251762

Oliv'

**Comment by tutur1004** [comment]
Haha en effet je n'es pas trop trop cherché 🙄.
Honte à moi x) en tous cas merci beaucoup 👌.
-MileKat-
