### ISSUE TITLE
Jarvis et domotique EEDOMUS

### ISSUE THREAD

**Issue by sejerome** [alexylem/jarvis#745]
### Description

Bonjour,
Déjà, un grand bravo pour le boulot réalisé sur Jarvis !
J'ai installé jarvis il y a quelque temps, et j'arrive bien à lui faire commander mes modules z-wave via ma box eedomus par HTTP.

### Mais je n'arrive pas avoir de retour sur l'état de mes modules, :(

Par exemple, si je lance la commande à jarvis : 'ouvre le garage' et que le garage est déjà ouvert, j'aimerai qu'il puisse me répondre : 'le garage est déjà ouvert'.

Pareil,   je n'arrive pas à obtenir les températures de mes sondes.
Je n'arrive par a extraire uniquement la valeur numérique de la commande http 
*JARVIS*TEMPERATURE*==say "La température est de $(curl -s "http://monIP/api/get?api_user=xxxx&api_secret=xxxxx&action=periph.caract&format=xml&periph_id=xxxx

Un plugin EEDOMUS est-il en préparation et va_t_il bientôt sortir ??

Merci d'avance pour vos aides sur le sujet.

**Comment by sejerome** [comment]
Re, une petite idée ?
Quelqu'un utilise la box eedomus ou autre box domotique ?

**Comment by Oliv4945** [comment]
>Re, une petite idée ?
Quelqu'un utilise la box eedomus ou autre box domotique ?

Salut,

Pour les gens pressés il y a une fonction recherche tout en haut ;)
