### ISSUE TITLE
Nouveau plugin pour utiliser heyu

### ISSUE THREAD

**Issue by domotic-29** [alexylem/jarvis#748]
Bonjour,

J'ai créé un nouveau plugin pour utiliser heyu : https://github.com/domotic-29/jarvis-heyu

Je peux ouvrir ou allumer avec le même ordre, dans le fichier command puis-je n'utiliser qu'une ligne au lieu de deux ?
*ALLUM[^ ]+ (*)==pg_jh_turn on "(1)"
*OUVR[^ ]+ (*)==pg_jh_turn on "(1)"

Dans le fichier function.sh, j'ai le "case" habituel : 
case "$1" in
        no_device_matching) echo "Aucun appareil ne correspond à $2";;
        switching_on) echo "J'allume $2";;
        switching_off) echo "J'éteins $2";;
        *) jv_error "ERROR: unknown translation key: $1";;
    esac

Mais puisque j'allume (la lumière) ou ouvre (un volet) avec un "on" comment puis-je distinguer pour dire "J'ouvre $2" ?

Merci pour votre aide.

PS : j'ai créé un compte pour pouvoir enregistrer le plugin sur votre site, je n'ai pas encore reçu de mail de confirmation/validation.

**Comment by Sh1n1x** [comment]
Salut si tu fais ça fonctionne pas ? : 
ALLUM[^ ]+ ()\OUVR[^ ]+ ()==pg_jh_turn on "(1)"

Pour ton soucis avec ton "j allume/j'ouvre" je te propose une solution plus simple... Tu demandes à jarvis de répondre "C'est fait" (parce que j'avais fait comme toi pour mes lumières et au bout d'un moment c'est chiant de l'entendre répéter "j'allume la lumière du salon". Et du coup ça t'enlève un pb ^^.

Pour le mail moi je l'avais reçu tout de suite, t'as check tes spam ?

**Comment by domotic-29** [comment]
Pour le long terme tu as certainement raison, mais au début pour vérifier qu'il a bien compris ce que je voulais, c'est bien qu'il répète.

En fait je ne comprends la ligne. Quelle différence par rapport à ALLUM* , qu'est-ce que ça fait ce "+ ()" ?
Et de l'autre côté, pas mieux. Je crois que j'ai un peu trop vite recopié un précédent texte, pg_jh_turn est censé être une variable ? J'ai l'impression que je ne l'utilise pas. Le "on" c'est pour l'avoir en $1 ? ou bien est-ce ce le (1) qui fait ça ?

Si quelqu'un a un lien avec plusieurs exemples adaptés à ce que l'on cherche affaire ici, je suis preneur.

D'autant que j'ai un autre problème, je peux aussi récupérer des données issue de sondes, thermomètre par exemple. Donc pour une pièce, je peux vouloir gérer la lumière, le volet ou la température. Du coup il faut que je réfléchisse à trouver les bons mots clés... 

PS : Le mail est arrivé une heure après.

**Comment by domotic-29** [comment]
Comment peut-on faire une opération avec le bash et une valeur située dans un fichier ?
Voici mon problème : 
le pluviomètre incrémente tout le temps la quantité de pluie mesurée, et il reprendra à 0 après avoir franchi les 9999 ou 99999.
Pour savoir s'il a plu dans la journée je sauvegarde la quantité de pluie mesurée à minuit dans un fichier. Ensuite quand je demande à Jarvis s'il a plu, je veut qu'il compare la valeur actuelle à celle enregistrée pour savoir s'il a plu et si oui combien de millimètres.

**Comment by Oliv4945** [comment]
Essaie de regarder avec l'opérateur `cat`, quelque chose du type `$(cat tonfichier.txt)`

**Comment by wikijm** [comment]
Clôture du ticket jusqu'à obtention d'une réponse de la part de l'auteur de l'issue.
Closing of the ticket until a valid answer from the applicant is obtained.
