### ISSUE TITLE
Reconnaissance vocale Bing retourne erreur "NOSPEECH":"1"

### ISSUE THREAD

**Issue by stackgil** [alexylem/jarvis#75]
### Description

DEBUG: json={"version":"3.0","header":{"status":"error","properties":{"requestid":"85ce32f6-a48f-40d3-be2f-db358ea64dad","NOSPEECH":"1"}}}

### Résultat
```
pi@raspberrypi:~/jarvis $ ./jarvis.sh
Checking for updates...[Up-to-date]

------- Config (verbose) -------
platform              linux
language              fr_FR
play_hw               hw:0,0
rec_hw                hw:1,0
trigger_stt           snowboy
command_stt           bing
tts_engine            svox_pico
conversation_mode     true
--------------------------------

DEBUG: program_startup hook
Jarvis: Bonjour monsieur
Jarvis: Waiting to hear 'Jarvis'
Gil: (listening...)
ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.rear
ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.center_lfe
ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.side
ALSA lib confmisc.c:1286:(snd_func_refer) Unable to find definition 'cards.bcm2835.pcm.surround51.0:CARD=0'
ALSA lib conf.c:4259:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:4738:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM surround21
ALSA lib confmisc.c:1286:(snd_func_refer) Unable to find definition 'cards.bcm2835.pcm.surround51.0:CARD=0'
ALSA lib conf.c:4259:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:4738:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM surround21
ALSA lib confmisc.c:1286:(snd_func_refer) Unable to find definition 'cards.bcm2835.pcm.surround40.0:CARD=0'
ALSA lib conf.c:4259:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:4738:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM surround40
ALSA lib confmisc.c:1286:(snd_func_refer) Unable to find definition 'cards.bcm2835.pcm.surround51.0:CARD=0'
ALSA lib conf.c:4259:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:4738:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM surround41
ALSA lib confmisc.c:1286:(snd_func_refer) Unable to find definition 'cards.bcm2835.pcm.surround51.0:CARD=0'
ALSA lib conf.c:4259:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:4738:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM surround50
ALSA lib confmisc.c:1286:(snd_func_refer) Unable to find definition 'cards.bcm2835.pcm.surround51.0:CARD=0'
ALSA lib conf.c:4259:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:4738:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM surround51
ALSA lib confmisc.c:1286:(snd_func_refer) Unable to find definition 'cards.bcm2835.pcm.surround71.0:CARD=0'
ALSA lib conf.c:4259:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:4738:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM surround71
ALSA lib confmisc.c:1286:(snd_func_refer) Unable to find definition 'cards.bcm2835.pcm.iec958.0:CARD=0,AES0=4,AES1=130,AES2=0,AES3=2'
ALSA lib conf.c:4259:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:4738:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM iec958
ALSA lib confmisc.c:1286:(snd_func_refer) Unable to find definition 'cards.bcm2835.pcm.iec958.0:CARD=0,AES0=4,AES1=130,AES2=0,AES3=2'
ALSA lib conf.c:4259:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:4738:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM spdif
ALSA lib confmisc.c:1286:(snd_func_refer) Unable to find definition 'cards.bcm2835.pcm.iec958.0:CARD=0,AES0=4,AES1=130,AES2=0,AES3=2'
ALSA lib conf.c:4259:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:4738:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM spdif
ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.hdmi
ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.hdmi
ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.modem
ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.modem
ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.phoneline
ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.phoneline
ALSA lib pulse.c:243:(pulse_connect) PulseAudio: Unable to connect: Connection refused

ALSA lib pulse.c:243:(pulse_connect) PulseAudio: Unable to connect: Connection refused

Cannot connect to server socket err = No such file or directory
Cannot connect to server request channel
jack server is not running or cannot be started
INFO:snowboy:Silence
INFO:snowboy:Silence
INFO:snowboy:Silence
INFO:snowboy:Silence
INFO:snowboy:Silence
INFO:snowboy:Silence
INFO:snowboy:Silence
INFO:snowboy:Silence
INFO:snowboy:Silence
INFO:snowboy:Silence
INFO:snowboy:Silence
INFO:snowboy:Silence
INFO:snowboy:Keyword 1 detected at time: 2016-07-28 23:53:55
Jarvis
DEBUG: entering_cmd hook
Jarvis: Oui monsieur?
Gil: (listening...)
./timeout.sh 10 rec -V1 -q -r 16000 -c 1 -b 16 -e signed-integer --endian little jarvis-record.wav silence 1 0.1 1% 1 0.5 1% trim 0 10
DEBUG: speech duration was 02 (10 = 1 sec)
DEBUG: curl https://speech.platform.bing.com/recognize/query?version=3.0&requestid=3a829ce8-1344-4109-babd-ad00b439a74f&appid=D4D52672-91D7-4C74-8AD8-42B1D98141A5&format=json&locale=fr-FR&device.os=linux&scenarios=ulm&instanceid=E043E4FE-51EF-4B74-8133-B728C4FEA8AA
DEBUG: json={"version":"3.0","header":{"status":"error","properties":{"requestid":"4a17e1cc-76a6-44b4-a4e9-5f4b2bec4712","NOSPEECH":"1"}}}
?(listening...)
./timeout.sh 10 rec -V1 -q -r 16000 -c 1 -b 16 -e signed-integer --endian little jarvis-record.wav silence 1 0.1 1% 1 0.5 1% trim 0 10
DEBUG: speech duration was 00 (10 = 1 sec)
DEBUG: curl https://speech.platform.bing.com/recognize/query?version=3.0&requestid=bf00913e-dab1-44cb-98d9-e72f5dc6c320&appid=D4D52672-91D7-4C74-8AD8-42B1D98141A5&format=json&locale=fr-FR&device.os=linux&scenarios=ulm&instanceid=E043E4FE-51EF-4B74-8133-B728C4FEA8AA
DEBUG: json={"version":"3.0","header":{"status":"error","properties":{"requestid":"85ce32f6-a48f-40d3-be2f-db358ea64dad","NOSPEECH":"1"}}}
?(listening...)
./timeout.sh 10 rec -V1 -q -r 16000 -c 1 -b 16 -e signed-integer --endian little jarvis-record.wav silence 1 0.1 1% 1 0.5 1% trim 0 10
DEBUG: speech duration was  (10 = 1 sec)
DEBUG: timeout, end of conversation
DEBUG: exiting_cmd hook

Jarvis: Waiting to hear 'Jarvis'
Gil: (listening...)

Jarvis repète ma demande mais n'execute aucun ordre comme "Quelle heure est'il?"
```

**Comment by stackgil** [comment]
DEBUG: curl https://speech.platform.bing.com/recognize/query?version=3.0&requestid=3a829ce8-1344-4109-babd-ad00b439a74f&appid=D4D52672-91D7-4C74-8AD8-42B1D98141A5&format=json&locale=fr-FR&device.os=linux&scenarios=ulm&instanceid=E043E4FE-51EF-4B74-8133-B728C4FEA8AA

reponse : 
<H2> Nos services ne sont pas disponibles en ce moment </ h2> <p> Nous travaillons à rétablir tous les services le plus tôt possible. S'il vous plaît revenez bientôt </ p> Ref A:. F12A66B492414E7792844CCD3DBCD702 Ref B: 7B45944358989BB3B235E8A4746EE558 Ref C: Jeu 28 juillet 15:19:59 PST 2016

cela peut-être lié?

**Comment by alexylem** [comment]
Non ce n'est pas lié, j'imagine que c'est temporaire. Pour les `?`, comme dit dans l'autre ticket, l'erreur:
```
"NOSPEECH":"1"
```
Indique que Bing n'a pas identifié de voix dans le fichier envoyé. Si toi tu entends ta voix, c'est donc un pb de qualité de micro ou de réglage de la sensibilité. Je t'invite à essayer d'autres réglages de sensibilité et si possible tester avec un autre micro.
Tu peux aussi essayer de parler plus fort ou plus près du micro pour voir c'est mieux.

**Comment by alexylem** [comment]
Je viens de faire une mise à jour pour faire un test, mets à jour puis fait:
```
cd stt_engines/bing/
./test.sh
```
Il va envoyer le contenu de fichier `test.wav` à Bing (un enregistrement de ma voix avec mon micro). Et partage le résultat.

**Comment by stackgil** [comment]
Bonjour alex je viens de faire le test et voila le résultat

pi@raspberrypi:~ $ cd jarvis/
pi@raspberrypi:~/jarvis $ cd stt_engines/bing/
pi@raspberrypi:~/jarvis/stt_engines/bing $ ./test.sh
main.sh: ligne 43: uuidgen : commande introuvable
main.sh: ligne 55: my_debug : commande introuvable
main.sh: ligne 67: my_debug : commande introuvable
main.sh: ligne 71: $forder : redirection ambiguë
pi@raspberrypi:~/jarvis/stt_engines/bing $

**Comment by stackgil** [comment]
Re nouveau test 
j'ai fait un update ; upgrade du RPI
reboot
relance de jarvis
et : 
Checking for updates...[Up-to-date]

------------ Config ------------
platform              linux
language              fr_FR
play_hw               hw:0,0
rec_hw                hw:1,0
trigger_stt           snowboy
command_stt           bing
tts_engine            svox_pico
conversation_mode     true
--------------------------------

DEBUG: program_startup hook
Jarvis: Bonjour monsieur
Jarvis: Waiting to hear 'Jarvis'
Gil: (listening...)
ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.rear
ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.center_lfe
ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.side
ALSA lib confmisc.c:1286:(snd_func_refer) Unable to find definition 'cards.bcm28                                                                                        35.pcm.surround51.0:CARD=0'
ALSA lib conf.c:4259:(_snd_config_evaluate) function snd_func_refer returned err                                                                                        or: No such file or directory
ALSA lib conf.c:4738:(snd_config_expand) Evaluate error: No such file or directo                                                                                        ry
ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM surround21
ALSA lib confmisc.c:1286:(snd_func_refer) Unable to find definition 'cards.bcm28                                                                                        35.pcm.surround51.0:CARD=0'
ALSA lib conf.c:4259:(_snd_config_evaluate) function snd_func_refer returned err                                                                                        or: No such file or directory
ALSA lib conf.c:4738:(snd_config_expand) Evaluate error: No such file or directo                                                                                        ry
ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM surround21
ALSA lib confmisc.c:1286:(snd_func_refer) Unable to find definition 'cards.bcm28                                                                                        35.pcm.surround40.0:CARD=0'
ALSA lib conf.c:4259:(_snd_config_evaluate) function snd_func_refer returned err                                                                                        or: No such file or directory
ALSA lib conf.c:4738:(snd_config_expand) Evaluate error: No such file or directo                                                                                        ry
ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM surround40
ALSA lib confmisc.c:1286:(snd_func_refer) Unable to find definition 'cards.bcm28                                                                                        35.pcm.surround51.0:CARD=0'
ALSA lib conf.c:4259:(_snd_config_evaluate) function snd_func_refer returned err                                                                                        or: No such file or directory
ALSA lib conf.c:4738:(snd_config_expand) Evaluate error: No such file or directo                                                                                        ry
ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM surround41
ALSA lib confmisc.c:1286:(snd_func_refer) Unable to find definition 'cards.bcm28                                                                                        35.pcm.surround51.0:CARD=0'
ALSA lib conf.c:4259:(_snd_config_evaluate) function snd_func_refer returned err                                                                                        or: No such file or directory
ALSA lib conf.c:4738:(snd_config_expand) Evaluate error: No such file or directo                                                                                        ry
ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM surround50
ALSA lib confmisc.c:1286:(snd_func_refer) Unable to find definition 'cards.bcm28                                                                                        35.pcm.surround51.0:CARD=0'
ALSA lib conf.c:4259:(_snd_config_evaluate) function snd_func_refer returned err                                                                                        or: No such file or directory
ALSA lib conf.c:4738:(snd_config_expand) Evaluate error: No such file or directo                                                                                        ry
ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM surround51
ALSA lib confmisc.c:1286:(snd_func_refer) Unable to find definition 'cards.bcm28                                                                                        35.pcm.surround71.0:CARD=0'
ALSA lib conf.c:4259:(_snd_config_evaluate) function snd_func_refer returned err                                                                                        or: No such file or directory
ALSA lib conf.c:4738:(snd_config_expand) Evaluate error: No such file or directo                                                                                        ry
ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM surround71
ALSA lib confmisc.c:1286:(snd_func_refer) Unable to find definition 'cards.bcm28                                                                                        35.pcm.iec958.0:CARD=0,AES0=4,AES1=130,AES2=0,AES3=2'
ALSA lib conf.c:4259:(_snd_config_evaluate) function snd_func_refer returned err                                                                                        or: No such file or directory
ALSA lib conf.c:4738:(snd_config_expand) Evaluate error: No such file or directo                                                                                        ry
ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM iec958
ALSA lib confmisc.c:1286:(snd_func_refer) Unable to find definition 'cards.bcm28                                                                                        35.pcm.iec958.0:CARD=0,AES0=4,AES1=130,AES2=0,AES3=2'
ALSA lib conf.c:4259:(_snd_config_evaluate) function snd_func_refer returned err                                                                                        or: No such file or directory
ALSA lib conf.c:4738:(snd_config_expand) Evaluate error: No such file or directo                                                                                        ry
ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM spdif
ALSA lib confmisc.c:1286:(snd_func_refer) Unable to find definition 'cards.bcm28                                                                                        35.pcm.iec958.0:CARD=0,AES0=4,AES1=130,AES2=0,AES3=2'
ALSA lib conf.c:4259:(_snd_config_evaluate) function snd_func_refer returned err                                                                                        or: No such file or directory
ALSA lib conf.c:4738:(snd_config_expand) Evaluate error: No such file or directo                                                                                        ry
ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM spdif
ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.hdmi
ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.hdmi
ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.modem
ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.modem
ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.phoneline
ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.phoneline
ALSA lib pulse.c:243:(pulse_connect) PulseAudio: Unable to connect: Connection r                                                                                        efused

ALSA lib pulse.c:243:(pulse_connect) PulseAudio: Unable to connect: Connection r                                                                                        efused

Cannot connect to server socket err = No such file or directory
Cannot connect to server request channel
jack server is not running or cannot be started
INFO:snowboy:Silence
INFO:snowboy:Silence
INFO:snowboy:Silence
INFO:snowboy:Silence
INFO:snowboy:Keyword 1 detected at time: 2016-07-30 08:40:17
Jarvis
DEBUG: entering_cmd hook
Jarvis: Oui monsieur?
Gil: (listening...)
./timeout.sh 10 rec -V1 -q -r 16000 -c 1 -b 16 -e signed-integer --endian little                                                                                         jarvis-record.wav silence 1 0.1 1% 1 0.5 1% trim 0 10
DEBUG: speech duration was 15 (10 = 1 sec)
DEBUG: token missing or expired
DEBUG: json={"access_token":"eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJhcGltLXVzZX                                                                                        ItaWQiOiI0ZTNmMDI5ZDkxN2E0OWIxYjZlMjNjM2UxMWM0OTA4NyIsImFwaW0tc3Vic2NyaXB0aW9uLW                                                                                        lkIjoiNzNmY2E5MjQyNjQ4NDFjM2FjMTY3YzJiMTczNWZiNTQiLCJhcGltLXVzZXItZW1haWwiOiJzdG                                                                                        FjazIxNkBob3RtYWlsLmNvbSIsImFwaW0ta2V5IjoiMWQ4NTY5MjJlMDRmNGU1NmIzZjQ1ODRkZGYzZD                                                                                        A5NTAiLCJjbGllbnQtaWQiOiIxZDg1NjkyMmUwNGY0ZTU2YjNmNDU4NGRkZjNkMDk1MCIsInNjb3BlIj                                                                                        oiaHR0cHM6Ly9zcGVlY2gucGxhdGZvcm0uYmluZy5jb20iLCJpc3MiOiJ1cm46bXMub3hmb3JkIiwiYX                                                                                        VkIjoidXJuOm1zLnNwZWVjaCIsImV4cCI6MTQ2OTg2MTQyNX0.iycaXThkATndb-w5IMyEQyan0p3ClV                                                                                        k5gPCjpz2ohtA","token_type":"jwt","expires_in":"600","scope":"https://speech.pla                                                                                        tform.bing.com"}
DEBUG: token will expire in 590 seconds
DEBUG: curl https://speech.platform.bing.com/recognize/query?version=3.0&request                                                                                        id=eddbd40a-78e8-4881-a7ae-6c174730016d&appid=D4D52672-91D7-4C74-8AD8-42B1D98141                                                                                        A5&format=json&locale=fr-FR&device.os=linux&scenarios=ulm&instanceid=E043E4FE-51                                                                                        EF-4B74-8133-B728C4FEA8AA
DEBUG: json={"version":"3.0","header":{"status":"success","scenario":"ulm","name                                                                                        ":"quelle heure est-il","lexical":"quelle heure est-il","properties":{"requestid                                                                                        ":"dea92266-3c89-4848-b713-f11e25f0d87e","HIGHCONF":"1"}},"results":[{"scenario"                                                                                        :"ulm","name":"quelle heure est-il","lexical":"quelle heure est-il","confidence"                                                                                        :"0.9463555","properties":{"HIGHCONF":"1"}}]}
quelle heure est-il
$> say "il est `date +%H:%M`"
Jarvis: il est 08:40
Gil: (listening...)
./timeout.sh 10 rec -V1 -q -r 16000 -c 1 -b 16 -e signed-integer --endian little                                                                                         jarvis-record.wav silence 1 0.1 1% 1 0.5 1% trim 0 10
DEBUG: speech duration was 15 (10 = 1 sec)
DEBUG: curl https://speech.platform.bing.com/recognize/query?version=3.0&request                                                                                        id=a969f8a6-32ee-4a95-ba21-c55330d8c3f9&appid=D4D52672-91D7-4C74-8AD8-42B1D98141                                                                                        A5&format=json&locale=fr-FR&device.os=linux&scenarios=ulm&instanceid=E043E4FE-51                                                                                        EF-4B74-8133-B728C4FEA8AA
DEBUG: json={"version":"3.0","header":{"status":"success","scenario":"ulm","name                                                                                        ":"quel temps fait-il aujourd'hui","lexical":"quel temps fait-il aujourd'hui","p                                                                                        roperties":{"requestid":"eb8288be-2f3f-4366-a72e-41918960bcd4","HIGHCONF":"1"}},                                                                                        "results":[{"scenario":"ulm","name":"quel temps fait-il aujourd'hui","lexical":"                                                                                        quel temps fait-il aujourd'hui","confidence":"0.9502172","properties":{"HIGHCONF                                                                                        ":"1"}}]}
quel temps fait-il aujourd'hui
Jarvis: I did not understand: quel temps faitil aujourdhui
Gil: (listening...)
./timeout.sh 10 rec -V1 -q -r 16000 -c 1 -b 16 -e signed-integer --endian little                                                                                         jarvis-record.wav silence 1 0.1 1% 1 0.5 1% trim 0 10
DEBUG: speech duration was 18 (10 = 1 sec)
DEBUG: curl https://speech.platform.bing.com/recognize/query?version=3.0&request                                                                                        id=f2d704da-33f1-4b6a-89f7-a145e2cd7c88&appid=D4D52672-91D7-4C74-8AD8-42B1D98141                                                                                        A5&format=json&locale=fr-FR&device.os=linux&scenarios=ulm&instanceid=E043E4FE-51                                                                                        EF-4B74-8133-B728C4FEA8AA
DEBUG: json={"version":"3.0","header":{"status":"success","scenario":"ulm","name                                                                                        ":"quelle est la météo du jour","lexical":"quelle est la météo du jour","propert                                                                                        ies":{"requestid":"9d1feb29-7548-4403-aadc-c28b7582143f","HIGHCONF":"1"}},"resul                                                                                        ts":[{"scenario":"ulm","name":"quelle est la météo du jour","lexical":"quelle es                                                                                        t la météo du jour","confidence":"0.9080658","properties":{"HIGHCONF":"1"}}]}
quelle est la météo du jour
$> say "je regarde" && say "`wget -q -O- "www.accuweather.com/fr/fr/pradelles/16                                                                                        0357/weather-forecast/160357" | awk -F\' '/acm_RecentLocationsCarousel.push/{pri                                                                                        nt $14" avec une température de "$10" degrés" }'| head -1`"
Jarvis: je regarde
Jarvis: Alternance de nuages et d avec une température de 15 degrés
Gil: (listening...)
./timeout.sh 10 rec -V1 -q -r 16000 -c 1 -b 16 -e signed-integer --endian little                                                                                         jarvis-record.wav silence 1 0.1 1% 1 0.5 1% trim 0 10
DEBUG: speech duration was 08 (10 = 1 sec)
DEBUG: curl https://speech.platform.bing.com/recognize/query?version=3.0&request                                                                                        id=2d636491-31ad-4bed-b048-73088cf23127&appid=D4D52672-91D7-4C74-8AD8-42B1D98141                                                                                        A5&format=json&locale=fr-FR&device.os=linux&scenarios=ulm&instanceid=E043E4FE-51                                                                                        EF-4B74-8133-B728C4FEA8AA
DEBUG: json={"version":"3.0","header":{"status":"success","scenario":"ulm","name                                                                                        ":"au revoir","lexical":"au revoir","properties":{"requestid":"e3cf02d1-0ee7-4cc                                                                                        0-986d-cd706d6882d3","HIGHCONF":"1"}},"results":[{"scenario":"ulm","name":"au re                                                                                        voir","lexical":"au revoir","confidence":"0.9237856","properties":{"HIGHCONF":"1                                                                                        "}}]}
au revoir
$> say "Au revoir $username"; exit
Jarvis: Au revoir Gil
pi@raspberrypi:~/jarvis $

Cela fonctionne avec la logitech C170 mais vu qu'il n'y a pas possibilité de réglages avec, j'ai parlé plus fort et ça marche ;)

**Comment by alexylem** [comment]
Bon super. J'ai aussi corrigé le test script de bing, donc tu peux essayer de refaire:
```
pi@raspberrypi:~/jarvis $ cd stt_engines/bing/
pi@raspberrypi:~/jarvis/stt_engines/bing $ ./test.sh
```

**Comment by stackgil** [comment]
Voilà le résultat : 

pi@raspberrypi:~/jarvis $ cd stt_engines/bing/
pi@raspberrypi:~/jarvis/stt_engines/bing $ ./test.sh
main.sh: ligne 18: my_debug : commande introuvable
main.sh: ligne 26: my_debug : commande introuvable
main.sh: ligne 40: my_debug : commande introuvable
main.sh: ligne 43: uuidgen : commande introuvable
main.sh: ligne 55: my_debug : commande introuvable
main.sh: ligne 67: my_debug : commande introuvable
main.sh: ligne 71: $forder : redirection ambiguë
pi@raspberrypi:~/jarvis/stt_engines/bing $

**Comment by alexylem** [comment]
Tu as mis à jour Jarvis ?

**Comment by stackgil** [comment]
euh non je viens de le faire et le résultat : 
pi@raspberrypi:~/jarvis $ cd stt_engines/bing/
pi@raspberrypi:~/jarvis/stt_engines/bing $ ./test.sh
DEBUG: token missing or expired
DEBUG: json={"access_token":"eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJhcGltLXVzZXItaWQiOiI0ZTNmMDI5ZDkxN2E0OWIxYjZlMjNjM2UxMWM0OTA4NyIsImFwaW0tc3Vic2NyaXB0aW9uLWlkIjoiNzNmY2E5MjQyNjQ4NDFjM2FjMTY3YzJiMTczNWZiNTQiLCJhcGltLXVzZXItZW1haWwiOiJzdGFjazIxNkBob3RtYWlsLmNvbSIsImFwaW0ta2V5IjoiMWQ4NTY5MjJlMDRmNGU1NmIzZjQ1ODRkZGYzZDA5NTAiLCJjbGllbnQtaWQiOiIxZDg1NjkyMmUwNGY0ZTU2YjNmNDU4NGRkZjNkMDk1MCIsInNjb3BlIjoiaHR0cHM6Ly9zcGVlY2gucGxhdGZvcm0uYmluZy5jb20iLCJpc3MiOiJ1cm46bXMub3hmb3JkIiwiYXVkIjoidXJuOm1zLnNwZWVjaCIsImV4cCI6MTQ2OTg3ODAzMn0.8rQzzkkU3fVeZKga97ZXv_iXeCgIaHCIDrP6VOsVcVk","token_type":"jwt","expires_in":"600","scope":"https://speech.platform.bing.com"}
DEBUG: token will expire in 590 seconds
DEBUG: curl https://speech.platform.bing.com/recognize/query?version=3.0&requestid=c28c6fc6-42b7-4963-a280-901fa9ac4285&appid=D4D52672-91D7-4C74-8AD8-42B1D98141A5&format=json&locale=en-US&device.os=osx&scenarios=ulm&instanceid=E043E4FE-51EF-4B74-8133-B728C4FEA8AA
DEBUG: json={"version":"3.0","header":{"status":"success","scenario":"ulm","name":"hello","lexical":"hello","properties":{"requestid":"565a6bb2-4545-4c1f-8cef-43b0211aa6e5","HIGHCONF":"1"}},"results":[{"scenario":"ulm","name":"hello","lexical":"hello","confidence":"0.9498509","properties":{"HIGHCONF":"1"}}]}
hello

**Comment by stackgil** [comment]
pi@raspberrypi:~/jarvis $ cd stt_engines/bing/
pi@raspberrypi:~/jarvis/stt_engines/bing $ ./test.sh
DEBUG: token missing or expired
DEBUG: json={"access_token":"eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJhcGltLXVzZXItaWQiOiI0ZTNmMDI5ZDkxN2E0OWIxYjZlMjNjM2UxMWM0OTA4NyIsImFwaW0tc3Vic2NyaXB0aW9uLWlkIjoiNzNmY2E5MjQyNjQ4NDFjM2FjMTY3YzJiMTczNWZiNTQiLCJhcGltLXVzZXItZW1haWwiOiJzdGFjazIxNkBob3RtYWlsLmNvbSIsImFwaW0ta2V5IjoiMWQ4NTY5MjJlMDRmNGU1NmIzZjQ1ODRkZGYzZDA5NTAiLCJjbGllbnQtaWQiOiIxZDg1NjkyMmUwNGY0ZTU2YjNmNDU4NGRkZjNkMDk1MCIsInNjb3BlIjoiaHR0cHM6Ly9zcGVlY2gucGxhdGZvcm0uYmluZy5jb20iLCJpc3MiOiJ1cm46bXMub3hmb3JkIiwiYXVkIjoidXJuOm1zLnNwZWVjaCIsImV4cCI6MTQ2OTg3ODAzMn0.8rQzzkkU3fVeZKga97ZXv_iXeCgIaHCIDrP6VOsVcVk","token_type":"jwt","expires_in":"600","scope":"https://speech.platform.bing.com"}
DEBUG: token will expire in 590 seconds
DEBUG: curl https://speech.platform.bing.com/recognize/query?version=3.0&requestid=c28c6fc6-42b7-4963-a280-901fa9ac4285&appid=D4D52672-91D7-4C74-8AD8-42B1D98141A5&format=json&locale=en-US&device.os=osx&scenarios=ulm&instanceid=E043E4FE-51EF-4B74-8133-B728C4FEA8AA
DEBUG: json={"version":"3.0","header":{"status":"success","scenario":"ulm","name":"hello","lexical":"hello","properties":{"requestid":"565a6bb2-4545-4c1f-8cef-43b0211aa6e5","HIGHCONF":"1"}},"results":[{"scenario":"ulm","name":"hello","lexical":"hello","confidence":"0.9498509","properties":{"HIGHCONF":"1"}}]}
hello

**Comment by alexylem** [comment]
Donc il t'as bien renvoyé "hello" ce qui correspond au mot prononcé (par moi) dans test.wav. Ca veut dire que ca marche 😄

**Comment by stackgil** [comment]
oui je dois juste tester avec mon autre micro et que je regarde #26 car je me vois pas hurler pour faire une commande ;)

**Comment by Tushti02** [comment]
Hi ,
I am facing the same error. I attache a .wav file on bot emulator and it should convert its vocal to text.
But I get {"version":"3.0","header":{"status":"error","properties":{"requestid":"64bd22e3-6f68-4d89-8f8b-05dba0e30c9f","NOSPEECH":"1"}}}

Could you please help if the problem was solved for you ?
