### ISSUE TITLE
Impossible d'installer pocketsphinx ou snowboy

### ISSUE THREAD

**Issue by Seeyko** [alexylem/jarvis#750]
### Description

Bonjour Alex, j'avais déja utiliser jarvis il y a quelque mois sans trop trop de problème mais aujourd'hui je le reinstalle et je n'arrive plus, voici les logs lorsque je clique sur installé pocketsphinx :

### Logs
```W: An error occurred during the signature verification. The repository is not updated and the previous index files will be used. GPG error: http://deb.playonlinux.com precise InRelease: Les signatures suivantes n'ont pas pu être vérifiées car la clé publique n'est pas disponible : NO_PUBKEY 73F0D6E88E3D6C3A
W: An error occurred during the signature verification. The repository is not updated and the previous index files will be used. GPG error: http://repository.spotify.com stable InRelease: Les signatures suivantes n'ont pas pu être vérifiées car la clé publique n'est pas disponible : NO_PUBKEY EFDC8610341D9410
W: The repository 'http://ppa.launchpad.net/ingalex/super-boot-manager/ubuntu xenial Release' does not have a Release file.
W: Impossible de récupérer http://deb.playonlinux.com/dists/precise/InRelease  Les signatures suivantes n'ont pas pu être vérifiées car la clé publique n'est pas disponible : NO_PUBKEY 73F0D6E88E3D6C3A
W: Impossible de récupérer http://repository.spotify.com/dists/stable/InRelease  Les signatures suivantes n'ont pas pu être vérifiées car la clé publique n'est pas disponible : NO_PUBKEY EFDC8610341D9410
E: Impossible de récupérer http://ppa.launchpad.net/ingalex/super-boot-manager/ubuntu/dists/xenial/main/binary-i386/Packages  404  Not Found
W: Le téléchargement de quelques fichiers d'index a échoué, ils ont été ignorés, ou les anciens ont été utilisés à la place.

```
Et pour installer snowboy j'ai cloner le repo github de snowboy dans le /jarvis/stt_engines/snowboy mais lorsque je clique sur snowboy il le voit toujours desinstaller..
EDIT : Je suis sous ubuntu 16.04 en 32 bits et snowboy ne semble pas fournir de versions, je peux contourner cela en utilisant une autre version de snowboy ou bien je dois obligatoirement utiliser bing ou pocketsphinx ? (Je precise que c'est simplement pour une presentation de la reconnaissance vocale dans une classe d'iut info donc pas grave si c'est en ligne/hors ligne)

Merci !

Cordialement,

Andrieu Tom.

**Comment by Oliv4945** [comment]
Salut,

Concernant PocketSphinx le soucis n'est pas dans le petit log que tu as donné, il faudrait le log entier.
Les warnings que tu montres sont liés à des depots dans ton fichier de config qui ne vont pas (spotify et superboot visiblement). Si tu n'as pas de soucis à être en ligne, je te conseille de faire Snowboy+Bing, plus facile et de meilleur qualité.

Pour Snowboy il faut effectivement le recompiler toi même pour ta plateforme, voir [ici](https://github.com/alexylem/jarvis/issues/660#issue-240023900).

**Comment by TomSeeyko** [comment]
Salut, oui j'ai pas de soucis pour être en ligne, mais je n'arrivais pas non plus a installer les dépendances pour la compilation de snowboy non plus... Mais du coup je vais faire toute ma présentation sur mon raspberry pi (la dessus l'installation se passe sans aucun problème !) Je dois juste emmener tout le matos a l'IUT mais bon c'est pas un problème ! 
Merci de ta réponse en tout cas
