### ISSUE TITLE
Petit probléme avec Snowboy

### ISSUE THREAD

**Issue by MoiLeviathan** [alexylem/jarvis#751]
### Description

Bonjour, j'ai suivi toute la méthode pour installer Jarvis, tout est reconnu (tant le haut parleur que le micro (Andoer multidirectionnel) mais je n'arrive pas a ajouter un snowboy.

Pourtant j'ai créer le miens sur le site, je l'ai mis dans le dossier. Il est bien reconnu par Jarvis car il est dans la liste. Mais quand je veux l'entrainer, je parle pour dire le mot clé, puis je fait Ctrl C et ce 3 fois. A la fin j'ai ca :  

### Logs

Input File     : 'default' (alsa)
Channels       : 2
Sample Rate    : 48000
Precision      : 16-bit
Sample Encoding: 16-bit Signed Integer PCM

In:0.00% 00:00:03.58 [00:00:00.00] Out:144k  [      |      ]        Clip:0
Done.

Input File     : 'default' (alsa)
Channels       : 2
Sample Rate    : 48000
Precision      : 16-bit
Sample Encoding: 16-bit Signed Integer PCM

In:0.00% 00:00:03.58 [00:00:00.00] Out:144k  [    -=|=-    ]        Clip:0
Done.
Checking updates for jarvis...Up-to-date
rec WARN formats: can't set sample rate 16000; using 11025

Input File     : 'default' (alsa)
Channels       : 1
Sample Rate    : 11025
Precision      : 16-bit
Sample Encoding: 16-bit Signed Integer PCM

In:0.00% 00:00:04.46 [00:00:00.00] Out:44.0k [      |      ] Hd:5.5 Clip:0    ^C
Aborted.
rec WARN formats: can't set sample rate 16000; using 11025

Input File     : 'default' (alsa)
Channels       : 1
Sample Rate    : 11025
Precision      : 16-bit
Sample Encoding: 16-bit Signed Integer PCM

In:0.00% 00:00:03.72 [00:00:00.00] Out:44.0k [ =====|===== ] Hd:4.9 Clip:0    ^C
Aborted.
rec WARN formats: can't set sample rate 16000; using 11025

Input File     : 'default' (alsa)
Channels       : 1
Sample Rate    : 11025
Precision      : 16-bit
Sample Encoding: 16-bit Signed Integer PCM

In:0.00% 00:00:04.46 [00:00:00.00] Out:44.0k [      |      ]        Clip:0    ^C
Aborted.
Training model...
######################################################################## 100,0%
{"detail":"Authentication credentials were not provided."}
ERROR: Missing/Invalid Snowboy token
HELP: Your token: ekko
HELP: Set it in menu Settings / Voice Reco / Snowboy Settings / Token

J'ai le même résultat si je laisse snowboy, d'origine.
Que dois je faire ?
Merci d'avance.

**Comment by bildu60** [comment]
salut
Je vois à la fin : ERROR: Missing/Invalid Snowboy token
As tu bien renseigné le token de snwboy?
Je te decris comment j ai fait si ça peut t aider:
1) allez sur le site : https://snowboy.kitt.ai/
se loger (moi je me loge avec mon compte google)
2) je clique sur "create hotword"
3) Il y a trois etapes ,a la derniere tu dois telecharger un fichier
4) il faut aussi recupere un token (suite de caractére) que tu trouves dans :
Tu clique en haut a droite sur l avatar qui est sencé te représenter puis sur profil setting,en dessous tu as you api token (tu doid copier cette suite de caractere).
5) Tu dois copier le fichier que tu as telecharger a l etape 3 dans jarvis/stt_engines/snowboy/resources/
6) tu lances jarvis et tu vas dans setting/ Voice recognition /Recognition of magic word et la tu choisis : snowboy
7) ensuite tu vas sur setting/ Voice recognition /Snowboy settings/Token  et tu colle la suite de caractere que tu as eu à l'etape 4.
Tu relances  jarvis et enjoy
Tu peux te rendre également a cette adresse : https://www.openjarvis.com/content/snowboy
c'est a cette adresse qu'il explique tout ça.
En attendant un petit retour de ta part pour me dire que tout est ok,je te souhaite une bonne soirée

**Comment by Oliv4945** [comment]
Super, on ne peut pas répondre mieux que @bildu60, merci !
A noter que `ekko` doit être dans non, pas dans "token api"

**Comment by MoiLeviathan** [comment]
Merci beaucoup de votre aide, tout marche maintenant ^^.
Par contre j'ai l'impression qu'il est très lent, et qu'il n'est pas très précis.

Et une autre question, je vois que Jarvis reconnaît par exemple comment * vas * ?
ca veut dire que je vois enregistrer d'abord le snowboy comment et ensuite vas ou je dois faire la phrase comment vas tu ?

Merci encore de vos réponses.

**Comment by bildu60** [comment]
Bonjour
Pour la reconnaissance vocal on utilise Snowboy uniquement pour la reconnaissance du  magic word (mot qui va permettre a jarvis de ce mettre en mode ecoute)
Pour le reste il est vivement conseillé d'utiliser bing.voir https://www.openjarvis.com/content/stt
Pour la paramétrage de bing voir https://www.openjarvis.com/content/bing
Si tu as besoin d un coup de main pour le paramétrage de bing je suis dispo.
Bon courage

**Comment by domotic-29** [comment]
Bonjour,

Je trouve que la dernière question de l'auteur est intéressante et je suis aussi intéressé pas la réponse.
J'utilise bing, mais je préférerais me contenter de Snowboy...

**Comment by Oliv4945** [comment]
@MoiLeviathan , @domotic-29 
Seul snowboy doit être entraîné, afin de pouvoir reconnaître un jeu réduit de mot hors ligne, un seul dans le cas de Jarvis. Dès que ce mot ce mot clef est reconnu tout l'audio est passé à un autre moteur de reconnaissance comme Bing qui sait reconnaitre des phrases complètes sans entraînement utilisateur

**Comment by domotic-29** [comment]
@Oliv4945 
Oui, il faut entraîner Snowboy, et c'est justement là dessus que porte la question.
Dans le cas d'une utilisation avec un nombre assez limité de mots/phrases, ça peut être intéressant d'utiliser Snowboy pour le respect de la vie privée et l'utilisation à 100% hors ligne.
Dans mon cas j'ai allume/éteins-lampe, ouvre/ferme-volet, température, et puis la liste des pièces (extérieur, salon, etc.).
Si on peut se contenter des mots clés, on voit que c'est assez peu, donc rapide à faire.
Par contre s'il faut reconstituer toutes les phrases possible, cela va être beaucoup plus long et contraignant.
Autrement dit, si on entraîne Snowboy avec les 3 mots (3 enregistrements distincts) Allume/Lampe/Salon, est-ce qu'il reconnaîtra la phrase "Allume la lampe du salon" ?

**Comment by Oliv4945** [comment]
J'avais joué un peu à ça avant Jarvis, ce n'est pas évident: plus il y a de mots à détecter en parallèle plus Snowboy prend de ressources, mais surtout il a du mal à enchaîner les mots donc il faut laisser une petite pause et ce n'est pas très naturel.

**Comment by domotic-29** [comment]
Ok, merci pour ce retour d'expérience :)

**Comment by domotic-29** [comment]
Il y a une vidéo sympa ici : https://www.youtube.com/watch?v=WIWkxEwM088&index=5&list=PL5h7NsxkT9YNeruVRhxyPRkfApqozn7xg

**Comment by Oliv4945** [comment]
Ok, je ferme
