### ISSUE TITLE
Variante home automation pour domoticz

### ISSUE THREAD

**Issue by landaisbenj** [alexylem/jarvis#752]
Bonjour. J'ai voulu facilité l'installation du plugin home automation pour ceux qui ont domoticz. J'ai modifié pas mal de chose pour concaténer home automation et temperature domoticz.
J'ai simplifier les codes ce qui je pense permettra d'ajouter d'autre fonction dans le temps.

Je voulais proposer les modifs sous forme de plugin mais je n'y connais rien a github. J'ai deja mis énormément de temps a savoir ou poster mes info.

Si l'idée peut etre réalisé vous pouvez m'aider un poil ?

**Comment by landaisbenj** [comment]
Jarvis est mort ? :'(

**Comment by wikijm** [comment]
Bonsoir @landaisbenj,

Où-là, non c'est juste que tous les contributeurs ont une semaine bien chargée 😜 
Commence par regarder du côté de https://github.com/alexylem/jarvis-plugin, qui est la structure de base pour faire un plugin.

Si tu souhaites en faire une copie sur ton compte pour y apporter ton travail pour Domoticz, il faut cliquer en haut de page sur 'Fork'. Tu pourras également suivre le tuto suivant : https://openjarvis.com/content/publish-your-plugin

**Comment by landaisbenj** [comment]
Ok cool :) Désolé c'est quand j'ai vu l'agenda de contribution de alexylem. Cela aurait ete dommage... Merci beaucoup pour les liens. Je crois qu'ils etaient proposé dans jarvis en plus mais je n'avais plus pensé a regarder. J'y vais de suite.

**Comment by landaisbenj** [comment]
Alors, pour la structure il n'y a pas de probleme. De toute facon je me suis appuyer sur l'existant dont deux plugin, home controle et domoticz temperature.
Par contre pour la creation, je n'ai pas fait fork j'ai fais la procédure de publish your plugin. J'ai bien le plugin de créé dans mon jarvis a moi, mais je n'ai pas de diffusion sur mon github... Apparemment ca doit etre automatique mais la ca ne fonctionne pas.. Je ne sais pas comment diffuser en manuel ?

Simply follow the instructions:
Provide a name for your plugin
Your plugin will be created locally from a basic plugin template
**Provide your GitHub credentials to publish your repo (100% secured)**

**Comment by wikijm** [comment]
Dans la procédure https://www.openjarvis.com/content/publish-your-plugin, il t'est conseillé d'utiliser le client Windows [GitHub Desktop](https://desktop.github.com/).

Cela te permettra de déposer tes fichiers dans un repository (dépôt en français) et ainsi partager ton script sur GitHub.

**Comment by landaisbenj** [comment]
Merci beaucoup !! Justement j’étais en train de voir cela... Je pensai que le dépôt se faisait tout seul via la création de plugin de jarvis...

**Comment by Oliv4945** [comment]
Salut @landaisbenj 

Effectivement ça devrait se mettre en place tout seul en utilisant le générateur intégré à Jarvis.

Si tu n'es pas sur de tes commandes Git, qu'utilises-tu ? Globalement il faut:
1. Ajouter tes fichiers dans le dossier créé par Jarvis (dans `plugins_installed`)
2. Aller dans le dossier de ton plugin puis: `git add .` pour indiquer à Git que tu veux qu'il prenne en compte tous les nouveaux fichiers
3. `git commit -m "Un message decrivant tes actions"` pour lui dire de les enregistrer en tant que nouvelle version
4. `git push -u origin master` pour lui dire de l'envoyer sur Github, branche master. Par la suite `git push` suffit

**Comment by landaisbenj** [comment]
A ok je ne savais meme pas qu'il y avait des commandes pour git hub. 
Bon apparement ca ne fonctionne pas plus. il a pas l'air de me trouver mon repo. Faut-il que le repo soit deja préalablement créé ?

**Comment by landaisbenj** [comment]
Alors j'ai refait la manip entiere via jarvis. Create a plugin. J'ai bien le repo qui se créé. Mais je n'ai pas les fichier dans le repo alors que je les ai dans le dossier sur le pi.

**Comment by landaisbenj** [comment]
J'ai reussi. Franchement j'ai ga-lé-ré un truc de malade. Mais au moins c'est en ligne je pourrais maintenant faire des modifications plus facilement.

**Comment by Oliv4945** [comment]
Super, je ferme l'issue du coup
