### ISSUE TITLE
Problème début de réponse

### ISSUE THREAD

**Issue by loujarvis** [alexylem/jarvis#753]
salut,
je suis un tout nouvel utilisateur de Jarvis, sachez que je ne suis pas encore super calé en informatique.
Mon problème c'est qu'a chaque début de réponse de la part de mon jarvis, il y a un temps muet.
(exemple: réponse normal: "désolé, je ne comprend pas"
réponse entendu: "... ne comprend pas")

j'ai essayer de trouver une solution dans "setting-audio" mais je ne comprend pas tout et malgré mes tentatives le problème persiste. Je n'ai pourtant rien modifier après l'installation de jarvis, pouvez-vous m'aider?
Merci

Louis

**Comment by bildu60** [comment]
Salut
J'ai eu le meme deconvenu,pour decouvrir par la suite que cela été du par la sorti HDMI que j utilisai.J'ai réglé ce probléme en passant par des enceintes branchées sur le jack (sortie son analogique )du raspberry

Voir : https://github.com/alexylem/jarvis/issues/749
