### ISSUE TITLE
Problème avec la reconnaissance du mot magic

### ISSUE THREAD

**Issue by Kev24** [alexylem/jarvis#754]
Bonjour à tous,

Suite à l'installation de Jarvis, celui-ci fonctionne correctement sauf une petite chose.
Je m'explique.
Lors que celui-ci est actif, je l'appel pour lui donner un ordre: 

MOI : "jarvis"
mais lui ne me répond pas.

pour qu'il m'écoute, je suis obligé de lancer la commande suivante :
http://ipduraspberry:8085/?action=listen
et la il m'écoute et répond correctement aux ordres.

Quelqu'un aurait une réponse à mon problème?

Merci d'avance pour vos réponses.

**Comment by Oliv4945** [comment]
Bonjour,
Comme demande quand vous avez créé l'issue, que donne `jarvis -nv` ?

**Comment by Kev24** [comment]
Bonjour @Oliv4945 

Voici le résultat de la commande 'jarvis-nv'

------------ Config ------------
jv_branch            master 
jv_version            
jv_arch              armv7l 
jv_os_name           raspbian 
jv_os_version        9 
language             fr_FR 
play_hw              hw:0,0 
rec_hw               hw:1,0 
speaker              ALSA 
microphone           Asahi Kasei Microsystems Co., Ltd  
recorder             snowboy 
trigger_stt          snowboy 
command_stt          bing 
tts_engine           svox_pico 
--------------------------------

DEBUG: program_startup hook
Starting RestAPI server on http://192.168.1.33:8085
Starting User Interface on http://192.168.1.33:8086
DEBUG: start_speaking hook

**Comment by Oliv4945** [comment]
Bonjour,

J'ai l'impression qu'il manque la fin, est-ce possible de recommencer avec un log complet ?

Merci

**Comment by Kev24** [comment]
oui j'ai coupé, excuse moi.

`pi@raspberrypi:~/jarvis $ ./jarvis.sh -nv
Notice: you can use 'jarvis' instead of './jarvis.sh'

------------ Config ------------
jv_branch            master 
jv_version            
jv_arch              armv7l 
jv_os_name           raspbian 
jv_os_version        9 
language             fr_FR 
play_hw              hw:0,0 
rec_hw               hw:1,0 
speaker              ALSA 
microphone           Asahi Kasei Microsystems Co., Ltd  
recorder             snowboy 
trigger_stt          snowboy 
command_stt          bing 
tts_engine           svox_pico 
--------------------------------

DEBUG: program_startup hook
Starting RestAPI server on http://192.168.1.33:8085
Starting User Interface on http://192.168.1.33:8086
DEBUG: start_speaking hook
Jarvis: Jarvis est là !
DEBUG: stop_speaking hook
User defined commands:
                        *TEST*                  *VERSION*
*AIDE*                                          *COMMENT APPEL MOI*|*QU
*OU SOMMES NOUS*        *REPETE (*) ET (*)      ANNULE COMMANDE*|TERMIN
ENCORE*|*REPETE COMMAND                         *BONJOUR*|*SALUT*
*COUCOU*                *BONSOIR*               *BONNE*SOIREE*
*CA VA*|*COMMENT CA VA* >*OUI*                  >*NON*|*PAS*
*MERCI*                 *AU REVOIR*|*BYE*
*NUMERO*POMPIERS*       *NUMERO*POLICE*|*GENDAR *NUMERO*SAMU*
*NUMERO SANS ABRIS*     *NUMERO ENFANTS MALTRAI *NUMERO KEVIN*
                        *TA GUEULE*|*TG*        *PUTE*
                        *COMMENT JE M APPELLE*| *QUI SUIS-JE*|*QUI SUIS
*OU SUIS-JE NE*|*OU SUI *QUAND SUIS-JE NE*|*QUA *QUEL EST MON TRAVAIL*
                        *QUEL EST TON PRENOM*   *QUI EST TU*
*OU EST TU NE*          *QUI EST TON CREATEUR*  *QUAND EST TU NE*
                        *TU COMPTE BIEN*|TU COM
Commands from plugin jarvis-api:

Commands from plugin jarvis-ui:
*OUVR*INTERFACE*
Commands from plugin jarvis-time:
*QUELLE HEURE*          *QUEL JOUR*
Commands from plugin jarvis-calendar:
*AJOUTE*EVENEMENT*      > (*)                   >> (*)
>>> (*)                 >>>> (*)                >>>>> (*)
>>>>>> (*)              >>>>>>> (*)             >>>>>>>> *OUI*
>>>>>>>> *NON*                                  *QUAND*EVENEMENT (*)
*EVENEMENT*JOUR*        *EVENEMENT*DEMAIN*      *PROCH*EVENEMENT*
Commands from plugin jarvis-testdebitadsl:
*DEBIT*INTERNET|*ADSL   *DEBIT*MINIMUM*         *DEBIT*MAXIMUM*
Commands from plugin jarvis-meteo-suisse:
*METEO*ACTUELLE*        *METEO*AUJOURD*         *METEO*DEMAIN*
*PLEUVOIR*DEMAIN*
Commands from plugin jarvis-ephemeride:
*FETE*JOUR*|*LA*SAINT*|
Commands from plugin jarvis-livebox:
*REDEMARE*              *REBOOT*                *NUMERO*
*RELANCE*INTERNET*      *PARTAGE*               *ACTIVER*WIFI*
*DESACTIVER*WIFI*       *ADRESSE*IP*            *MOT DE PASSE*LIVEBOX*
Commands from plugin jarvis-minuterie:
*EFFACE*MINUTE*         *MINUTE*                >(*)
Commands from plugin jarvis-deezer:
*LIST*PLAYLIST*         *PLAYLIST* (*)          *MIX* (*)
*ARR*TE*|*STOP*         *PAUSE*                 *LECTURE*
*CHANSON*SUIVANT*|*CHAN *CHANSON*PRECEDENT*|*CH *VOLUME*PAR D*FAU*
*VOLUME*FOND*           *VOLUME * (*)           *PLUS*FORT*|*AUGMENTE*|
*MOINS*FORT*|*BAISSE*   *TITRE*|*ARTISTE*
Commands from plugin jarvis-cestquand:
*PROCHAIN*EVENEMENT*|*P AVERTIRSILENCEEVENEMENT 
*EST QUAN[^ ] (*)       *EST*JOUR*LE (*)        POURPLUGINPIRESCLAVE
Commands from plugin jarvis-math:
*CALCUL* (*)
Commands from plugin jarvis-blagues:
*RACONT*BLAGUE*         *REPETE*BLAGUE*         *RETIEN*BLAGUE*
*LI*BLAGUE*NUM* (*)     *COMBIEN*BLAGUE*
Commands from plugin jarvis-liste-des-courses:
*AJOUTE (*) A LA LISTE* *SUPPRIME*LA LISTE*|*VI >*OUI*
>*NON*                  *LIS LA LISTE*|*QUOI*DA *ENVOI*LA*LIST*MAIL*
Commands from plugin jarvis-wikipedia:
*DONNE*DEFINITION*DE (*
Commands from plugin jarvis-wol:
*DEMARRE*PC (*)
Commands from plugin plugins_installed:

Jarvis: Waiting to hear 'Jarvis'
Kévin: (listening...)
DEBUG: models=jarvis
INFO:snowboy:Ticks: [2, 20, 5, -1]`

**Comment by Oliv4945** [comment]
Ok, comment as-tu généré ton mot magique ?
Est-ce que tu pourrais essayer d'en refaire un avec 3 syllabes ou plus pour tester ?

**Comment by Kev24** [comment]
Je l'ai généré lors de l'installation en le saisissant a l'écrit puis en le prononçant 3 fois.
J'ai changé le mot magique 'Jarvis' par 'OK Jarvis', maintenant cela fonctionne correctement.
Merci de votre aide.
Bonne soirée et bonne continuation sur le projet Jarvis.
PS : j'ai une autre question concernant un plugin, dois-je ouvrir un autre sujet ou peut'n en parler ici ?

**Comment by Oliv4945** [comment]
Super !
Même si ça fonctionne souvent bien avec deux syllabes, 3 est vraiment
recommandé, ce n'est pas pour rien que l'on a "Cortana", "Alexa", "Dis
siri", "ok Google" et "Snowboy" :-)

Pour le plugin il faut ouvrir une issue sur le repo git du plugin en lui
même, merci

**Comment by Kev24** [comment]
Ok merci beaucoup bonne soirée
