### ISSUE TITLE
install en boucle + snowboy fail

### ISSUE THREAD

**Issue by davidm06** [alexylem/jarvis#758]
### Description
bonjour
j'installe Jarvis comme decrit dans la video sur une raspberry.
j'arrive au bout avec l'option des moteurs, je choisis Snowboy. me dit que ce n'est pas installé et sort de l'install jarvis.
j'installe donc Snowboy manuellement, relance jarvis install et me retrouve dans le meme process, avec le meme message pour snowboy...
ca tourne en boucle quoi...
merci pour votre aide
david

**Comment by Oliv4945** [comment]
Peux-tu faire un Ascii cinéma ?

**Comment by Oliv4945** [comment]
Salut,

Je ferme en attendant une réponse
