### ISSUE TITLE
Playstation eyes & enregistrement bing

### ISSUE THREAD

**Issue by Voix78** [alexylem/jarvis#759]
### Description
J'utilise la playstation eyes en tant que micro suite à une lecture sur un forum GB.
J'ai encore des pb de detection des voix.
J'arrive à l'utiliser avec Jarvis, je voulais savoir si on peut optimiser la détection lointaine et augmenter le gain et/ou profiter des 4 micros intégrés.

Quand je dis "au revoir" la commande n'est pas comprise, je n'arrive à avoir un compte bing sauf un compte payant cb apparait....

Merci d'avance de vos retours

### Logs
```shell
<PASTE HERE> full content of the terminal with Jarvis in troubleshooting mode
(keep triple quotes above and below to preserve formatting) 
```
Alternatively attach a terminal session recording using asciinema:
```shell
sudo apt-get install -y asciinema && asciinema rec # start session recording
./jarvish.sh -nv # start jarvis directly in troubleshooting mode
Ctrl+D # stop recording
y # yes to upload and get URL to paste here
```

**Comment by Oliv4945** [comment]
Comme écrit, merci de poster le log avec `jarvis -nv`
Pour le compte Microsoft si vous ne voulez pas le faire il est possible d'utiliser wit

**Comment by wikijm** [comment]
Clôture du ticket jusqu'à obtention d'une réponse de la part de l'auteur de l'issue.
Closing of the ticket until a valid answer from the applicant is obtained.
