### ISSUE TITLE
Switcher les moteurs

### ISSUE THREAD

**Issue by foxmix** [alexylem/jarvis#761]
Salut les gens,

Tout d'abord, très gros et beau boulot @alexylem, ca force le respect.

Ce qui pourrait être pas mal (si ca n'a pas déjà été soulevé, j'ai quasiment tout parcouru) c'est de pouvoir switcher de moteur : 
- en pleine conversation (à la demande)
- en cas de non compréhension du kw

Voili voilou, et encore GOOD JOB MAN :+1:

**Comment by Oliv4945** [comment]
Salut,

En cas de non compréhension du keyword ça doit être faisable mais le meilleur actuellement est Snowboy, donc je ne suis pas sur de l'utilité.
Pour le switch en pleine conversation, as-tu un exemple de l'utilité ? En tout cas ce n'est pas dur, il suffit de mettre dans ton fichier de commandes `Change pour bing==export "command_stt=bing` && say "OK"`

Attention je n'ai pas testé, mais c'est l'idée ;)

**Comment by foxmix** [comment]
Salut @Oliv4945, 

Le problème est qu'avec snowboy c'est qu'il ne peut que matcher que ce qui est pré-configuré...
Je veux snowboy pour les KW et puis bing pour retranscrire le reste lorsque cela est nécessaire:
>(*)== ...

Je viens de configurer un plug-in qui va scraper youtube avec la requete et récupérer l'id de la 1ère vidéo puis push l'url sur chronium (pourquoi ne pas utiliser le plug-in existant me direz-vous... tout simplement car ma ligne est à 3Mo, oui oui c'est possible, fibre à 200m et même pas de simple haut débit ici, donc je ne peux download la vidéo comme le fait ce plug-in, autant streamer la data dans mon cas).

Bref, ca marche si je configure snowboy + bing en reconnaissance mais je n'ai pas besoin de bing pour tous les kw.

Je vais tester ta soluce

**Comment by foxmix** [comment]
Merci @Oliv4945 c'est bon ca marche :)

**Comment by foxmix** [comment]
Bon et bien non j'ai dû me planter j'ai toujours:

`/usr/local/bin/jarvis: ligne 465: bing_STT` 

quelque soit la syntaxe

**Comment by Oliv4945** [comment]
Salut,

Quel est le code complet que tu utilises ?

**Comment by wikijm** [comment]
Clôture du ticket jusqu'à obtention d'une réponse de la part de l'auteur de l'issue.
Closing of the ticket until a valid answer from the applicant is obtained.
