### ISSUE TITLE
Problème reconnaissance mot clé

### ISSUE THREAD

**Issue by Voix78** [alexylem/jarvis#763]
### Description

Bon voilà mon pb.
il ne semble pas reconnaître le mot clé enregistré trois fois.

### Logs

pi@chr:~/jarvis $ jarvis -nv

jv_branch            master
jv_version           17.08.29
jv_arch              armv7l
jv_os_name           raspbian
jv_os_version        9
language             fr_FR
play_hw              hw:0,1
rec_hw               hw:1,0
speaker              ALSA
microphone           Nam Tai E&E Products Ltd. or OmniVision Technologies, Inc. Sony Playstation Eye
recorder             sox
trigger_stt          snowboy
command_stt          snowboy
tts_engine           svox_pico

DEBUG: program_startup hook
DEBUG: start_speaking hook
Heva: Hello
DEBUG: stop_speaking hook
User defined commands:
*AIDE*                  *BONJOUR*|*SALUT*       *COMMENT*APPELLE*
*MERCI*                 *AU REVOIR*|*BYE*       ANNULE*|TERMINE*
ENCORE*                 *TEST*                  *VERSION*
*REPETE (*) ET (*)      *CA VA*                 >*OUI*
>*NON*|*PAS*
Heva: Waiting to hear 'Heva'
Chris: (listening...)
DEBUG: models=heva
INFO:snowboy:Ticks: [2, 20, 5, -1]
INFO:snowboy:Keyword 1 detected at time: 2017-12-07 17:55:12
INFO:snowboy:Keyword 1 detected at time: 2017-12-07 17:55:21
INFO:snowboy:Ticks status: 2 21 0 1
WARNING:snowboy:No match voice_before
INFO:snowboy:Keyword 1 detected at time: 2017-12-07 17:55:31
INFO:snowboy:Ticks status: 2 2 0 1
DEBUG: modelid=0
Heva
DEBUG: entering_cmd hook
Chris: (listening...)
DEBUG: models=alexa,heva,jarvis,lea,rebeca,snowboy
INFO:snowboy:Ticks: [2, 20, 5, -1]
DEBUG: timeout, end of conversation
DEBUG: listening_timeout hook
DEBUG: exiting_cmd hook
Heva: Waiting to hear 'Heva'
Chris: (listening...)
DEBUG: models=heva
INFO:snowboy:Ticks: [2, 20, 5, -1]
INFO:snowboy:Keyword 1 detected at time: 2017-12-07 17:55:50
INFO:snowboy:Ticks status: 2 1 0 1
DEBUG: modelid=0
Heva
DEBUG: entering_cmd hook
Chris: (listening...)
DEBUG: models=alexa,heva,jarvis,lea,rebeca,snowboy
INFO:snowboy:Ticks: [2, 20, 5, -1]
DEBUG: timeout, end of conversation
DEBUG: listening_timeout hook
DEBUG: exiting_cmd hook
Heva: Waiting to hear 'Heva'
Chris: (listening...)
DEBUG: models=heva
INFO:snowboy:Ticks: [2, 20, 5, -1]
^C
DEBUG: program_exit hook

Please need help huhu

**Comment by Oliv4945** [comment]
Salut,

Deux soucis:
1. "Heva" c'est un peu petit, essaie un mot clef en 3 syllabes, j'ai vu que tu as enregistré "Revecca" c'est pas mal.
2. Ton "command_stt" est Snowboy au lieu de Bing, donc il quand il détecte heva il ne lance pas le bon STT pour reconnaître les phrases complètes.

**Comment by Oliv4945** [comment]
Salut,

Je ferme en attendant une réponse
