### ISSUE TITLE
Google Home arrive sur le marché du PI....

### ISSUE THREAD

**Issue by Jean-Bernard-Hallez** [alexylem/jarvis#765]
https://www.androidpit.fr/comment-fabriquer-votre-propre-google-home

Bonjour... peux-ton intégrer à Jarvis uniquement la reconnaissance Google Home car il intégre beaucoup de fonctions qui peuvent court-circuiter les plugins construit autour de Jarvis...

On gagnerai aussi  en rapidité de réponse.... et il y aurai plus de fonctions...

**Comment by Sh1n1x** [comment]
Oui c'est pas très compliqué, il faut juste accéder au SDK et faire les requêtes là bas, mais si c'est pour envoyer toutes nos données à Google, autant acheter un Google Home ^^.

**Comment by Oliv4945** [comment]
Salut,

La dernière fois que j'ai testé (cet été), les commandes disponibles via l'API sur rPi étaient très restreintes (du type donne moi l'heure ou la météo), et en Anglais uniquement.
Est-ce que ça a évolué ?

Mais dans ce cas inutile d'intégrer à Jarvis, autant l'utiliser tel quel

**Comment by Sh1n1x** [comment]
Finalement j'ai jeté un petit coup d’œil c'est plus compliqué que ça en à l'air ^^.

Ce qui serait par contre intéressant, ce serait de développer un plugin qui se lancerai juste avant le "je ne comprends pas : mon ordre" afin d'avoir quand même une réponse. Ce qui est dommage de ce que j'ai vu c'est qu'on ne peut pas simplement call l'api en url du coup pas de retour json.
