### ISSUE TITLE
Comment faire après le 1er mois d'essai gratuit de reconnaissance vocale de Bing

### ISSUE THREAD

**Issue by bildu60** [alexylem/jarvis#766]
Bonjour à tous,

Comment faire après le 1 mois d'essai gratuit de reconnaissance vocal de Bing ?

Si quelqu'un a une procédure à suivre ou astuce,je suis preneur.Je crois comprendre que l'on doit laisser son numéro de carte bancaire et que l 'on a un certain nombre de requête gratuite.Mais pour le numéro de carte bancaire ,je ne suis pas chaud. Dommage je commençais à m'habituer à JARVIS et il me manque.

Au plaisir de vous lire.

**Comment by bildu60** [comment]
Bonjour à tous
Comment faire après le 1 mois d'essai gratuit de reconnaissance vocal de bing?Si quelqu'un a une procédure à suivre ou astuce,je suis preneur.Je crois comprendre que l'on doit laisser son numéro de carte bancaire et que l 'on a un certain nombre de requette gratuite.Mais pour le numéro de carte bancaire ,je ne suis pas chaud. Dommage je commençais à m'habituer à JARVIS et il me manque.
Au plaisir de vous lire

**Comment by Sh1n1x** [comment]
Salut,
c'est comme pour Google, il faut mettre ta carte de crédit (j'ai une mastercard mais de débit et pas accepté), c'est du grand n'importe quoi franchement.

La soluce que j'ai trouvé c'est d'utiliser Wit mais je sais pas pour combien de temps c'est gratos

**Comment by bildu60** [comment]
salut
j ai essayé une bonne partie de la journée de faire avec snowboy.Solution qui parait pas mal.
Avantage;
1) c'est du hors ligne
2) c'est gratuit
Inconvénient:
1) il faut créer toute ses commandes
2) La reconnaissace n'est pas top
Hé maintenant,que vais je faire ...
Je vais voir pour ta soluce 2
On se tient au courant si on a du neuf ,ok?

**Comment by Oliv4945** [comment]
Le mieux est de rentrer les infos, rien n'est gratuit :-)
Sinon, y'a [yopmail](http://www.yopmail.com/en/) tous les mois
