### ISSUE TITLE
Erreur 501 dans le navigateur

### ISSUE THREAD

**Issue by TheBlick** [alexylem/jarvis#769]
Salut,
J'ai un problème, quand je lance jarvis tout va bien mais quand je veut l'utiliser avec un navigateur il me marque cette erreur :

Error 501 from http://192.168.0.30:8081: error;
Error response
Error code 501.

Message: Unsupported method ('POST').

Error code explanation: 501 = Server does not support this operation. ;Unsupported method ('POST')

**Comment by Oliv4945** [comment]
`jarvis -nv` ?

**Comment by TheBlick** [comment]
c'est bon je suis passer sur Ubuntu et après avoir tous réinstaller tout marche nickel.

**Comment by wikijm** [comment]
Merci pour ton temps @Oliv4945 😃 
Passe d'excellentes fêtes de fin d'année.
