### ISSUE TITLE
système de scénario

### ISSUE THREAD

**Issue by remjou1** [alexylem/jarvis#77]
bonjour, voici une nouvelle idée qui me semble assez important pour un programme comme jarvis : un système de scénario... j'ai remarqué que ce genre de système était inclut dans pas mal de box domotique ou autre application du genre Jarvis (ex : [Gladys project](http://gladysproject.com/fr/) )... Je pense que ce serait une bonne idée de l'incruster a Jarvis afin d'augmenter ses possibilités en terme de domotique...

**Comment by stackgil** [comment]
moi j'ai trouvé cela
http://www.pihomeserver.fr/2013/08/22/raspberry-pi-home-server-gerer-vos-taches-avec-tracks/

**Comment by alexylem** [comment]
Je suis pas sûr que ca soit en rapport direct avec Jarvis.
Jarvis n'a pas vocation à devenir une plateforme de domotique, c'est simplement une interface vocale (voir plus tard visuelle #56 ) entre vous et votre système de domotique existant.
Si vous voulez effectuer une liste de tâches, vous pouvez déjà très bien le faire, soit en les listant, soit en passant par un script/programme externe.

Exemple:
```
BONNE*NUIT==./my_domo salon off && ./my_domo chambre off
```
ou
```
BONNE*NUIT==./my_domo all_lights off
```

**Comment by remjou1** [comment]
merci @stackgil
