### ISSUE TITLE
Lancer/Utiliser Jarvis (apres installation)

### ISSUE THREAD

**Issue by Ekologiaproject** [alexylem/jarvis#770]
**### Description**
J'ai effectué l'installation, RAS 
Puis tentative d'installation du plug in Gmail
Et après, impossible de démarrer Jarvis (Enfin je crois)

Quand je tape $> jarvis -h 
J'ai:
-bash: $: command not found
 
ou
$> jarvis -n
Rien ne se passe

J'ai cherché pour éventuellement réinstallé, mais pas trouver d'infos...

D'avance merci, et si pas de réponse avant les fêtes, et bien bonnes fêtes :p

Kris,

**Comment by Sh1n1x** [comment]
salut @Ekologiaproject 

As-tu essayé de te mettre dans le répértoire de Jarvis (cd jarvis) et de faire sh jarvis.sh ?

**Comment by Oliv4945** [comment]
Salut,

Je ferme en attendant une réponse

**Comment by Ekologiaproject** [comment]
Hello merci pour le retour et navré de la réponse tardive.
@Sh1n1x oui je rentre dans dossier mais idem rien ne me permet de démarrer Jarvis

Pou info je suis sur Mac
