### ISSUE TITLE
utiliser voix tts local sous linux/wine avec jarvis

### ISSUE THREAD

**Issue by alansan2017** [alexylem/jarvis#771]
Bonjour à tous,

j'utilise jarvis sous ubuntu 16.04.
sous ubuntu, j'utilise balabolka sous wine comme application tts , avec la voix microsoft speech platform Hortense. le programme balabolka, une fois lancé, capture et lit (voix Hortense) tout ce qui transite par le presse-papier....

dans jarvis paramètre voix tts, il y a plusieurs choix dont svoxpico que j'ai installé en local sous ubuntu.

j'aimerai que quand jarvis dit une réponse, que ce qu'il doit dire soit envoyé dans le presse-papier pour être 'lu" alors par balabolka, au lieu d'envoyer la réponse au moteur tts utilisé par jarvis lui-même .

une idée de quoi modifier dans des fichiers?

merci

**Comment by Oliv4945** [comment]
Salut,

Il faut ajouter un nouveau moteur TTS dans le dossier `tts_engines`, tu peux te baser sur un existant pour l'adapter.
Ensuite ajouter le nom du dossier aux options de `tts_engine` dans [configure.sh](https://github.com/alexylem/jarvis/blob/master/utils/configure.sh#L213)

**Comment by alansan2017** [comment]
Oliv4945,

ce n'est pas ce que je demande! ma requête est claire : "j'aimerai que quand jarvis dit une réponse, que ce qu'il doit dire soit envoyé dans le presse-papier pour être 'lu" alors par balabolka (qui surveille ce presse-papier depuis wine), au lieu d'envoyer la réponse au moteur tts utilisé par jarvis lui-même .

une idée de quoi modifier dans des fichiers?

**Comment by Oliv4945** [comment]
Ma réponse est claire aussi: il faut créer un nouveau TTS dans Jarvis qui copiera le résultat de la réponse dans le presse papier au lieu de créer un son.

Une autre méthode est avec un plugin qui fait un hook sur l'évènement `start_speaking` et envoie la commande dans le presse papier, la documentation est sur le site pour les [hooks](https://openjarvis.com/content/hooks) comme la [création de plugin](https://openjarvis.com/content/publish-your-plugin). Je n'ai pas proposé cette solution au premier tour car on se retrouve avec deux TTS...

Si la question porte sur comment mettre du texte dans un presse papier, voir [ici](https://www.google.fr/search?q=linux+bash+copy+to+clipboard&ie=utf-8&oe=utf-8&client=firefox-b&gfe_rd=cr&dcr=0&ei=oaxLWsLZHdXAaPvlvOAE).
