### ISSUE TITLE
Application Json Parsing error

### ISSUE THREAD

**Issue by Koploseus** [alexylem/jarvis#772]
### Description
Bonjour! 

J'ai installé Jarvis il y a une semaine , j'ai commancer à developper quelques plugins dessus, j'ai voulu utiliser l'application mobile , mais quand je parle j'ai l'erreur : 

Json Parsing error

Le soucis vient pas d'une mauvaise manip IP ou autre, car dans les logs je vois la connexion de mon téléphone.

![jarvis](https://user-images.githubusercontent.com/25018500/34343884-362448a6-e9de-11e7-88db-fc6c46dca226.png)

Une idée d'où cela peut venir ? :/

**Comment by fredericsuretat** [comment]
j'ai exactement la m$eme erreur ... aucune idée d'ou celà vient je cherche aussi :-(

**Comment by Oliv4945** [comment]
Bonjour,

Est-ce possible d'avoir un log complet de Jarvis, lancé avec `jarvis -nv` ?

**Comment by fredericsuretat** [comment]
voici : 
`pi@raspberrypi:~ $ jarvis -nv

------------ Config ------------
jv_branch            master
jv_version
jv_arch              armv7l
jv_os_name           raspbian
jv_os_version        9
language             fr_FR
play_hw
rec_hw
speaker              Default
microphone           Default
recorder             sox
trigger_stt          snowboy
command_stt          bing
tts_engine           svox_pico
--------------------------------

No mic configured, forcing keyboard mode
No speaker configured, forcing mute mode
DEBUG: program_startup hook
Starting RestAPI server on http://192.168.0.163:8081
Starting Facebook messenger-Jarvis server with user 'jarvis@suretat.com'
Starting User Interface on http://192.168.0.163:8080
DEBUG: start_speaking hook
Jarvis: Bonjour.
DEBUG: stop_speaking hook
User defined commands:
*AIDE*                  *BONJOUR*|*SALUT*|*HELL JE*SUIS (*)
*COMMENT*JE*APPELLE*    *COMMENT*TU*APPELLE*    *QUEL*ES*TON*NOM*
*MERCI*                 *AU REVOIR*|*BYE*       ANNULE*|TERMINE*
ENCORE*                 *TEST*                  *VERSION*
*REPETE (*) ET (*)      *CA VA*                 >*OUI*
>*NON*|*PAS*            *DOMOTIQUE*             *FREEBOX*
*ETEINT TOUT*           *ALLUME*LUMIERE*TV*     *ETEINT*LUMIERE*TV*
*ALLUME*SALON*          *ETEINT*SALON*          *ALLUME*SALLE*A*MANGER*
*ETEINT*SALLE*A*MANGER* ALLUME*|ETEINT*         *TEMPERATURE*
>*DEHORS*               >*CHAMBRE*              >*FRIGO*
>*SALON*                >*NILA*                 *NUIT*
*ENTRE*MAISON*          *SORS*MAISON*           *PARS*VACANCES*
*BON*JOUR*
Commands from plugin jarvis-fb-messenger:
*ENVOI*MESSAGE*FACEBOOK
Commands from plugin jarvis-ui:
*OUVR*INTERFACE*
Commands from plugin jarvis-api:

fred: DEBUG:root:Initializing Facebook messenger server with email 'jarvis@suretat.com', getId='False', verbose='True',  mute='True', allowAll='False' and allowedList='['1545349664', '1354384016', 'id_3_here', '...']'.
Logging in jarvis@suretat.com...
INFO:client:Logging in jarvis@suretat.com...
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): m.facebook.com
DEBUG:urllib3.connectionpool:https://m.facebook.com:443 "GET /?__req=1&seq=0 HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:https://m.facebook.com:443 "POST /login.php?login_attempt=1 HTTP/1.1" 302 0
DEBUG:urllib3.connectionpool:https://m.facebook.com:443 "GET /home.php?refsrc=https%3A%2F%2Fwww.facebook.com%2F&_rdr HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): www.facebook.com
DEBUG:urllib3.connectionpool:https://www.facebook.com:443 "GET /?__req=3&seq=0 HTTP/1.1" 200 None
Login of jarvis@suretat.com successful.
INFO:client:Login of jarvis@suretat.com successful.
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): 0-edge-chat.facebook.com
DEBUG:urllib3.connectionpool:https://0-edge-chat.facebook.com:443 "GET /pull?clientid=49f82490&__a=1&__user=100023716500330&ttstamp=6581718852536752101696911858658169791105086855412176882&__req=4&__rev=3551904&fb_dtsg=AQGX45C4eEEv%3AAQEOn2VU6yLX&msgs_recv=0&channel=p_100023716500330&seq=0 HTTP/1.1" 200 96
Listening...
INFO:client:Listening...
DEBUG:urllib3.connectionpool:https://0-edge-chat.facebook.com:443 "GET /active_ping?sticky_pool=ash4c09_chat-proxy&clientid=49f82490&__a=1&cap=0&partition=-2&viewer_uid=100023716500330&__user=100023716500330&ttstamp=6581718852536752101696911858658169791105086855412176882&__req=5&__rev=3551904&fb_dtsg=AQGX45C4eEEv%3AAQEOn2VU6yLX&channel=p_100023716500330&sticky_token=905&state=active&seq=0&uid=100023716500330 HTTP/1.1" 200 48
DEBUG:urllib3.connectionpool:https://0-edge-chat.facebook.com:443 "GET /pull?sticky_pool=ash4c09_chat-proxy&clientid=49f82490&__a=1&__user=100023716500330&ttstamp=6581718852536752101696911858658169791105086855412176882&__req=6&__rev=3551904&fb_dtsg=AQGX45C4eEEv%3AAQEOn2VU6yLX&sticky_token=905&msgs_recv=0&seq=0 HTTP/1.1" 200 124
DEBUG:urllib3.connectionpool:https://0-edge-chat.facebook.com:443 "GET /active_ping?sticky_pool=ash4c09_chat-proxy&clientid=49f82490&__a=1&cap=0&partition=-2&viewer_uid=100023716500330&__user=100023716500330&ttstamp=6581718852536752101696911858658169791105086855412176882&__req=7&__rev=3551904&fb_dtsg=AQGX45C4eEEv%3AAQEOn2VU6yLX&channel=p_100023716500330&sticky_token=905&state=active&seq=1&uid=100023716500330 HTTP/1.1" 200 48
DEBUG:urllib3.connectionpool:https://0-edge-chat.facebook.com:443 "GET /pull?sticky_pool=ash4c09_chat-proxy&clientid=49f82490&__a=1&__user=100023716500330&ttstamp=6581718852536752101696911858658169791105086855412176882&__req=8&__rev=3551904&fb_dtsg=AQGX45C4eEEv%3AAQEOn2VU6yLX&sticky_token=905&msgs_recv=0&seq=1 HTTP/1.1" 200 190
DEBUG:client:Chat Timestamps received: {'1354384016': 1514899246, '1545349664': 1514898375}
DEBUG:urllib3.connectionpool:https://0-edge-chat.facebook.com:443 "GET /active_ping?sticky_pool=ash4c09_chat-proxy&clientid=49f82490&__a=1&cap=0&partition=-2&viewer_uid=100023716500330&__user=100023716500330&ttstamp=6581718852536752101696911858658169791105086855412176882&__req=9&__rev=3551904&fb_dtsg=AQGX45C4eEEv%3AAQEOn2VU6yLX&channel=p_100023716500330&sticky_token=905&state=active&seq=2&uid=100023716500330 HTTP/1.1" 200 48
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (2): 0-edge-chat.facebook.com
DEBUG:urllib3.connectionpool:https://0-edge-chat.facebook.com:443 "GET /active_ping?sticky_pool=ash4c09_chat-proxy&clientid=49f82490&__a=1&cap=0&partition=-2&viewer_uid=100023716500330&__user=100023716500330&ttstamp=6581718852536752101696911858658169791105086855412176882&__req=b&__rev=3551904&fb_dtsg=AQGX45C4eEEv%3AAQEOn2VU6yLX&channel=p_100023716500330&sticky_token=905&state=active&seq=2&uid=100023716500330 HTTP/1.1" 200 48
192.168.0.133 - - [02/Jan/2018 14:21:39] "GET /?action=get_config&key=fred HTTP/1.1" 200 -
192.168.0.133 - - [02/Jan/2018 14:21:48] "POST / HTTP/1.1" 200 -
192.168.0.133 - - [02/Jan/2018 14:21:48] "GET /?action=get_config&key=fred HTTP/1.1" 200 -
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (3): 0-edge-chat.facebook.com
DEBUG:urllib3.connectionpool:https://0-edge-chat.facebook.com:443 "GET /active_ping?sticky_pool=ash4c09_chat-proxy&clientid=49f82490&__a=1&cap=0&partition=-2&viewer_uid=100023716500330&__user=100023716500330&ttstamp=6581718852536752101696911858658169791105086855412176882&__req=d&__rev=3551904&fb_dtsg=AQGX45C4eEEv%3AAQEOn2VU6yLX&channel=p_100023716500330&sticky_token=905&state=active&seq=2&uid=100023716500330 HTTP/1.1" 200 48
192.168.0.133 - - [02/Jan/2018 14:22:11] "POST / HTTP/1.1" 200 -
192.168.0.133 - - [02/Jan/2018 14:22:11] "GET /?action=get_config&key=fred HTTP/1.1" 200 -
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (4): 0-edge-chat.facebook.com
DEBUG:urllib3.connectionpool:https://0-edge-chat.facebook.com:443 "GET /active_ping?sticky_pool=ash4c09_chat-proxy&clientid=49f82490&__a=1&cap=0&partition=-2&viewer_uid=100023716500330&__user=100023716500330&ttstamp=6581718852536752101696911858658169791105086855412176882&__req=f&__rev=3551904&fb_dtsg=AQGX45C4eEEv%3AAQEOn2VU6yLX&channel=p_100023716500330&sticky_token=905&state=active&seq=2&uid=100023716500330 HTTP/1.1" 200 48
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (5): 0-edge-chat.facebook.com
DEBUG:urllib3.connectionpool:https://0-edge-chat.facebook.com:443 "GET /active_ping?sticky_pool=ash4c09_chat-proxy&clientid=49f82490&__a=1&cap=0&partition=-2&viewer_uid=100023716500330&__user=100023716500330&ttstamp=6581718852536752101696911858658169791105086855412176882&__req=h&__rev=3551904&fb_dtsg=AQGX45C4eEEv%3AAQEOn2VU6yLX&channel=p_100023716500330&sticky_token=905&state=active&seq=2&uid=100023716500330 HTTP/1.1" 200 48`

**Comment by Oliv4945** [comment]
Ok merci. Est-ce que Jarvis-api fonctionne ?

**Comment by Oliv4945** [comment]
Ok j'ai une idée.
@Koploseus, est-ce que tu utilises Jarvis sans micro ou enceinte ?

@fredericsuretat: Que donne le retour de `http://192.168.0.133:8081/?key=fred&order=test` ?
Je suppose que tu as le JSON suivant ? (Par ailleurs je comprends mieux ta question en #774)
```
[{"warning": "No mic configured, forcing keyboard mode"}, {"warning": "No speaker configured, forcing mute mode"}, {"answer": "Ca fonctionne!"}]
```

**Comment by fredericsuretat** [comment]
j'utilise jarvis sans micro ni enceintes . la commande donne bien.
[{"warning": "No mic configured, forcing keyboard mode"}, {"warning": "No speaker configured, forcing mute mode"}, {"answer": "Ca fonctionne!"}]

**Comment by Koploseus** [comment]
Merci de votre réponse,

J'utilise jarvis avec enceinte uniquement pour le moment (et encore le plus souvent c'est via le pc)

J'ai exactement comme fredericsuretat

**Comment by Oliv4945** [comment]
Voilà, version [v0.2.4](https://github.com/Oliv4945/jarvis-android-app/releases/tag/v0.2.4) publiée sur le store. Pouvez-vous mettre à jour et me dire ?

**Comment by fredericsuretat** [comment]
problème resolu pour moi. quel etait le soucis par curiosité ?

**Comment by Koploseus** [comment]
Probleme résolu également de mon coté :)

**Comment by Oliv4945** [comment]
Super ! Pour info il vaut mieux ouvrir une issue sur le [repo de l'application](https://github.com/Oliv4945/jarvis-android-app) :)

@fredericsuretat : tout con, je ne prenais pas en compte toute la réponse, mais que le premier élément du JSON qui s'avère être un warning dans votre cas.
