### ISSUE TITLE
warning s'affichent

### ISSUE THREAD

**Issue by fredericsuretat** [alexylem/jarvis#774]
### Description
Bonjour,
J'utilise jarvis depuis peu et je dois dire que c'est juste une turie.
J'ai juste un "petit" soucis mais qui s'avère énervant au quotidien.
Systématiquement quelque soit le mode de conversation j'ai les warnings qui s'affichent.
exemple si je lui demande d'éteindre une lampe j'ai la réponse suivante : 
No mic configured, forcing keyboard mode
No speaker configured, forcing mute mode
c'est fait

Or, oui, je sais je n'ai volontairement pas configuré de micro ni de haut parleur car je le veut qu'en conversation texte pour le moment (via la plugin messenger).

Mais il me l'affiche systématiquement dans chaque réponse. Serait-il possible de ne pas l'afficher ? Ou que lors de la première réponse de la conversation?

Cordialement.

**Comment by Oliv4945** [comment]
Salut,

Essaie de démarrer avec l'option "-k" 

Oliv'
-- 
Envoyé de mon appareil Android avec K-9 Mail. Veuillez excuser ma brièveté.

**Comment by fredericsuretat** [comment]
j'ai toujours les messages malgré le démarrage avec l'option K, n'y a t'il pas un fichier de conf ou on pourrait dire à jarvis de ne pas faire remonter ces erreurs ?

**Comment by Oliv4945** [comment]
salut,

Quelle commande utilises-tu pour lancer Jarvis ?

**Comment by fredericsuretat** [comment]
en temps normal je mets juste >jarvis
j'ai essayé avec différentes options (k) entre autre.
mais toujours le même soucis

**Comment by Oliv4945** [comment]
Salut,

J'ai un doute, mes messages suivants sont-il une fois au démarrage ou à chaque fois que tu entres une commande ?

```
No mic configured, forcing keyboard mode
No speaker configured, forcing mute mode
```

**Comment by fredericsuretat** [comment]
a chaque fois que j'entre une commande.

**Comment by Oliv4945** [comment]
@fredericsuretat : Du coup je n'arrive pas à reproduire, est-ce que tu peux me faire une capture d'écran de ton soucis ? merci

**Comment by fredericsuretat** [comment]
ce ne sera pas un screenshot mais voici le texte complet :


Jarvis: Bonjour.
fred: hello
warning: No mic configured, forcing keyboard mode
warning: No speaker configured, forcing mute 
modedebug: $> say "Bonjour"
debug: DEBUG: start_speaking hook
Jarvis: Bonjour
debug: DEBUG: stop_speaking hook

**Comment by Oliv4945** [comment]
Salut @fredericsuretat,
Sur ton log on voit effectivement les deux warning au démarrage, mais pas que ça se reproduit par la suite...

**Comment by fredericsuretat** [comment]
Bonjour,

J'ai pu faire un screenshot visible ici :
`https://drive.google.com/file/d/1zLT8gxPOJmCs3TGbjatzbnTabQplU1Xn3A/view?usp=sharing`

**Comment by Oliv4945** [comment]
Ok, du coup le soucis est dans le plugin messenger ;-)
J'ai ouvert une issue [ici](https://github.com/QuentinCG/jarvis-fb-messenger/issues/11) donc il n'y a plus qu'à attendre sa réponse. 
En attendant tu peux faire la modification que je propose

**Comment by QuentinCG** [comment]
@Oliv4945 @fredericsuretat J'ai fais le fix.
Pourriez vous me confirmer que tout fonctionne? (je n'ai pas les outils sous la main pour tester)

**Comment by Oliv4945** [comment]
@QuentinCG : Super !
Moi non plus, je n'utilise pas Facebook messenger

**Comment by fredericsuretat** [comment]
hello c'etait bien ca ca fonctionne. sauf la commande d'aide qui ne s'affiche plus. (jv_display_commands)

**Comment by QuentinCG** [comment]
Arggggg... En effet...

@Oliv4945 Te souviens tu de la clef json associée à la commande d'aide?

**Comment by Oliv4945** [comment]
J'ai répondu sur le repo du plugin, je ferme ici :)
