### ISSUE TITLE
nouvelle face pour jarvis-face : Jessica Alba !!!!!!

### ISSUE THREAD

**Issue by alansan2017** [alexylem/jarvis#775]
salut à tous

j'ai réalisé Jessica Alba !!

dispo via :  [https://github.com/alansan2017/jarvis-face-jessica.git](url)

enjoy !!  ;-)

**Comment by wikijm** [comment]
Bonsoir @alansan2017,

Afin de prendre en compte ta participation, merci de faire un PR sur le repository https://github.com/alexylem/jarvis-face/

Cordialement,
@wikijm
