### ISSUE TITLE
plugin lune-soleil réponses "null" concernant les heures !!

### ISSUE THREAD

**Issue by alansan2017** [alexylem/jarvis#778]
bonjour, 

problème simple: réponses "null" de jarvis: 

"alain: heure de lever du soleil 
Isabelle: Le soleil se lèvera à null heure null et il se couchera à null heure null. "

quelqu'un peut m'aider svp?! 
merci 
alansan2017

**Comment by Cqoicebordel** [comment]
Deux choses : les plugins sont fait par des développeurs indépendant de Jarvis. Pour signaler un bug, il faut aller sur leurs pages respectives, sinon il ne seront pas au courant. Dans le cas présent, la page est https://github.com/Jean-Bernard-Hallez/jarvis-lunesoleil
Ensuite, ce plugin demande la création d'une clé. Est-ce que ça a été fait ?
Si oui, il se peut que le service web dont est issue l'information (wunderground.com) soit en panne. Sinon, utiliser une clé valide est nécessaire.

**Comment by alansan2017** [comment]
merci pour la précision sur l'auteur des plugins!
oui, j'ai une api-key active pour ce plugin
