### ISSUE TITLE
Problème configuration Microphone

### ISSUE THREAD

**Issue by ze4lk** [alexylem/jarvis#781]
Bonjour,
J'utilise comme micro le H2 de chez ZOOM. Je le branche sur mon raspberry pi ( en usb bien sûr), je vais dans audio, et il est reconnu sur le raspberry pi comme ça
![2018-01-07-142511_1600x1200_scrot](https://user-images.githubusercontent.com/35194535/34650314-99b2f85a-f3bf-11e7-8c0c-46504415ba72.png)
J'aimerai donc l'utiliser comme micro dans JARVIS
Merci de votre réponse

**Comment by ze4lk** [comment]
Ah! et la configuration Micro de Jarvis Plante aussi

**Comment by Oliv4945** [comment]
>### Logs
```shell
<PASTE HERE> full content of the terminal with Jarvis in troubleshooting mode
(keep triple quotes above and below to preserve formatting) 
```
Alternatively attach a terminal session recording using asciinema:
```shell
sudo apt-get install -y asciinema && asciinema rec # start session recording
./jarvish.sh -nv # start jarvis directly in troubleshooting mode
Ctrl+D # stop recording
y # yes to upload and get URL to paste here
```

**Comment by ze4lk** [comment]
Non en fait c'est résolu merci quand même!
