### ISSUE TITLE
Problème reconnaissance des commandes.

### ISSUE THREAD

**Issue by ze4lk** [alexylem/jarvis#783]
Bonjour,
J'ai installé Jarvis, mon micro, tout fonctionne nickel. Le seul problème, c'est que Jarvis ne reconnais pas quand je dis des commandes, ça me marque des "#" à la place de ce que je dis. J'ai essayé avec Bing Speech API et WIT. Cependant, ça ne fonctionne toujours pas. Je ne sais pas si il faut que je le fasse en local.
J'ai hâte de recevoir vos réponse
Merci
ze4lk

**Comment by ze4lk** [comment]
Voici ce qui est marqué dans mon terminal:

> ------------ Config ------------
jv_branch            master 
jv_version            
jv_arch              armv7l 
jv_os_name           raspbian 
jv_os_version        9 
language             fr_FR 
play_hw              false 
rec_hw               false 
speaker              Default 
microphone           Default 
recorder             sox 
trigger_stt          snowboy 
command_stt          bing 
tts_engine           svox_pico 
--------------------------------

DEBUG: program_startup hook
DEBUG: start_speaking hook
jarvis: Hello
DEBUG: stop_speaking hook
User defined commands:
*AIDE*			*BONJOUR*|*SALUT*	*COMMENT*APPELLE*
*MERCI*			*AU REVOIR*|*BYE*	ANNULE*|TERMINE*
ENCORE*			*TEST*			*VERSION*
*REPETE (*) ET (*)	*CA VA*			>*OUI*
>*NON*|*PAS*
jarvis: Waiting to hear 'jarvis'
Gaspard: (listening...)
DEBUG: models=jarvis
INFO:snowboy:Ticks: [2, 20, 5, -1]
INFO:snowboy:Keyword 1 detected at time: 2018-01-08 19:40:52
INFO:snowboy:Ticks status: 2 1 1 1
DEBUG: modelid=0
jarvis
DEBUG: entering_cmd hook
Gaspard: (listening...)
DEBUG: start_speaking hook ""
utils/timeout.sh 10 rec -V1 -q -r 16000 -c 1 -b 16 -e signed-integer --endian little /dev/shm/jarvis-record.wav gain 30 silence 1 0.1 6.1% 1 0.5 6.1% pad 0.5 0.5 trim 0 5
<

**Comment by Oliv4945** [comment]
Salut,
Est-ce possible de refaire le log en allant jusqu'au problème de '#' ?
Si tu lances avec `jarvis -nv`, est-ce que tu t'entends correctement en echo ?

**Comment by wikijm** [comment]
Clôture du ticket jusqu'à obtention d'une réponse de la part de l'auteur de l'issue.
Closing of the ticket until a valid answer from the applicant is obtained.
