### ISSUE TITLE
Relai Jarvis avec une arduino uno

### ISSUE THREAD

**Issue by ze4lk** [alexylem/jarvis#785]
Bonjour,
J'aimerai savoir s'il était possible d'utiliser une arduino uno comme relai Jarvis pour une autre pièce ou carrément comme un autre Jarvis esclave de mon Jarvis maître. Si c'est possible, pourriez-vous me donner la liste des éléments nécéssaires et des scripts à mettre sur son Arduino?
Merci de votre réponse
ze4lk

**Comment by Oliv4945** [comment]
Relais Jarvis: https://openjarvis.com/plugins/multi-jarvis-server-esclaves
Pour l'Arduino non il n'a pas les capacités à moins de rajouter des puces autour, mais ça sera sûrement bientôt possible avec un ESP32, Espressif a annoncé travailler sur la détection de hotword, ensuite il peut faire le streaming de l'audio sans aucun soucis

**Comment by ze4lk** [comment]
Ok merci! Et sinon je pourrai utiliser un pi zero comme relai je suppose non?

**Comment by Sh1n1x** [comment]
Yes

**Comment by ze4lk** [comment]
ok cool!

**Comment by Oliv4945** [comment]
Salut,

Espressif va faire une carte très intéressant pour ça !! [voir ici](https://twitter.com/EspressifSystem/status/952152302781046785?s=09).
Le microcontroleur sait faire de la reconnaissance de hotword et streamer l'audio, en plus ils font un mic array !!!!
