### ISSUE TITLE
[Suggestion] Différencier la réponse api de la réponse jarvis

### ISSUE THREAD

**Issue by Sh1n1x** [alexylem/jarvis#786]
Hello,

Voilà vu que j'ai récemment développé une app android pour jarvis je me prends à rêver de nouvelles fonctionnalités ^^, je vous explique celle que je pense aujourd'hui.

Différencier la réponse jarvis avec la réponse vers l'api. Je m'explique un peux mieux, par exemple prenons le plugin météo. Il serait intéressant d'ajouter un retour du style : 
`[{"answer": "Voici les conditions météo actuelle : Pluie faible. Température 5 degré.", "extra": {"temp":"5","decription":"Pluie faible"}}]`

Ainsi on pourrait le traiter différemment en utilisant l'api pour afficher une jolie carte avec image.

**Comment by alexylem** [comment]
Discutons-en ici: #791
