### ISSUE TITLE
Problème plugin Jarvis-Alarm

### ISSUE THREAD

**Issue by ze4lk** [alexylem/jarvis#788]
Salut!
Je viens de réinstaller Jarvis et j'ai donc installé mes plugins habituels (Time, Jarvis_Alarm et jarvis-nui-hp-moins-fort). Seulement, quand je lance une alarme ça me met ça:

> jarvis: L'alarme est programmé pour le samedi 13 janvier 2018, 07:08:00 (UTC+0100).
jarvis: Veuillez attendre la fin de l'alarme pour donner d'autre instructions.
sleep : option invalide -- '1'
Saisissez « sleep --help » pour plus d'informations.
play FAIL formats: can't open input file `wake_up/wake_up.mp3': No such file or directory
jarvis: Il es 7 heures 8

Voilà, c'est un peu problématique.
Quelqu'un a-t-il une réponse?
ze4lk

**Comment by wikijm** [comment]
Bonsoir @ze4lk 

Ton problème semble être interne au plugin Jarvis-Alarm. Je t’invite donc à créer une issue sur [son repo](https://github.com/Pineapple-Geek/jarvis-alarm/issues).

Cordialement,
@wikijm
