### ISSUE TITLE
ImportError: /home/raspberry/jarvis/stt_engines/snowboy/_snowboydetect.so: wrong ELF class: ELFCLASS32

### ISSUE THREAD

**Issue by BelghitiAlaoui-Hicham** [alexylem/jarvis#79]
### Description

J'ai remarqué , lors du lancement de jarvis, le programme détecte snowboy même si je parle pas et aprés un certain temps il entre dans le mode timeout pendant 1 seconde aprés il lance snowboy .Du coup le mot magique ne marche pas :'(
### Résultat

```
raspberry@arduino:~/jarvis$ ./jarvis.sh 
Checking for updates...[Up-to-date]

------------ Config ------------
platform              linux 
language              fr_FR 
play_hw               false 
rec_hw                false 
trigger_stt           snowboy 
command_stt           bing 
tts_engine            svox_pico 
conversation_mode     true 
--------------------------------

DEBUG: program_startup hook
maison: Que puis-je faire pour vous?
maison: Waiting to hear 'maison'
hicham: (listening...)
DEBUG: models=snowboy
Traceback (most recent call last):
  File "stt_engines/snowboy/main.py", line 1, in <module>
    import snowboydecoder
  File "/home/raspberry/jarvis/stt_engines/snowboy/snowboydecoder.py", line 5, in <module>
    import snowboydetect
  File "/home/raspberry/jarvis/stt_engines/snowboy/snowboydetect.py", line 28, in <module>
    _snowboydetect = swig_import_helper()
  File "/home/raspberry/jarvis/stt_engines/snowboy/snowboydetect.py", line 24, in swig_import_helper
    _mod = imp.load_module('_snowboydetect', fp, pathname, description)
ImportError: /home/raspberry/jarvis/stt_engines/snowboy/_snowboydetect.so: wrong ELF class: ELFCLASS32
DEBUG: modelid=0
snowboy
maison: J'ai pas compris: snowboy
hicham: (listening...)
./timeout.sh 10 rec -V1 -q -r 16000 -c 1 -b 16 -e signed-integer --endian little jarvis-record.wav silence 1 0.1 1% 1 0.5 1% trim 0 10
DEBUG: speech duration was  (10 = 1 sec)
DEBUG: timeout, end of conversation

maison: Waiting to hear 'maison'
hicham: (listening...)
DEBUG: models=snowboy
Traceback (most recent call last):
  File "stt_engines/snowboy/main.py", line 1, in <module>
    import snowboydecoder
  File "/home/raspberry/jarvis/stt_engines/snowboy/snowboydecoder.py", line 5, in <module>
    import snowboydetect
  File "/home/raspberry/jarvis/stt_engines/snowboy/snowboydetect.py", line 28, in <module>
    _snowboydetect = swig_import_helper()
  File "/home/raspberry/jarvis/stt_engines/snowboy/snowboydetect.py", line 24, in swig_import_helper
    _mod = imp.load_module('_snowboydetect', fp, pathname, description)
ImportError: /home/raspberry/jarvis/stt_engines/snowboy/_snowboydetect.so: wrong ELF class: ELFCLASS32
DEBUG: modelid=0
snowboy
maison: J'ai pas compris: snowboy
hicham: (listening...)
./timeout.sh 10 rec -V1 -q -r 16000 -c 1 -b 16 -e signed-integer --endian little jarvis-record.wav silence 1 0.1 1% 1 0.5 1% trim 0 10
DEBUG: speech duration was 05 (10 = 1 sec)
DEBUG: curl https://speech.platform.bing.com/recognize/query?version=3.0&requestid=5df3d63f-0e5b-4744-87fe-350f4141963a&appid=D4D52672-91D7-4C74-8AD8-42B1D98141A5&format=json&locale=fr-FR&device.os=linux&scenarios=ulm&instanceid=E043E4FE-51EF-4B74-8133-B728C4FEA8AA
DEBUG: json={"version":"3.0","header":{"status":"success","scenario":"ulm","name":"au revoir","lexical":"au revoir","properties":{"requestid":"0cccdb6b-8be0-4ee4-a8e2-6eeaacb396b8","HIGHCONF":"1"}},"results":[{"scenario":"ulm","name":"au revoir","lexical":"au revoir","confidence":"0.8282486","properties":{"HIGHCONF":"1"}}]}
au revoir
$> say "Au revoir $username"; exit
maison: Au revoir hicham
![1](https://cloud.githubusercontent.com/assets/14890239/17274407/e0f856fc-56df-11e6-9b3c-a3ace2ba11d3.png)
![capture du 2016-07-31 05 24 40](https://cloud.githubusercontent.com/assets/14890239/17274410/e85168d0-56df-11e6-94d5-2d84128f1321.png)


```

**Comment by alexylem** [comment]
@BelghitiAlaoui-Hicham  Tu as 2 problèmes:
- Comme #78 tu utilises "maison" comme trigger mais n'a pas enregistré de modèle "maison.pmdl" pour snowboy. Regarde la solution sur #78 .
- Tu as une erreur lors du chargement de `_snowboydetect.so`. Ce fichier est pré-compilé pour fonctionner sur raspberry pi. Utilises-tu bien un raspberry pi? Quelle version de l'OS?

**Comment by Smanar** [comment]
ELF class: ELFCLASS32 correspond a une librairie 32bit.

**Comment by BelghitiAlaoui-Hicham** [comment]
Pour le 1er problème , j'ai bien mis le fichier maison.pmdl dans le dossier snowboy/ressources

Pour le 2 éme problème , j'utilise ubuntu 14.04 et je pense de là vient le problème.

Merci pour ta réponse

**Comment by alexylem** [comment]
Ok pour le premier problème, avec la mise à jour on devrait y voir plus clair 😄 
Par contre pour le second problème, tu peux toujours regarder [le repository de snowboy](https://github.com/kitt-ai/snowboy#precompiled-binaries-with-python-demo) et compiler toi même la librairie. Bon courage!

**Comment by BelghitiAlaoui-Hicham** [comment]
Merci :)

**Comment by Smanar** [comment]
Dsl, je ne connais rien a linux mais ubuntu 14.04 n'est pas en 64bit ?
Si c'est le cas ce fichier devrait marcher ? https://github.com/Kitt-AI/snowboy/tree/master/lib/ubuntu64

**Comment by alexylem** [comment]
De @Smanar (le post a l'air d'avoir disparu):
Dsl, je ne connais rien a linux mais ubuntu 14.04 n'est pas en 64bit ?
Si c'est le cas ce fichier devrait marcher ?
https://github.com/Kitt-AI/snowboy/tree/master/lib/ubuntu64

**Comment by Smanar** [comment]
Nope, c'est moi qui l'ai efface, j'ai vu apres que c'etait la lib *.so qui n'etait pas bonne, donc comme tu disais il va devoir recompiler, mais normallement le fichier make devrait compiler la bonne lib, la je vois pas pkoi ca deconne.

**Comment by mbl-35** [comment]
Pour ceux que cela intéresserait, voici la re-compilation du wrapper python (_snowboydetect.so) pour un environnement autre que ceux disponibles en standard. Pour ma part, ubuntu-mate 16.04 LTS server sur un PI-v2 (arm/32 bits), après installation automatique de snowboy par les scripts de @alexylem :

```
# cd /tmp
# sudo apt-get install swig make \
          libexpat1-dev libpython2.7 libpython2.7-dev libpython-dev python2.7-dev python-dev \
          libstdc++-5-dev g++-5 g++
# git clone https://github.com/Kitt-AI/snowboy
# cd snowboy/swig/Python
# make
```

On obtient alors la librairie tant attendue. L'intégrer dans jarvis:
```
# mv /tmp/snowboy/swig/Python/_snowboydetect.so ~jarvis/stt_engines/snowboy/
```

Faire le ménage : 
```
# sudo apt-get --purge remove swig make \
          libexpat1-dev libpython2.7 libpython2.7-dev libpython-dev python2.7-dev python-dev \
          libstdc++-5-dev g++-5 g++
```

**Comment by alexylem** [comment]
@mbl-35 Génial merci pour cette initiative. Je me demandais justement si ca ne serait pas judicieux d'exécuter ton script de compilation automatiquement si une librairie pré-compilée n'est pas disponible 😄  Je suis sûr que ca en intéresserait plus d'un!

**Comment by mbl-35** [comment]
@alexylem Bonne idée. Par contre, pour le moment, les instructions ne sont valables que pour Ubuntu 16 (validées avec version mate). Le script devrait être adapté pour d'autre version de Ubuntu, matériels (CHIP), ...
Il faudrait identifier les cibles...

**Comment by tazou** [comment]
Bonjour,
J'ai eu le même problème, je suis sous Debian 8, et j'ai pu le résoudre en suivant la procédure de recompilation de mbl-35.

Par contre sous Debian, certains packages ont une version différente, notamment la libstdc++ qui est disponible en 4.9 et non en 5.0.

En installant ces dépendances, la compilation fonctionne : 

> sudo apt install swig make libexpat1-dev libpython2.7 libpython2.7-dev libpython-dev python2.7-dev > python-dev   libstdc++-4.9-dev g++
> git clone https://github.com/Kitt-AI/snowboy
> cd snowboy/swig/Python
> make

Info OS : 
> Linux debian 3.16.0-4-amd64 #1 SMP Debian 3.16.36-1+deb8u2 (2016-10-19) x86_64 GNU/Linux

**Comment by wikijm** [comment]
Bonjour @BelghitiAlaoui-Hicham, est-ce que ton problème est toujours d'actualité ?
