### ISSUE TITLE
OSMC et Jarvis

### ISSUE THREAD

**Issue by B4rtux** [alexylem/jarvis#790]
Bonjour, j'aimerais installer Jarvis sûr mon Raspberry, qui a pour OS, OSMC, j'ai 2 cartes micro SD, une pour installer ce fameux jarvis sous Raspbian, comme expliqué sûr le site pour tester, et l'autre avec OSMC en OS de base, j'ai réussi a tout installer, même des dépendances manuellement (alsamixer) , mais au moment de vouloir installer snowboy, ça me marque ceci : 

` osmc@osmc:~/jarvis$ ./jarvis.sh
Notice: you can use 'jarvis' instead of './jarvis.sh'
1/2 Preparation of dependencies
stt_engines/snowboy/main.sh: line 14: [[: 9.3: syntax error: invalid arithmetic operator (error token is ".3")
osmc@osmc:~/jarvis$ `

Merci d'avance pour votre aide 👍 
Cordialement, B4rTux

**Comment by wikijm** [comment]
Bonsoir @B4rtux,

Un sujet similaire est abordé ici : https://github.com/alexylem/jarvis/issues/628
Serait-il possible d'y jeter un œil et de compléter l'issue une fois fait ?
