### ISSUE TITLE
Need help to add a feature on the pluggin Kodi

### ISSUE THREAD

**Issue by kevincaradant** [alexylem/jarvis#793]
(NB) Cette issue ne concernant pas vraiment l'application elle même, je me permets de l'écrire en francais.

-------------------------------------------------------

Hello @alexylem !,

Cela fait un bail que je n'ai pas trainé par ici :)

Comme tu pourras le voir le titre de l'issue n'est pas vraiment le cas mais peu importe.
Je viens pour te demander un tout petit peu d'aide avec le shell et le système de config de Jarvis, je tourne autour du pot depuis bien 2 heures là :/. Je souhaite améliorer pour certains utilisateurs le plugin mais je n'y arrive pas à cause d'une chose toute bête.

J'ai besoin de parser un contenu json et je l'ai defini dans le fichier config.sh:

```
#!/bin/bash
kodi=[{"name":"defaut","kodiUser":"kodi","kodiPassword":"abcd","kodiIp":"192.168.1.11","kodiPort":"7081"},{"name":"room1","kodiUser":"kodi","kodiPassword":"abc","kodiIp":"192.168.1.42","kodiPort":"7080"}]
```

Mais le problème c'est que quand je fais `echo "$kodi"` dans functions.sh je récupère le contenu dans les "" de chaque attribut du coup quand je veux parser avec jq ca explose :/

Exemple du rendu:

```
echo "$kodi"
[{name:defaut,kodiUser:kodi,kodiPassword:abcd,kodiIp:192.168.1.11,kodiPort:7081},{name:room1,kodiUser:kodi,kodiPassword:abc,kodiIp:192.168.1.42,kodiPort:7080}]
```

Je n'y arrive pas avec Jarvis, en dehors de ca c'est bon !

J'espère que tu auras un peu de temps pour m'aider à ce sujet, merci ! :)

**Comment by kevincaradant** [comment]
Hello @wikijm, merci d'avoir ajouté un label à ma question, comprends tu comment cela fonctionne avec Jarvis ? J'ai un peu de temps encore une semaine mais pas plus je devrais mettre en pause le dev ce qui serait domage pour les utilisateurs de Kodi, je ne comprends pas ce que fait Jarvis, pour me virer mes guillemets, ça me rend perplexe.... 

Merci d'avance en tout cas ')

**Comment by wikijm** [comment]
Hello @kevincaradant,

Hélas, mes compétences en développement sont très limitées.

C'est pourquoi ma contribution se limite à traiter les 'tâches administratives' (gestion des tickets) afin de libérer du temps à @alexylem et @Oliv4945 (gros contributeur ces derniers mois, merci à lui) pour le dev.

Je t'invite, afin que l'on comprenne mieux ton problème, à faire une vidéo avec ASCIINEMA en suivant les étapes ci-dessous :
`sudo apt-get install -y asciinema && asciinema rec` # Démarrer l'enregistrement de la session
`./jarvish.sh -nv `# Démarrer jarvis directement en mode troubleshooting
`Ctrl+D` # Arrêter l'enregistrement
`y` # Yes pour télécharger et obtenir l'URL, à coller ici

**Comment by kevincaradant** [comment]
Hello pas de soucis monsieur le secrétaire :D 

Voici suite à ta demande un petit enregistrement. Désolé mais c'est du direct et je me suis un peu perdu au bout d'un moment car je cherchais le dossier plugins ... 

Bref je ne sais pas si cela va pouvoir vous aider mais j'ai fais de mon mieux. N'hesite pas à me dire quoi faire de plus si besoin

https://asciinema.org/a/AtSelLxKITpMPagwTwZVVef1O

**Comment by kevincaradant** [comment]
Besoin de d'autres infos de ma part ? :)

**Comment by kevincaradant** [comment]
@alexylem @wikijm 

Hello je me permets de vous relancer car je n'ai toujours pas corrigé mon problème depuis 3 mois. Cela dans le but de répondre aux besoins des gens qui utilisent mon plugin Kodi. J'ai 2j de dispo cette semaine. Donc si vous avez un peu de temps pour m'aider à comprendre ce problème de parsing car je me suis cassé la tete dessus assez longtemps mais nada :/

Je vous en remercie d'avance ;)

**Comment by Oliv4945** [comment]
Avec un coup d'œil rapide je pense que Bash interprète les double quotes, essaie de mettre un antislash devant ( `"`=>`\"`) dans ton `config.sh`. C'est moche mais ça permet de vérifier dans un premier temps :)
Sinon mettre le json dans un `config.json` et utiliser jq directement dessus devrait pouvoir le faire facilement aussi

**Comment by kevincaradant** [comment]
Hello @Oliv4945, d'après un premier essai en effet, l’échappement dans le sh semble fonctionner :)

Je vais approfondir le truc avant de parler trop vite car cela fait qques mois que je n'ai pas touché le projet. Le coté config.json, j'aurais bien voulu mais je ne pourrais plus utiliser le système de variable de Jarvis si je ne dis pas de betise ? Seul config.sh peut etre utilisé ? Donc seul l’échappement reste une solution viable non ?

**Comment by kevincaradant** [comment]
Finalement je change d'avis, c'est pas encore OK.

En effet, voici le résultat depuis une invite de commande:

```
echo '[{"name":"defaut","kodiUser":"kodi","kodiPassword":"2608","kodiIp":"192.168.1.30","kodiPort":"8080"},{"name":"room1","kodiUser":"kodi","kodiPassword":"2608","kodiIp":"192.168.1.21","kodiPort":"5050"}]' | jq -r '.[].name'

defaut
room1
```

J'ai bien defaut et room1 comme valeur

---------------------------------------------------------------------------------------------------------------------

Maintenant dans jarvis j'ai que defaut comme valeur mais l'affichage du json est ok.
```
[{"name":"defaut","kodiUser":"kodi","kodiPassword":"2608","kodiIp":"192.168.1.30","kodiPort":"8080"},{"name":"room1","kodiUser":"kodi","kodiPassword":"2608","kodiIp":"192.168.1.21","kodiPort":"5050"}]
defaut
```
la commande dans jarvis est:
![image](https://user-images.githubusercontent.com/6093175/39869925-c7e58ff2-545f-11e8-8551-8f5a573e206d.png)

![image](https://user-images.githubusercontent.com/6093175/39869942-d5ec3c54-545f-11e8-9341-7143fb6ae1ce.png)

Il devrait bien me citer les 2 ? ou il y a un truc que j'ai pas compris ?

**Comment by Oliv4945** [comment]
Il faudrait que je test mais si tu remplaces `echo $kodi |...` par `cat $variableVersConfig.json | jq ... ` ?

**Comment by kevincaradant** [comment]
Pas sur d'avoir compris... Que vaut $variableVersConfig.json ? C'est le path du fichier json? Désolé, si je peux avoir un exemple... Merci d'avance :)

**Comment by Oliv4945** [comment]
En arrivant devant mon PC je comprends mieux. `jq` renvoi une liste mais ton code `bash` attend une valeur. `bash` limite donc au premier retour ;)

Il faut mettre des doubles quotes autour du résultat
```
#!/bin/bash
OUTPUT_KO=( $(jq -r '.[].name' kodi.json))
OUTPUT_OK="( $(jq -r '.[].name' kodi.json))"
echo "Ne fonctionne pas: $OUTPUT_KO"
echo "Fonctionne: $OUTPUT_OK"
```
Donne;
```
Ne fonctionne pas: defaut
Fonctionne: ( defaut room1)
```

**Comment by kevincaradant** [comment]
Hey!

Alors merci pour ta réponse qui m'a bien aidé. Après avoir réussi a récupérer ce que je voulais, j'ai la ligne suivante, un peu brutale mais ca fonctionne:
```
kodiIp=($(echo "$kodi" | jq 'map(select(.name == "'$2'") | .kodiIp) | first' | tr -d '"'))
```
J'ai juste pas reussi a charger le fichier "kodi.json" en utilisant ta méthode :(
Ca me dit file not found kodi.json. A vrai dire il est un cran en arrière dans la hiérarchie...et ../ ne semble pas fonctionner :/ donc je ne sais pas trop à ce sujet

**Comment by kevincaradant** [comment]
@Oliv4945 

Merci pour ton aide.
Si jamais tu as une idée de comment appeler kodi.json avec ceci:
https://github.com/kevincaradant/jarvis-kodi

Ca sera avec plaisir que je changerais le code car c'est pas ultra propre ces \ de partout ...
Je clos le ticket pour éviter d'encombrer mais n'hésite pas à répondre :)

**Comment by Oliv4945** [comment]
@kevincaradant : Je crois qu'avec `DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"` tu peux récupérer le dossier courant du script, donc ton fichier JSON
