### ISSUE TITLE
Microphone cravate Bluetooth

### ISSUE THREAD

**Issue by Bobby512** [alexylem/jarvis#794]
Dans notre club d'astro nous avons des mal-entendants. Nous avons l'intention de mettre en place une  solution pour eux. 
- un micro-cravate bluetooth pour le conférencier
- un Raspberry PI3 ou une Tinker Board pour la réception du signal, sa transcription en texte
- affichage de la transcription sur un écran TV
- envoi du son vers un système de baffle amplifié.

C'est le micro-cravate qui est le principal souci. Est-ce que celui-ci remplira les tâches demandées ?
[https://www.amazon.fr/Kaxima-micro-cravate-microphone-Bluetooth/dp/B0795NCJBJ/ref=sr_1_12?ie=UTF8&qid=1516787612&sr=8-12&keywords=micro-cravate+bluetooth](url)

**Comment by wikijm** [comment]
Tout d'abord, bonsoir @Bobby512 (la politesse est de mise).

Il ne me semble pas que quelqu'un ici utilise ce modèle de micro.
Ensuite, quel est le rapport avec OpenJarvis ? J'ai l'impression que vous cherchez exclusivement un système de Speech-to-Text avec retransmission sur écran. Or ce n'est pas ce que fais OpenJarvis.

Cordialement,
@wikijm

**Comment by wikijm** [comment]
Clôture du ticket jusqu'à obtention d'une réponse de la part de l'auteur de l'issue.
Closing of the ticket until a valid answer from the applicant is obtained.
