### ISSUE TITLE
Jarvis ne m'entend pas

### ISSUE THREAD

**Issue by edblv** [alexylem/jarvis#795]
### Description
Bonjour,
J'ai installé jarvis sur un portable Dell sous Ubuntu 16.04.
Tout fonctionne mais Jarvis refuse de m'entendre.
Je n'ai pas de micro donc j'utilise le micro interne du portable, j'ai fait tout les tests d'enregistrement, ça fonctionne, mais si je fais un jarvis -nv, j'obtiens ceci 

Une idée ?

### Logs
cat: /proc/asound/card0/usbid: Aucun fichier ou dossier de ce type
lsusb: option requires an argument -- 'd'
Usage: lsusb [options]...
List USB devices
  -v, --verbose
      Increase verbosity (show descriptors)
  -s [[bus]:][devnum]
      Show only devices with specified device and/or
      bus numbers (in decimal)
  -d vendor:[product]
      Show only devices with the specified vendor and
      product ID numbers (in hexadecimal)
  -D device
      Selects which device lsusb will examine
  -t, --tree
      Dump the physical USB device hierarchy as a tree
  -V, --version
      Show version of program
  -h, --help
      Show usage and help

------------ Config ------------
jv_branch            master 
jv_version            
jv_arch              x86_64 
jv_os_name           ubuntu 
jv_os_version        16.04 
language             fr_FR 
play_hw              false 
rec_hw               hw:0,0 
speaker              Default 
microphone            
recorder             snowboy 
trigger_stt          snowboy 
command_stt          bing 
tts_engine           svox_pico 
--------------------------------

DEBUG: program_startup hook
DEBUG: start_speaking hook
tu m'entends jarvis: Bonjour
DEBUG: stop_speaking hook
User defined commands:
*AIDE*			*BONJOUR*|*SALUT*	*COMMENT*APPELLE*
*MERCI*			*AU REVOIR*|*BYE*	ANNULE*|TERMINE*
ENCORE*			*TEST*			*VERSION*
*REPETE (*) ET (*)	*CA VA*			>*OUI*
>*NON*|*PAS*
Commands from plugin jarvis-time:
*QUELLE HEURE*		*QUEL JOUR*
tu m'entends jarvis: Waiting to hear 'tu m'entends jarvis'
eric: (listening...)
DEBUG: models=tu mentends jarvis
INFO:snowboy:Ticks: [2, 20, 5, -1]

**Comment by wikijm** [comment]
Bonsoir @edblv 

Un problème similaire a été abordé ici : https://github.com/alexylem/jarvis/issues/61
Si l'on regarde tes logs, on peut voir que :
* Le fichier /proc/asound/card0/usbid n'existe pas, or il est censé contenir la configuration audio
* play_hw est à false, ce qui veux dire qu'aucune sortie n'est déclarée

Je t'invite à refaire la configuration audio au sein même d'OpenJarvis et de nous en faire un retour 😉

**Comment by wikijm** [comment]
Clôture du ticket jusqu'à obtention d'une réponse de la part de l'auteur de l'issue.
Closing of the ticket until a valid answer from the applicant is obtained.
