### ISSUE TITLE
Pas de retour de Jeedom

### ISSUE THREAD

**Issue by lilp69** [alexylem/jarvis#798]
Bonjour, je viens d'installer le plugin jeedom dans le but de lancer des commandes vocales à Jeedom.
Lorsque sur Jarvis je tape le nom de mon scénario/intéractions, voici le retour que j'ai : 
```
$jv_pg_jd_waiting && say "Un instant..."; jeedom_call "$order"
curl --silent --fail --show-error "http://IPPublic:80/core/api/jeeApi.php?a
pikey=XxXs&type=interact" --data-urlencode "query=alertes pluies"                                                                   
DEBUG: start_sp
```

**Comment by wikijm** [comment]
Bonsoir @lilp69,

Je t'invite à créer ton issue sur le repository du plugin, ici :
https://github.com/alexylem/jarvis-jeedom

Cordialement,
@wikijm
