### ISSUE TITLE
Erreur avec le micro Jarvis

### ISSUE THREAD

**Issue by lilp69** [alexylem/jarvis#799]
Bonjour,
J'ai configurer Jarvis pour la détection du mot "Homer", lorsque je le lance et que je dit le mot "Homer", je voit une action dans les logs, mais après, j'ai beau essayé de dire "bonjour, ca va...?" jarvis sort en erreur : ```
------------ Config ------------
jv_branch            master
jv_version
jv_arch              armv6l
jv_os_name           raspbian
jv_os_version        9
language             fr_FR
play_hw
rec_hw               hw:1,0
speaker              Default
microphone           Intel Corp.
recorder             sox
trigger_stt          snowboy
command_stt          bing
tts_engine           svox_pico
--------------------------------

No speaker configured, forcing mute mode
DEBUG: program_startup hook
DEBUG: start_speaking hook
Homer: Hello
DEBUG: stop_speaking hook
User defined commands:
*AIDE*                  *BONJOUR*|*SALUT*       *COMMENT*APPELLE*
*MERCI*                 *AU REVOIR*|*BYE*       ANNULE*|TERMINE*
ENCORE*                 *TEST*                  *VERSION*
*REPETE (*) ET (*)      *CA VA*                 >*OUI*
>*NON*|*PAS*
Homer: Waiting to hear 'Homer'
LilP: (listening...)
DEBUG: models=homer
INFO:snowboy:Ticks: [2, 20, 5, -1]
INFO:snowboy:Keyword 1 detected at time: 2018-01-27 11:32:50
INFO:snowboy:Ticks status: 2 1 1 1
DEBUG: modelid=0
Homer
DEBUG: entering_cmd hook
LilP: (listening...)
DEBUG: start_speaking hook ""
utils/timeout.sh 10 rec -V1 -q -r 16000 -c 1 -b 16 -e signed-integer --endian li                                                                                                                                                             ttle /dev/shm/jarvis-record.wav gain  -2 silence 1 0.1 1% 1 0.5 1% pad 0.5 0.5 t                                                                                                                                                             rim 0 5
DEBUG: speech duration was 50 (10 = 1 sec)
WARNING: too long for a command (max 4 secs), ignoring...
HELP: try in order the following options
1) wait longer between voice commands
2) reduce ambiant background noise
3) decrease mic sensitivity in Settings > Audio
4) increase Min Silence Level to Stop
DEBUG: stop_listening hook
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM false
play FAIL formats: can't open output file `default': snd_pcm_open error: No such                                                                                                                                                              file or directory
ERROR: play command failed
HELP: Verify your speaker in Settings > Audio > Speaker

DEBUG: program_exit hook

```

**Comment by wikijm** [comment]
Bonsoir @lilp69,

Problème déjà abordé [ici](https://github.com/alexylem/jarvis/issues/343).
Je te laisse rouvrir ce ticket si jamais cela ne résout pas ton problème 😃

Cordialement,
@wikijm
