### ISSUE TITLE
Nouveau TTS Hors ligne avec Snowboy pour reconnaissance du mot clé

### ISSUE THREAD

**Issue by alexylem** [alexylem/jarvis#8]
https://snowboy.kitt.ai/

**Comment by remjou1** [comment]
tu compte l'ajouter a jarvis ?

**Comment by alexylem** [comment]
Oui comme alternative hors-ligne de PocketSphinx

**Comment by alexylem** [comment]
Premiers test de `snowboy` très concluant sur Mac (ultra rapide) 😄

**Comment by physicien** [comment]
Est-ce que snowboy est multilingue ou seulement en anglais? Après, pour reconnaître un seul mot, ça n'a pas vraiment d'importance.

**Comment by alexylem** [comment]
Il est vraiment language independant. L'utilisateur enregistre le trigger avec sa voix. Imparable. Je suis en train de l'intégrer à Jarvis.

**Comment by physicien** [comment]
Oh wow. C'est exactement ce qu'il faut. Ça me fait penser, avons-nous un ordre de grandeur quant au pourcentage d'utilisation du CPU d'une RP3 pour une config de Jarvis avec snowboy + envoie à un serveur?

**Comment by alexylem** [comment]
https://snowboy.kitt.ai/docs
> light-weight and embedded: it runs on Raspberry Pi’s and consumes **less than 10%**
CPU **on the weakest Pi’s** (single-core 700M Hz ARMv6).

J'attends les tests sur mon Raspberry Pi 3 pour confirmer, ca devrait être insignifiant 😄

**Comment by physicien** [comment]
Parfait! Je demande, car je veux rouler OpenCV (sur la même RP3 de préférence) et ça je sais que ça peut en demander plus.

**Comment by alexylem** [comment]
Je fais déjà tourner OpenCV sur le même raspberry pi 3, car je compte intégrer à Jarvis bientôt la détection et reconnaissance faciale avec apprentissage. D'ailleurs j'ai déjà fini cette partie mais l'intégrer à Jarvis prendra du temps (car j'aimerais tout réécrire en Python pour l'occasion).

**Comment by physicien** [comment]
Fabuleux! C'est exactement une des applications que je comptais utiliser, ça et la reconnaissance d'obstacles à distance (mais ça c'est une autre histoire). Bref, si je peux aider en quoi que ce soit, je suis rarement loin de mon PC.

**Comment by alexylem** [comment]
Je viens de finir l'intégration de snowboy avec Jarvis. Ca fonctionne à merveille **sur Mac**:
```
------- Config (verbose) -------
platform              osx 
language              fr_FR 
play_hw               false 
rec_hw                false 
trigger_stt           snowboy 
command_stt           google 
tts_engine            osx_say 
--------------------------------
SNOWBOY: Bonjour Alex
SNOWBOY: Waiting to hear 'SNOWBOY'
Alex: SNOWBOY
SNOWBOY: Oui?
Alex: au revoir
SNOWBOY: Au revoir Alex
```
Je commence les tests sur Raspberry Pi 3 (surtout la partie installation automatique de snowboy) et si c'est tout bon je mets en ligne 😄

**Comment by alexylem** [comment]
Premier tests de Snowboy sur Raspberry Pi 3 tout aussi concluent. Le CPU tourne entre 5% avec des pics à 10%. La reconnaissance est aussi fulgurante que sur le Mac. Aucun délai.

Il faut par contre que j'améliore encore un peu le script d'installation (la compilation n'est pas évidente) et la manière dont sont gérés les périphériques audio dans Jarvis (ce qui nécessitera probablement un reboot à chaque fois qu'on modifiera un périphérique...). Mais le jeu en vaut la chandelle.

**Comment by physicien** [comment]
Ce sera déjà ça de fait d'avoir un magic word qui fonctionne à tout coup! Je suppose qu'il est encore plus facilement modifiable ce mot, vu qu'on a pas besoin de gérer de dictionnaire ou de language model?

**Comment by alexylem** [comment]
Oui mais comme je disais plus haut ca ne sera pas pour tout de suite (car je souhaite que vous puissiez en profiter et commencer à le tester rapidement).
Donc il faudra se contenter de "SNOWBOY" comme mot magique pour le moment (le temps que je fasse l'interface pour *trainer* un autre mot)

**Comment by alexylem** [comment]
J'ai trouvé ca dans la doc de `snowboy` ce qui confirme mes résultats de test:
![capture d ecran 2016-06-25 a 18 49 54](https://cloud.githubusercontent.com/assets/11017174/16357953/a55ab9aa-3b05-11e6-8d47-9769a7891896.png)

**Comment by physicien** [comment]
Bien, ça laisse donc toute la place à OpenCV. J'ai hâte de l'essayer :smile:

**Comment by alexylem** [comment]
Intégration de Jarvis avec snowboy terminé. La mise à jour est disponible!

**IMPORTANT**
1) une fois la mise à jour effectuée, veuillez redémarrer votre raspberry pi
2) aller dans Settings > Voice recognition > Reco of magic word > choisir `snowboy`
3) cela changera votre trigger à `SNOWBOY`car on ne peut pas le modifier pour le moment, cela est prévu dans une prochaine version, suivre l'implémentation ici #13 

Si vous rencontrez des erreurs en utilisation basique de `snowboy` veuiller réouvrir ce ticket.

**Comment by physicien** [comment]
Malheureusement, dès qu'il entre en mode écoute après avoir entendu son nom, j'ai ce message d'erreur. J'ai essayé de changer de STT engine pour le mode écoute et ce n'est pas ça.
![capture d ecran - 2016-06-25 - 20 28 25](https://cloud.githubusercontent.com/assets/19982063/16359864/9c2eb63e-3b13-11e6-99b4-ae7377848005.png)

**Comment by alexylem** [comment]
merci pour le screenshot ca aide bcp, j'ai identifié le pb c'est `play_hw` qui est à false.
Va dans Settings > Audio > Speaker et refais la sélection du device. Ca devrait résoudre ton problème.

**Comment by physicien** [comment]
Oui, c'était bien ça. Merci.

**Comment by remjou1** [comment]
par contre maintenant que je le lance ça me donne ça :

pi@raspberrypi ~/jarvis $ ./jarvis.sh
Checking for updates...[Up-to-date]
JARVIS: Bonsoir rèmjou
JARVIS: Waiting to hear 'JARVIS'
rèmjou: rec WARN alsa: can't encode 0-bit Unknown or not applicable
#rec WARN alsa: can't encode 0-bit Unknown or not applicable
#rec WARN alsa: can't encode 0-bit Unknown or not applicable
Jarvis
JARVIS: Oui?
rèmjou: rec WARN alsa: can't encode 0-bit Unknown or not applicable

Date: Sat, 25 Jun 2016 09:45:17 -0700

**Comment by alexylem** [comment]
Mode troubleshoot stp

Alexandre MELY
email : alexandre.mely@gmail.com
tel : 06.20.18.21.76

2016-06-26 18:57 GMT+02:00 remjou1 <notifications@github.com>:
