### ISSUE TITLE
Micro/Enceinte multiple + reconnaissance vocale 

### ISSUE THREAD

**Issue by Haulier59** [alexylem/jarvis#804]
Bonsoir.  Je me permet d'ouvrir un ticket pour plusieurs questions concernant jarvis. 
-est il possible d'y connecter plusieurs micro et enceinte afin de repartir la domotisue un peu partout dans la maison ? Si non : je pense qu'il serait intéressant de pencher sur le problème. 

-est il possible de faire fonctionner jarvis avec une reconnaissance vocale qui reconnaît les personnes ? 
Je prend l'exemple à l'installation jarvis demande de prononcer 3 fois le mot magique pour un apprentissage mais ma façon de dire n'est pas la même que madame ou mon fils ..... (en même temps je suis pas sur qu'il faudrait agir sur jarvis mais plutôt sur la reconnaissance) 
De plus on pourrait imaginer un droit au commande restreint quand il reconnaît la voix d'un enfant par exemple. 

Merci de ton aide en tout cas c'est un magnifique projet que je suis de prêt, que je "finance" et que j'adore. God job

**Comment by wikijm** [comment]
Bonjour @Haulier59 

De mémoire, les points que tu évoques on déjà été soulevés.
Je t'invite donc à compléter les issues déjà existantes et [encore ouvertes](https://github.com/alexylem/jarvis/issues).
