### ISSUE TITLE
Jarvis multi node

### ISSUE THREAD

**Issue by shahwahed** [alexylem/jarvis#805]
Bonjour,

Je regardais à modifier Jarvis pour faire du multi node.
Deux possibilité :
Des Jarvis rpi reparti dans la maison mais qui sont tous relier à un rpi ou un pc plus puissant qui centralise les traitements et renvoie l'info au noeud déclancheur.

Autre possibilité avoir un deport de ressource pour des traitements nécessitant plus de puissance

Je pensais utiliser un rabbitmq pour le bus de messagerie d'échange d'info.

Vous avez déjà pensais à ça? Ou vous avez des pistes ?

**Comment by wikijm** [comment]
Bonjour @shahwahed 

Je t'invite à regarder ce plugin : https://openjarvis.com/plugins/multi-jarvis-server-esclaves
Peux-tu nous dire si cela correspond à ton besoin ?

Si oui, merci de clôturer l'issue 😃 
Si non :
* Penses-tu que le plugin ci-dessus peut être amélioré pour répondre à tes besoins ?
* Envisages-tu de créer un plugin ?

**Comment by shahwahed** [comment]
merci pour le lien vers ce plugin, en partie ça repond a mon besoin.
je suis en pleine relfexion pour comment couplé Jarvis a d'autre systeme (domotique, alarme intéligente, execution de tache etc), je pense que je vais cloturer l'issue, et je revienderais vers vous une fois que j'aurais les idées un peu plus clair

merci beaucoup!
