### ISSUE TITLE
Impossible de faire fonctionner le speaker

### ISSUE THREAD

**Issue by xtremp** [alexylem/jarvis#809]
Jarvis fonctionnait très bien, puis je l'ai entraîné à reconnaître quelques commandes, et depuis quand j'essaie de lancer Jarvis, il m'affiche ceci : 
ERROR: play command failed
HELP: Verify your speaker in Settings > Audio > Speaker
En allant dans les paramètres, je n'entend rien quand il me demande de faire le test. J'ai essayé avec la prise jack (hw:0,0) et les speakers de mon écran (hw:0,1) mais rien à faire, je n'arrive pas à reconfigurer mes speakers, et je ne peux démarrer Jarvis.
Quelqu'un saurait-il à quoi ce problème est du ? Merci !

**Comment by Oliv4945** [comment]
Comme demandé lors de l'ouverture de l'issue: `jarvis -nv` ?

**Comment by wikijm** [comment]
Pas de retour de l'utilisateur, je clôture donc l'issue.
Merci pour ton temps @Oliv4945 😃
