### ISSUE TITLE
Lancement de Jarvis sur Debian9

### ISSUE THREAD

**Issue by Eagleleader** [alexylem/jarvis#810]
Bonjour,

lorsque j'essaye de lancer jarvis après sont installation, je reçois le message d'erreur suivant:
mkdir: cannot create directory 'plugins_installed': permission denied
j'ai tenté de le lancer avec le SU mais du coup j'ai le message:
Jarvis must not be used as root

Je suis débutant sur Debian, j'ai essayé de mettre mon user actuel dans le groupe sudo mais cela ne change rien.

Une idée pour m'aider?

Cordialement,

**Comment by Oliv4945** [comment]
Salut,

Tu peux essayer de taper dans le dossier de Jarvis: `chown -R user:user ../jarvis`, en remplaçant "user" par ton nom d'utilisateur. Comment as-tu téléchargé/installé Jarvis ?

**Comment by Eagleleader** [comment]
alors quand je tape cette commande en remplaçant le deuxième user par mon user actuel il me dit invalid user
j'ai téléchargé en suivant le guide: https://www.openjarvis.com/content/installation

**Comment by Eagleleader** [comment]
cela fonctionne par contre si je fais: chown username ../jarvis
Oliv4945 je te remercie pour ton aide
