### ISSUE TITLE
Utilisation des variables

### ISSUE THREAD

**Issue by Munozmu8** [alexylem/jarvis#811]
Juste une question : 

Voilà en fait j'arrive pas à utilisé correctement la fonction : 
                          jv_error()

Je veut juste coloré le texte. Avez-vous une solution ?

Munozmu

**Comment by Oliv4945** [comment]
Bonjour,

Que souhaitez vous faire ? Da ce que je vois [ici](https://github.com/alexylem/jarvis/blob/736d82c416883430ebcba2878aba44ddea539ebe/utils/utils.sh#L296) il y a déjà des couleurs

**Comment by wikijm** [comment]
Pas de retour de l'utilisateur, je clôture donc l'issue.
Merci pour ton temps @Oliv4945 😃
