### ISSUE TITLE
installattion snowboy

### ISSUE THREAD

**Issue by ghost** [alexylem/jarvis#812]
Bonjour

Au moments de choisir son stt je choisis snow boy il me demande de l'installer je fait yes et la il me ne installe pas

**Comment by Oliv4945** [comment]
Bonjour,

Quel plateforme utilisez vous ?

**Comment by Eagleleader** [comment]
Salut @bagou35450 j'ai eu le meme soucis avec Debian 9, j'ai donc suivi les instructions de @Oliv4945 dans cet article: https://github.com/alexylem/jarvis/issues/660

**Comment by Eagleleader** [comment]
Pas de nouvelles = bonnes nouvelles ?

**Comment by wikijm** [comment]
Pas de retour de l'utilisateur, je clôture donc l'issue.
Merci pour votre temps @Oliv4945 et @Eagleleader 😃
