### ISSUE TITLE
Problème de commande

### ISSUE THREAD

**Issue by Anisogel** [alexylem/jarvis#819]
Bonjour à tous

J'ai un soucie aux niveau des commandes, en effet je commande mes volet avec ces commande:

```
*FERME*RIDEAU==say "Pas de souci";../decent.sh; say "C'est fait"
*FERME*RIDEAU*MOITIÉ==say "Pas de soucie je vais decendre le rideau à moitier";../decentmoit.sh;say "C'est fait"
*OUVRE*RIDEAU*==say "Pas de soucie";../monte.sh;say "C'est fait"
```

Elles renvoie à des fichier bash manipulant des gpio, qui active des relais.

Cependant voila mon problême, jarvis interprete "ferme les rideau à moitié" en executant le resultat de "ferme les rideau" ou ai je commis l'erreur ?

Merci par avance !

**Comment by wikijm** [comment]
Bonjour @Anisogel,

Quel est ton problème ?
Merci de nous fournir tout ce qui pourrait aider à résoudre ton soucis, tel que :

- Messages d'erreurs
- Captures d'écran
- Contexte de lancement

**Comment by Oliv4945** [comment]
Salut,

Quelle est la question ? et que nous dit `jarvis -nv` ?

**Comment by Anisogel** [comment]
Désoler peut être n'ai je pas été suffisamment explicite:
Lorsque je lui demande de fermer le rideau à moitié, il me lance le shell de lorsque je lui demande de fermer le rideau complétement, comme si il ne prenait pas le "à moitié", je bosse dessus depuis une pair d'heure, mais je ne trouve pas mon erreur.

J'ai lancer un jarvis -nv : 
```
pi@raspberrypi:~ $ ./jarvis/jarvis.sh -nv
Notice: you can use 'jarvis' instead of './jarvis/jarvis.sh'

------------ Config ------------
jv_branch            master
jv_version
jv_arch              armv7l
jv_os_name           raspbian
jv_os_version        9
language             fr_FR
play_hw              hw:0,0
rec_hw               hw:1,0
speaker              ALSA
microphone           Intel Corp.
recorder             sox
trigger_stt          snowboy
command_stt          bing
tts_engine           google
--------------------------------

DEBUG: program_startup hook
DEBUG: start_speaking hook "Coucou"
Gladys: Coucou
DEBUG: using cache /dev/shm/coucou.mp3
DEBUG: stop_speaking hook
User defined commands:
*AFFICHE* AIDE*         *BONJOUR*|*SALUT*       *COMMENT*APPELLE*
MERCI*                  *AU REVOIR*|*BYE*       ANNULE*|*TERMINE*
ENCORE*                 *TEST*                  *QUELLE EST TA VERSION*
*REPETE (*) ET (*)      *CA VA*                 >*OUI*
>*NON*|*PAS*            *CONNAIS*KIM*           >*BIEN SURE*
>*NON*                  *CONNAIS*THIBAULT*      *CONNAIS*LULU*
*CONNAIS*MICHEL*        *MONTRE-MOI LES GPIO*   *PREPARE*GPIO*
*FERME*RIDEAU           *FERME*RIDEAU*MOITIÉ    *OUVRE*RIDEAU*
Gladys: Waiting to hear 'Gladys'
Thibaut: (listening...)
DEBUG: models=gladys
INFO:snowboy:Ticks: [-1, -1, -1, -1]



```

**Comment by RvMeTaL** [comment]
Salut , l'erreur est que Jarvis lit les commandes dans l'ordre , donc quand il entend ferme les rideaux moitier , il traite d'abord ferme les rideaux ( premiere  commande qui correspond ) .

```
*FERME*RIDEAU*MOITIÉ==say "Pas de soucie je vais decendre le rideau à moitier";../decentmoit.sh;say "C'est fait"
*FERME*RIDEAU==say "Pas de souci";../decent.sh; say "C'est fait"
*OUVRE*RIDEAU*==say "Pas de soucie";../monte.sh;say "C'est fait"

```
En changeant l'ordre comme au dessus ça devrait convenir.

**Comment by Anisogel** [comment]
Donc si je comprend bien, plus on ajoute "d'argument", plus ils doivent se trouver en premier ?

**Comment by RvMeTaL** [comment]
C'est ça
Allume la lampe a 50 % en bleu
Allume la lampe a 50 %
Allume la lampe en bleu
Allume la lampe

**Comment by Anisogel** [comment]
Impec ! merci beaucoups pour votre coup de main, je peut passer le sujet en close ?

**Comment by Oliv4945** [comment]
C'est fait :)
