### ISSUE TITLE
Problem when you have multiple pmdl files

### ISSUE THREAD

**Issue by LengZai** [alexylem/jarvis#82]
Hello,

Quand on a plusieurs fichiers pmdl differents dans le dossier resources de snowboy, jarvis reagit alors qu'il ne devrait pas.
Exemple:
3 fichiers pmdl dans le repertoire resource de snowboy (Perceval.pmdl, Allume la lampe.pmdl et snowboy.umdl)
Je lance jarvis.sh en mode non conversation et que mon magic_word est snowboy

Voila le resultat sur la console (Pi3), en gras, les reactions de jarvis.sh alors qu'il ne devrait pas reagir..
Je ne pense pas que cela soit une grosse modif dans le code
Donc on peut rajouter une option dans jarvis.sh... Soit il reagit a tous les fichiers pmdl qui sont dans le dossier resources (pratique pour plusieurs membres d'un foyer) ou il ne reagit bien **QUE** au magic_word specifié dans les settings... soit snowboy dans mon exemple. (sachant que snowboy est un fichier umdl)

snowboy: Bonjour
snowboy: Waiting to hear 'snowboy'
Toto: snowboy
snowboy: Oui?
Toto: merci
snowboy: De rien
snowboy: Waiting to hear 'snowboy'
**Toto: Allume la lampe
snowboy: J'ai entendu ceci: Allume la lampe**
snowboy: Waiting to hear 'snowboy'
**Toto: Perceval
snowboy: J'ai entendu ceci: Perceval**
snowboy: Waiting to hear 'snowboy'
Toto: snowboy
snowboy: Oui?
Toto: merci
snowboy: De rien
snowboy: Waiting to hear 'snowboy'
Toto:

Quand penses-tu en esperant que tu aies compris mon souci?

**Comment by alexylem** [comment]
J'ai très bien compris, mais ce n'est pas un problème, c'est le comportement attendu depuis l'implémentation des commandes rapides #15 .
Voir ce post la pour plus de détails sur son fonctionnement:
https://github.com/alexylem/jarvis/issues/15#issuecomment-236276267

Si tu ne veux pas que Jargis réagisse sur ces autres .pmdl, déplace les du dossier `resources/` ou change l'extension.
