### ISSUE TITLE
Volumio2 par la voix est ce possible ?

### ISSUE THREAD

**Issue by jppmedia** [alexylem/jarvis#821]
Bonjour,
Je débute avec jarvis. Je souhaiterai contrôler [Volumio2](https://volumio.org/introducing-volumio-2/) par la voix avec jarvis, est ce possible ? Si oui comment ?
Merci d'avance
jp

**Comment by wikijm** [comment]
Oui il te faudra créer un plugin, car ce que tu demandes a pour but de répondre à un besoin bien précis.

>     Dans ce cas comment créer plugin pour Jarvis ?

Une documentation est disponible à cette adresse : https://openjarvis.com/
Pour la création d'un plugin, c'est par ici : https://openjarvis.com/content/publish-your-plugin

**Comment by wikijm** [comment]
Je clôture cette issue le temps que tu puisse prendre en compte les documentations que je t'ai indiqué.
Par la suite, n'hésites pas à créer une nouvelle issue si tu rencontres des difficultés à  le créer et le faire fonctionner 😃
