### ISSUE TITLE
Paquet jq non trouvé 

### ISSUE THREAD

**Issue by Romain91610** [alexylem/jarvis#822]
Bonjour, 
J'ai suivi les étapes pour l'installation de jarvis sur raspberry malheureusement le paquet jq me manque pour lancer jarvis.
Je suis bloqué et ne sais pas comment faire, pouvez-vous m'aider ?

Cordialement, 

Romain LENFANT

**Comment by wikijm** [comment]
Bonjour @Romain91610,

Les commandes suivantes devraient résoudre ton problème :
```
sudo apt-get update
sudo apt-get upgrade -y
sudo apt-install jq -y
```

**Comment by Romain91610** [comment]
Je viens de le faire et malheureusement le problème reste le même.


Télécharger Outlook pour Android<https://aka.ms/ghei36>

________________________________

**Comment by wikijm** [comment]
Peux-tu nous faire une capture d'écran de ton problème ?

**Comment by Romain91610** [comment]
Oui dès que je rentre je fait ça
Par contre le fait d'être en version wheezy y joue peut être un peu ?
J'avais le raspberry depuis quelques temps dans un tiroir et je n'avais jamais eu le temps de m'y replonger jusqu'à il y a quelques semaines, du coup le problème est sûrement celui-ci, je vais migrer vers jessie pour valider mon doute.

Merci encore pour ton retour rapide.

Télécharger Outlook pour Android<https://aka.ms/ghei36>

________________________________

**Comment by Romain91610** [comment]
Bonjour,

Je voulais juste vous informer que je suis passé en version Jessie et qu'effectivement cela fonctionne, il y avait bien une histoire de version Debian obsolète.

Merci encore pour votre aide.

Romain

Télécharger Outlook pour Android<https://aka.ms/ghei36>

________________________________

**Comment by Oliv4945** [comment]
Super, merci du retour. Pour info Debian en est à Stretch ;)
