### ISSUE TITLE
Après hotword, WARNING apparait

### ISSUE THREAD

**Issue by memorex37** [alexylem/jarvis#823]
### Bonjour,
J'ai ce soucis de non reconnaissance après mon hotword, voici le debug : 
------------ Config ------------
jv_branch            master 
jv_version            
jv_arch              armv7l 
jv_os_name           raspbian 
jv_os_version        9 
language             fr_FR 
play_hw              false 
rec_hw               false 
speaker              Default 
microphone           Default 
recorder             sox 
trigger_stt          snowboy 
command_stt          bing 
tts_engine           svox_pico 
--------------------------------

DEBUG: program_startup hook
DEBUG: start_speaking hook "Bonjour maitre"
Jarvis: Bonjour maitre
DEBUG: stop_speaking hook
User defined commands:
*AIDE*			*BONJOUR*|*SALUT*	*COMMENT*APPELLE*
*MERCI*			*AU REVOIR*|*BYE*	ANNULE*|TERMINE*
ENCORE*			*TEST*			*VERSION*
*REPETE (*) ET (*)	*CA VA*			>*OUI*
>*NON*|*PAS*
Jarvis: Waiting to hear 'Jarvis'
mes Maitres: (listening...)
DEBUG: models=jarvis
INFO:snowboy:Ticks: [2, 20, 5, -1]
INFO:snowboy:Keyword 1 detected at time: 2018-03-22 07:05:42
INFO:snowboy:Ticks status: 1 1 1 1
WARNING:snowboy:No match silence_before
INFO:snowboy:Keyword 1 detected at time: 2018-03-22 07:05:45
INFO:snowboy:Ticks status: 2 1 1 1
DEBUG: modelid=0
Jarvis
DEBUG: entering_cmd hook
mes Maitres: (listening...)
DEBUG: start_listening hook
utils/timeout.sh 10 rec -V1 -q -r 16000 -c 1 -b 16 -e signed-integer --endian little /dev/shm/jarvis-record.wav gain 0 silence 1 0.1 0.1% 1 0.5 0.1% pad 0.5 0.5 trim 0 5
DEBUG: speech duration was 50 (10 = 1 sec)
WARNING: too long for a command (max 4 secs), ignoring...
HELP: try in order the following options
1) wait longer between voice commands
2) reduce ambiant background noise
3) decrease mic sensitivity in Settings > Audio
4) increase Min Silence Level to Stop
DEBUG: stop_listening hook
(listening...)
DEBUG: start_listening hook
utils/timeout.sh 10 rec -V1 -q -r 16000 -c 1 -b 16 -e signed-integer --endian little /dev/shm/jarvis-record.wav gain 0 silence 1 0.1 0.1% 1 0.5 0.1% pad 0.5 0.5 trim 0 5
DEBUG: speech duration was 50 (10 = 1 sec)
WARNING: too long for a command (max 4 secs), ignoring...
HELP: try in order the following options
1) wait longer between voice commands
2) reduce ambiant background noise
3) decrease mic sensitivity in Settings > Audio
4) increase Min Silence Level to Stop

Si je suis en normal, il me met un # 
J'ai vu que mon play_hw et rec_hw était en false, mais j'entends bien ma voix lors des tests.

Je sais plus trop quoi faire.
Merci de l'aide à venir.

**Comment by wikijm** [comment]
Bonjour @memorex37,

Il arrive de temps en temps que la configuration saute.
C'est un problème connu, qui se résout généralement en la refaisant.

Sinon, étrange que la version de Jarvis n'apparaisse pas dans le log que tu as fourni 😞

**Comment by memorex37** [comment]
Pour la version de Jarvis, c'est celle qui s'installe avec le script fourni dans le tuto d'installation après avoir choisi la dernière version full de raspbian sur un raspberry Pi 3, un micro Andoer Omni-Directional et un HP en jack.

Je vais repartir d'une nouvelle installation de Raspbian full et de nouveau suivre le tuto d'installation.

Je teste dans le WE et je clôture si c'est OK.

**Comment by memorex37** [comment]
J'ai testé et tout s'est bien remis, j'espère que ça n'arrive pas souvent quand même.

Merci encore pour la réponse.
