### ISSUE TITLE
Plugin: Javis-youtube-music player doesn't work anymore

### ISSUE THREAD

**Issue by gina67** [alexylem/jarvis#827]
### Description

Hello,

This plugin worked very well 1 ou 2 months ago but now, when I ask Jarvis to play a song, he finds it because he informs me he will play the music with the singer name + song name, but after this, nothing.
I don't have any error mail;I am sure it is not due to a wrong API nb because in this case Jarvis would not find the song.
Rq: I have the same issue the Radio plugin

I use a raspberry Pi3 with Raspbian, the last version of Jarvis & the plugin concerned
I saw some people have the same issue as mine but I didin't find any solution in the web.

If someone could tel me how to solve it, or could give some clue to help me to find a solution....
Thanks a lot for your help!
Nicolas

**Comment by wikijm** [comment]
Hi @gina67,

I invite you to create an issue on plugin repository too.
Here is the link for it: https://github.com/Sh1n1x/jarvis-youtube-musics-player/issues

**Comment by gina67** [comment]
Hello Wikijm,

I hadn't seen this link; thanks for your information!
Nicolas
