### ISSUE TITLE
Matrix voice 

### ISSUE THREAD

**Issue by James97432** [alexylem/jarvis#828]
Bonjour,  je n'arrive pas à configurer matrix  voice avec jarvis ou utiliser un des micros
Peut-être la fréquence d'échantillonnage 
Une idée? 
Merci d'avance à tout le monde

**Comment by wikijm** [comment]
Bonjour @James97432,

Je t'invite à regarder les issues [ouvertes](https://github.com/alexylem/jarvis/issues?q=is%3Aopen+is%3Aissue) et [fermées](https://github.com/alexylem/jarvis/issues?q=is%3Aissue+is%3Aclosed), et particulièrement celui-là : https://github.com/alexylem/jarvis/issues/808

Tu y trouveras des éléments de réponse et surtout un utilisateur pour qui cela fonctionne 😃

**Comment by James97432** [comment]
Merci beaucoup votre réponse mais déjà lu ces commentaires

**Comment by wikijm** [comment]
OK.

Et du coup, qu'as-tu pu tester, et avec quels résultats ?
As-tu essayé de contacter  @Knoppix1 ?
Aurais-tu des logs ou résultats de commande à nous communiquer ?

**Comment by James97432** [comment]
Je dois recevoir le cm1000usb dans quelques jours. J'espère que ce sera plus
facile son paramétrage en espérant qu'avec des mis à jour le Matrix Voice
sera utilisé avec Jarvis.

**Comment by Knoppix1** [comment]
@James97432 
Il faut que tu vérifie ton ~/.asoundrc 
On en parle [ICI](https://github.com/alexylem/jarvis/issues/103#issuecomment-366470681)
Ensuite il faut modifier le fichier dans Jarvis comme indiqué dans mon issue que j'ai ouvert
Et bien sur ne pas faire la bêtise que j'ai faite, c'est-à-dire ne jamais lancer Jarvis en user root

Mais avant tout ça, teste ta Voice avec les exemple dans malos et essaie de t’enregistrer avec un rec -r 16k -c 1 test.wav puis pour écouter un aplay test.wav si ça fonctionne pas alors c'est que tu a un problème d'installation de la Voice

**Comment by James97432** [comment]
ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unkno
wn PCM false
Maintenant  problème alsa
Faut il enregistrer le produit avec matrix clim?
Ça fonctionne maintenant chez vous ?

**Comment by James97432** [comment]
rec -r 16k -c 1 test.wav  produit un claquement mais aucun enregistrement
Mais aucun problème avec arecord --device=mic_channel1
-r 16000 -c 1 -f S16_LE test.wav
Une idée ?

**Comment by Oliv4945** [comment]
Est-ce que tu peux essayer sans `-c 1` ?
Voir [ici](https://github.com/alexylem/jarvis/issues/525#issuecomment-312522806)

**Comment by Oliv4945** [comment]
Fermé en attendant une réponse
