### ISSUE TITLE
Ne vocalise pas en mode bouton (jarvis.sh -l)

### ISSUE THREAD

**Issue by la-couenne** [alexylem/jarvis#830]
Bonjour à tous :)

Je découvre Jarvis, il fonctionne parfaitement quand je le lance normalement, par contre moi j'aurais besoin de le faire fonctionner à l'aide d'un bouton plutôt que le hotword.
Je lance donc ./jarvis.sh -l 
La reconnaissance se fait très bien, mais il ne vocalise pas sa réponse, que je teste avec comme tts_engine: pocketsphinx ou Google aucun son ne sort de enceintes.

Alors je me demande si dans ce mode il est normal qu'il ne fasse qu'afficher ses réponses, ou si quelqu'un a une idée pour corriger mon problème :)

Voici ma config:
language             fr_FR 
play_hw              hw:0,0 
rec_hw               hw:1,0 
speaker              ALSA 
microphone           C-Media Electronics, Inc. Multimedia Headset [Gigaware by Ignition L.P.] 
recorder             sox 
trigger_stt          pocketsphinx 
command_stt          bing 
tts_engine           svox_pico 

Merci d'avance, et bravo pour tout ce travail!! :)

**Comment by la-couenne** [comment]
Re,
Hey bin vous êtes réactifs, ça fait plaisir..

J'ai trouvé, en modifiant les variables dans jarvis.sh :)

Bon w-end

**Comment by Oliv4945** [comment]
Salut,

> Hey bin vous êtes réactifs, ça fait plaisir..

Du coup je vais réagir vite pour une fois ... on est bénévoles, donc on développe et aide les gens sur notre temps libre ! Tu peux regarder les autres issues je mets souvent 2 semaines à répondre en ce moment
Donc oui le temps de réaction est long mais si tu veux sponsoriser le projet à hauteur d'un développeur temps plein c'est bien entendu une bonne idée ;)

> J'ai trouvé, en modifiant les variables dans jarvis.sh :)

Est-ce que tu pourrais nous dire ce que tu as modifié que ça puisse aider les autres, voir même que l'on change les valeurs par défault ? Merci

Oliv'

**Comment by wikijm** [comment]
Bonjour @Oliv4945,

//trollon

Laissons le bénéfice du doute à @la-couenne et attendons de voir en combien de temps il saura nous faire une pull request digne de ce nom ;-)

 //trolloff

**Comment by la-couenne** [comment]
ReBonjour à tous,

J'avais mis ça comme ça (vous êtes réactifs...), c'était maladroit de ma part mais ce n'était pas méchamment du tout, surtout que je me doute bien que c'est sur votre temps libre :) 
C'est vrai qu'en y relisant après coup ça paraît pas sympa, alors que quand je l'ai écris j'étais content car ça marche comme je veux :D 

En fait j'aurais bien voulu savoir si chez vous en lançant ./jarvis.sh -l vous avez un retour audio, ou si c'est normal de ne pas l'avoir.

En fait je vais expliquer mon projet en 2 mots, je bosse dans un service d'urgence, on a une pharmacie (pas seulement des médics mais aussi bcp de matériel) et on passe tjs un certain temps à chercher où sont rangées les choses. Il y a qques années j'avais réalisé à l'aide de S.A.R.A.H. (http://blog.encausse.net/sarah) un système où l'on demandait "Sarah où sont les masques à oxygène" et elle répondait genre "3ème tiroir de gauche"..
Elle a tourné durant presque un an, avant que je la débranche car fonctionnant avec un capteur Kinect elle n'entendait pas les voix féminines (trop aiguës) et avait tendance à avoir des faux-positif aux sonneries de téléphone. 
Je relance donc mon projet, mais avec Jarvis et un bouton (comme ça plus de faux-positifs), et un mini micro (de façon à ce qu'on coze direct dedans).

J'ai donc modifié jarvis.sh à la ligne 465 (environ car j'ai utilisé nano sans les numéro de ligne)
juste au-dessus de 
```
if $bypasse; then
  eval ${command_stt}_STT
else
  eval ${trigger_stt}_STT
```

j'ai mis: _bypass=true_ afin de sauter le hot-word.

Mais c'est sûr que ce n'est pas très joli tout ça ;)
Maintenant je vais le lancer à l'aide d'un bouton qui déclenchera ./jarvis -n
et voir pour qu'il quitte le programme si rien n'est détecté au bout de 10 secondes.

Voilà, je m'excuse encore pour mon "vous n'êtes pas réactifs" très mal formulé :)
Bon w-end à tous!

**Comment by la-couenne** [comment]
Pour quitter j'ai simplement mis _jv_exit_ sous la ligne où il est écrit time out (déclenché après 10 sec)
Salutations à tous :)

**Comment by wikijm** [comment]
Bonsoir @la-couenne,

Merci pour cette explication.

Entre les trolleurs, les gens qui veulent tout tout de suite sans effort ni réflexion et bien d'autres qui se reconnaitront, on a tendance à avoir rapidement une réponse épidermique 😸

**Comment by Oliv4945** [comment]
Effectivement y'a du boulot à faire sur le mode bouton, je n'ai jamais utilisé.
Sympa comme application en tout cas, merci pour le retour
