### ISSUE TITLE
Switch STT engine feature request

### ISSUE THREAD

**Issue by sajov** [alexylem/jarvis#832]
You guys have done a great job! thx
Is it possible to use snowboy hotword detection as default and use online service in a plugin?
I mean have seen a thread where is have been already discussed but cant find it anymore.

thanks for reply

**Comment by Oeil2L** [comment]
hello

maybe i didn't understand your need, but why a plugin for the online service, what's the purpose?
the hotword and command service are core integrated:
https://openjarvis.com/content/stt

**Comment by sajov** [comment]
Hi sorry Not a Plugin
The question was more switching sst from offline to online on demand or as a fallback

Like using hotword as Default
Jarvis. Hotword
Weather hotword 
How is the weather in Paris on this Weekend google

**Comment by Oliv4945** [comment]
Hi,

Fallback STT is not implemented yet. I might not be so difficult to do but it requires a lot of work and Jarvis core.

**Comment by sajov** [comment]
ok, i understand. I thounght i have saw a comment about that but i do not understand french.

**Comment by Oeil2L** [comment]
use quick command with snowboy 
https://www.openjarvis.com/content/snowboy
and limit the needs to online STT

**Comment by Oliv4945** [comment]
I think there is such feature request written in French ;)

As @Oeil2L says, quick commands might be a workaround : quick command that catches "Weather hotword", then starts the STT you need for "How is the weather in Paris on this Weekend".

**Comment by sajov** [comment]
@Oliv4945 Thanks you very much!
this is exactly what i'am looking for.
I cant get it work that way, i do not understand what's the different setting that hotword jarvis is not needed.
