### ISSUE TITLE
Pocketsphinx 

### ISSUE THREAD

**Issue by aprooooo** [alexylem/jarvis#837]
Thanks for the project 💜 
I Have a question: how can I add new words or good dictionary to pocketsphinx

**Comment by wikijm** [comment]
Hi @aprooooo,

Thanks to the issue #672, I can say to you that @SmallLeandre and @Oliv4945 are or have been users of PockerSphinx.

If you guys have a answer to bring, I'm pretty sure it will be appreciated 😜

**Comment by Oliv4945** [comment]
Hi,

You need to change [this line](https://github.com/alexylem/jarvis/blob/master/stt_engines/pocketsphinx/main.sh#L57) to use another dictionary, or [edit](https://github.com/alexylem/jarvis/blob/master/stt_engines/pocketsphinx/jarvis-dictionary.dic) the default.

**Comment by aprooooo** [comment]
@Oliv4945 
Thank you friend💜,  I will try
