### ISSUE TITLE
Unable to locate alsamixer Raspbian stretch 9.4 en SSH

### ISSUE THREAD

**Issue by Pierre55555** [alexylem/jarvis#839]
Bonjour,

Je viens de passer quelques semaines à découvrir les raspberry pi et Jeedom, et je suis impressionné par les capacités et l'activité de développement autour des cette petite boite :)
Rapport qualité/prix imbattable, mais tout de même un peu de temps à investir pour faire fonctionner... d'où cette question sur Jeedom/Jarvis.

Config sur Raspbian Stretch 9.4
J'ai installé Jarvis dans /home/pi/jarvis via SSH sur mon raspberry n°1 
Mon Jeedom tourne sur un rapsberry n°2.
J'ai créé un plugin jarvis sur Jeedom dans mon raspberry2 vers mon raspberry1
J'ai fait une mise à jour pour les connecter.
Par défaut, la config prévoit Jarvis en /opt/jarvis, alors que l'install raspberry la met en /home/pi/jarvis. J'ai donc mis à jour le chemin dans Jeedom et lancé une MaJ pour vérifier que tout est OK.
Ca a l'air de fonctionner au départ (par ex, les micro et carte son sont trouvés par raspberry2 du raspberry1, et jarvis statut actif)
Mais ca ne marche pas réellement pour moi en réalité. Par ex, je n'arrive pas à faire parler raspberry1 depuis jeedom, ni à lancer quoi que ce soit.

J'ai regardé le log de MaJ dans Jeedom, et le seul msg d'erreur que je trouve est:
E: Unable to locate package alsamixer
E: Unable to locate package aplay
E: Unable to locate package arecord

Pourtant, alsamixer, aplay et arecord sont en /usr/bin/
Est-ce que j'ai raté une étape?

Pierre.

### Logs
Installation/Update of jarvis in /home/pi/jarvis
Hit:1 http://raspbian.raspberrypi.org/raspbian stretch InRelease
Hit:2 http://archive.raspberrypi.org/debian stretch InRelease
Ign:3 http://giteduberger.fr rpimonitor/ InRelease
Get:4 http://giteduberger.fr rpimonitor/ Release [1,396 B]
Fetched 1,396 B in 1s (1,014 B/s)
Reading package lists...
Reading package lists...
Building dependency tree...
Reading state information...
alsa-utils is already the newest version (1.1.3-1).
curl is already the newest version (7.52.1-5+deb9u5).
gawk is already the newest version (1:4.1.4+dfsg-1).
git is already the newest version (1:2.11.0-3+deb9u2).
jq is already the newest version (1.5+dfsg-1.3).
mpg123 is already the newest version (1.23.8-1).
nano is already the newest version (2.7.4-1).
perl is already the newest version (5.24.1-3+deb9u3).
sed is already the newest version (4.4-1).
sox is already the newest version (14.4.1-5).
wget is already the newest version (1.18-5+deb9u2).
whiptail is already the newest version (0.52.19-1).
0 upgraded, 0 newly installed, 0 to remove and 6 not upgraded.
Reading package lists...
Building dependency tree...
Reading state information...
E: Unable to locate package alsamixer
E: Unable to locate package aplay
E: Unable to locate package arecord
HEAD is now at 7f4043b Merge pull request #800 from Cqoicebordel/Cqoicebordel-hooks
Already up-to-date.
Installation of jarvis sucess

**Comment by Oliv4945** [comment]
Bonjour,

Je vous invite à poser la question sur le repo du [plugin Jeedom](https://github.com/alexylem/jarvis-jeedom)
