### ISSUE TITLE
Commande d'ouverture de fichiers et de fermeture d’arrêt d'une carte raspberry, par jarvis

### ISSUE THREAD

**Issue by Auribaba** [alexylem/jarvis#840]
Bonjour,
je travaille sur un projet avec jarvis sur raspberry pi 3 et j'ai besoin que jarvis ouvre des fichiers, arrete la carte rpi quand je le lui demande vocalement. Merci de m'aider à travers des plugins ou des commandes.

**Comment by Oliv4945** [comment]
Allez un petit effort de réflexion ;)
Pas testé mais je dirais:
```
*STOP*==sudo halt
```

**Comment by Auribaba** [comment]
@Oliv4945  merci beaucoup, ca marche
