### ISSUE TITLE
Site web de jarvis inaccessible

### ISSUE THREAD

**Issue by willipdg** [alexylem/jarvis#844]
@alexylem impossible d'accéder au site http://domotiquefacile.fr/  de même qu'a la liste des plugins via rpi

**Comment by wikijm** [comment]
Bonjour à tous,

Le problème semble identique aux issues #841 et #842.

A voir si la cause est la même que ces dernières.

**Comment by tardistef** [comment]
Bonjour,
Votre site domotiquefacile est toujours inaccessible

Cordialement

**Comment by alexylem** [comment]
Je confirme même cause. On continue ici #841
