### ISSUE TITLE
Gérer une todo list avec Jarvis

### ISSUE THREAD

**Issue by AdrienHerman** [alexylem/jarvis#85]
### Description
Salut!
Maintenant que JARVIS marche je voudrais exécuté des commandes shell genre update du raspberry etc.. Est-ce possible? Si oui comment?

**Comment by Sopalin06** [comment]
C'est déjà possible en effet par exemple tu rajoutes la commande : 
*MET A JOUR*RASPBERRY*== say "Mise à jour en cours..." && sudo apt-get update && say "C'est fait, je suis à jour"

Puis tu dis par example : Jarvis met à jour le raspberry, et ça devrait fonctionner.

**Comment by AdrienHerman** [comment]
Ok merci et si je veux que jarvis me fasse un calcul genre 1 + 1 est-il possible de créer une variable en BASH à partir de JARVIS qu'il l'envoi au shell et qu'il lise le résultat que le shell affiche à l'écran?

**Comment by Sopalin06** [comment]
Tu peux tout faire en bash ou presque, je t'invite à regarder sur internet pour faire de petit script qui répondrons à tes attentes comme sur ce site : [http://www.linuxtricks.fr/wiki/guide-apprendre-a-scripter-en-bash](url)

**Comment by AdrienHerman** [comment]
Merci pour le site!
Je sais qu'il est possible de tout faire en BASH puisque c'est un langage de programmation comme un autre mais ce que je voulais dire c'est comment faire pour que JARVIS puisse passé deux informations au SHELL?

**Comment by Sopalin06** [comment]
Jarvis est capable de libre le résultat d'une commande shell, pour ma liste
de course j'utilise par example la ligne suivante :

*DONNE*LISTE*==say "`scripts/liste_course.sh -p`"

Le script liste_course.sh -p affiche dans le shell la liste des éléments,
et la commande say les lis comme du texte.

J'ai remarqué un soucis au niveau de la reconnaissance vocale, si tu dis
additionne 1 + 1, google va renvoyer au programme la phrase suivante :
additionne un plus un. Du coup impossible de réaliser des opérations de
calcul avec des chaines de caractères.

En espérant avoir éclairé ta lanterne

**Comment by AdrienHerman** [comment]
Ok merci!
Bon j'ai encore un problème :D Je veut avoir une liste de choses à faire donc j'ai créer un fichier list.sh à la racine du dossier de JARVIS et j'ai mis ça comme commande:
*OUVRE*LISTE*A FAIRE*==say "que dois-je ajouté?"
>(*)==./list.sh "(1)" && say "ok $username"

Et le terminal me rends:
Adrien: ouvre ma liste de choses à faire
JARVIS: que dois-je ajouté?
Adrien: faire les courses
./jarvis.sh: ligne 600: ./list.sh Permission non acordée
JARVIS: Cette commande à retournée une erreur!

Alors comment faire?
Merci d'avance!

**Comment by Sopalin06** [comment]
Tu as apparemment un soucis de permission.
Est-ce que ton script a les droit d’exécution ?
Est-ce que ton script fonctionne dans ton shell sans passer par jarvis ?

**Comment by AdrienHerman** [comment]
Apparemment c'est les droits d'exécutions qui posaient problème puisque maintenant il ne m'affiche pas d'erreurs. En revanche il ne m'écrit rien dans mon fichier list.sh.
Quand je lui fais lire avec la commande que tu m'as donné il ne fais que de me dire scripts/list.sh -p
Voilà mon code:
*OUVRE*LISTE*A FAIRE*==say "que dois-je ajouté?"
>(*)==./list.sh "(1)" && say "ok $username, dois-je la lire?"
>>*OUI*==say "ok && say "'scripts.list.sh -p'"
>>*NON*==say "ok"

**Comment by remjou1** [comment]
ya quelque chose dans le .sh ?

**Comment by AdrienHerman** [comment]
Non

**Comment by remjou1** [comment]
essaye de transformer la variable 1 en une autre variable

**Comment by Sopalin06** [comment]
Mon Script réalise un simple cat d'un fichier txt et l'affiche, du coup la
commande say lit la sortie de la commande.

2016-08-02 17:39 GMT+02:00 remjou1 <notifications@github.com>:

**Comment by remjou1** [comment]
oui je sais ça mais j'essaye de résoudre le problème de la var qui ne se met pas dans le .sh

**Comment by alexylem** [comment]
Merci tout le monde d'avoir aidé Adrien, ca fait plaisir de voir la communauté à l'oeuvre!
Voici ma modeste contribuer, exemple simple de ce qui "devrait" marcher (sans avoir à passer par un script intermédiaire):

**Commands Jarvis**
```shell
*AJOUTE*LISTE*==say "que dois-je ajouter?"
>(*)==echo (1) >> ~/todo.txt && "ok $username, dois-je la lire?"
>>*OUI*==say "elle contient $(cat ~/todo.txt)"
>>*NON*==say "ok"
```

**Comment by AdrienHerman** [comment]
Merci à tous de m'avoir aidé ça fais vraiment plaisir!
Tout marche correctement maintenant vraiment merci!
