### ISSUE TITLE
Impossible de faire fonctionner Jarvis

### ISSUE THREAD

**Issue by coder-76** [alexylem/jarvis#850]
Bonjour à tous, étant débutant en raspberry pi, je me suis lancé avec jarvis, le paramétrage s'est bien effectué même avec un micro bas de gamme. Mais voilà mon problème, quand je lance jarvis, il me dit Bonjour et attend d'entendre le mot magique; une fois "jarvis" dit il me dit "oui?" puis s'arrête en m'affichant un message d'erreur : ERROR: snowboy recognition failed

J'ai vérifié le fichier main.py et maindecoder_sox.py et rien ne me semble anormal.
Je vous laisse le code ici, merci à vous? :) 

<pi@raspberrypi:~/jarvis $ ./jarvis.sh
Notice: you can use 'jarvis' instead of './jarvis.sh'
Checking updates for jarvis...Up-to-date
Jarvis: Bonjour Dimitri
User defined commands:
*AIDE*			*BONJOUR*|*SALUT*	*COMMENT*APPELLE*
*MERCI*			*AU REVOIR*|*BYE*	ANNULE*|TERMINE*
ENCORE*			*TEST*			*VERSION*
*REPETE (*) ET (*)	*CA VA*			>*OUI*
>*NON*|*PAS*		*COMMENT JE M'APPELLE*	>*ET TOI*
*HELLO*
Jarvis: Waiting to hear 'Jarvis'
Dimitri: Jarvis
Jarvis: Oui ?
Dimitri: ERROR: snowboy recognition failed
HELP: run in troubleshooting mode for more information

pi@raspberrypi:~/jarvis $ ./jarvis.sh
Notice: you can use 'jarvis' instead of './jarvis.sh'

------------ Config ------------
jv_branch            master 
jv_version            
jv_arch              armv6l 
jv_os_name           raspbian 
jv_os_version        9 
language             fr_FR 
play_hw              hw:0,0 
rec_hw               hw:1,0 
speaker              ALSA 
microphone           C-Media Electronics, Inc. CM108 Audio Controller 
recorder             sox 
trigger_stt          snowboy 
command_stt          snowboy 
tts_engine           svox_pico 
--------------------------------

DEBUG: program_startup hook
DEBUG: start_speaking hook "Bonjour Dimitri"
Jarvis: Bonjour Dimitri
DEBUG: stop_speaking hook
User defined commands:
*AIDE*			*BONJOUR*|*SALUT*	*COMMENT*APPELLE*
*MERCI*			*AU REVOIR*|*BYE*	ANNULE*|TERMINE*
ENCORE*			*TEST*			*VERSION*
*REPETE (*) ET (*)	*CA VA*			>*OUI*
>*NON*|*PAS*		*COMMENT JE M'APPELLE*	>*ET TOI*
*HELLO*
Jarvis: Waiting to hear 'Jarvis'
Dimitri: (listening...)
DEBUG: models=jarvis
INFO:snowboy:Ticks: [2, 20, 5, -1]
INFO:snowboy:Keyword 1 detected at time: 2018-06-06 12:28:44
INFO:snowboy:Ticks status: 2 2 2 1
DEBUG: modelid=0
Jarvis
DEBUG: entering_cmd hook
DEBUG: start_speaking hook "Oui ?"
Jarvis: Oui ?
DEBUG: stop_speaking hook
Dimitri: (listening...)
DEBUG: models=Alarme,alexa,Enregistrer,hello,jarvis,merci,quelle heure,Redémarre,snowboy
Traceback (most recent call last):
  File "stt_engines/snowboy/main.py", line 83, in <module>
    trigger_ticks=ticks)
  File "/home/pi/jarvis/stt_engines/snowboy/maindecoder_sox.py", line 72, in __init__
    resource_filename=resource.encode(), model_str=model_str.encode())
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 335: ordinal not in range(128)
DEBUG: modelid=-10
ERROR: snowboy recognition failed
HELP: check error message above, if:
IOError: [Errno Invalid input device (no default output device)] -9996
  1) check your mic in Settings / Audio / Mic
  2) reboot your device
  3) report at: https://github.com/alexylem/jarvis/issues/415
IOError: [Errno Invalid sample rate] -9997
  1) check your mic in Settings / Audio / Mic
  2) try uninstalling pulseaudio
  3) try fresh OS install
  4) your mic does not support 16k sampling rate, change mic
  5) report at: https://github.com/alexylem/jarvis/issues/311
IOError: [Errno Unanticipated host error] -9999
  1) your mic is in error state, unplug/replug it
  2) report at https://github.com/alexylem/jarvis/issues/20
Other
  1) report at https://github.com/alexylem/jarvis/issues/new

DEBUG: program_exit hook
>

**Comment by Oliv4945** [comment]
Salut,

Snowboy est utilisé en trigger, il faut changer le "command stt" par autre chose comme bing ;)

**Comment by coder-76** [comment]
Merci, grâce à toi j'ai pu résoudre mon soucis en allant dans les paramètres de Jarvis en changeant le speech par bing comme tu l'as dit et je n'ai plus eu qu'à télécharger la clé API et maintenant il répond à la première comme aux autres commandes malgré qu'il ait un peu de mal quand même. :)

**Comment by Oliv4945** [comment]
Super !
