### ISSUE TITLE
Associer un avatar animé à Jarvis

### ISSUE THREAD

**Issue by coder-76** [alexylem/jarvis#852]
Bonjour, ayant récemment installé Jarvis sur mon raspberry, et ayant visité le site botlibre.com je me suis demandé si c'était possible de démarrer l'avatar quand jarvis se lance et que les lèvres bouges et même temps que jarvis parle. 
Cela ressemble a : 
<script type='text/javascript' src="https://www.botlibre.com/scripts/sdk.js"></script>
<script type='text/javascript'>
SDK.applicationId = "1253150357230229338";
var sdk = new SDKConnection();
var web = new WebAvatar();
web.connection = sdk;
web.avatar = "22225225";
web.voice = "jessica_voice";
web.voiceMod = "default";
web.lang = "fr";
web.width = "700";
web.height = "600";
web.background = "white";
web.createBox();
web.addMessage("Bonjour", "happy", "", "");
web.processMessages();
</script>

Est-ce possible? J'attend vos réponses avec impatience !

**Comment by wikijm** [comment]
Bonjour @coder-76,

Il existe un plugin pour ça : http://openjarvis.com/plugins/face

N'hésites pas à créer une issue sur le repository de ce plugin si tu rencontres des problèmes avec 😉

**Comment by coder-76** [comment]
Je te remercie @wikjim, je vais essayer ça de suite :)
Je te redis par la suite

**Comment by coder-76** [comment]
Bon eh bien ça marche j'ai remplacer fluorescent par cortana c'est déjà mieux :)
