### ISSUE TITLE
Mettre un script a la place de face

### ISSUE THREAD

**Issue by coder-76** [alexylem/jarvis#853]
Bonjour je viens d'installer le plugin jarvis-face mais je ne sais pas comment faire pour remplacer le visage de jarvis, ici cortana par un script qui, je crois est en javascript.
Voici le script que j'aimerai mettre à la place mais je ne sais pas également dans quel fichier le mettre : 

<script type='text/javascript' src="https://www.botlibre.com/scripts/sdk.js"></script>
<script type='text/javascript'>
SDK.applicationId = "1253150357230229338";
var sdk = new SDKConnection();
var web = new WebAvatar();
web.connection = sdk;
web.avatar = "22225225";
web.voice = "jessica_voice";
web.voiceMod = "default";
web.lang = "fr";
web.width = "700";
web.height = "600";
web.background = "white";
web.createBox();
web.addMessage("Bonjour", "happy", "", "");
web.processMessages();
</script>

 A l'occasion : Si quelqu'un travaille en ce moment sur jarvis et qui a un peu de temps à perdre, j'aimerai rentrer en contact avec pour travailler ensemble et s'échanger des connaissances à propros de jarvis ;)

**Comment by wikijm** [comment]
Re-bonjour @coder-76,

Comme dit dans le #852, je t'invite à créer une issue sur le repository du plugin lui-même, disponible à l'adresse suivante :  https://github.com/alexylem/jarvis-face

Bonne journée,
WikiJM
