### ISSUE TITLE
desinstaller jarvis

### ISSUE THREAD

**Issue by tardistef** [alexylem/jarvis#855]
### Description

Français and English are allowed.
Detailed description of your problem.
In case of feature request, please provide justification & example of usage.

### Logs
```shell
<PASTE HERE> full content of the terminal with Jarvis in troubleshooting mode
(keep triple quotes above and below to preserve formatting) 
```
Alternatively attach a terminal session recording using asciinema:
```shell
sudo apt-get install -y asciinema && asciinema rec # start session recording
./jarvish.sh -nv # start jarvis directly in troubleshooting mode
Ctrl+D # stop recording
y # yes to upload and get URL to paste here
```

**Comment by tardistef** [comment]
bonjour,
Je commence sur raspberry et jarvis , je voudrais desinstaller proprement jarvis suite a une erreur mais je n'y arrive pas, le sudo apt(get autoremove jarvis ne fonctionne pas.

Pouvez vous m'aidez pour le desinstaller proprement afin que je recommence,
J'ai aussi un probleme de micro, je ne trouve pas le device
enfin pour le mot clé je ne sais pas ou mettre le fichier, je ne trouve pas l'endroit.

Merci pour votre aide

**Comment by Oliv4945** [comment]
Salut,

Il suffit d'effacer le dossier de Jarvis et de supprimer le fichier `~/.asoundrc`

**Comment by tardistef** [comment]
Merci Je vais essayé,
Je vais me connecter en vnc pour voir,
Sinon je fait ta méthode en ssh.
Je vous tien au courant.
Désolé des question bête que je pose.
