### ISSUE TITLE
Problème avec le Respeaker Mic Array v2.0, le micro ne capte rien

### ISSUE THREAD

**Issue by petitsurfeur** [alexylem/jarvis#857]
Bonjour

RPI 2 avec Raspbian 8.1
J'ai acheté le Respeaker Mic Array v2.0,  installé python python-dev python-pip build-essential swig libpulse-dev libasound2-dev, pocketsphinx webrtcvad, portaudio, pyaudio pyusb. 
J'ai mis a jour le firmware. 
L'enceinte, connecté au Respeaker fonctionne bien > testé avec 
`mplayer http://rfm-live-mp3-128.scdn.arkena.com/rfm.mp3`

Le micro intégré fonctionne bien aussi, les leds réagissent et tests OK avec
```
arecord -D plughw:1,0 -f cd test.wav
aplay -D plughw:1,0 -f cd test.wav
```

Par contre lorsque je lance l'installation de jarvis: 
Au moment de tester le son, j'entend un fort grésillement (card 1, subdevice 0)
```
**** List of PLAYBACK Hardware Devices ****
card 0: ALSA [bcm2835 ALSA], device 0: bcm2835 ALSA [bcm2835 ALSA]
  Subdevices: 8/8
  Subdevice #0: subdevice #0
  Subdevice #1: subdevice #1
  Subdevice #2: subdevice #2
  Subdevice #3: subdevice #3
  Subdevice #4: subdevice #4
  Subdevice #5: subdevice #5
  Subdevice #6: subdevice #6
  Subdevice #7: subdevice #7
card 0: ALSA [bcm2835 ALSA], device 1: bcm2835 ALSA [bcm2835 IEC958/HDMI]
  Subdevices: 1/1
  Subdevice #0: subdevice #0
card 1: ArrayUAC10 [ReSpeaker 4 Mic Array (UAC1.0)], device 0: USB Audio [USB Audio]
  Subdevices: 0/1
  Subdevice #0: subdevice #0
```
Et surtout lors de la phase suivante, le micro n'enregistre rien. 
Selection of the microphone device (card 1, subdevice 0)
```
**** List of CAPTURE Hardware Devices ****
card 1: ArrayUAC10 [ReSpeaker 4 Mic Array (UAC1.0)], device 0: USB Audio [USB Audio]
  Subdevices: 1/1
  Subdevice #0: subdevice #0
```

Mon fichier ~/.asoundrc :
```
pcm.!default {
  type asym
   playback.pcm {
     type plug
     slave.pcm "false"
   }
   capture.pcm {
     type plug
     slave.pcm "hw:1,0"
   }
}
```

J'ai essayé toutes les combinaisons, je ne sais plus où chercher
Je donc coincé à l'installation, auriez-vous une idée ?

**Comment by Oliv4945** [comment]
Salut,

Une petite recherche dans les issues du projets, il y en a déjà un engagement ouverte où j'ai posté une solution ;)

**Comment by petitsurfeur** [comment]
Je ne sais pas si c'est cette solution mais j'ai fini par flasher le 1_channel_firmware et cela fonctionne, j'ai pu poursuivre l'installation.
Merci
