### ISSUE TITLE
Tuto vidéo: Installation de jarvis

### ISSUE THREAD

**Issue by Oeil2L** [alexylem/jarvis#858]
Bonjour,

je ne fais pas la promo de la chaine youtube mais je trouve que ce tuto vidéo pour installer jarvis est un bon complément à ce que l'on trouve déjà sur le site officiel http://openjarvis.com/content/installation:

https://www.youtube.com/watch?v=oVUUiPdQBNc&list=PL5h7NsxkT9YNeruVRhxyPRkfApqozn7xg&index=2

**Comment by wikijm** [comment]
Merci @Oeil2L,

Le tuto vidéo est en effet très bien fait, il faut juste savoir supporter l'accent Québecois 😜
