### ISSUE TITLE
Arrêt de Jarvis -n 

### ISSUE THREAD

**Issue by Sopalin06** [alexylem/jarvis#86]
J'ai lancé jarvis en background depuis hier soir, puis suite à des modifs dans les commands j'ai voulu le relancer, j'ai donc tuer le processus en cours puis relancé et là horreur un soucis sur le micro  : Devices is busy
Le fait de tuer le processus jarvis ne coupe pas la reco snowboy qui tourne en fond et verrouille le micro.
Du coup il faut également tuer le processus python qui fait tourner snowboy pour pouvoir relancer jarvis.

Il serais intéressant de pouvoir couper le processus qui tourne en service sans se préoccuper des processus sous-jacent.

**Comment by alexylem** [comment]
Comment as-tu quitté jarvis?
As-tu fait un `kill` manuellement ou as-tu lancé `./jarvis.sh` pour quitter jarvis? (il détecte et te propose de le quitter "proprement")

**Comment by Sopalin06** [comment]
J'y suis allé comme un bourrin avec un kill de jarvis. J'avais pas vu qu'il
y avait l'option, au temps pour moi.
Par contre il y a un petit soucis de gestion des accents je crois :
command :
*ALLUME*TELEVISION*===say "Je m'en occupe" && wget -qO /dev/null "
http://192.168.1.100:8080/json.htm?type=command&param=switchlight&idx=21&switchcmd=On
"

Réponse :
Thomas: allume la télévision
hey_tolia: Je ne comprend pas: allume la television

On peut fermer ce ticket et en ouvrir un autre si tu préfères pour pas
polluer sinon :p


2016-08-02 18:54 GMT+02:00 Alexandre Mély <notifications@github.com>:

**Comment by alexylem** [comment]
Donc je te confirme, si tu veux quitter proprement jarvis et limiter les problèmes de micro, relancer jarvis, il détecte et te proposera de le quitter.
Oui je veux bien que tu ouvre un ticket séparé pour le problème d'accents.
Sinon stp évite de répondre aux mails de notification de github, ca pollue le ticket avec l'historique des mails, il vaut mieux cliquer sur le lien et répondre sur le site, tu bénéficieras ainsi des modifications sur les posts.
Merci!!

**Comment by Sopalin06** [comment]
Tu peux cloturer ce ticket, le problème d'accent n'existe pas, si tu regarde ma commande j'avais mis 3 signes "=" :p 
Le fait de quitter via le menu marche sans soucis.
