### ISSUE TITLE
SVOX Pico

### ISSUE THREAD

**Issue by TwiSka** [alexylem/jarvis#860]
Bonjour,

j'ai un soucis pour installer SVOX Pico sur OSX j'ai toutes les dernières versions installées sur mon OS..

Si quelqu'un a une solution ?

**Comment by wikijm** [comment]
Bonjour @TwiSka,

Peux-tu s'il te plait fournir les informations demandées lors de la création de l'issue ? 
Difficile de t'aider sans cela 👼

**Comment by wikijm** [comment]
Bonjour @TwiSka,

As-tu vu mon message ?
