### ISSUE TITLE
Problème micro respeeker

### ISSUE THREAD

**Issue by petitsurfeur** [alexylem/jarvis#862]
### Description

Bonjour
Je n'arrive pas a comprendre pourquoi mon Respeeker ne parvient pas à enregistrer le son lors de la procédure d'installation de Jarvis.
J'ai une enceinte Anker qui est branchée sur le RPI (et non le Respeeker) et qui fonctionne très bien. Testé avec la commande 
`mplayer -ao alsa:device=hw=0,0 http://rfm-live-mp3-128.scdn.arkena.com/rfm.mp3`

Les commandes suivantes fonctionnent bien, ce qui m'a permis de déduire que les 2 périphériques sont opérationnels. 
```
arecord -D plughw:1,0 -f cd test.wav
[...]
aplay -D plughw:0,0 -f cd test.wav
```
Et pourtant lorsqu'il s'agit de tester le micro lors de la procédure d'installation de Jarvis, il ne se passe rien

```
Selection of the microphone device
**** List of CAPTURE Hardware Devices ****
card 1: ArrayUAC10 [ReSpeaker 4 Mic Array (UAC1.0)], device 0: USB Audio [USB Audio]
  Subdevices: 1/1
  Subdevice #0: subdevice #0
Indicate the card # to use [0-9]: 1
Indicate the device # to use [0-9]: 0
```
J'ai également essayé 0 - 0
Avez-vous une idée ? 
Merci

**Comment by satana888** [comment]
Bonjour,

 

As-tu essayé dans le terminal  

Sudo raspi-config

Et dans les paramètres  « advanced options »

Aller mettre les paramètres de sortie audio et relancer après validation ?

 

C’est bête, mais parfois les machines c’est capricieux !

 

 

 

De : petitsurfeur [mailto:notifications@github.com] 
Envoyé : dimanche 8 juillet 2018 23:39
À : alexylem/jarvis
Cc : Subscribed
Objet : [alexylem/jarvis] Problème micro respeeker (#862)

 


Description


Bonjour
Je n'arrive pas a comprendre pourquoi mon Respeeker ne parvient pas à enregistrer le son lors de la procédure d'installation de Jarvis.
J'ai une enceinte Anker qui est branchée sur le RPI (et non le Respeeker) et qui fonctionne très bien. Testé avec la commande
mplayer -ao alsa:device=hw=0,0 http://rfm-live-mp3-128.scdn.arkena.com/rfm.mp3

Les commandes suivantes fonctionnent bien, ce qui m'a permis de déduire que les 2 périphériques sont opérationnels.

arecord -D plughw:1,0 -f cd test.wav
[...]
aplay -D plughw:0,0 -f cd test.wav

Et pourtant lorsqu'il s'agit de tester le micro lors de la procédure d'installation de Jarvis, il ne se passe rien

Selection of the microphone device
**** List of CAPTURE Hardware Devices ****
card 1: ArrayUAC10 [ReSpeaker 4 Mic Array (UAC1.0)], device 0: USB Audio [USB Audio]
  Subdevices: 1/1
  Subdevice #0: subdevice #0
Indicate the card # to use [0-9]: 1
Indicate the device # to use [0-9]: 0

Avez-vous une idée ?
Merci

**Comment by satana888** [comment]
Re-bonjour,

 

Si pas ?

Autre truc a essayer…

Tu va dans l’installation de Jarvis et tu lui install le plugin «  alsamixer ? » si ce n’est pas déjà fait !

 

Deux choses a tenter avant de te proposer une désinstallation de Jarvis et le réinstaller pour voir.

 

 

De : petitsurfeur [mailto:notifications@github.com] 
Envoyé : dimanche 8 juillet 2018 23:39
À : alexylem/jarvis
Cc : Subscribed
Objet : [alexylem/jarvis] Problème micro respeeker (#862)

 


Description


Bonjour
Je n'arrive pas a comprendre pourquoi mon Respeeker ne parvient pas à enregistrer le son lors de la procédure d'installation de Jarvis.
J'ai une enceinte Anker qui est branchée sur le RPI (et non le Respeeker) et qui fonctionne très bien. Testé avec la commande
mplayer -ao alsa:device=hw=0,0 http://rfm-live-mp3-128.scdn.arkena.com/rfm.mp3

Les commandes suivantes fonctionnent bien, ce qui m'a permis de déduire que les 2 périphériques sont opérationnels.

arecord -D plughw:1,0 -f cd test.wav
[...]
aplay -D plughw:0,0 -f cd test.wav

Et pourtant lorsqu'il s'agit de tester le micro lors de la procédure d'installation de Jarvis, il ne se passe rien

Selection of the microphone device
**** List of CAPTURE Hardware Devices ****
card 1: ArrayUAC10 [ReSpeaker 4 Mic Array (UAC1.0)], device 0: USB Audio [USB Audio]
  Subdevices: 1/1
  Subdevice #0: subdevice #0
Indicate the card # to use [0-9]: 1
Indicate the device # to use [0-9]: 0

Avez-vous une idée ?
Merci

**Comment by Oliv4945** [comment]
Je ne suis pas devant mon PC mais cherchez Respeaker dans les issues, j'ai proposé des changements pour que ça fonctionne

**Comment by petitsurfeur** [comment]
Bonjour
Merci pour vos réponses. 
-> raspi-config // advanced options // modifier les paramètres audio n'a rien fait
-> alsamixer est déjà installé et fonctionne correctement puisque je peux ainsi régler le son
J'ai déjà hier supprimé le dossier jarvis et réinstallé.

@Oliv4945 > J'ai suivi la discussion #525 et dans le fichier jarvis/stt_engines/snowboy/main.sh j'ai remplacé les 3 lignes
`rec -r 16000 -c 1 -b 16 -e signed-integer /tmp/1.wav gain $gain`
par 
`rec -r 16000 -b 16 -e signed-integer /tmp/1.wav gain $gain remix -`
mais cela n'a rien donné. 
Jarvis n'est pas lancé en tant que root.
J'ai suivi les instructions récupérées https://github.com/alexylem/jarvis/issues/103#issuecomment-366437292  (notamment désinstallé pulseaudio que j'avais dû installer pour faire fonctionner l'enceinte en bluetooth) et cela fonctionne maintenant.

Merci
