### ISSUE TITLE
demande d'aide sur reconnaissance facial python 

### ISSUE THREAD

**Issue by husoka20188** [alexylem/jarvis#865]
est ce que je avoir une idée sur comment je peux faire un code python en utilisant tensorflow et toute en prenat compte des condition suivant:

Lorsqu'un visage est détecté par la camera, il regarde dans sa base
Si le visage est connu, il dit bonjour avec le prénom de la personne
Sinon, on affiche je vous ai pas reconnu
et merci d'avance

**Comment by wikijm** [comment]
Bonsoir,

Clôture de cette issue car en doublon avec #864
