### ISSUE TITLE
Problem with hooks

### ISSUE THREAD

**Issue by yukysky** [alexylem/jarvis#866]
Bonjour, j'ai un problème avec les hooks de jarvis, ou du moins je n'arrive pas à les faire fonctionner.
Je veux allumer une LED quand Jarvis parle et l'eteindre quand il a fini. Voilà les codes :

```shell
$verbose && jv_debug "DEBUG: start_listening hook"
import RPi.GPIO as gpio
import time

gpio.setwarnings(False)
gpio.cleanup()

gpio.setmode(gpio.BOARD)
gpio.setup(11,gpio.OUT)
pwm = gpio.PWM(11,100)
pwm.start(100)
```

```shell
$verbose && jv_debug "DEBUG: stop_listening hook"
gpio.setwarnings(False)
gpio.cleanup()

gpio.setmode(gpio.BOARD)
gpio.setup(11,gpio.OUT)
pwm = gpio.PWM(11,100)

pwm.stop()
gpio.cleanup()
```

aucune erreur n'est détecté ou quoi que ce soit, cependant ma LED ne s'allume pas, pourtant dans un prog test.py à pars, tout marche bien... des idées ? Merci d'avance

____________________________________________________________________________________________________________
Hello, I have an issue with hooks of Jarvis, I'm not sure if i use them correctly and if it's intended this way.
I try to light up an LED while he speaks, and switch it off when he no longer speaks.
Start_listening and stop_listening are the same from up here ^^^^
I have no errors running it, still no LED are lit up... Any ideas ? thanks
____________________________________________________________________________________________________________
Used :
raspberry pi 3 B connected to a LED with a resistor
Python 3
latest raspbian

**Comment by alexylem** [comment]
Jarvis en codé en bash, pas en python, on dirait que ton code est du python. Depuis le hook exécute ton fichier python et ca devrait le faire.
