### ISSUE TITLE
Partager un plugin

### ISSUE THREAD

**Issue by did57** [alexylem/jarvis#867]
Bonjour,

Je cherche à partager un plugin que je viens créer, [https://github.com/did57/jarvis-radio-salue-de](url), mais je ne trouve pas le lien pour le publier dans le store de Jarvis.

J’ai bien cliqué sur le bouton "Register my plugin" de la page "Create your plugin" et sur le bouton "Create an plugin" de la page "All Plugins" mais ils mènent tous les deux sur une page not found

**Comment by Oliv4945** [comment]
Salut,

Effectivement le nom de domaine n'a pas été changé dans le lien, vous pouvez utiliser http://openjarvis.com/user/login?destination=node/add/plugin

@alexylem , on va avoir besoin de toi là dessus :)

**Comment by alexylem** [comment]
@Oliv4945 oui merci j'avais remarqué que tous les liens de dur marchaient pas. J'ai commencé à les corriger 1 à 1. Pour la publication du plugin ca devrait être bon.
Merci!

**Comment by Oliv4945** [comment]
@alexymel Si tu es sous un système Unix, sed est ton ami :)

**Comment by alexylem** [comment]
😆 Donc je pensais en effet faire un rechercher-remplacer dans la BDD 👍

**Comment by did57** [comment]
C'est bon, je l'ai publié dans le store, merci pour vos réponses :)
