### ISSUE TITLE
Paramétrer les sons de Jarvis

### ISSUE THREAD

**Issue by Sopalin06** [alexylem/jarvis#87]
L'idée serait de pouvoir paramétrer les sons qui sont utilisés par jarvis facilement via le menu.
Pour le moment obliger de modifier le code en dur.

**Comment by alexylem** [comment]
Quels sont souhaiterais-tu changer?
Peux-tu donner un exemple?
J'ai récemment changé les "bips" de Jarvis pour qu'il sonne plus moderne, voir #62

**Comment by AdrienHerman** [comment]
Oui et non moi je pense aller jusqu’à pouvoir choisir d'autres sons pour un évènement, une commande ou voir même avoir sa musique directement sur la raspberry.

**Comment by alexylem** [comment]
On ne peut pas tout mélanger...

Son pour un évènement, quel évènement? exemple?
Son pour une commande, ca vous pouvez déjà faire:
```
*FAIT CELA*==play ~/my_sound.wav
```
Sa musique directement sur la raspberry, exemple? Contrôler une liste de lecture?

**Comment by AdrienHerman** [comment]
Exemple à 7:00 lance telle musique. <- évènement
Pour la liste de lecture oui c'est ça.

**Comment by alexylem** [comment]
On peut déjà faire tout ca avec Jarvis:

* Lancer une musique pour le réveil
 * Voir dans **Menu > Events** et rajouter une ligne au format `cron` pour jouer une musique à 7:00
```
0       7       *       *       *       play ~/music.wav
```

* Gérer une liste de lecture, ca dépend quel logiciel tu as sur ton raspberry pi, mais l'idée générale est:
```shell
*LECTURE*==player play
*PAUSE*==player pause
*STOP*==player stop
```

**Comment by AdrienHerman** [comment]
Peut-on lire du mp3 avec JARVIS?

**Comment by alexylem** [comment]
Rien à voir avec Jarvis. Demande-toi (ou à Google) plutôt comment lire un fichier mp3 sur un Raspberry Pi. Puis cherche la commande pour le faire depuis le terminal. Puis utilise cette commande dans Jarvis. Et voilà 😄 

Allez je suis sympa...
```
mpg123 music.mp3
```
