### ISSUE TITLE
domoticz plugin

### ISSUE THREAD

**Issue by Firegamer56** [alexylem/jarvis#871]
Je souhaiterais dans le plugin domoticz pouvoir faire varier une lumiere via dimmer.

**Comment by wikijm** [comment]
Bonjour à toi aussi @Firegamer56,

Ta demande étant relative au plugin Domoticz et non à OpenJarvis en lui-même même, je t'invite à créer ton issue ici : https://github.com/landaisbenj/jarvis-domoticz/issues

Cordialement,
@WikiJM
