### ISSUE TITLE
Jarvis ne m'entend pas alors que l'installation s'est bien déroulée ... aidez moi SVP

### ISSUE THREAD

**Issue by Guims** [alexylem/jarvis#881]
### Description

Bonjour, je viens à vous car je rencontre un probleme ... j'ai suivis le tutoriel d'installation à la lettre, j'ai un peu galéré à configurer le micro usb que vous conseillez dans le tuto mais j'ai réussi, je n'ai aucunes erreurs pendant l'installation mais quand je parle à jarvis il ne me comprend pas on dirait ... je vous joint plus bas les logs de putty et une video comme vous le demander, merci d'avance pour votre aide.

### Logs
```shell
DEBUG: program_startup hook
Starting RestAPI server on http://192.168.1.20:8080
Starting User Interface on http://192.168.1.20:8081
DEBUG: start_speaking hook "Hello"
jarvis: Hello
DEBUG: stop_speaking hook
User defined commands:
*AIDE*                  *BONJOUR*|*SALUT*       *COMMENT*APPELLE*
*MERCI*                 *AU REVOIR*|*BYE*       ANNULE*|TERMINE*
ENCORE*                 *TEST*                  *VERSION*
*REPETE (*) ET (*)      *CA VA*                 >*OUI*
>*NON*|*PAS*
Commands from plugin jarvis-ui:
*OUVR*INTERFACE*
Commands from plugin jarvis-api:

Commands from plugin jarvis-time:
*QUELLE HEURE*          *QUEL JOUR*
Commands from plugin jarvis-CEC:
*ETEIND*LA*TELE*        *ALLUME*LA*TELE*        *ETAT*DE*LA*TELE*
*SOURCE*TELE*
Commands from plugin jarvis-pense-bete:
*PENSE (*) TERMINE*|*PE *SUPPRIME*PENSE*|*VIDE* >*OUI*
>*NON*                  *LI*PENSE*|*QUOI*DANS*P *ENVOI*PENSE*MAUD*|*EVO
*ENVOI*PENSE*
Commands from plugin jarvis-livebox:
*REDEMARE*              *REBOOT*                *NUMERO*
*RELANCE*INTERNET*      *PARTAGE*               *ACTIVER*WIFI*
*DESACTIVER*WIFI*       *ADRESSE*IP*            *MOT DE PASSE*LIVEBOX*
Commands from plugin jarvis-tusaisfairequoi:
*TU*SAI*FAIR*QUOI*      >(*)
GOTOSORTI_QUOI


jarvis: Waiting to hear 'jarvis'
guillaume: (listening...)
DEBUG: models=jarvis
INFO:snowboy:Ticks: [2, 20, 5, -1]
INFO:snowboy:Keyword 1 detected at time: 2018-09-09 11:55:39
INFO:snowboy:No match - no voice before hotword
INFO:snowboy:Keyword 1 detected at time: 2018-09-09 11:55:44
INFO:snowboy:No match - no voice before hotword
INFO:snowboy:Keyword 1 detected at time: 2018-09-09 11:55:45
INFO:snowboy:No match - no voice before hotword
INFO:snowboy:Keyword 1 detected at time: 2018-09-09 11:55:50
INFO:snowboy:No match - no voice before hotword
INFO:snowboy:Keyword 1 detected at time: 2018-09-09 11:55:51
INFO:snowboy:No match - no voice before hotword
INFO:snowboy:Keyword 1 detected at time: 2018-09-09 11:56:05
INFO:snowboy:Keyword 1 detected at time: 2018-09-09 11:56:05
INFO:snowboy:Keyword 1 detected at time: 2018-09-09 11:56:05
INFO:snowboy:Ticks status: 2 5 0 1
DEBUG: modelid=0
jarvis
DEBUG: entering_cmd hook
guillaume: (listening...)
DEBUG: start_listening hook
utils/timeout.sh 10 rec -V1 -q -r 16000 -c 1 -b 16 -e signed-integer --endian little /dev/shm/jarvis-record.wav gain  7 silence 1 0.1 10.1% 1 0.5 10.1% pad 0.5 0.5 trim 0 5
DEBUG: stop_listening hook
DEBUG: timeout, end of conversation
DEBUG: listening_timeout hook
DEBUG: exiting_cmd hook
jarvis: Waiting to hear 'jarvis'
guillaume: (listening...)
DEBUG: models=jarvis
INFO:snowboy:Ticks: [2, 20, 5, -1]
INFO:snowboy:Keyword 1 detected at time: 2018-09-09 11:56:23
INFO:snowboy:Keyword 1 detected at time: 2018-09-09 11:56:23
^CStopping HTTP server

DEBUG: program_exit hook

```
:
```shell
https://asciinema.org/a/O2YzChZXOGrP6XqsoZooahIRs
```

**Comment by NoxInmortus** [comment]
J'ai exactement le même probleme...
J'utilise un raspberry pi 2B avec ce micro : https://www.amazon.fr/dp/B01LCIGY8U/ref=cm_sw_r_cp_ep_dp_-wFmybMAE6C66
 
Jarvis: Bonjour Maître
DEBUG: stop_speaking hook
Use "?" to display possible commands (in keyboard mode)
Jarvis: Waiting to hear 'Jarvis'
Maître: (listening...)
DEBUG: models=jarvis
INFO:snowboy:Ticks: [2, 20, 5, -1]
INFO:snowboy:Keyword 1 detected at time: 2018-09-15 20:32:25
INFO:snowboy:Keyword 1 detected at time: 2018-09-15 20:32:36
INFO:snowboy:Keyword 1 detected at time: 2018-09-15 20:32:42
INFO:snowboy:Ticks status: 2 22 1 1
WARNING:snowboy:No match voice_before
INFO:snowboy:Keyword 1 detected at time: 2018-09-15 20:32:47
INFO:snowboy:No match - no voice before hotword
INFO:snowboy:Keyword 1 detected at time: 2018-09-15 20:32:48
INFO:snowboy:Keyword 1 detected at time: 2018-09-15 20:32:57
INFO:snowboy:Ticks status: 2 17 0 1
DEBUG: modelid=0
Jarvis
DEBUG: entering_cmd hook
DEBUG: start_speaking hook "Oui Maître ?"
Jarvis: Oui Maître ?
DEBUG: stop_speaking hook
Maître: (listening...)
DEBUG: models=alexa,jarvis,snowboy
INFO:snowboy:Ticks: [2, 20, 5, -1]
INFO:snowboy:Keyword 2 detected at time: 2018-09-15 20:33:06
INFO:snowboy:Keyword 2 detected at time: 2018-09-15 20:33:07
DEBUG: timeout, end of conversation
DEBUG: listening_timeout hook
DEBUG: exiting_cmd hook
Jarvis: Waiting to hear 'Jarvis'
Maître: (listening...)
DEBUG: models=jarvis
INFO:snowboy:Ticks: [2, 20, 5, -1]

**Comment by Guims** [comment]
Salut j'ai réglé le problème, je pense que j'avais mal sélectionné le micro dans le steps wizard.
pour le micro chez moi c'est carte 1 et id de periph (#) 0 ensuite il faut régler la sensibilité et c tout bon.

c'est marrant on à le même raspi avec le même micro.

Maintenant mon problème est qu'il ne me répond pas ^^ je vais ouvrir un autre ticket.

**Comment by NoxInmortus** [comment]
Tu vois qu'il t'entends avec le debug?
