### ISSUE TITLE
Jarvis sur Raspbian Stetch ??

### ISSUE THREAD

**Issue by ludo80800** [alexylem/jarvis#885]
Bonjour à tous.

Jarvis fonctionne t il sur la dernière version de Raspbian, soit Raspbian Stetch ?

ou uniquement sur Jessie Full ?

(pour info, j'ai essayé avec la dernière version mais je bloque à l'utilisation de Jarvis)

Merci

**Comment by wikijm** [comment]
Bonjour @ludo80800,

Je confirme que cela fonctionne parfaitement.

Cordialement,
WikiJM
