### ISSUE TITLE
Speech Bing ne fonctionne pas (plus)

### ISSUE THREAD

**Issue by LordDarkneo** [alexylem/jarvis#888]
### Description
Hello,
Depuis quelques mois, la reconnaissance Bing ne fonctionne plus (en commandes uniquement).
Vu que le speech Bing a pas mal changé depuis, j'ai suivi cette procédure:
https://docs.microsoft.com/en-us/azure/cognitive-services/speech-service/get-started

Comme j'ai un compte Microsoft via le boulot. J4ai donc créer un compte Azure, activé le Speech, obtenu 2 clé de licences. Sauf qu'à chaque fois que j'essaye la reconnaissance (genre ca va ou autre), j'ai ce message d'erreur:

DEBUG: json={ "statusCode": 401, "message": "Access denied due to invalid subscription key. Make sure to provide a valid key for an active subscription." }
ERROR: Access denied due to invalid subscription key. Make sure to provide a valid key for an active subscription.

J'ai regénéré les clefs, mais toujours le même problème.

J'ai essayé de switcher avec Google, mais pour chaque commande que je lance en vocale, j'ai le "?", donc idem je pense qu'il y a un problème avec la clé d'API. IDem j'ai essayé d'en généré une 2eme sur Google, ca ne fonctionne pas non plus...

Evidemment en mode keyboard, tout fonctionne nickel :) Et j'entend bien ma commande "Ca va" avant qu'il lance le speech to text.

### Logs
Bing
```shell
Thomas: (listening...)
DEBUG: start_listening hook
utils/timeout.sh 10 rec -V1 -q -r 16000 -c 1 -b 16 -e signed-integer --endian little /dev/shm/jarvis-record.wav gain 35 silence 1 0.1 8.1% 1 0.5 8.1% pad 0.5 0.5 trim 0 5
DEBUG: speech duration was 18 (10 = 1 sec)
DEBUG: stop_listening hook
DEBUG: token missing or expired
DEBUG: json={ "statusCode": 401, "message": "Access denied due to invalid subscription key. Make sure to provide a valid key for an active subscription." }
ERROR: Access denied due to invalid subscription key. Make sure to provide a valid key for an active subscription.
(listening...)
DEBUG: start_listening hook
utils/timeout.sh 10 rec -V1 -q -r 16000 -c 1 -b 16 -e signed-integer --endian little /dev/shm/jarvis-record.wav gain 35 silence 1 0.1 8.1% 1 0.5 8.1% pad 0.5 0.5 trim 0 5
```

Google:
```shell
Thomas: (listening...)
DEBUG: start_listening hook
utils/timeout.sh 10 rec -V1 -q -r 16000 -c 1 -b 16 -e signed-integer --endian little /dev/shm/jarvis-record.wav gain 35 silence 1 0.1 8.1% 1 0.5 8.1% pad 0.5 0.5 trim 0 5
DEBUG: speech duration was 17 (10 = 1 sec)
DEBUG: stop_listening hook
DEBUG: 
?(listening...)
DEBUG: start_listening hook
utils/timeout.sh 10 rec -V1 -q -r 16000 -c 1 -b 16 -e signed-integer --endian little /dev/shm/jarvis-record.wav gain 35 silence 1 0.1 8.1% 1 0.5 8.1% pad 0.5 0.5 trim 0 5
```

**Comment by qentin1741** [comment]
Même problème pour moi.

**Comment by Dimdar** [comment]
@alexylem idem pour moi ERROR: bing recognition curl failed
en lançant ./test.sh il me met le même defaut....
Problème de Bing?

**Comment by Oeil2L** [comment]
Dans mon installation Bing fonctionne parfaitement.

Par contre le problème pourrait venir d'un changement de service à venir pour l'année prochaine pour les comptes existants, j'ai reçu un mail à ce sujet.

Et dans vos cas comme vos comptes sont récents vous êtes peut-être directement sur le nouveau service.

Le mail en question:
`### Bing Speech API will be retired on October 15, 2019—migrate to Speech Services and SpeechSDK

You’re receiving this email because you currently use the Cognitive Services Bing Speech API.

We recently released the generally available Speech Services API and Speech SDK which allow you to add speech-enabled features to your apps. Because Speech Services and Speech SDK each fully replaces the existing Bing Speech API capabilities, Bing Speech will be retired as a standalone service on October 15, 2019. As with all changes of this type, we’re providing 12 months’ notice so you have adequate time to adjust.
To continue using the capabilities of Bing Speech, please migrate to Speech Services by October 15, 2019. We encourage you to make the switch sooner, to gain the richer benefits of Speech Services. In addition to the Bing Speech features you’re already familiar with, Speech Services includes:
- Speech-to-text (speech recognition), intent, translation, and text-to-speech capabilities.
- A REST API that works with any programming language that can make HTTP requests.

### **Key dates**
Beginning **October 15, 2018**, we will no longer make updates to Bing Speech and its corresponding client libraries and REST APIs. New subscription keys will no longer be available; however, your existing keys can be renewed in the Azure portal.

On **October 15, 2019**, Bing Speech will be retired and no longer be available. 
**### Recommended action**
Migrate to Speech Services before October 15, 2019, to avoid disruptions to your applications and enjoy quality and feature updates.
`

**Comment by Dimdar** [comment]
Et si on migre vers speech service , notre jarvis fonctionnera correctement? Ou faut il attendre une mise à jour de jarvis?

**Comment by did57** [comment]
vous vous êtes vous vous êtes inscrit à la version de 30 jours à l'essai gratuit à tous les services d'Azure Microsoft

@Dimdar il faut effectivement faire une inscription en donnant le numéro de sa carte de crédit.

**Comment by LordDarkneo** [comment]
Dans mon cas j'étais effectivement en version d'essai. Mais avec mon boulot j'ai un compte Microsoft 365 donc j'ai activé azure et je ne comprends pas pourquoi ça ne fonctionne pas (alors qu'avec la version d'essai c'était ok). Et pour Google je comprends encore moins!!

**Comment by did57** [comment]
As-tu remis le nouvelle clé d'activation de Bing Speech?

**Comment by Dimdar** [comment]
Je suis aussi en version paiement à la demande pour bing, j'ai bien recu le mail et depuis le 15 plus rien....

**Comment by Oeil2L** [comment]
Dans mon cas, j'utilse le service historique de Bing après la période d'essai j'ai entré ma CB pour pouvoir continuer à l'utiliser (aucune facturation à craindre ce service était gratuit: Cf mon dernier post:https://github.com/alexylem/jarvis/issues/272), j'ai comme indiqué reçu le mail d'alerte signalant que le service s'arrêterai dans 1 an, mais le service fonctionne toujours très bien, testé encore ce matin.

Peut-être que les nouveaux utilisateurs ou utilisateurs à l'essai ne peuvent pas accéder ou conserver le service historique.

A voir si Jarvis ne nécessitera pas une adaptation pour supporter le nouveau service de Bing.

**Comment by Oeil2L** [comment]
En complément, l'adaptation de Jarvis semble inévitable, le lien vers l'API de Bing et la clé sera différente:
https://docs.microsoft.com/en-us/azure/cognitive-services/speech-service/rest-apis

Mais les retours JSON ne semble pas si différents que ce que j'ai pu voir dans les debug par le passé.

**Comment by Dimdar** [comment]
@Oeil2L : j'ai bien la version paiement à la demande comme toi, je me suis inscris avec carte bleu etc etc.
Ce matin un essai tout est revenu, bing re-fonctionne.. mais pour 1 an maintenant.

**Comment by JeremyWiart** [comment]
bonjour a tous,

Quelqu'un a t-il encore des problèmes avec bing ? car ce n'est pas fonctionnelle de mon coter,pourtant tous a été fait dans les règles de l'art en passant par azure.microsoft.com. je pense plutôt me tourner vers snowboy pour la reconnaissance des commandes même si il faut paramétré tous les hotwords.

**Comment by jbastruz** [comment]
Salut, je suis dans le même cas que toi :/ si quelqu'un a plus d'info sur le sujet je suis preneur (ou même me dire si il y a un morceau de code à changer...)

**Comment by LordDarkneo** [comment]
Hello à tous et désolé pour mon retour super tardif (je suis pas mal débordé en ce moment). Alors oui j'ai essayé de regénérer des clés, mais rien n'y fait. 
Et je ne suis pas sur l'ancienne version de Bing, mais bien sur le service Azure de Microsoft. 
Mais ce qui me surprend, c'est que même Google ne fonctionne plus en STT, alors qu'avant cela fonctionnait... 

Idem, je pense que je vais me prendre le temps qu'il faut pour configurer snowboy....

**Comment by JeremyWiart** [comment]
alors après plus de deux heures passer dans le bing/main.sh, j'ai reussi à remettre les endpoint de l'api bing à jour avec une suppression de quelques paramètre qui sont devenue obsolète depuis le passage chez azure j'ai les test qui est ok avec le retour du test.wav mais c'est pas encore parfait, je vous tien au jus se soir

**Comment by JeremyWiart** [comment]
> Hello à tous et désolé pour mon retour super tardif (je suis pas mal débordé en ce moment). Alors oui j'ai essayé de regénérer des clés, mais rien n'y fait.
> Et je ne suis pas sur l'ancienne version de Bing, mais bien sur le service Azure de Microsoft.
> Mais ce qui me surprend, c'est que même Google ne fonctionne plus en STT, alors qu'avant cela fonctionnait...
> 
> Idem, je pense que je vais me prendre le temps qu'il faut pour configurer snowboy....

Comment faisais tu pour lancer une commande avec Bing avant que celui ci plante ?
car tous fonctionne mais il me renvoi un point d'interrogation...

**Comment by LordDarkneo** [comment]
A moi le ? C'est avec Google! Je n'ai rien fait de particulier si ce n'est mettre ma clé azure a la fin de la période d'essai (comme j'ai un compte pro Microsoft). Mais ça marche plus.
Idem pour Google, ca a arrêté de fonctionner du jour au lendemain (j'avais fait des tests et bing était plus fiable de mon point de vue).
J'ai régénéré une clé Google..  ça change rien

**Comment by JeremyWiart** [comment]
Bing est fonctionnel chez moi mais me renvoi toujours ce fameux point d'interrogation, apparament dans le jarvis/jarvis.sh, il considère que la variable `$order` est vide en ligne 332 alors quelle est affecter par `@1` qui normalement stocke ce qui est lu par bing et `printf "?"` en ligne 479 au lieu du mot et c'est là que je coince...

Pour ceux qui veulent refaire marcher bing,ils vous faut passer sur azure avec création d'une nouvelle ressource au préalable et changer les endpoints et paramètre du fichier. je vous C/C le code du fichier modifier stt_engines/bing/main.sh : 

 VOTRE FICHIER DOIT MAINTENANT RESSEMBLER A CELUI POUR ETRE FONCTIONNEL

et vous renvoi normalement en réponse : 

DEBUG: curl https://northeurope.stt.speech.microsoft.com/speech/recognition/conversation/cognitiveservices/v1?language=fr-FR&format=simple&profanity=raw
DEBUG: json={"RecognitionStatus":"Success","DisplayText":"Allô.","Offset":5400000,"Duration":9700000}

[main.sh.txt](https://github.com/alexylem/jarvis/files/2581121/main.sh.txt)

**Comment by xStroke** [comment]
Hi, 
I hope you can help me allthough i cant speak french ^^
Are there still Azure Speech issues? 
I am trying to set up jarvis with the Azure Speech API but it says: 
**ERROR: Access denied due to invalid subscription key. Make sure to provide a valid key for an active subscription.**

Have I done sth wrong or is the Azure Speech API (old Bing) not supported atm? 

![unbenannt](https://user-images.githubusercontent.com/39802172/49314182-e321ca80-f4e9-11e8-9b51-191f7c171529.PNG)

**Comment by LordDarkneo** [comment]
Hello à tous!!
Bon alors je reviens sur ce ticket suite aux nombreux tests que j'ai (enfin) eu le temps de faire hier.... 
Côté Google: Speech API n'existe plus (ou en tout cas je ne le vois plus!) je n'ai accès qu'au Cloud Speech API, qui est payant.. Je suppose donc que c'est "normal" que le STT ne fonctionne plus.
Côté Azure, même blague... Bien qu'ayant pris la version gratuite, ca ne fonctionne toujours pas... 
@xStroke Which software are you using for hotwork detection?

**Comment by xStroke** [comment]
@LordDarkneo
I managed to fix this on #900 and uploaded there the needed files 

I am using Snowboy

**Comment by LordDarkneo** [comment]
HEllo à tous!!
Ca y est! Ca refonctionne enfin! 
Thanks a lot @xStroke for the main.sh!

CE que j'ai fait, vu que mes périodes d'essais étaient terminées:
- Sur AZURE, j'ai pris le Pay-as-you-go (oui avec le boulot mon compte est en anglais).
- J'ai pris Speech (via Cognitive Services)
- J'ai choisi le pricing F0 (qui est maintenant celui qui est gratuit, le S0 étant payant, cointrairement à ce qui est indiqué dans le ticket #272 ).
- J'ai récupérer le fichier de @xStroke, mis dans le stt_engine\bing
- Redémarrer Jarvis

Et c'est redevenu nickel!!! 

Par contre, pour Google, c'est toujours KO...  Je pense que je vais préparer snowboy pour éviter ce genre de déconvenues à l'avenir....

**Comment by jean51** [comment]
hello world
j ai installe JARVIS dernièrement.
j ai installe mon micro aujourd’hui, mais je galère avec la reconnaissance Vocale. j'ai fait ce qu'il ai dit au dessus. compte azure, les clés, j'ai recupere le fichier de @xStroke coller dans stt_engine/bing... et après redémarrage rien.
quand j'essaie de lui parler, il entend JARVIS et après me met ça
```
jean: *   Trying 13.74.139.192...
* TCP_NODELAY set
* Connected to northeurope.api.cognitive.microsoft.com (13.74.139.192) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* Cipher selection: ALL:!EXPORT:!EXPORT40:!EXPORT56:!aNULL:!LOW:!RC4:@STRENGTH
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/certs/ca-certificates.crt
  CApath: /etc/ssl/certs
* TLSv1.2 (OUT), TLS header, Certificate Status (22):
} [5 bytes data]
* TLSv1.2 (OUT), TLS handshake, Client hello (1):
} [512 bytes data]
* TLSv1.2 (IN), TLS handshake, Server hello (2):
{ [85 bytes data]
* TLSv1.2 (IN), TLS handshake, Certificate (11):
{ [3275 bytes data]
* TLSv1.2 (IN), TLS handshake, Server key exchange (12):
{ [365 bytes data]
* TLSv1.2 (IN), TLS handshake, Server finished (14):
{ [4 bytes data]
* TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
} [102 bytes data]
* TLSv1.2 (OUT), TLS change cipher, Client hello (1):
} [1 bytes data]
* TLSv1.2 (OUT), TLS handshake, Finished (20):
} [16 bytes data]
* TLSv1.2 (IN), TLS change cipher, Client hello (1):
{ [1 bytes data]
* TLSv1.2 (IN), TLS handshake, Finished (20):
{ [16 bytes data]
* SSL connection using TLSv1.2 / ECDHE-RSA-AES256-GCM-SHA384
* ALPN, server did not agree to a protocol
* Server certificate:
*  subject: CN=*.cognitive.microsoft.com
*  start date: Nov 29 11:13:49 2017 GMT
*  expire date: Nov 29 11:13:49 2019 GMT
*  subjectAltName: host "northeurope.api.cognitive.microsoft.com" matched cert's "*.api.cognitive.microsoft.com"
*  issuer: C=US; ST=Washington; L=Redmond; O=Microsoft Corporation; OU=Microsoft IT; CN=Microsoft IT TLS CA 5
*  SSL certificate verify ok.
} [5 bytes data]
> POST /sts/v1.0/issueToken HTTP/1.1
> Host: northeurope.api.cognitive.microsoft.com
> User-Agent: curl/7.52.1
> Accept: */*
> Content-Type: application/x-www-form-urlencoded
> Content-Length: 0
> Ocp-Apim-Subscription-Key: 8ffacaac44a142829a6895aaa7d61c46
> 
{ [5 bytes data]
< HTTP/1.1 401 Access Denied
< Content-Length: 143
< Content-Type: application/json
< apim-request-id: a0d973fb-46f0-408a-ba80-65fd5fbefa9f
< Strict-Transport-Security: max-age=31536000; includeSubDomains; preload
< x-content-type-options: nosniff
< WWW-Authenticate: AzureApiManagementKey realm="https://northeurope.api.cognitive.microsoft.com/sts/v1.0",name="Ocp-Apim-Subscription-Key",type="header"
< Date: Mon, 17 Dec 2018 14:46:36 GMT
< 
{ [143 bytes data]
* Curl_http_done: called premature == 0
* Connection #0 to host northeurope.api.cognitive.microsoft.com left intact
ERROR: Access denied due to invalid subscription key. Make sure to provide a valid key for an active subscription.
(timeout)

```
avez vous une idée de ce que j'aurais pu mal faire??

**Comment by jean51** [comment]
alors rectification, après avoir change dans azure Europe de l'ouest et north Europe. j'ai re-transféré une clé dans JARVIS, maintenant il me retourne un ? 
```
 Trying 13.74.139.192...
* TCP_NODELAY set
* Connected to northeurope.api.cognitive.microsoft.com (13.74.139.192) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* Cipher selection: ALL:!EXPORT:!EXPORT40:!EXPORT56:!aNULL:!LOW:!RC4:@STRENGTH
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/certs/ca-certificates.crt
  CApath: /etc/ssl/certs
* TLSv1.2 (OUT), TLS header, Certificate Status (22):
} [5 bytes data]
* TLSv1.2 (OUT), TLS handshake, Client hello (1):
} [512 bytes data]
* TLSv1.2 (IN), TLS handshake, Server hello (2):
{ [85 bytes data]
* TLSv1.2 (IN), TLS handshake, Certificate (11):
{ [3275 bytes data]
* TLSv1.2 (IN), TLS handshake, Server key exchange (12):
{ [365 bytes data]
* TLSv1.2 (IN), TLS handshake, Server finished (14):
{ [4 bytes data]
* TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
} [102 bytes data]
* TLSv1.2 (OUT), TLS change cipher, Client hello (1):
} [1 bytes data]
* TLSv1.2 (OUT), TLS handshake, Finished (20):
} [16 bytes data]
* TLSv1.2 (IN), TLS change cipher, Client hello (1):
{ [1 bytes data]
* TLSv1.2 (IN), TLS handshake, Finished (20):
{ [16 bytes data]
* SSL connection using TLSv1.2 / ECDHE-RSA-AES256-GCM-SHA384
* ALPN, server did not agree to a protocol
* Server certificate:
*  subject: CN=*.cognitive.microsoft.com
*  start date: Nov 29 11:13:49 2017 GMT
*  expire date: Nov 29 11:13:49 2019 GMT
*  subjectAltName: host "northeurope.api.cognitive.microsoft.com" matched cert's "*.api.cognitive.microsoft.com"
*  issuer: C=US; ST=Washington; L=Redmond; O=Microsoft Corporation; OU=Microsoft IT; CN=Microsoft IT TLS CA 5
*  SSL certificate verify ok.
} [5 bytes data]
> POST /sts/v1.0/issueToken HTTP/1.1
> Host: northeurope.api.cognitive.microsoft.com
> User-Agent: curl/7.52.1
> Accept: */*
> Content-Type: application/x-www-form-urlencoded
> Content-Length: 0
> Ocp-Apim-Subscription-Key: 92d53b4f7eb143158abcd44969cd3734
> 
{ [5 bytes data]
< HTTP/1.1 200 OK
< Cache-Control: no-cache
< Pragma: no-cache
< Content-Length: 759
< Content-Type: application/jwt; charset=us-ascii
< Expires: -1
< X-AspNet-Version: 4.0.30319
< X-Powered-By: ASP.NET
< apim-request-id: 8fd84b41-1438-XXXX-a52d-3fb974df9491
< Strict-Transport-Security: max-age=31536000; includeSubDomains; preload
< x-content-type-options: nosniff
< Date: Mon, 17 Dec 2018 15:15:07 GMT
< 
{ [759 bytes data]
* Curl_http_done: called premature == 0
* Connection #0 to host northeurope.api.cognitive.microsoft.com left intact
?

(timeout)
```
une idée??

**Comment by Oliv4945** [comment]
@jean51
Tout est dans les dernières ligne, ta clef API n'est pas valide

```
ERROR: Access denied due to invalid subscription key. Make sure to provide a valid key for an active subscription
```

**Comment by jean51** [comment]
Merci pour ta réponse. C'est ce que j'ai vu en écrivant le post. J'ai donc changé la clé azure que j'avais configurée en Europe de l'Ouest et je lai reconfigurée en Europe du Nord, pour pouvoir coller avec le script de @xStroke mais ma maintenant il me renvoie un point d'interrogation

**Comment by wikijm** [comment]
Bonsoir @jean51,

Je me suis permis de modifier un petit peu la valeur de 'Ocp-Apim-Subscription-Key' pour éviter qu'on te pique ta clé d'API 😉

**Comment by Potjoe-97** [comment]
@jean51 dans le main.sh tu as bien changé la langue ligne 45 ?

**Comment by jean51** [comment]
Bonjour @Potjoe-97. 
J'ai ligne 43 "local request="https://northeurope.stt.speech.microsoft.com/speech/recognition/conversation/cognitiveservices/v1?language=fr-FR"

**Comment by Potjoe-97** [comment]
Je me connecte au serveur Westeurope... Peut être que ça peut aider. Essaye de remplacer par :

https://westeurope.stt.speech.microsoft.com/speech/recognition/conversation/cognitiveservices/v1?

**Comment by jean51** [comment]
merci de prendre du temps pour moi @Potjoe-97 
il faut que je recupere une  nouvelle clé, west europe, et que je change les paramètres dans main.sh.
c'est bien ça?

**Comment by LordDarkneo** [comment]
Idem, j'ai    

` local request="https://westeurope.stt.speech.microsoft.com/speech/recognition/conversation/cognitiveservices/v1?"`

A mon avis, pas besoin de changer ta clé API, change juste la valeur dans le main.sh

EDIT: Pourquoi tu as notherneurope? C'est toi qui l'a mis comme ça?

**Comment by jean51** [comment]
oui je l'ai mis car le main.sh de @xStroke était configure en northEurope et ma clé Europe de l'Ouest me retournait une erreur
ERROR: Access denied due to invalid subscription key. Make sure to provide a valid key for an active subscription.

j'ai donc change ma cle

**Comment by LordDarkneo** [comment]
Du coup, si tu remet westeurope avec ton ancienne clé, ca dit quoi ?

**Comment by LordDarkneo** [comment]
Du coup, si tu remet westeurope avec ton ancienne clé, ca dit quoi

**Comment by Potjoe-97** [comment]
@jean51 il faut faire l'opération inverse. Édite une clé west europe et change le serveur tel que @lorkdakneo et moi te le suggérons dans le main.sh

**Comment by Potjoe-97** [comment]
@lorddarkneo les clés sont par serveur sur bing, il faut qu'il en recrée une

**Comment by LordDarkneo** [comment]
@Potjoe-97 oui, d'où l'idée de réutiliser celle qu'il avait avant :)

**Comment by Potjoe-97** [comment]
@lordDarkneo au temps pour moi, je t'avais mal lu !

**Comment by jean51** [comment]
alors je suis retourne sur azure, supprime speech, le mettre en Europe de l'ouest,la reediter, remis la clé dans jarvis.
je suis allé dans main.sh. et remplace 3 northeurope par westeurope.
et jarvis me renvoi un ?

Trying 13.93.122.1...
* TCP_NODELAY set
* Connected to westeurope.api.cognitive.microsoft.com (13.93.122.1) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* Cipher selection: ALL:!EXPORT:!EXPORT40:!EXPORT56:!aNULL:!LOW:!RC4:@STRENGTH
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/certs/ca-certificates.crt
  CApath: /etc/ssl/certs
* TLSv1.2 (OUT), TLS header, Certificate Status (22):
} [5 bytes data]
* TLSv1.2 (OUT), TLS handshake, Client hello (1):
} [512 bytes data]
* TLSv1.2 (IN), TLS handshake, Server hello (2):
{ [85 bytes data]
* TLSv1.2 (IN), TLS handshake, Certificate (11):
{ [3275 bytes data]
* TLSv1.2 (IN), TLS handshake, Server key exchange (12):
{ [365 bytes data]
* TLSv1.2 (IN), TLS handshake, Server finished (14):
{ [4 bytes data]
* TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
} [102 bytes data]
* TLSv1.2 (OUT), TLS change cipher, Client hello (1):
} [1 bytes data]
* TLSv1.2 (OUT), TLS handshake, Finished (20):
} [16 bytes data]
* TLSv1.2 (IN), TLS change cipher, Client hello (1):
{ [1 bytes data]
* TLSv1.2 (IN), TLS handshake, Finished (20):
{ [16 bytes data]
* SSL connection using TLSv1.2 / ECDHE-RSA-AES256-GCM-SHA384
* ALPN, server did not agree to a protocol
* Server certificate:
*  subject: CN=*.cognitive.microsoft.com
*  start date: Nov 29 11:22:55 2017 GMT
*  expire date: Nov 29 11:22:55 2019 GMT
*  subjectAltName: host "westeurope.api.cognitive.microsoft.com" matched cert's "*.api.cognitive.microsoft.com"
*  issuer: C=US; ST=Washington; L=Redmond; O=Microsoft Corporation; OU=Microsoft IT; CN=Microsoft IT TLS CA 2
*  SSL certificate verify ok.
} [5 bytes data]
> POST /sts/v1.0/issueToken HTTP/1.1
> Host: westeurope.api.cognitive.microsoft.com
> User-Agent: curl/7.52.1
> Accept: */*
> Content-Type: application/x-www-form-urlencoded
> Content-Length: 0
> Ocp-Apim-Subscription-Key: ----------------------------------------
> 
{ [5 bytes data]
< HTTP/1.1 200 OK
< Cache-Control: no-cache
< Pragma: no-cache
< Content-Length: 753
< Content-Type: application/jwt; charset=us-ascii
< Expires: -1
< X-AspNet-Version: 4.0.30319
< X-Powered-By: ASP.NET
< apim-request-id: ---------------------
< Strict-Transport-Security: max-age=31536000; includeSubDomains; preload
< x-content-type-options: nosniff
< Date: Wed, 19 Dec 2018 10:19:21 GMT
< 
{ [753 bytes data]
* Curl_http_done: called premature == 0
* Connection #0 to host westeurope.api.cognitive.microsoft.com left intact
??(timeout)

**Comment by jean51** [comment]
Merci beaucoup de vous intéresser a mon problème @LordDarkneo @Potjoe-97

**Comment by Potjoe-97** [comment]
Comment ça "3 northeurope ?" Il n'y a qu'une mention du serveur ligne 43, quelles lignes as-tu modifiées ?

**Comment by LordDarkneo** [comment]
Pas de soucis @jean51 :)

Côté Azure, sur le dashboard il te marque des infos ou pas?
![image](https://user-images.githubusercontent.com/40838306/50215061-35843780-0382-11e9-84b8-0b9c09a4399a.png)

EDIT: T'es sûr d'avoir réucpérer le bon main.sh? Car dans celui que j'ai de @xStroke c'était pas notherneurope... 

JE te met le fichier avec la correction du fr-FR, normalement il n'y a rien a changer dans ce main.sh
[main.zip](https://github.com/alexylem/jarvis/files/2694453/main.zip)

**Comment by jean51** [comment]
voila mon main.sh

#!/bin/bash
touch /tmp/jarvis_bing_token # initiate if don't exist
touch /tmp/jarvis_bing_expires # initiate if don't exist

_bing_transcribe () {
    if [ -z "$bing_speech_api_key" ]; then
        echo "" # new line
        jv_error "ERROR: missing bing speech api key"
        jv_warning "HELP: define bing key in Settings > Voice recognition"
        exit 1 # TODO doesn't really exit because launched with & forjv_spinner
    fi

    stt_bing_token="`cat /tmp/jarvis_bing_token`"
    stt_bing_expires="`cat /tmp/jarvis_bing_expires`"

    if [ -z "$stt_bing_expires" ] || [ "$stt_bing_expires" -lt "`date +%s`" ]; then
        $verbose && jv_debug "DEBUG: token missing or expired"
        # https://github.com/alexylem/jarvis/issues/145
        local json=`curl -v -X POST "https://westeurope.api.cognitive.microsoft.com/sts/v1.0/issueToken" \
            -H "Content-Type: application/x-www-form-urlencoded" \
            -H "Content-Length: 0" \
            -H "Ocp-Apim-Subscription-Key: $bing_speech_api_key" \
            --silent`
        $verbose && jv_debug "DEBUG: json=$json"

        local error=`echo $json | perl -lne 'print $1 if m{"message": "([^"]*)"}'`
        if [ -n "$error" ]; then
            jv_error "ERROR: $error"
            exit 1
        fi
        stt_bing_token="$json"
        echo $stt_bing_token > /tmp/jarvis_bing_token

        # TODO expiration date not provided anymore by bing, what to use?
        #local expires_in=`echo $json | perl -lne 'print $1 if m{"expires_in":"([^"]*)"}'`
        local expires_in=$(( 10 * 60 )) # 10 mins
        stt_bing_expires=`echo $(( $(date +%s) + $expires_in - 10 ))` # -10 to compensate webservice call duration
        echo $stt_bing_expires > /tmp/jarvis_bing_expires
        $verbose && jv_debug "DEBUG: token will expire in $(( $stt_bing_expires - `date +%s` )) seconds"
    fi

    [[ $OSTYPE = darwin* ]] && uuid=$(uuidgen) || uuid=$(cat /proc/sys/kernel/random/uuid)
    local request="https://westeurope.stt.speech.microsoft.com/speech/recognition/conversation/cognitiveservices/v1?language=fr-FR"
    request+="&format=simple"
    request+="&profanity=raw" #with this we avoid the insult with <profanity> tags

    $verbose && jv_debug "DEBUG: curl $request"
    # don't use local or else $? will not work
    json=`curl "$request" \
        -H "Accept: application/json" \
        -H "Transfer-Encoding: chunked" \
        -H "Host: westeurope.stt.speech.microsoft.com" \
        -H "Content-Type: audio/wav; codec=audio/pcm; samplerate=16000" \
        -H "Authorization: Bearer $stt_bing_token" \
        --data-binary "@$audiofile" \
        --silent --fail`
    if (( $? )); then
        jv_error "ERROR: bing recognition curl failed"
        exit 1
    fi
    $verbose && jv_debug "DEBUG: json=$json"
    local status=`echo $json | perl -lne 'print $1 if m{"status":"([^"]*)"}'`

    if [ "$status" = "success" ]; then
        echo $json | perl -lne 'print $1 if m{"name":"([^"]*)"}' > $forder
    fi
}

# Internal: Speech To Text function for Bing
# Return value: none
# Return code: 0 if success
bing_STT () {
    LISTEN $audiofile || return $?
    _bing_transcribe &
   jv_spinner $!
   return $? # return code of _bing_transcribe
}

ligne 19, 43, 52 j'ai remplace northeurope par westeurope

**Comment by Potjoe-97** [comment]
@LordDarkneo je te confirme que j'avais aussi northeurope quand j'ai copié le code de @xStroke...

**Comment by LordDarkneo** [comment]
ben les arguments dans le mien sont pas les même pour la requête vers azure...
dans celui de @jean51 ton local request donne:
https://westeurope.stt.speech.microsoft.com/speech/recognition/conversation/cognitiveservices/v1?language=fr-FR&format=simple&profanity=raw
dans le mien, ca donne: 
https://westeurope.stt.speech.microsoft.com/speech/recognition/conversation/cognitiveservices/v1?language=fr-FR&format=detailed

@Potjoe-97 tu as le profanity=raw et le format=simple chez toi?

EDIT: et je réitère, dans le #900 le lien qu'à posté xStroke est https://hannover.servegame.com/nextcloud/s/BjLHeHgg8DFrejZ et il est bien en westeurope.... :/
Faut pas copier coller ce qu'il a mis dans le ticket, c'est des tests qu'il avait fait ;)

**Comment by Potjoe-97** [comment]
@lordDarkneo j'ai exactement le même fichier que toi et je confirme que ça marche au poil avec celui-ci. @jean51 fais quand même une copie de sauvegarde de ton main.sh, et remplace le par celui que @lordDarkneo t'as envoyé.

Édit : oui je viens de voir qu'il avait des paramètres différents, je ne les ai pas non plus. Ah effectivement, tu as sûrement raison pour le Westeurope ! Ça fait quelques temps déjà, je croyais l'avoir modifié mais peut être pas. Ah si jeune et perdant déjà la mémoire... 

Par contre je me souviens que j'avais copié le main.sh du ticket, fait la modif de Oliv45, et changé le langage. Et ça marche chez moi

**Comment by LordDarkneo** [comment]
> Ça fait quelques temps déjà, je croyais l'avoir modifié mais peut être pas. Ah si jeune et perdant déjà la mémoire...


C'est surtout moi qui suit rassuré de voir que je suis pas fou :+1:

**Comment by jean51** [comment]
alléluia!!!!

MERCI beaucoup messieurs, ça fonctionne enfin. 
Vous avez assure

**Comment by LordDarkneo** [comment]
Ravi de le lire! Amuses toi bien! (Perso je pense que je vais tout passer sur snowboy, car le trouve la reconnaissance azure excessivement longue...)

**Comment by Potjoe-97** [comment]
@jean51 super tout ça ! @LordDarkneo juste avant de fermer le ticket, je viens de comparer nos deux main.sh ligne par ligne. Et il y a une ligne différente : 
Mon main.sh : ligne 67 : `local path=`echo $json | perl -lne 'print $1 if m{"ITN":"([^"]*)"}'``

Le tien : ligne 67 :  `local path=`echo $json | perl -lne 'print $1 if m{"Lexical":"([^"]*)"}'``

Je suis pas sûr d'interpréter correctement cette différence, une idée ?

**Comment by jean51** [comment]
@LordDarkneo J'ai regarde pour tout passer sur snowboy. il faut enregistrer  toute tes commandes et les entrer une par une sur jarvis?
j'ai un probleme, je me connecte a leur site. enregistrer une commande. et on doit l'enregistrer 3 fois. Moi il reste sur la première case et ne bouge plus après le premier enregistrement. Je ne peux pas la tester, rien

**Comment by Potjoe-97** [comment]
@jean51 fais un autre ticket s'il te plaît, ce thread est déjà chargé

**Comment by LordDarkneo** [comment]
@Potjoe-97 eu... Comme ça aucune idée... c'est pour débugguer les erreur "?" justement... mais je sais pas trop quelle différence ça fait de faire le test sur ITN ou Lexical... de ce que j'en comprends tu passes dans ce test que si la reconnaissance a fonctionné.. Donc je pense que c'est pour vérifié l'install de ton TTS, mais je n'en suis pas sûr...

@jean51 ton micro marche pas sur le site. Dans la barre d'url tu dois avoir une fenêtre barrée qui t'indique (si tu cliques dessus) que ton micro est bloqué :)

**Comment by Potjoe-97** [comment]
@lorddarkneo bon.. bah ça vaut pas le coup de se plonger dans l'API pour si peu. Merci !

**Comment by jean51** [comment]
@Potjoe-97 oui tu as raison, désolé, il est déjà charge et ça n'aidera pas le prochain qui  sera embêté.
Merci encore a vous 2

**Comment by Potjoe-97** [comment]
@jean51 Pas de souci ;) c'est juste pour une question de lisibilité

**Comment by Oliv4945** [comment]
Bonjour à tous, pourriez-vous tester l'intégration d'Azure/bing dans la version beta ?

Merci
Olivier
