### ISSUE TITLE
probleme de micro a l'installation

### ISSUE THREAD

**Issue by bugsymimi** [alexylem/jarvis#890]
### Description

bonjour 

j'essaye d'installer jarvis sur un pi3 b+ avec une pseye comme micro 
lors de l'install j'entend bien les aplaudissement 
mais lors du test micro je n'ai aucun marqueur sur le micro et bien sur pas de retour du coup donc impossible de finir l'instalation 

tester egalement avec un logitech c270

merci d'avance

**Comment by Oeil2L** [comment]
Bonjour,

Avez-vous fait une recherche sur "ps eye", il y a plusieurs sujet de modification du fichier .asoundrc?

Par ex:
https://github.com/alexylem/jarvis/issues/150
https://github.com/alexylem/jarvis/issues/678
https://github.com/alexylem/jarvis/issues/659

**Comment by bugsymimi** [comment]
bonjour
Oui, j'ai regarder un peu sur le git ainsi que sur le net, ce qui ma permis de voir que le micro fonctionne lors du test simple de raspbian, mais en 8bit 8khz.
Le test de jarvis est plus haut, est-ce lié, je l'ignore.  
J'ai vu deux ou trois modif du fichier asoundrc, que j'ai essayer sans succes.
Deux des exemple que tu m'as donné parle d'installation existante, malheureusement, je ne peut pas atteindre cette etappe car, comme il ne prend pas le micro a l'instal.
En fait si, il le trouve en hw1.0 mais ne recois apparement rien via jarvis,  pas de visu de niveau lors du test

**Comment by Oeil2L** [comment]
que donne cette commande:
arecord -l

Dans mon cas, les liens vers les exemples de fichiers .asoundrc impliquait de faire correspondre à mon matériel connecté: 
CameraB409241 devenant CameraB404271

PS: un peu de ponctuation dans la réponse ;)

**Comment by bugsymimi** [comment]
je teste cela de suite.
Desoler pour la ponctuation, je me suis fait la remarque apres avoir, repondu.
La paresse de la grippe sans doute. :) 

...

voila j'ai tesé la commande elle me renvoi sur 
pi@raspberrypi:~ $ arecord -l
**** Liste des Périphériques Matériels CAPTURE ****
carte 1: CameraB409241 [USB Camera-B4.09.24.1], périphérique 0: USB Audio [USB Audio]
  Sous-périphériques: 1/1
  Sous-périphérique #0: subdevice #0

et l'instal de jarvis me renvoi, cela lorsque je repond que je le micro n'a pas fonctionner 

pi@raspberrypi:~/jarvis $ ./jarvis.sh
Notice: you can use 'jarvis' instead of './jarvis.sh'
Checking updates for jarvis...Up-to-date

sounds/applause.wav:

 File Size: 463k      Bit Rate: 1.41M
  Encoding: Signed PCM    
  Channels: 2 @ 16-bit   
Samplerate: 44100Hz      
Replaygain: off         
  Duration: 00:00:02.62  

In:100%  00:00:02.62 [00:00:00.00] Out:116k  [      |      ] Hd:0.0 Clip:0    
Done.


Input File     : 'default' (alsa)
Channels       : 1
Sample Rate    : 16000
Precision      : 16-bit
Sample Encoding: 16-bit Signed Integer PCM

In:0.00% 00:00:03.07 [00:00:00.00] Out:48.0k [      |      ]        Clip:0    
Done.

/dev/shm/jarvis-record.wav:

 File Size: 96.0k     Bit Rate: 256k
  Encoding: Signed PCM    
  Channels: 1 @ 16-bit   
Samplerate: 16000Hz      
Replaygain: off         
  Duration: 00:00:03.00  

In:100%  00:00:03.00 [00:00:00.00] Out:48.0k [      |      ]        Clip:0    
Done.
Selection of the microphone device
**** Liste des Périphériques Matériels CAPTURE ****
carte 1: CameraB409241 [USB Camera-B4.09.24.1], périphérique 0: USB Audio [USB Audio]
  Sous-périphériques: 1/1
  Sous-périphérique #0: subdevice #0
Indicate the card # to use [0-9]: 
 
j'espere que cela sera plus clair ainsi

**Comment by bugsymimi** [comment]
bon pas de solution apparente
j'ai du reinstaller une nouvelle sd et la la cam ps est reconue directement
certainement un probleme de config lors de l'instal d'un autre composant

merci a Oeil2l d'avoir essayer
