### ISSUE TITLE
Snowboy key won’t be accepted.

### ISSUE THREAD

**Issue by Marcreed48** [alexylem/jarvis#891]
### Description

Français and English are allowed.
Detailed description of your problem.
In case of feature request, please provide justification & example of usage.

### Logs
```shell
<PASTE HERE> full content of the terminal with Jarvis in troubleshooting mode
(keep triple quotes above and below to preserve formatting) 
```
Alternatively attach a terminal session recording using asciinema:
```shell
sudo apt-get install -y asciinema && asciinema rec # start session recording
./jarvish.sh -nv # start jarvis directly in troubleshooting mode
Ctrl+D # stop recording
y # yes to upload and get URL to paste here
```

**Comment by Marcreed48** [comment]
Jarvis doesn’t accept snowboy api tokens. I’ve tried two, I’ll try another. It also doesn’t like it’s name changed from snowboy to Jarvis. Weird. I keep getting “invalid subscription key”. I’m on Azure and Snowboy.

**Comment by Oeil2L** [comment]
Hello

I use Snowboy and it's still working.

for Azure, Microsoft changed something, jarvis have to be update, we are talking about this (in french):
https://github.com/alexylem/jarvis/issues/888

**Comment by JeremyWiart** [comment]
Yes Snowboy work perfectly for me too

but don't use Bing for the moment cause we need an adaptation of source code of jarvis

you should use snowboy for STT and TTS and create your hotword one by one and put the word into the file command.

**Comment by Marcreed48** [comment]
Thank you for your help. I’ll create a few and let you know if it’s successful. I found another group chatting about azure, it seems I might have used my registration keys by mistake. But you’re correct, Microsoft is migrating it’s speech from common.

**Comment by Marcreed48** [comment]
I also believe we need to include the correct region end point.

**Comment by Oliv4945** [comment]
Hi, you can now try bing in the beta version of Jarvis
