### ISSUE TITLE
Aide

### ISSUE THREAD

**Issue by haddock1** [alexylem/jarvis#892]
### Description

Bonjour je me lance dans la programmation de Jarvis mais je ne suis pas programmeur et je ne comprends pas comment programmer malgrés l'aide sur le site. j'ai compris pour faire parler Jarvis mais je n'arrive pas à lui faire faire quelque chose. exemple : donner l'heure ou  la météo.
Par avance merci si quelqu'un peut m'aider

```

**Comment by JeremyWiart** [comment]
bonsoir,
avant de vouloir programmer et modifier un fichier source on apprend le langage de programmation qui va avec, autrement dit on ne programme pas sans savoir au préalable qu'est ce qu'une variable, une condition, instruction etc.... si tu n'as pas ces bases forme toi un minimum.

**Comment by haddock1** [comment]
Merci pour ta reponse aussi rapide mais peux tu me donner un exemple de commande avec le shell comme donner l heure. Histoire que je puisses programmer quelques truc sympa pour debuter
Par avance merci

**Comment by JeremyWiart** [comment]
alors moi je fait au plus simple car je connais le langage php, j'ai donc une seule ligne dans mes commande qui ressemble à ceci : 

(*)==say  $(curl -s "http://192.168.1.61/?var_a_recuperer_via_$_GET=(1)")

et je traitre ce qui est dit via un script php et une base de donner de mot et en fonction de se que je dit j'ai une réponse, car j'ai tag les mots pour que jarvis sache si il s'agit d'un sujet, d'un verbe, COD, COI, ect... et j'utilise donc un fonction server pour l'heure et la date.

Tape sur google tu auras des exemples de commande pour sa, il y a même certainement des issues sur ce sujet ici.

**Comment by Oeil2L** [comment]
alors je me trompe peut-être dans la compréhension de la demande @haddok1 mais pour obtenir l'heure ou météo de la part de Jarvis, aucune programmation n'est à prévoir.

Il suffit d'installer le plugin correspondant, et éventuellement de le paramétrer (pour la météo par ex, le code Insee de ta ville ou le code postal suivant le plugin que tu décides d'installer)

**Comment by JeremyWiart** [comment]
justement je ne suis pas sur non plus, mais je crois qu'il parler de la commande qui est lancer via les hotword de snowboy ou bing quand il sont détécter... a voir de sa réponse.

Mais dans tous les cas je pense que la solution de @Oeil2L  sera plus approprié pour toi.

**Comment by haddock1** [comment]
Wouah merci de toutes vos réponses, c'est génial.
Pour plus de compréhension, j'apprends a utiliser Jarvis avec les tutos d'Alexandre. Pour faire parler Jarvis, je n'ai pas rencontré de pb, de meme pour installer les plugins. Par contre pour rentrer quelques commandes "shell", je n'ai pas compris la syntaxe et pour quelqu'un qui ne programme pas ce n'est pas évident mais à partir d'un exemple je comprends mieux et aprés j'essaies de développer mes commandes. Donc merci pour vos commentaires et les exemples. Ca m'aide plus et si vous avez d'autres exemples je suis prenneur.
En tout cas je vous remercie de répondre à mes questions, c'est vraiment cool

**Comment by Oliv4945** [comment]
Je ferme car j'ai l'impression que le sujet est clos, réouvrir si besoin

Oliv'
