### ISSUE TITLE
ca-certificates

### ISSUE THREAD

**Issue by pnogier** [alexylem/jarvis#893]
### Description

Problème après la prononciation du hotword 3fois d'affilé a l'installation sur mac, voir log....

### Logs
```shell
Training model...

curl: (77) error setting certificate verify locations:
  CAfile: /usr/share/curl/ca-bundle.crt
  CApath: none
cat: /tmp/model.pmdl: No such file or directory

ERROR: error occured while training the model
HELP: check error above
```

**Comment by JeremyWiart** [comment]
désoler je ne suis pas sur mac,

mais tu as une erreur 77, tu utilise quoi comme stt ? vérifie tes paramètre de location, sa doit provenir de tes endpoints.

et no such file directory veux dire qu'il ne trouve pas le chemin pour acceder au /tmp/model.pmdl qui lui est le hotword que tu as enregistré, C'est pour sa qu'il ne se passe rien quand tu le prononce

**Comment by Oliv4945** [comment]
Curl ne trouve pas les certificats racine pour valider celui de Snowboy. Je ne suis pas sur mac mais il y a visiblement une solution [ici](https://stackoverflow.com/questions/45829588/brew-install-fails-curl77-error-setting-certificate-verify)

**Comment by wikijm** [comment]
Pas de retour depuis 4 mois, j'imagine que le problème est résolu. Je clôture donc cette issue.
