### ISSUE TITLE
Problème reconnaissance vocale hotword snowboy

### ISSUE THREAD

**Issue by totof74** [alexylem/jarvis#896]
Bonjour,

Voici ma configuration : 
Jarvis installé sur une config "Raspbian Stretch with desktop and recommended software".
matériel : RPI2 + micro MC1000
Je souhaite éviter d'utiliser les outils cloud pour la reconnaissance vocale.

Mon problème : 
Mon mot clef est reconnu à peu près correctement, mais les commandes que j'ai ajoutées le sont nettement moins bien.
AIDE / VERSION / OUI : ne sont jamais reconnus ou reconnus comme "TEST".
QUEL JOUR : est reconnu comme "NON" ou pas reconnu, sauf très rarement (dans ce cas, il me répond "nous sommes le", je n'ai pas réussi à lui faire afficher la date pour l'instant).
MERCI : est reconnu une fois sur deux.
CA VA / TEST : sont reconnus assez facilement.

J'ai refais les enregistrements sonores une multitude de fois, j'ai essayer de jouer avec le volume et la sensibilité, sans résultat probant... cela fait une semaine que je galère, je désespère ! :'(
Parfois, j'ai l'impression que les * sont indispensables devant certains mots, parfois, elles compliquent les choses. Bref, je suis très loin d'avoir un résultat probant.

Merci par avance de votre aide ! :)

PS : update orthographe

**Comment by P1GOU1** [comment]
Moi je retire les * dans les phrases car ça déconne. Du coup pour : quel jour, j'enregistre *quel jour* et pas *quel* et *jour* qui donne *quel*jour* dans le fichier command. Bref j’espère t'avoir éclairé un peu...

**Comment by Oliv4945** [comment]
Merci de respecter les consignes lors de l'ouverture d'une issue, comme `jarvis -nv`.
Je vous laisse rouvrir avec le log
