### ISSUE TITLE
ImportError: jarvis/tts_engines/snowboy/_snowboydetect.so: cannot open shared object fil: No such file of directory

### ISSUE THREAD

**Issue by CamilleLC** [alexylem/jarvis#90]
Bonjour, 
encore merci pour avoir developper ce programme et d'avoir repondu a mes questions.  
Je presente rapidement mon sujet:dans le cadre d'un projet dans mon universite, je dois utiliser une application comme jarvis pour l'installer sur un robot qui devra parler en anglais. Ce robot n'aura pas acces a internet, c'est pour cela que je dois choisir pocketsphinx. ce robot sera constitue d'un petit ordinateur tournant sur ubuntu. 

Je n'arrive pas a modifier le dictionnaire pocketsphinx. Lorsque je  lance Jarvis en mode troubleshooting avec snowboy configuré pour la reconnaissance du mot clé et que j'essaye de le déclencher en prononçant "snowboy" voici ce que ca donne:

![screenshot from 2016-08-03 14 59 56](https://cloud.githubusercontent.com/assets/20811029/17358647/3c1890e2-598d-11e6-9945-a31843c16cb3.png)
![screenshot from 2016-08-03 15 00 55](https://cloud.githubusercontent.com/assets/20811029/17358651/41c03bc6-598d-11e6-9f4e-992ab5638203.png)

merci dans tout les cas pour vos reponses precedentes.

Cordialement

**Comment by alexylem** [comment]
Bonjour,

Il semble qu'il te manque un fichier:
![image](https://cloud.githubusercontent.com/assets/11017174/17360557/7dad6ef4-596c-11e6-9117-376c315d7c4b.png)
Vérifie si tu l'as:
```
ls -l stt_engines/snowboy/_snowboydetect.so
```
Normalement Jarvis détecte si tu n'as pas `snowboy` installé et le fait pour toi (incluant le téléchargement du fichier `_snowboydetect.so`):
```
[ -f "`dirname "${BASH_SOURCE[0]}"`/_snowboydetect.so" ] || {
    dialog_yesno "Snowboy doesn't seem to be installed.\nDo you want to install it?" true >/dev/null && {
```
As-tu vu une installation de `snowboy` s'effectuer?
Si tu lance Jarvis ne te dit-il pas qu'il n'est pas installé?
Peut-être l'installation a planté, tu peux la relancer en désinstallant manuellement `snowboy`:
```
./stt_engines/snowboy/uninstall.sh
```
Puis relance Jarvis
```
./jarvis.sh
```

**Important**
Je vois que tu es sous Ubuntu, snowboy ne fournit pas de librairie compilée sur ubuntu, donc pas sûr que ca marche. Tu peux tenter mais tu risques rencontrer le même problème que ici:
#79.

**Comment by CamilleLC** [comment]
Merci pour tes réponses et tes remarques.
J'avais bien le dossier _snowboydetect.so mais effectivement quand je réinstalle je vois qu'il y a plusieurs problèmes
Donc je vais essayer de compiler ma propre librairie sur snowboy mais quand je lis la doc de snowboy il dit qu'il est compatible avec  Ubuntu 12.04 et 14.04 mais j'ai la version 15.04. Est ce que je peux quand même l'utiliser ? j'ai fait quelques recherches mais pas de réponses et je n'ai aucune idée si les nouvelles versions sont compatibles avec les anciennes. 
 Sinon je vais essayé de repasser sur pocketsphinx :)

**Comment by alexylem** [comment]
Juste par curiosité, tu n'as pas répondu à cette question, car ça pourrait grandement de simplifier la vie:
>D'ailleurs pourquoi ne pas utiliser de raspberry pi pour le robot? Ne serait-ce pas plus adapté? Le robot ne se trimballe quand même pas avec un PC sur le dos si?

**Comment by CamilleLC** [comment]
je n'ai pas vu cette question ! 
C'est un projet de l'université et je dois juste m'occuper du speech to text and text to speech, d'autres personnes ont d'autre tâches à effectuer sur le robot. C'est l'université qui a choisi de prendre un ordi. C'est un ordi qui a la taille d'une main. je n'ai pas plus d'info dessus. Il souhaite faire un robot de taille humaine qui communiquer et informer la personne avec qui il communique. Je suis dans la première phase, je teste un peu tout pour voir ce qui fonctionne. 
Du coup vous n'avez pas répondu non plus à ma question: est ce que je peux utiliser snowboy compatible avec ubuntu 14.04 et 12.04 alors que je suis en 15.04 ?

**Comment by alexylem** [comment]
Ok, ca serait bien de savoir si cet ordi est un raspberry pi :wink: 
Pour ta question je ne sait pas, le mieux serait de contacter snowboy et leur poser la question.

**Comment by physicien** [comment]
Très intéressant comme projet. Je suis curieux, est-ce que c'est dans le cadre d'un cours ou est-ce pour une thèse la conception de ce robot?
Si je peux y aller d'un conseil (ça fait un moment que je travaille moi aussi sur la conception d'un robot avec Jarvis comme framework), mise sur la modularité et l'indépendance des différentes parties du système nerveux. Tout ce que le cerveau principal n'a pas à calculer est du CPU sauvé les processus plus demandant.

Parmi les processus particulièrement demandant, le STT engine est certainement l'un des pires. Selon mes expérimentations des derniers mois, la RP3 n'est malheureusement pas assez puissante pour rouler PocketSphinx avec un niveau de reconnaissance acceptable (dico + language model + acoustic model assez gros). Cependant, elle n'est pas loin de la puissance minimale. Les principaux problèmes sont la faible vitesse de lecture/écriture sur micro SD et la fréquence du processeur qui n'est que de 1.2 GHz. Pour remédier à ça, plusieurs solutions s'offrent à vous:

- Utiliser un STT sur serveur externe (à exclure vu que le robot n'a pas accès à Internet);
- Utiliser un serveur STT interne en ajoutant un "cerveau" dédié (un laptop dont on a retiré les composantes superflus ou un nano-ordinateur tels que les [ODROID](http://www.hardkernel.com/main/main.php) peuvent être des solutions pour plus de puissance embarquée);
- Utiliser un système assez léger utilisant uniquement des commandes simples sous forme de _hotwords_.

Cela dit, j'ai bien hâte de voir si tout fonctionne bien pour votre robot :smile:

**Comment by CamilleLC** [comment]
Merci beaucoup pour ces informations. 
Je réalise ce projet dans le cadre de mon stage technicien. Stage que je dois réaliser pour mes études ( école d'ingénieur) 
Pour l'instant j'avoue que je suis un peu perdu, c'est un domaine dans lequel je n'ai jamais travaillé. je travaille presque que sur Matlab. Donc en gros à la moindre erreur ou au moindre problème je met trop longtemps à le résoudre, le temps de connaitre Linux les commandes sur le terminal etc et je pars de cette université dans 5 semaines donc je ne suis pas sur de pouvoir vous montrer quoi que ce soit ^^

Merci encore pour les informations et bonne continuation :)

**Comment by CamilleLC** [comment]
Pour l'ordinateur qui va servir pour le robot est Intel nuc5i5ryk 
 
il y a quelques informations ici si ça vous intéresse http://www.intel.com/content/www/us/en/nuc/nuc-kit-nuc5i5ryk.html

Bonne journée à vous

**Comment by alexylem** [comment]
@CamilleLC  je pense que la meilleure approche pour toi sera de réussir à compiler snowboy sur ton ubuntu 15.04. Tu as pu avancer de ce côté?

**Comment by alexylem** [comment]
@CamilleLC des news la dessus? On peut fermer le ticket?

**Comment by alexylem** [comment]
Timeout
