### ISSUE TITLE
Jabra 510 et hifiberry

### ISSUE THREAD

**Issue by P1GOU1** [alexylem/jarvis#901]
Bonjour à tous,

J'ai décidé d'essayer Jarvis sur mon raspberry 3, auparavant j'avais déjà installer une carte son Kuman, équivalente à l'hifiberry pour optimiser la qualité de la sortie du son sur ma carte. Carte sur laquelle je n'arrive pas à faire entendre ma voix via l'usb du micro jabra que Alexandre conseille d'acheter sur le site, et ce malgré la mise à jour de son firmware. J'ai toutefois essayé sur un autre système sans carte son supplémentaire, la vitesse de la voix est accéléré mais cela repère tout de même ma voix. Qu'est ce qui pourrait bien bloquer avec ma carte son ?

P1GOU1

**Comment by Potjoe-97** [comment]
Salut Pigou, as-tu vérifié que ta carte son est bien reconnue par le rpi et via Alsamixer ? 

Edit : Pas d'entrée USB sur la carte son en question d'après ce que je vois. Quel est le résultat de aplay -l ?

**Comment by P1GOU1** [comment]
Elle l'est, car quand je branche un ecouteur sur le jack de ma carte son, le son sort correctement, en sachant que j'ai du aussi modifier pour ça le fichier /boot/config.txt ainsi : 
#dtparam=audio=on
dtparam=i2s=on
dtoverlay=hifiberry-dacplus

**Comment by P1GOU1** [comment]
aplay -l
**** Liste des Périphériques Matériels PLAYBACK ****
carte 0: sndrpihifiberry [snd_rpi_hifiberry_dacplus], périphérique 0: HiFiBerry DAC+ HiFi pcm512x-hifi-0 []
  Sous-périphériques: 1/1
  Sous-périphérique #0: subdevice #0

**Comment by P1GOU1** [comment]
Je te donne ce soir le resultat de aplay-l avec le micro allumé, là je suis pas chez moi ^^

**Comment by Potjoe-97** [comment]
À partir du moment où ta carte son hifiberry ne te sert que pour le signal sortant, il faudra que tu configures Jarvis en lui indiquant que pour les speakers -> carte hifiberry, pour le micro -> carte défaut

**Comment by P1GOU1** [comment]
Oui c'est ce que j''essaye de lui expliquer en configurant ma sortie speaker sur la carte jabra durant la configuration de Jarvis, mais rien n'y fait... Je n'entends pas mon retour.
A noter que désormais ma carte par défaut est la hifi berry, et que meme dans alsa si je choisis Jabra, le son ne sort pas du periphérique.

**Comment by P1GOU1** [comment]
Voilà le resultat :

aplay -l
**** Liste des Périphériques Matériels PLAYBACK ****
carte 0: sndrpihifiberry [snd_rpi_hifiberry_dacplus], périphérique 0: HiFiBerry DAC+ HiFi pcm512x-hifi-0 []
  Sous-périphériques: 1/1
  Sous-périphérique #0: subdevice #0
carte 1: USB [Jabra SPEAK 510 USB], périphérique 0: USB Audio [USB Audio]
  Sous-périphériques: 1/1
  Sous-périphérique #0: subdevice #0

Donc en specifiant periphérique 1 et sous périphérique 1 à jarvis pour le micro rien, j'ai donc essayé 0 et 1 et 1 ou 0, sait on jamais, mais rien non plus...

**Comment by P1GOU1** [comment]
Si quelqu'un utilise un micro/speakder type jabra avec une carte son sur sa raspberry pi qu'il n'hesite pas en tout cas ^^ ça me rend dingue

**Comment by Potjoe-97** [comment]
J'étais en déplacement, désolé pour le retard. D'après ce que je lis les cartes sont bien reconnues, il faut que tu précises via settings < audio carte 0 device 0 pour les speakers et carte 1 device 0 pour le micro. Essaye avec ça et dis nous le résultat avec Jarvis lancé en mode troubleshooting.

Édit : il ne faut pas se référer aux sous-peripheriques mais aux périphériques (qui suivent la dénomination de la carte). Le problème vient peut être de là

**Comment by P1GOU1** [comment]
Bon, problème reglé, j'ai installer pulse audio qui gere beaucoup mieux les deux périphériques que alsa, tenez pour les prochains : https://www.framboise314.fr/audio-en-bluetooth-avec-le-raspberry-pi-3/
Ensuite juste à bidouiller un peu dans les paramètres et ça fonctionne . Merci potjoe pour ton temps !

**Comment by P1GOU1** [comment]
Bon, problème reglé, j'ai installer pulse audio qui gere beaucoup mieux les deux périphériques que alsa, tenez pour les prochains : https://www.framboise314.fr/audio-en-bluetooth-avec-le-raspberry-pi-3/
Ensuite juste à bidouiller un peu dans les paramètres et ça fonctionne . Merci potjoe pour ton temps !
