### ISSUE TITLE
openweathermap pas de temperatures

### ISSUE THREAD

**Issue by P1GOU1** [alexylem/jarvis#902]
Bonjour à tous !

Je commence avec Jarvis, et j'ai installé le plugins openweathermap (undergroundweather n'est plus actif visiblement),
j'ai ensuite tenté une traduction du plugin en renommant le dossier qui contient le fichier commands et function en "fr", ainsi que le contenu de ces deux dossier, est ce la bonne procedure à suivre ou je loupe quelque chose ?

En effetr, une fois le plugins lancé avec jarvis et ainsi parametré, il n'arrive pas à me donner la temperature malgré une bonne configuration avec mon api key, et articule pas tres français. J'en invoque un pythonier ou un jarvisien experimenté !

Merci par avance.

**Comment by Oliv4945** [comment]
Salut,

Je t'invite à ouvrir une issue sur le repo du plugin en question ;)
Au passage publie ton code et `jarvis -nv` pour que l'on puisse comprendre
