### ISSUE TITLE
Votre solution meteo?

### ISSUE THREAD

**Issue by P1GOU1** [alexylem/jarvis#904]
Bonjour,

Je cherche desesperement un plugin en français qui fonctionne pour la meteo, undergroundweather ne rend plus ce service aux particuliers et je n'arrive pas à traduire correctement en français et faire marcher correctement le dernier plugin "openweather", des solutions en lien avec domiticz ou jeedom existent elles ?

### Description

Français and English are allowed.
Detailed description of your problem.
In case of feature request, please provide justification & example of usage.

### Logs
```shell
<PASTE HERE> full content of the terminal with Jarvis in troubleshooting mode
(keep triple quotes above and below to preserve formatting) 
```
Alternatively attach a terminal session recording using asciinema:
```shell
sudo apt-get install -y asciinema && asciinema rec # start session recording
./jarvish.sh -nv # start jarvis directly in troubleshooting mode
Ctrl+D # stop recording
y # yes to upload and get URL to paste here
```

**Comment by Potjoe-97** [comment]
Jarvis-meteo-suisse fonctionne très bien, même en France.

**Comment by P1GOU1** [comment]
Merci ! Ca me suffit amplement, en effet.

**Comment by Oliv4945** [comment]
L'issue semble résolue, je ferme. N'hésitez pas à rouvrir si besoin
