### ISSUE TITLE
Jarvis alarm reglages

### ISSUE THREAD

**Issue by P1GOU1** [alexylem/jarvis#908]
Bonjour à tous !

Je viens ici car sur les "issues" du plugins alarme restent sans réponse.
Du coup je voudrais savoir comment me débrouiller pour programmer ce plugin, alors que je n'ai que snowboy en reconnaissance vocale, les phrases avec des (*) m'enbrouillent.

Faut il que j'enregistre chaque chiffre à la voix de 1 à 60 pour programmer une heure précise ? 
Même chose avec le minuteur, j'ai du mal à piger le principe, il reconnait *minute* et *effacer liste* après enregistrement de ces hotwords, mais pas le nombre de minutes que je lui ordonne de programmer avant de sonner.

bonnes fêtes à tous au passage !

**Comment by Oliv4945** [comment]
Utiliser Snowboy dans ce cas parait difficile. Il ne faut pas enregistrer chaque chiffre, mais toutes les combinaisons possible. Dans ce cas Snowboy n'arrivera pas à suivre car trop de fichiers à analyser.

Je vous invite à tester la branche beta où Bing/Azure refonctionne
