### ISSUE TITLE
controler la musique vocalement

### ISSUE THREAD

**Issue by remjou1** [alexylem/jarvis#91]
voila depuis pas mal de temps je lis de la musique avec jarvis mais un problème se pose : j'aimerais pouvoir arreter ou mettre en pause la musique pendant qu'elle est lu car impossible d'executer une commande pendant la lecture d'une musique.... bien sur je ne demande pas de pouvoir faire toutes les commande de la liste mais juste pouvoir inclure des commandes pause, lecture et arret pendant la lecture d'un fichier audio

**Comment by AdrienHerman** [comment]
Salut!
Il faut que tu fasse comme ceci:
`*LECTURE*==player play
*PAUSE*==player pause
*STOP*==player stop`

**Comment by remjou1** [comment]
oui mais quand je lance le musique avec jarvis je ne peut executer ces commandes

**Comment by LengZai** [comment]
Salut,

Il faut utiliser les commandes rapides avec snowboy... C'est la meilleure methode pour les commandes de bases. Mais attention... fais des commandes "longues" (3, 4 mots) sinon tu peux avoir des faux positifs.

(Je cherche une alternative pour des tests appronfondi... ..
... J'etudie un moyen pour soustraire le son d'une TV du son venu du microphone.)

**Comment by francoismartin** [comment]
@remjou1 j'ai le même soucis de mon côté avec mon issue #80 où je lance ma musique avec spotify.

@LengZai si tu arrives à faire ça, je serai curieux et intéresser.

Je me demande comment se démerde Amazon echo pour avoir un si belle écoute et compréhension de loin et avec du bruit ambiant.

**Comment by remjou1** [comment]
@LengZai je ne peut (et ne veut) pas installer snowboy, @francoismartin j'avais déja vu cette issue mais moi c'est pas pour spotify... je vais attendre peu etre une réponse de @alexylem

**Comment by francoismartin** [comment]
@remjou1 Quand tu lance ta musique, jarvis ne plante pas ? En te disant `play FAIL formats: can't open output file `default': snd_pcm_open error: Device or resource busy
ERROR: play command failed` ?

Merci

**Comment by remjou1** [comment]
non jarvis ne plante pas @francoismartin

**Comment by alexylem** [comment]
@remjou1 tu peux utiliser les [hooks](https://github.com/alexylem/jarvis/wiki/hooks) pour mettre en pause la musique lorsque jarvis passe en mode écoute d'une commande (puis la remettre à la fin du mode conversation).
