### ISSUE TITLE
Petit problème 

### ISSUE THREAD

**Issue by william59163** [alexylem/jarvis#913]
Bonsoir,
Grand débutant dans ce domaine, j aimerais pour créer plusieurs commandes march, arrêt, ... avec jarvis et envoyer sur les pins du rasberry une impulsion permettant de commander des relais dans un premier temps et après j aimerais en 433 mhz commander un arduino avec un Shields relais, mais je ne sais pas trop par où commencer et comment faire, aurait il une âme charitable pour me guider ?
Merci

**Comment by Oliv4945** [comment]
Bonjour,

Pour commencer je t'invite à aller voir la [documentation](http://openjarvis.com/) ainsi que le répertoire de plugin, notamment le [433 Mhz](http://openjarvis.com/plugins/domotique-433mhz)
