### ISSUE TITLE
Commandes des plugins ne fonctionnent  pas

### ISSUE THREAD

**Issue by vmasseron** [alexylem/jarvis#924]
Bonjour,
Pour commencer merci Alex pour ce projet très abouti.
Je vais vous décrire mon problème: quand j'installe un plugin, que j'enregistre un mot (j'utilise snowboy) et que je l'utilise dans une commande d'un plugin, il m'indique ne pas le comprendre.
J'ai essayé d'utiliser un de ces mots dans jarvis-command et la la commande fonctionne.

J'ai l'impression que les commandes des plugins ne sont pas liés.

Est-ce normal ? J'ai mal lu la doc ?
Si mon explication n'est pas claire, n'hésitez pas à demander des détails.
Merci.

**Comment by ocseb86** [comment]
Bonjour. Ta reconnaissance vocal pour les commandes est snowboy si j'ai bien compris. Tu rentre tes commandes de pluggin où ? D'après ce que je lis, tu les a rentré dans le fichier de commandes du pluggin lui même  /home/pi/jarvis/pluggin_installed/*pluggin*commandes. Et la ca ne marchera pas, il faut que toutes tes commandes soient dans les commandes de Jarvis directement.

Si tu mets bien tes commandes dans les commandes Jarvis, je saurai pas t'aider...

**Comment by vmasseron** [comment]
Merci d'avoir pris le temps de répondre à ma question. J'avais mal compris le fonctionnement / l'installation des plugins.
Maintenant tout fonctionne, merci beaucoup !
