### ISSUE TITLE
Obligation de reconfigurer le micro a chaque reboot

### ISSUE THREAD

**Issue by francoismartin** [alexylem/jarvis#93]
Impossible de savoir pourquoi.

`ERROR: snowboy recognition failed`

Tout marché, je n'ai pourtant (normalement) rient touché au config de mon micro et enceinte (j'ai fait les mises à jours).

J'ai beau reconfigurer comme il fallait ça ne marche pas. J'ai se problème quand je start jarvis.

En mode debug ça donne :

```
Checking for updates...[Up-to-date]

------------ Config ------------
system               Linux 4.4.13-v7+ armv7l 
os                   "Raspbian GNU/Linux 8 (jessie)" 
language             fr_FR 
play_hw              hw:1,0 
rec_hw               hw:0,0 
speaker              TerraTec Electronic GmbH Aureon Dual USB 
microphone           C-Media Electronics, Inc. CM108 Audio Controller 
trigger_stt          snowboy 
command_stt          bing 
tts_engine           google 
conversation_mode    true 
--------------------------------

DEBUG: program_startup hook
jarvis: Bonjour
jarvis: Waiting to hear 'jarvis'
Benjamin: (listening...)
DEBUG: models=jarvis,snowboy
ALSA lib pcm_dmix.c:1022:(snd_pcm_dmix_open) unable to open slave
ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.rear
ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.center_lfe
ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.side
ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.hdmi
ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.hdmi
ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.modem
ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.modem
ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.phoneline
ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.phoneline
ALSA lib pulse.c:243:(pulse_connect) PulseAudio: Unable to connect: Connection refused

ALSA lib pulse.c:243:(pulse_connect) PulseAudio: Unable to connect: Connection refused

ALSA lib pcm_dmix.c:1022:(snd_pcm_dmix_open) unable to open slave
Cannot connect to server socket err = No such file or directory
Cannot connect to server request channel
jack server is not running or cannot be started
Expression 'paInvalidSampleRate' failed in 'src/hostapi/alsa/pa_linux_alsa.c', line: 2048
Expression 'PaAlsaStreamComponent_InitialConfigure( &self->capture, inParams, self->primeBuffers, hwParamsCapture, &realSr )' failed in 'src/hostapi/alsa/pa_linux_alsa.c', line: 2719
Expression 'PaAlsaStream_Configure( stream, inputParameters, outputParameters, sampleRate, framesPerBuffer, &inputLatency, &outputLatency, &hostBufferSizeMode )' failed in 'src/hostapi/alsa/pa_linux_alsa.c', line: 2843
Traceback (most recent call last):
  File "stt_engines/snowboy/main.py", line 39, in <module>
    detector = snowboydecoder.HotwordDetector(models, sensitivity=sensitivities)
  File "/home/pi/jarvis/stt_engines/snowboy/snowboydecoder.py", line 115, in __init__
    stream_callback=audio_callback)
  File "/usr/lib/python2.7/dist-packages/pyaudio.py", line 747, in open
    stream = Stream(self, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/pyaudio.py", line 442, in __init__
    self._stream = pa.open(**arguments)
IOError: [Errno Invalid sample rate] -9997
DEBUG: modelid=-10
ERROR: snowboy recognition failed
```

**Comment by francoismartin** [comment]
J'ai réglé le problème :

En faite quand je reboot mon raspberry je suis obligé de remettre dans les config mic `hw:0,0` je ne sais pas pourquoi pourtant il est bien enregistré mais je suis obligé de le refaire après le lancement quand il doit avoir un problème a l'initialisation (à cause du crontab @reboot mopidy en sudo ?)

**Comment by physicien** [comment]
J'ai le même problème depuis un moment, mais je n'ai jamais vraiment compris pourquoi ça fait ça.

**Comment by alexylem** [comment]
Ce qu'il y a dans la config `mic` est uniquement utilisé pour générer le fichier `~/.asoundrc`. Puis Jarvis reload la configuration ALSA avec:
```
sudo /etc/init.d/alsa-utils restart
```
Jète donc un coup d'oeil au fichier (quand ca marche):
```
cat ~/.asoundrc
```
Puis reboot, et check le contenu du fichier. Si c'est le même, relance juste:
```
sudo /etc/init.d/alsa-utils restart
```
Et voit si ca marche.

**Comment by francoismartin** [comment]
Merci @alexylem pour ta réponse.

Quand tout marche ça donne

	cat ~/.asoundrc
	pcm.!default {
	  type asym
	   playback.pcm {
	     type plug
	     slave.pcm "hw:1,0"
	   }
	   capture.pcm {
	     type plug
	     slave.pcm "hw:0,0"
	   }
	}

Et au reboot en faite il doit avoir la configuration de base qui doit être sauvegardé : 

	cat ~/.asoundrc
	pcm.!default {
	  type asym
	   playback.pcm {
	     type plug
	     slave.pcm "hw:1,0"
	   }
	   capture.pcm {
	     type plug
	     slave.pcm "hw:0,0"
	   }
	}


	pcm.!default {
		type hw
		card 2
	}

	ctl.!default {
		type hw
		card 2
	}

Donc la config jarvis doit écraser le contenu de par défaut car même si je fais la commande `sudo /etc/init.d/alsa-utils restart` sans repasser pa la config jarvis, la config default reste present.

**Comment by alexylem** [comment]
Donc si je comprends bien, c'est la config Jarvis (la première) qui fonctionne, et l'autre (la 2ème qui en a un peu plus) revient à chaque reboot et fait planter Jarvis c'est bien ca?

**Comment by francoismartin** [comment]
@alexylem c'est bien ça

**Comment by alexylem** [comment]
Tu dois avoir un script qui te reconfigure ton `~/.asoundrc` au démarrage. Regarde dans ton `~/.bashrc`.
As-tu aussi un `/etc/asound.conf`?

**Comment by francoismartin** [comment]
je n'ai pas de `/etc/asound.conf`

je n'ai rien dans `~/.bashrc` qui parle de sound ou asound. Je vais checker du côté mopidy/mpd.

Car à part jarvis et mpoidy/mpd je n'ai rien d'autre.

**Comment by alexylem** [comment]
Je n'y connais rien à `modipy` et `mpd`. Mais en cherchant un peu il se peut qu'il y ait des conflits entre ta configuration ALSA et celle de mdp...

**Comment by alexylem** [comment]
@francoismartin  des nouvelles à ce sujet?

**Comment by francoismartin** [comment]
@alexylem J'étais en vacance je n'ai pas pu trop avancer sur ce point.
Ce que je vais faire c'est refaire une installation classique sur une autre carte sd et voir si sans mopidy il ya le problème ou pas, déjà ça aidera mais recherches.

Mais en tout cas sur mopidy la doc, je n'ai rien trouvé a ce sujet ni la possibilité de changer la config dans l'API (j'ai peut être mal cherché aussi)

**Comment by physicien** [comment]
Juste comme ça, dans Raspbian le fichier de configuration de alsa n'est pas à l'adresse habituelle. Le bon chemin est `/usr/share/alsa/alsa.conf`. On peut voir dans les premières lignes qu'il fait un pre-load à chaque boot.

**Comment by alexylem** [comment]
Merci @physicien je ne savais pas. En effet j'ai regardé dans le miens et il load aussi `/etc/asound.conf` (mais qui n'existe effectivement pas sur `raspbian`):
```
"/etc/asound.conf"
"~/.asoundrc"
```
@francoismartin se pourrait-il que le tiens a été modifié? Voici le miens:
[alsa.conf.txt](https://github.com/alexylem/jarvis/files/432891/alsa.conf.txt)

**Comment by physicien** [comment]
@alexylem Je viens de comparer avec le miens et je n'ai constaté aucune différence. Cependant, j'ai moi aussi le problème de config micro au démarrage. Je viens de faire quelques tests, et c'est seulement pour l'enregistrement audio que ça plante, car snowboy réagit très bien à un reboot.
![1](https://cloud.githubusercontent.com/assets/19982063/17899711/3df8855a-692a-11e6-921d-e1ac4e54c45e.png)
![2](https://cloud.githubusercontent.com/assets/19982063/17899712/3e015982-692a-11e6-860b-7dd522555db3.png)

**Comment by alexylem** [comment]
@physicien et est-ce que toi comme @francoismartin a ton `~/.asoundrc` qui est modifié à chaque reboot?

**Comment by physicien** [comment]
C'est exactement ça, et nous avons exactement les mêmes modifications.

**Comment by francoismartin** [comment]
Sur une nouvelle installation, avec un autre dac usb et sans mopidy/mpd je n'ai plus le problème de reconfiguration au démarrage bon, la j'ai un autre problème qu'après le snowbord, il ne détecte plus ma voix.

Je vais installer Mopidy pour voir si ça refait le problème ou pas du tout.

**Comment by francoismartin** [comment]
@alexylem 
Nos deux `alsa.conf` sont identiques : https://www.diffchecker.com/GOYmXbMv
Je n'arrives vraiment pas a comprendre d'où ça vient étant donné que j'ai refait une installation sur un autre raspberry et il y a aucun soucis.

**Comment by francoismartin** [comment]
ça doit venir de raspbian et de sa configuration avec la carte son de base de intégré sur le raspberry car quand je fais :

>pi@fili-1:~/jarvis $ cat /proc/asound/modules
> 0 snd_usb_audio
> 1 snd_usb_audio
> 2 snd_bcm2835

et dans mon cat ~/.asound.conf le pcm qui embête mentionne la card 2

>pcm.!default {
>	type hw
>	card 2
>}
>
>ctl.!default {
>	type hw
>	card 2
>}

**Comment by alexylem** [comment]
Une solution simple mais dégeu serait de regénerer `~/.asoundrc` à chaque lancement de `jarvis` suivi d'un petit `sudo /etc/init.d/alsa-utils restart`.
J'aurais vraiment aimé comprendre qu'est-ce qui modifie votre `~/.asoundrc` et le neutraliser.

**Comment by physicien** [comment]
Je ne sais pas si c'est quelqu'un d'ici qui pose des questions sur ce problème, mais des solutions font surface sur les internets depuis quelques jours. Voici celle du [RaspberryPiSE](http://raspberrypi.stackexchange.com/questions/54199/my-asoundrc-is-modified-every-reboot).

**Comment by francoismartin** [comment]
@physicien Oui j'ai demandé un ami de m'aider mais il n'a pas trouvé non plus la solution donc il a posé la question :D

**Comment by physicien** [comment]
@francoismartin Je te relance pour savoir s'il est sorti quelque chose des recherches de ton ami.

**Comment by francoismartin** [comment]
@physicien 

Non que dalle, aucune réponse de nul part.
Perso j'ai refait une autre carte avec un autre matos mic et enceinte et je n'ai plus le soucis ...

**Comment by francoismartin** [comment]
Depuis que je suis passé sur le soundTouch maintenant, j'ai un autre problème au démarrage et qu'il ne garde pas ma sensibilité à 54% mais retourne a 14%.
Et je recherche également a set mon volume pour qu'il est une valeur défini au démarrage.

Une idée de comment je peux faire ? Je dois tout paramétrer dans le `.asoundrc` ?

Merci les amis.

**Comment by francoismartin** [comment]
Bon en faite sur ma nouvelle j'ai encore le problème ...

et @alexylem en faite ta commande :

    /etc/init.d/alsa-utils restart

ne résout pas le problème d'enlever les `pcm.**` inutiles.
Je penses que ça vient de jessie le problème moi, il doit y avoir une configuration de base qui est implementer car quand j'avais la carte vierge j'avais cette config de base 

```
pcm.!default {
	type hw
	card 2
}

ctl.!default {
	type hw
	card 2
}
````

Donc la question est depuis où est-ce que pi fait l'ajout de sa config alsa, qu'on désactive son execution.

**Comment by alexylem** [comment]
Justement c'est le problème on ne sait pas. 
```
/etc/init.d/alsa-utils restart
```
Va simplement reloader `alsa` et prendre en compte de quelconques modifications apportées au `~/.asoundrc`. C'est mon idée de re-générer ce fichier à chaque lancement de Jarvis suivi de cette commande. Mais c'est vraiment pourri... Et ca ne résous le problème de perte du réglage de la sensibilité...

**Comment by francoismartin** [comment]
@alexylem Oui je penses que c'est une mauvaise idée, surtout si on a créer des asoudrc custom ça va tout foutre en l'air.

En ce moment, ce que j'ai fait pour résoudre le problème c'était d'utiliser le hook `Program start` et j'ai ajouté `cp /home/pi/jarvis/config/asound.conf ~/.asoundrc` et ça fait très bien l'affaire (temporairement jusqu'à trouver la cause)

**Comment by alexylem** [comment]
@francoismartin 
Il vaut mieux faire ceci pour lancer jarvis en tâche de fond:
```bash
/home/pi/jarvis/jarvis.sh -b
```
Le fichier de log est géré automatiquement, et de l'aide supplémentaire est affichée:
```bash
start_in_background () {
    ./jarvis.sh -n > jarvis.log 2>&1 &
    disown
    cat <<EOM
Jarvis has been launched in background

To view Jarvis output:
cat jarvis.log
To check if jarvis is running:
pgrep -lf jarvis.sh
To stop Jarvis:
./jarvis.sh and select "Stop Jarvis"

You can now close this terminal
EOM
}
```

**Comment by francoismartin** [comment]
@alexylem Merci je change ça.

**Comment by wikijm** [comment]
Pas de nouvelle de @francoismartin depuis le 14 septembre 2016, j'en conclus que le lancement de Jarvis en tâche de fond a fonctionné avec la commande `/home/pi/jarvis/jarvis.sh -b`.

Ne pas hésiter à ré-ouvrir le ticket s'il y a de nouveaux rebondissements ;-)

**Comment by francoismartin** [comment]
Oui ça fonctionne, désolé de ne pas être revenu pour le dire.

**Comment by wikijm** [comment]
Aucun problème @francoismartin, content que cela ai pu t'aider :-)
