### ISSUE TITLE
???

### ISSUE THREAD

**Issue by kikibga** [alexylem/jarvis#935]
Le projet est toujours en activité ?

**Comment by wikijm** [comment]
Bonjour à toi aussi,

Oui le projet est toujours en activité (en atteste les tickets crées et traités sur 2019, ainsi que l'activité sur la branche [beta](https://github.com/alexylem/jarvis/tree/beta)), mais comme tout projet opensource il demande l'implication de chacun de ses acteurs.

Cordialement,
WikiJM
