### ISSUE TITLE
./jarvis.sh: line 210: update_alsa: command not found

### ISSUE THREAD

**Issue by adsofts** [alexylem/jarvis#94]
### Description

Bonjour,
Je viens d'installer Jarvis, je tente de l'installer, tout fonctionne bien jusqu'au test du micro. je sélectionne la bonne carte et le bon device (en meme temps je n'en ai qu'un), et j'obtiens le message ci-dessous.

### Résultat
```
**** List of CAPTURE Hardware Devices ****
card 1: Device [C-Media USB Audio Device], device 0: USB Audio [USB Audio]
  Subdevices: 1/1
  Subdevice #0: subdevice #0
Indicate the card # to use [0-9]: 1
Indicate the device # to use [0-9]: 0
./jarvis.sh: line 210: update_alsa: command not found
rec FAIL formats: can't open input  `default': snd_pcm_open error: No such file or directory
play FAIL formats: can't open input file `jarvis-record.wav': No such file or directory
true
```

**Comment by adsofts** [comment]
Pour complément d'information, j'ai finalement réussis à faire fonctionner ton programme en le bidouillant un peu. Cependant ce n'est qu'un cache-misère et non une réelle résolution du problème, je ne parviens pas à trouver ou ca cloche, donc pas de pull request à te proposer, mais si ca peut t'aider ...
En mettant "export AUDIODEV=hw:1,0" avant chaque "rec" et "export AUDIODEV=hw:0,0" avant chaque play, ca fonctionne correctement.

**Comment by alexylem** [comment]
Bonjour et désolé pour le délai de ma réponse, j'étais en vacances, loin 😄 
Ton problème est que la fonction `update_alsa` qui créé le fichier `~/.asoundrc` n'a pas été trouvée:
```
./jarvis.sh: line 210: update_alsa: command not found
```
Ce qui m'étonne un peu car cette fonction est présente dans le fichier `utils/utils.sh` inclu avant le processus d'installation.
Peux-tu vérifier la présence de ce fichier dans le dossier jarvis:
```
$> ls -l utils/utils.sh
```
S'il n'y est pas, je te conseille de réinstaller Jarvis.

Pour un peu plus d'explication, ta modif fonctionne, mais n'est plus utile avec le fichier `~/.asoundrc` car il redéfinit les périphériques audio par défaut. Le problème est que ta modif va être perdue à la prochaine mise à jour de Jarvis.

**Comment by alexylem** [comment]
@adsofts As-tu pu résoudre ton problème?

**Comment by alexylem** [comment]
timeout
