### ISSUE TITLE
Null d'après Wolfram

### ISSUE THREAD

**Issue by Nitro62** [alexylem/jarvis#947]
Bonjour/Bonsoir

Je viens d'installer Jarvis il y a peu sur mon raspberry, et dans l'espoir de pouvoir lui poser des questions afin d'avoir un minimum d'échange, j'ai installer le plug-in "Web Answers".
J'ai bien récupéré les clés d'activation de Wolfram et Yandex, cependant à n'importe quelle question (y compris celle de l'exemple a savoir la hauteur de la tour Eiffel) Jarvis me répond "null d'après Wolfram", même en changeant l'ordre des moteurs de recherche et en mettant Google en premier, j'ai toujours la même réponse.

L'un d'entre vous a t'il une idée ou a t'il déjà été confronté a ce problème ? 

Mercii 😁

P.S au cas où ça ne se verrait pas je suis novice dans le domaine 🤓

**Comment by wikijm** [comment]
Bonjour @Nitro62 

Je tinvite à essayer OpenJarvis en premier sans aucun plug-in, pour valider sa bonne configuration.
Ensuite, tu pourras envisager d'intégrer des éléments additionnels.

Si le problème n'apparaît qu'à l'utilisation de "Web Answers", il faudra alors créer une issue sur le repository du plugin en question, à savoir [ici](https://github.com/lakadev/jarvis-web-answers/issues)

J'espère avoir pu répondre en partie à ton poblème 😃 .

**Comment by Nitro62** [comment]
Hello 

Je te remercie pour ta réponse 🙂
Concernant l'utilisation de base de Jarvis je ne rencontre aucun problème, je vais donc suivre ton conseil et me reporter au repositoy de "Web Answers" 

Bon weekend a toi 😁
