### ISSUE TITLE
Le projet est il mort?

### ISSUE THREAD

**Issue by Riseryn** [alexylem/jarvis#954]
Bonjour
Il semble ne pas y avoir de réponses aux différentes questions de ces derniers mois. Le projet est il mort?

**Comment by Oliv4945** [comment]
J'en ai peur oui. Je n'ai plus le temps de répondre, j'ai écris à @alexylem savoir si je peux archiver le projet il y a un moment, sans réponse. ça permettrait aux nouveaux de savoir à quoi s'attendre...

Je le ferais dans quelques semaines

**Comment by Riseryn** [comment]
Merci de la réponse.
 Ce message permettra au moins de prévenir  d'autres  personnes.
