### ISSUE TITLE
Mac OS X - iconv: conversion from utf8 unsupported

### ISSUE THREAD

**Issue by Montano5** [alexylem/jarvis#96]
Salut !

J'ai installé Jarvis depuis le git sur mon mac et après configuration je lance un petit test. Malheureusement, après chaque demande, il me renvoie une erreur 'I did not understand:' suivi d'un message d'erreur iconv sur un problème de conversion.
En mode normal, ça ressemble à ça:

HAL: Hello
HAL: Waiting to hear 'HAL'
Pierre-Jean: HAL
HAL: Yes?
Pierre-Jean: quelle heure est-il
iconv: conversion from utf8 unsupported
iconv: try 'iconv -l' to get the list of supported encodings
HAL: I did not understand:

Évidemment, après vérification avec iconv -l, le format d'encodage supporté est UTF-8 (avec un tiret).

Merci beaucoup pour le programme en tout cas, c'est passionnant ! :)

**Comment by Montano5** [comment]
Oui c'était bien cela !
Il faut modifier le fichier 'jarvis.sh' à la ligne 587:

<code>order=\`echo $1 | iconv -f utf8 -t ascii//TRANSLIT | sed 's/[^a-zA-Z 0-9]//g'\`</code>

en rajoutant un tiret à utf8 --> utf-8 et le problème est résolu ;)

**Comment by alexylem** [comment]
C'est bizarre sur mon mac ca marche:
```
$> iconv -l | grep UTF
UTF-8 UTF8
UTF-8-MAC UTF8-MAC
UTF-16
UTF-16BE
UTF-16LE
UTF-32
UTF-32BE
UTF-32LE
UNICODE-1-1-UTF-7 UTF-7 CSUNICODE11UTF7
```
Tu as aussi cette première ligne?
```
UTF-8 UTF8
```

**Comment by Montano5** [comment]
Ben non, je n'ai pas UTF8 sur mon mac :/

<code>iconv -l | grep UTF
UTF-8
UTF-8-MAC UTF8-MAC
UTF-16
UTF-16BE
UTF-16LE
UTF-32
UTF-32BE
UTF-32LE
UNICODE-1-1-UTF-7 UTF-7 CSUNICODE11UTF7</code>

Je ne sais pas s'il y a une dépendance. Mon mac est avec une installation par défaut, El Capitan 10.11.6...
L'écriture UTF-8 étant plus standard, autant l'utiliser ! ;)
