### ISSUE TITLE
OSX Say choisir quelle voix utiliser plutôt que la première dans la liste

### ISSUE THREAD

**Issue by Montano5** [alexylem/jarvis#97]
Autre petit bug: la gestion des voix dans OS X.

Avec le module tts_engines/osx_say dans le fichier main.sh, il y a cette variable qui permet de récupérer la liste des voix disponibles, d'utiliser la première de la langue choisie et d'afficher le texte récupérer par jarvis:

<code>osx_say_voice=`/usr/bin/say -v ? | grep $language | head -n 1 | awk '{print $1}'`</code>

Le problème est que le système peut avoir plusieurs voix d'installées et que la voix utilisée par le système (et donc préférée par l'utilisateur) n'est pas forcément la première de la liste.

Du coup, n'étant pas programmeur, j'ai effectué des modifications douteuses mais qui semblent fonctionner:

<code>osx_say_voice=`/usr/bin/say ? | awk '{print $1}'`</code>

et

<code>osx_say_TTS () { # TTS () {} Speaks text $1
/usr/bin/say $osx_say_voice "$1"</code>

**Comment by alexylem** [comment]
Ta modif "semble" fonctionner mais n'est pas la bonne solution 😄 
En effet
```
osx_say_voice=`/usr/bin/say ? | awk '{print $1}'`
```
Ne renvoie rien, donc `$osx_say_voice` est vide.
Puis
```
/usr/bin/say $osx_say_voice "$1"
```
Utilise donc la voix par défaut de ton mac (qui est la bonne). Mais cela ne fonctionnera pas pour ceux qui ont défini dans Jarvis un `language` différent de leur système.

Je vais essayer de trouver comment récupérer la voix sélectionnée dans les préférences d'OSX.

**Comment by Montano5** [comment]
:) ok merci pour le retour ! (Je savais que ma modif était foireuse!)

Je suis parti du postulat que l'utilisateur utilise jarvis dans le langage de son système.
Il était plus évident de changer la langue dans les paramètres système que dans les fichiers de jarvis qui ne sont pas accessible pour tout le monde.

La meilleure solution serait de pouvoir choisir la voix directement dans jarvis effectivement ! Ce serait même top ! Merci beaucoup ;)

**Comment by alexylem** [comment]
![image](https://cloud.githubusercontent.com/assets/11017174/17862180/7137ae32-6894-11e6-95e6-44fcf3564c95.png)
![image](https://cloud.githubusercontent.com/assets/11017174/17862189/788ded68-6894-11e6-881e-eb3b16a18fbc.png)
![image](https://cloud.githubusercontent.com/assets/11017174/17862193/7fa0bcca-6894-11e6-9199-8b5d5a9450b3.png)
![image](https://cloud.githubusercontent.com/assets/11017174/17862202/87669e8e-6894-11e6-99f1-42991dbc8233.png)

**Comment by KLF-29** [comment]
Bonjour,

Je cherche à changer de voix dans Jarvis (super outil ! :) merci encore), mais dans les options  Configuration > Speech synthesis, je n'ai que ça : 
```
Speech engine (svox_pico)                         │
OSX voice ()                
```
J'imagine qu'il faut installer d'autres voix manuellement ? Comment fait-on ? 
L'idée est d'avoir une voix d'homme (celle de Loïc, qui existe pourtant si on se réfère à un autre topic (#391)).

Merci d'avance pour votre aide !

**Comment by wikijm** [comment]
Bonjour @KLF-29,

Premier élément de réponse ici :
https://github.com/alexylem/jarvis/issues/446#issuecomment-283761044

**Comment by KLF-29** [comment]
Bonjour wikijm,

Bien vu, ce n'est plus possible d'utiliser voxygen. Bon, c'est pas grave, ça fonctionne sans. :)
Par contre, avec les possibilités actuelles, est-il réalisable de mettre une voix masculine (mon jeedom s'appelle "Georges", et la voix féminine ça fait... bizarre :D )

**Comment by Oliv4945** [comment]
@KLF-29 : Quel matériel utilises-tu ?
En attendant ta réponse, vu l'age du sujet je ferme l'issue
