### ISSUE TITLE
Maintien ?

### ISSUE THREAD

**Issue by ArnoStrasbourg** [alexylem/jarvis#978]
Bonjour,

Jarvis est-il toujours maintenu ?

Je viens de l'installer et j'ai eu des petits soucis. Comme le python 2.7 qui est toujours en cours d'utilisation. J'ai réglé ça, mais j'ai également un problème avec ma clé Bing qui est mauvaise. Tous les issues que je peux trouver sur le net à ce sujet datent de 2017...

**Comment by Perhan35** [comment]
Apparemment le projet est effectivement abandonné : https://github.com/alexylem/jarvis/issues/975#issuecomment-619359536

**Comment by ArnoStrasbourg** [comment]
Ok, merci
