### ISSUE TITLE
Bing speech API is free for 5000/month, not 50,000/month

### ISSUE THREAD

**Issue by xuchen** [alexylem/jarvis#98]
Regarding wiki:

https://github.com/alexylem/jarvis/wiki/stt

Pricing is here:

https://www.microsoft.com/cognitive-services/en-us/pricing

![image](https://cloud.githubusercontent.com/assets/543547/17643888/043117ca-612c-11e6-92e3-565fa2c1e497.png)

😺

**Comment by alexylem** [comment]
Well spotted, once again 👍  Fixed.
I'm proud the founder of Kitt.AI keeps an eye on Jarvis 😄 
`Snowboy` is more and more at the core of Jarvis, as it is the recommended engine for hotword detection and is also supported for quick commands:
https://github.com/alexylem/jarvis/wiki/snowboy#commandes-rapides
