### ISSUE TITLE
plugin freebox ( bug et refonte ) + demande onglet

### ISSUE THREAD

**Issue by braintrix-computer** [alexylem/jarvis#995]
Je cherche la commande pour le menu de la freebox, j'ai retourner tous internet pour la trouver, mais je trouve pas :D
Ce que je cherche ce n'est pas la commande remote, mais la commande des onglets de la freebox player...

Pourquoi ?

Car quand on fais un retour sur "home" qui vaut la touche sur la télécommande FREE cela nous renvoie pas sur l'onglet du milieu mais sur l'onglet précèdent, ce qui "introduit" des erreurs avec toutes les futurs commandes de Jarvis. ( En gros la freebox ne fait pas un retour central a chaque fois, je ne vais pas m'étalé sur le sujet, il suffit de tester, vous allez tous de suite comprendre )
Donc il y a l'URL de la remote , maintenant je cherche l'URL des onglets pour remplacer le home remote par un home onglet.

un peu de bug dans le fichier command du plugin freebox, de plus certaine partie son mal écrite ou erreur de syntaxe
Avec un coté pas pratique qui est Télé, si jamais on a brancher un dvd ou autre et que on parle de *TELE* cela peu tromper Jarvis.

Exemple de bug probable : NETFLIX , si vous vous ne trouver pas dans l'onglet Télévision et sur la ligne Freebox TV mais dans un autre onglet, la commande NETFLIX bug car Jarvis gère la remote ( télécommande )
j'ai refait tous le code : ( PS : je vais édite ce topic a chaque amélioration, pour éviter tous conflit j'ai remplacer TELE par FB ( freebox )

Ah oui au passage j'ai changer dans "functions.sh" le nom de : "freeboxplayer_url"
par : "freeboxplayer_urlremote" 
Si jamais je trouve l'URL des onglets qui commencera par : "freeboxplayer_urlonglet"

(( impossible d'afficher le code reel : "insert code" affiche pas correctement  ))

**Comment by wikijm** [comment]
Bonjour @braintrix-computer 

Pour être sûr d'être sur la position HOME, il suffit d'appeler 2 fois sur le bouton FREE.

Ci-dessous le texte que tu as précédemment mis dans ton message, sous forme de texte brut :

List programme dans l'ordre
-- Telecommande --
Allumer et Source
Numérations
Touche directionnel
Touche couleur directionnel
Touche principal FREE milieu
Touche volume / programme
Enregistrement
Lecture directionnel
-- Programme des Chaines televiser --
Affiche mozaique
Choix des Chaines
Zap des chaines dans l'ordre a partir de 1 (TF1) jusque 31 chaines et retour 0 (mozaique)
Incruster le PiP
Netflix
Prime video

Depart du code

Allumer et Source
ALLUMFBTV==say "La télé va s'allumer" && jv_curl "${freeboxplayer_urlremote}power" && sleep 12 && jv_curl "${freeboxplayer_urlremote}home" && jv_curl "${freeboxplayer_urlremote}ok"
ETEINFBTV==say "La télé va s'éteindre" && jv_curl "${freeboxplayer_urlremote}power"

Numérations
FBBOUTON*==say "bouton 0" && jv_curl "${freeboxplayer_urlremote}0"
FBBOUTON*==say "bouton 1" && jv_curl "${freeboxplayer_urlremote}1"
FBBOUTON*==say "bouton 2" && jv_curl "${freeboxplayer_urlremote}2"
FBBOUTON*==say "bouton 3" && jv_curl "${freeboxplayer_urlremote}3"
FBBOUTON*==say "bouton 4" && jv_curl "${freeboxplayer_urlremote}4"
FBBOUTON*==say "bouton 5" && jv_curl "${freeboxplayer_urlremote}5"
FBBOUTON*==say "bouton 6" && jv_curl "${freeboxplayer_urlremote}6"
FBBOUTON*==say "bouton 7" && jv_curl "${freeboxplayer_urlremote}7"
FBBOUTON*==say "bouton 8" && jv_curl "${freeboxplayer_urlremote}8"
FBBOUTON*==say "bouton 9" && jv_curl "${freeboxplayer_urlremote}9"

Touche directionnel
FBHAUT*==say "bouton haut" && jv_curl "${freeboxplayer_urlremote}up"
FBBAS*==say "bouton bas" && jv_curl "${freeboxplayer_urlremote}down"
FBGAUCHE*==say "bouton gauche" && jv_curl "${freeboxplayer_urlremote}left"
FBDROITE*==say "bouton droite" && jv_curl "${freeboxplayer_urlremote}right"
FBOK*==say "bouton OK" && jv_curl "${freeboxplayer_urlremote}ok"

Touche couleur directionnel
FBROUGE*==say "bouton retour" && jv_curl "${freeboxplayer_urlremote}red"
FBVERT*==say "bouton menu" && jv_curl "${freeboxplayer_urlremote}green"
FBJAUNE*==say "bouton info" && jv_curl "${freeboxplayer_urlremote}yellow"
FBBLEU*==say "bouton recherche" && jv_curl "${freeboxplayer_urlremote}blue"

Touche principal FREE milieu
FBFREE*==say "Bouton FREE" && jv_curl "${freeboxplayer_urlremote}home"

Touche volume / programme
FBCHANG*==jv_curl "${freeboxplayer_urlremote}prgm_inc"
FBREVIEN*==jv_curl "${freeboxplayer_urlremote}prgm_dec"
FBAUGMENTSON==say "augmente le son" && jv_curl "${freeboxplayer_urlremote}vol_inc"
FBBAISSSON==say "baisse le son" && jv_curl "${freeboxplayer_urlremote}vol_dec"
FBCOUPESON|FBREMETSON==jv_curl "${freeboxplayer_urlremote}mute"

Enregistrement
FBENREGISTRE*==say "Engistrement lancé" && jv_curl "${freeboxplayer_urlremote}rec" && && jv_curl "${freeboxplayer_urlremote}ok"

Lecture directionnel
FBPLAY*|PAUSE==say "bouton play" && jv_curl "${freeboxplayer_urlremote}play"
FBAVANCERAPIDE==say "bouton avance rapide" && jv_curl "${freeboxplayer_urlremote}next"
FBRECULERAPIDE==say "bouton recule rapide" && jv_curl "${freeboxplayer_urlremote}prev"
FBAVANC*==say "bouton avance" && jv_curl "${freeboxplayer_urlremote}fwd"
FBRECUL*==say "bouton recule" && jv_curl "${freeboxplayer_urlremote}bwd"

Affiche mozaique
AFFICHMOZAIQUE==say "Mozaïque" && jv_curl "${freeboxplayer_urlremote}0"

Choix des chaines
AFFICHTF1*|AFFICHTFUN|METLAUN==say "TF1" && jv_curl "${freeboxplayer_urlremote}1">/dev/null
AFFICHFRANCE 2*|METLA2==say "France 2" && jv_curl "${freeboxplayer_urlremote}2">/dev/null
AFFICHFRANCE 3*|METLA3==say "France 3" && jv_curl "${freeboxplayer_urlremote}3">/dev/null
AFFICHFRANCE 4*|METLA14==say "France 4" && jv_curl "${freeboxplayer_urlremote}1" && jv_curl "${freeboxplayer_urlremote}4"
AFFICHCANAL==say "Canal plus" && jv_curl "${freeboxplayer_urlremote}4"
AFFICHFRANCE 5*|METLA5==say "France 5" && jv_curl "${freeboxplayer_urlremote}5">/dev/null
AFFICHM6*|METLA6==say "M 6" && jv_curl "${freeboxplayer_urlremote}6">/dev/null
AFFICHARTE|METLASEPT==say "ARTER" && jv_curl "${freeboxplayer_urlremote}7">/dev/null
AFFICHC8*|METLA8==say "C 8" && jv_curl "${freeboxplayer_urlremote}8">/dev/null
AFFICHW9*|METLA9==say "W 9" && jv_curl "${freeboxplayer_urlremote}9">/dev/null
AFFICHTMC|METLA10==say "T M C" && jv_curl "${freeboxplayer_urlremote}1" && jv_curl "${freeboxplayer_urlremote}0">/dev/null
AFFICHNT1|AFFICHNTA|METLA11*==say "N T 1" && jv_curl "${freeboxplayer_urlremote}1" && jv_curl "${freeboxplayer_urlremote}1">/dev/null
AFFICHNRJ12*|AFFICHNRJDOUZ==say "N R J 12" && jv_curl "${freeboxplayer_urlremote}1" && jv_curl "${freeboxplayer_urlremote}2">/dev/null
AFFICHLCP*==say "LCP" && jv_curl "${freeboxplayer_urlremote}1" && jv_curl "${freeboxplayer_urlremote}3">/dev/null
AFFICHBFM==say "B F M" && jv_curl "${freeboxplayer_urlremote}1" && jv_curl "${freeboxplayer_urlremote}5">/dev/null
AFFICHITELE==say "I Télé" && jv_curl "${freeboxplayer_urlremote}1" && jv_curl "${freeboxplayer_urlremote}6">/dev/null
AFFICHCSTAR==say "C STAR" && jv_curl "${freeboxplayer_urlremote}1" && jv_curl "${freeboxplayer_urlremote}7">/dev/null
AFFICHGULLI*==say "GULLI" && jv_curl "${freeboxplayer_urlremote}1" && jv_curl "${freeboxplayer_urlremote}8">/dev/null
AFFICHFRANCO|AFFICHFRANCEO*==say "FRANCE O" && jv_curl "${freeboxplayer_urlremote}1" && jv_curl "${freeboxplayer_urlremote}9">/dev/null
AFFICHHD1*|AFFICHHD 1==say "H D 1" && jv_curl "${freeboxplayer_urlremote}2" && jv_curl "${freeboxplayer_urlremote}0">/dev/null
AFFICHEQUIPE*==say "L'équipe" && jv_curl "${freeboxplayer_urlremote}2" && jv_curl "${freeboxplayer_urlremote}1">/dev/null
AFFICHSIXTER|AFFICHSISTER*==say "6 TER" && jv_curl "${freeboxplayer_urlremote}2" && jv_curl "${freeboxplayer_urlremote}2">/dev/null
AFFICHNUMERO23==say "NUMERO 23" && jv_curl "${freeboxplayer_urlremote}2" && jv_curl "${freeboxplayer_urlremote}3">/dev/null
AFFICHRMCDECOUVERT==say "RMC DECOUVERTE" && jv_curl "${freeboxplayer_urlremote}2" && jv_curl "${freeboxplayer_urlremote}4">/dev/null
AFFICHCHERI25|AFFICHCHERIVINGTCINQ*==say "CHERIE 25" && jv_curl "${freeboxplayer_urlremote}2" && jv_curl "${freeboxplayer_urlremote}5">/dev/null
AFFICHLCI*==say "LCI" && jv_curl "${freeboxplayer_urlremote}2" && jv_curl "${freeboxplayer_urlremote}6">/dev/null
AFFICHFRANCE INFO==say "France info" && jv_curl "${freeboxplayer_urlremote}2" && jv_curl "${freeboxplayer_urlremote}7"
AFFICHPARIS PREMIER*==say "Paris première" && jv_curl "${freeboxplayer_urlremote}2" && jv_curl "${freeboxplayer_urlremote}8"
AFFICHRTL9*==say "RTL9" && jv_curl "${freeboxplayer_urlremote}2" && jv_curl "${freeboxplayer_urlremote}9">/dev/null
AFFICHGAME*==say "GAME ONE" && jv_curl "${freeboxplayer_urlremote}3" && jv_curl "${freeboxplayer_urlremote}7">/dev/null
AFFICHTEVA==say "TEVA" && jv_curl "${freeboxplayer_urlremote}3" && jv_curl "${freeboxplayer_urlremote}8"
AFFICHAB1==say "AB1" && jv_curl "${freeboxplayer_urlremote}3" && jv_curl "${freeboxplayer_urlremote}9"
AFFICHCOMEDIE*==say "COMEDIE+" && jv_curl "${freeboxplayer_urlremote}8" && jv_curl "${freeboxplayer_urlremote}0">/dev/null
AFFICHPLANE*==say "PLANETE+" && jv_curl "${freeboxplayer_urlremote}5" && jv_curl "${freeboxplayer_urlremote}9">/dev/null
AFFICHFIF*|AFFICHSISS*|AFFICHSYFY==say "Syfy" && jv_curl "${freeboxplayer_urlremote}8" && jv_curl "${freeboxplayer_urlremote}2">/dev/null
AFFICHMANGA==say "MANGAS" && jv_curl "${freeboxplayer_urlremote}9" && jv_curl "${freeboxplayer_urlremote}0">/dev/null
AFFICHNO LIFE==say "No life" && jv_curl "${freeboxplayer_urlremote}9" && jv_curl "${freeboxplayer_urlremote}3"
AFFICHTOONAMI==say "Tounami" && jv_curl "${freeboxplayer_urlremote}1" && jv_curl "${freeboxplayer_urlremote}5" && jv_curl "${freeboxplayer_urlremote}4"
AFFICHLUCKY JACK==say "Lucky jack" && jv_curl "${freeboxplayer_urlremote}2" && jv_curl "${freeboxplayer_urlremote}4" && jv_curl "${freeboxplayer_urlremote}4"

ZAP des chaines dans l'ordre ( sleep x temps attend avant de changer )
Fini sur mosaique
FBZAPORDRE==say "je vais zappé les chaines dans l'ordre" && jv_curl "${freeboxplayer_urlremote}1" && sleep 4 && jv_curl "${freeboxplayer_urlremote}prgm_inc" && sleep 3 && jv_curl "${freeboxplayer_urlremote}prgm_inc" && sleep 3 && jv_curl "${freeboxplayer_urlremote}prgm_inc" && sleep 3 && jv_curl "${freeboxplayer_urlremote}prgm_inc" && sleep 3 && jv_curl "${freeboxplayer_urlremote}prgm_inc" && sleep 3 && jv_curl "${freeboxplayer_urlremote}prgm_inc" && sleep 3 && jv_curl "${freeboxplayer_urlremote}prgm_inc" && sleep 3 && jv_curl "${freeboxplayer_urlremote}prgm_inc" && sleep 3 && jv_curl "${freeboxplayer_urlremote}prgm_inc" && sleep 3 && jv_curl "${freeboxplayer_urlremote}prgm_inc" && sleep 3 && jv_curl "${freeboxplayer_urlremote}prgm_inc" && sleep 3 && jv_curl "${freeboxplayer_urlremote}prgm_inc" && sleep 3 && jv_curl "${freeboxplayer_urlremote}prgm_inc" && sleep 3 && jv_curl "${freeboxplayer_urlremote}prgm_inc" && sleep 3 && jv_curl "${freeboxplayer_urlremote}prgm_inc" && sleep 3 && jv_curl "${freeboxplayer_urlremote}prgm_inc" && sleep 3 && jv_curl "${freeboxplayer_urlremote}prgm_inc" && sleep 3 && jv_curl "${freeboxplayer_urlremote}prgm_inc" && sleep 3 && jv_curl "${freeboxplayer_urlremote}prgm_inc" && sleep 3 && jv_curl "${freeboxplayer_urlremote}prgm_inc" && sleep 3 && jv_curl "${freeboxplayer_urlremote}prgm_inc" && sleep 3 && jv_curl "${freeboxplayer_urlremote}prgm_inc" && sleep 3 && jv_curl "${freeboxplayer_urlremote}prgm_inc" && sleep 3 && jv_curl "${freeboxplayer_urlremote}prgm_inc" && sleep 3 && jv_curl "${freeboxplayer_urlremote}prgm_inc" && sleep 3 && jv_curl "${freeboxplayer_urlremote}prgm_inc" && sleep 3 && jv_curl "${freeboxplayer_urlremote}prgm_inc" && sleep 3 && jv_curl "${freeboxplayer_urlremote}prgm_inc" && sleep 3 && jv_curl "${freeboxplayer_urlremote}prgm_inc" && sleep 3 && jv_curl "${freeboxplayer_urlremote}prgm_inc" && sleep 3 && jv_curl "${freeboxplayer_urlremote}0"

Incruster le PiP
FBPIPACTIV==say "incruste la chaine actuel" && jv_curl "${freeboxplayer_urlremote}green" && jv_curl "${freeboxplayer_urlremote}down" && jv_curl "${freeboxplayer_urlremote}down" && jv_curl "${freeboxplayer_urlremote}down" && jv_curl "${freeboxplayer_urlremote}right" && jv_curl "${freeboxplayer_urlremote}ok"

Desactiver le PiP
FBPIPDESACTIV==say "desactive la chaine incruster" && jv_curl "${freeboxplayer_urlremote}green" && jv_curl "${freeboxplayer_urlremote}ok"

Netflix
FBNETFLIX*==say "je met nextflix" && jv_curl "${freeboxplayer_urlremote}home" && jv_curl "${freeboxplayer_urlremote}right" && jv_curl "${freeboxplayer_urlremote}down" && jv_curl "${freeboxplayer_urlremote}down" && jv_curl "${freeboxplayer_urlremote}down" && jv_curl "${freeboxplayer_urlremote}home" && jv_curl "${freeboxplayer_urlremote}ok" && jv_curl "${freeboxplayer_urlremote}ok"

Prime video
FBPRIME*==say "je met prime video" && jv_curl "${freeboxplayer_urlremote}home" && jv_curl "${freeboxplayer_urlremote}right" && jv_curl "${freeboxplayer_urlremote}down" && jv_curl "${freeboxplayer_urlremote}down" && jv_curl "${freeboxplayer_urlremote}down" && jv_curl "${freeboxplayer_urlremote}down" && jv_curl "${freeboxplayer_urlremote}home" && jv_curl "${freeboxplayer_urlremote}ok" && jv_curl "${freeboxplayer_urlremote}ok"

**Comment by wikijm** [comment]
Info importante :
Le code de ce plugin est disponible dans le Repo https://github.com/wikijm/jarvis-freeboxplayer
Il faudrait donc y créer ton Issue, et non pas dans le repo d'OpenJarvis directement.

De même, tu proposes pas mal de corrections et améliorations, mais je ne vois [pas de fork](https://github.com/wikijm/jarvis-freeboxplayer/network/members) ni de [pull request](https://github.com/wikijm/jarvis-freeboxplayer/pulls) de ta part, est-ce voulu ?
![image](https://user-images.githubusercontent.com/10724809/103264411-db73cf00-49aa-11eb-9716-337522037cb0.png)
